### ISSUE TITLE
Error trying to run 'expo start' on Lubuntu: Unable to read ~/.cache/versions.json

### ISSUE THREAD

**Issue by fdbatista** [expo/expo-cli#1001]
## Description

Trying to run the command <code>expo start</code> throws a warning and an error in the console. I'm using expo 3.0.10 on Lubuntu.

## Expected Behavior

I issued the <code>expo start</code> for trying to run my fresh new application on the browser. I have another PC running windows and it all works fine. I even see a menu with all the available expo commands.

![Sin título](https://user-images.githubusercontent.com/11459171/64809159-af8acb00-d566-11e9-840d-bdebb9b75cd1.png)

## Observed Behavior

The following error gets thrown:

```
Warning: Problem validating app.json: Unable to perform cache refresh for /home/fd/.cache/schema-34.0.0.json: XDLError: Invalid JSON returned from API: SyntaxError: Unexpected token < in JSON at position 0. Response body: <HTML></HTML>
.
Unable to read /home/fd/.cache/versions.json. SyntaxError: Unexpected token u in JSON at position 0

```
![55](https://user-images.githubusercontent.com/11459171/64809350-1a3c0680-d567-11e9-8677-0269b59f887e.png)

The /home/fd/.cache/schema-34.0.0.json files does not exist.

/home/fd/.cache/versions.json contains the word 'undefined'. I removed .cache folder, but this file is regenerated with the same content.

## Environment

app.json:

{
  "expo": {
    "name": "TransportApp",
    "slug": "transport-app",
    "privacy": "public",
    "sdkVersion": "34.0.0",
    "platforms": [
      "ios",
      "android",
      "web"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/images/icon.png",
    "splash": {
      "image": "./assets/images/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    }
  }
}

package.json:

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/samples": "~3.0.3",
    "@expo/vector-icons": "^10.0.3",
    "@material-ui/core": "^4.4.1",
    "@react-navigation/web": "^1.0.0-alpha.9",
    "expo": "^34.0.1",
    "expo-asset": "^6.0.0",
    "expo-constants": "6.0.0",
    "expo-font": "~6.0.0",
    "expo-web-browser": "6.0.0",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-web": "^0.11.4",
    "react-navigation": "^3.11.0"
  },
  "devDependencies": {
    "babel-preset-expo": "^6.0.0",
    "jest-expo": "^34.0.0"
  },
  "private": true
}

Expo CLI 3.0.10 environment info:
    System:
      OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/bin/node
      Yarn: 1.17.3 - /usr/bin/yarn
      npm: 6.11.3 - /usr/bin/npm
    npmPackages:
      expo: ^34.0.0 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.12.1 
    npmGlobalPackages:
      expo-cli: 3.0.10

## Reproducible Demo

<code>expo init projectname</code>
<code>expo start</code>

**Comment by sysnpc** [comment]
+1 on platform mac

**Comment by 234146326** [comment]
I have the same problem.
