### ISSUE TITLE
EXPO-CLI 3.0.10 issue with Expo SDK34.0

### ISSUE THREAD

**Issue by FantasticSWT** [expo/expo-cli#1003]
![image](https://user-images.githubusercontent.com/38369131/64905046-28278e00-d705-11e9-82de-21e908dc2c68.png)

Cannot even expo start and expo install. Please help. Have been uninstalling and reinstall expo-cli.

**Comment by fson** [comment]
Sorry to hear that you are having trouble. If the problem still exists, please post to https://forums.expo.io/ for support.
