### ISSUE TITLE
expo start --offline does not serve app for local development

### ISSUE THREAD

**Issue by yreifschneider** [expo/expo-cli#101]
## Description

I want to develop an app with expo-cli, without expo-cli using the internet, because I'm working behind a corperate proxy.

## Expected Behavior

I can develop the app without internet by starting expo with `expo start --offline`

## Observed Behavior

Expo-cli starts and appears to be working, but when I open the iOS simulator and try to load the app from `localhost:19000` the Expo App running in the simulator shows the following error:
```
There as a problem loading the requested app.
```
and
```
Could not load exp://localhost:19000
```

The same error message appears, when I start the project without the offline flag and the corporate proxy blocking outgoing traffic. But then, the following log appears in expo-cli output:

```
Logs for your project will appear below. Press Ctrl+C to exit.
[16:56:21] Fetching the user profile failed
[16:56:21] getaddrinfo ENOTFOUND exp.host exp.host:443
[16:56:21] Fetching the user profile failed
[16:56:21] getaddrinfo ENOTFOUND exp.host exp.host:443
[16:56:21] An Expo user account is required to proceed.
```
Note that I'm logged in with a valid user, but the internet connection is blocked by my proxy settings.

It appears, that expo-cli somehow requires internet connection to start serving the app for the simulator. When I start expo-cli with full internet connectivity, the app loads without problem and I can reconnect to the closed network and it still works without problem.

## Environment

`expo diagnostics` output:

```
$ expo diagnostics
[16:58:57] Generating diagnostics report...
[16:58:57] You can join our slack here: https://slack.expo.io/.

Environment:
  OS: macOS 10.14
  Node: 8.12.0
  Yarn: Not Found
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.1 AI-173.4907809

Packages: (wanted => installed)
  expo: ^30.0.0 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
-[16:58:59] Fetching the user profile failed
[16:58:59] getaddrinfo ENOTFOUND exp.host exp.host:443
\[16:59:01] getaddrinfo ENOTFOUND exp.host exp.host:443
[16:59:01] Set EXPO_DEBUG=true in your env to view the stack trace.
```

My development platform is a Mac with macOS Mojave and using the iOS 12 Simulator.

## Reproducible Demo

You can reproduce this error with any project, by running `expo start --offline`

**Comment by tommotaylor** [comment]
Hi there, did you find a solution for this? I find it very frustrating that there is no good development workflow for Expo when completely offline.

**Comment by skidr0w** [comment]
@tommotaylor this issue was fixed in a later version of expo-cli. It was not marked as resolved in this issue though. Do you still encounter this behaviour in the latest version of expo-cli?

**Comment by hamidfzm** [comment]
Facing same issue still not fix in latest expo cli

**Comment by brunoreis** [comment]
This was working fine for Sierra and xCode 9, after I moved to Mojave and xCode 10, I'm seeing the same now.

**Comment by brunoreis** [comment]
Well, if I choose Local instead of Lan, it works...

![Screen Shot 2019-03-21 at 13 10 24](https://user-images.githubusercontent.com/217240/54766883-da5d1d80-4bda-11e9-8edb-b696efbf61ad.png)

**Comment by kevinthecity** [comment]
`yarn start —offline` and selecting `local` as @brunoreis mentioned above did the trick for me! Without the `—offline` it was failing and asking me to authenticate expo

**Comment by brentvatne** [comment]
thanks for the information folks! i created this issue to change expo-cli behavior to default to localhost when the offline flag is present: https://github.com/expo/expo-cli/issues/1307
