### ISSUE TITLE
Next.js (or its server component) is not installed in your app.

### ISSUE THREAD

**Issue by JClackett** [expo/expo-cli#1015]
## Description

Tried using the new Expo with Next.js feature using a blank template or with typescript, but get a "Next.js (or its server component) is not installed in your app." message.

Next is 100% installed in my app.

## Expected Behavior

Start the server and render app

## Observed Behavior

$ yarn web
yarn run v1.17.3
$ expo start --web
Starting project at /Users/<me>/expo-next
Expo DevTools is running at http://localhost:19003
Press d to open DevTools now, or shift-d to always open it automatically.
Starting Metro Bundler on port 19002.
Tunnel ready.
 web  Starting Next.js on port 19006 in development mode.
Next.js (or its server component) is not installed in your app. See https://docs.expo.io/versions/latest/guides/using-nextjs/
error Command failed with exit code 1.

## Environment

  Expo CLI 3.1.0 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 2.7.1 - /usr/local/bin/fish
    Binaries:
      Node: 12.8.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.8.0 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8

## Reproducible Demo

https://codesandbox.io/s/expo-next-0ln3q

**Comment by uber5001** [comment]
I saw no mention of `next-server` in the docs, but running `npm i next-server` got me past this issue. Now I'm running into a new issue:
```
Cannot find `babel-loader` generated by `@expo/webpack-config/withUnimodules`. It is likely an Expo issue. Please create a new issue at https://github.com/expo/expo-cli.
```

**Comment by JClackett** [comment]
adding ```next-server``` solved it!

regarding your error, have you tried adding ```babel-preset-expo``` as a dev dep?
