### ISSUE TITLE
Cannot publish due to "GraphQL error: Cannot destructure property"

### ISSUE THREAD

**Issue by Egizas** [expo/expo-cli#1016]
## Description

After expo-cli upgrade to 3.1.2 I cannot publish any app anymore due to GraphQL error

## Expected Behavior

When I click on Publish in the expo-cli devTools (http://localhost:19002/), I expect that popup Publishing will appear for some time and then after successful publishing will be replaced by a URI where I can find the published app.

## Observed Behavior

When I click on Publish, assets are successfully optimized, popup with the word "Publishing..." appears and gets stuck. If I am using firefox I see in a firefox console only empty "Error: ", however if I use Chrome, the console provides this kind of error:

```
index.js:1 Uncaught (in promise) Error: GraphQL error: Cannot destructure property `quality` of 'undefined' or 'null'.
    at new t (index.js:1)
    at e.<anonymous> (index.js:1)
    at u (index.js:1)
    at Object.next (index.js:1)
    at index.js:1
    at new Promise (<anonymous>)
    at l (index.js:1)
    at Object.next (index.js:1)
    at Object.handler (index.js:1)
    at e.processReceivedData (index.js:1)
```
![image](https://user-images.githubusercontent.com/15939884/65386800-52e69780-dd40-11e9-8796-2541f60cbf82.png)

Sometimes in firefox I also see these errors, but not always:
```
Firefox can't establish a connection to the server at ws://localhost:19002/NsVLE3MXMFedWlZH5QTe-a1wOVuw4DC5D0KHUe_rYBU/graphql. index.js:1:144825
Firefox can't establish a connection to the server at ws://localhost:19002/NsVLE3MXMFedWlZH5QTe-a1wOVuw4DC5D0KHUe_rYBU/graphql.
```

## Environment

  Expo CLI 3.1.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.11.3 - C:\Users\egidi\AppData\Roaming\npm\npm.CMD
    IDEs:
      Android Studio: Version  3.0.0.0 AI-171.4443003

## Reproducible Demo

1. Upgrade expo-cli to 3.1.0
2. expo start
3. Go to localhost:19002
4. Click "Publish or republish project.." -> "Publish"
5. Observe the issue

**Comment by Egizas** [comment]
Upgrading to expo-cli 3.1.2 did not help, the issue is still persisting:
![image](https://user-images.githubusercontent.com/15939884/65542897-5f214f00-df10-11e9-96a0-6ec1d9885419.png)

**Comment by Uniphix** [comment]
I am having this same issue too, it stops right at Optimizing Assets... but yes expo publish works too

**Comment by Egizas** [comment]
For me even the "expo publish" command stopped working with the expo-cli 3.3.0. Waiting the commited fix above to see if it solves anything

**Comment by Egizas** [comment]
[expo-cli@3.4.0 ](https://github.com/expo/expo-cli/releases/tag/expo-cli%403.4.0) fixed the issue
