### ISSUE TITLE
Expo is not running my Project

### ISSUE THREAD

**Issue by patrinoua** [expo/expo-cli#1017]
#297 Expo is not running my Project

About 4 days ago Expo on my iPhone stopped working, telling me that 

```
There was a problem loading the requested app. 

The experience you requested uses Expo SDK v(null), 
but this copy of Expo Client requires at least v33.0.0. 
The author should update their experience to a newer Expo SDK version.
```

When I ran it on my iPad it was working up until today where now I also get the same message there. 

I tried manually updating the versions according to [this](https://blog.expo.io/expo-sdk-v33-0-0-is-now-available-52d1c99dfe4c) article but there were version missmatches so I reverted back. 
I then tried reinstalling expo and the version that was installed was 31.0.2.

## Environment

Expo CLI 3.1.0 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.2 => 31.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.5 => 3.0.5 
    npmGlobalPackages:
      expo-cli: 3.1.0

- Phone/emulator/simulator platform, model and version: iPhone SE , iPad A1475

**Comment by patrinoua** [comment]
This is the package.json : 

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "@ptomasroos/react-native-multi-slider": "^1.0.0",
    "@react-native-community/async-storage": "^1.6.1",
    "dayjs": "1.7.5",
    "expo": "^31.0.2",
    "expo-linear-gradient": "^7.0.0",
    "firebase": "^5.7.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz",
    "react-native-datepicker": "^1.7.2",
    "react-native-fbsdk": "^1.0.1",
    "react-native-image-picker": "^0.27.1",
    "react-native-maps": "0.25.0",
    "react-native-multiple-select": "^0.5.3",
    "react-native-radio-buttons-group": "^1.0.7",
    "react-native-simple-radio-button": "^2.7.3",
    "react-navigation": "^3.0.5",
    "rn-range-slider": "^1.2.8",
    "styled-components": "^4.3.2"
  },
  "devDependencies": {
    "@babel/plugin-proposal-optional-chaining": "^7.2.0",
    "babel-preset-expo": "^5.0.0"
  },
  "private": true
}

```

**Comment by Egizas** [comment]
expo SDK 31 is not supported anymore, you will have to upgrade to a newer version. Latest version is v35. 
Here is a tutorial how to upgrade: https://blog.expo.io/expo-sdk-35-is-now-available-beee0dfafbf4

Just pay attention that there are breaking changes as with every major release.

**Comment by patrinoua** [comment]
That solved it, thanks a lot!!!

**Comment by ccheever** [comment]
Looks like this project just required an upgrade to work with the App Store version of the client.
Closing this out.
