### ISSUE TITLE
ExpoKit builds constantly failing due to "getaddrinfo ENOTFOUND d1wp6m56sqw74a.cloudfront.net"

### ISSUE THREAD

**Issue by llamaluvr** [expo/expo-cli#1022]
### Environment

```Expo CLI 3.0.6 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.14.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.2
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.1 => 3.11.1
    npmGlobalPackages:
      expo-cli: 3.0.6
```

Target: iOS, Android (ExpoKit)

### Steps to Reproduce

1. Regularly build ExpoKit iOS and Android binaries
2. Wait for this error to inevitably occur

### Expected Behavior

All else equal, the build is successful

### Actual Behavior

Maybe one every five builds, it will fail on :app:bundleReleaseExpoAssets or when running the equivalent build script step in iOS.

The error will be something like:
```
Error: getaddrinfo ENOTFOUND d1wp6m56sqw74a.cloudfront.net d1wp6m56sqw74a.cloudfront.net:443
    at errnoException (dns.js:55:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:26)
Command /bin/sh failed with exit code 1
```
But I've also gotten
```
connect ETIMEDOUT
```
And a few times:
```
> Task :app:bundleReleaseExpoAssets
Opening `/dev/tty` failed (6): Device not configured
[09:26:26] ESOCKETTIMEDOUT
```

The last error was on an admittedly slow hotspot connection, but the rest happen regularly on solid wifi, even when I can maintain a 99.9% successful ping rate to Cloudfront.

### Reproducible Demo
It's difficult to say with 100%. certainty what causes this. Certainly, the demo needs to be an ExpoKit project with bundled assets. More bundled assets may make the issue more likely (my project has around ~300, most of which are thumbnail images, but some are larger). I think the issue became more frequent when I added about 30-50 screen-sized images to the mix.

In terms of network and computer configuration, I don't think there is any specific marker of the issue being more likely. My computer has no network proxies or VPN enabled (it's a personal laptop, so no corporate network stuff at all). I've experienced the issue on AT&T Uverse and Spectrum cable internet at home, on public and home wifi at locations in Ohio, Indiana, Michigan, and Pennsylvania. I've talked to another user experiencing the issue in the UK. The issue persisted after I reformatted my computer entirely. This issue has occurred for me on Expo SDK's 29-34.

This issue is not correlated with poor network performance. I've maintained 99.5%+ ping rates between here and d1wp6m56sqw74a.cloudfront.net and Google.com while the issue has occurred. At the time the issue occurs, I've seen no other network issues with my computer or any other device on the network.

The issue may happen three times in a row and not happen for ten more builds after that. I build about 35 apps in ExpoKit (we white label), and I probably experience this issue on 5-10% of my builds.

### Discussion

I'm currently working around this issue by using a custom node.js script that launches `expo build` via `shelljs`, reading `sdrerr` for one of the aforementioned errors, and restarting my build if one of those errors occurs. I don't doubt that there are no issues with the cloud provider (those things are pretty solid). It does, however, seem like the bundling assets step is awfully sensitive to anything less than the most ideal possible network conditions. Having some sort of retry for this process could save a lot of build time.

This is the same/related to the following issues:
https://github.com/expo/expo/issues/3906 (no issue template)
https://github.com/expo/expo/issues/1856 (closed by the original submitter without comment)

**Comment by ide** [comment]
@fson could you look into this? Specifically, @vpontis has a very helpful diagnosis here: https://github.com/expo/expo-cli/issues/1022#issuecomment-534045935. We probably just need to add something like https://www.npmjs.com/package/p-limit.

**Comment by vpontis** [comment]
@fson awesome thank you! <3
