### ISSUE TITLE
`expo url`'s message when the project isn't running prints code

### ISSUE THREAD

**Issue by ide** [expo/expo-cli#1032]
Run `expo url` in a directory that doesn't contain an Expo project:
```
$ expo url
Project is not running. Please start it with `function(str) {
  if (arguments.length === 0) return this._name;
  this._name = str;
  return this;
} start`.
```

Needs to be fixed cleanly but probably isn't too hard.

**Comment by davidli3100** [comment]
I'll tackle this issue. Starting a PR now

**Comment by ccheever** [comment]
@ide what version of expo-cli do you see this behavior in?
I can't repro using v3.4.0 which I believe is the latest one.

```
ccheever@Charlies-iMac:~/tmp/empty$expo url
Project is not running. Please start it with `expo start`.
```

**Comment by ide** [comment]
I could repro with 3.0.9 but not 3.4.0 so I think we can close this.
