### ISSUE TITLE
After Upgrading to Expo SDK version to 35. The linear gradient does not seem to be worked for my web project.

### ISSUE THREAD

**Issue by bikashsahucbnits** [expo/expo-cli#1035]
After Upgrading to Expo SDK version to 35. The linear gradient does not seem to be worked for my web project.
Project is running in the expo-cli version of 3.1.2

**Comment by chayancbnits** [comment]
I have tested linear-gradient after upgrading SDK version 35, it is working file in mobile devices but does not reflect on the web.

**Comment by EvanBacon** [comment]
Will investigate this problem (and why tests didn't catch this) now.

**Comment by EvanBacon** [comment]
fix is live in `expo-linear-gradient@7.0.1` really sorry for any inconvenience this may have caused.

**Comment by vjsingh** [comment]
@EvanBacon Just ran into this. Thank you for fixing it!
