### ISSUE TITLE
Detached android application, changed SLUG, no effects.

### ISSUE THREAD

**Issue by Changdao** [expo/expo-cli#1040]
## Description
Detached android application, changed SLUG, no effects.
What I do:
changed slug and save app.json first.
expo publish
cd android & ./gradlew build
./gradlew installProdKernelRelease
check android logcat, which sows that the app.json is still the old one.
What should I do ?

## Expected Behavior
1. After changing the slug, it's easy to make the change take effects.

## Environment
 Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.1.1 - /usr/local/bin/zsh
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 6.8.0 - ~/.nvm/versions/node/v10.13.0/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.9.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.21.2

**Comment by Changdao** [comment]
I manually changed the MainApplication.java
Is there any way to automatic refresh/regenerate the MainApplication.java?

**Comment by EvanBacon** [comment]
- detach / ExpoKit is now deprecated in favor of eject/bare workflow.
- you can now re-run `expo eject` to sync up changes made by Expo. I'd recommend nuking the application files before attempting to regenerate them though.
