### ISSUE TITLE
NextJS only runs in production, even when expo is in Development mode

### ISSUE THREAD

**Issue by arrygoo** [expo/expo-cli#1048]
## Description

I had NextJS working on a project, but after upgrading to SDK 35, it always runs in production even when Expo CLI is clearly in development mode.

I replicated this issue in a blank sdk35 repo

## Expected Behavior

NextJS to run in development mode rather than production mode, and live reloading to work. I had live reloading working for my NextJS app with SDK34 in development mode, but after the release of sdk35, it has stopped working.

## Observed Behavior

* Symptoms: 
1- If I change code, the browser won't reload, and if I manually reload changes aren't reflected until I stop and start expo again. This was fine with sdk34. I realize this might be the expected behavior in production mode, but I see it in dev mode.
2- The logs seem to indicate NextJS is running in production
Notice that even though it starts with ` web  Starting Next.js on port 19006 in development mode.`, it's followed by

```
Creating an optimized production build

Compiled successfully.

Automatically optimizing pages

```
Logs:
```
 work@MacBook-Pro-3  ~/dev/baobab/a   expo35 ●  expo start --web
Starting project at /Users/work/dev/baobab/a
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Starting Metro Bundler on port 19001.
Tunnel ready.
The environment property `polyfill` is deprecated.
 web  Starting Next.js on port 19006 in development mode.
> Using external babel configuration
> Location: "/Users/work/dev/baobab/a/babel.config.js"
Creating an optimized production build

Compiled successfully.

Automatically optimizing pages

Page            Size     Files  Packages
┌ ⚡ /           54 kB        0        10
├   /_app       203 kB       0         3
├   /_document
└   /_error     6.12 kB      0         3

σ  (Server)       page will be server rendered (i.e. getInitialProps)
⚡  (Static File)  page was prerendered as static HTML

Compiled successfully!
┌──────────────────────────────────────────────────────────────────────────┐
│                                                                          │
│   Web support in Expo is experimental and subject to breaking changes.   │
│   Do not use this in production yet.                                     │
│                                                                          │
└──────────────────────────────────────────────────────────────────────────┘
┌──────────────────────────────────────────────────────────────────────────┐
│                                                                          │
│   Web support in Expo is experimental and subject to breaking changes.   │
│   Do not use this in production yet.                                     │
│                                                                          │
└──────────────────────────────────────────────────────────────────────────┘

 React  You can now view a in the browser.

  Local:            http://localhost:19006/
  On Your Network:  http://192.168.0.29:19006/

Note that the development build is not optimized.

 › To create a production build, run expo build:web
 › Press Ctrl+C to exit.

  exp://192.168.0.29:19000

  To run the app with live reloading, choose one of:
  • Scan the QR code above with the Expo app (Android) or the Camera app (iOS).
  • Press a for Android emulator, or i for iOS simulator.
  • Press e to send a link to your phone with email.
  • Press s to sign in and enable more options.

 Expo  Press ? to show a list of all available commands.
Logs for your project will appear below. Press Ctrl+C to exit.

```

## Environment

web, nextjs

```
 work@MacBook-Pro-3  ~/dev/expoBug   master ●  expo diagnostics

  Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
    npmGlobalPackages:
      expo-cli: 3.1.2
```

## Reproducible Demo

https://github.com/arrygoo/expoNextjsIssue

**Comment by arrygoo** [comment]
@hesyifei @EvanBacon 
If you guys have any pointers as to how I can debug this further, I can take a deeper look. Where does NextJS look to find the development environment? I tried setting `NODE_ENV=development` but it doesn't seem to affect it.

**Comment by hesyifei** [comment]
I am able to reproduce the problem. It seems that it was working correctly with `expo-cli` version `3.1.0` and not working correctly with `3.1.2`. For now, you could simply downgrade `expo-cli` in your `package.json` to `3.1.0` while we look for the fix. Thanks!

**Comment by arrygoo** [comment]
@hesyifei Thank you so much for the quick response, and all your efforts to add NextJS to Expo!

Sadly I still have the problem after downgrading `expo-cli` to `3.1.0` in my package.json (and removed the global one), I verified by wiping `node_modules` and cache.

Do you not get `Creating an optimized production build .` with `3.1.0` in development?

**Comment by hesyifei** [comment]
@arrygoo Yes, I did not get that after I downgraded my `expo-cli` to `3.1.0`. Have you tried `yarn start --web-only --dev`?

**Comment by JClackett** [comment]
I tried using 3.1.0 as you suggested but am still getting

```
The environment property `polyfill` is deprecated.
 web  Starting Next.js on port 19006 in development mode.
> Using external babel configuration
> Location: "/Users/jclackett/Documents/Apps/Examples/expo-next/babel.config.js"
Creating an optimized production build  
```

Creates a production build

**Comment by 5ervant** [comment]
Hello @arrygoo.. Are the Next.js pages with `react-navigation` on your Expo Web application also work on an Android or iOS device? What are you doing to make Next.js pages work on a native device?

Thanks in advanced!
