### ISSUE TITLE
expo publish fails when using an absolute path

### ISSUE THREAD

**Issue by rahamin1** [expo/expo-cli#105]
I am posting here since I didn't find a solution for this in the forum (https://forums.expo.io/t/expo-publish-fails-when-using-an-absolute-path/14808) and in SO (https://stackoverflow.com/questions/52820669/expo-publish-fails-when-using-an-absolute-path).

## Description

expo `publish` fails when I am using an absolute path (bundling and running on an emulator don't have any problems)

## Expected Behavior

I have defined an absolute path in my .babelrc file as following:

    {
      "presets": ["babel-preset-expo"],
      "env": {
        "development": {
          "plugins": [
              ["transform-react-jsx-source"],
              ["module-resolver", {
                "alias": {
                  "mypet": "./src",
                }
              }]
            ]
        }
      }
    }

And expected `publish` to work...

## Observed Behavior

- publish fails with the following error: 'Failed to publish the project. See Metro logs for details.'
- the metro logs have the following error message: `Unable to resolve "mypet/store/store" from "App.js"` (which means that the absolute path definition didn't work during publish)
- Additional errors are printed, but they describe the same problem. I included them at the bottom of this post.

## Environment ( `expo diagnostics`)

**Environment:**
  OS: Windows 10
  Node: 8.11.1
  Yarn: 1.9.4
  npm: 6.1.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4720617

**Packages: (wanted => installed)**
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

**Diagnostics report:**
  https://exp-xde-diagnostics.s3.amazonaws.com/rahamin-75d815f9-b51e-4186-bcf1-dd6f3e4714fc.tar.gz

## Phone/emulator/simulator platform, model and version
Error is during publish, before running

## Reproducible Demo
I am using import with an absolute path.
For example, in App.js the following import statement exists, which causes the above error:
`import store from 'mypet/store/store';`

## Full error message
```
500 - "{\"originModulePath\":\"C:\\\\esites-native\\\\mypet\\\\App.js\",\"targetModuleName\":\"mypet/store/store\",\"message\":\"Unable to resolve module `mypet/store/store` from `C:\\\\esites-native\\\\mypet\\\\App.js`: Module `mypet/store/store` does not exist in the Haste module map\\n\\nThis might be related to https://github.com/facebook/react-native/issues/4968\\nTo resolve try the following:\\n  1. Clear watchman watches: `watchman watch-del-all`.\\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.\",\"errors\":[{\"description\":\"Unable to resolve module `mypet/store/store` from `C:\\\\esites-native\\\\mypet\\\\App.js`: Module `mypet/store/store` does not exist in the Haste module map\\n\\nThis might be related to https://github.com/facebook/react-native/issues/4968\\nTo resolve try the following:\\n  1. Clear watchman watches: `watchman watch-del-all`.\\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.\"}],\"name\":\"Error\",\"stack\":\"Error: Unable to resolve module `mypet/store/store` from `C:\\\\esites-native\\\\mypet\\\\App.js`: Module `mypet/store/store` does not exist in the Haste module map\\n\\nThis might be related to https://github.com/facebook/react-native/issues/4968\\nTo resolve try the following:\\n  1. Clear watchman watches: `watchman watch-del-all`.\\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.\\n    at ModuleResolver.resolveDependency (C:\\\\esites-native\\\\mypet\\\\node_modules\\\\metro\\\\src\\\\node-haste\\\\DependencyGraph\\\\ModuleResolution.js:161:1460)\\n    at ResolutionRequest.resolveDependency (C:\\\\esites-native\\\\mypet\\\\node_modules\\\\metro\\\\src\\\\node-haste\\\\DependencyGraph\\\\ResolutionRequest.js:91:16)\\n    at DependencyGraph.resolveDependency (C:\\\\esites-native\\\\mypet\\\\node_modules\\\\metro\\\\src\\\\node-haste\\\\DependencyGraph.js:272:4579)\\n    at dependencies.map.relativePath (C:\\\\esites-native\\\\mypet\\\\node_modules\\\\metro\\\\src\\\\DeltaBundler\\\\traverseDependencies.js:376:19)\\n    at Array.map (<anonymous>)\\n    at resolveDependencies (C:\\\\esites-native\\\\mypet\\\\node_modules\\\\metro\\\\src\\\\DeltaBundler\\\\traverseDependencies.js:374:16)\\n    at C:\\\\esites-native\\\\mypet\\\\node_modules\\\\metro\\\\src\\\\DeltaBundler\\\\traverseDependencies.js:212:33\\n    at Generator.next (<anonymous>)\\n    at step (C:\\\\esites-native\\\\mypet\\\\node_modules\\\\metro\\\\src\\\\DeltaBundler\\\\traverseDependencies.js:297:313)\\n    at C:\\\\esites-native\\\\mypet\\\\node_modules\\\\metro\\\\src\\\\DeltaBundler\\\\traverseDependencies.js:297:473\"}"
ERROR
12:12
Unable to resolve "mypet/store/store" from "App.js"
ERROR
12:12
Building JavaScript bundle: error
```

**Comment by jeremiehirsch** [comment]
Hello rahamin1, 

Do you have tried to update 'alias' like this :
`"alias": {
     "@app_name/mypet": "./src",
}`

Jérémie

**Comment by rahamin1** [comment]
Thank you @jeremiehirsch 
I will check and update

**Comment by gilsonviana** [comment]
I am having the same issue while trying to publish.
![Untitled](https://user-images.githubusercontent.com/12987365/57927689-c81afb00-787c-11e9-8da8-93da686a164e.png)

**Comment by gilsonviana** [comment]
@rahamin1 

Please, make the following change on your _.bablerc_ file.
`{
  "presets": ["babel-preset-expo"],
  "env": {
    "development": {
      "plugins": [
          ["transform-react-jsx-source"],
          ["module-resolver", {
            "root": ["./"],
            "alias": {
              "@mypet": "./src",
            }
          }]
        ]
    }
  }
}`

And you need also to update your **import** statement to reflect the given alias name.
For example: 
`import { MODULE } from '@mypet'`

I hope this work for you

**Comment by rahamin1** [comment]
Thank you, but it didn't help

**Comment by CristyTarantino** [comment]
Has anybody been able to solve this?

**Comment by brentvatne** [comment]
the problem is that the plugin you've specified is only under the `development` env

```
  "presets": ["babel-preset-expo"],
  "env": {
    "development": { <----------------- hello there
      "plugins": [
          ["transform-react-jsx-source"],
          ["module-resolver", {
            "root": ["./"],
            "alias": {
              "@mypet": "./src",
            }
          }]
        ]
    }
  }
```

you should either duplicate that for production or just remove the development bit

**Comment by rahamin1** [comment]
Indeed. And so simple... Thanks much, Brent!
