### ISSUE TITLE
Cannot destructure property `teamId` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by chrisdrackett** [expo/expo-cli#1052]
## Description

I'm trying to run the `expo upload:ios` in expo-cli `3.1.2` and I keep getting the following error:

```Cannot destructure property `teamId` of 'undefined' or 'null'.```

when using `3.0.10` I don't have any issues.

## Expected Behavior

Upload works without issue

## Observed Behavior

Upload fails with 

```Cannot destructure property `teamId` of 'undefined' or 'null'.```

## Environment

```
  Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.6.0 - /var/folders/ls/x4zssmm56vxgm5hc_81l99sm0000gn/T/yarn--1569884978201-0.06992665050503133/node
      Yarn: 1.17.3 - /var/folders/ls/x4zssmm56vxgm5hc_81l99sm0000gn/T/yarn--1569884978201-0.06992665050503133/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: 5.2.1 => 5.2.1 
      @types/expo: ^32.0.13 => 32.0.13 
      @types/react: ^16.8.22 => 16.9.2 
      @types/react-native: ^0.60.3 => 0.60.8 
```

**Comment by ccheever** [comment]
Hi-- Thanks for reporting this. 
Could you try again using the latest version of `expo-cli` which is 3.4.0?
I'm sorry you ran into this problem.

**Comment by soconrep** [comment]
I also same error with version 3.4.0 

> Failed to upload the standalone app to the app store.
Cannot destructure property `teamId` of 'undefined' or 'null'.
TypeError: Cannot destructure property `teamId` of 'undefined' or 'null'.
    at IOSUploader._getAppleTeamId (/expo-cli@3.4.0/src/commands/upload/IOSUploader.js:115:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
xxx-iMac:app-member xxx$ expo -V
3.4.0

**Comment by zelenko** [comment]
Same error with `expo-cli` version 3.4.1

**Comment by fson** [comment]
Looks like https://github.com/expo/expo-cli/pull/1122 might address this issue. It will be included in the next release.

**Comment by jeffreya421** [comment]
no



On Nov 14, 2019 12:58, "Ville Immonen" <notifications@github.com> wrote:

Looks like #1122 <https://github.com/expo/expo-cli/pull/1122> might address
this issue. It will be included in the next release.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/expo/expo-cli/issues/1052?email_source=notifications&email_token=AE3ET6PHTOQL57NQ64O3RLLQTW3XDA5CNFSM4I4BZ7Y2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEDISGY#issuecomment-554076443>,
or unsubscribe

**Comment by dsokal** [comment]
@chrisdrackett @soconrep @jeffreya421 could any of you if this is still an issue with the latest expo-cli version (3.22.3 at the moment)? Thanks!

**Comment by chrisdrackett** [comment]
I haven't seen this recently myself
