### ISSUE TITLE
expo install should handle broken npm install semver behavior

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#1054]
`npm install expo@~34.0.0` leads to `"expo": "^34.0.4"` in package.json. This is very problematic when used with libraries like `react-native-gesture-handler`, where minor version bumps mean native changes. If a user is to run `expo install` and get a version with a `^` matcher when we expect a `~` matcher, then `npm update` will likely cause errors in their app. Related issue: https://github.com/npm/npm/issues/19211

## Possible solutions

- Update package.json manually to have the proper version, and then run `npm install` without args, rather than running `npm install package@version`.
- Set `npm_config_save_prefix='~'` for users. This is not ideal because for some libraries we actually are OK with using `^`, eg: `babel-preset-expo`. It also forces us to modify a global config setting on the users machine (we could reset it immediately afterwards though, but that may lead to some weird race conditions if we run `expo install` in multiple places at the same time).

**Comment by byCedric** [comment]
I would prefer the first approach, manually update the package file and then run `npm install`. Should have no side-effects for other dependencies and it "forces" npm to use the `~` range, set in the file. 

There is one thing to keep in mind when "manually editing package files". It should keep the newlines and indentation intact, as set by the user. Had to do this too with [`semantic-release-expo`](https://github.com/byCedric/semantic-release-expo/blob/develop/src/expo.ts#L79-L83) 😄 

I'm happy to create a first draft of this!
