### ISSUE TITLE
expo upload:ios: "You must provide a company name to use on the App Store. You must provide a company name to use on the App Store."

### ISSUE THREAD

**Issue by fson** [expo/expo-cli#1066]
## Description

Uploading fails with the message "You must provide a company name to use on the App Store. You must provide a company name to use on the App Store."

## Expected Behavior

Created a new app with `expo init`, built with `expo build:ios` and expected `expo upload:ios` to upload it to the App Store.

## Observed Behavior

```
Ensuring the app exists on App Store Connect, this may take a while...

+----------------+------------------------------------+
|             Summary for produce 2.132.0             |
+----------------+------------------------------------+
| app_identifier | space.fson.example.testexpocli2310 |
| app_name       | Test320                            |
| username       | REDACTED                           |
| language       | English                            |
| sku            | 1570133934                         |
| platform       | ios                                |
| skip_itc       | false                              |
| skip_devcenter | false                              |
+----------------+------------------------------------+

[23:18:57]: [DevCenter] App 'space.fson.example.testexpocli2310' already exists, nothing to do on the Dev Center
[23:18:59]: Creating new app 'Test320' on App Store Connect
Failed to upload the standalone app to the app store.
You must provide a company name to use on the App Store. You must provide a company name to use on the App Store.
Set EXPO_DEBUG=true in your env to view the stack trace.
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

  Expo CLI 3.2.0 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /var/folders/vm/7_1sz9n56yj8d6v_dl1xpdf80000gn/T/fnm-shell-8862664/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /var/folders/vm/7_1sz9n56yj8d6v_dl1xpdf80000gn/T/fnm-shell-8862664/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.23 => 16.9.4 
      @types/react-native: ^0.57.65 => 0.57.65 
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.2.0

Also specify:

- Phone/emulator/simulator platform, model and version:
iOS, Xcode 11

**Comment by scott-d-young** [comment]
I have the same problem. Any updates?

More environment information
  Expo CLI 3.2.3 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      npm: 6.11.3 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.4
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.1 => 3.11.1
    npmGlobalPackages:
      expo-cli: 3.2.3

**Comment by thongnx6** [comment]
I have the same problem. Any updates?

**Comment by robbm1** [comment]
Same here:

Expo CLI 3.11.1 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      npm: 6.12.1 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.0 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-navigation: ^4.0.9 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.11.1

**Comment by robbm1** [comment]
In my case it was necessary to manually add the new app in App Store Connect to solve the problem. This is something that should be described in the Expo documentation or in the error message.
