### ISSUE TITLE
Eject doesn't create index.js file anymore

### ISSUE THREAD

**Issue by Aximem** [expo/expo-cli#107]
## Description

Eject command doesn't create index.js file anymore.

## Expected Behavior

expo init Test
cd Test
expo start
expo eject

## Observed Behavior

No index.js file are created (like it was in previous version), we get a : 

>  Cannot find entry file index.js

And we have to create, manually, index.js file.

## Environment

Environment:
  OS: macOS 10.14
  Node: 8.12.0
  Yarn: 1.3.2
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  expo: Not Found
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/aximem4363-f21198ce-aaec-4ede-9b5e-5f6c9d620287.tar.gz

Phone/emulator/simulator iOS or Android

**Comment by j3r1ch0-2007** [comment]
I understand that there limited development resources to work on issues but this was opened in October. I just encountered the same issue.

**Comment by bmwertman** [comment]
I'm just gettin started with React Native and ran into this issue. I ejected using the "React Native" option following this [Medium post](https://codeburst.io/how-to-avoid-wasting-time-building-a-mobile-app-and-make-a-release-with-single-click-part-1-19c598d21392) on getting started.

**Comment by sergeichestakov** [comment]
Sorry for the delay everyone. This issue was resolved in #567.
