### ISSUE TITLE
@expo/config's ProjectConfig type doesn't declare a "web" field

### ISSUE THREAD

**Issue by ide** [expo/expo-cli#1072]
In Config.ts (in `@expo/config`) we have the type:

```
type ProjectConfig = {
    exp: ExpoConfig;
    pkg: PackageJSONConfig;
    rootConfig: AppJSONConfig;
};
```

Then, in `jest-expo-puppeteer` we have:

```
const { web = {} } = readConfigJson(projectPath); // returns a ProjectConfig instance
```

This causes TypeScript errors because `ProjectConfig` does not declare a web field. We either need to declare that field, or change jest-expo-puppeteer.

**Comment by EvanBacon** [comment]
Fixed #1344
