### ISSUE TITLE
yarn v2 support

### ISSUE THREAD

**Issue by satishbabariya** [expo/expo-cli#1073]
> Error: node_modules directory is missing. Please run `npm install` in your project directory.

when using yarn v2 expo can't able to find node_modules folder ( due to yarn v2 dosn't use them instead it uses cache with zip)

```log
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Error: node_modules directory is missing. Please run `npm install` in your project directory.
Couldn't start project. Please fix the errors and restart the project.
Set EXPO_DEBUG=true in your env to view the stack trace.

```

**Comment by brentvatne** [comment]
@satishbabariya - anything we can do to help you add support for this in expo-cli?

**Comment by satishbabariya** [comment]
@brentvatne, I think we need to add support for yarn's PnP API. 
[https://next.yarnpkg.com/advanced/pnpapi](https://next.yarnpkg.com/advanced/pnpapi)
[https://next.yarnpkg.com/advanced/pnpify](https://next.yarnpkg.com/advanced/pnpify)

**Comment by brentvatne** [comment]
i personally don't have time to work on that but contributions are welcome!

**Comment by fson** [comment]
Right now Metro doesn't support the [Plug'n'Play](https://next.yarnpkg.com/features/pnp) mode, which is enabled by Berry (Yarn v2) by default (at least in the current `2.0.0-rc.27` version), so the most promising path to get Berry working would be using the [node-modules plugin](https://github.com/yarnpkg/berry/tree/master/packages/plugin-node-modules), which creates a backwards compatible `node_modules` folder. The plugin is enabled by creating a `.yarnrc.yml` file with the following contents in the project folder:
```yaml
nodeLinker: node-module
```

However, there seems to be a bug in Yarn `2.0.0-rc.27`, which makes the `yarn install` command hang indefinitely in this mode:
```
% rm -rf node_modules 
 % yarn -v 
2.0.0-rc.27
% yarn               
➤ YN0000: ┌ Resolution step
➤ YN0002: │ babel-preset-expo@npm:8.0.0 doesn't provide @babel/core@* requested by metro-react-native-babel-preset@npm:0.56.4
➤ YN0002: │ babel-preset-expo@npm:8.0.0 doesn't provide @babel/core@^7.0.0-0 requested by @babel/plugin-proposal-decorators@npm:7.8.3
➤ YN0002: │ babel-preset-expo@npm:8.0.0 doesn't provide @babel/core@^7.0.0-0 requested by @babel/preset-env@npm:7.8.3
➤ YN0002: │ expo@npm:36.0.2 doesn't provide react-native@* requested by @unimodules/react-native-adapter@npm:5.0.0
➤ YN0002: │ expo@npm:36.0.2 doesn't provide react@* requested by react-native-view-shot@npm:3.0.2
➤ YN0002: │ expo@npm:36.0.2 doesn't provide react-native@* requested by react-native-view-shot@npm:3.0.2
➤ YN0000: └ Completed in 0.32s
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 1.26s
➤ YN0000: ┌ Link step
➤ YN0007: │ core-js@npm:2.6.11 must be built because it never did before or the last one failed
➤ YN0000: └ Completed in 22.57s
➤ YN0000: Done with warnings in 24.2s
➤ YN0000: ⠹ ===============================================================================
^C%                                                                                                                                       
```
The command hangs indefinitely and the progress bar doesn't go away until `yarn` is terminated with ctrl-c. On the next run it finishes, but it seems that some packages are missing:
```
Attempting to open the project in a web browser...
(node:15094) UnhandledPromiseRejectionWarning: Error: Cannot find module 'worker-loader'
Require stack:
- /Users/ville/Projects/expo-cli/packages/webpack-config/webpack/loaders/createWorkerLoader.js
...
```

**Comment by scriptmaster** [comment]
This node_modules ecosystem sucks from past 10 years... Learn from NuGet.config

**Comment by tiagob** [comment]
This works for me in my expo app

In `.yarnrc.yml`
```
nodeLinker: node-module
```

```bash
% yarn --version
2.1.1
```

Like @fson said, Plug'n'Play has issues with Metro

- https://github.com/facebook/metro/issues/308
- https://github.com/react-native-community/cli/issues/27

**Comment by alamothe** [comment]
bump

**Comment by mekwall** [comment]
No reason to bump this. It's not something Expo can fix since React Native doesn't support Yarn PnP. It is tracked in https://github.com/react-native-community/cli/issues/27 and https://github.com/facebook/metro/issues/308

**Comment by Slapbox** [comment]
@mekwall this comment seems to suggest maybe otherwise: https://github.com/facebook/metro/issues/308#issuecomment-1020554787

But without some more reading I can't know whether that's truly relevant.

**Comment by Slapbox** [comment]
Any movement on this? Expo has been holding us back from upgrading Yarn for years now.

**Comment by mekwall** [comment]
> Any movement on this? Expo has been holding us back from upgrading Yarn for years now.

See my comment above. This is not an Expo issue.

**Comment by byCedric** [comment]
Hi all! Expo now supports `npm`, `yarn@1`, and `bun` without any additional setup. `yarn@2+` and `pnpm` requires additional setup for now:
- pnpm requires a `.npmrc` file, containing `node-linker=hoisted` ([docs](https://pnpm.io/npmrc#node-linker))
- yarn v2+ requires a `.yarnrc.yml` file, containing `nodeLinker: node-modules` ([docs](https://yarnpkg.com/configuration/yarnrc#nodeLinker)

Hope this helps!
