### ISSUE TITLE
Json file size

### ISSUE THREAD

**Issue by shadynoah** [expo/expo-cli#1076]
my app have two  json files  the first one size is 4 MB and second is 7MB and this make issue cause they enlarge bundles size ... how  can I reduce my json files size ????? is there alternative to use them ?

**Comment by raajnadar** [comment]
I think it has nothing to do with expo-cli

**Comment by ccheever** [comment]
Hi-- This isn't an issue with expo-cli so I'm going to close this issue.

You can post questions like this on StackOverflow or in the Expo forums.
