### ISSUE TITLE
Webpack config doesn't load TypeScript files from dependencies

### ISSUE THREAD

**Issue by kushalmahajan** [expo/expo-cli#1080]
I've an import from shared package of a typescript file

```
import { ButtonStyles } from "@org/shared/components/button";
```
But then on running `expo start --clear --web` throws me an error 

> Module parse failed: Unexpected token (6:7)
You may need an appropriate loader to handle this file type.
| const ButtonTypes = tuple("outlined", "primary", "danger", "link");

Expo version - 3.1.2
"expo-yarn-workspaces": "^1.2.0",

**Comment by AndreiCalazans** [comment]
@EvanBacon what's the status of this? I have monorepo setup with Expo and it fails to load the shared TypeScript module. I tried introducing ts-loader as well but it ends up with more issues. Is there a paved road for this? (note that I'm using Expo for a web app)

**Comment by EvanBacon** [comment]
Adding this feature would make Expo pretty slow. Libraries should ship their modules transpiled ahead of time.
If users would like to add this functionality, I recommend exposing the webpack.config.js and adding the `ts-loader` themselves, this way they can target the few packages they want to locally transpile every time.

If I could, I'd remove this functionality from Metro (native) as well. A base project currently takes ~10s to transpile.
