### ISSUE TITLE
Securing WebSocket API prevents use of Expo DevTools

### ISSUE THREAD

**Issue by kerbe** [expo/expo-cli#1081]
## Description

While using expo-cli from Docker container, access to Expo DevTools isn't anymore easily achieved. Previously Expo DevTools would listen 0.0.0.0:19002, which was easy to redirect in Docker. Now #1008 has increased security, but at same time forces Expo DevTools to bind only to 127.0.0.1:19002, preventing their use in this case, and also if wanting to have multiple computers accessing Expo DevTools.

## Expected Behavior

I would expect that this securing effort would be extended, so there would be option to choose which address Expo DevTools bind. There is already REACT_NATIVE_PACKAGER_HOSTNAME that is used to give correct address when expo-cli is ran inside Docker, there should also be something like EXPO_DEVTOOLS_LISTEN_ADDRESS, which could specify specific IP address, or even 0.0.0.0, while defaulting to 'localhost'.

## Observed Behavior

While expo-cli starts inside Docker just fine, and mobile phone can connect to it, trying to access port 19002 from outside Docker gives only error that no content is received. Inspecting what is happening inside Docker container, it is seen that ports 19000 and 19001 are listening ::, while 19002 is bound to 127.0.0.1

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:
```
Expo CLI 3.2.3 environment info:
    System:
      OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 12.10.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.0.9 => 3.4.1
    npmGlobalPackages:
      expo-cli: 3.2.3
```

**Comment by fson** [comment]
I think adding `EXPO_DEVTOOLS_LISTEN_ADDRESS` as an escape hatch for using Dev Tools with a special network set up, like with Docker would be a good solution. When the environment variable set, we should probably print a warning, to remind that using this setting requires you to protect the port from external access (e.g. by using a firewall), when you're in a public wi-fi or other untrusted network.

**Comment by kerbe** [comment]
I did try to add support for environment variable (branch & code visible above in my fork). That seems to allow listening 0.0.0.0 as desired, however if I try to access Expo DevTools via browser, I get only black background without any elements. I don't know where to start digging this further, so help is appreciated.
Needed to install expo-cli@3.0.11-alpha.1 which is previous release before this breaking change, and that works as before.

I tried asking pointers/guidance in expo slack, as I'm willing to help fix this, I just lack a bit knowledge right now. Any help is appreciated so I can get back to work with this.

**Comment by kerbe** [comment]
I think it was @sazzy4o who reported original issue, does he have knowledge / time to look at this & help forming pull request?

**Comment by kevinfaguiar** [comment]
Any news on this @kerbe @fson ? I'm currently running expo inside a docker container with VSCode Remote extension and can't access debug server (19002)...

**Comment by kerbe** [comment]
@kevinfaguiar no news. I've tried asking help in Slack, forums and here, but there hasn't been response that could help me to solving this problem further. So far only idea has been to use netcat to tunnel local port to inside docker container. It just is quite dirty hack, and not nice way for non-technical people to do.
Do you happen to have any chance to take a look into codebase, if you for example spot what I missed in my changes?

**Comment by nvcristea** [comment]
I have the same issue. Does anyone found any solution to this?

**Comment by kerbe** [comment]
Alright, I was able to figure it out. There is now PR made, lets hope it gets included in SDK 36.

@nvcristea and @kevinfaguiar there is working Docker image in my Docker Hub repo. You can pull it with this:
`docker pull kerbe/expo:devtoolfix`

And I use this kind of command to start my container:
`docker run -it --rm --name=expoio -p 19000:19000 -p 19001:19001 -p 19002:19002 -p 19006:19006 -v "$PWD:/app" -e REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.101 -e EXPO_DEBUG=true -e EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0 kerbe/expo:devtoolfix start`
Obviously change your own local IP address to that.

If you want to temporarily fix your own Docker images, this is how you can do it:
- Clone my fork of expo-cli
- Navigate to `expo-cli/packages/dev-tools` folder and run `npm pack`, which creates `expo-dev-tools-0.7.2.tgz` in same folder.
- Copy that tgz to your Docker image build directory and unpack it `tar xzf expo-dev-tools-0.7.2.tgz`
- Add following to your Dockerfile, after you have installed expo-cli: 
  - `ADD ./package /usr/local/lib/node_modules/expo-cli/node_modules/@expo/dev-tools`
- Build your image as usual.
