### ISSUE TITLE
Disabling wifi should change the indicator in the browser

### ISSUE THREAD

**Issue by fson** [expo/expo-cli#11]

**Comment by ccheever** [comment]
I tried reading the linked issue, but I still don't totally understand this issue. I don't see a wifi indicator in the expo-cli application. 

Can someone describe more clearly what should be implemented here?
@tcdavis or @fson ?

**Comment by tcdavis** [comment]
This is quite old so may be fine to just close.  Issue was that there are things within the UI (eg publishing, tunnel connection) that are guaranteed to not work if the user doesn't have a network connection and indicating that in some way would be nicer.
