### ISSUE TITLE
Remove either enquirer or inquirer 

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo-cli#1104]

**Comment by EvanBacon** [comment]
Getting rid of the snipped prompt in `expo init` in favor of just a name prompt would be nice too

**Comment by byCedric** [comment]
Maybe [this issue](https://github.com/expo/expo-cli/issues/1240) can help with dropping enquirer?

**Comment by EvanBacon** [comment]
Closing in favor of https://github.com/expo/expo-cli/issues/1983
