### ISSUE TITLE
Prompt user to install new version of client rather than just tell them there is a new version

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#1109]
When you have an outdated version of the client app in your simulator or emulator we should give users the ability to install the updated version in one or two keystrokes rather than having to manually remove the app from the simulator.

In cases where we can't do anything (physical iOS device, Android device not connected to machine) we should recommend people get the new version from the store or maybe do nothing? Up to the discretion of the implementer.

This will allow us to get rid of half of this step from "Upgrade Your App" bit of the release notes:

> Update the Expo app on your phones from the App Store / Google Play. expo-cli will automatically update your apps in simulators if you delete the existing apps, or you can run expo client:install:ios and expo client:install:android.

will become

> Update the Expo app on your phones from the App Store / Google Play. expo-cli will automatically prompt you to update the app in simulators.

**Comment by byCedric** [comment]
Do we need to "grab a list of clients/supported SDKs" when the developer wants to upgrade to a slightly older version of Expo? Or is that risk worth taken and just prompt if the user wants to upgrade?

**Comment by brentvatne** [comment]
that's a reasonable question - currently we don't actually factor in whether the latest expo client supports the sdk version that you're updating to. we probably want to warn / add some tag to unsupported versions (eg: in version list it could say `- 32.0.0 (Deprecated)`)

this gave me another idea - it might make sense for our client install commands to automatically install a version of the expo client app that is compatible with the sdkVersion in the local project

**Comment by byCedric** [comment]
Sounds great! Within the upgrade command, we can easily use the `iosClientUrl` and `androidClientUrl` from the SDK version they are upgrading to. I'm still having mixed feelings about not being able to fetch the currently installed client version. If a developer already installed it manually or upgraded another project, it might feel a bit annoying to constantly seeing the warning about upgrading the client. If there is no way, so be it, but it might be wise to take a look at this if it's possible.

In the `expo client:install:ios` we can reuse the `exp.sdkVersion` to determine their best option, right? Might be best to ask them if they want to install the "most compatible" one or just one of the list you mentioned?

**Comment by brentvatne** [comment]
> If a developer already installed it manually or upgraded another project, it might feel a bit annoying to constantly seeing the warning about upgrading the client. If there is no way, so be it, but it might be wise to take a look at this if it's possible.

I agree, maybe when we prompt to update automatically we can let people opt-out of seeing the message again for the current SDK version? We'd have to store that info in the `.expo` directory probably.

> In the expo client:install:ios we can reuse the exp.sdkVersion to determine their best option, right? Might be best to ask them if they want to install the "most compatible" one or just one of the list you mentioned?

Yes! That would be great. In addition to this we probably want to warn people if they are on a SDK verison that is incompatible with the clients currently on the store.

**Comment by byCedric** [comment]
I created a first draft of the install command, this might also affect my previous PR to simply "upgrade to latest" when upgrading. You can see what I did in #1148, any feedback is welcome ofc. 😄 Hope I did something you had in mind too.
