### ISSUE TITLE
The `expo-cli` user needs to be logged in to use development mode.

### ISSUE THREAD

**Issue by Gramatiik** [expo/expo-cli#111]
Hello expo community !

I just started using expo today and unfortunately I ran into an issue right after creating my project with expo-cli...
So just after creating my project with expo-cli, the app can't open on my mobile device with this error : **The Expo SDK requires Expo to run. It appears the native Expo modules are unavailable and this code is not running on Expo**

---

Setup information :
- macOS `10.14`
- node.js `8.12.0`
- expo-cli `2.2.1`
- watchman `4.9.0`
- Chrome 70

---

Steps to reproduce :
1. Create a new project with `expo init project_name` using any template.
2. `cd project_name && expo start`
3. Open Expo app on device and scan the QR code.
4. After the build, the following message appears : "**The Expo SDK requires Expo to run. It appears the native Expo modules are unavailable and this code is not running on Expo**"

This only happens when my app is **not** in production mode or if I am not logged in to expo-cli with my expo account.

I hope I gave enough information to investigate on this issue, if not, don't hesitate to leave a message, I will try to be as precise as possible !

Cheers 😃

**Comment by funkjunky** [comment]
Logging in to your expo account fixes this issue? Even outside production mode?

**Comment by funkjunky** [comment]
Wow you're correct! I didn't even know you could login through expo-cli.

So logging in through the cli solved my problem. I'm going to close my issue, but yours is definitely still valid. I was stuck all day, because I didn't even know you could login through the expo-cli.

**Comment by brentvatne** [comment]
hi! we rolled back expo-cli to 2.2.0 for now, if you install that it will resolve the issue. tomorrow we'll publish an updated new version tomorrow with the changes from 2.2.1/2.2.2 plus a fix for this
