### ISSUE TITLE
expo start always return getaddrinfo ENOTFOUND exp.host

### ISSUE THREAD

**Issue by kubido** [expo/expo-cli#1114]
I just updated expo-cli to `3.3.0`, every time I run `expo start` it stuck at this part 
`Opening DevTools in the browser... (press shift-d to disable)`

then after 4-5 minutes the packager is started running but displaying error like this :
```
Fetching the user profile failed
getaddrinfo ENOTFOUND exp.host
```

I able to scan the QR code but the bundling process won't start

**Comment by mori5321** [comment]
I encountered the same problem.

**Comment by ccheever** [comment]
Hi--
Are you connected to the Internet when you do this?
Do you have anything special setup in your local DNS config (`/etc/hosts` file or anything like that?)
What operating system are you on?
And what version of node?
If you're comfortable, can you say what part of the world you're running this command from?

**Comment by kubido** [comment]
Hi, 
I connected to the internet, no special config in  `/etc/hosts`
I use OSX Catalina (I'm not sure it's after updated to catalina or to expo-cli 3.3.0)

node `v12.11.1`,  I run from kuwait.

here's the log for `nslookup exp.host`
```
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	exp.host
Address: 104.197.216.164
```

`dig exp.host`
```
; <<>> DiG 9.10.6 <<>> exp.host
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 22516
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;exp.host.			IN	A

;; ANSWER SECTION:
exp.host.		221	IN	A	104.197.216.164

;; Query time: 147 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Oct 15 17:46:07 +03 2019
;; MSG SIZE  rcvd: 53
```

**Comment by MoathOthman** [comment]
Same for me here , it started like a week ago . 
when i run `nslookup exp.host` though 
I get 
;; connection timed out; no servers could be reached

@kubido did you find a solution for your issue ?

**Comment by fson** [comment]
Glad to hear you found a workaround. Normally `exp.host` should resolve to the IP address of the Expo backend API, I’m sorry to hear that is not the case in your location.

Please note that you can also always start the dev server with `expo start --offline` – in the offline mode it should not make any requests to `exp.host`. I hope this helps!

**Comment by ccheever** [comment]
Hi --

Also, if you know of a VPN/proxy server we could use that is inside Kuwait, we could maybe debug this more.

**Comment by MoathOthman** [comment]
@ccheever am not aware of a vpn that has a server in kuwait. I will let you know if I found one. 
@fson thank you for the `--offline` tip.

**Comment by Q8hma** [comment]
hello ,, how to build and make apk or ios ver ?? is it work offline ?

thnx

**Comment by MoathOthman** [comment]
You should be able to use expo build:ios/android normally , this issue wont affect that

Sent from my iPhone

On Dec 3, 2019, at 2:02 PM, HAMAD ADHBIYAH <notifications@github.com> wrote:

﻿

hello ,, how to build and make apk or ios ver ?? is it work offline ?

thnx

**Comment by Codeskin-byte** [comment]
@fson  Thank You! It  really helped me!

**Comment by marcosp200** [comment]
> Same for me here , it started like a week ago .
> when i run `nslookup exp.host` though
> I get
> ;; connection timed out; no servers could be reached
> 
> this occurs for ios and android deployment (`expo start --ios`) , `expo start --web ` works fine.
> 
> @kubido did you find a solution for your issue ?
> 
> update: when connecting through a vpn (us ip) it works fine.

Any other information on this ? - I am hitting the same issue on windows 10 - was working fine until last night - then  windows update - Rolled back the update but it does not resolve it.

**Comment by brentvatne** [comment]
it sounds like you might have dns issues. maybe something like this would be helpful https://stackoverflow.com/questions/222326/how-do-you-diagnose-network-issues-on-windows/222443

**Comment by marcosp200** [comment]
> it sounds like you might have dns issues. maybe something like this would be helpful https://stackoverflow.com/questions/222326/how-do-you-diagnose-network-issues-on-windows/222443
> 
> another option is to run it with `expo start --offline` until you figure it out

Yes I am using expo start --offline
But can no longer text the App on my Iphone device using QRCode . I do not have an apple device right now ..... 
All devices can ping and load pages from the other but Expo App will NOT load an app create with 'Expo Init' on the android emulator - It reports an exception -- Error: getaddrinfo EAI_AGAIN exp.host 
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
-- but works fine with Expo start --offline

**Comment by brentvatne** [comment]
you need to find out what is wrong with your dns or network config such that you're unable to reach exp.host.

try opening this in your browser: https://exp.host/--/api/v2/versions - does that work?

**Comment by marcosp200** [comment]
> https://exp.host/--/api/v2/versions



> you need to find out what is wrong with your dns or network config such that you're unable to reach exp.host.
> 
> try opening this in your browser: https://exp.host/--/api/v2/versions - does that work?

it did once .... but after restating expo it no longer works - tried several times - 'expo start ' 
Some how the DNS server is not responding reliably

**Comment by marcosp200** [comment]
Thanks brentvatne  - that link you gave pointed me on the right direction !
Resolved by clearing the DNS cache client service in windows. I used the steps from https://geeksadvice.com/how-to-fix-dns_probe_finished_nxdomain-error/
After that it all worked - I think the DNS cache got in a bad state during windows update

**Comment by marcosp200** [comment]
> you need to find out what is wrong with your dns or network config such that you're unable to reach exp.host.
> 
> try opening this in your browser: https://exp.host/--/api/v2/versions - does that work?

Thanks brentvatne - that link you gave pointed me on the right direction !
Resolved by clearing the DNS cache client service in windows. I used the steps from https://geeksadvice.com/how-to-fix-dns_probe_finished_nxdomain-error/
After that it all worked - I think the DNS cache got in a bad state during windows update

**Comment by marcosp200** [comment]
Thanks brentvatne - that link you gave pointed me on the right direction !
Resolved by clearing the DNS cache client service in windows. I used the steps from https://geeksadvice.com/how-to-fix-dns_probe_finished_nxdomain-error/
After that it all worked - I think the DNS cache got in a bad state during windows update

**Comment by omar-bakhsh** [comment]
connect to Router, not your Mobile Data works for me well :)

**Comment by Rahulyadav97** [comment]
there might be some issue with network try reconnecting to the network ,worked for me on second attempt

**Comment by sgClaudia98** [comment]
> Glad to hear you found a workaround. Normally `exp.host` should resolve to the IP address of the Expo backend API, I’m sorry to hear that is not the case in your location.
> 
> Please note that you can also always start the dev server with `expo start --offline` – in the offline mode it should not make any requests to `exp.host`. I hope this helps!

The `expo start --offline` command worked for me. Tnks
