### ISSUE TITLE
expo init error

### ISSUE THREAD

**Issue by h2m8n** [expo/expo-cli#1119]
I ran an expo init project to create an expo project.
However, yarn-error.log was generated and sdk35 not found error occurred.

 Error: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz: Request failed "404 Not Found"

**Comment by mori5321** [comment]
I encountered the same problem.
After I update expo-cli to 3.3.0, I could not run DevTools.

#### packages
expo-cli 3.3.0
expo 35.0.0

**Comment by h2m8n** [comment]
I use expo-cli 3.3.0 ...

**Comment by fson** [comment]
@mori5321 that sounds like a different, issue: this one is about the `expo init` command failing. Could you open a separate issue about it?

**Comment by fson** [comment]
@h2m8n it sounds like that could have been a temporary networking issue, with the request to https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz failing. Did you run `expo init` again after that and did it work? If you didn't try yet, could you try again? Also, which template did you choose in `expo init`?

If it works now, we might simply need to add some retry logic to the `npm install` part of the process.

**Comment by h2m8n** [comment]
I have tried several times.
But the error was the same.

The template uses blank and typescript.

It's not a temporary network error.

**Comment by h2m8n** [comment]
<img width="561" alt="스크린샷 2019-10-16 18 56 04" src="https://user-images.githubusercontent.com/48459881/66908785-a483f880-f046-11e9-9c04-217388b039c6.png">

**Comment by cruzach** [comment]
I can confirm the same `yarn-error.log` message is generated on `expo-cli` v3.4.0
However, I'm able to run all the usual commands without any problem

**Comment by fson** [comment]
It turns out the `yarn-error.log` file is a red herring. It was accidentally included in the published `expo-template-blank` and `expo-template-blank-typescript` packages, so currently it gets created every time when using those templates, even if there are no actual errors. (See https://github.com/expo/expo/pull/6024.)
