### ISSUE TITLE
"The Expo SDK requires Expo to run" red screen since install 2.2.1

### ISSUE THREAD

**Issue by funkjunky** [expo/expo-cli#112]
[Note: I've tried 2.2.2 and downgrading to 2.2.0 and the issue persists since upgrading]
## Description

Upgraded expo-cli to 2.2.1 as per recommendation of the expo start command. Got the title's red screen. Now I get that screen no matter the situation.

## Expected Behavior

I want a new app to show. `expo init`, then expo start to show a blank application. It currently shows the red screen.

## Observed Behavior

Red screen:

```
The Expo SDK requires Expo to run. It appears the native Expo modules are unavailable and this code is not running on Expo. Visit https://docs.expo.io to learn more about develop an Expo project.
```

## Environment

`expo diagnostics`
```
[14:58:34] Generating diagnostics report...
[14:58:34] You can join our slack here: https://slack.expo.io/.

  Expo CLI 2.2.2 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.8.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^30.0.1 => 30.0.1
      react: 16.3.1 => 16.3.1
      react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4
      react-navigation: ^2.18.0 => 2.18.0
    npmGlobalPackages:
      expo-cli: 2.2.2

  Diagnostics report:
\[14:58:44] Request failed with status code 500
[14:58:44] Set EXPO_DEBUG=true in your env to view the stack trace.
```

Also specify:

device: One Plus 5T

## Reproducible Demo

`npm i -g expo-cli`
`expo init`

**Comment by funkjunky** [comment]
Update: production mode works! but development mode doesn't work. It gives the red screen.

**Comment by juan-carlos-correa** [comment]
Update 

I init new test proyect using expo init, choose blank project. After installation of npm, i move to test folder and expo start. Scan QR and the same problem, What i missed?

node 8.12.0
npm 6.4.1

**Comment by alaboudi** [comment]
I also have this error on my android physical and virtual devices. I have not tried it with an iPhone. I am on `expo-cli@2.2.2`.

**Steps to reproduce:**

1. expo init myapp
2. expo start

**Comment by funkjunky** [comment]
So as per the issue #111 , If you login through expo-cli, the red screen goes away. At least it did for me.

So if other people are having this issue, try logging in through expo-cli. If not, perhaps create a new issue. I'm going to close this issue, because 111 is more specific.

**Comment by brentvatne** [comment]
hi! we rolled back expo-cli to 2.2.0 for now, if you install that it will resolve the issue. tomorrow we'll publish an updated new version tomorrow with the changes from 2.2.1/2.2.2 plus a fix for this
--
