### ISSUE TITLE
The "nonPersistent" option is gone from RN CLI / Metro

### ISSUE THREAD

**Issue by ide** [expo/expo-cli#1128]
See this failed CI run in which Expo CLI used the `nonPersistent` option when starting the RN server: https://circleci.com/gh/expo/expo/98998.

Fixing this is launch-blocking for SDK 36.

**Comment by fson** [comment]
This is fixed by #1132.

**Comment by slorber** [comment]
Hey, does the "expo" package comes with an expo-cli version or something?

I got this error after upgrading to SDK 36 on publish. Was only fixed after I add explicitly "expo-cli": "expo-cli@3.11.1" in my package.json. Not sure which version and how my CI run "expo" commands before but after my upgrade the version was probably incorrect.

Not sure it's a problem on Expo side, just giving a potential solution for people looking for one ;)
