### ISSUE TITLE
Expo CLI logs twice with RN 0.61

### ISSUE THREAD

**Issue by ide** [expo/expo-cli#1130]
RN 0.61 added a separate implementation of serializing logs on the client and sending them to the RN server. This means we see logs twice, because there is RN's implementation and our implementation. It is easy to repro (just `console.log(something)`).

I'm inclined to use our implementation of logging because we handle serialization better in several places and we want to manage the logs instead of a third-party dependency (RN) displaying its output.

**Comment by fson** [comment]
Fixed in https://github.com/expo/expo-cli/pull/1149.
