### ISSUE TITLE
does't instal expo cli

### ISSUE THREAD

**Issue by anilchejara1361** [expo/expo-cli#1134]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS D:\C_Drive_Program\js> npm install -g expo-cli
npm WARN deprecated joi@14.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN tarball tarball data for @expo/traveling-fastlane-darwin@1.10.0 (sha512-Ry9gHhDIPjSnP5lvtUcR7LoE5vU2Ngn893B22PYEk1RuwJG5m7ezKSGyXjs3W1WVUvPW/2+ikF1YjrNyPAIrqQ==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @expo/traveling-fastlane-linux@1.10.0 (sha512-+9Mjvs9m15Meexp00A2JDXLfQHwcgua1dI0ldqVboHblzTACTMvXrfHmewxBoIBLZ45c1lLuIHD7+3UAnBHVCA==) seems to be corrupted. Trying one more time.
Terminate batch job (Y/N)? ^C

**Comment by anilchejara1361** [comment]
i could not install exop cli in vs code

**Comment by Ravindia** [comment]
Yes, I am facing the issue/error during installation. Any fix for that?

**Comment by jkhales** [comment]
Hi, is this a fresh install or an upgrade?

**Comment by Ravindia** [comment]
It is fresh install

**Comment by jkhales** [comment]
Hm, can't seem to replicate it.

**Comment by mkhaledche** [comment]
I have this issue as well. Has been on the last line for 30 minutes.
npm WARN deprecated joi@14.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN tarball tarball data for @expo/traveling-fastlane-linux@1.10.0 (sha512-+9Mjvs9m15Meexp00A2JDXLfQHwcgua1dI0ldqVboHblzTACTMvXrfHmewxBoIBLZ45c1lLuIHD7+3UAnBHVCA==) seems to be corrupted. Trying one more time.
[            ......] - extract:@expo/traveling-fastlane-darwin: sill extract @expo/traveling-fastlane-darwin@1.10.0 ext

**Comment by eccianime** [comment]
Same here...
Any solutions?

**Comment by DKdEviL** [comment]
Please try uninstalling the nodejs and the removing `npm` and `node_modules` from your computer  where you can find them except your project folders and from `environment variable` also, remove `.npmrc` file too from `C:/user/*USERNAME*`
After that, install nodejs, move to `C:/user/*USERNAME*/Appdata/Roaming/npm` and there open cmd type `npm install -g expo-cli` and then it will work. I was facing this problem for 3-4 days but after the above mentioned steps it worked fine.

**Comment by jkhales** [comment]
Hi I passed to around to some other people and they couldn't reproduce it either. All I can suggest it  trying to uninstall it and retry. Sorry we couldn't be more helpful.

**Comment by ruvasqm** [comment]
Same issue, DKdEviL didnt work.

**Comment by wanderer-1994** [comment]
Same issue. Wasting alot of time with @expo/traveling-fastlane-linus and @expo/traveling-fastlane-darwin

**Comment by maroof-ahmed** [comment]
This worked for me...

https://stackoverflow.com/questions/58234545/npm-warn-tarball-tarball-data-for-expo-traveling-fastlane-darwin1-10-0-seems-t/59323762#59323762
