### ISSUE TITLE
Whats the future of below unsupported SDKs in Bare workflow ?

### ISSUE THREAD

**Issue by Gardens18** [expo/expo-cli#1139]
Whats the future of below unsupported SDKs in Bare workflow ?

We want to use Apploading, Auth session, splash screen in the bare workflow , whats the solution since the project has been ejected from managed to bare workflow, now everything broken.

AR
AppLoading
AuthSession
BackgroundFetch
ErrorRecovery
Linking
Notifications
ScreenOrientation
SplashScreen
StoreReview
TaskManager
Updates

**Comment by Gardens18** [comment]
Can anybody suggest the alternative for Apploading, AuthSession and SplashScreen

**Comment by fson** [comment]
This issue tracker is for reporting bugs in the Expo CLI, so I'll close this issue.

For discussions, the best place is Expo Forums (I saw you already opened a discussion at https://forums.expo.io/t/whats-the-future-of-unsupported-sdks-in-bare-workflow/29194 👍).

For new features, we use Canny (https://expo.canny.io/feature-requests), where you could submit a feature request for the modules that you would like to see in the bare workflow.
