### ISSUE TITLE
getting the same error even after changing to this

### ISSUE THREAD

**Issue by ahmedmansour1997** [expo/expo-cli#1145]
on C:\Users\ahmed mansour\AppData\Roaming\npm\node_modules\expo-cli\node_modules\getenv\lib\getenv.js:66
 throw new Error('GetEnv.NoBoolean: ' + value + ' is not a boolean.');
i followed the solution here https://github.com/expo/expo-cli/issues/295
but getting the same error even after changing to this  

> var isBool = (value === 'true' || value === 'false' || value === 'TRUE' || value === 'FALSE');

_Originally posted by @anujpro007 in https://github.com/expo/expo-cli/issues/295#issuecomment-539532088_

**Comment by manuelcelemin** [comment]
Hello, also i have same error after change text in getenv.js to :. 
var isBool = (value === 'true' || value === 'false' || value === 'TRUE' || value === 'FALSE');

Any solution?

**Comment by aldrinhronchi** [comment]
I also have this error

**Comment by fson** [comment]
Closing this, since it’s a duplicate of #295
