### ISSUE TITLE
app.json ios.icon field is ignored when ejecting to expokit

### ISSUE THREAD

**Issue by willmoffat** [expo/expo-cli#1153]
## Description

The `exp.ios.icon` field is ignored when ejecting to expokit. Despite being documented:
https://docs.expo.io/versions/latest/workflow/configuration/#ios

The `exp.android.icon` works as expected.

The bug appears to be in 
https://github.com/expo/expo-cli/blob/master/packages/xdl/src/detach/IosIcons.ts
which is missing the `isDetached` logic of the Android version:
https://github.com/expo/expo-cli/blob/master/packages/xdl/src/detach/AndroidIcons.ts#L120
```
if (isDetached) {
    iconUrl = manifest.android && manifest.android.icon ? manifest.android.icon : manifest.icon;
}
```

## Expected Behavior

`exp.ios.icon` should overrule `exp.icon`

## Observed Behavior

The value of `exp.ios.icon` is ignored.

## Environment
```
  Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.12.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
```

## Reproducible Demo

```
cd /tmp
expo init test
cd test
```

Edit `app.json` and add:
```
    "ios": {
      "icon":"THIS_IS_IGNORED",
      "supportsTablet": true
    }
```

Then run:
`expo eject --eject-method expokit`

Actual output:
```
03c90> (kCGColorSpaceDeviceRGB)] ( 0 0 0 1 )
<CGColor 0x7fc7cc603550> [<CGColorSpace 0x7fc7cc602450> (kCGColorSpaceDeviceRGB)] ( 0 0 0 1 )
<CGColor 0x7f7fa8202bd0> [<CGColorSpace 0x7f7fa8202930> (kCGColorSpaceDeviceRGB)] ( 0 0 0 1 )
…
```

Expected output:
```
 Invalid URI "THIS_IS_IGNORED"
```

## Workaround

Use `exp.icon` for the iOS icon and `exp.android.icon` for the Android icon.
... once you've spent an afternoon fighting the App Store validation tool :-(

**Comment by DottieDot** [comment]
I'm having the same issue for `expo.android.adaptiveIcon`.

```json
    "android": {
      "package": "******",
      "versionCode": 30,
      "icon": "./assets/ios-icon.png",
      "adaptiveIcon": {
        "foregroundImage": "./assets/android-icon-foreground.png",
        "backgroundImage": "./assets/android-icon-background.png"
      },
      "publishBundlePath": "android\\app\\src\\main\\assets\\shell-app.bundle",
      "publishManifestPath": "android\\app\\src\\main\\assets\\shell-app-manifest.json"
    },
```

**Comment by EvanBacon** [comment]
ExpoKit is now deprecated as of SDK 37. Please use the bare-workflow instead.
