### ISSUE TITLE
Make expo --help easier to read

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#1155]
Currently we show a ton of information when you run the help command, partially because we the command style we have gone for leaves us with a bunch of top level commands (eg: `expo push:android:upload`, `expo push:android:show`, `expo push:android:clear` are all top-level commands rather than sub commands or flags on `expo push`). We should somehow organize this to be neater. This will probably require opting out of the default commander help.

**Comment by tsapeta** [comment]
I completely agree. We have our own fork of commander (https://github.com/expo/commander.js) that we're using for expotools. See `et --help` in expo repo - it looks much clearer to me, uses chalk colors internally and supports multiple command aliases.

**Comment by ccheever** [comment]
How some other tools do it:

Netlify
![image](https://user-images.githubusercontent.com/56719/68747835-32a0bf80-05b0-11ea-89d1-70e5d9e3e6d6.png)

Heroku
![image](https://user-images.githubusercontent.com/56719/68748004-7f849600-05b0-11ea-8270-5a3ac14e8363.png)

ngrok
![image](https://user-images.githubusercontent.com/56719/68748017-86aba400-05b0-11ea-93f9-f99d3d755556.png)

Node (looks like it has the same problems as expo-cli)
![image](https://user-images.githubusercontent.com/56719/68748187-d1c5b700-05b0-11ea-8f0a-fc9616de901f.png)

Gatsby
![image](https://user-images.githubusercontent.com/56719/68748238-eb66fe80-05b0-11ea-931b-49f6e2fa0106.png)

**Comment by ccheever** [comment]
I tried swapping in @expo/commander, and here is how it looks:
![image](https://user-images.githubusercontent.com/56719/68792989-46c0dd00-0601-11ea-8d27-7fce4249e87a.png)

![image](https://user-images.githubusercontent.com/56719/68793006-4de7eb00-0601-11ea-8d0a-12f917afb365.png)

What do you think @brentvatne and @fson ?

**Comment by brentvatne** [comment]
@ccheever that looks like a good start!

**Comment by ccheever** [comment]
Discussed with @fson and he thought the Heroku and Netlify helps look the best, and I agree with him, so I think we should try that

**Comment by ccheever** [comment]
Following up on this, Heroku and Netlify use this library called [oclif](https://oclif.io/).
We should probably just switch to it from commander, or least seriously investigate doing that. It seems pretty good.
At a glance, doing this is probably not hard but is probably time consuming since commander is so intertwined in this library and the tutorials for using oclif involve running some setup command to make a new program with oclif rather than adding it to an existing program.

**Comment by ccheever** [comment]
I looked a little more at oclif and I'm not sure its worth the trouble of switching if we mainly just want the help messages to be prettier.

**Comment by EvanBacon** [comment]
Fixed in #2538
