### ISSUE TITLE
compiler.getInfrastructureLogger is not a function

### ISSUE THREAD

**Issue by davidbiller** [expo/expo-cli#1156]
### Environment
Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.10.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^3.12.0 => 3.13.0
    npmGlobalPackages:
      expo-cli: 3.4.1

Expo SDK 35 - WEB - Aws Amplify Build failed:

if i try to deploy, i get this message

```
                                 # Executing command: expo build:web
2019-10-28T18:22:56.709Z [WARNING]: - Making sure project is set up correctly...
2019-10-28T18:22:59.540Z [WARNING]: [18:22:59] compiler.getInfrastructureLogger is not a function
2019-10-28T18:22:59.571Z [WARNING]: [18:22:59] TypeError: compiler.getInfrastructureLogger is not a function
                                    at ExpoProgressBarPlugin.apply (/root/.nvm/versions/node/v10.16.0/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/node_modules/webpack/lib/ProgressPlugin.js:79:14)
                                    at webpack (/root/.nvm/versions/node/v10.16.0/lib/node_modules/expo-cli/node_modules/webpack/lib/webpack.js:47:13)
                                    at bundleWebAppAsync (/@expo/xdl@56.5.0/src/Webpack.ts:298:20)
                                    at Object.bundleAsync (/@expo/xdl@56.5.0/src/Webpack.ts:341:11)
2019-10-28T18:22:59.580Z [ERROR]: !!! Build failed

```

**Comment by maxparelius** [comment]
Getting same issue. My builds for web are not working

**Comment by maxparelius** [comment]
More context: tried going back to expo-cli version 3.3.0 and 3.2.0 and still not working so guising its an issue on amplify end? WIll continue investigating.

**Comment by jonathonlui** [comment]
I have same issue when running in Netlify automated deploy env. After doing some testing I can reproduce locally by running the build command with stdout and stderr redirected like this: 

```sh
expo build:web 2>&1 | cat
```

It'll output the `TypeError: compiler.getInfrastructureLogger is not a function` error.

I *think* the error is because `expo-cli` depends on `@expo/xdl` which installs `webpack@4.29.6` and separately the `expo` package depends on `@expo/webpack-config` which installs the newer `webpack@4.39.0` which has the webpack logger feature.

Since I use `yarn` and I also install `expo-cli` in the my project's `devDependencies` (instead of globally) I can force the webpack version using yarn's resolutions feature by adding this to my project's  package.json
```json
  "resolutions": {
    "expo-cli/**/webpack": "4.39.0"
  },
```

Works ok for me as I'm able to deploy on Netlify's build env and things like local dev seem ok.

I guess the right way to fix would be to align `@expo/xdl`'s webpack version with `@expo/webpack-config`.

**Comment by maxparelius** [comment]
Thanks @jonathonlui I was just gonna say seams related to https://github.com/webpack/webpack/issues/9553. I agree the better fix is to align the webpack versions being used.

**Comment by davidbiller** [comment]
> I have same issue when running in Netlify automated deploy env. After doing some testing I can reproduce locally by running the build command with stdout and stderr redirected like this:
> 
> ```shell
> expo build:web 2>&1 | cat
> ```
> 
> It'll output the `TypeError: compiler.getInfrastructureLogger is not a function` error.
> 
> I _think_ the error is because `expo-cli` depends on `@expo/xdl` which installs `webpack@4.29.6` and separately the `expo` package depends on `@expo/webpack-config` which installs the newer `webpack@4.39.0` which has the webpack logger feature.
> 
> Since I use `yarn` and I also install `expo-cli` in the my project's `devDependencies` (instead of globally) I can force the webpack version using yarn's resolutions feature by adding this to my project's package.json
> 
> ```json
>   "resolutions": {
>     "expo-cli/**/webpack": "4.39.0"
>   },
> ```
> 
> Works ok for me as I'm able to deploy on Netlify's build env and things like local dev seem ok.
> 
> I guess the right way to fix would be to align `@expo/xdl`'s webpack version with `@expo/webpack-config`.

@jonathonlui 
So you know an other fix? 
i get this error on amplify:

 expo: command not found

when i install it as dev dep.

**Comment by chayancbnits** [comment]
+1

**Comment by jonathonlui** [comment]
@davidbiller

The `expo: command not found` error is likely because when using locally-installed expo you'll need to run the build command like this:

```sh
yarn expo build:web
# or
./node_modules/.bin/expo build:web
```

> warning Resolution field "webpack@4.39.0" is incompatible with requested version "webpack@4.29.6"

That's an expected warning when overriding versions using yarn resolutions.

**Comment by davidbiller** [comment]
> @davidbiller
> 
> The `expo: command not found` error is likely because when using locally-installed expo you'll need to run the build command like this:
> 
> ```shell
> yarn expo build:web
> # or
> ./node_modules/.bin/expo build:web
> ```
> 
> > warning Resolution field "webpack@4.39.0" is incompatible with requested version "webpack@4.29.6"
> 
> That's an expected warning when overriding versions using yarn resolutions.

THX! Works! 
So now i have to wait fpr mjs support in Webpack. https://github.com/expo/expo/issues/4665

`Error: /codebuild/output/src271489382/src/aivy-dashboard-expo-web/node_modules/@aws-amplify/api/node_modules/graphql/index.mjs 49:0-53:205
                                    Can't reexport the named export 'BREAK' from non EcmaScript module (only default export is available)`

**Comment by brentvatne** [comment]
hey all, thank you for the detailed info, investigating, and the pr! @EvanBacon or @fson will get to it soon :)

**Comment by EvanBacon** [comment]
Seems like there is a part of the application code parsing that doesn't support MJS, will investigate now.

**Comment by sjchmiela** [comment]
Try installing `expo-cli@3.6.0`! It includes https://github.com/expo/expo-cli/commit/3768f280a6b22cd9f8f89a66d969037f7e8d29e6 which should fix the issue. 🙂

**Comment by maxparelius** [comment]
Thanks @sjchmiela problem is fixed for me

**Comment by arrygoo** [comment]
Just experiencing this on 3.8.0 again :(

**Comment by brentvatne** [comment]
@arrygoo - is this happening on 3.9.0? our ci appears to be running as expected so if you can give me an easy repro case we can look into it!

**Comment by brentvatne** [comment]
as far as i know this is not an issue and i cannot reproduce it on the latest version 3.9.1. please do let me know if it arises again.

we've taken precautions to prevent this in the future by locking the webpack dependency to a fixed version rather than flexible on minor version.
