### ISSUE TITLE
EXPO WEB - Can't reexport the named export 'BREAK' from non EcmaScript module

### ISSUE THREAD

**Issue by davidbiller** [expo/expo-cli#1167]
I get this error after expo start on web.

```
node_modules/@aws-amplify/api/node_modules/graphql/index.mjs 49:0-53:205
Can't reexport the named export 'BREAK' from non EcmaScript module (only default export is available)
```
i saw this:
https://github.com/expo/expo-cli/pull/1075

posted it on aws side too:
https://github.com/aws-amplify/amplify-js/issues/4299

**Comment by cruzach** [comment]
what version of `expo-cli` are you using?

**Comment by davidbiller** [comment]
> what version of `expo-cli` are you using?

```
➜  ~ expo-cli --version
3.5.0
```

**Comment by micabe** [comment]
Same issue here

**Comment by davidbiller** [comment]
@EvanBacon @cruzach 
Is there any workaround until its fixed? Any Idea?

**Comment by EvanBacon** [comment]
Could you please provide a repro so I can confirm if #1093 fixes the bug

**Comment by davidbiller** [comment]
@EvanBacon 
https://github.com/davidbiller/expo-amplify-test

**Comment by esuarezz** [comment]
The same here using amplify

**Comment by Elijen** [comment]
Worth to mention that the fix was done in `@expo/webpack-config` so updating this package solves the issue.
