### ISSUE TITLE
Can't escape "Production Mode" when developing

### ISSUE THREAD

**Issue by Slapbox** [expo/expo-cli#1168]
I enabled production mode for the first time in many months after getting stuck in it for a day in Expo 31. Unfortunately, same issue in Expo 33. Nothing you do can escape it except uninstalling Expo.

`expo start -c`: Nope
**Clearing Metro and Haste caches**: Nope
**Use "Clear Data" button for the project, from Expo's Info screen:** Nope
**Clearing Expo Cache on device:** Nope
**Restarting development machine:** Nope
**Clearing all Expo data on device:** ~~Nope~~ *Works if you clear all caches on development machine, stop the Expo app, and clear all data.* (Previously a full uninstall was the only thing that worked, back around February)

~~The ONLY THING that can get you out of development mode and back to production mode is completely uninstalling the Expo app. ~~

The CLI will say it's in development mode, but no changes to code are applied and shaking the device does not produce the Expo menu.

Expo SDK: 33 (Issue since at least 31)
Expo CLI: 2.21.2 (Issue since at least 2.14)
OS: Windows 7

**Comment by brentvatne** [comment]
here's a way to make sure you're not in production mode:

1) close expo-cli
2) close expo client
3) in your project directory delete the `.expo` directory
4) run `expo start --dev`
5) open your project in expo client again
6) you will *definitely* be in development mode

if not, please record a video of this happening and we can go from there :)

**Comment by brentvatne** [comment]
sdk 36 will help a lot with this next week. in addition to that, @cruzach landed a change to expo-cli recently that will default to starting expo-cli in development mode every time it's restarted.

**Comment by YahiaBadr** [comment]
i got the same problem in android only

**Comment by brentvatne** [comment]
@YahiaBadr - please create a new issue and fill out the issue template. i don't know how to reproduce this and need more info
