### ISSUE TITLE
Pre-pull request: [feat] Preserve color in command line

### ISSUE THREAD

**Issue by jrobber** [expo/expo-cli#1170]
## Description

I wrote some code that preserves log coloring in the terminal.  Right now color is only respected in the browser.

## Expected Behavior

When is send a log with color I want to see that color in the browser console (remote debugger), and in the cli-terminal

## Observed Behavior

What actually happened when you performed the above actions?

If you send node colors the browser looks terrible, if you send browser colors node looks terrible.

## Proposal

When the CLI receives a log report from the browser it will check for `%c`-the browser color escape character.  If it find it will parse and look for colors and plug them in to the existing chalk instance to re-format the string to use node viable colors.

The code blow modifies @expo/xdl/build/Project.js.  
It adds a reducer to the body to construct combinations of colorized string to their colors.
Then feeds them into a new function that builds the new colorized strings with chalk.

This would be my first pull request the cli, and before I put in all the effort to test it thoroughly and what not I wanted to make sure this is a direction you'd be okay with.

```
function convertWebColorToChalk(logObj) {
  const { msg, colors } = logObj;
  if (!colors) {
    return msg;
  }

  return msg
    .split('%c')
    .filter(x => x)
    .map((part, idx) => {
      return colors[idx] ? _chalk().default.hex(colors[idx])(part) : part;
    })
    .join('');
}

function _handleDeviceLogs(projectRoot, deviceId, deviceName, logs) {
  for (let i = 0; i < logs.length; i++) {
    let log = logs[i];
    let body = typeof log.body === 'string' ? [log.body] : log.body;
    let { level } = log;

    if (_isIgnorableBugReportingExtraData(body)) {
      level = _Logger().default.DEBUG;
    }

    if (_isAppRegistryStartupMessage(body)) {
      body = [`Running application on ${deviceName}.`];
    }

    let string = body
      .reduce((result, msg, i) => {
        if (typeof msg === 'undefined') {
          result.push({ msg: 'undefined' });
          return result;
        }

        if (msg === 'null') {
          result.push({ msg: 'null' });
          return result;
        }

        const last = result && result.length && result[result.length - 1];
        if (last && last.hasWebColorHash && msg.match(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/)) {
          last.colors = last.colors || [];
          last.colors.push(msg.trim());
        } else if (last && last.hasWebColorHash && msg.match(/^color:/)) {
          last.colors = last.colors || [];
          last.colors.push(msg.replace('color:', '').trim());
        } else {
          const hasWebColorHash = msg.indexOf('%c') >= 0;
          result.push({ msg, hasWebColorHash });
        }
        return result;
      }, [])
      .map(obj => {
        if (typeof obj.msg === 'string') {
          return convertWebColorToChalk(obj);
        }

        if (typeof obj.msg === 'number' || typeof obj.msg === 'boolean') {
          return obj.msg;
        }

        try {
          return JSON.stringify(obj.msg);
        } catch (e) {
          return obj.toString();
        }
      })
      .join(' ');

    ProjectUtils().logWithLevel(
      projectRoot,
      level,
      {
        tag: 'device',
        deviceId,
        deviceName,
        groupDepth: log.groupDepth,
        shouldHide: log.shouldHide,
        includesStack: log.includesStack,
      },
      string,
    );
  }
}
```

**Comment by brentvatne** [comment]
@jrobber thanks for this proposal! it seems like a reasonable thing to add. i'm not entirely sure about the implementation details but we can absolutely discuss it in a pull request! i'll close the issue and we can follow up in the pr if you're still interested!
