### ISSUE TITLE
Can´t run on android after ejecting

### ISSUE THREAD

**Issue by luis-sama** [expo/expo-cli#118]
## Description

I created a new project with expo init and then ejected. The I tried npm run android.

## Expected Behavior

I expected the app to start on my android emulator

## Observed Behavior

> C:\Users\Luis\Documents\Programacion\Proyectos\automsj>npm run android

> > empty-project-template@ android C:\Users\Luis\Documents\Programacion\Proyectos
> \automsj
> > react-native run-android
> 
> Scanning folders for symlinks in C:\Users\Luis\Documents\Programacion\Proyectos\
> automsj\node_modules (63ms)
> Starting JS server...
> Building and installing the app on the device (cd android && gradlew.bat install
> Debug)...
> Incremental java compilation is an incubating feature.
> :app:preBuild UP-TO-DATE
> :app:preDebugBuild UP-TO-DATE
> :app:checkDebugManifest
> :app:preReleaseBuild UP-TO-DATE
> :app:prepareComAndroidSupportAppcompatV72301Library
> :app:prepareComAndroidSupportRecyclerviewV72301Library
> :app:prepareComAndroidSupportSupportV42301Library
> :app:prepareComFacebookFrescoDrawee081Library
> :app:prepareComFacebookFrescoFbcore081Library
> :app:prepareComFacebookFrescoFresco081Library
> :app:prepareComFacebookFrescoImagepipeline081Library
> :app:prepareComFacebookFrescoImagepipelineOkhttp081Library
> :app:prepareComFacebookReactReactNative0201Library
> :app:prepareOrgWebkitAndroidJscR174650Library
> :app:prepareDebugDependencies
> :app:compileDebugAidl
> :app:compileDebugRenderscript
> :app:generateDebugBuildConfig
> :app:mergeDebugShaders
> :app:compileDebugShaders
> :app:generateDebugAssets
> :app:mergeDebugAssets
> :app:generateDebugResValues
> :app:generateDebugResources
> :app:mergeDebugResources
> :app:bundleDebugJsAndAssets SKIPPED
> :app:processDebugManifest
> :app:processDebugResources
> warning: string 'catalyst_debugjs' has no default translation.
> warning: string 'catalyst_element_inspector' has no default translation.
> warning: string 'catalyst_jsload_error' has no default translation.
> warning: string 'catalyst_jsload_message' has no default translation.
> warning: string 'catalyst_jsload_title' has no default translation.
> warning: string 'catalyst_reloadjs' has no default translation.
> warning: string 'catalyst_settings' has no default translation.
> warning: string 'catalyst_settings_title' has no default translation.
> 
> :app:generateDebugSources
> :app:incrementalDebugJavaCompilationSafeguard
> :app:compileDebugJavaWithJavac
> :app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed,
> no previous execution, etc.).
> C:\Users\Luis\Documents\Programacion\Proyectos\automsj\android\app\src\main\java
> \com\automsj\MainApplication.java:5: error: cannot find symbol
> import com.facebook.react.ReactApplication;
>                          ^
>   symbol:   class ReactApplication
>   location: package com.facebook.react
> C:\Users\Luis\Documents\Programacion\Proyectos\automsj\android\app\src\main\java
> \com\automsj\MainApplication.java:6: error: cannot find symbol
> import com.facebook.react.ReactNativeHost;
>                          ^
>   symbol:   class ReactNativeHost
>   location: package com.facebook.react
> C:\Users\Luis\Documents\Programacion\Proyectos\automsj\android\app\src\main\java
> \com\automsj\MainApplication.java:14: error: cannot find symbol
> public class MainApplication extends Application implements ReactApplication {
>                                                             ^
>   symbol: class ReactApplication
> C:\Users\Luis\Documents\Programacion\Proyectos\automsj\android\app\src\main\java
> \com\automsj\MainApplication.java:16: error: cannot find symbol
>   private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
>                 ^
>   symbol:   class ReactNativeHost
>   location: class MainApplication
> C:\Users\Luis\Documents\Programacion\Proyectos\automsj\android\app\src\main\java
> \com\automsj\MainApplication.java:36: error: cannot find symbol
>   public ReactNativeHost getReactNativeHost() {
>          ^
>   symbol:   class ReactNativeHost
>   location: class MainApplication
> C:\Users\Luis\Documents\Programacion\Proyectos\automsj\android\app\src\main\java
> \com\automsj\MainActivity.java:5: error: MainActivity is not abstract and does n
> ot override abstract method getPackages() in ReactActivity
> public class MainActivity extends ReactActivity {
>        ^
> C:\Users\Luis\Documents\Programacion\Proyectos\automsj\android\app\src\main\java
> \com\automsj\MainApplication.java:16: error: cannot find symbol
>   private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
>                                                        ^
>   symbol:   class ReactNativeHost
>   location: class MainApplication
> C:\Users\Luis\Documents\Programacion\Proyectos\automsj\android\app\src\main\java
> \com\automsj\MainApplication.java:35: error: method does not override or impleme
> nt a method from a supertype
>   @Override
>   ^
> 8 errors
> :app:compileDebugJavaWithJavac FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:compileDebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug
> option to get more log output.
> 

> BUILD FAILED
> 
> Total time: 58.978 secs
> Could not install the app on the device, read the error above for details.
> Make sure you have an Android emulator running or a device connected and have
> set up your Android development environment:
> https://facebook.github.io/react-native/docs/getting-started.html
> 

## Environment

> C:\Users\Luis\Documents\Programacion\Proyectos\automsj>expo diagnostics
> [10:46:45] Generating diagnostics report...
> [10:46:45] You can join our slack here: https://slack.expo.io/.
> 
>   Expo CLI 2.2.4 environment info:
>     System:
>       OS: Windows 7
>     Binaries:
>       npm: 4.6.1 - C:\Program Files\nodejs\npm.CMD
>     IDEs:
>       Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338
> 
>   Diagnostics report:
> /[10:56:22] Request failed with status code 500
> [10:56:22] Set EXPO_DEBUG=true in your env to view the stack trace.
> 

Emulator : Genymotion
Phone: Samsung Galaxy S8 API 26

**Comment by SebaGM94** [comment]
Exactly the same problem,
Got any solution ?!

**Comment by luis-sama** [comment]
No. Couldn't make it work.

**Comment by exidniy** [comment]
The same issue =(

**Comment by notflip** [comment]
+1 on this, any news?

**Comment by brentvatne** [comment]
apologies for no response on this. as far as i know any issues around building for android after ejecting have been intermittent and fixed quickly. if anyone encounters this again please create a new issue with more info
