### ISSUE TITLE
node_modules/expo/AppEntry.js: "" is not a valid identifer name

### ISSUE THREAD

**Issue by jeanverster** [expo/expo-cli#1182]
## Description

I've recently upgraded to the latest version of the expo cli, and when I run `expo init` and select the blank TypeScript template, when I cd into the directory it creates and run yarn start. The app doesn't compile and I get hit with:

`node_modules/expo/AppEntry.js: "" is not a valid identifer name`

## Expected Behavior

I expected the app to compile after initialising a new expo project.

## Observed Behavior

The app didn't compile and threw an error.

If there's an error message, please paste the _full terminal output and error message_ in this code block:

```
Logs for your project will appear below. Press Ctrl+C to exit.
Opening exp://127.0.0.1:19000 in iOS simulator
node_modules/expo/AppEntry.js: "" is not a valid identifer name
Failed building JavaScript bundle.
```

## Environment

  Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.23 => 16.9.11 
      @types/react-native: ^0.57.65 => 0.57.65 
      expo: ^35.0.0 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.4.1

Also specify:

- iPhone 11 Emulator, iOS 13.1

## Reproducible Demo

https://github.com/jeanverster/expo-repro

**Comment by asibrahim1985** [comment]
I checked the error on expo client on mobile device and it was pointing to this file 
C:\Ahmed\ReactNativeProjects\cust-fonts\node_modules\@babel\types\lib\definitions\core.js at line 322.
This line was changed in babel package version 7.7 to be throw new TypeError(`"${val}" is not a valid identifer name`);

however in version 7.6.3 used error this line does not exist.

As a workaround I delete this line from the file and then I am able to run the app normally

**Comment by leogouveia** [comment]
@asibrahim1985 seems babel fixed this error on version 7.7.1 https://github.com/babel/babel/releases/tag/v7.7.1

**Comment by asibrahim1985** [comment]
@leogouveia Hello dearm yes you are right,

**Comment by jeanverster** [comment]
Closing this issue as has been fixed on Babel's side 👍
