### ISSUE TITLE
expo build:android results in "connect ECONNREFUSED"

### ISSUE THREAD

**Issue by sudeephazra** [expo/expo-cli#1186]
This is my first mobile development project and I decided to go the platform-independent route. For this, React Native seemed to be my choice and Expo the preferred toolchain.

My builds were getting completed properly until yesterday. And then I started facing issues with the android build.

This started happening suddenly when the android build started to fail with the below error

`connect ECONNREFUSED 127.0.0.1:19001
Error: connect ECONNREFUSED 127.0.0.1:19001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)`

Windows 7
Node: 10.15.3
NPM: 6.4.1
Expo: 35.0.0
Expo CLI: 3.4.1
React: 16.8.3
React Native: 0.59.10

I tried deleting the `.expo` folder, clearing the cache using running `expo start -c` but to no avail. I also deleted my modules and did an `npm install` to reload the modules but still reached nowhere.

I saw a lot of issues raised for this and the solution that worked for me was to run `expo start` to run MetroBuilder locally on one window and then create another window and run `expo build:android`

Although this is solved, I would like to know why this happened suddenly. I did not upgrade any software on my machine and I am not sure if this will happen again or what I can do to avoid it.

**Comment by cruzach** [comment]
Do you have `expo-cli` installed globally? 
Another common solution is to run `expo start` and cancel with `ctrl+c`

I've seen this reported before but have yet to repro it, not sure if this is windows-specific?

**Comment by sudeephazra** [comment]
Yes. `expo-cli` is installed globally. In this situation, I am running the command from the project folder. Not sure if that makes any difference. The greatest reason for my confusion is the fact that the same thing just suddenly stopped working out-of-the-blue one fine day.

**Comment by jhenrich** [comment]
Had the same error, removing the .expo folder fixed it for me

**Comment by owencyc** [comment]
> Had the same error, removing the .expo folder fixed it for me

yeah,it works for me,thx~

**Comment by brentvatne** [comment]
we'll investigate how we can detect if the `.expo` saved config is invalid and follow up in https://github.com/expo/expo-cli/issues/1308

**Comment by simdanonline** [comment]
> Had the same error, removing the .expo folder fixed it for me

Thanks, worked for me too

**Comment by chohonest** [comment]
> Had the same error, removing the .expo folder fixed it for me

Thanks this fixed it for me as well!

**Comment by IronYeti** [comment]
I used cruzach's suggestion (run expo start then ctrl+c) which worked for me, almost.

During my build I got an EPERM error about operation not permitted, rename '...packager-info.json.1807243929' to 'packager-info.json'.  So then removed .expo like the others and then my build worked.

This is the first time I've had this issue after many successful builds.  No idea what triggered it.  Glad it was an easy fix (once I found this thread).

**Comment by iib0011** [comment]
> Had the same error, removing the .expo folder fixed it for me
me too
thanks

**Comment by Cyrille09** [comment]
Thanks, it works for me too

**Comment by JohanQueo** [comment]
@jhenrich it woks fine for me thanks :)

**Comment by SantyLorenzo** [comment]
> Had the same error, removing the .expo folder fixed it for me

It works for me too <3
