### ISSUE TITLE
chore(deps): reference to unknown version of gulp-babel

### ISSUE THREAD

**Issue by jamesgeorge007** [expo/expo-cli#1188]
Installing dependencies result in the following error being thrown:-
```bash
sudo npm i
npm ERR! code ETARGET
npm ERR! notarget No matching version found for gulp-babel@^8.0.01.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'expo-cli'
npm ERR! notarget 
```

**Comment by ccheever** [comment]
@wkozyra95 -- you made change b45e9dbf7 which upgraded this package from 7.0.1 to 8.0.01.

```
-    "gulp-babel": "^7.0.1",
+    "gulp-babel": "^8.0.01",

```

Looking at the npm website, there is no 8.0.01 version of the package? Is there a reason to use that instead of 8.0.0?

**Comment by wkozyra95** [comment]
Probably typo when upgrading the package.

**Comment by wkozyra95** [comment]
https://github.com/expo/expo-cli/commit/fc17769741615d13c979b156ab61e3383aef4919
