### ISSUE TITLE
Detach command relies on a name instead of a slug.

### ISSUE THREAD

**Issue by n-sviridenko** [expo/expo-cli#119]
Sorry for writing it without following the format. I need to use this time to find a workaround for the issue below :( 

After ejecting, I renamed my app. After I run xcode and it was failed because it was expected my ios app path to be changed as well. The issue is that I didn't change the slug. So it means that name is not only for displaying it in app list? Why not to use slug then?

**Comment by n-sviridenko** [comment]
This will give you more context:
- https://github.com/expo/expo-cli/blob/b7a059b78f12e1283a6b5c4ab9dec0b6ae86ca0f/packages/xdl/src/detach/IosWorkspace.js#L353-L354
- definition of `name`: https://docs.expo.io/versions/latest/workflow/configuration#name-563

**Comment by EvanBacon** [comment]
AFAICT this feature has moved to `@expo/config` and is thoroughly unit tested as part of the bare-workflow.
