### ISSUE TITLE
onLayout relies on ResizeObserver which is not supported by your browser. Firefox and Safari

### ISSUE THREAD

**Issue by chayancbnits** [expo/expo-cli#1198]
onLayout relies on ResizeObserver which is not supported by your browser. Please include a polyfill, e.g., https://github.com/que-etc/resize-observer-polyfill. Falling back to window.onresize.

How do I fix that in issue, I am using React Native Expo 35 SDK?

[Refered Link](https://github.com/necolas/react-native-web/issues/1473)

**Comment by fson** [comment]
cc @EvanBacon, should we include (or document the instructions for including) `resize-observer-polyfill`?

**Comment by EvanBacon** [comment]
@chayancbnits which browser are you using that doesn't support `ResizeObserver`?

**Comment by chayancbnits** [comment]
> @chayancbnits which browser are you using that doesn't support `ResizeObserver`?

I am using the Safari browser. I have tested my code in Chrome and Firefox as well but I didn't get that error.
![Screenshot 2019-11-15 at 6 37 31 PM](https://user-images.githubusercontent.com/51107138/68945818-4bd78500-07d7-11ea-8ac0-c9406e1752a5.png)

**Comment by brentvatne** [comment]
`ResizeObserver` isn't supported on a number of browsers still: https://caniuse.com/#feat=resizeobserver
