### ISSUE TITLE
Expo-cli can't access network by proxy

### ISSUE THREAD

**Issue by smartsoul** [expo/expo-cli#120]
PS E:> expo login
[11:09:52] Fetching the user profile failed
[11:09:52] write EPROTO 15264:error:14094419:SSL routines:ssl3_read_bytes:tlsv1 alert access denied:openssl\ssl\record\rec_layer_s3.c:1407:SSL alert number 49

I am on proxy network environment.

Expo-cli: 2.2.4
Expo: 30.0.0

**Comment by mei-rong** [comment]
Hi, I have this problem again, is there any idea?

**Comment by brentvatne** [comment]
i believe we need to make it possible to add a proxy config. we use axios for our http requests (see this code: https://github.com/expo/expo-cli/blob/d8eb90e1f9acd3907001994ae20cbde54acae84c/packages/xdl/src/ApiV2.ts#L135-L189), and as far as i understand we can customize axios for proxies using [the config described here](https://github.com/axios/axios/issues/1679#issuecomment-407406296).

**Comment by EvanBacon** [comment]
Unfortunately this error is too broad to approach. Please open a more specific error using the error template so we can better understand the root cause.
