### ISSUE TITLE
how to proxy  exp://127.0.0.1:19000

### ISSUE THREAD

**Issue by soitun** [expo/expo-cli#1200]
Hello everyone, I installed docker on the server, and run expo in docker. I also configured nginx proxy 19000 port on the server, but the expo client can't access it. What do I need to do?

**Comment by ccheever** [comment]
Hi -- I moved this over to our forums since I don't think its a bug with expo-cli, just that you're having trouble with getting things setup.

https://forums.expo.io/t/how-to-proxy-exp-127-0-0-1-19000/30013/2

Can you add additional information over there and maybe someone will be able to help you?
