### ISSUE TITLE
Attempting to open the project in a web browser... results in UnhandledPromiseRejectionWarning: Error: Cannot find module 'es-abstract/es7'

### ISSUE THREAD

**Issue by rkeshwani** [expo/expo-cli#1203]
## Description

Running into the following error when attempting to launch the browser version of my react native application using expo. For reference this occurred after I updated my global expo cli version from **3.4.0** to **3.4.1**. I ran into issues running the install command so I deleted the entire expo cli folder from my global node_modules folder and re-installed expo cli. I attempted to test using a clean expo init project but ran into other issues there which I won't cover here. I suspect the issue has to do with corejs which expo uses internally but not sure. After doing some digging, I can't determine which module is requiring the es-abstract/es7 module I checked the webpack-config module and could not find anything there except a potential reference to babel-cli-preset but could not find anything related to es-abstract/es7. See: [Es-abstract](https://www.npmjs.com/package/es-abstract)

## Expected Behavior

I expect my application to compile normally and serve/launch the application in a new window when I press the w key in an interactive console after I run npm start or expo start.

## Observed Behavior

There is an error message while doing this.

```
Attempting to open the project in a web browser...
(node:11328) UnhandledPromiseRejectionWarning: Error: Cannot find module 'es-abstract/es7'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\<UserName>\AppData\Roaming\nvm\v10.16.3\node_modules\expo-cli\node_modules\object.entries\implementation.js:3:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
(node:11328) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:11328) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:
  Expo CLI 3.4.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5900203

**Comment by rkeshwani** [comment]
I found out that there was an issue with my npm cache (not sure why).
The "es-abstract" dependency of expo-cli was being installed by npm but only the package,.json file and nothing else. 

I completely removed the expo-cli node_module, ran` npm clear cache --force`, and then re-installed expo-cli which resolved the issue.

**Comment by tabrez500** [comment]
> I found out that there was an issue with my npm cache (not sure why).
> The "es-abstract" dependency of expo-cli was being installed by npm but only the package,.json file and nothing else.
> 
> I completely removed the expo-cli node_module, ran` npm clear cache --force`, and then re-installed expo-cli which resolved the issue.

Hi @rkeshwani, I think the actual command for clearing cache is `npm cache clean/clear --force` depending on your needs.
Reference: https://docs.npmjs.com/cli-commands/cache.html

**Comment by rkeshwani** [comment]
@tabrez500 You are correct. I edited the comment above to correctly reflect that.
