### ISSUE TITLE
[android] Upgrade Google Play Developer API to version 3

### ISSUE THREAD

**Issue by lporras** [expo/expo-cli#1208]
Hi guys,

Yesterday I published an android app on the play store using expo sdk version 33 without problems.  But I'm getting a message about upgrading google Play developer API to version 3.

<img width="993" alt="Captura de Pantalla 2019-07-03 a la(s) 09 56 31" src="https://user-images.githubusercontent.com/232293/60599864-2b091880-9d7d-11e9-9731-ed2db4350866.png">

How can I upgrade the google Play Developer API to version 3?

Thanks,

**Note:** The link "learn more" goes to this [page](https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html)

I also made a post as a feature request [here](https://expo.canny.io/feature-requests/p/upgrade-google-play-developer-api-to-version-3), but I don't know if this applies as a feature request.

**Comment by fson** [comment]
Looks like the fix landed in the latest Fastlane release, so we now just need to upgrade Fastlane.

**Comment by fson** [comment]
We'll look into this soon, but please note that even after December 1st you can always [upload your Expo app to Play Store](https://support.google.com/googleplay/android-developer/answer/113469?hl=en) manually, like any other Android app, using `expo upload:android` is optional.

**Comment by dsokal** [comment]
This should be fixed in the next release of expo-cli.

**Comment by lundcm** [comment]
If this issue will be resolved in the next release wouldn't it stay open until that release happens?

What release version is that? When is that release or is there a page for it?

**Comment by leoskyrocker** [comment]
@lundcm It should be there since expo 3.8.1.
This seems to be the fix related to this issue:
https://github.com/expo/expo-cli/commit/4ac868b5c8ca359de923147c70a36b500ff44194

![Screen Shot 2019-12-06 at 3 19 22 PM](https://user-images.githubusercontent.com/2366893/70303978-d4c46800-183b-11ea-9863-892e91ab4a1d.png)
