### ISSUE TITLE
Hotkey to clear screen in terminal

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#122]
Can't to the typical ctrl+l so it would be good to have some equivalent, or just make ctrl+l work

**Comment by fson** [comment]
@brentvatne Ctrl+L works for me (using Terminal.app). Which terminal emulator are you using?

**Comment by brentvatne** [comment]
iTerm

**Comment by EvanBacon** [comment]
you know about ⌘+k right?

**Comment by brentvatne** [comment]
@EvanBacon - i did not. ur a leg

**Comment by technoplato** [comment]
Is there any way to do this programatically a la nodemon when the app refreshes?

https://github.com/remy/nodemon/issues/1318#issuecomment-382656915

**Comment by Norfeldt** [comment]
@EvanBacon 
> you know about ⌘+k right?

It does "clear" it, but the history shows again when another `console.log` is hit

**Comment by sferdev** [comment]
## For Windows

* Right-click on terminal's title
*  Check `Clear Terminal`

![2023-05-28 13_00_54](https://github.com/expo/expo-cli/assets/23435998/7fc935d8-0adf-4401-b3ad-9401ea363ef3)

* This will add this icon on which you can click every time you want to clear your terminal

![2023-05-28 12_56_29](https://github.com/expo/expo-cli/assets/23435998/6c830cb8-1d3b-498d-b55e-216722d4b28f)

## For Linux

Just right-click on the terminal and select clear terminal.

Hope this helps :)
