### ISSUE TITLE
Non interactive mode asks for input

### ISSUE THREAD

**Issue by antoine-souesme-needone** [expo/expo-cli#1224]
## Description

Input is asked when running build command with `--non-interactive` flag.

## Expected Behavior

Built an ios archive, then re-run command in a bitbucket pipeline. Expo-cli should not ask for input.

## Observed Behavior

```
There were no new changes from the last build, you can download that build from here: https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/ios/%40lcde/onestaff-d38289d9-9e0e-4f8d-8d9a-88123d5278f1-archive.ipa
 Input is required, but Expo CLI is in non-interactive mode.
Required input:
> Do you want to build app anyway?
```

Pipeline fails

## Environment

```
Expo CLI 3.4.1 environment info:
    System:
      OS: Linux 4.19 Debian GNU/Linux 9 (stretch) 9 (stretch)
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.12.1 => 3.12.1 
```

## Reproducible Demo

Build once, then re-run the command: `expo build:ios --release-channel staging --no-publish --no-wait --non-interactive`

**Comment by fson** [comment]
Looks like we need to add a `--force` flag for non-interactive mode. It would correspond to choosing “yes build anyway” in the prompt.

**Comment by antoine-souesme-needone** [comment]
Thank you for your response !
So as you suggested, I added the --force flag to the command, `expo build:ios --release-channel staging --no-publish --no-wait --non-interactive --force`.

Seems like expo does not know this flag

```
error: unknown option `--force'
```

**Comment by fson** [comment]
Yes, sorry I meant it doesn't exist yet, we'll need to add it to Expo CLI first 😅

**Comment by antoine-souesme-needone** [comment]
Oh ok lol, thanks for your time, looking forward to it !

**Comment by robsonsky** [comment]
I've got the same issue. Any news on this?

**Comment by khanzzirfan** [comment]
I've got the same issue. Expo Android Build fails every time since last 3 days for me.
Surprisingly it did build once today successfully. But giving me the older version of the build. Still pointing to older version code and cannot deploy to google store.
https://expo.io/builds/238d024e-9a42-47e8-b337-fd86340ff0ce.

I tried to build with new version code and back to same build failures. Did expo changed build policy to build only one time a day? A quick help would be really appreciated.


Cheers,
Irfan

**Comment by fcsonline** [comment]
We've got the same issue. 

A workaround with the `yes` command could be:

```bash
yes | expo build:ios --release-channel staging --no-publish --no-wait --non-interactive
```

**Comment by brentvatne** [comment]
that workaround is a good option! we also removed this forced prompt and it will go out in the next release

**Comment by 369855707** [comment]
I dont know why but I am using window7, it was failed to run **expo build:android --release-channel staging --no-publish --no-wait** at git bash. 
but, but.. if you run the same from cmd, it will letting you choose
