### ISSUE TITLE
 _xdl(...).ProjectUtils.readConfigJsonAsync is not a function

### ISSUE THREAD

**Issue by thebetterjort** [expo/expo-cli#1228]
**Software** 

- expo: 3.4.1
- expo sdk 35
- yarn run v1.16.0

**What I've done so far:**
```
expo init kittens
cd kittens
yarn run start (& and npm run start)
```

**Error**
_Starting project at /home/th/kittens
_xdl(...).ProjectUtils.readConfigJsonAsync is not a function_

I've also tried _expo upgrade_, same error.

**Comment by rrufus** [comment]
Seems to be the same for any `expo` function. I am seeing it on `start` and `publish`.

Also this issue is the same. https://github.com/expo/expo-cli/issues/1227

**Comment by fson** [comment]
We're working on a quick fix to this. Closing this issue as a duplicate, tracking progress in #1227.
