### ISSUE TITLE
expo start isn't working

### ISSUE THREAD

**Issue by 7sean68** [expo/expo-cli#1233]
## Description

expo start doesn't work even for a new project that was just created using expo-cli

## Expected Behavior

Starts or restarts a local server for your app and gives you a url to it.

## Observed Behavior

```
Starting project at E:\nasnav\AwesomeProject
_xdl(...).ProjectUtils.readConfigJsonAsync is not a function
TypeError: _xdl(...).ProjectUtils.readConfigJsonAsync is not a function
    at configureProjectAsync (C:\expo-cli@3.4.1\src\commands\start.js:188:43)
    at action (C:\expo-cli@3.4.1\src\commands\start.js:58:34)
    at C:\expo-cli@3.4.1\src\commands\start.js:230:16
    at Command.<anonymous> (C:\expo-cli@3.4.1\src\exp.ts:81:7)
```

## Environment

Expo CLI 3.4.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.19.1 - C:\Users\username\AppData\Roaming\npm\yarn.CMD
      npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD

**Comment by ahkaneti** [comment]
Are there going to be any updates on this issue?

**Comment by brentvatne** [comment]
this was an issue if you attempted to install an old version of expo-cli recently (3.4.1 was the one mentioned here, 3.9.1 is the latest). we fixed the issue on old expo-cli versions and the latest versions don't show this error.
