### ISSUE TITLE
expo start gives freeport-async error [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received 65536.

### ISSUE THREAD

**Issue by DaveClissold** [expo/expo-cli#1238]
## Description

For the past couple of days since trying to update the expo-cli from version 3.0.4 to 3.4.1, when I try running `expo start` the dev tools opens on port :19002 in the browser, as expected but when I try to launch the app using the ios or android simulators, it hangs and terminal eventually publishes an error saying that it cannot find an open port, I have tried rolling back to a different version of expo-cli and have tried multiple versions of node, but nothing will get past this error

## Expected Behavior

freeport-async to find a port, connect and launch the expo app

## Observed Behavior

The simulator loads with the 'There was a problem loading the requested app' screen.  When i test freeport-async in a separate repo with the following code 

```
const freeportAsync = require('freeport-async');
freeportAsync(19000).then(port => {
  console.log(port);
});
```
I get assigned the port I pass in to function

Below is the error message terminal will show after 15 seconds waiting on expo start

```
(node:4996) UnhandledPromiseRejectionWarning: RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received 65536.
    at Server.listen (net.js:1412:13)
    at /Users/Dave/.config/yarn/global/node_modules/@expo/xdl/node_modules/freeport-async/index.js:8:12
    at new Promise (<anonymous>)
    at testPortAsync (/Users/Dave/.config/yarn/global/node_modules/@expo/xdl/node_modules/freeport-async/index.js:6:10)
    at availableAsync (/Users/Dave/.config/yarn/global/node_modules/@expo/xdl/node_modules/freeport-async/index.js:24:17)
    at Promise (/Users/Dave/.config/yarn/global/node_modules/@expo/xdl/node_modules/freeport-async/index.js:37:23)
    at new Promise (<anonymous>)
    at freePortRangeAsync (/Users/Dave/.config/yarn/global/node_modules/@expo/xdl/node_modules/freeport-async/index.js:33:10)
    at /Users/Dave/.config/yarn/global/node_modules/@expo/xdl/node_modules/freeport-async/index.js:43:18
(node:4996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:4996) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

## Environment

Expo CLI 3.0.4 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react: 5.2.1 => 5.2.1 
      @types/expo: ^32.0.13 => 32.0.13 
      @types/react: ^16.8.25 => 16.9.11 
      @types/react-native: ^0.60.3 => 0.60.22 
      expo: ^35.0.0 => 35.0.1 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.0.4

Also specify:

ios simulator 10.1

## Reproducible Demo

This happens with expo init and a blank project.

**Comment by DaveClissold** [comment]
Have just tested with version 1.1.1 of freeport-async and everything runs as expected.

**Comment by vayovayo** [comment]
I have exactly the same issue, except that dev tools don't even open for me. I've just updated to the latest version of expo-cli and this did not happen before. 

`
(node:3404) UnhandledPromiseRejectionWarning: RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received 65536.
    at Server.listen (net.js:1416:13)
    at /usr/local/lib/node_modules/expo-cli/node_modules/freeport-async/index.js:8:12
    at new Promise (<anonymous>)
    at testPortAsync (/usr/local/lib/node_modules/expo-cli/node_modules/freeport-async/index.js:6:10)
    at availableAsync (/usr/local/lib/node_modules/expo-cli/node_modules/freeport-async/index.js:24:17)
    at Promise (/usr/local/lib/node_modules/expo-cli/node_modules/freeport-async/index.js:37:23)
    at new Promise (<anonymous>)
    at freePortRangeAsync (/usr/local/lib/node_modules/expo-cli/node_modules/freeport-async/index.js:33:10)
    at /usr/local/lib/node_modules/expo-cli/node_modules/freeport-async/index.js:43:18
(node:3404) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3404) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by ahkaneti** [comment]
I have the same issue. I have been trying to fix this for 2 weeks now.

**Comment by brentvatne** [comment]
hey, i will look into this soon, it was likely caused by this pr: https://github.com/expo/freeport-async/pull/3

**Comment by callum-katene** [comment]
Hi, Has any progress been made on this? I can't move forward at all - it's starting to become a major problem. Does anyone know of any workarounds to get past this problem? Downgrading doesn't seem to help.

**Comment by DaveClissold** [comment]
@callum-katene I went into `yarn/global/node_modules/@expo/xdl/node_modules/freeport-async/index.js`  and replaced it with the code from v1.1.1. I know not an ideal solution but until @brentvatne gets time to look at this and pushes a new version, this will resolve it for now

https://github.com/expo/freeport-async/blob/d2adc87de833d63cf64506ec52adca3f1996f476/index.js

```
var net = require('net');

var DEFAULT_PORT_RANGE_START = 11000;

function testPortAsync(port) {
  return new Promise(function (fulfill, reject) {
    var server = net.createServer()
    server.listen(port, function (err) {
      server.once('close', function () {
        setTimeout(() => fulfill(true), 0);
      });
      server.close();
    });
    server.on('error', function (err) {
      setTimeout(() => fulfill(false), 0);
    });
  });
}


function freePortRangeAsync(rangeSize, rangeStart) {
  rangeSize = rangeSize || 1;
  return new Promise(function (fulfill, reject) {
    var lowPort = rangeStart || DEFAULT_PORT_RANGE_START;
    var awaitables = [];
    for (var i = 0; i < rangeSize; i++) {
      awaitables.push(testPortAsync(lowPort + i));
    }
    return Promise.all(awaitables).then(function (results) {
      var ports = [];
      for (var i = 0; i < results.length; i++) {
        if (!results[i]) {
          return freePortRangeAsync(rangeSize, lowPort + rangeSize).then(fulfill, reject);
        }
        ports.push(lowPort + i);
      }
      fulfill(ports);
    });
  });
}

function freePortAsync(rangeStart) {
  return freePortRangeAsync(1, rangeStart).then(function (result) {
    return result[0];
  });
}

module.exports = freePortAsync;

module.exports.availableAsync = testPortAsync;
module.exports.rangeAsync = freePortRangeAsync;
```

**Comment by callum-katene** [comment]
@DaveClissold Thanks, at least I've got a workaround for now.

**Comment by ninuannvarghese** [comment]
Same issue here using expo-cli 3.9.0

**Comment by midhetfatema94** [comment]
Same issue here using expo-cli 3.9.1. I had already initialised the application in another system and pushed it. On pulling, I can't do an `npm start`. Also, if I initialise a new project, the same error occurs. If I use the code given above, I get an error of `getaddrinfo ENOTFOUND localhost`

**Comment by hazwanhz** [comment]
Found out the problem are caused by my hosts file setting where the localhost been setup to different IP not 127.0.0.1

Reset localhost back to 127.0.0.1 fixed my problem from this error

**Comment by midhetfatema94** [comment]
Where do I find the host file settings? How did you resolve this?

**Comment by hazwanhz** [comment]
It's either in C:\Windows\System32\Drivers\etc\hosts (Windows)
Or /etc/hosts

Just make sure there is 127.0.0.1 localhost in the setting. If there is another IP using localhost, just remove it

**Comment by midhetfatema94** [comment]
Modified the `hosts~orig` file, but it didn't work...

**Comment by aedwards12** [comment]
Same issue here using expo-cli 3.9.2

**Comment by midhetfatema94** [comment]
Hi, so I fixed that error. The reason was the my hosts file had gotten corrupted, now its working fine. Check the resolution out (here)[https://github.com/angular/angular-cli/issues/2227#issuecomment-285955502]

**Comment by samohan123** [comment]
It might be coz the **localhost** is not defined with the *required syntax* in the **"hosts"** file of the system.
the file can be located @:

=>            etc/hosts
(above file for ***linux***)
or
=>            c:\ **Windows** \System32\Drivers\ **etc** \ **hosts**
(above file for **Windows**)

i.e. file has some wrong input.

So, Try replacing everything in that file with the text below as this is the default text that was always there in *hosts* file when it worked fine:


127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost 
fe80::1%lo0	localhost

**Comment by DaveClissold** [comment]
@samohan123 Thanks. I didn't notice the final line missing from my hosts file.  

`fe80::1%lo0 localhost`

Can confirm that this fixed for me on OSX 10.13.6 and with the latest expo-cli version 3.11.5

@brentvatne, I would suggest putting a note somewhere in the docs, about checking the hosts file if this issue arrises for others.

**Comment by samohan123** [comment]
> Hi, Has any progress been made on this? I can't move forward at all - it's starting to become a major problem. Does anyone know of any workarounds to get past this problem? Downgrading doesn't seem to help.

https://github.com/expo/expo-cli/issues/1238#issuecomment-572994718

**Comment by nfmshow** [comment]
@samohan123 you are a lifesaver

**Comment by hexiaolong24** [comment]
>cat /etc/hosts 127.0.0.1 localhost

**Comment by qiaork** [comment]
add '127.0.0.1 localhost' to my host, then it works!

**Comment by usmansbk** [comment]
A custom `WEB_HOST` env var was causing this error for for me

**Comment by qiaork** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的邮件我已收到，谢谢！
