### ISSUE TITLE
Reuse existing Chrome tab for dev tools

### ISSUE THREAD

**Issue by fson** [expo/expo-cli#124]
When Chrome is set as the default browser, we should reuse the existing tab instead of opening a new tab. On macOS we could do something like this: https://github.com/facebook/create-react-app/blob/d671b8fb0430d11ebc6f399274bd5f2cfbb1de65/packages/react-dev-utils/openChrome.applescript, but we should also first check if Chrome is the default browser. To detect if Chrome is the default browser, we can do `defaults read ~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure` and find the handler for `LSHandlerURLScheme = http`.

**Comment by imflavio** [comment]
Any update on this feature?

**Comment by methodbox** [comment]
I strongly support this!

I just opened my browser after working for a few hours on an app last night to find my pinned tab (btw you should be sure this also re-uses the pinned tab) plus another 6 tabs opened. Those are just the ones I missed when I put it to sleep last night.

Every time I push a commit I get a new tab. It's pretty annoying.

**Comment by moshfeu** [comment]
Just like the debugger window.
Another sub task, if somehow the process exited, just close the tab.

Thanks!

**Comment by byCedric** [comment]
I would be up to get some work started on this issue! Yesterday I had 29 tabs open 😅... 

To get started I think some guidance is required. E.g. where should the script(s) for this functionality be placed? I noticed [Vue CLI ripped the code from CRA](https://github.com/vuejs/vue-cli/commit/985654943238e80916677fd8487460fdfacefb35) and placed it in a similar spot. I don't think Expo has the same structure right? (a specific `expo-dev-utils` folder). Should it be placed in the `xdl`, `dev-tools`, `expo-cli` or should it be in a new folder named something like `open-dev-tools`?

For now, I think I can start on creating a dedicated script to find the best approach to open the browser (e.g. platform/browser check). After that, I can try to make the default browser check happening?

PS. I think this feature is also a good opportunity to upgrade `opn` to the latest `open` version (it was renamed), but that [requires dropping `node@6` support](https://github.com/expo/expo-cli/issues/457#issuecomment-487370630).

**Comment by byCedric** [comment]
This is now fixed by #565, right? Thanks Evan ❤️
