### ISSUE TITLE
expo init should to be simpler

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#1240]
- `expo init projectname` should work and not prompt for name
- You should not have to provide a slug
- Other things @EvanBacon?

**Comment by fson** [comment]
Yess! 100% agree. Happy to take this on.

**Comment by EvanBacon** [comment]
I'd add the points @fson brought up in here https://github.com/expo/expo-cli/pull/1044 
Would be nice if after this existed, something like `-y` generated the package.json in the folder you ran the command, installed expo, react, react-native, react-native-web, react-dom, and created an App.js. This way we don't have to add `minimum` to the templates.
