### ISSUE TITLE
i can't intsall npm install -g expo-cli

### ISSUE THREAD

**Issue by rajureddy2010** [expo/expo-cli#1248]
at the time of installation iam getting some errors like:
npm WARN npm npm does not support Node.js v12.13.1
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN deprecated joi@14.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.

?////////
but updated npm ....

Let me any one solved the problem and share me the link it's help full for me.
![expocli](https://user-images.githubusercontent.com/13249141/69188826-37d5af80-0b58-11ea-8c30-b410d3796cd6.png)
![npmupdate](https://user-images.githubusercontent.com/13249141/69188827-37d5af80-0b58-11ea-9817-a1238dc12f40.png)

**Comment by luizeduul** [comment]
The same

**Comment by yastrebovb** [comment]
Same

**Comment by Allend13** [comment]
Same

**Comment by redbeard2** [comment]
same ...

**Comment by redbeard2** [comment]
Same

**Comment by rajureddy2010** [comment]
any one solved the issue let me know.share some details about this issue .....   :)

**Comment by redbeard2** [comment]
> any one solved the issue let me know.share some details about this issue ..... :)

I'm working on it to try and figure it out I deleted my system completely I will keep you updated.

**Comment by redbeard2** [comment]
I managed to fix it, but on a despaired way I deleted all my stuff node & npm is broken true the new update... its a fault on node part... 

Delete everything software-wise and go reinstall from scratch... I did go back to a older version of node one who is stable for me v12.12...

**Comment by brentvatne** [comment]
as @redbeard2 pointed out, this appears to be an issue with node/npm itself. probably best to uninstall/reinstall node :)

**Comment by kadaj30** [comment]
i solved this issue by deleting expo and expo-cli files from C:\Users\(PCNAME)\AppData\Roaming\npm

**Comment by taofik-adeniyi** [comment]
if anyone knows how to solve this in ubuntu please help needed

**Comment by luizeduul** [comment]
@taofik-adeniyi  It really helped me a lot. I finally managed to use the expo by doing what you said. Thank you.
