### ISSUE TITLE
expo build:android results in a 500 error

### ISSUE THREAD

**Issue by Kumagor0** [expo/expo-cli#1252]
## Description

Trying to build expo project for android results in a 500 error.

## Expected Behavior

I expected the project to build

## Observed Behavior

```
$ EXPO_DEBUG=true expo build:android
Checking if there is a build in progress...

Request failed with status code 500
Error: Request failed with status code 500
    at createError (/home/gleb/.config/yarn/global/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/gleb/.config/yarn/global/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/gleb/.config/yarn/global/node_modules/axios/lib/adapters/http.js:237:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)```
```

## Environment
  Expo CLI 3.8.0 environment info:
    System:
      OS: Linux 4.15 Ubuntu 16.04.3 LTS (Xenial Xerus)
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 8.13.0 - ~/.nvm/versions/node/v8.13.0/bin/node
      Yarn: 1.19.1 - ~/.yarn/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.13.0/bin/npm
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
    npmPackages:
      @types/expo: ^32.0.10 => 32.0.10 
      @types/react: ^16.8.13 => 16.8.13 
      @types/react-navigation: ^3.0.6 => 3.0.6 
      expo: ^33.0.0 => 33.0.3 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 

## Reproducible Demo

https://github.com/Kumagor0/expo-500-repro/tree/master

## Workaround

Building works if I change slug in app.json to any other value. But I've already built my project with this slug (and even published to Google Play), so I'd very much like to keep building with it.

**Comment by Tuki-M** [comment]
**Same issue here, error 500 when building for android, the response data:**

```
{"err":"Undefined binding(s) detected when compiling FIRST query: select count(\\"id\\") from \\"build_jobs\\" where \\"account_id\\" = ? and \\"priority\\" = ? limit ?.","apiError":false,"code":"SERVER_ERROR"}
```

**Environment:**
Expo CLI 3.8.0
Windows 10

**Complete trace log of response:**

```
{
  status: 500,
  statusText: 'Internal Server Error',
  headers: {
    server: 'openresty/1.15.8.2',
    date: 'Wed, 20 Nov 2019 18:09:24 GMT',
    'content-type': 'application/json; charset=utf-8',
    'content-length': '202',
    connection: 'close',
    'strict-transport-security': 'max-age=31536000; includeSubDomains',
    vary: 'Accept-Encoding, Origin',
    'set-cookie': [
      'ks=s-LsPX3RilTyq-5jLZldDBeQ; path=/; secure; httponly',
      'kb=b-rr7taAm6RU6Cthw7P7SGBA; path=/; expires=Sun, 24 Sep 3015 10:40:00 GMT; secure; httponly',
      'io.expo.auth.currentUser=146aaabd-88c2-4534-baff-afb16e11b93d; path=/; expires=Wed, 15 Jan 2020 18:09:24 GMT; secure; httponly'
    ],
    'x-frame-options': 'SAMEORIGIN',
    'x-content-type-options': 'nosniff'
  },
  config: {
    url: 'https://exp.host/--/api/build/%5B%5D',
    method: 'put',
    data: '{"manifest":{"name":"globo-final","slug":"expo.io/@tukim/globo-release","privacy":"public","sdkVersion":"35.0.0","platforms":["ios","android","web"],"version":"1.0.0","orientation":"portrait","icon":"./assets/icon.png","splash":{"image":"./assets/splash.png","resizeMode":"contain","backgroundColor":"#ffffff"},"updates":{"fallbackToCacheTimeout":0},"assetBundlePatterns":["**/*"],"ios":{"supportsTablet":true,"bundleIdentifier":"com.globomantics.globofinal"},"android":{"package":"com.globomantics.globofinal"}},"options":{"mode":"status","platform":"android","current":true,"releaseChannel":"default","sdkVersion":"35.0.0"}}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json;charset=utf-8',
      'Exp-ClientId': 'c-B0YFG0ATT1eMIUnRo8JSpw',
      'Exponent-Client': '3.8.0',
      'Expo-Session': '{"id":"f47beb72-1259-44a6-bc87-a6f1c1d2c8e9","version":1,"expires_at":1893456000000}',
      'User-Agent': 'axios/0.19.0',
      'Content-Length': 626
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: 104857600,
    validateStatus: [Function: validateStatus]
  },
  request: ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function],
      abort: [Function],
      aborted: [Function],
      error: [Function],
      timeout: [Function],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 6,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      _SNICallback: null,
      servername: 'exp.host',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'exp.host',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular],
      [Symbol(res)]: [TLSWrap],
      [Symbol(asyncId)]: 201,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    connection: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      _SNICallback: null,
      servername: 'exp.host',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'exp.host',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular],
      [Symbol(res)]: [TLSWrap],
      [Symbol(asyncId)]: 201,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'PUT /--/api/build/%5B%5D HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json;charset=utf-8\r\n' +
      'Exp-ClientId: c-B0YFG0ATT1eMIUnRo8JSpw\r\n' +
      'Exponent-Client: 3.8.0\r\n' +
      'Expo-Session: {"id":"f47beb72-1259-44a6-bc87-a6f1c1d2c8e9","version":1,"expires_at":1893456000000}\r\n' +
      'User-Agent: axios/0.19.0\r\n' +
      'Content-Length: 626\r\n' +
      'Host: exp.host\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      maxCachedSessions: 100,
      _sessionCache: [Object]
    },
    socketPath: undefined,
    method: 'PUT',
    path: '/--/api/build/%5B%5D',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      connection: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 500,
      statusMessage: 'Internal Server Error',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular],
      responseUrl: 'https://exp.host/--/api/build/%5B%5D',
      redirects: []
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    _redirectable: Writable {
      _writableState: [WritableState],
      writable: true,
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 626,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function],
      _currentRequest: [Circular],
      _currentUrl: 'https://exp.host/--/api/build/%5B%5D'
    },
    [Symbol(kNeedDrain)]: false,
    [Symbol(isCorked)]: false,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      'exp-clientid': [Array],
      'exponent-client': [Array],
      'expo-session': [Array],
      'user-agent': [Array],
      'content-length': [Array],
      host: [Array]
    }
  },
  data: '{"err":"Undefined binding(s) detected when compiling FIRST query: select count(\\"id\\") from \\"build_jobs\\" where \\"account_id\\" = ? and \\"priority\\" = ? limit ?.","apiError":false,"code":"SERVER_ERROR"}'
}
```

**Comment by tcdavis** [comment]
Thanks for the great reports! 
I'm not able to reproduce.  Can you verify if you still have the issue?

**Comment by jkhales** [comment]
Also it maybe that your expo-cli install is finicky. Try using `npx expo-cli` to check if the problem is just with your install.

**Comment by Tuki-M** [comment]
In my case everything seems to be ok now, I have the same issue but with more info about the raison, which seems to be => the 'slug' field validation regex, (yesterday i did not had this message in red, weirdo) :
![image](https://user-images.githubusercontent.com/37219596/69324116-2966c100-0c48-11ea-9524-4b854cca08d6.png)

Which refer to :
![image](https://user-images.githubusercontent.com/37219596/69325586-ad21ad00-0c4a-11ea-8222-28499cb429b4.png)

`npx expo-cli` looks fine

@jkhales & @tcdavis Thanks guys ^^

**Comment by Kumagor0** [comment]
@tcdavis Yeah, still 500 for me. Since reproduction depends on the slug, it might as well depend on account.

Here's what I found so far: error happens in request [here](https://github.com/expo/expo-cli/blob/master/packages/xdl/src/Api.ts#L103) with the following data:

```
{
    url: 'https://exp.host/--/api/getCredentials/%5B%5D',
    method: 'post',
    headers: {
      'Exp-ClientId': 'c-Yt8zsbbuQqGSJL_mkMcf9w',
      'Exponent-Client': '3.8.0',
      'Expo-Session':
        '{"id":"5a841ae9-557a-453f-a005-6c46a09ec04c","version":1,"expires_at":1893456000000}',
    },
    maxContentLength: 104857600,
    data: {
      username: 'kumagoro',
      experienceName: '@kumagoro/magic-piano',
      bundleIdentifier: undefined,
      platform: 'android',
      decrypt: false,
    },
  }
```

If I change experienceName to anything else, for example, '@kumagoro/magic-piano-2', error doesn't happen. Hope this info might help you pinpoint the problem.

P.S. I've tried to register new expo.io account and build repro with it without changing slug and it worked, so the problem seems to be actually account-related. I mean, account+slug related.

**Comment by tcdavis** [comment]
@Kumagor0 I've added some additional logging to our backend.  Would you please run the problematic account/slug again?

**Comment by jkhales** [comment]
We pushed expo-cli@3.9.0 just now. Would you see if the issue still persists after upgrading?

**Comment by Kumagor0** [comment]
@tcdavis I have just did, last time less than a minute before posting this comment.

@jkhales unfortunately it does.

**Comment by quinlanj** [comment]
hey @Kumagor0 , i took a look at your error and it looks like the android keystore credentials that you have stored under `magic-piano` were not uploaded correctly. If you could update your android credentials for that project, the error should be resolved. You can do this by going to your project directory and running `expo credentials:manager -p android`

lmk if this works for you!

**Comment by axador** [comment]
I had different names in "name" and "slug" fields. And when I set up one name for both fields, my build was pushed to expo. May be it will help you.

**Comment by Kumagor0** [comment]
@quinlanj I ran into the following error:

```
$ expo credentials:manager -p android
? You are currently in a directory with @kumagoro/magic-piano experience. Do you want to select it? Yes
{ ApiV2Error: An unknown error occurred.
    at ApiV2Client._requestAsync (/@expo/xdl@57.0.2/src/ApiV2.ts:182:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  code: 'INTERNAL_SERVER_ERROR',
  details: undefined,
  serverStack: undefined,
  _isApiError: true }
? Do you want to quit Credential Manager Quit Credential Manager
```

**Comment by JorgeMoralesLopez** [comment]
I am having the same problem and I don't know how to solve it.
A couple of weeks ago I compiled and there was no problem.
Help please!

**Comment by brentvatne** [comment]
@Kumagor0 @JorgeMoralesLopez - can you send your build info and any other relevant details to secure@expo.io?

**Comment by JorgeMoralesLopez** [comment]
@brentvatne I have already sent it to secure@expo.io. Thank you

**Comment by Kumagor0** [comment]
@brentvatne You mean everything I have already posted in this issue? Because I'm not quite sure what else can be relevant.

**Comment by wkozyra95** [comment]
@Kumagor0 your credentials were mangled somehow (empty string) I removed it manually from db. Currently uploading them with `build` command or `credentials:manager` should work.

@JorgeMoralesLopez what is your username on expo?

**Comment by JorgeMoralesLopez** [comment]
@Kumagor0, my username on expo is jorgem

**Comment by Kumagor0** [comment]
@wkozyra95 this has resolved my problem, thank you! Should it ever arise again, should I open another issue, comment in this one, or is there some more appropriate way to report it?

**Comment by wkozyra95** [comment]
@Kumagor0 I'll add some checks to `expo-cli`, so cleaning credentials should work even if there is something wrong with existing ones, but if sth similar happens yes please file separate issue.

@JorgeMoralesLopez are you sure that it's the same problem? If you are sure you can clean credentials with `expo build:android -c`, if not please provide output of expo cli when building and any relevant information

**Comment by JorgeMoralesLopez** [comment]
@wkozyra95 
with expo build:android -t apk
jorge@jorge-PE60-6QE:~/Projects/LE/LE_expo_firestore/le-firestore-1-sdk35-rNav4-reduxV6$ expo build:android -t apk
Checking if there is a build in progress...

Publishing to channel 'default'...
Building iOS bundle
Building Android bundle
Analyzing assets
Uploading assets
Uploading /assets/fakeSwipe2.png
Processing asset bundle patterns:
- /home/jorge/Projects/LE/LE_expo_firestore/le-firestore-1-sdk35-rNav4-reduxV6/**/*
Uploading JavaScript bundles
Request failed with status code 500
Set EXPO_DEBUG=true in your env to view the stack trace.
jorge@jorge-PE60-6QE:~/Projects/LE/LE_expo_firestore/le-firestore-1-sdk35-rNav4-reduxV6$ expo build:android -t apk
^C
jorge@jorge-PE60-6QE:~/Projects/LE/LE_expo_firestore/le-firestore-1-sdk35-rNav4-reduxV6$ export EXPO_DEBUG=true
jorge@jorge-PE60-6QE:~/Projects/LE/LE_expo_firestore/le-firestore-1-sdk35-rNav4-reduxV6$ expo build:android -t apk
Checking if there is a build in progress...

Publishing to channel 'default'...
Building iOS bundle
Building Android bundle
Analyzing assets
Uploading assets
No assets changed, skipped.
Processing asset bundle patterns:
- /home/jorge/Projects/LE/LE_expo_firestore/le-firestore-1-sdk35-rNav4-reduxV6/**/*
Uploading JavaScript bundles
Request failed with status code 500
Error: Request failed with status code 500
    at createError (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
jorge@jorge-PE60-6QE:~/Projects/LE/LE_expo_firestore/le-firestore-1-sdk35-rNav4-reduxV6$

**Comment by wkozyra95** [comment]
@JorgeMoralesLopez in your case publish is failing, it's unrelated to credentials. I'll look into that more, but if you need it to be fixed fast, the fastest way is to change slug. If you already uploaded apk to playstore remember that you need to use the same credentials.

**Comment by JorgeMoralesLopez** [comment]
@wkozyra95 I have uploaded the app to google play as a test and to TestFlight by ios. if I change the slug would have problems on these platforms?

**Comment by wkozyra95** [comment]
slug doesn't matter for actual store uploads (only bundle identifier on ios and package name for android), but publishes from new slug won't update existing application (via OTA updates). On ios you can generate new credentials or use the old ones, but on android you need the same keystore you used last time.

**Comment by JorgeMoralesLopez** [comment]
@wkozyra95  Ok, then I'll try to create a new .apk and a .ipa and I'll change the slug to see if it works. By the way I would also like to change the name of the project, does this influence anything?
Thank you!!!!

**Comment by jkhales** [comment]
@JorgeMoralesLopez Would you mind seeing if it works with your desired slug now? It seems like there was a stale cache issue.

**Comment by JorgeMoralesLopez** [comment]
@jkhales It already works, I was able to compile with the slug I had.
Thank you!

**Comment by brentvatne** [comment]
it sounds like this has been resolved, thanks @wkozyra95 and @jkhales!

**Comment by JorgeMoralesLopez** [comment]
338/5000
Yesterday I compiled .aab to upload to google play and they tell me this: Your Android App Bundle is signed with the wrong password. Make sure it is signed with the correct signature key and try again. SHA1: 42: 9F ...
I have not done anything that is different from other previous compilations. Do you know why this happens and how can I solve it?
Thank you!

**Comment by wkozyra95** [comment]
You need to use the same keystore you used for the first upload. If you have old keystore, run `expo build:android -c` and provide manually all the data, if not you will need to contact google support team to reset your upload keystore. They will need public key from your new keystore to do that, run `expo fetch:android:upload-cert` to get it.

**Comment by JorgeMoralesLopez** [comment]
@wkozyra95 Thanks for your quick response ... I have already uploaded a lot of versions and at the beginning I let expo handle the keys and I never had problems. Why now would you have to enter the data by hand? And how do I know if I have the old keystore available and where?

**Comment by wkozyra95** [comment]
If you have this error that means you cleared credentials in the past with `expo build:android -c` and expo generated new ones (different than play store expects).

**Comment by JorgeMoralesLopez** [comment]
I have not executed expo build: android - c, I have always executed expo build: android -t apk to be able to install an apk on my physical device and expo build: android -t app-bundle to upload version to google play.

**Comment by wkozyra95** [comment]
your credentials were updated on 2019-11-28 20:56:21.460024+00 (the same date you first posted on this issue). There is no other way to modify credentials other than with `-c` flag

`SHA1: 42: 9F: 65: 36: 9D: EC: 7C: 70 ` is a fragment of fingerprint for a public key, basically error message tells you that fingerprint is different than expected because it was signed with the different private key

**Comment by JorgeMoralesLopez** [comment]
@wkozyra95 Thanks, I will see how I can solve it and I will contact Google
