### ISSUE TITLE
Remove `-p` option in `expo login`, use a token env var instead

### ISSUE THREAD

**Issue by sjchmiela** [expo/expo-cli#126]
<table><tr><td>🚧</td><td>Moved from <a href="https://github.com/expo/expo/issues/172">https://github.com/expo/expo/issues/172</a></td></tr></table>
Currently not passing a password to `exp login` via `--password` in non-interactive mode throws an error: <a href="https://github.com/expo/exp/blob/1a89b83ba9ee921a4feabb4dc060271c40abbeea/src/accounts.js#L82-L89">https://github.com/expo/exp/blob/1a89b83ba9ee921a4feabb4dc060271c40abbeea/src/accounts.js#L82-L89</a>

So instead of the `--password`  (`-p`) option, we should change it to look for `EXPO_CLI_PASSWORD` env variable and remove the `--password` option from the CLI.

`EXPO_CLI_PASSWORD` needs to be added to the [blacklist](https://github.com/expo/xdl/blob/a67d52482e6246250d4e22ed2d95e0965c9310d6/src/Project.js#L1236) in xdl, so it's never exposed in the manifest of the development server.

**Comment by epicfaace** [comment]
@sjchmiela Are you sure we want to move the `-p` option from the CLI altogether?

**Comment by sjchmiela** [comment]
I'm not sure, this issue has been open for quite a while, so maybe the reasoning behind it is outdated. 🤷‍♂️ @fson will be the one to ask. 🙂

**Comment by fson** [comment]
We should also remove the `-p, --password` option from `expo init`, because it encourages writing the password in build scripts in plain (as opposed to using environment variables, which are the way to store secrets in many CI services).

**Comment by epicfaace** [comment]
@fson Are you sure? Wouldn't that break existing build scripts? What process does Expo have to make sure people are fully aware of backwards-compatible changes?

**Comment by EvanBacon** [comment]
https://github.com/expo/expo-cli/pull/2658#issuecomment-693578458
