### ISSUE TITLE
ERROR ITMS-90725: "SDK Version Issue. This app was built with the iOS SDK. All iOS apps submitted to the App Store must be built with the iOS 11 SDK or later, included in Xcode 9 or later.

### ISSUE THREAD

**Issue by spyshower** [expo/expo-cli#1263]
## Description

I am trying to upload a new of my app to Apple Store Connect (for beta apps) using the new Transporter tool (instead of the one in Xcode that got removed). I used `expo build:ios` to get the `.ipa`

However, I get this error:

ERROR ITMS-90725: "SDK Version Issue. This app was built with the iOS SDK. All iOS apps submitted to the App Store must be built with the iOS 11 SDK or later, included in Xcode 9 or later. Further, starting March 2019, all iOS apps submitted to the App Store must be built with the iOS 12.1 SDK or later, included in Xcode 10.1 or later."

## Expected Behavior

Shouldn't have gotten this error, as past uploads worked fine.

## Environment

Expo CLI 3.9.0 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.13.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.1 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.9.0

**Comment by spyshower** [comment]
I fixed by downgrading to 3.8.1

**Comment by brentvatne** [comment]
not sure what would have happened here, there is actually no difference between 3.8.1 and 3.9.0 except that the dependency on @expo/xdl is locked so it won't be automatically updated with future @expo/xdl releases. so it must have been some intermittent issue, perhaps on apple's side
