### ISSUE TITLE
Expo server dos not start

### ISSUE THREAD

**Issue by amira133** [expo/expo-cli#1264]
Hello, I am new in react native.
after create a project with `expo init AwesomeProject` I can't start that project without any errors.

when I use `expo start` it shows below code and then my browser closed.
`expo start
Starting project at C:\ReactNative Projects\AwesomeProject
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Starting Metro Bundler on port 19001.
Tunnel ready.`

Some one can help me why my project does't start or why my browser closed?
Thanks ...

OS = windows 10
npm version = 6.12.1
expo Version = 3.9.0
Browser : Chorom , firefox

**Comment by brentvatne** [comment]
hi! it's unclear what your issue is exactly. what do you mean your browser closed? it opens and closes? do you see an error in the terminal?

it might be best to post questions to https://forums.expo.io/ until you are sure that you have found a bug :) thanks!

**Comment by amira133** [comment]
Thanks for answer.
when `expo start` called , then browser start automatically to show Expo server, but after a time browser crashed and closed. 
there is no error to show me.
