### ISSUE TITLE
How to generate 404 page in web

### ISSUE THREAD

**Issue by chayancbnits** [expo/expo-cli#1271]
How to generate 404 page ( Not found ) in the web, I am using Expo SDK 35 and expo-cli version 3.9.1

**Comment by luisrivas** [comment]
Hi @chayancbnits , I think you need a router to handle the web navigation flow, so can try https://reacttraining.com/react-router/web/

**Comment by EvanBacon** [comment]
Ideally you'd want to use a router for this. Optionally you can use the Expo SDK with other tools like Gatsby or Next.js which have more mature ways of handling 404 at the moment. Here is an example Expo Gatsby project that has support for a [404 page](https://github.com/expo/examples/blob/master/with-gatsby/src/pages/404.tsx): [Expo with Gatsby](https://github.com/expo/examples/tree/master/with-gatsby/)
