### ISSUE TITLE
i have this error message when running expo. plz help me fix this 

### ISSUE THREAD

**Issue by aboudi619** [expo/expo-cli#1274]
Starting project at C:\Users\abdullah\New
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class. Run CLI with --verbose flag for more details.

Metro Bundler process exited with code 1
Set EXPO_DEBUG=true in your env to view the stack trace.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `expo start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abdullah\AppData\Roaming\npm-cache\_logs\2019-11-27T19_10_08_705Z-debug.log

**Comment by brentvatne** [comment]
see the solutions in https://github.com/expo/expo-cli/issues/1074

this is a bug with node and metro
