### ISSUE TITLE
Getting Error from Build Command "next build"

### ISSUE THREAD

**Issue by chayancbnits** [expo/expo-cli#1280]
I am using Next.js v9.1.4, Expo SDK 35, Expo-CLI 3.9.1

Creating an optimized production build  

Failed to compile.

./node_modules/react-native/Libraries/Animated/src/components/AnimatedImage.js
Module not found: Can't resolve '../../../Image/Image' in '/node_modules/react-native/Libraries/Animated/src/components'

> Build error occurred
Error: > Build failed because of webpack errors
    at build (/home/nits/.nvm/versions/node/v12.13.0/lib/node_modules/next/dist/build/index.js:9:900)

Referred Link [https://docs.expo.io/versions/latest/guides/using-nextjs/](https://docs.expo.io/versions/latest/guides/using-nextjs/)

**Comment by EvanBacon** [comment]
Please refer to the unversioned docs https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/guides/using-nextjs.md

**Comment by brentvatne** [comment]
closing because inactivity and because i believe a good way to integrate with next is described well in the docs
