### ISSUE TITLE
Installation failing for 3.8.0+

### ISSUE THREAD

**Issue by mdwoodruff2** [expo/expo-cli#1284]
## Description

Install seems to fail after some recent updates. All versions up to 3.7.1 seem to install correctly.

## Expected Behavior

I would expect the install to be successful. 

## Observed Behavior

npm install --global expo-cli@3.7.1 (Success)
npm install --global expo-cli@3.8.0 (Fails)
npm install --global expo-cli (Fails)

```
> test -d .git && cp gitHookPrePush.sh .git/hooks/pre-push || true

'test' is not recognized as an internal or external command,
operable program or batch file.
'true' is not recognized as an internal or external command,
operable program or batch file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-darwin-ia32@2.2.8 (node_modules\expo-cli\node_modules\@expo\ngrok-bin-darwin-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-darwin-ia32@2.2.8: wanted {"os":"darwin","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-freebsd-ia32@2.2.8 (node_modules\expo-cli\node_modules\@expo\ngrok-bin-freebsd-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-freebsd-ia32@2.2.8: wanted {"os":"freebsd","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-darwin-x64@2.2.8 (node_modules\expo-cli\node_modules\@expo\ngrok-bin-darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-darwin-x64@2.2.8: wanted {"os":"darwin","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-freebsd-x64@2.2.8 (node_modules\expo-cli\node_modules\@expo\ngrok-bin-freebsd-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-freebsd-x64@2.2.8: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/traveling-fastlane-darwin@1.10.0 (node_modules\expo-cli\node_modules\@expo\traveling-fastlane-darwin):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/traveling-fastlane-darwin@1.10.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\expo-cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-win32-ia32@2.2.8-beta.1 (node_modules\expo-cli\node_modules\@expo\ngrok-bin-win32-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-win32-ia32@2.2.8-beta.1: wanted {"os":"win32","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-sunos-x64@2.2.8 (node_modules\expo-cli\node_modules\@expo\ngrok-bin-sunos-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-sunos-x64@2.2.8: wanted {"os":"sunos","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-linux-x64@2.2.8 (node_modules\expo-cli\node_modules\@expo\ngrok-bin-linux-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-linux-x64@2.2.8: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-linux-ia32@2.2.8 (node_modules\expo-cli\node_modules\@expo\ngrok-bin-linux-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-linux-ia32@2.2.8: wanted {"os":"linux","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-linux-arm64@2.2.8 (node_modules\expo-cli\node_modules\@expo\ngrok-bin-linux-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-linux-arm64@2.2.8: wanted {"os":"linux","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-linux-arm@2.2.8 (node_modules\expo-cli\node_modules\@expo\ngrok-bin-linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-linux-arm@2.2.8: wanted {"os":"linux","arch":"arm"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! envsub@3.1.0 postinstall: `test -d .git && cp gitHookPrePush.sh .git/hooks/pre-push || true`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the envsub@3.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

## Environment

  Expo CLI 3.7.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312

## Reproducible Demo

npm install --global expo-cli

**Comment by mpcen** [comment]
Same issue here.

Windows 10, using latest Node LTS

**Comment by mpcen** [comment]
Was having this same issue when using Windows Powershell or CMD.exe. Was able to get passed it by using Git Bash. Try running npm install -g expo-cli from a MINGW64 terminal (ex: Git Bash)

**Comment by bandcult** [comment]
+ 1.  Confirmed that the same issue happens for me when running npm install -g expo-cli.

**Comment by hodgef** [comment]
Indeed, expo-cli 3.9.1 won't install on Windows.

![image](https://user-images.githubusercontent.com/25509135/69909502-dddfb000-13c9-11ea-8439-c5a20cf26073.png)

It likely failing due to the `cp gitHookPrepush.sh` part, as there's no `cp` command in Windows.

Hopefully CI testing can be expanded, as CircleCI is just set up to test on Ubuntu: https://circleci.com/gh/expo/expo-cli/tree/master

**Comment by davidroyo** [comment]
This issue is real, tomorrow i got an interview using react native (expo) and couldn't install it. I'm fucked, hope anyone can fix this pls

**Comment by davidroyo** [comment]
> Was having this same issue when using Windows Powershell or CMD.exe. Was able to get passed it by using Git Bash. Try running npm install -g expo-cli from a MINGW64 terminal (ex: Git Bash)

Thx bro, you saved my interview, worked for me

**Comment by arsath-thariq** [comment]
> Was having this same issue when using Windows Powershell or CMD.exe. Was able to get passed it by using Git Bash. Try running npm install -g expo-cli from a MINGW64 terminal (ex: Git Bash)

not working installation having issue again

**Comment by arsath-thariq** [comment]
i am install node js latest version and iam trying to install react Native but its not working kindly help me to solve the issue

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! envsub@3.1.0 postinstall: `test -d .git && cp gitHookPrePush.sh .git/ho
ks/pre-push || true`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the envsub@3.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ing output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\thariq\AppData\Roaming\npm-cache\_logs\2019-12-03T05_38_23
984Z-debug.log

**Comment by jass1121** [comment]
> Was having this same issue when using Windows Powershell or CMD.exe. Was able to get passed it by using Git Bash. Try running npm install -g expo-cli from a MINGW64 terminal (ex: Git Bash)

Thanx Brother Its Working you Saved my Life

**Comment by guy-patrick** [comment]
Thanks soooooo much. Its now working.

**Comment by akewlguy4eva** [comment]
Thanks Also , Thought I was screwed unless I bought a linux machine. :)

**Comment by vitorbertolucci** [comment]
Thank you, I was having the same issue but was able to install using git bash

**Comment by ciruz** [comment]
thank you @mpcen

**Comment by nebmesemaou** [comment]
> Was having this same issue when using Windows Powershell or CMD.exe. Was able to get past it by using Git Bash. Try running npm install -g expo-cli from a MINGW64 terminal (ex: Git Bash)

worked for me thx. with running C:\Program Files\Git\git-bash.exe

**Comment by kasraouimouad** [comment]
> Was having this same issue when using Windows Powershell or CMD.exe. Was able to get past it by using Git Bash. Try running npm install -g expo-cli from a MINGW64 terminal (ex: Git Bash)

the install work , but in cmd the command expo doesn't known

**Comment by rusty-jnr** [comment]
> Was having this same issue when using Windows Powershell or CMD.exe. Was able to get past it by using Git Bash. Try running npm install -g expo-cli from a MINGW64 terminal (ex: Git Bash)

Thanks a lot it installed successfully

**Comment by brentvatne** [comment]
this should be resolved on 3.10.2. the issue was that `@expo/build-tools` was installing a library called `envsub` that would fail on windows 10 in powershell/cmd.exe, so we switched that to an optional dependency - you will still see that `envsub` failed to install but the installation of expo-cli should succeed. we're going to consider breaking `@expo/build-tools` and similar functionality into a separate cli tool to avoid issues like this in the future.

**Comment by gauravsahu8691** [comment]
> 
> 
> Indeed, expo-cli 3.9.1 won't install on Windows.
> 
> ![image](https://user-images.githubusercontent.com/25509135/69909502-dddfb000-13c9-11ea-8439-c5a20cf26073.png)
> 
> Hopefully CI testing can be expanded, as the builds are only tested on Ubuntu at the moment: https://circleci.com/gh/expo/expo-cli/tree/master
> 
> Edit: Seems to have been proposed by @brentvatne in #1260

https://github.com/facebook/react-native/issues/26575#issuecomment-589450778 resolved the problem

**Comment by NithyashreeChandrasekar** [comment]
cp -R node_modules_patches/ node_modules/
'cp' is not recognized as an internal or external command,
operable program or batch file.
