### ISSUE TITLE
upload:ios complains about missing EXPO_APPLE_ID instead of prompting for Apple credentials

### ISSUE THREAD

**Issue by damienix** [expo/expo-cli#1286]
## Description

After upgrading to Expo Cli 3.7.1 upload:ios starts complaining about missing EXPO_APPLE_ID.

Reference: https://forums.expo.io/t/unable-to-expo-build-ios/30236/16

## Expected Behavior

When uploading an artifact, Expo Cli asks me to log-in to apple account as in the 3.6.0 and earlier versions - similar to building an artifact.

## Observed Behavior

After downloading an artifact, the following error is shown:

```
Failed to upload the standalone app to the app store.
GetEnv.Nonexistent: EXPO_APPLE_ID does not exist and no fallback value provided.
```

## Environment

expo-cli 3.7.1 and above (haven't tried 3.7.0).

```
  Expo CLI 3.9.1 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.13.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.23 => 16.9.3
      @types/react-native: ^0.57.65 => 0.57.65
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
    npmGlobalPackages:
      expo-cli: 3.9.1

```

**Comment by faoiseamh** [comment]
What's the recommended workaround for this for now?

**Comment by dsokal** [comment]
@faoiseamh the workaround is to set `EXPO_APPLE_ID` and `EXPO_APPLE_PASSWORD` env variables.
`EXPO_APPLE_ID=YOUR_APPLE_ID_HERE EXPO_APPLE_PASSWORD=YOUR_PASSWORD_HERE expo upload:ios`

**Comment by tafelito** [comment]
this is still happening even after I updated to expo-cli `3.11.1` and expo `36`

**Comment by dsokal** [comment]
Sorry, but the fix has been released yet. It will be included in the upcoming version of expo-cli.
