### ISSUE TITLE
ISSUE IN DURING STARTING ONWARDS EXPO CLI

### ISSUE THREAD

**Issue by arsath-thariq** [expo/expo-cli#1290]
npm ERR! path C:\Users\thariq\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@babel\core\node_modules\minimist
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\thariq\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@babel\core\node_modules\minimist' -> 'C:\Users\thariq\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@babel\core\node_modules\.minimist.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
THIS IS ERROR DURING INSTALLATION PLEASE CHECK UPDATE GUYS

**Comment by brentvatne** [comment]
```
npm uninstall -g expo-cli
npm install -g expo-cli
```

give that a go. create a new issue if this doesn't work and provide the information that is requested in the template :)
