### ISSUE TITLE
expo client:ios command throwing 'bundleIdentifier required' error in expo-cli@3.9.1

### ISSUE THREAD

**Issue by alexandermckay** [expo/expo-cli#1295]
## Description

After upgrading from expo-cli@3.4.1 to expo-cli@3.9.1 I am unable to create a custom ios dev build. I have tried building the custom expo client both in a directory that contains an `app.json` file with a `ios: { bundleIdentifier: '...' }` key, as well as in a directory without an`app.json` file, both fail. Reverting to version 3.4.1 eliminates the error for me.

My first port of call was the documentation, specifically [this page](https://docs.expo.io/versions/v35.0.0/guides/adhoc-builds/), however there is no mention of a `bundleIdentifer` requirement, leading me to suspect this is an error, rather than oversight on my part.

## Expected Behavior

Ran `expo client:ios`
Expected build to begin on expo servers

## Observed Behavior

Running `expo client:ios` throws the following error:

```
"bundleIdentifier" is required.
```

Running the command from a directory with an `app.json` file with a `bundleIdentifier` has no visible effect.

## Reproducible Demo

- `yarn global add expo-cli@3.9.1`
- `expo client:ios`
- Error thrown after prompt: `Would you like to register a new device to use the Expo Client with?`

**Comment by quinlanj** [comment]
hi @alexandermckay , could you upgrade to expo-cli@3.9.2 and see if that solves your issue? It's probably related to https://forums.expo.io/t/blocker-expo-custom-client-ios-builds-failing/30343/10

**Comment by brentvatne** [comment]
i can't reproduce this on the latest expo-cli, i believe it should be resolved. if not, let me know and i will reopen the issue
