### ISSUE TITLE
Incorrect password escape on Windows

### ISSUE THREAD

**Issue by AdamJNavarro** [expo/expo-cli#130]
## Description

When the password contains a special character, the CLI may not escape the password correctly in a Windows environment.

## Expected Behavior

expo build:ios results in an error while gathering & validating credentials.

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the _full terminal output and error message_ in this code block:

```
Reason:Invalid credentials, raw:“Invalid username and password combination. Used ‘XXXXX’ as the username.”
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

Also specify:

- Phone/emulator/simulator platform, model and version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

Relevant Forum Post: https://forums.expo.io/t/build-ios-not-working-on-windows-invalid-credentials/15385

**Comment by JoelRummel** [comment]
Any update? I had to change my Apple ID password because of this.
