### ISSUE TITLE
Update Next in dev-tools

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#1302]
It currently uses Next 5, which is on Babel 6 and React 16.2. Sad times.

**Comment by EvanBacon** [comment]
Just putting it out there but react-native-web is faster than emotion https://necolas.github.io/react-native-web/benchmarks/

**Comment by brentvatne** [comment]
That also seems like a reasonable option but I'm hesitant to spend more time than necessary on upgrading this.
