### ISSUE TITLE
Expo client unable to open app after Xcode update 11.2.1

### ISSUE THREAD

**Issue by iamsuneeth** [expo/expo-cli#1309]
## Description

After updating Xcode to version 11.2.1 , Expo client fails to open app in iOS simulator. It works properly on Android device. The error message received is given below.

```
Error: Cannot resolve entry file: The `main` field defined in your `package.json` points to a non-existent path.
    at getEntryPointWithExtensions (/Users/username/.config/yarn/global/node_modules/@expo/config/src/paths/paths.ts:88:17)
    at getEntryPoint (/Users/username/.config/yarn/global/node_modules/@expo/config/src/paths/paths.ts:52:10)
    at Object.determineEntryPoint (/@expo/xdl@57.1.2/src/Exp.ts:36:17)
    at manifestHandler (/@expo/xdl@57.1.2/src/Project.ts:1924:28)
```
Environment

Expo CLI 3.10.2 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.12.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      @testing-library/react-native: ^5.0.0 => 5.0.0 
      @types/react: ^16.8.23 => 16.9.11 
      @types/react-native: ^0.57.65 => 0.57.65 
      expo: ^35.0.0 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.10 => 4.0.10

Simulator:
iPhone 11  running iOS 13.2.2

**Comment by brentvatne** [comment]
this is strange because this error would be unrelated to the platform (ios/android) unless your project is configured in some non-standard way. we'll need more information on your project. also, i imagine if you create a new project this works as expected? if so, please create a minimal reproducible example (https://stackoverflow.com/help/mcve)

**Comment by iamsuneeth** [comment]
Thanks for the reply @brentvatne. I confirm that it is working as expected with new projects. I will try moving my project files to a new expo project and see if I can reproduce this issue.

**Comment by iamsuneeth** [comment]
I found the issue. The issue was with main field defined in package.json. instead of 
`"main": "node_modules/expo/AppEntry.js"`
it was 
`"main": "AppEntry.js",`

**Comment by EvanBacon** [comment]
Quick reminder that expo CLI will auto assume the main field is node_modules/expo/AppEntry if expo is installed and there is no index.js in the root folder. So technically you can delete the field when using Expo
