### ISSUE TITLE
Expo Next Not working with vectors icons

### ISSUE THREAD

**Issue by ghmeec** [expo/expo-cli#1310]
##Description

Tried to use expo-next project with @expo/vector-icons', with the following code

import React from 'react'
import {View,Text} from 'react-native'
import { Ionicons } from '@expo/vector-icons';
export default function(){
    return(
        <View>
            <Text>The Ocean</Text>
            <Ionicons name="md-checkmark-circle" size={32} color="green" />
        </View>
    )
}

## Expected Behavior

Expected to display the Icon

## Observed Behavior
Error
```
[ error ] ./node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/FontAwesome5_Brands.ttf 1:0
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```

## Environment

 Expo CLI 3.10.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 10.16.1 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.10.2

**Comment by brentvatne** [comment]
you can follow this guide for that for now: https://github.com/expo/expo/blob/c52eb6272fa406766bc654f6ce64bd1f79840192/docs/pages/versions/unversioned/guides/using-nextjs.md#font-support

these docs aren't released yet but will be soon

**Comment by Slapbox** [comment]
@brentvatne I'm seeing the same error but with a `.wasm` file. I can't just exclude the `.wasm`  with `blacklistRE` because a `.js` file is looking for it and then I get, "Unable to result path/to/file.wasm`"

This wasn't an issue a couple months back with the same files and configuration. Any ideas? 

We're on:

- `expo-cli@3.11.1`
- `node@12` (upgraded from `node@10` since last known working)
