### ISSUE TITLE
push:web:generate: There is no PUT API endpoint at this URL.

### ISSUE THREAD

**Issue by jaulz** [expo/expo-cli#1316]
## Description

`expo push:web:generate --vapid-subject test@example.com` (as described [here](https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/guides/using-vapid.md)) fails with the following result:
```
Reading project configuration...
Logging in...
Generating and setting VAPID keys on Expo's servers...
There is no PUT API endpoint at this URL.
```
## Expected Behavior

The VAPID keys should be generated.

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the _full terminal output and error message_ in this code block:

```
Reading project configuration...
Logging in...
Generating and setting VAPID keys on Expo's servers...
There is no PUT API endpoint at this URL.
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:
````
  Expo CLI 3.10.2 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      Yarn: 1.19.2 - ~/.yarn/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.2/11B52 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.9.13 => 16.9.13 
      @types/react-native: ^0.60.23 => 0.60.23 
      expo: ^35.0.0 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.12.1 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.10.2
````

Also specify:

- Phone/emulator/simulator platform, model and version: n/a

## Reproducible Demo

n/a

**Comment by EvanBacon** [comment]
Thanks for the report, will investigate.

**Comment by jaulz** [comment]
Also, I get this error:
```
Error: Problem validating fields in app.json. See https://docs.expo.io/versions/v36.0.0/workflow/configuration/
 • Field: notification - should NOT have additional property 'vapidPublicKey'."
```

Could this be related?

**Comment by EvanBacon** [comment]
The feature of web push notifications doesn't exist, the docs were published in error.

**Comment by jaulz** [comment]
Oh, sad to hear. Will this still be integrated at some point of time?

**Comment by BenoitFroment** [comment]
Could you be precise about a release date? This is key feature to choose starting a project with Expo or not.

**Comment by fractalmarc** [comment]
Bump, @EvanBacon thanks for letting us know the sitch. Is web push on the roadmap for expo any time soon or should plan workarounds for this?

**Comment by Lyubomyr** [comment]
Hi. Any update on this?

**Comment by bnussman** [comment]
Can we get some clarity on this? Are web push notifications even supported? I'm getting a simlar error when I try to generate my keys. 

`~/Documents/Projects/Beep > expo push:web:generate --vapid-subject "mailto:myemail@mydomain.com"
Reading project configuration...
Logging in...
Generating and setting VAPID keys on Expo's servers...
Request failed with status code 404
Error: Request failed with status code 404
    at createError (/usr/lib/node_modules/expo-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/lib/node_modules/expo-cli/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)`

**Comment by brentvatne** [comment]
sorry this was pulled in to the latest docs release again even though it is not supported. I have deleted it from the docs again, will be deployed shortly.

@EvanBacon's above comment still applies, we don't provide web push notifications apis yet (but you can do it on your own if you want to). i will lock the thread and we will update it when the situation changes

**Comment by brentvatne** [comment]
i closed this because we're not working on web notification apis currently and we've removed previous indications that we had experimented with it. we'll revisit this in the future and announce through https://blog.expo.io when we have something :) again, you can do whatever you need to support web notifications in your app as you would with any other tool, we just don't currently give you a super easy way to do it with expo-notifications in the same way that we do for ios and android.
