### ISSUE TITLE
Prompt user to manually open the simulator if it's taking a while

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#132]
Sometimes when opening the app in the iOS simulator, xdl hangs on "Opening iOS simulator" because it's waiting for it to boot, but no matter how long you wait it will not boot. You need to manually open the simulator and then once you do it'll immediately show up with `Opening exp://127.0.0.1:19000` in expo-cli. We should warn people after some threshold of time if they need to open it manually, and probably also determine if there is anything we can do to mitigate this in the first place. It only happens when you don't have a simulator open yet. I believe it's more common if you have the simulator app open, then press cmd+w to close the instance of the simulator but leave the app technically open, then try opening the app in the simulator again from expo-cli.

**Comment by EvanBacon** [comment]
I think this isn't as much of an issue because the simulators have become a lot more reliable since 2018.
