### ISSUE TITLE
fail to init project  

### ISSUE THREAD

**Issue by xcqweb** [expo/expo-cli#133]
![default](https://user-images.githubusercontent.com/31958483/47853125-b8742180-de18-11e8-853f-943588f266ef.PNG)

**Comment by molebox** [comment]
Same here

**Comment by jakubste** [comment]
@xcqweb @molebox Is this IP accessible via a web browser? Should respond with 403 error from CloudFront, but that would indicate you can reach it at all

**Comment by xcqweb** [comment]
> @xcqweb @molebox Is this IP accessible via a web browser? Should respond with 403 error from CloudFront, but that would indicate you can reach it at all

It can't be accessed through web. It may be the interception of the company's internal network.

**Comment by jakubste** [comment]
Yup. So it's a problem with your computer accessing Amazon AWS servers. What country are you in?
Maybe consider using a VPN.
I'm going to close this issue because it's nothing we can help, but feel free to comment here with a solution (or asking for help).
