### ISSUE TITLE
expo client:install:ios/android should work outside of a project directory

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#1331]
In this case it should just install the latest version of the client. cc @byCedric

**Comment by byCedric** [comment]
I'm pushing a quick fix now! Tonight I'll work on a better fix. (ETA 20:00 GMT+1)

**Comment by byCedric** [comment]
I believe this is now fixed by #1358, right?

**Comment by brentvatne** [comment]
yep! thanks
