### ISSUE TITLE
[next-js] @expo/vector-icons issue compiling with SSR

### ISSUE THREAD

**Issue by nandorojo** [expo/expo-cli#1332]
First off, I think the integration with `next` is awesome! Thanks for the great work. 

I've encountered a minor bug that prevents a page from compiling.

## Description

Using a file that requires `@expo/vector-icons` via `react-native-paper` doesn't work. My guess is there is an issue with SSR and the font package.

## Expected Behavior

Expected next.js route to compile into a page. I imported the `Button` component from `react-native-paper`:

**pages/index.tsx**

```es6
import * as React from 'react'

// breaks
import { Button } from 'react-native-paper'

export default function Index() {
  return <Button>Hi, expo + next!</Button>
}

// works
import { Text } from 'react-native'

export default function Index() {
  return <Text>Hi, expo + next!</Text>
}
```

## Observed Behavior

The app fails to compile. However, it works fine if I replace `Button` with a typical `Text` from `react-native`.

```es6
[ wait ]  compiling ...
[ error ] ./node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/MaterialCommunityIcons.ttf 1:0
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
ModuleParseError: Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
    at handleParseError (/Users/expo-next-test/node_modules/next/node_modules/webpack/lib/NormalModule.js:469:19)
    at /Users/expo-next-test/node_modules/next/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/expo-next-test/node_modules/next/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/expo-next-test/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/expo-next-test/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at /Users/expo-next-test/node_modules/loader-runner/lib/LoaderRunner.js:205:4
    at /Users/expo-next-test/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

## Environment

```es6
  Expo CLI 3.10.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      Yarn: 1.19.2 - /usr/local/bin/yarn
      npm: 6.12.1 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.2/11B52 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.23 => 16.9.11 
      @types/react-native: ^0.57.65 => 0.57.65 
      expo: ^35.0.0 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.10.2
```

- Phone/emulator/simulator platform, model and version: **Next.js in the browser**

## Reproducible Demo

Here is a simple demo: https://github.com/nandorojo/expo-next-issue

Steps to re-create the demo on your own:

**1. run this:**

```
expo init test
cd test
yarn add @expo/next-adapter react-native-paper
yarn expo-next
yarn next dev
```

**2. add this in pages/index.tsx:**

```es6
import * as React from 'react'
import { Button } from 'react-native-paper'

export default function Index() {
  return <Button>Hi, expo + next!</Button>
}
```

**3. open [http://localhost:3000](http://localhost:3000)**

**Comment by nandorojo** [comment]
I found this on `react-native-paper`'s docs for configuring webpack for web, but I'm not familiar with how webpack works (thanks to expo keeping me from needing to use it.)

https://callstack.github.io/react-native-paper/using-on-the-web.html

**Comment by EvanBacon** [comment]
> If you want to use libraries like `expo-font`, `@expo/vector-icons`, or `react-native-vector-icons` you'll need to change a few things.

Next.js doesn't support font loading by default 🙃  I think this is kinda wack, so I created a guide for [adding font support to Next.js + Expo](https://docs.expo.io/versions/latest/guides/using-nextjs/#font-support)

**Comment by nandorojo** [comment]
Ah, you thought of everything. Sorry for missing that in the docs. Thanks again!
