### ISSUE TITLE
Plug-in framework for commands

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#1349]
Currently for the `optimize` command we suggest that people use npx:

```
npx expo-optimize
```

This is problematic because `npx` will rebuild native dependencies every time you run it.

```
expo run optimize
```

This should be able to handle installing `expo-cli-plugin-optimize` and running it for you, so we don't need to tell people to use `npx` which doesn't work well with native dependencies.

**Comment by EvanBacon** [comment]
I don't think this is something we want to do anymore. Instead we have chosen to move all service related commands to eas-cli and roll expo-cli up with webpack.
