### ISSUE TITLE
Clear lockfiles and dependencies when upgrading

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#1357]
This would be ideal so we don't get into situations like this: https://github.com/expo/expo/issues/5763#issuecomment-565213287

It could, however, cause problems if folks have other dependencies that break when the latest version in their allowed semver range changes.

**Comment by byCedric** [comment]
I'm working on something to get this implemented, but I struggle a bit when this should happen.

1. **Remove modules and lock file _before_ installing other packages**
To me, this seemed like the best solution. It doesn't have to reinstall everything once the versions are changed in the package file. Unfortunately, this results in this error for me (using a monorepo):
![Screenshot 2020-01-26 at 00 21 34](https://user-images.githubusercontent.com/1203991/73128590-094dd800-3fd2-11ea-9f52-f4c0cfbe1544.png)

2. **Reinstall modules and lock file _after_ installing other packages**
This works, but it bumps up the total duration from 33s to 1m23s. I'm not sure if this is a problem though.

If option 2 is a problem, we might be able to reuse the "manually inserting versions" mechanism from the NPM manager. With that we could delay the install script. After we changed the upgraded packages, we can just remove modules/lockfile and install everything once.

What do you think?

**Comment by brentvatne** [comment]
hm yeah neither of those scenarios seem ideal. it'd be useful if we had some projects that encountered this problem and we could look based on those specific cases what would be the best solution. open to ideas for what you think would be best

**Comment by EvanBacon** [comment]
fixed in 35b250c
