### ISSUE TITLE
expo login read ECONNRESET

### ISSUE THREAD

**Issue by SPineapple** [expo/expo-cli#1366]
I am having an issue when logging-in in my terminal, although the 'expo start' works fine, but I need to log-in in order to use expo notifications. 

Whether I run on emulator or physical phone I keep getting : 

read ECONNRESET
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:204:27)

## Observed Behavior
The other day when I tried it again, i signed-in successfully, but when I run my project again today, it keeps telling me : 
Fetching the user profile failed
read ECONNRESET

So after that, I had to logout and login again, but now 'expo login' stopped.

Is there anything I can do to solve the problem ?
or a way around to get expo token notifications.

##ERROR
```
read ECONNRESET
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:204:27)

Fetching the user profile failed
read ECONNRESET
```

## Environment

Expo CLI 3.11.1 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.3.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.2 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.0 => 4.0.0 

Also specify:

- Phone/emulator/simulator platform, model and version:
iPhone X

**Comment by brentvatne** [comment]
it sounds like a network issue, perhaps one of the solutions in this thread could help: https://stackoverflow.com/questions/17245881/node-js-econnreset
