### ISSUE TITLE
Pass release channel as part of webhook body.

### ISSUE THREAD

**Issue by anasanzari** [expo/expo-cli#1367]
Current web hooks gives
```
status - a string specifying whether your build has finished successfully (can be either finished or errored)
id - the unique ID of your build
artifactUrl - the URL to the build artifact (we only include this field if the build is successful)
```
Passing the release channel would help to identify the channel to deploy to.

**Comment by jkhales** [comment]
Thanks for the suggestion! Deployed.

**Comment by anasanzari** [comment]
@jkhales Great! Documentation is not updated yet.

**Comment by jkhales** [comment]
> @jkhales Great! Documentation is not updated yet.

Great point. Fixed! https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/distribution/building-standalone-apps.md

**Comment by mdivani** [comment]
I don't want to open new issue for this but it would be insanely helpful if you can also add platform info for completed build like ios or android

**Comment by jkhales** [comment]
I'll take a look soon!

**Comment by jkhales** [comment]
@mdivani updated! https://docs.expo.io/distribution/building-standalone-apps/#4-wait-for-it-to-finish-building

**Comment by anasanzari** [comment]
@jkhales Would be great if you can add artifact type for android (whether app-bundle or apk). Also may be version from app.json for the build

**Comment by mdivani** [comment]
> @mdivani updated! https://docs.expo.io/distribution/building-standalone-apps/#4-wait-for-it-to-finish-building

Thanks a lot!
