### ISSUE TITLE
[expo-cli] Fix generate-module for Kotlin template

### ISSUE THREAD

**Issue by sjchmiela** [expo/expo-cli#1372]
https://github.com/expo/expo/pull/6022 refreshed and introduced Kotlin support to `expo-module-template`. `expo-cli` doesn't support new directory structure and errors with

```
Using NPM package as template: expo-module-template@8.1.0
ENOENT: no such file or directory, lstat '/Users/sjchmiela/Applications/expo/expo-notifications/android/src/main/java/expo/module/template'
Set EXPO_DEBUG=true in your env to view the stack trace.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by bbarthec** [comment]
@sjchmiela please use `--template` option or update to newest `expo-cli` 😉

**Comment by sjchmiela** [comment]
I have used the `expo-cli` that is installed in the `expo` repo, sorry if it has already been fixed.

**Comment by bbarthec** [comment]
There's a slight change it's not published yet as merging newer `expo-module-template` was just a followup after merge of this #1135 made by @brentvatne.

**Comment by brentvatne** [comment]
the version of expo-cli uses in expo/expo was a bit out of date, i bumped that, tested it and it works.

one odd thing though is that when i ran `expo generate-module expo-barthec` from `expo/packages/` it created `expo-barthec` in the the root `expo/` directory.
