### ISSUE TITLE
Problem in communication with expo.host

### ISSUE THREAD

**Issue by zerob4wl** [expo/expo-cli#138]
There is a problem in connection between expo-cli and expo server (expo.host). I am not sure the problem in client side or in the server! However when I try to login or create user with CLI, I receive 400 error code. The Nginx response is this: 400 The plain HTTP request was sent to HTTPS port.

**Comment by jakubste** [comment]
That's odd.
First of all: what version of `expo-cli` are you using? What OS? Are you behind some kind of corporate proxy?

**Comment by zerob4wl** [comment]
versions:
expo-cli: 2.2.5
node: 10.8
OS: arch linux

I give this error with/without a proxy!
( I tried from Iran and Germany)

**Comment by zerob4wl** [comment]
I have no error in the latest version of expo-cli.
I close the issue.
