### ISSUE TITLE
Sending push notification for android when not signed in results in Error: Couldn't get GCM token for device

### ISSUE THREAD

**Issue by cruzach** [expo/expo-cli#1389]
## Description

If you're not signed into `expo-cli`, and you try to send an android push notification, you'll see an in the logs:
```
[Unhandled promise rejection: Error: Couldn't get GCM token for device]
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

Also specify:

- Android device (pixel, but it's been reported on others)

## Reproducible Demo

Run the docs example - https://snack.expo.io/@charliecruzan/pushnotifications34?platform=ios locally, signed out of `expo-cli` and signed in

related - https://github.com/expo/expo/issues/5900

workaround is to just sign in to expo-cli

**Comment by ucallQA** [comment]
We have updated to use FCM from GCM a few months ago and several users still trigger this error in Sentry. We are certain they updated the app and are using FCM now, although we still see this error in production several months later

Expo Diagnostics: 
  Expo CLI 3.11.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.17.3
      npm: 6.9.0

Devices: Android 28, Android 29, Android 26

**Comment by serhiipalash** [comment]
The easiest way to reproduce this issue is to start your dev server in offline mode and then open your project on real Android device and try to get this device push token with `Notifications.getExpoPushTokenAsync()`.

```
expo-cli start --offline
```

**Comment by TheEarlyNerd** [comment]
I am experiencing the same problem.
