### ISSUE TITLE
expo fetch:android:upload-cert returns error: There is no valid Keystore defined for this app

### ISSUE THREAD

**Issue by amber-pli** [expo/expo-cli#1394]
## Description
After `expo init` a new project `expo build:android --clear-credentials` (following instructions at https://docs.expo.io/versions/v36.0.0/distribution/app-signing/#1-using-app-signing-by-google-play)

`EXPO_DEBUG=true expo fetch:android:upload-cert` returns error: `There is no valid Keystore defined for this app`

## Expected Behavior

It should download the certificate from the keystore into .pem file

## Observed Behavior

It returns following error:

```

There is no valid Keystore defined for this app
Writing upload key to /Users/pli/my/git/amber/expo-tests/packages/paul-test4/paul-test4_upload_cert.pem
keytool exited with non-zero code: 1
Error: keytool exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/pli/.nvm/versions/node/v12.13.1/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:300:26)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
    ...
    at spawnAsync (/Users/pli/.nvm/versions/node/v12.13.1/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at Object.exportCertBase64 (/@expo/xdl@57.4.2/src/credentials/AndroidCredentials.ts:65:12)
    at fetchAndroidUploadCertAsync (/expo-cli@3.11.3/src/commands/fetch/android.js:60:30)
    at Command.<anonymous> (/expo-cli@3.11.3/src/exp.ts:81:7)
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

```
Expo CLI 3.11.3 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      Yarn: 1.19.2 - ~/.nvm/versions/node/v12.13.1/bin/yarn
      npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.11.3
```

Also specify:

- Phone/emulator/simulator platform, model and version: N/A

## Reproducible Demo

N/A

## Addition Info

1. Expo Build: https://expo.io/dashboard/amber-ci/builds/eec7cc9b-ec2d-4fc3-8342-811241f8ddfd
2. Forums: https://forums.expo.io/t/there-is-no-valid-keystore-defined-for-this-app/31490

**Comment by Hirbod** [comment]
Same issue here

**Comment by cruzach** [comment]
Hi! Just wanted to let you know that we're aware of this issue and are currently looking into it. We'll update you here with any further info

**Comment by cruzach** [comment]
@amber-pli as a workaround for a new project- you can run `expo credentials:manager -p android` and for the desired project (it should automatically suggest the current project directory) select `Update Upload Keystore`, then select `Let Expo handle the process`. It should say - `Updated Keystore successfully`, then you should select `Go back to experience overview.` (At this point, I suggest choosing the option to `Download Keystore from the Expo servers`, and back it up to a safe location so you have those credentials saved)

This will create a new keystore and save it onto our servers, and you should then be able to run `expo build:android` to build binaries using those credentials. All the `expo fetch:android:[]` commands will also work.

This is just a workaround to be able to generate android credentials and use them for subsequent builds, we are still investigating the issue

**Comment by Hirbod** [comment]
Ok, sounds good. What if the upload-cert has a password (which it does). Can we submit them too?

**Comment by cruzach** [comment]
Not sure I understand you- you mean you created your own upload-cert with a password and you're asking if you can upload it to the play store?

**Comment by Hirbod** [comment]
I am asking if I can store my self generated upload cert on expo servers in order to let expo handle the process for future releases. It was never my intention to create this store and key myself but I was forced to.

**Comment by ide** [comment]
Cross-posting the resolution also posted on the forums:


We believe this issue has been fixed and that regenerating credentials will address the issue. Projects that didn’t have this issue should be unaffected.

We found there was an issue with saving credentials, so when commands like “expo fetch:android:keystore” looked for credentials and found none, that was actually the case. Saving credentials should now be fixed, so after regenerating or reuploading them, they should now be saved successfully so they can be fetched.

**Comment by cruzach** [comment]
@Hirbod you should be able to upload that cert without a problem, if you don't let me know

Closing this issue since it's resolved, tested that myself. If you built a new Android app and deployed it to the Google Play store from 12/19 to 12/26, then you may have to reset your keystore on the Google Play store (which isn't a problem as long as you are using [App Signing by Google Play](https://docs.expo.io/versions/latest/distribution/app-signing/#android) which is enabled by default now).

**Comment by Hirbod** [comment]
Thanks for the response. Thank god I had App Signing by goole play active. People without in this period of time will have a big problem now I guess. I'll report back as soon as I am able to re-upload. Google inserted my new pem but I am blocked for 2 days now until the new upload cert gets activated.

**Comment by cruzach** [comment]
Luckily since this issue only applies to people who built and deployed new android apps, and app signing is enabled by default on new android apps, hopefully that number of a people that have to create a new app is either very small or 0
