### ISSUE TITLE
Auto-linking not supported in a fresh bare-workflow project; and several manually-linked dependencies included from beginning

### ISSUE THREAD

**Issue by shirakaba** [expo/expo-cli#1398]
## Description

I'm trying to use the bare workflow, but am concerned about receiving React Native CLI error messages due to it manually linking several dependencies (see `ios/Podfile`, for example):

```
  # Other native modules
  pod 'RNGestureHandler', :podspec => '../node_modules/react-native-gesture-handler/RNGestureHandler.podspec'
  pod 'RNReanimated', :podspec => '../node_modules/react-native-reanimated/RNReanimated.podspec'
  pod 'RNScreens', :path => '../node_modules/react-native-screens'
```

## Expected Behavior

Given that this is React Native 0.61.4, these dependencies should instead be auto-linked to avoid the error appearing. Note, however, that unlinking them so that auto-linking can take care of the rest is not working for me either (I receive a paradoxical error message saying dependencies have not been installed, which suggests that I should try running `pod install` – which does not improve the situation).

## Observed Behavior

The dependencies are manually linked, so this CLI error appears:

```
$ yarn ios
yarn run v1.21.1
$ react-native run-ios
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-gesture-handler (to unlink run: "react-native unlink react-native-gesture-handler")
  - react-native-reanimated (to unlink run: "react-native unlink react-native-reanimated")
  - react-native-screens (to unlink run: "react-native unlink react-native-screens")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
```

### Why manually linking them is bad

This error message lead to me going in a loop for ages, unlinking them to dispel the error (but then receiving the above-mentioned paradoxical error, and following its recommendations only to be returned back to step one).

## Environment

```
$ expo diagnostics

  Expo CLI 3.11.3 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 4.4.23 - /usr/local/bin/bash
    Binaries:
      Node: 13.4.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ~16.9.0 => 16.9.17 
      @types/react-native: ~0.60.23 => 0.60.26 
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: ~0.61.4 => 0.61.5 
    npmGlobalPackages:
      expo-cli: 3.11.3
```

* iPhone 11 (iOS 13.3)
* Developing on macOS 10.14.6

## Reproducible Demo

```sh
expo init myapp
# ? Choose a template: expo-template-bare-typescript
# ✔ Please enter names for your project. · 100% completed
# ? Yarn v1.21.1 found. Use Yarn to install dependencies? Yes

# change directory to "myapp" if expo cli hasn't taken you there already.

cd ios && pod install
cd .. && yarn ios
```

---

**EDIT:**

🚨 I have found that it is not just these three particular dependencies, but all subsequent installed dependencies in the bare workflow fail to auto-link.

**Comment by brentvatne** [comment]
new projects have upstream autolinking configured now. you can follow https://github.com/expo/expo/commit/b8e06d2735ff05ee122efa21de5686c058cd39f7 to add it to an existing project

**Comment by shirakaba** [comment]
@brentvatne I’ll give this a try tomorrow! Thanks so much 🙂

**Comment by zaptrem** [comment]
I'm dealing with this issue right now but I don't understand what you mean when you suggest we "follow" the commit you linked @brentvatne . Can you clarify?

Thanks.

**Comment by shirakaba** [comment]
@zaptrem My understanding was to do all the same things that were done in that commit.

Refer to all the files before and after. Here are my notes giving links to the before and after states:

## `.gitignore`

Just add:

```
# Template projects
templates/**/android/**/generated/*
templates/**/android/app/build
```

## `android/app/build.gradle`

```
/* 
* AUTO-LINKING COMMIT:
* https://github.com/expo/expo/commit/b8e06d2735ff05ee122efa21de5686c058cd39f7
* 
* BEFORE AUTO-LINKING:
* https://github.com/expo/expo/blob/d11a4a064dd32e31da2c73dca01a60e0c377412a/templates/expo-template-bare-typescript/android/app/build.gradle
*
* AFTER AUTO-LINKING:
* https://github.com/expo/expo/blob/b8e06d2735ff05ee122efa21de5686c058cd39f7/templates/expo-template-bare-typescript/android/app/build.gradle
*
*/
```

## `android/app/src/main/java/com/linguabrowse/MainApplication.java`

```
/* 
* AUTO-LINKING COMMIT:
* https://github.com/expo/expo/commit/b8e06d2735ff05ee122efa21de5686c058cd39f7
* 
* BEFORE AUTO-LINKING:
* https://github.com/expo/expo/blob/d11a4a064dd32e31da2c73dca01a60e0c377412a/templates/expo-template-bare-typescript/android/app/src/main/java/com/helloworld/MainApplication.java
*
* AFTER AUTO-LINKING:
* https://github.com/expo/expo/blob/b8e06d2735ff05ee122efa21de5686c058cd39f7/templates/expo-template-bare-typescript/android/app/src/main/java/com/helloworld/MainApplication.java
*
*/
```

## `android/settings.gradle`

```
/* 
project(':react-native-gesture-handler').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-gesture-handler/android')		 * AUTO-LINKING COMMIT:
 * https://github.com/expo/expo/commit/b8e06d2735ff05ee122efa21de5686c058cd39f7
 * 
 * BEFORE AUTO-LINKING:
 * https://github.com/expo/expo/blob/d11a4a064dd32e31da2c73dca01a60e0c377412a/templates/expo-template-bare-typescript/android/settings.gradle
 *
 * AFTER AUTO-LINKING:
 * https://github.com/expo/expo/blob/b8e06d2735ff05ee122efa21de5686c058cd39f7/templates/expo-template-bare-typescript/android/settings.gradle
 *
 */
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle");
applyNativeModulesSettingsGradle(settings)
```

## `ios/Podfile`

```
#
# AUTO-LINKING COMMIT:
# https://github.com/expo/expo/commit/b8e06d2735ff05ee122efa21de5686c058cd39f7
# 
# BEFORE AUTO-LINKING:
# https://github.com/expo/expo/blob/d11a4a064dd32e31da2c73dca01a60e0c377412a/templates/expo-template-bare-typescript/ios/Podfile
#
# AFTER AUTO-LINKING:
# https://github.com/expo/expo/blob/b8e06d2735ff05ee122efa21de5686c058cd39f7/templates/expo-template-bare-typescript/ios/Podfile
#
```

**Comment by shirakaba** [comment]
@zaptrem I can't share my commit with you because the repo is private, but I can share screenshots of the diffs I made:

![image](https://user-images.githubusercontent.com/14055146/73927748-de189200-48c9-11ea-9eb1-04d0001fb8a1.png)

![image](https://user-images.githubusercontent.com/14055146/73927774-ebce1780-48c9-11ea-883f-905617e8a629.png)

![image](https://user-images.githubusercontent.com/14055146/73927803-f5577f80-48c9-11ea-830d-6c0a0dba5e82.png)

![image](https://user-images.githubusercontent.com/14055146/73927848-0ef8c700-48ca-11ea-9f62-27a3980917a9.png)

![image](https://user-images.githubusercontent.com/14055146/73927886-1d46e300-48ca-11ea-8ba9-3d86e3092d9c.png)

Note that I have only been building on iOS, so I can't say how healthy the Android side of my changes is.

Sadly, although many (or all) of the packages from the Expo universe **did** successfully auto-link:

* `react-native-vector-icons`
* `react-native-webview`
* `react-native-safe-area-context`
* `react-native-fs`

... My self-made packages did not:

* [`mecab-ko`](https://github.com/shirakaba/mecab-ko)
* [`mecab-ko-naist-jdic-utf-8`](https://github.com/shirakaba/mecab-naist-jdic-utf-8)
* [`mecab-ko-dic-utf-8`](https://github.com/shirakaba/mecab-ko-dic-utf-8)

I based them on the `react-native-webview` repo, so I'm not sure what more is needed to make them be detected by auto-linking @brentvatne .

**Comment by brentvatne** [comment]
thanks for providing that info to help others out @shirakaba!

as for how to make your libraries detected by autolinking- that's described here:https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#what-do-i-need-to-have-in-my-package-to-make-it-work

**Comment by shirakaba** [comment]
Hi @brentvatne. Although I based my packages on the `package.json` style of the `react-native-webview` repo (as suggested in those docs), and include a `podspec` in the root of each repo as mentioned in the docs, autolinking doesn't detect them. I'm unsure where the issue might lie.

Is there any more magic to it than that, and do I appear to have followed your commit correctly?

**Comment by brentvatne** [comment]
if all of those packages linked properly then the config was correct, yeah. i don't know too much about troubleshooting this personally as i'm more familiar with expo autolinking than react-native-cli's version of it, i'd reach out to @grabbou or create an issue on react-native-cli about it
