### ISSUE TITLE
assets with assetBundlePatterns property not bundled into the released android APK

### ISSUE THREAD

**Issue by christtrc** [expo/expo-cli#1410]
# READ THIS FIRST, PLEASE!

We're looking to keep questions on our forums and bug reports on the GitHub repo -- please choose whichever you feel is more appropriate for your issue:

- For questions and help using Expo CLI, post in our community forums (log in with your Expo developer account): https://forums.expo.io/c/expo-cli
- File a bug on the Expo CLI repo (for bugs related to the Expo CLI tools): https://github.com/expo/expo-cli/issues/new
- File a bug on the main Expo repo (for other bugs): https://github.com/expo/expo/issues/new
- Request a feature on Canny: https://expo.canny.io/feature-requests

Thanks for reporting the issue you found with Expo CLI!

# Required format for issues

Please make our job easier by filling this template out to completion.

## Description

My app use Expokit. When upgrade to SDK 36, the fonts assets config by the `assetBundlePatterns` property was not bundled into the released APK. 

I used `./gradlew assembleRelease` to build the apk

My `assetBundlePatterns` config was:

```
"assetBundlePatterns": [
      "assets/*",
      "src/assets/fonts/*",
      "src/assets/images/*"
    ],
```

## Expected Behavior

The fonts should be bundled into the released APK.

## Observed Behavior

I used android studio to analyze the apk, there was nothing with `asset_[hash].ttf`. And in the ·shell-app-manifest.json`, there were four fonts assets: 
```
"bundledAssets":["asset_85bc2a875182f81ef23340b4cfdecd9b.ttf","asset_f7213526ec9296ff43426bfe3eae8926.ttf","asset_9e52b00d737492e337b2498406aef98f.ttf","asset_a8de8ffe262db7e277deb8f1c439c518.ttf"]
```

## Environment

```
Expo CLI 3.11.3 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.17.3 - ~/.yarn/bin/yarn
      npm: 6.13.3 - ~/.nvm/versions/node/v10.15.3/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      @ant-design/react-native: ^3.1.9 => 3.1.9
      expo: ~36.0.0 => 36.0.0
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
      react-navigation: ~4.0.10 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.11.3
```

**Comment by pedro-lb** [comment]
We're also having the same problem here after updating a ExpoKit ejected app to SDK 36.

Apparently `assetBundlePatterns` doesn't work.
