### ISSUE TITLE
New Expo Developer on Windows, Fails on Invalid Regular Expression

### ISSUE THREAD

**Issue by mohamedmansour** [expo/expo-cli#1411]
I am following this page https://expo.io/learn installed Node, and ran the steps, and failed:

```
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class.
```

I know this has been discussed couple of months ago #1074 but as a new user to Expo, the first thing that happens when running it, is that it failed. 

Would be great to have some verification technique to assist users not installing the wrong pre-requisites. Something like `expo doctor`

**Comment by brentvatne** [comment]
is this on a sdk36 project or sdk35?

**Comment by mohamedmansour** [comment]
This is SDK36 which is the default when you expo cli the project.

**Comment by brentvatne** [comment]
this should be resolved on new projects now thanks to @cpojer publishing an update to metro (the bundler used by react-native) with a fix. if you initialize a new project it should work. if it does not, please let me know.
