### ISSUE TITLE
Parallelize opening iOS simulator and downloading client

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#1416]
The following is all executed serially:

```
expo client:install:ios
Could not find your Expo project. If you run this from a project, we can help pick the right Expo client version!
? Do you want to install the latest client? Yes
Opening iOS simulator
Uninstalling Expo client from iOS simulator.
Downloading the Expo client app [========================================] 100% 0.0s
Installing Expo client on iOS simulator
Done!
```

So, while we wait for `Uninstalling Expo client from iOS simulator.` we waste precious time where we could have been downloading the Expo client app too.

**Comment by EvanBacon** [comment]
On iOS we no longer uninstall before reinstalling. On Android it's actually pretty fragile and this optimization may prove to be less helpful in the long run.
