### ISSUE TITLE
Why does expo start not work if a version isn't defined in the config

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo-cli#1418]
Git blame shows some [4 year old code](https://github.com/expo/expo-cli/blob/11ca5bb1645a4c445cf47b6718e889a7f26ad5f7/packages/xdl/src/Exp.ts#L251) throws an error if version isn't defined in the `app.json` (or the `package.json`) then nothing is done with the version after that check is run. Do we still need this check? [version docs](https://docs.expo.io/versions/v36.0.0/workflow/configuration/#version)

related: #1213

**Comment by brentvatne** [comment]
it seems like maybe this was required for the initial version of turtle, based on the commit.

we should verify the following:

- [ ] the publish endpoint works if `version` is not defined in manifest
- [ ] turtle works if `version` is not defined in manifest (if so, what does it default to? binary needs a version)

**Comment by dsokal** [comment]
For iOS builds we use `ios.buildNumber` field from `app.json` and for Android we take `android.versionCode`. It seems that Turtle doesn't use the `version` field from the root object. 

https://docs.expo.io/versions/latest/workflow/configuration/#version

**Comment by EvanBacon** [comment]
We now default the version so it's less of an issue.
