### ISSUE TITLE
Support init with a specific sdkVersion

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#142]
## Description

create-react-native-app let you do this by passing in a custom scripts version. We should let you use old templates by passing in a sdkVersion, eg: `expo init --sdkVersion=28`

**Comment by fson** [comment]
You can now use dist tags of the template packages to do this. For example:
```
expo init --template expo-template-blank@sdk-31
```
These versioned templates are available starting with `sdk-31`.

**Comment by kylesziv** [comment]
Is there a way to install sdkVersion 30?

**Comment by brentvatne** [comment]
we added this feature on sdk31 so not using the command that @fson mentioned, no.

you can clone our old templaste at sdk30 though - this link points to the specific commit https://github.com/expo/new-project-template/tree/3384700874785f34a955ac9d90f870dbc2914d95
