### ISSUE TITLE
expo build:android fail

### ISSUE THREAD

**Issue by frediustcDev** [expo/expo-cli#143]
Hi, first of all thanks for what you have achieved so far the project is really good and I love it.
I am actually new in react native (Expo). and this is my first app:

Since yesterday I am trying to build a standalone version of my app to get my keystones as I am planing to use maps on it but I keep getting errors.
I am actually working on my mac, but I have also tried on my win8.1 machine I still get the same error I don’t know if it's my code, expo-cli or expo that has the problem.
Can someone help me?

**in my console**

[00:30:35] You can monitor the build at

https://expo.io/builds/4232eaba-d9b2-479d-9887-507323d2a472

|[00:30:35] Waiting for build to complete. You can press Ctrl+C to exit.
-[00:31:36] Standalone build failed!

**this is the error found on the link above:**

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
at Function.Buffer.from (buffer.js:183:11)
at runShellAppBuilder (/app/build/builders/android.js:46:65)
at

**computer spec**

MacOS mojave
version: 10.14
expo-cli version 2.2.5
expo version: 30.0.1
react: 16.3.1,
react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz,

**Comment by jakubste** [comment]
Do you have a backup of your keystore?
Try building with a new one (`expo build:android -c`).

**Comment by frediustcDev** [comment]
Sorry I have forgotten to close the issue you have already helped me. Thanks again
