### ISSUE TITLE
Gesturehandler not properly working Expo SDK 36 in web

### ISSUE THREAD

**Issue by chayancbnits** [expo/expo-cli#1430]
Expo CLI 3.11.5 environment info:
    System:
      OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.14.0 - ~/.nvm/v12.14.0/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 6.13.4 - ~/.nvm/v12.14.0/bin/npm
    npmGlobalPackages:
      expo-cli: 3.11.3

**Comment by EvanBacon** [comment]
Please open more specific issues in the [react-native-gesture-handler](https://github.com/software-mansion/react-native-gesture-handler/issues) repo so I can investigate. Thanks in advance.
