### ISSUE TITLE
Use react-native-cli Metro HTTP server instance directly

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#1434]
This will require changes to react-native-cli. We should be able to inject our middleware to react-native-cli's express server. This has some benefits:

- don't need to start an other express server on another port
- don't need to start up a tunnel on both servers, just one
- don't need to serialize config and pass it in awkwardly in command line flags
- many more

idea via @EvanBacon

**Comment by EvanBacon** [comment]
Fixed in SDK 40 or now with `EXPO_USE_DEV_SERVER=true`.
