### ISSUE TITLE
Stop including environment variables in manifest in development

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#1435]
As per discussion in https://github.com/expo/expo-cli/pull/540#issuecomment-573240102 - a better solution than automatically pulling in env vars with `EXPO_` and `REACT_NATIVE_` prefixes is to allow folks to expose whichever env vars they want to manually inside of `app.config.js`, which will be introduced with https://github.com/expo/expo-cli/pull/1342.

When we remove automatically exposed environment variables we will need to provide people with a clear migration path to using `app.config.js`.

**Comment by fson** [comment]
This was implemented in https://github.com/expo/expo-cli/pull/3063. Starting from SDK 41 we will no longer expose any environment variables in the `env` property of the manifest.
