### ISSUE TITLE
expo bundle-assets - no output

### ISSUE THREAD

**Issue by virus2016** [expo/expo-cli#1437]
## Description

I am looking to do standalone builds and host bundles. Trying to run expo bundle-assets and nothing happens.

> expo bundle-assets --platform ios --dest ./iosout
> expo bundle-assets --platform android --dest ./androidout

## Expected Behavior

Create shell-app-mainifest.json and bundle with all the assets? 

## Observed Behavior

Nothing... cli just exits, no error even with EXPO_DEBUG=true.

I run publish and it creates shell-app-mainifest.json and bundle in the iOS and android folders with no assets however it pushes to expo. App works perfect though.

If I run expo export, the assets and bundles are created in the dist folder.

## Environment

  Expo CLI 3.11.5 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.9.1 - /usr/local/bin/node
      npm: 6.10.2 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.9.17 => 16.9.17 
      @types/react-native: ^0.57.36 => 0.57.65 
      @types/react-navigation: ^3.0.1 => 3.4.0 
      expo: ^36.0.2 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ~3.13.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.11.5

**Comment by brentvatne** [comment]
can you reproduce this in a brand new project? it'd be useful to have a [mcve](https://stackoverflow.com/help/mcve)

**Comment by EvanBacon** [comment]
`expo bundle-assets` is deprecated as part of ExpoKit. The new EAS Build has no similar issues to this.
