### ISSUE TITLE
Console logs in Remote JS Debugging mode

### ISSUE THREAD

**Issue by elfstyle** [expo/expo-cli#144]
## Description

After updating from sdk30 to sdk31, terminal started to show console output in Remote JS Debugging mode.

## Expected Behavior

In Remote JS Debugging mode console output should be in web browser only.

## Observed Behavior

In Remote JS Debugging mode console output is in the terminal window and in the web browser.

## Environment

Expo CLI 2.2.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.4.1

**Comment by maharjanaman** [comment]
This is making my system hang a lot. Can we get update on this?

**Comment by colinux** [comment]
Same issue here, the cli is becoming unusable with large amount of logs (redux-logger…)
Displaying console.log in terminal should be disable by an option. Ideally, the option could be configurable depending of the level of the message (log/warn/error…)

**Comment by brentvatne** [comment]
this issue (showing logs in chrome dev tools & cli when remote debugging) has been resolved 

interesting idea re: disabling logs. open to a rfc to discuss.
