### ISSUE TITLE
$ yarn start yarn run v1.21.1 $ expo start Starting project at C:\Users\hinde\Desktop\Mobileapp\login Expo DevTools is running at http://localhost:19002 Press d to open DevTools now, or shift-d to always open it automatically. Derror Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\ .*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class.  Metro Bundler process exited with code 1 Set EXPO_DEBUG=true in your env to view the stack trace. error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### ISSUE THREAD

**Issue by mohcine-ysc** [expo/expo-cli#1443]
how i can fix this error

$ yarn start
yarn run v1.21.1
$ expo start
Starting project at C:\Users\hinde\Desktop\Mobileapp\login
Expo DevTools is running at http://localhost:19002
Press d to open DevTools now, or shift-d to always open it automatically.
Derror Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\
.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class.

Metro Bundler process exited with code 1
Set EXPO_DEBUG=true in your env to view the stack trace.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by brentvatne** [comment]
in addition to ensuring you have the latest version of expo-cli, please also remove any lockfile, delete node_modules, and run `npm install` or `yarn` again
