### ISSUE TITLE
expo start on iOS simulator and real device returns 400

### ISSUE THREAD

**Issue by kmanj-pixel** [expo/expo-cli#1444]
## Description

expo start on iOS simulator and real iPhonereturns 400 in console and "Could not load exp://[IP]:19000" in expo client. Is this related to #1436?

Does not seem to be happening on Android simulator. (No real Android device to test.)

## Expected Behavior

What action did you perform, and what did you expect to happen?
App builds -- none of our code changed so this should be working...

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the _full terminal output and error message_ in this code block:

```
Error: Request failed with status code 400
    at createError (/home/user/.nvm/versions/node/v12.14.0/lib/node_modules/expo-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/user/.nvm/versions/node/v12.14.0/lib/node_modules/expo-cli/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/user/.nvm/versions/node/v12.14.0/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:
  Expo CLI 3.11.5 environment info:
    System:
      OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
      Yarn: 1.21.1 - ~/.nvm/versions/node/v12.14.0/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
    npmPackages:
      expo: ^36.0.0 => 36.0.2 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.11.5

Also specify:

- Phone/emulator/simulator platform, model and version:
Emulator: iPhone X
Phone: iPhone XR, iOS 13

**Comment by chrisdrackett** [comment]
seeing this on a Mac as well, lots of people seem to be having this issue: https://forums.expo.io/t/request-failed-with-status-code-400-on-local-environment/32156/11

**Comment by BrianLi101** [comment]
same issue affecting both Android/iOS devices and emulators on my mac

**Comment by tonyhhart** [comment]
I guess it`s fixed. Probably some server error

**Comment by Sford4** [comment]
Same issue, iOS simulator and both iOS and Android device cannot load, return 400

**Comment by anbackmynt** [comment]
Had same experience, works now, plz close issue

**Comment by brentvatne** [comment]
indeed there was a server issue, apologies for that!

**Comment by mikeRChambers610** [comment]
Is there a server issue right now? 6PM 4/14/2020.

Experiencing a 400 error. Start happening randomly. Seems to be the same error as previous server issues. Can someone confirm and give an estimated time for the issue to be resolved? Thanks in advance? 
Error: Request failed with status code 400
    at createError (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by mikeRChambers610** [comment]
@brentvatne Would you kindly check on my post above?

**Comment by brentvatne** [comment]
everything working as expected. what expo-cli version are you using?

**Comment by mikeRChambers610** [comment]
> everything working as expected. what expo-cli version are you using?

Thanks for the quick response Brent. Im using expo 3.2.3. I've been using expo for a couple of years now and never ran into this issue before. It just started randomly happening when I try to run the project on the devices.

**Comment by mikeRChambers610** [comment]
I am seeing that my issue is that same as @iranmarcius issue posted in thread #1069 . I tried downgrading and upgrading the expo-cli to no avail. 

The issue is persisting in all of the following expo-cli versions

3.1.2
3.2.0
3.2.1
3.2.2
3.2.3 
3.4.1
3.7.1

**Comment by mikeRChambers610** [comment]
The issue is now resolved on my end by upgrading to the latest CLI 3.18.0 by using below install.

npm uninstall -g expo-cli
npm install -g expo-cli

**Comment by averyyip** [comment]
Had the same problem on my end and it was working the night before. @mikeRChambers610 solution works.

**Comment by brentvatne** [comment]
indeed you should always try to use the latest version of expo-cli! this is why we show warnings when you run commands to tell you about new versions

**Comment by 67millwood** [comment]
i just did a fresh reinstall of expo-cli and have the same issue.  nothing changed in code between last night and today.

**Comment by 67millwood** [comment]
> i just did a fresh reinstall of expo-cli and have the same issue. nothing changed in code between last night and today.

resolved....really odd error to come out of the blue like that.

**Comment by brentvatne** [comment]
the error was due to a backend change that the older version of the expo-cli depended on. it only impacted versions of expo-cli that were, iirc, 4+ months old
