### ISSUE TITLE
expo build:android ✖ Build failed. Standalone build failed!

### ISSUE THREAD

**Issue by michaelVictoriaDev** [expo/expo-cli#1450]
## I'm creating expo build:android
✖ Build failed.
Standalone build failed!

## Expected Behavior
It will export apk project

## Error Logs

```
> Task :app:processReleaseGoogleServices FAILED
Parsing json file: /app/turtle/workingdir/android/sdk33/android-shell-app/app/google-services.json
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:processReleaseGoogleServices'.
[stderr] > No matching client found for package name 'com.xtendly.staging'
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 30s
9 actionable tasks: 9 executed
Error: ./gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/app/turtle/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
    ...
    at spawnAsync (/app/turtle/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at spawnAsyncThrowError (/app/turtle/node_modules/@expo/xdl/build/detach/ExponentTools.js:235:45)
    at buildShellAppAsync (/app/turtle/node_modules/@expo/xdl/build/detach/AndroidShellApp.js:881:11)
    at <anonymous>
```

## Environment

  Expo CLI 3.8.0 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.4 => 33.0.4
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
      react-navigation: ^2.18.3 => 2.18.3

**Comment by brentvatne** [comment]
@michaelVictoriaDev - please provide your build id so @dsokal can investigate

**Comment by dsokal** [comment]
Hi @michaelVictoriaDev!
Have you specified `expo.android.googleServicesFile` in your `app.json`? I can see that your app's Android package is `com.xtendly.staging` so you most probably have an app for "staging" and for "production". Maybe you're trying to use the same `google-services.json` file for two totally different Android apps. 
If that's not the case, like Brent said, please share your build id with us :)

**Comment by michaelVictoriaDev** [comment]
@dsokal you are correct that I have staging app and prod app, and I'm using same `google-services.json` but the staging app is not really upload in google playstore so I assume that's not a problem ?

```
BUILD ID
1e2c2d1d-455f-4ad4-a855-06ca7e1ca790
```

**Comment by dsokal** [comment]
@michaelVictoriaDev 
Even though you're not uploading your staging app to Google Play Store you have to use another `google-services.json` generated specifically for your staging app :) This file contains the package name of your app so when you use the production json file the package names don't match hence you get the error from you first message :)

**Comment by olawalejuwonm** [comment]
please i'm experiencing this same issue @dsokal

**Comment by olawalejuwonm** [comment]
[stderr] FAILURE: Build failed with an exception.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr] * What went wrong:
Fri, 12 Mar 2021 04:58:43 GMT
[stderr] Execution failed for task ':app:mergeReleaseResources'.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr] > 
Fri, 12 Mar 2021 04:58:43 GMT
[stderr] Multiple task action failures occurred:
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]       > Android resource compilation failed
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]         /app/turtle/workingdir/android/sdk40/android-shell-app/app/src/main/res/mipmap-mdpi/ic_launcher.png: AAPT: error: failed to read PNG signature: file does not start with PNG signature.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]             
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]         /app/turtle/workingdir/android/sdk40/android-shell-app/app/src/main/res/mipmap-mdpi/ic_launcher.png: AAPT: error: file failed to compile.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]             
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]       > Android resource compilation failed
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]         /app/turtle/workingdir/android/sdk40/android-shell-app/app/src/main/res/mipmap-xxhdpi/ic_launcher.png: AAPT: error: failed to read PNG signature: file does not start with PNG signature.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]             
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]         /app/turtle/workingdir/android/sdk40/android-shell-app/app/src/main/res/mipmap-xxhdpi/ic_launcher.png: AAPT: error: file failed to compile.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]             
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]       > Android resource compilation failed
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]         /app/turtle/workingdir/android/sdk40/android-shell-app/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png: AAPT: error: failed to read PNG signature: file does not start with PNG signature.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]             
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]         /app/turtle/workingdir/android/sdk40/android-shell-app/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png: AAPT: error: file failed to compile.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]             
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]       > Android resource compilation failed
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]         /app/turtle/workingdir/android/sdk40/android-shell-app/app/src/main/res/mipmap-xhdpi/ic_launcher.png: AAPT: error: failed to read PNG signature: file does not start with PNG signature.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]             
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]         /app/turtle/workingdir/android/sdk40/android-shell-app/app/src/main/res/mipmap-xhdpi/ic_launcher.png: AAPT: error: file failed to compile.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]             
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]       > Android resource compilation failed
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]         /app/turtle/workingdir/android/sdk40/android-shell-app/app/src/main/res/mipmap-hdpi/ic_launcher.png: AAPT: error: failed to read PNG signature: file does not start with PNG signature.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]             
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]         /app/turtle/workingdir/android/sdk40/android-shell-app/app/src/main/res/mipmap-hdpi/ic_launcher.png: AAPT: error: file failed to compile.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]             
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]       > Android resource compilation failed
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]         /app/turtle/workingdir/android/sdk40/android-shell-app/app/src/main/res/drawable-xxxhdpi/splashscreen_image.png: AAPT: error: failed to read PNG signature: file does not start with PNG signature.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]             
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]         /app/turtle/workingdir/android/sdk40/android-shell-app/app/src/main/res/drawable-xxxhdpi/splashscreen_image.png: AAPT: error: file failed to compile.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]             
Fri, 12 Mar 2021 04:58:43 GMT
[stderr] * Try:
Fri, 12 Mar 2021 04:58:43 GMT
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr] * Get more help at https://help.gradle.org
Fri, 12 Mar 2021 04:58:43 GMT
[stderr] BUILD FAILED in 1m 1s
Fri, 12 Mar 2021 04:58:43 GMT
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Fri, 12 Mar 2021 04:58:43 GMT
Use '--warning-mode all' to show the individual deprecation warnings.
Fri, 12 Mar 2021 04:58:43 GMT
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings
Fri, 12 Mar 2021 04:58:43 GMT
19 actionable tasks: 19 executed
Fri, 12 Mar 2021 04:58:44 GMT
Error: ./gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/app/turtle/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (events.js:418:26)
    at ChildProcess.emit (events.js:311:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
    ...
    at spawnAsync (/app/turtle/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at spawnAsyncThrowError (/app/turtle/node_modules/@expo/xdl/build/detach/ExponentTools.js:201:45)
    at buildShellAppAsync (/app/turtle/node_modules/@expo/xdl/build/detach/AndroidShellApp.js:976:11)
    at async Object.createAndroidShellAppAsync (/app/turtle/node_modules/@expo/xdl/build/detach/AndroidShellApp.js:396:5)
    at async runShellAppBuilder (/app/turtle/build/builders/android.js:95:9)
    at async Object.buildAndroid [as android] (/app/turtle/build/builders/android.js:43:28)
    at async build (/app/turtle/build/jobManager.js:181:33)
    at async processJob (/app/turtle/build/jobManager.js:118:32)
    at async Object.doJob (/app/turtle/build/jobManager.js:49:5)
    at async main (/app/turtle/build/server.js:66:13)

**Comment by olawalejuwonm** [comment]
Could not find google-services.json while looking in [src/nullnull/debug, src/debug/nullnull, src/nullnull, src/debug, src/nullnullDebug]
Fri, 12 Mar 2021 04:58:09 GMT
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Fri, 12 Mar 2021 04:58:09 GMT
Could not find google-services.json while looking in [src/nullnull/release, src/release/nullnull, src/nullnull, src/release, src/nullnullRelease]
Fri, 12 Mar 2021 04:58:09 GMT
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Fri, 12 Mar 2021 04:58:20 GMT
> Task :app:preBuild UP-TO-DATE
Fri, 12 Mar 2021 04:58:20 GMT
> Task :app:extractProguardFiles
Fri, 12 Mar 2021 04:58:20 GMT
> Task :app:preReleaseBuild
Fri, 12 Mar 2021 04:58:20 GMT
> Task :app:compileReleaseAidl NO-SOURCE
Fri, 12 Mar 2021 04:58:20 GMT
> Task :app:compileReleaseRenderscript NO-SOURCE
Fri, 12 Mar 2021 04:58:20 GMT
> Task :app:generateReleaseBuildConfig
Fri, 12 Mar 2021 04:58:20 GMT
> Task :app:generateReleaseResValues
Fri, 12 Mar 2021 04:58:20 GMT
> Task :app:generateReleaseResources
Fri, 12 Mar 2021 04:58:20 GMT
> Task :app:processReleaseGoogleServices
Fri, 12 Mar 2021 04:58:20 GMT
Parsing json file: /app/turtle/workingdir/android/sdk40/android-shell-app/app/google-services.json
Fri, 12 Mar 2021 04:58:28 GMT
> Task :app:createReleaseCompatibleScreenManifests
Fri, 12 Mar 2021 04:58:28 GMT
> Task :app:extractDeepLinksRelease
Fri, 12 Mar 2021 04:58:29 GMT
> Task :app:processReleaseManifest
Fri, 12 Mar 2021 04:58:29 GMT
/app/turtle/workingdir/android/sdk40/android-shell-app/app/src/main/AndroidManifest.xml:17:9-26:20 Warning:
Fri, 12 Mar 2021 04:58:29 GMT
	provider#expo.modules.filesystem.FileSystemFileProvider@android:authorities was tagged at AndroidManifest.xml:17 to replace other declarations but no other declaration present
Fri, 12 Mar 2021 04:58:29 GMT
> Task :app:javaPreCompileRelease
Fri, 12 Mar 2021 04:58:29 GMT
> Task :app:prepareLintJar
Fri, 12 Mar 2021 04:58:29 GMT
> Task :app:mergeReleaseShaders
Fri, 12 Mar 2021 04:58:29 GMT
> Task :app:compileReleaseShaders NO-SOURCE
Fri, 12 Mar 2021 04:58:29 GMT
> Task :app:generateReleaseAssets UP-TO-DATE
Fri, 12 Mar 2021 04:58:31 GMT
> Task :app:mergeReleaseAssets
Fri, 12 Mar 2021 04:58:32 GMT
> Task :app:checkReleaseDuplicateClasses
Fri, 12 Mar 2021 04:58:32 GMT
> Task :app:processReleaseJavaRes NO-SOURCE
Fri, 12 Mar 2021 04:58:37 GMT
> Task :app:collectReleaseDependencies
Fri, 12 Mar 2021 04:58:37 GMT
> Task :app:sdkReleaseDependencyData
Fri, 12 Mar 2021 04:58:37 GMT
> Task :app:mergeReleaseJniLibFolders
Fri, 12 Mar 2021 04:58:38 GMT
> Task :app:validateSigningRelease
Fri, 12 Mar 2021 04:58:38 GMT
> Task :app:mergeReleaseJavaResource
Fri, 12 Mar 2021 04:58:39 GMT
> Task :app:mergeReleaseResources FAILED
Fri, 12 Mar 2021 04:58:43 GMT
> Task :app:mergeReleaseNativeLibs
