### ISSUE TITLE
Expo does not generate the token of mobile on IOS.

### ISSUE THREAD

**Issue by saidhappy010** [expo/expo-cli#1452]
I'm trying to retrieve the mobile token.
on android I could recover it but on ios I couldn't. Despite it was working fine.
`   const { status: existingStatus } = await Permissions.getAsync(Permissions.NOTIFICATIONS);`
  ` let finalStatus = existingStatus;`
   `if (existingStatus !== 'granted') {`
    `  // Android remote notification permissions are granted during the app`
      `// install, so this will only ask on iOS`
     ` const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);`
     ` finalStatus = status;`
  ` }`
   `// Stop here if the user did not grant permissions`
   `if (finalStatus !== 'granted') {`
     ` return;`
   `}`
  `// Get the token that uniquely identifies this device`
  `let tokenOfMobile = await Notifications.getExpoPushTokenAsync();`
thank you.

**Comment by brentvatne** [comment]
hello! this is not a complete issue report. additionally, this is the expo-cli repository and this issue is not related to the cli itself. please post your issue to https://github.com/expo/expo/issues and fill out the issue template correctly
