### ISSUE TITLE
`expo upgrade` fails with yarn. Package-Manager searches for `yarnpkg`.

### ISSUE THREAD

**Issue by yreifschneider** [expo/expo-cli#1455]
## Description

When running `expo upgrade` to ugrade my expo project to the newest version, the command failes installing packages via yarn.

## Expected Behavior

I expected `expo upgrade` to work properly with yarn.

## Observed Behavior

`expo upgrade` fails with the following error message:

```
Installing the expo package...

> yarn add expo@^36.0.0
spawn yarnpkg ENOENT
Set EXPO_DEBUG=true in your env to view the stack trace.
```

## Environment

```
% expo diagnostics

  Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.1 - /opt/local/bin/node
      Yarn: 1.19.2 - /opt/local/bin/yarn
      npm: 6.13.4 - /opt/local/bin/npm
    IDEs:
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.0 => 32.0.7 
      @types/react: ^16.8.23 => 16.9.5 
      @types/react-native: ^0.57.65 => 0.57.65 
      @types/react-navigation: ^3.0.1 => 3.0.5 
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.1 => 3.11.1 
```

## Reproducible Demo

Run `expo upgrade` on a Mac with yarn installed via MacPorts.

The issue is, that Package-Manager tries to spawn yarn via the `yarnpkg` executable name. I have yarn installed via MacPorts and it does not have a `yarnpkg` executable, but only `yarn` without `pkg`.

**Comment by brentvatne** [comment]
oh weird, i have never used macports and was not aware of this case. for a simple workaround for now you can just alias `yarnpkg` to `yarn` but we should fix this

**Comment by brentvatne** [comment]
cc @byCedric can you investigate a good fix?

**Comment by byCedric** [comment]
It looks like [CRA was struggling with this too](https://github.com/facebook/create-react-app/issues/1429), some time ago. I also see fson was [involved in something related to this](https://github.com/facebook/create-react-app/issues/1363#issuecomment-271300800) for create-react-app. We can switch using `yarn` in our references, but that might also not work for some people. E.g., [Hadoop Yarn](https://hadoop.apache.org/docs/current/hadoop-yarn/hadoop-yarn-site/YARN.html) might conflict with this.

So eventually, it's a system installation thing that's hard to fix without compromises. We might be able to catch this error and provide some helpful information on this, like manually adding the `yarnpkg` symlink. Or add something to `expo doctor` that double checks if `yarn` exists, without a `yarnpkg` bin.

Symlinking is now the best solution for you @yreifschneider I think, you can do that with:
```
$ ln -s /usr/local/bin/yarn /usr/local/bin/yarnpkg
```

We can also add a PR to macports, but that might take a while though.

**Comment by brentvatne** [comment]
fixing this on macports seems like a good solution :+1:

**Comment by brentvatne** [comment]
it looks like this bit someone again in #1804. not sure what to do with this... looking for suggestions

**Comment by byCedric** [comment]
@brent It's a tough one, I could go either way. I've seen similar issues on other repos as well (like [this](https://github.com/facebook/create-react-app/issues/4437)). One thing I noticed is that the [React Native CLI](https://github.com/react-native-community/cli/blob/5503369b3b454580818d89e9c832e6bdfd292b9f/packages/cli/src/tools/packageManager.ts#L33) uses `yarn`.

The main question would be, how likely would Expo users have Hadoop installed on their machine _and_ want to use yarn?

**Comment by brentvatne** [comment]
maybe we can somehow check from calling something on the `yarn` binary if it is yarnpkg or the hadoop thing? perhaps some command that yarn has that hadoop's bin will definitely not have?

**Comment by byCedric** [comment]
Yeah, I think there might be something. Hadoop's Yarn is returning the whole help section for `yarn --version`, while Yarn itself returns a simple semver 😄

**Comment by byCedric** [comment]
Small update, [MacPorts got updated to also symlink `yarnpkg`](https://github.com/macports/macports-ports/blob/master/devel/yarn/Portfile#L51)! 😄 But still, there might be other ways to not-have this `yarnpkg` link to yarn.

**Comment by jkhales** [comment]
Since this is primarily an external issue and the original MacPorts issue has been resolved, @fson and I are closing this.
