### ISSUE TITLE
expo start is not opening a project

### ISSUE THREAD

**Issue by saadheikh** [expo/expo-cli#1460]
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Error: spawn cmd ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
at onErrorNT (internal/child_process.js:456:16)
at processTicksAndRejections (internal/process/task_queues.js:80:21)

everything was working okay untill i press shift-d and then this happened. i already updated the expo to the latest version
Expo CLI 3.11.7
npm: 6.10.3
unable to find anything related to this devtool issue on github/expo forum
how to disable devtool the metro bundler /lan/tunnel is not starting up.

**Comment by brentvatne** [comment]
you can delete the `.expo` directory and try it again. can you run `expo diagnostics` to give us more info please?

**Comment by saadheikh** [comment]
yes i provided in the decription also i tried reinstalling it after deleting int completely 
but doesnt work

**Comment by brentvatne** [comment]
that's not the full result of `expo diagnostics` in the description :O

**Comment by EvanBacon** [comment]
Possibly fixed https://github.com/expo/expo-cli/pull/1735

**Comment by derahn** [comment]
hi< I am presently experiencing this issues as well. I just installed the new expo yesterday and this is my first build with it. Tried deleting the .expo file and running again but still getting the same error. By the way, this is happening just 4 days after @EvanBacon  closed this issue, please waiting on your suggestions

**Comment by derahn** [comment]
I tried running expo diagnostics in the command and am getting this error.

`Command failed: wmic os get Caption
'wmic' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by brentvatne** [comment]
@derahn - what operating system are you using?

**Comment by derahn** [comment]
> @derahn - what operating system are you using?

I am using windows 10 ... I finally got past this issue, but now I'm at another... apparently expo start works and launches the metro bundler but once I try to run on my android emulator i get the `couldn't start project on Android: could not install *smart socket* listener: cannot bind. Only one usage of each socket address (protocol/network address/port) is normally permitted.`
.....
I did a little research and tried changing the ADB option from genymotion to my android sdk but still getting another error

**Comment by galgord** [comment]
@EvanBacon I still get this error. I am using expo 4.11.0 and when I try and run expo start --android  I get the following:

Couldn't start project on Android: 

Error
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

Works fine on IOS
