### ISSUE TITLE
Eject to Expokit 36 with expo.android.config={}: missing fabric/crashlytics config

### ISSUE THREAD

**Issue by slorber** [expo/expo-cli#1462]
## Description

When ejecting without `expo.android.config` in app.json, a freshly created app can build and start without crash

When ejecting with `expo.android.config={}` in app.json, a freshly created app can build but crash on startup due to Crashlytics error

## Expected Behavior

With a `expo.android.config` we should be able to eject a fresh Expo managed app to Expokit, build and run the app, without having to touch native-generated files. 

That would be a better developer experience for ejection to ensure the ejected project is always runnable.

## Observed Behavior

Simply adding an empty android config in app.json just before ejecting makes the native app crash on startup.

Here's a logcat output:

![image](https://user-images.githubusercontent.com/749374/72723812-f37b8580-3b81-11ea-8b6e-603f6da8cb71.png)

```
The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics
                                                             onboarding instructions and ensure you have a valid Crashlytics account.
```

I've compared 2 ejections (with/without android config), and it seems the version with android config slighly differ:
- fabric.properties is absent
- manifest does not contain "io.fabric.ApiKey"
- also does not contain Google maps api key (I guess it could also be a problem for some users...)

![image](https://user-images.githubusercontent.com/749374/72723932-376e8a80-3b82-11ea-8b07-23fb1acce291.png)

As I did put an empty config, if fabric (+ google maps) config are required to build/start, wouldn't it make sense to still fallback to the default Fabric values you have when you eject without expo.android.config?

## workaround

I've tried to put these settings manually (manifest + fabric.properties) and was able to build/run the app.

Does it make sense to do so? 

Wouldn't it report my app's crashes to Expo managed crashlytics?

## Why would I want to do `expo.android.config={}` in the first place?

 Actually my real app has a real android config, without fabric settings, but with google maps settings.

![image](https://user-images.githubusercontent.com/749374/72724349-5d485f00-3b83-11ea-9a57-f8bcf01761ad.png)

I had a problem ejecting it and had to inspect what was going on and why I wasn't able to make it start without crashing. Found out having an empty config object is the minimal setup to get this bug.

## Unability to obtain my own Fabric api key / secret

Note it looks like due to Fabric/Crashlytics being integrated recently in Firebase, it's currently impossible to signup for a Fabric account and get key/secret required.

So it looks like any user that ejects to Expokit with a `config` will have the same problem as me:
- freshly ejected app will crash
- impossibility to install manually fabric/crashlytics config

For those reasons I guess it's better to always eject with a fabric key/secret in the final config (unless app.json contains a user-provided fabric key/secret that he would have obtained in the past, when it was still possible...)

Otherwise they'll have to find a workaround to be able to start their app, like reusing the default fabric/crashlytics key/secret of Expo when ejecting without config.

Note I'm often "re-ejecting my app", for me this is an easy way to upgrade my ExpoKit app as I only have a few native deps (intercom/onesignal). The most viable workaround is to put these expo key/secret in my app.json:

```
        "fabric": {
          "apiKey": "a25fafe9f9edee11a9882b32e0cd7a26df6e2c42",
          "buildSecret": "83176563693e1eefa1a91359c4151b88c3fd17e52ddf6d64416b7f1e0fa9cede"
        }
```
Now when re-ejecting I'm safe as the fabric config will be there.

But I must admit I don't know the impact of this, as I never really used Crashlytics for now... don't even know where this key/secret come from and where does it report the crashes :)

## Can we disable crashlytics?

Note that this does not work (wasn't able to run with `./gradlew installDebug --stacktrace`)

```
  buildTypes {
    debug {
      debuggable true
      ext.enableCrashlytics = false
    }
```

Even if crashlytics is disabled, it seems we need to have the api key/secret in the config to be able to start without crashing

## Environment

![image](https://user-images.githubusercontent.com/749374/72724167-e01cea00-3b82-11ea-8282-cb4240da5277.png)

Samsung S9 crashes

## Reproducible Demo

Really it's a fresh project. I used:

```
# use latest version
npm install -g expo-cli@3.11.7

# choose blank template, use yarn 1.21.1 for dependencies
expo init bug-expokit-crashlytics
cd bug-expokit-crashlytics

# eject to expokit
yarn expo eject --non-interactive --eject-method expokit

# start
yarn expo start -c

# in another terminal:
cd android
./gradlew installDebug
```

Branch that works (ejected without expo.android.config): https://github.com/slorber/bug-expokit-crashlytics/tree/default-expokit
Branch that does not work (ejected with expo.android.config = {}): https://github.com/slorber/bug-expokit-crashlytics/tree/bug-expokit

------

Avaible here, or on Expo Slack @slorber or Twitter DM @sebastienlorber if needed to help clarify if needed

**Comment by EvanBacon** [comment]
ExpoKit has been deprecated and ejecting to expokit has been removed https://github.com/expo/expo-cli/issues/1513
