### ISSUE TITLE
Can't import SVGs in web app using expo's next-adapter

### ISSUE THREAD

**Issue by rgavinc** [expo/expo-cli#1465]
## Description

I set up a new project through @expo/next-adapter and followed the steps outlined [here](https://github.com/kristerkari/react-native-svg-transformer) so I could import SVGs. I am able to import SVGs for the mobile app but not the web app.

## Expected Behavior

I should be able to import SVGs in the mobile and web app

## Observed Behavior

I receive a compilation error

```
Failed to compile
./src/icons/December.svg 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

## Environment

  Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.5.0 - ~/.nvm/versions/node/v13.5.0/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v13.5.0/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^5.3.6 => 5.3.6 
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.11.7

## Reproducible Demo

```
import React from "react";
import { StyleSheet, View } from "react-native";
import Icon from "../icons/December.svg";

export default () => {
  return (
    <View style={styles.container}>
      <Icon width={120} height={40} />
    </View>
  );
}

```

**Comment by EvanBacon** [comment]
This is a problem with Next.js and not Expo. Please refer to this [SO](https://stackoverflow.com/questions/55175445/cant-import-svg-into-next-js/55180310). All of the solutions here should work with the Expo + Next.js workflow.
