### ISSUE TITLE
Better error screen in web dev tools when server not running

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#1470]
<img width="1052" alt="Screen Shot 2020-01-22 at 14 16 06" src="https://user-images.githubusercontent.com/90494/72897234-cd8ce700-3d21-11ea-90ed-d71508439ef7.png">

**Comment by fson** [comment]
That seems like a bug, this is what Dev Tools normally looks like in that situation:
<img width="939" alt="Screenshot 2020-01-22 at 21 01 58" src="https://user-images.githubusercontent.com/497214/72924988-9ab31500-3d5a-11ea-8cfe-3bdc995a56c1.png">

**Comment by wschurman** [comment]
Tried to repro this in 3.22.3 by ctrl-c'ing the `expo start` process with the browser still open, and I see what @fson mentioned. @brentvatne - were there other repro steps that you remember? If not, I'll close this out for now.

**Comment by brentvatne** [comment]
i believe this has been resolved @wschurman - or at least i haven’t encountered it recently.
