### ISSUE TITLE
Webpack fails to run when you have a *.expo.js version of a component

### ISSUE THREAD

**Issue by anikrooz** [expo/expo-cli#1477]
## Description
`expo start:web` fails to compile when there's a component with both `.js` and `.expo.js` extensions.

## Expected Behavior

I would have expected it to use `.js` or `.web.js` components, and ignore `.expo.js`

## Observed Behavior

```sh
 web  Failed to compile.
...tabstemplate/components/TabBarIcon.expo.js 8:4
Module parse failed: Unexpected token (8:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export default function TabBarIcon(props) {
|   return (
>     <Ionicons
|       name={props.name}
|       size={26}
```

## Environment

  Expo CLI 3.11.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.16.0 - C:\Users\Ant\AppData\Roaming\npm\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156

## Reproducible Demo

expo init (managed with tabs template)
copy eg. components/TabBarIcon.js to components/TabBarIcon.expo.js
expo start:web

**Comment by anikrooz** [comment]
@expo\webpack-config\webpack\env\extensions.js seems to return the following for getModuleFileExtensions('web'):
```
[
  '.web.expo.ts',  '.web.expo.tsx',
  '.web.expo.mjs', '.web.expo.js',
  '.web.expo.jsx', '.expo.ts',
  '.expo.tsx',     '.expo.mjs',
  '.expo.js',      '.expo.jsx',
  '.web.ts',       '.web.tsx',
  '.web.mjs',      '.web.js',
  '.web.jsx',      '.ts',
  '.tsx',          '.mjs',
  '.js',           '.jsx',
  '.json',         '.wasm'
]
```

**Comment by EvanBacon** [comment]
Yes we have `.expo.js` take higher priority than a platform. Workflow extensions like `.expo` should be used to control how something works in an expo environment. A good example of this is switching between an Expo package and a community version of our package. I would recommend you try to limit the usage of `.expo` as much as possible.

**Comment by anikrooz** [comment]
That's fine I'm only using .expo.js because it's an Expokit project.
But it would be good for webpack to be able to use one of them and not just crash when it sees an .expo.js file

**Comment by jvivaspatternag** [comment]
I am having a similar issue.

I am following the example in https://docs.expo.io/versions/v36.0.0/bare/using-expo-client/ for Mapbox and when I add the `MyMap.expo.tsx` file. The webpack compiler throws an error

```
 web  Failed to compile.
Map.web.expo.tsx 7:4
Module parse failed: Unexpected token (7:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| const MyMap = () => {
|   return (
>     <View
|       style={{
|         flex: 1,

```
