### ISSUE TITLE
Invalid Podfile generated by `expo init` when starting new react native project

### ISSUE THREAD

**Issue by guribe94** [expo/expo-cli#1478]
## Description

When creating a new project with `expo init`, it successfully completes but generates a bad Podfile. When you go into /ios and do `pod install` as instructed, cocoapods creates an error of invalid podfile.

## Expected Behavior

What action did you perform, and what did you expect to happen?

Fresh format/install of MacOS 10.14 and 10.15.
Xcode installed + CLI tools 11.3 + cocoapods from `brew cask install cocoapods`
Installed yarn and expo-cli with `npm install -g yarn` and `npm install -g expo-cli`
Created a new project with `expo init project`, successfully completes.
`cd /ios && pod install` 

I expected initial podfile to be valid and for initial app to compile and boot when `yarn start` is run.

## Observed Behavior

What actually happened when you performed the above actions?

Podfile is invalid error

```
MacBook :: congress/ios » pod install

[!] Invalid `Podfile` file: No such file or directory - npx.

 #  from /Users/user/devspace/congress/ios/Podfile:42
 #  -------------------------------------------
 #
 >    use_native_modules!
 #  end
 #  -------------------------------------------
```

## Environment

  ```
Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 13.7.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.6 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.11.7
```

Also specify:

- Phone/emulator/simulator platform, model and version:

## Reproducible Demo

See above in Expected Behavior

**Comment by guribe94** [comment]
I would also like to mention that I replicated that on OS X 10.13 also.

**Comment by IjzerenHein** [comment]
@guribe94 We are looking into the issue. Which version of cocoapods are you using?

**Comment by IjzerenHein** [comment]
Hi, the problem seems to be related to an older version of the `react-native-community/cli`, which depended on `npx` to be installed. This was fixed in https://github.com/react-native-community/cli/releases/tag/v3.1.0

To fix, you can also try creating new project which should install the latest react-native-community/cli, or you can update the `yarn.lock` file to [point to a newer version of the cli](https://github.com/react-native-community/cli#updating-the-cli).
