### ISSUE TITLE
@expo/next-adapter with express js

### ISSUE THREAD

**Issue by obiwankenoobi** [expo/expo-cli#1481]
Hey! 

There is any example of how to setup expo-next.js with Express.js? Its the last piece I really need to bootstrap my project. Couldn't find anything really.

Thank you!

**Comment by EvanBacon** [comment]
https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/guides/using-nextjs.md#using-a-custom-server

**Comment by obiwankenoobi** [comment]
@EvanBacon the "Using a custom server" is REALLY limited. I can't really see how to get from there to actually adding `express` to it. The API doesn't look like it fits. Any chance there is something a little more expended?
