### ISSUE TITLE
HMR

### ISSUE THREAD

**Issue by ksjogo** [expo/expo-cli#1484]
Is HMR supposed to work with the web version yet?
I get ```The development server has disconnected.
Refresh the page if necessary.``` and a full reload after editing code.

**Comment by EvanBacon** [comment]
I think if I started working on this, by the time it's rolled into production Fast Refresh may already be ready. Closing in favor of #1498

**Comment by deathemperor** [comment]
> I managed to enable hot reload using react-hot-loader. It was a little tricky to figure out, but actually pretty simple. Just requires that you alter your App.js slightly.
> 
> Example here: https://github.com/hookedjs/eusy.git

this works flawlessly on my first try. Thanks @bdombro .
