### ISSUE TITLE
add ExpoKit update command

### ISSUE THREAD

**Issue by esamelson** [expo/expo-cli#149]
As discussed in Slack, we'd like to create an `expo update` (or similar) command that would make it easier for people to upgrade the SDK version of their ExpoKit projects. This would mostly involve automating the work listed here: https://docs.expo.io/versions/latest/expokit/expokit#upgrading-expokit but would also involve making sure the Podfile/gradle files are up-to-date with the latest unimodules.

Additionally, there are often some other miscellaneous changes necessary for certain SDK version upgrades (usually other changes in Podfile/gradle files). For example, SDK 31 requires the Podfile's target to be changed to iOS 10, and SDK 27 had a bunch of gradle changes to support bundling assets on Android. Ideally, we'd have some mechanism for including arbitrary changes. At the least, we'd want a way to log instructions for people to complete steps manually.

Since people's ExpoKit projects can be highly customized, any script that we write will almost certainly not work in 100% of cases. We should aim for as much coverage as possible, but in the event of a failure, we should output a clear and helpful error message with instructions about how to proceed.

**Comment by tsapeta** [comment]
I guess we don't want this feature anymore since we have other priorities and are going to deprecate ExpoKit in the long-term.

But maybe `expo update` command could be simplified to just updating expo versions in `package.json` and `app.json` for SDK upgrades in managed workflow?
