### ISSUE TITLE
Support Fast Refresh for Expo Web

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo-cli#1498]
- when it's done https://github.com/facebook/react/issues/16604

**Comment by ksjogo** [comment]
#16660 seems to be a wrong link

**Comment by EvanBacon** [comment]
This works with `EXPO_WEBPACK_FAST_REFRESH=true` btw

**Comment by yomybaby** [comment]
@EvanBacon  `EXPO_WEBPACK_FAST_REFRESH` doens't work. Any update? 😁

**Comment by EvanBacon** [comment]
Yes I remove the experimental setup in https://github.com/expo/expo-cli/pull/3697 because it wasn't working properly. You can easily recreate the implementation locally with this guide https://dev.to/expo/fast-refresh-with-expo-web-3di2 (one plugin).

**Comment by EvanBacon** [comment]
Fast Refresh is available in experimental [Metro web support](https://docs.expo.dev/guides/customizing-metro/#web-support). We're getting ~4x faster refreshes than we were getting with Webpack Fast Refresh.

**Comment by EvanBacon** [comment]
https://github.com/expo/expo/pull/18422

The feature is already enabled by default in Expo Router.

**Comment by EvanBacon** [comment]
Decided to move forward with using Metro instead of Webpack, I'll no longer be adding new features to Webpack. Fast Refresh is already in Expo CLI's Metro for web, and it's ~4-6x faster than Webpack Fast Refresh.
