### ISSUE TITLE
Debugging expo web doesn't work properly

### ISSUE THREAD

**Issue by robclouth** [expo/expo-cli#1505]
### Environment

Expo CLI 2.20.2 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.19 => 16.8.21 
      @types/react-native: ^0.57.60 => 0.57.63 
      expo: ^33.0.0 => 33.0.6 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.11.8

SDK 33 with Expo Web

### Steps to Reproduce

Create a new project with ```expo-cli init```, then start expo in web mode ```expo start -w```. Open Chrome dev tools and set a break point. It will be hit the first time, and every time you refresh the page. But then if you change the code and let it auto-reload, the breakpoint will no longer be hit until you restart expo.

### Expected Behavior

The code stops on breakpoints instead of going into the bundle.js.
The "this" context is correct.

### Actual Behavior

Breakpoints are often ignored then the debugger jumps into bundle.js. Looking the contents of "this" shows the window object.

**Comment by EvanBacon** [comment]
We've rebuilt how source maps work. Debugging should work as expected now.

**Comment by robclouth** [comment]
🍾

**Comment by robozb** [comment]
The debugger is useless on this way, the breakpoints is shifted:

https://github.com/expo/expo-cli/assets/8656998/9b79c502-1ea7-4e43-81cc-e2f363ac0200

...
  "dependencies": {
    "expo": "~49.0.8",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.4"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
...
