### ISSUE TITLE
DevTools don't work in devcontainer. Websocket failed: HTTP Authentication failed; no valid credentials available

### ISSUE THREAD

**Issue by rockettomatooo** [expo/expo-cli#1506]
## Description

Hi!
I'm trying to setup expo within a VSCode devcontainer with the official "Remote - Containers" extension. Unfortunately I'm not able to access the dev tools that are supposed to run on http://localhost:19002

## Expected Behavior

When running `expo start` within the container, I expected to be able to open the devtools on localhost:19002 (I forwarded the port in the `devcontainer.json` of course).

## Observed Behavior

I can access both the bundler on localhost:19001 and expo on localhost:19000. The devtools however won't open up in my browser. Opening up localhost:19002 results in a black screen with multiple of the following errors in the console:
```
WebSocket connection to 'ws://0.0.0.0:19002/krNGNvAI6Zd5Jh0L5Kyo-9hy54NK2dltcaVKml5vEjs/graphql' failed: HTTP Authentication failed; no valid credentials available
```

## Environment

`expo diagnostics` output: (please note that this is the environment of the docker container. I'm running this on OSX 10.15.2)
```
  Expo CLI 3.11.7 environment info:
    System:
      OS: Linux 4.19 Debian GNU/Linux 9 (stretch) 9 (stretch)
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    npmPackages:
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.11.7
```

## Reproducible Demo

I have a minimal reproduction here: https://github.com/rockettomatooo/expo-devtools-reproduction
To reproduce, you need the official "Remote - Containers" extension for VSCode. Then just reopen the repo in container and run `expo start`. I was not able to access the devtools there.

> In this repo, I basically just ran `expo init` and added the stock `node:12` devcontainer files. I only set the `appPort` setting in the `devcontainer.json` to `[19000, 19001, 19002]` and added the `yarn global add expo-cli` to the docker file for convenience.

**Comment by brentvatne** [comment]
hey! we don't support integration with every tool out there. if you can show specifically that there is a bug with expo-cli that is making this integration not work i would be happy to investigate, otherwise i would go to the remote - containers team and ask them for help! :)

**Comment by Ndidi** [comment]
@rockettomatooo did you ever find a solution to this issue?

**Comment by rockettomatooo** [comment]
@Ndidi I didn't unfortunately. And to be completely honest I kind of lost sight of this issue a little bit. When I click the link from the terminal, it still sends me to a random port (despite the console saying http://0.0.0.0:19002) and the site there gives me the Websocket-Error from the original description. I can confirm that the same projects works without the container which makes it even more suspicious tbh. 

@brentvatne I can understand that you won't chase like every ghost that could possibly be there. I tried multiple things that came to mind regarding the network layer + port forwarding but as I mentioned above, it always leads me to a random port which I can't forward beforehand (for obvious reasons) and I also didn't manage to get a response from the port 19002 from outside. While I use `EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0` I didn't find any way to control the port that is chosen for the devtools (as I said it appears to be random) and therefor idk what else to try on the network layer and I'm still suspecting that this is not a problem of my container but somthing regarding the expo-cli.
As this is still my first project with expo I'm not sure of how I can assist with hopefully resolving this issue. Do you have any ideas as of how to debug this maybe?

**Comment by Ravnurin** [comment]
@rockettomatooo  I am getting a near _identical_ issue as you are. My environment consists of WSL2, Docker and VSCode + Remote - WSL extension. Like you, no issues viewing `localhost:19000` and `localhost:19001` in my browser, but `localhost:19002` produces a black screen with the following message in my browser console log:

```
WebSocket connection to 'ws://192.168.x.x:19002/29MznPOgld76BGvZklJwkuilN1tvpBPMEj95b_LTfLQ/graphql' failed: WebSocket is closed before the connection is established.
```

I also get the same thing, where clicking on the `http://0.0.0.0:19002` log in VSCode opens up a tab with a completely different address and port, e.g. `http://127.0.0.1:51045/`

For context, I have no issues viewing my Express server's GraphQL playground in the browser nor with viewing a separate React frontend app. It is exclusively Expo's devtools I am having difficulties with.

**Comment by rockettomatooo** [comment]
@Ravnurin could you, by chance, take my reproduction repo from above and verify, that it throws also throws the error on your machine? If so, we might get this issue to be reopened. Also, since you mentioned that it worked fine a few months back, maybe we can also check the changelog / try out older versions to maybe get a hint on what causes the problem. 
As you, I never ever had issues with portforwarding in docker containers before so this really seems like an expo bug to me.

**Comment by moracabanas** [comment]
I also got running issues.  
I tried to build my custom dockerized Vue Native dev environment but seems like devtools port does something wrong.
I found [here](https://hub.docker.com/r/kerbe/expo) that you can override those env variables in your docker-compose with:  
    
`-e REACT_NATIVE_PACKAGER_HOSTNAME=<<YOUR HOST LOCAL NETWORK IP>> \ --> I do not know why you cannot map this to 0.0.0.0 so this is exposed to host "localhost"  

-e EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0 \` --> this is because defaul localhost value inside a container is not exposed  
  
Then the MOST important part to get devtools working on:
you `npm start` and it displays  
`Expo DevTools is running at http://0.0.0.0:19002`  --> you cannot use `localhost:19002` on your browser.
There is somehow graphql issues where REACT_NATIVE_PACKAGER_HOSTNAME is the only hostname you can use so you must open it like `<<YOUR HOST LOCAL NETWORK IP>>:19002` and it will work  

`Your native app is running at exp://<<YOUR HOST LOCAL NETWOR IP>>:19000`  --> this works scanning QR
