### ISSUE TITLE
expo init not creating project

### ISSUE THREAD

**Issue by nikijoe** [expo/expo-cli#1511]
C:\Users\Nijo Joseph Chakkala\Documents\Net Ninja\React Native>expo init myproject
? Choose a template: expo-template-blank
Using npm to install packages. You can pass --yarn to use Yarn instead.
Extracting project files...
Customizing project...
Initialized a git repository.
Installing dependencies...
npm WARN deprecated deep-assign@3.0.0: Check out `lodash.merge` or `merge-options` instead.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nijo Joseph Chakkala\AppData\Roaming\npm-cache\_logs\2020-02-04T09_25_11_199Z-debug.log
npm exited with non-zero code: 4294967291
Set EXPO_DEBUG=true in your env to view the stack trace.

**Comment by abhaykumar01234** [comment]
Same issue here

**Comment by brentvatne** [comment]
this sounds like a problem with npm. try installing yarn and expo-cli will use that instead. https://classic.yarnpkg.com/lang/en/

**Comment by RyanMitchellWilson** [comment]
Still getting this issue. Can this please be reopened? We use npm for all our project and would really like to not split our tools. Everything we use is with npm, our own npm repository and private gitlab do not currently support yarn, so it would be much more work trying convert everything to be able to handle yarn just for this one project.

**Comment by brentvatne** [comment]
@RyanMitchellWilson - this isn't an issue with expo it's an issue with npm. i only recommended yarn here because it is easier to switch to that than to help people to debug issues with npm.

if you can post an issue with more information to demonstrate that the issue is on the expo side (to show that you are using the latest stable version of npm and that the installation is working correctly) we will definitely investigate. however, with a properly working npm setup, `expo init` works exactly as expected

**Comment by RyanMitchellWilson** [comment]
Ok interesting. @brentvatne do you have a working version of npm you'd suggest to get this working? I'm currently using v6.13.4

**Comment by brentvatne** [comment]
I am using 6.13.7, I suspect it isn't really the npm version but the status of the installation on your machine. Do you use Windows by any chance? Do you have git installed?

**Comment by nikijoe** [comment]
Try these steps
	1. npm install -g expo-cli

	2. expo init <YourProject> --yarn

	3. cd AwesomeProject
	yarn start / expo start
