### ISSUE TITLE
index.html in web-build folder shows blank page

### ISSUE THREAD

**Issue by hbt1903** [expo/expo-cli#1514]
## Description

I am trying to build a web page by using Expo. When I run the "expo start -w" command, I got no errors and can see the page that I created. When I build by using "expo build:web" command it builds the web-build folder with no errors. But when I open the index.html file it shows a blank page.

## Expected Behavior

Having the same view as I see when I run "expo start -w" command when I open the index.html file in web-build folder.

## Observed Behavior

There is an empty page in index.html file. 

(No errors occurred during all these processes)

## Environment
Expo CLI 3.11.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD

I tried with Google Chrome, Microsoft Edge, Internet Explorer

## Reproducible Demo

Create a new project with expo, then run "expo build:web"

**Comment by EvanBacon** [comment]
I cannot repro using `Expo CLI 3.11.9` on a mac. 
You can try: 
- force reloading the web page, maybe a service worker is caching a blank page on the host
- building with `EXPO_DEBUG_WEB=true expo build:web` which will build the project unminified. This will help you debug any problems and possibly provide more info as to what's happening.

**Comment by hbt1903** [comment]
I checked the console and I saw that the errors in first photo.
![errors](https://user-images.githubusercontent.com/26011820/74091895-14befa00-4ace-11ea-8792-58f6ae11eef6.JPG)

Then, I changed 
**<script src="/static/js/bundle.js"></script></body>** part of the index.html as 
**<script src="./static/js/bundle.js"></script></body>**

Then I got the following error.
![error_new](https://user-images.githubusercontent.com/26011820/74091908-4041e480-4ace-11ea-9aba-0591abd706c6.JPG)

**Comment by brentvatne** [comment]
in the `web-build` directory run `npx serve` then open the url that it gives you :)
