### ISSUE TITLE
Unable to upgrade with yarn workspaces

### ISSUE THREAD

**Issue by GrimDev** [expo/expo-cli#1529]
## Description

Hi there. 
I'm using expo-yarn-workspaces as described [here](https://github.com/expo/expo/tree/master/packages/expo-yarn-workspaces) and it's works fine except for expo upgrade/update.

## Expected Behavior

As mensionned above, i'm using official expo-yarn-workspaces and i'm not experiencing issues with yarn or expo in other usages than *expo update*.

So I ran

```shell
expo update
```

And this should update my expo packages.

I also tried to remove the symlink created by expo-yarn-workspaces before running the command but it still don't work.

## Observed Behavior

When I do not remove the expo-yarn-workspace symlink, the *expo-yarn-workspaces postinstall* fails due to the already existing symlink : **EXIST: file already exists, symlink '../../../node_modules/expo' -> ...**

So I removed the symlink manualy but I face the following error :
```
Cannot find module 'expo/bundledNativeModules.json'
Require stack:
- /Users/kcousin/dev/[...]/packages/mobile/noop.js
```

## Environment

  Expo CLI 3.11.9 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.7.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.6 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.11.9

- Phone: Huawei P20 Pro, Android Pie

## Reproducible Demo

Standard expo managed app with yarn workspaces following [those instructions](https://github.com/expo/expo/tree/master/packages/expo-yarn-workspaces)  then run:

```shell
expo upgrade
```

**Comment by GrimDev** [comment]
PS : I removed yarn workspaces to upgrade my expo packages before restablishing them and it works, but it woul'd be fine to upgrade expo whith active yarn workspaces

**Comment by GrimDev** [comment]
@brentvatne `expo install` with yarn workspaces make this on my side :

```
Cannot find module 'expo/bundledNativeModules.json'
Require stack:
- /Users/kcousin/dev/superflix/packages/mobile/noop.js
```

**Comment by brentvatne** [comment]
i see. i don't think there is much we can do to help you here without a minimal reproducible example. these commands work as expected in the expo monorepo https://github.com/expo/expo which also uses expo-yarn-workspaces. this is a pretty advanced feature and you should be prepared to debug some gnarly things like this if you're going to use yarn workspaces. if you can demonstrate that this is indeed an issue in expo-cli and not in your config then please create an issue with that information. thanks!
