### ISSUE TITLE
undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by JonBergman** [expo/expo-cli#1535]
When running `expo upload:ios` I get the following error after downloading build and authentication with Apple.

## Expected Behavior

New build uploaded to TestFlight

## Observed Behavior

Build uploaded, authenticated with Apple and then the terminal stops execution and receives the above error message.

```
Failed to upload the standalone app to the app store.
undefined method `[]' for nil:NilClass
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/app/resolve_itc_team_id.rb:17:in `block (2 levels) in <main>'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/app/resolve_itc_team_id.rb:17:in `each'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/app/resolve_itc_team_id.rb:17:in `find'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/app/resolve_itc_team_id.rb:17:in `block in <main>'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/app/funcs.rb:4:in `with_captured_stderr'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/app/resolve_itc_team_id.rb:11:in `<main>'
```

## Environment

```
Expo CLI 3.11.9 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.9.1 => 3.12.1 
    npmGlobalPackages:
      expo-cli: 3.11.9
```

macOS 10.15.3 Catalina

**Comment by dsokal** [comment]
Hi @JonBergman,
Could you please upgrade expo-cli to the latest version and run `expo upload:ios` again? Please share the error message. This time it should be more descriptive.

**Comment by bradfmd** [comment]
I am running into this same issue. When run ```expo upload:ios``` I get the following output:

```
Failed to upload the standalone app to the app store.
undefined method `[]' for nil:NilClass
    /Users/bradfmd/.nvm/versions/node/v12.16.0/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/app/resolve_itc_team_id.rb:19:in `block in <main>'
    /Users/bradfmd/.nvm/versions/node/v12.16.0/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/app/funcs.rb:4:in `with_captured_stderr'
    /Users/bradfmd/.nvm/versions/node/v12.16.0/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/app/resolve_itc_team_id.rb:11:in `<main>'
Error: undefined method `[]' for nil:NilClass
    /Users/bradfmd/.nvm/versions/node/v12.16.0/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/app/resolve_itc_team_id.rb:19:in `block in <main>'
    /Users/bradfmd/.nvm/versions/node/v12.16.0/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/app/funcs.rb:4:in `with_captured_stderr'
    /Users/bradfmd/.nvm/versions/node/v12.16.0/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/app/resolve_itc_team_id.rb:11:in `<main>'
    at runFastlaneAsync (/expo-cli@3.11.9/src/commands/upload/utils.ts:84:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at IOSUploader._uploadToTheStore (/expo-cli@3.11.9/src/commands/upload/IOSUploader.ts:199:40)
    at IOSUploader.upload (/expo-cli@3.11.9/src/commands/upload/BaseUploader.ts:32:5)
    at /expo-cli@3.11.9/src/commands/upload.js:102:7
    at Command.<anonymous> (/expo-cli@3.11.9/src/exp.ts:81:7)
```
I am on expo-cli version 3.11.9, maxOS 10.15.3

**Comment by dsokal** [comment]
@bradfmd `expo-cli@3.12.1` is the latest version :) Could you please upgrade it and send us the new output? Thanks!

**Comment by luukschipperheyn** [comment]
@dsokal I think I'm having the same issue. This is the output I get using `expo-cli@3.12.1`:
```
Resolving the ITC team ID...
Failed to upload the standalone app to the app store.
Failed to find your team (3Y332V4JFT - Afdeling Buitengewone Zaken Coöperatie U.A.) on iTunes, something went terribly wrong!
```

**Comment by dsokal** [comment]
@luukschipperheyn do you happen to have an account on Expo Developers Slack? Would you like to help me debug this issue?

**Comment by artemkrynkin** [comment]
same problem on expo-cli@3.12.1
<img width="684" alt="Снимок экрана 2020-02-12 в 15 25 36" src="https://user-images.githubusercontent.com/6913231/74334937-09105380-4dac-11ea-8552-0edfb9c0fd21.png">

**Comment by dsokal** [comment]
Hello guys,
Please install `expo-cli@3.13.0` (`yarn global add expo-cli3.13.0` or `npm i -g expo-cli3.13.0`) and let me know if the issue still exists for you.
Thank you @luukschipperheyn for your help with debugging the issue!

**Comment by JonBergman** [comment]
The error messaging is much better but I am still getting an error.

```
Failed to upload the standalone app to the app store.
Your Apple Developer Account doesn't seem to be on XXXXXXXXXXX team, available teams: . Are you sure you chose the correct account/team?```

My account only has one team and I don't see any documentation on how to indicate a team in expo if that is even needed. I didn't have to specify a team when I uploaded this app the first time.

**Comment by dsokal** [comment]
@JonBergman 
That's a really weird error. 
It's being thrown here - https://github.com/expo/expo-cli/blob/master/packages/traveling-fastlane/actions/resolve_itc_team_id.rb#L18
Unless you redacted the error message your Apple Developer Account doesn't seem to be on any team `... team, available teams: . Are ...` (note the empty space after "available teams:")

I have two ideas on how to fix this: 

1. `fastlane` might have done something weird so your session is corrupted. Try deleting the `~/.fastlane/spaceship/` directory and then run `expo upload:ios` again.

2. Find the directory where `@expo/traveling-fastlane-darwin` is installed and edit the `.../node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.12.1-osx/lib/app/resolve_itc_team_id.rb` file (you need to be on the latest version of expo-cli).
 Replace the assignment on line 18 with: 
```
      $result = JSON.generate({
        result: 'failure',
        reason: JSON.generate({ teams: portal_client.teams })
      })
  ```
  Run `expo upload:ios` and let me know what's in the `teams` array.

**Comment by JonBergman** [comment]
@dsokal I tried both of these suggestions but getting the same error message. I verified I am on a team because it's in my list of teams when logging into apple connect.

**Comment by dsokal** [comment]
@JonBergman do you have an account on the Expo Developers Slack? Could you please help me debug this?

**Comment by reactNDeveloper** [comment]
Hi, I have this issue and can't upload .ipa file to testflight more than 2 days, how can you help me?

**Comment by EvanBacon** [comment]
`expo upload:ios` has been deprecated in favor of `eas submit -p ios` which does iOS uploads in the cloud to circumvent the many local issues users have encountered with Fastlane.
