### ISSUE TITLE
`Missing app.json` error message needs to be improved when file exists but only with react-native init keys

### ISSUE THREAD

**Issue by pensierinmusica** [expo/expo-cli#154]
Hi,

When I try to open with Expo (v2.19.2) an app that I created a few days ago with [`https://github.com/react-community/create-react-native-app`](https://github.com/react-community/create-react-native-app) it gives me this error message:

```sh
Error: Missing app.json
```

The problem though is that an `app.json` file actually exists in the project's root folder. Any idea what should be causing this and how to get it working?

Thx!

**Comment by Tiiso** [comment]
> Hi,
> 
> When I try to open with Expo (v2.19.2) an app that I created a few days ago with [`https://github.com/react-community/create-react-native-app`](https://github.com/react-community/create-react-native-app) it gives me this error message:
> 
> ```shell
> Error: Missing app.json
> ```
> 
> The problem though is that an `app.json` file actually exists in the project's root folder. Any idea what should be causing this and how to get it working?
> 
> Thx!

I have ran into the same problem.
These are the commands I used:

- yarn global add create-react-native-app@1.0.0
- create-react-native-app
- yarn start

**Comment by webdevbyjoss** [comment]
Now when `create-react-native-app ` is deprecated, I've got this issue with Expo CLI.

Just followed this official guide on a website
https://facebook.github.io/react-native/docs/getting-started

```
npm install -g expo-cli
expo init AwesomeProject
expo eject
```

Result:
```
$ expo eject
Missing app.json. See https://docs.expo.io/
There is an error with your project. See above logs for information.
Set EXPO_DEBUG=true in your env to view the stack trace.
⠋ Making sure project is set up correctly...
```

Seams like the most common application setup in React Native is broken in latest version.

**Comment by fson** [comment]
Closing this issue, as the original problem has been fixed some time ago, i.e. the error message is now something like this:
```
Property 'expo' in app.json is not an object. Please make sure app.json includes a managed Expo app config like this: {"expo":{"name":"My app","slug":"my-app","sdkVersion":"..."}}
```
