### ISSUE TITLE
Unable to use --config flag

### ISSUE THREAD

**Issue by CristyTarantino** [expo/expo-cli#1542]
Unable to use --config flag as I used to in previous versions.

When running `expo start --config app/my-red-app.js` I get error:

```
Error: Cannot find the project's `slug`. Please add a `name` or `slug` field in the project's `app.json` or `app.config.js`). ex: `"slug": "my-project"`
    at Object.getPublishInfoAsync (/@expo/xdl@57.5.1/src/Exp.ts:262:11)
    at manifestHandler (/@expo/xdl@57.5.1/src/Project.ts:2091:31)
```

If I just move the manifest file in the root, the app starts just fine.
Unfortunately due to the nature of my project I need that flag working.

## Environment

  Expo CLI 3.12.1 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.6.1 - /usr/local/bin/zsh
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.1
      react: ^16.10.2 => 16.12.0
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^4.0.6 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.12.1

Problem with any iPhone version on simulator.

**Comment by rakirox** [comment]
+1
expo-cli: 3.12.1

**Comment by EvanBacon** [comment]
Could you please supply the contents of `app/my-red-app.js`

**Comment by EvanBacon** [comment]
Really sorry for the inconvenience, I've created a fix and added some tests to ensure this doesn't happen again. https://github.com/expo/expo-cli/pull/1545
