### ISSUE TITLE
[next-adapter] Expo web breaks when installing the next adapter

### ISSUE THREAD

**Issue by maggo** [expo/expo-cli#1544]
## Description

After installing next support (`yarn add -D @expo/next-adapter` & `yarn next-expo` the Expo web target doesn't compile anymore with an error message. This is caused by the babel preset [`babel-preset-expo`](https://github.com/expo/expo/tree/master/packages/babel-preset-expo), removing it fixes the build for Expo web.

## Expected Behavior

Both nextjs and Expo web targets should work side-by-side

## Observed Behavior

nextjs works, Expo web is broken with following error message:

```
 web  Failed to compile.
../node_modules/react-error-overlay/lib/index.js
Module not found: Can't resolve '@babel/runtime-corejs2/core-js/array/from' in '/Users/maggo/.config/yarn/global/node_modules/@expo/webpack-config/node_modules/react-error-overlay/lib'
```

**Comment by EvanBacon** [comment]
This use-case could be really difficult to support and maintain. One possible approach would be to set an environment variable and toggle the babel config based on that variable:

```js
cosnt getenv = require('getenv');

module.exports = function(api) {
  const imUsingNextJS = getenv.boolish('IM_USING_NEXT', false);
  return imUsingNextJS ? { presets: ['@expo/next-adapter/babel'] } : { presets: ['babel-preset-expo'] };
```

Then start with `IM_USING_NEXT=true yarn next dev`.
