### ISSUE TITLE
buidling javascript bundle has floating percent

### ISSUE THREAD

**Issue by pmgou** [expo/expo-cli#1546]
## Description

When expo is building a new javascript bundle the percent goes up and down.. is nonsense

## Expected Behavior

I expect that the percentage  of completion won't go back.

## Observed Behavior

When expo is building a new javascript bundle the percent goes up and down.. is nonsense

## Environment

expo-cli 3.12.1

**Comment by brentvatne** [comment]
this is an issue with metro - http://github.com/facebook/metro - we just report the numbers that they give us. my understanding of what is happening is that as a file is transformed it is found to depend on some other files that also must be transformed, and so doing work sometimes ends up in discovery of more work.
