### ISSUE TITLE
Expo App Test the local server

### ISSUE THREAD

**Issue by GayanEranga92** [expo/expo-cli#157]
how to test expo app localhost serve?

**Comment by thg303** [comment]
use the latest version of expo-cli [currently 2.4]
run `expo start` in the project directory. it will run a local server usually on port "19002" - it might be different if that port is in use - 
simply open the metro bundler at "http://localhost:19002", at the side bar at CONNECTION section choose "local" and it will run on your locally attached device or the emulator. 

ps: it will install expo client app on the device/emulator if it was not previously installed.

**Comment by jakubste** [comment]
Please elaborate more if you still have a problem.
