### ISSUE TITLE
[client] Error running app on iPhone XS

### ISSUE THREAD

**Issue by garrett-gottlieb** [expo/expo-cli#1571]
## Description

After running `expo build:ios` and installing the expo client on iOS, I scan the QR code but when the app opens it comes up with the blank white screen saying "The data couldn't be read because it isn't in the correct format."

The computer at phone are on the same WiFi network.

## Expected Behavior

It should run my app.

## Observed Behavior

```
The data couldn't be read because it isn't in the correct format.
```

## Environment

  Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 10.18.0 - /usr/local/bin/node
      Yarn: 1.19.1 - ~/.yarn/bin/yarn
      npm: 3.5.3 - /usr/local/n/versions/0.12.4/bin/npm
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4

iPhone XS v13.3.1

**Comment by brentvatne** [comment]
hello! try change the connection mode to tunnel, it's possible that your wifi network doesn't allow peers to connect to each other

**Comment by garrett-gottlieb** [comment]
Thanks for the response @brentvatne! I seem to have figured it out. I added `.babelrc` while setting up Jest tests and removing it fixes this issue. I'm guessing it overrides Expo/RN's internal config. Turns out I didn't need it for Jest, but it begs the question: what if one needs to edit the Babel config?

**Comment by brentvatne** [comment]
babel.config.js

**Comment by fson** [comment]
Sounds like this issue is resolved.

**Comment by timtensor** [comment]
Hi , i have a similar problem . It seems to be working for the web in my case

**Comment by DejiAwoniyi** [comment]
I have this same issue just after updating from expo sdk39 to sdk 41
![simulator_screenshot_187D8671-879C-4255-A8E8-6053CC8A2C39](https://user-images.githubusercontent.com/83350689/116699178-2d5e4d00-a9bd-11eb-9346-b148e45489db.png)

**Comment by skittlesaur** [comment]
Any fix for this?
