### ISSUE TITLE
can't scroll up to check the previous errors of execution

### ISSUE THREAD

**Issue by albjeremias** [expo/expo-cli#1573]
## Description

Hi, when i am runnning: ` $ expo start` and i re-spawn the app on android using the 'a' letter, all the output from previous trials disappears, and I can't scroll up to check what happened. This is not very helpful when developing code

## Expected Behavior

I expect that expo-cli would not delete the logs while im developing code.. or at least have some option for it

## Observed Behavior
expo-cli deletes all logs whenever i re-run the code in the device

## Environment

im using expo: 3.13.1

**Comment by brentvatne** [comment]
@fson let's discuss this, ping me about it sometime!

**Comment by EvanBacon** [comment]
You can disable the deletion with `EXPO_DEBUG=true`

**Comment by albjeremias** [comment]
:+1:
