### ISSUE TITLE
push notifications

### ISSUE THREAD

**Issue by conka991** [expo/expo-cli#1574]
Hi there, I just want to ask for some help related to the push notification on android devices using expo client. I was trying to fix the error following the thread described on https://github.com/expo/expo-cli/issues/1389 but I have no succeded. Im still getting "Error: Couldn't get GCM token for device"
The example described in https://snack.expo.io/@charliecruzan/pushnotifications36?platform=android works nice but running the same code locally is not working
My current config running "expo diganostics" is:
  Expo CLI 3.13.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548

Any suggestion is welcome, thanks in advance

**Comment by brentvatne** [comment]
hello! https://forums.expo.io/ is the best place to go for help! good luck!

**Comment by conka991** [comment]
hi there, thanks for your answer and sorry my late aswer. I could find the solution to my problem It was a mismatch name in the google-services.json and the name in a grandle file. Thanks anyway :)
