### ISSUE TITLE
error ! "events.js":167

### ISSUE THREAD

**Issue by daminebenz** [expo/expo-cli#158]
[https://slack-imgs.com/?c=1&url=https%3A%2F%2Fi.gyazo.com%2F26c07d573284ea4d6c2b48eadb8ade2f.png](screenshot of the error)
it shuts down after some serval hours on a screen process on ubuntu 18.04 VPS server

**Comment by achaldesai** [comment]
same issue on localhost

**Comment by brentvatne** [comment]
hey! thanks for the report. tracking it here: https://github.com/expo/expo-cli/issues/519 - this is a tricky one :(
