### ISSUE TITLE
Template lookup always uses npm registry

### ISSUE THREAD

**Issue by gb-rlee** [expo/expo-cli#1586]
Getting error while downloading expo-template-blank with command `expo init <project>`. 

![Screen Shot 2020-02-20 at 9 14 55 AM](https://user-images.githubusercontent.com/39382945/74960621-839b2d80-53c1-11ea-9bce-84f7504fd326.png)

I have npm registry set to something besides `https://registry.npmjs.org`, but it seems like expo-cli is still trying to download from `https://registry.npmjs.org`.

**Comment by brentvatne** [comment]
interesting! i think this is because we use npm's library for looking up packages in the registry: https://github.com/expo/expo-cli/blob/af5a7276c16463dd51b46935dcb9da196457de24/packages/expo-cli/src/commands/init.ts#L149

open to a PR to support other options!

**Comment by gb-rlee** [comment]
@brentvatne I can submit an MR, I have a couple of questions though. 

Are there instructions on how to use the expo-cli from cloned repo?
Are there any restrictions on adding npm packages? (Might add an npm package for detecting if a user's npm config registry has been set)

**Comment by brentvatne** [comment]
@gb-rlee 

> Are there instructions on how to use the expo-cli from cloned repo?

yup! https://github.com/expo/expo-cli/blob/master/CONTRIBUTING.md - after things are set up i use this alias to run the local version:

```
alias local-expo="node ~/coding/expo-cli/packages/expo-cli/bin/expo.js"
```

the path of course depends on where you clone the repo to.

> Are there any restrictions on adding npm packages? (Might add an npm package for detecting if a user's npm config registry has been set)

that's fine, the library should be maintained and minimal though. we should also lock it to a fixed version rather than using `~` and `^` matchers

**Comment by JovialJaghut** [comment]
Please excuse my ignorance, but is there a workaround for this? I have the same issue where I use an internal registry but expo-cli is trying to pull files from the Internet. I apologize for not fully understanding, but do I need to go into certain files (like the init file..?) and pass a registry option to pacote? I've tried a few things and I can't seem to get it to work. Thanks for your help!

**Comment by brentvatne** [comment]
@JovialJaghut - can you explain why this is a problem? your internal registry would not include the expo template projects unless you manually published them there, so how would you initialize a project if not pulling from the public registry?

**Comment by brentvatne** [comment]
a workaround for now would be to do what i describe in the comment above yours - clone the repo locally, modify the code to point to your registry. if you'd like to upstream it you can define an environment variable, like `EXPO_CUSTOM_NPM_REGISTRY` to point pacote to

**Comment by JovialJaghut** [comment]
@brentvatne:

_"modify the code to point to your registry"_

This is what I'm confused about. I'm not sure how to do this.

_"your internal registry would not include the expo template projects unless you manually published them there"_

The internal registry that I use is a clone of the public registry. It contains the templates. I set the registry path globally for NPM, and I have no problem installing packages. But when I try to initialize a project using expo-cli, it still tries to pull the templates from the public NPM registry, which I cannot reach from our internal network. Based on what was said above, I'm still not sure how to point to the right path for expo-cli. I found registry links in some of the files and changed them to point to our internal registry, but it didn't seem to work.

Anyway, I apologize for the confusion and really appreciate your help. Thank you!

**Comment by mdghunaym** [comment]
> @JovialJaghut - can you explain why this is a problem? your internal registry would not include the expo template projects unless you manually published them there, so how would you initialize a project if not pulling from the public registry?

for me I need to use a custom npm registry because I'm behind a cooperate proxy wall. so still there's no way to config the expo-cli to use custom registry?
