### ISSUE TITLE
Dev Tools fails after upgrading Expo CLI

### ISSUE THREAD

**Issue by fson** [expo/expo-cli#159]
Reported by dani-z on Slack, after upgrading Expo CLI from 2.2.0 to 2.3.0, Dev Tools fails to load in the browser:
![image](https://user-images.githubusercontent.com/497214/48075504-0fe50980-e1ec-11e8-858c-8de6bbe4ef6a.png)

The screenshot shows that the browser is trying to request an old version of the JS assets (hash `82640410-a652-42e3-87ad-7643f355d028`) and not the `22998993-25b2-438b-93d3-80f51a0e7b09` in `@expo/dev-tools@0.2.0`.

It seems that this is the old issue we had with npm resetting the modified timestamps of published files to October 26th 1985. (See https://unpkg.com/@expo/dev-tools@0.2.0/build/client/) The result of this is that the browser thinks it has the latest version of the `index.html` file and requests JS assets (from the previous version) specified in it. We previously worked around this by using Yarn to publish, but it seems that Yarn has also started to reset the timestamps now, so we need to fix this in a different way.

**Comment by gusmattos1** [comment]
same problem

**Comment by fson** [comment]
This has been fixed in `expo-cli@2.3.5`.
