### ISSUE TITLE
error Invalid regular expression:

### ISSUE THREAD

**Issue by HarutSargsyan** [expo/expo-cli#1591]
I have an issue when I write npm start command in cmd prompt, it returns following error...

error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class.

Metro Bundler process exited with code 1
Set EXPO_DEBUG=true in your env to view the stack trace.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `expo start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sveta\AppData\Roaming\npm-cache\_logs\2020-02-22T20_09_19_783Z-debug.log

**Comment by brentvatne** [comment]
https://github.com/expo/expo-cli/issues/1074#issuecomment-559220752
