### ISSUE TITLE
issues with spawning expo start and stopping expo client

### ISSUE THREAD

**Issue by FrederickEngelhardt** [expo/expo-cli#1596]
## Description

I am using [NVM](https://github.com/nvm-sh/nvm/blob/master/README.md)
Whenever I start expo I have to run `rm -rf .expo` to remove the expo folder from the project to successfully start the expo client

Also tried uninstalling nvm and using node 12 and yarn and got the same error.

This bug has existed for me since SDK 32 (sorry for delayed report)

## Expected Behavior

What action did you perform, and what did you expect to happen?

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the _full terminal output and error message_ in this code block:

Whenever expo-cli is stopped it runs into this error.
```
Stopping packager...
› Closing Expo server
› Stopping Metro bundler
Error: spawn pgrep EAGAIN
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
error Command failed with exit code 1.
```

## Environment

```
  Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.9.0 => 16.9.20
      @types/react-native: ^0.60.15 => 0.60.31
      expo: ^36.0.0 => 36.0.2
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4
    npmGlobalPackages:
      expo-cli: 3.13.1

```

- Phone/emulator/simulator platform, model and version: simulator 13.3

## Reproducible Demo
1. Install NVM
1. nvm install 12
1. nvm alias default 12
1. nvm use 12
1. ```brew install yarn --ignore-dependencies```
1. `yarn global add expo-cli`
1. `expo init` > chose any option
1. `yarn start`
1. CTRL+C to quit out (notice you have the Process.ChildProcess error and the quit hangs for about 5-10 seconds
1. `yarn start` notice that you cannot start. You will receive another Process.ChildProcess error. Using the command `rm -rf ./expo` will allow expo to start again.

**Comment by brentvatne** [comment]
this is not reproducible on my machine by using the same set of steps. can you share the contents of the .expo directory that you have when you end up in a state where you cannot start it?

**Comment by diegolaciar** [comment]
+1 Exactly the same issue here. But using npm instead of yarn

**Comment by brentvatne** [comment]
@diegolaciar https://github.com/voidcosmos/npkill/issues/25#issuecomment-522968839

**Comment by diegolaciar** [comment]
Hi @brentvatne,

thanks , but didn't work.

my setting was:
```
$   launchctl limit maxfiles
	maxfiles    256            unlimited
```
I did change the setting to:
```
$  launchctl limit maxfiles
	maxfiles    65536          200000
```

But the issue persist.

I just  execute  "expo start" , then, I kill the process with CTRL+CMD  and shows that error.

**Comment by swalker326** [comment]
+1 having the same problem. 

```
› Closing Expo server
› Stopping Metro bundler
Error: spawn pgrep EAGAIN
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

```
=> expo --version
3.22.3
```

```
=> node -v
v14.5.0
```

Mac
Iterm
Fish Shell

**Comment by FrederickEngelhardt** [comment]
Reference [here](https://github.com/expo/expo-cli/issues/3262): It may be related to `./expo/packager-info.json`

**Comment by EvanBacon** [comment]
The [new Expo CLI](https://blog.expo.dev/the-new-expo-cli-f4250d8e3421?gi=73ca3904668b) only uses `packager-info` for tunnel, everything else is managed in memory.
