### ISSUE TITLE
Consider passing --no-interactive when starting react-native server

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#1607]
Related: https://github.com/react-native-community/cli/pull/1027

My only concern here is we need to be careful not to pass in this flag when it isn't supported, or the server will fail to start, eg:

```
╰─$ react-native start --fake-config-opt
error: unknown option `--fake-config-opt'
```

**Comment by fson** [comment]
It seems that this won't be necesssary once https://github.com/expo/expo-cli/issues/1434 is done, since we won't start the CLI, only Metro and the dev server middleware.

**Comment by EvanBacon** [comment]
Fixed in SDK 40 or now with `EXPO_USE_DEV_SERVER=true`.
