### ISSUE TITLE
Ctrl+C does not gracefully stop Expo server in PowerShell and Windows CMD

### ISSUE THREAD

**Issue by srmagura** [expo/expo-cli#1608]
## Description

When `expo start` is stopped with `Ctrl+C` in PowerShell or the Windows Command Prompt, the server does not print "Closing Expo server; Stopping Metro bundler" before terminating. The only problem this causes is that, when `expo publish` runs, it does not start up Expo server again, because it thinks it is already running. Deleting the `.expo` directory before running `expo publish` makes it start Expo server as expected.

## Expected Behavior

Press `Ctrl+C` to exit `expo start`. It should print
```
Stopping packager...
[16:44:25] › Closing Expo server
[16:44:25] › Stopping Metro bundler
Packager stopped.
```
Then run `expo publish`. It should start a new Expo server process because one is not running. I get this behavior when running Expo through git bash on Windows or through Terminal on OS X.

## Observed Behavior

Pressing `Ctrl+C` causes Expo server to stop without printing anything. `expo publish` produces the output
```
Publishing to channel 'test'...
Building iOS bundle
connect ECONNREFUSED 127.0.0.1:19001
Set EXPO_DEBUG=true in your env to view the stack trace.
```

## Environment
I have been having this problem consistently for several months, i.e. the problem is not specific to this `expo-cli` version.

```
  Expo CLI 3.13.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
```

## Reproducible Demo

Reproducible in a project created via `expo-init` with `expo-template-blank`.

**Comment by snsie** [comment]
I'm having this issue as well. I can still see services running in the resource monitor even if I close the terminal. I have to log out to actually kill everything.

**Comment by brentvatne** [comment]
hi there! we would love it if you folks could help us to solve this issue, a PR would be very welcome. until then, it seems like git bash or WSL is a good solution for windows users.

**Comment by Wheeler-Christian** [comment]
A fix that I found is that you shut down both your app and the expo app (shut down an app by swiping up on the app and let go, so that the app disappears upwards) and then it actually shuts down the app correctly.
