### ISSUE TITLE
expo init error Uncaught Error [Error: EPERM: operation not permitted

### ISSUE THREAD

**Issue by SenikFarsyan** [expo/expo-cli#1619]
Hey everyone.
i have just installed expo cli globally , version 3.13.1
when trying to init project gives error 
```
Uncaught Error [Error: EPERM: operation not permitted, open 'C:\Users\Acer\.expo\PATH'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'open',
  path: 'C:\\Users\\Acer\\.expo\\PATH'
}
```
i am using windows 10 node -v 12.16.1 npm v - 6.13.4

**Comment by brentvatne** [comment]
this is a problem with your npm configuration. you should google "EPERM: operation not permitted" and find a solution that works for you. eg: https://stackoverflow.com/questions/34600932/npm-eperm-operation-not-permitted-on-windows

**Comment by vijaycseng** [comment]
After Following what @brentvatne mentioned in his post don't forget to restart ur computer.

**Comment by MatiSera** [comment]
@SenikFarsyan do you fix this problem? It's happening the same for me on windows

**Comment by TedisAgolli** [comment]
This error just happened to me on Windows Git Bash. 
It does not happen when using Powershell. 
I wish I had more information than that but hope it helps a bit.
