### ISSUE TITLE
remove unnecessary logs from `expo eject` output

### ISSUE THREAD

**Issue by esamelson** [expo/expo-cli#162]
Partial feedback from https://github.com/expo/universe/issues/2604#issuecomment-407228879 .

Right now, when running `expo eject` a lot of output is logged during the eject process for both iOS and Android. Most of it is not relevant to people who are just ejecting, especially the `buildPhase` logs which are meant for turtle. Can we hide most of this so that only important/relevant output is logged to the console?

e.g. `{ buildPhase: 'running shell app modifications' } 'Warning: No config file specified.’` is unnecessary and actually confusing, because it seems like something has gone wrong.

**Comment by fson** [comment]
Also related: #208

**Comment by fson** [comment]
Fixed in #267.
