### ISSUE TITLE
2FA step fails with Authentication with Apple Developer Portal failed! Reason: Unknown reason, raw: "Unauthorized Access"

### ISSUE THREAD

**Issue by sbrighiu** [expo/expo-cli#1631]
Hi guys.

I'm trying to create an iOS build through expo. When i start `expo build:ios --release-channel prod`, it asks for my Apple ID and password, and after for the 2FA. I enter all the credentials, I get the message, I input the code and it fails with `Authentication with Apple Developer Portal failed! Reason: Unknown reason, raw: "Unauthorized Access" [Returned: code: 1  signal: null]`

Not really sure what i'm supposed to do to fix it. I tried:
- several times until Apple stopped sending messages to my phone and suggested I just use the last one provided
- my account is linked to multiple Apple Developer Teams, but I accepted every terms and condition/policy update documents present on my personal account, so that should not be an issue
- I can clearly log in to my account using 2FA
- I've tried adding the clear credentials params to the expo command, but I guess that only works if you manage to log in or were previously logged in

Any advice?

Expo CLI 3.13.1 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.0 - /usr/local/bin/node
      npm: 6.13.7 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: 33.0.1 => 33.0.1 
      @types/react: ^16.9.0 => 16.9.21 
      @types/react-native: ^0.60.15 => 0.60.31 
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.13.1

**Comment by sbrighiu** [comment]
Here is a preview of what I see in the terminal.
`
Checking if there is a build in progress...

Please enter your Apple Developer Program account credentials. These credentials are needed to manage certificates, keys and provisioning profiles in
your Apple Developer account.
The password is only used to authenticate with Apple and never stored.
? Apple ID: XXXXXXXXXXXXXX
? Password (for XXXXXXXXXXXXXX): [hidden]
Trying to authenticate with Apple Developer Portal...
Available session is not valid any more. Continuing with normal login.
Two-factor Authentication (6 digits code) is enabled for account 'XXXXXXXXXXXXXX'
More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915

If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

(Input `sms` to escape this prompt and select a trusted phone number to send the code as a text message)

(You can also set the environment variable `SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER` to automate this)
(Read more at: https://github.com/fastlane/fastlane/blob/master/spaceship/docs/Authentication.md#auto-select-sms-via-spaceship-2fa-sms-default-phone-number)

Please enter the 6 digit code:
XXXXXX
Requesting session...
Authentication with Apple Developer Portal failed!
Reason: Unknown reason, raw: "Unauthorized Access"`

**Comment by benm93** [comment]
I'm having exactly the same issue. I was able to run expo build:ios yesterday with no issues.

**Comment by sbrighiu** [comment]
Still not working. Updated to 3.13.2.

> ...
> 
> Please enter the 6 digit code:
> ⠧ Trying to authenticate with Apple Developer Portal...
> 
> ✖ Authentication with Apple Developer Portal failed!
> Reason: Unknown reason, raw: "Unauthorized Access"

Something that is new is that Trying to authenticate with Apple Developer Portal... message is loading when i am asked to input 6 digit code. If I enter it, it still does not work. Also it does not seem to stop loading.

**Comment by tedglee** [comment]
The same happens to me if I use the "Account Holder" Apple ID. If I use a developer account (with admin/certificate management) access, it works, even with 2FA enabled.

**Comment by quinlanj** [comment]
Given the timing of when this issue was opened, it could be related to https://github.com/fastlane/fastlane/issues/16108 and is suspected to be related to a change in Apple's servers. A workaround has been proposed [here](https://github.com/fastlane/fastlane/issues/16108#issuecomment-594049615), where you choose the `sms` option and the *second* sms contains the valid code(?!)

**Comment by jesiegel1** [comment]
@quinlanj I’m currently working on a fix for https://github.com/fastlane/fastlane/issues/16108, PR should be ready soon

**Comment by YoshiYo** [comment]
Same bug here. I'm back to 3.13.1 and it works well.

**Comment by ddmaster** [comment]
Have same bug.
Switch to 3.13.1 doesn't help.

**Comment by pachun** [comment]
Neither 3.16.1 nor 3.13.1 avoids this problem in my experience. I am in the USA.

**Comment by YoshiYo** [comment]
3.13.1 was for me the last version where Apple auth worked. Maybe try to "find" the current version where your auth worked well. On my side, my gitlab-ci and laptop point on 3.13.1 exactly. I do not upgrade since this issue is opened (I'm affraid of this bug aswell).

**Comment by raynux** [comment]
In my case, setting `SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER` solved the issue, with 3.15.5

**Comment by GuillaumeRZ** [comment]
Same problem here with Expo version `3.17.11`

**Comment by 16oh4** [comment]
I am having the same problem

```
Authenticating to Apple Developer Portal...
Authentication with Apple Developer Portal failed!
Reason: Unknown reason, raw: "Unauthorized Access"
Error: Reason: Unknown reason, raw: "Unauthorized Access"
    at runAction (C:\expo-cli@3.17.20\src\appleApi\fastlane.ts:28:17)     
    at processTicksAndRejections (internal/process/task_queues.js:97:5)   
    at authenticate (C:\expo-cli@3.17.20\src\appleApi\authenticate.ts:48:40)
    at Context.ensureAppleCtx (C:\expo-cli@3.17.20\src\credentials\context.ts:56:24)
    at IOSBuilder.bestEffortAppleCtx (C:\expo-cli@3.17.20\src\commands\build\ios\IOSBuilder.ts:99:14)
    at IOSBuilder.prepareCredentials (C:\expo-cli@3.17.20\src\commands\build\ios\IOSBuilder.ts:116:5)
    at IOSBuilder.run (C:\expo-cli@3.17.20\src\commands\build\ios\IOSBuilder.ts:46:7)
    at IOSBuilder.command (C:\expo-cli@3.17.20\src\commands\build\BaseBuilder.ts:29:7)
    at Command.<anonymous> (C:\expo-cli@3.17.20\src\exp.ts:85:7)
```

**Comment by whockey** [comment]
I think this has to do with some fraud detection issues on Apple's side. Try switching to a VPN or to different IPs. I was getting this error consistently when tethered and on my home network, but when I switched to a corporate VPN it went back to normal.

**Comment by Johnfredadams** [comment]
A Similar issue here in the uk. Have tried on multiple platforms - OSX gives me `failed to prepare credentials` Windows gives me `raw: "Unauthorized Access"`. I have 2FA. 2FA is also unreliable. Sometimes window expo-cli will give an unauthorized error whilst 2FA is still underway.

**Comment by nvbach91** [comment]
> The same happens to me if I use the "Account Holder" Apple ID. If I use a developer account (with admin/certificate management) access, it works, even with 2FA enabled.

I just tried your suggestion and it worked. The reason might be that I created an organization from my original Apple ID and it is now the account holder. All I did was:
1) Go to appstoreconnect.apple.com
2) Users and Access
3) Create new user with Developer role
4) Use that new User with expo-cli

Note: 2FA is not configured for that new account

Setup:
- windows 10
- expo-cli 3.20.1
- sdkVersion 36.0.0

```
Authenticating to Apple Developer Portal...
Authenticated with Apple Developer Portal successfully!
Only 1 team associated with your account, using Apple Team with ID: XXXXXXXXXX
Fetching available credentials
√ App ID found on Apple Developer Portal.
√ Getting Distribution Certificates from Apple...
√ Successfully validated Distribution Certificate against Apple Servers
√ Getting Push Keys from Apple...
√ Successfully validated Push Key against Apple Servers
| Getting Provisioning Profile info from Apple's Servers...
√ Successfully fetched Provisioning Profile YYYYYYYYYY from Apple Servers
√ Configuring existing Provisioning Profiles from Apple...
Successfully configured Provisioning Profile ZZZZZZZZZZ on Apple Servers with Distribution Certificate WWWWWWWWWW
Successfully assigned Provisioning Profile to @user/awesome-app (com.awesomeness.app)
```

**Comment by tsuz** [comment]
For a workaround, this is what I did [according to this comment](https://github.com/fastlane/fastlane/issues/16108#issuecomment-594049615)

<img width="412" alt="スクリーンショット 0032-05-09 2 04 38" src="https://user-images.githubusercontent.com/6927131/81430036-b6bbb480-9199-11ea-8da1-799e737a28ea.png">

> Please enter the 6 digit code

sms

> Please select a trusted phone number to send code to:
1. +81.... 17

1

> Successfully requested a text message to +81....17
Please enter the 6 digit code

123456

**Comment by rstumpe** [comment]
@tsuz This is exactly what worked here, too. My apple account sends me an sms per default. This sms does not work with the failure described above. if I use your method, I get a second sms. this sms does work.

**Comment by mrtwebdesign** [comment]
## Description

Not able to authenticate with Apple Developer Portal when trying to build an archive(ipa) for distribution using `expo build:ios`

## Expected Behavior

After entering password, the project is bundled and sent to expo servers for build process

## Observed Behavior

I would get an error message telling me authentication failed. I have during retries entered the incorrect password once, but error details were not the ones I'm copying below.
Sometimes I would get an OS level alert with the 6-digit code. This was sometimes accompanied by a terminal request to type in the code, but not always as was the case below.

```
Authenticating to Apple Developer Portal...
Available session is not valid any more. Continuing with normal login.
Authentication with Apple Developer Portal failed!
Reason: Unknown reason, raw: "Unauthorized Access"
Error: Reason: Unknown reason, raw: "Unauthorized Access"
    at runAction (/Users/Matthew/.nvm/versions/node/v10.20.1/lib/node_modules/expo-cli/src/appleApi/fastlane.ts:28:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

## Environment

  Expo CLI 3.21.5 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.20.1 - ~/.nvm/versions/node/v10.20.1/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v10.20.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.0.7 => 3.0.9 
    npmGlobalPackages:
      expo-cli: 3.21.5

I develop on the simulator: iPhone 8 iOS 13.5
and sometimes an actual device: iPhone 11 running iOS 13.5

## Reproducible Demo

I'm able to reproduce it with `expo build:ios`

**Comment by mrtwebdesign** [comment]
I got out my old MBP and synced up my repo, ran `expo build:ios` in the terminal. It was running an old version, 3.0.9. The build process went very smooth. I did have to login to expo in the terminal, but that was it. I'm going to see if I can uninstall expo-cli and install an older version on my main development machine. At least I can get app published again.

**Comment by mrtwebdesign** [comment]
I can verify 3.0.9 works on the machine that wouldn't authenticate before.
`npm -g uninstall expo-cli --save`
then
`npm install expo-cli@3.0.9 --global`
I'm sure there are more recent versions that may do the trick, but that was the one installed on my other system. I'll be looking out for a new version of expo-cli and try it when it's available.

**Comment by tomfinney** [comment]
@mrtwebdesign Hi, thanks for that. I was having issues on `3.19.2` just error in terminal after logging into an Apple dev account. `3.0.9` seems to work relatively flawlessly

**Comment by stonebinox** [comment]
Is there an update on this issue? This is still very persistent and easily reproducible. I've been through multiple threads and none of the alternatives worked and I cannot downgrade my expo-cli to an older version for other reasons just to get this to work.

**Comment by lminggvick** [comment]
(window 10)

I'm having the same problem, and I haven't solved it so far.

I tried below methods

```
1. run expo build with powerShell
2. ... with unbuntu on windows
3. using expo version 3.21.5 / 3.0.9
```

However, the same problem occurs.. Is there any case that solved this problem? help :( ...

**Comment by asherccohen** [comment]
This is how I resolved it:

- in wsl2 run the build command and authenticate with 2fa, it will ask for a 6 digits code, but you can type 'sms' to verify it is sent to the right number.
- once authenticated it creates a session, the process continues but I get stuck at metro non being called, which gives me an error referring to 127.0.0.1:1900 not seeing the webserver.
- at this point clean your .expo folder with "rm -r", open PowerShell and run build command again, authentication will work without asking for 2fa and metro will be called correctly.

Hope this helps.

**Comment by stonebinox** [comment]
For those on a Mac and running expo-cli version 3.21.5 and greater, this is what worked for me: I turned on my VPN and used a US IP address, ran `expo build:ios -c`, and it worked. I'm not sure why this should be an issue in the first place since our authentication as devs should suffice, but this did the trick for me. Hope this helps!

**Comment by stonebinox** [comment]
> Have same bug.
> Switch to 3.13.1 doesn't help.
> 
> Upd: suddenly works with USA VPN for me

This is right - for some reason, this works.

**Comment by theutkarshsoni** [comment]
@tsuz  @rstumpe I did the same. I got two different 6 digit codes and I use the latter one but the error remains the same. I created my Apple account but didn't pay for Apple Developer Program. Do you think that it is the reason? I don't want to upload the app to the App Store. I just want the .ipa file. Can anyone help me out?

**Comment by theutkarshsoni** [comment]
@tsuz @rstumpe I believe you had paid account on Apple. After a short research, I found that without a paid account you can't build a .ipa file. 

If anyone wants to know more, please checkout below link:
https://github.com/expo/expo/issues/1528

**Comment by lminggvick** [comment]
An attempt to build into `wsl` made some progress for me. 

Now, After entered my apple id and pw, I can proceed to the `2FA` stage.

But, The "Unauthorized Access" issue continues. T^T.

Is there any other way I can try?

```
Checking if there is a build in progress...

Removed existing credentials from expo servers
Please enter your Apple Developer Program account credentials. These credentials are needed to manage certificates,
keys and provisioning profiles in your Apple Developer account.
The password is only used to authenticate with Apple and never stored.
? Apple ID: cs@zip84.com
? Password (for cs@zip84.com): [hidden]
Trying to authenticate with Apple Developer Portal...
Two-factor Authentication (6 digits code) is enabled for account 'cs@zip84.com'
More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915

If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

(Input `sms` to escape this prompt and select a trusted phone number to send the code as a text message)

(You can also set the environment variable `SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER` to automate this)
(Read more at: https://github.com/fastlane/fastlane/blob/master/spaceship/docs/Authentication.md#auto-select-sms-via-spaceship-2fa-sms-default-phone-number)

Please enter the 6 digit code:
sms
Please select a trusted phone number to send code to:
1. +82 •••-••••-••28
?  1
Authentication with Apple Developer Portal failed!
Reason: Unknown reason, raw: "Unauthorized Access" <<
Set EXPO_DEBUG=true in your env to view the stack trace.
```

**Comment by theutkarshsoni** [comment]
@lminggvick Did you enroll for Apple Developer Program? If no, then you can't build. If yes, then please do check your password.

**Comment by lminggvick** [comment]
@theutkarshsoni Apple developer account is registered and paid payment is registered. You can log in to the Apple Connect and Apple sites normally, and you can log in by receiving a code from a mobile phone registered with 2FA authentication.

By the way, in the part that authenticates to build expo in the cli environment, the following message is displayed even if 6 digit code is entered.

```
Reason: Unknown reason, raw: "Unauthorized Access"
```


I hope the problem is resolved : ( .............

**Comment by quinlanj** [comment]
Can you guys upgrade to `expo-cli@3.21.10` or later and see if the problem is resolved? It's got a version of traveling-fastlane with this promising [fix](https://github.com/fastlane/fastlane/pull/16162)

**Comment by terryhowelljr** [comment]
Any update on this?  I have the same issue while running expo build:ios with GitHub Actions.  I even tried a different developer account. It appears Apple doesnt trust the Github Ubuntu instance and is forcing 2FA. 

`name: Expo Build IOS
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-cache: true
      - run: |
          cd finzly
          npm install
          expo build:ios --apple-id ${{ secrets.APPLE_ID }} --non-interactive --no-wait
        env:
          EXPO_APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}`

**Comment by quinlanj** [comment]
@terryhowelljr can you upgrade your expo-cli and report back whether the issue still persists

**Comment by tomasgvivo** [comment]
I'm having a similar issue:
```
Checking if there is a build in progress...

Configuring credentials for tomasgvivo in project opinaia_local
Authenticating to Apple Developer Portal...
Two-factor Authentication (6 digits code) is enabled for account '*********@******.net'
More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915

If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

Authentication with Apple Developer Portal failed!
Reason: Unknown reason, raw: "invalid byte sequence in US-ASCII"
Error: Reason: Unknown reason, raw: "invalid byte sequence in US-ASCII"
    at runAction (/usr/local/lib/node_modules/expo-cli/src/appleApi/fastlane.ts:28:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at authenticate (/usr/local/lib/node_modules/expo-cli/src/appleApi/authenticate.ts:47:40)
    at Context.ensureAppleCtx (/usr/local/lib/node_modules/expo-cli/src/credentials/context.ts:72:24)
    at IOSBuilder.bestEffortAppleCtx (/usr/local/lib/node_modules/expo-cli/src/commands/build/ios/IOSBuilder.ts:87:14)
    at IOSBuilder.prepareCredentials (/usr/local/lib/node_modules/expo-cli/src/commands/build/ios/IOSBuilder.ts:153:5)
    at IOSBuilder.run (/usr/local/lib/node_modules/expo-cli/src/commands/build/ios/IOSBuilder.ts:60:7)
    at IOSBuilder.command (/usr/local/lib/node_modules/expo-cli/src/commands/build/BaseBuilder.ts:46:7)
    at Command.<anonymous> (/usr/local/lib/node_modules/expo-cli/src/exp.ts:80:7)
```

**Comment by tomasgvivo** [comment]
Any update on this issue?

**Comment by stonebinox** [comment]
> Any update on this issue?

I was able to get past this issue by using a VPN and ensuring that it works through a US IP address. I had no glitches whatsoever and it works with the first authentication code prompt on my device. `expo upload:ios` works without a VPN though - somehow it's only `expo build:ios` that seems to have trouble.

**Comment by tomasgvivo** [comment]
@stonebinox Didn't worked for me... I was building from my home pc in Argentina. So I tried to build using a CI Pipeline on a US server and resulted in the same error.

**Comment by AlbertoLopSie** [comment]
> @stonebinox Didn't worked for me... I was building from my home pc in Argentina. So I tried to build using a CI Pipeline on a US server and resulted in the same error.

Same problem.. same location... Lo resolviste?

**Comment by tomasgvivo** [comment]
> > @stonebinox Didn't worked for me... I was building from my home pc in Argentina. So I tried to build using a CI Pipeline on a US server and resulted in the same error.
> 
> Same problem.. same location... Lo resolviste?

@AlbertoLopSie No, because I stopped trying (low priority project). Suerte.

**Comment by EvanBacon** [comment]
I've removed Fastlane in the latest version `expo-cli@4.1.0`. Authentication is now done in JS and surfaces more error information. If the problem persists on ^4.1.0, please open a new issue.
