### ISSUE TITLE
expo-cli install fails for dependency analytics-node@3.3.0

### ISSUE THREAD

**Issue by jamesrperkins** [expo/expo-cli#1635]
##  Description
Attempting a fresh install of expo-cli it fails due to a dependency version mismatch

## Expected Behavior

npm install -g expo-cli (per the documentation) 

## Observed Behavior
The following error is returned
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for analytics-node@3.3.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@expo/xdl'
npm ERR! notarget 
```

## Environment

MACOS Catalina
Node v10.16.3

**Comment by brentvatne** [comment]
seems like an intermittent bug with npm registry, this package and version has existed for 2 years - see the versions tab on https://www.npmjs.com/package/analytics-node
