### ISSUE TITLE
dev tools improvements for ExpoKit

### ISSUE THREAD

**Issue by esamelson** [expo/expo-cli#164]
Partial feedback from https://github.com/expo/universe/issues/2604#issuecomment-407228879 .

(from Brent's notes)
- Ran `expo start` and cmd+click to open dev tools
	- Any reason for not having interactive prompt?
	- Can’t restart the app and clear cache from expo-cli GUI
	- Should the dev-tools UI change for detached apps? Still see open in simulator and device buttons for example. URL not to useful (http://url.brentvatne.ca/ZRJqSd). Rest of the UI seems good though.

**Comment by brentvatne** [comment]
rip expokit
