### ISSUE TITLE
npm install: Failed at the core-js postinstall script

### ISSUE THREAD

**Issue by MrSquaare** [expo/expo-cli#1646]
## Description

During the installation of expo-cli via the command `sudo npm install -g expo-cli`, I encounter a problem in the postinstall of the core-js dependency

## Expected Behavior

expo-cli installation

## Observed Behavior

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! core-js@2.6.11 postinstall: `node -e "try{require('./postinstall')}catch(e){}"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the core-js@2.6.11 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

[Complete log](https://github.com/expo/expo-cli/files/4302129/debug.log)

## Environment

Ubuntu 19.10

Node:
Version: v12.16.1
Installation: snap

npm:
Version: 6.13.4

## Reproducible Demo

1. `sudo npm install -g expo-cli`

**Comment by brentvatne** [comment]
you should not install any npm package with sudo :) 

if you are doig this ebcause of `EACCES` errors with npm you may want to read this instead: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
