### ISSUE TITLE
Expo-Cli 3.13.2 won't let me build ios app and throws 404 error

### ISSUE THREAD

**Issue by edumorlom** [expo/expo-cli#1647]
## Description
`expo build:ios` throws an error **Request failed with status code 404** when I use the following PNG in my build directory.

![swipeup-gif](https://user-images.githubusercontent.com/11444894/76150004-c15fad80-6073-11ea-922a-5f40192e9d52.png)

## Expected Behavior
Should build without a problem, it shouldn't ask me to login to my Apple Developer account every time I build.

What action did you perform, and what did you expect to happen?
`expo build:ios` should build without a problem but instead throws a 404 error.

## Observed Behavior
Weirdly, when I run the build command. It makes me sign into my Apple Developer account. Always.... It never used to do this, it would always remember my account. After downgrading to 3.13.1 the issue no longer happens and I am able to build the exact same directory without any issues. It seems to be with 3.13.2 Also, if I removed that specific PNG, it builds just fine.

What actually happened when you performed the above actions?
```
Publishing to channel 'default'...

? Do you have access to the Apple Account that owns the app with the bundle identifier edu.fiu.moms-infants-healthy?

..............

Building iOS bundle
Building Android bundle
Analyzing assets
Uploading assets
Uploading /swipeup-gif.png
Request failed with status code 404

```

**Comment by edumorlom** [comment]
Uploading any other image works, it seems to be related to that image in specific... That's the weird part. Also, why does it make me log in to the Apple Developer account anytime I build with this new version? Downgrading to 3.13.1 works just fine.

**Comment by fnfilho** [comment]
I am also having issues with 3.13.2 and it is throwing a 404 error. Was able to downgrade to 3.13.1 and have the build work fine again.

```
Nery:app fernando$ expo ba
Checking if there is a build in progress...


? Would you like to upload a keystore or have us generate one for you?
If you don't know what this means, let us handle it! :)
 false
Unable to find an existing Expo CLI instance for this directory, starting a new one...
Starting Metro Bundler on port 19001.
Successfully ran `adb reverse`. Localhost URLs should work on the connected Android device.
Tunnel ready.
Publishing to channel 'default'...
Building iOS bundle
Finished building JavaScript bundle in 2553ms.
Building Android bundle
Analyzing assets
Building JavaScript bundle [====================================================================================================] 100%Finished building JavaScript bundle in 1793ms.
Finished building JavaScript bundle in 1080ms.
Finished building JavaScript bundle in 1127ms.
Uploading assets
Uploading /assets/images/latam@1x.png
Uploading /assets/images/latam@2x.png
Uploading /assets/images/latam@3x.png
› Closing Expo server
› Stopping Metro bundler
Request failed with status code 404
```

diagnostics

```
  Expo CLI 3.13.2 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/opt/node@10/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/opt/node@10/bin/npm
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-navigation: ~4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.13.2
```

**Comment by serusko** [comment]
same here, 

```
Building iOS bundle
Building Android bundle
Analyzing assets
Uploading assets
Uploading /src/icon.png
```
produces  `error 404`

after downgrade back to 3.13.1 its working

**Comment by ionTea** [comment]
Same issue for me

**Comment by eladhayun-jul-avo** [comment]
Same issue for me....

**Comment by wodin** [comment]
From the forums:

https://forums.expo.io/t/build-android-fails-if-assets-have-changed/34284/7?u=wodin

> [soyjavi](https://forums.expo.io/u/soyjavi)
> 
> That is not the issue, the issue is if you change any of the assets (icon, splash…) You will get the 404… But is not about change the name, is just change the content of the .png
> 
> I already texted in all my expo projects and I get that issue. Also you can try creating a new expo blank project and then change icon.png or splash.png
> 
> Hope the expo team can fix it soon

**Comment by zivl** [comment]
I'm also facing this issues and my project has not yet designed so no images what's so ever...
Up until this version I was able to publish my project with no issues

**Comment by fson** [comment]
We're working on fixing this. In the meantime, downgrading back to Expo CLI `3.13.1` (`npm i -g expo-cli@3.13.1`) should to fix the issue.

**Comment by ionTea** [comment]
Confirming that the downgrade fix the issue for me 👍

**Comment by jkhales** [comment]
Thanks for letting us now, just deployed the fix. Let us know if you have any other issues please!

**Comment by sungsong88** [comment]
3.13.5 still has this problem with 403. This issue should be reopened I think...
And thanks to @fson . Downgrading works.

**Comment by bill-pairaktaridis** [comment]
I've been having the `Request body larger than maxBodyLength limit` issue for a couple days now but downgrading seems to have resolved it

**Comment by jkhales** [comment]
@bill-pairaktaridis, @sungsong88 which version did you downgrade to?

And you are both just running `expo build:ios` on a new project?

**Comment by NikolaNikushev** [comment]
@jkhales  I just upgraded my version to 3.13.6 and I started getting the same issue.

Running on Mac, 
Node v12,
 expo v36.0.0 

**Request body larger than maxBodyLength limit**
```

Error: Request body larger than maxBodyLength limit
    at RedirectableRequest.write (/myuser/.nvm/versions/node/v12.10.0/lib/node_modules/expo-cli/node_modules/axios/node_modules/follow-redirects/index.js:97:24)
    at RedirectableRequest.end (/myuser/.nvm/versions/node/v12.10.0/lib/node_modules/expo-cli/node_modules/axios/node_modules/follow-redirects/index.js:116:8)
    at dispatchHttpRequest (/myuser/.nvm/versions/node/v12.10.0/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:272:11)
    at new Promise (<anonymous>)
    at httpAdapter (/myuser/.nvm/versions/node/v12.10.0/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:20:10)
    at dispatchRequest (/myuser/.nvm/versions/node/v12.10.0/lib/node_modules/expo-cli/node_modules/axios/lib/core/dispatchRequest.js:59:10)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at ApiV2Client._requestAsync (/@expo/xdl@57.5.5/src/ApiV2.ts:200:18)
    at ApiV2Client.uploadFormDataAsync (/@expo/xdl@57.5.5/src/ApiV2.ts:157:12)
    at _uploadArtifactsAsync (/@expo/xdl@57.5.5/src/Project.ts:970:16)
make: *** [publish] Error 1

```

Is there something I can run to give more context?

**Comment by jkhales** [comment]
woudl you mind running the same command with `EXPO_LEGACY_API=true` so it would be: `EXPO_LEGACY_API=true expo build:ios` or something.

**Comment by sungsong88** [comment]
@jkhales I downgraded to 3.13.1 following @fson 's advice. I was at 3.13.5.
Currently I'm using Expo sdk 35, Running on Mac.
And I see the same message as @NikolaNikushev when I hit `publish project` from DevTools on Chrome browser.

**Comment by hrmoller** [comment]
> I've been having the `Request body larger than maxBodyLength limit` issue for a couple days now but downgrading seems to have resolved it

Yeah, seeing this as well in 3.13.6.
I just downgraded to 3.13.1 which seems to work.

**Comment by NikolaNikushev** [comment]
@jkhales with EXPO_LEGACY_API=true expo publish it was able to deploy it with no issues.

**Comment by jkhales** [comment]
OK thank you for testing that, very helpful.
