### ISSUE TITLE
Got this issue today on **windows**, but don't need to downgrade node, just as discussed on [stackoverflow](https://stackoverflow.com/a/58199866) just need to change some hashes on  your project:

### ISSUE THREAD

**Issue by FayyazAliKhan1** [expo/expo-cli#1648]
I do not know this but when i reinstall windows when i created a new react native project every time i have to change this code in blaklist.js just like you mentioned otherwise the metro bundler is stopped automatically..but before my reinstall of windows i have not faced issue like this the metro bundler would run properly.. but now this situation is coming every time... plz give long term solution to fix this.. so that i do not have to change the below code every time in blaklist.js file....
Got this issue today on **windows**, but don't need to downgrade node, just as discussed on [stackoverflow](https://stackoverflow.com/a/58199866) just need to change some hashes on  your project:

> **\node_modules\metro-config\src\defaults\blacklist.js**

```
var sharedBlacklist = [
  /node_modules[/\\]react[/\\]dist[/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];
```

change to:

```
var sharedBlacklist = [
  /node_modules[\/\\]react[\/\\]dist[\/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];
```

Hope it works like worked for me :)

_Originally posted by @hadessama1994 in https://github.com/expo/expo-cli/issues/1074#issuecomment-546167583_

**Comment by brentvatne** [comment]
this is resolved on the latest version of react-native-cli used in the project. you should just be able to init a new project and it will work as expected, provided that the project is on sdk36. if this is not the case then please let me know.

**Comment by Ramboaa** [comment]
But there is another  issue in the new Version 0.61.5 while making an apk 

error EEXIST: file already exists, mkdir 'D:\React'. Run CLI with --verbose flag for more details.
Error: EEXIST: file already exists, mkdir 'D:\React'

> Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'npx.cmd'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 47s
6 actionable tasks: 2 executed, 4 up-to-date

**Comment by brentvatne** [comment]
@Ramboaa - this isn't related to expo-cli or expo as far as i can tell. create a new issue and fill in the template if the issue persists
