### ISSUE TITLE
Can't install Expo CLI on Windows cmd, Powershell and WSL

### ISSUE THREAD

**Issue by abdella206** [expo/expo-cli#1649]
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
*********************************************************************************
npm WARN deprecated joi@14.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

![expo-cli](https://user-images.githubusercontent.com/25184204/76155785-0dc3e100-60a6-11ea-8f9c-e06b6542329f.png)

**Comment by brentvatne** [comment]
this is not an error blocking installation, it is a warning from a npm package that is one of the dependencies. you can safely ignore it

**Comment by senatoreagle** [comment]
i have same error . please help  installation stop when i receive this error

**Comment by brentvatne** [comment]
hey @senatoreagle!

> this is not an error blocking installation, it is a warning from a npm package that is one of the dependencies. you can safely ignore it
