### ISSUE TITLE
Expo server does not start and web build fail

### ISSUE THREAD

**Issue by chayancbnits** [expo/expo-cli#1657]
I am getting the error message from the expo when I had run the command "expo start --web" after few seconds show the error message "Invalid mode "undefined" was used to evaluate the project config." and also I am getting the error from circle ci.
![Screenshot from 2020-03-10 14-40-27](https://user-images.githubusercontent.com/51107138/76296991-1d793a80-62dd-11ea-8c9a-4c10c1dce527.png)
![Screenshot from 2020-03-10 14-41-15](https://user-images.githubusercontent.com/51107138/76297087-3da8f980-62dd-11ea-9027-ba8c701df87a.png)

Expo CLI 3.13.2 environment info:
    System:
      OS: Linux 5.3 Ubuntu 18.04.3 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    npmGlobalPackages:
      expo-cli: 3.13.2

**Comment by EvanBacon** [comment]
Fixed in #1581
