### ISSUE TITLE
Remove usage of REACT_NATIVE_APP_ROOT

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#1666]
As per https://github.com/react-native-community/cli/pull/935, new versions of react-native-cli will stop using this env var and so we should switch to an alternative, eg: cli flag.

**Comment by grabbou** [comment]
You should be able to use `--watchFolders` as a quick migration (https://github.com/react-native-community/cli/pull/935/files#diff-af85a4b1a1be582648ac04d6bdfefe13L17), but I am not sure how do you use this option right now.

**Comment by fson** [comment]
I'm working on https://github.com/expo/expo-cli/issues/1434, which will allow us to pass in Metro configuration directly without using the CLI flags. I think we can then just use the `watchFolders` config option.

**Comment by EvanBacon** [comment]
Related https://github.com/expo/expo-cli/issues/254

**Comment by EvanBacon** [comment]
Fixed in SDK 40 or now with `EXPO_USE_DEV_SERVER=true`.
