### ISSUE TITLE
can't install latest version of expo-cli

### ISSUE THREAD

**Issue by arthuranteater** [expo/expo-cli#167]
## Description

I've hide a million problems with `expo start`. But with `expo init` I get the warning message that I'm running old version of expo-cli. When I check using npm ls -g expo-cli, it shows I have the latest version.

## Expected Behavior

I don't expect the warning for the older version to coming up. I'm not sure why it would come up unless I had expo-cli installed locally as well. I'm sure that is not the case since I have created new projects in new folders.

## Observed Behavior

What actually happened when you performed the above actions?

`➜  garfunk-2 npm ls -g expo-cli
/Users/arthurapplegate/.nvm/versions/node/v10.4.0/lib/node_modules/node/lib
└── expo-cli@2.3.0

➜  garfunk-2 npm ls expo-cli
/Users/arthurapplegate
└── (empty)

➜  garfunk-2 expo init
There is a new version of expo-cli available (2.3.0).
You are currently using expo-cli 2.2.5
Run `npm install -g expo-cli` to get the latest version
? Choose a project name:`

If there's an error message, please paste the _full terminal output and error message_ in this code block:

```
Error text goes here!
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

[00:25:11] You can join our slack here: https://slack.expo.io/.

  Expo CLI 2.2.5 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.0.0 - ~/.nvm/versions/node/v10.4.0/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.3.0

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/arthuranteater-d5bb5fad-71ab-4a60-99bc-4ab059c99c57.tar.gz

Also specify:

- Phone/emulator/simulator platform, model and version:

See above

## Reproducible Demo

See above.

**Comment by GayanEranga92** [comment]
1.run "npm update -g" update all npm global packages
2.run "yarn add global expo-cli"
3.uninstall exop cli > clean npm cache folder, .expo folder install  install again

**Comment by inetkid** [comment]
error install expo-cli, had given full filesystem permission even anonymous have full access. below is log beginning line 4303...
```
4303 timing action:finalize Completed in 222851ms
4304 verbose unlock done using C:\Users\raymond.tan\AppData\Roaming\npm-cache\_locks\staging-3b3ea7b8e690fd7a.lock for C:\Users\raymond.tan\AppData\Roaming\npm\node_modules\.staging
4305 timing stage:rollbackFailedOptional Completed in 2675ms
4306 timing stage:runTopLevelLifecycles Completed in 271842ms
4307 verbose stack Error: EPERM: operation not permitted, unlink 'C:\Users\raymond.tan\AppData\Roaming\npm\node_modules\expo-cli\node_modules\.xdl.DELETE\binaries\windows\adb\AdbWinApi.dll'
4308 verbose cwd C:\Users\raymond.tan\Documents\Projects
4309 verbose Windows_NT 10.0.17134
4310 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\raymond.tan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "-g" "i" "expo-cli"
4311 verbose node v10.8.0
4312 verbose npm  v6.4.1
4313 error path C:\Users\raymond.tan\AppData\Roaming\npm\node_modules\expo-cli\node_modules\.xdl.DELETE\binaries\windows\adb\AdbWinApi.dll
4314 error code EPERM
4315 error errno -4048
4316 error syscall unlink
4317 error Error: EPERM: operation not permitted, unlink 'C:\Users\raymond.tan\AppData\Roaming\npm\node_modules\expo-cli\node_modules\.xdl.DELETE\binaries\windows\adb\AdbWinApi.dll'
4317 error  { [Error: EPERM: operation not permitted, unlink 'C:\Users\raymond.tan\AppData\Roaming\npm\node_modules\expo-cli\node_modules\.xdl.DELETE\binaries\windows\adb\AdbWinApi.dll']
4317 error   cause:
4317 error    { Error: EPERM: operation not permitted, unlink 'C:\Users\raymond.tan\AppData\Roaming\npm\node_modules\expo-cli\node_modules\.xdl.DELETE\binaries\windows\adb\AdbWinApi.dll'
4317 error      errno: -4048,
4317 error      code: 'EPERM',
4317 error      syscall: 'unlink',
4317 error      path:
4317 error       'C:\\Users\\raymond.tan\\AppData\\Roaming\\npm\\node_modules\\expo-cli\\node_modules\\.xdl.DELETE\\binaries\\windows\\adb\\AdbWinApi.dll' },
4317 error   stack:
4317 error    'Error: EPERM: operation not permitted, unlink \'C:\\Users\\raymond.tan\\AppData\\Roaming\\npm\\node_modules\\expo-cli\\node_modules\\.xdl.DELETE\\binaries\\windows\\adb\\AdbWinApi.dll\'',
4317 error   errno: -4048,
4317 error   code: 'EPERM',
4317 error   syscall: 'unlink',
4317 error   path:
4317 error    'C:\\Users\\raymond.tan\\AppData\\Roaming\\npm\\node_modules\\expo-cli\\node_modules\\.xdl.DELETE\\binaries\\windows\\adb\\AdbWinApi.dll',
4317 error   parent: 'expo-cli' }
4318 error The operation was rejected by your operating system.
4318 error It's possible that the file was already in use (by a text editor or antivirus),
4318 error or that you lack permissions to access it.
4318 error
4318 error If you believe this might be a permissions issue, please double-check the
4318 error permissions of the file and its containing directories, or try running
4318 error the command again as root/Administrator (though this is not recommended).
4319 verbose exit [ -4048, true ]
```

**Comment by fson** [comment]
@arthuranteater the environment info you've copy pasted in shows that you're using v2.2.5, but you also have v2.3.0 installed. Can you check, if you have installed `expo-cli` in different ways, for example one version with Yarn and one with npm? `yarn global list` shows global packages installed with Yarn.

**Comment by sohaibiii** [comment]
> yarn add global expo-cli

thanks it works for me
