### ISSUE TITLE
Support maskable icons for Android PWAs

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo-cli#1673]
We should reuse the `android. adaptiveIcon` field in the `app.json` to create `maskable` PWA icons for Chrome PWAs.

- [Android Native Adaptive Icons](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive)
- [Android PWA Adaptive Icons](https://web.dev/maskable-icon/)
- [Expo Android Icons](https://docs.expo.io/versions/latest/guides/app-icons/#android)

**Comment by unindented** [comment]
What's your plan for this feature? Can I help implement this?

**Comment by EvanBacon** [comment]
On further inspection I don't think it'll make sense to mix it with `android.adaptiveIcon`, I'd like to think of a nice abstraction over all of PWA icons. Said abstraction should consider round desktop PWA icons as well.

**Comment by unindented** [comment]
Ah, I was thinking of adding a `web.adaptiveIcon` or  `web.maskableIcon` option, and adding `"purpose": "maskable"` to that entry in the manifest...

**Comment by JWesorick** [comment]
I would appreciate this enhancement.
