### ISSUE TITLE
React Native does not export createElement ???

### ISSUE THREAD

**Issue by Arlen22** [expo/expo-cli#1676]
## Description

When trying to use createElement directly from "react-native", the app throws a runtime error `undefined is not an object (evaluating '_reactNative.createElement.apply')`. Importing createElement from "react" works just fine. 

The error does not make it back to the terminal, it is only displayed on the device. 

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:
```plain
  Expo CLI 3.13.5 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.21.1 - ~/.npm-packages/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.13.5
```

Also specify:

- Phone/emulator/simulator platform, model and version:
```plain
iOS 13, iPad Mini 5th gen
```

## Reproducible Demo

Create a new project using the expo-cli using the blank (typescript) template, then modify App.tsx as shown:

```ts
import React from "react";
import { StyleSheet, Text, View, createElement } from "react-native";

export default function App() {
  return createElement(
    View,
    { style: styles.container },
    createElement(Text, {}, "Open up App.tsx to start working on your app!")
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center"
  }
});
```

**Comment by Arlen22** [comment]
`"react-native"` apparently resolves to `node_modules/react-native/Libraries/react-native/react-native-implementation.js`, which does not export createElement.

**Comment by brentvatne** [comment]
it does not, similar to how ReactDOM does not. React does

**Comment by Arlen22** [comment]
Then why do all the types and examples, including the default Typescript template still use it. The tsconfig.json file is set to resolve jsx to "react-native" in the Typescript template.

**Comment by Arlen22** [comment]
Also, when did this change happen, because it definitely used to work!

**Comment by brentvatne** [comment]
see: https://www.typescriptlang.org/docs/handbook/jsx.html#basic-usage
