### ISSUE TITLE
Validate that server is actually running in Project.currentStatus and handle cases when it is not

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#1677]
## Description

The [Project.currentStatus(projectDir)](https://github.com/expo/expo-cli/blob/a26baf39c19cefd016eb0acc0445c4a3cba16915/packages/xdl/src/Project.ts#L176-L185) function determines the project status by looking at the packager info in the project `.expo` directory.

Sometimes expo-cli can close in an unexpected way (not exactly sure which steps will repro this, I suspect maybe a hard reboot without closing expo-cli would do it) and the information in `.expo` will be stale. We should validate that the status in this file is actually correct, eg: by sending a request to packager/expo server.  

## Expected Behavior

expo-cli should gracefully handle the information in `.expo` being stale/incorrect.

## Observed Behavior

Cryptic errors like this can happen when running `expo publish`:

```
Publishing to channel 'default'...
Building iOS bundle
connect ECONNREFUSED 127.0.0.1:19001
Error: connect ECONNREFUSED 127.0.0.1:19001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14)
```

**Comment by brentvatne** [comment]
@byCedric - interested?

**Comment by byCedric** [comment]
Done! Hope this is something you are looking for. I reproduced the issue by killing the metro bundler process and publish a new bundle.
