### ISSUE TITLE
Expo ejected app crashes with SIGABRT

### ISSUE THREAD

**Issue by ninjaboy** [expo/expo-cli#1679]
## Description

Expo ejected app crashes with SIGABRT

## Expected Behavior

The app started and running in minimal config with tabs and without crashes

## Observed Behavior

The app crashes
```
libsystem_kernel.dylib`__pthread_kill:
    0x7fff523bc7f0 <+0>:  movl   $0x2000148, %eax          ; imm = 0x2000148 
    0x7fff523bc7f5 <+5>:  movq   %rcx, %r10
    0x7fff523bc7f8 <+8>:  syscall 
->  0x7fff523bc7fa <+10>: jae    0x7fff523bc804            ; <+20>
    0x7fff523bc7fc <+12>: movq   %rax, %rdi
    0x7fff523bc7ff <+15>: jmp    0x7fff523b6a89            ; cerror_nocancel
    0x7fff523bc804 <+20>: retq   
    0x7fff523bc805 <+21>: nop    
    0x7fff523bc806 <+22>: nop    
    0x7fff523bc807 <+23>: nop    
```

## Environment

  Expo CLI 3.13.6 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.4.2 - /usr/local/bin/zsh
    Binaries:
      Node: 12.16.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.0 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.13.6

Running this on ios simulator

## Reproducible Demo

```
expo init myawsomeapp (choose `tabs`)
cd myawesomeapp
yarn start (runs in simulator well)
expo eject (choose eject to expokit)
cd ios; pod install
yarn start
open ios/myawesomeapp.xcworkspace in XCode
start the app in simulator
```

**Comment by brentvatne** [comment]
we need to improve the instructions to clarify that you need to remove imports from the `"expo"` package when you eject. eg: in this case we are importing `Linking` and `SplashScreen` from '"expo". 

if you run those above steps again and remove imports from the "expo" package (not expo-asset, expo-font, etc, just expo) then it will solve your problem.

<img width="1361" alt="Screen Shot 2020-03-12 at 4 10 03 PM" src="https://user-images.githubusercontent.com/90494/76575294-f442e080-647b-11ea-8405-fa4c025ab3ec.png">
