### ISSUE TITLE
Abundant and clear instructions on eject

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#1684]
Currently we don't give people enough information when they eject to know what they might need to do to get their app running. We should fix this. Related: https://github.com/expo/expo-cli/issues/1679

**Comment by cruzach** [comment]
+ to this: warn after ejecting if using not-bare-friendly modules like [apploading](https://docs.expo.io/versions/latest/sdk/app-loading/) and spit out replacements (in that case, splashscreen)

**Comment by EvanBacon** [comment]
Fixed
