### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by Ramboaa** [expo/expo-cli#1687]
But there is another issue in the new Version 0.61.5 while making an apk

error EEXIST: file already exists, mkdir 'D:\React'. Run CLI with --verbose flag for more details.
Error: EEXIST: file already exists, mkdir 'D:\React'

Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
Process 'command 'npx.cmd'' finished with non-zero exit value 1

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 47s
6 actionable tasks: 2 executed, 4 up-to-date

**Comment by brentvatne** [comment]
this seems unrelated to expo-cli as far as i can tell. fill out issue template next time please!

**Comment by mohity777** [comment]
yes. i am facing this problem too. Any solutions pls

**Comment by mohity777** [comment]
why is this closed??

**Comment by mohity777** [comment]
this error was coming because i had spaces in the name of the folder in which project was located. i resolved this issue by removing spaces
