### ISSUE TITLE
Using numeric sepator will throw SyntaxError

### ISSUE THREAD

**Issue by borislemke** [expo/expo-cli#1691]
## Description

Using numeric separators (e.g `10_000_000`) will throw a `SyntaxError`

## Expected Behavior

Number values with numeric separators should not throw error.

## Observed Behavior

Using numeric separators will throw a `SyntaxError`

```
SyntaxError: ~/src/index.tsx: Identifier directly after number (12:14)

  10 | import { AppContainer } from './containers/App'
  11 |
> 12 | console.log(10_000_000)
     |               ^
  13 |
  14 | const Stack = createStackNavigator()
  15 |
Failed building JavaScript bundle.
```

## Environment

```
  Expo CLI 3.13.8 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.5.0 - ~/.nvm/versions/node/v13.5.0/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v13.5.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2
      react: ~16.9.0 => 16.9.0
      react-native: ~0.61.4 => 0.61.5
    npmGlobalPackages:
      expo-cli: 3.13.8
```

Also specify:

- Phone/emulator/simulator platform, model and version:
Tested on iOS 13.3.1, iPhone Xs

## Reproducible Demo

Create a new expo project:
```
$ expo init numeric // Choose bare minimal
$ cd numeric
$ nano App.js // add console.log(10_000_000) to top of file
$ expo start
```

Launch app on Expo app and see the error

**Comment by brentvatne** [comment]
you can enable this by adding the babel plugin: https://babeljs.io/docs/en/babel-plugin-proposal-numeric-separator

it's supported by typescript but typescript isn't used to compile the js, it is just used for typechecking. it might be worth opening a pr to react-native upstream to add this babel plugin by default

**Comment by EvanBacon** [comment]
Closing as this is a problem with an upstream tool.
