### ISSUE TITLE
Compiling new app initialized from "tabs" template with live reloading ends with error

### ISSUE THREAD

**Issue by YanDatsiuk** [expo/expo-cli#1692]
## Description

Starting new app from "tabs" template ends with error. If you try to start expo app for opening it in web browser  - you will get compilation error: "`web Failed to compile. /usr/lib/node_modules/expo-cli/node_modules/url/url.js Error: EIO: i/o error`"

## Expected Behavior
Get you app to be compiled without errors.

## Observed Behavior
Error during compilation phase.

```
web Failed to compile. /usr/lib/node_modules/expo-cli/node_modules/url/url.js Error: EIO: i/o error
```

Screenshot
![image](https://user-images.githubusercontent.com/3888040/76702446-a70c7c00-66d2-11ea-9977-a63c389f9d71.png)

## Environment

```
Expo CLI 3.13.8 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.14.1 - /usr/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 6.13.7 - /usr/bin/npm
    npmPackages:
      expo: ~36.0.0 => 36.0.2
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
    npmGlobalPackages:
      expo-cli: 3.13.8
```

## Reproducible Demo
1. Install new project via `expo init project-name` command
2. Choose "tabs" template
3. After installation completes run `yarn start` command
4. Press key "w" to get your app compiled with live reloading for web browser.

**Comment by brentvatne** [comment]
I can't reproduce this, it looks like an issue with your node installation - there is an i/o error when trying to load a js file from expo-cli. Perhaps a permissions issue?
