### ISSUE TITLE
cli init message > undefined start

### ISSUE THREAD

**Issue by codedawi** [expo/expo-cli#1693]
## Description
After initializing my expo application with cmd `expo init app` the output message in command prompt  says `undefined start`.

## Expected Behavior
It does not seem to notice it was installed using `npm`

Expected Message:
```
To get started, you can type:

  cd app
  npm start
```

## Observed Behavior
Printing out `undefined start` rather than `npm start`
```
To get started, you can type:

  cd app
  undefined start
```
## Environment
`expo v3.13.8`
`PATH=/usr/local/.npm_global/bin/expo`
`node v12.16.1`
`npm v6.11.3`

## Reproducible Demo
1. `npm install -g expo-cli`
2. `expo init app` 

## Source Code Location
https://github.com/expo/expo-cli/blob/ff53b987b35086f98ca99faadf7ac63d9f7946cb/packages/expo-cli/src/commands/init.ts#L202-L207

**Comment by brentvatne** [comment]
thanks for the detailed report! it looks like this happens when only npm is installed in some cases. i believe it should be fixed in the latest version, `expo-cli@3.15.4`
