### ISSUE TITLE
expo start ignoring --localhost flag on windows

### ISSUE THREAD

**Issue by arqex** [expo/expo-cli#1695]
## Description

I'm using windows. With the latest version of expo, intiating the server with `expo start --localhost` doesn't honor the flag and it starts with the host set as LAN (with an ip like 192.168....).

The option `expo start --host localhost` doesn't work either.

## Expected Behavior

the server should start in local mode with an IP like 127.0.0....

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:
```
Expo CLI 3.15.2 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 10.14.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.16.0 - C:\Users\Perry\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
    npmPackages:
      expo: ^36.0.0 => 36.0.2
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4
```

I'm using the emulator:
Nexus 5X API 29, Android 10.0

## Reproducible Demo
`expo start --localhost`

**Comment by brentvatne** [comment]
thanks for the report! I fixed this in expo-cli@3.15.3
