### ISSUE TITLE
Verify the iOS bundle identifier and Android packages are unique while in development

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#1697]
This is useful when you init a project so you don't end up having to change it later (which is a bit annoying in bare projects).

**Comment by fson** [comment]
How can we check that they are unique?

**Comment by brentvatne** [comment]
Not sure - Xcode does this and I assume there is an API somewhere. For Android we can do something like this https://stackoverflow.com/a/23031760/659988

**Comment by EvanBacon** [comment]
This could be awkward if they are reassigning their package and it thinks the value isn't unique because they've already published their app.

**Comment by brentvatne** [comment]
yeah we should definitely factor in that possibility

**Comment by EvanBacon** [comment]
fixed in #2616
