### ISSUE TITLE
expo upload:android with passed --id produces "We couldn't find build with id"

### ISSUE THREAD

**Issue by trexpert** [expo/expo-cli#1699]
## Description

Cannot upload a specific builId (by passing the --id parameter) to android play store using the expo ua command.

BUILD ID was taken from this section on expo detail page:
![Expo](https://user-images.githubusercontent.com/16317797/76956519-7caa0100-6914-11ea-96e2-a085e011ca7b.PNG)

Both (Web and CLI) are logged as same user.

## Expected Behavior

I expect i can pass the BUILD ID found on Build Detail page to upload:android command

`
expo ua --id "[BUILD_ID]" --key [PATCH_TO_ACCESS_JSON] --track alpha
`

## Observed Behavior

Upload action fails with message
``` 
expo ua --id "[BUILD_ID]" --key [PATCH_TO_ACCESS_JSON] --track alpha
Failed to upload the standalone app to the app store.
We couldn't find build with id [BUILD_ID]
Error: We couldn't find build with id [BUILD_ID]
    at AndroidUploader._downloadBuildById (/expo-cli@3.15.4/src/commands/upload/BaseUploader.ts:67:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at AndroidUploader.upload (/expo-cli@3.15.4/src/commands/upload/BaseUploader.ts:31:23)
    at /expo-cli@3.15.4/src/commands/upload.ts:108:7
    at Command.<anonymous> (/expo-cli@3.15.4/src/exp.ts:85:7)
```

## Environment

```
  Expo CLI 3.15.4 environment info:
    System:
      OS: macOS Sierra 10.12.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4
      react-navigation: ^4.0.10 => 4.0.10
```

## Reproducible Demo

Just try to not use the --latest flag and specify a build id with --id [BUILD_ID]
I was not able to use the id flag on 2 tested accounts and multiple projects

**Comment by Johann01** [comment]
Having the same issue did you find a solution?

**Comment by trexpert** [comment]
> Having the same issue did you find a solution?

no solution yet. still facing the same problem

**Comment by BojanOro** [comment]
Chiming in that we're having the same problem, but that it worked last week.

**Comment by fractalmarc** [comment]
I'm also having this problem

**Comment by ajouve** [comment]
Same for 

```
expo upload:ios --id <id>
```

**Comment by ccheever** [comment]
Hi -- For people who had this problem, can you please e-mail your build IDs to secure@expo.io ?
That will help us do a better job of investigating this. @trexpert  @BojanOro  @fractalmarc @ajouve

**Comment by jkhales** [comment]
We've identified the problem and will be deploying a fix imminently.

**Comment by jkhales** [comment]
This issue should be resolved now, thanks for your patience!

**Comment by ptkpyitheim** [comment]
@jkhales 
I'm having the same issue for using `--path <id>`

` expo upload:ios --id <id>`

The error is : Failed to upload the standalone app to the app store.
We couldn't find build with id <id>

My expo version: 3.25.1
My expo version on package.json dependencies: ~38.0.8

I'm certain the build id I'm passing in is correct. I got it from the place where the original poster of this mentioned for build ids.

**Comment by brentvatne** [comment]
hey @ptkpyitheim! 

can you share the build id?

**Comment by ptkpyitheim** [comment]
Sure

6713ec26-8a71-4ae2-afb9-f93fcb56ba22

**Comment by ptkpyitheim** [comment]
> hey @ptkpyitheim!
> 
> can you share the build id?

In addition to the id, I tried with --latest tag but it tells me I need to run 'expo build:ios'. I've ran it about 3 times.

**Comment by brentvatne** [comment]
this does not appear to be a valid build id. where are you finding that?

**Comment by brentvatne** [comment]
you can go to your dashboard: https://expo.io/dashboard/
then find the build, click on it, and check the Build ID field

**Comment by ptkpyitheim** [comment]
> you can go to your dashboard: https://expo.io/dashboard/
> then find the build, click on it, and check the Build ID field

This is where I got it from

![Screen Shot 2020-08-28 at 5 33 23 PM](https://user-images.githubusercontent.com/36285777/91620138-b0be2f00-e954-11ea-858d-10b3cade37e3.png)

**Comment by brentvatne** [comment]
ah i see - i think you may be seeing this error because it is a simulator build, and you can't upload simulator builds to apple. the error is indeed confusing around this though

**Comment by ptkpyitheim** [comment]
> ah i see - i think you may be seeing this error because it is a simulator build, and you can't upload simulator builds to apple. the error is indeed confusing around this though

Ah but the only options I have are simulator or archive builds. That means I have to do the archive build instead then, correct?

**Comment by brentvatne** [comment]
correct

**Comment by ptkpyitheim** [comment]
> correct

I appreciate you.
