### ISSUE TITLE
Suggestion: Add option to log window output to console

### ISSUE THREAD

**Issue by karlvd** [expo/expo-cli#17]
### Suggestion
Add an option to log window output to browser console in expo

### Problem description

- Enabling Remote JS debugging makes apps painfully slow and introduces new weird bugs since JS is executed in the browser and not in the app.
- Viewing console.log in the expo output window becomes difficult with large objects & arrays since it´s plain text, no collapse/expand functionality.

### Solution
Add an option to log window output to console on the device tab window.

This way you would benefit from both having the JS code executed in the app and having the power of expanding/collapsing objects & arrays in the browser dev tools console.

If you think it´s good suggestion I belive it would be fairly easy to implement with a checkbox on top of the device window as a switch and just console.log() all output from that window if checked.

![image](https://user-images.githubusercontent.com/3678047/44645914-ad94af00-a9d9-11e8-8a34-f08e021850b0.png)

**Comment by fson** [comment]
Thanks for the suggestion @karlvd! I think it would be even nicer, if the log screen itself supported expanding/collapsing objects and arrays just like the browser console does. This is something we're planning to add.

Logging all the log output to console would be an easy to implement workaround for the same problem, but it's harder for users to discover and there's no separation of different log sources. Therefore I think improving the log component itself to support this would be a better long term solution.

**Comment by omar-bakhsh** [comment]
why this error showsup every time 

$ npm i -g @expo-cli --save
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "@expo-cli": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Amoory.SO\AppData\Roaming\npm-cache\_logs\2019-05-17T19_28_11_226Z-debug.log
