### ISSUE TITLE
Install pods automatically on eject, init bare project, or expo install in bare

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#1705]
@react-native-community/cli does this and it's pretty convenient:

- https://github.com/react-native-community/cli/blob/8f977d978da8c254c5bf48b88a35d5fbcf7f7200/packages/cli/src/commands/doctor/healthchecks/cocoaPods.ts
- https://github.com/react-native-community/cli/blob/4dbfc7751aee90c5e9c78286b3825796a4d332ab/packages/cli/src/tools/installPods.ts

**Comment by EvanBacon** [comment]
Done
