### ISSUE TITLE
installing expo installing using npm hangs

### ISSUE THREAD

**Issue by ssomlk** [expo/expo-cli#1708]
## Description

Installation of the latest expo-cli using npm hangs

## Expected Behavior

What action did you perform, and what did you expect to happen?
I tried steps mentioned in https://github.com/expo/expo-cli/issues/440 but nothing worked

## Observed Behavior

What actually happened when you performed the above actions?

installion is stuck at the below point. not progressing further

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[..................] \ fetchMetadata: WARN deprecated request@2.88.2: request has been deprecated, see https://github.c

## Environment

WIndows 7 64 bit OS

**Comment by pitpitpat** [comment]
Same here using MacOS Catalina 10.15.3.
Command: sudo npm install -g expo-cli

**Comment by ssomlk** [comment]
@pitpitpat 

Deleting npm and npm-cache folders in Users%username%\AppData\Roaming (windows 7) and running npm install

this worked for me. Refer to https://stackoverflow.com/questions/47545940/when-i-run-npm-install-it-returns-with-err-code-eintegrity-npm-5-3-0/47922056

**Comment by rid3thespiral** [comment]
> Same here using MacOS Catalina 10.15.3.
> Command: sudo npm install -g expo-cli

same for me

**Comment by ssomlk** [comment]
@rid3thespiral Did you try https://stackoverflow.com/questions/47545940/when-i-run-npm-install-it-returns-with-err-code-eintegrity-npm-5-3-0/47922056

**Comment by pitpitpat** [comment]
@rid3thespiral 
I managed to solve the issue on MacOS by running:
1. **npm cache clean --force** ( as suggested by @ssomlk )
2. **sudo npm install -g expo-cli**
The installation took about 10-15 minutes, so give it some time if it looks like it's stuck.

**Comment by dspashish** [comment]
Can i switch the window after doing that
