### ISSUE TITLE
Reference Error: regenerateRuntime is not defined when running npm start after expo eject.

### ISSUE THREAD

**Issue by amandeeptherockstar** [expo/expo-cli#171]
![sddsdsdsdd](https://user-images.githubusercontent.com/34765485/48203284-15c62080-e38d-11e8-8ad6-9ae098f04b87.png)
I am able to eject from the expo using eject expo command. Android and ios folders were created successfully, but after then when i run npm start to start building the project i get this error:

Reference Error: regenerateRuntime is not defined.
The full error is here in the image:

**Comment by Petar-np** [comment]
I have the same problem

**Comment by brentvatne** [comment]
this was an intermittent issue and has been resolved for a while :) thanks for the report
