### ISSUE TITLE
Can't download expo-cli using npm and yarn.

### ISSUE THREAD

**Issue by Nikko71** [expo/expo-cli#1722]
[node -v
v13.11.0]
[npm -v
6.14.3]
Installed latest node.js 
Installed Git.
WINDOWS 10

Trying to download expo-cli on windows (npm install expo-cli --global) and I had a issues lik this

**npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142**

Also I tried yarn, same problems.
 What should I do to fix this?

**Comment by myvagrantlife** [comment]
I experienced the same issue on my macbook, it seems to hang on the warning message mentioned by @Nikko71  

Not sure of the underlying issue, but If you give it enough time it will continue and complete the install. 

For me it took around 5 minutes to complete.

**Comment by CelestinoPaulo** [comment]
> I experienced the same issue on my macbook, it seems to hang on the warning message mentioned by @Nikko71
> 
> Not sure of the underlying issue, but If you give it enough time it will continue and complete the install.
> 
> For me it took around 5 minutes to complete.

@Nikko71 the above solution worked for you?
I'm facing the same problem.
