### ISSUE TITLE
Could not connect to localhost/127.0.0.1.

### ISSUE THREAD

**Issue by Rafay3198** [expo/expo-cli#1723]
![image](https://user-images.githubusercontent.com/62332750/77307801-bff0df00-6d1b-11ea-92d4-7a16675f7d0d.png)
 
I found this issue for many days
when i scan QR code "Something went wrong.......Could not load to exp://127.0.0.19024" this message is shown

**Comment by gphelipe1** [comment]
You can try to specify your environment variable to use the correct IP address. You can change Expo LAN IP using the command

>  set REACT_NATIVE_PACKAGER_HOSTNAME=your_ip_address

**Comment by byCedric** [comment]
Hi @Rafay3198! On top of my mind, I can see 2 points to look at.

1. Your port number `19024` is a bit larger than we normally would expect, might be related with old processes. If you restart your computer, they should be stopped. Could you check what your port number is after a restart?

2. Your IP is set to local, but in your screenshot LAN is selected. Could you either try the solution from @gphelipe1, or try using a tunnel and see if you can connect?

Hope it helps 😄
