### ISSUE TITLE
Warn when git is not installed and possibly install it for people too

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#1725]
Git is currently required to use expo-cli. This is mainly because some packages point to a git repo (eg: the react-native expo fork).

**Comment by byCedric** [comment]
Maybe installing this on any platform might be a bit complicated, but a warning log shouldn't be that hard 😄

**Comment by brentvatne** [comment]
true!

**Comment by byCedric** [comment]
If we build this into the `Doctor` XDL, we could also "pimp" the `expo doctor` command and add some system checks. Should resolve stuff like #1858 too.
