### ISSUE TITLE
[Web] expo start --web no longer starts the Webpack server automatically

### ISSUE THREAD

**Issue by bayoremit** [expo/expo-cli#1729]
## Description

`expo start --web` used to automatically start the Webpack server automatically on port 19006, this stoped working around expo-cli version 3.13.xx i believe.

Now I have to either start the web server by pressing w on the cli or use the developer tool

## Expected Behavior

Running the command above should automatically start the Webpack dev server for expo web development.

## Observed Behavior

Expo starts without the web server. It now has to be launched separately after the cli is up and running.

## Environment

```
  Expo CLI 3.15.5 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.14.2 - ~/.nvm/versions/node/v10.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: 36.0.2 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.15.5
```

Also specify:

- This is for Expo Web

## Reproducible Demo

- Run `expo start --web` on expo-cli v 3.15.5
- Go to `http://localhost:19006/`
- Do NOT PROFIT.... Until the web server is manually started 😢 

Thanks Team Expo!!!

**Comment by fson** [comment]
Could you try running `expo start:web` instead? This command replaces the `expo start --web-only` command.

**Comment by bayoremit** [comment]
Hi @fson , thanks for the fast response. I tried the new command and as you called out, it starts the web development server only and the native server no longer works. The old command used to start both the native and web server at the same time. Do you know if this can still be done and I am behind on some documentation?

Thanks

**Comment by weizlini** [comment]
that's too bad (start:web) it can't be passed from yarn to expo like --web-only could.
