### ISSUE TITLE
unable to sign in to expo via command line

### ISSUE THREAD

**Issue by dmorr041** [expo/expo-cli#174]
# READ THIS FIRST, PLEASE!

We're looking to keep questions on our forums and bug reports on the GitHub repo -- please choose whichever you feel is more appropriate for your issue:

- Post in our community forums (log in with your Expo developer account): https://forums.expo.io/c/help
- File a bug on the Expo CLI repo (for bugs related to the Expo CLI tools): https://github.com/expo/expo-cli/issues/new
- File a bug on the main Expo repo (for other bugs): https://github.com/expo/expo/issues/new
- Request a feature on Canny: https://expo.canny.io/feature-requests

Thanks for reporting the issue you found with Expo CLI!

# Required format for issues

Please make our job easier by filling this template out to completion.

## Description

1-2 sentences describing the problem you're having or the feature you'd like to request

I created an expo account and ran expo start within my project directory. I then pressed s to sign in with my expo account. The CLI prompts me to choose whether to make a new account, sign in to an existing one or cancel, and says the (Use arrow keys) to pick one, however pressing the arrow keys, pressing enter and pressing Ctrl+C all do nothing. The CLI seems to just freeze, and does not respond to any input.

## Expected Behavior

What action did you perform, and what did you expect to happen?

I attempted to sign in by pressing s after running expo start. I expected to be able to choose whether to make a new account, sign in or cancel.

## Observed Behavior

What actually happened when you performed the above actions?

Nothing. The CLI tells me to use arrow keys to choose, but does not respond to arrow keys, enter, or Ctrl+C.

If there's an error message, please paste the _full terminal output and error message_ in this code block:

```
Error text goes here!
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

C:\RengTech\ReactNativeExercise\countdown>expo diagnostics
[12:16:04] Generating diagnostics report...
[12:16:04] You can join our slack here: https://slack.expo.io/.

  Expo CLI 2.3.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.0.0.0 AI-171.4443003

  Diagnostics report:
\[12:16:08] Request failed with status code 500
[12:16:08] Set EXPO_DEBUG=true in your env to view the stack trace.

Also specify:

- Phone/emulator/simulator platform, model and version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

cd into react native project root directory

run expo start

type s to sign in

attempt to choose an option (FAILS)

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by gabgagnon** [comment]
I have the same problem and it is very annoying! I always have to scan with my camera to build my app...
I'm on Windows 10 and I have the last version of Expo-CLI.

**Comment by gabgagnon** [comment]
[There is a alternative solution.
](https://github.com/expo/expo-cli/issues/66#issuecomment-436387767)

**Comment by jakubste** [comment]
@dmorr041 sorry for a late response. Are you using Git Bash? It's not an interactive command line tool, so you'll need something like Windows Subsystem for Linux or Powershell.

**Comment by musicaldoofus** [comment]
I'm having the same issue. Tried starting up in cmd and Powershell with the same behavior.

**Comment by reginaochotzki** [comment]
I am using Ubuntu and I have the same issue
