### ISSUE TITLE
[electron] Error when start project

### ISSUE THREAD

**Issue by ggunti** [expo/expo-cli#1743]
# READ THIS FIRST, PLEASE!

We're looking to keep questions on our forums and bug reports on the GitHub repo -- please choose whichever you feel is more appropriate for your issue:

- For questions and help using Expo CLI, post in our community forums (log in with your Expo developer account): https://forums.expo.io/c/expo-cli
- File a bug on the Expo CLI repo (for bugs related to the Expo CLI tools): https://github.com/expo/expo-cli/issues/new
- File a bug on the main Expo repo (for other bugs): https://github.com/expo/expo/issues/new
- Request a feature on Canny: https://expo.canny.io/feature-requests

Thanks for reporting the issue you found with Expo CLI!

# Required format for issues

Please make our job easier by filling this template out to completion.

## Description
I created an expo project with typescript that works on web + android + iOS.
Then I installed electron for expo, following the steps described [here](https://docs.expo.io/versions/latest/guides/using-electron/).
Then, I started the project (on mac) for electron using the `yarn expo-electron start` command.

## Expected Behavior
Run the app for electron.

## Observed Behavior
The app started, but I got an error and nothing else is showed in the window:
<img width="801" alt="Captură de ecran din 2020-03-28 la 09 52 40" src="https://user-images.githubusercontent.com/26307699/77818389-913b8580-70da-11ea-844f-e82dea7fb6b6.png">

Also, in the command line I got this error message while compiling:
```
  ERROR in multi ./node_modules/electron-webpack/out/electron-main-hmr/main-hmr ./electron/main/index.js
  Module not found: Error: Can't resolve 'babel-loader' in '/Users/macbook/Desktop/react_projects/opa_builder_expo'
   @ multi ./node_modules/electron-webpack/out/electron-main-hmr/main-hmr ./electron/main/index.js main[1]

```

## Environment
  Expo CLI 3.15.5 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.7 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.15.5
Also specify:

- Phone/emulator/simulator platform, model and version: electron (macOS 10.15.2)

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by MHarris021** [comment]
I also hit this error. Installing babel-loader resolved this issue
