### ISSUE TITLE
webhook `artifactUrl` is `https://expo.io/artifacts/null`

### ISSUE THREAD

**Issue by kidroca** [expo/expo-cli#1747]
## Description

Our slack hook started to receive `{ artifactUrl: 'https://expo.io/artifacts/null' }` The last time when `artifactUrl` was working was a week ago on 23.03 and since 25th it's been `null` even though builds are successful and flagged as such in at https://expo.io/dashboard 

## Expected Behavior

Get the correct `artifactUrl` in the request payload data of the webhook

## Observed Behavior

The string`https://expo.io/artifacts/null` is received

#### Last successful hook call payload

```json
{
  "status":"finished",
  "id":"4d149823-2f0a-4103-9e2a-4fe635e7f5fa",
  "artifactUrl":"https://expo.io/artifacts/b1d14710-8faa-4c38-bf51-6b1b37561502"
}
```

#### Recent hook call payloads look like 

```json
{
  "status": "finished",
  "id": "09030144-f9a8-4c6e-83bd-006105aecdf8",
  "artifactUrl": "https://expo.io/artifacts/null",
  "releaseChannel": "staging"
}
```

## Environment

CI  node 12.16 docker image environment
Running `build:ios` using expo-cli 3.16.1

If it's relevant to the cli somehow the last expo-cli version where this was working was `3.13.2` 

## Reproducible Demo

- Have an `expo` account and login to `expo-cli` 
- Setup a build webhook (https://docs.expo.io/versions/latest/distribution/building-standalone-apps/#4-wait-for-it-to-finish-building)
- Build an app `expo build:ios`
- Wait for the webhook to be triggered 
- See the payload that the webhook was triggered with

**Comment by jkhales** [comment]
Thanks, will take a look tomorrow.

**Comment by jkhales** [comment]
This should be fixed now, thanks for letting us know!
