### ISSUE TITLE
adb process is left running after closing down the server

### ISSUE THREAD

**Issue by mekwall** [expo/expo-cli#175]
## Description

adb process is left running after closing down the server

## Expected Behavior

Closing down the server should terminate any processes spawned by it

## Observed Behavior

adb process is left running after closing down the server, so you have to manually terminate it. This is a pain on Windows because it will cause EPERM errors when trying to update your packages or delete node_modules since adb.exe is locked.

## Environment

Expo CLI 2.3.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.12.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/playpilot-64c6760d-c1d9-4541-b0c9-03ab3a210476.tar.gz

## Reproducible Demo

Can be reproduced on any system running Windows. Init a fresh app, start the server with `expo start`, stop it and then try to rimraf `node_modules` and you'll get an EPERM error since `adb.exe` is locked because it's still running.

**Comment by IanSaucy** [comment]
I wanted to chime in that I've been having this same issue as well. It normally prevents me from switching git branches and just generally makes things not run correctly. I'm running a mix of Windows 10 mostly consisting of build 1809. With expo-cli 3.7.1, I normally have to use process explorer to find ADB to kill it to switch branches. I've observed this happening on branch new machines(fresh VM in Azure) and long-running machines as well. 

Please fix this expo <3

**Comment by brentvatne** [comment]
@IanSaucy - it's definitely something we want to resolve but i have some other work to do before i can get to it. given that we know exactly what is going on and you have an environment on your machine that allows you to easily reproduce the issue, maybe you could have a go at fixing it? :)

**Comment by IanSaucy** [comment]
@brentvatne Can't promise any results but I'll give a crack at it over my winter break and see where I get!

**Comment by EvanBacon** [comment]
fixed in #1876
