### ISSUE TITLE
Request is deprecated

### ISSUE THREAD

**Issue by byCedric** [expo/expo-cli#1750]
# Required format for issues

Please make our job easier by filling this template out to completion.

## Description

[`request` is deprecated and is only in maintenance mode right now](https://github.com/request/request/issues/3142). We might want to switch to Axios fully.

## Expected Behavior

Not having deprecation warnings about `request`.

## Observed Behavior

![Screen Shot 2020-03-30 at 13 31 46](https://user-images.githubusercontent.com/1203991/77907925-d7374b80-728a-11ea-8208-5de77b921604.png)

## Environment

```
  Expo CLI 3.13.6 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
```

## Reproducible Demo

```
$ npm install -g expo-cli
```

**Comment by fson** [comment]
There seems to be only two files that use it:
https://github.com/expo/expo-cli/blob/ad26f2ad81683e011398d874108efe2b4a854e65/packages/expo-cli/src/commands/build/ios/utils/image.ts#L5
https://github.com/expo/expo-cli/blob/2abd81b14bd056f82bbca6fcb3be35c4a152cbc9/packages/xdl/src/detach/ExponentTools.ts#L6
The rest has been converted to use Axios. We can probably convert those two to use Axios as well.

**Comment by byCedric** [comment]
Duplicate of #1733
