### ISSUE TITLE
unable to install Expo cli 

### ISSUE THREAD

**Issue by ahmi354** [expo/expo-cli#1753]
![Screenshot 2020-03-31 at 3 29 55 AM](https://user-images.githubusercontent.com/62913134/77968146-0340e400-7300-11ea-92a3-d5d618ec0974.png)
i am unable to install expo cli . i was using the older version of expo cli i tried to update it but it was not working for me so i saw some comment that uninstall it and then reinstall it .so i tried to uninstall it but that  also not worked so i went to /usr/local/lib/ and from there i delete the expo folder now i am unable to reinstall it is not showing any error but after completing the installation when i try to make project the notification appears that command not found can anyone please help me how can i install it .i have tried every possible command (sudo npm install --unsafe-perm -g expo-cli) (sudo cnpm install expo-cli -g)
(sudo npm i -g expo-cli --unsafe-perm=true --allow-root)
node version v12.16.1
mac Os 10.15.4

**Comment by brentvatne** [comment]
npm is not installed properly on your machine. your path does not include it. you can check out how to get npm in your path on google, here's an example of one possible article https://medium.com/@jagatjyoti.1si13cs040/npm-g-install-npm-package-not-working-as-desired-why-why-why-19795abf0b59

**Comment by ahmi354** [comment]
i uninstalled the node and installed it from scratch but still facing the same problem that i havent get any error in installation but after installation when i try to make my project it says command not found

**Comment by brentvatne** [comment]
add this to your shell config (.zshrc or .bash_profile) and restart it:

```
export PATH="$(npm bin -g):$PATH"
```

**Comment by ahmi354** [comment]
can you please tell me how to add this because i am new in programming i dont know how to add it thank you sorry for disturbing you

**Comment by ahmi354** [comment]
thank you soo much for your help it works
