### ISSUE TITLE
Expo React Native couldn't start project on Android: “The system cannot find the path specified”

### ISSUE THREAD

**Issue by Maharoz** [expo/expo-cli#1756]
Before I update my Expo cli there is no problem when I run React Native project in Android emulator (from Android Studio) I can run it from localhost, but after I updated my expo cli I got this error:
**Couldn't start project on Android: The system cannot find the path specified**
![Screenshot_58](https://user-images.githubusercontent.com/30576161/77929538-97dd1f00-72cb-11ea-8bcb-b0dadbbf87c7.png)

**Comment by Makaru26** [comment]
same issue, someone help this issue
![def1](https://user-images.githubusercontent.com/46154422/79347029-b39c2280-7f65-11ea-92d0-2ae1003cb22d.PNG)

**Comment by fernandoalb12** [comment]
I faced the same issue. I solved the problem changing the path of my ANDROID_HOME environment variable. It was wrong!!!
Make sure that the path points to your android sdk location, for default the path is something like this:
C:\Users\YourUser\AppData\Local\Android\Sdk

I also updated my "path" system variable adding these two paths:
C:\Users\YourUser\AppData\Local\Android\Sdk\plataforms
C:\Users\YourUser\AppData\Local\Android\Sdk\plataform-tools

I hope it solve your problem too. Good luck guys!

**Comment by nightness** [comment]
For me, I ejected for fun and was playing around with Android Studio. Long story short, I ended up messing up my environment variables via ~/.bashrc (specifically for me bash in VS code on Windows 10) and adding an incorrect value for ANDROID_AVD_HOME; be sure this isn't incorrect either.

**Comment by raviish95** [comment]
nothing to worried about this if you are using expo. just open any
 emulator and install expo on the emulator then copy LAN connection
 from metro run after this open expo app in emulator just paste that
 link in clipboard now relax and chill your app is build on emulator.

**Comment by zonblade** [comment]
> I faced the same issue. I solved the problem changing the path of my ANDROID_HOME environment variable. It was wrong!!! Make sure that the path points to your android sdk location, for default the path is something like this: C:\Users\YourUser\AppData\Local\Android\Sdk
> 
> I also updated my "path" system variable adding these two paths: C:\Users\YourUser\AppData\Local\Android\Sdk\plataforms C:\Users\YourUser\AppData\Local\Android\Sdk\plataform-tools
> 
> I hope it solve your problem too. Good luck guys!

i saw you everywhere with this answer.
"I also updated my "path" system variable adding these two paths"
please provide path name bruh, we're not god that know your mind.

**Comment by Silventino** [comment]
> > I faced the same issue. I solved the problem changing the path of my ANDROID_HOME environment variable. It was wrong!!! Make sure that the path points to your android sdk location, for default the path is something like this: C:\Users\YourUser\AppData\Local\Android\Sdk
> > I also updated my "path" system variable adding these two paths: C:\Users\YourUser\AppData\Local\Android\Sdk\plataforms C:\Users\YourUser\AppData\Local\Android\Sdk\plataform-tools
> > I hope it solve your problem too. Good luck guys!
> 
> i saw you everywhere with this answer. "I also updated my "path" system variable adding these two paths" please provide path name bruh, we're not god that know your mind.

PATH is the name of the environment variable...
