### ISSUE TITLE
unable to resolve module build error 

### ISSUE THREAD

**Issue by ahmi354** [expo/expo-cli#1757]
![Screenshot 2020-03-31 at 11 43 54 PM](https://user-images.githubusercontent.com/62913134/78063413-9f72f580-73a9-11ea-80c5-9449098f26e7.png)
can anyone please help me to resolve this issue after installing some dependencies [nstall react-native-gesture-handler react-native-reanimated react-navigation-stack@1.10.3] i have start getting this error i dont know why if some on know to solve this please let me know i have update ever thing and try to make new project but i getting the same error in new project too
thank you in advance 
environment:node -v13.12.0
expo  --vesion 3.16.1
npm -v6.14.4
mac OS :10.15.4

**Comment by brentvatne** [comment]
follow the install instructions from the docs: https://reactnavigation.org/docs/getting-started#installing-dependencies-into-an-expo-managed-project

**Comment by ahmi354** [comment]
![Screenshot 2020-04-01 at 12 32 43 AM](https://user-images.githubusercontent.com/62913134/78067552-5bcfba00-73b0-11ea-81be-6c6bcc21624a.png)
now i am getting this error :(
