### ISSUE TITLE
i am getting this error :( any help ?

### ISSUE THREAD

**Issue by ahmi354** [expo/expo-cli#1758]
![Screenshot 2020-04-01 at 12 32 43 AM](https://user-images.githubusercontent.com/62913134/78067552-5bcfba00-73b0-11ea-81be-6c6bcc21624a.png)
now i am getting this error :(

_Originally posted by @ahmi354 in https://github.com/expo/expo-cli/issues/1757#issuecomment-606829776_

**Comment by brentvatne** [comment]
this is not a place to post questions, you can get support on https://forums.expo.io/

issues are for bugs. please also follow template and at least try to provide some help to people helping you, eg: by providing a mcve - https://stackoverflow.com/help/mcve
