### ISSUE TITLE
Metro Bundler has encountered an internal error.. while delete or change file names

### ISSUE THREAD

**Issue by ArronHsiao** [expo/expo-cli#176]
## Description

While I delete a folder or rename a existing file, say File.js to file.js, and then run expo start again, it will show 

![image](https://user-images.githubusercontent.com/38834142/48394823-fa259600-e74f-11e8-9b0f-fe1e57300e14.png)

## Environment

Expo CLI 2.3.8 environment info:
    System:
      OS: macOS High Sierra 10.13.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.11.1 - /usr/local/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 6.4.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^30.0.1 => 30.0.1 
      react: ^16.3.1 => 16.4.0 
      react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4 
      react-navigation: ^2.13.0 => 2.17.0 
    npmGlobalPackages:
      expo-cli: 2.3.8

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/arronhsiao-ffa0ffda-8478-4589-a8c3-44f31e283d4b.tar.gz

iphone 7 Plus, ios 11

**Comment by brentvatne** [comment]
hey there! sorry there was no reply here. this issue appears to have been resolved since it was posted, i was unable to reproduce it locally. thanks for the report nonetheless!
