### ISSUE TITLE
[Android] Error when using custom keystore: "Cannot read property 'errors' of undefined"

### ISSUE THREAD

**Issue by ShimShamSam** [expo/expo-cli#1760]
## Description

We are receiving an error when trying to build using our own keystore (not managed or created by Expo).

The issue seems to have been caused by #1700

We do not receive this error if we let Expo manage the keystore for us. In our case, this simply isn't an option.

For now, we have set the `EXPO_LECACY_API` environment variable to use the old version.

## Expected Behavior

The Android build should complete without error

## Observed Behavior

```
Cannot read property 'errors' of undefined
TypeError: Cannot read property 'errors' of undefined
    at Object.updateCredentialsForPlatform (/@expo/xdl@57.7.1/src/credentials/credentials.ts:135:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

## Environment

```
Expo CLI 3.16.1 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.16.1
```

**Comment by byCedric** [comment]
Hi @ShimShamSam! Thanks for the report and for checking out where the issue is located. I was able to reproduce this using a new project and the latest expo cli (`3.17.1`). As you said, using `EXPO_LECACY_API=true expo build:android` would work as a temporary workaround until this is resolved. Again, thanks for the issue! 😄

**Comment by nangot** [comment]
Hi same problem here with expo cli 3.17.11 !
