### ISSUE TITLE
expo build:ios not working

### ISSUE THREAD

**Issue by ytimocin** [expo/expo-cli#1764]
> I have a paid Apple dev account
> Yesterday I was able to run expo build:ios and it was working as expected
> As of this morning, I started to get this error:

![image](https://user-images.githubusercontent.com/5220939/78085732-a5001980-7370-11ea-87c6-58ed917ca645.png)

Sorry if this is the wrong place to talk about this issue but I was thinking that it might be related to a release.

**Comment by EvanBacon** [comment]
This is an error forwarded from the Apple API, here are some troubleshooting tips https://forums.expo.io/t/no-team-id-associated-with-my-apple-account/12966/2?u=bacon
