### ISSUE TITLE
Fix progress bars when publishing

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#1770]
When running `expo publish` without an existing CLI instance open (and sometimes with it open) it's really easy to reproduce this:

<img width="1766" alt="Screen Shot 2020-03-31 at 8 54 35 PM" src="https://user-images.githubusercontent.com/90494/78097720-d50be480-7391-11ea-8840-c543da61b88e.png">

**Comment by byCedric** [comment]
I see that the `@expo/simple-spinner` also conflicts with the "building bundle" messages. We might be better off refactoring the output to the "newer" format like the eject or upgrade format 😄 I'll dig into why the progress bar isn't adding a new line for now.
