### ISSUE TITLE
expo build:ios will build Android bundle

### ISSUE THREAD

**Issue by edumorlom** [expo/expo-cli#1771]
## Description
If I run 'expo build:ios', it will build the Android bundle but I didn't request that... I only requested Android. It won't build the apk but why is it building anything Android-related if I only requested iOS.
## Expected Behavior
It should only build iOS-related stuff.

## Observed Behavior
What actually happened when you performed the above actions?
Midway through the building process, before the build is queued, it says "Building Android bundle
".

## Environment

  Expo CLI 3.17.5 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.11.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.3 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.17.5

**Comment by ioness** [comment]
Hello edumorlom,

Take the following words with caution as I am just a novice...

---- AFAIK:

- Short answer:

When you expo build:ios it first executes expo publish.

- Long answer:
Expo javascript  ( which is multi plaform ) is published in a CDN for your binary to call ( OTA Update concept ) so even when you're building a binary for IOS your javascript needs to be shipped for both platforms, even if Android is never used...

The IOS binary will never touch this javascript, just download the IOS version.

**Comment by edumorlom** [comment]
Thanks! I see, so if it's not an issue it can be closed.
