### ISSUE TITLE
Validation error (SDK 37): Field: androidNavigationBar.visible - should be boolean.

### ISSUE THREAD

**Issue by pavelkukov** [expo/expo-cli#1772]
## Description
With SDK 37.0.0 - app.json -> field androidNavigationBar.visible is string.
It is updated in the docs: https://docs.expo.io/versions/v37.0.0/workflow/configuration/#androidnavigationbar

When I'm running `expo publish` it throws an error and exits.
`Error: Problem validating fields in app.json. See https://docs.expo.io/versions/v37.0.0/workflow/configuration/
 • Field: androidNavigationBar.visible - should be boolean.`

expo-cli version is 3.17.5

## Expected Behavior
To validate app.json as per specified SDK

## Observed Behavior
It fails to validate app.json properly. The project cannot be published.

```
> expo publish --release-channel dev

Publishing to channel 'dev'...
Error: Problem validating fields in app.json. See https://docs.expo.io/versions/v37.0.0/workflow/configuration/
 • Field: androidNavigationBar.visible - should be boolean.
Couldn't publish because errors were found. (See logs above.) Please fix the errors and try again.
npm ERR! code ELIFECYCLE
```

## Environment

  Expo CLI 3.17.5 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.16.0 - C:\ProgramData\nodejs\node.EXE
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.4 - C:\ProgramData\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
    npmPackages:
      expo: ^37.0.0 => 37.0.3
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4

## Reproducible Demo

In package.json I have - 
```
"expo": "^37.0.0",
....
"react-native": "https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz",```
```
In app.json
```
"sdkVersion": "37.0.0",
....
"androidNavigationBar": {
      "visible": "sticky-immersive",
```

**Comment by fson** [comment]
The validation schema should be fixed in our API now.

**Comment by pavelkukov** [comment]
Many thanks! It works for me.

**Comment by SinghRameshwar** [comment]
thank you
