### ISSUE TITLE
error to upload my own keystore

### ISSUE THREAD

**Issue by jsoares568974** [expo/expo-cli#1774]
## Description

error to upload my own keystore

## Expected Behavior

I do constant uploads of my apk, I went to do the same process as always, I managed to generate the ipa for ios, the android presented errors

Command: `expo build:android --config "variants/rocketpizza.json" --clear-credentials`

Selected: `2) I want to upload my own keystore!`

Path to keystore: /Users/macbookpro/Documents/projetos/plom-beta/plom-lanches.bak.jks
? Keystore Alias: delivery-key-alias
? Keystore Password: [hidden]
? Key Password: [hidden]

## Observed Behavior

Cannot read property 'errors' of undefined
TypeError: Cannot read property 'errors' of undefined
    at Object.updateCredentialsForPlatform (/@expo/xdl@57.7.1/src/credentials/Credentials.ts:135:21)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at AndroidBuilder.collectAndValidateCredentials (/expo-cli@3.16.1/src/commands/build/AndroidBuilder.ts:204:9)
    at AndroidBuilder.run (/expo-cli@3.16.1/src/commands/build/AndroidBuilder.ts:30:5)
    at AndroidBuilder.command (/expo-cli@3.16.1/src/commands/build/BaseBuilder.ts:29:7)
    at Command.<anonymous> (/expo-cli@3.16.1/src/exp.ts:85:7)`

## Environment

Expo CLI 3.16.1 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2 
      react: 16.12.0 => 16.12.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^4.1.1 => 4.3.6 
    npmGlobalPackages:
      expo-cli: 3.16.1

**Comment by jkhales** [comment]
Hi! Would you mind trying the same process but with 
`EXPO_LEGACY_API=true expo ...`
instead of 
`expo ...`?

**Comment by jsoares568974** [comment]
@jkhales I did the test and it worked. Thanks.

**Comment by jkhales** [comment]
> @jkhales I did the test and it worked. Thanks.

Just to be clear, does it work only when you have `EXPO_LEGACY_API=true`? Or does it work in general now?

**Comment by jsoares568974** [comment]
@jkhales works only when EXPO_LEGACY_API = true

**Comment by jkhales** [comment]
OK thanks.

**Comment by jkhales** [comment]
Hm, can't seem to repro this. Glad it's working for you, closing for now.
