### ISSUE TITLE
Warn the user if upgrading or ejecting with an old version of expo-cli

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#1778]
It's safest to be using the latest version for commands like this. We should check for the latest version (without cache) and warn people if they aren't using it, and prompt them to ask if they'd like to proceed anyways.

**Comment by EvanBacon** [comment]
we already warn users on every command if they aren't using the latest version of expo-cli

**Comment by brentvatne** [comment]
yeah but we publish enough that this becomes noise and many people ignore it. we might want to be very clear that not upgrading to the latest expo-cli for some commands could be particularly bad.
