### ISSUE TITLE
expo can't setup on windows

### ISSUE THREAD

**Issue by programmerabs** [expo/expo-cli#1780]
Npm expo-cli not setup on windows 10

My setup:
npm Version:6.13.4
node:v12.16.1

Error code:
C:\Users\INFINITYIT>npm install -g expo-cli
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/traveling-fastlane-darwin@1.13.1 (node_modules\expo-cli\node_modules\@expo\traveling-fastlane-darwin):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha512-3YivoxYTmvuA3/DZR3vAm4+6zqSnzUoaMiKTtVVJO8ykAnBrpAL4oxyZqG9FBe7H4Sz4GCk1pUAx9COIXvYGpw== integrity checksum failed when using sha512: wanted sha512-3YivoxYTmvuA3/DZR3vAm4+6zqSnzUoaMiKTtVVJO8ykAnBrpAL4oxyZqG9FBe7H4Sz4GCk1pUAx9COIXvYGpw== but got sha512-UlH4Sbtb17PEd0vi92qJO7t99xtY7QXPLvAbVNbgCzdhNRPiP1s6FVUVn2QIY22YovUL5737r6sCgEuiL4pBFQ==. (486686 bytes)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/traveling-fastlane-linux@1.13.1 (node_modules\expo-cli\node_modules\@expo\traveling-fastlane-linux):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha512-6VnrOfbU9vOtdVpkalu23q1BIyoj5AKALDWo2mVhoPm8Qi9xiIdjT+pfiMeBUDrRuAitRZ3DORmpz4RtsZqDsg== integrity checksum failed when using sha512: wanted sha512-6VnrOfbU9vOtdVpkalu23q1BIyoj5AKALDWo2mVhoPm8Qi9xiIdjT+pfiMeBUDrRuAitRZ3DORmpz4RtsZqDsg== but got sha512-YNCw9nCTgOQrtFQA/Vd7qPvkKzT/L3turWRx3zovN1YMid8VUHipxdXDDFBFZw1uathOkvwMNMK7Gyl0jYwTWA==. (425288 bytes)

npm ERR! Unexpected end of JSON input while parsing near '...sP/bTBePkjOi\ncumU7Ty'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\INFINITYIT\AppData\Roaming\npm-cache\_logs\2020-04-05T13_58_22_992Z-debug.log

**Comment by UsamaShaikh0** [comment]
Same problem

**Comment by brentvatne** [comment]
this is a problem with npm on your machine / your internet connection: https://www.google.com/search?q=npm+ERR!+Unexpected+end+of+JSON+input+while+parsing+near&rlz=1C5CHFA_enUS891US891&oq=npm+ERR!+Unexpected+end+of+JSON+input+while+parsing+near&aqs=chrome..69i57j0l7.115j0j7&sourceid=chrome&ie=UTF-8
