### ISSUE TITLE
Add a note about how to open the project in web

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo-cli#1784]
The printed note should also indicate that pressing "w" will open the project in the browser.

```
 React  You can now view p01 in the browser.

  Local:            http://localhost:19006/
  On Your Network:  http://192.168.1.10:19006/

Note that the development build is not optimized.

 › To create a production build, run expo build:web
 › Press Ctrl+C to exit.

 Expo  Press ? to show a list of all available commands.
```

**Comment by Fahad-Mahmood** [comment]
I would like to add this enhancement, I am facing issue running it on windows.

**Comment by saideepesh000** [comment]
@EvanBacon, it's there, this issue needs to be closed.

![Screenshot (266)](https://user-images.githubusercontent.com/43727167/91339611-5c03a280-e7f4-11ea-81d1-deb5aca7a9ed.png)

**Comment by EvanBacon** [comment]
Added in 7d9e6fe
