### ISSUE TITLE
Configuration of sourceExts is awkward

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#1786]
We override sourceExts provided through metro.config.js, so people need to pass them in through `packagerOpts.sourceExts` in app.json. *But* then they need to make sure to pass in all of our defaults too! See: https://github.com/kristerkari/react-native-svg-transformer#step-3-configure-the-react-native-packager

**Comment by fson** [comment]
Duplicate of https://github.com/expo/expo-cli/issues/2199
