### ISSUE TITLE
expo build fails inside xdl with "Cannot read property 'forEach' of undefined"

### ISSUE THREAD

**Issue by fwal** [expo/expo-cli#179]
## Description

After upgrading to SDK 31 (from 30), when trying to publish new app release  using `expo build:android`, the command fails with an error in xdl.

## Expected Behavior

Successful publishing of new app version.

## Observed Behavior

Error `Cannot read property 'forEach' of undefined` is thrown

```
> EXPO_DEBUG=true expo build:android
Checking if current build exists...

No currently active or previous builds for this project.
Publishing to channel 'default'...
Building iOS bundle
Building Android bundle
Analyzing assets
Uploading assets
No assets to upload, skipped.
Processing asset bundle patterns:
- **/assets/*
Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at /xdl@51.5.8/src/Project.js:924:26
    at Generator.next (<anonymous>)
    at step (node_modules/xdl/build/Project.js:2099:191)
    at node_modules/xdl/build/Project.js:2099:361
```

## Environment

```
  Expo CLI 2.3.8 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.1.0 - /var/folders/tk/y088_5bd5j35y441vr9wc94h0000gn/T/yarn--1542185394983-0.9208830028306552/node
      Yarn: 1.12.3 - /var/folders/tk/y088_5bd5j35y441vr9wc94h0000gn/T/yarn--1542185394983-0.9208830028306552/yarn
      npm: 6.4.1 - node_modules/.bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.5 => 31.0.5
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/v0.57.5.tar.gz => 0.57.5
      react-navigation: ^2.18.2 => 2.18.2
```

**Comment by fwal** [comment]
Seems to be this line [packages/xdl/src/Project.js#L924](https://github.com/expo/expo-cli/blob/master/packages/xdl/src/Project.js#L924)

**Comment by fwal** [comment]
This was due to me linking `react-native` to `v.57.5` instead of `sdk-31.0.0`. 🤦‍♂️

Did this to try to get around [this issue](https://github.com/facebook/react-native/issues/21052) in react-native. (The [workaround](https://github.com/facebook/react-native/issues/21052#issuecomment-421667360) posted there works btw)

**Comment by kevinwolfcr** [comment]
@fwal I am trying to upload using `SDK-31-with-hooks-experimental` but I am receiving the same issue, here is my diagnostics:

```
  Expo CLI 2.4.0 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.1.0 - /var/folders/9n/cv2mkp1n02d6f7t3v4f9dbq00000gn/T/yarn--1542680106176-0.31941804285834574/node
      Yarn: 1.12.3 - /var/folders/9n/cv2mkp1n02d6f7t3v4f9dbq00000gn/T/yarn--1542680106176-0.31941804285834574/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.5 => 31.0.5
      react-native: https://github.com/expo/react-native/archive/sdk-31-with-hooks-experimental.tar.gz => 0.57.4-hooks.0
    npmGlobalPackages:
      expo-cli: 2.2.5
```

Any suggested solution? Upgrading to hooks broke my CI process :(

**Comment by kevinwolfcr** [comment]
Yes, I've added `@babel/runtime@7.0.0` and `@babel/plugin-transform-runtime@^7.1.0`, additionally this is my `babel.config.js`:

```js
module.exports = function babelConfig(api) {
  api.cache(true)
  return {
    presets: ['babel-preset-expo'],
    plugins: ['@babel/plugin-transform-runtime'],
  }
}
```

And if it works, my `package.json`:

```json
{
  "private": true,
  "version": "6.0.0",
  "name": "@gopato/app",
  "main": "./app-entry.js",
  "scripts": {
    "postinstall": "flow-typed install  --overwrite",
    "start": "expo start",
    "flow": "flow",
    "lint": "eslint .",
    "stylelint": "stylelint **/*.js",
    "test": "echo 'Tests disabled'",
    "deploy": "node ./scripts/deploy.js"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.js": [
      "eslint --fix",
      "git add"
    ]
  },
  "dependencies": {
    "@babel/runtime": "7.0.0",
    "@gopato/duck-system-box": "^0.1.4",
    "@gopato/duck-system-button": "^0.1.4",
    "@gopato/duck-system-core": "^0.6.0",
    "@gopato/duck-system-default-theme": "^0.6.0",
    "@gopato/duck-system-naked-button": "^0.2.2",
    "@gopato/duck-system-separator": "^0.1.4",
    "@gopato/duck-system-social-button": "^0.1.4",
    "@gopato/duck-system-text": "^0.2.4",
    "aws-amplify": "^1.1.10",
    "aws-amplify-react-native": "^2.0.8",
    "expo": "^31.0.5",
    "react": "^16.7.0-alpha.2",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31-with-hooks-experimental.tar.gz",
    "react-navigation": "^3.0.0",
    "react-navigation-fluid-transitions": "^0.2.73",
    "react-navigation-hooks": "^1.0.0-alpha.2"
  },
  "devDependencies": {
    "@babel/plugin-transform-runtime": "^7.1.0",
    "babel-eslint": "^10.0.1",
    "change-case": "^3.0.2",
    "eslint": "^5.9.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-config-react-app": "^3.0.5",
    "eslint-plugin-flowtype": "^3.2.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.2",
    "eslint-plugin-react": "^7.11.1",
    "expo-cli": "^2.4.0",
    "flow-bin": "^0.86.0",
    "flow-typed": "^2.5.1",
    "husky": "^1.1.4",
    "lint-staged": "^8.0.5",
    "react-native-debugger-open": "^0.3.17",
    "schedule": "0.4.0",
    "stylelint": "^9.8.0",
    "stylelint-config-standard": "^18.2.0",
    "stylelint-config-styled-components": "^0.1.1",
    "stylelint-order": "^1.0.0",
    "stylelint-processor-styled-components": "^1.5.1"
  }
}
```

**Comment by blurdylan** [comment]
I had this issue, [From the docs](https://docs.expo.io/versions/latest/distribution/building-standalone-apps#2-configure-appjson) I found out that this is not a required option of app.json.

So I removed this line `"assetBundlePatterns": ["**/*"],` in the expo's `app.json`

And it worked.

**Comment by blurdylan** [comment]
Try changing `"assetBundlePatterns": ["**/*"]` to `"assetBundlePatterns": ["assets/*"]` in `app.json`

**Comment by kevinwolfcr** [comment]
@blurdylan that removes the issue, but when I try accesing the app by url, then the images are not being downloaded.

**Comment by eytanronen** [comment]
I'm having same issue described above "Cannot read property 'forEach' of undefined" when posting to expo or standalone app. Note I'm using React Hooks so relying on this specific dependencies.

These are my dependencies:

  "dependencies": {
    "expo": "^32.0.0",
    "firebase": "^5.7.2",
    "moment": "^2.23.0",
    "react": "16.7.0-alpha.2",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31-with-hooks-experimental.tar.gz",
    "react-navigation": "^3.0.9",
    "react-number-format": "^4.0.6"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0"
  },

**Comment by Filipoz** [comment]
I'm having the exact same error here.
Same project config as the beginning.
With the assetBundlePatterns: ["**/*"] or ["assets/images/*"] I get the forEach error for undefined
With the assetBundlePatterns: ["assets/*"] I get no forEach error but the app comes with no images and if I declare an personalised Icon on the app.json, I get an gradle error for file with no .png signature (already checked for wrong extension / type in the file)

Still no clue of how to fix :/

**Comment by joaowiciuk** [comment]
> assets/*

Hell yeah, it worked for me

**Comment by joaowiciuk** [comment]
> Try changing `"assetBundlePatterns": ["**/*"]` to `"assetBundlePatterns": ["assets/*"]` in `app.json`

Hell yeah, it worked for me

**Comment by RichMatthews** [comment]
anyone know why isn't the standard yet?

**Comment by niyasshefeek** [comment]
Mine is not working. i tried all the above suggestions. but no hope. please help if someone know the solution ?
Analyzing assets
Finished building JavaScript bundle in 4299ms.
Finished building JavaScript bundle in 6228ms.
Uploading assets
No assets to upload, skipped.
Processing asset bundle patterns:
- D:\MobileApp\assets\*
Cannot read property 'forEach' of undefined

below is my app.json
```
{
  "expo": {
    "sdkVersion": "32.0.0",
    "icon": "./assets/android-icon.png",
    "slug": "testapp",
    "loading": {
      "hideExponentText": true,
      "backgroundImage": "./assets/Default@2x~iphone~comany.png"
    },
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "packagerOpts": {
      "assetExts": [
        "ttf"
      ]
    },
    "androidStatusBarColor": "#334393",
    "androidStatusBar": {
      "barStyle": "light-content",
      "backgroundColor": "#334393"
    },
    "assetBundlePatterns": [
      "assets/*"
    ],
    "splash": {
      "image": "./assets/Default@2x~iphone~comany.png",
      "backgroundColor": "#FEF9B0"
    },
    "ios": {
      "bundleIdentifier": "com.app.test"
    },
    "android": {
      "package": "com.app.test"
    },
    "name": "Test App",
    "version": "2.5.0",
    "platforms": [
      "android",
      "ios"
    ],
    "description": ""
  }
}
```

**Comment by ThakurBallary** [comment]
[Solved] Update expo-cli

> npm i -g expo-cli

**Comment by aryojamousi** [comment]
still having the issue here. I have updated the expo-cli as well. It seems that this `"assetBundlePatterns": ["**/*"]` is the problematic line here. `"assetBundlePatterns": ["assets/*"]` and `"assetBundlePatterns": ["./assets/"]` don't work either. When I changed it to `"assetBundlePatterns": ["./assets/"]`, it runs without any errors and publishes the app successfully but the assets do not get displayed in the app. It seems that they do get uploaded somehow. I tried including different assets and publishing the app and the dimension of the placeholders in my app changed according to the dimensions of the image. But still they were not displayed

**Comment by Aryojaam** [comment]
Fixed the issue by downgrading my project SDK to version 32 in order to see images correctly on publishes.
```
"expo": "^32.0.0",
"expo-cli": "^2.21.1",
"react": "16.8.3",
"react-dom": "^16.8.6",
"react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
```
It is not the best workaround but it works! Maybe the devs can look into the problem in SDK 33 :)

**Comment by garfieldnate** [comment]
I had the same issue trying to update to SDK 33 for the RxDB example: https://github.com/pubkey/rxdb/pull/1268. 

I don't think this issue should be closed.

The offending line is here: https://github.com/expo/expo-cli/blob/84bae582640c0b5411160023bddb726571ea93df/packages/xdl/src/Project.js#L1037

How do we enable the debug statement a few lines above? (`ProjectUtils.logDebug`). I set the environment variable EXPO_DEBUG to`true` but that didn't do anything here.

**Comment by FabianOMB** [comment]
I have the same issue after upgrading to SDK 33. I have noticed that it works if I clear the cache first (expo start -c) and then run expo publish.

**Comment by ThalKod** [comment]
Had the same issue, 
- Clean the cache `expo start -c`
- Update expo-cli `npm i -g expo-cli`
- Update `["**/*"]` to `["assets/*"]` of assetBundlePatterns property in `app.json` 

Worked for me

**Comment by joeyfenny** [comment]
Working for me, I:

clean cache `expo start -c`
updated cli `npm i -g expo-cli`
swiched `["**/*"]` to `["assets/*"]`

also did this, but not sure I needed to
`react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz`
might switch this back and update if it still works.

Thanks @ThalKod

**Comment by trev91** [comment]
After updating `expo-cli`, I was trying to publish with `exp publish`... 
Solved the issue by publishing with `expo publish` instead!

**Comment by irshadalijan** [comment]
I had the same issue after i updated to sdk 33, but my issue got resolved with 
- Clean the cache `expo start -c`
I didn't change "assetBundlePatterns" it is same  `["**/*"]`

**Comment by oraclerevolution** [comment]
J'ai resolu mon probleme en utilisant la solution @joeyfenny !
j'ai fait un `npm install -g expo/cli` après quoi j'ai vider le cache avec `expo start -c` et j'ai remplacer `"**/*"` par `"assets/*"`

**Comment by FullMoon04** [comment]
I had the same issue when using sdk 33, but I solved it as follows.

1. npm install -g expo-cli
2.swiched ["**/*"] to ["assets/*"] in app.json

**Comment by hasanzia1993** [comment]
switching from `"**/*"` to `"assets/*"` in app.json fixes the problem of building the app but the back button for stack navigation does not appear

**Comment by superandrew** [comment]
I can confirm for the poor folks that fall into this awkward problem that simply starting expo with -c (cleaning the cache) is the simple one only fundamental thing that worked on my project.

**Comment by hasanzia1993** [comment]
I was able to fix the issue by keeping `"**/*"` so that all my assets can be included (e.g. react navigation back button which didn't include with `assets/*` ) with these steps 

- `npm install -g expo-cli` (update expo cli) 
- `expo start -c`

After that just publish your project and it should be good to go expo cli, it wasn't being updated because of some permission issue but after that was resolved, it all worked fine.

**Comment by nasof** [comment]
Is there a final solution to this?  Not a workaround.  A code fix?

**Comment by superandrew** [comment]
I'm not sure which code needs to be fixed honestly, but in my experience (this happened on two expo version switches recently, from 32 to 34 and from 34 to 35) the "final" solution (not code based, but still useful as a future reference) is

`npm install -g expo-cli`
`expo start -c`

**Comment by dev-neeraj** [comment]
> > Try changing `"assetBundlePatterns": ["**/*"]` to `"assetBundlePatterns": ["assets/*"]` in `app.json`
> 
> Hell yeah, it worked for me
> 
> **UPDATE**
> 
> In fact, I had to switch back to `"assetBundlePatterns": ["**/*"]` and change the line `"react-native": "^0.57.1",` in package.json to `"react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",`
> 
> After this I executed `expo build:android` and everything worked™

Thanks it worked for me too

**Comment by umairkhan1997** [comment]
I copy all the files instead of node module the paste that copied in new folder then i run "npm i" then
the project got run .

**Comment by nowrbuild** [comment]
@umairkhan1997 sorry but I don't understand which steps you performed exactly. Could you please elaborate?

**Comment by superandrew** [comment]
@umairkhan1997 sorry but I don't understand which steps you performed exactly. Could you please elaborate?
