### ISSUE TITLE
babel-preset-cli depends on typescript (should be a peer dep?)

### ISSUE THREAD

**Issue by ide** [expo/expo-cli#1791]
Every project that installs babel-preset-cli now has an extra copy of TypeScript c.f. the expo repo. Usually the project author wants to control the version of TS they use, in which case it should be a peer dependency.

**Comment by fson** [comment]
The `typescript` dependency was removed from the preset in https://github.com/expo/expo-cli/commit/c0c7b5bba611b0efece1febdc974e953ff94e539#diff-a6dfdf34b2055a5f70aaaad9f0e0261f.
