### ISSUE TITLE
[ios] Unable to install Expo app to iOS simulator for simulating Vue-Native blank app

### ISSUE THREAD

**Issue by xerroxcopy** [expo/expo-cli#1792]
## Description

I am running Expo-CLI via Vue-Native. Running `npm start` on a new blank vue-native project folder gives the following error. Could you identify what I am doing wrong?

## Expected Behavior

The Vue-Native hello world screen appears.

## Observed Behavior

Installed required libraries following [Vue-Native doc](https://vue-native.io/docs/installation.html). Running `npm start` opens http://localhost:19002/ as expected (though sometimes completely blacked-out. It accepts inputs like `i` on terminal though). I press 'Run on iOS simulator' and it opens. Several seconds later, the Expo app logo appears, starts loading/installing, but it stops halfway, and leaves this:
<img width="559" alt="image" src="https://user-images.githubusercontent.com/13182777/78226936-736d8680-7507-11ea-8ae5-b833fa93ed0a.png">
Clicking on the greyed-out app icon gives `Unable To Install "Expo" Please try again later.` error.

What I've tried:
- changed simulation device from iPhone 11 to 8
-  deleted the app on the simulator
- Ran `expo client:install:ios` as suggested by [doc](https://docs.expo.io/versions/latest/workflow/ios-simulator/#expo-cli-is-printing-an-error-message-about). Same error.
- Ran `Device > Erase All Contents and Settings...` as suggested by [doc](https://docs.expo.io/versions/latest/workflow/ios-simulator/#expo-cli-is-printing-an-error-message-about). No effect.
- Reinstalled `watchman` as suggested [here](https://github.com/expo/expo-cli/issues/933#issuecomment-521426547). No effect.

Error:
```
Installing Expo client on iOS simulator
-Error running `xcrun simctl install booted /Users/mm/.expo/ios-simulator-app-cache/Exponent-2.15.3.tar.app`: An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Could not install at this time.
Failed to chmod /Users/mm/Library/Developer/CoreSimulator/Devices/7F5A7653-CC1D-4FF9-A96A-0B08FCCC379F/data/Bundle/Application/C649D771-028F-40F8-8FCC-D0E9F0EF79A1/Exponent-2.15.3.tar.app/Exponent : No such file or directory
Underlying error (domain=MIInstallerErrorDomain, code=4):
        Failed to chmod /Users/mm/Library/Developer/CoreSimulator/Devices/7F5A7653-CC1D-4FF9-A96A-0B08FCCC379F/data/Bundle/Application/C649D771-028F-40F8-8FCC-D0E9F0EF79A1/Exponent-2.15.3.tar.app/Exponent : No such file or directory

Error installing or running app. Error: xcrun exited with non-zero code: 1
|
This download is taking longer than expected. You can also try downloading the clients from the website at https://expo.io/tools
|
```

## Environment

```
Expo CLI 3.17.11 environment info:
  System:
    OS: macOS 10.15.4
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    npm: 6.13.1 - ~/.npm-global/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  IDEs:
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  npmPackages:
    expo: ~37.0.3 => 37.0.3 
    react: ~16.9.0 => 16.9.0 
    react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
  npmGlobalPackages:
    expo-cli: 3.17.11
```

Possible cause?:
- I recently upgraded macOS version from 10.14 to 10.15.4, since Catalina was required for installing Xcode.
- running `npm install` gives me the following warnings:
```zsh
npm WARN vue-native-scripts@0.1.4 requires a peer of react-native@^0.59.0 but none is installed. You must install peer dependencies yourself.
npm WARN vue-native-scripts@0.1.4 requires a peer of metro@^0.51.0 but none is installed. You must install peer dependencies yourself.
npm WARN vue-native-scripts@0.1.4 requires a peer of metro-bundler@* but none is installed. You must install peer dependencies yourself.
npm WARN vue-native-scripts@0.1.4 requires a peer of metro-react-native-babel-transformer@^0.51.0 but none is installed. You must install peer dependencies yourself.
```
I am not quite sure if this is Expo-cli problem or Vue-native-cli problem.

## Reproducible Demo

If there is a nice way to reproduce this kind of environment, please let me know. I'll do whatever needed to reproduce this. I can provide `app.json` and/or `package.json` if that helps.

**Comment by brentvatne** [comment]
try deleting your global cache: `rm -rf ~/.expo` and running `expo client:install:ios` after that

**Comment by xerroxcopy** [comment]
Thank you so much. It worked as expected!
