### ISSUE TITLE
Authentication with Apple Developer Portal failed! spawn bash ENOENT

### ISSUE THREAD

**Issue by Gabrielhvcardoso** [expo/expo-cli#1797]
I was trying to build an IPA using Expo cli on my Windows 10 and I got this error:

```
> expo build:ios

Checking if there is a build in progress...

? Do you have access to the Apple account that will be used for submitting this app to the App Store? Yes
Please enter your Apple Developer Program account credentials. These credentials are needed to manage certificates, keys and provisioning profiles in your Apple
Developer account.
The password is only used to authenticate with Apple and never stored
Learn more here (​https://bit.ly/2VtGWhU​)
? Apple ID: *****
? Password (for *****): [hidden]
Authenticating to Apple Developer Portal...
Authentication with Apple Developer Portal failed!
spawn bash ENOENT
Error: spawn bash ENOENT
    at notFoundError (C:\Users\gabri\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\gabri\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\gabri\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```
I've tried several ways to do this, but I always end up with this error and I haven't found any match with it.

**Comment by tamdao** [comment]
The same issue :(

**Comment by trexpert** [comment]
Same problem using expo-cli version 3.17.18 and passing all kind of certs running this:

```
npx expo build:ios --non-interactive --release-channel $CHANNEL --apple-id $EXPO_APPLE_USERNAME --team-id $EXPO_APPLE_TEAM_ID --dist-p12-path $EXPO_APPLE_P12_PATH --push-id $EXPO_APPLE_PUSH_KEY --push-p8-path $EXPO_APPLE_P8_PATH --provisioning-profile-path $EXPO_APPLE_PROV_PATH
```

All enviroments + EXPO_APPLE_PASSWORD are set

i receive this error:

```
[...] Checking if there is a build in progress...
[...] Please enter your Apple Developer Program account credentials. These credentials are needed to manage certificates, keys and provisioning profiles in your Apple Developer account.
[...] The password is only used to authenticate with Apple and never stored
[...] Learn more here (​https://bit.ly/2VtGWhU​)
[...] Input is required, but Expo CLI is in non-interactive mode.
Pass your Apple ID using the --apple-id flag.
```

**Comment by quinlanj** [comment]
hi we've updated the `non-interactive` documentation to make it more clear what you need, and we've also made some fixes to the error handling. Could you please update to `expo-cli@3.19.2` and update us if your problem still persists?

Non Interactive Documentation: https://github.com/expo/fyi/blob/master/credentials-non-interactive.md

Past fixes:
https://github.com/expo/expo-cli/pull/1928
https://github.com/expo/expo-cli/pull/1929

**Comment by Gabrielhvcardoso** [comment]
Yeah, it's working fine right now! Thanks

**Comment by fernandojmj** [comment]
Hello, people..

can you help with error bellow ?

Authenticating to Apple Developer Portal...
Authentication with Apple Developer Portal failed!
Failed to set up Distribution Certificate
Failed to prepare all credentials.
The next time you build, we will automatically use the following configuration:

**spawn bash ENOENT
Error: spawn bash ENOENT**


 Expo CLI 3.20.1 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
    npmPackages:
      expo: ~37.0.3 => 37.0.8
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: ~0.61.5 => 0.61.5
      react-native-web: ~0.11.7 => 0.11.7
      react-navigation: ^4.3.7 => 4.3.9

**Comment by Gabrielhvcardoso** [comment]
I'm getting the same error again in expo 3.21.5.

**Comment by Gabrielhvcardoso** [comment]
The error was due to the lack of the ubunto subsystem on my machine, when I installed all ocurred right.
