### ISSUE TITLE
Possible bug with interactive prompt and sign in

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#180]
https://twitter.com/Ognjetina/status/1063092760952139776

<img width="660" alt="screen shot 2018-11-15 at 5 48 09 pm" src="https://user-images.githubusercontent.com/90494/48564436-1287e300-e8ff-11e8-89d2-b5053de808ed.png">

**Comment by EvanBacon** [comment]
- Cannot open projects via barcode scanner any more 
- Cannot open anon projects IIRC
