### ISSUE TITLE
Expo publish with expo-updates, requires `/android/app/src/main/AndroidManifest.xml`

### ISSUE THREAD

**Issue by Matt-Swingvy** [expo/expo-cli#1803]
### Environment

 Expo CLI 3.17.11 environment info:
    System:
      OS: macOS Mojave 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
      Yarn: 1.19.1 - ~/.yarn/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.3
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
    npmGlobalPackages:
      expo-cli: 3.17.11

Android

### Steps to Reproduce
```
expo init myProject
expo install expo-updates
expo publish
ENOENT: no such file or directory, open '/myProject/android/app/src/main/AndroidManifest.xml'
```

### Expected Behavior

According to https://expo.fyi/embedded-assets
No particular actions is required to publish, beside the generated app.bundle and app.manifest files.

Expecting the managed workflow not to require manually creating a `AndroidManifest.xml` file.
And publish the app successfully with a published link.

### Actual Behavior
Exiting publish cli with the error below:
`ENOENT: no such file or directory, open '/myProject/android/app/src/main/AndroidManifest.xml'`

App is not published.

**Comment by pauliedoherty** [comment]
Hi, I am also running in to same error. When I run `expo publish:history` I can see that it has logged the attempt but I am unable to view the app on a 'sharable link' for testing. Where can this link usually be found? Is there a known version that I can revert to that doesn't have this issue?

**Comment by brentvatne** [comment]
thanks for reporting this! you can continue importing `Updates` from the expo package for now, we'll get this fixed asap though

**Comment by brentvatne** [comment]
this is resolved in the latest version of expo-cli: expo-cli@3.17.18 with this commit https://github.com/expo/expo-cli/commit/14d85cca1bf6c842c5baa1e8691885cf43cf0b75
