### ISSUE TITLE
Write all logs from package manager and other tools to an expo-cli specific logfile for project

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#1806]
When you run `expo upgrade` and yarn doesn't install some dependencies properly we should dump the yarn output to something like an `expo-error.log` file.

**Comment by brentvatne** [comment]
Maybe this isn't even an error log but just a generic log of things that expo-cli is doing behind the scenes.

Then we could make it so if installing packages on npm or cocoapods is taking a while then we update the "Installing ..." message to tell people they can go check out `expo-cli.log` or whatever for more info, if that's a thing, and they could open up another tab and run `tail -f expo-cli.log` to see what's going on

**Comment by byCedric** [comment]
I think @fson had a similar idea, we talked a bit about it in our pairing session. Something like this could also be useful for issue reporting, just like `npm-debug.log` 😄
