### ISSUE TITLE
[nextjs] How to implement next-i18next to translate a Next-Expo web app, Cannot use import statement outside a module

### ISSUE THREAD

**Issue by 5ervant** [expo/expo-cli#1807]
## Description

I'm trying to translate my Next.js app made with `@expo/next-adapter` using this approach: https://github.com/isaachinman/next-i18next

## Behavior

However, upon following their instruction https://github.com/isaachinman/next-i18next#setup, I'm getting this terminal output even though my _"/public/static/locales/en/common.json"_ isn't empty:

```
react-i18next:: i18n.languages were undefined or empty _undefined_
```

And my `t('getting-started')` call is just outputting _"getting-started"_ instead of the paragraph that's listed on my _"/public/static/locales/en/common.json"_.

Is it because of how we run a Next.js app, i.e. `yarn next dev`?
By changing it with `npm run dev`, I'm getting this `SyntaxError: Cannot use import statement outside a module`:

```
> @ dev C:\Users\USER\Documents\PROJECTS\PLATFORM\APPNAME
> node server.js

C:\Users\USER\Documents\PROJECTS\PLATFORM\APPNAME\src\apis\i18n-next.js:1
import NextI18Next from 'next-i18next';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1067:16)
    at Module._compile (internal/modules/cjs/loader.js:1115:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\USER\Documents\PROJECTS\PLATFORM\APPNAME\server.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `node server.js`
npm ERR! Exit status 1
```

* "Using next.js?" section of `react-i18next` SSR documentation: https://react.i18next.com/latest/ssr#using-next-js
* "Using a custom server" section of Using Next.js with Expo for Web's Documentation: https://docs.expo.io/versions/latest/guides/using-nextjs/#using-a-custom-server
* My raised `next-i18next` issue related about this: https://github.com/isaachinman/next-i18next/issues/678

## Environment

- OS: Windows 10
- Browser: Chromium-powered browser, Chromium: 80.0.3987.122 (Official Build) (64-bit)
- Version of Next.js: "^9.2.2"
- Version of Expo: "~36.0.0"

---

Any guideline how to implement https://github.com/isaachinman/next-i18next to translate the web version of our `next-expo` app? I guess we really need that? Or best alternative if not possible...

**Comment by EvanBacon** [comment]
The custom server method is optional, I'd recommend just not using it for now.

**Comment by 5ervant** [comment]
But it's necessary to setup `next-i18next`.

> The custom server method is optional, I'd recommend just not using it for now.

Seems right, since `startServerAsync` looks lack of functionality:

```
(async () => {
  return await startServerAsync(__dirname, {
    /* port: 3000 */
  });
})();
```

@EvanBacon Any best alternative for the internationalization or translation of a Next.js app with Expo for Web?

**Comment by 5ervant** [comment]
@EvanBacon Do you think this approach will work on a serverless Next.js app with Expo for Web? https://docs.expo.io/versions/latest/sdk/localization/#usage

**Comment by 5ervant** [comment]
https://github.com/i18next/react-i18next/tree/master/example/react-native and not `next-i18next` will work.
