### ISSUE TITLE
react native starting project issue

### ISSUE THREAD

**Issue by fahad11111** [expo/expo-cli#1808]
hi anyone can help me with this, trying to setup up react-native once I start the project with npm start I get this error 

Starting project at /Users/faddy/Desktop/reactapp/rn-first-app
Cannot determine which native SDK version your project uses because the module `expo` is not installed. Please install it with `yarn add expo` and try again.
Set EXPO_DEBUG=true in your env to view the stack trace.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `expo start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
faddy@Fahads-Macbook rn-first-app %

**Comment by brentvatne** [comment]
hi! you should follow documentation to see how to get started: https://docs.expo.io/versions/v37.0.0/

basically:
- `npm i -g expo-cli`
- `expo init myproject`
