### ISSUE TITLE
Eject can end up in infinite loop if renaming package that contains old name

### ISSUE THREAD

**Issue by kgpasta** [expo/expo-cli#1814]
https://github.com/expo/expo-cli/blob/c7909f93ec454a36d9352d73c817c9e9526908da/packages/config/src/android/Package.ts#L89

If a package is named `com.example` and you rename it to `com.example.test`, the line above will cause an infinite loop - causing eject to hang.

**Comment by brentvatne** [comment]
deployed in expo-cli@3.17.16
