### ISSUE TITLE
Can't build & sign android apk with existing keystore fetched using-  expo fetch:android:keystore

### ISSUE THREAD

**Issue by marvinIsSacul** [expo/expo-cli#1816]
## Description

Hi... Please help,

As I am trying to build an apk using `expo build:android -c` and want to sign it with the keystore I initially had Expo create for me, and I saved a copy of it by using `expo fetch:android:keystore` - and I do provide the path of the keystore, as well as the alias, keystore password and password.

But I am unable to. (See below).

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:
```
Expo CLI 3.16.1 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.0 - C:\Users\Marvin\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156
    npmPackages:
      expo: ^36.0.0 => 36.0.2
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4
      react-navigation: ^3.13.0 => 3.13.0
```

## Steps to Reproduce
1. create expo app
2. build for android ( expo build:android)
3. select option 2
4. enter **correct** values for the keystore (alias, password)

## Expected Behavior
I expected to be able to build an .apk generated by expo build, signed with the supplied keystore.

## Actual Behavior
After entering the keystore information and credentials... I get the following error:
```
Cannot read property 'errors' of undefined
Set EXPO_DEBUG=true in your env to view the stack trace.
```
I am sure I am correctly entering the credentials. What could be the problem? Please help.

Thanks.

**Comment by brentvatne** [comment]
hi @marvinIsSacul! please update to the latest version of expo-cli and try again and let me know how that goes

**Comment by marvinIsSacul** [comment]
Hi @brentvatne 

As the build was urgent I ended downgrading to `npm install -g expo-cli@3.15.4`.

It did the job fine.

So that specific version that I attached in my issue message should be the problem.

May you can check that revision?

Thanks.

**Comment by brentvatne** [comment]
hi there. yeah we were aware of a related issue with that version and it has since been resolved in a more recent version. thanks for the follow up
