### ISSUE TITLE
Cannot start new build, as there is a build in progress

### ISSUE THREAD

**Issue by amaurymartiny** [expo/expo-cli#1820]
Please make our job easier by filling this template out to completion.

## Description

In my CI/CD, I'm building binaries for multiple platforms parallely:
`expo build:android -t app-bundle`
`expo build:android -t apk`
`expo build:ios`

## Expected Behavior

When I go to expo.io/builds, I expect to see my three tasks. They might be queued, that's not a problem.

## Observed Behavior

The first build runs. Then a couple of seconds later, the second build starts, and outputs:

```
Cannot start a new build, as there is already an in-progress build.
```

## Environment

Unfortunately I cannot run `expo diagnostic`, since it's on CI (Github Actions).

It's expo-cli@3.17.16, on Ubuntu 18.04.4 LTS.

## Reproducible Demo

See https://github.com/amaurymartiny/shoot-i-smoke/runs/564345714, toggle timestamps to figure out the order.
- `expo-production-binaries (android-apk)` ran the build first
- When `expo-production-binaries (android-app-bundle)` started the build, it canceled the above build, and output the error message.

The Github Action yaml file is [here](https://github.com/amaurymartiny/shoot-i-smoke/blob/a983b5ad2ed583f29d5fbf79d337179d16f6d859/.github/workflows/production.yml#L46-L77), the 3 tasks are run parallely using a matrix

## Notes

Found the following notes:
- https://github.com/expo/expo/issues/6269, no solution, I decided to create a new issue here instead of staying in that repo
- https://forums.expo.io/t/android-build-is-failing-due-to-cannot-start-a-new-build-as-there-is-already-an-in-progress-build/28538, recommends to fallback to 3.1.2, which I would like to avoid.
- Seems like a **regression** compared to expo-cli@3.15.5, see https://github.com/amaurymartiny/shoot-i-smoke/runs/524534625. Show timestamps to convince yourself that the 3 builds did run parallelly.

**Comment by brentvatne** [comment]
we only support one build at a time - it does seem like there was a brief window where we supported parallel builds but the actual regression was the fact that it was supported, not that we no longer support it 😅 it's expensive for us to run this as a free service and so this is one of the limitations we place on it. we will likely add this to our [developer services](https://expo.io/developer-services) accounts at some point in the future!

if you really want to have this workflow you describe then i recommend looking into running the builds on your own ci as well: https://docs.expo.io/versions/latest/distribution/turtle-cli/

here's a related feature request that you can upvote: https://expo.canny.io/feature-requests/p/allow-building-android-apk-and-ios-ipa-at-the-same-time
