### ISSUE TITLE
Cannot Install expo-cli 

### ISSUE THREAD

**Issue by bera5186** [expo/expo-cli#1830]
I am installing expo-cli with the command ```npm install -g expo-cli``` but my install stop by showing this error [..................] / fetchMetadata: WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142 .

It does not proceeds further and i cannot install it. It is the first time i am installing expo-cli

**Comment by bera5186** [comment]
PS C:\WINDOWS\system32> npm i -g expo-cli                                                                                                                                                       npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142                                                                             npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/traveling-fastlane-darwin@1.13.1 (node_modules\expo-cli\node_modules\@expo\traveling-fastlane-darwin):                                    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/traveling-fastlane-darwin@1.13.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})                                                                                                                                                                                                       npm ERR! Unexpected end of JSON input while parsing near '...d6MoHd+2DIwQCFEMQ929h'                                                                                                                                                                                                                                                                                                             npm ERR! A complete log of this run can be found in:                                                                                                                                            npm ERR!     C:\Users\Rahul\AppData\Roaming\npm-cache\_logs\2020-04-08T01_28_14_027Z-debug.log

**Comment by byCedric** [comment]
Hi @bera5186! We are working on removing the last parts of request from the CLI, but these are considered warnings and should not block you from installing the CLI. The error you also sent seems to be related to either the registry or local cache. Could you try to run `npm cache verify` or even `npm cache clean`? This might help fixing your cache 😄

**Comment by bera5186** [comment]
It didn't helped me 🙁 after removing requests from expo cli would you guys will do a new release ???

**Comment by sBx99** [comment]
Hello! I am facing the exact same issue, though I'm working on linux (ubuntu 18.04). I also tried out `npm cache verify` and `npm cache clean`. I can't seem to figure out what the error is since it just hangs after this 😓

![Screenshot from 2020-04-08 20-44-58](https://user-images.githubusercontent.com/52620128/78801515-715d6900-79da-11ea-8db8-331c216e5001.png)

**Comment by byCedric** [comment]
> after removing requests from expo cli would you guys will do a new release ??? 
We will do a new release once it's done. 😄  But that isn't blocking the install here.

To me it looks like a proxy or connectivity issue with NPM. You can try 2 things to either workaround it, or provide more information about the issue you are experiencing.

1. Try installing with Yarn `yarn add global expo-cli`
2. Try installing with `npm install --global --verbose expo-cli` and open a new issue with the output from this command, [as described here](https://stackoverflow.com/questions/16873973/npm-install-hangs/39376187). Without this info we can't determine the exact issue I'm afraid.

Hope it helps 😄

**Comment by allexandresampaio** [comment]
Same problem here :(

**Comment by adminov** [comment]
I ran the npm install --global --verbose expo-cli command and then stopped at boot

[..................] - fetchMetadata: http fetch GET 304 https://registry.npmjs.org/@expo%2ftraveling-fastlane-linux 207ms (from cache)

**Comment by adminov** [comment]
> > after removing requests from expo cli would you guys will do a new release ???
> 
> We will do a new release once it's done.  But that isn't blocking the install here.
> 
> To me it looks like a proxy or connectivity issue with NPM. You can try 2 things to either workaround it, or provide more information about the issue you are experiencing.
> 
> 1. Try installing with Yarn `yarn global add expo-cli`
> 2. Try installing with `npm install --global --verbose expo-cli` and open a new issue with the output from this command, [as described here](https://stackoverflow.com/questions/16873973/npm-install-hangs/39376187). Without this info we can't determine the exact issue I'm afraid.
> 
> Hope it helps

I ran the npm install --global --verbose expo-cli command and then stopped at boot

[..................] - fetchMetadata: http fetch GET 304 https://registry.npmjs.org/@expo%2ftraveling-fastlane-linux 207ms (from cache)

**Comment by adminov** [comment]
I am installing expo-cli with the command npm install -g expo-cli but my install stop by showing this  [..................] / fetchMetadata: sill resolveWithNewModule expo-cli@3.19.2 checking installable status

**Comment by adminov** [comment]
I am installing expo-cli with the command npm install -g expo-cli but my install stop by showing this error
[..................] \ fetchMetadata: sill fetchPackageMetaData error for semver@5.5.0 Unexpected end of JSON input while parsing near '.../2iOL3YN0kjANio/bMWJr'

Please help, what's up.

**Comment by brentvatne** [comment]
this is a problem with npm caching. run npm cache clean and then try again

**Comment by adminov** [comment]
> this is a problem with npm caching. run npm cache clean and then try again

![Снимок экрана (11)](https://user-images.githubusercontent.com/22399430/80438236-810b0600-8925-11ea-84d7-fa7842574a80.png)

**Comment by ishalimi** [comment]
I used yarn and I think it worked 

`yarn global add expo-cli`
