### ISSUE TITLE
Error: spawn /bin/cp ENOENT

### ISSUE THREAD

**Issue by cmcodes1** [expo/expo-cli#1839]
## Description

Spawn error occured after running the command `expo build:android`

## Expected Behavior

Project build for android.

## Observed Behavior

```
spawn /bin/cp ENOENT
Error: spawn /bin/cp ENOENT
    at notFoundError (C:\Users\chand\AppData\Local\Yarn\Data\global\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\chand\AppData\Local\Yarn\Data\global\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\chand\AppData\Local\Yarn\Data\global\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

## Environment

 Expo CLI 3.17.18 environment info:
    System:
      OS: Windows 10 10.0.17763
    Binaries:
      Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~37.0.3 => 37.0.6
      react: ~16.9.0 => 16.9.0
      react-native: ~0.61.5 => 0.61.5

**Comment by brentvatne** [comment]
hello! can you please provide more information about your project? is it an expokit project? is it a bare project? what's your app.json

**Comment by celandro** [comment]
Im not sure if I am having the same issue or not, but I am getting the same error running expo eject on windows.

I have tried both google cloud shell with and without git-bash

The logs with debug are not helpful
```
[16:44:45] Error: spawn /bin/cp ENOENT
    at notFoundError (C:\Users\celan\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\celan\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\celan\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

**Comment by 16oh4** [comment]
@cmcodes1 @brentvatne I had the same problem on Windows 10, actually today. I had to use WSL to install Ubuntu and use bash to run the build. Here are the steps that I took:

1. Run this command in Powershell to enable Windows Subsystem for Linux (WSL):
```
> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
```
2.  Restart your computer
3. Download the Linux Distribution you want to use in Microsoft's packaging here **(must be this '.Appx' format)** [](https://docs.microsoft.com/en-us/windows/wsl/install-manual).

I personally picked Ubuntu 18.04 although it shouldn't matter. Click on one of these and download to a directory of your choosing:

![image](https://user-images.githubusercontent.com/37783822/78843035-49183f00-79c7-11ea-8bc2-77b76750ec38.png)


4. Before installing it, make sure you have enough space **in your C:/ drive!!** I only had 500 MB and the installation errored out, and I could not find a way to specify the installation. I didn't measure exactly, but it was more than 3GB after install.

5. Open a new Powershell again (you can use the one in VS Code) and navigate to the folder where the .Appx file you just downloaded is at.

6. Run this command in Powershell
```
> Add-AppxPackage .\YOUR_APPX_FILENAME_HERE.appx
```

7. Once it is installed, you should see it popup in your start (home button):
![screenie](https://user-images.githubusercontent.com/37783822/78846129-6dc4e480-79d0-11ea-90f5-1cb199c59bd8.png)

Open it and wait for it to install.

8. Once it's done, you need to install nodejs to run the expo-cli in the Linux shell. You will have to fetch the repository URL because apt-get installs nodejs version 4 by default. The following will install nodejs 13.

```
$ sudo apt-get -y update
$ curl -sL https://deb.nodesource.com/setup_13.x | sudo bash -
$ sudo apt-get install -y nodejs
```

9. Navigate to your expo project and try running within the shell
```
$ expo build:android
```
10. Should work for you now!

**Comment by cmcodes1** [comment]
@brentvatne 
It's just a simple text containing react native application.
I want to build the APK and then install on my device.
If there's a simple and easy way to do so, do tell.

**app.json**
```
{
  "name": "rnapp",
  "displayName": "rnapp",
  "expo": {
    "name": "rnapp",
    "slug": "rnapp",
    "version": "1.0.0",
    "platforms": [
      "ios",
      "android",
      "web"
    ],
    "assetBundlePatterns": [
      "**/*"
    ],
    "android": {
      "package": "com.cmcodes.rnapp"  
    }
  }
}
```

**full log**
```
C:\Users\chand\Downloads\rnapp>expo build:android
Checking if there is a build in progress...


? Would you like to upload a keystore or have us generate one for you?
If you don't know what this means, let us handle it! :)
 false
Warning: Your project may contain unoptimized image assets. Smaller image sizes can improve app performance.
To compress the images in your project, abort publishing and run npx expo-optimize.
Unable to find an existing Expo CLI instance for this directory; starting a new one...
Starting Metro Bundler on port 19001.
debug Watch mode is not supported in this environment
debug Checking for a newer version of React Native
debug Current version: 0.61.5
debug No release cache found
debug No release cache found
debug Checking for newer releases on GitHub
debug No release cache found
debug Saving W/"6d6386b01438c6ef0acd213d304b5839" to cache
debug No release cache found
debug No release cache found
debug Latest release: 0.60.0
Tunnel ready.
Publishing to channel 'default'...
Building iOS bundle
Building Android bundle
Building JavaScript bundle [====================================================================================================] 100%Finished building JavaScript bundle in 1254ms.
::ffff:127.0.0.1 - - [09/Apr/2020:01:20:08 +0000] "GET /index.bundle?dev=false&minify=true&hot=false&platform=ios HTTP/1.1" 200 873952 "-" "axios/0.19.0"
Analyzing assets
Building JavaScript bundle [====================================================================================================] 100%Finished building JavaScript bundle in 994ms.
::ffff:127.0.0.1 - - [09/Apr/2020:01:20:09 +0000] "GET /index.bundle?dev=false&minify=true&hot=false&platform=android HTTP/1.1" 200 882381 "-" "axios/0.19.0"
Finished building JavaScript bundle in 926ms.
::ffff:127.0.0.1 - - [09/Apr/2020:01:20:10 +0000] "GET /index.assets?dev=false&minify=true&hot=false&platform=ios HTTP/1.1" 200 - "-" "axios/0.19.0"
Uploading assets
No assets to upload, skipped.
Processing asset bundle patterns:
- C:\Users\chand\Downloads\rnapp\**\*
Uploading JavaScript bundles
Finished building JavaScript bundle in 942ms.
::ffff:127.0.0.1 - - [09/Apr/2020:01:20:11 +0000] "GET /index.assets?dev=false&minify=true&hot=false&platform=android HTTP/1.1" 200 - "-" "axios/0.19.0"
{"name":"xdl-detach","hostname":"cmcodes","pid":5636,"level":30,"buildPhase":"reading manifest","msg":"Using manifest: {\"name\":\"rnapp\",\"slug\":\"rnapp\",\"android\":{\"package\":\"com.cmcodes.rnapp\"},\"locales\":{},\"version\":\"1.0.0\",\"platforms\":[\"ios\",\"android\",\"web\"],\"sdkVersion\":\"37.0.0\",\"dependencies\":[\"expo\",\"expo-updates\",\"react\",\"react-dom\",\"react-native\",\"react-native-gesture-handler\",\"react-native-reanimated\",\"react-native-screens\",\"react-native-unimodules\",\"react-native-web\"],\"bundledAssets\":[],\"id\":\"@cmcodes/rnapp\",\"releaseId\":\"043e7c8f-e12a-4b45-a02d-cf98d612acd3\",\"revisionId\":\"1.0.0-r.xtyeltW3K\",\"publishedTime\":\"2020-04-09T01:20:26.369Z\",\"commitTime\":\"2020-04-09T01:20:26.513Z\",\"bundleUrl\":\"https://d1wp6m56sqw74a.cloudfront.net/%40cmcodes%2Frnapp%2F1.0.0%2F03479fb66a6a6c858f978bc5f832bcce-37.0.0-ios.js\",\"releaseChannel\":\"default\",\"hostUri\":\"exp.host/@cmcodes/rnapp\"}","time":"2020-04-09T01:20:29.095Z","id":"4c8a6b70-7a00-11ea-9b45-e5cab6288fed","v":0}
{"name":"xdl-detach","hostname":"cmcodes","pid":5636,"level":30,"buildPhase":"reading manifest","msg":"Using manifest: {\"name\":\"rnapp\",\"slug\":\"rnapp\",\"android\":{\"package\":\"com.cmcodes.rnapp\"},\"locales\":{},\"version\":\"1.0.0\",\"platforms\":[\"ios\",\"android\",\"web\"],\"sdkVersion\":\"37.0.0\",\"dependencies\":[\"expo\",\"expo-updates\",\"react\",\"react-dom\",\"react-native\",\"react-native-gesture-handler\",\"react-native-reanimated\",\"react-native-screens\",\"react-native-unimodules\",\"react-native-web\"],\"bundledAssets\":[],\"id\":\"@cmcodes/rnapp\",\"releaseId\":\"d3ec5c50-9c62-4149-9add-37881f658385\",\"revisionId\":\"1.0.0-r.xtyeltW3K\",\"publishedTime\":\"2020-04-09T01:20:26.369Z\",\"commitTime\":\"2020-04-09T01:20:26.513Z\",\"bundleUrl\":\"https://d1wp6m56sqw74a.cloudfront.net/%40cmcodes%2Frnapp%2F1.0.0%2Fdf309b1183a14bfc8b3d4c0920a40041-37.0.0-android.js\",\"releaseChannel\":\"default\",\"hostUri\":\"exp.host/@cmcodes/rnapp\"}","time":"2020-04-09T01:20:29.118Z","id":"4c8dede0-7a00-11ea-9b45-e5cab6288fed","v":0}
The system cannot find the path specified.
› Closing Expo server
› Stopping Metro bundler
spawn /bin/cp ENOENT
Error: spawn /bin/cp ENOENT
    at notFoundError (C:\Users\chand\AppData\Local\Yarn\Data\global\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\chand\AppData\Local\Yarn\Data\global\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\chand\AppData\Local\Yarn\Data\global\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

**Comment by cmcodes1** [comment]
@16oh4 
Thanks for this detailed solution! But, this seems to be a lot of work just to build an APK.
If you discover any workaround, do share.

**Comment by dsychin** [comment]
I am getting the same error trying to run `expo eject` on Windows.

**Comment by vivekverma007** [comment]
I am getting the same error on eject on windows

```
spawn /bin/cp ENOENT
Error: spawn /bin/cp ENOENT
    at notFoundError (C:\Users\x\AppData\Local\Yarn\Data\global\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\x\AppData\Local\Yarn\Data\global\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\x\AppData\Local\Yarn\Data\global\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

**Comment by brentvatne** [comment]
this is the related issue: https://github.com/expo/expo-cli/issues/1827
if someone wants to open a pr to help that'd be cool! otherwise we will get to it soon

**Comment by epixapp** [comment]
Same error when I run `expo eject` on SDK 37, with the latest Expo CLI 3.20.1:
```
√ App configuration (app.json) updated.
√ Created native project directories (./ios and ./android) and updated .gitignore.
√ Updated package.json and added index.js entry point for iOS and Android.
√ Installed JavaScript dependencies.
\ Applying iOS configuration The system cannot find the path specified.
spawn /bin/cp ENOENT
Error: spawn /bin/cp ENOENT
    at notFoundError (C:\Users\...\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\...\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\...\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```


`expo diagnostics`:
```
Expo CLI 3.20.1 environment info:
System:
  OS: Windows 10 10.0.18362
Binaries:
  Node: 13.11.0 - C:\Program Files\nodejs\node.EXE
  npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
npmPackages:
  expo: ^37.0.0 => 37.0.8
  react: ~16.9.0 => 16.9.0
  react-dom: 16.9.0 => 16.9.0
  react-native: ~0.61.5 => 0.61.5
  react-native-web: ^0.11.7 => 0.11.7
  react-navigation: ^3.0.4 => 3.13.0
```
Same issue when I run through git bash.

Any idea?

**Comment by Abdelrahman-Nabil** [comment]
Same issue with expo eject on SDK 37.0.0 and latest expo-cli
any solutions ?

**Comment by Seanmclem** [comment]
my guess is the expo/RN team is primarily Mac OS based, and windows support seems like a buggy after thought. For instance, it seems the real issue here is `The system cannot find the path specified.` ... that path being `/bin/cp` which isn't a Windows path. Makes sense it can't find it.

Seems like I'll have to dust off my Macbook Air to work on this app

**Comment by erncncbk** [comment]
According to my opinion this issue related to SDK 37.0.0. 

After doing "expo eject", we should see the following question.

>?How would you like to eject your app? 

If you don't see the question above you should check your app.json file . You will probably not see anything related to 'privacy' and 'sdkVersion' inside your app.json file.

To solve this problem, you can add the following under "expo" in the app.json file.

```
"privacy": "public",
"sdkVersion": "36.0.0",
```

?We recommend upgrading to the latest SDK version before ejecting. SDK 37 introduces support for OTA updates and notifications in ejected projects and includes many features that make ejecting your project easier. Would you like to continue ejecting anyways?  You should enter yes

After doing this process, you will be able to see the question below.
>? How would you like to eject your app?
  Read more: https://docs.expo.io/expokit/eject/ (Use arrow keys)
> **Bare**: I'd like a bare React Native project. 
  ExpoKit: I'll create or log in with an Expo account to use React Native and the Expo SDK. 
  Cancel: I'll continue with my current project structure. 

If you choose  Bare workflow, there will be no problem.

**Comment by tasos31** [comment]
@erncncbk 
thanks adding `"sdkVersion": "36.0.0"` solved it.
just wanted to add you dont have to add the privacy setting.

**Comment by wiicod-team** [comment]
I haved the same pb, ths @tasos31 solution worked for me
Thanks

**Comment by subhamg** [comment]
> According to my opinion this issue related to SDK 37.0.0.
> 
> After doing "expo eject", we should see the following question.
> 
> > ?How would you like to eject your app?
> 
> If you don't see the question above you should check your app.json file . You will probably not see anything related to 'privacy' and 'sdkVersion' inside your app.json file.
> 
> To solve this problem, you can add the following under "expo" in the app.json file.
> 
> ```
> "privacy": "public",
> "sdkVersion": "36.0.0",
> ```
> 
> Now you can try expo eject process
> 
> > ?We recommend upgrading to the latest SDK version before ejecting. SDK 37 introduces support for OTA updates and notifications in ejected projects and includes many features that make ejecting your project easier. Would you like to continue ejecting anyways?
> > **You should enter yes**
> 
> After doing this process, you will be able to see the question below.
> 
> > ? How would you like to eject your app?
> > Read more: https://docs.expo.io/expokit/eject/ (Use arrow keys)
> > **Bare**: I'd like a bare React Native project.
> > ExpoKit: I'll create or log in with an Expo account to use React Native and the Expo SDK.
> > Cancel: I'll continue with my current project structure.
> 
> If you choose Bare workflow, there will be no problem.

I don't want to use sdk version 36.0.0. I still want expo services like  OTA update and notification. Which we can only get in sdk version 37.

**Comment by brentvatne** [comment]
eject should work as expected using the latest version of expo-cli on sdk37 or greater
