### ISSUE TITLE
if adb is installed, expo xdl breaks without clear error. 

### ISSUE THREAD

**Issue by superandrew** [expo/expo-cli#1858]
## Description

When Android SDK (particularly `adb`) is not installed, there is no clear error when interacting with expo xdl 

## Expected Behavior

see: https://github.com/microsoft/vscode-react-native/issues/1230

## Observed Behavior
in Android.js
`getAdbOutputAsync` fails with empty error string, which makes impossible to understand what the problem is.

This is because `e.stderr` and `e.stdout` are empty.

In this particular case a message could be created, such as "Are you sure adb is installed and in your path?"

![CleanShot 2020-04-10 at 14 25 11](https://user-images.githubusercontent.com/71364/78990594-1b520800-7b37-11ea-8680-fb6182bdc88d.png)

**Please note that while `react-native doctor` warns me of a missing Android installation, expo doctor doesn't!**

## Environment

```

  Expo CLI 3.17.21 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.12.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.17.15
```

## Reproducible Demo

Just remove adb from your path and use https://github.com/microsoft/vscode-react-native to debug your expo project from VS Code.

**Comment by SounD120** [comment]
I think this is not even connected with the `vscode-react-native` extension since it just tries to read `stderr` outputs from the XDL. XDL package functions that uses ADB should return correct error messages if ADB is not found (`null` or `undefined`).
