### ISSUE TITLE
Three.js for both Next.js and native apps with Expo for Web

### ISSUE THREAD

**Issue by 5ervant** [expo/expo-cli#1861]
## Description

I'm planning to build Three.js graphics on both Next.js and native applications with Expo for Web.

## Behaviors

When I follow this Next.js example with Three.js: https://github.com/zeit/next.js/blob/canary/examples/with-three-js/pages/boxes.js

I'm getting this error on my native environment when I run my native app:
> Unable to resolve "expo-gl" from "node_modules\react-three-fiber\native.js"
> Failed building JavaScript bundle.

And when I follow this `expo-three` Usage: https://github.com/expo/expo-three#usage
I'm now getting this on my Next.js environment if I start my Next.js localhost:
> SyntaxError: Cannot use import statement outside a module

How would I make Three.js work for both Next.js and native apps with `@expo/next-adapter`?
Any example for that?

## Environment

- OS: Windows 10
- Browser: Chromium-powered browser, Chromium: 80.0.3987.122 (Official Build) (64-bit)
- Version of Next.js: "^9.2.2"
- Version of Expo: "~36.0.0"

**Comment by EvanBacon** [comment]
This is a common problem with Next.js. Please refer to this thread about using react-three-fiber with Next.js https://spectrum.chat/react-three-fiber/general/nextjs-build-using-react-three-fiber~535837b1-83c8-4b3b-9084-9aa8a221cef4

**Comment by 5ervant** [comment]
@EvanBacon No, I mean `react-three-fiber` is working well with Next.js app but not on the Expo native app.

**Comment by brentvatne** [comment]
to be fair that is not at all what is described in the issue you posted.. can you please provide a minimal reproducible example? it sounds like this has nothing to do with nextjs

**Comment by 5ervant** [comment]
@brentvatne When I implement this: https://github.com/zeit/next.js/blob/canary/examples/with-three-js/pages/boxes.js
It's working on my Next.js app but not on my Expo native app.

When I switch to implement this: https://github.com/expo/expo-three#usage
It will work on my Expo native app but not on my Next.js app.

Remember my Next.js and Expo native apps with `@expo/next-adapter` are sharing some same codes.

One of the solutions that I'm thinking for this, is just to pass the **page objects** for Next.js _(not supported on Expo native)_ as arguments for Next.js app and pass the **screen objects** for Expo native _(not supported on Next.js)_ as args for Expo native app.
If that doesn't work, then just build two Three.js programs for my Next.js and for my Expo native app.

Is there any solution or example that described how to make Three.js work on both Next.js and Expo native platforms? It would be really great to just have a single component for multiple platforms.

Or do I really need to create two different Three.js programs?

**Comment by 5ervant** [comment]
This `Test` component is working well on Next.js web app, except that some text of the web page are being selected by clicking a `Box`' `mesh`:

```
import React, { useRef, useState, Suspense } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { useTranslation } from 'react-i18next';
import { Canvas, useFrame } from 'react-three-fiber';

export default function Test() {
  const { t } = useTranslation('test');

  return (
    <View style={styles.container}>
      <Text>{t('title')}</Text>

      <BirdsPage />
    </View>
  );
}

const Box = (props) => {
  const mesh = useRef();

  const [hovered, setHover] = useState(false);
  const [active, setActive] = useState(false);

  useFrame(() => (mesh.current.rotation.x = mesh.current.rotation.y += 0.01));

  return (
    <mesh
      {...props}
      ref={mesh}
      scale={active ? [6, 6, 6] : [5, 5, 5]}
      onPointerUp={(e) => setActive(!active)}
      onPointerOver={(e) => setHover(true)}
      onPointerOut={(e) => setHover(false)}
    >
      <boxBufferGeometry attach="geometry" args={[1, 1, 1]} />
      <meshStandardMaterial
        attach="material"
        color={hovered ? '#2b6c76' : '#720b23'}
      />
    </mesh>
  );
};

const BirdsPage = () => {
  return (
    <Canvas
      style={{ width: 200, height: 100 }}
      camera={{ position: [0, 0, 35] }}
    >
      <ambientLight intensity={2} />
      <pointLight position={[40, 40, 40]} />
      <Suspense fallback={null}>
        <Box position={[10, 0, 0]} />
        <Box position={[-10, 0, 0]} />
        <Box position={[0, 10, 0]} />
        <Box position={[0, -10, 0]} />
      </Suspense>
    </Canvas>
  );
};

const styles = StyleSheet.create({
  container: { marginBottom: 50 },
});
```

The animation is still working on Expo native app, but the `Box`es are not clickable with the following YellowBox warnings:

> (28) window.performance.clearMeasures is not implemented
> (28) windows.performance.clearMarks is not implemented
> (28) window.performance.measure is not implemented
> (28) window.performance.mark is not implemented

I tried to capture the initial output on the terminal:

```
Warning: THREE.WebGLRenderer: OES_texture_float extension not supported.
Warning: THREE.WebGLRenderer: WEBGL_depth_texture extension not supported.
Warning: THREE.WebGLRenderer: OES_texture_half_float extension not supported.       
Warning: THREE.WebGLRenderer: OES_texture_half_float_linear extension not supported.
Warning: THREE.WebGLRenderer: OES_standard_derivatives extension not supported.     
Warning: THREE.WebGLRenderer: OES_element_index_uint extension not supported.       
Warning: THREE.WebGLRenderer: ANGLE_instanced_arrays extension not supported.       
Warning: THREE.WebGLRenderer: OES_texture_float_linear extension not supported.     
Warning: THREE.WebGLRenderer: EXT_blend_minmax extension not supported.
Warning: THREE.WebGLRenderer: EXT_frag_depth extension not supported.
Warning: THREE.WebGLRenderer: WEBGL_draw_buffers extension not supported.
Warning: THREE.WebGLRenderer: EXT_shader_texture_lod extension not supported.       
```

ref: https://github.com/react-spring/react-three-fiber/issues/338#issue-598222474

**Comment by jakubrpawlowski** [comment]
I'm running into this as well. I'm not using Next - just `react-three-fiber` and `expo-gl`. On the web it all works great, but on my iPhone XR click on Box take 0.5seconds to update scene and I'm seeing same warnings.

Before I dive deeper, curious what did you end up doing @5ervant ?

**Comment by 5ervant** [comment]
@jakubrpawlowski https://github.com/react-spring/react-three-fiber/issues/338#issuecomment-614854465
