### ISSUE TITLE
expo init needs regex for naming conventions related to Firebase apps & exposing of SHA1 keys for Firebase on managed workflow

### ISSUE THREAD

**Issue by 16oh4** [expo/expo-cli#1865]
I was trying to implement expo-firebase-core and I noticed expo bare workflow automatically names packages based on the expo init name. On a manged workflow, although this is abstracted to the user, I am assuming the same naming convention is applied because I had issues with Firebase detecting expo-firebase-core.

This is an issue when registering a Firebase app for iOS (not Android):

![image](https://user-images.githubusercontent.com/37783822/79031492-9847a680-7b64-11ea-87ca-aca7bebe7aa0.png)

This is a proof the CLI does not apply this naming convention:

![image](https://user-images.githubusercontent.com/37783822/79031382-fa53dc00-7b63-11ea-9cfc-86b79d01e4be.png)

Also, the user cannot fetch debug keys present in ./android using
```
./gradlew signingReport
```
on bare workflows for use with initializing Android Firebase apps:
![image](https://user-images.githubusercontent.com/37783822/79031566-29b71880-7b65-11ea-83ed-030a216ccc2f.png)

**Comment by brentvatne** [comment]
cc @fson apparently underscores are invalid?

**Comment by IjzerenHein** [comment]
Hi! For managed you need to set the iOS bundleIdentifier and Android package in app.json. Do you mean that you set the `bundleIdentifier ` in `app.json` to `com.16oh4_managed` and you didn't get an error from the cli?

> Also, the user cannot fetch debug keys present in ./android using `./gradlew signingReport`

This only applies when you're building debug builds using the bare-workflow and not to managed

**Comment by brentvatne** [comment]
ah yeah, i read this issue incorrectly, good points @IjzerenHein.

@16oh4 - please refer to https://docs.expo.io/versions/v37.0.0/distribution/building-standalone-apps/#2-configure-appjson for information on how to set your bundle id and package in your app
