### ISSUE TITLE
add support for yarn workspaces in expo update

### ISSUE THREAD

**Issue by Albert-Gao** [expo/expo-cli#1867]
I have a yarn workspace setup

---project root
------universal (expo managed workflow)
------serverless
------shared

All works good, the `universal` project has a `"expo-yarn-workspaces": "^1.2.1"` dev-dependency.

1. under `./universal`
1. running `yarn`, no errors
![image](https://user-images.githubusercontent.com/18282328/79041603-2eeb9480-7c45-11ea-8fe7-2b5a70b8f04c.png)
1. running `expo update`, get the error
![image](https://user-images.githubusercontent.com/18282328/79041637-58a4bb80-7c45-11ea-9548-0bb47f5ceb69.png)
1. running `yarn` again, now gets error
![image](https://user-images.githubusercontent.com/18282328/79041647-74a85d00-7c45-11ea-9959-027f3a407750.png)
1. check the `./proejctRoot/universal/node_modules`, the `expo` module folder has been replaced as a sym link.

Just wonder what command does it run when tried to update the expo sdk?
Shouldn't it be `yarn workspace universal add expo`? `universal` refers to the workspace name which can be found in the `./projectRoot/package.json`:

```json
{
  "private": true,
  "workspaces": [
    "shared",
    "universal",
    "serverless"
  ]
}
```

Can compare the value with the __dirname to get it.

Or, I miss something?

**Comment by brentvatne** [comment]
can you open a pull request to fix any issues with expo update in yarn workspaces?

**Comment by Albert-Gao** [comment]
Could do, am thinking how to write a proper test for this... Should be a good start. Any clues?

**Comment by brentvatne** [comment]
we can help guide you around how to write a good test when we see the scope of the changes. it's possible that integration testing isn't necessary and unit tests will be sufficient

**Comment by Albert-Gao** [comment]
Thanks, how to build a local expo-cli and run it?

**Comment by brentvatne** [comment]
instructions are here https://github.com/expo/expo-cli/blob/master/CONTRIBUTING.md

**Comment by Albert-Gao** [comment]
Thanks. I actually read that instruction, I got everything running, but how to test my local expo-cli after changing?

**Comment by brentvatne** [comment]
run the bin/expo.js file in packages/expo-cli. i like to set up an alias:

```
alias local-expo="node ~/code/expo-cli/packages/expo-cli/bin/expo.js"
```
