### ISSUE TITLE
 web  Failed to compile.  Failed to find the instance of sharp used by the global sharp-cli package.

### ISSUE THREAD

**Issue by haksa** [expo/expo-cli#1874]
I want to run expo start:web, it's always get to this point, what should i do?

I'm using:
expo-cli 3.17.23
SDK 37
Node Version 12.16.2
Expo Managed Workflow

and here's maybe help

![image](https://user-images.githubusercontent.com/33511114/79205997-e44a6200-7e68-11ea-9c64-b1ab0451e925.png)

### Edited
FOUND SOMETHING, when i build a new one, this "thing" didn't appear, don't know why, something problem with my last project? but my last project running good in Android.

Please help :(

**Comment by EvanBacon** [comment]
Perhaps your copy of sharp-cli is corrupted?
`npm uninstall -g sharp-cli && npm install -g sharp-cli`
If the problem persists you can just uninstall sharp-cli and it will skip this step.

**Comment by haksa** [comment]
dude,
> If the problem persists you can just uninstall sharp-cli and it will skip this step.

thats work! thanks a lot

**Comment by barnu5** [comment]
Still having this issue - `expo optimise` worked but causes this issue with builds therafter.

Consider re-opening

**Comment by mediansapp** [comment]
great dude,

If days this problem persists, you can uninstall sharp-cli and this step will be skipped, thanks a lot

**Comment by barnu5** [comment]
Still having this issue - removing globally installed sharp-cli is the only fix.

**Comment by fhirfly** [comment]
You should at least remove the warning about installing sharp-cli in your web build output.

**Comment by brentvatne** [comment]
please post a new issue with full context on what you are experiencing :)
