### ISSUE TITLE
manual installation

### ISSUE THREAD

**Issue by Brayacon** [expo/expo-cli#188]
how can I setup the expo-cli when manually installed it from the repo. my computer has network issues so I had to install it manually in another one.

**Comment by fson** [comment]
You can install dependencies and build the project locally by running `yarn run bootstrap` in the root folder of the repo (see [CONTRIBUTING.md](https://github.com/expo/expo-cli/blob/master/CONTRIBUTING.md#setting-up-the-repository-for-development)). This add the `expo` executable in the local path `./node_modules/.bin/expo`. This is useful when you're developing Expo CLI.

However, for using Expo CLI, right now the supported way to install it is with npm or Yarn.
