### ISSUE TITLE
Set up automated changelog

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#1883]
https://github.com/lerna/lerna-changelog
https://github.com/conventional-changelog/conventional-changelog
https://github.com/semantic-release/changelog

Something like these. Just one changelog for the monorepo seems fine to me to keep things simple.

**Comment by byCedric** [comment]
I think semantic release might be a bit "too much" for this. That pretty much automates the whole process, based on conventional commit types. Would recommend something more based on PRs like Lerna's changelog 😄

**Comment by brentvatne** [comment]
even something custom would be useful, like a github action that runs on release commits on master and does the manual work of:

1. renaming the "master" header to the `[date](link-to-release-commit-commit)`
2. adding template back to the top
3. commit the change

**Comment by brentvatne** [comment]
here's what i'm using right now: https://github.com/expo/expo-cli/blob/master/scripts/changelog-draft.js

closing this because it's not going anywhere, but definitely open to improving this
