### ISSUE TITLE
expo-optimize no longer working. Can't find sharp-cli

### ISSUE THREAD

**Issue by bayoremit** [expo/expo-cli#1900]
## Description

Any attempt of trying to run expo-optimize results in the error [below](#Observed-Behavior)

```sh
This will overwrite the original assets.

› Optimizing assets...
› Cannot optimize images without sharp-cli.
› Run this command again after successfully installing sharp with `npm install -g sharp-cli`
```

After digging a bit more, it seems the actual culprit is `@exp/image-util` as this is where the sharp detection logic lies.

Potential issue might be due this [commit](https://github.com/expo/expo-cli/commit/8b9b581c732b5a5e8c7f6907de5f7f141f9cf585) and this [findSharpBinAsync](https://github.com/expo/expo-cli/blob/3d849b51b8176065285fe65a3c461522f28037aa/packages/image-utils/src/sharp.ts#L95)

## Expected Behavior

Ran `yarn expo-optimize` and expected it to optimize my expo assets

## Observed Behavior

Expo did not optimize, but rather error-ed out

```sh
This will overwrite the original assets.

› Optimizing assets...
› Cannot optimize images without sharp-cli.
› Run this command again after successfully installing sharp with `npm install -g sharp-cli`
```

## Environment

```sh
  Expo CLI 3.18.2 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.2/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: 37.0.7 => 37.0.7 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.18.2
```

Also specify:

- expo-optimize: v0.1.19
- sharp-cli: v1.13.1

## Reproducible Demo

- Install `sharp-cli`
- init managed workflow expo project
- Install `expo-optimize` as dev dependency
- Run `yarn expo-optimize`
- DO NOT PROFIT.. :(

**Comment by byCedric** [comment]
Hi @bayoremit! Thanks for bringing this up and doing some research about this ❤️ Just to double check, did you add `expo-optimize` and `sharp-cli` as dependency to your `package.json`? If so, could you try if this works when installing `sharp-cli` globally? I created a PR in the meantime, let's get this fixed! 😄

**Comment by bayoremit** [comment]
Hey @byCedric 
`expo-optimize` is installed as a dev dep in my `package.json` and `sharp-cli` is installed globally to npm. Will try your suggestion soon and report back
Thanks

**Comment by bayoremit** [comment]
Apparently testing that was faster than expected. I have the same issue as described. Both of the deps included in `package.json` (devDep) did not work. `expo-optimize` still cant find `sharp-cli`

**Comment by byCedric** [comment]
Thanks for testing! I created a PR to fix this, shouldn't take too long to merge it and update the CLI. You might be able to work around this issue by using `expo-cli@3.17.24` locally in your project. I haven't test this myself, but that does not include the commit you mentioned. Again, thanks a lot for reporting this 😄

**Comment by bayoremit** [comment]
Super thanks. Happy to validate and report back

**Comment by JunaidChaudry** [comment]
Is this fixed yet? I am having the same issue, and seems like it still hasn't been fixed. I am using `expo-cli@3.20.1`

**Comment by brentvatne** [comment]
@byCedric - can you investigate this? able to repro on my end too:

```
╭─~/code/loadcsv ‹master›
╰─$ npx expo-optimize
npx: installed 1 in 1.332s

This will overwrite the original assets.

› Optimizing assets...
› Cannot optimize images without sharp-cli.
› Run this command again after successfully installing sharp with `npm install -g sharp-cli`
╭─~/code/loadcsv ‹master›
╰─$
╭─~/code/loadcsv ‹master›
╰─$ npm i -g sharp-cli                                                                                  130 ↵
/usr/local/bin/sharp -> /usr/local/lib/node_modules/sharp-cli/bin/cli.js
+ sharp-cli@1.13.1
updated 2 packages in 4.306s
╭─~/code/loadcsv ‹master›
╰─$ npx expo-optimize
npx: installed 1 in 0.758s

This will overwrite the original assets.

› Optimizing assets...
› Cannot optimize images without sharp-cli.
› Run this command again after successfully installing sharp with `npm install -g sharp-cli`
```

**Comment by JunaidChaudry** [comment]
seems to work... Thanks!

**Comment by xoco-o** [comment]
Is this fixed yet? I have same issue

**Comment by JunaidChaudry** [comment]
> @byCedric - can you investigate this? able to repro on my end too:
> 
> ```
> ╭─~/code/loadcsv ‹master›
> ╰─$ npx expo-optimize
> npx: installed 1 in 1.332s
> 
> This will overwrite the original assets.
> 
> › Optimizing assets...
> › Cannot optimize images without sharp-cli.
> › Run this command again after successfully installing sharp with `npm install -g sharp-cli`
> ╭─~/code/loadcsv ‹master›
> ╰─$
> ╭─~/code/loadcsv ‹master›
> ╰─$ npm i -g sharp-cli                                                                                  130 ↵
> /usr/local/bin/sharp -> /usr/local/lib/node_modules/sharp-cli/bin/cli.js
> + sharp-cli@1.13.1
> updated 2 packages in 4.306s
> ╭─~/code/loadcsv ‹master›
> ╰─$ npx expo-optimize
> npx: installed 1 in 0.758s
> 
> This will overwrite the original assets.
> 
> › Optimizing assets...
> › Cannot optimize images without sharp-cli.
> › Run this command again after successfully installing sharp with `npm install -g sharp-cli`
> ```
> 
> edit: it looks like an alpha version was marked as latest when published :\ I reset it back to 0.1.23 as the latest
> 
> @JunaidChaudry - run `npx expo-optimize@0.1.23` to get around npx caching

**Comment by byCedric** [comment]
@JunaidChaudry I can't repro this using both a locally and globally installed `sharp-cli`. Could you try running `npx expo-optimize --version` for me, to double-check the version you are running?

**Comment by SampsonCrowley** [comment]
Im still seeing this with v0.1.77

The point of npx is supposed to be that other packages are managed, not needing to also install other global dependencies

**Comment by brentvatne** [comment]
@SampsonCrowley - sharp is a native package that can often break on various machine configurations (eg: new node versions), and we have found that when developers see an error when running any expo command they tend to assume that it is due to that command and not the dependencies. so we want to make it clear that sharp-cli is being used here, since that will help them understand intuitively where to look to get support on resolving their issue. also, this allows us to release new versions of expo-optimize without requiring developers to rebuild sharp. computers are hard. open to suggestions for how to improve this

**Comment by brentvatne** [comment]
here's an example of running this command:

```
╭─~/code/blanky ‹master›
╰─$ npx expo-optimize
npx: installed 1 in 1.266s

This will overwrite the original assets.

› Optimizing assets...
› Cannot optimize images without sharp-cli.
› Run this command again after successfully installing sharp with `npm install -g sharp-cli`
╭─~/code/blanky ‹master›
╰─$ npm i -g sharp-cli
/Users/brentvatne/.nvm/versions/node/v14.15.2/bin/sharp -> /Users/brentvatne/.nvm/versions/node/v14.15.2/lib/node_modules/sharp-cli/bin/cli.js

> sharp@0.24.1 install /Users/brentvatne/.nvm/versions/node/v14.15.2/lib/node_modules/sharp-cli/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /Users/brentvatne/.npm/_libvips/libvips-8.9.0-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=14.15.2 runtime=node arch=x64 libc= platform=darwin)
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
  CXX(target) Release/obj.target/sharp/src/operations.o
  CXX(target) Release/obj.target/sharp/src/pipeline.o
  CXX(target) Release/obj.target/sharp/src/sharp.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
  SOLINK_MODULE(target) Release/sharp.node
ld: warning: directory not found for option '-L/usr/local/opt/ruby/lib'
ld: warning: dylib (../vendor/lib/libvips-cpp.42.dylib) was built for newer macOS version (10.13) than being linked (10.7)
ld: warning: dylib (../vendor/lib/libvips.42.dylib) was built for newer macOS version (10.13) than being linked (10.7)
ld: warning: dylib (../vendor/lib/libglib-2.0.0.dylib) was built for newer macOS version (10.13) than being linked (10.7)
ld: warning: dylib (../vendor/lib/libgobject-2.0.0.dylib) was built for newer macOS version (10.13) than being linked (10.7)
+ sharp-cli@1.14.1
added 145 packages from 125 contributors in 23.221s
╭─~/code/blanky ‹master›
╰─$ npx expo-optimize
npx: installed 1 in 0.772s

This will overwrite the original assets.

› Optimizing assets...
› Checking assets/adaptive-icon.png
 › Skipping: Original was 22.4 kB smaller.
› Checking assets/favicon.png
 › Skipping: Original was 872 B smaller.
› Checking assets/icon.png
 › Skipping: Original was 22.2 kB smaller.
› Checking assets/splash.png
 › Skipping: Original was 13.1 kB smaller.

› All assets were fully optimized already.
```

**Comment by SampsonCrowley** [comment]
@brentvatne the fact that it works as soon as you run a global install is the problem. This package should be including sharp-cli in it's dependencies if it depends on it.

The whole point of `npx` is to be able to run a self-contained command without separate installation, and if you have to install a required dependency separately, then the command isn't set up for `npx` correctly

**Comment by SampsonCrowley** [comment]
If you are going to require a separate installation, you might as well skip running it with `npx` and run it with standard run commands in the docs so users don't expect it to run as a self-contained command

**Comment by brentvatne** [comment]
i've explained our reasoning already. expo-optimize includes the logic around using sharp-cli to optimize images in your project. sharp-cli is a separate bin that we ask the user to have on their machine to run the command. it's good to follow expectations of a tool but we shouldn't do it blindly.

many commands depend on other local binaries to work. sharp itself depends on the existence of compilers. expo-cli and react-native-cli depend on the existence of adb and xcrun, to name a couple

**Comment by SampsonCrowley** [comment]
@brentvatne sharp is a node binary, it's not a native package. If your package depends on sharp, it needs to be a dependency, and you don't want users to have to rebuild, don't change the dependency range or list it as a `>=`; if it works with literally any version, then put the dependency range as a `"*"`. If users _already_ have it installed, it won't be rebuilt. For users running for the first time, if there's an error, _then_ you can allow users to install their own version by showing the error above.

`npx` packages are still installed to a global folder if not installed at command time, they aren't redownloaded on every single run. Showing an error _first_ then running is bad UX

`adb` is not the same as what is happening here. If this was a native package missing error, I wouldn't be commenting

**Comment by SampsonCrowley** [comment]
@brentvatne if it's that important to leave it out, then leave it out; I'm just putting my two cents in for how most users expect commands to work

**Comment by brentvatne** [comment]
sharp has native extensions, and its capabilities are accessed through js. whether you install it through homebrew or npm i think it doesn't matter really, the key part is that this is part of the installation process:

```
╰─$ npm i -g sharp-cli
/Users/brentvatne/.nvm/versions/node/v14.15.2/bin/sharp -> /Users/brentvatne/.nvm/versions/node/v14.15.2/lib/node_modules/sharp-cli/bin/cli.js

> sharp@0.24.1 install /Users/brentvatne/.nvm/versions/node/v14.15.2/lib/node_modules/sharp-cli/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /Users/brentvatne/.npm/_libvips/libvips-8.9.0-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=14.15.2 runtime=node arch=x64 libc= platform=darwin)
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
  CXX(target) Release/obj.target/sharp/src/operations.o
  CXX(target) Release/obj.target/sharp/src/pipeline.o
  CXX(target) Release/obj.target/sharp/src/sharp.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
  SOLINK_MODULE(target) Release/sharp.node
ld: warning: directory not found for option '-L/usr/local/opt/ruby/lib'
ld: warning: dylib (../vendor/lib/libvips-cpp.42.dylib) was built for newer macOS version (10.13) than being linked (10.7)
ld: warning: dylib (../vendor/lib/libvips.42.dylib) was built for newer macOS version (10.13) than being linked (10.7)
ld: warning: dylib (../vendor/lib/libglib-2.0.0.dylib) was built for newer macOS version (10.13) than being linked (10.7)
ld: warning: dylib (../vendor/lib/libgobject-2.0.0.dylib) was built for newer macOS version (10.13) than being linked (10.7)
+ sharp-cli@1.14.1
```

try running `npx sharp-cli --help` twice. this is the experience that you would get when running `npx expo-optimize` if we bundled it

**Comment by SampsonCrowley** [comment]
> try running `npx sharp-cli --help` twice. this is the experience that you would get when running `npx expo-optimize` if we bundled it.

It installs the first time, when it hasn't been installed yet (as expected), then it uses the installed version the second time (as expected)

If there's really no way to include it as a dependency so users don't have to run things twice, then the error message should at the least provide a link to an explanation of why it's not installed by the automatic installation process `npx` uses so users like me don't think it's a dependency issue

**Comment by SampsonCrowley** [comment]
![Screenshot from 2021-02-24 14-05-23](https://user-images.githubusercontent.com/22461638/109065855-6e7a6e00-76a9-11eb-80ef-2bbe76fad349.png)

I used `--version` instead for this screenshot just to make it easier to screenshot, but it works the same with `--help` too

**Comment by brentvatne** [comment]
what node version are you using?

**Comment by brentvatne** [comment]
```
╭─~/code/eas-example ‹master›
╰─$ time npx sharp-cli
info sharp Using cached /Users/brentvatne/.npm/_libvips/libvips-8.9.0-darwin-x64.tar.gz
ld: warning: directory not found for option '-L/usr/local/opt/ruby/lib'
ld: warning: dylib (../vendor/lib/libvips-cpp.42.dylib) was built for newer macOS version (10.13) than being linked (10.7)
ld: warning: dylib (../vendor/lib/libvips.42.dylib) was built for newer macOS version (10.13) than being linked (10.7)
ld: warning: dylib (../vendor/lib/libglib-2.0.0.dylib) was built for newer macOS version (10.13) than being linked (10.7)
ld: warning: dylib (../vendor/lib/libgobject-2.0.0.dylib) was built for newer macOS version (10.13) than being linked (10.7)
Missing required arguments: input, output

Specify --help for available options
npx sharp-cli  17.45s user 5.69s system 74% cpu 31.106 total
╭─~/code/eas-example ‹master›
╰─$ time npx sharp-cli                                                                                                                                                                                                                                    1 ↵
info sharp Using cached /Users/brentvatne/.npm/_libvips/libvips-8.9.0-darwin-x64.tar.gz
ld: warning: directory not found for option '-L/usr/local/opt/ruby/lib'
ld: warning: dylib (../vendor/lib/libvips-cpp.42.dylib) was built for newer macOS version (10.13) than being linked (10.7)
ld: warning: dylib (../vendor/lib/libvips.42.dylib) was built for newer macOS version (10.13) than being linked (10.7)
ld: warning: dylib (../vendor/lib/libgobject-2.0.0.dylib) was built for newer macOS version (10.13) than being linked (10.7)
ld: warning: dylib (../vendor/lib/libglib-2.0.0.dylib) was built for newer macOS version (10.13) than being linked (10.7)
Missing required arguments: input, output

Specify --help for available options
npx sharp-cli  17.25s user 4.45s system 76% cpu 28.445 total
```

node v14.15.2 / npm 6.14.9

**Comment by SampsonCrowley** [comment]
@brentvatne 15.1.0 on arch linux

but as far as the fact it didn't install twice, that's just how `npx` works, nothing to do with my system. if first looks in local `node_modules`, then it looks in global packages, then it checks a global cache, then if it's still not found, then it installs. You just showed it yourself; even the *first* run you did used the *existing* binary you have installed globally, it didn't ask you to install it first

Needing to have `libvips` isn't the issue here, that needs to be done at the system level and has nothing to do with installing sharp-cli. having the underlying native binaries for node still have to be handled, no matter how dependencies are linked.

**Comment by SampsonCrowley** [comment]
> what node version are you using? what is the result for `time sharp-cli`?

![Screenshot from 2021-02-24 14-25-12](https://user-images.githubusercontent.com/22461638/109067745-2a3c9d00-76ac-11eb-9eb7-e329c56d59ca.png)

**Comment by brentvatne** [comment]
@SampsonCrowley - right, it sounds like prebuilt binaries are available for your machine. they're often not, like in my case.

**Comment by SampsonCrowley** [comment]
@brentvatne  you still had to build and install them for your system though, correct?

whether `sharp-cli` is linked here, or installed as a global npm module you have to have the native `libvps` on your system either way. if a user did `npm install -g sharp-cli` it would need the same binaries that the package installed through `npx` would need.

**Comment by SampsonCrowley** [comment]
and again, if it's *already* installed through `npm i -g sharp-cli`, `npx` is *not* going to install it again

**Comment by SampsonCrowley** [comment]
this issue isn't about how to add `libvps` to your computer, that will have to be done by the user regardless

**Comment by SampsonCrowley** [comment]
![Screenshot from 2021-02-24 14-38-46](https://user-images.githubusercontent.com/22461638/109069123-067a5680-76ae-11eb-8d0c-5ba452ea5fad.png)

Here's a screen shot proving `npx` will always use the existing package if already installed

**Comment by brentvatne** [comment]
> and again, if it's _already_ installed through `npm i -g sharp-cli`, `npx` is _not_ going to install it again

it does:

```
╭─~/code/eas-example ‹master›
╰─$ which sharp                                                                                                                                                                                                                                           1 ↵
/Users/brentvatne/.nvm/versions/node/v14.15.2/bin/sharp
╭─~/code/eas-example ‹master›
╰─$ time npx sharp-cli
info sharp Using cached /Users/brentvatne/.npm/_libvips/libvips-8.9.0-darwin-x64.tar.gz
ld: warning: directory not found for option '-L/usr/local/opt/ruby/lib'
ld: warning: dylib (../vendor/lib/libvips-cpp.42.dylib) was built for newer macOS version (10.13) than being linked (10.7)
ld: warning: dylib (../vendor/lib/libvips.42.dylib) was built for newer macOS version (10.13) than being linked (10.7)
ld: warning: dylib (../vendor/lib/libglib-2.0.0.dylib) was built for newer macOS version (10.13) than being linked (10.7)
ld: warning: dylib (../vendor/lib/libgobject-2.0.0.dylib) was built for newer macOS version (10.13) than being linked (10.7)
Missing required arguments: input, output

Specify --help for available options
npx sharp-cli  18.94s user 4.93s system 81% cpu 29.281 total
```

<hr />

an alternative here, if you like, is to fork expo-optimize and include sharp-cli as a dependency. it's all open source and mit licensed so you can do whatever you need with it..

from my point of view there are problems with including sharp as a dependency of expo-optimize. i appreciate you taking the time to talk through this, if you want to start a dedicated discussion about it (https://github.com/expo/expo-cli/discussions) and alternatives to the current approach, that could be a good way to proceed.

**Comment by SampsonCrowley** [comment]
> > and again, if it's _already_ installed through `npm i -g sharp-cli`, `npx` is _not_ going to install it again
> 
> it does, in some cases apparently:
> 
> ```
> ╭─~/code/eas-example ‹master›
> ╰─$ which sharp                                                                                                                                                                                                                                           1 ↵
> /Users/brentvatne/.nvm/versions/node/v14.15.2/bin/sharp
> ╭─~/code/eas-example ‹master›
> ╰─$ time npx sharp-cli
> info sharp Using cached /Users/brentvatne/.npm/_libvips/libvips-8.9.0-darwin-x64.tar.gz
> ld: warning: directory not found for option '-L/usr/local/opt/ruby/lib'
> ld: warning: dylib (../vendor/lib/libvips-cpp.42.dylib) was built for newer macOS version (10.13) than being linked (10.7)
> ld: warning: dylib (../vendor/lib/libvips.42.dylib) was built for newer macOS version (10.13) than being linked (10.7)
> ld: warning: dylib (../vendor/lib/libglib-2.0.0.dylib) was built for newer macOS version (10.13) than being linked (10.7)
> ld: warning: dylib (../vendor/lib/libgobject-2.0.0.dylib) was built for newer macOS version (10.13) than being linked (10.7)
> Missing required arguments: input, output
> 
> Specify --help for available options
> npx sharp-cli  18.94s user 4.93s system 81% cpu 29.281 total
> ```

I don't see it being reinstalled anywhere, only an error that you're not passing any options to the command.

notice how in my screenshot it has a message:
```bash
[sampson@development client]$ time npx sharp-cli --version
Need to install the following packages:
  sharp-cli
Ok to proceed? (y) y
1.14.1
```

yours did not install anything.

**Comment by SampsonCrowley** [comment]
>an alternative here, if you like, is to fork expo-optimize and include sharp-cli as a dependency. it's all open source and mit licensed so you can do whatever you need with it..

If there is no way to include the package as a `"*"` dependency in the optimize package that won't break things for uses with custom binaries, then there should at least be a **link** in the error message about *why* it's not just listed as a dependency

**Comment by qiqiliang1996** [comment]
> Hi @bayoremit! Thanks for bringing this up and doing some research about this ❤️ Just to double check, did you add `expo-optimize` and `sharp-cli` as dependency to your `package.json`? If so, could you try if this works when installing `sharp-cli` globally? I created a PR in the meantime, let's get this fixed! 😄

**Thank you!! I added sharp-cli & expo-optimize as my dependency on package.json, and it worked** 
simply run **npm i sharp-cli** & **npm i expo-optimize** and my problem get fixed
