### ISSUE TITLE
Renaming App.js to App.jsx fails when running `expo start`

### ISSUE THREAD

**Issue by Glutnix** [expo/expo-cli#191]
## Description
* `expo start` does not resolve `import App from '../../App'` to `App.jsx`
* When using `expo start`, the root file set in `package.json`'s `main` property is ignored. It seems hard coded to `node_modules/expo/AppEntry.js`

## Expected Behavior

```
expo init jsx-file-test -t blank
cd jsx-file-test
mv App.js App.jsx
expo start
```
and then try visit the app on a device or simulator in order to trigger the JavaScript bundler to build.

Renaming `App.js` to `App.jsx` in order to meet our team coding standards, as files that contain JSX should be named `*.jsx` (specifically eslint, and `"rules": { "react/jsx-filename-extension": [1, {"extensions": [".js", ".jsx"] }]}`)

I expected that it would just work as normal when running `expo start`

## Observed Behavior

At first I got 

```
Unable to resolve "../../App" from "node_modules/expo/AppEntry.js"
```

when running `expo start`. The builder also got stuck at 0%.

## Attempted work around

I tried following the docs.expo.io instructions [What if I want to name my main app file something other than App.js?](https://docs.expo.io/versions/v31.0.0/sdk/register-root-component#what-if-i-want-to-name-my), but creating a main.js as described there, and pointing the `package.json` main property at that main.js file did not change the observed behaviour.

## Environment

```
  Expo CLI 2.4.0 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.2.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.2 => 31.0.2
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 2.4.0

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/glutnix-b2d01851-bc4d-41b0-af66-ed9604386626.tar.gz
```

## Reproducible Demo

Not hard to reproduce if you follow the basic steps above.

**Comment by jhullse** [comment]
@Glutnix I found something that worked for me at https://stackoverflow.com/questions/50311473/how-to-allow-react-native-to-enable-support-for-jsx-extension-files. I created a file `metro.config.js` at project's root with the following content:

```
module.exports = {
  resolver: {
    sourceExts: [
      'jsx',
      'js',
      'json',
      'ts',
      'tsx'
    ],
  }
};
```

I hope that helps.

**Comment by ilahishaikh** [comment]
hello guys, i m getting bellow error .

Unable to resolve "../../App" from "node_modules\expo\AppEntry.js"
Failed building JavaScript bundle.

**Comment by Asday** [comment]
@jhullse that no longer works with `expo-cli` `3.x`.

**Comment by jhullse** [comment]
Thank you @Asday. I edited my response based on your comment.

**Comment by DavidSvetlik** [comment]
@jhullse @Asday 

Found quick workaround for 3.x. In app.json, in part `packagerOpts`, just add `sourceExts` like this:

```
{
  "expo": {
    ...
    "packagerOpts": {
      "sourceExts": [ "js", "json", "ts", "tsx", "jsx" ], 
      "config": "metro.config.js"
    }
  }
}
```

And for clarity comment out that `sourceExts` in metro config.

**Comment by Asday** [comment]
Breaking changes are the whole reason for major version numbers, which is fine.

Sure wish they were documented though.

Thanks for coming in so hot and fast with a solution @DavidSvetlik, you're a certified beast.  I ended up not needing to upgrade to `expo-cli` `3.x`, so it's not _currently_ useful to me, but I'm still in love with you.  :heart:

**Comment by jrrcdev** [comment]
Fix:

Create the metro.config.js with:

```
module.exports = {
  resolver: {
    sourceExts: ["js", "json", "ts", "tsx", "jsx"]
  }
};
```
Put this in app.json:

```
{
  "expo": {
    ...
    "packagerOpts": {
      "config": "metro.config.js"
    }
  }
}
```

**Comment by zarzarbin** [comment]
Hi guys,

I tried the solution above but unfortunately it doesn't seem to work for me.

here is may app.json

`{
  "expo": {
    "name": "test",
    "slug": "test",
    "privacy": "public",
    "sdkVersion": "35.0.0",
    "platforms": [
      "ios",
      "android",
      "web"
    ],
    "packagerOpts": {
      "sourceExts": [ "js", "json", "ts", "tsx", "jsx" ], 
    },
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    }
  }
}

I'm using expo-cli 3.9.0

I've spent 3 days looking for a solution and trying a lot of things like install/uninstall/reinstall, trying on different devices and computers...etc

Nothing seems to work !

`latest config i use:
node 13.2.0
expo-cli 3.9.0
react-native-cli: 2.0.1
react-native: 0.59.8

Any help will be appreciate.

**Comment by brentvatne** [comment]
i just tried this on a brand new app and it worked as expected

app.json
```json
{
  "expo": {
    "name": "lol",
    "slug": "lol",
    "privacy": "public",
    "sdkVersion": "35.0.0",
    "platforms": [
      "ios",
      "android",
      "web"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "packagerOpts": {
      "sourceExts": [ "js", "json", "ts", "tsx", "jsx" ],
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    }
  }
}
```


App.jsx
```js
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <Text>hello there</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```
