### ISSUE TITLE
Some valid file paths show "File does not exist." during exp build:ios

### ISSUE THREAD

**Issue by tensiondriven** [expo/expo-cli#192]
1) make a new project with `exp init`
2) build for ios with `exp build:ios`
3) On "? Do you already have a distribution certificate you'd like us to use...", enter a longish file path like the one below:

```
? Do you already have a distribution certificate you'd like us to use,
or do you want us to manage your certificates for you? false
? Path to P12 file: /Users/j/Documents/SomePath-mobile-app/Expo/DistributionCertificate.p12
File does not exist.
```

Actual: That didn't work, so copy it to the desktop and give it a dumber name:
```
? Path to P12 file: /Users/j/Desktop/p.p12
? Certificate P12 password:
```
That worked. 

Expected: The longer valid file path should work.

**Comment by fson** [comment]
Fixed in 400b7486da7f04c4b3d9050df96d59a18a530582.
