### ISSUE TITLE
feat(expo-cli): add the ability to "extend" app.json

### ISSUE THREAD

**Issue by kaminskypavel** [expo/expo-cli#1924]
# What?

similar to how we extend tsconfig.json in typescript, it would be great if we can
create multiple config files without duplicating most of the entries.

# Why?

suppose you want to release different apps (apk/ipa) for `dev` and `prod`,
with different app-icons so it would be distinguishable on the launcher,

# Alternative
expo-cli might want to support a custom app.json entry from the command line

**Comment by byCedric** [comment]
Hi @kaminskypavel! We are working on an additional method for the app manifest, I think this should be possible with that. Once it out we will write about it! For now, I would say try the `--config` flag 😄 This should work on `expo start`, `expo publish` and `expo build:ios|android`

**Comment by kaminskypavel** [comment]
thanks @byCedric thats great to hear the team is working on it! let me know if I can help.

`--config [path] | Specify a path to app.json.`

using --config will still imply managing two copies of app.json with minor changes between them,
that's exactly where we could use "extends"

**Comment by EvanBacon** [comment]
You can currently use the `app.config.js`, we just haven't documented it yet. 

```js
export default {
  "name": "my-app"
}
```

**Comment by kaminskypavel** [comment]
thanks @EvanBacon , I wasn't aware app.config.js feature is coming.. will it be release with SDK 38?

**Comment by byCedric** [comment]
You should be able to use it already 😄
