### ISSUE TITLE
Cant authenticate apple developer account with expo

### ISSUE THREAD

**Issue by simdanonline** [expo/expo-cli#1927]
While running expo build:ios
After entering Apple ID verification Code, I still get Authentication with Apple Developer Portal Failed.
Reason: unknown reason, raw: 'unathorized Access'
Set expo_debug = true in env file to view stack trace

**Comment by brentvatne** [comment]
perhaps related https://github.com/fastlane/fastlane/issues/16108

**Comment by quinlanj** [comment]
looks like a duplicate of https://github.com/expo/expo-cli/issues/1631 . Closing this issue so we can track any updates in the original issue
