### ISSUE TITLE
typescript and jest

### ISSUE THREAD

**Issue by diegolaciar** [expo/expo-cli#193]
Hi,

Can someone provide an example how to config jest and typescript ?

Thanks

**Comment by fson** [comment]
I think you'll get an answer to this question faster, if you post it to our forums at https://forums.expo.io/c/help. Try to be as specific as possible and provide any relevant context in your question. Thanks!

**Comment by diegolaciar** [comment]
Ok,  I posted the question here in case someone can help with this question

https://forums.expo.io/t/config-an-expo-project-with-typescript-and-jest/16522

Thanks
