### ISSUE TITLE
development mode as "Production" when running expo start for ANDROID

### ISSUE THREAD

**Issue by zhuxh529** [expo/expo-cli#1932]
I run expo start locally and I open expo client on both my Apple and Android phone. When it's Apple, the process.env.NODE_ENV is development but when it's Android phone, the NODE_ENV is production! Btw mode in web Expo Dev Tools is NOT production mode.
last week it was working as expected on both IOS and Android(NODE_ENV is development).
I am wondering it's expo client issue or server issue~

**Comment by brentvatne** [comment]
what is the value of `__DEV__` on android? close and reopen the client maybe? make sure you're opening the project that you expect?

i'm closing this issue because it didn't follow the issue template, hope that advice helped.
