### ISSUE TITLE
Ensuring auto SSL certificate is created (you might need to re-run with sudo)

### ISSUE THREAD

**Issue by PaulB2Code** [expo/expo-cli#1935]
### Please note that Expo CLI issues opened in the core Expo repository will be closed.

We change version of expo and we get this issue 
Is it normal ?

expo --version
3.18.5

We have an issue when we use expo for web . 

They ask us a password. 

[20:25:01] Your native app is running at exp://192.XX.1.XX:19000
[0] Logs for your project will appear below. Press Ctrl+C to exit.
[0] Ensuring auto SSL certificate is created (you might need to re-run with sudo)
Password:

And on chrome we have

Your connection is not private
Attackers might be trying to steal your information from localhost (for example, passwords, messages or credit cards). Learn more
NET::ERR_CERT_INVALID

**Comment by actuallymentor** [comment]
> Error creating SSL certificates: Error: EACCES: permission denied, mkdir '/Users/XX/Library/Application Support/devcert/domains/localhost'

I'm encountering this error as well. I see the issue is closed but how does one fix this?

**Comment by wallynm** [comment]
I'm having the same issue, didn't find a way to handle this without sudo, anyway to start without https at localhost?

**Comment by wallynm** [comment]
I'm also having a issue where web only works with sudo,
and ios build only works without sudo 🤔

**Comment by actuallymentor** [comment]
> starting web with sudo works

For me this fails as well.

I ended up allowing insecure SSL through `chrome://flags/#allow-insecure-localhost`.
