### ISSUE TITLE
error when publish app to itunes "ERROR ITMS-90596: "Invalid Bundle. The asset catalog at 'Payload/ExpoKitApp.app/Assets.car'"

### ISSUE THREAD

**Issue by foxdreamstudio** [expo/expo-cli#195]
hi , I have a problem when uploading my apps to iTunes using application loader, the error is look like this 

ERROR ITMS-90596: "Invalid Bundle. The asset catalog at 'Payload/ExpoKitApp.app/Assets.car' can't be processed. Rebuild your app, and all included extensions and frameworks, with the latest GM version of Xcode and resubmit.”

I’m build the apps  using expo build:os, the build process is ok, bet the error show when i publish the apps on itunes using application loader, can anyone help?

    "expo": "^29.0.0",
    "react": "16.3.1",
    "react-native": "~0.55.2",

![image](https://user-images.githubusercontent.com/37882679/48931697-58a9fb80-ef2a-11e8-8aa0-0ba03428a90e.png)

**Comment by Mark-Jung** [comment]
I also have this problem. Any updates?

**Comment by foxdreamstudio** [comment]
> I also have this problem. Any updates?

yes i have update the expo version and the react-native version on app.json,  and then im updated the application loader to the newest version, and its fix the problem. maybe you can try it.

**Comment by BrodaNoel** [comment]
Me too, I'm having the same issue with Expo 31

**Comment by Mark-Jung** [comment]
I followed what @foxdreamstudio commented and just updated expo and all of the related software(xcode, application loader) and it started working. Have you given that a shot?

**Comment by BrodaNoel** [comment]
@Mark-Jung I'm not using Movaje OS (the latest version), so, I won't have the latest xCode version.
That should be the problem.

I'll try to move from High Sierra to Movaje.

I have the latest Xcode available on High Sierra, so, the Latest Applicacion Loaded (I re-updated it today), I already have the latest Expo version (31) and I rebuild the App

**Comment by Mark-Jung** [comment]
Your English is fine @foxdreamstudio. I fixed my error so I'm a happy man :)

**Comment by exaland** [comment]
Same problem with 
`"expo": "25.0.0"`,
`"react": "16.2.0"`,

and Xcode 9.4.1

**Comment by amsimoes** [comment]
Having the same problem with Expo SDK 30 and MacOS Sierra (XCode 9.2 therefore...).

@brentvatne Care to give a stable solution? Are we forced to update to Mojave (XCode 10) in order to build and deploy an app with Expo?

**Comment by esamelson** [comment]
@amsimoes you can get Xcode 10 without upgrading to Mojave.

**Comment by codemt** [comment]
facing the same issue , any updates on this. i am updating to Xcode 10 now using High Sierra? Do i need to upgrade to Mojave as well?

**Comment by Mark-Jung** [comment]
@codemt Yes, or at least that's how I solved it.

**Comment by codemt** [comment]
@Mark-Jung  What if you use react native init , without expo , i think that will help us use whatever SDK versions we want right and we can still do it. i was first time experimenting with expo , as u can quickly build something. but with deployment u need all latest tools i guess.

**Comment by thebergamo** [comment]
You can try to use instead of Application Loader from previous version of XCode you can try fastlane to send it to app store. (https://docs.fastlane.tools/getting-started/ios/appstore-deployment/)

**Comment by foxdreamstudio** [comment]
@codemt ,  i have solved it, actually the problem just the xcode version. i 'v upgraded xcode to version 10. after that, everyting working percfectly well.
this the list technology i used:
1. expo sdk 29.0.0
2. react-native v 0.55.2
3. excode v. 10
4. mac osx high sierra

actually the problem just happen on xcode version, couse xcode v 10 has the latest version of app loader.  i hope its work for you.

ps: 'expo sdk version 31.0.0 is Dropping support for iOS 9 and Android 4.4, you can check on this blog " https://blog.expo.io/expo-sdk-v31-0-0-is-now-available-cad6d0463f49" ',

**Comment by foxdreamstudio** [comment]
@codemt , i have solved it, actually the problem just the xcode version. i 'v upgraded xcode to version 10. after that, everyting working percfectly well.
this the list technology i used:

    expo sdk 29.0.0
    react-native v 0.55.2
    excode v. 10
    mac osx high sierra

actually the problem just happen on xcode version, couse xcode v 10 has the latest version of app loader. i hope its work for you.

ps: 'expo sdk version 31.0.0 is Dropping support for iOS 9 and Android 4.4, you can check on this blog " https://blog.expo.io/expo-sdk-v31-0-0-is-now-available-cad6d0463f49" ',
