### ISSUE TITLE
allow passing host ip to start command running on docker container

### ISSUE THREAD

**Issue by zanona** [expo/expo-cli#1951]
I am currently running my dev environment from a docker container and would like to be able to run `expo start`  but passing the host IP address so the QR code generated for previewing the app works accordingly.

At the moment it uses the container IP address which is not available publicly.

Perhaps something like `expo start --host ${HOST_IP}`

**Comment by yannissgarra** [comment]
It would be a great feature !

**Comment by zanona** [comment]
I have actually found a way to achieve this on docker by setting the `--network host` flag which exposes the same IP and ports as the host and make all work seamlessly. But I'm not sure if there would be any use cases besides docker itself?

**Comment by yannissgarra** [comment]
Well, I don’t know if it’s a good idea... and it doesn’t work on MacOS... 😢

**Comment by zanona** [comment]
Well spotted! that's true. In this case, allowing the setup of the host manually from the expo start call would be quite handy.

**Comment by fson** [comment]
You should be able to use the `EXPO_PACKAGER_HOSTNAME` environment variable for this.
