### ISSUE TITLE
google app signin not working as documented

### ISSUE THREAD

**Issue by hariomshah** [expo/expo-cli#1952]
### Please note that Expo CLI issues opened in the core Expo repository will be closed.
Greetings,

I have already published an app on the play store. however, in order to reduce the app size, I want to re-publish using the android app bundle. 

As per the document when I follow the first step **_expo opt-in-google-play-signing_** and providing the google play encryption key, I'm getting the 

> Error: keytool exited with non-zero code: 3221225781

Operating System: Windows 10
Node: v10.13.0
Expo: 3.17.11

Kindly provide some solution.
![Capture](https://user-images.githubusercontent.com/24752085/79969886-ba6bed80-84af-11ea-83ae-0f2688349c2b.PNG)

**Comment by brentvatne** [comment]
It looks like this requires keytool to be installed and in path

**Comment by wkozyra95** [comment]
I couldn't reproduce that error, but base on quick google search it seems to be linking error
```3221225781 = 0xC0000135 STATUS_DLL_NOT_FOUND```
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55

make sure you can run keytool commands from your terminal e.g.
```keytool -genkey -v -keystore my-release-key.keystore -alias alias_name -keyalg RSA -keysize 2048 -validity 10000```

**Comment by fson** [comment]
The `opt-in-google-play-signing` command has been removed from Expo CLI (https://github.com/expo/expo-cli/pull/2247).  To opt in for Android app signing, please use the steps detailed on https://docs.expo.io/distribution/app-signing/#android instead. 🙏
