### ISSUE TITLE
CLI not creating provisioning profile

### ISSUE THREAD

**Issue by mrtom** [expo/expo-cli#1954]
## Description

I can't get expo to generate a new provisioning profile. 

When I run `expo credentials:manager -p ios` I see the following output:

```
Application credentials

  Experience: @temelliott/letsdothisapp, bundle identifier: com.letsdothis.alpha.app
    Provisioning profile is missing. It will be generated during the next build
```

Similarly if I select `Remove provisioning profile` I get the following:

```
? What do you want to do? Remove Provisioning Profile
There are no Provisioning Profiles available in your account
```

So it appears I do not have a Provisioning Profile on Expos servers.

Whenever I run:

```
expo build:ios
```

or 
```
expo build:ios --clear-provisioning-profile
```

I see the following, which also suggests there is no provisioning profile:

```
(base) tom$ expo build:ios --clear-provisioning-profile --apple-id <me@foo.com>
? Choose the build type you would like: archive
Checking if there is a build in progress...

Authenticating to Apple Developer Portal...
Authenticated with Apple Developer Portal successfully!
Only 1 team associated with your account, using Apple Team with ID: XXXXX
Fetching available credentials
✔ App ID found on Apple Developer Portal.
Failed to prepare all credentials.
The next time you build, we will automatically use the following configuration:

Project Credential Configuration:
  Experience: @temelliott/letsdothisapp, bundle identifier: com.letsdothis.alpha.app
    Provisioning profile is missing. It will be generated during the next build
```

According to the docs, and the line above, the way to get Expo to create a new provisioning profile is just to have one missing and it will be created, i.e. from [https://docs.expo.io/versions/latest/distribution/app-signing/](here): You will just need to create a new one the next time you build your app by running expo build:ios --clear-provisioning-profile

But no matter how many times I run the build command I can't get it to create one for me.

Because of this, my builds won't complete.

## Expected Behavior

A provisioning profile is created for me and my builds to succeed.

## Observed Behavior

Broken builds, i.e. [this one](https://expo.io/dashboard/temelliott/builds/69356546-8883-4760-81d4-774785230636).

No errors sadly

## Environment

```
tom$ expo diagnostics

  Expo CLI 3.18.6 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.7
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
```

Also specify:

- Phone/emulator/simulator platform, model and version:

N/A

## Reproducible Demo
I'm not sure that's possible here but please let me know if you disagree.

Many thanks!

**Comment by mrtom** [comment]
The other thing that's weird is I have both a personal Expo account (`@temelliott`) and a company one (`@letsdothis`) and they both exhibit the same problem.

I tried creating my own shell account earlier (`expo client:ios`) and that worked perfectly, creating all the necessary profiles and certificates.

**Comment by mrtom** [comment]
OK, I think I've figured this out. I had set the `EXPO_IOS_DIST_P12_PASSWORD` environment variable incorrectly.

Assuming that was the root cause, it would have been nice for the command line to print out that it was failing to use the certificate rather than making it look like a provisioning profile issue - any chance that's possible? Thanks :)

**Comment by quinlanj** [comment]
hi @mrtom - are you using the expo teams feature, where your company account is the one that owns the app and your personal account has admin/developer access? If so, there is currently a credentials-related problem where you aren't able to properly configure credentials from the personal account for the company's app. We've released the newest patch version in the `cli` with client side fixes (expo-cli@3.19.2) and the server side fixes are slated to be deployed in the next day or so.

**Comment by marceliwac** [comment]
I think it's worth mentioning that this can also occur in both local and CI environments if the `--skip-credentials-check` is being used but the provisioning profile does not exist for the updated/new certificate.

Running the `expo build:ios` locally fixed the issue for me, creating both provisioning profile and the push key (latter of which I could not skip, even though it's not being used).

**Comment by yasirwahid** [comment]
✔ Will you provide your own Apple Distribution Certificate? › Let Expo handle the process
✔ Created Apple distribution certificate
Failed to set up Distribution Certificate
Failed to prepare all credentials. 
The next time you build, we will automatically use the following configuration:
No credentials configured for app @yasirwahid/noah with bundle identifier com.noahark.myappaboutnoah

Request failed with status code 504
Error: Request failed with status code 504
    at createError (/opt/homebrew/lib/node_modules/expo-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/homebrew/lib/node_modules/expo-cli/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/homebrew/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (node:events:391:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)


@quinlanj  i am getting this above error for past two days now. im an admin of developers account and expo account is on my name as well . credentials are fine its creating distribution certificate then crash just after that. not creating keys and profiles. 
I am using expo cli --version 4.1.6 .
and expo sdk 40.0.1 .

Please help. Thanks
