### ISSUE TITLE
Current Node (14.x.y) is not supported

### ISSUE THREAD

**Issue by SleeplessByte** [expo/expo-cli#1955]
## Description

Node JS 14.0.0 was released yesterday. I did not expect it to work with `expo-cli` yet, but the messaging is outdated.

## Expected Behavior

Current Node should work, or the messaging should change. Or the messaging should be "version is _not yet_ supported".

## Observed Behavior

```text
ERROR: Node.js version 14.0.0 is no longer supported.

expo-cli supports following Node.js versions:
* >=10.13.0 <11.0.0 (Active LTS)
* >=12.0.0 <13.0.0 (Active LTS)
* >=13.0.0 <14.0.0 (Current Release)
```

## Offending source code

https://github.com/expo/expo-cli/blob/a6ad3fd617e9ddcf42f45d57575e8cee198e6926/packages/expo-cli/bin/expo.js#L7-L10

Perhaps add:

```javascript
var maxVersion = supportedVersions[supportedVersion.length - 1].range
if (semver.gt(version, maxVersion)) {
  // not YET supported
}

**Comment by brentvatne** [comment]
can you open a PR to fix this message?

**Comment by SleeplessByte** [comment]
@brentvatne attempted to do it from a mobile view as desktop browser 😄
