### ISSUE TITLE
The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by aliraouf20390** [expo/expo-cli#1969]
## Description

I have upgraded my app from expo SDK 34 to 37, it is upgraded successfully now I need to eject my app to react native cli but on expo-cli latest version 3.18.6 I am facing this issue 
The "path" argument must be of type string. Received type undefined
I run command expo eject
it creates the iOS/android directories also setup the index.js file, but while configuring iOS setting it stopes on this error

## Expected Behavior

application should be ejected to react native cli

## Observed Behavior

seems like error due to the expo-cli 

```
The "path" argument must be of type string. Received type undefined
```

## Environment

Expo CLI 3.18.6 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.6 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-navigation: ^3.11.1 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 3.18.6

Also specify:

- iPhone 7plus

## Reproducible Demo

simply open the terminal in project root directory and run expo eject

**Comment by aliraouf20390** [comment]
**⠋ Applying iOS configurationThe "path" argument must be of type string. Received type undefined**

any solution to get successfully ejected from expo to native-cli

**Comment by brentvatne** [comment]
this was an intermittent issue with eject that has since been resolved

**Comment by davemurphysf** [comment]
Just had this crop up for me and I can't eject the project

```
 expo diagnostics

  Expo CLI 3.27.10 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.7 - ~/.nvm/versions/node/v12.18.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.1
        System Images: android-29 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.16 => 0.12.32 
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.2 => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.13 
    npmGlobalPackages:
      expo-cli: 3.27.10
    Expo Workflow: bare
```

**Comment by nicholasdavidlister** [comment]
Same for me
```
expo diagnostics

  Expo CLI 3.27.10 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.18.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react-native: ~0.63.2 => 0.63.2 
    npmGlobalPackages:
      expo-cli: 3.27.10
    Expo Workflow: bare
```

**Comment by brentvatne** [comment]
guys, don't comment on old closed issues. what you are facing may have the same error message but it's different. please open a new issue and provide more information on how we can reproduce it, thank you!
