### ISSUE TITLE
`Error starting tunnel: XDLError: Parse Error`

### ISSUE THREAD

**Issue by danjocha** [expo/expo-cli#197]
When I start a project I get the following message: 

> Error starting tunnel: XDLError: Parse Error

Then when I try to get the tunnel URL I get the following message: 

> Switched to a LAN URL because the tunnel appears to be down. Only devices in the same network can access the app. You can restart the project to try reconnecting.

Any ideas?

**Comment by fson** [comment]
Looks like this should be fixed in ngrok by now, so I'm closing this issue.
