### ISSUE TITLE
Request failed with status code 404 the first time I refresh after building app bundle 

### ISSUE THREAD

**Issue by griffink3** [expo/expo-cli#1972]
## Description

When I started the app on the iOS simulator it was working fine but then the first time I refreshed, I got the request failed with status code 404 error and the app won't show. I can't get rid of the error even by restarting (expo start). I also tried reinstalling the latest expo app on the simulator which didn't work.

## Expected Behavior

I expected the app to show up again after I refreshed.

## Observed Behavior

After I refreshed I got the request failed error in terminal and the iOS simulator just showed a blank loading screen.

If there's an error message, please paste the _full terminal output and error message_ in this code block:

```
Request failed with status code 404
- node_modules/axios/lib/core/createError.js:15:17 in createError
- node_modules/axios/lib/core/settle.js:16:9 in settle
- node_modules/axios/lib/adapters/xhr.js:52:6 in handleLoad
- node_modules/event-target-shim/dist/event-target-shim.js:818:39 in EventTarget.prototype.dispatchEvent
- node_modules/react-native/Libraries/Network/XMLHttpRequest.js:566:23 in setReadyState
- node_modules/react-native/Libraries/Network/XMLHttpRequest.js:388:25 in __didCompleteResponse
- node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:190:12 in emit
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:436:47 in __callFunction
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:111:26 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:110:17 in __guard$argument_0
* [native code]:null in callFunctionReturnFlushedQueue
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.12.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.14.2 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ~16.9.0 => 16.9.19 
      @types/react-native: ~0.60.23 => 0.60.31 
      expo: 36.0.0 => 36.0.0 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-navigation: ^4.3.1 => 4.3.1 
    npmGlobalPackages:
      expo-cli: 3.18.0

Also specify:

- Phone/emulator/simulator platform, model and version: iPhone 11 Pro simulator 

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by jkhales** [comment]
Hi! Thanks for writing in. In order to address this bug we need a reproducible example. Would you be able to provide us with link to a github repo that illustrates this issue?

**Comment by EvanBacon** [comment]
Please feel free to reopen this issue with a reproducible example.
