### ISSUE TITLE
Link to docs for using https with Next.js 

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo-cli#1988]
We require HTTPS a lot for Expo web, seems like it's more involved to use with Next.js.

**Comment by nandorojo** [comment]
Next.js doesn't appear to have plans to support HTTPS (https://github.com/zeit/next.js/issues/2633#issuecomment-317602742).

I was able to get it up and running using a custom server file, so I'm happy to help with this.

**Comment by nandorojo** [comment]
This is how I got it working: https://www.notion.so/How-to-use-HTTPs-with-localhost-in-Expo-Next-js-8b5048bead124430b34f71ca30ddd655
