### ISSUE TITLE
Expo throwing error while running npm start after creating project using expo init.

### ISSUE THREAD

**Issue by rinkumalik11** [expo/expo-cli#1990]
` Couldn't start project on Android: Error running adb: adb: failed to install /home/spinny/.expo/android-apk-cache/Exponent-2.15.4.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl1528221011.tmp/base.apk using APK Signature Scheme v2: SHA-256 digest of contents did not verify]`

I am running ubuntu 18.04
Node 12.x
Npm 6.x

**Comment by brentvatne** [comment]
- do you have expo client installed on your device already?
- what version of android are you using?

**Comment by EvanBacon** [comment]
I cannot reproduce this issue. Please feel free to reopen with more info.

**Comment by dilipmaurya** [comment]
I'm also having the same issue, Please help. What more info do you need?

**Comment by needo2** [comment]
Please re-open this. I'm trying to run my application in an emulator and expo can't install Exponent-2.19.6.apk due to INSTALL_PARSE_FAILED_NO_CERTIFICATES

**Comment by brentvatne** [comment]
@needo2 - try clearing your apk cache, perhaps the download was interrupted or otherwise: `rm -rf ~/.expo/android-apk-cache/`

this can also happen if the minimum supported android version in the apk is greater than the android OS version on your device.

**Comment by davelozier** [comment]
@brentvatne Thanks for the tip. I had the same issue and it was resolved with deleting the android apk cache directory.
