### ISSUE TITLE
Can't open project in Expo Android App

### ISSUE THREAD

**Issue by muril0-0** [expo/expo-cli#1993]
Hi,
This is my second project with Expo and React Native.

The first project runs OK in app, but when I try to run the second project in app, it's try to open the first project URL/QRCode.

I'll try explain with more details:
PROJECT 1: 
I created a app with `expo-init` and ran with `yarn start --lan`;
I finished project and published in my Github;
Turned off my laptop;

PROJECT 2:
I created other repo and other project in my computer;
I initiated this new project with `expo-init` and ran with `yarn-start --lan`
But this time, when I try scan the new project QRCode in my app, the app returns the first project localhost and splash background-color and show me a error blue screen with a message 'Package is not running at http://192.168.0.110:19001', but this project is running in 19002 port.

**Comment by brentvatne** [comment]
@muril0-0 - if you follow those exact steps does that happen for you again?

**Comment by muril0-0** [comment]
@brentvatne Yes, I tried 3 times but is the same error, it try to open first project

**Comment by brentvatne** [comment]
what if you try to open your first project, does that work?

**Comment by muril0-0** [comment]
Well I will try, I should have done this before, my bad

**Comment by muril0-0** [comment]
![WhatsApp Image 2020-04-25 at 17 00 43](https://user-images.githubusercontent.com/51198449/80289666-7890b080-8716-11ea-9424-4cea43f2320a.jpeg)
![Screenshot_1](https://user-images.githubusercontent.com/51198449/80289667-79294700-8716-11ea-90c6-99fc32c29802.jpg)

The same error

**Comment by brentvatne** [comment]
try switching to tunnel connection

**Comment by muril0-0** [comment]
Wow it's works, I used --tunnel tag and now my project opened.
Thank you @brentvatne , really thank you.😄✌️

**Comment by brentvatne** [comment]
ok great! so i think what is happening is that your phone isn't on the same wifi network OR your wifi network has some config that is preventing devices from connecting with each other. so if you can resolve that issue you might want to switch back to lan because it is faster, but you can use tunnel for now.
