### ISSUE TITLE
expo-cli prints wrong error message for not yet supported nodejs versions

### ISSUE THREAD

**Issue by CodeWitchBella** [expo/expo-cli#1994]
## Description

There is code in expo-cli entrypoint which handles showing error message for unsupported nodejs versions.

## Expected Behavior

When using nodejs version newer than ones supported by expo cli it should show that it is not yet supported.

## Observed Behavior

It shows that node.js 14 is no longer supported.

```
ERROR: Node.js version 14.0.0 is no longer supported.

expo-cli supports following Node.js versions:
* >=10.13.0 <11.0.0 (Active LTS)
* >=12.0.0 <13.0.0 (Active LTS)
* >=13.0.0 <14.0.0 (Current Release)
```

## Environment

N/A - shows same error message

`node --version` shows `v14.0.0`

and this is on macos catalina with nodejs installed from brew. 

expo-cli was installed using yarn 1.22.4 and its version is 3.18.6

## Reproducible Demo

I unfortunately do not know how to easily make one. But following sequence of commands reproduces it inside docker container:

```
docker run -it --entrypoint /bin/sh node:14.0.0
yarn global add expo-cli
expo --help
```

## Additional information

`yarn global add expo-cli` shows following warning

```
warning expo-cli > @expo/xdl > @expo/webpack-config > react-dev-utils > fork-ts-checker-webpack-plugin > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
```

**Comment by brentvatne** [comment]
hi there! this has already been resolved on the latest version of expo-cli :) we noticed it with node 14 also. thanks for the report!

**Comment by florentroques** [comment]
@CodeWitchBella 

Until the latest version of expo-cli supporting node 14 is pushed, you can use version 12 of node quickly. Here's how to do it:

```bash
brew unlink node
brew install node@12
brew link --overwrite --force node@12
```

source: https://stackoverflow.com/a/61417592/1152843

**Comment by josmontes** [comment]
@brentvatne I just updated expo and it still shows the same error, I don't think this thread should be closed.

**Comment by brentvatne** [comment]
@josmontes - please elaborate on what error is shown to you and what node version you are using
