### ISSUE TITLE
Foreach error when attempting to publish with assets(No assets to upload, skipped.)

### ISSUE THREAD

**Issue by dhairya0907** [expo/expo-cli#1997]
## Description

Getting below error when attempting to run 'expo publish' using sdk version 37.

## Expected Behavior

App successfully publishes, with images, font and icon present in published version.

## Observed Behavior

What actually happened when you performed the above actions?

Asstes are not uploaded, and I am not able to see images, icon and font in published app on expo client. 

```
C:\EMPLOYED_INDIA>expo publish
Publishing to channel 'default'...
Building iOS bundle
Building Android bundle
Analyzing assets
Uploading assets
No assets to upload, skipped.
Processing asset bundle patterns:
- C:\EMPLOYED_INDIA\**\*
Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at _configureExpForAssets (C:\@expo\xdl@57.8.28\src\Project.ts:1165:26)
```

## Environment

  Expo CLI 3.18.6 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338
    npmPackages:
      expo: ~37.0.3 => 37.0.7
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-navigation: ^4.3.8 => 4.3.8

## My package.json is:

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "expo": "~37.0.3",
    "localstorage-polyfill": "^1.0.1",
    "native-base": "^2.13.12",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-hide-show-password-input": "^1.1.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.6.0",
    "react-native-web": "~0.11.7",
    "react-navigation": "^4.3.8",
    "react-navigation-stack": "^2.3.13"
  },
  "devDependencies": {
    "babel-preset-expo": "~8.1.0",
    "@babel/core": "^7.8.6"
  },
  "private": true
}

```
## My app.json is:

```
{
  "expo": {
    "name": "Employed India",
    "slug": "EMPLOYED_INDIA",
    "privacy": "unlisted",
    "sdkVersion": "37.0.0",
    "platforms": ["ios", "android", "web"],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": ["**/*"],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.employedindia.example"
    },
    "android": {
      "package": "com.employedindia.example"
    }
  }
}

```

I'm aware that this is related to the issue documented here [#753](https://github.com/expo/expo-cli/issues/753). But I tried all the solution there and they did not work for me.

**Comment by brentvatne** [comment]
could you possibly share your project privately with me on github @dhairya0907? it would be very helpful

**Comment by dhairya0907** [comment]
> could you possibly share your project privately with me on github @dhairya0907? it would be very helpful

Yes I can do that. I just sent you an invite to collaborate.

**Comment by brentvatne** [comment]
@dhairya0907 - looking at this now

**Comment by brentvatne** [comment]
this worked as expected for me. can you try running `expo start -c` and then `expo publish`? curious if it might be a cache issue

**Comment by dhairya0907** [comment]
> this worked as expected for me. can you try running `expo start -c` and then `expo publish`? curious if it might be a cache issue

Okay trying @brentvatne

**Comment by dhairya0907** [comment]
It worked.
Thank You @brentvatne

**Comment by brentvatne** [comment]
great, thanks for letting me know!
