### ISSUE TITLE
[nextjs] External URL is being blocked by CORS policy

### ISSUE THREAD

**Issue by 5ervant** [expo/expo-cli#2003]
Referring to [my `react-three-fiber` _"useLoader external URL is being blocked by CORS policy"_ issue](https://github.com/react-spring/react-three-fiber/issues/352#issue-606813669).

Is there a way to configure Next.js server's CORS policy?
If any, where's the guideline?

Because whenever I load external files on my `react-three-fiber` scene, I'm getting this console error:

> Access to XMLHttpRequest at 'https://github.com/zeit/next.js/blob/canary/examples/with-three-js/public/glb/stork.glb' from origin 'http://localhost:3001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Here's my _"server.js"_:

```
const { startServerAsync } = require('@expo/next-adapter');

startServerAsync(__dirname, {
  port: 3001,
});
```

**This is definitely important functionality for a Next.js application.**
I hope there's already a fix for this.

#### Reference
- [Any example how to use `react-three-fiber`'s `useLoader` on `react-native`?](https://spectrum.chat/react-three-fiber/general/any-example-how-to-use-useloader-on-react-native~5674fbe6-0cc3-406a-a39e-be16c755b2ec)

---

I already tried this _"server.js"_ code:

```
const { createServerAsync } = require('@expo/next-adapter');
const Cors = require('cors');

const projectRoot = __dirname;

createServerAsync(projectRoot, Cors()).then(({ server, app }) => {
  const port = 3000;

  server.listen(port, () => {
    console.log(`> Ready on http://localhost:${port}`);
  });
});
```

But getting this terminal error:

```
C:\Users\USER\Documents\PROJECTS\PLATFORM\APP_NAME\node_modules\cors\lib\index.js:219
            originCallback(req.headers.origin, function (err2, origin) {
                               ^

TypeError: Cannot read property 'headers' of undefined
```

**Comment by 5ervant** [comment]
@EvanBacon **May I know if there's an example how to load a .glb file with `expo-three`?**

**Comment by EvanBacon** [comment]
In React Native you can load different asset types like this https://github.com/expo/expo-three#expothreeloadasync
I'm unsure how to do the same in Next.js.

**Comment by 5ervant** [comment]
**BUG:** By the way, `app: (App) => App` is throwing an `UnhandledPromiseRejectionWarning: TypeError: app.getRequestHandler is not a function`.

```
const { createServerAsync } = require('@expo/next-adapter');
const cors = require('cors');

createServerAsync((projectRoot = __dirname), {
  // UnhandledPromiseRejectionWarning: TypeError: app.getRequestHandler is not a function
  app: (App) => {
    App.use(cors()); // To enable all CORS requests
    return App;
  },
}).then(({ server, app }) => {
  // ...
});
```

---

I'll end up and try using `react-native-webview` to support multi-platform Three.js graphics.
