### ISSUE TITLE
Suggest the closest match to an unknown command

### ISSUE THREAD

**Issue by jamesgeorge007** [expo/expo-cli#2005]
## Feature Request

Recommend matching commands if the user made a typo. Say, `expo inti` which would result in an appropriate suggestion showing up: `Did you mean init?`

**Comment by jamesgeorge007** [comment]
I would be happy to work on a PR :+1:

**Comment by brentvatne** [comment]
hey! i have an issue for this already: https://github.com/expo/expo-cli/issues/1926

if you want to work on it that'd be awesome! pr is welcome
