### ISSUE TITLE
Keyboard Shortcuts in web-based Dev Tools

### ISSUE THREAD

**Issue by ccheever** [expo/expo-cli#2008]
## Description

There are a number of improvements that should be made related to keyboard shortcuts in the web-based dev tools.

- At a high level, it's desirable that the same shortcuts work in the command line version of expo-cli and the web-based tools. This way, users only have to learn them once and remember one thing.
- The keyboard shortcuts need to be documented. There appears to be one keyboard shortcut for the dev tools right now (`Ctrl+l` to clear logs) but I can't find anywhere that this is documented. This should probably be documented in the tool itself, and/or possibly in our docs pages.
- On non-Mac platforms (i.e. Windows and Linux), `Ctrl+l` will focus the location bar in the browser and so it doesn't work as a keyboard shortcut. We should use a different shortcut -- either something else across all platforms; or a different modifier key + `l` on non-Mac platforms.
- We should add as many of the terminal based shortcuts as make sense in the web based interface as possible.
    - When doing this, we should make sure that the keyboard shortcuts as disabled as necessary in contexts when a textbox is focused or there is some other need to type things. For example, when you send a link, you type in an e-mail address there and while you're typing that, you don't want to trigger any of these shortcuts.
- There should be some kind of easily findable help dialog that shows you all the keyboard shortcut, and possibly lets you filter by typing something like "web" to see the shortcuts where the description matches "web".

**Comment by ccheever** [comment]
In [`TerminalUI.ts` in `handleKeypress`](https://github.com/expo/expo-cli/blob/48d67f8b5ef225c127dd0c6400d92627a707e4ad/packages/expo-cli/src/commands/start/TerminalUI.ts#L143), the keyboard shortcuts for the terminal CLI are implemented.

The list isn't that long
- `Ctrl+c` & `Ctrl+d` - quit
- `Ctrl+L` - clear console
- `w` - Open web project in your browser
- `?` - Help, print usage instructions
- `c` - clear console and print server info
- `d` - Open dev tools in the browser
- `a` - Try to open project on Android emulator; or if in web only mode, try to open web project in Chrome on Android, if web-only project
- `i` - Try to open project in iOS simulator. Or, if in web only mode, try to open web project in Mobile Safari on iOS simulator
- `e` - Send URL for project to an e-mail address
- `D` (`Shift+d`) - Toggle saved setting for opening dev tools at startup
- `p` - Toggle production mode / dev mode
- `r` - restart Metro bundler
- `R` (`Shift+r`) - restart Metro bundler and clear Metro bundler cache
- `s` - Sign out or sign in
- `o` - Open project in your editor of choice

All those pretty much make sense except maybe not the toggle for opening dev tools at startup.

**Comment by EvanBacon** [comment]
https://github.com/expo/expo-cli/issues/160

**Comment by EvanBacon** [comment]
Closing since we plan to reduce the web based devtools until we have more resources https://github.com/expo/expo-cli/pull/3966
