### ISSUE TITLE
After installing new expo-cli it is showing expo not found

### ISSUE THREAD

**Issue by satya700743** [expo/expo-cli#2009]
expo : The term 'expo' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.

after installing the expo the message was showing 
+ expo-cli@3.19.2
+ global@4.4.0
added 1671 packages from 918 contributors and audited 33685 packages in 801.475s

39 packages are looking for funding
  run `npm fund` for details

found 3 vulnerabilities (2 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details.

But still expo is not running

**Comment by byCedric** [comment]
Hi @satya700743! Thanks for reporting this. It looks like you installed `expo-cli` and `global`, which makes me wonder if you run this command by any chance: `npm install global expo-cli`. If so, that syntax is yarn specific, you can install global packages with yarn like `yarn global add expo-cli`. For NPM you have to use the `--global` flag, like `npm install --global expo-cli`. Also make sure your NPM path is added to your system, else terminal can't find `expo-cli` even when installed globally.

Hope it helps!
