### ISSUE TITLE
xdl docs?

### ISSUE THREAD

**Issue by skidding** [expo/expo-cli#204]
Is there a place where I can find docs for [expo/xdl](https://github.com/expo/xdl) APIs?

The README points to a [broken link](https://docs.expo.io/versions/devdocs/index.html). 

Thanks!

**Comment by fson** [comment]
To be able to show the QR code from a server, I recommend that you create a file named `.exprc` in the project folder with following contents to make it always use the same port:
```
{
  "manifestPort": 19010
}
```
(I've used port 19010, but you can choose any free port you want.) This way you don't need to parse the output from Expo CLI to determine which port it is using. Then spawn the CLI on the server with `child_process.spawn('expo', ['start'])` or [`spawnAsync`](https://github.com/expo/spawn-async). The manifest URL is now `http://public-url-of-your-server:19010`.

If you have more questions related to using Expo CLI programmatically, feel free to [write on our forums](https://forums.expo.io/c/help) and ping me!
