### ISSUE TITLE
Prompt to pick available simulators and emulators

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#2047]
When you press <kbd>a</kbd> or <kbd>i</kbd> in the interactive prompt in expo-cli we just open the first device/emulator/simulator that we come across. We should add <kbd>shift+a</kbd> and <kbd>shift+i</kbd> to show a prompt to pick from available devices/avds and simulators.

**Comment by EvanBacon** [comment]
Related https://github.com/expo/expo-cli/issues/290

**Comment by brentvatne** [comment]
it's also useful to be pick a simulator/android device when running `expo client:install:[ios/android]`

**Comment by brentvatne** [comment]
fixed by @EvanBacon:
- https://github.com/expo/expo-cli/pull/2550
- https://github.com/expo/expo-cli/pull/2541
