### ISSUE TITLE
expo whoami returns `not logged in` for server error.

### ISSUE THREAD

**Issue by jkhales** [expo/expo-cli#2052]
With no local server running, try: `EXPO_LOCAL=1 expo whoami`
![Screen Shot 2020-04-30 at 6 41 20 AM](https://user-images.githubusercontent.com/1220444/80717296-9d39af00-8aad-11ea-86b2-2e140cccd1ed.png)

Make error message report a server/connection issue instead.

**Comment by EvanBacon** [comment]
Related https://github.com/expo/expo-cli/pull/2019
