### ISSUE TITLE
expo publish is failing with error

### ISSUE THREAD

**Issue by Mahesha-Bhat** [expo/expo-cli#2054]
hi,
 Expo CLI 3.18.2 environment info:
    System:
      OS: Windows 10 10.0.16299
    Binaries:
      Node: 12.7.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.10.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5977832
    npmPackages:
      expo: ^37.0.0 => 37.0.7
      react: ~16.9.0 => 16.9.0
      react-native: ~0.61.5 => 0.61.5
      react-navigation: ^3.13.0 => 3.13.0

when I tried to run expo publish i get **spawn /bin/cp ENOENT**
please help me to fix this.

**Comment by fson** [comment]
It seems that you were using Expo CLI version `3.18.2`, when this happened. Could you upgrade to the latest version and see, if the problem still exists? Also could you send the contents of your `app.json`, in case there are some settings that might be affecting this?

**Comment by Mahesha-Bhat** [comment]
i upgraded expo-cli to 3.20.3 and when i ran **expo eject** i got following error.

![image](https://user-images.githubusercontent.com/45633194/81861904-93707b00-9586-11ea-9370-a30733571466.png)

expo-cli version 3.18.2 only generates android directory. but version 3.20.3 generates both android and ios, but  I'm using windows may be this is causing the issue.
please help me to fix this.

**Comment by fson** [comment]
Thanks for the additional info. Your screenshot doesn’t show the full command that you ran. Which one was it? (You mentioned `expo publish` before, but the screenshot looks like `expo eject`.)

**Comment by Mahesha-Bhat** [comment]
i'm trying to detach the expo,i had tried both expo eject and publish.
**with version 3.18.2 expo eject is working but expo publish is failing.**
**with version 3.20.3 expo eject itself failing on windows due to creation of both android and ios.**

**Comment by EvanBacon** [comment]
ejecting ios is now skipped on windows due to the various xcode requirements.
