### ISSUE TITLE
Expo-cli has not yet been tested against Node.js version 14.1.0

### ISSUE THREAD

**Issue by ComputerFlash** [expo/expo-cli#2055]
## Observed Behavior

```
Error text goes here!
```

**Comment by ComputerFlash** [comment]
Expo is not ready for node.js version 14.1.0

**Comment by byCedric** [comment]
Hi @ComputerFlash, what is the issue you encounter with Node 14? I just ran the basic commands like `expo login`, `expo start` and `expo publish`. They work fine on my computer.
