### ISSUE TITLE
Expo whoami does not go to stdout anymore

### ISSUE THREAD

**Issue by llamaluvr** [expo/expo-cli#2057]
## Description

On previous versions of expo-cli, the `expo whoami` command output to stdout, so the output could be written to a file, or read as a variable using `shelljs.exec()` or `child_process.exec()`. However, on the latest version (3.20.1), I notice the output of this command does not show up in `stdout` when running it via shelljs, child_process, or even when using bash redirection.

I'm not exactly sure when this changed, but it was not a problem on the last version I had installed - 3.16.1. For what it's worth, I notice on the old version that the user name outputted in green and on the new one it outputs in blue.

I previously executed `expo whoami` and read the output via shelljs to confirm the logged in user before executing publish; I realize I can now use the `owner` field in `app.json` instead. However, I found when looking for related bugs in the shelljs github that some tools for outputting to the terminal are not compatible with shelljs and other methods of reading output. So, if any other expo-cli commands behave like this, it may pose more of an issue for other CI/ automation use cases than just this particular command not working.

## Expected Behavior

I can read the output of `expo whoami` (which says something to the effect of `Logged in as [username]`) from stdout when executing from a node script or redirecting output to a file.

## Observed Behavior

I cannot read the output of `expo whoami` from stdout when executing from a node script or redirecting output to a file. Stdout is instead blank, or just contains the path and name of the command, depending on how it's run.

## Environment

```Expo CLI 3.20.1 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.14.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2
      react: 16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4
      react-navigation: 4.0.10 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.20.1
```

## Reproducible Demo

I first noticed this with shelljs, then tried child_process in a node script, but found I could reproduce most easily with simple bash redirection. In any case, all show the same behavior- the output is not accessible. So...

1. Run `expo whoami > output.txt` on the latest `expo-cli`.
2. Check the contents of `output.txt`. It will be empty.
3. Now downgrade to `expo-cli@3.16.1`with `npm install -g expo-cli@3.16.1`
4. Run `expo whoami > output.txt`.
5. Check the contents of `output.txt`. It will contain the output you would see in the terminal, e.g., `Logged in as [username]`.

**Comment by michaek** [comment]
This is due to the changes in https://github.com/expo/expo-cli/pull/2019/files as it now checks whether the stdout is a TTY before outputting the text you're looking for. From the source it would appear one could set `log.config.raw` to true and get some output, but I don't see any way that's exposed to the CLI.

**Comment by michaek** [comment]
I don't know whether the issue I described above was transient, or whether this change fixed it: I added an (unused) iOS app to my Firebase config and replaced my `google-services.json`. After rebuilding, I'm seeing an idToken. I'm sure that's the only change I made, as I inspected the diff of the config file.

**Comment by michaek** [comment]
Is this expected in version 3.20.6?

**Comment by michaek** [comment]
This is in 3.20.7 and it seems correct. Note: you'll get only the username on stdout, not "Logged in as ...".
