### ISSUE TITLE
Expo web caching issues

### ISSUE THREAD

**Issue by jjg77** [expo/expo-cli#2058]
UDPATE:  this issue is impacting the Safari browser, both Chrome and Firefox are able to pull down the latest files (with a refresh).  Safari users need to delete cache.

Expo web: looks like service worker is caching the chunk files.  I've had many users complain that the site won't load (after a new verison is deployed), hosted on netlify, and was able to reproduce it myself. What I saw was 404 errors for chunks that no longer exist.  The only fix was to delete cached files in the browser and reload the site.  Obviously I can't expect users to do this with every new deployment.  How can I fix this problem?

Note: when deploying to netifly, the deployment is atomic and old files are destroyed.  The issue with service workers is described here in more detail: https://community.netlify.com/t/primary-domain-cache-problem/8295

Looks like this issue was reported previously, but closed without a fix: https://github.com/expo/expo-cli/issues/449

**Comment by ianmartorell** [comment]
I'm seeing the same issue on iOS Safari, while desktop Chrome updates correctly after visiting the site again (so a refresh is needed to see the new version).

My site is deployed on [Vercel](https://vercel.com/), not Netlify.

**Comment by pors** [comment]
I have the same issue. The reason, in my case, is that production builds generate equal file names for the javascript bundles, even though the source code has changed. With regular webpack builds this won't happen, any ideas on how to approach this?

**Comment by pors** [comment]
Never mind my previous comment. I do have this issue, but even with changed asset names I have 404 errors for chunks that don't exist. Probably the same is as OP.

**Comment by ianmartorell** [comment]
I haven't tried it yet, but maybe we can look for an existing update and reload the site using [`expo-updates`](https://docs.expo.io/versions/latest/sdk/updates/).

**Comment by EvanBacon** [comment]
This is a problem with service workers, I have changed them to be opt-in only starting in SDK 39 (same as create-react-app). To disable the service workers now, please refer to this https://github.com/expo/expo-cli/tree/master/packages/webpack-config#fully-disabling-the-service-worker

**Comment by victorwads** [comment]
Just to improve knowledge about this problem:

Closing Chrome (All process) and restarting make chrome update the workers, it will happen when users restart their computers ou Cellphones, so chrome don't spend a lot of time searching for updates.

https://stackoverflow.com/questions/12124261/chrome-not-loading-latest-version-of-web-worker-script-runs-a-cached-version
