### ISSUE TITLE
Failed to register service-worker DOMException: Failed to register a ServiceWorker for scope (‘http://localhost:19006/’)

### ISSUE THREAD

**Issue by kopax** [expo/expo-cli#2063]
### Environment

When I access my app in development with `http://$ip:19006`, it work fine, but when I try to access with `http://localhost:19006` in order to use the geolocation, I have the following error:

    Failed to register service-worker DOMException: Failed to register a ServiceWorker for scope 
('http://localhost:19006/') with script ('http://localhost:19006/expo-service-worker.js'): The script has an unsupported MIME type ('text/html').

I am quite concerned, is there a way to fix the localhost url? I have tried to open the dev tools, go to application, service worker, unregister and refresh, but that didn’t help.

Platform: web

### Steps to Reproduce

`expo start --web`

### Expected Behavior

Service worker should register

### Actual Behavior

It shows a warning

### Reproducible Demo

Not yet

### Related issues

- https://stackoverflow.com/questions/63396049/expo-service-worker-js-93-uncaught-domexception-failed-to-execute-importscrip
- https://github.com/expo/expo-cli/issues/2468
- https://github.com/expo/expo-cli/issues/2403
- https://forums.expo.io/t/expo-how-to-fix-web-push-notification-in-development-when-accessing-throw-localhost-and-how-to-fix-the-localhost-service-worker/41752

**Comment by adam-kramer** [comment]
Encountering same issue after upgrading expo to latest sdk ~ 38.0.2. Also upgraded expo-cli to version below.
expo-cli: 3.22.0
react-native-cli: 2.0.1
react-native: 0.62.2

`Failed to register service-worker TypeError: Failed to register a ServiceWorker for scope ('http://localhost:19006/') with script ('http://localhost:19006/expo-service-worker.js'): ServiceWorker script evaluation failed`

**Comment by jsilvao** [comment]
I'm also having the same issue

**Comment by jsilvao** [comment]
Here's my actual error message

**Comment by jsilvao** [comment]
@kopax Have you found a solution yet?

**Comment by sheehyjohn** [comment]
Hello...
I've just started using expo/react-native and I am seeing something the same or similar. 

in my console I'm seeing the "info"
Failed to register service-worker TypeError: ServiceWorker script at http://localhost:19006/expo-service-worker.js for scope http://localhost:19006/ threw an exception during script evaluation.

expo-cli 3.22.3
node v10.21.0
react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz

**Comment by lewisjones28** [comment]
> 
> 
> Hello...
> I've just started using expo/react-native and I am seeing something the same or similar.
> 
> in my console I'm seeing the "info"
> Failed to register service-worker TypeError: ServiceWorker script at http://localhost:19006/expo-service-worker.js for scope http://localhost:19006/ threw an exception during script evaluation.
> 
> expo-cli 3.22.3
> node v10.21.0
> react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz

Me too...

**Comment by jsilvao** [comment]
Is there anyone from Expo willing to help us? Or did we came to the wrong place?

**Comment by lewisjones28** [comment]
> You need to enable the service worker in your web browser.
> 
> For chromium based browsers you need to go to: chrome://serviceworker-internals/ and check 'Open DevTools window and pause JavaScript execution on Service Worker startup for debugging.'

This didn't change anything, it still produces the following error;

![ee](https://user-images.githubusercontent.com/22603162/88771456-317fe480-d177-11ea-9b9e-2183d7092d68.png)

**Comment by OHHAKO** [comment]
I got same error in my react-native project using expo-cli. It's really weird becasue before seperate the css file it's works. but after seperate own css file it doesn't works. i think expo-cli supports react code not perfectly.

**Comment by ramanvaidhya** [comment]
I was facing a similar issue. This is my first project with the expo. 

I know this error occurs because all the web requests are default redirected to index.html hence when the application thinks this is a Text or an HTML page. We need to serve this service-worker.js from the location so the type is loaded as text/javascript. But unable to find where to set this property.

Any advanced Expo Users Help!!

**Comment by kopax** [comment]
I am still, stuck, I am trying to implement web push myself since expo does not provide web support in push notifications.

1. I can't fetch `expo-service-worker.js` at  `http://localhost:19006/expo-service-worker.js` when access from `localhost` but I can fetch it using the `ip`
 `http://192.168.10.101:19006/expo-service-worker.js` (instead of `localhost`)
1. When accessing from the `ip`, I can't get the web push permissions because I am not accessing in `https` nor `localhost`. 

Is there a way to fix (1) or (2) so I can use notification in development locally ?

**Comment by kopax** [comment]
I am trying to solve this so I can work with web push notification but I still got the issue after upgrade expo-cli, is this related?

## Related issues

- https://stackoverflow.com/questions/63396049/expo-service-worker-js-93-uncaught-domexception-failed-to-execute-importscrip
- https://github.com/expo/expo-cli/issues/2468
- https://github.com/expo/expo-cli/issues/2403
- https://forums.expo.io/t/expo-how-to-fix-web-push-notification-in-development-when-accessing-throw-localhost-and-how-to-fix-the-localhost-service-worker/41752

**Comment by kopax** [comment]
I have hosted at http://localhost:4001/expo-service-worker.js but when my site try to load it, it tries using the url we access it from http://localhost:19006 and fail ending on unexisting route http://localhost:19006/expo-service-worker.js which fallback in a wildcard that return the index.html, is there a way to fix this?
