### ISSUE TITLE
Next: withExpo not working with all modules

### ISSUE THREAD

**Issue by RWOverdijk** [expo/expo-cli#2065]
## Description

Using [this guide](https://docs.expo.io/guides/using-nextjs) I managed to setup expo + next love. It works great until you try to add something like ui-kitten + react native svg, then everything explodes and sadness splashes everywhere:

```
node_modules/react-native/Libraries/Utilities/warnOnce.js:15
const warnedKeys: {[string]: boolean} = {};
      ^^^^^^^^^^

SyntaxError: Missing initializer in const declaration
```

## Expected Behavior

Less explosions, more love.

## Observed Behavior

```
Oh no, I guess I ruined the format of the issue. 

node_modules/react-native/Libraries/Utilities/warnOnce.js:15
const warnedKeys: {[string]: boolean} = {};
      ^^^^^^^^^^

SyntaxError: Missing initializer in const declaration
```

## Environment

```
  Expo CLI 3.20.1 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.5
      react: ~16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: ~0.61.4 => 0.61.5
      react-native-web: ^0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.20.1
```

## Reproducible Demo

Just expo + that guide + ui-kitten quickstart.

## Workaround

I decided to add something to the issue template. I'm a rebel like that.

Currently I have a workaround but it feels icky and things get suuuuper slow. Which is saddening but next is so fast when used on its own.

The workaround is quite simple.

1. Install these deps:
`npm i --save next-compose-plugins next-transpile-modules`

2. Update next.config.js

```js
// @generated: @expo/next-adapter@2.1.3
// Learn more: https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/guides/using-nextjs.md#withexpo

const { withExpo } = require('@expo/next-adapter');

const withPlugins = require('next-compose-plugins');
const withTM = require('next-transpile-modules')(['@ui-kitten/components', 'react-native-svg']);

module.exports = withPlugins([withTM], withExpo({
  projectRoot: __dirname,
}));
```

And now everything works. I used this same workaround with the react-native-web + next template, so I figured I'd give it a go here... And sure enough it works.

## Another issue

```
SyntaxError: /Users/rwoverdijk/projects/mobile/mot/src/components/VenueList/index.js: Decorators are not enabled.
If you are using ["@babel/plugin-proposal-decorators", { "legacy": true }], make sure it comes *before* "@babel/plugin-proposal-class-properties" and enable loose mode, like so:
	["@babel/plugin-proposal-decorators", { "legacy": true }]
	["@babel/plugin-proposal-class-properties", { "loose": true }]

  10 | import { Footer } from '../Footer'
  11 |
> 12 | @observer
     | ^
  13 | export class VenueList extends Component {
  14 |   static defaultProps = {
  15 |     category: null,
```

**Comment by byCedric** [comment]
Hi @RWOverdijk, I think I know why this is happening. It's [related to this issue](https://github.com/expo/expo/issues/8060#issuecomment-620808399), right? If so, you can try the code I wrote there. To summarize it: 

Libraries built for React Native requires some "special" translating. Right now, the default settings will ignore all `node_modules` libraries and therefore not transpile libraries (such as `ui-kitten`). With the code mentioned there, it's added to the transpile whitelist but that _may_ cause other issues.

Hope it helps!

**Comment by RWOverdijk** [comment]
I could try that but I stopped using expo. Want me to close this issue?

**Comment by EvanBacon** [comment]
```
node_modules/react-native/Libraries/Utilities/warnOnce.js:15
const warnedKeys: {[string]: boolean} = {};
      ^^^^^^^^^^

SyntaxError: Missing initializer in const declaration
```

When you see this error, it means that something is calling into React Native instead of React Native for web. This is because on "React Native" is an iOS + Android framework, and Expo is a "iOS, Android, web" framework. We internally alias some of the bundled iOS + Android packages (like View, Text, Image) to use a web version in "react-native-web". When a package outside of the Expo scope attempts to use React Native it breaks this paradigm because Expo cannot transpile it. This often happens when the package doesn't start with `expo`, `react-native`, `@expo`, `react-navigation`. You can combat this by manually transpiling the packages https://www.npmjs.com/package/@expo/webpack-config#expobabeloptions
