### ISSUE TITLE
Expo build:android stuck on slash screen in apk with react-redux

### ISSUE THREAD

**Issue by ThMon** [expo/expo-cli#2067]
## Description
Hello, I have a problem when I want to build my expo in APK format. When I start my app on my device the app stuck on the slash screen.

## Expected Behavior

The problem happens when I use the component provider from react-redux in my App.js

Exemple with problem : 

```
import store from "./store";
import { Provider } from "react-redux";

export default class App extends React.Component {
  render(){
    return (

      <Provider store={store} >
        <Routes/>     
      </Provider>

    );
  }
}
```

Exemple without problem, the app run normaly but I can't use redux store : 

```
import store from "./store";
import { Provider } from "react-redux";

export default class App extends React.Component {
  render(){
    return (
        <Routes/>    
    );
  }
}
```

I tried to put the latest version of redux, react-redux, expo, expo-sdk, expo-cli, the bug persists.
I know that the problem comes from react-redux, any idea how can I fix it ?

## Environment

  Expo CLI 3.20.1 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.8
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-native-web: ^0.12.2 => 0.12.2
      react-navigation: ^4.3.9 => 4.3.9
    npmGlobalPackages:
      expo-cli: 3.20.1

Thank for your answers.

**Comment by brentvatne** [comment]
hi! we need a reproducible example to help with this. please create a new issue and provide an example that we can run to demonstrate the issue. this is likely a bug in your own code and trying to provide a minimal reproducible example will help you to locate that bug! if you can reproduce it then it'll help us to investigate! more guidance on how to do this if you need it: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by ThMon** [comment]
Hello, 

I tried to make a minimal reproductible and the mistake was in my code. react-redux work well with expo build.

Thank you for your help.
