### ISSUE TITLE
"assetExts" in app.json are ignored

### ISSUE THREAD

**Issue by drager** [expo/expo-cli#2077]
## Description
Specifying `assetExts` in `app.json` are ignored.

```json
 "packagerOpts": {
      "assetExts": [
          "bmp",
          "gif",
          "jpg",
          "jpeg",
          "png",
          "svg",
          "webview.js"
        ]
    }
```

And having a file called `index.webview.js` in `assets/web/index.webview.js` I get `Error: 'assets/web/index.webview.js' cannot be loaded as its extension is not registered in assetExts`

## Environment

```
Expo CLI 3.11.3 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.14.0 - ~/.nvm/versions/node/v8.14.0/bin/node
      Yarn: 1.19.1 - ~/.yvm/shim/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.14.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^5.3.8 => 5.3.8 
      expo: ^36.0.2 => 36.0.2 
      react: 16.12.0 => 16.12.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4
```

**Comment by brentvatne** [comment]
this is not how assetExts work, you can't call it `.webview.js` you would have to call it `.webview`. `.js` is already taken by a sourceExt. you can open an issue or pull request against http://github.com/facebook/metro if you would like it to support something similar to what you're doing here

**Comment by drager** [comment]
@brentvatne The same error occurs with that...

**Comment by brentvatne** [comment]
you are correct, we are passing the `assetExts` through but react-native-cli is ignoring them.

you can create the following `metro.config.js` file in your project root:

```js
const { getDefaultConfig } = require("metro-config");

module.exports = (async () => {
  let defaultConfig = await getDefaultConfig();

  return {
    resolver: {
      assetExts: [...defaultConfig.resolver.assetExts, "webview"],
    },
  };
})();
```

here's a full working example for you: https://github.com/brentvatne/asset-exts-example

here's where we import the asset then read it: https://github.com/brentvatne/asset-exts-example/blob/6964ad62cc27d734fbc3174a5bc04b51db3c1aed/App.tsx#L7-L24

**Comment by drager** [comment]
> you are correct, we are passing the `assetExts` through but react-native-cli is ignoring them.
> 
> you can create the following `metro.config.js` file in your project root:
> 
> ```js
> const { getDefaultConfig } = require("metro-config");
> 
> module.exports = (async () => {
>   let defaultConfig = await getDefaultConfig();
> 
>   return {
>     resolver: {
>       assetExts: [...defaultConfig.resolver.assetExts, "webview"],
>     },
>   };
> })();
> ```
> 
> here's a full working example for you: https://github.com/brentvatne/asset-exts-example
> 
> here's where we import the asset then read it: https://github.com/brentvatne/asset-exts-example/blob/6964ad62cc27d734fbc3174a5bc04b51db3c1aed/App.tsx#L7-L24

Thanks! But how about when I actually want to load js-files? If i change all my js-files to `.webview` instead of `.js` Safari will complain about `no-sniff` i.e. `Refused to execute http://127.0.0.1:19001/assets/assets/file.webview as script because "X-Content-Type: nosniff" was given and its Content-Type is not a script MIME type.`

This is because I have my `index.html` with a `script` tag: `<script type="text/javascript" src="file.webview"></script>`

**Comment by brentvatne** [comment]
i'm not really sure about that, you may want to inquire with react-native-webview team what they had in mind for it.

we've updated documentation to add information about a recommended way to handle customizing assetExts now, thanks for bringing this to my attention! https://docs.expo.io/guides/customizing-metro/

**Comment by drager** [comment]
> i'm not really sure about that, you may want to inquire with react-native-webview team what they had in mind for it.
> 
> we've updated documentation to add information about a recommended way to handle customizing assetExts now, thanks for bringing this to my attention! https://docs.expo.io/guides/customizing-metro/

@brentvatne Well, it's not a problem with react-native-webview. The main problem here is that we can't bundle local js files. Running `expo publish` won't publish the correct files (i.e. no js files).
