### ISSUE TITLE
"The batch file can not be found" when detaching to  ExpoKit on windows (harmless but annoying message)

### ISSUE THREAD

**Issue by joshua-tmc** [expo/expo-cli#208]
### Environment

Environment:
  OS: Windows 10
  Node: 8.10.0
  Yarn: 1.5.1
  npm: 5.8.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^26.0.0 => 26.0.0
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/jaugustinus-ef24bdd1-a262-406f-bc79-230d5c1f62c8.tar.gz

### Steps to Reproduce

```
create-react-native-app test

cd test

npm run eject
```

When asked choose to eject to Expokit
errors will appear on screen
[2018-04-05T01_01_21_097Z-debug.log](https://github.com/expo/expo/files/1878281/2018-04-05T01_01_21_097Z-debug.log)

### Expected Behavior
No errors

(Write what you thought would happen.)

### Actual Behavior

See attachment

### Reproducible Demo

https://github.com/joshua-tmc/expo-test.git

**Comment by EvanBacon** [comment]
- Detaching to ExpoKit is deprecated
- ExpoKit is deprecated
- react-native-scripts is deprecated
