### ISSUE TITLE
Android build failed on newly created project

### ISSUE THREAD

**Issue by bharatpatil** [expo/expo-cli#2083]
Today I installed expo-cli and created a project using it and when I try to `yarn android`, I faced an issue. I'm using Windows 10.

**Steps I did**
1. yarn global add expo-cli
2. expo init my-project
3. yarn android

**Error faced**
```
* What went wrong:
Could not compile script 'node_modules\expo-updates\expo-updates.gradle'.
> startup failed:
  script 'node_modules\expo-updates\expo-updates.gradle': 22: unable to resolve class GradleVersion
   @ line 22, column 19.
         GradleVersion gradleVersion = GradleVersion.current()
```

I was able to solve issue and could run app successfully by doing below:
1. opened `node_modules\expo-updates\expo-updates.gradle`
2. added this line at the top `import org.gradle.util.GradleVersion`

Any help is appreciated. I'm currently confused about how to move forward.

**Comment by brentvatne** [comment]
hi there! i just tried this and it worked as expected on my machine.

i also opened `node_modules/expo-updates/expo-updates.gradle` and `import org.gradle.util.GradleVersion` was there. also see https://github.com/expo/expo/blob/e972c68dfd55a1202fc9c5824a090f0cebcda43c/packages/expo-updates/expo-updates.gradle#L4

the latest time expo-updates was published was 8 days ago, so nothing would have changed between when you ran this and when i did.

can you try following your reproduction steps and verify that this is happening for you? it's possible you accidentally made some change to your project if you didn't follow those steps exactly.

**Comment by bharatpatil** [comment]
Hi, I was able to fix this by changing `expo-updates` version from  `0.1.0` to `0.1.3`.
This problem occurred because I removed `~` sign from package.json file from `expo-updates` to have the exact versions of packages and version was `0.1.0`

I'm very sorry for the trouble and confusion. This is the step I should have mentioned while opening the issue. So closing this issue.
