### ISSUE TITLE
expo-cli npm ERR! Unexpected end of JSON input while parsing near '...@expo/xdl":"57.8.24",'

### ISSUE THREAD

**Issue by codetexi** [expo/expo-cli#2084]
C:\>npm install -g expo-cli
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/traveling-fastlane-darwin@1.13.1 (node_modules\expo-cli\node_modules\@expo\traveling-fastlane-darwin):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/traveling-fastlane-darwin@1.13.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! Unexpected end of JSON input while parsing near '...@expo/xdl":"57.8.24",'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Hacker\AppData\Roaming\npm-cache\_logs\2020-05-07T13_32_59_186Z-debug.log

C:\>

how to solve ?

**Comment by brentvatne** [comment]
hi there! this is a probably that people occasionally encounter with npm on windows: https://stackoverflow.com/questions/47675478/npm-install-errorunexpected-end-of-json-input-while-parsing-near-nt-webpack

to resolve it, run:

```
npm cache clean --force
npm install -g expo-cli
```
