### ISSUE TITLE
App with large data files > Packager not happy

### ISSUE THREAD

**Issue by PiTiLeZarD** [expo/expo-cli#209]
G'day fellas,

Firstly thanks for all the hard work, I'm loving expo/react-native! Didn't have many problems and I could find answers to most of'em but I'm now stuck with loading large data files.

My app has a map with 3k+ points and each point has 1 to 5 polygons attached. These polygons can be quite complex (read lots of data...) ([example of one](https://twitter.com/VK4ALE/status/954177446173011969), and there's 3k+ of'em)

For now the 3k+ points no worries at all. The polygon situation on the other hand is a bit sticky.

I'm having something like this:

export type Coord = Array<number>;
export type Polygon = Array<Coord>;
export type Geom = Array<Polygon>;
export type Boundaries = {
    [ItemID]: Geom
};

And a file which is **18Mb** of:

boundaries["XXX"] = [[[148.507052846,-24.437629595],[148.524729893,-24.445195653] etc...
boundaries["XXX"] = [[[148.507052846,-24.437629595],[148.524729893,-24.445195653] etc...
etc...

Well, in theory it's all fine and dandy but the packager really doesn't like it. It goes to 99.7% and then the 8 cores of my machine go bonkers for what looks like forever (I didn't try to see if it reaches any success/failure, stopped after 4/5 min wait)

So my question is: "Is this supposed to work or not?" if it is supposed to work then I'm doing something wrong. If it's not intended that way I'm probably having a design issue here.

Things I've tried:
 - Reducing the size of files (it was originally 25Mb well printed, I removed all spaces and whatnot)
 - Having db/boundaries/index.js loading 10 files max 5Mb where the data is split by states => Still doesn't load

Things I haven't tried but considered:
 - Using assets for these files (but Assets says it's specifically for anything *but* JS, would it work?)
 - Download on start (sounds quite user unfriendly)
 - SQLite database (but I have to detach my app right? I've seen it's impossible to use a preloaded database without downloading it, am I right assuming this?)
 - Remote api and asking polygons on demand, which will be my last resort if all else fail

Is there another solution? Which one should I try first? I realise I have to decide myself but there's quite the time investment in each and any experienced advice would be gratefully received.

Cheers

**Comment by EvanBacon** [comment]
This is an upstream Metro bundler issue. Nothing we can do in `expo-cli`.
