### ISSUE TITLE
npm install -g expo-cli: No matching version found for @expo/config@3.2.1

### ISSUE THREAD

**Issue by yrjwcharm** [expo/expo-cli#2097]
![image](https://user-images.githubusercontent.com/34397383/81546086-6ec0ab80-93ac-11ea-8501-a10e8d25f5bb.png)

**Comment by fson** [comment]
That's weird. This version should exist, it was published a few days ago.

Could you tell what the following commands return for you?
```
npm view @expo/config versions

npm config get registry
```

**Comment by yrjwcharm** [comment]
I  have already solved it!

**Comment by Rohini1907** [comment]
@yrjwcharm can you tell the solution for the above. Getting the same issue
thanks in advance
