### ISSUE TITLE
Fonts loading compatibility with bare workflow and expo client

### ISSUE THREAD

**Issue by maurovisintin** [expo/expo-cli#2098]
We’re using bare workflow to build our app, generating our bundle with ‘expo export’.
The fonts are correctly imported and loaded in our bare app, but they fail to load when we run the same bundle on the expo client (both default expo-icons and custom ones are rendered as ? ).
We get no error message suggesting that the fonts are not loaded correctly, they just don’t get rendered.
We found out that we can make it work correctly in expo client by changing the template of the bundle when exporting ‘expo export --template managed’, like suggested in (https://github.com/expo/expo/issues/8107) but this makes the native bare app fail to build.

Is there a way to make the bundle work for both expo client and bare app?

expo-cli 3.19.2

**Comment by mdcuk34** [comment]
I've also dedicated some time to this issue, would be interested to hear if there's a solution. Mentioned on the expo forum here: https://forums.expo.io/t/fonts-loading-compatibility-with-bare-workflow-and-expo-client/37503

**Comment by brentvatne** [comment]
hey there! this isn't well documented, but you can do the following:

use different release channels when publishing for expo client and for standalone apps. for example, maybe you use the `default` channel for expo client and the `prod` channel for standalone apps. then you would run `expo publish --target managed --release-channel default`  and it would publish to the default channel with config to run in expo client. if you run `expo publish --target bare --release-channel prod` it would publish to the prod channel with the bare config. the default value for release channel is `default` and the default value for `target` is bare in a bare app and managed in a managed app. so you could alternatively just write `expo publish --target managed` and `expo publish --release-channel prod` to accomplish the same thing as those commands

**Comment by maurovisintin** [comment]
Thanks for the quick response!
We host the bundles internally, so we can't leverage release-channels.
So you confirm that we have to host 2 different bundles to run for bare and managed workflows?

**Comment by brentvatne** [comment]
yup, the build process is different between the two. for example, in managed apps we pull in files with the `.expo.[js/ts/jsx/tsx]` extension with higher priority than other extensions, and so the resulting build ends up being quite different since some libraries depend on this to differentiate between managed and bare workflow.
