### ISSUE TITLE
Give an option to correct project name when an invalid one is provided

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#2103]
```
╰─$ expo init lol-new-one
? Choose a template: expo-template-bare-typescript
Project name can only include ASCII characters A-Z, a-z and 0-9
```

It'd be better if instead of exiting here it said:

```
╰─$ expo init lol-new-one
? Choose a template: expo-template-bare-typescript
A project name can only include ASCII characters A-Z, a-z and 0-9. Learn more.
> Enter a project name: LolNewOne
```

in this case we 1) give people a link to expo.fyi with info about why these restrictions exist (if we can't justify, we should remove) 2) let them enter a new name 3) default the new name to a transformed version of the old name to remove invalid characters

**Comment by expelledboy** [comment]
Can someone explain why expo now has this limitation?

This might sound stupid, but we have consistency of strings for a project across multiple repos, and what is being set as the project name generates into locations which I need to be consistent. Previously it wasnt an issue to create my-cool-app.

**Comment by brentvatne** [comment]
you can't include `-` in ios and android project names iirc

**Comment by EvanBacon** [comment]
When ejecting you can now use any character you want, init still requires the npm-safe name which also has better prompting in #2604
