### ISSUE TITLE
 Something when wrong installing JavaScript dependencies. Check your yarn logs. Continuing to initialize the app.

### ISSUE THREAD

**Issue by yrjwcharm** [expo/expo-cli#2105]
![image](https://user-images.githubusercontent.com/34397383/81631461-80509480-943a-11ea-9448-a3666babf92d.png)

**Comment by brentvatne** [comment]
go into the project directory and run yarn. probably there is some issue with your machine, maybe you don’t have git installed

**Comment by yrjwcharm** [comment]
I  already installed git.
![image](https://user-images.githubusercontent.com/34397383/81632215-5009f580-943c-11ea-962a-6de8c2b713fc.png)

**Comment by yrjwcharm** [comment]
@brentvatne  help!!!

**Comment by brentvatne** [comment]
run yarn in your project directory

**Comment by yrjwcharm** [comment]
Powerful !!!

**Comment by AmrShaar13006** [comment]
I have the same problem, what can I do?

**Comment by wyzlhf** [comment]
I have the same problem

**Comment by PedroGSantos** [comment]
I am having the same problem. What did you do to fix this? I downgrade expo-cli to 3.15.5, but I did not fix this.

**Comment by brentvatne** [comment]
you need to have git installed on your machine to use expo-cli

**Comment by junioruche49** [comment]
After searching online I tried these steps and it worked

step 1
npm cache clean --force

Step 2
npm cache verify

Step 3
npm -g uninstall expo-cli --save

Final Step
npm install expo-cli --global

**Comment by LuisSanchez** [comment]
This worked for me:
1. Deleted **node_modules** and **package.lock.json**
2. **npm install**

**Comment by HenriqueGPinho** [comment]
I've solved it by using "expo init <project> --npm" instead of "expo init <project>"

**Comment by belmiro-kunga** [comment]
![Captura de ecrã de 2020-08-12 01-41-09](https://user-images.githubusercontent.com/24614505/89964354-d30c3900-dc41-11ea-9488-36646ef20bfc.png)



I have the same problem, I've done everything that was said and it doesn't solve my problem, someone else has another alternative

**Comment by willytony** [comment]
Use :  
expo init npm myProject

Instead of. expo init myProject

**Comment by anshucodebook15** [comment]
> After searching online I tried these steps and it worked
> 
> step 1
> npm cache clean --force
> 
> Step 2
> npm cache verify
> 
> Step 3
> npm -g uninstall expo-cli --save
> 
> Final Step
> npm install expo-cli --global

It works Man and you don't have to uninstall expo just clear the cache and then start your expo
npm cache clean --force

expo init myNewProject

**Comment by alexjayd** [comment]
Unfortunately, all the solutions described above didn't work on my machine...
Here is my latest solution for this problem...
This worked **100%** on my machine...
Use `npm i -g expo-cli`
This will automatically add the required packages and also remove the unnecessary ones.
Yes, surely, you don't need to uninstall and re-install it again.
Just follow my steps.
And, you can create your expo project using `expo init`.
_I hope my solution will help you out from this annoying problem..._.

**Comment by kotunde** [comment]
> Use :
> expo init npm myProject
> 
> Instead of. expo init myProject

It worked! Thanks!

**Comment by jawwadakhter674** [comment]
unfortunately all the solutions described above didn't work in my pc ..kindly someone help me what i can do to install expo easily because its so difficult and stupidly things error during installation....

**Comment by davidglauber** [comment]
im facing this problem with expo eject too, Does someone know how to fit it?

**Comment by yhoungdev** [comment]
> ![Captura de ecrã de 2020-08-12 01-41-09](https://user-images.githubusercontent.com/24614505/89964354-d30c3900-dc41-11ea-9488-36646ef20bfc.png)
> 
> I have the same problem, I've done everything that was said and it doesn't solve my problem, someone else has another alternative

 go to your project folder and type yarn 
 that was the method that worked for me

**Comment by marcusoftnet** [comment]
Here's another vote for just running `yarn` in the project directory. That worked for me and cleaned up the missing stuff in `package.json` and it's missing lock file that seemed to be the problem. 

Just a tip - I don't like yarn on my machine but a simple `npx yarn` solved that. 

Just run `npx yarn` in the project folder, in other words
Or `npm i` that seemed to solve the problem too

**Comment by DraconView** [comment]
run expo init command and project name again
![expo init](https://user-images.githubusercontent.com/81877111/118917210-f2817200-b8f5-11eb-8f8b-4adcdffc658b.png)

**Comment by budostylz** [comment]
Just putting a bit of seasoning in this discussion thread. Make sure your node, expo and rest of your machine environment are in sync. Check out Node Version Manager https://github.com/nvm-sh/nvm.

**Comment by Mudassir164** [comment]
> Here's another vote for just running `yarn` in the project directory. That worked for me and cleaned up the missing stuff in `package.json` and it's missing lock file that seemed to be the problem.
> 
> Just a tip - I don't like yarn on my machine but a simple `npx yarn` solved that.
> 
> Just run `npx yarn` in the project folder, in other words Or `npm i` that seemed to solve the problem too

my issue is to be solve using this step

**Comment by wyzlhf** [comment]
Thank you. Your email is received and will be handled  as soon as possible.谢谢。您的邮件已收到，我会尽快处理。

**Comment by ishaiknadeem** [comment]
Just simply make sure that npm version is above 12.0.0. This is the actual issue.

**Comment by wyzlhf** [comment]
Thank you. Your email is received and will be handled  as soon as possible.谢谢。您的邮件已收到，我会尽快处理。

**Comment by VuDoanDungVN** [comment]
This seems to be an error caused by yarn but I solved this problem with the following:
expo init AppFri -> error
expo init AppFri --npm (OK)
![image](https://user-images.githubusercontent.com/103544773/224229414-51063a76-7b7a-4472-89f4-ee30d45c6d0b.png)
