### ISSUE TITLE
Strongly suggest using a good terminal for Windows

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#2107]
cmd.exe is not a good tool for development. They should use Powershell or Bash via WSL or something instead. If we can detect WSL, we should also warn and suggest using WSL2

**Comment by Fahad-Mahmood** [comment]
I have created a pre-start script that logs for windows: 'Please avoid using CMD for development. Use PowerShell or Bash via WSL';

`
let os = require('os');

// check for windows OS
if (os.platform() === 'win32') {
  console.log('Please avoid using cmd.exe for development. Instead use PowerShell or Bash via WSL');
}
`

**Comment by brentvatne** [comment]
nice! can you open a pull request?

**Comment by brentvatne** [comment]
you could add it to https://github.com/expo/expo-cli/blob/master/packages/expo-cli/bin/expo.js

**Comment by Fahad-Mahmood** [comment]
right now I have added it in scripts folder with the file name: "check-windows.js";
package.json looks like this with prestart: 
````
"scripts": {
    "format": "prettier --write .",
    "build": "lerna run prepare --stream",
    "postinstall": "expo-yarn-workspaces check-workspace-dependencies",
    "publish": "echo \"This script is deprecated. Run \\\"node ./scripts/publish.js\\\" instead.\"; exit 1",
    "prestart": "node ./scripts/check-windows.js",
    "start": "lerna --ignore \"@expo/{dev-tools,next-adapter,electron-adapter}\" --ignore expo-optimize --ignore pod-install --ignore uri-scheme run watch --parallel",
    "tsc": "echo 'You are trying to run \"tsc\" in the workspace root. Run it from an individual package instead.' && exit 1",
    "lint": "eslint . --ext js,ts"
  },
````

**Comment by Fahad-Mahmood** [comment]
should it work for expo? not for expo-cli development.

**Comment by Fahad-Mahmood** [comment]
added script in the mentioned file and created pull request here: https://github.com/expo/expo-cli/pull/2164

**Comment by Fahad-Mahmood** [comment]
Did you check PR? What should be done to improve it?
