### ISSUE TITLE
build:* warns (fails in --non-interactive) when --config option used

### ISSUE THREAD

**Issue by christynwegner** [expo/expo-cli#2109]
## Description

We have an app that  allows for different operators to skin, enable features, and to customize their experience via different `app.json` configuration files. These files have been defined in `config/<appName>.json` which we pass into the expo-cli commands via the `--config` option. As such, we have removed the `app.json` from the project root directory.

As of the expo-cli version `3.20.3`, the `expo build:* --config ./config/<appName>.json` commands warn that the app is not using the expo managed workflow; however, the app has never been ejected and thus should be an expo managed workflow app.

Quickly digging into the code base I found that the managed workflow check requires that the `app.json` exist in the project root directory, ignoring the path declared in the `--config` option: https://github.com/expo/expo-cli/blob/expo-cli%403.20.3/packages/expo-cli/src/commands/utils/ProjectUtils.ts#L25

The check that was added in version `3.20.3` is `maybeBailOnWorkflowWarning` https://github.com/expo/expo-cli/blob/expo-cli%403.20.3/packages/expo-cli/src/commands/build/index.ts#L15

The current workaround for this to apply the `--skip-workflow-check` option to both `build:ios` and `build:android` commands

## Expected Behaviour

`expo build:* --config config/path.json` passes the expo managed workflow check using the `app.json` file declared via the `--config` option

## Observed Behaviour

CI/CD build failed due to failing the expo managed workflow check (with `--non-interactive` enabled)
```
[16:42:06] ⚠️  expo build:android currently only supports managed workflow apps.
[16:42:06] If you proceed with this command, we can run the build for you but it will not include any custom native modules or changes that you have made to your local native projects.
[16:42:06] Unless you are sure that you know what you are doing, we recommend aborting the build and doing a native release build through Android Studio.
[16:42:06] Input is required, but Expo CLI is in non-interactive mode.
Required input:
> Would you like to proceed?
```

## Environment

```
$ expo diagnostics

  Expo CLI 3.20.3 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 13.10.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.7 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.8 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-navigation: ^4.0.10 => 4.3.7 
    npmGlobalPackages:
      expo-cli: 3.20.3
```

**Comment by brentvatne** [comment]
thanks, I'll handle this as it's my fault. really appreciate the time you took to investigate the root cause, and i'm glad that you were able to use `--skip-workflow-check` to workaround for now
