### ISSUE TITLE
New apps for iPhone or iPad must be built with the iOS 13 SDK or later

### ISSUE THREAD

**Issue by pindamonhangaba** [expo/expo-cli#2113]
## Description

I can't upload the .ipa to the app store

## Expected Behavior

Upload to AppStoreConnect

## Observed Behavior

After building the iOS app, when I try to upload to the store via Transporter I get this error:

```
    ERROR ITMS-90725: “SDK Version Issue. This app update was built with the iOS SDK. New apps for iPhone or iPad must be built with the iOS 13 SDK or later.”

```

If I try through cmd, with xcrun altool --upload-app --type ios --file expo.ipa:

```
    ERROR: ERROR ITMS-90207: “Invalid Bundle. The bundle at ‘ExpoKitApp.app’ does not contain a bundle executable.”

```

## Environment

Expo CLI 3.20.3 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.16.2 - C:\Users\...\AppData\Local\Temp\yarn--1589368303876-0.2262724249603949\node.CMD
      Yarn: 1.22.4 - C:\Users\...\AppData\Local\Temp\yarn--1589368303876-0.2262724249603949\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^37.0.0 => 37.0.10
      react: 16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-navigation: ^3.11.0 => 3.13.0

**Comment by brentvatne** [comment]
this happens when you are using an old version of xcode or transporter on your machine. you should upgrade to the latest.

how are you uploading from windows? that shouldn't be possible?

**Comment by pindamonhangaba** [comment]
I develop on Windows but upload through a Mac. 

There was an xcode update pending. After updating it worked. Thanks!
