### ISSUE TITLE
expo upgrade doesn't know when expo package upgrade failed

### ISSUE THREAD

**Issue by d4rky-pl** [expo/expo-cli#2114]
## Description

When running `expo upgrade` on existing project, if there's a problem when upgrading `expo` package, expo-cli still believes that everything went well which results in broken upgrade.

## Expected Behavior

If upgrading `expo` package fails, expo-cli should stop whatever it's doing

## Observed Behavior

```
✖ Failed to install expo package with error: yarnpkg exited with non-zero code: 1
✔ Installed expo@^37.0.0
```

Manually upgrading expo reveals the error as:

```
error move-file@2.0.0: The engine "node" is incompatible with this module. Expected version ">=10.17". Got "10.15.1"
```

## Environment

expo-cli 3.20.3
upgrading from SDK 35 to SDK 37

## Reproducible Demo

Try upgrading with `expo upgrade` while running on node version older than `10.17` (hard to create a reproducible demo for this)

**Comment by fson** [comment]
How did you end up with the `move-file` dependency in your project (since installing results in this error)? Is `move-file` a dependency of your project or being included by one of its dependencies? Could you run `yarn why move-file` to check that?

**Comment by brentvatne** [comment]
i agree we should stop if we fail to install the expo package, i'll look into it

**Comment by d4rky-pl** [comment]
@fson it's a dependency unrelated to Expo but it's also unrelated to the reported problem (it's just a reason why the bug got triggered in the first place) :)

**Comment by brentvatne** [comment]
@byCedric or @cruzach - could you take care of making upgrade fail entirely if installing the expo package fails? related code here https://github.com/expo/expo-cli/blob/master/packages/expo-cli/src/commands/upgrade.ts#L453
