### ISSUE TITLE
expo upgrade can downgrade packages

### ISSUE THREAD

**Issue by d4rky-pl** [expo/expo-cli#2115]
## Description

When running `expo upgrade`, if any of the dependencies are in newer version, they're being downgraded even if there's no reason to.

## Expected Behavior

`expo upgrade` should keep the newer versions

## Observed Behavior

- @expo/webpack-config `^0.12.5` -> `^0.11.25`
- react-native-gesture-handler `^1.6.1` -> `~1.6.0` (this one may actually make sense though)

## Environment

expo-cli  3.20.3

**Comment by brentvatne** [comment]
expo upgrade picks the versions of a library that are compatible with the sdk version you are using. if you want to risk switching to another package version that isn't explicitly supported, you will need to opt in to that.

`@expo/webpack-config ^0.12.5 -> ^0.11.25` will resolve to the same thing

**Comment by martin-braun** [comment]
@brentvatne This is the behavior that is right, but it is not working in my case.

I forcefully upgrade all packages, then I upgrade expo and I want it to downgrade all packages, but it's not downgrading my packages in the package.json: 

`npm-check-updates -u && npm i expo-cli@latest -D && expo upgrade` should result in `"react": "18.0.0"`, but I end up with `"react": "18.2.0"`, thus I get: 

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-app@0.0.1
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
```

when running `npm i`. Why?
