### ISSUE TITLE
expo web loader is broken with new webpack

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo-cli#2123]
the format is wack

**Comment by robclouth** [comment]
Yep I'm getting this. Any ideas? I can try downgrading webpack

**Comment by hammadj** [comment]
Also getting this. 
```
webpack Dev Server Invalid Options

options should NOT have additional properties
```
Revert to older version?

**Comment by robclouth** [comment]
I went back to 0.12.3 for now. It works great with the latest expo in a monorepo.

**Comment by mdlavin** [comment]
I hit this today after upgrading to Expo 38

**Comment by EvanBacon** [comment]
Fixed in https://github.com/expo/expo-cli/pull/3766
