### ISSUE TITLE
expo start error 

### ISSUE THREAD

**Issue by Wani28** [expo/expo-cli#2125]
hi 
i'm trying to start expo but i keep getting this message (btw i'm a new programmer forgive my stupid Q's)

(node:43920) UnhandledPromiseRejectionWarning: RangeError [ERR_SOCKET_BAD_PORT] [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received 65536.
    at Server.listen (net.js:1440:13)
    at /usr/local/lib/node_modules/expo-cli/node_modules/freeport-async/index.js:8:12
    at new Promise (<anonymous>)
    at testPortAsync (/usr/local/lib/node_modules/expo-cli/node_modules/freeport-async/index.js:6:10)
    at availableAsync (/usr/local/lib/node_modules/expo-cli/node_modules/freeport-async/index.js:24:17)
    at /usr/local/lib/node_modules/expo-cli/node_modules/freeport-async/index.js:37:23
    at new Promise (<anonymous>)
    at freePortRangeAsync (/usr/local/lib/node_modules/expo-cli/node_modules/freeport-async/index.js:33:10)
    at /usr/local/lib/node_modules/expo-cli/node_modules/freeport-async/index.js:43:18
(node:43920) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:43920) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by EvanBacon** [comment]
Please update your version of node
