### ISSUE TITLE
DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#2133]
When running `expo start` on latest expo-cli with Node 12 or 14 and probably others.

**Comment by DmitryKvant** [comment]
same issue, please some help

**Comment by mikescott** [comment]
Same `(node:1813) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated` following a failed publish

**Comment by brentvatne** [comment]
@DmitryKvant - this doesn't impact usage of the tool, it is just a warning.
