### ISSUE TITLE
expo start fails

### ISSUE THREAD

**Issue by SeungsuKim** [expo/expo-cli#2139]
## Description

expo start and yarn start fails with error message "error Unrecognized command "start""

## Expected Behavior

Expect to be normally started.

## Observed Behavior

```
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
error Unrecognized command "start".

info Run "react-native --help" to see a list of all available commands.
Metro Bundler process exited with code 1
Error: Metro Bundler process exited with code 1
    at ChildProcess.<anonymous> (/@expo/xdl@57.9.9/src/Project.ts:1838:16)
    at Object.onceWrapper (events.js:428:26)
    at ChildProcess.emit (events.js:321:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

## Environment

 Expo CLI 3.20.9 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.6.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.2 => 36.0.2
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
      react-native-web: ^0.12.1 => 0.12.2

**Comment by brentvatne** [comment]
sorry nobody got back to you on this. i'm not sure what was happening in your particular instance, we'd need more information to be certain. if this is still an issue for you, please let us know how to reproduce. but because this is likely stale now i'm going to close until we hear back
