### ISSUE TITLE
Cache is not cleared when running expo r -c -w

### ISSUE THREAD

**Issue by deathemperor** [expo/expo-cli#2143]
## Description

Expo-cli doesn't clear web cache folder when running with -c.

I'm using `babel-plugin-import-graphql` to read graphql files. The plugin caches the files.

## Expected Behavior

`.expo/web/cache` folder is cleared

## Observed Behavior

contents on `.expo/web/cache` are still there when running with -c option

## Environment

```
Expo CLI 3.20.3 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.10.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.8
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.20.3
```

## Reproducible Demo

N/A

**Comment by EvanBacon** [comment]
This appears to be resolved in the latest, versioned Expo CLI. If you encounter this issue in the future, please open an issue on [expo/expo](https://github.com/expo/expo/issues/new?assignees=&labels=needs+review%2CCLI&template=bug_report_cli.yml).
