### ISSUE TITLE
Verify that `fastlane supply` works fine on linux/windows

### ISSUE THREAD

**Issue by dsokal** [expo/expo-cli#2155]
We're using `fastlane supply` for uploading Android apps with `expo upload:android`. Currently, we don't let people to use that on any other os than macOS (https://github.com/expo/expo-cli/blob/master/packages/expo-cli/src/commands/upload.ts#L118). 
We should verify if this restriction is still needed.

**Comment by EvanBacon** [comment]
supplyAndroid is no longer used in expo-cli
