### ISSUE TITLE
With @expo/next-adapter, process.env is not available even on server side.

### ISSUE THREAD

**Issue by en30** [expo/expo-cli#2156]
## Description
I tried to use `process.env` in `getServerSideProps`, but I cannot.
Might `@expo/next-adapter` rewrite `process.env`?

## Expected Behavior
Environment variable is available on server side as bare Next.js.

## Observed Behavior
`process.env` only has keys `NODE_ENV` , `PUBLIC_URL`, `APP_MANIFEST` always.

## Environment

```console
$  expo diagnostics                                                                                                           
  Expo CLI 3.20.9 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.7.1 - /usr/local/bin/zsh
    Binaries:
      Node: 12.15.0 - ~/.nvm/versions/node/v12.15.0/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.15.0/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.12
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.20.9
```

## Reproducible Demo
https://github.com/en30/expo-next-adapter-env-issue

```console
yarn next dev
curl http://localhost:3000/
```

**Comment by marklawlor** [comment]
For more context, NextJS 9.4 added inbuilt support for loading environment variables from multiple .env files [documentation here](https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables)

When starting a NextJS App you see the output

```
info  - Loaded env from .env.local
info  - Loaded env from .env
```

But Expo will override the process.env

**Comment by rodrigorm** [comment]
By now you need to prefix your environment variables with `EXPO_` or `REACT_NATIVE_` but Expo will remove all variables with `/(PASSWORD|SECRET|TOKEN)/i` according to https://github.com/expo/expo-cli/blob/master/packages/webpack-config/src/plugins/ExpoDefinePlugin.ts#L63

I think a better solution would be to keep existing variables in `process.env` and filter variables to `manifest` for Expo compatibility and supports `process.env` in Next.js SSR.

**Comment by EvanBacon** [comment]
I opened a PR that I think fixes the issue. Would be helpful if someone could verify the changes in #2177. Essentially instead of defining:
```
process.env = { NODE_ENV: 'development' ... }
```
It'll define the keys like Next.js:
```
process.env.NODE_ENV = 'development'
```
This means that doing the following logs an empty object:
```js
console.log(process.env)
```

**Comment by marklawlor** [comment]
Hi @EvanBacon, I'm not sure if setting `process.env` to `{}` and only allowing known keys is desired behaviour on the server side.

Quite a number of server side packages rely on `process.env` variables that may not be available at built time and only exist within the server environment. For example: `aws-sdk` automatically uses an authentication token that already exists on the EC2/Lambda environment, and will not be provided at build time

**Comment by codinsonn** [comment]
Hi @EvanBacon 👋 Could it be that `@expo/next-adapter` still rewrites publicly exposed env vars (prefixed with `NEXT_PUBLIC_` as recommended by the next docs [here](https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser))?

They do seem to be available server side now, but once hydrated by next, not even env vars with `NEXT_PUBLIC_` are available it seems.

Could you have a look?

**Comment by bombillazo** [comment]
Hey, I stumbled on this trying to get expo-constants to work wiht Next.js.

How should I set up my next.config/js file so that Next can source the variables set in the `extra` section of the app.config.js using process.env.
