### ISSUE TITLE
[Electron] Electron build doesn't reset after saving / Editing App 

### ISSUE THREAD

**Issue by kaiyes** [expo/expo-cli#2160]
## Description
Electron build doesn't reset after saving /editing anything in the react native app. Say you change a text in your react native app, electron build goes blank and shows this. 
   
![Screenshot 2020-05-23 at 12 34 21 AM](https://user-images.githubusercontent.com/5293742/82698804-4f1f6200-9c8d-11ea-89e7-f2a9e5a6aee5.png)

#### Expected Behaviour
Basically I would want to see app reset and changes to the electron render. 

##### What action did you perform, and what did you expect to happen?

Editing anything and saving gives the above blank screen in electron render.

###### Please run `expo diagnostics` in the project folder and copy the output here:

  Expo CLI 3.20.9 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.13.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.9 => 0.12.9
      expo: ~37.0.9 => 37.0.12
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.20.9

## Reproducible Demo

1. init a fresh expo app with tab navigator 
2. Do the necessary electron related stuff as per expo documentation 
https://docs.expo.io/guides/using-electron/
3. change anything basic in the app and you should get this error message

**Comment by kaiyes** [comment]
Stopped using electron and opted for react-native-macos from microsoft. Builds beautifully in the tray.

https://twitter.com/Kaiyes_Ansary/status/1264627081305927680

**Comment by Jonatthu** [comment]
@kaiyes  how do you use it with expo?

**Comment by kaiyes** [comment]
https://twitter.com/FernandoTheRojo/status/1264020579734126592

**Comment by Jonatthu** [comment]
I mean how did you set up your project structure in order to support react native for mac using expo?

**Comment by kaiyes** [comment]
@Jonatthu  followed that tutorial in the tweet !

**Comment by kaiyes** [comment]
@Jonatthu  this is how ! 🤓  
https://twitter.com/Kaiyes_Ansary/status/1263728861541359616

**Comment by dwisk** [comment]
I was able to solve the issue with setting `devServer.historyApiFallback` to `true`.

If not already happened reveal the main process with:
```bash
yarn expo-electron customize
```

Then edit `electron/webpack.config.js` like this:
```
const { withExpoWebpack } = require('@expo/electron-adapter');

module.exports = config => {
  const conf = withExpoWebpack(config);
  conf.devServer.historyApiFallback = true;
  return conf;
};
```

Now hot-reload or manually reloading the Electron-App shows the App again.

**Comment by nandorojo** [comment]
> I mean how did you set up your project structure in order to support react native for mac using expo? @kaiyes

https://github.com/nandorojo/expo-electron-copy-magic
