### ISSUE TITLE
Deprecate JSON5 config support in favor of app.config.js/ts

### ISSUE THREAD

**Issue by fson** [expo/expo-cli#2169]
We've previously supported JSON5 syntax in `app.json`. Possibly the most important feature is that it allows comments. However, you can now add comments by switching to `app.config.js` or `app.config.ts` instead.

Also the file extension was always `.json` (not `.json5`), meaning that some 3rd party tools like editors may not have formatted the source correctly, when using JSON5.

To limit the number different config formats, I believe we should remove JSON5 support in `app.json`. `app.json` can still coexist with JS or TS config. Its strong point is being in JSON, which makes it widely interoperable and machine readable/writable (particularly when it's not JSON5).

**Comment by fson** [comment]
@brentvatne @EvanBacon any thoughts on this?

**Comment by brentvatne** [comment]
i'm ok with deprecating this, it just seems like lots of work to do it well and i'm not sure there's much of a benefit to it

**Comment by EvanBacon** [comment]
I think it’s not very inconvenient to keep it around. Json file does a pretty good job handling all of the complexity.
