### ISSUE TITLE
Expo export failing when src has images 

### ISSUE THREAD

**Issue by AlefiyaG** [expo/expo-cli#2179]
I am trying to use expo-updates and expo-assets in my react-native app so that we can use the self hosting OTA capability. 
When running the command expo-export i am getting the following error: 

expo export --public-url https://raw.githubusercontent.com/xxxx/xxxx

I would expect this to work smoothly.

## Observed Behavior

```
Found an existing Expo CLI instance running for this project but the target did not match.
› Closing Expo server
› Stopping Metro bundler
Starting a new Expo CLI instance...
Exporting your app...
Warning: Problem validating app.json: Unable to perform cache refresh for /Users/xxx/.expo/cache/schema-37.0.0.json: Error: Request failed with status code 400.
Starting Metro Bundler on port 19003.
Building iOS bundle
Building Android bundle
Finished building JavaScript bundle in 1800ms.
Finished building JavaScript bundle in 1188ms.
Finished saving JS Bundles.
Analyzing assets
Finished building JavaScript bundle in 1020ms.
Finished building JavaScript bundle in 968ms.
Warning: Unable to resolve manifest assets. Icons might not work. Unable to perform cache refresh for /Users/f058391/.expo/cache/schema-37.0.0.json: Error: Request failed with status code 400.
Resolving assets failed.
Error: Resolving assets failed.
    at _resolveManifestAssets (/@expo/xdl@57.9.1/src/Project.ts:349:13)

```

Expo CLI 3.20.1 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.3/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.8 => 37.0.8 
      react: 16.11.0 => 16.11.0 
      react-native: 0.62.2 => 0.62.2 
    npmGlobalPackages:
      expo-cli: 3.20.1

Also specify:

- Phone/emulator/simulator platform, model and version:

 -->

## Reproducible Demo

Could you please look into the issue. I am new to expo so would need some help here.

**Comment by byCedric** [comment]
Hi @AlefiyaG! Using assets in your `src` folder should work without issues. I'm using a similar approach in [this app](https://github.com/byCedric/Hue-P/blob/master/app.json#L23). Could you share some more info on your project, or even the project itself? That would give us more context on why this is happening for you 😄 

Hope it helps!

**Comment by AlefiyaG** [comment]
Hi Cedric,
Thanks for the response. Sorry i should have updated earlier. The issues was caused due to my vpn and proxy. Once disconnected it worked fine. 

Regards
Alefiya

**Comment by byCedric** [comment]
Awesome, no worries. Glad you figured it out 😄
