### ISSUE TITLE
Can't set webhooks for project using expo-cli

### ISSUE THREAD

**Issue by hyperion0201** [expo/expo-cli#2180]
## Description
I'm trying to set a webhook for my expo project.
I'm getting below error:
```
ApiV2Error: Failed to set webhook for experience: @hyperion0201/demo-expo.                                                        
Unable to set webhook and secret for this project.                                                                                
Error: Unable to set webhook and secret for this project.                                                                         
    at /home/hyperion0201/.config/yarn/global/node_modules/expo-cli/src/commands/webhooks.ts:35:15                 
    at processTicksAndRejections (internal/process/task_queues.js:97:5)   
```

## Environment

```
Expo CLI 3.20.9 environment info:
System:
OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
Shell: 5.8 - /usr/bin/zsh
Binaries:
   Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
   Yarn: 1.22.4 - /usr/bin/yarn
   npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm

```

**Comment by jkhales** [comment]
Looking into this now.

**Comment by jkhales** [comment]
Did you publish this app with `expo publish`? 
You need to have a published project in order to set a webhook.
We are working on a better error message right now.

**Comment by hyperion0201** [comment]
Sorry for late reply. I hosted my project followed by this [guide](https://docs.expo.io/distribution/hosting-your-app/). Do i need to run ```expo publish``` too?

**Comment by jkhales** [comment]
> Sorry for late reply. I hosted my project in a private repo, followed by this [guide].(https://docs.expo.io/distribution/hosting-your-app/). I don't how to publish this.

Hi, webhooks are triggered when a build on expo servers completes. In order to create a build on expo servers, you need to `expo publish` the app to our servers.

So as long as you self host your project, webhooks etc. are not available for you.

Closing issue for now, if you are interested in understanding this further, perhaps post in here: https://forums.expo.io/
