### ISSUE TITLE
Unable to install @expo modules for fresh expo init project

### ISSUE THREAD

**Issue by avinashlng1080** [expo/expo-cli#2182]
## Description

I just did a fresh expo init --npm and unfortunately, not all of the modules under node_modules got installed.  I get the following error : 

```
 _ENOENT: no such file or directory, node_modules/@expo/configure-splash-screen/bin/configure.js'
npm ERR! enoent This is related to npm not being able to find a file._
```

## Expected Behavior
All modules should installed successfully.

## Observed Behavior
Unable to complete npm install on the project because of the above error.

## Environment

 ```
Expo CLI 3.21.1 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.15.0 - /usr/local/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.12 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.21.1
```

## Reproducible Demo
I am able to reproduce this error with each new project init using expo 3.21.1

**Comment by brentvatne** [comment]
could you try `npm cache clean --force` and re-initializing a project? npm can be pretty unreliable when it comes to caching sometimes

**Comment by brentvatne** [comment]
tried it locally and worked as expected:

```
╭─~/code
╰─$ expo init tryrepro --npm
? Choose a template: expo-template-blank
✔ Downloaded and extracted project files.
✔ Installed JavaScript dependencies.

✅ Your project is ready!

To run your project, navigate to the directory and run one of the following npm commands.

- cd tryrepro
- npm start # you can open iOS, Android, or web from here, or run them directly with the commands below.
- npm run android
- npm run ios
- npm run web
╭─~/code
╰─$ cd tryrepro
╭─~/code/tryrepro ‹master›
╰─$ expo start
Starting project at /Users/brentvatne/code/tryrepro
Expo DevTools is running at http://localhost:19003
Press d to open DevTools now, or shift-d to always open it automatically.
Starting Metro Bundler on port 19005.

  exp://192.168.1.73:19004

etc ...
```

**Comment by avinashlng1080** [comment]
[2020-05-26T18_48_38_085Z-debug.log](https://github.com/expo/expo-cli/files/4684383/2020-05-26T18_48_38_085Z-debug.log)

I tried it and I am still getting the error as per the debug log.

**Comment by brentvatne** [comment]
does init with yarn work for you?

**Comment by brentvatne** [comment]
looks like this is a common issue with your npm version, eg: https://github.com/microsoft/azure-pipelines-tasks/issues/12195

try upgrading npm - `npm i -g npm`

**Comment by avinashlng1080** [comment]
no - it failed and I get the error 
[yarn-error.log](https://github.com/expo/expo-cli/files/4684400/yarn-error.log)

**Comment by brentvatne** [comment]
are you using some custom registry?

`Error: //registry.npmjs.org/expo: Invalid URI "//registry.npmjs.org/expo"`

this is not an expected error

**Comment by avinashlng1080** [comment]
@brentvatne  No I'm not using a custom registry - this is from the expo init log.

I also updated my NPM version to 6.14.5 and it is not working also doing the force clean.

**Comment by brentvatne** [comment]
there are tens of thousands of people using the software without this issue so there is something going on with the machine you're using :) can you run `npm config list`?

**Comment by brentvatne** [comment]
here is an issue related to what you're seeing: https://discuss.erpnext.com/t/invalid-uri-http-registry-npmjs-org-showdown/55408

the user was able to fix it by running `npm config set registry https://registry.npmjs.org `

**Comment by avinashlng1080** [comment]
Sure.  Here is the log: 

```
Avinash:fh avinashlingaloo$ npm config list
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.14.5 node/v12.15.0 darwin x64"

; node bin location = /usr/local/bin/node
; cwd = /Users/avinashlingaloo/Desktop/ex/fh
; HOME = /Users/avinashlingaloo
; "npm config ls -l" to show all defaults.
```

**Comment by brentvatne** [comment]
is there any chance you're behind a proxy or something that could be interfering with your connection to the npm registry?

**Comment by avinashlng1080** [comment]
I'm on mac os catalina v10.15.4.

Maybe something there is blocking it.  I will dig in this direction and revert if I find anything.

Thanks for your help @brentvatne

**Comment by brentvatne** [comment]
let me know what you find out @avinashlng1080!

**Comment by avinashlng1080** [comment]
No luck.  nothing is preventing it from acccessing NPM.

I can use yarn & npm on my other projects.

It's only this @expo package that is not downloading and hence the following js file is not found during installation.
node_modules/@expo/configure-splash-screen/bin/configure.js

**Comment by gaetan-petit** [comment]
I can confirm the exact same thing is happening to me righ now.
Tried clearing npm cache, reinstall expo-cli, init a new project with Tabs template.

**Comment by kendall0013** [comment]
I've been receiving this as well. Tried the previous suggestions of updating my npm version, clearing the npm cache and double-checking the config registry. 

I was able to get past it by installing the 0.1.7 version (0.1.8 is newest) of @expo/configure-splash-screen and then installing expo-splash-screen again. When trying to install the newest @expo/configure-splash-screen, I got the following message indicating expo-splash-screen is a required peer but isn't installed: 

> npm WARN @expo/configure-splash-screen@0.1.8 requires a peer of expo-splash-screen@* but none is installed. You must install peer dependencies yourself.

When I attempted to then install expo-splash-screen for the peer dependency I got an error indicating it couldn't find the configure-splash-screen\bin\configure.js file which of course doesn't exist because @expo/configure-splash-screen can't be installed without the other already installed.

> npm ERR! code ENOENT
> npm ERR! syscall chmod
> npm ERR! path \node_modules\@expo\configure-splash-screen\bin\configure.js    
> npm ERR! errno -4058
> npm ERR! enoent ENOENT: no such file or directory, chmod \node_modules\@expo\configure-splash-screen\bin\configure.js'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent

**Workaround:**
```
npm install @expo/configure-splash-screen@0.1.7
npm install expo-splash-screen
```

**Environment Info:**
> Expo CLI 3.21.1 environment info:
>     System:
>       OS: Windows 10 10.0.18362
>     Binaries:
>       Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
>       npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
>     IDEs:
>       Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
>     npmPackages:
>       expo: ~37.0.9 => 37.0.12
>       react: ~16.9.0 => 16.9.0
>       react-dom: ~16.9.0 => 16.9.0
>       react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
>       react-native-web: ~0.11.7 => 0.11.7

**Comment by brentvatne** [comment]
i've reverted `@expo/configure-splash-screen@0.1.7` to the latest version, does that help for you?

unsure why this would be happening though. npm does seem to have been having a variety of issues today such as delays in publishing packages and now npm stats not showing up on npm package pages..

**Comment by gaetan-petit** [comment]
@brentvatne I think the same. I'm still new to this, but I tried to init a project with the --yarn parameter and installation complete without an error.

**Comment by kendall0013** [comment]
@brentvatne Definitely working for me out of the box after the reversion to 0.1.7
