### ISSUE TITLE
exp build:ios doesn't allow blank p12 passwords

### ISSUE THREAD

**Issue by SBIWebteam** [expo/expo-cli#219]
## Description

When `expo-cli` prompts me for the password to my distribution certificate, which is blank, I cannot continue. It does not appear to allow a blank entry.

## Expected Behavior

I expect to be able to enter a blank password for my distribution certificate, as this is a valid option during the creation of said certificate.

## Observed Behavior

When I press enter without entering anything when prompted for the distribution certificate P12 file's password, `expo-cli` does not respond.

**Comment by jakubste** [comment]
We want to encourage Expo users to safe habits, so I don't think it's a wrong behaviour. Additionally, it looks like it could generate new problems (see: https://github.com/fastlane/fastlane/issues/2814).

**Comment by SBIWebteam** [comment]
Gotcha, thanks for the response.
