### ISSUE TITLE
Feature (& PR offer) - dependency update script

### ISSUE THREAD

**Issue by actuallymentor** [expo/expo-cli#2221]
## Description

Running `expo install` installs a compatible dependency version. Right now I rely on [ncu](https://www.npmjs.com/package/npm-check-updates) to check for dependency updates, but that does not take into account expo-compatible updates.

Ideally we would add an `expo update` command that runs `expo install` for every line in the `package.json` dependency trees.

Optionally we can add an exclusion `-x` marker to skip certain packages.

## PR offer

I'm happy to write the code for this. If this is a desirable feature let me know and I'll take some time for it.

**Comment by brentvatne** [comment]
hey @actuallymentor! thank for you the issue.

currently `expo upgrade` handles this, so we could reuse some code from there. i think what we may want is something like `expo install --fix`. i'm afraid that `update` will clash too much with `upgrade`

if you want to work on that it would be great. sorry for not getting back to you until now!

**Comment by actuallymentor** [comment]
Thanks for the response!

Could we do something in `expo-cli/packages/expo-cli/src/commands/upgrade.ts` like:

1. `if( currentSdkVersionString == latestSdkVersion.version && process.argv.includes( '--dependencies' ) )`
2. Skip SDK code part of `upgradeAsync`
3. Update the relevant end-log entries (e.g. "updated SDK" etc)
4. Leave the rest of the script as is

That would allow for the relatively intuitive `expo upgrade --dependencies`.

**Comment by actuallymentor** [comment]
Shall I draft a PR?

![johntravolta](https://user-images.githubusercontent.com/9071382/89023506-f66ee400-d323-11ea-8758-ea47b7136680.gif)

**Comment by brentvatne** [comment]
hello! i think i lost this in my sea of github notifications. usually the best way to move something forward is to just open a pr and discuss there.

i would rather this functionality live on install than upgrade. a common use case here is if you run `npm install` and get the wrong version of a package, then we can just tell people to run `expo install --some-flag` to ensure all of their dependencies are compatible with the sdk version.

so, something like `expo install --fix` or `expo install --fix-sdk-dependencies` or `expo install:sync-sdk-dependencies` would be a good fit for this

**Comment by EvanBacon** [comment]
I think this is better suited for `expo doctor`

**Comment by brentvatne** [comment]
@EvanBacon - maybe `expo doctor --fix-dependencies`?
