### ISSUE TITLE
[cli] list/checkboxes broken with multiline choices

### ISSUE THREAD

**Issue by quinlanj** [expo/expo-cli#2224]
# problem
inquirer breaks with a long multiline list. This is affecting users especially with credential related actions. here is a gif scrolling through a list with 200 multiline options - notice there are no cursors and it skips a huge chunk of choices.

![ezgif-6-95afd84c78d2](https://user-images.githubusercontent.com/6380927/83701709-67617c00-a5bf-11ea-9733-6741bd19cbe4.gif)

# todo

- [ ] bump inquirer once https://github.com/SBoudrias/Inquirer.js/pull/928 lands and is published

**Comment by EvanBacon** [comment]
We no longer use inquirer for this.
