### ISSUE TITLE
App icon cannot have transparency

### ISSUE THREAD

**Issue by jonsamp** [expo/expo-cli#2225]
# Description

When building with `expo build:ios`, I got this error message:

"Your application icon can't have transparency if you wish to upload your app to Apple Store."

## Expected Behavior

It would be great to suggest a solution or to automatically fix this. I ended up using [this tool](https://github.com/bpolat/Alpha-Channel-Remover). At the very least it might be helpful to link to this tool or to explain that the image must be re-exported without transparency.

## Reproducible Demo

This icon has transparency and should create this error:

![example](https://user-images.githubusercontent.com/6455018/83705843-fb453f00-a5e3-11ea-9ca5-e31fdbc25369.png)

**Comment by brentvatne** [comment]
i'd love to see someone contribute an improvement for this!
