### ISSUE TITLE
Asset referenced in html file doesn't get published

### ISSUE THREAD

**Issue by drager** [expo/expo-cli#2226]
Hey, when I reference a file in a html file that's supposed to be used together with `react-native-webview` it doesn't get published when running `expo publish`. 

Reproducible example: https://github.com/drager/webview-example and if you `expo publish` that and debug the published app via Safari you will notice that it's not able to find the "webviewjs" file:

![bild](https://user-images.githubusercontent.com/1957563/83724225-2cebf380-a640-11ea-9264-2f970d3c4af5.png)

**Comment by brentvatne** [comment]
i'm not sure this is something that we can feasibly fix - we would have to parse html files to find script tags that refer to local paths, then append those to the asset registry. i don't think we actually want to do this.

another thing we could do potentially is add another app.json field for listing assets that you would like to include in your app but that live outside of the react-native asset registry. this probably isn't something we are going to do anytime soon, but if you'd like to start a discussion around it this would be a good spot: https://github.com/expo/expo/discussions

for now, it would be best to write a good guide around bundling html and its related assets for webviews
