### ISSUE TITLE
show a confirmation for sign out instead of immediately signing out

### ISSUE THREAD

**Issue by mojtabast** [expo/expo-cli#2229]
Most of the times I accidentally press `s` in terminal and I need to login again each time. 
some other tools like `nodemon` are using `rs` for restarting and this is doing two separate things in expo and it's possible to use it wrongly.

I understand maybe this is happening rarely for all users, but happening for occasionally.

**Comment by brentvatne** [comment]
i agree this is really annoying. @EvanBacon removed the sign out shortcut entirely in #2752, it'll go out in our next release
