### ISSUE TITLE
uri-scheme adding scheme in tvOS Info.plist in React Native

### ISSUE THREAD

**Issue by vikrantnegi** [expo/expo-cli#2235]
## Description
I'm using `uri-scheme` package to add URIs but when I'm using command `npx uri-scheme add mycoolredirect` it seems to update the Info.plist file of tvOS instead of the original project.

## Expected Behavior
It should update the the project's Info.plist file.

## Observed Behavior
1. Run `npx uri-scheme add mycoolredirect` comand in the React Native project
2. Run `npx uri-scheme list` to view the URI schemes

![Screen Shot 2020-06-05 at 10 19 07](https://user-images.githubusercontent.com/3294287/83838153-0d26ff00-a716-11ea-8ff1-28b19ba54ed7.png)

## Environment
- React Native CLI with uni modules installed with following dependencies
```
"expo-auth-session": "^1.2.1",
"react": "16.11.0",
"react-native": "0.62.2",
"react-native-unimodules": "^0.9.1"
```

```
Expo CLI 3.21.3 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      react: 16.11.0 => 16.11.0 
      react-native: 0.62.2 => 0.62.2 
    npmGlobalPackages:
      expo-cli: 3.21.3
```

## Reproducible Demo
Find the repo here with [issue/uri-scheme](https://github.com/vikrantnegi/RN-auth-session/tree/issue/uri-scheme) branch

**Comment by EvanBacon** [comment]
You can use the `--info-path` to select which plist to use. Unfortunately it's pretty hard to predict which `Info.plist` is the "intended" plist so I added the `--info-path` flag.

**Comment by vikrantnegi** [comment]
@EvanBacon I understood it now. 
Is there any way to make it defaults to the project's Info.plist instead of tv-OS?  I think majority of developer won't be developing tv-OS anyway so I think it would be helpful to make decent default.

**Comment by amhinson** [comment]
Running into this as well. I'm up for submitting a PR, but what would be an ideal solution here? 

It seems like purely just checking the target name (i.e. `Demo`, `Demo-tvOS`, `DemoTests`) wouldn't be reliable because the suffix could technically be changed to anything.

Perhaps we could present an option to select which file to append the URI scheme to? It looks like we'd also need to show all of the files and their schemes from the `list` command as well.

**Comment by brentvatne** [comment]
hey all! we don't have bandwidth right now to be proactively working on this but if you'd like to open a PR with a proposal for how to handle it better we can have a look!
