### ISSUE TITLE
Expo Start is not working.

### ISSUE THREAD

**Issue by gayankasun** [expo/expo-cli#2238]
I' m getting this error when run expo start.
my dev configurations are....
npm 6.14.5
node 14.3.0
expo 3.21.3
windows 10

![Capture](https://user-images.githubusercontent.com/5936088/83950663-15805680-a84a-11ea-938a-01dbec067662.PNG)

can any one help me on this

**Comment by brentvatne** [comment]
hi there! looks like nobody got back to you on this, it seems everyone missed it. if you are still having the issue, can you run `expo diagnostics` and paste the output here? thanks, closing until we hear back

**Comment by gayankasun** [comment]
I have fixed the issue. the reason was the win32 path was not there for execute node in environment variables. once set the path it worked. cheers

![Capture](https://user-images.githubusercontent.com/5936088/87646513-95181400-c76c-11ea-8c2a-97e7642c307d.PNG)
