### ISSUE TITLE
Check that key alias exists in key store before upload

### ISSUE THREAD

**Issue by LinusU** [expo/expo-cli#2239]
## Description

I recently had a build failing because of a typo in the key alias name (`--keystore-alias`). In the investigation to see what went wrong I realised that it's quite easy to check up front if a key with that alias exists. An early error would have saved me a lot of time, and would have put one less project in the build queue 🙂 

## Expected Behavior

I expected an error:

```text
The specified Keystore "foobar.keystore" has no key with the given alias "foo".
```

## Observed Behavior

```text
✖ Build failed.
[16:29:51] Standalone build failed!
```

## Environment

```text
  Expo CLI 3.21.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.0.0 - /usr/local/bin/node
      Yarn: 1.22.4 - node_modules/.bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.12 => 37.0.12 
      react: 16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
      react-native-web: ^0.11.7 => 0.11.7 
```

## Reproducible Demo

n/a

-----

This could be implemented something like this:

```js
const aliases = child_process.spawnSync('keytool', ['-v', '-list', '-keystore', keystorePath, '-storepass', password])
  .stdout
  .toString()
  .split('\n')
  .filter(line => line.startsWith('Alias name: '))
  .map(line => line.replace('Alias name: ', ''))

// ...

aliases.includes(keystoreAlias.toLowerCase())
```

**Comment by EvanBacon** [comment]
This appears to be resolved with EAS Build. If you encounter this issue in the future, please open an issue on [expo/eas-cli](https://github.com/expo/eas-cli/issues/new/choose).

**Comment by AndreaUnige** [comment]
Hi,
got a similar problem here.

When I build the App with command

`eas build --platform android`

I get this very obscure error

`Build failed: The alias specified for this keystore does not exist. Make sure you specified the correct value.
`
How did you solve ? I check my keystore with the command

`eas credentials`

and it seems it is there, alias inlcuded.
Any help ?

Thanks!
