### ISSUE TITLE
Cannot start my Expo due to 'Metro Bundler process exited with code 1'

### ISSUE THREAD

**Issue by anavathe** [expo/expo-cli#2255]
## Description

I ran `npm start` in both node.js and my git shell. It was working fine when I was last working on my side project in April but found there to be an error today.

## Expected Behavior

I would expect to be able to see a new browser tab pop up with a QR code for me to scan on my client Expo app, so that I may get some live reloading and my app would run within the Expo container. 

I did a `npm install -g expo-cli` and tried to reproduce and got the same error so I am wondering what changed in a month.

## Observed Behavior

It briefly opened the QR code page for me to scan from my Expo mobile app, but then the page blanked out, and in the command prompt, I saw the following error:

```
Opening DevTools in the browser... (press shift-d to disable)
internal/modules/cjs
Metro Bundler process exited with code 1
Error: Metro Bundler process exited with code 1
    at ChildProcess.packagerProcess.once (C:\@expo\xdl@57.9.13\src\Project.ts:1870:16)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! FamilyFeudFrontend@0.1.0 start: `expo start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the FamilyFeudFrontend@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

## Environment

  Expo CLI 3.21.5 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 10.16.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^36.0.0 => 36.0.2
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4
      react-navigation: ^4.0.10 => 4.0.10

## Reproducible Demo
![image](https://user-images.githubusercontent.com/16593963/84574802-d9735700-ad5d-11ea-9cf3-e8750a60682b.png)

**Comment by brentvatne** [comment]
hi there! sorry you didn't get a response on this. is this still happening in the latest version of expo-cli?

**Comment by brentvatne** [comment]
closing until we get a response, hope all is well :)

**Comment by anavathe** [comment]
Thank @brentvatne! Won't reopen, it looks to be doing OK for now...

**Comment by arahman0715** [comment]
I am getting the issue again and again

**Comment by RONAKDHOLARIYA** [comment]
me too getting same error in expo sdk 39.0.2 version please reopen issue.

**Comment by umairahmed88** [comment]
try this one
1. rm -r node_modules

2. rm package-lock.json

3. expo upgrade

4. npm start -c
