### ISSUE TITLE
[Bug] Incorrect mapping of a React Native version to an Expo SDK version

### ISSUE THREAD

**Issue by RedMickey** [expo/expo-cli#2257]
Hello,
I am a maintainer of [React Native Tools](https://github.com/microsoft/vscode-react-native) VS Code extension. The extension is used for debugging React Native (including Expo) applications.

## [Bug] Incorrect mapping of a React Native version to an Expo SDK version
We use [`facebookReactNativeVersionToExpoVersionAsync`](https://github.com/expo/expo-cli/blob/master/packages/xdl/src/Versions.ts#L196-L219) function to get appropriate Expo SDK version and add it to `app.json` file. 
This function worked fine until Expo added new SDK v38 to Expo SDK versions. 
We investigated how this function works and found out that after [`chore: clean up lodash usage (#2170)`](https://github.com/expo/expo-cli/commit/6e8fbc4dec5c49eab347f9a0b5f7c4005b09356c) commit its behavior has been changed a bit.
It seems that now the original `facebookReactNativeVersion` parameter passed to the function is overlaped in [this loop](https://github.com/expo/expo-cli/blob/master/packages/xdl/src/Versions.ts#L209-L217) by internal `facebookReactNativeVersion` variable. Therefore in each iteration we compare the `facebookReactNativeVersion` parameter with itself. 

![image](https://user-images.githubusercontent.com/33267199/84643523-a1f3de80-af06-11ea-9886-64fea4ed7bfc.png)
![image](https://user-images.githubusercontent.com/33267199/84643554-acae7380-af06-11ea-95f5-f2c6b70cc80d.png)

## Expected Behavior

For example we pass `facebookReactNativeVersion` equals to  `0.61.4` to this function . We expect to get Expo SDK 37 version.

## Observed Behavior

But `facebookReactNativeVersionToExpoVersionAsync` function returnes Expo SDK 38 version.

![image](https://user-images.githubusercontent.com/33267199/84644237-96ed7e00-af07-11ea-9269-d96fbf9d3257.png)

It seems that all iterations are performed in the loop and we get the version of the newest SDK (38). I suppose that we haven't faced this problem earlier since Expo SDK 37 was the latest version.

## Environment
System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 15.94 GB
  Binaries:
    Node: 12.14.1
    Yarn: 1.17.3
    npm: 6.13.4
  SDKs:
  Expo-CLI: 3.21.5
  Expo: 37.0.9
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 27.0.3, 28.0.2, 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897

**Comment by wschurman** [comment]
This may have been fixed by https://github.com/expo/expo-cli/pull/2396#discussion_r460323875

**Comment by RedMickey** [comment]
@wschurman, thank you, now it works correctly.
