### ISSUE TITLE
Expo Publish issue

### ISSUE THREAD

**Issue by santhoshdasari786** [expo/expo-cli#2259]
## Description

when i use expo publish getting error. this was working fine just 3-4 days back. dougting npm clean did some thing wrong but as per package.json in place it work as expected.
Expo start is working as usual and was able to use it.

## Expected Behavior

Expo publish had been executed but failed to publish

## Observed Behavior

IosWorkspace(...).getPaths is not a function
[18:01:56] TypeError: IosWorkspace(...).getPaths is not a function
    at _maybeConfigureExpoKitEmbeddedAssetsAsync (C:\@expo\xdl@57.8.28\src\EmbeddedAssets.ts:201:48)
    at Object.configureAsync (C:\@expo\xdl@57.8.28\src\EmbeddedAssets.ts:35:9)
    at process._tickCallback (internal/process/next_tick.js:68:7) block: 

```
IosWorkspace(...).getPaths is not a function
```

## Environment

 Expo CLI 3.18.6 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
    npmPackages:
      expo: ^36.0.0 => 36.0.2
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4
      react-navigation: ^4.0.10 => 4.0.10

Also specify:

Not required as this is publish issue

## Reproducible Demo

Expo publish

**Comment by brentvatne** [comment]
is this a bare project? expokit project?

**Comment by fson** [comment]
Please upgrade to the latest Expo CLI version, 3.18.6 was released in April and at the time of writing this, the latest version is 3.21.13.

You can upgrade with `npm i -g expo-cli`.

**Comment by brentvatne** [comment]
closing, will reopen if the same issue occurs on the latest version of expo-cli. let me know.
