### ISSUE TITLE
xde and exp start connecting to wrong ip address with Ethernet network

### ISSUE THREAD

**Issue by moahammadalt** [expo/expo-cli#226]
I am having a problem with running expo project showing this error "Packager is not running at http://192.168.42.6:19001 ".

 I am using windows 10 and android emulator.

I tried all these solutions:
**Assigning interface matric (priority) for your Wifi Adapter**
**Setting REACT_NATIVE_PACKAGER_HOSTNAME**
**Behind a NAT, add port redirects for firewall**
**Disable VirtualBox since Expo is taking the IP address of VirtualBox**

xde even exp start --lan is still connecting to a wrong IP address "exp://192.168.42.6:19000" which I don't have it at all, also I tried to connect from wifi network but still the same problem

I set react native packager like this:
`setx REACT_NATIVE_PACKAGER_HOSTNAME 192.168.42.124 /M`

> C:\Users\XWorker_02>ipconfig
>Windows IP Configuration
>
>Ethernet adapter Ethernet 2:
>
 >  Connection-specific DNS Suffix  . : localdomain
 >  Link-local IPv6 Address . . . . . : fe80::119e:d39:fbfb:d84e%16
 >  IPv4 Address. . . . . . . . . . . : 192.168.42.113
  > Subnet Mask . . . . . . . . . . . : 255.255.255.0
  > Default Gateway . . . . . . . . . : 192.168.42.1
>
>Wireless LAN adapter Wi-Fi:
>
 >  Media State . . . . . . . . . . . : Media disconnected
 > Connection-specific DNS Suffix  . : localdomain
>
>Wireless LAN adapter Yerel Ağ Bağlantısı* 10:
>
 >  Media State . . . . . . . . . . . : Media disconnected
  > Connection-specific DNS Suffix  . :
>
>Wireless LAN adapter Yerel Ağ Bağlantısı* 1:
>
  > Media State . . . . . . . . . . . : Media disconnected
  > Connection-specific DNS Suffix  . :
>
>Ethernet adapter Bluetooth Ağ Bağlantısı 2:
>
>  Media State . . . . . . . . . . . : Media disconnected
>  Connection-specific DNS Suffix  . :

i started to lose my hope so please any help!!

**Comment by fson** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen, if you still encounter this issue in the latest version of Expo CLI.

**Comment by spinus** [comment]
`export REACT_NATIVE_PACKAGER_HOSTNAME=$(ip route get 1.1.1.1 | awk '{print $7}')`
