### ISSUE TITLE
expo build fails to build the bundles without issuing expo start first

### ISSUE THREAD

**Issue by CostachescuCristinel** [expo/expo-cli#2263]
## Description
It happens multiple times that, when I start a build, expo fails to build the bundles, if I don't run `expo start` first. Mostly, this happens with ios builds, but rarely Android builds fail similarly.
I have to mention that I usually make ios builds with the -c flag, just so I am able to change the ios provisioning profile between an AppStore and an Ad-Hoc one for the same app.

## Expected Behavior
Bundles should build, and a build instance should be started.

## Observed Behavior
expo-cli fails to proceed, throwing the following error:

```
$ expo build:ios
...
Publishing to channel 'default'...
Building iOS bundle
connect ECONNREFUSED 127.0.0.1:19001
Error: connect ECONNREFUSED 127.0.0.1:19001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
```
The issue, I think, has something to do with detecting an Expo server / Metro bundler instance running on the system, so it can be stopped before proceding further. After running expo start (with or without -c), and closing the instance with CTRL+C, the build command works just fine.

## Environment
```
Expo CLI 3.21.5 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.17.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.12 => 37.0.12 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ~0.11.7 => 0.11.7
```

## Reproducible Demo
N.A.

**Comment by iamgovindthakur** [comment]
### Hello @CostachescuCristinel  The below steps just work fine for me and i was able to build the bundle so what's you have to do is that

step.1  open your editor i am using vs code and run the **NPM SCRIPTS** in terminal `expo start` , and then
step.2 open command prompt in the same project directory and try `expo build:android -t app-bundle` or diff if you want for iOS
after that you will able to build the bundle or application.still if you have doubt you can ask me.
i have attached the screenshot you can easily understand from that.
you can thanx me if this work for you.

![Screenshot (140)](https://user-images.githubusercontent.com/32303373/86780003-dc6e1880-c079-11ea-8798-62d1e03e018e.png)

**Comment by CostachescuCristinel** [comment]
> ### Hello @CostachescuCristinel The below steps just work fine for me and i was able to build the bundle so what's you have to do is that

Hi, thank you for your reply, but the problem isn't that I am unable to build at all.
The issue is that, only sometimes, `expo build:xxx` will fail to start the build with the error that I have reported in my initial post (`ECONNREFUSED`). When this happens, it is enough for me to run the command `expo start` (with or without the `-c` flag), then stop the instance, and run the `expo build:xxx` command again - and it will run correctly.

I haven't been able to really figure out the circumstances that cause this issue. It may be related to the Metro bundler instances (since it tries to run on localhost). My suspect is that expo is trying to kill any running instances of the app to build, before starting the build, but somehow it fails - or maybe it is actually trying to _start_ an instance instead, I'm not sure.

This is not much of an issue for me. As I said, running `expo start` before `expo build:xxx` fixes it - and it's more of an annoyance at this point. If it would be fixed, that would be great; but personally I can live with it not being fixed too.
I am not sure however how this affects any automatization / build scripts that others may use, it may be more of an issue to them.

**Comment by EvanBacon** [comment]
This should be fixed in SDK 40, you can use the new dev server now with `EXPO_USE_DEV_SERVER=true`.
