### ISSUE TITLE
Feature request: please fix the problematic expo build:ios -c procedure

### ISSUE THREAD

**Issue by CostachescuCristinel** [expo/expo-cli#2264]
## Description
I have many issues with the expo command build:ios -c.
1) Why does the command `expo build:ios -c` have the answer "Y" as default for their questions? The build -c command is a destructive command, and it's very easy to slightly press the Enter key twice and answer yes to a question that you'd rather answer no instead.
2) since a few versions now, the -c command will ask questions about clearing app certificates, keys ect. before signing in to the apple account. This means that, if you don't have access to the apple account that was set, you now cleared everything, and cannot build an app with the previously used certificates, keys, ect. Why? Please move the clearing questions back after signing in to apple's account. You can't even do much without signing in to an apple account (like creating a new distribution certificate, or key), so the current behavior doesn't actually make sense.
3) The build:ios -c command assumes that you want to build appstore builds and will only suggest those; instead, most of the builds I make (and I think I can assume that it's the same for other developers as well) are ad-hoc testing builds.
So, when it comes to selecting an app profile, expo would lovely suggest the AppStore profile in the apple account, but not the AdHoc profile. So I have to answer no to using the suggested profile, then answer that I want to upload a new profile, and then that I want to upload my own file instead of letting expo handle it. Can't this be done any better? For example, list the profiles available on the specified apple account and some extra options at the end:

```
1) AppStore profile (25 Mar 2020)
2) Ad-Hoc profile (23 Feb 2020)
3) Upload a new profile
4) Let Expo create a new profile
```

4) Again, on the improper behavior for ios app profiles: Why is it that switching the app profile requires me to issue the -c switch? This should be as simple as the build:android command where you are presented with the apk and appbundle options: can't expo ask which mobileprovision profile to use when I issue build:ios (without -c)? This should also prevent the issues described before in this list, and would be much appreciated.

5) Apple team: how likely is that you will want to switch the apple team used for an app, more than once or twice during development? Can't expo simply save the apple team preference for an app? I have mistakenly selected the wrong apple team (I have 4 in my account) in numerous builds, with not so nice consequences, and I have never understood why I was always asked this question. Can't you include this preference together with the certificates, keys, and profile settings? so if ever needed, expo build:ios -c would clear this preference and allow to choose a different team ?

So, please, fix the build:ios procedure to make it actually simple and meaningful to use. The current procedure is so frustrating and prone to user error, I hate it... I am sure many other developers feel the same...

**Comment by brentvatne** [comment]
hi there! we haven't optimized for your use case, unfortunately.

the current build workflow on ios is oriented towards doing release builds for distribution through testflight/app store, or doing simulator builds. i believe most expo users use these rather than ad-hoc builds, because we don't provide any guidance around creating and configuring an ad-hoc provisioning profile nor (as you noticed) any affordances for switching between app store and ad-hoc. the apk and app bundle options are quite different because the same credentials apply in both cases, even if in practice the result is that one can run easily on your device and the other is intended for the store.

it sounds like the main thing you are interested in is to be able to switch the provisioning profile easily between builds. this would indeed be useful. @quinlanj may have more thoughts on this. also cc @wkozyra95 as we will get to first-class support for ad-hoc builds soon enough.

**Comment by wkozyra95** [comment]
Hi, thanks for pointing this, as brent mentioned we didn't really plan to support anything like this. Most of the points you make could be answered that `--clear-credentials` flag is not intended to be used regularly, it's mostly there to set up credentials initially or when they expire.

We are currently working on a significant rewrite of infrastructure related to builds and credentials management. I think the workflow you described should be well supported when we finish, but I don't think we will want to add this to the current implementation.

For the current implementation, I think that better workaround for your workflow would be to setup second application with a different name and just switch `slug` in app.json, or if you don't want to modify file every time you can use `app.config.js` and modify slug based on env variable

**Comment by CostachescuCristinel** [comment]
First of all, thank you all for considering my request!

> Most of the points you make could be answered that `--clear-credentials` flag is not intended to be used regularly

I completely agree, this flag should be used so rarely that users should forget it exists unless they actually need to change credentials or certificates and other stuff connected to the app profile.
However, I still think that default answers to clearing credentials should be "No". Whether intentional or not, the clear credentials flag should prevent the user from doing damage, or even if only trying to change some of the credentials. The way I see it, after issuing the `expo build:ios -c` (same for android part as well), you should be able to safely exit the command by just pressing "Enter" at each step - and no changes should occur, unless you answer "Y" at any step.

> it sounds like the main thing you are interested in is to be able to switch the provisioning profile easily between builds

Switching app profiles for ios builds is part of my daily development process, and yes, I would love to have an easier way to do this.
However, please still consider the other points that I made. The way that I see it, the other big issue that I have with `build:ios -c` is that the process it follows is fundamentally flawed in design. As I commented right above, questions asked by this command (and the `build:android -c` counterpart) should have "No" as default answer for irreversible destructive actions. If I mistakenly answer "Yes" to the question asking if I want to remove the push notifications key, that is a way bigger deal than removing, say, the provisioning profile; I can restore the profile very easily by just downloading it from Apple and reuploading it in expo; the push notifications key however, once removed from the apple account, cannot be restored. And removing it will affect any other apps connected to the same key, including apps published on the store. With just a mispress of an Enter key, you could be forced to rebuild many apps in the same apple account, just so you can restore push notifications functionality.

I have faith that you can understand my concerns and you'll make a better process out of this. I'll keep an eye open for incoming support for ad-hoc builds, and in the meantime, I'll try to stay away from `-c` as much as possible.

**Comment by EvanBacon** [comment]
`expo build:ios` is now deprecated in favor of `eas build -p ios`
