### ISSUE TITLE
[Bug] Incorrect check of the packager port in the "setOptionsAsync" function 

### ISSUE THREAD

**Issue by RedMickey** [expo/expo-cli#2270]
Hello,
I am a maintainer of [React Native Tools](https://github.com/microsoft/vscode-react-native) VS Code extension. The extension is used for debugging React Native (including Expo) applications.

## Description

We use the [`setOptionsAsync`](https://github.com/expo/expo-cli/blob/master/packages/xdl/src/Project.ts#L2421-L2432) function from the `@expo/xdl` package. After the latest release of the `@expo/xdl` package ([`@expo/xdl@57.9.14`](https://www.npmjs.com/package/@expo/xdl/v/57.9.14)) we faced the problem with configuring of the packager port.
Now this function throws the error:
```
XDLError: packagerPort must be an integer
```

But we provide an integer packager port parameter.

![image](https://user-images.githubusercontent.com/33267199/84753475-b5b34980-afc7-11ea-899a-68e3b8192809.png)

It seems that [the condition for verification of the packager port](https://github.com/expo/expo-cli/blob/master/packages/xdl/src/Project.ts#L2428) is incorrect.

## Expected Behavior

I suppose that the condition for verification of the packager port could look something like this:
```
  if (options.packagerPort != null && !Number.isInteger(options.packagerPort)) {
    throw new XDLError('INVALID_OPTIONS', 'packagerPort must be an integer');
  }
```

This condition will be true if `packagerPort` isn't `null` and `packagerPort` isn't integer. So in such case the error should be thrown.

## Observed Behavior
This is the current condition, which was added in this commit [`chore: upgrade and partially remove deprecated joi package`](https://github.com/expo/expo-cli/commit/468fdf9a4d1ae04dabd07fd1ce5d0ab0f7fee6d4).

```
  if (options.packagerPort != null && Number.isInteger(options.packagerPort)) {
    throw new XDLError('INVALID_OPTIONS', 'packagerPort must be an integer');
  }
```

This condition will be true if `packagerPort` isn't `null` and `packagerPort` is integer. So the error `"packagerPort must be an integer"` will be thrown if  `packagerPort` is integer instead of when it isn't integer.

**Comment by brentvatne** [comment]
thanks for the issue! this will be fixed on the next release that goes out
