### ISSUE TITLE
Support XDG Base Directory specification

### ISSUE THREAD

**Issue by distefam** [expo/expo-cli#2274]
## Description

Expo should place its configuration files according to the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

## Expected Behavior

Follow the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and place the contents of the aforementioned `.expo` directory in `$HOME/config/expo`.

## Observed Behavior

Expo puts a hidden directory (`.expo`) in the user's home directory when run.

## Reproducible Demo

1. Install expo using `npm install -g expo-cli`
2. Run `expo start` from within project directory
3. Run `ls -lA $HOME | grep expo` and observe `.expo` directory

**Comment by brentvatne** [comment]
Hi there!

This PR starts with a very strong assumption:

> Expo should place its configuration files according to the XDG Base Directory Specification.

Can you explain the reasoning further please? We're open to being convinced, but we would need to hear more.

**Comment by distefam** [comment]
You're right, _should_ is strong language. It would be very nice in my opinion, however. Basically, on Linux systems installed programs used to litter one's home directory with a bunch of hidden files, "dotfiles". The XDG Base Directory specification linked above is an attempt to migrate those hidden files to a standard directory structure. 

This makes the output of `ls -la` much more useful when in one's home directory, makes dotfile syncing easier as they are now contained in a single place (`$HOME/.config`) and generally is much less cluttered.

The [Archlinux wiki maintains a list of programs](https://wiki.archlinux.org/index.php/XDG_Base_Directory#Supported) (incomplete but pretty substantial) that adhere to or at least have workarounds to accommodate the spec.

**Comment by erayaydin** [comment]
Any news about this improvement? I think we can add this issue to Arch Linux Wiki for tracking @distefam . XDG Base Directory Specification is important for most of the GNU/Linux users.

**Comment by codingjerk** [comment]
@brentvatne
Can I propose a code that will keep backward compatibility? There are a lot of advantages to segregate configs and persistent/temporary data from each other.

@distefam
The files in `.expo` directory are not configs, so it will be better to store them in `$XDG_CACHE_HOME` aka `.cache` or even in `$XDG_DATA_HOME` aka `.local/share`.

**Comment by brentvatne** [comment]
@codingjerk - i'm open to a pr that is backwards compatible!

> The files in `.expo` directory are not configs, so it will be better to store them in `$XDG_CACHE_HOME` aka `.cache` or even in `$XDG_DATA_HOME` aka `.local/share`.

there is some combination of cache and shared data here. within the `.expo` directory:
- the android-apk-cache, ios-simulator-app-cache, template-cache, and cache directories are, as you would expect, caches.
- the PATH and xde-recent-exps.json files are no longer used
- state.json and ngrok.yml contain data shared between different expo projects on the same machine

**Comment by jedahan** [comment]
How about breaking it down into two or more steps

## step one - add XDG_CONFIG_HOME support
Change the default directory from hardcoded $HOME/.expo to these fallbacks, in order:
  - $XDG_CONFIG_HOME/expo
  - $HOME/.config/expo
  - $HOME/.expo

## step two - splitting directories into more appropriate places
Migrate {android-apk,ios-simulator-app,template}-cache, and other directories to
  - $XDG_CACHE_HOME/expo
  - $XDG_CONFIG_HOME/expo # unsure about this one
  - $HOME/.cache/expo
  - $HOME/.expo

Migrate configs that users are not expected to edit to 
  - $XDG_DATA_HOME/expo
  - $XDG_CONFIG_HOME/expo # unsure about this one
  - $HOME/.local/share/expo
  - $HOME/.expo

**Comment by ZerdoX-x** [comment]
```
$ expo start --web
Uncaught Error Error: EACCES: permission denied, mkdir '/home/zerdox/.expo'
error Command failed with exit code 1.
```
I do not want your app creating trash files and littering in my home directory.

---
And please remove "needs more info" label. Everything is described in specs. Which info are you missing? Every user-friendly linux application supports this specification.

**Comment by sk8ersteve** [comment]
Can we reopen this?
