### ISSUE TITLE
expo publish fails with '-' in android.package

### ISSUE THREAD

**Issue by yanchenko** [expo/expo-cli#228]
```
$ expo publish
• Field: android.package - 'android.package' should be a reverse DNS notation unique name for your app. For example, host.exp.exponent, where exp.host is our domain and Expo is our app..
Couldn't publish because errors were found. (See logs above.) Please fix the errors and try again.
```
```
"android": {
    "package": "my.domain-name.app // leads to the error
    "package": "my.domainname.app // publishes fine
}
```

**Comment by fson** [comment]
Unfortunately Android package names may not contain hyphens. Only allowed characters are uppercase or lowercase characters A-Z, numbers 0-9 and underscore (`_`). See https://developer.android.com/guide/topics/manifest/manifest-element#package.

I'm going to add this to the error message to make it clearer which characters are allowed.

**Comment by fson** [comment]
We've improved the error message in the configuration schema.
