### ISSUE TITLE
IOS build and upload commands should rely on the same env vars

### ISSUE THREAD

**Issue by cruzach** [expo/expo-cli#2280]
`expo build:ios` expects the `EXPO_APPLE_PASSWORD` env variable, whereas `expo upload:ios` expects the `EXPO_APPLE_ID_PASSWORD` env variable. Unless there's a reason to have these be two different keys, it would avoid confusion to use the same one in both scenarios

Since this would be a breaking change, we can wait to fix this until we are about ready to ship a new major version. It's an easy change to make, but could cause a headache for people who are accustomed to the current workflow

**Comment by 1337LutZ** [comment]
> `expo build:ios` expects the `EXPO_APPLE_PASSWORD` env variable, whereas `expo upload:ios` expects the `EXPO_APPLE_ID_PASSWORD` env variable. Unless there's a reason to have these be two different keys, it would avoid confusion to use the same one in both scenarios
> 
> Since this would be a breaking change, we can wait to fix this until we are about ready to ship a new major version. It's an easy change to make, but could cause a headache for people who are accustomed to the current workflow

I vote for this as well. Now we are managing 2 different keys in 3 projects.
