### ISSUE TITLE
@expo/next-adapter overrides Vercel provided environment variables

### ISSUE THREAD

**Issue by marklawlor** [expo/expo-cli#2289]
## Description

The [docs](https://docs.expo.io/guides/using-nextjs/#deploy-to-vercel) for @expo/next-adapter say that Vercel is a supported deployment platform. However after deploying to Vercel I am unable to access any [integration](https://vercel.com/docs/v2/build-step#integration-environment-variables) or [system](https://vercel.com/docs/v2/build-step#system-environment-variables) environment variables within my NextJS application. Instead they are overwritten by @expo/next-adapter

## Expected Behavior

The environment variables provided by Vercel should be available to my NextJS application

## Observed Behavior

`process.env` is overwritten to 

```
{"NODE_ENV":"production","PUBLIC_URL":"","APP_MANIFEST": {"name":"3fa87522","slug":"3fa87522","version":"1.0.0","sdkVersion":"37.0.0","platforms":["ios","android","web"],"web":{}}}
```

## Environment

Project was build and deployed by the Vercel Github Integration.

```
  "dependencies": {
    "expo": "37.0.7",
    "next": "9.3.5",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-web": "0.11.7"
  },
  "devDependencies": {
    "@babel/core": "7.9.0",
    "@expo/next-adapter": "2.1.0"
  },
```

## Reproducible Demo

1. Run
```
npx create-react-native-app -t with-nextjs;
```

2. Create a single API endpoint in `./api/test.js`

```
export default (req, res) => {
  res.statusCode = 200;
  res.setHeader("Content-Type", "application/json");
  res.end(
    JSON.stringify({
      name: "John Doe",
      age: 12,
      password: process.env.DB_PASS, // Integration environment variable
      username: process.env.DB_USER,  // Integration environment variable
      url: process.env.VERCEL_URL,  // System environment variable
      actual: process.env, // Here you can see they are being overwritten
    })
  );
};
```

3. Deploy to Vercel
4. Go to your apps API endpoint `/api/test`

**Comment by EvanBacon** [comment]
Is this using the latest changes from https://github.com/expo/expo-cli/pull/2177 essentially no keys besides the designated expo keys should be defined. Also no keys should be getting deleted by the Expo webpack config since it explicitly defines values like: `process.env.APP_MANIFEST={}` rather than `process.env = { APP_MANIFEST: {} }`

**Comment by marklawlor** [comment]
Sorry, yes that fixes the issue. Looks like `npx create-react-native-app -t with-nextjs;` creates you a project with a version locked package.json. I'm not sure if that is intentional for maintenance purposes or possibly an issue.

**Comment by baptisteArnaud** [comment]
Indeed, I had to update manually the package as well after creating my project using `npx create-react-native-app -t with-nextjs`.
