### ISSUE TITLE
Diagnostics too invasive and should not automatically upload to S3

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#229]
https://twitter.com/freeatnet/status/1068212508023013376

**Comment by freeatnet** [comment]
@brentvatne Thank you for filing this. The tweet may sound a bit angry, but I was mostly jarred by the situation. I appreciate what you guys do and what you do to support the community.

If you need an extra pair of hands on resolving this issue, don't hesitate to let me know.

**Comment by fson** [comment]
We have now removed the legacy diagnostics upload functionality from Expo CLI and released `expo-cli@2.6.0`.
