### ISSUE TITLE
Why I get stuck in loading Screen after building the apk in expo?

### ISSUE THREAD

**Issue by Ysrbolles** [expo/expo-cli#2292]
Usually when i login either with google or Facebook in my app i get automatically redirected to the home menu that is a map but after i build and ran my app i get stuck in loading Screen every-time after i log in

before building :

![Capture](https://user-images.githubusercontent.com/37486496/85133582-ddf2b080-b232-11ea-9b13-a4dbd92f34b0.JPG)

After building :

![Capture1](https://user-images.githubusercontent.com/37486496/85133663-05e21400-b233-11ea-909f-26d43c052603.JPG)

**Comment by brentvatne** [comment]
there could be a lot of reasons. try switching to production mode (https://docs.expo.io/workflow/development-mode/) in expo-cli and debugging it locally. if that doesn't fix it, try watching device logs when you open your app to see if there are any useful errors (android logs are very noisy!)

**Comment by AdamJNavarro** [comment]
Hey @Ysrbolles, I hope Brent's advice was helpful. I'm going to close this issue but if you find a reproducible bug that comes from Expo, please open up a new issue with as much information as you can provide and the reproducible test case.

Cheers,
Adam
