### ISSUE TITLE
[Electron] AuthSession guidance

### ISSUE THREAD

**Issue by Jonatthu** [expo/expo-cli#2294]
I have been trying so far to make it work with electron.
There is no official docs but so far it is working good in ios/web but on electron you are able to sign in with a new window but on the redirect back the window do not close and loads another instance of the electron application.

https://docs.expo.io/versions/latest/sdk/auth-session/

Please could we add a section for electron usage?
and maybe some demo or official test?

**Comment by EvanBacon** [comment]
AuthSession does not support Electron -- `@expo/electron-adapter` is not an officially supported Expo platform, it's just an experimental project I setup. We would rather support native operating systems in the future.

If you'd like to add support you can open a PR on expo/expo with an Electron version of this file [`ExpoWebBrowser.web.ts`](https://github.com/expo/expo/blob/master/packages/expo-web-browser/src/ExpoWebBrowser.web.ts).
