### ISSUE TITLE
XDLError: packagerPort must be an integer

### ISSUE THREAD

**Issue by mjstelly** [expo/expo-cli#2295]
## Description
Today is the first time I've used Expo for any production code. I've encountered this error:

 `[Error] XDLError: packagerPort must be an integer`

the first time I've tried to use the VSC Expo debug configuration. This error does not occur when launching expo normally.

## Expected Behavior

Use case: Debug expo app using VSC integrated debugger.

1. Add expo config to `launch.json`
2. In Debug mode, run the configuration

Expected app to launch in debug mode

## Observed Behavior

Upon launching the debug config, the bundler starts successfully. However, immediately after that,  I receive the following console output terminating the launch process. It is unrecoverable and the app will not launch in debug mode at all.

```
Loading dependency graph, done.
[Info] Packager started.

[Info] Prewarming bundle cache. This may take a while ...

[Info] Building and running application.

[Error] XDLError: packagerPort must be an integer
```

## Environment
Debug config:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug in Exponent",
      "cwd": "${workspaceFolder}",
      "type": "reactnative",
      "request": "launch",
      "platform": "exponent"
    }
  ]
}
```
Diagnostics
```
Expo CLI 3.21.9 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.10 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ~0.11.7 => 0.11.7 
      react-navigation: ^4.3.9 => 4.3.9 
```

## Reproducible Demo
I do not have a demo.

**Comment by omefire** [comment]
I'm facing the same issue.

**Comment by brentvatne** [comment]
this seems like an issue with the visual studio code extension, could you open an issue on that repo and link to it here?

**Comment by omefire** [comment]
Yeah, that's what I'm realizing. It seems like an argument isn't being set before calling the `setOptionsAsync` exposed by this codebase.

**Comment by mjstelly** [comment]
I appreciate the response. It may be an issue with VSC's handling of the expo debugger. I can use their debugger with no problem on my non-expo apps. I'll see what they have to say about it.

**Comment by mjstelly** [comment]
The VSC issue template recommends loading the IDE w/o extensions using `code --disable-extensions`. I did so. The debugger failed to launch. This leaves me with a third dependency, `React Native Tools` that mucks up the works. At this point, I don't have the time to run down this rabbit hole. I hope someone finds this and can offer a solution.
![Screen Shot 2020-06-28 at 10 04 51 AM](https://user-images.githubusercontent.com/313819/85951146-d1ebaa80-b926-11ea-8ac0-d62755247fe7.png)

**Comment by mjstelly** [comment]
I opened an [issue with VSCode](https://github.com/microsoft/vscode/issues/101236). They, too, punted on the issue.
