### ISSUE TITLE
[config] preserve comments and whitespace in AndroidManifest.xml

### ISSUE THREAD

**Issue by cruzach** [expo/expo-cli#2296]
the package we use to read and write the AndroidManifest (`xml2js`) doesn't preserve comments, whitespace, and in some cases, order of tags

**Comment by EvanBacon** [comment]
related https://github.com/expo/expo-cli/pull/1408/files

**Comment by fson** [comment]
As @bbarthec pointed out elsewhere https://github.com/expo/expo-cli/pull/2249#issuecomment-647706053, `xml-js` removes whitespace, so it's probably not what we want.

One spec compliant parser/serializer that does preserve comments and formatting is `xmldom`: https://yarnpkg.com/package/xmldom. It's also [reasonably sized](https://packagephobia.com/result?p=xmldom) and [widely used](https://www.npmjs.com/browse/depended/xmldom).

However, it just outputs a standard DOM, so finding elements and manipulating it can be a bit cumbersome, unless we find something like a CSS selector library that can operate on the DOM objects it produces. But even we need to traverse the DOM manually to find the elements, it might still be worth it if it allows us not to clobber with unrelated parts of the `AndroidManifest.xml` file.

**Comment by EvanBacon** [comment]
Duplicate #1902

**Comment by EvanBacon** [comment]
I don't think this is something we want to support right now. Users tap into how we parse XML via config plugins and we opted for the simplest interface possible.
