### ISSUE TITLE
expo publish Fetching the user profile failed

### ISSUE THREAD

**Issue by je310solution** [expo/expo-cli#2308]
```
Fetching the user profile failed
getaddrinfo ENOTFOUND exp.host exp.host:443
Fetching the user profile failed
getaddrinfo ENOTFOUND exp.host exp.host:443
An Expo user account is required to proceed.
```

Suddenly I am getting this error when trying to do expo publish.

when im trying to visit https://exp.host/ it just says "not found"

**Comment by brentvatne** [comment]
there were some outages recently, you can always check the status at https://status.expo.io/. sorry for the trouble!
