### ISSUE TITLE
start a new project in react native - error

### ISSUE THREAD

**Issue by Postyy** [expo/expo-cli#231]
![screen shot 2018-12-01 at 5 26 17 am](https://user-images.githubusercontent.com/9606235/49328700-da50e900-f529-11e8-8559-63c0c62b739b.png)
 Please help

**Comment by catievickers** [comment]
I am having the exact same error.

**Comment by raajnadar** [comment]
You should not use `sudo` there is a security risk..
Try running `expo init` in another directory where you can read and write without `sudo`

**Comment by fson** [comment]
Yeah, you should not use `sudo` to run `expo init`. Please let me know if you're getting an error when running without `sudo`.
