### ISSUE TITLE
expo eject is not working on Windows

### ISSUE THREAD

**Issue by alex-fournier** [expo/expo-cli#2312]
## Description

I am not able to make an `expo eject`. I tried on a fresh blank project just after an `expo init`, I got the following error :

![eject](https://user-images.githubusercontent.com/1874622/85740747-2a8e2e00-b702-11ea-9ca5-8e596cb57504.jpg)

## Environment

```
Expo CLI 3.21.10 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.16.1 - D:\Programs\nodejs\node.EXE
      Yarn: 1.22.4 - D:\Programs\Yarn\bin\yarn.CMD
      npm: 6.13.4 - D:\Programs\nodejs\npm.CMD
    npmPackages:
      expo: ~37.0.3 => 37.0.12
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: ~0.61.5 => 0.61.5
      react-native-web: ~0.11.7 => 0.11.7
```

**Comment by brentvatne** [comment]
a workaround for this is available in the latest version of expo-cli (expo-cli@3.21.13). it won't apply the entitlements but also won't error out when it doesn't work. @byCedric will work on a better fix soon
