### ISSUE TITLE
[nextjs] I'm getting "An unexpected error has occurred." by embedding my page using `react-native-webview`

### ISSUE THREAD

**Issue by 5ervant** [expo/expo-cli#2320]
Hello, I used the following code to embed https://techintel.github.io/item-displays into my Expo native app:

      {Platform.OS === 'web' ? (
        <Page />
      ) : (
        <WebView
          source={{
            uri: Constants.manifest.extra.PUBLIC_URL + '/item-displays',
          }}
          style={{ height: Layout.window.height }}
        />
      )}

Unfortunately, that component just outputs the following:

    An unexpected error has occurred.

Any problem, what's going on, I guess `WebView` is preventing some of my page scripts?
Any fix?

Ref: https://github.com/vercel/next.js/discussions/14628

-----

### Luckily, it's working on my phone but not on my Android Emulator!

**Comment by fson** [comment]
Hi, this issue tracker is for bugs and problems with Expo CLI. For questions, please try https://forums.expo.io/ instead. Thanks!

**Comment by Xprj3ct** [comment]
what he asked is a bug that needs to be fixed am also getting the same problem, is not a question
