### ISSUE TITLE
ERROR ITMS-90725: "SDK Version Issue. This app was built with the iOS SDK. As of June 30, 2020, all apps for iPhone or iPad must be built with the iOS 13 SDK or later, included with Xcode 11 or later."

### ISSUE THREAD

**Issue by mcarlson** [expo/expo-cli#2328]
Looks like the turtle build service needs a newer version of XCode. I'm using SDK 38 and this just started happening... :/ See https://github.com/expo/expo/issues/3125 for context the last time this happened...

**Comment by mcarlson** [comment]
I'm using Transporter Version 1.1.1 (1171) and XCode Version 11.3.1 (11C504)... Would these be the issue?

**Comment by mcarlson** [comment]
I ask because I was able to build and upload a native version of the app with my local XCode and everything was fine. Any other ideas?

**Comment by dsokal** [comment]
I'm looking into this now. That's a little weird because the builder service is currently using Xcode 11.4 which includes iOS 13 SDK.

**Comment by dsokal** [comment]
I tried to reproduce this issue:
- I ran `expo init` to initialize a new project.
- I edited `app.json` to add `ios.bundleIdentifier`.
- I ran `expo build:ios` to build .ipa for the project.
- I created an app on App Store Connect.
- Using Transporter Version 1.1.1 (1171), I submitted the .ipa.
- After a little while, I got the following email from Apple: 
> Dear [REDACTED],
>
> The following build has completed processing:
> 
> Platform: iOS
> App Name: [REDACTED]
> Build Number: 1
> Version Number: 1.0.0
> App SKU: [REDACTED]
> App Apple ID: [REDACTED]
>
> You can now use this build for TestFlight testing or submit it to the App Store.
>
> If you have any questions regarding your app, click Contact Us in App Store Connect.
> 
> Regards,
> 
> The App Store team

My guess is that you're probably not using SDK 38. Can you share the build id so I could take a look at logs?

**Comment by mcarlson** [comment]
Please see https://expo.io/dashboard/maxemt/builds/b00dd1e1-1f7f-4fb6-9755-94f7730723cc

**Comment by dsokal** [comment]
Sorry to say that but we probably don't have any bug on our side. And I don't know how to help you.
My another guess would be that you're trying to submit some other `.ipa` than the one built on our servers.
Could you try to reproduce this issue for a fresh Expo project? Basically you could follow the steps from my previous message - https://github.com/expo/expo-cli/issues/2328#issuecomment-652289622. That would be totally helpful.

**Comment by coreybrown89** [comment]
I am experiencing the same issue with sdk 38

**Comment by coreybrown89** [comment]
builds fine on expo servers, but I get this error when uploading with Transport 
```
ERROR ITMS-90725: "SDK Version Issue. This app was built with the iOS SDK. As of June 30, 2020, all apps for iPhone or iPad must be built with the iOS 13 SDK or later, included with Xcode 11 or later."
```

**Comment by coreybrown89** [comment]
Update: I clicked "Verify" first before delivering to the app store and the process went smoothly and updated.

@mcarlson this may help

**Comment by ashwinsingh1089** [comment]
Hi, am sorry, but I have been facing the same issue, my expo sdk version 37.0.0

**Comment by brentvatne** [comment]
@ashwinsingh1089 

from the previous comment:

> Update: I clicked "Verify" first before delivering to the app store and the process went smoothly and updated.

**Comment by brentvatne** [comment]
if anyone encounters this issue again and the above suggestions don't help, please create a new issue and provide as much information as possible
