### ISSUE TITLE
after publish, IOS is not working but android is working

### ISSUE THREAD

**Issue by nomi9995** [expo/expo-cli#2339]
## Description
https://expo.io/@theentertainer/module
I have published my app on expo by `expo publish`. when I scan **QR Code** from android it is loading the app and working well. but when I try to scan  **QR Code** when I get **there was a problem loading the requested** on expo client app

<img src="https://user-images.githubusercontent.com/36044436/86491086-21950080-bd83-11ea-9cd7-57dfc338a37b.jpeg" height="480">

## Expected Behavior
when I scan **QR Code**, expo client should load the app

## Observed Behavior

```
there was a problem loading the requested
```

## Environment

```
Expo CLI 3.21.6-alpha.0 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.15.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.21.6-alpha.0
```

**Comment by brentvatne** [comment]
ensure that you are signed in to the account `theentertainer` or an account that is part of that team in order to open the app. it is not possible to open other users' apps on ios due to restrictions of the app store.

**Comment by nomi9995** [comment]
@brentvatne thanks
