### ISSUE TITLE
Expo CLI slow to return manifest - Timeout on mobile

### ISSUE THREAD

**Issue by Inlustra** [expo/expo-cli#2342]
## Description

Running expo start, starts up absolutely fine. The CI is responsive. (Pressing `?` correctly returns the expo help info)
However, as soon as I attempt to connect to port 19000 to return the manigest and configuration required to run expo, it completely hangs. The CI will no longer respond to input and the request can take well over 2 - 3 minutes, by which point the expo app has already closed.

## Expected Behavior
I would expect this part of the CLI to run relatively quickly.

My app.config.json: 
```
export default {
  name: "My App",
  slug: "my-app",
  version: "0.0.1",
  extra: {
    GRAPHQL_API_ENDPOINT: `${process.env.GRAPHQL_API_HOST}${process.env.GRAPHQL_API_PATH}`,
    DOMAIN: `${process.env.DOMAIN}`,
  },
};
```

I have tried changing this to be a regular JSON file but that doesn't help.
I have also upgraded to see if that helped. it did not.

## Environment
```
  Expo CLI 3.21.3 environment info:
    System:
      OS: Linux 4.19 Ubuntu 18.04.4 LTS (Bionic Beaver)
      Shell: 5.4.2 - /bin/zsh
    Binaries:
      Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
      Yarn: 1.22.4 - /usr/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
    npmPackages:
      expo: ^37.0.0 => 37.0.12 
      react: 16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ^0.11.7 => 0.11.7 
```

Other library versions:
```
    "@babel/core": "7.9.0",
    "@expo/next-adapter": "2.1.15",
    "typescript": "~3.9.6"
```

My babel.config.js:
```
module.exports = {
  presets: ["@expo/next-adapter/babel"],
};
```

If anyone can think of things for me to try, I'm happy to give them a go.
At first I thought this might be a disk speed problem. 
However, testing this with: 
```
55eb6436cd54# sync; dd if=/dev/zero of=tempfile bs=1M count=1024; sync
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 1.37908 s, 779 MB/s
55eb6436cd54# dd if=tempfile of=/dev/null bs=1M count=1024                                        
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 0.365912 s, 2.9 GB/s
```
Shows that my disk is plenty capable.

**Comment by gsbenevides2** [comment]
Hello @Inlustra so I would like to know something the CLI starts to execute crash only when it starts using dynamic manifests like `app.config.js` or `ts`?  It's just that I tried to use these manifests and I noticed a behavior similar to yours.

**Comment by brentvatne** [comment]
@Inlustra - can you share a mcve please? https://stackoverflow.com/help/mcve

**Comment by brentvatne** [comment]
closing until we have a [mcve](https://stackoverflow.com/help/mcve), we can't do much without a way to reproduce this
