### ISSUE TITLE
[web][nextjs] expo/vector-icons not working with NextJS & withFonts 

### ISSUE THREAD

**Issue by daxfrost** [expo/expo-cli#2347]
## Description

Following the instructions to use `withFonts` (next-fonts) for Expo with NextJS (https://docs.expo.io/guides/using-nextjs/#font-support), I am still unable to compile for the web.

To get into this state is easy, I only did the following:

Run these commands to setup the project:

```
expo init NextFontTest -t expo-template-bare-typescript
cd NextFontTest
yarn add -D @expo/next-adapter
yarn next-expo
git add .;git commit -m "commit my changes first"
yarn add @expo/vector-icons
```

After that, I do a simple import of Ionicons in `./pages/index.js`
Then of course, adding `withFonts` to `next.config.js`

## Expected Behavior

The font files do not cause an error during Next JS compilation.

## Observed Behavior

```
yarn build
yarn run v1.22.4
$ next build
> Using external babel configuration
> Location: "/Users/dbooysen/Documents/dev/expo/FontTest/test2/NextFontTest/babel.config.js"
Creating an optimized production build

Failed to compile.

./node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/EvilIcons.ttf 1:0
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)


> Build error occurred
Error: > Build failed because of webpack errors
    at build (/Users/dbooysen/Documents/dev/expo/FontTest/test2/NextFontTest/node_modules/next/dist/build/index.js:13:917)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Environment

```
  Expo CLI 3.22.0 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.2.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.1 => 38.0.8
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: ~0.62.2 => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.21.13
```

## Reproducible Demo

I have created a project for you to reproduce: https://github.com/daxfrost/ExampleNextJSwithFonts

Simply checkout and run:

`yarn install`
`yarn build`

**Comment by daxfrost** [comment]
@EvanBacon it's worth noting that I had to set the @expo/next-adapter version manually to [2.1.17](https://github.com/daxfrost/ExampleNextJSwithFonts/blob/master/package.json#L30) in the example project due to the current issue you are aware of in #2345

**Comment by brentvatne** [comment]
this should be resolved on the latest version of expo-cli

**Comment by daxfrost** [comment]
Thank you, @brentvatne - I can confirm it is corrected! On a fresh project though, we have a sort of [related issue](https://github.com/expo/expo-cli/issues/2345) of being forced to downgrade `@expo/next-adapter` to `2.1.17`, which is what I did to check it is corrected.

**Comment by chichke** [comment]
Can somebody share code that is working, I'm still stuck adding ```    "@expo/vector-icons": "^10.0.0",
``` to Next.js ```    "next": "^10.0.1",
    "next-compose-plugins": "^2.2.1",
    "next-fonts": "^1.5.1",
    "next-images": "^1.6.2",
    "next-transpile-modules": "^4.1.0",
    "nextjs-progressbar": "^0.0.7",```

**next.config.js** : 
```javascript
module.exports = withPlugins([
  withTM,
  [withFonts, {projectRoot: __dirname}],
  withImages,
  [withExpo, { projectRoot: __dirname }],
]);

```

**Comment by chichke** [comment]
<img width="948" alt="Capture d’écran 2020-11-22 à 3 15 24 PM" src="https://user-images.githubusercontent.com/26006762/99906124-8cfd5180-2cd5-11eb-8d6a-67f1e349c710.png">

**Comment by Terkhos** [comment]
I'm having the same issue as @chichke:

```json
"@expo/next-adapter": "^2.1.62"
"next": "^10.0.8"
"next-images": "^1.7.0"
"next-fonts": "^1.5.1"
```

```javascript
module.exports = withPlugins([
    [withFonts, { projectRoot: __dirname }],
    withImages,
    [withExpo, { projectRoot: __dirname }],
], nextConfig)
```

**Comment by listatt** [comment]
Same for me, local fonts couldn't be uploaded

**Comment by ajsmth** [comment]
I also ran into this issue the other day - I'm not sure about the status of the next-fonts plugin, it seems quite old. Fortunately the implementation is fairly straightforward - I'm use this as a temporary workaround and it seems to work (at least for local fonts) - hope it helps!

```

  withFonts(
    withExpo({
      projectRoot: __dirname,
    })
  )

function withFonts(nextConfig = {}) {
  return Object.assign({}, nextConfig, {
    webpack(config, options) {
      if (!options.defaultLoaders) {
        throw new Error(
          "This plugin is not compatible with Next.js versions below 5.0.0 https://err.sh/next-plugins/upgrade"
        );
      }

      const enableSvg = nextConfig.enableSvg || false;

      let testPattern = /\.(woff(2)?|eot|ttf|otf)(\?v=\d+\.\d+\.\d+)?$/;

      if (enableSvg)
        testPattern = /\.(woff(2)?|eot|ttf|otf|svg)(\?v=\d+\.\d+\.\d+)?$/;

      config.module.rules.push({
        test: testPattern,
        // Next.js already handles url() in css/sass/scss files
        issuer: /\.\w+(?<!(s?c|sa)ss)$/i,
        use: [
          {
            loader: require.resolve("url-loader"),
            options: {
              esModule: false,
              limit: 50000,
              name: "./static/fonts/[name].[ext]",
            },
          },
        ],
      });

      if (typeof nextConfig.webpack === "function") {
        return nextConfig.webpack(config, options);
      }

      return config;
    },
  });
}

```
