### ISSUE TITLE
node_modules/react-native-scripts/build/bin/crna-entry.js: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by MrDave888** [expo/expo-cli#235]
## Description

When running npm start from the project root the packager runs but after scanning the qr code from the app it red screens with the error: /home/dave/Documents/Projects/roma/roma-mobile-react/App.js: Cannot read property '1' of undefined

## Expected Behavior

The bundle compiles and app runs as usual.

## Observed Behavior

What actually happened when you performed the above actions?
Red screen with the following error:

/home/dave/Documents/Projects/roma/roma-mobile-react/App.js: Cannot read property '1' of undefined

## Environment

Expo CLI 2.6.0 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 11.3.0 - /usr/bin/node
      npm: 6.4.1 - /usr/bin/npm
    npmPackages:
      expo: ~31.0.6 => 31.0.6
      react: ~16.6.3 => 16.6.3
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1
      react-navigation: ~3.0.4 => 3.0.4
    npmGlobalPackages:
      expo-cli: 2.6.0

Phone modal:
Motorola G5
Android 7.0

## Reproducible Demo

Not sure how I would do this but happy to provide a link to a repo in private if needed

**Comment by fson** [comment]
Since the error comes from the `App.js` file, could you show the contents of this file? Maybe there's an error in the code?

**Comment by fson** [comment]
If you're still having problems with this, please post your question to [Expo forums](https://forums.expo.io/c/help).
