### ISSUE TITLE
[Bug Report]: Expo CLI global package dependency missing

### ISSUE THREAD

**Issue by dalisoft** [expo/expo-cli#2354]
## Description

I have Ansible script which gets all `npm` packages and then installs missing, but `npm ls --depth=0 -g` gives error which comes from this package.
Because of this error my Ansible installation script fails while doing `npm ls --depth=0 -g`.

## Expected Behavior

```
❯ npm ls --depth=0 -g
/Users/dalisoft/.npm-global/lib
├── expo-cli@3.22.1
└── npm@6.14.6
```

## Observed Behavior

```
❯ npm ls --depth=0 -g
/Users/dalisoft/.npm-global/lib
├── expo-cli@3.22.1
└── npm@6.14.6

npm ERR! peer dep missing: react-refresh@^0.8.2, required by @pmmmwh/react-refresh-webpack-plugin@0.3.3
```

## Environment

OS: macOS Mojave 10.14.6
Node: v14.5.0
npm: 6.14.6

## Reproducible Demo

Ansible installation task [here](https://github.com/dalisoft/config/blob/master/ansible/roles/modules/tasks/main.yml#L22-L38)

**Comment by brentvatne** [comment]
hi there! this is currently left out because react-native includes it too and we're concerned that the versions may clash and cause issues. is this limiting your ability to use expo-cli?

**Comment by dalisoft** [comment]
Hi @brentvatne 

Thanks for reply. I am newbie and wanna learn mobile development. I know and already downloaded **expo-cli** before, but before this bug isn't existed.
This feature does not blocks from use, but blocks my script from executing, it's not need for fast-fix, but could be great if this issue was fixed.

**Comment by dalisoft** [comment]
It's not a Expo-CLI issue as even installing dependecy as global does not help, so i think better to close this issue and install expo-cli in project devDependecy as always.

Thanks

**Comment by rasulrukhilloev** [comment]
But this bug shows up only after installing Expo-cli. If i remove expo-cli, there is no error after command `npm ls --depth=0 -g`

**Comment by brentvatne** [comment]
@rasulrukhilloev - does it impact your ability to use expo-cli?

**Comment by dalisoft** [comment]
@rasulrukhilloev I know, bug happens only after installing @expo/expo-cli, but seems @expo team did this change to reduce conflict with **react-native**, so we there cannot do something except **Fork** and using own repo

**Comment by sahilrajput03** [comment]
Seroiusly, its a bug that corrupts the global dependency tree, so its bad to install it globally, please fix this issue, or refer some workaround for this.
I also use npm i -t --depth 0 to get list of globally installed packages but just I can't get the list now..., what do i do now???
i use that command in scripts. 
This is bad bugg!!!

**Comment by dalisoft** [comment]
As this bug affected to many peoples including me, i'll reopen this issue

**Comment by EvanBacon** [comment]
react-refresh was added in #2579

**Comment by samiq** [comment]
I can see this issue was closed by linking to @EvanBacon pull requested being merged, I have updated to latest version and I can see this is still an issue and even worst now it has increased to something more, any chance these type of checks are added as part of release process of the cli? it's difficult as this corrupts the global listing of packages installed. 

```bash
npm ERR! peer dep missing: react-refresh@^0.8.2, required by @pmmmwh/react-refresh-webpack-plugin@0.3.3
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.5.2
```

**Comment by brentvatne** [comment]
these peer deps are both transitive, one coming from [schema-utils](https://www.npmjs.com/package/schema-utils) and the other from [@pmmmwh/react-refresh-webpack-plugin](https://www.npmjs.com/package/@pmmmwh/react-refresh-webpack-plugin).

do you have any suggested solution for this? maybe you could open a pr to those libraries to remove the peer dependency?
