### ISSUE TITLE
Unable to eject

### ISSUE THREAD

**Issue by dutzi** [expo/expo-cli#2362]
Expo CLI version: 3.22.3

I just installed a fresh copy of Expo CLI, created a new project and immediately tried to eject. It asks me:

```
? What would you like your Android package to be named?
```

And whatever I type it doesn't continue.

**Update:** I tried `blah.com` and it worked (I also tried `foo.bar.com` and `com.foo.bar` and it didn't)

**Comment by cruzach** [comment]
Hi! I tried to reproduce this on the same version of `expo-cli`, but it seems to work for me:
<img width="1019" alt="Screen Shot 2020-07-15 at 9 59 06 AM" src="https://user-images.githubusercontent.com/35579283/87554263-e9929500-c681-11ea-875d-f1416f13a709.png">


Could you provide more information for us to reproduce the issue? We lay out everything we need in the template

**Comment by brentvatne** [comment]
also cannot repro this.

if the issue persists, please follow the issue template and create a new issue. we provide the issue template to help guide developers to provide us with the information that we need to help you

**Comment by charlie632** [comment]
I'm having the same issue :(

**Comment by jeremyolsen** [comment]
Also running into this.  Using <your name here>.com works though.  Not ideal, but gets past the error.

**Comment by brentvatne** [comment]
@jeremyolsen, @charlie632 - i commented above:

> also cannot repro this.
>
> if the issue persists, please follow the issue template and create a new issue. we provide the issue template to help guide developers to provide us with the information that we need to help you

**Comment by ndotie** [comment]
What would you like your Android package to be named? 

> Expo CLI version: 3.22.3
> 
> I just installed a fresh copy of Expo CLI, created a new project and immediately tried to eject. It asks me:
> 
> ```
> ? What would you like your Android package to be named?
> ```
> 
> And whatever I type it doesn't continue.
> 
> **Update:** I tried `blah.com` and it worked (I also tried `foo.bar.com` and `com.foo.bar` and it didn't)

worked when we add `something.com`

**Comment by Harrijefria** [comment]
> Expo CLI version: 3.22.3
> 
> I just installed a fresh copy of Expo CLI, created a new project and immediately tried to eject. It asks me:
> 
> ```
> ? What would you like your Android package to be named?
> ```
> 
> And whatever I type it doesn't continue.
> 
> **Update:** I tried `blah.com` and it worked (I also tried `foo.bar.com` and `com.foo.bar` and it didn't)

Thank you very much

**Comment by brentvatne** [comment]
if you run into this problem please create a new issue and fill in the issue template
