### ISSUE TITLE
Expo Login is failing with error

### ISSUE THREAD

**Issue by MaheshaBhat** [expo/expo-cli#2363]
I am trying to execute expo login, but I am getting "unable to get local issuer certificate" error.
I am using expo SDK: 38.0.0.
all expo commands are failing.
what should I do to fix this problem?

**Comment by MaheshaBhat** [comment]
I am using 3.22.3

**Comment by brentvatne** [comment]
can you share the exact error message?

**Comment by brentvatne** [comment]
https://github.com/nodejs/node/issues/3742

this is a node issue, you can run `npm config set strict-ssl false` to resolve it, but i'd suggest reading over the thread to be familiar with alternatives and what that actually does

**Comment by MaheshaBhat** [comment]
i tried **npm config set strict-ssl false**  command, still I am getting the same error.
I am getting following error "Error: unable to get local issuer certificate."

**Comment by brentvatne** [comment]
please create a new issue and follow the issue template (the text that is provided in the comment box when you create a new issue).

**Comment by MaheshaBhat** [comment]
ya sure will do.
i didn't face any problem while using any of the npm commands.
but while **expo start** i got following warning:
`Warning: Problem validating app.json: Unable to perform cache refresh for ....\.....\schema-37.0.0.json: Error: unable to get local issuer certificate.`
for expo login i got following error:
`unable to get local issuer certificate.`

**Comment by MaheshaBhat** [comment]
Hi,
after executing following commands i was able to resolve this issue.
**npm config set strict-ssl false
SET NODE_TLS_REJECT_UNAUTHORIZED=0**
thanks for the help.
