### ISSUE TITLE
[configure-splash-screen] using wrong call signature for SplashScreen.show in MainActivity

### ISSUE THREAD

**Issue by felixroos** [expo/expo-cli#2365]
## Description

expo-splash-screen command seems to insert a wrong call signature to MainActivity.java. 

command:

```sh
npx expo-splash-screen -p android "#ffffff" ./splash.png
```

when i run the android build, the following error is thrown:

```log
MainActivity.java:16: error: incompatible types: boolean cannot be converted to Class<? extends ViewGroup>
    SplashScreen.show(this, SplashScreenImageResizeMode.CONTAIN, false);
```

## Environment

<details>
<summary>expo diagnostics</summary>

```log

  Expo CLI 3.20.5 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v10.16.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.13.1 => 16.13.1 
      react-native: 0.63.1 => 0.63.1 
    npmGlobalPackages:
      expo-cli: 3.20.5
```

- using "expo-splash-screen": "^0.3.1"
- testing with "Pixel 2 API 28" emulator

</details>

## Reproducible Demo

1. init project:

```sh
react-native init splashtest --npm
cd splashtest
npm i expo-splash-screen@^0.3.1 react-native-unimodules@^0.10.1 --save
```

2. [set up unimodules for android](https://docs.expo.io/bare/installing-unimodules/#configuration-for-android)

3. run expo-splash-screen:

```sh
curl https://i.imgur.com/GYmxbaZ.png > splash.png
npx expo-splash-screen -p android "#ffffff" ./splash.png
```

4. run android build to get the error:

```sh
npm run android
```

## fix

This fixes the build (MainActivity.java):

```diff
+import com.facebook.react.ReactRootView;
/* */
-SplashScreen.show(this, SplashScreenImageResizeMode.CONTAIN, false);
+SplashScreen.show(this, SplashScreenImageResizeMode.CONTAIN, ReactRootView.class);
```

I found this fix in the readme under [Manual Configuration](https://github.com/expo/expo/tree/master/packages/expo-splash-screen#-update-mainactivityjavakt).

The source code can be found [here](https://github.com/expo/expo-cli/blob/master/packages/configure-splash-screen/src/android/MainActivity.ts#L66) and [here](https://github.com/expo/expo-cli/blob/master/packages/configure-splash-screen/src/android/MainActivity.ts#L79)

Thank you

**Comment by brentvatne** [comment]
thank you for reporting this!

I have released `expo-splash-screen@0.4.0` to include the latest changes, it seem that this was not released recently when we should have done so and so it became out of sync with the automatic configuration package.
