### ISSUE TITLE
[web] Service worker in Safari does not update

### ISSUE THREAD

**Issue by david-arteaga** [expo/expo-cli#2367]
## Description
When building a web app with the expo cli (`expo build:web`), the generated service worker does not get updated on Safari (macOS and iOS) even when a new version of the site is deployed.

### Potential solution

According to [the service worker lifecycle](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#updates), service workers are only updated if the registered file is byte-different than the last version the browser cached.
There is a comment in the service worker docs that mentions that `We're extending this to include imported scripts/modules too`.
It seems that both Chrome and Firefox have implemented this behavior already.

These are the request that each browser makes after the service worker has been installed and the site is cached:
<img width="479" alt="Screen Shot 2020-07-16 at 10 45 33" src="https://user-images.githubusercontent.com/7199015/87694400-c801de00-c753-11ea-9efe-180fa9e90cf7.png">

As you can see, Safari only requests `expo-service-worker.js`.

Both Chrome and Firefox also request `service-worker.js` and `precache-manifest.[hash].js`, even when the `expo-service-worker.js` file is identical to the one cached in the browser.

The `service-worker.js` file is imported by `expo-service-worker.js` using `importScripts` [here](https://github.com/expo/expo-cli/blob/master/packages/webpack-config/web-default/expo-service-worker.js#L93), and the precache manifest is imported by the `service-worker.js` file generated by Workbox.

For Safari to pick up the change in the site, the registered service worker file has to be byte-different compared to the last generated version.

I see two potential solutions to this.

1. Make `expo-service-worker.js` byte-different on every build that changed any files. This could be accomplished by adding a comment with the name of the `precache-manifest.[hash].js` to the file. I already tested that any change in the file (even comments) triggers the reload on Safari (since it is byte-different). This seems like the easiest change but kind of a hack.

2. Register the `service-worker.js` file generated by Workbox as the main service worker file (change [this](https://github.com/expo/expo-cli/blob/master/packages/webpack-config/web-default/register-service-worker.js#L6)), and import `expo-service-worker.js` using the `importScripts` option in `GenerateSW` [here](https://github.com/expo/expo-cli/blob/master/packages/webpack-config/src/addons/withWorkbox.ts#L152). The generated `service-worker.js` file already imports the recache-manifest file, so any time any site content changes, the precache-manifest file name changes, and the contents of the `service-worker.js` file change. I looked around in the repo and this option seems a lot more complicated for the current setup. Also, if any site has already been deployed with the `expo-service-worker.js` file as the main sw registered file, I am not sure what would need to be done to make sure the site keeps working and updating properly.

## Expected Behavior
The service worker should be updated when a new version of the site is deployed and the updated site should be displayed in the browser.

## Observed Behavior
The service worker and site are not updated in Safari.

## Environment
I tested the issue in Safari (Version 13.1.1 (15609.2.9.1.2)) on macOS Catalina (10.15.5) and on Safari on iOS 13.5.1.

Expo CLI 3.22.1 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild

## Reproducible Demo
1. Generate an expo project `expo init service-worker-test`
2. Build the project `expo build:web`
3. Serve the project on localhost and access the site using Safari. Make sure the service worker is installed and the site works offline.
4. Update the project in some way and build again.
5. Reload the page in safari.
6. The site does not get updated.

**Comment by brentvatne** [comment]
i think PWAs are still too raw and we probably should disable them by default due to issues like this. to do this we need to:

- disable them and do a new release
- update docs / articles to remove 'pwa by default' mentions

**Comment by david-arteaga** [comment]
Yeah I agree that service workers should be disabled by default.
Keeping the manifest and other PWA related features does seem worthwhile though (same as CRA does)

**Comment by EvanBacon** [comment]
Service workers will be disabled in SDK 39
