### ISSUE TITLE
Does expo-cli need to pin exact lodash version?

### ISSUE THREAD

**Issue by jtbeach** [expo/expo-cli#2374]
## Description

We're seeing a low-severity lodash CVE reported in our repository because expo-cli pins lodash to a vulnerable version (4.17.15). It would be great if this restriction could be loosened to allow for patch version updates so that security fixes can be applied without custom resolution being required. Obviously this isn't a real security issue since expo-cli wouldn't be in final code bundle, but it will trigger Github alerts for all projects using expo-cli regardless

CVE details:

GHSA-p6mc-m468-83gw
low severity
Vulnerable versions: < 4.17.19
Patched version: 4.17.19
Versions of lodash prior to 4.17.19 are vulnerable to Prototype Pollution. The function zipObjectDeep allows a malicious user to modify the prototype of Object if the property identifiers are user-supplied. Being affected by this issue requires zipping objects based on user-provided property arrays.

This vulnerability causes the addition or modification of an existing property that will exist on all objects and may lead to Denial of Service or Code Execution under specific circumstances.

## Expected Behavior

expo-cli depends on lodash "~4.7.15"

## Observed Behavior

expo-cli depends on lodash "4.7.15"

**Comment by EvanBacon** [comment]
Looks like this was fixed in https://github.com/expo/expo-cli/pull/3124
