### ISSUE TITLE
app.config.js is called more than once

### ISSUE THREAD

**Issue by MehmetKaplan** [expo/expo-cli#2375]
## Description

When `expo start` is called, `app.config.js` is called more than once. This makes tasks like managing build numbers, logging current build parameters, etc harder.

## Expected Behavior
When `expo start` starts execution, it would be better it forms the final app.json only once, and reuses that final app.json every time it needs.

## Observed Behavior
Using same method mentioned in [related documentation](https://docs.expo.io/workflow/configuration/), when `expo start` is run the log is written multiple times, which implies most of the (if not each) times app.json is needed the exported function in `app.config.js` is called again and again.

```
export default ({ config }) => {
  console.log(config.name); // prints 'My App'
  return {
    ...config,
  };
};
```

This causes build number management within `app.config.js` near impossible, logs to be generated unnecessary times, the process itself to slow down.

## Environment

```
mehmetkaplan@MACOS:app-config-test$ expo diagnostics

  Expo CLI 3.22.3 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.18.2 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.8 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 2.2.0


```

## Reproducible Demo

In the below demo please note the text `app-config-test` is coming from the `app.config.js` and it continues to be logged even after the QR code is generated.

```
mehmetkaplan@MACOS:test$ figlet app-config-test
                                          __ _             _            _   
  __ _ _ __  _ __         ___ ___  _ __  / _(_) __ _      | |_ ___  ___| |_ 
 / _` | '_ \| '_ \ _____ / __/ _ \| '_ \| |_| |/ _` |_____| __/ _ \/ __| __|
| (_| | |_) | |_) |_____| (_| (_) | | | |  _| | (_| |_____| ||  __/\__ \ |_ 
 \__,_| .__/| .__/       \___\___/|_| |_|_| |_|\__, |      \__\___||___/\__|
      |_|   |_|                                |___/                        
mehmetkaplan@MACOS:test$ expo init app-config-test
? Choose a template: expo-template-blank

🧶 Using Yarn to install packages. You can pass --npm to use npm instead.

✔ Downloaded and extracted project files.
✔ Installed JavaScript dependencies.

✅ Your project is ready!

To run your project, navigate to the directory and run one of the following yarn commands.

- cd app-config-test
- yarn start # you can open iOS, Android, or web from here, or run them directly with the commands below.
- yarn android
- yarn ios
- yarn web
mehmetkaplan@MACOS:test$ cd app-config-test/
mehmetkaplan@MACOS:app-config-test$ echo "
> export default ({ config }) => {
>   console.log(config.name); // prints 'My App'
>   return {
>     ...config,
>   };
> };
> " > app.config.js
mehmetkaplan@MACOS:app-config-test$ yarn start
yarn run v1.21.1
$ expo start
app-config-test
Starting project at /Users/mehmetkaplan/ActiveCodes/test/app-config-test
app-config-test
Expo DevTools is running at http://localhost:19002
Press d to open DevTools now, or shift-d to always open it automatically.
app-config-test
app-config-test
app-config-test
app-config-test
Starting Metro Bundler on port 19001.
app-config-test
app-config-test
app-config-test

  exp://172.20.10.4:19000

[REMOVED QR CODE]

  To run the app with live reloading, choose one of:
  • Sign in as @mehmetkaplan in Expo client on Android or iOS. Your projects will automatically appear in the "Projects" tab.
  • Scan the QR code above with the Expo app (Android) or the Camera app (iOS).
  • Press a for Android emulator, or i for iOS simulator, or w to run on web.
  • Press e to send a link to your phone with email.

 Expo  Press ? to show a list of all available commands.
Logs for your project will appear below. Press Ctrl+C to exit.
app-config-test

Stopping packager...
› Closing Expo server
› Stopping Metro bundler
Packager stopped.
✨  Done in 71.18s.
mehmetkaplan@MACOS:app-config-test$ 
```

**Comment by brentvatne** [comment]
this is expected behavior. if we changed it to evaluate only once, you would need to restart expo-cli every time you want to make a change to it. this would make the behavior different from app.json. if you'd like to propose a change please open a discussion: https://github.com/expo/expo-cli/discussions

**Comment by dlaynes** [comment]
Hi. We are porting an android app to React Native, and I just noticed the same issue.
We have a custom app.config.ts, which loads a logo and a splash image from a directory based on an environment value. There are dozens of company logos and backgrounds, and putting them in the assets folder is not a good option.

Since the assets folder keeps changing every few seconds, this triggers a reload in the app.

Is there a way to:
1) remove only the assets folder from watchman
2) Use a expo start pre-hook in order to copy the images, or something similar?

Thanks for letting me borrow this thread

**Comment by brentvatne** [comment]
this isn't really related to app.config.js. there is a `watchFolders` option in metro that you can investigate, and [this docs page](https://docs.expo.io/guides/customizing-metro/) tells you how to customize metro config
