### ISSUE TITLE
Prompt users whether they want to init a git project if they are already within a git project

### ISSUE THREAD

**Issue by goofiw** [expo/expo-cli#2378]
## Description

Expo init command initializes a git repo in the target folder.  When using a mono repo, this ends up being a submodule which is undesired behavior.

## Expected Behavior

Expo init should not initialize a git repo.

## Observed Behavior

I thought I had been commiting and adding files by using git commands in the root directory, and running a clean on submodules permanently deleted all the work I had done in the project. 😢 

## Environment

expo 3.22.1
osx 10.15.6
yarn (with workspaces)

**Comment by brentvatne** [comment]
perhaps we should adjust this to prompt the user whether they want to init a git repo if already inside a git repo. otherwise i think this is a reasonable default to keep

**Comment by goofiw** [comment]
@brentvatne does expo need the git history for some commands/file watchers?

**Comment by brentvatne** [comment]
@goofiw - nope, but most developers use git and this is a convenience for people. additionally, some packages installed through npm depend on git, so it's required to have it on your machine to use expo anyhow

**Comment by PiXHULA** [comment]
Hi! 
I actually did this and ended up with a nested git repo. Could anyone be so kind to explain like I'm five on how to remove the git (I've removed the .git files coming with the "expo init" - command). IE make the folder created just being a part of the git created with my backend project? Thanks!

**Comment by EvanBacon** [comment]
rm -rf .git in the new project folder to delete the git project @PiXHULA

**Comment by PiXHULA** [comment]
@EvanBacon Cheers! I guess you'd have to copy the content of .gitignore to the original one aswell?

**Comment by saideepesh000** [comment]
@brentvatne, @EvanBacon, Hey I am working on this.

**Comment by kbrandwijk** [comment]
See: https://github.com/expo/expo-cli/pull/4121
