### ISSUE TITLE
WSL blue screen when running yarn add while running server

### ISSUE THREAD

**Issue by robertwt7** [expo/expo-cli#2379]
## Description

Hey guys, for the past couple of months my company started developing on mobile apps and I chose to use expo as one of the tech stack. Great job guys!

However I realise that for the past few months on when I'm developing on my windows PC, I tend to get a blue/green screen when developing on simulator (android). This doesn't happen on my macbook pro though. It tends to happen when I'm running expo start and do other stuff. 

I have docker running to serve my backend, I don't think having multiple VM affect windows (I already reported at windows forum as well)

This past week I realize and tested that my blue/green screen of death starts on specific action. During `expo start` is running, and if I do `yarn add <package-name>`  then most of the time my pc will crash. I'm not sure if this is an expo bug or not but can anyone reproduce the same issue?

Cheers guys

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

```
> expo diagnostics

  Expo CLI 3.22.3 environment info:
    System:
      OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
      Yarn: 1.22.4 - /usr/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
    npmPackages:
      expo: ~38.0.8 => 38.0.8
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.22.3
```

**Comment by brentvatne** [comment]
this is the first i've heard of this. are you using wsl to run expo-cli? this could be a wsl bug

**Comment by robertwt7** [comment]
Yeah i'm using wsl, with nvm inside wsl... Could be but i just realise it only happens on expo. Doesn't happen when I run package install other things in CRA or NextJS

**Comment by brentvatne** [comment]
could you try moving to wsl2? my understanding is that it's a lot better.

i don't really know what could be causing this, it could be watchman or metro if it's only occurring when you run `yarn add` while the server is running.

**Comment by robertwt7** [comment]
Hmm I did wsl 2 back then but its super slow in accessing the windows drive (where I saved all my projects in).

i'll try to reproduce this in wsl 2 and let you know. 

I actually just saw that issue in WSL! Probably its a wsl bug as well. I'm just not sure, should I close this one if its confirmed there? it appears that plenty of other users are experiencing the same issue there but not here

**Comment by brentvatne** [comment]
yeah let's track the issue on wsl instead because i think we can't do anything here to resolve it
