### ISSUE TITLE
Couldn't adb reverse: adb.exe: error: Invalid source port: 'null'

### ISSUE THREAD

**Issue by bricwood** [expo/expo-cli#2382]
**Description**
When selecting "Run on Android device/emulator" the console logs the error **Couldn't adb reverse: adb.exe: error: Invalid source port: 'null'**.
Expo is then installed on the device, opened and then an error appears: **Something went wrong. Could not load exp://<IP>:80. Network response timed out.**

**Environment**
  Expo CLI 3.22.3 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 14.5.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    npmPackages:
      expo: ~38.0.8 => 38.0.8
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native-web: ~0.11.7 => 0.11.7

I am using an Android Emulator and have tried numerous phone models.

I have looked at previous issues with the same error but they did not help.

**Comment by brentvatne** [comment]
@byCedric - can you investigate this?

**Comment by joelemanoel** [comment]
I have error. Any solution?

**Comment by brentvatne** [comment]
close expo-cli, delete the `.expo` directory within your project, then run `expo start` again

**Comment by bricwood** [comment]
Hi, I have attempted this and instead of the null invalid source port, I now receive:
**Couldn't adb reverse: adb.exe: error: Invalid source port: 'undefined'**

**Comment by turnerguo** [comment]
me too... on Mac: `Couldn't adb reverse: adb: error: Invalid source port: 'undefined'`

**Comment by pablolucio97** [comment]
Me too... on Windows: Couldn't adb reverse: adb.exe: error: Invalid source port: 'null'

**Comment by pablolucio97** [comment]
Looks that expo delays the application starting. In my case, I waited some minutes and then the applications was opened on the emulator.

**Comment by turnerguo** [comment]
It maybe my config issues, I was just add `platform: ['web']` in my `app.json`, after add `['ios', 'android']` (or remove platform config as well, https://docs.expo.io/versions/latest/config/app/#platforms) the problem solved for me. If you met some other strange issues remember type `shift + r` in your console to clean cache and reload app. 
FYI.

**Comment by tertiussc** [comment]
Clearing the cache help for me just run: **expo r -c**

**Comment by Graf-J** [comment]
> close expo-cli, delete the `.expo` directory within your project, then run `expo start` again.
> 
> edit: that is a workaround that will unblock you @joelemanoel, we will come up with a proper fix

**Comment by potier97** [comment]
hi, i have the same problem, what is the status of this problem? any update on sdk 40 for this problem? or do we keep deleting the .expo folder?

Thank you

**Comment by brentvatne** [comment]
@potier97 - you can clear the .expo directory when you run into this for now.

related issues, if you want to contribute an improvement:
- https://github.com/expo/expo-cli/issues/2953
- https://github.com/expo/expo-cli/issues/2952

**Comment by turnerguo** [comment]
Hi @byCedric , is there any update for this issue?

**Comment by EvanBacon** [comment]
We no longer store the majority of process settings in the `.expo` directory. In the latest versioned Expo CLI `npx expo`, the settings are stored in-memory and reset every time the process starts over. We also no longer vendor adb with the project, you must install a global adb that works on your device manually. This means the issue should effectively be resolved. If you encounter this issue again the future, please open an issue on [expo/expo](https://github.com/expo/expo/issues/new?assignees=&labels=needs+review%2CCLI&template=bug_report_cli.yml).
