### ISSUE TITLE
Expo Build APK is crashing on Real Device (Android)

### ISSUE THREAD

**Issue by Haseeba393** [expo/expo-cli#2386]
## Description
I am developing an application using Expo. While development mode, everything is working fine in Expo. Then I build an APK using expo build:android -t apk. After installing the apk, it is crashing on start everytime without showing any error

## Expected Behavior
After installing the app, it should work perfect as it is working in development mode
## Observed Behavior

<!--
Whenever I'm opening the app, it crashes and closes without showing any error. While same app is running perfect in expo development mode
## Environment

<!--

Expo CLI 3.22.1 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 10.19.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
    npmPackages:
      expo: ~38.0.8 => 38.0.8
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7

I'm using Huawei Y7 Prime 2019

## Reproducible Demo
From here you can download the APK to see the issue:
[https://expo.io/artifacts/3b1e5af6-ce4b-4066-abea-a3e258702744](url)

**Comment by brentvatne** [comment]
hi there!

here is some info on how to debug: https://docs.expo.io/workflow/debugging/#production-errors

**Comment by Haseeba393** [comment]
Why you closed the issue without discussions. I have tried almost all
internet for this but nothing come out for me.

**Comment by brentvatne** [comment]
because there is nothing we can do to help you based on the report except guide you to the documentation page with information on how to debug :) once you can share a specific error message then feel free to create an issue with more information.

**Comment by Haseeba393** [comment]
But sir, I tried it and seeing no error message.

**Comment by brentvatne** [comment]
![Screen Shot 2020-07-23 at 7 42 46 PM](https://user-images.githubusercontent.com/90494/88356447-b05ec280-cd1c-11ea-9229-a77eb084a650.png)

following that link to native logs

![Screen Shot 2020-07-23 at 7 43 03 PM](https://user-images.githubusercontent.com/90494/88356458-ba80c100-cd1c-11ea-9abe-9f77014339aa.png)

**Comment by Haseeba393** [comment]
Okay sir, I'll try it out and will revert back to you.
Thanks for the help

**Comment by Haseeba393** [comment]
Sir, I run the application using this command "expo start --no-dev --minify" and it is running fine with zero error on the console as well as on logcat

**Comment by Haseeba393** [comment]
But the issue is same here that after building APK successfully, it is crashing on real devices. I have tried the apk on different Android versions as well 8, 9 and 10 as well

**Comment by brentvatne** [comment]
can you send the build url to secure@expo.io?

**Comment by Haseeba393** [comment]
Okay, I'm sending it to this Email.

**Comment by Haseeba393** [comment]
I have sent the URL to your given Email

**Comment by Haseeba393** [comment]
![image](https://user-images.githubusercontent.com/41360976/88364492-851bb800-cd9c-11ea-93f8-9188e3374508.png)

**Comment by Haseeba393** [comment]
Did you check the APK?

**Comment by Haseeba393** [comment]
In logcat getting some errors. Is it related to the application?
![image](https://user-images.githubusercontent.com/41360976/88378034-a6d76800-cdb9-11ea-88bf-05bbf61775b2.png)

**Comment by Haseeba393** [comment]
I'm waiting for your response. its very urgent and important for me. kindly
help me out in this regard

**Comment by cruzach** [comment]
Hi @Haseeba393, I ran your app and actually encountered quite a few errors in the logs, and it seems like the JS bundle actually runs before the app crashes. If you can provide some minimal code (see [here](https://stackoverflow.com/help/minimal-reproducible-example)) we can use to reproduce this ourselves, rather than just an APK, that would be very helpful

**Comment by Haseeba393** [comment]
I integrated stripe and expo notifications 2 days ago. After that I'm
encountering this problem. Today, I removed expo stripe from app and build
it then apk is working fine. Why is it?
