### ISSUE TITLE
Unable to start the application

### ISSUE THREAD

**Issue by vignesh-manel** [expo/expo-cli#239]
After creating the application and starting it, once the app URL is opened in the browser following error is shown
{"error":"XDLError: ValidationError: child \"urlRandomness\" fails because [\"urlRandomness\" must be a string]"}

And the following error is shown in the developer console

Couldn't start project on Android: /home/pi/.nvm/versions/node/v11.3.0/lib/node_modules/expo-cli/node_modules/xdl/binaries/linux/adb/adb: 1: /home/pi/.nvm/versions/node/v11.3.0/lib/node_modules/expo-cli/node_modules/xdl/binaries/linux/adb/adb: Syntax error: Unterminated quoted string

I have installed expo-cli on Raspberry Pi 3
OS - Raspbian Stretch
Versions tried - latest, 2.5.0, 2.2.0 ,2.0.0

Please help to solve this issue

**Comment by quinlanj** [comment]
hi @vignesh-manel , could you share the contents of your `settings.json` file in `<projectRoot>/.expo/settings.json`? 

Also, to clarify, you are starting your project with `expo start` in order to open the window on the browser?

**Comment by vignesh-manel** [comment]
Content of settings.json                                                                            
{                                                                               
  "hostType": "localhost",                                                      
  "lanType": "ip",                                                              
  "dev": true,                                                                  
  "minify": false,                                                              
  "urlRandomness": null                                                         
}

I  am doing "npm start" which in turn calls "expo start"

**Comment by brentvatne** [comment]
try deleting the `.expo` directory that contains `settings.json` then running `expo start` again
