### ISSUE TITLE
Expo build APK is crashing on devices

### ISSUE THREAD

**Issue by Haseeba393** [expo/expo-cli#2392]
## Description
I'm developing an application using expo. Everything is working fine in development mode. When I made the apk using expo build:android -t apk and test it on really devices then the app is continuously crashing on starting on almost all versions of android.

## Expected Behavior
I want that application should work perfect on real devices as well like in development mode.

## Observed Behavior
Whenever I'm trying to open the application installed through expo built apk then it is crashing. I have check the logcat as well but getting some error and unknown text in it. i don't either it is related to this app or not. I ran the app in production mode as well and it is working fine on expo but through APK it is crashing. These are the errors screenshots:
![image](https://user-images.githubusercontent.com/41360976/88378392-544a7b80-cdba-11ea-9d02-3b2ca3691de4.png)
This one also and some more
Cannot initialize app loader. host.exp.exponent.taskManager.ExpoHeadlessAppLoader

## Environment
Expo CLI 3.22.3 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 10.19.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
    npmPackages:
      expo: ^38.0.0 => 38.0.8
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
Phone: Huawei Y7 prime 2019, Samsung S6 and Oppo F11 Pro

## Reproducible Demo
Here is the apk link which you can check your side as well:
https://expo.io/artifacts/94f6a1f7-8fe2-46c9-9b54-4e729ef7473f

**Comment by Haseeba393** [comment]
I'm checking the logcat and it is showing some exceptions and errors. i don't know are these related to my issue or not. Please have a look:
![image](https://user-images.githubusercontent.com/41360976/88387430-dabb8900-cdcb-11ea-92a5-646ba365f87d.png)
![image](https://user-images.githubusercontent.com/41360976/88387516-09396400-cdcc-11ea-892f-6c13bc13603c.png)

**Comment by Narduzzi** [comment]
I got a similar issue with Expo  38.0.8. 
I am trying to display a video. The application works fine in development mode (`expo start --no-dev`) but crashes when compiled as APK.

Logcat: 

```
AndroidRuntime: FATAL EXCEPTION: main
08-24 13:45:30.001  1049  1049 E AndroidRuntime: Process: com.talk.speechrate, PID: 1049
08-24 13:45:30.001  1049  1049 E AndroidRuntime: java.lang.RuntimeException: Expo encountered a fatal error: RangeError: Maximum call stack size exceeded., stack:
08-24 13:45:30.001  1049  1049 E AndroidRuntime: get@691:5662
08-24 13:45:30.001  1049  1049 E AndroidRuntime: addDep@691:15017
08-24 13:45:30.001  1049  1049 E AndroidRuntime: depend@691:4355
08-24 13:45:30.001  1049  1049 E AndroidRuntime: get@691:5662
08-24 13:45:30.001  1049  1049 E AndroidRuntime: addDep@691:15017
08-24 13:45:30.001  1049  1049 E AndroidRuntime: depend@691:4355
08-24 13:45:30.001  1049  1049 E AndroidRuntime: get@691:5662
08-24 13:45:30.001  1049  1049 E AndroidRuntime: addDep@691:15017
08-24 13:45:30.001  1049  1049 E AndroidRuntime: depend@691:4355
08-24 13:45:30.001  1049  1049 E AndroidRuntime: get@691:5662
08-24 13:45:30.001  1049  1049 E AndroidRuntime: addDep@691:15017
08-24 13:45:30.001  1049  1049 E AndroidRuntime: depend@691:4355
08-24 13:45:30.001  1049  1049 E AndroidRuntime: get@691:5662
08-24 13:45:30.001  1049  1049 E AndroidRuntime: addDep@691:15017
08-24 13:45:30.001  1049  1049 E AndroidRuntime: depend@691:4355
08-24 13:45:30.001  1049  1049 E AndroidRuntime: get@691:5662
08-24 13:45:30.001  1049  1049 E AndroidRuntime: add
08-24 13:45:30.001  1049  1049 E AndroidRuntime: 	at host.exp.exponent.experience.f.o(BaseExperienceActivity.java:7)
08-24 13:45:30.001  1049  1049 E AndroidRuntime: 	at host.exp.exponent.experience.a.run(Unknown Source:2)
08-24 13:45:30.001  1049  1049 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
08-24 13:45:30.001  1049  1049 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-24 13:45:30.001  1049  1049 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
08-24 13:45:30.001  1049  1049 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7078)
08-24 13:45:30.001  1049  1049 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-24 13:45:30.001  1049  1049 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
08-24 13:45:30.001  1049  1049 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
08-24 13:45:30.003  5229  5304 D ViewRootImpl@b0871e1[speechrate]: MSG_RESIZED: frame=[0,0][1080,2220] ci=[0,72][0,144] vi=[0,72][0,144] or=1
08-24 13:45:30.003  5229  5246 D WindowManager: setSystemUiVisibility: vis= 0x8018, fullscreenVis= 0x0, dockedVis= 0x0, win=Window{a513b06 u0 Splash Screen com.talk.speechrate}
08-24 13:45:30.004  1049  1151 I ReactNative: [GESTURE HANDLER] Tearing down gesture handler registered for root view versioned.host.exp.exponent.ReactUnthemedRootView{bf82c48 V.E...... ........ 0,0-1080,2076 #1}
08-24 13:45:30.005  5229  6948 D SamsungPhoneWindowManager: adjustSystemUiVisibilityLw: vis=0x8018
08-24 13:45:30.005  5541  5541 D LightBarController: onNavigationVisibilityChanged : vis = 8018, nbModeChanged = false navigationBarMode = 4
08-24 13:45:30.005  5229  6948 D InputManager-JNI: setSystemUiVisibility dexmode: false changed: true displayid: 0 visibility: 0x8018 DD: 0x8018 OD: 0x0
08-24 13:45:30.010  5229  6841 D Debug   : !@DumpState : SHIP
08-24 13:45:30.010  5229  6841 D Debug   : !@DumpState : debug level:0x4f4c
08-24 13:45:30.010  5229  6841 D Debug   : !@Dumpstate : Finally, system will skip dumpstate
08-24 13:45:30.010  5229  6841 W ActivityManager: crash : com.talk.speechrate,0
08-24 13:45:30.015  5229  6841 W ActivityManager:   Force finishing activity com.talk.speechrate/host.exp.exponent.MainActivity```

**Comment by daanrama** [comment]
i anyone here get fix from this problem? i have same issue
