### ISSUE TITLE
--no-publish doesn't take new native only properties from app.json (config ignore)

### ISSUE THREAD

**Issue by SleeplessByte** [expo/expo-cli#2398]
## Description

From the documatation:
| flag | description |
| --- | --- |
| `--no-publish` | Prevents an OTA update from occurring during the build process. |

From the logs:

```text
 [03:20:19] Looking for releases...
 [03:20:20] Using existing release on channel "live-38.0.8":
 publicationId: <uuid>
   publishedTime: <iso8601>
 [03:20:20] Checking if this build already exists...
 [03:20:20] Did you know that Expo provides over-the-air updates?
 Please see the docs (https://docs.expo.io/guides/configuring-ota-updates/) and check if you can use them instead of building your app binaries again.
 [03:20:20] There were no new changes from the last build, you can download that build from here: https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40<username>/<slug>-<uuid>-signed.aab
```

It's using the previous release (as expected, because `--no-publish`). According to the [limitations on OTA updates](https://docs.expo.io/workflow/publishing/#some-native-configuration-cant-be-updated-by), a new build is required to update these properties. However, in conjunction with the `--no-publish` flag, the new values are not taken into account.

## Expected Behavior

`app.json` is _always_ used, regardless of the `--no-publish` flag

## Observed Behavior

`app.json` is only used when doing a publish. 

## Use case

Released an app with a release channel that is both on iOS and Android. You want to change the icon for android/ios, or add some permissions, etc. You don't want to publish (because nothing has actually changed in the _js bundle_).

**Comment by wkozyra95** [comment]
This is expected behavior

build is always using data from last publish, our workers have access only to manifest (slightly modified app.json) stored on our servers. We are aware of the problem with version updates, but it's hard to change that without breaking anything for people that rely on that behavior.

> Released an app with a release channel that is both on iOS and Android. You want to change the icon for android/ios, or add some permissions, etc. You don't want to publish (because nothing has actually changed in the js bundle).

Publish is uploading js bundle and all assets to our s3 storage, so if you change icon you would still need to publish even if we would change that behavior.

**Comment by SleeplessByte** [comment]
I understand that this is expected behaviour based on the **implementation**, but that is _not_ documented. 

This issue was to highlight that the documentation does not match the reality, so either there is a bug in the code, or in the documentation. Closing this issue doesn't solve either.
