### ISSUE TITLE
Problem validating app.json: Unable to perform cache refresh 

### ISSUE THREAD

**Issue by VibinKesavan** [expo/expo-cli#2399]
Hi All, i had everything working fine, great tool Expo. however, after updating the expo (npm i -g expo --save) i started getting this problem. 

i managed to solve the invalid version issue by adding  "sdkVersion": "38.0.0"  to my app config - but it was working fine before that. don't know why it started appearing now.  struggling to solve "unknown option `--assetExts'" issue here, could you please help ? 

Warning: Problem validating app.json: Unable to perform cache refresh 
for \schema-undefined.json: Error: Request failed with status code 404.
Error: Invalid sdkVersion. Valid options are 7.0.0, 8.0... 38.0.0
error: **unknown option `--assetExts'**
Metro Bundler process exited with code 1
Set EXPO_DEBUG=true in your env to view the stack trace.

app.json

{
  "name": "roughnote",
  "displayName": "roughnote",
  "expo": {
    "name": "roughnote",
    "slug": "roughnote",
    "version": "1.0.0",
    "sdkVersion": "38.0.0",
    "assetBundlePatterns": [
      "**/*"
    ]
  }
}

package.json

{
  "main": "index.js",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "axios": "^0.19.2",
    "deprecated-react-native-listview": "0.0.6",
    "expo": "~38.0.1",
    "expo-status-bar": "^1.0.0",
    "expo-updates": "~0.2.10",
    "random-words": "^1.1.1",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "~0.62.2",
    "react-native-gesture-handler": "~1.6.1",
    "react-native-reanimated": "~1.9.0",
    "react-native-screens": "~2.9.0",
    "react-native-unimodules": "~0.10.1",
    "react-native-vector-icons": "^7.0.0",
    "react-native-web": "~0.11.7",
    "react-navigation": "^2.11.2"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-jest": "~25.2.6",
    "jest": "~25.2.6",
    "prettier": "2.0.5",
    "react-test-renderer": "~16.11.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}

**Comment by LydiaCha** [comment]
I'm having the exact same issue, I've been at it all day and still can't figure out what's going on

**Comment by VibinKesavan** [comment]
bit struggled with the problem - then I have created new react app and moved my code - all good now

**Comment by iFahad94** [comment]
updating your expo cli will fix the issue

`npm install -g expo-cli`

then check the new version
`expo --version`
