### ISSUE TITLE
expo-service-worker.js:93 Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope':

### ISSUE THREAD

**Issue by fadhlaouir** [expo/expo-cli#2403]
## Observed Behavior

```
Error text goes here!
```

**Comment by fadhlaouir** [comment]
expo-service-worker.js:93 Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:19006/service-worker.js' failed to load.     at http://localhost:19006/expo-service-worker.js:93:6

**Comment by brentvatne** [comment]
hi! please follow the issue template

**Comment by OHHAKO** [comment]
hi! how did you handle this issue? i got error same like you.

**Comment by kopax** [comment]
It's not solved and this should be reoponed @brentvatne , there are many unresolved issues left ignored by the expo team! Any chance to get helpful on this one?

## Related issues:

- https://stackoverflow.com/questions/63396049/expo-service-worker-js-93-uncaught-domexception-failed-to-execute-importscrip
- https://github.com/expo/expo-cli/issues/2468
- https://github.com/expo/expo-cli/issues/2063 
- https://forums.expo.io/t/expo-how-to-fix-web-push-notification-in-development-when-accessing-throw-localhost-and-how-to-fix-the-localhost-service-worker/41752
