### ISSUE TITLE
Expo Client App Unresponsive in Debug Mode

### ISSUE THREAD

**Issue by vinayg-me** [expo/expo-cli#2405]
## Description
The expo client app becomes unresponsive when remote debugging is enabled on iPad via LAN. 
But works a bit sluggishly when connected via Tunnel. 
On android tablet, it works sluggishly. 

## Expected Behavior
The app should work as expected without any sluggishness or unresponsiveness. 

## Observed Behavior
The app is totally unresponsive within the expo client. 

## Reproducible Demo

Install latest libraries/clients. 
Open expo client
Enable Remote Debug JS
Reload app and check

**Comment by vinayg-me** [comment]
Diagnostics Information:
Expo CLI 3.23.1 environment info:
System:
OS: Windows 10 10.0.18363
Binaries:
Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
npmPackages:
expo: ^38.0.0 => 38.0.8
react: 16.11.0 => 16.11.0
react-dom: 16.11.0 => 16.11.0
react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
My app stops responding to touches when remote debug js is turned on.
But works fine when I turn off the remote debug js.
Screen Recording: https://drive.google.com/file/d/1222r-HKRvLnrx47ACzCHHCGUty3D6m3D/view?usp=sharing

**Comment by brentvatne** [comment]
this is an upstream react-native issue: when you are debugging on your device, the javascript is being executed in your browser on your computer :(

**Comment by superandrew** [comment]
Hi @brentvatne I have this same issue and thought it was my code.. I understand that is a react native issue. Is there any way to work around this? Or ideas on when it will be solved on expo?

**Comment by superandrew** [comment]
Not sure 100% but so far it seems that expo 40 has fixed the issue, is it possible?

**Comment by superandrew** [comment]
I stand corrected, it seems the issue is still there
