### ISSUE TITLE
Wrong artifactUrl in Webhook data

### ISSUE THREAD

**Issue by anasanzari** [expo/expo-cli#2408]
Data Received: 
```
{ 
"status":"finished", 
"id":"7862b6fe-e9e8-499a-8f19-0284897d022d",
 "artifactUrl":"http://localhost:3000/artifacts/32d119fb-a1f1-4867-9d4e-d0a34af0685f", 
"releaseChannel":"default", "platform":"android"
 }
```

Expected Behavior

Right artifact url is expected

Observed Behavior

artifact url is wrong

Environment: sdk 37

**Comment by brentvatne** [comment]
hi there! this appears to have been an intermittent issue caused by the webhook being fired from the wrong environment on our end. it should not happen again, please create a new issue if it does.
