### ISSUE TITLE
Ejected Android project not getting development URL correctly when built on Windows

### ISSUE THREAD

**Issue by esamelson** [expo/expo-cli#241]
One user has reported issues with their ejected Android build (on Windows) not getting the correct development URL hardcoded into the build. This results in an error like:

```
E/AndroidRuntime: FATAL EXCEPTION: main
Process: Unable to start activity java.lang.IllegalArgumentException: unexpected url: http:
```

A workaround is to manually edit the `DEVELOPMENT_URL` in android\app\src\main\java\host\exp\exponent\generated\DetachBuildConstants.java, but it would be best if we could figure out the source of the problem so everything works out of the box.

Report: https://blog.expo.io/expokit-might-not-be-so-scary-3c26769215fa (see section 6)

**Comment by igorclark** [comment]
Hi, I'm getting this on macOS, and unfortunately this workaround doesn't work. The build process generates DetachBuildConstants.java every time, always reverting the `DEVELOPMENT_URL` to port 80, so the app can never connect to it.

I've worked around it by running a reverse proxy from 80->19000, but it'd be great to know how to fix this properly.

I'm guessing it's something to do with [expo-cli/packages/xdl/src/detach/Detach.js](https://github.com/expo/expo-cli/blob/9d2d17cbc239ba57631b0d7a0eb96f69934c5f1a/packages/xdl/src/detach/Detach.js#L464) but it's kinda deep in there :-)

**Comment by esamelson** [comment]
hey @igorclark - just to make sure, you have `expo start` already running in another terminal window when you build the Android app, correct? If not, try doing that.

**Comment by igorclark** [comment]
Hi @esamelson, sure, it wouldn't work at all otherwise 😬 It works fine when I port-forward or proxy from port 80 to 19000, because the `DEVELOPMENT_URL` sets the packager port as 80 instead of 19000 (which is the problem), so when the phone tries to connect to port 80 and I forward the connection to 19000 it sees the packager and everything connects. But without that, the phone just says it can't connect, and to make sure the packager is running. Which it is, just not on the port the phone's expecting.

**Comment by medicmilos** [comment]
@esamelson that worked for me, thanks!

**Comment by medicmilos** [comment]
> hey @igorclark - just to make sure, you have `expo start` already running in another terminal window when you build the Android app, correct? If not, try doing that.

@esamelson that worked for me, thanks!

**Comment by brentvatne** [comment]
expokit is depreacted now and this works as expected in bare workflow
