### ISSUE TITLE
undefined is not an object, evaluating t.latitude 

### ISSUE THREAD

**Issue by Elijah-trillionz** [expo/expo-cli#2414]
## Description

Expo cli is evaluating an object that doesn't exist only on production mode

## Expected Behavior

It is expected to behave the way it does during development, i am fetching location from Location.getCurrentPositionAsync({}), but it seems working, as i can get the latitude and longitude of the user.

## Observed Behavior
sending the latitude and longitude of the user to the database works fine on development only, during production.

 the app crashes; according to the error sentry gives] it says:::
undefined is not an object, (evaluating t.location) and there is nothing like that in my code

## Environment
System:
OS: Windows 7 6.1.7601
Binaries:
Node: 12.16.3 - C:\Program Files (x86)\nodejs\node.EXE
npm: 6.14.4 - C:\Program Files (x86)\nodejs\npm.CMD
npmPackages:
expo: ~38.0.8 => 38.0.8
react: ~16.11.0 => 16.11.0
react-dom: ~16.11.0 => 16.11.0
react-native: https://github.com/expo/react-native/archive/sdk-38.0.1.tar.
gz => 0.62.2
react-native-web: ~0.11.7 => 0.11.7
react-navigation: ^4.4.0 => 4.4.0.

Phone. Android OS, v29

**Comment by byCedric** [comment]
Hi @Elijah-trillionz, thanks for the issue response. I'm a bit confused about what you mean by `on development only, during production.`. I'm also not 100% sure how this relates to the Expo CLI. If you see this issue in Sentry, from a built standalone app, there is no Expo CLI involved. 

If you can provide an example to reproduce this issue, we can investigate and fix it. For now, the only reason I can think of is that the resolved value of `getCurrentPositionAsync` has no `location` property (see [docs](https://docs.expo.io/versions/latest/sdk/location/#location) and [example](https://snack.expo.io/@bycedric/expo-location)).

Hope this helps!
