### ISSUE TITLE
Couldn't start project on Android: ���⥬� �� 㤠���� ���� 㪠����� ���.

### ISSUE THREAD

**Issue by siteapp** [expo/expo-cli#2417]
[ScreenShot](https://a.radikal.ru/a02/2008/90/81427d442d6d.jpg)

**Why does this happen, expo throws off a strange error?**

`Couldn't start project on Android: ���⥬� �� 㤠���� ���� 㪠����� ���.`

`Error opening simulator. Check Metro logs for details.`

**Comment by brentvatne** [comment]
sorry i have no idea what would be causing this without more information. when you create an issue there is a bunch of text we ask you to fill out, you'll need to create a new issue and answer the questions we ask in that text
