### ISSUE TITLE
Help with ejected App use myself servers

### ISSUE THREAD

**Issue by hnlinzhi19** [expo/expo-cli#242]
# This is a doubt about ejected App 

 Maybe my question is silly, or my English is soso, please give me Help;

When I ecjet my project, at the same time I want to host my App on myself servers;But I do not know
how to set my android studio build or xcode build. I also has run ```expo export -public-url xxx.com/xx```; In my android dir , the hostUri still is exp.host. So I want to get the solution to build my app with my servers;

thanks;

**Comment by brentvatne** [comment]
hi there! @quinlanj will get back to you on this very shortly

**Comment by Charlie-Hua** [comment]
hello @brentvatne, any update about using `public-url` for ejected app?
Thank you!

**Comment by brentvatne** [comment]
hey folks, we're in the process of deprecating expokit and also rebuilding the updates API to work in any react-native app. for now, if your self-hosting use case isn't described on https://docs.expo.io/versions/v35.0.0/distribution/hosting-your-app/ it isn't supported.
