### ISSUE TITLE
App Bundle was not written to the local directory when I used `expo publish`

### ISSUE THREAD

**Issue by deot** [expo/expo-cli#2425]
## Description

App Bundle was not written to the local directory when I used `expo publish`;
This issue came up when I upgraded from `expo@37` to `expo@38`(I also upgraded `expo-cli`)
The local file cannot be found first under release mode（Bare workflow）

## Expected Behavior

The files exist on both the local directory and the server when `expo publish`

- local files
```
./android/app/src/main/assets/app.bundle
./android/app/src/main/assets/app.manifest
./ios/demo/Supporting/app.manifest
./ios/demo/Supporting/app.bundle
```

## Observed Behavior

The file was not written locally, only exists on the server

```
 Expo CLI 3.23.2 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.0.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.23.2
```

## Reproducible Demo

`expo init` then `cd demo && expo publish`

![image](https://user-images.githubusercontent.com/18424466/89450480-305d4180-d78d-11ea-9f96-ebf990d77a69.png)

**Comment by brentvatne** [comment]
this is expected behavior. the bundle is created when you do your build in xcode/android studio. see https://blog.expo.io/over-the-air-updates-from-expo-are-now-even-easier-to-use-376e2213fabf
