### ISSUE TITLE
OTA Update in Bare Workflow taking .expo suffix version of files instead of default

### ISSUE THREAD

**Issue by kgpasta** [expo/expo-cli#2426]
## Description

After publishing an update, when registerRootComponent is called, registerRootComponent.expo.js is executed instead of registerRootComponent.js, causing the error Error: The Expo SDK requires Expo to run. It appears the native Expo modules are unavailable and this code is not running on Expo. Visit https://docs.expo.io to learn more about developing an Expo project

## Expected Behavior

Expect Expo on the Bare Workflow to default to the normal file, not .expo.js suffix version which (I think) is for managed workflow

## Observed Behavior

```
Error: The Expo SDK requires Expo to run. It appears the native Expo modules are unavailable and this code is not running on Expo. Visit https://docs.expo.io to learn more about developing an Expo proje
```

## Environment

Android Pixel 3

Expo CLI 3.23.2 environment info:
System:
OS: macOS 10.15.5
Shell: 5.7.1 - /bin/zsh
Binaries:
Node: 14.5.0 - /usr/local/bin/node
Yarn: 1.22.4 - /usr/local/bin/yarn
npm: 6.14.5 - /usr/local/bin/npm
IDEs:
Android Studio: 3.6 AI-192.7142.36.36.6308749
Xcode: 11.6/11E708 - /usr/bin/xcodebuild
npmPackages:
expo: ^37.0.0 => 37.0.7
react: ~16.9.0 => 16.9.0
react-dom: ~16.9.0 => 16.9.0
react-native: ~0.61.4 => 0.61.5
react-native-web: ~0.11.7 => 0.11.7
react-navigation: ^4.0.10 => 4.3.8

## Reproducible Demo

    Create a blank bare workflow template with expo-cli
    Create release build with expo-updates set to a channel
    Release OTA update to the channel
    App will fail to start

**Comment by kgpasta** [comment]
I believe the culprit is this commit: https://github.com/expo/expo-cli/commit/b125430c2e18e73975cf2c8af3a7f2ece18888ed#diff-151647f2545b8fae9481e4845b54e580 which refactored publishAsync to call `startReactNativeServerAsync`, however, `publishAsync does not pass `target` as an option.

I think the fix would be to change this line https://github.com/expo/expo-cli/blob/b125430c2e18e73975cf2c8af3a7f2ece18888ed/packages/expo-cli/src/commands/publish.ts#L102

to 

`
  const result = await Project.publishAsync(projectDir, {
    releaseChannel: options.releaseChannel,
    quiet: options.quiet,
    target
  });
`

**Comment by brentvatne** [comment]
thank you for catching this and investigating! I am going to try to repro this so I can test a fix

**Comment by brentvatne** [comment]
@kgpasta - that was indeed part of the problem, we also weren't using the default target inside of Project.publishAsync if the option was left out.

fix is in expo-cli@3.23.3

**Comment by brentvatne** [comment]
related commit: https://github.com/expo/expo-cli/commit/b8d426905ddc23f135134171268a483100c19800

**Comment by kgpasta** [comment]
@brentvatne  thank you for the fast response and fix!
