### ISSUE TITLE
Can't update expo cli to 3.23.3

### ISSUE THREAD

**Issue by chkrause** [expo/expo-cli#2430]
## Description

Trying to update to expo cli 3.23.3

## Expected Behavior

Update is working

## Observed Behavior

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@expo/package-manager/-/package-manager-0.0.30.tgz
npm ERR! 404
npm ERR! 404  '@expo/package-manager@0.0.30' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'expo-cli'

## Environment

  Expo CLI 3.22.3 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 14.3.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
    npmPackages:
      expo: ^38.0.0 => 38.0.8
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7

## Reproducible Demo
npm install -g expo-cli

**Comment by dardinier** [comment]
Same problem here :

```
$ yarn global add expo-cli
yarn global v1.22.4
[1/4] Resolving packages...
error Couldn't find package "@expo/build-tools@^0.1.10" required by "expo-cli" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
warning expo-cli > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning expo-cli > react-dev-utils > fork-ts-checker-webpack-plugin > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning expo-cli > react-dev-utils > fork-ts-checker-webpack-plugin > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
Error: Couldn't find package "@expo/dev-tools@0.13.31" required by "expo-cli" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/share/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/share/yarn/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:310:30)
    at /usr/share/yarn/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "@expo/json-file@8.2.22" required by "expo-cli" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/share/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/share/yarn/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:310:30)
    at /usr/share/yarn/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
...
```

**Comment by michaelkleinhenz** [comment]
Same here:

**Comment by dardinier** [comment]
It seems to be a globam problem with scoped packages installation from NPM registry :

https://status.npmjs.org/

Guess we'll just wait for them to fix this problem :shrug:

**Comment by dardinier** [comment]
NPM issues are fixed, no more problem here :)

**Comment by brentvatne** [comment]
i believe this should be resolved now that npm is working properly again :)
