### ISSUE TITLE
ApiV2Error: Not Authorized when launching

### ISSUE THREAD

**Issue by superandrew** [expo/expo-cli#2436]
Upgraded to latest expo-cli, cannot launch on ios anymore

## Expected Behavior
expo r -c

## Observed Behavior
Error below

```
 Expo  Press ? to show a list of all available commands.
ApiV2Error: Not Authorized.
    at ApiV2Client._requestAsync (/@expo/xdl@57.9.28/src/ApiV2.ts:236:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
ApiV2Error: Not Authorized.
    at ApiV2Client._requestAsync (/@expo/xdl@57.9.28/src/ApiV2.ts:236:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

## Environment
 Expo CLI 3.23.3 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.12 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-navigation: ^4.0.10 => 4.3.9 
    npmGlobalPackages:
      expo-cli: 3.23.3

## Reproducible Demo

I am not sure how to reproduce it outside of my computer

**Comment by superandrew** [comment]
I checked and with expo-cli@3.20.3 I don't have this problem

**Comment by superandrew** [comment]
I was logging with another user on expo-cli, not sure if this error has been introduced recently? Feel free to close the issue in case.

**Comment by byCedric** [comment]
When you authenticate, it writes a session token to the expo cache directory. If you logged in with another user in the CLI, it could overwrite this path and possibly messing this up. Glad you got it working anyways 😄

**Comment by chrisdrackett** [comment]
@byCedric not sure if this should be closed. I just ran into this as well and found that downgrading to `3.20.3` also seems to fix the issue. I was trying to run the react-navigation example. Not sure this has anything to do with authentication...

**Comment by ewal** [comment]
Posting even though it's closed. Dunno if this is an actual solution but for me it worked by logging out from the terminal with `expo logout` and after I relaunched expo the message was gone.

**Comment by OneHatRepo** [comment]
I have only run into this when Javascript Debugging is enabled. But when the error happens, I can't disable Javascript Debugging. However, `expo logout` did the trick!

**Comment by husniadil** [comment]
I run in to the same problem today when trying to run the `react-navigation` example project.
Turns out it is caused by the `owner` field in the `app.json`. Just remove it (or change it to match with your Expo username) to make it work.

![image](https://user-images.githubusercontent.com/10581130/100630930-c1b87b00-335d-11eb-9af9-1a3d422d079d.png)

**Comment by icnaves** [comment]
`expo logout` works for me

**Comment by mercurio236** [comment]
npx expo start --offline

**Comment by mercurio236** [comment]
if the error displayed is this
![InkedMicrosoftTeams-image](https://user-images.githubusercontent.com/32252053/200307690-a49067c3-7060-488d-8ce0-6cf298f0286c.jpg)
and in your terminal it is showing only this error
**ApiV2Error: Entity Not Authorized**

first make sure you have expo-cli installed
**https://www.npmjs.com/package/expo-cli**

if you have it installed on your machine, just give the command
npx expo logout

if expo-cli is not installed when trying to run the project it will ask to log in with an account

**Comment by vestimir** [comment]
I had the same issue and changing/removing `owner` didn't help. 

You also need to remove the `eas` part of your `app.json` configuration (if it was set previously by another developer) and it works like a charm!

**Comment by tony-schumacher** [comment]
@vestimir comment was working for me. 
Expo was trying to fetch data from the EAS Project ID.

Very painful problem when trying to work on a flight.

Thank you!

**Comment by gruckion** [comment]
None of the above appears to work for me. @vestimir what "eas" config are you speaking off as I don't see any eas config in the app.json

https://github.com/react-navigation/react-navigation/blob/8f8bf02bb77c85cd7a6451533642451954301a94/example/app.json

**Comment by vpokrityuk** [comment]
@OneHatRepo Thank you so much! `expo logout` fixed everything for me as well

**Comment by kuriel-trivu** [comment]
ApiV2Error: Entity Not Authorized.

Persists.

Same user on expo-cli and expo client.

With extra.eas.projectId defined.

**Comment by xenxei46** [comment]
> I had the same issue and changing/removing `owner` didn't help.
> 
> You also need to remove the `eas` part of your `app.json` configuration (if it was set previously by another developer) and it works like a charm!

thank you this works like magic

**Comment by fahad0samara** [comment]
same error not fix it

**Comment by uwemneku** [comment]
> npx expo start --offline works for me

This worked.

**Comment by nakapon9517** [comment]
Maybe what works with `npx expo start -offline` is not the essential solution.

I was able to solve the problem with the following steps, and I hope it will be helpful to someone else.
1. change `xxx` in the following URL to your organization name
  - https://expo.dev/accounts/xxx/settings/members
2. as shown in the attached picture, specify not a specific person but the unit of the organization listed in the red frame in the app.json > owner section
3. start again with `expo start -clear

I wish you luck in resolving this issue.


![image](https://github.com/expo/expo-cli/assets/62886817/36474a60-c83e-4658-aa4e-e7079088f921)

**Comment by HobaiGuigui** [comment]
just lougout into expo accout by running: expo logout

**Comment by softicnermin** [comment]
One other scenario/solution:
1. delete if exists from app.json
 ```
"eas": {
        "projectId": "......"
      }
```
2. run `eas init` 

This is will add a new projectId to your expo account and update the `app.json`

**Comment by zeealik** [comment]
I got the similar issue and maybe this helps.
https://github.com/expo/eas-cli/issues/1324#issuecomment-1234839617
