### ISSUE TITLE
Unable to install expo-cli

### ISSUE THREAD

**Issue by sudrohit** [expo/expo-cli#2439]
Description
I am unable to install expo client using the command npm install -g expo-cli. 

Expected Behavior
Ideally is should be installed without errors.

Observed Behavior
@Expo/config 3.2.17 no matching package found

Environment
I am installing it on windows 10 64-bit machine.
npm version = 6.14.6
node version = v12.18.3
react-native-cli = 2.0.1

Can someone tell me the near stable version of expo-cli that i can install and the compatible version of npm package, node and react-native-cli if needed. I am new to react native and getting stuck with installation part itself due to this expo cli installation issue.

**Comment by Ycomer** [comment]
you can try `yarn global add expo-cli`,it works for me

**Comment by Unequaled804** [comment]
same issue

**Comment by Rohini1907** [comment]
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @expo/config@3.2.17.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'expo-cli'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xyz\AppData\Roaming\npm-cache\_logs\2020-08-10T08_10_59_976Z-debug.log

Trying to solve this issue from 3days getting the same error

**Comment by byCedric** [comment]
Looks like there is something wrong with the registry you are using. If you use a mirror registry, make sure it's up to date. If you are using the normal registry, try clearing the cache. [`@expo/config` version `3.2.17`](https://www.npmjs.com/package/@expo/config) was published 6 days ago and should be available to download.

Hope it helps!

**Comment by Rohini1907** [comment]
can you brief @byCedric
