### ISSUE TITLE
No icons generated for PWA manifest.json 

### ISSUE THREAD

**Issue by rickysullivan** [expo/expo-cli#2441]
## Description

Generated `manifest.json` does not contain **icons** key.

## Expected Behavior

A `manifest.json` containing an **icons** key with an array of icon objects.

## Observed Behavior

No errors, just a manifest that lacks icons:

```
{
  "display": "standalone",
  "lang": "en",
  "name": "manifest-test",
  "short_name": "manifest-test",
  "start_url": "/?utm_source=web_app_manifest"
}
```

## Environment

Expo CLI 3.23.3 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 14.6.0 - ~/.nvm/versions/node/v14.6.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v14.6.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.9 => 38.0.9
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: ~0.62.2 => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.23.3

➜ sharp --version
1.14.1

## Reproducible Demo

https://github.com/rickysullivan/manifest-test

**Comment by rickysullivan** [comment]
I take it back. Icons are generate during a `web:build` but not during development.

**Comment by claudioviola** [comment]
Hello @rickysullivan 
I would open it again since I face same issue.

App config here:

```
    name: "myapp",
    icon: "./assets/production/icon.png",
    orientation: 'portrait',
```

I run `expo-pwa manifest`

this is the result of the manifest.json

```
{
  "background_color": "#012C3D",
  "display": "standalone",
  "lang": "en",
  "name": "myapp",
  "short_name": "myapp",
  "start_url": "/?utm_source=web_app_manifest",
  "orientation": "portrait",
}
```


The version of expo-pwa is `0.0.125`

If it could be relevant here I will drop expo info details

 ```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.13.0/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.0.4
      expo: ^48.0.0 => 48.0.17
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
      react-native-web: ~0.18.7 => 0.18.12
    npmGlobalPackages:
      eas-cli: 3.13.0
      expo-cli: 6.1.0
    Expo Workflow: managed
```

**Comment by hbcondo** [comment]
Same issue. The [Expo PWA instructions](https://docs.expo.dev/guides/progressive-web-apps/) shows that the `icons` property will be generated in the manifest,json by specifying the `icon` property in the app.json (or app.config.json) file but no icon information is generated. Due to this, the manifest.json file isn't deemed valid:

> Manifest does not contain a suitable icon - PNG format of at least 144px is required, the sizes attribute must be set, and the purpose attribute, if set, must include "any"
