### ISSUE TITLE
running expo:install:android is not installing the newest version of expo client on emulator

### ISSUE THREAD

**Issue by dnovacik** [expo/expo-cli#2447]
## Description

I've upgraded my project to use new expo 38.0.0 but I can't run it anymore on my android emulator. I've ran command expo client:install:android but it won't install the newest version (2.16.1) but 2.15.4 (which has no support for SDK 38).

My VD is Pixel 3a XL running Android API 30 x86

## Expected Behavior

I should be able to install newest expo client on my emulated device to use the project

## Observed Behavior

The installed expo client is of lower version (and not fitting for the new SDK)

Command output
```
# expo client:install:android
? You are currently using SDK 38.0.0. Would you like to install client 2.16.1 released for this SDK? Yes
Uninstalling Expo from Android device.
Installing Expo on device
Done!
```

## Environment

  Expo CLI 3.24.0 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.3.2 - C:\Users\ra6e\AppData\Roaming\npm\yarn.CMD
      npm: 6.5.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5900203
    npmPackages:
      expo: ^38.0.0 => 38.0.9
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7

Android Virtual Device via Android Studio - Pixel 3a XL running Android API 30 x86

## Additional Info

I am able to run the project just fine on my physical android device via expo app

## Workaround
I was able to just install it from the apk via downloading from https://expo.io/tools

**Comment by bill-pairaktaridis** [comment]
Yeah, I've encountered that too. It seems to always install an older version of the app, for some reason.
