### ISSUE TITLE
[xdl] Fix publish test that is timing out on CI

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#2463]
https://github.com/expo/expo-cli/blob/c900edc9f612904bed4eef92b2df166c422a5d24/packages/xdl/src/__tests__/Project-publishAsync-test.ts#L121-L133

I tried increasing the timeout 60 seconds and it still times out. Runs on my local machine fine. I ignored the test for now with `xit`

**Comment by EvanBacon** [comment]
This is no longer relevant.
