### ISSUE TITLE
Expo Web App in a Subdirectory Results in Wrong URL

### ISSUE THREAD

**Issue by Siyavoshi** [expo/expo-cli#2465]
I apologize in advance if I'm asking this question in the wrong repository.

## Description
I'm using react-navigation v4 + @react-navigation/web alongside Expo 38 bare workflow.
I added  `"homepage": "http://localhost/mypwa/"` to the package.json file.
I run expo build:web then copy the contents of web-build to WAMP's www/mypwa/ folder.

When I open up my PWA, the project starts just fine but the URL is incorrect.
Same results for when I run `yarn web`.
I expect the first URL to be `localhost/mypwa/LoginScreen` but it's actually `localhost/LoginScreen`.
Now this doesn't ruin my pwa or anything since I can navigate through the app just fine.
The problem is when I "Add to Home Screen" the URL, my website's main page is added to the homescreen instead of the PWA.

I also implemented react navigation's web container:
`const AppContainer = isWeb ? createBrowserApp(AppSwitchNavigator) : createAppContainer(AppSwitchNavigator);`

I haven't modified webpack.config.js since I don't know enough about webpack.

**Comment by EvanBacon** [comment]
React Navigation v4 doesn't support web. Please upgrade to V5 and use the linking https://reactnavigation.org/docs/deep-linking/#universal-links

**Comment by byronigoe** [comment]
So, 2 and a half years later, this is still a problem. Now create-expo-app uses React Navigation 6, which still does not support web deployment to a subfolder. The [documentation of Linking.prefixes](https://reactnavigation.org/docs/configuring-links#prefixes) even says that it is ignored on the web.

The only reason I'm considering Expo is so I can build once and deploy to both native devices and the web (in a subfolder). There's an [open bounty](https://stackoverflow.com/questions/75793589/deploy-expo-react-native-web-app-to-a-subfolder) for a solution.
