### ISSUE TITLE
Expo: How to fix web push notification in development when accessing throw localhost (and how to fix the `localhost` service worker)?

### ISSUE THREAD

**Issue by kopax** [expo/expo-cli#2468]
Please provide the following:

1. SDK Version: 36
2. Platforms(Android/iOS/web/all): web

When I access my app in development with  `htt://$ip:19006` , it work fine, but when I try to access with  `http://localhost:19006`  in order to use the geolocation, I have this error :

```
Failed to register service-worker DOMException: Failed to register a ServiceWorker for scope ('http://localhost:19006/') with script ('http://localhost:19006/expo-service-worker.js'): The script has an unsupported MIME type ('text/html').
```

This is problematic to developer web push notification as only `localhost` can work without when `HTTPS` is not used.

How can I fix it?

## Related issues

- https://github.com/expo/expo-cli/issues/2063 
- https://github.com/expo/expo-cli/issues/2403
- https://stackoverflow.com/questions/63396049/expo-service-worker-js-93-uncaught-domexception-failed-to-execute-importscrip
- https://forums.expo.io/t/expo-how-to-fix-web-push-notification-in-development-when-accessing-throw-localhost-and-how-to-fix-the-localhost-service-worker/41752

**Comment by kopax** [comment]
I have discovered hosted the expo-service-worker file at http://localhost:4001/expo-service-worker.js but when my site try to load it, it tries using the url we access it from http://localhost:19006 and fail ending on unexisting route http://localhost:19006/expo-service-worker.js which fallback in a wildcard that return the index.html, is there a way to fix this?

**Comment by EvanBacon** [comment]
In the latest webpack-config [we've removed support for Workbox](https://github.com/expo/expo-cli/pull/3729), going forward we'll be supporting service worker related features in user-space rather than inside the CLI
