### ISSUE TITLE
console logs appear twice in the console: both react-native logger and expo logger output at the same time

### ISSUE THREAD

**Issue by CostachescuCristinel** [expo/expo-cli#2469]
## Description
In a project I have, for every `console.log` call will get duplicate prints in the console, due to both expo's logger and react-native's logger outputting the same message. The following is an extract of the project logs, as soon as the project starts up:

```
 Expo  Press ? to show a list of all available commands.
Logs for your project will appear below. Press Ctrl+C to exit.
[Mon Aug 17 2020 18:35:43.160]  BUNDLE  node_modules/expo/AppEntry.js 
Running application on iPhone 11 Pro Max.
[Mon Aug 17 2020 18:36:06.926]  LOG      Running "main" with {"rootTag":1,"initialProps":{"exp":{"manifest":{"developer":{"projectRoot":"/Users/work00/Documents/Projects/MyProject","tool":"expo-cli"},"mainModuleName":"node_modules/expo/AppEntry","privacy":"unlisted","assetBundlePatterns":["**/*"],"hostUri":"192.168.0.131:19000","xde":true,"env":{},"orientation":"portrait","bundleUrl":"http://192.168.0.131:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false","android":{"package":"com.project.my","useNextNotificationsApi":true},"id":"@my-username/MyProject","sdkVersion":"38.0.0","userInterfaceStyle":"automatic","iconUrl":"http://192.168.0.131:19001/assets/./assets/icon.png","name":"MyProject","loadedFromCache":false,"version":"0.1.2","platforms":["ios","android"],"icon":"./assets/icon.png","logUrl":"http://192.168.0.131:19000/logs","ios":{"supportsTablet":true,"bundleIdentifier":"com.project.my","infoPlist":{"NSFaceIDUsageDescription":"Used to allow signing in"}},"isVerified":true,"splash":{"resizeMode":"contain","backgroundColor":"#ffffff","image":"./assets/splash.png","imageUrl":"http://192.168.0.131:19001/assets/./assets/splash.png"},"updates":{"enabled":false,"checkAutomatically":"ON_ERROR_RECOVERY","fallbackToCacheTimeout":0},"debuggerHost":"192.168.0.131:19001","slug":"Project","packagerOpts":{"urlRandomness":null,"https":false,"minify":false,"hostType":"lan","dev":true,"lanType":"ip"}},"appOwnership":"expo","initialUri":"exp://192.168.0.131:19000","shell":0}}}
[Main::onStartLoading] INITIALIZING APP
[Main::initializeDeviceInfo] Detecting device info
[Redux::dispatch] (function) detectTypeAndRootAsync
[Redux::dispatch] DEVICE_DETECTTYPEANDROOT { deviceType: 1, isRooted: false (boolean) }
[Main::initializeFonts] Loading fonts
[Main::initializeTheme] Loading user preference
[Redux::dispatch] (function) changeUserThemeAsync
[Redux::dispatch] THEME_CHANGEUSERTHEME { system: "light", user: "system" }
[Main::initializeTheme] Detecting system theme
[Redux::dispatch] (function) changeSystemThemeAsync
[Redux::dispatch] THEME_CHANGESYSTEMTHEME { system: "light", user: "system" }
[Main::initializeTheme] Subscribing for system theme changes
[Main::initializePushNotifications] Obtaining push notifications token from Expo
[Mon Aug 17 2020 18:36:06.926]  LOG      [Main::onStartLoading] INITIALIZING APP
[Mon Aug 17 2020 18:36:06.927]  LOG      [Main::initializeDeviceInfo] Detecting device info
[Mon Aug 17 2020 18:36:06.927]  LOG      [Redux::dispatch] (function) detectTypeAndRootAsync
[Mon Aug 17 2020 18:36:06.928]  LOG      [Redux::dispatch] DEVICE_DETECTTYPEANDROOT { deviceType: 1, isRooted: false (boolean) }
[Mon Aug 17 2020 18:36:06.928]  LOG      [Main::initializeFonts] Loading fonts
[Mon Aug 17 2020 18:36:06.947]  LOG      [Main::initializeTheme] Loading user preference
[Mon Aug 17 2020 18:36:06.953]  LOG      [Redux::dispatch] (function) changeUserThemeAsync
[Mon Aug 17 2020 18:36:06.954]  LOG      [Redux::dispatch] THEME_CHANGEUSERTHEME { system: "light", user: "system" }
[Mon Aug 17 2020 18:36:06.954]  LOG      [Main::initializeTheme] Detecting system theme
[Mon Aug 17 2020 18:36:06.954]  LOG      [Redux::dispatch] (function) changeSystemThemeAsync
[Mon Aug 17 2020 18:36:06.955]  LOG      [Redux::dispatch] THEME_CHANGESYSTEMTHEME { system: "light", user: "system" }
[Mon Aug 17 2020 18:36:06.955]  LOG      [Main::initializeTheme] Subscribing for system theme changes
[Mon Aug 17 2020 18:36:06.955]  LOG      [Main::initializePushNotifications] Obtaining push notifications token from Expo
[Main::initializePushNotifications] Error while initializing push notifications token: [Error: Notification registration failed: remote notifications are not supported in the simulator]
[Main::initializeAuthentication] Detecting device features
[Redux::dispatch] AUTH_SIGNIN_CHANGEBIOMETRIC { hasHardware: true (boolean), isEnrolled: false (boolean) }
[Main::initializeAuthentication] Loading authentication data
[Mon Aug 17 2020 18:36:06.972]  LOG      [Main::initializePushNotifications] Error while initializing push notifications token: [Error: Notification registration failed: remote notifications are not supported in the simulator]
[Mon Aug 17 2020 18:36:06.975]  LOG      [Main::initializeAuthentication] Detecting device features
```
The project in question is the only project that I have that displays this behavior. Most of the times, react-native's logger will output before expo's, but can also happen the other way around.

The original project was started on Expo SDK 36, regularly upgraded up to the current SDK 38. The issue first appeared after the upgrade from SDK 37 to 38. The first times, I was able to get rid of the issue by creating a new project (`expo init`, blank project) and moving over the files from the old project to the newly created one. This would restore only expo's logger output. However, now, this does not work anymore.

## Expected Behavior
Only expo's logger output should be printed to the console.

## Observed Behavior
Both react-native's logger and expo's logger will print to the console the same messages.
Sometimes I would also see these errors:
`Console.error: "There was a problem sending log messages to your development environment", Error: Out of memory`
To be fair, I am not sure if this error is related to the issue I'm describing.

## Environment
expo diagnostics
```
  Expo CLI 3.24.0 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.2 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.8 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7
```

package.json
```
{
	"main": "node_modules/expo/AppEntry.js",
	"scripts": {
		"start": "expo start",
		"startp": "NODE_ENV='production' && expo start --no-dev --minify"
	},
	"dependencies": {
		"@eva-design/eva": "^2.0.0",
		"@eva-design/material": "^2.0.0",
		"@react-native-community/masked-view": "0.1.10",
		"@react-navigation/bottom-tabs": "^5.6.1",
		"@react-navigation/material-top-tabs": "^5.2.12",
		"@react-navigation/native": "^5.6.1",
		"@react-navigation/stack": "^5.6.2",
		"@ui-kitten/components": "^5.0.0",
		"axios": "^0.19.2",
		"base-64": "^0.1.0",
		"buffer": "^5.6.0",
		"expo": "^38.0.0",
		"expo-barcode-scanner": "~8.2.1",
		"expo-constants": "~9.1.1",
		"expo-device": "~2.2.1",
		"expo-document-picker": "~8.2.1",
		"expo-file-system": "~9.0.1",
		"expo-font": "~8.2.1",
		"expo-image-picker": "~8.3.0",
		"expo-jwt": "^1.3.0",
		"expo-linear-gradient": "~8.2.1",
		"expo-local-authentication": "~9.1.1",
		"expo-notifications": "~0.3.3",
		"expo-permissions": "~9.0.1",
		"expo-secure-store": "~9.0.1",
		"expo-status-bar": "^1.0.0",
		"form-data": "^3.0.0",
		"querystring": "^0.2.0",
		"react": "16.11.0",
		"react-dom": "16.11.0",
		"react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
		"react-native-appearance": "~0.3.3",
		"react-native-gesture-handler": "~1.6.0",
		"react-native-reanimated": "~1.9.0",
		"react-native-safe-area-context": "~3.0.7",
		"react-native-screens": "~2.9.0",
		"react-native-svg": "12.1.0",
		"react-native-tab-view": "^2.14.4",
		"react-native-web": "~0.11.7",
		"react-redux": "^7.2.0",
		"react-refresh": "^0.8.3",
		"redux": "^4.0.5",
		"redux-thunk": "^2.3.0"
	},
	"devDependencies": {
		"@babel/core": "^7.10.4",
		"@ui-kitten/metro-config": "^5.0.0",
		"babel-eslint": "^10.1.0",
		"babel-plugin-transform-remove-console": "^6.9.4",
		"babel-preset-expo": "^8.2.3",
		"eslint": "^7.4.0",
		"eslint-plugin-react": "^7.20.3",
		"eslint-plugin-react-native": "^3.8.1",
		"metro-config": "^0.58.0",
		"react-native-svg-transformer": "^0.14.3"
	},
	"private": true
}
```

metro.config.js
```
const MetroConfig = require("@ui-kitten/metro-config");
const defaultConfig = require("metro-config/src/defaults").getDefaultValues();

const evaConfig = {
	evaPackage: "@eva-design/eva",
	// Optional, but may be useful when using mapping customization feature.
	customMappingPath: "./theme/mapping.json",
};

module.exports = MetroConfig.create(evaConfig, {
	transformer: {
		babelTransformerPath: require.resolve("react-native-svg-transformer"),
	},
	resolver: {
		assetExts: defaultConfig.resolver.assetExts.filter(ext => ext !== "svg"),
		sourceExts: [...defaultConfig.resolver.sourceExts, "svg"]
	},
});
```

babel.config.js
```
module.exports = function (api) {
	api.cache(true);

	// console.log(process.env);
	if ((process.env.NODE_ENV === "production") || (process.env.BABEL_ENV === "production")) {
		return {
			presets: ["babel-preset-expo"],
			plugins: ["transform-remove-console"]
		};
	}

	return {
		presets: ["babel-preset-expo"]
	};
};
```

## Reproducible Demo
~~This project is too big and complex to build a minimal version that reproduces the issue. I am not sure how to help with this...~~

Reproducible demo added in this post: https://github.com/expo/expo-cli/issues/2469#issuecomment-778110706

**Comment by izzetkalic** [comment]
Same here. It started after I upgrade expo sdk 36 to 39.

**Comment by m4ttheweric** [comment]
This is also happening for me on Expo 39.

**Comment by jameslouiz** [comment]
Do you have a simulator AND a real device running?

**Comment by CostachescuCristinel** [comment]
Hi, I have managed to reduce my original project into a small reproducible demo. You can find it below.
[my-app.zip](https://github.com/expo/expo-cli/files/5971032/my-app.zip)

Run `yarn install`, then `expo start`, and watch the messages appearing in the console.

**Comment by m4ttheweric** [comment]
pls keep this thread updated if you find a solution. this is still happening to me as well.

**Comment by CostachescuCristinel** [comment]
@m4ttheweric Could not find a solution, or the root cause of the issue. Since I initially posted, I have ejected the project, and now I'm running react-native directly. Without some expo devs' help, it was far too much to look into on my own, so I just lived with it for the time being.

Should anyone try to look into this, if still relevant for expo SDK 39+, I had some feeling that something was messing with any post-install scripts in the npm packages, or with the metro bundler.
For instance, the project (attached above) uses `UI Kitten`, with theme pre-compilation run during bundle time.
It also uses `babel-plugin-transform-remove-console`, which by mistake may remove any expo-cli customization to the `console.xxx` functions.

I haven't tested all these, but maybe it's a further head start for who may look further into this.

@m4ttheweric As I said in my first post here, sometimes I was able to "fix" the issue by creating a new blank project (`expo init`) and porting over the sources. Sometimes I would only copy `package.json` at first, run `npm install`/`yarn`, and then port the other source files. Sorry, not sure how to help further...

**Comment by m4ttheweric** [comment]
I found a solution:

Comment out or remove the metro.config.js file from your project. This is something that ui-kitten uses to allegedly improve performance. 

You can read more about it here:

https://akveo.github.io/react-native-ui-kitten/docs/guides/improving-performance#improving-performance

When I comment out the metro config (and I also remove the `mapping` prop from the ui-kitten `ApplicationProvider` since it's no longer applicable) the logs only appear once now!

**Comment by EvanBacon** [comment]
My understanding is that this issue was resolved in the CLI around February, but it seems that some configurations (like ui-kitten) are causing similar issues to occur.

To add some more information; Expo uses a custom system for sending logs to the CLI:

`expo` package has [runtime code](https://github.com/expo/expo/blob/50661f5c77b26c1192492496b17ed251d4965ff0/packages/expo/src/logs/RemoteLogging.ts#L122-L126) that sends console logs to an endpoint `/logs` which expo-cli listens to in the dev server [here](https://github.com/expo/expo-cli/blob/master/packages/dev-server/src/middleware/clientLogsMiddleware.ts)

Whereas react-native has [runtime code](https://github.com/facebook/react-native/blob/19f8d2f7da13f4524f31acf7aa10cc0aa91b5da4/Libraries/Utilities/HMRClient.js#L118-L135) that sends logs to the Metro bundler via WebSockets, those socket messages are then listened to in expo-cli [here](https://github.com/expo/expo-cli/blob/1375d6eea5dd112331244d6800996c62c983b0da/packages/xdl/src/logs/PackagerLogsStream.ts#L310-L311) and then promptly ignored.
 
We also get rid of some default logs (like the giant metro/react ascii logos) [here](https://github.com/expo/expo-cli/blob/1375d6eea5dd112331244d6800996c62c983b0da/packages/metro-config/src/ExpoMetroConfig.ts#L159-L161). 

We do this because we wanted the simplest and cleanest system for sending logs from runtime to client, our approach is also agnostic to the Metro bundler, enabling users to switch bundlers as they see fit.

If someone adds some nonstandard code to their `metro.config.js`, then weird logging issues could occur.

Because this issue cannot be repro'd in Expo SDK 42, I'd recommend we close this issue so similar issues with different root causes can get better help.

**Comment by Codelica** [comment]
@EvanBacon so would you prefer a new issue for this behavior (that I'm seeing with SDK 42) triggered by the "recommended" Metro config addition for Kitten UI?  (below for reference)

```js
const MetroConfig = require('@ui-kitten/metro-config');

const evaConfig = {
  evaPackage: '@eva-design/eva',
  customMappingPath: './path-to/mapping.json',
};

module.exports = MetroConfig.create(evaConfig, {
  // Whatever was previously specified
});
```

I'm way out of my element on this configuration, but am guessing Expos config is getting lost in the process and should be included in some way.  Thanks..

**Comment by CostachescuCristinel** [comment]
There is also an async config variant that could be explored. It allows to import `@expo/metro-config` and use it for the custom config. Following is from [an answer by `artyorsh`](https://github.com/akveo/react-native-ui-kitten/issues/1371#issuecomment-796533835) on an issue I opened in the `akveo/react-native-ui-kitten` github page:

```js
// imports added for clarity of the code
const UIKittenMetroConfig = require('@ui-kitten/metro-config');
const { getDefaultConfig } = require("@expo/metro-config");

module.exports = (async () => {
	const { resolver: { sourceExts, assetExts } } = await getDefaultConfig(__dirname);

	return UIKittenMetroConfig.create({
		evaPackage: "@eva-design/eva",
		customMappingPath: "./theme/mapping.json",
	}, {
		transformer: {
			assetPlugins: ['expo-asset/tools/hashAssetFiles'],
			babelTransformerPath: require.resolve("react-native-svg-transformer")
		},
		resolver: {
			assetExts: assetExts.filter(ext => ext !== "svg"),
			sourceExts: [...sourceExts, "svg"]
		},
	});
})();
```

At the time I opened that issue I had already ejected the project, and didn't experience this original issue anymore (expo-cli was not being used anymore).  
However, you can notice that only `{ sourceExts, assetExts }` have been destructured from the expo metro config. I suppose that there is more that should be included from it?
