### ISSUE TITLE
Cannot find module 'expo/tools/LogReporter'

### ISSUE THREAD

**Issue by lc3t35** [expo/expo-cli#247]
## Description
I've updated to expo-cli 2.6.8 for my project and I can't run "expo start" anymore, as I have this error message : 
```
expo start
[17:33:07] Starting project at /Users/laurent/Work/....
[17:33:07] Expo DevTools is running at http://localhost:19002
[17:33:07] Opening DevTools in the browser... (press shift-d to disable)
[17:33:10] Cannot find module 'expo/tools/LogReporter'
[17:33:10] Set EXPO_DEBUG=true in your env to view the stack trace.
````
with EXPO_DEBUG=true we have :
````
[17:52:38] Error: Cannot find module 'expo/tools/LogReporter'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.resolveModule (/xdl@52.0.8/src/project/ProjectUtils.js:137:18)
    at /xdl@52.0.8/src/Project.js:1489:41
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/expo-cli/node_modules/xdl/build/Project.js:2211:191)
    at /usr/local/lib/node_modules/expo-cli/node_modules/xdl/build/Project.js:2211:361
    at <anonymous>
````
Of course I made before : yarn install, I can check that node_modules/expo/tools/LogReporter is present here.
I've already seen this : https://stackoverflow.com/questions/49151286/expo-cannot-find-a-module-logreporter?rq=1

same behaviour if I remove yarn.lock and use npm install

I can see that project/ProjectUtils.js was changed 5 days ago by https://github.com/expo/expo-cli/pull/140

## Environment
````
Expo CLI 2.6.8 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.4 - /usr/local/bin/node
      Yarn: 1.12.3 - ~/.yarn/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.2 => 31.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
      react-navigation: ^2.18.2 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.6.8
````

## Reproducible Demo
I've started with a fresh new project (expo init with tabs template) -> same behaviour

I've already seen this : https://stackoverflow.com/questions/49151286/expo-cannot-find-a-module-logreporter?rq=1

````
cd .expo/
pc162:.expo laurent$ ls
packager-info.json	settings.json
pc162:.expo laurent$ more packager-info.json 
{
  "devToolsPort": 19002,
  "expoServerPort": 19000
}
pc162:.expo laurent$ more settings.json 
{
  "hostType": "lan",
  "lanType": "ip",
  "dev": true,
  "minify": false,
  "urlRandomness": null
}
````
and package.json (generated by expo init) is 
````
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject",
    "test": "node ./node_modules/jest/bin/jest.js --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/samples": "2.1.1",
    "expo": "^31.0.2",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz",
    "react-navigation": "^2.18.2"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0",
    "jest-expo": "^31.0.0"
  },
  "private": true
}
````
same behaviour if I remove yarn.lock and use npm install
same behaviour with 2.6.6
**WORDAROUND : rollback to expo-cli 2.4.3**

**Comment by daminebenz** [comment]
same problem and i'm loosing time cause of this

**Comment by lc3t35** [comment]
@daminebenz rollback with `npm install -g expo-cli@2.4.3` (I spent 4 hours to find where it came from and document this issue)

**Comment by Johnsonzhangc** [comment]
@lc3t35 Thanks very much! I also met the same problem today, and then it turns to "react native is not installed" error, but it's fine when coming to version 2.4.3.

**Comment by fson** [comment]
@lc3t35 thanks for reporting this issue. Could you tell me the output from the following commands inside your project folder?

```
node -v
node -e "console.log(require.resolve('expo/tools/LogReporter'))"        
node -e "console.log(require.resolve('expo/tools/LogReporter', {paths:[process.cwd()]}))"
ls -al $(node -e "console.log(require.resolve('expo/tools/LogReporter'))")
```

**Comment by daminebenz** [comment]
@lc3t35 
mdamine@SSWDES-1010 MINGW64 /d/app (master)
$ node -v
v8.9.4

mdamine@SSWDES-1010 MINGW64 /d/app (master)
$ node -e "console.log(require.resolve('expo/tools/LogReporter'))"
D:\app\node_modules\expo\tools\LogReporter.js

mdamine@SSWDES-1010 MINGW64 /d/app (master)
$ node -e "console.log(require.resolve('expo/tools/LogReporter', {paths:[process.cwd()]}))"
D:\app\node_modules\expo\tools\LogReporter.js

mdamine@SSWDES-1010 MINGW64 /d/app (master)
$

mdamine@SSWDES-1010 MINGW64 /d/app (master)
$ node -e "console.log(require.resolve('expo/tools/LogReporter', {paths:[process.cwd()]}))"
D:\app\node_modules\expo\tools\LogReporter.js

mdamine@SSWDES-1010 MINGW64 /d/app (master)
$ ls -al $(node -e "console.log(require.resolve('expo/tools/LogReporter'))")
stdout is not a tty
total 439
drwxr-xr-x 1 mdamine 1049089      0 déc.  10 10:56 ./
drwxr-xr-x 1 mdamine 1049089      0 déc.  10 09:12 ../
drwxr-xr-x 1 mdamine 1049089      0 déc.  10 10:54 .expo/
drwxr-xr-x 1 mdamine 1049089      0 déc.   7 15:46 .git/
-rw-r--r-- 1 mdamine 1049089     74 oct.  26  1985 .gitignore
-rw-r--r-- 1 mdamine 1049089      3 oct.  26  1985 .watchmanconfig
-rw-r--r-- 1 mdamine 1049089     56 déc.  10 10:53 App.js
-rw-r--r-- 1 mdamine 1049089    899 déc.   7 17:15 app.json
drwxr-xr-x 1 mdamine 1049089      0 déc.  10 10:24 assets/
-rw-r--r-- 1 mdamine 1049089    107 oct.  26  1985 babel.config.js
drwxr-xr-x 1 mdamine 1049089      0 déc.  10 10:56 fonts/
drwxr-xr-x 1 mdamine 1049089      0 déc.  10 10:58 node_modules/
-rw-r--r-- 1 mdamine 1049089    863 déc.  10 10:58 package.json
drwxr-xr-x 1 mdamine 1049089      0 déc.  10 11:00 src/
-rw-r--r-- 1 mdamine 1049089 276580 déc.  10 10:58 yarn.lock

mdamine@SSWDES-1010 MINGW64 /d/app (master)

**Comment by lc3t35** [comment]
```
pc162:sharesapp laurent$ node -v
v8.9.4
pc162:sharesapp laurent$ node -e "console.log(require.resolve('expo/tools/LogReporter'))"
/Users/laurent/Work/fame/v1/sharesapp/node_modules/expo/tools/LogReporter.js
pc162:sharesapp laurent$ node -e "console.log(require.resolve('expo/tools/LogReporter', {paths:[process.cwd()]}))"
/Users/laurent/Work/fame/v1/sharesapp/node_modules/expo/tools/LogReporter.js
pc162:sharesapp laurent$ ls -al $(node -e "console.log(require.resolve('expo/tools/LogReporter'))")
-rw-r--r--  1 laurent  staff  351  9 déc 17:15 /Users/laurent/Work/fame/v1/sharesapp/node_modules/expo/tools/LogReporter.js
````

**Comment by fson** [comment]
Thanks for all the information. This has been fixed in the latest version of `expo-cli`.

**Comment by abdrmdn** [comment]
`sudo npm uninstall expo-cli`
fixed it for me

**Comment by happykennedy** [comment]
Still having this issue as of latest expo release

**Comment by parthvyas7** [comment]
Still having this issue as of latest expo release

**Comment by dvetal** [comment]
There has been a new release since the comments above and just a note I am still having this issue on the latest release. (SDK35)

**Comment by LokeshLM** [comment]
@abdrmdn Thanks for updates. We need to uninstall **expo-cli** within a application and globally. and reinstall globally. it resolves my problem.

npm uninstall expo-cli
npm uninstall -g expo-cli

npm install -g expo-cli
