### ISSUE TITLE
No console log output in expo terminal

### ISSUE THREAD

**Issue by whitecolor** [expo/expo-cli#2470]
## Description
I'm trying to setup expo project inside a monorepo with a help of custom metro resolver. So i'm running the simplest app. So far app actually launches and works normal way with hot reload, etc.

The problem that I don't see any output in the terminal made by `console.log` in RN app (App.tsx).  It works in standard setup (with yarn repo). So I wonder what can be the reason for such issue, where should I dig in?

Btw `console.warn` appear in yellow box on the device screen, but not in the terminal.

## Expected Behavior

See terminal console.log output.

## Environment

Windows 10, Android emulator.

**Comment by whitecolor** [comment]
Managed to turn it on with this:
```
import { Logs } from 'expo'

Logs.enableExpoCliLogging()
```

So I wonder why I don't have to do this in the standard setup?

**Comment by byCedric** [comment]
Hi @whitecolor, I'm not 100% sure how you set up your monorepo and custom metro config. You can set it up in a lot of different ways, and maybe [yours is affecting this line in `expo` itself](https://github.com/expo/expo/blob/master/packages/expo/src/environment/logging.fx.ts#L10)? I'm not sure how we can help in setting up your custom metro config, I'm afraid we are limited in a way here.

One tip I can give you is the [`expo-yarn-workspaces`](https://github.com/expo/expo/tree/master/packages/expo-yarn-workspaces) package, it can help you setting up a monorepo with one or more expo projects in there. I've used it myself in [`use-expo`](https://github.com/byCedric/use-expo/blob/master/example/package.json#L18), and [other open-source projects](https://github.com/search?q=expo-yarn-workspaces&type=Code) are using it too (including `expo` of course 😄 )

Hope this helps!

**Comment by whitecolor** [comment]
I don't use yarn, not not going to my setup is working alright. I just setup the metro to require files from other locations that it "normally" does.  This is no good that that kind of setup influences how expo works. Or at least you could make a hint would could be the cause, if expo architecture is clean.

**Comment by whitecolor** [comment]
Hm, checked, now it actually works without explicit enabling. Not sure what might cause.

**Comment by orome** [comment]
After `expo upgrade` (to 45) no logging appears using either `console.log` or a package like react-native-logs. Even
```
import { Logs } from 'expo'

Logs.enableExpoCliLogging()
console.log( ' ~~ EXPO CONSOLE LOGGING ENABLED ~~' )
```
produces no output.

**Comment by credo7** [comment]
Change device name into English!

**Comment by charlesmchen-replit** [comment]
Thanks @credo7 I was seeing this issue when using a device name with an emoji.

**Comment by pencilcheck** [comment]
tried everything mentioned here, still doesn't work, no console.log in terminal window

1. tried opening a completely different terminal app and tried
2. rename device name (emulator)
3. reset metro and watchman and other caches
4. add lines to turn on log expo cli logging
5. add lines to turn off react native remove debugging
6. more

....

I'm running out of ideas, it used to work, it stopped working i think around the time I accidentally clicked on remote debugging...

**Comment by nickjuntilla** [comment]
Yes I am trying to view logs on a progressive web app and they do not appear in the console.
