### ISSUE TITLE
Error: Can't find react-native in package.json dependencies

### ISSUE THREAD

**Issue by whitecolor** [expo/expo-cli#2478]
This error is not actuall when monorepo or other more flexible structure is used, as react-native can be installed in parents.

**Comment by brentvatne** [comment]
it should still be in your package.json for the project, no?

**Comment by whitecolor** [comment]
It is in parent's modules. It works in my setup this way. Aso this error is bypassed (just shown without consequences) in dev mode, but it throws on publish.

**Comment by brentvatne** [comment]
we don't support this kind of setup. if you're using yarn workspaces for a monorepo you still need to include the react-native package in those directories. if you can post a minimal reproducible example in a new issue of exactly what you're trying to accomplish (as in, recreate a minimal monorepo using whatever approach you're using) we can help out there :)

**Comment by whitecolor** [comment]
> we don't support this kind of setup.

You don't in mind, but it works in reality. `react-native` package is needed by packager (metro), not expo. Why expo is checking it availability? There is a situation when expo "can not find" the package, but the packager can and works ok.

**Comment by Nziranziza** [comment]
Also having the same issue, I am using yarn workspaces and I understand I have to add it to all directories. Is there a way I can make sure all my expo apps use the same react-native version without me going to update each directories

**Comment by chandantiwari1** [comment]
I am having the same issue in my monorepo can somebody help me.
