### ISSUE TITLE
Error: React Native is not installed. Please run `npm install`

### ISSUE THREAD

**Issue by coryb08** [expo/expo-cli#248]
## Description

Running `npm start` after using `expo init my-app` gives error `Error: React Native is not installed. Please run npm install in your project directory.` running `npm install` (inside project directory) does not fix. yarn does not work either. Upgrading/downgrading npm does not work.

## Expected Behavior

For my new app to start successfully after `npm start`

## Observed Behavior

The error persists:  `Error: React Native is not installed. Please run `npm install`

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Cory\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@4.6.1
3 info using node@v8.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @~prestart: @
6 silly lifecycle @~prestart: no script for prestart, continuing
7 info lifecycle @~start: @
8 verbose lifecycle @~start: unsafe-perm in lifecycle true
9 verbose lifecycle @~start: PATH: C:\Users\Cory\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\users\cory\desktop\dev\blur-swipe3\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\nodejs\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files (x86)\Yarn\bin\;C:\Users\Cory\AppData\Local\Microsoft\WindowsApps;C:\Users\Cory\AppData\Roaming\npm;C:\Users\Cory\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Cory\AppData\Local\Yarn\bin
10 verbose lifecycle @~start: CWD: C:\users\cory\desktop\dev\blur-swipe3
11 silly lifecycle @~start: Args: [ '/d /s /c', 'expo start' ]
12 silly lifecycle @~start: Returned: code: 1  signal: null
13 info lifecycle @~start: Failed to exec start script
14 verbose stack Error: @ start: `expo start`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Cory\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Cory\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid @
16 verbose cwd C:\users\cory\desktop\dev\blur-swipe3
17 verbose Windows_NT 10.0.16299
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Cory\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 verbose node v8.9.4
20 verbose npm  v4.6.1
21 error code ELIFECYCLE
22 error errno 1
23 error @ start: `expo start`
23 error Exit status 1
24 error Failed at the @ start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

```

## Environment

Expo CLI 2.6.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 4.6.1 - C:\Program Files\nodejs\npm.CMD

react-native-cli: 2.0.1
react-native: 0.57.1

**Comment by MatthieuCoelho** [comment]
Same error after installing Expo CLI 2.6.8, I've tried to use previous versions with no success ...

**Comment by danielneal** [comment]
I'm seeing the exact same thing `Error: React Native is not installed. Please run `npm install` in your project directory.` 

The issue appeared after upgrading to `2.6.8`, and I also couldn't get it working again by downgrading to `2.6.6`.

**Comment by fson** [comment]
@danielneal @MatthieuCoelho could you both copy paste the output of `expo diagnostics` here? I'm trying to narrow down which platforms this happens on.

**Comment by fson** [comment]
Also when creating your project with `expo init`, when it asks `Use Yarn to install dependencies?` did you choose yes or no?

**Comment by Johnsonzhangc** [comment]
@fson I also experience the same problem right now, seems it doesn't visit your github file. I downgrade to expo-cli@2.4.3, it seems fine now.

**Comment by coryb08** [comment]
@johnsonzhang  can you post your error details? I don’t think this error is related to yours

**Comment by coryb08** [comment]
@fson per my original post it does not work with yarn either, when prompted to use yarn even.

**Comment by coryb08** [comment]
@fson , @MatthieuCoelho uses windows...  i’m going to try to use expo init on my Mac when I get home and see if it happens on OS X. Will report back

**Comment by fson** [comment]
Thanks @coryb08. Could you also let me know what the output from running these commands in the project folder is?
```
node -v
node -e "console.log(require.resolve('react-native/local-cli/cli.js'))"
node -e "console.log(require.resolve('react-native/local-cli/cli.js', {paths:[process.cwd()]}))"
```

**Comment by mauriciosoares** [comment]
@fson I'm having the exact same problem, so to try to speed things up, I'll share the logs you asked 

`node -v`
`v8.7.0`

`node -e "console.log(require.resolve('react-native/local-cli/cli.js'))"`
`/Users/mauricio.oliveira/workspace/olx-swipe-ui/node_modules/react-native/local-cli/cli.js`

`node -e "console.log(require.resolve('react-native/local-cli/cli.js', {paths:[process.cwd()]}))"`
`/Users/mauricio.oliveira/workspace/olx-swipe-ui/node_modules/react-native/local-cli/cli.js`

**Comment by coryb08** [comment]
@fson 

node -v: `v8.9.4`

node -e "console.log(require.resolve('react-native/local-cli/cli.js'))": `C:\users\cory\desktop\dev\blur-swipe3\node_modules\react-native\local-cli\cli.js`

node -e "console.log(require.resolve('react-native/local-cli/cli.js', {paths:[process.cwd()]}))"
: `C:\users\cory\desktop\dev\blur-swipe3\node_modules\react-native\local-cli\cli.js`

**Comment by danielneal** [comment]
I fixed this for my project by upgrading from node version 8.7.0 to 10.14.1.

**Comment by mauriciosoares** [comment]
@danielneal updating to 10.14.1 also worked for me 💃

**Comment by MatthieuCoelho** [comment]
I fixed it by removing xdl folder from my global npm then install expo-cli again.

**Comment by coryb08** [comment]
@danielneal @fson upgrading to node v 10.14.1 worked for me! Problem solved.

**Comment by giovanib02** [comment]
i had the same issue using node v10.15.3.
I have resolved the issue with the next steps:

1. Remove node_modules folder.
2. run "yarn install".
3. run "expo start".

**Comment by ELBEQQAL94** [comment]
> i had the same issue using node v10.15.3.
> I have resolved the issue with the next steps:
> 
>     1. Remove node_modules folder.
> 
>     2. run "yarn install".
> 
>     3. run "expo start".

it's worked for me, thank you so much.

**Comment by ananthprasad91** [comment]
1. removed node_modules and package.lock.json
2. "**npm install**" it worked

**Comment by Nicosan-K** [comment]
> i had the same issue using node v10.15.3.
> I have resolved the issue with the next steps:
> 
> 1. Remove node_modules folder.
> 2. run "yarn install".
> 3. run "expo start".

it worked for me also, but without step one. just "yarn install" and run it.

**Comment by techtunix** [comment]
I have resolved this strange issue with these steps on Win10

    1. Removed node_modules folder
    2. Removed package.lock.json file
    2. deleted all file from "C:\Users\XXXXXXX\AppData\Roaming\npm-cache" i.e. clear cache
    3. run "npm install".
    4. run "expo start".

I have used Windows PowerShell (Admin) to overcome permission issues.

---

Note: some might need to do this if they are facing "error Invalid regular expression: "

Open "PROJECT-DIR\node_modules\metro-config\src\defaults\blacklist.js"

Go to line #14 and Replace this 
`
var sharedBlacklist = [
  /node_modules[/\\]react[/\\]dist[/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];
`
With this :
`
var sharedBlacklist = [
  /node_modules[\/\\]react[\/\\]dist[\/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];
`

I hope this will also be helpfull for someone.

Thank you.

**Comment by widiyasasih** [comment]
> I have resolved this strange issue with these steps on Win10
> 
> ```
> 1. Removed node_modules folder
> 2. Removed package.lock.json file
> 2. deleted all file from "C:\Users\XXXXXXX\AppData\Roaming\npm-cache" i.e. clear cache
> 3. run "npm install".
> 4. run "expo start".
> ```
> 
> I have used Windows PowerShell (Admin) to overcome permission issues.
> 
> Note: some might need to do this if they are facing "error Invalid regular expression: "
> 
> Open "PROJECT-DIR\node_modules\metro-config\src\defaults\blacklist.js"
> 
> Go to line #14 and Replace this
> `var sharedBlacklist = [ /node_modules[/\\]react[/\\]dist[/\\].*/, /website\/node_modules\/.*/, /heapCapture\/bundle\.js/, /.*\/__tests__\/.*/ ];`
> With this :
> `var sharedBlacklist = [ /node_modules[\/\\]react[\/\\]dist[\/\\].*/, /website\/node_modules\/.*/, /heapCapture\/bundle\.js/, /.*\/__tests__\/.*/ ];`
> 
> I hope this will also be helpfull for someone.
> 
> Thank you.
Finally after 2 days on trouble, this fixed my problem

**Comment by mehmoodchohan** [comment]
Remove node_modules folder.
run "yarn install".
run "expo start".

this work fo rme

**Comment by giusousa** [comment]
Remove node_modules folder.
run "yarn install".
run "expo start".

Thanks!!

**Comment by ltsaiete** [comment]
> Remove node_modules folder.
> run "yarn install".
> run "expo start".
> 
> this work fo rme

It also worked for me, but without the fist step:

1. run "yarn install".
2. run "expo start".

**Comment by Ronedias** [comment]
> i had the same issue using node v10.15.3.
> I have resolved the issue with the next steps:
> 
> 1. Remove node_modules folder.
> 2. run "yarn install".
> 3. run "expo start".

Dude it worked for me too thanks!
1-run "yarn install".
1-run "npm satrt".

**Comment by marcalgyn** [comment]
> > i had the same issue using node v10.15.3.
> > I have resolved the issue with the next steps:
> > 
> > 1. Remove node_modules folder.
> > 2. run "yarn install".
> > 3. run "expo start".
> 
> it worked for me also, but without step one. just "yarn install" and run it.

Worked for me too, thanks. Funcionou para min também. Valeu!!

**Comment by omsingh11** [comment]
I was do this many time but same error are throw

**Comment by najathi** [comment]
1. Delete node_modules: rm -rf node_modules (using git bash in windows)
 2. run "yarn install".
 3. run "npm start".

**Comment by rushi812** [comment]
I resolved this issue by following these steps:

`npm install -g expo-cli` (this will update the expo cli to latest version)
`npm install`
`npm start`

**Comment by mikecon3ras** [comment]
I encounter the same issue and fix by:
running "yarn install" inside my project folder.

**Comment by JonRoosevelt** [comment]
> i had the same issue using node v10.15.3.
> I have resolved the issue with the next steps:
> 
> 1. Remove node_modules folder.
> 2. run "yarn install".
> 3. run "expo start".

Worked!
Thanks!

**Comment by Nate97320** [comment]
I had same problem.

I simply used the expo update command.


You are currently using SDK 1.0.0. Would you like to update to the latest version, 44.0.0?

and I said yes.

Every Thing was good to go with the npm start command

thats all

**Comment by colenndamn** [comment]
I had this exact same problem, it's because you are trying to install packages while expo is running, go to the console, stop the execution (ctrl+c), then install the package using either yarn or npm, and then start the server again once the package has been installed using expo start. it worked for me, hope this helps
