### ISSUE TITLE
16:11:40 fatal error(expo client)

### ISSUE THREAD

**Issue by subhampanja** [expo/expo-cli#2483]
installed expo.
-> expo init react-native
-> expo start
-> http://localhost:19002/ (opened)
-> expo client (on my android phone)
-> scanning qr code(but it never scanning its just stuck everytime)
-> send to email (access it to my android phone and then clicked on it.)
-> showing "Something went wrong. Could not load exp://192.168.0.105:19000"
-> I clicked on "view error log"
-> showing "Uncaught Error: java.net.ConnectException: Failed to connect to /192.168.0.105:19000"

each time showing same result.

note :- same network

**Comment by byCedric** [comment]
Hi @subhampanja, I'm sorry you are having issues. Unfortunately, without some context there isn't much I can do to help.  If you are running on Windows or MacOS Catalina, the firewall might block the connection between your computer (react native/expo server) and your phone (expo client). You can try running it in a tunnel, with `$ expo start --tunnel`. With this you avoid local firewalls and connect through a ngrok tunnel.

Hope that helps!
