### ISSUE TITLE
console.warn displayed in red (error) color

### ISSUE THREAD

**Issue by whitecolor** [expo/expo-cli#2486]
## Description

console.warn messages made for example inside context of `metro.config.js` are displayed in red color, which is a color of error messages.

## Expected Behavior

Some other color, it seems light red is used for some warning messages, or yellow as conventinal.

## Environment

  Expo CLI 3.24.2 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 14.4.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      react-native: ~0.62.2 => 0.62.2

**Comment by byCedric** [comment]
Hi @whitecolor, I'm not 100% sure how you set it up with the monorepo (assuming this is in the same project as your earlier issue https://github.com/expo/expo-cli/issues/2470). I can't repro this on my end, and there isn't a lot we can do in projects that are configured manually. So I'm going to close this, maybe [the comment I made](https://github.com/expo/expo-cli/issues/2470#issuecomment-680234809) in your other issue can help here as well!

**Comment by whitecolor** [comment]
>  I can't repro this on my end,

1. I just inited new expo project (blank typescript)
2. added metro.config.js with following content
```js
console.log('log: metro.config.js')
console.warn('warn: metro.config.js')
console.error('error: metro.config.js')
```
3. run `yarn start`
4. A see **red** `console.warn` output, the same color as `console.error` output.

![image](https://user-images.githubusercontent.com/736697/91275245-50cf5900-e799-11ea-9f76-df3e065b4059.png)
