### ISSUE TITLE
39.0.0 is not valid SDK

### ISSUE THREAD

**Issue by whitecolor** [expo/expo-cli#2487]
## Description

39.0.0 seems to be released on npm, latest expo-cli gives invalid SDK version is it possible to bypass this?

## Expected Behavior

Allow bypass.

**Comment by byCedric** [comment]
Hi @whitecolor! It's released on NPM as `next`, we are currently in the process of releasing the new SDK but it's not available (yet). We want to make sure everything works as expected with the latest iOS for example. Once it's there we will announce it, and you can use it 😄
