### ISSUE TITLE
Expo CLI - expo start from powershell, expo-cli cant find my device.

### ISSUE THREAD

**Issue by ghost** [expo/expo-cli#2489]
## Description

In powershell we need to escape @ symbol with quatiton mark. And avd device names starts with @ symbol.
Here I described with a simple screenshot. 

## Expected Behavior

I expected to open my android virtual device

## Observed Behavior

expo-cli said

```
emulator: ERROR: No AVD specified. Use '@foo' or '-avd foo' to launch a virtual device named 'foo'
```

## Reproducible Demo

Just run expo-cli from powershell
![image](https://user-images.githubusercontent.com/54193214/90964698-b25aa380-e4cb-11ea-8e25-ebc39db4736f.png)

here you can see. The first one is the command executed by expo-cli  but The second command that I edited, worked successfully

**Comment by byCedric** [comment]
Hi @5co, thanks for this! Could you also create a PR? I'm happy to test/approve it 😄

**Comment by 5co** [comment]
> Hi @5co, thanks for this! Could you also create a PR? I'm happy to test/approve it smile

Hi @byCedric . I created a PR. 

https://github.com/expo/expo-cli/pull/2494

**Comment by EvanBacon** [comment]
This appears to be resolved in the latest, versioned Expo CLI. If you encounter this issue in the future, please open an issue on [expo/expo](https://github.com/expo/expo/issues/new?assignees=&labels=needs+review%2CCLI&template=bug_report_cli.yml).
