### ISSUE TITLE
Add env var to distinct which expo command is currenlty run

### ISSUE THREAD

**Issue by whitecolor** [expo/expo-cli#2490]
## This a feature request. 

It would be useful for example in `metro.config.js` (or even `app.config.js`) to know by which expo command it was used `start/publish/export`. So expo could set some env var that will be propagated to child processes.

**Comment by byCedric** [comment]
Hi @whitecolor! Unfortunately, we don't "accept" feature requests here. It's hard for us to keep track of these feature requests between the issues, and gets lost easily. If you create a feature request on canny, and get people to upvote it, that would be awesome. Make sure to add your use case as well, why this would be useful for example.

> - Request a feature on Canny: https://expo.canny.io/feature-requests
