### ISSUE TITLE
There was a problem booting a device in iOS Simulator. Quit Simulator, and try again. Error installing or running app. Error: No iPhone devices available in Simulator.

### ISSUE THREAD

**Issue by vivek-mhajn** [expo/expo-cli#2492]
## Description
When I try `sudo yarn ios` in the terminal. This log shows up when the simulator is booted:
> Trying to open the project in iOS simulator...
Booting device in iOS simulator...
There was a problem booting a device in iOS Simulator. Quit Simulator, and try again.
Error installing or running app. Error: No iPhone devices available in Simulator.

And when I try `sudo yarn ios` when the iOS Simulator is not boot, the log shows up:
> Trying to open the project in iOS simulator...
Opening iOS simulator
iOS Simulator device failed to boot. Try opening Simulator first, then running your app.
Error installing or running app. Error: Timed out waiting for iOS Simulator device to boot.

I've tried everything from here:  https://github.com/facebook/react-native/issues/23878 even followed the Expo [iOS Simulator](https://docs.expo.io/workflow/ios-simulator/) docs and nothing seems to work.

**Courses of action I've taken unto now:**
1. The first time I tried up installing the _Expo client_  it worked like charm into the XCode Simulator.
2. Next time there were again problems. I tried uninstalling the Expo Client from the Simulator. Since then nothing worked.
3. I installed latest stable version of the XCode, that is 11.6 at the time of writing and nothing worked.
4. I then again installed the latest stable version of the XCode from the App Store and nothing worked.
5. I asked the issue in the Expo forum and had wished to get the issue resolved there.
6. Now I'm filing the issue in the `expo-cli git repo`.

## Expected Behavior
Upon the CLI command it was expected to install the Expo Client into the iOS Simulator and run the application bundler and it was expected to work seamlessly leading great developer experiences.

## Environment

**Expo Diagnostics**
> Expo CLI 3.24.2 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.14.6 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.0 => 38.0.9 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: 0.11.7 => 0.11.7 

**`xcodebuild -version`**
> Xcode 11.6
Build version 11E708

**`xcrun simctl list devices --json`**
> {
  "devices" : {
    "com.apple.CoreSimulator.SimRuntime.tvOS-13-4" : [
      {
        "dataPath" : "\/Users\/BBE0017\/Library\/Developer\/CoreSimulator\/Devices\/C78E9584-0AE3-46C0-9F7A-B6D3AB145748\/data",
        "logPath" : "\/Users\/BBE0017\/Library\/Logs\/CoreSimulator\/C78E9584-0AE3-46C0-9F7A-B6D3AB145748",
        "udid" : "C78E9584-0AE3-46C0-9F7A-B6D3AB145748",
        "isAvailable" : true,
        "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p",
        "state" : "Shutdown",
        "name" : "Apple TV"
      },
      {
        "dataPath" : "\/Users\/BBE0017\/Library\/Developer\/CoreSimulator\/Devices\/2B30406A-9E77-4280-A6F9-05D97807853D\/data",
        "logPath" : "\/Users\/BBE0017\/Library\/Logs\/CoreSimulator\/2B30406A-9E77-4280-A6F9-05D97807853D",
        "udid" : "2B30406A-9E77-4280-A6F9-05D97807853D",
        "isAvailable" : true,
        "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-4K",
        "state" : "Shutdown",
        "name" : "Apple TV 4K"
      },
      {
        "dataPath" : "\/Users\/BBE0017\/Library\/Developer\/CoreSimulator\/Devices\/E2E73248-E2C3-457D-85D9-C3316F1C8DD5\/data",
        "logPath" : "\/Users\/BBE0017\/Library\/Logs\/CoreSimulator\/E2E73248-E2C3-457D-85D9-C3316F1C8DD5",
        "udid" : "E2E73248-E2C3-457D-85D9-C3316F1C8DD5",
        "isAvailable" : true,
        "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-1080p",
        "state" : "Shutdown",
        "name" : "Apple TV 4K (at 1080p)"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.watchOS-6-2" : [
      {
        "dataPath" : "\/Users\/BBE0017\/Library\/Developer\/CoreSimulator\/Devices\/F445BD2F-3072-4663-81BE-1FD6FF054BFC\/data",
        "logPath" : "\/Users\/BBE0017\/Library\/Logs\/CoreSimulator\/F445BD2F-3072-4663-81BE-1FD6FF054BFC",
        "udid" : "F445BD2F-3072-4663-81BE-1FD6FF054BFC",
        "isAvailable" : true,
        "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-4-40mm",
        "state" : "Shutdown",
        "name" : "Apple Watch Series 4 - 40mm"
      },
      {
        "dataPath" : "\/Users\/BBE0017\/Library\/Developer\/CoreSimulator\/Devices\/4A1C4C39-ECC6-4540-866A-F0ECA334D405\/data",
        "logPath" : "\/Users\/BBE0017\/Library\/Logs\/CoreSimulator\/4A1C4C39-ECC6-4540-866A-F0ECA334D405",
        "udid" : "4A1C4C39-ECC6-4540-866A-F0ECA334D405",
        "isAvailable" : true,
        "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-4-44mm",
        "state" : "Shutdown",
        "name" : "Apple Watch Series 4 - 44mm"
      },
      {
        "dataPath" : "\/Users\/BBE0017\/Library\/Developer\/CoreSimulator\/Devices\/10A5E2ED-39CE-4546-869A-8D44A586E6ED\/data",
        "logPath" : "\/Users\/BBE0017\/Library\/Logs\/CoreSimulator\/10A5E2ED-39CE-4546-869A-8D44A586E6ED",
        "udid" : "10A5E2ED-39CE-4546-869A-8D44A586E6ED",
        "isAvailable" : true,
        "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-5-40mm",
        "state" : "Shutdown",
        "name" : "Apple Watch Series 5 - 40mm"
      },
      {
        "dataPath" : "\/Users\/BBE0017\/Library\/Developer\/CoreSimulator\/Devices\/25CA184E-7C57-4CA3-B655-AADC0418C69A\/data",
        "logPath" : "\/Users\/BBE0017\/Library\/Logs\/CoreSimulator\/25CA184E-7C57-4CA3-B655-AADC0418C69A",
        "udid" : "25CA184E-7C57-4CA3-B655-AADC0418C69A",
        "isAvailable" : true,
        "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-5-44mm",
        "state" : "Shutdown",
        "name" : "Apple Watch Series 5 - 44mm"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.iOS-13-6" : [
      {
        "dataPath" : "\/Users\/BBE0017\/Library\/Developer\/CoreSimulator\/Devices\/383DBFD9-E0A0-45E6-B79A-EB73567D8887\/data",
        "logPath" : "\/Users\/BBE0017\/Library\/Logs\/CoreSimulator\/383DBFD9-E0A0-45E6-B79A-EB73567D8887",
        "udid" : "383DBFD9-E0A0-45E6-B79A-EB73567D8887",
        "isAvailable" : true,
        "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-8",
        "state" : "Shutdown",
        "name" : "iPhone 8"
      },
      {
        "dataPath" : "\/Users\/BBE0017\/Library\/Developer\/CoreSimulator\/Devices\/169C0000-613C-43D8-9F7E-C61A56FACC06\/data",
        "logPath" : "\/Users\/BBE0017\/Library\/Logs\/CoreSimulator\/169C0000-613C-43D8-9F7E-C61A56FACC06",
        "udid" : "169C0000-613C-43D8-9F7E-C61A56FACC06",
        "isAvailable" : true,
        "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-8-Plus",
        "state" : "Shutdown",
        "name" : "iPhone 8 Plus"
      },
      {
        "dataPath" : "\/Users\/BBE0017\/Library\/Developer\/CoreSimulator\/Devices\/365B5C62-D206-4FDF-9D40-781121583D69\/data",
        "logPath" : "\/Users\/BBE0017\/Library\/Logs\/CoreSimulator\/365B5C62-D206-4FDF-9D40-781121583D69",
        "udid" : "365B5C62-D206-4FDF-9D40-781121583D69",
        "isAvailable" : true,
        "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-11",
        "state" : "Shutdown",
        "name" : "iPhone 11"
      },
      {
        "dataPath" : "\/Users\/BBE0017\/Library\/Developer\/CoreSimulator\/Devices\/D79F087B-96A9-4620-B789-C81C226717DF\/data",
        "logPath" : "\/Users\/BBE0017\/Library\/Logs\/CoreSimulator\/D79F087B-96A9-4620-B789-C81C226717DF",
        "udid" : "D79F087B-96A9-4620-B789-C81C226717DF",
        "isAvailable" : true,
        "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-11-Pro",
        "state" : "Shutdown",
        "name" : "iPhone 11 Pro"
      },
      {
        "dataPath" : "\/Users\/BBE0017\/Library\/Developer\/CoreSimulator\/Devices\/A18E2E25-673E-4DD2-B6E6-547860B51872\/data",
        "logPath" : "\/Users\/BBE0017\/Library\/Logs\/CoreSimulator\/A18E2E25-673E-4DD2-B6E6-547860B51872",
        "udid" : "A18E2E25-673E-4DD2-B6E6-547860B51872",
        "isAvailable" : true,
        "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-11-Pro-Max",
        "state" : "Shutdown",
        "name" : "iPhone 11 Pro Max"
      },
      {
        "dataPath" : "\/Users\/BBE0017\/Library\/Developer\/CoreSimulator\/Devices\/2C6AC2CC-5A4A-471E-A133-2EA21CA5969C\/data",
        "logPath" : "\/Users\/BBE0017\/Library\/Logs\/CoreSimulator\/2C6AC2CC-5A4A-471E-A133-2EA21CA5969C",
        "udid" : "2C6AC2CC-5A4A-471E-A133-2EA21CA5969C",
        "isAvailable" : true,
        "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-SE--2nd-generation-",
        "state" : "Booted",
        "name" : "iPhone SE (2nd generation)"
      },
      {
        "dataPath" : "\/Users\/BBE0017\/Library\/Developer\/CoreSimulator\/Devices\/F281EAC0-9011-4E80-8CF1-AE7057067BE3\/data",
        "logPath" : "\/Users\/BBE0017\/Library\/Logs\/CoreSimulator\/F281EAC0-9011-4E80-8CF1-AE7057067BE3",
        "udid" : "F281EAC0-9011-4E80-8CF1-AE7057067BE3",
        "isAvailable" : true,
        "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-",
        "state" : "Shutdown",
        "name" : "iPad Pro (9.7-inch)"
      },
      {
        "dataPath" : "\/Users\/BBE0017\/Library\/Developer\/CoreSimulator\/Devices\/E686D725-C610-4540-A35B-00FBAB89CDC4\/data",
        "logPath" : "\/Users\/BBE0017\/Library\/Logs\/CoreSimulator\/E686D725-C610-4540-A35B-00FBAB89CDC4",
        "udid" : "E686D725-C610-4540-A35B-00FBAB89CDC4",
        "isAvailable" : true,
        "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPad--7th-generation-",
        "state" : "Shutdown",
        "name" : "iPad (7th generation)"
      },
      {
        "dataPath" : "\/Users\/BBE0017\/Library\/Developer\/CoreSimulator\/Devices\/67E8CCDE-A1C2-43BD-B3B8-ECD0960A8D64\/data",
        "logPath" : "\/Users\/BBE0017\/Library\/Logs\/CoreSimulator\/67E8CCDE-A1C2-43BD-B3B8-ECD0960A8D64",
        "udid" : "67E8CCDE-A1C2-43BD-B3B8-ECD0960A8D64",
        "isAvailable" : true,
        "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro--11-inch---2nd-generation-",
        "state" : "Shutdown",
        "name" : "iPad Pro (11-inch) (2nd generation)"
      },
      {
        "dataPath" : "\/Users\/BBE0017\/Library\/Developer\/CoreSimulator\/Devices\/C0366553-8E96-47B0-BA4D-A60ED211C728\/data",
        "logPath" : "\/Users\/BBE0017\/Library\/Logs\/CoreSimulator\/C0366553-8E96-47B0-BA4D-A60ED211C728",
        "udid" : "C0366553-8E96-47B0-BA4D-A60ED211C728",
        "isAvailable" : true,
        "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---4th-generation-",
        "state" : "Shutdown",
        "name" : "iPad Pro (12.9-inch) (4th generation)"
      },
      {
        "dataPath" : "\/Users\/BBE0017\/Library\/Developer\/CoreSimulator\/Devices\/2E311BF8-FEB8-4C61-BA6C-EF817F3B6908\/data",
        "logPath" : "\/Users\/BBE0017\/Library\/Logs\/CoreSimulator\/2E311BF8-FEB8-4C61-BA6C-EF817F3B6908",
        "udid" : "2E311BF8-FEB8-4C61-BA6C-EF817F3B6908",
        "isAvailable" : true,
        "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Air--3rd-generation-",
        "state" : "Shutdown",
        "name" : "iPad Air (3rd generation)"
      }
    ]
  }
}

**Comment by byCedric** [comment]
Hi @vivek-mhajn! I'm sorry to hear you are having issues with the Simulator. It looks like you did everything right, so let's try to pinpoint some issues with the simulator. If you did not change anything, we can try executing some commands to see where it's going wrong. The first set of commands to test are:

```
// This should boot up the preferred device ID using your device dump
// Check if this works normally, or if it produces errors/warnings
$ xcrun simctl boot 383DBFD9-E0A0-45E6-B79A-EB73567D8887

// Also try to shut it down, and boot it up again
$ xcrun simctl shutdown 383DBFD9-E0A0-45E6-B79A-EB73567D8887

// If that fails, try to erase the simulator to remove any conflicting settings
$ xcrun simctl erase 383DBFD9-E0A0-45E6-B79A-EB73567D8887
```

After these commands, please try the `$ expo client:install:ios` command. That might help installing the proper client on the simulator instead of the default one. If you run this from your project, it detects the best compatible one.

Let me know if this helps!
Cedric

**Comment by vivek-mhajn** [comment]
Hi @byCedric I boot up the device, shut it down and while installing the client on the simulator the error showed up with the following log:

> There was a problem booting a device in iOS Simulator. Quit Simulator, and try again.
No iPhone devices available in Simulator.
Error: No iPhone devices available in Simulator.
    at _getFirstAvailableDeviceAsync (/@expo/xdl@57.9.31/src/Simulator.ts:208:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at _bootDefaultSimulatorDeviceAsync (/@expo/xdl@57.9.31/src/Simulator.ts:168:21)
    at _openAndBootSimulatorAsync (/@expo/xdl@57.9.31/src/Simulator.ts:145:7)
    at Object.upgradeExpoAsync (/@expo/xdl@57.9.31/src/Simulator.ts:420:3)
    at /usr/local/share/.config/yarn/global/node_modules/expo-cli/src/commands/client/index.ts:321:11
    at Command.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/expo-cli/src/exp.ts:79:7)

Then erased the simulator device and boot up the device again, I then again tried installing the client on the simulator and the same error showed up again. What could I try next ?

**Comment by vivek-mhajn** [comment]
Hi @byCedric I boot up the device, shut it down and while installing the client on the simulator the error showed up with the following log:

> There was a problem booting a device in iOS Simulator. Quit Simulator, and try again.
No iPhone devices available in Simulator.
Error: No iPhone devices available in Simulator.
    at _getFirstAvailableDeviceAsync (/@expo/xdl@57.9.31/src/Simulator.ts:208:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at _bootDefaultSimulatorDeviceAsync (/@expo/xdl@57.9.31/src/Simulator.ts:168:21)
    at _openAndBootSimulatorAsync (/@expo/xdl@57.9.31/src/Simulator.ts:145:7)
    at Object.upgradeExpoAsync (/@expo/xdl@57.9.31/src/Simulator.ts:420:3)
    at /usr/local/share/.config/yarn/global/node_modules/expo-cli/src/commands/client/index.ts:321:11
    at Command.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/expo-cli/src/exp.ts:79:7)

Then erased the simulator device and boot up the device again, I then again tried installing the client on the simulator and the same error showed up again. Then closed the simulator and again tried installing the client on the simulator, the simulator opened up and the following log showed up:

> ? You are currently using SDK 38.0.0. Would you like to install client 2.16.1 released for this SDK? Yes
Opening iOS simulator
iOS Simulator device failed to boot. Try opening Simulator first, then running your app.
Timed out waiting for iOS Simulator device to boot.
Error: Timed out waiting for iOS Simulator device to boot.
    at _waitForDeviceToBoot (/@expo/xdl@57.9.31/src/Simulator.ts:241:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at _openAndBootSimulatorAsync (/@expo/xdl@57.9.31/src/Simulator.ts:141:5)
    at Object.upgradeExpoAsync (/@expo/xdl@57.9.31/src/Simulator.ts:420:3)
    at /usr/local/share/.config/yarn/global/node_modules/expo-cli/src/commands/client/index.ts:321:11
    at Command.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/expo-cli/src/exp.ts:79:7)

What could I try next ?

**Comment by vivek-mhajn** [comment]
**Note:** I've used the above three mentioned commands only, for the device boot up(cmd 1), for device shut down (cmd 2) and for erasing the simulator(cmd 3).

**Comment by byCedric** [comment]
I'm not sure what's going wrong, if a full erase didn't work something is going on with your simulator outside of Expo. When you fully reset the device, you are resetting all Expo related code and data. My best next guess would be to double-check your system permissions, [as mentioned here](https://developer.apple.com/forums/thread/11313). It could also help if you try to launch normal iOS projects through XCode and see if they are running as expected.

Hope it helps!

**Comment by vivek-mhajn** [comment]
Hello @byCedric , I'd followed almost steps in the suggested given link. It lead me here and I'm still facing some issues.

**Comment by vivek-mhajn** [comment]
Hello @byCedric , I'd implemented the suggested steps and implemented almost steps in the suggested link and it lead me [here](https://github.com/expo/expo-cli/issues/2735) again with some issues.
