### ISSUE TITLE
Expo build webhooks are not being fired

### ISSUE THREAD

**Issue by mymattcarroll** [expo/expo-cli#2499]
## Description

My webhook for my app is not being called any more? Builds are completing successfully however the webhook is not being called. Last webhook was on Monday 21st August 2020 1:43 pm AEST (`2020-08-21T13:43:07.375+10:00`)

## Expected Behavior

Expected webhook to be called

## Observed Behavior

Webhook was not called.

## Environment

```
  Expo CLI 3.18.6 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.5.1 - /usr/local/bin/zsh
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.14.8 - ~/.npm-packages/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.7 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
      react-navigation: 4.0.10 => 4.0.10 
```

**Comment by byCedric** [comment]
Hi @mymattcarroll! I'm happy to check this out for you, but for that, I need your app and account name. Could you send a mail to secure@expo.io with the info?

If not, could you provide the information you see when running `$ expo webhooks` from within your project?

**Comment by byCedric** [comment]
Hey People! As a follow-up, we identified a possible cause for the webhooks not being fired on some projects. Today we rolled out the fix and this should be working as expected now. If you still have any issues with the webhooks, please send us a mail with the project information and a short description of what's happening. I'd be happy to dig into the issue further!

Thanks for reporting this!

**Comment by mymattcarroll** [comment]
I can confirm our webhooks are working again.

Thank you for the quick turn around Expo Team 👍

**Comment by shahidcodes** [comment]
@byCedric I set up webhooks for two of my projects but did not receive any requests. Sent an email on secure@expo.io.
