### ISSUE TITLE
unable to load post publish hooks since expo-cli@2.6.10/xdl@52.0.9

### ISSUE THREAD

**Issue by alxyuu** [expo/expo-cli#250]
## Description

expo-cli is no longer loading files for post publish hooks, following this change to use import fresh:
https://github.com/expo/expo-cli/commit/4e07a26877b98162b6726f4e19cee5bb42ce5c86

I'm using a modified version of the sentry-expo sourcemap upload, with this configuration:

```
    "hooks": {
      "postPublish": [
        {
          "file": "./scripts/upload-sourcemaps",
          "config": {
            "organization": "...",
            "project": "...",
            "authToken": "..."
          }
        }
      ]
    }
```
When debugging, the value of `fullPath = ProjectUtils.resolveModule(modulePath, projectRoot, exp);` is indeed the absolute path of the upload-sourcemaps file, and changing `importFresh(fullPath)` back to `require(fullPath)` allows the hook to work again. I got as far as finding that the `callerPath()` function inside of import-fresh was returning null, which I assume should not be the case.

I initially thought this only affected local files but it looks like files in node_modules are affected as well.

Could potentially be a duplicate of this issue: https://github.com/expo/expo-cli/issues/42, but since it created back in September and import fresh was added today, I suspect it has a different root cause. 

## Expected Behavior

Post publish hooks should be able to run

## Observed Behavior

Post publish hook throws the follow error when trying to publish:

```
[15:22:02] Unable to find an existing Expo CLI instance for this directory, starting a new one...
[15:22:05] Starting Metro Bundler on port 19001.
[15:22:05] Metro Bundler ready.
[15:22:06] Tunnel ready.
[15:22:06] Publishing to channel 'preview'...
[15:22:07] Unable to load postPublishHook: './scripts/upload-sourcemaps'. The module does not export a function.
[15:22:07] Please fix your postPublish hook configuration.
```

## Environment

```
  Expo CLI 2.6.11 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.4 - /usr/local/Cellar/node/11.0.0/bin/node
      npm: 6.4.1 - /usr/local/Cellar/node/11.0.0/bin/npm
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^27.0.0 => 27.0.1 
      react: 16.3.1 => 16.3.1 
      react-native: https://github.com/expo/react-native/archive/sdk-27.0.2.tar.gz => 0.55.2 
      react-navigation: 1.0.0-beta.23 => 1.0.0-beta.23 
    npmGlobalPackages:
      expo-cli: 2.6.11
```

## Reproducible Demo

https://github.com/alxyuu/local-post-publish

Running `expo publish` will result in the error above. Modifying the file in app.json to `./scripts/upload-sourcemaps` to use a local file instead also result in a similar error.

If you modify the global node module file `node_modules/expo-cli/node_modules/xdl/build/Project.js` to use require instead of import fresh, the post publish hook works again.

**Comment by alxyuu** [comment]
if anyone is having this problem and needs to deploy, I'm currently running this workaround prior to publish on my ci tool:

`sed -i.bak s/"(0, (_importFresh || _load_importFresh()).default)"/require/g $(npm -g root)/expo-cli/node_modules/xdl/build/Project.js`

**Comment by outaTiME** [comment]
Same here 😢

**Comment by rxhivzero** [comment]
2.6.11 Same

**Comment by onlined** [comment]
I think it is resolved with 2.6.12.

**Comment by brentvatne** [comment]
@fson - ping

**Comment by brentvatne** [comment]
as @onlined pointed out, indeed this looks to be fixed in 2.6.12 - https://github.com/expo/expo-cli/commit/59728739091ed39fc1d34d121098ef7282f67225

**Comment by cyrus-za** [comment]
Experiencing this in 2.7.1 on macOS

**Comment by cyrus-za** [comment]
nevermind. I had a syntax error
