### ISSUE TITLE
`expo publish --quiet xxxx` doesn't work

### ISSUE THREAD

**Issue by whitecolor** [expo/expo-cli#2500]
Expo cli version 3.24.2

`expo publish --quiet xxxx` show help but doesn't run `publish` if `--quite` is removed, it works.

**Comment by byCedric** [comment]
Hi @whitecolor, could you elaborate a bit more on this? E.g. environment, the output you receive etc. I can't reproduce this:

![Screenshot 2020-08-25 at 17 57 37](https://user-images.githubusercontent.com/1203991/91198229-95f17d80-e6fc-11ea-849b-bd2289e3f4d2.png)

**Comment by whitecolor** [comment]
`expo publish --quiet project-folder` - I run not in project-folder and add it to cmd. relative to PWD.

**Comment by byCedric** [comment]
Have you tried swapping the `--quiet` option and the relative directory? E.g. something like `$ expo publish project-folder --quiet`, that works for me 😄

**Comment by whitecolor** [comment]
But this quite unexpected and seems like a bug, usage in `--help` says:
```
Usage: publish|p [options] [project-dir]

  Publishes your project to exp.host

  Options:

    -q, --quiet                          Suppress verbose output from the Metro bundler.
...
```
