### ISSUE TITLE
npx expo-optimize

### ISSUE THREAD

**Issue by himrocks33** [expo/expo-cli#2511]
## Description

Expo-optimize returns the below error since upgrading to expo-cli: 3.25.0

## Expected Behavior

Should not return an error.

## Observed Behavior

```
npx expo-optimize
Cannot find module 'getenv'
Require stack:
- C:\Users\username\AppData\Roaming\npm-cache\_npx\12508\node_modules\expo-optimize\node_modules\@expo\image-utils\build\sharp.js
- C:\Users\username\AppData\Roaming\npm-cache\_npx\12508\node_modules\expo-optimize\node_modules\@expo\image-utils\build\Image.js
- C:\Users\username\AppData\Roaming\npm-cache\_npx\12508\node_modules\expo-optimize\node_modules\@expo\image-utils\build\index.js
- C:\Users\username\AppData\Roaming\npm-cache\_npx\12508\node_modules\expo-optimize\node_modules\@expo\config\build\ios\Icons.js
- C:\Users\username\AppData\Roaming\npm-cache\_npx\12508\node_modules\expo-optimize\node_modules\@expo\config\build\ios\index.js
- C:\Users\username\AppData\Roaming\npm-cache\_npx\12508\node_modules\expo-optimize\node_modules\@expo\config\build\index.js
- C:\Users\username\AppData\Roaming\npm-cache\_npx\12508\node_modules\expo-optimize\build\index.js
```

## Environment

Windows 10

## Reproducible Demo

run npx expo-optimize

**Comment by ochikov** [comment]
Same here: 
`Cannot find module 'getenv'
Require stack:
- /Users/ognyanchikov/.npm/_npx/21597/lib/node_modules/expo-optimize/node_modules/@expo/image-utils/build/sharp.js
- /Users/ognyanchikov/.npm/_npx/21597/lib/node_modules/expo-optimize/node_modules/@expo/image-utils/build/Image.js
- /Users/ognyanchikov/.npm/_npx/21597/lib/node_modules/expo-optimize/node_modules/@expo/image-utils/build/index.js
- /Users/ognyanchikov/.npm/_npx/21597/lib/node_modules/expo-optimize/node_modules/@expo/config/build/ios/Icons.js
- /Users/ognyanchikov/.npm/_npx/21597/lib/node_modules/expo-optimize/node_modules/@expo/config/build/ios/index.js
- /Users/ognyanchikov/.npm/_npx/21597/lib/node_modules/expo-optimize/node_modules/@expo/config/build/index.js
- /Users/ognyanchikov/.npm/_npx/21597/lib/node_modules/expo-optimize/build/index.js`

**Comment by byCedric** [comment]
Hi @himrocks33! Thanks for bringing this up, I'll create a fix immediately! For now, you can work around this by using `0.1.43` instead:

```
$ npx expo-optimize@0.1.43
```
