### ISSUE TITLE
expo client:ios build hanging

### ISSUE THREAD

**Issue by special-character** [expo/expo-cli#2513]
I ran the command `expo client:ios` yesterday and the build is still stuck in "Waiting to build your Expo client". I don't really have any way to debug why this is happening. I started another one this morning just to try but it looks like it may be stuck as well with the same message. I posted a question on forums but it was hidden by a bot by default and is still hidden.

## Expected Behavior

The custom expo client would be built so that we can test background tasks.

## Observed Behavior

Build is hanging with message "Waiting to build your Expo client" for a full day.

## Environment

```
  Expo CLI 3.24.2 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.0 - /usr/local/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 6.12.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.9 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
```

## Reproducible Demo

Run `expo client:ios`

**Comment by Jose4gg** [comment]
I'm experiencing the same thing.

**Comment by jbrumwell** [comment]
We are having the same issue as well :( I checked the turtle status but I don't think these are reported there?

**Comment by LouisJS** [comment]
I'm having an issue with "expo publish"

It loads indefinitely with : [Uploading JavaScript bundles](https://ibb.co/LknP4m9)

**Comment by special-character** [comment]
@Jose4gg @jbrumwell Another thread was opened in the forums and has a workaround: https://forums.expo.io/t/the-custom-expo-client-for-ios-takes-forever-to-build/42265/7

**Comment by EvanBacon** [comment]
Seems this was a server outage that has since been fixed https://forums.expo.io/t/the-custom-expo-client-for-ios-takes-forever-to-build/42265/9?u=bacon sorry for the inconvenience.
