### ISSUE TITLE
Turtle build seems to use old manifest

### ISSUE THREAD

**Issue by fwal** [expo/expo-cli#252]
## Description

When running `turtle build:android` on my project it seems to use an old version of the manifest, either from some local cache or an online case.

## Expected Behavior

When running `turtle build:android` I expect the manifest in the project folder to be used.

## Observed Behavior

When running `turtle build:android` on an project with an updated version number, and other updated values, the build still contains the old values from an earlier build.

## Environment

expo sdk: 31
turtle-cli: 0.3.9

**Comment by brentvatne** [comment]
can you share any information such as what project this is happening to and the build id? support@expo.io would be a good place to send that info

**Comment by fwal** [comment]
It's a non-listed project but I'm using `turtle-cli` to build on in-house machines. I get the feeling that it reads the manifest from the last version published to expo rather than the app.json in the project, am I right? In that case I assume that I need to export the bundle first using `expo export`?

**Comment by brentvatne** [comment]
that's correct, it reads from the latest published version, so you can either run `expo publish` again to update it, or you can use `expo export` and put the resulting files on some hosting service then (if i'm not mistaken, i am not an expert on turtle-cli personally) you should be able to pass in a `public-url` flag similar to https://docs.expo.io/versions/v31.0.0/distribution/hosting-your-app#build-standalone-app to point to it

**Comment by fwal** [comment]
Ok, I made an assumption somewhere that `turtle` packaged everything together but now I see I was mistaken, I'll close this now as this is most likely an error on my part 🙂.

Thanks for clearing it up for me @brentvatne!
