### ISSUE TITLE
Expo Web Showing All my files in inspection

### ISSUE THREAD

**Issue by vrinch** [expo/expo-cli#2520]
I am using expo web to develop a web app, after hosting my files on firebase hosting, I decided to inspect the page to check how the files would display to users who try to view it. While doing this I noticed it was showing all my files including the node module folder to users. I have tried this with three different laptops and its the same thing, below is an image of the file structure in inspection and my firebase.json file
![image](https://user-images.githubusercontent.com/51086859/91326710-8fc2d600-e7bc-11ea-9c86-f3093f794446.png)
![image](https://user-images.githubusercontent.com/51086859/91326796-a8cb8700-e7bc-11ea-91f0-4325e7e10ee5.png)

Can someone please point me in the right direction

**Comment by EvanBacon** [comment]
I think this is a problem with how the source maps are generated.

**Comment by vrinch** [comment]
> I think this is a problem with how the source maps are generated.

thank you evan, I checked your expogram app to be sure I wasn't making any mistakes, it was the same thing. A temporary fix was to delete the .map files in the web-build/static/js
I am not sure if this would have any effects on the app though

**Comment by EvanBacon** [comment]
Could you please provide a minimal repro. I can't seem to repro locally. Perhaps it's related to building a windows machine?

**Comment by vrinch** [comment]
I don't think its related to just a windows machine
below is an image of the same issue from your instagram clone project at https://expogram.netlify.app/#/
![image](https://user-images.githubusercontent.com/51086859/91539998-19d08300-e912-11ea-95b1-6731275ef467.png)

**Comment by byCedric** [comment]
I can reproduce this as well, looks like the path transformation when building a production build doesn't work as expected. Whenever I manually replace the `config.output.devtoolModuleFilenameTemplate` with this method:

```
config.output.devtoolModuleFilenameTemplate = (info) => {
  return path.relative(env.projectRoot, info.absoluteResourcePath);
};
```

The production build sourcemaps are relative to my project again.

**Comment by nrz2000** [comment]
Same problem(

**Comment by c302750253** [comment]
remove the file "web-build/static/js/app.xxxxxxx.chunk.js.map" ,it works!

**Comment by kirtikapadiya** [comment]
same issue with expo web

**Comment by giaset** [comment]
This seems like a pretty big issue (just noticed it after a few years of using Expo and react-native-web)

Fixed it by making my build script something like this: `expo export:web && rm ./web-build/static/js/*.js.map`, but really wish I'd caught this sooner...

**Comment by byCedric** [comment]
Hi all! Since there are two versions of "web export" current in Expo, I'll reply to the same question twice.

## Using `npx expo export:web` (Webpack)

> ⚠️ Note, Expo's webpack support has been sunset and is not actively maintained anymore. ([docs](https://docs.expo.dev/router/migrate/from-expo-webpack/))

When using Webpack, you could disable source map exports through a `webpack.config.js` file. E.g. run `npx expo customize`, select the `webpack.config.js`, and disable `config.devtool` whenever you don't want source maps.

```js
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync(env, argv);

  // Disable source map exports when building for production
  // You can customize when the source maps are turned off, or always keep it off
  if (process.env.NODE_ENV === 'production') {
    // See: https://webpack.js.org/configuration/devtool/#root
    config.devtool = false;
  }

  return config;
};
```

## Using `npx expo export --platform web` (Metro)

If you are using Metro to export your app to web, you don't need to do anything. The source maps are disabled by default, and can be exported when using `npx expo export --platform web --source-maps`.

Hope this helps!
