### ISSUE TITLE
[build] build command should enforce publish action to set target as 'managed'

### ISSUE THREAD

**Issue by Charlie-Hua** [expo/expo-cli#2521]
## Description
We have 5 managed apps and 2 bare apps in one expo repo (each has its own app.json).
When running `expo build`,  publish action assumes it's `bare` target and this breaks some assets (like fonts).

## Expected Behavior
When running `expo build`, the  publish action should use `--target managed` option to build app correctly.
(it doesn't make sense to build managed app and publish for bare target after all, does it?)

## Observed Behavior
`publish` assume its a bare app, due to the existence of `ios/**/*.xcodeproj` or `'android/**/*.gradle'`
This breaks assets.

## Environment
  expo-cli: 3.25.0
  expo: 38.0.8

## Root cause
`expo build` would just run `publish` without `--target managed`, and `publish` uses `getDefaultTarget` from `@expo/config` to decide the target.
For SDK < 37, it defaults to `managed`.
But for SDK > 38, it checks the existence of `ios/**/*.xcodeproj` or `'android/**/*.gradle'`.

https://github.com/expo/expo-cli/blob/e9101dbab0b378b531dcd07904240628462615e8/packages/config/src/Config.ts#L487

## Proposed solution
`build` command passes `duringBuild: true` to publish action, which can be used to set the target to `managed` correctly.

## Related issues
expo/expo#9280
expo/expo#9517

**Comment by staghouse** [comment]
See also: https://github.com/expo/expo/issues/7792, specifically https://github.com/expo/expo/issues/7792#issuecomment-704339649

I'm having this issue under different conditions.

**Comment by brentvatne** [comment]
we're moving away from the `target` flag entirely in sdk 41 so this will be a non issue
