### ISSUE TITLE
An unknown error occurred. (error while login in expo-cli@3.25.1)

### ISSUE THREAD

**Issue by tomasgvivo** [expo/expo-cli#2523]
## Description
When trying to login using the command `expo login --username xxx@yyy.zzz --password xxxxxx`, I get the error "An unknown error occurred".
This problem occurs using the version 3.25.1.
The problem does not occur when downgrading to the version 3.25.0.
I understand the version 3.25.1 was released a few hours ago.

## Environment
```
  Expo CLI 3.25.1 environment info:
    System:
      OS: Linux 5.0 Debian GNU/Linux 9 (stretch) 9 (stretch)
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 14.5.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    npmPackages:
      expo: ^38.0.0 => 37.0.12 
      react: 16.11.0 => 16.9.0 
      react-dom: 16.11.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.61.4 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.25.1
```

**Comment by brentvatne** [comment]
hi there! there was an intermittent server issue and it should be resolved now. let me know if the issue persists and i can reopen this issue and investigate.

**Comment by tomasgvivo** [comment]
Yep, solved. Thanks.

**Comment by BannyT** [comment]
problem still exists
