### ISSUE TITLE
CRNA Support for --with-web-support

### ISSUE THREAD

**Issue by jamespacileo** [expo/expo-cli#253]
CRNA lost support for --with-web-support

Original CRNA ticket was closed with "moving to expo-cli"

https://github.com/react-community/create-react-native-app/issues/769

**Comment by drewbitt** [comment]
There's recent work with expo and web support, see https://github.com/expo/expo/commit/8394eff539fc3ec0efb90836e00cd57bec08716c today and NCL. It would be nice to see this in expo-cli now, I believe before it just wasn't ready.
