### ISSUE TITLE
pod-install hangs after Pod installation complete!

### ISSUE THREAD

**Issue by grit96** [expo/expo-cli#2535]
## Description

When running `npx pod-install`, the command hangs for a long time after displaying `Pod installation complete!`.

If I run `time pod install` the command takes `7.5s`. However, if I run `time npx pod-install` the command takes `1m27.3s`.

## Expected Behavior

Command should exit after displaying `Pod installation complete!`.

## Observed Behavior

Command hangs for about `1m20s` after displaying `Pod installation complete!`.

## Environment

Node version: v12.4.0
NPM version: 6.9.0
Cocoapods version: 1.8.4

## Reproducible Demo

```bash
git clone https://github.com/grit96/pod-install-test
cd pod-install-test
npx pod-install
```

**Comment by EvanBacon** [comment]
The repro runs in 1.75s:
```
evanbacon@Evans-MBP pod-install-test % time npx pod-install
npx: installed 1 in 0.668s
Scanning for pods...
1.9.3
> pod install
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 0 dependencies from the Podfile and 0 total pods installed.
npx pod-install  1.75s user 0.68s system 101% cpu 2.395 total
evanbacon@Evans-MBP pod-install-test % 
```

**Comment by brentvatne** [comment]
@grit96 - could you have been experiencing an intermittent internet connectivity issue?

**Comment by grit96** [comment]
I think it's related to HTTP proxies. If I run `pod install` or `npx pod-install` without proxies they both finish quickly, whereas with HTTP proxies enabled (through `http_proxy` and `https_proxy` environment variables) `pod install` finishes quickly but `npx pod-install` hangs.

**Comment by EvanBacon** [comment]
I think http proxy is out of scope for this particular tool. Open to PRs if you’d like to contribute!
