### ISSUE TITLE
Apple Push Notification service key for your account could not be loaded

### ISSUE THREAD

**Issue by mymattcarroll** [expo/expo-cli#2544]
## Description

Our app was successfully sending push notifications to iOS and at some point it has stopped working, sorry we don't have an exact date. May 7th 2020 was when the issue was reported by our users.

## Expected Behavior

Push notification certificate to be cleared and changed to the uploaded push notifications certificate. It seems that the `--clear-credentials` flag is not working as expected? 

## Observed Behavior

The push notification is successfully received by Expo, getting the following payload returned:

```json
[
  {
    "status": "ok",
    "id": "b8bc0532-cbc0-4f1c-97ce-683b69e8c9f1"
  }
]
```

However, when querying expo to get the receipt, we get the following error response:

```json
{
  "b8bc0532-cbc0-4f1c-97ce-683b69e8c9f1": {
    "status": "error",
    "message": "The Apple Push Notification service key for your account could not be loaded, likely due to a malformed p8 file. Expo needs a valid PEM key in order to deliver notifications to APNs.",
    "details": {
      "error": "InvalidCredentials",
      "sentAt": 1598837677
    },
    "__debug": {
      "internalError": "Failed to generate token: error:0909006C:PEM routines:get_name:no start line"
    }
  }
}
```

We have attempted to re-create the p8 file and re-build the app, but the same error keeps occurring.

Our builds are automated and currently use the following command:

```sh
build:ios --apple-id fake@email.com --team-id FAKE_TEAM_ID --dist-p12-path ./path/to/file.p12 --push-id FAKE_PUSH_ID --push-p8-path path/to/file.p8 --provisioning-profile-path path/to/file.mobileprovision --no-wait --non-interactive --clear-credentials --release-channel v3
```

## Environment

```
  Expo CLI 3.25.1 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.5.1 - /usr/local/bin/zsh
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.14.8 - ~/.npm-packages/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.9 => 38.0.9 
      react: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-navigation: 4.0.10 => 4.0.10 
```

This is occurring on all iOS devices? We can reproduce in TestFlight and on a live app.

**Comment by mymattcarroll** [comment]
Updating to `expo-cli@2.26.1` seems to have fixed our issue.

**Comment by kuriel-trivu** [comment]
@mymattcarroll  what do you mean? with updating expo-cli, do we need to build another binary? to fix issue. Or just by updating expo-cli locally? (wich is not probably the solution since binary and server has no relation with local)

**Comment by kuriel-trivu** [comment]
Just check the error InvalidCredentials in docs:

https://docs.expo.dev/push-notifications/sending-notifications/#push-receipt-errors
