### ISSUE TITLE
Unable to log in with Apple ID

### ISSUE THREAD

**Issue by miko1991** [expo/expo-cli#2545]
Hello, I tried to login with apple id to build my ios version of the app, and the password is 100% correct, but i cant.

**Comment by EvanBacon** [comment]
Please fill out the entire issue template. Are you on a mac? Perhaps the password was incorrectly entered the first time, and saved in keychain, if that's the case use `EXPO_NO_KEYCHAIN=true` to disable the keychain. Learn more: https://docs.expo.io/distribution/security/#keychain

**Comment by EvanBacon** [comment]
Closing, please feel free to open with more info.
