### ISSUE TITLE
Failed to publish with error: "files must be an array"

### ISSUE THREAD

**Issue by jeloagnasin** [expo/expo-cli#2549]
## Description

When I try to publish, it fails with an error: "files must be an array".

## Expected Behavior

I ran: `expo publish --release-channel prod-2.7.0` and I'm expecting it finish successfully.

## Observed Behavior

```
$ expo publish --release-channel prod-2.7.0
Warning: this is a bare workflow project. The resulting publish will only run properly inside of a native build of your project.
If you want to publish a version of your app that will run in Expo client, please use expo publish --target managed.
You can skip this warning by explicitly running expo publish --target bare in the future.

Publishing to channel 'prod-2.7.0'...
We noticed that you have not built a standalone app with this SDK version and release channel before. Remember that OTA updates will only work for builds with matching SDK versions and release channels. Read more here: https://docs.expo.io/workflow/publishing/#limitations
Starting Metro Bundler.
Building iOS bundle
Building Android bundle
Building source maps
Building asset maps
Finished building JavaScript bundle in 7930ms.
Finished building JavaScript bundle in 1905ms.
Finished building JavaScript bundle in 0ms.
Finished building JavaScript bundle in 0ms.
Analyzing assets
Uploading assets
{"buildID":"5","type":"bundl
Uploading /src/assets/dfi-trial-popup.jpg
"files" must be an array.
Building JavaScript bundle [==========================================               ] 74%
```

## Environment

```
  Expo CLI 3.25.1 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.18.2/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.6 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
      react-native-web: ~0.11.7 => 0.11.7 
```

**Comment by tobias7an** [comment]
I began experiencing the same issue today.

The same cryptic error immediately occurs after uploading an asset, for both `expo publish` and `expo build`.

My environment is as follows:
`  Expo CLI 3.25.1 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4907809
    npmPackages:
      expo: ^36.0.0 => 36.0.2
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4
      react-navigation: ^3.11.1 => 3.13.0
`


I could not find this error defined anywhere in the metro bundler and expo github repositories, or any way to access any additional logging about the source of the error.

**Comment by franjorub** [comment]
same issue for me, the way I can made a build was taking a look in the files that are loading in the console 
![image](https://user-images.githubusercontent.com/24401350/91786746-4ae0da00-ebd6-11ea-9718-c52e5b5e1faa.png)
I deleted them and copy many times another asset and rename it. 

later says that the assets doesn't changed, SKIP and did the deploy

**Comment by lindboe** [comment]
Other people have been reporting this issue on the expo slack: https://expo-developers.slack.com/archives/C04Q3JTSV/p1598917527029400

**Comment by tobias7an** [comment]
This issue has been resolved from my end as of this post. 

(On Expo Priority if that makes a difference, as this seemed to be a server-side bug.)

**Comment by EvanBacon** [comment]
Seems this was a server outage, closing.
