### ISSUE TITLE
Could not find the "expo" package in your project when configuring the packager

### ISSUE THREAD

**Issue by vjpr** [expo/expo-cli#255]
## Description
```
[19:43:42] Could not find the "expo" package in your project when configuring the packager
```

Using `console-caller` to track location of message:

```
{caller: [getCliConfig$ (/xxx/node_modules/.github.com/expo/react-native/archive/sdk-31.0.0.tar.gz/react@16.5.0/node_modules/react-native/local-cli/core/index.js:141:9)]}
```

```js
async function getCliConfig(): Promise<RNConfig> {
  const cliArgs = minimist(process.argv.slice(2));
  const config = await Config.load(
    cliArgs.config != null ? path.resolve(__dirname, cliArgs.config) : null,
  );

  config.transformer.assetRegistryPath = ASSET_REGISTRY_PATH;

  // NOTE(expo): include the Expo asset plugin to support static resources
  try {
    let expoAssetPluginPath = require.resolve('expo/tools/hashAssetFiles');
    config.transformer.assetPlugins = [expoAssetPluginPath];
  } catch (e) {
    console.warn('Could not find the "expo" package in your project when configuring the packager');
  }

  config.resolver.hasteImplModulePath =
    config.resolver.hasteImplModulePath || defaultConfig.hasteImplModulePath;
  config.resolver.platforms = config.resolver.platforms
    ? config.resolver.platforms.concat(defaultConfig.getPlatforms())
    : defaultConfig.getPlatforms();
  config.resolver.providesModuleNodeModules = config.resolver
    .providesModuleNodeModules
    ? config.resolver.providesModuleNodeModules.concat(
        defaultConfig.getProvidesModuleNodeModules(),
      )
    : defaultConfig.getProvidesModuleNodeModules();

  return {...defaultRNConfig, ...config};
}
```

This is the cause:

```
let expoAssetPluginPath = require.resolve('expo/tools/hashAssetFiles');
```

`expo` needs to then be a dependency of `react-native`.

In a pnpm monorepo setting `react-native` is here:

```
/xxx/node_modules/.github.com/expo/react-native/archive/sdk-31.0.0.tar.gz/react@16.5.0/node_modules/react-native/local-cli/cli.js
```

But `expo` is only available in the sub-package of the monorepo.

This should be configurable.

**Comment by SounD120** [comment]
Hello, I am maintainer of [vscode-react-native](https://github.com/Microsoft/vscode-react-native). We had faced with the same problem recently when running pure React Native app via Expo. This works without any problem on `XDL@52.0.0`, but the latest versions throws us the similar error connected with `expo/tools/hashAssetFiles` file absence.

**Comment by fson** [comment]
@ide this seems to be related to this hack in the SDK 31 react-native version that imports `expo` directly: https://github.com/expo/react-native/commit/d41bc86fd9fec9c55ae72bd4cdc1508097f7796b. `expo` is not a dependency of `react-native`, so this only works by accident, if the packages happen to be flattened in the `node_modules` tree. What's the plan for getting rid of that code in the fork?

**Comment by ide** [comment]
xdl was written to work with expo - xdl stands for eXpo Development Library. Also the patched version of RN is designed for expo as well so you'll need both of those.

> expo is not a dependency of react-native, so this only works by accident, if the packages happen to be flattened in the node_modules tree

In practice (99.99% of projects?) expo is installed next to react-native. package.json should specify both expo and react-native => npm/yarn will install expo next to react-native regardless of flattening.
> What's the plan for getting rid of that code in the fork?

Metro broke the URL-based way of specifying the plugin so we need this. We'd need to patch Metro and then make a change to XDL.

**Comment by ruslan-bikkinin** [comment]
Hi @ide does it mean that since latest version if expo cli/xdl if we want to run RN project under the expo cli (`expo start`) we need to install expo package inside the project? I am asking because recently it wasn't obligatory for older versions.

**Comment by ide** [comment]
Yes, that is the intent. It may have unintentionally worked before but Expo CLI is meant to be used with `expo`. If you don't use any of the Expo APIs, the Expo JS won't get bundled in your app so there should be no effect there.

**Comment by ruslan-bikkinin** [comment]
Thanks for confirmation @ide.

**Comment by EvanBacon** [comment]
We've changed how configs are read, please feel free to reopen if the issue persists.
