### ISSUE TITLE
Error in publish assets "files" must be an array

### ISSUE THREAD

**Issue by mhisham** [expo/expo-cli#2551]
## Description
Upload assets failed on expo-cli 3.25.1
with Error message :

 _"files" must be an array._

I tried to trace the error from the expo-cli code and found that error coming from the API request:
**Request:**
PUT https://exp.host/--/api/v2/assets/upload
**Response:** 
[ { code: 'API_ERROR', message: '"files" must be an array.' } ]

Reproduction:
1- Creating a new expo project
2- add any image on the page 
`<Image source={require("../assets/images/addIcon.png")} resizeMode="contain" />` 
3- run expo publish

## Expected Behavior
- Publish to expo successfully

## Observed Behavior

```
"files" must be an array.
```

## Environment
Mac OS 10.15.6
expo-cli 3.25.1
NodeJs v12.18.3

  Expo CLI 3.25.1 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.10 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.25.1

**Comment by mhisham** [comment]
![Screen Shot 2020-09-01 at 4 53 15 AM](https://user-images.githubusercontent.com/873566/91786142-9e234e80-ec0f-11ea-949a-38175c9d7bad.png)

**Comment by franjorub** [comment]
I have this error too starts today

**Comment by afkim14** [comment]
Same thing here. Using `expo-cli 3.21.3`.

**Comment by franjorub** [comment]
I really don't fall in spam or something but anyway to notify the maintainers directly ? or a workaround for made a quick build locally ? we need publish a new version soon  :(

**Comment by mhisham** [comment]
@franjorub I spent 8 hours trying to know the reason, try to uninstall expo-cli and install old version may that solve the problem, I’m not sure which version could work

**Comment by franjorub** [comment]
@mhisham looking at your post 

PUT https://exp.host/--/api/v2/assets/upload

maybe could be a problem in theirs API as such ?

**Comment by wschurman** [comment]
Looking into this now, thanks for the report!

**Comment by davidsed** [comment]
I also have this error.  I am using expo-cli 3.22.1.  I'm wondering if I can change my settings so it skips the upload as I don't need to upload any changed assets but I really need to publish

**Comment by wschurman** [comment]
This should be fixed as of 8:39 PST. Let me know if you are still seeing issues.

**Comment by davidsed** [comment]
Looks like this is fixed now.  Publish worked for me

**Comment by franjorub** [comment]
fixed. Thanks a lot @wschurman
