### ISSUE TITLE
Failed to find the instance of sharp used by the global sharp-cli package.

### ISSUE THREAD

**Issue by barnu5** [expo/expo-cli#2552]
## Description
expo build:web fails to run.

I have tried the usual - 

- uninstalling and reinstalling sharp-cli globally with npm and yarn.
- upgrading expo-cli
- removing sharp-cli globally altogether

Unfortunately the error prevents build

## Environment

 Expo CLI 3.25.1 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
    npmPackages:
      expo: ~38.0.0 => 38.0.8
      react: ~16.11.0 => 16.11.0
      react-dom: ^16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ^0.11 => 0.11.7

**Comment by byCedric** [comment]
Hi @barnu5, thanks for the report. What is the exact error you get when running `$ expo build:web`? Sharp should be an optional dependency, and it should fallback to the slower jimp package. Because of that, it could be something else that's blocking your command. 😄

**Comment by EvanBacon** [comment]
You can disable sharp with the env variable `EXPO_IMAGE_UTILS_NO_SHARP`, like `EXPO_IMAGE_UTILS_NO_SHARP=true expo build:web`

**Comment by EvanBacon** [comment]
Closing, please feel free to open with more info (like the error message that's thrown).
