### ISSUE TITLE
Error when generating build for web

### ISSUE THREAD

**Issue by LorhanSohaky** [expo/expo-cli#2554]
# Description
When running `expo build:web` it gives a error

Example
https://github.com/LorhanSohaky/example-expo-build-web-error

## Observed Behavior
```
 web  Failed to compile.

unable to locate '/home/user/project/app/web' at '/home/user/project/app/web/**/*'
Error: unable to locate '/home/user/project/app/web' at '/home/user/project/app/web/**/*'

```

## Environment
  Expo CLI 3.26.0 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    npmPackages:
      expo: ~37.0.3 => 37.0.7 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
      react-native-web: ~0.11.7 => 0.11.7

**Comment by EvanBacon** [comment]
Could you please provide a repro?

**Comment by LorhanSohaky** [comment]
@EvanBacon , here https://github.com/LorhanSohaky/example-expo-build-web-error

**Comment by EvanBacon** [comment]
Thanks for the repro, made it much easier to solve!

**Comment by EvanBacon** [comment]
In the meantime if you eject any other file like `web/index.html` it should fix the bug.

**Comment by LorhanSohaky** [comment]
@EvanBacon , can you tell me when will the next release be fixed?
