### ISSUE TITLE
expo upgrade command uses [object Object] as latest SDK version

### ISSUE THREAD

**Issue by jleroy-dev** [expo/expo-cli#2556]
##  Description

When running `expo upgrade` command without specifying the targeted SDK version, it will use [object Object] instead.

## Expected Behavior

When not providing a target SDK version, it should default to latest SDK version.

## Observed Behavior

1. Install `expo-cli@26.0.0`
2. Observe following log:  
```? You provided the target SDK version value of [object Object] which does not seem to exist. But hey, I'm just a program, what do I know. Do you want to try to upgrade to it anyways? (Y/n)```

## Environment

```
  Expo CLI 3.26.0 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.10
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
```

**Comment by byCedric** [comment]
Hi @jleroy-dev, thanks for the report. I've created a PR that should fix this!

**Comment by brentvatne** [comment]
can you explain the use case for passing in a sdk version manually to `expo upgrade`?

**Comment by jleroy-dev** [comment]
Thank you for the fast answer 👍 
Awesome package by awesome developers

**Comment by brentvatne** [comment]
expo-cli@3.26.1 is out with the fix :) thanks @jleroy-dev for the report!
