### ISSUE TITLE
[12:44:35] (_xdl || _load_xdl(...)).Exp.downloadTemplateApp is not a function [12:44:35] Set EXPO_DEBUG=true in your env to view the stack trace.expo diagnostics

### ISSUE THREAD

**Issue by younes856** [expo/expo-cli#2564]
Hi all, 
I m Newer in ReactNative, I installed expo npm install -g exp
When I try to create new App I had always this message:
[12:44:35] (_xdl || _load_xdl(...)).Exp.downloadTemplateApp is not a function
[12:44:35] Set EXPO_DEBUG=true in your env to view the stack trace.
I uninstalled exp then install new one, always the same message. I saw forum but no solution.
Thank you for your help

**Comment by EvanBacon** [comment]
Install expo with `npm i -g expo-cli`. Please refer to the docs for how to get started https://docs.expo.io/
