### ISSUE TITLE
App doesn't open on iOS Devices from release-channel

### ISSUE THREAD

**Issue by AyazBulls** [expo/expo-cli#2609]
##  Description

I published my Expo app on a release channel. The app works fine on Android but it doesn't even open on iOS devices, it shows an error "There was a problem loading the requested app". Also do know that it works fine on both platform in local mode (expo start).

## Expected Behavior
I tried publishing it in a new channel but it still doesn't open on iOS devices.

## Observed Behavior
It doesn't open the app and shows this error:
```
There was a problem loading the requested app
[..]
exp://exp.host/@devhara/Peach?release-channel=develop-v1

Could not load ex://exp.host/@devhara/Peach?release-channel=develop-v1
```

## Environment
`expo diagnostics`
```
  Expo CLI 3.26.2 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 10.14.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6308749
    npmPackages:
      expo: ~38.0.8 => 38.0.8
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.1.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
      react-navigation: ^4.4.0 => 4.4.0
```
I tried to open the app from the release-channel with an iPhone 6.

## Reproducible Demo

Here is the release-channel link: https://expo.io/@devhara/Peach?release-channel=develop-v1

**Comment by brentvatne** [comment]
are you signed in to the `devhara` account in the iOS client?

**Comment by AyazBulls** [comment]
No i'm not. But i'm not signed in on Android and it works fine...

**Comment by brentvatne** [comment]
it's required on ios due to app store policies

**Comment by AyazBulls** [comment]
Oh i see, i didn't see it in the documentation. Thanks a lot @brentvatne !

**Comment by AyazBulls** [comment]
It works :)
