### ISSUE TITLE
Installed SDK Version not in range of accepted versions

### ISSUE THREAD

**Issue by schematis** [expo/expo-cli#2610]
## Description

When running `expo start` an error occurs saying that the installed sdk version is not in the accepted range. `expo init` installs version `^38.0.0`, max supported in range is `37.0.0`.

## Expected Behavior

I went through the steps for `expo init`, selected a template and then ran `yarn start` when it finished installing.

## Observed Behavior

```
Error: Invalid sdkVersion. Valid options are 7.0.0, 8.0.0, 9.0.0, 10.0.0, 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0, 16.0.0, 17.0.0, 18.0.0, 19.0.0, 20.0.0, 21.0.0, 22.0.0, 23.0.0, 24.0.0, 25.0.0, 26.0.0, 27.0.0, 28.0.0, 29.0.0, 30.0.0, 31.0.0, 32.0.0, 33.0.0, 34.0.0, 35.0.0, 36.0.0, 37.0.0
```

## Environment
```
  Expo CLI 3.26.2 environment info:
    System:
      OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
      Yarn: 1.22.4 - /usr/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
    npmPackages:
      expo: ~38.0.8 => 38.0.10
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
```

## Reproducible Demo

No demo. occurs on first run with any template.

**Comment by brentvatne** [comment]
which template did you select?

**Comment by brentvatne** [comment]
i can't reproduce this on my end, it sounds like you have an old schema cache. this is stored in `~/.expo/cache`. can you zip the contents of that directory and share it?

**Comment by schematis** [comment]
> 
> 
> which template did you select?

I've tried the blank, blank typescript, and tabs typescript. It's worth noting that the tabs typescript also installed an old version of expo-splash-screen

>
>
> i can't reproduce this on my end, it sounds like you have an old schema cache. this is stored in ~/.expo/cache. can you zip the contents of that directory and share it?

I uninstalled expo-cli, rm -rf'ed my ~/.expo folder, and then re-installed expo-cli and tried again. Same result. Attached is my template-cache folder.

[template-cache.zip](https://github.com/expo/expo-cli/files/5191034/template-cache.zip)

**Comment by brentvatne** [comment]
hey @schematis - that is the template cache and not the schema cache. could you share the schema cache? `~/.expo/cache`. it should contain files like `versions.json`

**Comment by schematis** [comment]
Ah, I don't have that so I thought you meant the template cache. Here's what I do have:
```
bvinson@MGPF18GEWF:~/.expo$ ll
total 8
drwxrwxrwx 1 bvinson bvinson 4096 Sep  8 15:49 ./
drwxr-xr-x 1 bvinson bvinson 4096 Sep  8 15:44 ../
-rw-rw-rw- 1 bvinson bvinson 1790 Sep  8 15:49 PATH
-rw-rw-rw- 1 bvinson bvinson 1807 Sep  8 15:49 state.json
drwxrwxrwx 1 bvinson bvinson 4096 Sep  8 15:44 template-cache/
-rw-rw-rw- 1 bvinson bvinson   41 Sep  8 15:49 xde-recent-exps.json
```

**Comment by schematis** [comment]
I found versions.json under ~/.cache/expo, here is that folder.
[expo-cache.zip](https://github.com/expo/expo-cli/files/5191107/expo-cache.zip)

**Comment by brentvatne** [comment]
indeed that file appears to be out of date. can you try clearing `~/.cache/expo` and trying again?

**Comment by brentvatne** [comment]
also, does https://expo.io/--/api/v2/versions load for you?

**Comment by schematis** [comment]
Was just testing that and it looks like deleting that folder fixed the issue with the SDK version (though the expo splash screen one in the tabs typescript template still persists). 

That does load for me in the browser, however I'm behind a work proxy so curl, etc is problematic and it throws this error:

```
Warning: Problem validating app.json: Unable to perform cache refresh for /home/bvinson/.cache/expo/schema-38.0.0.json: Error: Request failed with status code 400.
```

**Comment by brentvatne** [comment]
> That does load for me in the browser, however I'm behind a work proxy so curl, etc is problematic and throws an ssl error.

i see, i believe this is related to https://github.com/expo/expo-cli/issues/120#issuecomment-562807876. want to take a stab at fixing that?

> (though the expo splash screen one in the tabs typescript template still persists).

i just published an update to the template to resolve this. you may need to clear your template cache to get it right away. the reason it happened is we bumped the splash screen version last week and looks like i missed out on updating this template accordingly (the template would continue to work fine, it's just a warning).

**Comment by schematis** [comment]
> 
> 
> > That does load for me in the browser, however I'm behind a work proxy so curl, etc is problematic and throws an ssl error.
> 
> i see, i believe this is related to [#120 (comment)](https://github.com/expo/expo-cli/issues/120#issuecomment-562807876). want to take a stab at fixing that?

My schedule is unfortunately pretty busy, but shouldn't that be as simple as detecting if http(s) proxy environment variables are set and then setting the agent param on axios if they're there?

> 
> > (though the expo splash screen one in the tabs typescript template still persists).
> 
> i just published an update to the template to resolve this. you may need to clear your template cache to get it right away. the reason it happened is we bumped the splash screen version last week and looks like i missed out on updating this template accordingly (the template would continue to work fine, it's just a warning).

One related question, what packages can I upgrade without breaking things? For instance Typescript and React Native are several version behind.

**Comment by brentvatne** [comment]
> My schedule is unfortunately pretty busy, but shouldn't that be as simple as detecting if http(s) proxy environment variables are set and then setting the agent param on axios if they're there?

probably, but i don't have time personally to work on this

> One related question, what packages can I upgrade without breaking things? For instance Typescript and React Native are several version behind.

the react-native version is the latest stable version at the time when sdk 38 was released and each sdk version only works with a single react-native version. you can use a newer typescript version if you want to. this page might be helpful for info on using libraries in managed workflow: https://docs.expo.io/bare/using-libraries/
