### ISSUE TITLE
Support vapidPublicKey in app.json

### ISSUE THREAD

**Issue by jaulz** [expo/expo-cli#2613]
## Description

Currently, `vapidPublicKey` is supported in code but not in `app.json`:
https://github.com/expo/expo/blob/master/packages/expo-notifications/src/getDevicePushTokenAsync.web.ts#L70

## Expected Behavior

`vapidPublicKey` should be supported in `app.json`. While I understand that there might no official support for web push notifications it would be great if could add this at least to the validation. If someone could point me to the part where the validation/schema is located I'm happy to raise a PR.

## Observed Behavior

While running `expo publish` I get the following error:

```
[09:23:23] Error: Problem validating fields in app.json. See https://docs.expo.io/workflow/configuration/
[09:23:23]  • Field: notification - should NOT have additional property 'vapidPublicKey'.
[09:23:23] Couldn't publish because errors were found. (See logs above.) Please fix the errors and try again.
```

## Environment

```
  Expo CLI 3.26.2 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 3.1.2 - /usr/local/bin/fish
    Binaries:
      Node: 14.7.0 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.7/11E801a - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.28 => 0.12.28 
      expo: ^38.0.9 => 38.0.9 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz => 0.62.2 
      react-native-web: 0.13.9 => 0.13.9 
    npmGlobalPackages:
      expo-cli: 3.26.2
```

## Reproducible Demo

Add `vapidPublicKey` property in `expo.notification` in `app.json` and run `expo publish` afterwards.

**Comment by robertherber** [comment]
+1

**Comment by brentvatne** [comment]
this is not a publicly documented feature and therefore isn't supported
