### ISSUE TITLE
I have a question with expo build: ios

### ISSUE THREAD

**Issue by dan9159** [expo/expo-cli#2630]
## Description

build: ios I build my app react native expo and when I downloaded the compiled one, it returned a zip file to me. My question is how do I extract the .ipa file or how do I install it on my iphone to be able to test my app?

## Expected Behavior

be able to install the .ipa file on my iphone

## Observed Behavior

In the zip file there are many things but I do not see one in a specific ipa extension

## Environment

react native expo

## Reproducible Demo

![image](https://user-images.githubusercontent.com/71149135/92960594-233a0f00-f42b-11ea-8a5b-3bb202ab1835.png)

**Comment by brentvatne** [comment]
- if you build with the "simulator" type you can run it on your simulator
- if you build with the "archive" type, you need to upload it to testflight and then from there you can test it on your device :)

in the future we'll have first-class ad-hoc provisioning profile support to make it easier to test on your device without Expo client, but for now this is the state of the world. if you are familiar enough with app signing, you can create your own ad-hoc provisioning profile and use it with the build service ([more info](https://docs.expo.io/distribution/building-standalone-apps/#adhoc-distribution))
