### ISSUE TITLE
Allow complete override of packager URL 

### ISSUE THREAD

**Issue by Inlustra** [expo/expo-cli#2633]
## Description

I'm currently hosting my development environment via [code-server](https://hub.docker.com/r/linuxserver/code-server) which does present some challenges that I'm hoping to solve.

I'd like to caveat this by saying that I understand that this is still a pretty niche topic, nevertheless it works well for me in other regards, I can effectively develop on my Samsung Dex and iPad pro for example.

The way you expose ports from within the docker container looks something like this: https://19000.mydomain.com, https://19001.mydomain.com... etc
The internal code server then proxies those requests to the individual ports.

Using this for expo presents some issues as it _always_ appends the port to the url as opposed to allowing us to specify a full exp:// url for example.

### Example command: 

`REACT_NATIVE_PACKAGER_HOSTNAME=19000.mydomain.com EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0 expo start'`

QR Code and URL output:
`exp://19000.mydomain.com:19000`

## Solution

I'm happy to raise this PR and it looks like some fairly straightforward changes to:
https://github.com/expo/expo-cli/blob/master/packages/dev-tools/server/DevToolsServer.ts

```
function devtoolsGraphQLHost(): string {
  if (process.env.EXPO_DEVTOOLS_LISTEN_ADDRESS && process.env.REACT_NATIVE_PACKAGER_HOSTNAME) {
    return process.env.REACT_NATIVE_PACKAGER_HOSTNAME.trim();
  } else if (process.env.EXPO_DEVTOOLS_LISTEN_ADDRESS) {
    return process.env.EXPO_DEVTOOLS_LISTEN_ADDRESS;
  }
  return 'localhost';
}
```

and

```
export async function createAuthenticationContextAsync({ port }: { port: number }) {
  const clientAuthenticationToken = await generateSecureRandomTokenAsync();
  const endpointUrlToken = await generateSecureRandomTokenAsync();
  const graphQLEndpointPath = `/${endpointUrlToken}/graphql`;
  const hostname = `${devtoolsGraphQLHost()}:${port}`;
  const webSocketGraphQLUrl = `ws://${hostname}${graphQLEndpointPath}`;
  const allowedOrigin = `http://${hostname}`;
  return {
    clientAuthenticationToken,
    graphQLEndpointPath,
    webSocketGraphQLUrl,
    allowedOrigin,
    requestHandler: (request: express.Request, response: express.Response): void => {
      response.json({ webSocketGraphQLUrl, clientAuthenticationToken });
    },
  };
}
```

And also to the file:
https://github.com/expo/expo-cli/blob/master/packages/xdl/src/UrlUtils.ts

I wanted to get some feedback to understand whether their would be other changes needed?

**Comment by kiwina** [comment]
Totally agree, beeing able to expose the ui especially on the local network has quite a few advantages, for me mainly been screen real estate, beeing able to monitor from a different machine on the network

**Comment by brentvatne** [comment]
hi there! if anyone is interested in pursuing this further, please go ahead and open a pr. you can run this and test it locally to make sure it fits your needs. nobody at expo uses this workflow so we are not the best suited to implement it

**Comment by srosato** [comment]
Am I missing something more complex or is the PR would consist that we just pass in a `EXPO_DEVTOOLS_LISTEN_PORT` env var and then use this and fallback to the default port of 19002? 

That way users can use a combination of `EXPO_DEVTOOLS_LISTEN_PORT` with `REACT_NATIVE_PACKAGER_HOSTNAME` to get their desired host:port.
