### ISSUE TITLE
couldn't start project on android: error running adb: error running app

### ISSUE THREAD

**Issue by boualizakaria** [expo/expo-cli#2637]
when i run `npm start` command to run my app on android emulator this error appears 

couldn't` start project on android: error running adb: error running app. error: activity not started, unable to resolve intent { act=android.intent.action.view dat=exp://192.168.1.2:19000 flg=0x10000000 }

**Comment by EvanBacon** [comment]
Please fill out the full issue template, `npm start` can mean anything.

**Comment by EvanBacon** [comment]
Closing because I cannot repro, please feel free to reopen with more info.
