### ISSUE TITLE
New Project: "Failed building JavaScript bundle. Cannot read property 'map' of undefined"

### ISSUE THREAD

**Issue by ajrehl** [expo/expo-cli#2638]
## Description
Created a new project (expo init testapp). Started the template app (expo start). Tried running on android emulator and physical device by scanning the QR code with phone. 

## Expected Behavior
The template app should have booted up on either device.

## Observed Behavior
The app breaks with errors.
The following is the output from the console in Metro Bundler:
```
INFO  Starting Metro Bundler.
ERROR  Building JavaScript bundle: error
ERROR  Cannot read property 'map' of undefined
```
The following is the error shown on the phone/emulator:
![image](https://user-images.githubusercontent.com/37492983/93034002-75c32900-f5ed-11ea-8886-1dfe795a95b1.png)

## Environment
Windows 10 pro

**Expo Diagnostics**

 Expo CLI 3.27.4 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 19, 21, 22, 24, 25, 27, 28, 29
        Build Tools: 23.0.3, 25.0.2, 27.0.3, 28.0.1, 28.0.3, 30.0.0, 30.0.2
        System Images: android-22 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
    npmPackages:
      expo: ~38.0.8 => 38.0.10
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    Expo Workflow: managed

**Phone**
model: moto g7 power
android version: 10.0

**Emulator (x2)**
model: Nexus 5 API 24
android version: 7.0

model: Pixel 3a API 29
android version: 10.0

## Reproducible Demo
`expo init testapp`
`cd testapp`
`expo start`

In Metro Bundler:
Click on "Run on Android Device/Emulator"
Also scan QR code for physical device
Both result in the same error

**Comment by bogda23** [comment]
Same problem here!

**Comment by brentvatne** [comment]
hi there! which terminal are you using?

@byCedric - any chance you could try to repro this given it seems to be a windows issue?

**Comment by ajrehl** [comment]
@brentvatne @bogda23 

Sorry for the delay. Yes, the only step I took, which resulted in the error, was to init a blank app and try to run it. 

I figured out a workaround until this issue is resolved. I ultimately reverted back to previous versions of expo and react. Below is my temporary configuration. Hopefully, this will help the team troubleshoot.

Expo CLI 3.27.4 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 19, 21, 22, 24, 25, 27, 28, 29
        Build Tools: 23.0.3, 25.0.2, 27.0.3, 28.0.1, 28.0.3, 30.0.0, 30.0.2
        System Images: android-22 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
    npmPackages:
      expo: ~37.0.12 => 37.0.12
      react: 16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: ~0.61.3 => 0.61.3
      react-native-web: ~0.11.7 => 0.11.7
    Expo Workflow: managed

**Comment by shukhratgadoev** [comment]
Same problem!

**Comment by matiasracedo** [comment]
Same problem here!

**Comment by matiasracedo** [comment]
I found the answer!! I solved this issue my deleting this folder C:\Users\<USER>\AppData\Local\Temp\metro-cache –

**Comment by brentvatne** [comment]
if you encounter this problem, try running `expo start --clear` to clear your cache
