### ISSUE TITLE
"All iOS apps submitted to the App Store must be built with the iOS 12.1 SDK or later"

### ISSUE THREAD

**Issue by rxhivzero** [expo/expo-cli#264]
SDK Version Issue - This app was built with the iOS 12.0 SDK. Starting March 2019, all iOS apps submitted to the App Store must be built with the iOS 12.1 SDK or later, included in Xcode 10.1 or later.

**Comment by esamelson** [comment]
Tracking this here https://github.com/expo/expo/issues/3125. I'm going to go ahead and close this issue since it isn't a problem with expo-cli

**Comment by candasnasif** [comment]
I am using Expo SDK 33.0. I built my project for ios(expo build:ios).But generated ipas  sdk version is still 11.4.Because of that I am getting error about my sdk issue. What am i missing?

**Comment by dsokal** [comment]
Hello @candasnasif,
could you please send the url to the build logs page? I need that to help you :)

**Comment by candasnasif** [comment]
[](https://expo.io/builds/5ed41d86-8fca-45c9-92ea-4d7cdd0f943a)

**Comment by dsokal** [comment]
@candasnasif are you sure you were uploading the right .ipa file? :)
I checked your `.ipa` and it's on sdk 12.1:
![Screenshot 2019-06-17 at 11 13 35](https://user-images.githubusercontent.com/5256730/59592872-2859c280-90f1-11e9-9a28-cd140818577b.png)

**Comment by candasnasif** [comment]
Thanks for the help:)

Dominik Sokal <notifications@github.com>, 17 Haz 2019 Pzt, 12:16 tarihinde
şunu yazdı:
