### ISSUE TITLE
Can't install expo-cli

### ISSUE THREAD

**Issue by alejandroaperez1994g** [expo/expo-cli#2646]
node --version v10.19.0

sudo npm install --unsafe-perm -g expo-cli
npm WARN deprecated @hapi/joi@17.1.1: joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)
npm WARN deprecated @hapi/formula@2.0.0: This version has been deprecated and is no longer supported or maintained
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/traveling-fastlane-darwin@1.15.1 (node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/traveling-fastlane-darwin@1.15.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! Unexpected end of JSON input while parsing near '...ependencies":{"@babel'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-15T17_42_35_484Z-debug.log
alejandro@alejandro-InsydeH2O-EFI-BIOS:~$ sudo npm install expo-cli --global
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning undefined: network timeout at: https://registry.npmjs.org/expo-cli
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm WARN deprecated @hapi/joi@17.1.1: joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)
npm WARN deprecated @hapi/formula@2.0.0: This version has been deprecated and is no longer supported or maintained
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/traveling-fastlane-darwin@1.15.1 (node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/traveling-fastlane-darwin@1.15.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! Unexpected end of JSON input while parsing near '...ependencies":{"@babel'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-15T17_55_40_081Z-debug.log

**Comment by brentvatne** [comment]
lots of issues have been posted about this :) it's a npm issue

from https://github.com/expo/expo-cli/issues/2084#issuecomment-625428161

> hi there! this is a probably that people occasionally encounter with npm on windows: https://stackoverflow.com/questions/47675478/npm-install-errorunexpected-end-of-json-input-while-parsing-near-nt-webpack
>
> to resolve it, run:
>
> ```
> npm cache clean --force
> npm install -g expo-cli
> ```
