### ISSUE TITLE
Ejecting to bare workflow in Windows 10 issues with package name/path

### ISSUE THREAD

**Issue by popeating** [expo/expo-cli#2675]
## Description

When ejecting to bare workflow (using Windows10 and Powershell) the resulting Android project do not create correctly the path and files based on package name choosen while ejecting; also package and reference in MainActivity.java, MainApplication.java, generated/BasePackageList.java are incomplete

## Expected Behavior

Ejecting should create path, files, package and reference correctly

## Observed Behavior

First of all i created a new expo project with:
```expo init eject_app```
and everything went with no error:
![image](https://user-images.githubusercontent.com/10193354/93821658-23be7b00-fc5f-11ea-9917-78a915d1d2a3.png)

Then i entered the app folder and tested (successfully) the app in expo with Android emulator
![image](https://user-images.githubusercontent.com/10193354/93821837-7ac45000-fc5f-11ea-9158-1a2e7465d763.png)

At this point i ejected the app using:
```expo eject```
and used com.popland.eject_app as package name and com.popland.ejectapp as iOS Bundle identifier
![image](https://user-images.githubusercontent.com/10193354/93822387-72b8e000-fc60-11ea-9f38-1bdd6ab925eb.png)

i got a warning about MainActivity (that's because MainActivity was not created where it should)
if i check 
```eject_app\android\app\src\main\java\com```
there is ejectapp folder that contains

- MainActivity.java

- MainApplication.java 

- generated\BasePackageList.java

![image](https://user-images.githubusercontent.com/10193354/93823203-bc55fa80-fc61-11ea-9f5f-fc53c5a9ebab.png)

and popland (which contains the empty folder eject_app)
![image](https://user-images.githubusercontent.com/10193354/93823284-d98ac900-fc61-11ea-9a97-c406ca5827c2.png)

if i inspect the above java file the package name is wrong (but coherent to the path where the files are created) and the import reference is wrong too (line 14)
![image](https://user-images.githubusercontent.com/10193354/93823473-2bcbea00-fc62-11ea-8b08-215e3e004161.png)

now, when i run 
```yarn android```
the app fail to compile with the following error (repeated more times)

```
C:\Users\lorenzo\eject_app\android\app\src\main\java\com\ejectapp\MainApplication.java:39: error: cannot find symbol
      return BuildConfig.DEBUG;
             ^
  symbol: variable BuildConfig
```
![image](https://user-images.githubusercontent.com/10193354/93823810-bb719880-fc62-11ea-969f-15ac594319a5.png)

As a workaround, i moved the java files in the correct path, fixed the package name and reference and that make the app compile

## Environment
 Expo CLI 3.27.6 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    npmPackages:
      expo: ~38.0.8 => 38.0.10
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: ~0.62.2 => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    Expo Workflow: bare

## Reproducible Demo
The following git contains the project created with the above procedure
https://github.com/popeating/eject_app

**Comment by brentvatne** [comment]
thanks for the information! i was unable to reproduce this macos, so it seems that this is a windows specific bug.

**Comment by popeating** [comment]
> thanks for the information! i was unable to reproduce this macos, so it seems that this is a windows specific bug.

yes, in macos it works as expected
on windows it looks like it switch the name of iOS bundle identifier and package name in some ways; in fact in my example i used two differente namespaces, but it looks that files are created in the iOS bundle name path, even if it is partial when creating the path on disk (hope this make sense)
