### ISSUE TITLE
Silence "Using node to generate images" during eject

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#2676]
From https://github.com/expo/expo-cli/issues/2675

<img width="821" alt="Screen Shot 2020-09-21 at 3 04 47 PM" src="https://user-images.githubusercontent.com/90494/93826313-cd7c1880-fc1b-11ea-9eca-3c775cb25a07.png">

We should just generate the images without the warning.

**Comment by EvanBacon** [comment]
please add a proposal for how users will learn about installing sharp CLI globally

**Comment by brentvatne** [comment]
good point - if users run this command to sync config then it would be useful for them to know.

i think we should add that to some validation that we do before running the command.

**Comment by DJFriar** [comment]
I am getting this error even though I have sharp-cli installed globally...

**Comment by OwenMelbz** [comment]
> I am getting this error even though I have sharp-cli installed globally...

Same, this frustrates me every build seeing it error despite it being installed e.g.

```
➜ which sharp
/Users/owen/.nvm/versions/node/v16.13.1/bin/sharp
```

**Comment by la55u** [comment]
having the same issue, sharp is not being detected even though it's installed:
```
## output of which sharp:
~/.nvm/versions/node/v18.12.1/bin/sharp
```

**Comment by bryanltobing** [comment]
same here. sharp-cli already installed globally via npm

```bash
which sharp
/opt/homebrew/bin/sharp
```

**Comment by redareda9** [comment]
Same here 
❯ which sharp
/Users/reda/Library/pnpm/sharp

**Comment by arvl130** [comment]
Seems to be an issue with the sharp-cli detection code in `sharp.ts` https://github.com/expo/expo-cli/blob/main/packages/image-utils/src/sharp.ts Though, it's still unclear what exactly causes it to happen.
