### ISSUE TITLE
Handle unauthorized devices when listing Android devices with adb

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#2677]
https://github.com/expo/expo-cli/blob/6ad25c3dde3242bfdc2b0d8e846c7bb5fec14136/packages/xdl/src/Android.ts#L237

It's possible for the adb output to look like this:

```
List of devices attached
984e71340418728d       unauthorized transport_id:2
emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
```

This can happen when you connect a device but don't accept the prompt to allow USB debugging. More context in https://forums.expo.io/t/couldnt-start-project-on-android-cannot-read-property-replace-of-undefined/42484/15?u=notbrent

**Comment by EvanBacon** [comment]
To unauthorize the device:

1. On device:
    - Open settings app
    - Press "Revoke USB debugging authorizations" in "Developer Options"
2. Reconnect the device to the computer
