### ISSUE TITLE
Unable to resolve "./environment/mutewarnings.fx" from "node_modules\expo\build\Expo.Fx.expo.js after updating Expo CLI

### ISSUE THREAD

**Issue by Jeganath** [expo/expo-cli#2682]
Today i updated Expo CLI on my windows 10 PC , after that i am not able to publish on Android or web simulator. before that it was working fine. 

It Shows the below error.

Building JavaScript bundle: error

Unable to resolve "./environment/mutewarnings.fx" from "node_modules\expo\build\Expo.Fx.expo.js

If i can't solve this issue , how to degrade the Expo CLI

**Comment by EvanBacon** [comment]
`npm i -g expo-cli@x.x.x` to install an earlier version of the CLI.

**Comment by openmindcom** [comment]
I have the same problem, only on android, on iOS it works perfectly, I also run npm i -g expo-cli@x.x.x but it doesn't work.

**Comment by mcoelho40** [comment]
I had the same problem. 
**expo r -c** to clear the cache and the problem should be solved.

**Comment by openmindcom** [comment]
> I had the same problem.
> **expo r -c** to clear the cache and the problem should be solved.

work for me, thank you!

**Comment by AhmadMazaal** [comment]
> I had the same problem.
> **expo r -c** to clear the cache and the problem should be solved.

Thanks, you saved my life!

**Comment by lakshmanprabhu219** [comment]
> I had the same problem.
> **expo r -c** to clear the cache and the problem should be solved.

Thanks man!!!!!

**Comment by pravinkumar777** [comment]
i had same problem 
expo r -c  to clear the cache and the problem should be solved

**Comment by pravinkumar777** [comment]
thanks bro

**Comment by swanand6300** [comment]
> I had the same problem.
> **expo r -c** to clear the cache and the problem should be solved.

Work for me. Thanks

**Comment by hakoemmy** [comment]
Just had the same issue and you saved my life
