### ISSUE TITLE
Ejecting in Windows 10 could mess some paths for Macos

### ISSUE THREAD

**Issue by popeating** [expo/expo-cli#2683]
## Description

Working in a mixed environment (windows + mac + linux) could lead to potential issue whene ejecting
even if i try to keep everything the same on all machine when i ejected a project on windows (and there are installed some libraries, like the firebase one) in ios file project.pbxproj paths retains windows notation
![image](https://user-images.githubusercontent.com/10193354/93887826-793e6a80-fce7-11ea-909b-51d68829df5c.png)
 

## Expected Behavior

Even if i understand that ejecting and sharing a project could lead (initially) to confusion and could be hard to make a platform agnostic eject, especially when path involved, a warning with a list to things to check when moving to another platform could be useful

## Observed Behavior

i noticed this because my  pod install failed, it took me a lot to debug and discover the c:\ and the wrong slash in path

## Environment

Windows 10 / Mac OS
firebase libraries (@react-native-firebase/app)

**Comment by brentvatne** [comment]
isn't this the same issue as https://github.com/expo/expo-cli/issues/2675?
