### ISSUE TITLE
In China , expo eject so slow or connect time out

### ISSUE THREAD

**Issue by hnlinzhi19** [expo/expo-cli#269]
# In China , expo eject so slow or connect time out

In China , you know our great wall protection，when i run expo cli ,it make a long long time; In the same I also use VPN ,but sometimes happen in my computer time out or too slow. Can you give some way to run expo do not need connect to Network,  like unzip a zip file in my computer;

**Comment by hnlinzhi19** [comment]
modify title

**Comment by ide** [comment]
Not sure we can fix this if there's essentially an issue with your internet connectivity. Expo CLI installs packages from npm and connects to Google Cloud, which are pretty standard services.

**Comment by hnlinzhi19** [comment]
Hi @ide  ,I know connects questions ,you can not resolve it ; But this is cannot build apk or ipa like react native ? If your team cannot give a best way for user like me, I think a lot of Chinese do not want use this best tool.
