### ISSUE TITLE
EXPO CLI reporting incorrect version

### ISSUE THREAD

**Issue by pelicanenglw** [expo/expo-cli#2701]
## Description

Expo CLi reporting odd version numbers

## Expected Behavior

Report the installed version

## Observed Behavior

┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                          │
│   There is a new version of expo-cli available (3.27.8).                                                                                 │
│   You are currently using expo-cli 3.9.1                                                                                                 │
│   Install expo-cli globally using the package manager of your choice; for example: `npm install -g expo-cli` to get the latest version   │
│                                                                                                                                          │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

expo-cli --version reports 3.27.8, but I am getting the login in cert issue for ios, so it would appear that this is in fact 3.9.1

## Environment

  Expo CLI 3.9.1 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 6.21.00 - /bin/tcsh
    Binaries:
      Node: 14.12.0 - ~/.nvm/versions/node/v14.12.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.12.0/bin/npm
    IDEs:
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 3.27.8

**Comment by pelicanenglw** [comment]
which expo-cli - yields
/Users/lwhite/.nvm/versions/node/v14.12.0/bin/expo-cli

**Comment by brentvatne** [comment]
do you have `expo-cli` installed in your package.json in your project? it's possible that if you do and you're running `npm start` to start it then it's using that version of it rather than your global install.

there is no way that this would produce the wrong version: https://github.com/expo/expo-cli/blob/2d7da199b586a33417df90ea2d45a36e69d594cd/packages/expo-cli/src/exp.ts#L702-L714

the version is read directly from the package.json in expo-cli.

**Comment by pelicanenglw** [comment]
package.json expo list - 

 "expo": "^39.0.0",
    "expo-application": "~2.3.0",
    "expo-asset": "~8.2.0",
    "expo-constants": "~9.2.0",
    "expo-device": "~2.3.0",
    "expo-font": "~8.3.0",
    "expo-intent-launcher": "~8.3.0",
    "expo-linking": "^1.0.3",
    "expo-permissions": "~9.3.0",
    "expo-web-browser": "~8.5.0",

**Comment by pelicanenglw** [comment]
expo-cli --version reports 3.27.8

**Comment by pelicanenglw** [comment]
which expo-cli - yields
/Users/lwhite/.nvm/versions/node/v14.12.0/bin/expo-cli

**Comment by brentvatne** [comment]
there is some other installation of expo-cli on your machine with version 3.9.1. i can't say where it comes from because everyone's system setup is different. maybe you have another version of node installed outside of nvm and it was installed there. try removing nvm from your path and opening a new shell and see what node version you have.

**Comment by pelicanenglw** [comment]
yep and I finally found it.  The part that got me (and still does) is the diagnostic report

Expo CLI 3.9.1 environment info:
System:
OS: macOS 10.15.6
Shell: 6.21.00 - /bin/tcsh
Binaries:
Node: 14.12.0 - ~/.nvm/versions/node/v14.12.0/bin/node
Yarn: 1.13.0 - /usr/local/bin/yarn
npm: 6.14.8 - ~/.nvm/versions/node/v14.12.0/bin/npm
IDEs:
Xcode: 11.5/11E608c - /usr/bin/xcodebuild
npmPackages:
expo: ^39.0.0 => 39.0.3
react: 16.13.1 => 16.13.1
react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2
npmGlobalPackages:
expo-cli: 3.27.8

my thought would be to either allow a flag to use the global version or make a note in the report that the global version is not being used or better yet not the path of the cli that is being used.

**Comment by pelicanenglw** [comment]
note (not not) ;-)

**Comment by brentvatne** [comment]
interesting! so this was in your project node_modules then?

**Comment by pelicanenglw** [comment]
nope  - /usr/local/lib/node_modules/expo-cli

my thinking is a slight adjustment to the diagnostic report would send people down the right path.

**Comment by brentvatne** [comment]
i'm still kind of confused how this happened. when you ran `expo diagnostics` you saw the above diagnostics report but if you ran `expo --version` you were told `3.27.8`?

**Comment by pelicanenglw** [comment]
Yes, exactly.  Hence the bug report.  I knew I was running an older version because I was seeing the iOS App Store cert issue, but this was at odds with the reported version.  I am now running 3.27.8 and all is working fine, but there is something really odd going on with the reported version at least in this specific case.

**Comment by pelicanenglw** [comment]
The other related problem is that which expo-cli was also incorrect.

**Comment by Symyon** [comment]
Had exact same issues. And found out that `expo -V` and `expo-cli -V` gave different version. Turned out the 'expo-cli' version was coming from npm and 'expo' version was coming from yarn global. Removed both, installed with npm, all good now.
