### ISSUE TITLE
Add a way to prevent publishing to the wrong account

### ISSUE THREAD

**Issue by slorber** [expo/expo-cli#271]
Hi,

I'm a freelancer and work with many different clients, building one Expo app for each of them. 
Each client obviously have a distinct account.

There is no way to store Expo credentials locally, per project ([canny](https://expo.canny.io/feature-requests/p/per-project-expo-account))

This leads me to very often publish app of client1 to client2 account, because it's very easy to forget checking the current Expo account I'm logged in with

In the meantime, could it be possible to have a feature which make the publish fail with an error, instead of publishing to the wrong account?

This feature could be quite similar to the [publishConfig](https://docs.npmjs.com/misc/registry#i-dont-want-my-package-published-in-the-official-registry-its-private) of node, which permits to prevent publishing to public repo internal company packages by mistake

I'm thinking of having "publishAccount": "myClientName" in app.json, and if the current logged in user is not myClientName, the publish would fail with an error saying the wrong account was used or something.

If you agree with that feature I can submit a PR

**Comment by ide** [comment]
@tcdavis would the "owner" field for professional accounts handle this? It seems like it would since it would more strongly associated projects with users.

**Comment by tcdavis** [comment]
Sorry for the very delayed response, but yes the "owner" field should address this for you.
https://docs.expo.io/workflow/configuration/#owner
It works more or less as you describe, but would fail saying you do not have permission to publish to client2's account.
