### ISSUE TITLE
ENOENT: no such file or directory, scandir  when ejecting

### ISSUE THREAD

**Issue by rusagent** [expo/expo-cli#2711]
## Description

When using expo eject i always get this error: NOENT: no such file or directory, scandir 

## Expected Behavior

expo eject

## Observed Behavior

```
⚠️  iOS config synced with warnings that should be fixed:
- splash: Unable to automatically configure splash screen. Please refer to the expo-splash-screen README for more information: https://github.com/expo/expo/tree/master/packages/expo-splash-screen
ENOENT: no such file or directory, scandir 'G:\repos\NewBelled\beLLed\android\app\src\main\java\G:\repos\NewBelled\beLLed\android\app\src\main\java\com\belled'
Error: ENOENT: no such file or directory, scandir 'G:\repos\NewBelled\beLLed\android\app\src\main\java\G:\repos\NewBelled\beLLed\android\app\src\main\java\com\belled'
    at Object.readdirSync (fs.js:955:3)
    at Object.renamePackageOnDisk (C:\Users\flori\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\config\src\android\Package.ts:78:24)
    at configureAndroidProjectAsync (C:\Users\flori\AppData\Roaming\npm\node_modules\expo-cli\src\commands\apply\configureAndroidProjectAsync.ts:119:31)
    at configureAndroidStepAsync (C:\Users\flori\AppData\Roaming\npm\node_modules\expo-cli\src\commands\eject\Eject.ts:218:3)
    at Object.ejectAsync (C:\Users\flori\AppData\Roaming\npm\node_modules\expo-cli\src\commands\eject\Eject.ts:82:3)
    at action (C:\Users\flori\AppData\Roaming\npm\node_modules\expo-cli\src\commands\eject.ts:48:5)
    at Command.<anonymous> (C:\Users\flori\AppData\Roaming\npm\node_modules\expo-cli\src\exp.ts:302:7)
```

## Environment

  Expo CLI 3.27.10 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.18.3 - G:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.6 - G:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2
        System Images: android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    npmPackages:
      expo: ^39.0.3 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.2 => 0.63.2
      react-native-web: ^0.13.14 => 0.13.14
    Expo Workflow: bare

## Reproducible Demo

This is my package.json
{
  "scripts": {
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "lint": "yarn eslint --ext '.js,.ts,.tsx' src/* --quiet --fix"
  },
  "dependencies": {
    "expo": "^39.0.3",
    "expo-splash-screen": "~0.6.0",
    "expo-status-bar": "~1.0.2",
    "expo-updates": "~0.3.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "~0.63.2",
    "react-native-gesture-handler": "^1.7.0",
    "react-native-reanimated": "^1.13.1",
    "react-native-screens": "^2.10.1",
    "react-native-unimodules": "~0.11.0",
    "react-native-web": "^0.13.14",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/drawer": "^5.9.1",
    "@react-navigation/material-bottom-tabs": "^5.2.17",
    "@react-navigation/native": "^5.7.4",
    "@react-navigation/stack": "^5.9.1",
    "color": "^3.1.2",
    "react-native-appearance": "^0.3.4",
    "react-native-elements": "^2.3.2",
    "react-native-paper": "^4.2.0",
    "react-native-restart": "^0.0.17",
    "react-native-safe-area-context": "^3.1.4",
    "react-native-tab-view": "^2.15.1",
    "react-native-vector-icons": "^7.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@callstack/eslint-config": "^9.1.0",
    "@types/color": "^3.0.1",
    "@types/react": "~16.9.35",
    "@types/react-native": "~0.63.2",
    "@typescript-eslint/eslint-plugin": "^2.25.0",
    "@typescript-eslint/parser": "^2.25.0",
    "babel-jest": "~25.2.6",
    "babel-preset-expo": "^8.3.0",
    "eslint": "^6.8.0",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.21.1",
    "jest": "~25.2.6",
    "prettier": "2.1.2",
    "react-test-renderer": "~16.13.1",
    "typescript": "~3.9.2"
  },
  "private": true
}

**Comment by brentvatne** [comment]
related to https://github.com/expo/expo-cli/issues/2683

i think ejecting on windows is not working properly at the moment, apologies

**Comment by rusagent** [comment]
Any solution for this?

**Comment by brentvatne** [comment]
you can use linux or macos to eject or rollback to an older version of expo-cli until we resolve this

**Comment by KaniuBillows** [comment]
I have the same problem

**Comment by rusagent** [comment]
linux helps - just use a vm or wsl. pull your repository - eject - commit - push - and pull on windows. fixes it.

**Comment by akshay2739** [comment]
I am having the same issue

**Comment by Anis-Ghliss** [comment]
same probem here

**Comment by rusagent** [comment]
> linux helps - just use a vm or wsl. pull your repository - eject - commit - push - and pull on windows. fixes it.

this helps. now use it!

**Comment by luklew** [comment]
@brentvatne Do you know ETA when it'll be fixed?

**Comment by Brunohvc** [comment]
same problem :/

**Comment by brentvatne** [comment]
we don't have time to work on it this week but we'd love to have some contributions to help out for windows! if someone could set up an integration test to run eject on windows to make sure we don't regress here again and then fix the issue it'd very appreciated. this is just a node command line app and shouldn't be too difficult if you have experience with node. https://github.com/expo/expo-cli/blob/master/CONTRIBUTING.md

**Comment by rusagent** [comment]
I can look into this tonight. How would i write an integration test for this? Never did node programming before...
