### ISSUE TITLE
CLI passing args issue: `expo start --clear project-dir` doesn't work

### ISSUE THREAD

**Issue by whitecolor** [expo/expo-cli#2717]
Help says: `Usage: expo [options] [command]`

Expo cli version 3.27.10

I expect `expo start --clear project-dir` to work. But it doesn't just print outs help, as if it wan not correct command.

And it is even clear how to pass the parms with `project-dir` included, should be done this way: `expo start project-dir --clear`?

**Comment by brentvatne** [comment]
good catch - `expo [options] [command]` looks backwards

`expo start project-dir --clear` will work

**Comment by whitecolor** [comment]
A like issue https://github.com/expo/expo-cli/issues/2500

**Comment by EvanBacon** [comment]
The help prompt is fixed in this PR https://github.com/expo/expo-cli/pull/2721

**Comment by EvanBacon** [comment]
Confirmed this is fixed on master
