### ISSUE TITLE
EPERM: operation not permitted, rename packager-info.json

### ISSUE THREAD

**Issue by wclr** [expo/expo-cli#2718]
Expo cli version 3.27.10

When starting the project I eventually (sometimes) get the error:
```
EPERM: operation not permitted, rename '...\.expo\packager-info.json.2845281363' -> '...\expo-m\.expo\packager-info.json'
```

![image](https://user-images.githubusercontent.com/736697/94371218-6c1de300-010e-11eb-854b-08ee3244b5d0.png)

Next run it starts ok.

**Comment by brentvatne** [comment]
run `expo-cli` as administrator to avoid these issues

**Comment by whitecolor** [comment]
This is a floating error as I said, it happens rarely, just for your notice that your method of writing this file may cause this issue on windows.
