### ISSUE TITLE
Uncaught Error [Error: EPERM: operation not permitted, open 'C:\Users\user\.expo\PATH']

### ISSUE THREAD

**Issue by MatiSera** [expo/expo-cli#2725]
When I'm trying to run the project or create a new one I have this error:

`C:\Users\userName\projects\mobile>expo start
Uncaught Error [Error: EPERM: operation not permitted, open 'C:\Users\userName\.expo\PATH'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'open',
  path: 'C:\\Users\\userName\\.expo\\PATH'
}`

I already uninstall and install different node versions and edit the  prefix in .npmrc file

**Comment by brentvatne** [comment]
sounds like a permissions error on your machine. your user needs to be able to create a `.expo` directory at the root of your user for storing global settings

**Comment by MatiSera** [comment]
The problem was that the PATH file on .expo directory was hidden. Now I can run the project without problems

**Comment by wll265** [comment]
also came across this issue. it was because the .expo folder had a read only and hidden attributes

**Comment by Eduardo-Coyto** [comment]
> El problema era que el archivo PATH en el directorio .expo estaba oculto. Ahora puedo ejecutar el proyecto sin problemas.

Tuve este problema por semanas y por suerte, y gracias a ti, lo pude solucionar. Muchas gracias Mati!
