### ISSUE TITLE
Expo Bare Project (ejected) do not load assets - iOS

### ISSUE THREAD

**Issue by todor-droxic** [expo/expo-cli#2732]
Expo diagnostics:

`
  Expo CLI 3.27.4 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.11.0 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.9 
      react: ~16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: ~0.62.2 => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
      react-navigation: ^3.11.1 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.27.4
    Expo Workflow: bare`

## Description

None of the asssets are loaded in the app.

## Expected Behavior

I expect all of the assets to be loaded

It is happen after run from Xcode 12 in any device which I build (physical device or simulator)

Will be glad to fix this issue because we are already on AppStore submission phase.

Thanks!

**Comment by EvanBacon** [comment]
"Assets" is pretty vague, I can eject an app and have an image asset load in it. Please provide more info or a repro.

**Comment by todor-droxic** [comment]
@EvanBacon  just run the app from Xcode (simulator or device)
and none of my images are loaded except the `splash.png` from that directory:

<img width="354" alt="Screenshot 2020-10-01 at 11 57 35" src="https://user-images.githubusercontent.com/71084192/94789284-64e02900-03dd-11eb-8d8f-eab27d910aef.png">

**Comment by todor-droxic** [comment]
@EvanBacon one more thing:
When I hit from the terminal `expo start` -> `i` for iOS - and the app is build from the "expo app" - everything is fine with the assets.
But when I run if from Xcode and the app is build without "expo app" - the assets are not loaded

**Comment by EvanBacon** [comment]
How are the assets "not loaded"

**Comment by todor-droxic** [comment]
@EvanBacon are you joking ? 
That means the assets are not showing on the screen - what do you suppose to be ?
The first example here is after hit "expo start" from the terminal - you can see they are shown. (FIRE logo)
The second example is after run from Xcode - you can see they are not showing (FIRE logo)
It happens with all of the images from the app on every screen.

<img width="761" alt="Screenshot 2020-10-01 at 14 53 15" src="https://user-images.githubusercontent.com/71084192/94806187-3c185d80-03f6-11eb-9009-e71eee4e19e8.png">

**Comment by EvanBacon** [comment]
I'm not joking. Here's how I attempted to reproduce your issue:

- `expo init`
- `expo eject`
- Add an image to the project: `foo.png`
- Change the `App.tsx`:
```
import React from "react";
import { StyleSheet, Text, Image, View } from "react-native";

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.tsx to start working on your app!</Text>
      <Image
        source={require("./foo.png")}
        style={{ width: 30, height: 30 }}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
```
- Run the app: `npx react-native run-ios`:

<img width="584" alt="Screen Shot 2020-10-01 at 3 02 23 PM" src="https://user-images.githubusercontent.com/9664363/94812510-20618700-03f7-11eb-8c19-ed50574bd0f8.png">

I cannot reproduce the issue as you've described it. Either you've poorly explained the issue, or this isn't an issue with Expo CLI.

**Comment by EvanBacon** [comment]
I can only guess that this is a problem with React Native 63. https://github.com/facebook/react-native/issues/29369

**Comment by todor-droxic** [comment]
@EvanBacon  thank you, I think this is regression bug. 

On the Expo 39 Blog post there is an issue described crearly:

> Standalone apps for iOS will not read assets correctly in exported projects (with expo export) (issue).

But it is strange, because I am with iOS 14 and Expo 38.0.10 and tried to upgrade to Expo 39 with 

`npm install --global expo-cli` but it still install the same version 38.

I will wait that fixes to be announced and would try again :)

**Comment by brentvatne** [comment]
@todor-droxic - are you using `expo export`? if not then this isn't an issue

**Comment by brentvatne** [comment]
@todor-droxic - in that case the issue you are encountering is totally unrelated. as @EvanBacon pointed out this is working as expected so perhaps what you need to do is initialize a blank bare project and compare the configuration with yours. if you determine that you have found a bug rather than an issue with your app configuration and can provide a [mcve](https://stackoverflow.com/help/mcve) please feel free to create a new issue on https://github.com/expo/expo/issues :)
