### ISSUE TITLE
Unable to run on iPhone simulator with error xcrun exited with non-zero code: 4

### ISSUE THREAD

**Issue by vivek-mhajn** [expo/expo-cli#2735]
##  Description
Unable to run the app on the XCode simulator while running `sudo yarn ios` command.

## Expected Behavior
The app should had started working in the opened up iPhone simulator.

## Observed Behavior
This is my first time running the app in the XCode Simulator. It is observed that it has an unusual error as it weren't in the Android Simulator.

```
The error logs up as:

> yarn run v1.17.3
warning ../../package.json: No license field
$ expo start --ios
Starting project at /Users/BBE0017/Apps/spree-react-native
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Starting Metro Bundler.
xcrun exited with non-zero code: 4
Error: xcrun exited with non-zero code: 4
    at ChildProcess.completionListener (/Users/BBE0017/Apps/spree-react-native/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
    ...
    at spawnAsync (/Users/BBE0017/Apps/spree-react-native/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at xcrunAsync (/@expo/xdl@58.0.11/src/SimControl.ts:323:18)
    at Object.bootAsync (/@expo/xdl@58.0.11/src/SimControl.ts:137:11)
    at action (/@expo/xdl@58.0.11/src/Simulator.ts:310:25)
    at waitForActionAsync (/@expo/xdl@58.0.11/src/Simulator.ts:292:22)
    at ensureSimulatorOpenAsync (/@expo/xdl@58.0.11/src/Simulator.ts:207:24)
    at Object.openProjectAsync (/@expo/xdl@58.0.11/src/Simulator.ts:641:14)
    at /Users/BBE0017/Apps/spree-react-native/node_modules/expo-cli/src/urlOpts.ts:91:11
    at async Promise.all (index 1)
    at Object.handleMobileOptsAsync (/Users/BBE0017/Apps/spree-react-native/node_modules/expo-cli/src/urlOpts.ts:76:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Environment

```
  Expo CLI 3.26.2 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.14.6 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.0/12A8189h - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.10 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.26.2
```
Note: I've installed the latest expo-cli that is ```3.27.12``` it still shows up ```3.26.2```.

What can I try next ?

**Comment by EvanBacon** [comment]
> What can I try next ?

Running without sudo (which will fix the problem). https://github.com/expo/expo-cli/issues/1823

**Comment by vivek-mhajn** [comment]
Every time I run the app without sudo the following error logs up:
```
yarn run v1.17.3
warning ../../package.json: No license field
$ expo start --ios
Uncaught Error [Error: EACCES: permission denied, open '/Users/BBE0017/.expo/state.json.66791048'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/Users/BBE0017/.expo/state.json.66791048'
}
error Command failed with exit code 1.
```

What can I try next ?

**Comment by brentvatne** [comment]
try starting the simulator beforehand. usually when xcrun fails it is because something is wrong with the simulator process on your machine. you can try also try reseting the state of your simulator entirely by opening it and choosing this from the toolbar

![Screen Shot 2020-10-04 at 9 46 12 PM](https://user-images.githubusercontent.com/90494/95041252-06d86d80-068b-11eb-8876-df6e47d1a9a2.png)

**Comment by vivek-mhajn** [comment]
Hi @brentvatne , I've implemented the suggested steps and same error logs up.

**Comment by tasdemirbahadir** [comment]
@EvanBacon fixed my issue when used sudo:
`sudo expo start`

**Comment by rahadkc** [comment]
Thanks @brentvatne for pointing out the issue. I was facing the same problem then check simulator list with "shift+i" found it was using a older version of iPhone simulator so I changed it to latest version and error is gone. I didn't have to do anything else.

**Comment by fletc3her** [comment]
Simply using Shift-i to select a current iPhone model worked for me as well.

**Comment by KananIslamzada** [comment]
For example: if you set url type like  "myApp" in Xcode.
then try `npx uri-scheme open myApp:// --ios` , instead of `npx uri-scheme open myApp --ios.`
I think, problem is in writing this -->  `://` . It worked for me.

**Comment by MendyLanda** [comment]
In my case the issue was not ever opening Xcode before running expo. 
After opening it and going through the initial setup, the error was gone. 
I think it's an extreme edge case but just in case I'm adding it here.

**Comment by felipeduarte27** [comment]
Erase all content and services as mentioned above worked for me.
