### ISSUE TITLE
Enable Branding with multiple package names on the fly

### ISSUE THREAD

**Issue by MD1990** [expo/expo-cli#2737]
Hi there, 

I am having an expo app built-in version 32 and upgraded to the latest version i.e. expo 38. Now this app was ejected when it was on version 33. while ejecting and while upgrading the app there were multiple instances when we need to paste our package name. 

Currently, we are having a requirement to use the same project with different-different package names and to have different builds with unique package names. 

while ejecting I want to know which is the internal command which asks for package name and set it all around. 

I will be using this expo command in my build pipeline to enable branding.

**Comment by EvanBacon** [comment]
Not entirely sure what you want but you can change the package name dynamically like so:
```js
// app.config.js

export default {
  expo: {
    android: {
      package: process.env.MY_ANDROID_PACKAGE
    }
  }
}
```

Then run/rerun
```sh
$ MY_ANDROID_PACKAGE=com.somn.myapp expo eject
```

**Comment by MD1990** [comment]
Hi EvanBacon, 

Thanks for your response but this is what I already know and when I follow this process only a few changes get automated. But we have to make manual changes in build.Gradle, manifest, service files, etc. 

I got help from this article: https://medium.com/@devesu/how-to-change-bundle-identifier-of-ios-app-and-package-name-of-android-app-within-react-native-app-4fbdd6679aa2 where we have a process for IOs but we have to manually change in android files 

I specifically wanted to have the command that runs at the time of eject which asks us for package names, this command is the best fit for my solution can you please look for it

Thanks

**Comment by MD1990** [comment]
Hey @EvanBacon I still need your help why did you close this issue 

Can you please open it and provide me some help 

Thanks in advance

**Comment by brentvatne** [comment]
there is no command for that specific functionality of eject. you could run `expo eject --no-install` to apply the configuration from app.json again on an already ejected project if you want, but ymmv.

**Comment by MD1990** [comment]
Thanks @brentvatne, I will try this solution and will get back to you
