### ISSUE TITLE
npm start/expo start not working after expo update(31.0.6)

### ISSUE THREAD

**Issue by orsospatrick** [expo/expo-cli#274]
# Required format for issues

npm start/expo start not working after expo update(31.0.6)

## Description

I tryed to run a react-native application with expo and when i put expo start or npm start i have a problem.

![untitled](https://user-images.githubusercontent.com/39964878/50387060-9aca8680-06fc-11e9-8697-9cd56ec73e40.png)

![screenshot_1](https://user-images.githubusercontent.com/39964878/50387069-de24f500-06fc-11e9-881a-ead3f47524bf.png)

## Observed Behavior

When I put on cmd:"npm start",it show me:

npm ERR! code ELIFECYCLE 
npm ERR! 
errno 1 npm ERR!
 @ start: expo
start npm ERR!
 Exit status 1 npm ERR! 
npm ERR! Failed at the @ start script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in: npm ERR!
C:\Users\Orsos Patrick\AppData\Roaming\npm-cache_logs\2018-12-23T19_24_36_810Z-debug.log

When I put on cmd:"expo start",it show me:

Error: spawn cmd ENOENT at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19) at onErrorNT (internal/child_process.js:407:16) at process._tickCallback (internal/process/next_tick.js:63:19)

## Environment

Expo CLI 2.6.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-181.5540.7.32.5056338

Also specify:

-Huawei P Smart,Android 8.0

**Comment by seebi98** [comment]
@orsospatrick  how did you solve the problem?
 i'have same problem after updating not working!

**Comment by orsospatrick** [comment]
Hello, i need to change the enviroment variables to work. 

Trimis din Yahoo Mail pe Android 
 
  Pe joi, feb. 28, 2019 la 21:44, seebi98<notifications@github.com> a scris:   
@orsospatrick how did you solve the problem?
i'have same problem after updating not working!

**Comment by Sanaullahbugti** [comment]
@orsospatrick have you solved this problem if yes then let me know I am getting the same error
