### ISSUE TITLE
Packager is not running on.. ip:80

### ISSUE THREAD

**Issue by wclr** [expo/expo-cli#2745]
expo cli version 3.27.12

Well this issue happens all over the way of dev experience and makes things very unpleasant. There where reports about alike issue in expo repo.

https://github.com/expo/expo/issues/1381
https://github.com/expo/expo/issues/7366

But the issue seems not to have been resolved and addressed properly.

Usually, it happens after: 
- Exit running app on an android emulator.
- Restarting packager (R in the console).

![image](https://user-images.githubusercontent.com/736697/94853850-70673a80-0445-11eb-9ba1-926034da6146.png)

![image](https://user-images.githubusercontent.com/736697/94853884-79f0a280-0445-11eb-9431-d63147d125e7.png)

Why it even try to load at port 80?? This port is not reserved for EXPO dev services at all.

After I press `R` in the console, app starts loading, but then fails to load on 19003!

![image](https://user-images.githubusercontent.com/736697/94853962-9ab8f800-0445-11eb-9630-18217de63bf6.png)

This is a floating bug. It happens occasionally. "Fixed" by either restarting packager (R in the console) or exiting and restarting expo (expo start).

A like (probably the same) issue happens during publishing.

![image](https://user-images.githubusercontent.com/736697/94864229-1bcbbb80-0455-11eb-971e-eb093de6c1fd.png)

This is really annoying that those bugs are floating. It happens, and the next run it doesn't. And there are quite many issues of that kind in expo dev experience.

**Comment by AdamJNavarro** [comment]
Hey @whitecolor,

Sorry you're encountering this issue. Our aim is to make the developer experience as smooth as possible and it never feels good to know when we fall short of that. Can you let me know OS you are running on your computer? As well, to clarify, does this primarily (or only) after using Android emulator?

Cheers,
Adam

**Comment by whitecolor** [comment]
Window 10.
> As well, to clarify, does this primarily (or only) after using Android emulator

I use mostly android emulator. It happens during its use.

**Comment by Alain00** [comment]
I'm having the same issue on Ubuntu 18.04 with a pyshical android device
