### ISSUE TITLE
cannot install expo-cli global

### ISSUE THREAD

**Issue by zanisis** [expo/expo-cli#275]
## Description

cannot install global expo-cli when using node v10.14.x

## Expected Behavior

command expo can install on node v10.14.x

## Observed Behavior

actualy i downgrade my node on v10.13.0 there can run command expo

If there's an error message, please paste the _full terminal output and error message_ in this code block:

```
Error text goes here!
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

Also specify:

- mac os sierra node v10.14.2 (latest)

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by sketchthat** [comment]
+1 

## Environment
macOS High Sierra 10.13.6


## Reproducible Demo
```
$node -v
v9.10.0
$ npm -v
6.4.1
$ npm i expo-cli -g
$ expo init my-new-project
zsh: command not found: expo

**Comment by fson** [comment]
Sounds like the issue got fixed.

A summary: To fix the error `command not found: expo` when you already have installed `expo-cli` with `npm install -g expo-cli`, you need to add the path where npm adds global executables to your `PATH` environment variable. You can find the path with this command:
```
npm bin -g
```
If you used Yarn to install `expo-cli`, the command to print the path is:
```
yarn global bin
```
Then add it to your `PATH` environment variable. It can be set using the "Edit System Variable" option of the control panel on Windows, or in your shell's startup file (e.g. `.bashrc`) on Linux and macOS.
