### ISSUE TITLE
Error when ejecting: the “path” argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#2753]
I haven't been able to reproduce this but it's being reported in the forums: https://forums.expo.io/t/expo-eject-is-failing-the-path-argument-must-be-of-type-string-received-undefined/43273

If someone can please share a project that reproduces or reliable reproduction steps, this it should be very helpful.

Trace from forums thread:

```
The “path” argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The “path” argument must be of type string. Received undefined
** at validateString (internal/validators.js:120:11)**
** at Object.resolve (path.js:980:7)**
** at new pbxProject (/Users/eslalaguse/.npm-global/lib/node_modules/expo-cli/node_modules/xcode/lib/pbxProject.js:35:26)**
** at Object.pbxProject [as project] (/Users/eslalaguse/.npm-global/lib/node_modules/expo-cli/node_modules/xcode/lib/pbxProject.js:33:16)**
** at Object.getPbxproj (/Users/eslalaguse/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/config/src/ios/utils/Xcodeproj.ts:164:25)**
** at Object.setDeviceFamily (/Users/eslalaguse/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/config/src/ios/DeviceFamily.ts:52:19)**
** at configureIOSProjectAsync (/Users/eslalaguse/.npm-global/lib/node_modules/expo-cli/src/commands/apply/configureIOSProjectAsync.ts:17:26)**
** at configureIOSStepAsync (/Users/eslalaguse/.npm-global/lib/node_modules/expo-cli/src/commands/eject/Eject.ts:166:3)**
** at Object.ejectAsync (/Users/eslalaguse/.npm-global/lib/node_modules/expo-cli/src/commands/eject/Eject.ts:81:3)**
** at action (/Users/eslalaguse/.npm-global/lib/node_modules/expo-cli/src/commands/eject.ts:48:5)**
** at Command. (/Users/eslalaguse/.npm-global/lib/node_modules/expo-cli/src/exp.ts:302:7)**
```

This seems to be related to `deviceFamily` configuration on iOS.

**Comment by svm1** [comment]
So I managed to get `expo eject` to work by changing the boolean value of the `supportsTablet` key in `app.json` to a string, as such:

```
"ios": {
      "supportsTablet": "true",
      "bundleIdentifier": "com.chat.bot"
    }
```
Was able to successfully eject and generate the iOS and Android project files. However, when I try to actually launch the iOS app from Xcode, I am hit with a brand new issue, errors about `expo-update` exactly as described in the Git issue linked below.

https://github.com/expo/expo/issues/10331

**Comment by brentvatne** [comment]
@svm1 - can you share your project?

**Comment by EvanBacon** [comment]
Can confirm `ios.supportsTablet = false` or `undefined` causes this.

**Comment by svm1** [comment]
My bad @brentvatne, missed your comment. 

Can't share my actual project but happy to create and share a minimal example if that would still be necessary. Though I see a fix has been issued and merged now?

**Comment by brentvatne** [comment]
@svm1 - yup! @EvanBacon found the problem and we will deploy a fix for it sometime later today

**Comment by svm1** [comment]
Sounds good. Thank you! :)
