### ISSUE TITLE
New build fails - no builds in progress

### ISSUE THREAD

**Issue by pelicanenglw** [expo/expo-cli#2762]
## Description

Build fails with no build in progress, error message is incorrect.

## Expected Behavior

Build should proceed or there should be a build to clear in the queue.

## Observed Behavior

Checking if there is a build in progress...

Cannot start a new build, as there is already an in-progress build.
```

## Environment

  Expo CLI 3.27.10 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 6.21.00 - /bin/tcsh
    Binaries:
      Node: 14.12.0 - ~/.nvm/versions/node/v14.12.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.12.0/bin/npm
    Managers:
      CocoaPods: 1.5.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    IDEs:
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.3 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.14 
    npmGlobalPackages:
      expo-cli: 3.27.10
    Expo Workflow: managed

**Comment by byCedric** [comment]
Hi @pelicanenglw, could you also provide the app or user affected? Without this, I'm not sure how I can help 😅

**Comment by pelicanenglw** [comment]
pelicaneng is the account

**Comment by brentvatne** [comment]
you appear to have a build queued, you can cancel it and start it again: https://expo.io/accounts/pelicaneng/builds/406a8f81-4fc2-408c-b6a4-ad1d4d9989be (note that this url is only available to you, any teammates you might have, and admins).
