### ISSUE TITLE
Using expo upgrade reverts the react native version from "sdk-39.0.3.tar.gz" to "sdk-39.0.0.tar.gz"

### ISSUE THREAD

**Issue by divonelnc** [expo/expo-cli#2768]
## Description

There were some issues with SDK 39 at launch and the recommended behavior is to upgrade to sdk 39.0.3 (taken from here: https://github.com/expo/expo/issues/10464#issuecomment-703178030)

However, when calling `expo upgrade`, the react-native version is set to `sdk-39.0.0.tar.gz`. If you had already manually set it to 39.0.3, it will force revert it back to the lower version.

## Expected Behavior

`expo upgrade` should give you the recommended react-native package, instead of the ones with issues.

## Environment
```
  Expo CLI 3.27.14 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 10.15.3 - E:\nodejs\node.EXE
      Yarn: 1.22.0 - E:\Yarn\bin\yarn.CMD
      npm: 6.14.5 - E:\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 29
        Build Tools: 29.0.0, 29.0.3
        System Images: android-29 | Google APIs Intel x86 Atom
    npmPackages:
      expo: ^39.0.0 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.16
    Expo Workflow: managed
```

## Reproducible Demo

Call `expo upgrade` in your project and check the version of react-native in the package.json.

**Comment by brentvatne** [comment]
thanks. `"expoReactNativeTag"` needed to be updated for sdk-39 on https://expo.io/--/api/v2/versions - this is resolved now
