### ISSUE TITLE
Expo-cli can not be installed on Ubuntu

### ISSUE THREAD

**Issue by surajsahani** [expo/expo-cli#2770]
## Observed Behavior

```
Error text goes here!
```

**Comment by brentvatne** [comment]
yes it can. if you are having issues then we will need more information. most likely, something is wrong with your node setup.

**Comment by surajsahani** [comment]
@brentvatne Can you please help
i run the command `sudo npm i -g expo-cli` in my ubuntu setup version 
but getting error in return 
```
npm ERR! Unexpected end of JSON input while parsing near '...//registry.npmjs.org/'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-07T19_43_14_847Z-debug.log
```
I tried to clear the cache of npm but it is still not installing.

**Comment by brentvatne** [comment]
https://stackoverflow.com/questions/47675478/npm-install-errorunexpected-end-of-json-input-while-parsing-near-nt-webpack

**Comment by surajsahani** [comment]
Thank you @brentvatne 
It works i run command
rm -rf ~/.npm
rm -rf ~/.npm-backup
sudo npm cache clean --force
sudo npm cache verify
sudo npm i npm@latest -g
sudo npm i -g expo-cli
![Screenshot from 2020-10-08 01-46-09](https://user-images.githubusercontent.com/22853459/95383017-1fa18700-0908-11eb-9dac-c2271a46eb33.png)
