### ISSUE TITLE
Ejecting from with-reanimated2 Template missing Reanimated AppDelegate changes

### ISSUE THREAD

**Issue by ksitko** [expo/expo-cli#2776]
## Description

[The expo docs for reanimated](https://docs.expo.io/versions/latest/sdk/reanimated/) point to a nifty preconfigured reanimated2 template. Ejecting from it doesn't give you a working app in ios as the ejected AppDelegate is missing the reanimated2 declarations. 

Being able to quickly create a bare expo app that with Reanimated V2 would be useful.

## Expected Behavior

Ejecting would provide the same AppDelegate as the managed app's, so when you run you would have a working ejected app with Reanimated V2. Though at the very least a note in the docs to allow users to know they must manually set up Reanimated V2 when ejecting would be nice. 

## Observed Behavior

```
[Sat Oct 10 2020 14:41:09.313]  ERROR    Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.
[Sat Oct 10 2020 14:41:09.314]  LOG      Running "main" with {"rootTag":1,"initialProps":{}}
[Sat Oct 10 2020 14:41:09.315]  ERROR    Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
```

## Environment

```
  Expo CLI 3.27.14 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.2 => 39.0.3 
    Expo Workflow: bare
```
## Reproducible Demo

```
npx crna --template with-reanimated2
expo eject
yarn ios
```

**Comment by brentvatne** [comment]
hi there!

thanks for the heads up. support for reanimated v2 is still very experimental, as suggested by the `experiments` flag required to enable it. fwiw, the appdelegate when you eject is very much *not* the same as a managed app, although it is intended to produce the same results (in this case, that is clearly not happening).

what we need to do here is add a warning that links to the reanimated setup instructions when ejecting using reanimated v2. when the library stable and has a cleaner setup process we can handle it automatically, but i think at this point we don't want to be making changes to source files with regexes when people eject.

**Comment by ksitko** [comment]
Hey Brent, I understand that reanimated v2 is still very experimental, but the results are so exciting that it's hard not to jump in! The only reason why I even encountered this is I was trying to debug a completely different reanimated v2 issue I am experiencing and I was hoping to quickly create a bare expo app + reanimated v2 to isolate it.

Following the documentation in `https://docs.swmansion.com/react-native-reanimated/docs/installation` gets you there to a working solution once you add the reanimated declarations and imports into your appdelegate along with renaming the extension to .mm. I may make a quick patch for myself in the meanwhile if I need to do it again, though I think there's more work for me in the renaming process if I want to rename it outside of Xcode. 

Regardless, it would be nice to have some sort of warning!

**Comment by brentvatne** [comment]
agreed! we'll add a warning.

**Comment by EvanBacon** [comment]
App delegate changes won't be needed in SDK 44 (next week) https://github.com/software-mansion/react-native-reanimated/pull/2595
