### ISSUE TITLE
Does expo works on Catalina ( mac os)

### ISSUE THREAD

**Issue by jpca999** [expo/expo-cli#2777]
My system keeps on freezing up the moment run  yarn start --ios 

Expo CLI 3.27.14 environment info:
System:
OS: macOS 10.15.6
Shell: 5.7.1 - /bin/zsh
Binaries:
Node: 10.15.3 - /usr/local/bin/node
Yarn: 1.3.2 - /usr/local/bin/yarn
npm: 6.14.6 - /usr/local/bin/npm
Watchman: 4.7.0 - /usr/local/bin/watchman
SDKs:
iOS SDK:
Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
IDEs:
Xcode: 10.3/10G8 - /usr/bin/xcodebuild
npmPackages:
expo: ~39.0.2 => 39.0.3
react: 16.13.1 => 16.13.1
react-dom: 16.13.1 => 16.13.1
react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
react-native-web: ~0.13.12 => 0.13.18
npmGlobalPackages:
expo-cli: 3.27.14
Expo Workflow: managed

**Comment by AdamJNavarro** [comment]
Hey @jpca999, it looks like your Xcode is in need of an update. SDK39 includes iOS 14 support which means you'll need to update to Xcode 12.x to make sure that the simulators are iOS 14 compatible.

**Comment by EvanBacon** [comment]
Expo does support catalina, I'm using it right now and cannot repro. Maybe try freeing up more space on your computer. Native development can be pretty taxing.
