### ISSUE TITLE
Unable to load database file

### ISSUE THREAD

**Issue by TAHERx** [expo/expo-cli#279]
Hi,

I try to load .db file using `Asset` and `require()` to my project
I create the project by `$ expo init`

but it can not resolve the .db file

and I am sure that my code is correct because when I try the code in snack it work
but i do not know why it not work in my project

my code same as this https://snack.expo.io/SyeEiOvzX
but with my database

the error from this line in the code
``` Asset.fromModule(require('./assets/db/noWordDataBase.db')).uri;```

the error
```Unable to resolve "./assets/db/noWordDataBase.db" from "App.js"```

![0](https://user-images.githubusercontent.com/35800914/50530784-17e96780-0b12-11e9-9f00-450e8853345f.png)

app.json
```
{
  "expo": {
    "name": "SQLite",
    "slug": "SQLite",
    "privacy": "public",
    "sdkVersion": "31.0.0",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "packagerOpts": {
      "assetExts": ["db"]
    }
  }
}
```

**Comment by derKuba** [comment]
+1

**Comment by derKuba** [comment]
I was able to bypass this incorrect behaviour by changing the file ending. i renamed the .db - file to mp4 (or jpg, png, one of the working ending ). instead of loading a .db file, i load the .mp4 and then rename it to .db.

`import Expo, {FileSystem, Asset} from 'expo'
 FileSystem.downloadAsync(
      Asset.fromModule(require('../../assets/db/myDatabaseFile.mp4')).uri,
      `${FileSystem.documentDirectory}SQLite/myDatabaseFile.db`
    );
`
and yes, it's a hack. :-)

**Comment by esamelson** [comment]
Hi @TAHERx @derKuba - could one of you provide a GitHub repo that fully reproduces this issue? There are lots of variables at play here and it's hard to tell exactly what the issue is without being able to exactly replicate it. Thanks!

**Comment by derKuba** [comment]
hi @esamelson,
i provided a github repo to show the problem: https://github.com/derKuba/reactNativeDBProblem .
have a look on the App.js, lines 4+5

**Comment by esamelson** [comment]
Thanks for the repro. It looks like this is probably an upstream issue with [metro](https://github.com/facebook/metro). We might be able to fix this but I can't promise anything on any given timeline, sorry 😞 I'd suggest going with the workaround you found for now.

**Comment by TAHERx** [comment]
Hi,

I also provided repo that may help you
https://github.com/TAHERx/sqlite

and thanks

**Comment by aazwar** [comment]
Create file `metro.config.js`

```
module.exports = {
  resolver: {
    assetExts: ["db", "ttf", "png", "jpg"]
  }
}
```

**Comment by TAHERx** [comment]
aazwar
IT WORKS!! THANKS!!
Where are you all this time! 😊

**Comment by codymullins** [comment]
Having the same issue, thought I was an idiot since I'm new to RN/Expo. The hack seems to "fix" it for now.

**Comment by fson** [comment]
@codymullins that is a good question, since it concerns the Expo SDK (this issue tracker is for Expo CLI related issues) could you open an issue about it on https://github.com/expo/expo/issues or a feature request at https://expo.canny.io? Thanks!

**Comment by fson** [comment]
Update to this issue: in newer versions `sourceExts` and `assetExts` specified in `expo.packagerOpts` of `app.json` should work, but as of Expo SDK 35, these settings can **not** be specified in `metro.config.js`.

**Comment by Gustl22** [comment]
I use Expo SDK 37.0.1 and it only works in `metro.config.js` and not in `app.json` so I'm a little bit confused of your comment @fson.

**Comment by amm-elkheir** [comment]
For me none of the above mentioned solutions worked...
Then I tried the `fromModule` function on `Asset` and it worked just fine. It can be used like this:

`const asset = Asset.fromModule(require("./path/to/asset.anyExt"));`
you can also use `Asset.loadAsync`  if you want to download the asset.
