### ISSUE TITLE
[Solved] Build Error while upgrading from SDK 37 to 39 (Unexpected token)

### ISSUE THREAD

**Issue by BrodaNoel** [expo/expo-cli#2790]
## Description
"Build error" while upgrading from SDK 37 to 39, and here I report the fix.

## Expected Behavior
Build success

## Observed Behavior
There was an `Unexpected token` (pointing to a spread operator `...`) in some file of `node_modules/react-native`.
Can't remember right now. After 5 hours of debugging, I don't want to see it anymore.

# What did I do to reproduce it?
(And I did it 100 times)

```
- expo upgrade
- yarn start
- Then read the QR code and open the app from iOS real device
- The build start but stop with an error on ~90%
```

# Fix
Just add `@babel/core` on `devDependencies`

```
  "devDependencies": {
    "@babel/core": "~7.9.0"
  },
```

## Environment

```
 Expo CLI 3.27.14 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v12.19.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 29
        Build Tools: 23.0.1, 23.0.3, 25.0.3, 26.0.1, 27.0.3, 28.0.3
        System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 11.7/11E801a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
    npmGlobalPackages:
      expo-cli: 3.27.14
    Expo Workflow: managed
```

## Reproducible Demo
Kind of hard. Probably something really related to my project. I saw in some comments here and there that it may be fixed after upgrading to the last version of `jest`, but I totally removed jest from my project. That's may be why it is missing this dependency.

## How I found the fix
I created a new brand project and I saw that:

1. `react-native-scripts` was not there, so I removed it
1. `"@babel/core": "~7.9.0",` was there, and it was not added on my pckage.json

**Comment by EvanBacon** [comment]
We don't add `react-native-scripts` to any projects from SDK 37+, `expo upgrade` is not capable of determining how to remove packages like this.
