### ISSUE TITLE
yarn global add expo-cli fails on "conventional-changelog"

### ISSUE THREAD

**Issue by AshCoolman** [expo/expo-cli#2792]
When I try to install I get this error:
```
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/conventional-changelog/-/conventional-changelog-1.2.0.tgz: Request failed \"404 Not Found\"".
```

https://registry.yarnpkg.com/conventional-changelog/-/conventional-changelog-1.1.0.tgz exists

https://registry.yarnpkg.com/conventional-changelog/-/conventional-changelog-1.2.0.tgz does not

**Comment by brentvatne** [comment]
we don't use this anywhere within expo, maybe you have some other global yarn package that is pulling this in?

https://github.com/expo/expo-cli/search?q=conventional-changelog

not in any lockfiles or anything.
