### ISSUE TITLE
Error when launching the app

### ISSUE THREAD

**Issue by judicaelandria** [expo/expo-cli#2794]
## Reproducible Demo
It a new app that I created, didn't touch the code

**Comment by brentvatne** [comment]
hi! we can't help with this information. it sounds like you might have an issue with the setup on your machine.

**Comment by judicaelandria** [comment]
omg, I'm sorry
I did add some details when creating this issue but i don't why this happen
and no, I don't have an issue with the setup in my machine because I've done many apps with expo before, but that happen after I upgraded the expo cli
I get the error, 
error validating app.json, error: getaddrinfo expo.exit

**Comment by judicaelandria** [comment]
![expo.PNG](https://user-images.githubusercontent.com/46365844/96218725-ffb83600-0f8d-11eb-850f-50a4b5504c30.PNG)

**Comment by brentvatne** [comment]
for some reason your compute ris unable to reach exp.host / expo.io. you might be having dns issues or it could have been an intermittent outage.

https://downforeveryoneorjustme.com/exp.host - exp.host is functional
https://downforeveryoneorjustme.com/expo.io - expo.io is functional
https://status.expo.io/ - our status page

**Comment by judicaelandria** [comment]
@brentvatne do expo need internet access now?
