### ISSUE TITLE
configure-splash-screen is not working on iOS (bare project).

### ISSUE THREAD

**Issue by hehex9** [expo/expo-cli#2801]
## Description

**@expo/configure-splash-screen** (using `npx expo-splash-screen`) does not work on **iOS**.

```
npx expo-splash-screen -b white -i ./android/app/src/main/res/mipmap-hdpi/ic_launcher.png -p ios
```

due to the unuseful error message (`Cannot read property 'undefined' of undefined`), I tried

```diff
// node_modules/@expo/configure-splash-screen/build/index-cli.js

async function runAsync() {
    try {
        await cli_command_1.default().parseAsync(process.argv);
    }
    catch (e) {
-        console.error(`\n${e.message}\n`);
+        console.error(e);
        process.exit(1);
    }
}
```

then rerun the command

```
TypeError: Cannot read property 'undefined' of undefined
    at pbxProject.getPBXVariantGroupByKey (/demo/node_modules/@expo/configure-splash-screen/node_modules/xcode/lib/pbxProject.js:1932:56)
    at pbxProject.addFile (/demo/node_modules/@expo/configure-splash-screen/node_modules/xcode/lib/pbxProject.js:2047:19)
    at Object.addStoryboardFileToProject (/demo/node_modules/@expo/configure-splash-screen/build/xcode/index.js:9:29)
    at updatePbxProject (/demo/node_modules/@expo/configure-splash-screen/build/ios/Storyboard.js:24:17)
    at Object.configureStoryboard [as default] (/demo/node_modules/@expo/configure-splash-screen/build/ios/Storyboard.js:148:11)
    at async Promise.all (index 3)
    at async Object.configureIos [as default] (/demo/node_modules/@expo/configure-splash-screen/build/ios/index.js:16:5)
    at async action (/demo/node_modules/@expo/configure-splash-screen/build/cli-command.js:19:13)
    at async Command.<anonymous> (/demo/node_modules/@expo/configure-splash-screen/build/cli-command.js:102:5)
    at async Promise.all (index 0)
```

[calling pbxProject.addFile with `undefined` group key](https://github.com/expo/expo-cli/blob/master/unlinked-packages/configure-splash-screen/src/xcode/index.ts#L13) might be the cause of this problem, since we don't have any `PBXVariantGroup` in [bare project's project.pbxproj](https://github.com/facebook/react-native/blob/0.63-stable/template/ios/HelloWorld.xcodeproj/project.pbxproj).

## Expected Behavior

no error

## Observed Behavior

output

```
Cannot read property 'undefined' of undefined
```

**and**

- **cleared Info.plist file.**
- created `ios/demo/SplashScreen.storyboard`.
- created `SplashScreen.imageset` and `SplashScreenBackground.imageset` without any image.

## Environment

```
  Expo CLI 3.28.0 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.7 - ~/.nvm/versions/node/v12.16.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /Users/xxx/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 23, 25, 26, 27, 28, 29
        Build Tools: 28.0.3, 29.0.0, 29.0.2
        System Images: android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.13.1 => 16.13.1
      react-native: 0.63.3 => 0.63.3
    Expo Workflow: bare
```

## Reproducible Demo

```
npx react-native init demo

yarn add expo-splash-screen@0.6.2

npx expo-splash-screen -b white -i ./android/app/src/main/res/mipmap-hdpi/ic_launcher.png -p ios
```

**Comment by maharjanaman** [comment]
Any progress or workaround for this?

**Comment by JDMathew** [comment]
Having the same issue here. I think it is failing on updating info.plist

**Comment by brentvatne** [comment]
hi there! prs welcome for this. otherwise @bbarthec will investigate when he has some time

another way to init a project where this will work is to run `expo init` and then choose one of the bare templates

**Comment by SergueyML** [comment]
Sorry for commenting on a closed the issue, but I have a question regarding the fix.
We have a fairly old project that we've recently updated to a recent version of expo and have stumbled upon this issue.
I have updated our expo project to the beta version of SDK40 to see if this will fix it, but to I am still experiencing this issue when running `npx expo-splash-screen -b white -i ./src/assets/splash.png -p ios`. Any idea how I can make this work? I am using a bare workflow

**Comment by bbarthec** [comment]
The fix is published in the [`@expo/configure-splash-screen@0.3.1`](https://www.npmjs.com/package/@expo/configure-splash-screen/v/0.3.1) and this package is published in [`expo-splash-screen@0.8.1`](https://www.npmjs.com/package/expo-splash-screen/v/0.8.1). Ensure that `npx` is picking the correct version of the package or you can always directly call the `npx @expo/configure-splash-screen@0.3.1 <rest of your command>` 😉

**Comment by SergueyML** [comment]
@bbarthec Thanks, that worked! but I've encountered a new issue when using `expo eject`. I get this warning when ejecting 
```
⚠️  iOS config synced with warnings that should be fixed:
- splash: Unable to automatically configure splash screen. Please refer to the expo-splash-screen README for more information: https://github.com/expo/expo/tree/master/packages/expo-splash-screen
⚠️  Android config synced with warnings that should be fixed:
- splash: Unable to automatically configure splash screen. Please refer to the expo-splash-screen README for more information: https://github.com/expo/expo/tree/master/packages/expo-splash-screen
```

I assume that this is because the fixes still need to be implemented to SDK40?

**Comment by bbarthec** [comment]
Yeah, SDK 40 is still not supported 😞 It will be supported soon though 😊

**Comment by SergueyML** [comment]
Ok thanks for the info! 😄
