### ISSUE TITLE
Suggestion: Emit error on `expo eject` when lacking certain app.json props

### ISSUE THREAD

**Issue by paulshapiro** [expo/expo-cli#2806]
## Description

I was stumped for some hours when doing `expo eject` on a blank project - it only silently failed after I hit enter after entering the name of the android project (which it asked me) ... it turns out that the process was stalling/dead-ending because, as `expo eject` instructions indeed state, I hadn't made sure app.json had all the needed `ios` and `android` root key config params needed.

## Expected Behavior

A full expo eject completion OR an error - "? What would you like your Android package name to be? " response should at least yield an error about why it keeps returning to that required input - so rather, an error should be shown here and `expo eject` should exit.

## Observed Behavior

`expo-cli` asked me "? What would you like your Android package name to be? " but upon entering an answer, it only cleared the input and did not continue the process... i.e. a silent failure.

## Environment

MacOS

## Reproducible Demo

`expo eject`

**Comment by brentvatne** [comment]
hi @paulshapiro! I don't think I fully understand the issue you encountered. you entered an android package name and the process was stuck? can you give me more information about your project to help me reproduce it? notice that we explicitly ask for you to run `expo diagnostics` in the issue template because it is helpful for us to debug: `Please run `expo diagnostics` in the project folder and copy the output here`. this seems to be an issue particular to your setup and machine so we need more information to help.

**Comment by paulshapiro** [comment]
Yes, you can just do a `expo init asdfasdf`, cd `asdfasdf`, `expo eject` and experience it.

**Comment by brentvatne** [comment]
@paulshapiro - no i can't. this is happening on your machine and not mine :P

**Comment by paulshapiro** [comment]
Oh.. can't repro that on yours? I'm kinda secretive so reluctant to post my version numbers here.

**Comment by brentvatne** [comment]
<img width="762" alt="Screen Shot 2020-10-17 at 2 27 31 PM" src="https://user-images.githubusercontent.com/90494/96353867-e645e580-1084-11eb-81a9-6675e684a3f3.png">

> I'm kinda secretive so reluctant to post my version numbers here.

we can't help in that case. we need actual information to reproduce or understand the issue in order to help.

**Comment by paulshapiro** [comment]
Ah ok, seems like some versions thing somewhere. Good to know; thanks. :)

**Comment by brentvatne** [comment]
good luck! i don't understand why you wouldn't share the diagnostics info as there is literally zero sensitive information available through that, but to each their own.
