### ISSUE TITLE
expo eject

### ISSUE THREAD

**Issue by mboworldbest** [expo/expo-cli#2807]
expo --version
3.28.0
expo eject
Failed to locate the ios/*.xcodeproj files relative to path
Please report this as an issue on https://github.com/expo/expo-cli/issues
Error: Failed to locate the ios/*.xcodeproj files relative to path
at getAllXcodeProjectPaths 
at getAllPBXProjectPaths
at Object.getPBXProjectPath
at getPbxproj
at modifyPbxprojAsync
at configureIOSProjectAsync

how to fix ios?
Thanks!

**Comment by EvanBacon** [comment]
You'll need to fill out the entire issue template before we can help.

**Comment by dane-brown** [comment]
@mboworldbest I had a similar issue, found out by googling that you should delete the **ios** folder before running expo eject. Hope it helps!

**Comment by pyankoff** [comment]
Also happened when I had non-English name of the app in my app.json.

**Comment by app-arianamini** [comment]
> @mboworldbest I had a similar issue, found out by googling that you should delete the **ios** folder before running expo eject. Hope it helps!

You should also delete Android Folder.
