### ISSUE TITLE
Can't launch android emulator

### ISSUE THREAD

**Issue by franjorub** [expo/expo-cli#2808]
Hi since android studio upgraded to version 4.1 its annoying be able to start the project in the android emulator. I have this message: 

Couldn't adb reverse: adb E  2717 119116 usb_osx.cpp:138] Unable to create an interface plug-in (e00002be)
error: device 'adb' not found

this happens in MacOS and Windows 10. if you keep hitting in the terminal `a` to launch the emulator it will start after many error logs

----

expo-cli 3.28.0

**Comment by EvanBacon** [comment]
Possibly unrelated to expo-cli https://stackoverflow.com/a/36662403 seems something else is blocking expo from starting the emulator
