### ISSUE TITLE
OTA Updates to specific platforms - Bare Workflow

### ISSUE THREAD

**Issue by valentinchelle** [expo/expo-cli#2813]
## Description

I want to be able to send separate OTA updates depending on the platform iOS or Android in the bare workflow. But `expo publish --releaseChannel prod_ios` always overwrites the releaseChannel I specified in Expo.plist and in the Android Manifest to 'prod_ios'.

## Expected Behavior

`expo publish --releaseChannel prod_ios` publishes the current files to the release channel **prod_ios** but doesn't change the values of EXUpdatesReleaseChannel in Expo.plist and expo.modules.updates.EXPO_RELEASE_CHANNEL in AndroidManifest.xml.

## Observed Behavior

As far as I understood, OTA updates will always be pushed to both platforms automatically. It would be perfect if expo publish had an option like `expo publish --release-channel prod_1.0 --platform ios`.

I am currently using the following workflow to get two different channels for Android and iOS, so that I can send separate OTA updates if needed

1) set the release channel for iOS to **prod_1.0_ios** in Expo.plist
2) set the release channel for android to **prod_1.0_android** in the Android Manifest
3) publish builds to both stores
4) work on a hot fix for iOS, and run `expo publish --release-channel prod_1.0_ios` to only update the iOS version
5) work on a hot fix for Android, and run `expo publish --release-channel prod_X.X_android` to only update the iOS version

But I noticed that when I  run `expo publish --release-channel prod_1.0_ios`, expo will automatically change the Android Manifest and the Expo.plist to the prod_1.0_ios release channel. I then would need to change the Android manifest back to prod_1.0_android if I need to publish to the play store again. 

Am I adopting the wrong approach?

**Comment by Juno31** [comment]
@valentinchelle
Sad that this issue closed without any conversations...
Going though same concerns. Any progress you made you can share?
