### ISSUE TITLE
Expo init failing to install react-native-maps and stopping

### ISSUE THREAD

**Issue by P-Holland** [expo/expo-cli#282]
READ THIS FIRST, PLEASE!

We're looking to keep questions on our forums and bug reports on the GitHub repo -- please choose whichever you feel is more appropriate for your issue:

Post in our community forums (log in with your Expo developer account): https://forums.expo.io/c/help File a bug on the Expo CLI repo (for bugs related to the Expo CLI tools): https://github.com/expo/expo-cli/issues/new
File a bug on the main Expo repo (for other bugs): https://github.com/expo/expo/issues/new
Request a feature on Canny: https://expo.canny.io/feature-requests

Thanks for reporting the issue you found with Expo CLI!
Required format for issues

Please make our job easier by filling this template out to completion.
Description

I'm trying to start a new project but expo init is failing to clone react-native-maps

##Expected Behavior

I entered sudo expo init and selected blank template and expected it to start a new project and install 
the correct dependencies

##Observed Behavior

It runs fine until it tries to clone react-native-maps where it is reporting permission denied on the git clone file.

If there's an error message, please paste the full terminal output and error message in this code block:

```
[16:26:30] Extracting project files...
[16:26:31] Customizing project...
[16:26:31] Initialized a git repository.
[16:26:31] Installing dependencies...
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b v0.22.1-exp.0 git://github.com/expo/react-native-maps.git /home/paul/.npm/_cacache/tmp/git-clone-f6bfb854
npm ERR! /home/paul/.npm/_cacache/tmp/git-clone-f6bfb854/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paul/.npm/_logs/2018-12-29T16_26_53_553Z-debug.log
[16:26:53] Process exited with non-zero code: 1
```

Environment

Please run expo diagnostics in the project folder and copy the output here:

Expo CLI 2.6.14 environment info:
System:
OS: Linux 4.4 Ubuntu 16.04.5 LTS (Xenial Xerus)
Shell: 4.3.48 - /bin/bash
Binaries:
Node: 11.6.0 - /usr/bin/node
npm: 6.5.0-next.0 - /usr/bin/npm
npmGlobalPackages:
expo-cli: 2.6.14

Also specify:

Phone/emulator/simulator platform, model and version:

Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

I installed nodejs by following the instructions on the website and then ran sudo npm install -g expo-cli and sudo expo init

**Comment by fson** [comment]
npm requires git for installing some packages and fails if it's not installed. Can you check that git is installed? On Ubuntu you can install it with `apt-get install git`.

**Comment by P-Holland** [comment]
I have git installed, I made sure to update it the first time I got the error.

**Comment by darojuv** [comment]
I am have exact problem

**Comment by joesanchezsu** [comment]
Me too! I have not found any solution

**Comment by dan1983** [comment]
Me too!

**Comment by NikhilSharmay** [comment]
same here :(

**Comment by joesanchezsu** [comment]
I resolved this with yarn, maybe it can be also useful for you guys 
https://github.com/react-community/create-react-native-app/issues/236

**Comment by dan1983** [comment]
it worked!!! thanks joesanchezsu  and  NikhilSharmay

**Comment by kromakollision** [comment]
I had to delete package-lock.json too. Then run `npm install`

**Comment by arjayosma** [comment]
I encountered the same issue.
I just `sudo npm install` in my folder and it's now okay.

**Comment by victorsilvasilva** [comment]
I deleted node_modules and package-lock.json, then ran `npm install` and it worked fine. Thanks

**Comment by mccordgh** [comment]
I'm hitting this issue right now:
```
"expo": "^32.0.0",
"react": "16.5.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz",
```

have tried `rm -rf node_modules` then removing `package-lock.json` and doing `npm install` with no luck. Have tried 3 times...

Still getting the errors:
```
npm WARN tarball tarball data for react-native-maps@github:expo/react-native-maps#v0.22.1-exp.0 (sha1-5wwO9U3U7S8QAD4CAhO56Wkm4bg=) seems to be corrupted. Trying one more time.

...

(here is a looong list of "npm WARN tar ENOENT: no such file or directory, open [file path])

...

npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting react-native-maps@github:expo/react-native-maps#v0.22.1-exp.0:
npm ERR! Verification failed while extracting react-native-maps@github:expo/react-native-maps#v0.22.1-exp.0:
npm ERR! sha1-5wwO9U3U7S8QAD4CAhO56Wkm4bg= integrity checksum failed when using sha1: wanted sha1-5wwO9U3U7S8QAD4CAhO56Wkm4bg= but got sha512-5wpiR6Sfa9PbDBWzSWIhY8DIrcI6VyPU4BmO+/aSpKxdfxsDKixbly8casPCJm+86vYIn23qwJc4K7U8QzO3IA== sha1-WroFxhrS02IHPuj1apbF4IxbTqk=. (245980 bytes)
```

even tried `sudo npm install`

**Comment by mccordgh** [comment]
**FOLLOW UP: fixed**

Must have been some kind of cache / npm thing going on. I was able to successfully install after running
`npm i -g npm`
then
`npm cache clean --force`
