### ISSUE TITLE
Provide link to information about deploying to app stores during first build

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#2820]
It's common for people to miss the documentation at https://docs.expo.io/distribution/app-stores/ and this can lead to some wasted time and energy as they search for solutions to things like how to adjust Android permissions after submitting to the store and seeing the list of permissions used.

We could display some message like this:

> Planning on deploying this build to an app store? We recommend reading the "Deploying to App Stores" guide before proceeding. Learn more. (https://docs.expo.io/distribution/app-stores/)

We probably don't want to block on this, but I'm open to being convinced that a `Continue? (y/n)` prompt is worthwhile here.

**Comment by EvanBacon** [comment]
Closing in favor of `eas submit`
