### ISSUE TITLE
expo-cli should enforce OS-specific configuration, such as permission descriptions in infoPlist for iOS

### ISSUE THREAD

**Issue by CostachescuCristinel** [expo/expo-cli#2822]
## Description

This request comes from a number of rejections from Apple for not including some permission usage descriptions.

At this moment, expo-cli allows building iOS apps without specifying a permissions usage description in the required keys in infoPlist. This causes builds to be rejected by Apple on the grounds of not providing such descriptions.
Moreover, it is not clear which `NS<...>UsageDescription` entries should be filled in order to comply with the request.

## Expected Behavior

First of all, I am not sure why this inconsistency in checking app.json. If you try to include extraneous keys in app.json configuration (or misplace an OS specific configuration key in the root object instead of the OS specific configuration), expo-cli will warn you about that or even refuse to build due to invalid configuration. But if you omit required configuration keys, it simply gets over them? Anyway...

At the very least, expo-cli should warn the user when trying to build an iOS app without including the proper `NS<...>UsageDescription` key in the infoPlist configuration. An `Are you sure you want to continue? (y/N)` dialog would be the better choice, and I would personally prefer the build to stop.

expo-cli should also provide some clear information on which `NS<...>UsageDescription` keys are actually needed. For example, on iOS 10, in order to use the camera, both `CAMERA` and `CAMERA_ROLL` permissions are required. This means that both `NSPhotoLibraryUsageDescription` and `NSCameraUsageDescription` keys are required in infoPlist. On iOS 11+ however, you may omit either of them, depending on which features you're interested into (Camera, Photo library, or both).

Warning about required keys should be based on the (expo supported) packages that are included in the code.
Notable examples:
- Including `expo-image-picker` requires the `CAMERA` permission on Android, even if photos are only ever selected from the gallery (because the default android gallery app can also open the camera). Thus, the `CAMERA` permission should be specified in the android permissions configuration, in app.json.
- Including `expo-document-picker` on iOS, requires the developer to enable iCloud storage in the mobileprovision profile, and to include the `usesIcloudStorage: true` key in the iOS configuration
- Including `expo-local-authentication` requires both the `USE_BIOMETRIC` and `USE_FINGERPRINT` permissions on Android, while on iOS requires the `NSFaceIDUsageDescription` key in infoPlist
- Including `expo-notifications` on Android, requires a `google-services.json` file and a `googleServicesFile` key in the android configuration in app.json.

## Observed Behavior

expo-cli would happily build without letting the developer know about missing permissions or some configuration keys.
While the case in point is more about iOS permission descriptions, it still applies to other areas, and to Android.

Missing any of these configurations will let the app build. But during usage, most of the times, the app will fail silently, or result in unexpected crashes (if any feature rejects a promise, and it's not caught in a `.catch()` or `try{ await ... } catch(){ }` block).

## Environment

```
  Expo CLI 3.28.1 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.2 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.10 => 38.0.10 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    Expo Workflow: managed
```

#### iOS
Start a new expo managed project and include some minimal code to open the camera, but do not include the `NSCameraUsageDescription` or `NSPhotoLibraryUsageDescription` keys in app.json. Then build the app with `expo build:ios`:
The result is that the app builds, but if you try to send it to Apple for review, it will be rejected due to missing descriptions for the required permissions.
#### Android
Start a new managed expo project, include code to enable push notifications, but do not include the `googleServicesFile`key in app.json. Then build the app.
The result is that the app builds, but no push notifications will arrive on Android.

**Comment by CostachescuCristinel** [comment]
Relevant for this request:
https://forums.expo.io/t/app-rejected-due-to-permissions-by-app-store/18406/2

I see threads like this appearing from time to time in different platforms (expo forums, github, stackoverflow, ect.). I may not be the only one who would appreciate if expo checked for these...

**Comment by EvanBacon** [comment]
We now mostly have this with managed EAS Build, the `expo run:*` commands, and config plugins. It's pretty much impossible to create a perfect version of this system but what we have now works pretty well for passing App Store review.
