### ISSUE TITLE
Switch to use expo dev server by default on SDK >= 40

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#2824]
We should add this code now, we don't need to wait for SDK 40.

Invert the default for `EXPO_USE_DEV_SERVER` so for SDK >= 40, we make it true and otherwise it's false. In the future for SDK 41 and later, we should make it so you can't opt out of it, but we don't need to add this logic now.

**Comment by EvanBacon** [comment]
resolved in #2921
