### ISSUE TITLE
Node 15 issues!

### ISSUE THREAD

**Issue by quangnguyen17** [expo/expo-cli#2826]
Hi, 

My RN App is acting up when I updated to Node 15.X.X and NPM 7.X.X. 
When are you guys updating the CLI to support this latest release of Node?

Thanks so much!

**Comment by AdamJNavarro** [comment]
Hey @quangnguyen17 , we only support LTS releases (meaning the even versions of Node --- 12, 14, 16, etc). Odd numbers are experimental versions. As per Node's official page, production apps should only use LTS releases. https://nodejs.org/en/about/releases/

Cheers,
Adam

**Comment by coopbri** [comment]
@quangnguyen17 If you'd like to force `expo-cli` to work with Node 15.X.X, you can pass the `--ignore-engines` flag.

I use yarn, and I did: `yarn global add expo-cli --ignore-engines`
