### ISSUE TITLE
WARNING: expo-cli has not yet been tested against Node.js v15.0.1.

### ISSUE THREAD

**Issue by blackhacker009** [expo/expo-cli#2829]
WARNING: expo-cli has not yet been tested against Node.js v15.0.1.

help me sol WARNING!

**Comment by AdamJNavarro** [comment]
Hey @blackhacker009, we only support LTS releases (meaning the even versions of Node --- 12, 14, 16, etc). Odd numbers are experimental versions. As per Node's official page, production apps should only use LTS releases. https://nodejs.org/en/about/releases/

Cheers,
Adam
