### ISSUE TITLE
adb.exe is left running in the background (`npm install -g expo-cli` fails with "EPERM: operation not permitted, unlink '...\adb.exe')

### ISSUE THREAD

**Issue by coryb08** [expo/expo-cli#283]
## Description

I receive an error when running `npm install -g expo-cli`

## Expected Behavior

For there not to be an error

## Observed Behavior

```
npm ERR! path C:\Users\Cory\AppData\Roaming\npm\node_modules\expo-cli\node_modules\.xdl.DELETE\binaries\windows\adb\adb.exe
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\Cory\AppData\Roaming\npm\node_modules\expo-cli\node_modules\.xdl.DELETE\binaries\windows\adb\adb.exe'
npm ERR!  { [Error: EPERM: operation not permitted, unlink 'C:\Users\Cory\AppData\Roaming\npm\node_modules\expo-cli\node_modules\.xdl.DELETE\binaries\windows\adb\adb.exe']
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'C:\Users\Cory\AppData\Roaming\npm\node_modules\expo-cli\node_modules\.xdl.DELETE\binaries\windows\adb\adb.exe'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path:
npm ERR!       'C:\\Users\\Cory\\AppData\\Roaming\\npm\\node_modules\\expo-cli\\node_modules\\.xdl.DELETE\\binaries\\windows\\adb\\adb.exe' },
npm ERR!   stack:
npm ERR!    'Error: EPERM: operation not permitted, unlink \'C:\\Users\\Cory\\AppData\\Roaming\\npm\\node_modules\\expo-cli\\node_modules\\.xdl.DELETE\\binaries\\windows\\adb\\adb.exe\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path:
npm ERR!    'C:\\Users\\Cory\\AppData\\Roaming\\npm\\node_modules\\expo-cli\\node_modules\\.xdl.DELETE\\binaries\\windows\\adb\\adb.exe',
npm ERR!   parent: 'expo-cli' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Cory\AppData\Roaming\npm-cache\_logs\2018-12-30T20_05_51_538Z-debug.log
```

## Environment

cant run because expo-cli will not install

**Comment by S00161418** [comment]
I am getting the same error. I tried updating node and npm and then running as administrator but the error still appears.

**Comment by coryb08** [comment]
Will try this when I get home, thanks.

**Comment by Silva-Amon** [comment]
> This has caught me out as well. It looks like if you've run `expo` on Windows it leaves its `adb.exe` running in the background, presumably until you reboot. As a result, when you try and update expo-cli, there's processes locking you out. I figured this out through trial and error, so there's a step I'm listing that you probably don't need to do.
> 
> * Open **Task Manager** - right-click on the task bar and select it, or from the screen when you Ctrl-Alt-Delete. If you have the standard Task Manager, click to expand **More details**. (If you're using something like Process Explorer, you're probably comfortable finding your own way.)
> * In the **Background processes** click on **adb.exe (32 bit)** (or, presumably, something similar). Click **End task** or press Delete to kill the process. This should unlock the problematic files.
> * This is probably not necessary - I deleted the folder that contained the files that caused the error in the first place, `.xdl-DELETE`. (I would expect `npm` to do it for me but I was testing my hypothesis 😉.) Remember to close any command prompts or Explorer windows afterwards, because otherwise you'll be locking the `expo-cli` folder. (I'd left an Explorer window open in that folder which is why I mention it 🤦‍♂️.)
> * Run `npm i -g expo-cli` to update. You'll have time to make a cup of tea while it's going, so I suggest doing that.
> 
> That's exactly what I did, and now I'm up to date.

Thank you so much! It worked fine for me.

**Comment by nonoyek** [comment]
ya the solution work perfectly tq!!

**Comment by mekwall** [comment]
The above is merely a workaround. Expo CLI should make sure to kill the running adb process when itself exists.

**Comment by digicoparis** [comment]
> This is a duplicate of #175. The above is merely a workaround. Expo CLI should make sure to kill the running adb process when itself exists.

I agree, it's not super handy to have to kill the process on Windows before updating. It took me a while to find solution here, thanks to @IrregularShed.

Now I know Windows users are not a lot while doing Expo/React :)

**Comment by humandevs** [comment]
In my case, this issue appears to have only shown up when trying to uninstall exp-cli. Installing it (in order to update) seemed to go okay, but the old version was still being used somehow. So, the uninstaller should probably try to kill adb.exe first before attempting to remove the package somehow?
