### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:80 for Android build

### ISSUE THREAD

**Issue by kgorol** [expo/expo-cli#2831]
## Description

Running command `expo build:android` produces ECONNREFUSED error.

I've tried so far deleting `node_modules` and `.expo` directories, tried multiple times running expo with `expo start -c` command, and also performed clean `npm install` for my project. Nothing helps and I am keep receiving these errors.

## Expected Behavior

Successful Android build.

## Observed Behavior

```
expo build:android
✔ Choose the build type you would like: › apk
Checking if there is a build in progress...

Accessing credentials for **** in project ****

- Expo SDK: 39.0.0
- Release channel: default
- Workflow: Managed

Building optimized bundles and generating sourcemaps...
Starting Metro Bundler.
Building iOS bundle
connect ECONNREFUSED 127.0.0.1:80
Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)
```

## Environment

```
Expo CLI 3.28.2 environment info:
    System:
      OS: Linux 5.9 Manjaro Linux
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.12.0 - /usr/bin/node
      npm: 6.14.7 - /usr/bin/npm
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 3.28.2
    Expo Workflow: managed

```

**Comment by AdamJNavarro** [comment]
Hey @kgorol, has anything changed with your network environment? Also, are you able to run the project via `expo start` successfully?

**Comment by larts85** [comment]
hello @kgorol !
Did you resolve that problem?
It's happening the same to me.

**Comment by kgorol** [comment]
@AdamJNavarro `expo start` working like a charm, and no changes were made to my network config

@larts85 I did "solve" the issue... It appears to be absolutely random. Steps I am doing to workaround this:

1. Start application with `expo start`
2. Launch app in any simulator (Android or iOS)
3. Try to launch `expo build:android`
4. At this point on your `localhost:19002` should appear information that expo lost connection to its server, nothing to worry about.
5. Repeat step 3 until build starts.

Step 3 should fail a couple of times, but after some retries it successfully starts build.
