### ISSUE TITLE
[Electron] Invalid hook call (expo-electron adapter with React Native)

### ISSUE THREAD

**Issue by rmtry** [expo/expo-cli#2835]
I am trying to use `expo-electron` adapter to my React Native project to start making app for desktop. The setup worked perfectly, the Navigation transform was also correct, however there are weird behaviors whenever I tried to use Hook syntax from an external library (like `react-redux` useSelector, `react-i18next` useTranslation). It all returned same kind of error: **`Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component.`**

**App.tsx**

```
import React from 'react'
import {NavigationContainer} from '@react-navigation/native'
import RootRoute from '~routes/root-route'
import {ThemeProvider} from 'styled-components/native'
import {useSelector} from 'react-redux'
import {getTheme} from '~selectors/theme-selectors'
import {ThemeEnums} from '~types/theme-reducer.type'
import {LIGHT_THEME, DARK_THEME} from '~styles/index'

const App = () => {
  const chosenTheme = useSelector(getTheme)
  const theme = chosenTheme === ThemeEnums.LIGHT ? LIGHT_THEME : DARK_THEME

  return (
    <ThemeProvider theme={theme}>
      <NavigationContainer>
        <RootRoute />
      </NavigationContainer>
    </ThemeProvider>
  )
}

export default App
```

**Error**: 

> Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
>     at resolveDispatcher (/Users/rmtry/Documents/works/DarkglassAppRN/node_modules/react/cjs/react.development.js:1465)
>     at useContext (/Users/rmtry/Documents/works/DarkglassAppRN/node_modules/react/cjs/react.development.js:1473)
>     at useReduxContext (/Users/rmtry/Documents/works/DarkglassAppRN/node_modules/react-redux/lib/hooks/useReduxContext.js:27)
>     at useSelector (/Users/rmtry/Documents/works/DarkglassAppRN/node_modules/react-redux/lib/hooks/useSelector.js:114)
>     at App (App.tsx?d35d:11)
>     at renderWithHooks (react-dom.development.js?61bb:14803)
>     at mountIndeterminateComponent (react-dom.development.js?61bb:17482)
>     at beginWork (react-dom.development.js?61bb:18596)
>     at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:188)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:237)

**TranslatedText.tsx** (this works on React Native but return the same kind of error on Electron):
```
import React from 'react'
import {useTranslation} from 'react-i18next'
import {Text} from 'react-native'

interface Props {
  children: string
  style?: any
}

const TranslatedText = (props: Props) => {
  const {children, style} = props
  const {t} = useTranslation()

  return <Text style={style}>{t(children)}</Text>
}

export default TranslatedText
```

**TranslatedText.electron.js** (I tried to modify it to Class-based component but same error)
```
import React from 'react'
import { withTranslation } from 'react-i18next'
import {Text } from 'react-native'

console.log('Yo')

class TranslatedText extends React.Component {
  render() {
    console.log(this.props)
    return <Text style={this.props.style}>{ this.props.t ? this.props.t(this.props.children) : this.props.t}</Text>
  }
}

export default withTranslation()(TranslatedText);
```

> The error I got: 
> /Users/rmtry/Documents/works/DarkglassAppRN/node_modules/react/cjs/react.development.js:1465 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
>     at resolveDispatcher (/Users/rmtry/Documents/works/DarkglassAppRN/node_modules/react/cjs/react.development.js:1465)
>     at useContext (/Users/rmtry/Documents/works/DarkglassAppRN/node_modules/react/cjs/react.development.js:1473)
>     at useTranslation (/Users/rmtry/Documents/works/DarkglassAppRN/node_modules/react-i18next/dist/commonjs/useTranslation.js:28)
>     at withI18nextTranslation(TranslatedText) (/Users/rmtry/Documents/works/DarkglassAppRN/node_modules/react-i18next/dist/commonjs/withTranslation.js:33)
>     at renderWithHooks (react-dom.development.js?61bb:14803)
>     at mountIndeterminateComponent (react-dom.development.js?61bb:17482)
>     at beginWork (react-dom.development.js?61bb:18596)
>     at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:188)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:237)
>     at invokeGuardedCallback (react-dom.development.js?61bb:292)

And my React Native log was clear.

I was able to add Electron setup to my RN project through Expo's tutorial for Electron adapter.
Package using:
```
    "@expo/electron-adapter": "^0.0.27",
    "electron": "^10.1.5",
    "i18next": "^19.8.1",
    "react-native": "0.63.3",
    "react": "16.13.1",
    "react-native-web": "^0.14.4",
    "react-redux": "^7.2.1",
    "redux": "^4.0.5",

```
Any helps would be grateful. Thanks!

**Comment by wrsulliv** [comment]
@rmtry Did you find a solution?  I'm having the same issue.  For me, hooks are working on Web and iOS, but not Electron.

**Comment by wrsulliv** [comment]
@rmtry I believe I've found a solution.  Others have discussed similar issues with Electron:

- https://github.com/facebook/react/issues/13991#issuecomment-683109390
- https://github.com/electron-userland/electron-webpack/issues/283#issuecomment-487470932

**Solution**
Add the package you're attempting to use to "whiteListedModules" in "electron-webpack.js".  For example, to use "react-responsive":

*electron-webpack.js*
```
const { withExpoAdapter } = require('@expo/electron-adapter');

module.exports = withExpoAdapter({
  projectRoot: __dirname,
  whiteListedModules: [ "react-responsive" ]
});
```

**Explanation**

If I understand correctly, with `electron-webpack`, (almost) all modules are treated as "externals" by default:  https://webpack.electron.build/configuration#white-listing-externals

An "external" is a module not included in the Webpack bundle.

However, a few modules including "react", "react-dom", and "vue" ARE included in the bundle by default:  https://github.com/electron-userland/electron-webpack/issues/283#issuecomment-487459087

This means when Webpack bundles the application, the app pulls react from the Webpack bundle.  However, the dependencies pull from the non-bundled version in node_modules.

This means at runtime there are two different instances of React.  This matches reason #3 in the react error log.

**Comment by rmtry** [comment]
@wrsulliv Hi! Thanks for your response!
I had decided to postpone the React native with Electron project until next year since there was no solution found. Your answer looks so promising, we will try and update the status later!

**Comment by rmtry** [comment]
We finally changed to use React Electron boilerplate and it works as expected. In addition, it has more configurations for us. I will close the issue. Thank you for your support!
