### ISSUE TITLE
expo-cli question: Unable to open iOS build after choosing simulator option.

### ISSUE THREAD

**Issue by crofoot** [expo/expo-cli#2842]
## Description
I am trying to build my app using the `simulator` option with expo-cli version `3.28.2`. And everything works fine but when I download the zip and try to open it or push up with Transporter it gives me the error message pasted down below.

Thanks for your time! 
 

## Expected Behavior

To be able to push up using Transporter to the App Store Connect.

## Observed Behavior

```
The developer of this app needs to update it to work with this version of macOS. Contact the developer for more information.
```

## Environment

  Expo CLI 3.28.2 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.1.0 - /usr/local/bin/fish
    Binaries:
      Node: 12.16.3 - /usr/local/bin/node
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.10
      react: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
    npmGlobalPackages:
      expo-cli: 3.28.2
    Expo Workflow: managed

## Reproducible Demo

* Initialize a Managed Expo Application
* run `expo build:ios`
* select `simulator` option
* After build runs download zip and try to open application

**Comment by byCedric** [comment]
Hi @crofoot! You can't send a simulator version of your app with Transporter. You need an archive, or version installable through the store, for that. The only thing you can do with a simulator build is to install it on an iPhone simulator, e.g. by drag and drop.

Hope this helps!
