### ISSUE TITLE
"yarn global add expo-cli" don't work

### ISSUE THREAD

**Issue by newtonsandey** [expo/expo-cli#2853]
windows 10 2004
node v12.18.4

When trying to install with yarn (yarn global add expo-cli), I get this:

> yarn global v1.22.5
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> info @expo/traveling-fastlane-darwin@1.15.1: The platform "win32" is incompatible with this module.
> info "@expo/traveling-fastlane-darwin@1.15.1" is an optional dependency and failed compatibility check. Excluding it from installation.
> info @expo/ngrok-bin-darwin-ia32@2.2.8: The platform "win32" is incompatible with this module.
> info "@expo/ngrok-bin-darwin-ia32@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
> info @expo/ngrok-bin-darwin-ia32@2.2.8: The CPU architecture "x64" is incompatible with this module.
> info @expo/ngrok-bin-darwin-x64@2.2.8: The platform "win32" is incompatible with this module.
> info "@expo/ngrok-bin-darwin-x64@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
> info @expo/ngrok-bin-freebsd-ia32@2.2.8: The platform "win32" is incompatible with this module.
> info "@expo/ngrok-bin-freebsd-ia32@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
> info @expo/ngrok-bin-freebsd-ia32@2.2.8: The CPU architecture "x64" is incompatible with this module.
> info @expo/ngrok-bin-freebsd-x64@2.2.8: The platform "win32" is incompatible with this module.
> info "@expo/ngrok-bin-freebsd-x64@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
> info @expo/ngrok-bin-linux-arm@2.2.8: The platform "win32" is incompatible with this module.
> info "@expo/ngrok-bin-linux-arm@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
> info @expo/ngrok-bin-linux-arm@2.2.8: The CPU architecture "x64" is incompatible with this module.
> info @expo/ngrok-bin-linux-arm64@2.2.8: The platform "win32" is incompatible with this module.
> info "@expo/ngrok-bin-linux-arm64@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
> info @expo/ngrok-bin-linux-arm64@2.2.8: The CPU architecture "x64" is incompatible with this module.
> info @expo/ngrok-bin-linux-ia32@2.2.8: The platform "win32" is incompatible with this module.
> info "@expo/ngrok-bin-linux-ia32@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
> info @expo/ngrok-bin-linux-ia32@2.2.8: The CPU architecture "x64" is incompatible with this module.
> info @expo/ngrok-bin-linux-x64@2.2.8: The platform "win32" is incompatible with this module.
> info "@expo/ngrok-bin-linux-x64@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
> info "@expo/ngrok-bin-sunos-x64@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
> info @expo/ngrok-bin-win32-ia32@2.2.8-beta.1: The CPU architecture "x64" is incompatible with this module.
> info "@expo/ngrok-bin-win32-ia32@2.2.8-beta.1" is an optional dependency and failed compatibility check. Excluding it from installation.
> info fsevents@1.2.13: The platform "win32" is incompatible with this module.
> info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
> info fsevents@2.1.3: The platform "win32" is incompatible with this module.
> info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
> [3/4] Linking dependencies...
> warning "expo-cli > @expo/config > @expo/configure-splash-screen@0.2.1" has unmet peer dependency "expo-splash-screen@*".
> warning "expo-cli > @expo/xdl > @expo/dev-server > @expo/metro-config > metro-react-native-babel-transformer@0.58.0" has unmet peer dependency "@babel/core@*".       
> [4/4] Building fresh packages...
> success Installed "expo-cli@3.28.4" with binaries:
>       - expo
>       - expo-cli

Even though the "success Installed..." message, expo and expo-cli don't works.

**Comment by EvanBacon** [comment]
this is just an annoying quirk of NPM

**Comment by newtonsandey** [comment]
> this is just an annoying quirk of NPM. If the cli "doesn't work" please specify how so and feel free to reopen. Also filling out the issue template is required for this repo.

When I say it doesn't work, I mean that I get this error trying to use it:

![image](https://user-images.githubusercontent.com/58047532/98165759-30bcc400-1ec5-11eb-9ddb-fa9039c5fad2.png)

**Comment by brentvatne** [comment]
this is a bug with your installation of yarn. my understanding of portuguese is not the best, but the error you are getting is saying, as far as i know, that it's unable to find the expo executable. this would happen if the yarn global install path is not in your command line PATH.

**Comment by brentvatne** [comment]
https://stackoverflow.com/questions/40317578/yarn-global-command-not-working

**Comment by SleeplessByte** [comment]
Run `yarn global bin`, add the result to your windows environment PATH variabele. Close all terminals and start a new one. Try `expo --help`, it should now work.
