### ISSUE TITLE
Installing expo-cli on catalina with node 12 and npm 6 does not yield an executable in path

### ISSUE THREAD

**Issue by MichaelHindley** [expo/expo-cli#2875]
## Description

Running `npm install --global expo-cli` does not result in expo cli being available on the machine
No other globally installed package shows this behaviour.

## Expected Behavior

`expo` executable to be available in /usr/local/bin, like all other globally installed packages on the same system

## Observed Behavior

expo-cli installed to global packages,
no expo excutable symlinked 

## Output of installing:
+ expo-cli@3.28.5
updated 1 package in 36.748s

## Other global packages
`npm list -g --depth 0`
/usr/local/Cellar/node@12/12.18.3/lib
├── expo-cli@3.28.5 (does not work)
├── npm@6.14.8 (works) /usr/local/bin/npm
├── ts-node-dev@1.0.0 (works) /usr/local/bin/ts-node-dev
└── typescript@4.0.3 (works) /usr/local/bin/tsc

## Environment
zsh (latest)
macos catalina 10.15.7
node v12.18.3
npm 6.14.8

**Comment by brentvatne** [comment]
we don't do anything special, this is just like any other package. your machine is not properly configured to look in the right place.
