### ISSUE TITLE
Eject hanging on installing CocoaPods when sudo is needed

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#2879]
When trying to eject after setting up a fresh macOS machine, I ended up in this state:

> ⠙ CocoaPods CLI not found in your PATH, installing it now.Your password might be needed to install CocoaPods CLI: https://guides.cocoapods.org/using/getting-started.html#installation

![Screen Shot 2020-11-12 at 6 49 09 PM](https://user-images.githubusercontent.com/90494/99022989-82de9480-2518-11eb-9d05-68eca9e13f32.png)

I didn't see any prompt to continue, but tried entering my password anyhow and hitting return and this unblocked it.

![Screen Shot 2020-11-12 at 6 55 14 PM](https://user-images.githubusercontent.com/90494/99023030-9d187280-2518-11eb-82f5-a466b8c5d438.png)

**Comment by brentvatne** [comment]
Also - `sudo gem install cocoapods` no longer works with the Ruby version that ships with macOS, or at least that's my experience here

**Comment by cloggo** [comment]
The installation will continue if you actually enter the password even though there is no prompt that asking you to enter the password.

**Comment by brentvatne** [comment]
@cloggo - yup! i noted that above:

> I didn't see any prompt to continue, but tried entering my password anyhow and hitting return and this unblocked it.

**Comment by ismaelbarry** [comment]
> @cloggo - yup! i noted that above:
> 
> > I didn't see any prompt to continue, but tried entering my password anyhow and hitting return and this unblocked it.

Exactly, which password should be entered here as it doesn't specify?

**Comment by brentvatne** [comment]
@ismaelbarry - your operating system user. the same as if you ran `sudo <some-command>`

**Comment by ismaelbarry** [comment]
> @ismaelbarry - your operating system user. the same as if you ran `sudo <some-command>`

Gotcha! Thanks, I was able to get it to work.

**Comment by ghacosta** [comment]
this happened to me too on macOS Catalina and using latest SDK and expo-cli at the moment. I've solved this too by entering my SO password and hitting return/enter key
