### ISSUE TITLE
Please upgrade @expo/webpack-config's webpack dependency to 5.x

### ISSUE THREAD

**Issue by andymatuschak** [expo/expo-cli#2881]
## Description

`@expo/webpack-config`'s `webpack` dependency is currently 4.43.0, the last major version. The current major version is 5.x, and it'd be great to support that: I'd like to be able to take advantage of some of the changes in recent releases.

## Expected Behavior

`@expo/webpack-config` should depend on `webpack@5` 

## Observed Behavior

`@expo/webpack-config` depends on `webpack@4.43.0`

## Environment

I don't think this is relevant, but here you are!

```
Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v12.18.4/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
    npmPackages:
      react: ~17.0.1 => 17.0.1 
    Expo Workflow: managed
```

**Comment by EvanBacon** [comment]
Looks like it's not ready yet, there's a lot of overlap between CRA and expo/webpack-config, a couple of the plugins don't appear to support Webpack 5 properly yet https://github.com/facebook/create-react-app/pull/7929

**Comment by nandorojo** [comment]
Webpack 5 doesn't seem fully there yet, but Next.js has experimental support for it: https://nextjs.org/docs/messages/webpack5

**Comment by nandorojo** [comment]
I'd like to bring this issue back up. Vercel is putting real resources behind Webpack 5, and Next is releasing many advances for it. It has many performance advantages that would be nice to take advantage of for build time. Maybe it could be published behind a `next` tag?

**Comment by nandorojo** [comment]
Possibly related: https://github.com/expo/expo-cli/issues/3226

**Comment by nandorojo** [comment]
I believe I figured this out. I'll submit a PR once I stress test it more.

As it stands, my solution is to disable Expo's transpiling of modules when `webpack5: true`. In those cases, you'd need to use `next-transpile-modules`. For instance, you'd add `react-native-web` to your `next-transpile-modules` array, along with other `expo-*` packages.

**Comment by marklawlor** [comment]
Building upon @nandorojo's work, I have an experimental "working" version of `@expo/next-adapter` which includes a couple of patches to `@expo/webpack-config` to allow for webpack 5 support. 

This won't work for the pure Expo web applications, but if your using NextJS it should allow you to update to NextJS 10.2 and use Webpack5.

https://github.com/marklawlor/expo-nextjs-webpack-5

**Comment by csvan** [comment]
This has severe implications for users of Node 17 and later, see https://github.com/webpack/webpack/issues/14532
