### ISSUE TITLE
[expo upload:ios] Pinned version of Fastlane 2.146.1 not working on XCode 12

### ISSUE THREAD

**Issue by oliw** [expo/expo-cli#2882]
## Description

`expo upload:ios` is failing to upload my artifact to Testflight. My suspicion is that expo-cli's pinned version of Fastlane is too old (2.146.1 was released in april, the latest Fastlane version is 2.166).
 
https://github.com/fastlane/fastlane/pull/16689

## Expected Behavior

`expo upload:ios` could upload my app to Testflight

## Observed Behavior

The command `expo upload:ios` fails with the following output

```
[22:43:53]: Login successful
[22:43:56]: Ready to upload new build to TestFlight (App: 1529817354)...
[22:43:58]: Going to upload updated app to App Store Connect
[22:43:58]: This might take a few minutes. Please don't interrupt the script.
[22:43:58]: [iTMSTransporter] -Djava.ext.dirs=/Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/itms/java/lib/ext is not supported.  Use -classpath instead.

[22:43:58]: [iTMSTransporter] Error: Could not create the Java Virtual Machine.

[22:43:58]: [iTMSTransporter] Error: A fatal exception has occurred. Program will exit.

[22:43:58]: iTunes Transporter output above ^
[22:43:58]: The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
Failed to upload the standalone app to the App Store.
We recommend using Transporter.app instead of the expo upload:ios command if you have any trouble with it.
Error uploading ipa file, for more information see above
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.146.1/pilot/lib/pilot/build_manager.rb:37:in `upload'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/app/pilot_upload.rb:20:in `block in <main>'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/app/funcs.rb:4:in `with_captured_stderr'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/app/pilot_upload.rb:12:in `<main>'
```

## Environment
```
  Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.6.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.18
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: managed
```

**Comment by brentvatne** [comment]
as the error suggests, we recommend using transporter.app right now instead. it's complicated to ship fastlane within expo-cli and the ruby tool, traveling-ruby, that we were depending on for this is no longer maintained so we are stuck on an old version. we are rewriting this tool as a hosted service, similar to https://github.com/expo/expo-cli/pull/2876 which switches the android upload command to a hosted equivalent, where the upload is performed from our servers in a controlled environment.

that said, macos server time is very expensive, and this may not be a free feature (or it will be limited for free plans). it will live in a new cli tool that is intended to interact with the expo services, we'll share more about that in december. the plan for this command in expo-cli is to only handle registering your bundle id and creating the app through app store connect, then recommending that you use transporter.app, since we don't want to become maintainers of portable ruby binaries.

**Comment by oliw** [comment]
All good, thanks for the advice Brent. Makes sense.

I'm doing this app development from a hobbyist perspective and this was the first app I've worked on outside of the XCode closed garden so Transporter is new for me. Seems to have worked. 

https://developer.apple.com/news/?id=10152019a

**Comment by oliw** [comment]
Not urgent/important but has the team considered making Fastlane an optional dependency that people installing expo-cli have to install themselves via homebrew? Or does that solve one problem but create five more.

![image](https://user-images.githubusercontent.com/1246970/99113391-06919300-25a4-11eb-9bd1-d31eb07d82dc.png)

**Comment by brentvatne** [comment]
@oliw - we considered that, but it has some limitations compared to the hosted approach. in addition to requiring installation of a separate toolchain, it will still only work on macos, whereas the hosted solution will work from any operating system. your idea could be a good idea for something to exist in userspace though! you can see how we get the recent build url in the expo-cli source and copy that over to a package that wraps fastlane and wires it together.
