### ISSUE TITLE
Support the --config option for expo upgrade

### ISSUE THREAD

**Issue by hpjaj** [expo/expo-cli#2884]
## Description

I am trying to upgrade from Expo SDK 37 to 38.  I am getting this error message when running `expo upgrade 38`

```
➜ expo upgrade 38

Updating your app.json to account for breaking changes (if applicable)
Project at path ....../mobile does not contain a valid Expo config
```

Our Expo app is somewhat uniq in that we have two apps within it, and they each have their own `app.json` file, neither of which are at the root of the directory.  Their respective paths are:

- `apps/goals/app.json`
- `apps/perks/app.json`

Based on some research, I tried running the following command and received the below error:

```
➜ expo upgrade 38 --config apps/goals/app.json

error: unknown option `--config'
```

## Expected Behavior

I see that other `expo-cli` commands offer the `--config` option.  For example:

```
expo start --config apps/goals/app.json
expo build:ios --config apps/goals/app.json
expo build:android --config apps/goals/app.json
```

As such, in order to be able to upgrade the SDK, our hope/expectation would for the `--config` option to be accessible in the `expo upgrade` command.

If not, then some other way to tell Expo to find the config files at these locations so that I can upgrade the SDK

Thanks!

## Observed Behavior

```
➜ expo upgrade 38 --config apps/goals/app.json

error: unknown option `--config'
```

## Environment

```
➜  expo diagnostics

  Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.3
      react: 16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: managed
```

**Comment by brentvatne** [comment]
i would suggest copying one of the app.json files to the root temporarily, and then running upgrade. we won't change the app.json file so it doesn't really matter which one you use

**Comment by hpjaj** [comment]
@brentvatne - that worked...thanks!

**Comment by EvanBacon** [comment]
Closing as we're dropping support for `--config` property in favor of `app.config.js` in the root of a project. https://github.com/expo/expo-cli/pull/3382
