### ISSUE TITLE
pod install: Unable to find a specification for `EXTaskManagerInterface`

### ISSUE THREAD

**Issue by OldhamMade** [expo/expo-cli#289]
## Description

Unable to `exp detach` and successfully `pod install` using the latest SDK32.

## Expected Behavior

`pod install` should complete successfully.

## Steps to reproduce

Note: it may not be needed to run all the following steps, but this is how I reproduced with a bare example.

1. `expo init Example`
2. `cd Example && npm install`
3. `npm start`, then run the iOS simulator and confirm the example message is displayed.
4. `exp detach`
5. `cd ios && pod install`

## Observed Behavior

```
$ cd ios && pod install
...
Fetching podspec for `EXSegment` from `../node_modules/expo-analytics-segment/ios`
Fetching podspec for `EXSensors` from `../node_modules/expo-sensors/ios`
Fetching podspec for `EXSensorsInterface` from `../node_modules/expo-sensors-interface/ios`
Pre-downloading: `ExpoKit` from `http://github.com/expo/expo.git`, tag `ios/2.10.0`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `yoga` from `../node_modules/react-native/ReactCommon/yoga`
[!] Unable to find a specification for `EXTaskManagerInterface` depended upon by `EXLocation`
```

## Environment

```
$ expo diagnostics

  Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 5.6.2 - /usr/local/bin/zsh
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.6.14

$ cat package.json
...
  "dependencies": {
    "expo": "^32.0.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz"
  },
...
```

- Phone/emulator/simulator platform, model and version: any

**Comment by esamelson** [comment]
Hi @OldhamMade - could you make sure you're running `expo eject` instead of `exp detach`? The `exp` CLI tool is out of date and no longer maintained. `expo eject` is (almost) a drop-in replace for the `detach` command, you'll just need to pick `ExpoKit` when presented with a set of options.

**Comment by brentvatne** [comment]
install the latest version of expo-cli

**Comment by rreorr** [comment]
I'm running into the same error upgrading an older app ExpoKit from 25 to 32. I've successfully resolved most of the issues except for this one. I updated expo cli in case that was the issue. 

``` Expo CLI 2.6.14 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.10.0 - ~/.nvm/versions/node/v10.10.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v10.10.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.6.14
```

**Comment by Zynio** [comment]
add: 
pod 'EXTaskManagerInterface',
    :path => "../node_modules/expo-task-manager-interface/ios"

in ios\Podfile

**Comment by arzynik** [comment]
adding 
```
  pod 'EXTaskManager',
    :path => "../node_modules/expo-task-manager/ios"
  pod 'EXTaskManagerInterface',
    :path => "../node_modules/expo-task-manager-interface/ios"
  pod 'EXAppLoaderProvider',
    :path => "../node_modules/expo-app-loader-provider/ios"
```

to `io/Podfile` and running `pod install` worked for me

**Comment by chairmin** [comment]
> adding
> 
> ```
>   pod 'EXTaskManager',
>     :path => "../node_modules/expo-task-manager/ios"
>   pod 'EXTaskManagerInterface',
>     :path => "../node_modules/expo-task-manager-interface/ios"
>   pod 'EXAppLoaderProvider',
>     :path => "../node_modules/expo-app-loader-provider/ios"
> ```
> 
> to `io/Podfile` and running `pod install` worked for me

pod install success!

**Comment by EvanBacon** [comment]
I believe the problem has since been fixed. If anyone runs into this bug again, please open a new issue.
