### ISSUE TITLE
Open specific iOS simulator

### ISSUE THREAD

**Issue by epicfaace** [expo/expo-cli#290]
## Description

It would be nice to be able to run expo --ios with a specific simulator, given the simulator name. This would be like the `--simulator` flag in React Native (https://facebook.github.io/react-native/docs/running-on-simulator-ios).

## Expected Behavior

`expo --ios` should give me the option to select which ios simulated device I need.

## Observed Behavior

`expo --ios` just opens up the app in the default iOS simulator, even if I have multiple iOS simulators open.

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:
```
  Expo CLI 2.6.14 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^30.0.1 => 30.0.1
      react: 16.3.1 => 16.3.1
      react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4
      react-navigation: ^2.18.2 => 2.18.2
    npmGlobalPackages:
      expo-cli: 2.6.14
```

**Comment by EvanBacon** [comment]
Perhaps it'd make more sense to open by device ID since the names change often.

**Comment by brentvatne** [comment]
fixed in 3.26.0!

**Comment by MariuzM** [comment]
Hm sorry but what was fixed? how do use? i tried with above suggestions but not working

**Comment by MariuzM** [comment]
@brentvatne able to advise?

**Comment by MariuzM** [comment]
I'm able todo this with build but not Expo Go `expo run:ios --device iPhone 14`

**Comment by brentvatne** [comment]
@MariuzM - we would need more information. this works as expected for me:

```
npx expo run:ios --device "iPhone 13"
› Using --device 6A2D77A0-F8B2-4B24-BC5E-8EA166D9D8B0
```

you could try running `xcrun simctl list` to get the UDID of a device and pass that in instead
