### ISSUE TITLE
Socket hang up on build

### ISSUE THREAD

**Issue by lokewk** [expo/expo-cli#2933]
Ran expo build:android and expo build:ios.
I have this error. Please advise.

![image](https://user-images.githubusercontent.com/68896130/99896896-bb782e00-2ccf-11eb-8301-6e63029cf0cb.png)

P/s: Our network is up but access expo.io on browser is slow and sometime fails.

Expo CLI 3.28.5 environment info:
System:
OS: macOS 10.15.5
Shell: 5.7.1 - /bin/zsh
Binaries:
Node: 12.18.1 - /usr/local/bin/node
npm: 6.14.8 - /usr/local/bin/npm
Managers:
CocoaPods: 1.9.3 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
IDEs:
Android Studio: 4.0 AI-193.6911.18.40.6626763
Xcode: 11.5/11E608c - /usr/bin/xcodebuild
npmPackages:
expo: ^39.0.0 => 39.0.3
react: 16.13.1 => 16.13.1
react-dom: 16.13.1 => 16.13.1
react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
react-native-web: ~0.13.7 => 0.13.18
react-navigation: ^4.4.0 => 4.4.3
npmGlobalPackages:
expo-cli: 3.28.5
Expo Workflow: managed

**Comment by ponikar** [comment]
I had so many expectations with EXPO 39! But I am literally disappointed with EXPO 39! It takes a lot of time to download updates. Every day I have to face a new error!

**Comment by lokewk** [comment]
Hi Expo team,
Can you provide the ip range, ports use to build/publish our apps?
So my network folks can test out if is our network issues.

Cheers.

**Comment by lokewk** [comment]
Update.
I have test on a new blank application still not able to run only any devices (emulator/physical alike).
Not able to build too.
Please advise. Really need to get over this.

**Comment by brentvatne** [comment]
@lokewk - what country are you in? are you able to access aws and gcp?

**Comment by lokewk** [comment]
@brentvatne - i am in Singapore, yes we can access both AWS and GCP.

**Comment by MehmetKaplan** [comment]
Is there a possibility that a momentary network failure could have caused this?
Same experience here but the queued build seems to proceed.

![image](https://user-images.githubusercontent.com/2387157/105032585-0318fd00-5a68-11eb-9dbb-698531ffc2e7.png)


![image](https://user-images.githubusercontent.com/2387157/105034528-a79c3e80-5a6a-11eb-8348-af150e3a92f9.png)

**Comment by samtsai** [comment]
I'm still seeing this issue ever since I've upgraded to Expo SDK 41. I am unable to `expo publish`. When I switched to a branch still on 40 I was able to publish.

```
❯ expo diagnostics
WARNING: expo-cli has not yet been tested against Node.js v16.4.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <13.0.0 (Maintenance LTS)
* >=14.0.0 <15.0.0 (Active LTS)
* >=15.0.0 <17.0.0 (Current Release)


  Expo CLI 4.7.1 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.4.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.18.1 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed
```

**Comment by brentvatne** [comment]
hi there! this appears to be caused by network connectivity issues between you and our servers. if switching to another branch resolved it for you, that likely was just a coincidence.

**Comment by zarcodim** [comment]
I think this and #3603 are dupes.

@brentvatne, is there anything that comes to mind for further debugging the network connectivity issues? Like perhaps a succinct test request? (I'm no expert at this, I've tried `EXPO_DEBUG=true`, `NPM_DEBUG=net`, looking through `tcpdump host exp.host` and Little Snitch. So far I don't have any leads.)

**Comment by brentvatne** [comment]
you can try running `expo doctor` in your project to see if you're able to connect to our servers. that will run this code: https://github.com/expo/expo-cli/blob/8f551d89859a42ce0dfcf357b14988f3c924e5ff/packages/xdl/src/project/Doctor.ts#L456-L464

**Comment by brentvatne** [comment]
also, you could try using `traceroute` with our various hosts to get a better understanding of what is happening with your connection

**Comment by zarcodim** [comment]
Thank you! `brew doctor` (and also validateExpoServersAsync, separately) both said things were fine. It turns out that this is a Symantec firewall thing on my work laptop. From what I gather it must be allowing the TCP handshake and before closing the connection?

Your attention here nonetheless is very much appreciated.

**Comment by sumit31agarwal** [comment]
expo build:android is giving an error of socket hang up 
<img width="529" alt="Screenshot 2021-09-01 at 12 42 42 PM" src="https://user-images.githubusercontent.com/88984245/131628223-f1e5c0e7-8861-4832-b256-7012f933760c.png">


Please help me out

**Comment by lokewk** [comment]
@sumit31agarwal had that issue sometime back. got to check with your ISP to whitelist expo.io ip addresses.

**Comment by sumit31agarwal** [comment]
@lokewk can you please tell me the address so that I can ask my ISP to whitelist. Thanks

**Comment by harshmdr-devslane** [comment]
✖ Uploading to EAS Build (2.6 MB / 24.0 MB)
FetchError: request to https://storage.googleapis.com/......./
failed, reason: socket hang up
    Code: ECONNRESET
