### ISSUE TITLE
Expo Start stuck on "Starting Metro Bundler."

### ISSUE THREAD

**Issue by nadavl** [expo/expo-cli#2934]
## Description
Expo Start stuck on "Starting Metro Bundler":
![image](https://user-images.githubusercontent.com/5332234/99939070-eadf7700-2d71-11eb-8f06-a6ae64e0ffbb.png)

## Expected Behavior
The project should build and run.

## Observed Behavior
- Running `expo init [app_name] --npm`.
- After successful init, running `expo start` in the new folder.
- Getting as far as the above and that's it.

Happens for any of my existing projects and also for a fresh one as described above.
All was working as usual up to few days ago - no major changes in OS / Env.

```
No error text.
```

## Environment
Macbook Pro 2019

## Reproducible Demo

- Run `expo init [app_name] --npm`.
- After successful init, run `expo start` in the new folder.

## Expo diagnostics

  Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v12.18.4/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.4 => 39.0.4
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: managed

**Comment by AdamJNavarro** [comment]
Hey @nadavl, my first thought here would be a network issue. Any chance you have been able to test with your system connected to a different network?

**Comment by jospas** [comment]
I have exactly the same behaviour, can't get expo working because of this

**Comment by brentvatne** [comment]
@jospas - i don't have any information about your environment so it is very difficult to help. are you using expo sdk 40? run `expo diagnostics` in your directory and share more information

**Comment by jospas** [comment]
Hi there @brentvatne, 

Sorry diagnostics info below:

Phone Samsung S20 Ultra

```
Expo CLI 4.0.13 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 15.4.0 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 7.0.15 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
      Android SDK:
        API Levels: 29
        Build Tools: 29.0.3
        System Images: android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.13
    Expo Workflow: managed
```

I wasn't planning on using the local emulators I had them from a previous project and can remove them.

When I start up a clean expo project the web ui only show Starting Metro Bundler.

When I try to access from Android using the barcode on LAN I get: 

```
Something went wrong
Network response timed out
```

I am on a MAC SOE but don't think there is is any firewall in play, I can see port 19000 is open and listening:

```
netstat -anvp tcp | grep 19000
tcp46      0      0  *.19000                *.*                    LISTEN      131072 131072  73345      0 0x0100 0x00000106
```

I have tried removing expo, upgrading node and npm, cleaning my NPM cache etc.

I have tried this in Tunnel mode the the web ui immediately shows:

```
Error loading DevTools
ValidationError: "urlType" must be one of [exp, http, redirect, no-protocol]
```

Local mode fails to open with USB debugging enabled, just gives me a spinning wait cursor.

The Expo APIs sample project runs nicely on my phone.

I'm thinking expo won't work on my mac from a clean install, I'm a bit lost!

**Comment by brentvatne** [comment]
you will need to open more ports than 19000.

19000: serves your app manifest (try navigating to http://localhost:19000/ with the server running)
19001: serves the app bundle (this is metro bundler)
19002: serves the expo web tools "web ui"

<hr />

> I have tried this in Tunnel mode the the web ui immediately shows: ...

interesting! can you let me know what you did in order to try the tunnel mode?

**Comment by jospas** [comment]
Hi @brentvatne 

I dug a bit deeper and it seems we run a daemon firewall on macs not connected to the corp network and I managed to disable that and everything has started to work as expected.  

Thanks for assisting, all similar posts point to networking restrictions being the root cause I just couldn't see one was enabled!

**Comment by brentvatne** [comment]
@jospas - 🙏  thanks for the update

if you have any suggestions for how we could handle this better i'm very open to ideas!

**Comment by nadavl** [comment]
Seems it just waited for me to scan the QR code.At some point after many tries and re installs, after I just scanned the QR code, it started working.

**Comment by jospas** [comment]
I have noticed that expo can die with out of memory if you include any big node dependencies (like the AWS SDK) it gets stuck at 99% compiling and memory spikes up.

I use this script to run expo now, if you are seeing slow compilation, giving expo more ram might help:

    #!/bin/bash
    
    set -e
    
    NODE_OPTIONS=--max_old_space_size=4096 expo start

**Comment by jospas** [comment]
My issue was definitely a local firewall blocking external port access, I would verify you can load a simple webpage from your computer using your phone first, that led me to a deeper investigation of inbound port blocking.

**Comment by 2MO5** [comment]
Facing the same problem for a few hours now.
 
 Nothing worked.
 
 Yup, no firewall is blocking it.
 
 Is there any other possible solution for this? @jospas 
 
 Thanks a megaton!

**Comment by brentvatne** [comment]
@2MO5 - i don't know enough about windows to be able to tell you why `wmic` isn't available in your path. we use `envinfo` to gather some diagnostic information, in particular this line is causing the error: https://github.com/tabrindle/envinfo/blob/c78209a50274e738628020040425b16c17f9be82/src/helpers/ides.js#L49 - i imagine the authors of this library would only use this utility if it was expected to be installed on every windows machine. perhaps you removed it? what windows version do you use?

**Comment by 2MO5** [comment]
Hey thanks!

Somehow I found a way out of it. It was loads of trial and error. Quite difficult to trace back what I did!


Btw, I am using  Windows 10

**Comment by mkhoussid** [comment]
Switching from LAN to Tunnel worked for me.

**Comment by MenachemICTBIT** [comment]
@mkhoussid Switching to tunnel also worked for me, for some reason. This was a really frustrating bug. Hopped on my computer ready to code, and BAM, an hour of frustratingly trying to get the project to start.

**Comment by humbertocarvalho** [comment]
I was facing the same problem.
Switched fron LAN to Tunnel and worked too.

**Comment by AlenToma** [comment]
I faced this once, first restart the vs code, and then run `expo upgrade`. this will delete the `package.lock.json` and the `modulenode ` and reinstall everything. 

then run `expo start` and start working

**Comment by Kheman9862** [comment]
> Switching from LAN to Tunnel worked for me. Android physical device and Mac connected to same network.

Thanks, man this worked for me too.

**Comment by ahmedyounes** [comment]
> Switching from LAN to Tunnel worked for me. Android physical device and Mac connected to same network.

worked for me too

**Comment by ClappTrap** [comment]
Tried, but I am running expo in WSL2 on windows, still no luck.

**Comment by ajayo2** [comment]
You need to install watchman for this. Assuming you have homebrew working, run below command in terminal to install repo
**git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow**

After that **brew install watchman**

And then **expo start** . This should solve your problem, as it did mine.
PS: I turned off firewall before trying this as it was suggested somewhere and didn't turned it on again.

**Comment by nico-on-vacation** [comment]
Things that might fix it that worked for me:

- [ ] npm audit fix
- [ ] If on expo start some packages are incompatible install those packages with "expo install <packagename> ..."
- [ ] Try in another network as it might be just a network issue
- [ ] Use tunnel 

I hope that helps, cheers.

**Comment by nico-on-vacation** [comment]
Things that might fix it that worked for me:

- [ ] npm audit fix
- [ ] If on expo start some packages are incompatible install those packages with "expo install <packagename> ..."
- [ ] Try in another network as it might be just a network issue
- [ ] Use the expo tunnel instead of lan

I hope that helps, cheers.

**Comment by lakshman008** [comment]
> You need to install watchman for this. Assuming you have homebrew working, run below command in terminal to install repo
> **git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow**
> 
> After that **brew install watchman**
> 
> And then **expo start** . This should solve your problem, as it did mine.
> PS: I turned off firewall before trying this as it was suggested somewhere and didn't turned it on again.

this solved my issue, thanks!

**Comment by ABSphreak** [comment]
Had the same issue today, while trying to learn React Native.
I thought it was some issue with  Apple Silicon.
Things that worked for me:
- Updated homebrew and reinstalled watchman: `brew install watchman`
- Switched connection a couple of times from WebUI → to make sure that connection is not stale.
- Finally, clicked on 'Run on iOS simulator' and it worked → you would need Xcode installed.

Reinstalling `watchman` would likely solve the issue as it is the file-watching
service of MacOS, sometimes it doesn't respond and `expo-cli` crashes

You can verify, if that happens to you, if you see an error like this in your terminal:
```
Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:178:28)
```

**Comment by edisonnkemande** [comment]
make sure your watchman is installed properly
