### ISSUE TITLE
Getting "Offline (PWA) support is not enabled in this build" even after configuring webpack offline: true

### ISSUE THREAD

**Issue by jarrvis** [expo/expo-cli#2942]
## Description
I would like to enable PWA mode on expo 39.0.0.
I followed https://expo.fyi/enabling-web-service-workers - generated webpack.config.js and enabled offline mode. When running expo build:web I keep getting "Offline (PWA) support is not enabled in this build. Learn more https://expo.fyi/enabling-web-service-workers"

## Expected Behavior
"Offline (PWA) support is not enabled in this build. Learn more https://expo.fyi/enabling-web-service-workers"
message should either not appear after enabling offline mode or instructions under https://expo.fyi/enabling-web-service-workers
should be changed to really enable PWA.

Seems like code relies on GenerateSW plugin to display message.

## Observed Behavior

```
Error text goes here!
```

## Environment
  Expo CLI 3.28.5 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 14.7.0 - /usr/local/bin/node
      npm: 6.14.7 - /usr/local/bin/npm
    npmPackages:
      @expo/webpack-config: ^0.12.44 => 0.12.44 
      expo: ^39.0.3 => 39.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: managed

**Comment by EvanBacon** [comment]
fixed in https://github.com/expo/expo-cli/pull/2907
