### ISSUE TITLE
Updating my application on Android Play Store shows Error

### ISSUE THREAD

**Issue by devmotionfr** [expo/expo-cli#2944]
Hello everyone,

I published a first version of my application to the Play Store successfully.

I've made some few hot fix in my JS and I want to publish the update on the Play Store.

So I've run the command :
`expo build:android -t app-bundle`

To create a new version of my application

Then I've upload the .aab file to the Play Console. And here is the message :
`Your Android App Bundle is signed with the wrong key. Ensure that your App Bundle is signed with the correct signing key and try again`

I don't know exactly what I did wrong

**Comment by Demonbruster** [comment]
I faced the same problem.

**Comment by simon-tannai** [comment]
Any solution for this issue ? 
I have the same error when I'm running `eas submit --platform android`
