### ISSUE TITLE
GetEnv.NoBoolean Error trying to start project with expo-cli

### ISSUE THREAD

**Issue by reggie3** [expo/expo-cli#295]
This issue is based on the following thread from the Expo forums: [](https://forums.expo.io/t/getenv-noboolean-error-trying-to-start-project-with-expo-cli/17611)  It has been posted here at the request of @brentvatne 

## Description

Using ` expo-cli start -c` on expo-cli version 2.6.0 results in the following error
`C:\Users\regin\AppData\Roaming\npm\node_modules\expo-cli\node_modules\getenv\lib\getenv.js:66
throw new Error(‘GetEnv.NoBoolean: ’ + value + ’ is not a boolean.’);` and failure to start the Expo packager.

## Expected Behavior

Expect the Expo packager to run.

## Observed Behavior

What actually happened when you performed the above actions?
The above listed error

If there's an error message, please paste the _full terminal output and error message_ in this code block:

```
C:\Users\regin\AppData\Roaming\npm\node_modules\expo-cli\node_modules\getenv\lib\getenv.js:66
throw new Error(‘GetEnv.NoBoolean: ’ + value + ’ is not a boolean.’);
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:
I’m using the following:
expo-cli 2.6.14
node 10.15.0
WIndows 10 build 17134.472

Trying to run the expo diagnostics command results in the same error.

Also specify:

- Phone/emulator/simulator platform, model and version: Android One Plus 5

## Reproducible Demo

N/A

The problem is in the getenv.js file of the getenv package:

Here is the code that is being referenced in getenv.js

```
boolish: function(value) {
    try {
      return convert.bool(value)
    }
    catch(err) {
      var isBool = (value === '1' || value === '0' || );
      if (!isBool) {
        throw new Error('GetEnv.NoBoolean: ' + value + ' is not a boolean.'); //// Here is line 66
      }

      return (value === '1');
    }
  },
```

```
That code references the convert.bool function which looks like this

bool: function(value) {
    var isBool = (value === 'true' || value === 'false' );
    if (!isBool) {
      throw new Error('GetEnv.NoBoolean: ' + value + ' is not a boolean.');
    }

    return (value === 'true')
  }
```

Changing `var isBool = (value === 'true' || value === 'false' );` to `var isBool = (value === 'true' || value === 'false' || value === 'TRUE' || value === 'FALSE');` solves the error.

**Comment by fson** [comment]
Maybe you have some environment variable (e.g. `EXPO_DEBUG`) set with an incorrect value?

**Comment by lylest** [comment]
facing the same problem

**Comment by anujpro007** [comment]
getting the same error even after changing to this  

> var isBool = (value === 'true' || value === 'false' || value === 'TRUE' || value === 'FALSE');

**Comment by fson** [comment]
To help track the cause of this issue, please check the environment variables set in your terminal session, as this error means that Expo CLI failed to parse one of them.

On Windows you can do this by running the command:
```cmd
SET
```
and on macOS or Linux:
```sh
env
```
