### ISSUE TITLE
Clear the project .expo directory when running expo start -c

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#2953]
Related: https://github.com/expo/expo-cli/issues/2952

This would be easier than instructing people to delete the `.expo` directory

**Comment by EvanBacon** [comment]
duplicate https://github.com/expo/expo-cli/issues/1308

**Comment by brentvatne** [comment]
i think this is a bit different, i'm thinking we should just clear the config every time you pass -c rather than trying to do some test of validity
