### ISSUE TITLE
I can't run "expo start".

### ISSUE THREAD

**Issue by boychik-serzh** [expo/expo-cli#2972]
I tried to run "expo start".
But it returns 
==============================================================
WARNING: expo-cli has not yet been tested against Node.js v15.3.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=10.13.0 <11.0.0 (Maintenance LTS)
* >=12.13.0 <13.0.0 (Active LTS)
* >=14.0.0  <15.0.0 (Current Release)
==============================================================
My node.js version is 15.3.0
My expo-cli version is 3.28.5

Which version of node.js do I have to install?

**Comment by KicassOS** [comment]
I'd suggest you install the Active LTS (LTS stands for Long Term Support), it's the stable version meaning no update is going to suddenly break your whole project, unless you need some specific new feature.

**Comment by EvanBacon** [comment]
Correct we currently don't support the latest version of node. Please install the LTS (per our setup instructions) https://docs.expo.io/get-started/installation/#requirements
