### ISSUE TITLE
some error like "Couldn't start project on Android: Error running adb"

### ISSUE THREAD

**Issue by Zhou-Bill** [expo/expo-cli#2973]
![image](https://user-images.githubusercontent.com/13554001/100605808-75604180-3343-11eb-84dd-f20fd9c65b51.png)

i have an error like above, how to solve ?

`system: win 10`
`expo-cli version:  4.0.4`
``

![image](https://user-images.githubusercontent.com/13554001/100606060-ce2fda00-3343-11eb-80dd-542ece7f71e8.png)

**Comment by brentvatne** [comment]
it seems that you can't connect to cloudfront. are you based out of china? you need to be able to access google cloud and amazon aws services in order to use these tools

**Comment by Zhou-Bill** [comment]
> it seems that you can't connect to cloudfront. are you based out of china? you need to be able to access google cloud and amazon aws services in order to use these tools

i am in china,  i visit google is ok,  but visit  this url  `http://d1ahtucjixef4r.cloudfront.net/` is unavalible
![image](https://user-images.githubusercontent.com/13554001/100686569-919ec580-33b9-11eb-9da1-267560630327.png)

**Comment by brentvatne** [comment]
it looks like this domain shouldn't actually be blocked in china, so perhaps you have some dns issues. here's the first search result for the `DNS_PROBE_FINISHED_NXDOMAIN` error: https://kinsta.com/knowledgebase/dns_probe_finished_nxdomain/ - maybe it will be helpful for you.

(verified that it isn't blocked in china by looking at https://www.comparitech.com/privacy-security-tools/blockedinchina/)

**Comment by Zhou-Bill** [comment]
i change dns by network in ipv4 , `8.8.8.8` and it's work, thank you
