### ISSUE TITLE
Android stuck on splash screen

### ISSUE THREAD

**Issue by derrickclaye** [expo/expo-cli#2979]
I am using the latest EXPO SDK and CLI

Currently in development, I ran yarn run configure-splash-screen [options] using the image flag and background color flag ...the splash screen was set on both ios and android, but on android the app is suck on the splash screen rather than proceeding to the main screen after the apps loads.. any idea why this is happening and how i can fix it?

**Comment by brentvatne** [comment]
follow issue template, also post https://stackoverflow.com/help/minimal-reproducible-example to new issue. use typical debugging techniques, explain what you tried and didn't work. we can't read your mind :)
