### ISSUE TITLE
Expo export does not support uploading of sourcemaps to sentry

### ISSUE THREAD

**Issue by timdelange** [expo/expo-cli#298]
## Description

When using "expo export --dump-sourcemap --public-url=http://www.example.com", the resulting sourcemap isnt uploaded to sentry, despite the post-publish hook confoguration in app.json.

It is also unclear how to do this manually in a way that will allow sentry to resolve code references properly, especially/including bundles subsequently added to detached app apk/ipa's

## Expected Behavior

There should be an option to have the same effect as the sentry-expo post-publish hook.

## Observed Behavior
No sourcemaps are ever uploaded, manual attempts seem not to resolove properly on sentry.

## Environment

I'm seeing it with expo-cli version 2.6.14, however, it has never worked since the release of "export" for expo-cli.

## To Reproduce

run "expo export" in a project dir.  Notice the lack of source code resolution in sentry when an error occurs.

**Comment by fson** [comment]
We might need to add a separate hook for this use case, e.g. `postExport`, make sure it works with the `sentry-expo/upload-sourcemaps` script and update the docs here to mention it: https://docs.expo.io/versions/latest/guides/using-sentry

**Comment by nitishdhar** [comment]
Hey guys, any resolution to this? How do I enable sentry to resolve code references properly. I was able to generate source maps using `expo export`. Does this not work with the postPublish hook?

**Comment by esemeniuc** [comment]
Interested in this issue as well! Local sourcemap dump would be very handy for browser debugging

**Comment by bradjones1** [comment]
Is this the necessary follow-up to https://github.com/expo/eas-cli/pull/1228?

**Comment by EvanBacon** [comment]
@bradjones1 that does seem like a fix for the original intent of the issue. Sentry + export + update works.
