### ISSUE TITLE
Stuck Downloading Javascript bundle 100.00% during remote debugging with VScode attach to packager.

### ISSUE THREAD

**Issue by phatluong** [expo/expo-cli#2982]
After starting a new project with `expo init <project_name>` everything runs fine. But when I try to test out the debugger by starting VScode 'Attach to packager' (having React Native Tools installed), and then use `Debug Remote JS` the expo app on my IOS Simulator just stops at `Downloading Javascript bundle 100.00%`. My VSCode debugger is reporting that it is connected. I am using node `v12.20.0`.

### Problem
<img width="315" alt="Screenshot 2020-12-02 at 06 42 00" src="https://user-images.githubusercontent.com/50320833/100833090-81462380-3469-11eb-9859-3fa2a00801e8.png">

Works fine if I use Firefox to debug.

**Comment by brentvatne** [comment]
sorry we don't provide support for external tools, in this case the vscode debugger. i don't know what the problem could be with that particular tool. the only supported debugging tool for react-native is the built in remote debugging
