### ISSUE TITLE
[web] linking configuration urls don't work on browser page refresh on production builds

### ISSUE THREAD

**Issue by dincozdemir** [expo/expo-cli#2983]
### Summary of Issue 
I'm running a new expo project with tab examples. It has two tabs of BottomTabNavigator with a LinkingConfiguration defined in NavigationContainer. When I run the project on web, I can navigate between the tabs, see the url changes accordingly and refresh the page that is mapped to the current url successfully. When I run the application on production mode, I can navigate between the tabs, see the url changes accordingly but when I refresh the page I get an error message:

![Screenshot from 2020-12-01 23-21-51](https://user-images.githubusercontent.com/2143920/100803794-0e6a8780-342c-11eb-89b0-6b80329ab857.png)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 4.0.6 environment info:
    System:
      OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        Android NDK: 20.0.5594570
    npmPackages:
      expo: ~39.0.2 => 39.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-native-web: ~0.14.0 => 0.14.8 
    npmGlobalPackages:
      expo-cli: 4.0.6
    Expo Workflow: managed

Target: web

### Steps to Reproduce

- Start a new expo project with expo init. Choose `tabs (TypeScript)     several example screens and tabs using react-navigation and TypeScript` template. Without any change in the code, start expo and open web in production mode. Refresh any screen.

### Expected Behavior vs Actual Behavior

- Page refresh should open the page mapped to the url, as it does in development mode.
- Page refresh shows an error message instead

**Comment by Patrick-Sawyer** [comment]
Hi, I am having this exact same issue actually. My web linking works in Development but not in production mode. Same as above, when I navigate to pages through the app it works ok, but if i type "localhost:19000/signup" it gets a 404 back. The issue is also the same if i run "expo build:web" and then "npx serve web-build". I tried it in incognito mode with no luck. Will this work when hosted online?

**Comment by Patrick-Sawyer** [comment]
Here is a stripped version of my app.js if it helps

import React from "react";
import { createStackNavigator } from "@react-navigation/stack";
import { NavigationContainer } from "@react-navigation/native";

const Stack = createStackNavigator();

const linking = {

  prefixes: [
    "exp://",
    "localhost:19000",
    "http://localhost:19000"
    
  ],
  config: {
    screens: {
      signup: "signup",
      venue: "venue",
      webview: "webview",
      legal: "legal",
      home: "",
      error: "error",
      terms: "terms",
      privacy: "privacy"
    }
  }
};

export default function App() {
 
    return (
      <NavigationContainer
        linking={linking}
        theme={MyTheme}
      >
        <Stack.Navigator
          screenOptions={{
            headerShown: false,
            initialRouteName: "home",
          }}
          style={{flexGrow: 1}}

**Comment by Patrick-Sawyer** [comment]
```import React from "react";
import { createStackNavigator } from "@react-navigation/stack";
import { NavigationContainer } from "@react-navigation/native";

const Stack = createStackNavigator();

const linking = {

  prefixes: [
    "exp://",
    "localhost:19000",
    "http://localhost:19000"
    
  ],
  config: {
    screens: {
      signup: "signup",
      venue: "venue",
      webview: "webview",
      legal: "legal",
      home: "",
      error: "error",
      terms: "terms",
      privacy: "privacy"
    }
  }
};

export default function App() {
 
    return (
      <NavigationContainer
        linking={linking}
        theme={MyTheme}
      >
        <Stack.Navigator
          screenOptions={{
            headerShown: false,
            initialRouteName: "home",
          }}
          style={{flexGrow: 1}}

**Comment by Patrick-Sawyer** [comment]
Here is a stripped version of the start of my app.js file if it helps

```import React from "react";
import { createStackNavigator } from "@react-navigation/stack";
import { NavigationContainer } from "@react-navigation/native";

const Stack = createStackNavigator();

const linking = {

  prefixes: [
    "exp://",
    "localhost:19000",
    "http://localhost:19000"
    
  ],
  config: {
    screens: {
      signup: "signup",
      venue: "venue",
      webview: "webview",
      legal: "legal",
      home: "",
      error: "error",
      terms: "terms",
      privacy: "privacy"
    }
  }
};

export default function App() {
 
    return (
      <NavigationContainer
        linking={linking}
        theme={MyTheme}
      >
        <Stack.Navigator
          screenOptions={{
            headerShown: false,
            initialRouteName: "home",
          }}
          style={{flexGrow: 1}}

**Comment by Patrick-Sawyer** [comment]
Hi. Any update on this?

**Comment by brentvatne** [comment]
this is not an issue with expo. you need to configure your hosting provider to handle client-side routing like this, eg: https://github.com/expo/vector-icons/blob/master/website/now.json

here's the answer on create-react-app about this same problem: https://create-react-app.dev/docs/deployment/#serving-apps-with-client-side-routing

**Comment by Patrick-Sawyer** [comment]
Hi, cheers for the reply although I am stiil a bit confused. Unfortunately this wont be deployed on netlify, although it sounds like that takes away some of the hassle. I have since ejected from expo, does this change anything atall regarding this issue?

**Comment by joamartico** [comment]
I'm having exactly the same problem and I'm deploying in vercel. Anyone could solve it?

**Comment by Patrick-Sawyer** [comment]
I fixed it with a hack. In your web build folder you have a index.html. A traditional website will look in a folder called /signup when it gets a get request, as these are one page apps those /signup folders dont exist. If you copy your index.html into a folder called signup or whatever in the root of the web build it will prob work. it did for me. You need to do this for all your routes though. I only had about 10, but if you had 100 this would be impractical.

________________________________

**Comment by joamartico** [comment]
I think I understand, but to be sure could you show me your project? > I fixed it with a hack. In your web build folder you have a index.html. A traditional website will look in a folder called /signup (or whatever route) when it gets a get request, as these are one page apps those /signup folders dont exist. If you copy your index.html into a folder called signup or whatever in the root of the web build it will prob work. it did for me. You need to do this for all your routes though. I only had about 10, but if you had 100 this would be impractical. I think it has the added benefit of these pages showing up in google bots which helps with SEO.

**Comment by Patrick-Sawyer** [comment]
I havent got it currently set up but say you have a route called "signup" e.g. navigation.navigate("signup") then you need a folder called signup in the root folder of your web build with a copy of index.html inside. You also need linking set up

**Comment by joamartico** [comment]
Thanks! I will try it but I found another way to solve it, caching the routes (enabling offline mode in webpack.config.js)

**Comment by taj567** [comment]
guys,am also facing same issue 
in my local project is working fine with linking after deploying it and refresh 404 page not found.
![Screenshot 2022-03-08 153213](https://user-images.githubusercontent.com/74459204/157213907-5deb6ea1-ba5a-4087-959c-b959fdb11c6d.png)

**Comment by brentvatne** [comment]
https://github.com/expo/expo-cli/issues/2983#issuecomment-743916090

**Comment by astriskit** [comment]
@brentvatne - thanks for the reply; yep, the links - yet to try those. Been trying on `localhost` so far and not deployed as such.

**Comment by astriskit** [comment]
@brentvatne - thanks for the comment; It helped.

**Comment by danielyaa5** [comment]
Try setting the framework in Vercel to `create-react-app`

**Comment by irealycode** [comment]
> I fixed it with a hack. In your web build folder you have a index.html. A traditional website will look in a folder called /signup (or whatever route) when it gets a get request, as these are one page apps those /signup folders dont exist. If you copy your index.html into a folder called signup or whatever in the root of the web build it will prob work. it did for me. You need to do this for all your routes though. I only had about 10, but if you had 100 this would be impractical. I think it has the added benefit of these pages showing up in google bots which helps with SEO.

WORKS

**Comment by LunatiqueCoder** [comment]
> this is not an issue with expo. you need to configure your hosting provider to handle client-side routing like this, eg: https://github.com/expo/vector-icons/blob/master/website/now.json
> 
> here's some info about deploying to netlify: https://github.com/expo/examples/tree/master/with-react-router#deploying-to-netlify
> 
> here's the answer on create-react-app about this same problem: https://create-react-app.dev/docs/deployment/#serving-apps-with-client-side-routing

## With Vercel:

1. Add this in a `vercel.json` file inside the root of your project.

```json
{
  "rewrites": [
    { "source": "/:path*", "destination": "/index.html"}
  ]
}
```

2. Add your whole repository to Vercel.
3. Your deployment settings should look like this: 

![image](https://github.com/expo/expo-cli/assets/55203625/8a454b68-4eb1-4f31-b71b-169b5a2cf9c5)


### ⚠️ **Note:** 
According to [Expo Docs: Distribution - Deploy your web app](https://docs.expo.dev/distribution/publishing-websites/#create-a-build), you should use `npx expo export:web` along with `webpack`. However, if you use `expo-router`, you will have to use Metro bundler, and `npx expo export:web` will fail. Nevertheless, step 3 (`npx expo export` only) works perfectly fine for me. 

Good luck for everyone with this issue!
