### ISSUE TITLE
Ejected app - push notifications not properly received on iOS (but something goes through)

### ISSUE THREAD

**Issue by hardcodet** [expo/expo-cli#2989]
## Description

Feel free to close if this is the wrong place - I assume something went wrong with ejecting OR publishing my app, since I can't receive push notifications anymore. The behavior is quite weird though, maybe it's something else.

## Expected Behavior

Sent push notifications should be received on the target.

## Observed Behavior

Ejected app, SDK 39.0.0, and my iOS app doesn't really handle them anymore. I thought iOS was simply broken, but then, I can update badge numbers through the push notification tool. Here's what works and what doesn't:

- I can get a token on both iOS / Android
- Sending messages from the iPhone to the Android phone works
- Sending messages from the Android app to the iOS app doesn't result in any activity on the iPhone

- Sending "hello world" message to Android through the expo push notification test tool works (message displayed)
- Sending "hello world" to iOS through the expo push notification test tool doesn't result in a message being displayed on the phone.
BUT:
- **Setting the badge number along with the "hello world" message in the tool results in the badge being updated. So messages _do_ come through.**

Setup:
- iOS: App installed through TestFlight, built with expo certificates and provisioning profiles that were present from the managed workflow. Had to manually set the push notifications / remote notifications capabilities.
- Android: I didnt' specify anything specifically after ejecting.

My understanding was that since it's an ejected app (and push notifications used to work when managed), no changes are necessary, as all the necessary information has already been uploaded. Also no code changes compared to the managed app (experience ID is included in subscription), and same code on iOS / Android. Am I missing something in the ejected code, or is this a potential issue?

## Environment

```
  Expo CLI 4.0.7 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.5.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
      Android SDK:
        API Levels: 26, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.0
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.4 => 39.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.3 => 0.63.3 
      react-native-web: ~0.13.7 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.7
    Expo Workflow: bare
```

Also specify:

- iPhone 6, iOS 12
- Galaxy S10, Android 10

**Comment by hardcodet** [comment]
Oh, might be background notifications that are missing. Closing for now, will reopen if necessary.

**Comment by hardcodet** [comment]
Now they work again, at least on most phones (still broken on my iPhone 6 despite reinstalls and app restarts). Feel free to close.

TBH, push notifications with expo have been a bit of an on/off experience (e.g. with hanging promises just to fetch a push notification token). If they were critical to my app, I'd go through the hassle of switching to an alternative implementation by now.

**Comment by EvanBacon** [comment]
Looks like bare workflow support for the Expo token was added in Expo SDK 41 https://github.com/expo/expo/pull/12465
