### ISSUE TITLE
error when i start my project

### ISSUE THREAD

**Issue by HocineDev** [expo/expo-cli#299]
## Description

1-when i start my project after few second it display for me an error message 

## Expected Behavior
i put the following commend line in the cmd:expo init myMovies 
==> cd myMovies ==>npm start
i wanted to get a QR code to connect with my device and get the render of my project 

## Observed Behavior

after expo init commend i got many errors 
and when i start my project after few second it display me an error message:Expo Developer Tools is disconnected from Expo CLI. Use the expo start command to start the CLI again.(the content of the message)
*************************
If there's an error message, please paste the _full terminal output and error message_ in this code block:

Ethe error message in the cmd:(below)
-------------------------------------------------------
[11:16:59] Starting project at C:\Users\Admin\Desktop\myMovies
[11:17:00] Expo DevTools is running at http://localhost:19002
[11:17:00] Opening DevTools in the browser... (press shift-d to disable)
[11:17:06] Error: node_modules directory is missing. Please run `npm install` in
 your project directory.
[11:17:06] Couldn't start project. Please fix the errors and restart the project
.
[11:17:06] Set EXPO_DEBUG=true in your env to view the stack trace.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `expo start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to in
stall?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2019-01-11T10_17_06_
711Z-debug.log

------------------------------------------------------------------
## Environment

C:\Users\Admin\Desktop\myMovies>expo diagnostics

  Expo CLI 2.6.14 environment info:
    System:
      OS: Windows 8.1
    Binaries:
      npm: 6.4.1 - D:\Programmation\node js\npm.CMD

Also specify:

- Phone/emulator/simulator platform, model and version: android device(phone) version 5.1.1

**Comment by amandeepmittal** [comment]
Hey @HocineDev I think you need to run `npm install` command to install dependencies. Look at the error message from the log you published: 

`[11:17:06]Error:node_modules directory is missing. Please run npm install in
your project directory.`

Also, which Expo version are you running?

**Comment by GalacticRogue** [comment]
I am having the same exact issue with the same exact errors , while I have tried `npm install` but it  just stops and says `bad system call`
