### ISSUE TITLE
Node Versions

### ISSUE THREAD

**Issue by Daniyalzakir321** [expo/expo-cli#2990]
WARNING: expo-cli has not yet been tested against Node.js v15.3.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=10.13.0 <11.0.0 (Maintenance LTS)
* >=12.13.0 <13.0.0 (Active LTS)
* >=14.0.0  <15.0.0 (Current Release)

[Please Make it Compatible with all versions of Nodes]
I use both  expo and react-native, in react-native version 6.3 (which is stable version) require updated node,
but when i install that ,and run expo it says expo is not compatible with this node version

**Comment by brentvatne** [comment]
published expo-cli@4.0.8 to remove this warning for node 15, as it seems that not many users have encountered issues.

an aside, i think react-native docs should update their install instructions to suggest installing the active LTS release, but that's a separate issue.

thanks for raising this, it was a good time to revisit node 15 support!

**Comment by ThwishaKotian** [comment]
I tried to install expo-cli using npm install --unsafe-perm -g expo-cli and when I check the expo version this is coming up. Can anyone tell me what's wrong?

expo-cli has not yet been tested against Node.js v16.3.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <13.0.0 (Maintenance LTS)
* >=14.0.0 <15.0.0 (Active LTS)
* >=15.0.0 <17.0.0 (Current Release)

**Comment by daomtthuan** [comment]
> I tried to install expo-cli using npm install --unsafe-perm -g expo-cli and when I check the expo version this is coming up. Can anyone tell me what's wrong?
> 
> expo-cli has not yet been tested against Node.js v16.3.0.
> If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues
> 
> expo-cli supports following Node.js versions:
> 
> * > =12.13.0 <13.0.0 (Maintenance LTS)
> * > =14.0.0 <15.0.0 (Active LTS)
> * > =15.0.0 <17.0.0 (Current Release)



> I tried to install expo-cli using npm install --unsafe-perm -g expo-cli and when I check the expo version this is coming up. Can anyone tell me what's wrong?
> 
> expo-cli has not yet been tested against Node.js v16.3.0.
> If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues
> 
> expo-cli supports following Node.js versions:
> 
> * > =12.13.0 <13.0.0 (Maintenance LTS)
> * > =14.0.0 <15.0.0 (Active LTS)
> * > =15.0.0 <17.0.0 (Current Release)

@ThwishaKotian I think you should use 14 LTS :)) `expo-cli supports following Node.js versions: 15.0.0 <17.0.0 (Current Release)` like a joke

**Comment by brentvatne** [comment]
we don't support node 17 yet @divyaboominathan

**Comment by GeeteshSingh** [comment]
Inside your project folder have a .nvmrc file and write **16** in it. go out of the directory and come again and it will load npm 16 which would solve this issue.
