### ISSUE TITLE
Overriding `NODE_OPTIONS` when `fork`ing `react-native/local-cli/cli.js` breaks WebStorm multiprocess debugging

### ISSUE THREAD

**Issue by vjpr** [expo/expo-cli#3009]
## Description

https://github.com/expo/expo-cli/blob/5e2e9f8c9ae00bcbb0afac0b675eab2dffd9a8eb/packages/xdl/src/Project.ts#L1552-L1562

WebStorm [passes information via `process.env.NODE_OPTIONS`](https://youtrack.jetbrains.com/issue/WEB-43320#focus=Comments-27-3918889.0-0 ) to allow [debugging child processes](https://www.jetbrains.com/help/webstorm/node-multiprocess-debugging.html). 

```
console.log(process.env.NODE_OPTIONS)
--require /private/var/folders/kp/06ys69nn6hq9k23cv0xxn19m0000gn/T/debugConnector.203.5981.155.js
```

Expo overrides it preventing the WebStorm debugger working.

## Environment

```
  Expo CLI 4.0.8 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.2.0 - ~/nvm/versions/node/v14.2.0/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.4 - ~/nvm/versions/node/v14.2.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.5
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 3.21.5
    Expo Workflow: managed
```

## Expected Behavior

WebStorm debugger should work.

## Observed Behavior

WebStorm debugger doesn't work in child processes from `react-native` onwards.

## Fix

`process.env.NODE_OPTIONS` should not be overridden. It should be concatenated.

Something like:

```
NODE_OPTIONS: (process.env.NODE_OPTIONS ?? ' ') + ' ' + process.env.METRO_NODE_OPTIONS
```

## Workaround

a. I'm figuring out if there is a way to pass WebStorm's `NODE_OPTIONS` modifications via `METRO_NODE_OPTIONS`.

b. Possibly we could unset `js.debugger.use.node.options` in WebStorm registry, but then we would manually have to pass down `--inspect`...

## Reproducible Demo

- Try set a breakpoint in a `react-native` when using the WebStorm debugger.

**Comment by brentvatne** [comment]
we don't spawn a react-native-cli process in expo sdk 40 and higher, you can opt into it in earlier SDKs by using `EXPO_USE_DEV_SERVER=1` env var

**Comment by brentvatne** [comment]
(let me know if this doesn't fix your issue and i'll reopen)

**Comment by vjpr** [comment]
Solved!
