### ISSUE TITLE
You must set the --apple-id flag and set the EXPO_APPLE_PASSWORD environment variable

### ISSUE THREAD

**Issue by tylerthedeveloper** [expo/expo-cli#3012]
## Description

I created a command to run expo build:ios to save time on having to enter credentials all the time and in order to help with automating it in the future, but I am hitting the following error: 

You must set the --apple-id flag and set the EXPO_APPLE_PASSWORD environment variable #2343

Here is the build script:

scripts: {
"ebi": "expo build:ios -t archive --apple-id *****@gmail.com --team-id ******",
}

This seems to be the similar issue as - https://github.com/expo/expo-cli/issues/2343

## Environment

  Expo CLI 3.24.2 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.3 - /usr/local/bin/node
      npm: 6.14.4 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.24.2

## Expected Behavior

This should run the whole as expected 

## Observed Behavior

I hit the error listed above

```
You must set the --apple-id flag and set the EXPO_APPLE_PASSWORD environment variable
```

**Comment by brentvatne** [comment]
1) your expo-cli version is very old! please always try to use the latest. this alone may resolve your issue
2) what if you run `expo build:ios -t archive --apple-id *****@gmail.com --team-id ******` on its own, without going through an npm script? do you have the same issue?

**Comment by tylerthedeveloper** [comment]
turns out the though the env variable was set and would print from local, the terminal wasn't re-sourced for expo to pick it up

Thanks Brent! closing this issue (:

**Comment by brentvatne** [comment]
awesome, glad you found the source of the issue!
