### ISSUE TITLE
Getting error when I run the app

### ISSUE THREAD

**Issue by Santhoshonet** [expo/expo-cli#3022]
Getting the below error when I run the app, 

Your project is accessing the following APIs from a deprecated global rather than a module import: Constants (expo-constants).

The global "__expo" and "Expo" objects will be removed in SDK 41. Learn more about how to fix this warning: https://expo.fyi/deprecated-globals

Please suggest

**Comment by Santhoshonet** [comment]
Also getting the below after the error

It appears that you are using old version of react-navigation library. Please update @react-navigation/bottom-tabs, @react-navigation/stack and @react-navigation/drawer to version 5.10.0 or above to take full advantage of new functionality added 
to react-native-screens

**Comment by Noamsachartov** [comment]
i have the same problem

**Comment by brentvatne** [comment]
ok, read the error message and then do what it says :)

**Comment by Bound3R** [comment]
I have the same problem but I am using `expo-constants` as indicated in the warning :/

**Comment by brEaTh-263** [comment]
Anyone understood what was meant to be changed?

**Comment by BCalitz** [comment]
> Anyone understood what was meant to be changed?

With you don't understand either updated all react-navigation packages (tab, drawer, stack) but still has the error

**Comment by brentvatne** [comment]
ok, there are two separate discussion here.

for the global warning, please refer to https://github.com/expo/fyi/blob/master/deprecated-globals.md

for the react-native-screens warning, please refer to https://github.com/expo/expo/issues/11301#issuecomment-742833563

**Comment by AnyByte** [comment]
> 
> 
> ok, read the error message and then do what it says :)

Its kinda hard when it doesn't say which library is causing this and the logs are 100% useless.

```
- node_modules\react-native\Libraries\LogBox\LogBox.js:117:10 in registerWarning
- node_modules\react-native\Libraries\LogBox\LogBox.js:63:8 in warnImpl
- node_modules\react-native\Libraries\LogBox\LogBox.js:36:4 in console.warn
- node_modules\expo\build\environment\react-native-logs.fx.js:18:4 in warn
- node_modules\expo\build\deprecatedGlobal.js:18:4 in logWarning
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:130:14 in _callTimer
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:383:16 in callTimers
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:416:4 in __callFunction
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:109:6 in __guard$argument_0
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:108:4 in callFunctionReturnFlushedQueue
* [native code]:null in callFunctionReturnFlushedQueue
```

**Comment by mfy5013** [comment]
I'm getting this warning but when i search for Expo. or __expo the only mentions are under cached files for expo babel-loader

/.expo/web/cache/development/babel-loader/xxxx.json

cleared cache but still getting the warning, any idea?

**Comment by rnakhan** [comment]
I am seeing this warning "expo your project is accessing the following APIs from a deprecated global context rather than a module import: Constants" but **only on Android (not iOS)**.

Here are two pieces of relevant information.
1. In all my code I am using the module export as recommended 
`import Constants from 'expo-constants';`

2. Also I searched under node_modules for any of my dependencies using the global context 
`grep -lr "__expo.Constants" node_modules`
`grep -lr "from 'expo'" node_modules`
But I did not find anything unusual there either.

On Android when it triggers it seems to be coming when I try to use https://www.npmjs.com/package/react-native-popover-view in my code, but this library seems fine and it has no dependency on expo.
The yellow box warning is of no particular use either.

Is there any way to find out where is this deprecated code? Unless this is a Expo bug. 

Thanks!

**Comment by brentvatne** [comment]
you could try opening https://github.com/expo/expo/blob/master/packages/expo/build/globals.js#L20 in your node_modules and adding a debugger. the calling location is lost because we aggregate messages in order to spam less when the app starts - https://github.com/expo/expo/blob/d4a0f2d7557c4abbb3535e95acd1b5417411a70d/packages/expo/src/deprecatedGlobal.ts#L4-L7

**Comment by rnakhan** [comment]
Thanks for the pointers. 
The offending code seems  to be in SafeAreaView 
 ```
 /**
   * This is a temporary workaround because we don't have a way to detect
   * if the status bar is translucent or opaque. If opaque, we don't need to
   * factor in the height here; if translucent (content renders under it) then
   * we do.
   */
  if (Platform.OS === 'android') {
    if (global.Expo) {
      return global.Expo.Constants.statusBarHeight;
    } else {
      return 0;
    }
  }
```

I have tried using both imports
import SafeAreaView from 'react-native-safe-area-view'; and 
import { SafeAreaView } from 'react-native'; but both point to same source. 

Is this something that is known? Or is there a workaround?

Thanks

**Comment by CatthewMoker** [comment]
I had SafeView from react-navigation, and that caused me to get that deprecated warning. Having said that and switching it to react-native module instead it cleared that error for me.

Thanks for the SafeView tip! Had it in the wrong place.

**Comment by yash-k15** [comment]
Did anyone figure out where to import Constants from 'expo-constants' ? SafeAreaView is giving me the warning, if I remove it, the warning stops, where and what needs to be changed??

**Comment by dariocostanzo** [comment]
> Did anyone figure out where to import Constants from 'expo-constants' ? SafeAreaView is giving me the warning, if I remove it, the warning stops, where and what needs to be changed??

I am having the same issue, I can't figure out what is triggering this warning, I have checked and update all of my libraries, none of them is using the globals "__expo" and "Expo". I am out of ideas.

**Comment by yash-k15** [comment]
> > Did anyone figure out where to import Constants from 'expo-constants' ? SafeAreaView is giving me the warning, if I remove it, the warning stops, where and what needs to be changed??
> 
> I am having the same issue, I can't figure out what is triggering this warning, I have checked and update all of my libraries, none of them is using the globals "__expo" and "Expo". I am out of ideas.

For me, instead of importing SafeAreaView from 'react-native, I imported it from 'react-native-safe-area-context', that solved the issue

**Comment by superandrew** [comment]
> ok, read the error message and then do what it says :)

It's been a couple of months I'm trying to get rid of it after trying many times to do what it says, unfortunately @yash-k15 's advice didn't work either..
