### ISSUE TITLE
Constants.nativeAppVersion shows wrong value, Not picking up the app.json version value.

### ISSUE THREAD

**Issue by chamikabm** [expo/expo-cli#3023]
## Description

 Constants.nativeAppVersion returns an invalid value (2.18.2(, rather than the version value from app.json

## Environment
 Expo CLI 4.0.13 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.21.0 - ~/.nvm/versions/node/v10.21.0/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v10.21.0/bin/npm
    Managers:
      CocoaPods: 1.9.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.13
    Expo Workflow: managed

Also specify:

Running on Iphone X, IOS 14.2

## Expected Behavior
It should return the app.json version value

## Observed Behavior
An invalid value is being returned from  Constants.nativeAppVersion 

## Reproducible Demo
```
import React from 'react';
import { useTheme } from '@react-navigation/native';
import {
  View, Text, StyleSheet, Button,
} from 'react-native';
import Constants from 'expo-constants';

const SettingsScreen = ({ navigation }) => {
  const { colors } = useTheme();

  return (
    <View style={styles.container}>
      <View>
        <Text style={{ color: colors.text }}>
          {`My App ${Constants.nativeAppVersion} (${Constants.nativeBuildVersion})`}
        </Text>
      </View>
    </View>
  );
};

export default SettingsScreen;
```

**Comment by brentvatne** [comment]
https://docs.expo.io/versions/latest/sdk/constants/#constantsnativeappversion

> The Info.plist value for CFBundleShortVersionString on iOS and the version name set by version in app.json on Android at the time the native app was built.

**Comment by chamikabm** [comment]
@brentvatne Thank you!
