### ISSUE TITLE
Feature `android.hardware.sensor.compass` is not declared in manifest when using DeviceMotion API in managed workflow.

### ISSUE THREAD

**Issue by Baloche** [expo/expo-cli#3025]
## Description

Hello !
I am building a navigation app for Android which mainly act as a compass. To achieve this, I use the DeviceMotion API from ‘expo-sensors’ in order to get the user’s device orientation relative to the north.

Users without a compass in their device can still download the app but the app won't work. When I upload my .aab bundle to the Google Play console and inspect the bundle here is what I see : 

<img src="https://aws1.discourse-cdn.com/business5/uploads/expo/original/3X/d/c/dcbb09c30df2aea21248a8b4e284023c40dd4f4c.png"/>

➡️ The feature `android.hardware.sensor.compass is missing`. And because I am in managed workflow, I can not edit the `AndroidManifest.xml` myself and add the line `<uses-feature android:name="android.hardware.sensor.compass" android:required="true" />`

## Environment

```
Expo CLI 3.28.5 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
      Yarn: 1.17.3 - ~/.yarn/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 28
        Build Tools: 28.0.3, 29.0.3
        System Images: android-22 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.16 => 0.12.38 
      expo: ^39.0.4 => 39.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.16 => 0.13.16 
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: managed
```
## Expected Behavior

The feature `android.hardware.sensor.compass` should appear in the declared features of the manifest when using DeviceMotion API

## Observed Behavior

That feature is missing

**Comment by EvanBacon** [comment]
You should be able to use `DeviceMotion.isAvailableAsync()` to determine if the device hardware is present. You can also create an [Expo config plugin](https://docs.expo.io/guides/config-plugins/#modifying-the-androidmanifestxml) to modify the AndroidManifest.xml in managed EAS build.
