### ISSUE TITLE
expo/xdl and expo/ngrok packages are failed to install in some cases when npm 7 is used

### ISSUE THREAD

**Issue by SounD120** [expo/expo-cli#3027]
## Description
Hello, we are the [React Native Tools extension team for VS Code](https://github.com/microsoft/vscode-react-native/issues/1473). 
In order to provide our customers debugging for Expo applications we install some additional modules to our extension dynamically, using `npm install` command since they are binary platform dependent (`@expo/xdl` and `@expo/ngrok`). But on Node.js 15 and npm 7 it became [impossible to install these modules](https://github.com/microsoft/vscode-react-native/issues/1473) in [React Native Tools](https://github.com/microsoft/vscode-react-native) repository project using the command `npm install @expo/xdl @expo/ngrok --verbose --no-save` due to the error below.
It is possible that this behavior is connected with the `type-fest` package which is the dependency for `react-refresh-webpack-plugin`: https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/244. 
We are not sure if this a global npm problem or an issue with local packages, so please let us know if it is better to move this conversation to [@npm/cli](https://github.com/npm/cli) repo. 

## Environment

```
  Expo CLI 4.0.13 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 15.4.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\yuri.skorokhodov\AppData\Roaming\npm\yarn.CMD
      npm: 7.1.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    Expo Workflow: managed
```

## Expected Behavior
`@expo/xdl` and `@expo/ngrok` installs without problems to [React Native Tools](https://github.com/microsoft/vscode-react-native) repository using `npm install @expo/xdl @expo/ngrok --verbose --no-save` command like it worked on Node.js < 15.

## Observed Behavior

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: type-fest@0.8.1
npm ERR! node_modules/type-fest
npm ERR!   type-fest@"^0.8.1" from globals@12.4.0
npm ERR!   node_modules/globals
npm ERR!     globals@"^12.1.0" from @eslint/eslintrc@0.2.2
npm ERR!     node_modules/@eslint/eslintrc
npm ERR!       @eslint/eslintrc@"^0.2.2" from eslint@7.15.0
npm ERR!       node_modules/eslint
npm ERR!         peer eslint@"^5.0.0 || ^6.0.0 || ^7.0.0" from @typescript-eslint/eslint-plugin@3.10.1
npm ERR!         node_modules/@typescript-eslint/eslint-plugin
npm ERR!         4 more (@typescript-eslint/experimental-utils, ...)
npm ERR!     globals@"^12.1.0" from eslint@7.15.0
npm ERR!     node_modules/eslint
npm ERR!       peer eslint@"^5.0.0 || ^6.0.0 || ^7.0.0" from @typescript-eslint/eslint-plugin@3.10.1
npm ERR!       node_modules/@typescript-eslint/eslint-plugin
npm ERR!         dev @typescript-eslint/eslint-plugin@"^3.7.1" from the root project
npm ERR!       4 more (@typescript-eslint/experimental-utils, ...)
npm ERR!   type-fest@"^0.8.0" from serialize-error@5.0.0
npm ERR!   node_modules/serialize-error
npm ERR!     serialize-error@"^5.0.0" from @expo/xdl@59.0.12
npm ERR!     node_modules/@expo/xdl
npm ERR!       @expo/xdl@"*" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional type-fest@"^0.13.1" from @pmmmwh/react-refresh-webpack-plugin@0.3.3
npm ERR! node_modules/@pmmmwh/react-refresh-webpack-plugin
npm ERR!   @pmmmwh/react-refresh-webpack-plugin@"^0.3.3" from @expo/webpack-config@0.12.51
npm ERR!   node_modules/@expo/webpack-config
npm ERR!     @expo/webpack-config@"0.12.51" from @expo/xdl@59.0.12
npm ERR!     node_modules/@expo/xdl
npm ERR!       @expo/xdl@"*" from the root project
```

## Reproducible Demo
1. Install Node.js 15 and npm 7
1. `git clone https://github.com/microsoft/vscode-react-native.git`
1. `cd vscode-react-native`
1. `npm install @expo/xdl @expo/ngrok --verbose --no-save`

**Comment by EvanBacon** [comment]
`expo/ngrok` is now an optional package which you install globally before using `expo start --tunnel`. This should prevent the issue from blocking development. Seems we may need to update ngrok to support node 15 🤔

**Comment by RedMickey** [comment]
Thanks for the help. We can no longer reproduce this problem. I believe the issue can be closed.

**Comment by rajnavadiya6** [comment]
npm install ngrok -g
