### ISSUE TITLE
Running Expo Devtools on another device on local

### ISSUE THREAD

**Issue by borasumer** [expo/expo-cli#3028]
## Description

Can't run Devtools on another local device

## Environment
macOS

I would like to browse Devtools on my other device which is in the same local connection.
## Observed Behavior
When I browse this, it says Safari can't connect the server, or Google Chrome, same error.
<!--
What actually happened when you performed the above actions?
It should open the Devtools on another local machine by browsing "ip-address-that-runs-the-app-":19002
When I browse "ip-address-that-runs-the-app-":19002, it says Safari can't connect the server, or Google Chrome, same error.
Not sure what I am missing, or this is actually a CLI bug.

**Comment by EvanBacon** [comment]
dev tools is pretty coupled to the local CLI instance, this feature could be difficult to maintain and continuously test.
