### ISSUE TITLE
npm install --global expo-cli npm WARN deprecated @hapi/joi@17.1.1: Switch to 'npm install joi' npm ERR! cb() never called!

### ISSUE THREAD

**Issue by joanna-7** [expo/expo-cli#3032]
## Description

**issue in upgrading expo-cli**

## Environment

**Expo CLI 3.26.2 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.15.2 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7**

**Comment by AdamJNavarro** [comment]
Hey @joanna-7, to clarify does the install not work or are you just seeing this deprecation warning during the install?

**Comment by raadu** [comment]
@AdamJNavarro The installation works fine. But hangs up some time during the installation. Shows this message and have to wait for a while.

**Comment by joanna-7** [comment]
> Hey @joanna-7, to clarify does the install not work or are you just seeing this deprecation warning during the install?

the install didn't work

**Comment by AhmadxAli** [comment]
how to fix ?

**Comment by thedarkcder** [comment]
yarn  global add expo-cli

**Comment by brentvatne** [comment]
the warning is a red herring. the bug "cb() never called" is something on the npm side, you can use yarn or upgrade npm or read related npm support pages, eg: https://npm.community/t/npm-err-cb-never-called/486

**Comment by kriscooper07** [comment]
Hi, Can anyone help me fix this bug while I'm trying to install expo on cmd?

npm WARN deprecated @hapi/joi@17.1.1: Switch to 'npm install joi'

**Comment by Ahercode** [comment]
Please I am finding difficulty to install expo
this is output I got 
npm WARN deprecated @hapi/joi@17.1.1: Switch to 'npm install joi'
npm ERR! cb() never called!

**Comment by brentvatne** [comment]
https://stackoverflow.com/questions/15393821/npm-err-cb-never-called
