### ISSUE TITLE
[config] Android icon inconsistent with the equivalent setting in managed workflow

### ISSUE THREAD

**Issue by jurica-penjgusic** [expo/expo-cli#3035]
With new build services android icon looks funny.

Screenshoot attached. 
The black one should be looking exact like green one, obviously in black color :)

![Screenshot_2020-12-16-13-18-24-495_com miui home](https://user-images.githubusercontent.com/26301007/102347860-4c75b880-3fa1-11eb-92d3-90700f3094c1.jpg)

**Comment by gyl89** [comment]
Same issue, I have got an ugly icon with `eas build.` Image is a 256x256 png, no-alpha file.

**Comment by D10S60948** [comment]
This issue also happens to me after ejecting without building with EAS (using gradle)..

**Comment by D10S60948** [comment]
Found out that it happens on android 8+ devices due to [adaptive icon of android](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive).
Try editing the icon so it will have 1/6 of it in each side transparent.

**Comment by gyl89** [comment]
Not sure to understand. Do you mean that for every of the 4 edges of the image, there should be a transparent strip whose width is 1/6th of the length of the image edge?

**Comment by D10S60948** [comment]
Yes. See the link in my previous comment. The explanation in the Android documentation is pretty clear.

**Comment by artsnr1** [comment]
I created the icon using editing figma sample file but still the icon is blurred using EAS. It's fine with expo build

**Comment by WeslleyBorges** [comment]
Any solution xD?
