### ISSUE TITLE
Failed to run “expo start” in WSL, spawn powershell.exe ENOENT

### ISSUE THREAD

**Issue by greyring** [expo/expo-cli#3041]
## Description

When I run “expo start” in WSL, it failed to launch DevTools in the browser, the error message says failed to spawn powershell.exe

## Environment

My WSL version is 1

Expo CLI 4.0.15 environment info:
System:
OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
Shell: 5.4.2 - /bin/zsh
Binaries:
Node: 14.15.3 - /usr/local/bin/node
npm: 6.14.9 - /usr/local/bin/npm
npmPackages:
expo: ~40.0.0 => 40.0.0
react: 16.13.1 => 16.13.1
react-dom: 16.13.1 => 16.13.1
react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
react-native-web: ~0.13.12 => 0.13.18
npmGlobalPackages:
expo-cli: 4.0.15
Expo Workflow: managed

## Expected Behavior

I expected the browser will be opened.

The strange thing is powershell.exe should locate in “/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe” rather than “/mnt/c/System32/WindowsPowerShell/v1.0/powershell.exe”

I tried to copy powershell.exe to “/mnt/c/System32/WindowsPowerShell/v1.0/powershell.exe” and the error becomes EACCES. “sudo” doesn’t help with this issue either.

Besides, the “shift-d” doesn’t stop the opening process of DevTools.

## Observed Behavior

```
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Error: spawn /mnt/c/System32/WindowsPowerShell/v1.0/powershell.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by brentvatne** [comment]
we use [react-dev-utils](https://www.npmjs.com/package/react-dev-utils) to open the browser (https://github.com/expo/expo-cli/blob/master/packages/expo-cli/src/commands/start/TerminalUI.ts#L14) 

it seems like there is a related issue on that repo: https://github.com/facebook/create-react-app/issues/7251

perhaps the suggestions there will help

**Comment by greyring** [comment]
Thanks, I looked through the related issue and found

```
export BROWSER=none
expo start
```

works in my case.
However, modifying $PATH doesn't help with this case.

The interactive prompt works fine with "shift+d" when I ssh to a remote server and run "expo start". Besides, it works fine if I add "export BROWSER=none" before "expo start"
