### ISSUE TITLE
expo upload:ios => RangeError: Invalid array length when running

### ISSUE THREAD

**Issue by cooperbrown9** [expo/expo-cli#3046]
## Description
When running `expo upload:ios` I get a `RangeError: Invalid array length` (note image)
<img width="611" alt="Screen Shot 2020-12-27 at 12 39 59 PM" src="https://user-images.githubusercontent.com/12388607/103179485-7c467b00-4841-11eb-9aa2-1d91e30193a9.png">

## Environment
`"expo-cli": 4.0.16`
`"react-native": "https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz"`

This app already exists on the App Store, I'm just publishing a new update.

##Expo Diagnostics
`Expo CLI 4.0.16 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.18.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.9 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.16
    Expo Workflow: managed`

##Notes
Thank you all in advance!

**Comment by brentvatne** [comment]
we will be removing this command shortly: https://github.com/expo/expo-cli/pull/3030

see this for more info on why we are doing it and what the alternatives are: https://github.com/expo/expo-cli/issues/2192#issuecomment-745626708

i'd recommend using `eas submit` or switching to using Transporter.app for uploads
