### ISSUE TITLE
illegal operation on a directory read after expo init

### ISSUE THREAD

**Issue by Neuraxis** [expo/expo-cli#3047]
## Description
Run expo init <folderName>, after init is finished the folder now has EISDIR: illegal operation on a directory read.
I have done this many times on this computer but today I get this error and I can not push up the folder to git.

## Environment
Windows 10

## Expected Behavior
Folder should be accessible 

## Observed Behavior
EISDIR: illegal operation on a directory read

## Reproducible Demo
install latest expo-cli and try for yourself.

**Comment by brentvatne** [comment]
some issue with your system: https://stackoverflow.com/questions/34959038/npm-stuck-giving-the-same-error-eisdir-illegal-operation-on-a-directory-read-a
