### ISSUE TITLE
How to get rid of the "The global “__expo” and “Expo” objects will be removed in SDK 41" warning?

### ISSUE THREAD

**Issue by dariocostanzo** [expo/expo-cli#3052]
SDK Version:40
Platforms(Android/iOS/web/all): Android/iOS

Hi there, I am getting this warning after upgrading to Expo 40:

> Your project is accessing the following APIs from a deprecated global rather than a module import: Constants (expo-constants).
> The global “__expo” and “Expo” objects will be removed in SDK 41. Learn more about how to fix this warning: https://expo.fyi/deprecated-globals

I did a quick search and found many reports [9160](https://github.com/react-navigation/react-navigation/issues/9160) and  [3022](https://github.com/expo/expo-cli/issues/3022)  about finding out that someone fixed it by updating react-native-paper (which did not work in my case) or by hiding it, but I can’t get rid of it. Is anyone willing to assist?

I have already tried to hide it and to update all of my libraries to no avail. I would rather fix it now than hiding it, so I am ok for the next upgrades.

Thanks in advance.

**Comment by brentvatne** [comment]
the only reason this could possibly happen is if you have some source code in your app or its dependencies that are reaching into the global expo object. so, if it's not in your app source, you can search node_modules.

if you can't find it, share your repo with me on github :)

**Comment by dariocostanzo** [comment]
Thanks @brentvatne I got rid of the warning by upgrading react-native-paper to the newest version 4.5.0

**Comment by brentvatne** [comment]
good to hear!
