### ISSUE TITLE
expo install firebase errors, npm install firebase doesn't

### ISSUE THREAD

**Issue by criesbeck** [expo/expo-cli#3066]
## Description

Installing the Firebase module fails using `expo install firebase`, works using `npm install firebase` on Windows 8 and 10.

## Environment

```
 Expo CLI 4.0.17 environment info:
    System:
      OS: Windows 8.1 6.3.9600
    Binaries:
      Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed
```

## Expected Behavior

In a fresh Expo project, I do

```
expo install firebase
```
I expect Firebase to install successfully.

## Observed Behavior

An error happens and Firebase fails to install. Here's the error output. 

```
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.24.2/node-v83-win32-x64-unknown.tar.gz
node-pre-gyp WARN Pre-built binaries not found for grpc@1.24.2 and node@14.15.4 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=C:\\Users\\riesbeck\\workspace\\javascript\\react\\mytest\\node_modules\\grpc\\src\\node\\extension_binary\\node-v83-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\riesbeck\\workspace\\javascript\\react\\mytest\\node_modules\\grpc\\src\\node\\extension_binary\\node-v83-win32-x64-unknown" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd C:\Users\riesbeck\workspace\javascript\react\mytest\node_modules\grpc
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --library=static_library --module=C:\Users\riesbeck\workspace\javascript\react\mytest\node_modules\grpc\src\node\extension_binary\node-v83-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\riesbeck\workspace\javascript\react\mytest\node_modules\grpc\src\node\extension_binary\node-v83-win32-x64-unknown --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\riesbeck\workspace\javascript\react\mytest\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\riesbeck\\workspace\\javascript\\react\\mytest\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\Users\riesbeck\workspace\javascript\react\mytest\node_modules\grpc
node-pre-gyp ERR! node -v v14.15.4
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.24.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.24.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\riesbeck\AppData\Roaming\npm-cache\_logs\2021-01-08T21_00_17_570Z-debug.log

[15:00:17] npm exited with non-zero code: 1
[15:00:17] Error: npm exited with non-zero code: 1
    at ChildProcess.completionListener (C:\Users\riesbeck\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.cp.emit (C:\Users\riesbeck\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
    ...
    at Object.spawnAsync [as default] (C:\Users\riesbeck\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:26:19)
    at NpmPackageManager._runAsync (C:\Users\riesbeck\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\package-manager\src\NodePackageManagers.ts:157:31)
    at NpmPackageManager.addAsync (C:\Users\riesbeck\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\package-manager\src\NodePackageManagers.ts:100:18)
    at installAsync (C:\Users\riesbeck\AppData\Roaming\npm\node_modules\expo-cli\src\commands\install.ts:129:3)
    at Command.<anonymous> (C:\Users\riesbeck\AppData\Roaming\npm\node_modules\expo-cli\src\exp.ts:346:7)
```

## Reproducible Demo

Create a fresh Expo app, try to install Firebase with the Expo CLI. Note: this dumps many C compilation warnings dumped to foo.txt.

```
expo init mytest --template blank
cd mytest
expo install firebase > foo.txt
```

The following does NOT have an error. No compilation warnings appear either.

```
expo init mytest --template blank
cd mytest
npm install firebase
```

**Comment by nathanvogel** [comment]
I'm having the same issue, but doing `yarn add firebase@7.9.0`, which the version selected by Expo, also fails.
So to avoid this, two possibilities:
- either Expo updates to version ^8
- or we fix building firebase@7.9.0

(I'm having issues with Expo+Firebase 8, not sure if downgrading to 7.9.0 would fix it).

**Comment by nathanvogel** [comment]
Got it to work by downgrading to Node.js `10.16.0`!

**Comment by ashen780** [comment]
im also having the same problem.

**Comment by iqbalgithub1998** [comment]
I m trying to solve this problem for the last 2 days but no result

**Comment by criesbeck** [comment]
For me and some students, it worked to let **npm** install the current Firebase, rather than the version Expo wants to install.

**Comment by GeorgeStudio96** [comment]
I encountered the same problem .... Who knows the solution? use npm install firebase instead of expo install firebase ?

**Comment by Prashanth073-cloud** [comment]
Thank you @nathanvogel. I have been trying from two days. Your comment helped me.

**Comment by leoafarias** [comment]
Same issue, and resolved by just downloading the latest version of firebase. Is there a way the expo install command can be updated to skip this version?

**Comment by actionjacks** [comment]
> Got it to work by downgrading to Node.js `10.16.0`!

yep done and working

**Comment by jojenki** [comment]
Can we get a dev or project manager to weigh in and set expectations? This seems rather significant if Firebase is practically unusable in Expo. I say practically because downgrading to a version of Node that is nearly 3 years old and about to leave maintenance doesn't seem practical.

https://nodejs.org/en/about/releases/

**Comment by brentvatne** [comment]
@jojenki - we have bumped the supported firebase js version in sdk 41 but left things as-is in sdk 40. this is a result of changes in the ecosystem that have occurred since we released sdk 40, in particular the native dependency firebase@7.9.0 has on grpc and the interaction with that and certain node versions / development machine configurations.

related pr: https://github.com/expo/expo/pull/11692

you can install firebase@8.2.3 in your sdk 40 project and it will work as expected, but you will get a warning about it not being the suggested version.

**Comment by criesbeck** [comment]
Yes, installing firebase with npm rather than expo worked for me, except for the warning from Expo.

**Comment by jojenki** [comment]
Thanks for the quick response. I'm running into a related but separate error, it seems, so I'll open a separate issue for that.

**Comment by Ninx96** [comment]
> @jojenki - we have bumped the supported firebase js version in sdk 41 but left things as-is in sdk 40. this is a result of changes in the ecosystem that have occurred since we released sdk 40, in particular the native dependency firebase@7.9.0 has on grpc and the interaction with that and certain node versions / development machine configurations.
> 
> related pr: [expo/expo#11692](https://github.com/expo/expo/pull/11692)
> 
> you can install firebase@8.2.3 in your sdk 40 project and it will work as expected, but you will get a warning about it not being the suggested version.

works for me thanks you..

**Comment by LOTRAudition** [comment]
Some dependencies are incompatible with the installed expo package version:
 - firebase - expected version range: 8.2.3 - actual version installed: ^8.4.1

Firebase updated yet expo didn't? Why..
Running:
expo install firebase@8.2.3 
Worked for me but why downgrading pehh.

**Comment by brentvatne** [comment]
@LOTRAudition - you don't have to downgrade necessarily, if you want to just ignore the warning and the newer version works for you then it's fine. but we only test against the expected version, and it is not uncommon for new firebase js releases to break compatibility with react-native

**Comment by brentvatne** [comment]
expo sdk 41 tests against and recommends firebase@8.2.3, which resolves the original issue topic, so i'm closing this
