### ISSUE TITLE
Hot reload not working on iOS when running "npm run ios"

### ISSUE THREAD

**Issue by VonageBon** [expo/expo-cli#3068]
## Description

When running "npm run ios" on my CI server changes are not hot reloading.

Running the same locally the changes get picked up without any changes to the code or commands.

I do not see any errors anywhere and cannot find anything online which works

- Fast Refresh (Enabled) 
- Debug Remote JS (Disabled)
- Changes on the CI server get picked up by the web browser fine but the iOS Simulator app does not update
- If I open the shake menu and click "Reload" the changes do not show up either.

## Environment

```
expo diagnostics

  Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.19.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /Users/vagrant/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 15, 17, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
        Build Tools: 19.1.0, 21.1.2, 22.0.1, 23.0.3, 24.0.3, 25.0.3, 26.0.1, 26.0.2, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0
        System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
        Android NDK: 21.0.6113669
    IDEs:
      Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: managed
```

XCode 12.0 - iOS 14.1 Simulator

## Expected Behavior

Changes update automatically on iOS Simulator

## Observed Behavior

Changes do not update on iOS Simulator

## Reproducible Demo

https://github.com/damo1884/react-native-expo-hello-world

Note this is only happening on my CI server the reload works fine locally but I cannot find any reason why it is failing on the CI server

**Comment by brentvatne** [comment]
hi there,

i don't really know much about your ci server environment. you should look at your environment on your local machine and ci server and try to narrow down the problem. i imagine there may be an issue with the filesystem watcher, maybe try installing `watchman`

**Comment by EvanBacon** [comment]
I believe a CI server cannot be used with HMR since HMR requires local web sockets which are connected to the local development server.
