### ISSUE TITLE
Jest Module Not Found After Init (and then fails when installed)

### ISSUE THREAD

**Issue by cwbuecheler** [expo/expo-cli#307]
## Description

Expo-cli does not currently install Jest when you run its `init` feature, and even if you manually install Jest afterwards, the tests don't run properly.

## Expected Behavior

Jest should be correctly installed and work properly when the test script is run.

## Observed Behavior

When you use the latest version of Expo-cli and run `expo init [name]`, and choose the more robust option (with the example files and tabs), it correctly installs a bunch of stuff. However, if you then `cd` to your new directory and type `npm run test`, it attempts to run the Jest testing suite ... except the Jest testing suite hasn't been installed. `node_modules` shows a ton of Jest-related stuff, but not Jest itself.

If you manually run `npm i --save-dev jest` and then attempt to run `npm run test`, you get the following error:

```
FAIL  components/__tests__/StyledText-test.js
  ● Test suite failed to run

    /Users/chris/sites/temp/node_modules/react-native/jest/mockComponent.js: Unexpected token (20:23)

      Jest encountered an unexpected token
      This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
      By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
      Here's what you can do:
       • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
       • If you need a custom transformation specify a "transform" option in your config.
       • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
      You'll find more details and examples of these config options in the docs:
      https://jestjs.io/docs/en/configuration.html
      Details:
        18 |
        19 |   const Component = class extends SuperClass {
      > 20 |     static displayName = 'Component';
           |                        ^
        21 |
        22 |     render() {
        23 |       const name =
```

The same error occurs for `App-test.js`

**note:** It's possible this is due to Jest being unable to read the JavaScript-based babel configuration file that `expo init` generates.

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

```
  Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.6.2 - /usr/local/bin/zsh
    Binaries:
      Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
      npm: 6.5.0 - ~/.nvm/versions/node/v10.15.0/bin/npm
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.0
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.0.9 => 3.0.9
    npmGlobalPackages:
      expo-cli: 2.6.14
```

Also specify:

- Phone/emulator/simulator platform, model and version: *none. This is a command line issue.*

## Reproducible Demo

I've reproduced this on both OSX and Windows systems. You can reproduce this on any system by running the following commands:

`expo init temp`
`cd temp`
`npm run test`
("no Jest found" error)
`npm i --save-dev jest`
`npm run test`
(various test failure errors due to babel confusion)

**Comment by tcdavis** [comment]
Thanks for reporting and for testing on windows as well!

**Comment by janhesters** [comment]
Same error here on mac. Any progress on this?

**Comment by janhesters** [comment]
Update: Changing `package.json` to `"test": "node_modules/.bin/jest"` runs the tests, but they always fail.

```bash
 FAIL  __tests__/example-test.js
  ● Test suite failed to run

    /path/to/app/node_modules/react-native/jest/mockComponent.js: Unexpected token (20:23)

      Jest encountered an unexpected token
      This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
      By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
      Here's what you can do:
       • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
       • If you need a custom transformation specify a "transform" option in your config.
       • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
      You'll find more details and examples of these config options in the docs:
      https://jestjs.io/docs/en/configuration.html
      Details:
        18 | 
        19 |   const Component = class extends SuperClass {
      > 20 |     static displayName = 'Component';
           |                        ^
        21 | 
        22 |     render() {
        23 |       const name =

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.506s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

**Comment by mcglonelevi** [comment]
I am hitting the same issue on Linux.

**Comment by LuisMiguelFilipe** [comment]
@janhesters you need to add those files to your `transformIgnorePatterns` in `jest` config. 
That should do the trick

**Comment by EvanBacon** [comment]
This appears to be resolved in the latest, Expo SDK (not a CLI issue). If you encounter this issue in the future, please open an issue on [expo/expo](https://github.com/expo/expo/issues/new?assignees=&labels=needs+review%2CCLI&template=bug_report_cli.yml).
