### ISSUE TITLE
Expo Client app installation not working in iOS simulator

### ISSUE THREAD

**Issue by kjpradeep** [expo/expo-cli#3070]
OS : MACOS 11.1
Make : MacBook Pro
Chip: Apple M1
Simulator : iPhone 12 , iOS 14.3
expo-cli : 4.0.17
node : 4.15.4
rpm : 6.14.11
expo client : 2.17.4 and 2.18.2 tried

commands used

> sudo expo start
> shift + i ( for iOS simulator selection )
> i

no exceptions or errors . it only says 
**Opening on iOS...
Opening exp://127.0.0.1:19000 on iPhone 12**

I don't see any expo client app installed on the iOS simulator 
<img width="1312" alt="Screenshot 2021-01-10 at 3 52 19 PM" src="https://user-images.githubusercontent.com/37394212/104154401-d8e19280-540a-11eb-996f-15acedb1f40f.png">
<img width="707" alt="Screenshot 2021-01-10 at 3 53 05 PM" src="https://user-images.githubusercontent.com/37394212/104154406-dbdc8300-540a-11eb-93d0-051a3ca3cb9c.png">
<img width="370" alt="Screenshot 2021-01-11 at 10 13 01 AM" src="https://user-images.githubusercontent.com/37394212/104154410-dc751980-540a-11eb-8852-fd79c85b3ff8.png">
<img width="782" alt="Screenshot 2021-01-11 at 12 04 48 PM" src="https://user-images.githubusercontent.com/37394212/104154411-dd0db000-540a-11eb-8e79-775179bdd561.png">
<img width="1254" alt="Screenshot 2021-01-11 at 12 18 17 PM" src="https://user-images.githubusercontent.com/37394212/104154414-dda64680-540a-11eb-976f-d7342a13684f.png">
![Simulator Screen Shot - iPhone 8 - 2021-01-10 at 16 56 05](https://user-images.githubusercontent.com/37394212/104154416-dda64680-540a-11eb-883d-3691d3936407.png)

**Comment by brentvatne** [comment]
close all of your simulators. press i. tell me what happens

**Comment by kjpradeep** [comment]
No change same thing. the simulator opens .. but no expo client .. no app opening
https://user-images.githubusercontent.com/37394212/104156724-b605ad00-540f-11eb-8505-d1fbcf61af3d.mp4

**Comment by kjpradeep** [comment]
I have checked the live logs for iPhone Simulator and there are no entries in it when it is trying to open the expo app in iPhone 12. So, I doubt the Terminal in VS code is able to open Simulator but unable to communicate with it and publish app onto it.

**Comment by kjpradeep** [comment]
some folder or file or automation permissions at Mac OS level might be the root cause .. but I at least expect some logs and exceptions to get the root cause and later fix it.

**Comment by kjpradeep** [comment]
Okay … i got a work around.

The solution was to
```

    sudo chmod -R 777 ~/.expo/

    sudo rm -rf ~/.expo

    npm start

```
( without sudo )

i think the rot cause was i installed expo-cli with root / sudo . And hence all the folder permissions issues. after npm start , i could see the expo app installed on the ios simulator and happy days are back. Now the app is working fine on the ios Simulator.

**Comment by kjpradeep** [comment]
But i feel there should be some permissions or folder privilege isues should be shown .. without that i was clueless on the root-cause of the issue.

**Comment by jsamr** [comment]
@kjpradeep Are you using Rosetta? When I try to install the client on the simulator (Silicon), it fails (see #3080). Would love to have some additional information on your setup.

**Comment by EvanBacon** [comment]
Unfortunately there isn't much we can do when the CLI is installed with sudo. Please uninstall it and reinstall without sudo.

**Comment by HPaulson** [comment]
Worked for me! Thanks.

**Comment by joeydotdev** [comment]
> Okay … i got a work around.
> 
> The solution was to
> 
> ```
> 
>     sudo chmod -R 777 ~/.expo/
> 
>     sudo rm -rf ~/.expo
> 
>     npm start
> ```
> 
> ( without sudo )
> 
> i think the rot cause was i installed expo-cli with root / sudo . And hence all the folder permissions issues. after npm start , i could see the expo app installed on the ios simulator and happy days are back. Now the app is working fine on the ios Simulator.

confirmed to work on my m1 machine as well

**Comment by Kumar2106** [comment]
> > Okay … i got a work around.
> > The solution was to
> > ```
> > 
> >     sudo chmod -R 777 ~/.expo/
> > 
> >     sudo rm -rf ~/.expo
> > 
> >     npm start
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ( without sudo )
> > i think the rot cause was i installed expo-cli with root / sudo . And hence all the folder permissions issues. after npm start , i could see the expo app installed on the ios simulator and happy days are back. Now the app is working fine on the ios Simulator.
> 
> confirmed to work on my m1 machine as well

I having the same problem but the solution by you did not worked for me.

**Comment by lifeeric** [comment]
**Workaround**

We had installed expo-cli with root permission (sudo), that's the problem. first check if you had installed with npm or yarn
**for NPM:**
```npm list -g --depth 0```

if you see `expo-cli` there remove it:
```
sudo npm uninstall -g expo-cli
sudo rm -rf ~/.expo

npm install --global expo-cli

```
**FOR Yarn**
```
yarn global list
yarn remove global expo-cli
sudo rm -rf ~/.expo

yarn add global expo-cli
```

if you see permission issue 
```
EACCES: permission denied, open 
```

run this command:
```
sudo chmod -R 777 .expo
```

now run it

**Comment by Maykonctba** [comment]
> 

Tks bro my Hero kakakakakakaka
it is resolve my problems 
tks
Have a nyce day.
