### ISSUE TITLE
Unable to generate android build for existing package 

### ISSUE THREAD

**Issue by varora1406** [expo/expo-cli#3073]
## Description

Error generating regarding key alias, when I run command `expo build:android`
Note: I have used this key store information to make package in pwabuilder and publish it in playstore as well. It's just not happening with expo tool

## Environment

  Expo CLI 4.0.16 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 15.0.1 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.10 - D:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2
        System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    npmPackages:
      expo: ~40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

## Expected Behavior

Action performed - `expo build:android`
Expectation - Build android package as requested

## Observed Behavior

```
Accessing credentials for ______ in project _____________________
√ Would you like to upload a Keystore or have us generate one for you?
If you don't know what this means, let us generate it! :) » I want to upload my own file

WARNING! In this mode, we won't be able to make sure that your credentials are valid.
Please double check that you're uploading valid files for your app otherwise you may encounter strange errors!

When building for IOS make sure you've created your App ID on the Apple Developer Portal, that your App ID
is in app.json as `bundleIdentifier`, and that the provisioning profile you
upload matches that Team ID and App ID.

√ Path to the Keystore file. ... ____________________________________________________\signing.keystore
√ Keystore password ... ************
? Key alias » ---------------
√ Key alias ...
√ Key password ... ************
An error occurred when validating the Android keystore: keytool error: java.lang.Exception: Alias <> does not exist

Make sure that you provided correct credentials in 'credentials.json' and the path provided under 'keystorePath' points to a valid keystore file.
Error: An error occurred when validating the Android keystore: keytool error: java.lang.Exception: Alias <> does not exist

Make sure that you provided correct credentials in 'credentials.json' and the path provided under 'keystorePath' points to a valid keystore file.
    at validateKeystoreAsync (C:\Users\varor\AppData\Roaming\npm\node_modules\expo-cli\src\credentials\utils\validateKeystore.ts:42:11)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at UpdateKeystore.open (C:\Users\varor\AppData\Roaming\npm\node_modules\expo-cli\src\credentials\views\AndroidKeystore.ts:44:7)
    at CredentialsManager.run (C:\Users\varor\AppData\Roaming\npm\node_modules\expo-cli\src\credentials\route.ts:41:12)
    at runCredentialsManager (C:\Users\varor\AppData\Roaming\npm\node_modules\expo-cli\src\credentials\route.ts:12:10)
    at AndroidBuilder.collectAndValidateCredentials (C:\Users\varor\AppData\Roaming\npm\node_modules\expo-cli\src\commands\build\AndroidBuilder.ts:88:7)
    at AndroidBuilder.run (C:\Users\varor\AppData\Roaming\npm\node_modules\expo-cli\src\commands\build\AndroidBuilder.ts:33:5)
    at AndroidBuilder.command (C:\Users\varor\AppData\Roaming\npm\node_modules\expo-cli\src\commands\build\BaseBuilder.ts:40:7)
    at Command.<anonymous> (C:\Users\varor\AppData\Roaming\npm\node_modules\expo-cli\src\exp.ts:346:7)
```

**Comment by srborines** [comment]
Hi!
I have been able to use my own the Keystore pressing enter when the prompt ask for Key alias and then writing the Key alias.

What I was doing at the beginning was writing the Key alias and then pressing enter twice but as I said, pressing enter, then the key and then enter again it worked for me.

I hope it helps!

**Comment by varora1406** [comment]
no longer looking at it, so closing this bug

**Comment by MichaelKim39** [comment]
Surely expo should update the credentials manager or add a warning for this bug? Still requires a change to the manager as users are not sure when to press enter and why this issue is happening.

**Comment by mohammedaminelahmami** [comment]
write key alias twice

**Comment by anasalaqeel** [comment]
its 2022 and still not fixed, why should I write the alias twice?
