### ISSUE TITLE
expo client:install:ios fails on Apple Silicon Mac

### ISSUE THREAD

**Issue by jsamr** [expo/expo-cli#3080]
## Description

Running 
```sh
expo client:install:ios
```
on an Apple Silicon mac fails.

## Environment

OS : MACOS 11.1
Make : MacBook Pro
Chip: Apple M1
Simulator : iPhone 11 , iOS 14.3 (Apple Silicon)
expo-cli : 4.0.17 and 4.0.18 (Apple Silicon)
node : 15.5.1 (Apple Silicon)
npm : 7.3.0 (Apple Silicon)
expo client : 2.18.2 | 2.17.4 | 2.15.4

## Expected Behavior

The install process succeeds. 

## Observed Behavior

The install process fails. 

```
\zsh: file size limit exceeded  expo client:install:ios==============================================                ] 75% 19.0s
```
while there is plenty of space available on the disk.

## Reproducible Demo

You need an Apple Silicon Macintosh, install node with brew and expo-cli with npm.

## Related issues

Looks a lot like #3070, but unrelated. The workaround involving file permissions does not apply here, since in my setup, the .expo folder does indeed belong to the logged user.

**Comment by jsamr** [comment]
The issue I had was that the default shell (zsh) had a file size limit set for reasons I haven't managed to unfold. To check if that is the case, type this command in a shell:

```sh
ulimit -f
```

If it doesn't print "unlimited", then you have a size limit set. To override this limit, type:
```sh
ulimit -f unlimited
```

**Comment by brentvatne** [comment]
odd. perhaps we could handle this error and warn. pr would be welcome to add a better experience around it!
