### ISSUE TITLE
expo ca-bundle.crt is not expired, yet continuing to get 'unable to get local issuer certificate' error 

### ISSUE THREAD

**Issue by mercale** [expo/expo-cli#3086]
## Description
First time with React Native using expo-cli. I was able to install expo-cli however I couldn't get pass ```expo init```  due to the certificate issue.
```
request to https://registry.npmjs.org/expo-template-blank failed, reason: unable to get local issuer certificate
```

## Environment
 Expo CLI 4.0.17 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Expo Workflow: managed

## Expected Behavior
Should be able to create a new project using ``` expo init ``` with blank template 

## Observed Behavior

Other test done  
CURL Test seems to work fine, no certificate blocking observed
```
>curl https://registry.npmjs.org/expo-template-blank -o blank-template
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  101k  100  101k    0     0   101k      0  0:00:01 --:--:--  0:00:01  196k
```

Browser test also seemed fine, no certificate blocking occurred

It seems that the error only appears with ```expo ``` even though ca-bundle.crt is not expired.
I've verified the ca-bundle.crt is not expired, see result below :
```
>openssl x509 -enddate -noout -in ca-bundle.crt
notAfter=Jan 28 12:00:00 2028 GMT
```
 

## Reproducible Demo
expo init testproj
√ Choose a template: » blank                 a minimal app as clean as an empty canvas
request to https://registry.npmjs.org/expo-template-blank failed, reason: unable to get local issuer certificate
FetchError: request to https://registry.npmjs.org/expo-template-blank failed, reason: unable to get local issuer certificate
    at ClientRequest.<anonymous> (C:\Users\mercale\AppData\Roaming\npm\node_modules\expo-cli\node_modules\minipass-fetch\lib\index.js:97:14)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:327:22)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by brentvatne** [comment]
can you try this and let me know if it works?

```
npm install expo-template-blank
```

**Comment by mercale** [comment]
npm install expo-template-blank, this went through successfully. I can see bunch of node_modules packages there now.

**Comment by brentvatne** [comment]
it seems like this might be caused by your proxy config, a suggested solution on stackoverflow is to change your npm registry to use http instead of https https://stackoverflow.com/a/45884819/659988

we probably need to expose a way to configure fetch requests from expo-cli to use your proxy

**Comment by mercale** [comment]
so setting my npm registry to http didn't work
here is the snapshot
```
; userconfig C:\Users\mercale\.npmrc
cafile = "c:\\users\\mercale\\zscaler-curl-bundle.pem"
registry = "http://registry.npmjs.org/"

; globalconfig C:\Users\mercale\AppData\Roaming\npm\etc\npmrc

; builtin config undefined
prefix = "C:\\Users\\mercale\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\mercale\reactnative
; HOME = C:\Users\mercale
; "npm config ls -l" to show all defaults.


C:\Users\mercale\reactnative>expo init Done
√ Choose a template: » blank                 a minimal app as clean as an empty canvas
request to https://registry.npmjs.org/expo-template-blank failed, reason: unable to get local issuer certificate
FetchError: request to https://registry.npmjs.org/expo-template-blank failed, reason: unable to get local issuer certificate
    at ClientRequest.<anonymous> (C:\Users\mercale\AppData\Roaming\npm\node_modules\expo-cli\node_modules\minipass-fetch\lib\index.js:97:14)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:327:22)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

```

**Comment by mercale** [comment]
Any other work around? 
I was hoping I could do a presentation of this library next week to my team.

**Comment by brentvatne** [comment]
you could do: `npx create-react-native-app -t blank` as an alternative - this will use github instead of npm

it looks like we should be pointing to the npmrc configured cafile when making network requests. if someone would like to contribute an improvement for this it would be much appreciated

**Comment by mercale** [comment]
Hey there, failing with -t blank arg, 
```
$ npx create-react-native-app -t blank
npx: installed 1 in 8.825s
√ What is your app named? ... expotrial
✖ Could not locate the template named "blank". 
```
I removed the -t blank arg it seemed to default to blank anyway  and was successful. Our team can continue exploring this tool (we like what we are discovering so far). One question,  can you explain the difference for using 
using npx crna over expo init?

**Comment by brentvatne** [comment]
interesting...

```
╰─$ npx crna -t blank
npx: installed 1 in 0.663s
npx: installed 1 in 0.668s
✔ What is your app named? … brent
✔ Downloaded and extracted project files.

🧶 Using Yarn to install packages. You can pass --use-npm to use npm instead.

✔ Installed JavaScript dependencies.

✅ Your project is ready!

To run your project, navigate to the directory and run one of the following yarn commands.

- cd brent
- yarn android
- yarn ios
- yarn web
```

it seems like there is maybe also an issue using git to init from a template.

`create-react-native-app` gives you a "bare" react-native app by default (see this [comparison of managed and bare workflow](https://docs.expo.io/introduction/managed-vs-bare/) for more info) and has an option to choose a template from this list of community supported examples that integrate with third party libraries and services: http://github.com/expo/examples 

`expo-cli` only includes a small set of focused templates (blank, typescript, and navigation) with first-party code written and maintained by expo

**Comment by mercale** [comment]
Yes interesting, not sure why it wouldn't work with single dash t like you demoed but it does work with double dash t for me, see below, 

**Single dash t ```-t```, throws an error** × 
C:\Users\mercale\expo>npx create-react-native-app -t blank
npx: installed 1 in 3.832s
√ What is your app named? ... npxcratblank
× Could not locate the template named "blank".

**With double dash t ```--t```, it works**  √
C:\Users\mercale\expo>npx create-react-native-app --t blank
npx: installed 1 in 4.167s
√ What is your app named? ... crnatblank
√ How would you like to start » Default new app
√ Downloaded and extracted project files.

🧶 Using Yarn to install packages. You can pass --use-npm to use npm instead.

√ Installed JavaScript dependencies.
√ Skipped installing CocoaPods because operating system is not on macOS.

✅ Your project is ready!

To run your project, navigate to the directory and run one of the following yarn commands.

- cd crnatblank
- yarn android
- yarn ios # you need to use macOS to build the iOS project - use the Expo app if you need to do iOS development without a Mac
- yarn web

**Comment by mercale** [comment]
The ```npx crna``` command didn't work for me , here's the screen shots for all three approaches. It isn't a show stopper for me as the ```npx create-react-native-app``` one works for me , but I thought I'd let you know.

**$ npx crna**
C:\Users\mercale\expo>npx crna
npx: installed 1 in 4.425s
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn npx ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn npx',
  path: 'npx',
  spawnargs: [ 'create-react-native-app' ]
}

**npx crna -t blank**
C:\Users\mercale\expo\crnatblank>npx crna -t blank
npx: installed 1 in 4.551s
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn npx ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn npx',
  path: 'npx',
  spawnargs: [ 'create-react-native-app', '-t', 'blank' ]
}

**npx crna --t blank**
C:\Users\mercale\expo\crnatblank>npx crna --t blank
npx: installed 1 in 5.109s
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn npx ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn npx',
  path: 'npx',
  spawnargs: [ 'create-react-native-app', '--t', 'blank' ]
}

### Environment Info
```
 Expo CLI 4.1.3 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.3
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare
```

**Comment by viplavkallam** [comment]
I got same issue. It's asking for issuer certificate while I use any expo (like upgrade) or Yarn commands . Not sure. It's asking local issuer certificate. On another laptop it's working fine.
