### ISSUE TITLE
Expo SDk 40 breaks React Navigation's Material Bottom Tabs

### ISSUE THREAD

**Issue by TheChicken14** [expo/expo-cli#3090]
## Description

Hi everyone, after update my Expo SDK from version 39 to version 40, I keep getting an error when bundling.

I've tried everything I've found that should fix this problem:
- remove `node_modules` and `yarn.lock` and run `yarn`
- updating `@babel/core`
- updating other packages such as `@react-navigation/native` and `react-native-paper`

## Environment
```
  Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.13.0 - ~/.nvm/versions/node/v14.13.0/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.7/11E801a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed
```

I'm running it on my Motorola Moto g8 Plus

## Expected Behavior

I expect it to package like it did before updating to SDK 40

## Observed Behavior

When bundling I get this error:

```
Failed building JavaScript bundle.
SyntaxError: ./node_modules/@react-navigation/material-bottom-tabs/src/index.tsx: Unexpected token (14:12)

  12 |  * Types
  13 |  */
> 14 | export type {
     |             ^
  15 |   MaterialBottomTabNavigationOptions,
  16 |   MaterialBottomTabNavigationProp,
  17 |   MaterialBottomTabScreenProps,
```

## Reproducible Demo

The only thing that changed was my Expo SDK version and I couldn't find any other issues relating to this.

**Comment by SirPhemmiey** [comment]
@TheChicken14 i had this same problem for about 1 week and later discovered that expo-cli 4 doesn't work with expo sdk40 when you have @react-navigation/<package-name> installed.

**Comment by brentvatne** [comment]
@TheChicken14 

here's my attempt to reproduce: https://github.com/brentvatne/cli-3090

worked as expected. happy to reopen if you can provide a reproducible example

<hr />

@SirPhemmiey 

> i had this same problem for about 1 week and later discovered that expo-cli 4 doesn't work with expo sdk40 when you have @react-navigation/ installed. You have to downgrade your cli version

this is certainly incorrect. you can initialize a new tabs project with `expo init` to verify. you should always use the latest expo-cli version.

**Comment by SirPhemmiey** [comment]
Well, it didn't work for me. Maybe because I'm using it in a monorepo, but I don't think that matters. So yeah, I downgraded to expo cli 3

**Comment by brentvatne** [comment]
@SirPhemmiey - many people use expo-cli@4 and react navigation 5+ in a monorepo context, including me on several apps (and the http://github.com/expo/expo repo too). i'm happy to dig into this issue more if someone can provide information on how to reproduce.

**Comment by TheChicken14** [comment]
Hi, I "fixed" it by just downgrading back to SDK 39, so there's no need to reopen for me. Thanks though :)

**Comment by SirPhemmiey** [comment]
Ah okay, you'd still need to eventually upgrade though :)

**Comment by brentvatne** [comment]
yeah - again i'm happy to help if i can reproduce this!

**Comment by adanielyan** [comment]
Have the same issue. Upgraded from 39 to 40 and bottom tabs stopped working. It seems the tabs are overlapping each other, because I have a text input in one of the tabs and I can see the keyboard comes up when I switch to that tab, but nothing else changes on the screen (the tab with the text input is not displayed).
