### ISSUE TITLE
Allow overriding publicPath in development for the web

### ISSUE THREAD

**Issue by d4rky-pl** [expo/expo-cli#3092]
Currently the `@expo/webpack-config` detects that we're in development mode and hard-overrides the `publicPath` to be `/`. The note in [packages/webpack-config/src/env/paths.ts](https://github.com/expo/expo-cli/blob/master/packages/webpack-config/src/env/paths.ts) says _"In development, we always serve from the root. This makes config easier."_ without elaborating further what it means or what the hidden complexity is.

**Our use case:** we have several mixed web/native apps that can be ran on one machine at the same time during development. 

Currently we're handling that by assigning ports for every app and configuring our backend to support that. In production we have one frontend server with the apps deployed in subdirectories (so for ex. `app.foo/bar`, `app.foo/baz` etc.). It would've been much easier for us to handle this, onboard new developers and explain to everyone not managing the infrastructure how and where they can find the apps and launch them properly if we could have a similar setup in dev. The only missing part is being able to run the app in development under a subdirectory.

**Comment by conzett** [comment]
Ran into this recently myself. I expected setting `WEB_PUBLIC_PATH` to work the same way in development mode as production.

**Comment by d4rky-pl** [comment]
bump

**Comment by hadron-mhchu** [comment]
I'm also facing the same situation where a dev app needs to be in a directory when deployed to a dev server, but cannot because of this hard coded `/`

**Comment by d4rky-pl** [comment]
bump...

**Comment by d4rky-pl** [comment]
I'm going to bump this one more time, if it's still ignored and autobotted afterwards I'll just patch-package it in our projects.
It would be great to at least know the reason for this decision though.

**Comment by EvanBacon** [comment]
@d4rky-pl I don't have any time to work on this feature, you're welcome to open a PR if you'd like. Generally, there should be no constraints preventing this feature from being added.

**Comment by d4rky-pl** [comment]
When I have time to look into this I'll send a PR, for now I'll close the issue
