### ISSUE TITLE
Cannot run EXPO after update

### ISSUE THREAD

**Issue by gabox8888** [expo/expo-cli#310]
After updating to expo 32 and expo-cli 16.4.1 I cannot run expo start i get the following errors

[23:17:18] Warning: Problem validating app.json: Unable to perform cache refresh for C:\Users\gabri\AppData\Local\Expo\schema-undefined.json: Error: Request failed with status code 404.
[23:17:19] Error: Invalid sdkVersion. Valid options are 10.0.0, 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0, 16.0.0, 17.0.0, 18.0.0, 19.0.0, 20.0.0, 21.0.0, 22.0.0, 23.0.0, 24.0.0, 25.0.0, 26.0.0, 27.0.0, 28.0.0, 29.0.0, 30.0.0, 31.0.0, 32.0.0, 7.0.0, 8.0.0, 9.0.0

[23:17:25] wrapItem(...).trimStart is not a function
[23:17:25] TypeError: wrapItem(...).trimStart is not a function

App.json has the correct version as well as project.json and i have reinstalled node_modules several times

**Comment by tcdavis** [comment]
Can you post your app.json and package.json?

**Comment by tcdavis** [comment]
Also what shell are you using and what versions of node?

**Comment by gabox8888** [comment]
App.json
```
{
  "expo": {
    "expo": "32.0.0",
    "react": "16.5.0"
  }
}
```

package.json
```
{
  "name": "reverie-mobile",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-15": "^1.0.6",
    "enzyme-adapter-react-16": "^1.1.1",
    "jest": "22.2.2",
    "jest-enzyme": "^6.0.2",
    "jest-expo": "^28.0.0",
    "react-native-scripts": "^2.0.1",
    "react-test-renderer": "16.2.0"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "expo start",
    "eject": "expo eject",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo",
    "setupFiles": [
      "./config/setupTests.js"
    ]
  },
  "dependencies": {
    "expo": "^32.0.1",
    "jsdom": "^11.11.0",
    "react": "^16.4.1",
    "react-bootstrap": "^0.32.1",
    "react-dom": "^16.4.1",
    "react-native": "0.52.0",
    "react-native-elements": "^0.19.1",
    "react-native-paper": "^1.11.1",
    "react-native-ui-kitten": "akveo/react-native-ui-kitten",
    "react-native-vector-icons": "^4.5.0",
    "react-navigation": "^3.0.8",
    "react-redux": "^6.0.0",
    "redux": "^4.0.1",
    "redux-actions": "^2.3.0",
    "redux-promise": "^0.6.0",
    "yarn": "^1.8.0"
  }
}
```

Updating to Node 10.15 got rid of the type error and it does not crash but I still cannot run the app as i get the sdkVersion error

**Comment by gabox8888** [comment]
Running on win10

**Comment by tcdavis** [comment]
🙏 The keys you have under expo in your app.json aren't right https://docs.expo.io/versions/latest/workflow/configuration
