### ISSUE TITLE
[webpack-config] Can't set workbox.useServiceWorker to false

### ISSUE THREAD

**Issue by zecakeh** [expo/expo-cli#3102]
## Description

I we set the `workbox.useServiceWorker` option to false in webpack-config's function, an error occurs at build time, making it unusable.

## Environment

Expo CLI 4.0.17 environment info:
  System:
    OS: Linux 5.10 Manjaro Linux
    Shell: 5.1.0 - /bin/bash
  Binaries:
    Node: 15.4.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.9 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
  npmPackages:
    @expo/webpack-config: ^0.12.53 => 0.12.53 
    react: 16.13.1 => 16.13.1 
    react-dom: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-web: ~0.14.0 => 0.14.10 
  npmGlobalPackages:
    expo-cli: 4.0.17
  Expo Workflow: bare

## Expected Behavior

When I set `workbox.useServiceWorker` option to `false` in `argv`, the script should call Workbox's InjectManifest.

## Observed Behavior

An error occurs at build time:

```bash
Failed to compile.

"navigateFallback" is not a supported parameter.
Error: "navigateFallback" is not a supported parameter.
    at /@expo/xdl@59.0.14/src/Webpack.ts:280:23
    at finalCallback (/usr/lib/node_modules/expo-cli/node_modules/webpack/lib/Compiler.js:257:39)
    at /usr/lib/node_modules/expo-cli/node_modules/webpack/lib/Compiler.js:279:21
    at /usr/lib/node_modules/expo-cli/node_modules/webpack/lib/Compiler.js:492:20
    at eval (eval at create (/usr/lib/node_modules/expo-cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:53:1)
```

This is an error in `@expo/webpack-cli` at [`withWorkbox.ts#L158`](https://github.com/expo/expo-cli/blob/6065d5f717917637bb7364dc5d04cbddc7e91e47/packages/webpack-config/src/addons/withWorkbox.ts#L158). A `customManifestProps` object that includes a `navigateFallback` is passed although it is not a parameter of `InjectManifest`.

## Reproducible Demo

1. [Create a new app](https://docs.expo.io/get-started/create-a-new-app/)
2. [Add web support](https://docs.expo.io/guides/running-in-the-browser/#adding-web-support-to-expo-projects)
3. [Enable Service Workers](https://github.com/expo/fyi/blob/master/enabling-web-service-workers.md)
4. Create a `service-worker.js` file in web
5. Modify `webpack.config.js` like this:
  ```javascript
  const createExpoWebpackConfigAsync = require("@expo/webpack-config");

module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync(
    {
      ...env,
      offline: true,
    },
    {
      ...argv,
      workbox: {
        useServiceWorker: false,
        injectManifestOptions: {
          swSrc: "service-worker.js",
        },
      },
    }
  );
  return config;
};
```
6. `expo build:web`

**Comment by EvanBacon** [comment]
I'd recommend just installing workbox into your project and adding a custom config that way. I'll be pulling workbox out of webpack-config since users need to change versions and have more control over the entire plugin.

**Comment by EvanBacon** [comment]
Resolved in https://github.com/expo/expo-cli/pull/3729
