### ISSUE TITLE
Add a way to publish project as a snack

### ISSUE THREAD

**Issue by HeIp** [expo/expo-cli#3105]
Instead of publishing a project as a project, should be able to published to the website as a snack.

**Comment by brentvatne** [comment]
this would be nice to have, but unfortunately it is not that easy and not something that we plan on working on right now. snack operates slightly differently than projects run through expo-cli, and so we can't guarantee that the exact same code in every case will work on snack even if it runs locally. we want to get rid of this discrepancy in the future, but it's not something we can do without a lot of reworking of snack.

you can try your luck with importing it from git using this option screenshotted below:

![Screen Shot 2021-01-20 at 6 45 27 PM](https://user-images.githubusercontent.com/90494/105273199-ac86ee00-5b4f-11eb-8ca3-0f49d274a246.png)

if you'd like to create a feature request to track this, you can do it here: https://expo.canny.io/feature-requests

**Comment by HeIp** [comment]
Instructions for important git repo not clear. Fails every time I try.
Instructions needed.

**Comment by brentvatne** [comment]
it should point to a repository that has an expo app in the root of it. if it's not in the root, you can expand advanced options and point it to the root
