### ISSUE TITLE
Device logging support for bare apps

### ISSUE THREAD

**Issue by fson** [expo/expo-cli#3106]
Currently when running a bare app with `expo start --dev-client`, `console.log()` and other device logs are not printed to the terminal and Expo Dev Tools. This is because the `RemoteLogging` runtime in the `expo` package is only included for managed apps (`Expo.fx.expo.tsx`, module with side-effects for managed apps, [imports `environment/logging.fx`](https://github.com/expo/expo/blob/fab688aaa38c370b54bcd04a54bb53b1009480b8/packages/expo/src/Expo.fx.expo.tsx#L2)
, which [enables logging](https://github.com/expo/expo/blob/fab688aaa38c370b54bcd04a54bb53b1009480b8/packages/expo/src/environment/logging.fx.ts#L6-L16)).

It would be ideal to use the same device logging implementation for both managed and bare apps. There are two possible implementations to consider:
- [`RemoteLogging`](https://github.com/expo/expo/blob/fab688aaa38c370b54bcd04a54bb53b1009480b8/packages/expo/src/logs/RemoteLogging.ts) and [`RemoteConsole`](https://github.com/expo/expo/blob/fab688aaa38c370b54bcd04a54bb53b1009480b8/packages/expo/src/logs/RemoteConsole.ts) in the Expo SDK
  * sends logs to the `/logs` endpoint of Expo CLI's dev server batched a HTTP POST requests
  * currently used for managed apps in Expo CLI
- [`HMRClient` in React Native](https://github.com/facebook/react-native/blob/9b1f3b16b0675622b9bc663a143509f0c2d1a1b7/Libraries/Utilities/HMRClient.js#L108-L140)
  *  sends `client_log` events to the WebSocket server
  * used by default `TerminalReporter` in Metro
  * currently ignored in Expo CLI to avoid printing logs twice, because we use the logging method above

**Comment by brentvatne** [comment]
we've added basic support for this right now with these commits:

- https://github.com/expo/expo/commit/98bb5ce511741d7db4d20c275764ac45aa7a709f
- https://github.com/expo/expo/commit/7aaad50827491ffd5e4c7f9b3c6850ca7c77c1d4

so let' repurpose this issue to tracking your investigation/implementation of the idea of moving away from our `RemoteLogging` to possibly consolidate on the built-in logging

**Comment by fson** [comment]
Does the above implementation require that  the `Expo.fx.ts` module from the `expo` package is imported? How do we ensure this happens in bare apps?

**Comment by brentvatne** [comment]
yeah. it happens by default in bare apps via registerRootComponent

**Comment by EvanBacon** [comment]
This is complete
