### ISSUE TITLE
Add expo:version command

### ISSUE THREAD

**Issue by giacomocerquone** [expo/expo-cli#3111]
Hi, this is an idea to enhance the expo cli!
I'd like to have a command similar to `npm version minor` etc. but for expo.

Of course I'd also imagine commands like: `expo:version minor` or `expo:version buildNumber --increase` or a similar syntax
Do you think this could be a good idea? If not, why?

**Comment by byCedric** [comment]
Hi! I created the [`standard-version-expo`](https://github.com/expo-community/standard-version-expo) plugin for standard-version, but haven't updated this for a while. I'd love to have a native version of this, just to make this easier. But I do think it's a bit more complex than just `expo:version minor`.

Basically, we have 4 different types of "version".
1. `package.json`'s version (not necessarily important)
2. app manifest `expo.version`
3. app manifest `expo.ios.buildNumber`
4. app manifest `expo.android.versionCode`

Now, to make things even better, we also can't use semver for each of these. `expo.android.versionCode` requires an `int` type of version, while the others can be semver. Now, there are some approaches to this (like [Maxi Rosson's approach](https://medium.com/@maxirosson/versioning-android-apps-d6ec171cfd82))

I think it's good to think of a concept of dealing with these differences, approaches, and limitations. But I'm happy to think along 😄

**Comment by giacomocerquone** [comment]
@byCedric yes, I opened this issue exactly to discuss that, knowing that we couldn't use semver for everything (and of course to discuss with the product owners if they'd like to have such a feature in the cli).
In my apps I do use sometime a similar approach of the one you linked and as far as I'm concerned , I wouldn't necessarily "link" expo.version with the versioncode and build number, but I do see that it's a very handy thing to have.

Looking at your package, I can see android/increment as well as ios/increment, so I propose this:

```
expo:version major/minor/patch
expo:version manifest major/minor/patch
expo:version ios increment/1.0.0 (or whatever)
expo:version android increment/101010 (or whatever)
```

The first command (let's say expo:version patch) would apply:

expo.version = 0.0.1
expo.android.versionCode = (maxi rosson's or a simpler one like the following) 000001
expo.ios.buildNumber = 0.0.1

**Comment by giacomocerquone** [comment]
An alternative to Rosson's post, could be for example to remove screen-sizes third number and place it at the end of the int.
For example if we have 1.0.0-rc1, then the versionCode would be 01000021.

Those two numbers would be generated from something like this:

0 - alpha
1 - beta
2 - rc

following the rc number.

**Comment by brentvatne** [comment]
we don't want to increase the scope of expo-cli to handle this, but we are working on supporting autoincrement versions in eas build :)

this would work well as another cli tool. also check out http://increment.build/

**Comment by giacomocerquone** [comment]
@brentvatne ok, your decision here but if you plan to provide an autoincrement functionality I think it would be worth implementing a manual version handling through the expo-cli.

I'll close the issue then.
Thank you very much!

**Comment by brentvatne** [comment]
@giacomocerquone - we've considered that, but with eas-cli it would basically do the following:

1) increase the version in app.json
2) run `eas build:configure`

so it may not be particularly useful
