### ISSUE TITLE
`expo eject` not working with Expo 40

### ISSUE THREAD

**Issue by Nostrus** [expo/expo-cli#3116]
## Description

I recently upgraded from Expo 38 to 40, and then tried to do an eject. It needed some extra Gradle configuration (because of memory issues mainly). Managed to get it running eventually, but my previously working app crashed immediately on startup. 

So I reverted all changes, tried again, at one point reinstalled `node_modules`, and couldn't get `expo eject` working anymore. 

## Environment

```
  Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.7.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.11 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 27, 28, 29
        Build Tools: 28.0.3, 29.0.2
        System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: bare
```

## Expected Behavior

App working after `expo eject`.

## Observed Behavior

App crashes immediately on startup or `expo eject` breaks. 

It fails at the `iOS config syncing` step with the below error:

```
/usr/local/lib/node_modules/expo-cli/node_modules/@expo/configure-splash-screen/src/ios/pbxproj.ts:45
        throw new Error(`.pbxproj file parsing issue: ${err.message}.`);
              ^
Error: .pbxproj file parsing issue: undefined.
    at pbxProject.<anonymous> (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/configure-splash-screen/src/ios/pbxproj.ts:45:15)
    at pbxProject.emit (events.js:314:20)
    at pbxProject.<anonymous> (/usr/local/lib/node_modules/expo-cli/node_modules/xcode/lib/pbxProject.js:45:18)
    at ChildProcess.emit (events.js:314:20)
    at emit (internal/child_process.js:906:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

I tried removing splash screen settings from `app.json` to avoid syncing the config, but then I got a weird `Could not locate a valid AppDelegate at root` error.

According to this comment the above package is not supported in Expo 40, not sure why, and what the workaround would be: https://github.com/expo/expo-cli/issues/2801#issuecomment-739887752

**Comment by byCedric** [comment]
Hi @Nostrus, thanks for the report. It looks like your `ios/*` files got malformed somehow. Did you try either fully remove both `ios` and `android` folders before ejecting again? And if so, could you open the project in XCode?

**Comment by brentvatne** [comment]
happy to investigate further if you can provide more information to help us understand the specific problem that you're encountering!

**Comment by Charioteer** [comment]
Hi @brentvatne, @byCedric amd @Nostrus!

I've just encountered the exact same issue while using `expo eject`. I've create a React Native app by following the steps described in React Native's documentation [here](https://reactnative.dev/docs/environment-setup) (Expo CLI Quickstart).

To test my initial setup I've started the app with `npm run android` which basically starts the Metro bundler, Expo server and so on.
Everything works just fine.

If I try to use `expo eject` however, after about 10 seconds I've got the following console output:

```bash
✔ Created native projects
✔ Added Metro bundler configuration.
✔ Updated package.json and added index.js entry point for iOS and Android.
- Removed "main": "node_modules/expo/AppEntry.js" from package.json because we recommend using index.js as main instead.

🧶 Using Yarn to install packages. You can pass --npm to use npm instead.

✔ Cleaned JavaScript dependencies.
✔ Installed JavaScript dependencies.
⠙ iOS config syncing
/usr/local/lib/node_modules/expo-cli/node_modules/@expo/configure-splash-screen/src/ios/pbxproj.ts:45
        throw new Error(`.pbxproj file parsing issue: ${err.message}.`);
              ^
Error: .pbxproj file parsing issue: undefined.
    at pbxProject.<anonymous> (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/configure-splash-screen/src/ios/pbxproj.ts:45:15)
    at pbxProject.emit (node:events:376:20)
    at pbxProject.<anonymous> (/usr/local/lib/node_modules/expo-cli/node_modules/xcode/lib/pbxProject.js:45:18)
    at ChildProcess.emit (node:events:376:20)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
```

My environment is almost the same as @Nostrus'. Just let me know if you need further informations. I've tried using `expo eject --npm` but (as I've already expected) it yields the same result.

@byCedric's tip to just remove the `android` and `ios` folder is no option in my case because those folders didn't exist in the first place.

Thanks a lot and have a nice (still a little distant) weekend.

**Comment by ajlouie** [comment]
I was getting this same error when ejecting. To eject successfully, I had to revert any changes to `package.json` to the pre-ejected version, then run this sequence of commands at the root level of my expo project:
```
rm -rf android
rm -rf ios
rm -rf node_modules
rm -rf package-lock.json
rm -rf .expo
npm install
expo install
expo eject
```

**Comment by brentvatne** [comment]
thanks for sharing @ajlouie! those are good steps to follow if you have tried ejecting before and then only partially reverted, although it's not needed to delete your package-lock or .expo directories or run expo install.

```
rm -rf android
rm -rf ios
# Open package.json, remove react-native-unimodules if it's there, then:
rm -rf node_modules
npm install
expo eject
```
