### ISSUE TITLE
React-Native Image not rendering on screen, warning: Unable to resolve manifest assets.

### ISSUE THREAD

**Issue by mercale** [expo/expo-cli#3117]
## Description
Image are not rendering on screen 

## Environment
  Expo CLI 4.0.17 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.3
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare

## Expected Behavior
Image to appear on the Android simulator 

## Observed Behavior

Receiving following warning 

```
Warning: Unable to resolve manifest assets. Icons might not work. Unable to perform cache refresh for C:\Users\mercale\AppData\Local\Expo\schema-40.0.0.json: Error: unable to get local issuer certificate.
Finished building JavaScript bundle in 4925ms.
Warning: Problem validating app.json: Unable to perform cache refresh for C:\Users\mercale\AppData\Local\Expo\schema-40.0.0.json: Error: unable to get local issuer certificate.
Running application on Android SDK built for x86.
```

## Reproducible Demo
project created with ```npx create-react-native-app```

started with ```expo start```
Run Android from Metro Bundler
expecting image to render, code snipper below
```
 <Image
        source={{
          width: 200,
          height: 300,
          uri: 'https://reactnative.dev/img/tiny_logo.png'
        }}
      ></Image>
```
however, the logo didn't display  on the android simulator

**Comment by brentvatne** [comment]
this seems like a similar issue to https://github.com/expo/expo-cli/issues/3086 - at least for some of the warnings you see

you could refer to https://docs.expo.io/guides/troubleshooting-proxies/ for info on troubleshooting proxies, but we don't work in these environments and depend on the community to keep it up to date. it seems like your network is blocking requests to `https://reactnative.dev/img/tiny_logo.png` to download the image.

**Comment by mercale** [comment]
I've done a couple of test downloading the image from browser and through curl they all passed the network, the block is happening when running curl in Visual Studio Code integrated bash terminal. I'll work this out with our network team. 

Thanks for looking into this, you've been a lot of help.  Closing this ticket.

**Comment by arnoldkunihira** [comment]
![image](https://user-images.githubusercontent.com/19782721/125210753-73cc0400-e2aa-11eb-8954-357b9c91434b.png)
I know this was closed a while ago, however am failing to run android on both the emulator and actual device.
Could someone please help me with this error?

**Comment by brentvatne** [comment]
@arnoldkunihira - install the latest version of `expo-cli` and run `expo doctor` -- can you connect to expo servers?

**Comment by remberluyckx** [comment]
@brentvatne I have the same problem as @arnoldkunihira . I installed the latest version of expo-cli and ran expo doctor, this is the result. 
![Capture](https://user-images.githubusercontent.com/17109821/131656923-ab7f256d-750a-474a-beca-059f72d97022.JPG)

However when I check the expo server status, everything seems to be up and running
