### ISSUE TITLE
Can not login from cli (expo publish) with env keys.

### ISSUE THREAD

**Issue by wclr** [expo/expo-cli#3119]
## Description

Can not log in from cli (expo publish) with env variables set. It seems to me that it worked when using sdk 38 passing `EXPO_USERNAME` and `EXPO_PASSWORD` worked for automatic login.

After upgrade it doesn't. I also tried `EXPO_CLI_USERNAME` and `EXPO_CLI_PASSWORD` it doesn't work.

## Environment

  Expo CLI 4.0.17 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\alexo\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Expo Workflow: managed

## Expected Behavior

`expo publish` (if expo is looged manuualy using `expo login`) doesn't request manual entrance of credentials.

## Observed Behavior

`expo publish` requests manual entrance of credentials if not logged in previously.

**Comment by byCedric** [comment]
Hi @wclr, thanks for writing in. The `EXPO_CLI_USERNAME` and `EXPO_CLI_PASSWORD` are the correct ones, but you could also try [using an access token](https://docs.expo.io/accounts/programmatic-access/) with `EXPO_TOKEN`. 

I see that you are working from a Windows environment, how do you define these environment variables?

**Comment by wclr** [comment]
I see that you are working from a Windows environment, how do you define these environment variables?

In this case i'm running with `child_process.execSync`, code looks like this:

```ts
  const cmd = ['expo publish', dir, ...configArgs].join(' ')
  exec.sync(cmd, {
    env: {
      EXPO_USERNAME: username,
      EXPO_PASSWORD: password,
    },
  })
```

**Comment by brentvatne** [comment]
confirmed that i'm having this issue as well. that said, `EXPO_TOKEN` works great and is a better approach than using your username and password in this context. you can create a token here: https://expo.io/settings/access-tokens

**Comment by brentvatne** [comment]
fix deployed in latest expo-cli
