### ISSUE TITLE
Resolve requests different in dev and publish modes

### ISSUE THREAD

**Issue by wclr** [expo/expo-cli#3122]
## Description

I'm using a custom metro resolver. It receives a request to resolve `../AppEntry.js`  and resolves it to a custom module (that imports `registerRootComponent` and runs it in a particular way). It works in Dev mode. And before update to sdk 40 and the latest CLI everything worked for published apps.

After this upgrade a problem appeared: while running `expo publish` the first resolve request that comes to the custom resolver is not `../AppEntry.js` but `../../App`, so that AppEntry.js happens to be already resolved (to default location in `node_modules/expo/AppEntry.js`), which is inconsistent with how the process of resolution behaves in dev mode.

## Environment

```
  Expo CLI 4.0.17 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\alexo\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Expo Workflow: managed

```

## Expected Behavior

Dev and Publish modes of resolution should be consistent. Both should start with `../AppEntry.js` requests.

## Observed Behavior

In dev module it the resolution starts with `../AppEntry.js` request and in publish mode this request is skipped and resolved without invovlment of custom metro resolver.

```
Error text goes here!
```

**Comment by brentvatne** [comment]
please provide a minimal reproducible example: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by wclr** [comment]
> please provide a minimal reproducible example

I know how to configure metro resolver, and as I described it all worked before the update. And actually, I can work around the issue I described, I just pointing to an inconsistency bug in your platform.

```js
resolver: {
  resolveRequest: (context, realModuleName, platform, moduleName) => {
    // In dev mode: the first request moduleName: `..node_modules/expo/AppEntry.js`
   
    // In publish mode the first request moduleName: `../../App`
  }
}
```

Those who are responsible for modules the resolution process should understand what it all about.

**Comment by brentvatne** [comment]
what version were you using prior to sdk 40 where you observed the desired behavior?

**Comment by wclr** [comment]
Setting env variable EXPO_USE_DEV_SERVER -> '0' does not change the behaviour

> what version were you using prior to sdk 40 where you observed the desired behavior?

I'm not sure was a couple of months ago. Anyway, the current resolution behavior is definitely inconsistent in the described way.

**Comment by brentvatne** [comment]
@wclr - got it. are you sure this is an issue in expo's set up rather than with metro itself?

**Comment by wclr** [comment]
I don't know who is responsible for what is passed to the custom resolver in expo-cli design. But currently and then (when it worked consistenlty) I believe the same version of `metro 0.58.0` was used.

**Comment by brentvatne** [comment]
this is our metro config: https://github.com/expo/expo-cli/blob/master/packages/metro-config/src/ExpoMetroConfig.ts

**Comment by wclr** [comment]
I'm not sure that it is related. In my project I have `metro.config.js` which exports config with `resolver.resolveRequest` custom function. And this function gets different (initial) requests while dev and while publish.

**Comment by brentvatne** [comment]
sorry i don't know what the reason is for this behavior, and i suspect it's just something about metro that i am not familiar with. you can investigate further yourself if you like by looking at the @expo/dev-server `bundleAsync` / `bundleAsync` methods (called on publish) and `runMetroDevServerAsync` method (used for serving bundles in development).

you will notice that in `bundleAsync``, the `entryPoint` is `'node_modules/expo/AppEntry.js'` as you would expect (you can add logs to the method to verify it if you like). what happens after this inside metro is more of a question for the metro team.

anyways, if you can demonstrate that this behavior is due to something that expo is doing incorrectly, we can investigate that further.
