### ISSUE TITLE
Error in expo build:ios using non-interactive expo-cli@4.1.3 

### ISSUE THREAD

**Issue by 1337LutZ** [expo/expo-cli#3138]
## Description
Upgrading expo-cli from version 4.0.17 to 4.1.3 broke our build locally and in CI (Bitrise) when using `expo build:ios --non-interactive`. Is there an expo-cli change that I'm not aware of?

## Environment

```
Expo CLI 4.1.3 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
    Managers:
      CocoaPods: 1.8.4 - /Users/xxx/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
      Android SDK:
        API Levels: 28, 29
        Build Tools: 29.0.0, 29.0.2, 30.0.0
        System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.3 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.13 
    Expo Workflow: managed
```

## Expected Behavior
I expect the build not fail when running:

```
EXPO_APPLE_PASSWORD=xxx expo build:ios --release-channel test --non-interactive --no-publish --apple-id xxx@xxx.xxx
```

## Observed Behavior
The build is failing with the below error in expo-cli 4.1.3, however has no issues in expo-cli 4.0.17.

```
[11:10:29] Checking if there is a build in progress...

[11:10:29] Accessing credentials for dept in project HR-App

[11:10:29] › Log in to your Apple Developer account to continue
[11:10:29] Authentication with Apple Developer Portal failed!
[11:10:29] Input is required, but Expo CLI is in non-interactive mode.
Required input:
> Apple ID:
```

## Reproducible Demo
I don't have a reproducible demo, however I would expect that running the above in your project would result in the same issue.
This is more a question regarding any expo-cli changes that havent been documented when moving from 4.0.17 to 4.1.3.

**Comment by EvanBacon** [comment]
ya we removed fastlane, I'll investigate.

**Comment by brentvatne** [comment]
re: changes to expo-cli, we document anything meaningful in changelog - https://github.com/expo/expo-cli/blob/master/CHANGELOG.md

in this case this item was "[cli] Copy over EAS Apple API methods" - we missed out on passing an option through though, but it should have not been a breaking change

**Comment by 1337LutZ** [comment]
> re: changes to expo-cli, we document anything meaningful in changelog - https://github.com/expo/expo-cli/blob/master/CHANGELOG.md
> 
> in this case this item was "[cli] Copy over EAS Apple API methods" - we missed out on passing an option through though, but it should have not been a breaking change

Yea I checked the changelog, but couldn't really find anything that sounded like that would break this.
I'll use 4.0.17 for now and upgrade expo-cli once the bugfix has been applied.

Thanks to the both of you!

**Comment by brentvatne** [comment]
another thing you could do is use the `--skip-credentials-check` flag to `expo build:ios` - this will allow you to run your build w/o interacting with apple, and will make it a bit faster
