### ISSUE TITLE
Expo could make a emulator for the web preview.That include functions same like the ios and android emulators.And shows some errors that make sense during compilng or debugging error.

### ISSUE THREAD

**Issue by haneenmahd** [expo/expo-cli#3155]
**Do you understand that any feature requests opened in the core Expo repository will be closed?**

true

**Comment by brentvatne** [comment]
isn't this just a web browser? not sure i follow what you are suggesting :)

**Comment by haneenmahd** [comment]
I mean a emulator made natively for both windows and mac os .I am suggesting this because the web browser doesn't show enought information about the error.
