### ISSUE TITLE
expo-cli 4.1.4 throws "Request body larger than maxBodyLength limit" when try to publish

### ISSUE THREAD

**Issue by vhuerta** [expo/expo-cli#3158]
**Summary**

After upgrade to expo-cli@4.1.4 I'm not able to publish my project anymore, downgrading to expo-cli@4.1.3 solves the problem

**Environment**

Expo CLI 4.1.4 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.3 - ~/.nvm/versions/node/v14.15.3/bin/node
      npm: 6.14.9 - ~/.nvm/versions/node/v14.15.3/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
    npmGlobalPackages:
      expo-cli: 4.1.4
    Expo Workflow: managed

**Please specify your device/emulator/simulator platform, model and version**

ios,android

**Error output**

Request body larger than maxBodyLength limit
Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit
    at RedirectableRequest.write (/Users/victor/.nvm/versions/node/v14.15.3/lib/node_modules/expo-cli/node_modules/follow-redirects/index.js:96:24)
    at RedirectableRequest.end (/Users/victor/.nvm/versions/node/v14.15.3/lib/node_modules/expo-cli/node_modules/follow-redirects/index.js:121:10)
    at dispatchHttpRequest (/Users/victor/.nvm/versions/node/v14.15.3/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:300:11)
    at new Promise (<anonymous>)
    at httpAdapter (/Users/victor/.nvm/versions/node/v14.15.3/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:46:10)
    at dispatchRequest (/Users/victor/.nvm/versions/node/v14.15.3/lib/node_modules/expo-cli/node_modules/axios/lib/core/dispatchRequest.js:52:10)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at ApiV2Client._requestAsync (/@expo/xdl@59.0.20/src/ApiV2.ts:232:18)
    at ApiV2Client.uploadFormDataAsync (/@expo/xdl@59.0.20/src/ApiV2.ts:184:12)
    at _uploadArtifactsAsync (/@expo/xdl@59.0.20/src/Project.ts:873:10)

**Reproducible demo or steps to reproduce from a blank project**

Try to publish a project

**Comment by alexhouse** [comment]
I was searching in circles for hours earlier before seeing your ticket (similar issue appeared last year too)! Glad it wasn't just me.

**Comment by shaebler** [comment]
Downgrading expo-cli to 4.1.3 solved my exact same problem.
```bash
npm install -g expo-cli@4.1.3
```

With expo-cli@4.1.4:
```bash
$ winpty expo.cmd build:android -t apk
Checking if there is a build in progress...
... 8< snip 8< ...
Uploading JavaScript bundles
Request body larger than maxBodyLength limit
Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit
... 8< snip 8< ...
```

With expo-cli@4.1.3:
```bash
$ winpty expo.cmd build:android -t apk
┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│   There is a new version of expo-cli available (4.1.4).                 │
│   You are currently using expo-cli 4.1.3                                │
│   Install expo-cli globally using the package manager of your choice;   │
│   for example: `npm install -g expo-cli` to get the latest version      │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘
Checking if there is a build in progress...
... 8< snip 8< ...
Waiting for build to complete.
You can press Ctrl+C to exit. It won't cancel the build, you'll be able to monitor it at the printed URL.
\ Build queued...
```

**Comment by tripplilley** [comment]
A cursory investigation suggests that the update of `axios` (and therefore `follow-redirects`) broke this. I looked at `expo-cli/ApiV2.ts` and it looks like it's setting `maxContentLength` correctly, so perhaps something broke between axios 0.19.0 and 0.21.1 (based on the yarn.lock changes in 5dd643e )

**Comment by giautm** [comment]
I ran into same issue when use `expo/expo-github-action`

**Comment by byCedric** [comment]
Thanks for the reports! We patched an issue, it should work as intended again with `expo-cli@4.1.5`. If you encounter other issues, feel free to open a new issue.
