### ISSUE TITLE
Pressing Ctrl-C chooses "n" on "y/n" prompt rather than exiting

### ISSUE THREAD

**Issue by gregfenton** [expo/expo-cli#3159]
**Summary**

When running `expo update`, pressing Ctrl-C should exit the command.  At a Y/N prompt, Ctrl-C is taken to be "n".

**Environment**

 Expo CLI 4.1.4 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v14.15.4/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.0
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
      react-navigation: ^4.4.0 => 4.4.1
    npmGlobalPackages:
      expo-cli: 4.1.4
    Expo Workflow: managed

**Please specify your device/emulator/simulator platform, model and version**

N/A

**Error output**

Pressing Ctrl-C at the Y/N prompt for the question:
```
? Would you like to upgrade the Expo app in the iOS simulator? › (y/N)
```
simply goes to the next step of the process.

**Reproducible demo or steps to reproduce from a blank project**

1. Start with a project that can be upgraded.  I'm in an SDK38 project
2. Run: `expo update 39 --npm`
3. At the first Y/N prompt (above), press Ctrl-C.  The command accepts the input as a "no" and goes to the next Y/N.

Full shell interaction here below.  My only input to the command once started is Ctrl-C which I had to press 3 times to get the command to exit:

```
$ expo upgrade 39 --npm                
Your git working tree is clean
To revert the changes after this command completes, you can run the following:
  git clean --force && git reset --hard

✖ Would you like to upgrade the Expo app in the iOS simulator? … no

✖ Would you like to upgrade the Expo app in the Android emulator? … no

⠼ Installing the expo@^39.0.0 package...
$ 
```

**Comment by EvanBacon** [comment]
Good catch, I've opened a PR to fix this.
