### ISSUE TITLE
expo-cli update notice appears even with --non-interactive

### ISSUE THREAD

**Issue by tripplilley** [expo/expo-cli#3160]
**Summary**

`expo-cli` displays the update notice ("There is a new version of expo-cli available [...]") even when the `--non-interactive` flag is set. This breaks uses which don't explicitly suppress stderr (e.g., calling `$(expo-cli url:apk --non-interactive)` in a bash script). I would expect `--non-interactive` to suppress messages which aren't actually _errors_.

**Environment**

```
  Expo CLI 4.1.3 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.1.4 - /usr/local/bin/bash
    Binaries:
      Node: 15.5.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.3.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz => 0.63.2 
      react-navigation: ^4.4.3 => 4.4.3 
    Expo Workflow: managed
```

**Please specify your device/emulator/simulator platform, model and version**

n/a

**Error output**

_No response_

**Reproducible demo or steps to reproduce from a blank project**

`expo-cli url:apk --non-interactive`

**Comment by brentvatne** [comment]
pr welcome, related code here https://github.com/expo/expo-cli/blob/753a0d67c3347fa75dfad0c0e32a6606fba5d7e8/packages/expo-cli/src/exp.ts#L332-L344
