### ISSUE TITLE
Installation on Apple Silicon with yarn fails, because of missing Electron dependency

### ISSUE THREAD

**Issue by cseelus** [expo/expo-cli#3177]
**Summary**

```
node_modules/electron/install.js:47
  throw err
  ^

Error: Failed to find Electron v1.8.8 for darwin-arm64 at https://github.com/electron/electron/releases/download/v1.8.8/electron-v1.8.8-darwin-arm64.zip
```

Afaik there is no Electron v.1.8.8 for Darwin Arm64: https://github.com/electron/electron/releases/tag/v1.8.8

**Environment**

Can't run, as I can't install `expo-cli`

**Please specify your device/emulator/simulator platform, model and version**

MacBook Air M1

**Error output**

_No response_

**Reproducible demo or steps to reproduce from a blank project**

Without `expo-cli` installed run `yarn global add expo-cli`

**Comment by brentvatne** [comment]
expo-cli doesn't depend on electron

**Comment by brentvatne** [comment]
```
╭─~/code/expo-cli ‹master›
╰─$ yarn why electron
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "electron"...?
[2/4] 🚚  Initialising dependency graph...
warning Resolution field "hermes-engine@0.0.0" is incompatible with requested version "hermes-engine@^0.2.1"
[3/4] 🔍  Finding dependency...
error We couldn't find a match!
✨  Done in 1.22s.
```

most likely what you are experiencing is this quirk with yarn where when you install any global package it attempts to rebuild every other package that you've installed globally already. try running `npm i -g expo-cli` (npm doesn't have this behavior) and you will see that it works

**Comment by cseelus** [comment]
Quirky yarn behavior indeed. Thanks for the great answer ☺️
