### ISSUE TITLE
Global @expo/ngrok installation not detected

### ISSUE THREAD

**Issue by stratoss** [expo/expo-cli#3181]
**Summary**

I'm trying to run a project using a tunnel, but I'm getting 'The package @expo/ngrok@^2.4.3 is required to use tunnels, would you like to install it globally?' error no matter that the package is already installed. Also getting a bunch of 'Tunnel URL not found (it might not be ready yet), falling back to LAN URL.' errors.

**Environment**

  Expo CLI 4.1.6 environment info:
    System:
      OS: Linux 5.9 Debian GNU/Linux bullseye/sid
      Shell: 5.1.0 - /bin/bash
    Binaries:
      Node: 12.19.0 - /usr/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 6.14.10 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz => 0.63.2 
      react-navigation: ^4.4.3 => 4.4.3 
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: managed

**Please specify your device/emulator/simulator platform, model and version**

No emulator - trying to run a tunnel

**Error output**

Tunnel URL not found (it might not be ready yet), falling back to LAN URL.
✖ The package @expo/ngrok@^2.4.3 is required to use tunnels, would you like to install it globally? … yes

**Reproducible demo or steps to reproduce from a blank project**

expo start --tunnel -a on a blank project

**Comment by stratoss** [comment]
On an empty project with sudo expo start --tunnel the tunnel is found, but the following error appears:

> Error: EACCES: permission denied, open '/tmp/haste-map-metro-4-e4159473e98c27ff0ecb4dee65107544-edc11b02b0a22d0ab3be1ed79078640b'
    at Object.openSync (fs.js:462:3)
    at Object.writeFileSync (fs.js:1384:35)
    at Object.writeFileSync (/home/stratoss/projects/tunnel-test/node_modules/jest-serializer/build/index.js:196:21)
    at HasteMap._persist (/home/stratoss/projects/tunnel-test/node_modules/jest-haste-map/build/index.js:944:31)
    at /home/stratoss/projects/tunnel-test/node_modules/jest-haste-map/build/index.js:497:17
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/stratoss/projects/tunnel-test/node_modules/jest-haste-map/build/index.js:193:24)
    at _next (/home/stratoss/projects/tunnel-test/node_modules/jest-haste-map/build/index.js:213:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

with a red 'Could not connect to development server.' error on the IOS client.

**Comment by calebdre** [comment]
I've got the same issue

**Comment by calebdre** [comment]
@stratoss Looks like a duplicate of #2459

**Comment by brentvatne** [comment]
@stratoss - do you install npm packages with `sudo` typically? it seems odd to me that you would not have access to files in tmp directory.

re: global installation - this was an intentional change, we automatically install it on demand rather than installing with every expo-cli download because not everybody wants/needs the tunnel capabilities and it adds a bunch of warnings and weight to the installation.

**Comment by calebdre** [comment]
I downgraded to `expo-cli: 4.1.0` and it started working for me, even though I still get a `Tunnel URL not found (it might not be ready yet), falling back to LAN URL.` warning.

**Comment by stratoss** [comment]
@brentvatne only the global packages, which I generally tend to avoid.

**Comment by stratoss** [comment]
> I downgraded to `expo-cli: 4.1.0` and it started working for me, even though I still get a `Tunnel URL not found (it might not be ready yet), falling back to LAN URL.` warning.

Works for me as well! tHANKS @calebdre

**Comment by brentvatne** [comment]
@stratoss - it's strongly recommended not to install packages globally using sudo. if you have problems with that, follow this guide: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by brentvatne** [comment]
another thing to try if that won't work for you - remove your global @expo/ngrok installation and install @expo/ngrok to your project itself

**Comment by MAYURKALE11** [comment]
Hi Guys

node v14.16.0
expo 4.3.0
npm 7.6.3

Your development laptop/computer needs to be on the same network as your mobile.

I connected my phone to my home wifi router and turned off the mobile carrier network. Then I connected my laptop to the same wifi router

To test I scaffolded a minimum project and the tabs project. I then started both by executing **expo start --tunnel** at the project root

I managed to loaded both projects by scanning the qr code on my iphone using expo go app.

However, even when connected and using the app on my iPhone i still see logging "Tunnel URL not found (it might not be ready yet), falling back to LAN URL." be outputted in my dev terminal.

**Comment by brentvatne** [comment]
@MAYURKALE11 - perhaps ngrok isn't working on your machine. try running `npx @expo/ngrok http 3000` - does that result in something like this?

<img width="614" alt="Screen Shot 2021-03-17 at 3 57 55 PM" src="https://user-images.githubusercontent.com/90494/111549511-8a69b080-8739-11eb-8f67-e3d63f79cac2.png">

**Comment by erickriva** [comment]
Add global node_modules paths (npm/yarn) to an environment variable called `NODE_MODULES`.

NPM: npm config get prefix + '\node_modules'
YARN: yarn global dir + '\node_modules'
