### ISSUE TITLE
License of binaries?

### ISSUE THREAD

**Issue by hyandell** [expo/expo-cli#3195]
I noticed there are binary files in the project that appear, by their name, to be from a different source from expo-cli, but there is no license called out. Would it be possible to identify their licensing?

https://github.com/expo/expo-cli/tree/master/packages/xdl/binaries

**Comment by byCedric** [comment]
Hi @hyandell! We are in the process of removing these binaries from future versions, so it shouldn't matter too much. But here they are:

- Linux
  1. [adb](https://github.com/expo/expo-cli/tree/master/packages/xdl/binaries/linux/adb) - See [this SO answer](https://stackoverflow.com/a/13534832/2277025)
  2. [get-path-bash](https://github.com/expo/expo-cli/blob/master/packages/xdl/binaries/linux/get-path-bash) - Our script, [our license](https://github.com/expo/expo-cli#license)
- MacOS / OSx
  1. [adb](https://github.com/expo/expo-cli/tree/master/packages/xdl/binaries/osx/adb) - See [this SO answer](https://stackoverflow.com/a/13534832/2277025)
  2. [watchman](https://github.com/expo/expo-cli/blob/master/packages/xdl/binaries/osx/watchman/watchman) - [Facebook's watchman license](https://github.com/facebook/watchman/blob/master/LICENSE)
  3. [xde](https://github.com/expo/expo-cli/tree/master/packages/xdl/binaries/osx/xde) - Our [old XDE environment])(https://github.com/expo/xde/blob/master/LICENSE)
  4. [get-path-bash](https://github.com/expo/expo-cli/blob/master/packages/xdl/binaries/osx/get-path-bash) - Our script, [our license](https://github.com/expo/expo-cli#license)
- Windows 
  1. [7z1602-extra](https://github.com/expo/expo-cli/tree/master/packages/xdl/binaries/windows/7z1602-extra) - _See the folder itself for the license_
  2. [adb](https://github.com/expo/expo-cli/tree/master/packages/xdl/binaries/windows/adb) - See [this SO answer](https://stackoverflow.com/a/13534832/2277025)

Hope this helps!
