### ISSUE TITLE
Expo Warning: Problem validating app.json: Unable to perform cache refresh 

### ISSUE THREAD

**Issue by eyadoxaty** [expo/expo-cli#3196]
**Summary**

Warning: Problem validating app.json: Unable to perform cache refresh for C:\Users\iyadox\AppData\Local\Expo\schema-40.0.0.json: Error: connect ETIMEDOUT 104.197.216.164:443.

**Environment**

app.json 

{
  "expo": {
    "name": "my-project",
    "slug": "my-project",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      }
    },
    "web": {
      "favicon": "./assets/favicon.png"
    }
  }
}

package.json

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~40.0.0",
    "expo-status-bar": "~1.0.3",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0"
  },
  "private": true
}

**Please specify your device/emulator/simulator platform, model and version**

android network with expo go

**Error output**

Warning: Problem validating app.json: Unable to perform cache refresh for C:\Users\iyadox\AppData\Local\Expo\schema-40.0.0.json: Error: connect ETIMEDOUT 104.197.216.164:443.

**Reproducible demo or steps to reproduce from a blank project**

Warning: Problem validating app.json: Unable to perform cache refresh for C:\Users\iyadox\AppData\Local\Expo\schema-40.0.0.json: Error: connect ETIMEDOUT 104.197.216.164:443.

**Comment by byCedric** [comment]
Hi @eyadoxaty! Thanks for writing in, it looks like you are having trouble connecting to our API. The IP address is our `exp.host` endpoint. Can you try to open this manually:
- https://exp.host/--/api/v2/project/configuration/schema/40.0.0

This is the endpoint it should be requesting for an XDL schema update, for SDK 40. If that doesn't work, there is something blocking access to that domain. Unfortunately, we can't help debugging that on our end.

**Comment by yasniel1408** [comment]
hola tengo el mismo error, sin embargo cuando pincho en el link que publicaste si logro ver lo que tiene, como puedo resolver esto?????    :(

**Comment by Stevemoretz** [comment]
This should be marked somewhere :)
I had the same problem.My ip was blocked too.

**Comment by hsnemzed7** [comment]
I had the same problem , not fixed for me via using a vpn , help me please ...

**Comment by conor909** [comment]
I just started getting this, the app ran fine a few hours ago, with no changes to the code I'm getting this

**Comment by Gr3at** [comment]
> Hi @eyadoxaty! Thanks for writing in, it looks like you are having trouble connecting to our API. The IP address is our `exp.host` endpoint. Can you try to open this manually:
> 
> * https://exp.host/--/api/v2/project/configuration/schema/40.0.0
> 
> This is the endpoint it should be requesting for an XDL schema update, for SDK 40. If that doesn't work, there is something blocking access to that domain. Unfortunately, we can't help debugging that on our end.

Had the same issue upon running `expo export`. 

What's odd is that i can `curl https://exp.host/--/api/v2/project/configuration/schema/40.0.0` and retrieve the contents just fine.

I am behind a company proxy. 
Does `expo` respect the system proxy?
Or does it require explicit configuration?
