### ISSUE TITLE
ngrok implementation in expo crashes on macOS 11.2 on M1 processor

### ISSUE THREAD

**Issue by d2bspzoo** [expo/expo-cli#3202]
**Summary**

I found that ngrok implementation in expo (4.1.6) crashes on macOS 11.2 on M1 processor.

It returns: Tunnel URL not found (it might not be ready yet), falling back to LAN URL.
Error starting tunnel Starting tunnels timed out.
When I check Console, there is a crash report on that.

I checked the same project on macOS 11.2 running on Intel processor and everything works as a charm. I do not know, if it is an @expo/ngrok 2.3.4 issue or ngrok 3.4.0 (I installed it using yarn, and expo/ngrok was forked from it). 

I tried using ngrok manually from terminal and it works fine. 

It looks like a problem with @expo-cli implementation. 

**Environment**

 Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 11.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 15.8.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 7.5.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 29.0.2
        System Images: android-25 | Google APIs ARM EABI v7a, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: managed

**Please specify your device/emulator/simulator platform, model and version**

MacBook Pro (late 2020) M1 processor

**Error output**

Tunnel URL not found (it might not be ready yet), falling back to LAN URL.
Error starting tunnel Starting tunnels timed out.

**Reproducible demo or steps to reproduce from a blank project**

expo init <new_project>
expo start --tunnel

**Comment by brendo-m** [comment]
See https://github.com/bubenshchykov/ngrok/issues/207

**Comment by brendo-m** [comment]
To summarize there are 2 problems:

1. The wrong `ngrok` binary is used. On M1 macs we need to use `ngrok-bin-darwin-amd64` [1] but `ngrok-bin-darwin-x64` is used because `process.arch` still returns `x86`
2. After switching to the correct binary we get 503's. Retries were added for these in https://github.com/bubenshchykov/ngrok/issues/148 on 3.3 but @expo/ngrok is still on 2.4.3

**Comment by jonnyasmar** [comment]
Anyone have any ideas on this? Pretty big gap for M1 devs to not be able to share our Expo builds without publishing.

**Comment by janva255** [comment]
@d2bspzoo can you tell me how to do a quick fix for this please, could you find a workaround by installing ngrok? thanks

**Comment by moxorama** [comment]
I have to run all development environment via Rosetta

**Comment by tabvn** [comment]
i got same issue. Latest version of Expo just installed 2 days ago on Macbook Apple M1

**Comment by d2bspzoo** [comment]
@janva255 the fastest solution is to run expo on Intel based mac. I did that and the problem is no longer critical for me :) From my point of view the solution looks pretty simple it is just a matter of updating @expo/ngrok to current ngrok version. Current ngrok version works fine on M1 mac.

**Comment by tabvn** [comment]
@d2bspzoo  so now we have to wait for update @expo/ngrok  from Expo Team , Yes ngrok (node or brew install)on mac M1 is working fine .

**Comment by d2bspzoo** [comment]
@tabvn Yup! I submitted this issue on expo forum and send message to support team in February and waiting :)

**Comment by bjornlll** [comment]
Any known workarounds?

**Comment by moxorama** [comment]
> Any known workarounds?

Run all development environment and Terminal via Rosetta

**Comment by Kudo** [comment]
we've upgraded the ngrok.

for existing users, please try
`yarn global add '@expo/ngrok'` if the project is inited with yarn (default when Yarn is installed)
or
`npm -g add '@expo/ngrok'` if the project is initied with npm (default when Yarn is not installed)

**Comment by Kudo** [comment]
going to close this. please let us know if encountered any problems for the updated version.

**Comment by oscar-b** [comment]
@Kudo This still doesn't work, on Apple Silicon M1 without Rosetta 2 installed:

```
Developer tools running on http://localhost:19002
Starting Metro Bundler
Error starting ngrok: 
Tunnel URL not found (it might not be ready yet), falling back to LAN URL.
Tunnel URL not found (it might not be ready yet), falling back to LAN URL.
Tunnel URL not found (it might not be ready yet), falling back to LAN URL.

```

**Comment by oscar-b** [comment]
@Kudo Huh this is weird, I tracked it down to this:

https://github.com/expo/xdl/blob/main/packages/xdl/src/start/ngrok.ts#L113-L119

It fails on my machine (macOS, M1) without any Android stuff installed, and brings down the whole ngrok initialising with it.

**Comment by Chriko2502** [comment]
✔ The package @expo/ngrok@^4.1.0 is required to use tunnels, would you like to install it globally? … yes
Installing @expo/ngrok@^4.1.0 for tunnel support...
Successfully installed @expo/ngrok@^4.1.0
Error starting ngrok: qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
Tunnel URL not found (it might not be ready yet), falling back to LAN URL.

For me it's also still not working (MacBook Pro M1) using docker (image node:16)

**Comment by bbuchalter** [comment]
@Chriko2502 I also encountered this problem with Docker and M1. One workaround is to use the platform argument when specifying base image of your dockerfile:

```
FROM --platform=linux/amd64 node:lts-bullseye
```

Sadly, this has dramatically reduced the performance of the container. A better solution is still needed.

**Comment by oscar-b** [comment]
I’ve tracked down the exact reason for it above, it should be a simple fix for the maintainers. I don’t use the functionality myself (checkout Tailscale instead). 

I suspect that installing `adb` would “fix” the issue as well (I didn’t want to do that on my machine though).
