### ISSUE TITLE
The scroll in web doesn’t work perfectly

### ISSUE THREAD

**Issue by joamartico** [expo/expo-cli#3212]
In the web you can scroll the html, when you should only be able to scroll the content of the app. This makes harder to slide between top tabs: ![image](https://user-images.githubusercontent.com/63528825/107547924-cd6dbc80-6bac-11eb-96f4-13cb92e04893.png)

![image](https://user-images.githubusercontent.com/63528825/107547944-d2cb0700-6bac-11eb-8956-b8afaae78275.png)

**Comment by brentvatne** [comment]
hi! you might want to dig deeper to understand what is happening and report to a more appropriate repo, possibly react navigation (for the top tabs)

**Comment by joamartico** [comment]
Hi, but the problem is not with react-navigation. The problem is that expo-web index.html allows to scroll the html and the body. I tried to solve it adding position fixed or overflow:hidden to the body and the html style but get other unwanted results.
It is not a big issue but if you can solve it the expo web apps will look and feel much more native.

**Comment by brentvatne** [comment]
@joamartico - you can eject the index.html and change it as needed. feel free to open a discussion with a deeper description of the problem and your suggestions: https://github.com/expo/expo-cli/discussions :)

**Comment by joamartico** [comment]
Ok thanks! I will open a discussion
