### ISSUE TITLE
sync metro-react-native-babel-transformer's version with react-native

### ISSUE THREAD

**Issue by giautm** [expo/expo-cli#3213]
Currently I have two version of `metro-react-native-babel-transformer` installed in node_modules.
one from `@expo/metro-config`

https://github.com/expo/expo-cli/blob/610c5c60413a2cae824c7b4d25f41244cf71eef8/packages/metro-config/package.json#L38

And one from `react-native`
https://github.com/expo/expo/blob/e4945a62bd1c172f790251600b792d62f09e18a7/ios/versioned-react-native/ABI40_0_0/ReactNative/package.json#L102

**Comment by EvanBacon** [comment]
Sounds reasonable, thanks for raising this. I've opened a PR to bump the version.
