### ISSUE TITLE
Running default template on web causes chokidar errors due to watching node_modules

### ISSUE THREAD

**Issue by OliverBalfour** [expo/expo-cli#3214]
**Describe the bug**
When you do `npm run web` on the default fresh install of this template the `node_modules` directory is watched by the file watching mechanism (chokidar). This causes errors due to the inotify limit being exceeded on Linux. Although this can be increased, a fresh install has ~40,000 files in `node_modules` (compared to 40 in my app) which equates to 40MB of memory needlessly watching files. Would it be possible to disable watching the `node_modules` folder or add a configuration option to allow this?

**To Reproduce**
1. `npx create-react-native-app test`
2. `cd test`
3. `npm i -g expo-cli`
4. `npm run web`

**Desktop**
 - OS: up to date Manjaro Linux (with node 14.7.0)

**Comment by EvanBacon** [comment]
I'm having trouble reproducing, my understanding is that this code prevents what you're describing https://github.com/expo/expo-cli/blob/8b217fe6561df154f2ef13768191817fd9c2c547/packages/webpack-config/src/addons/withDevServer.ts#L214-L220

**Comment by OliverBalfour** [comment]
Looks like that code is deliberately watching `node_modules` per `src/node_modules is not ignored to support absolute imports`. Makes sense, so this is a feature and not a bug. I think this could be improved to only watch files that are actually included with absolute imports instead of watching the entire `node_modules` black hole, but I'm not too concerned if that's a lot of work, I'm no longer working on the project I ran into this problem with.
