### ISSUE TITLE
Cannot run ios simulator after ejecting a blank expo project

### ISSUE THREAD

**Issue by liemdo** [expo/expo-cli#3219]
**Summary**

After ejecting a blank expo project without modifying anything, I can't run the ios app. It worked before ejecting. 

**Environment**

Expo CLI 4.1.6 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 15.5.1 - /usr/local/bin/node
      npm: 7.3.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /Users/myMac/.gem/ruby/2.6.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 23, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 11.2/11B52 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: bare

**Please specify your device/emulator/simulator platform, model and version**

iphone 11 13.2 simulator

**Error output**

> my-app@1.0.0 ios
> react-native run-ios

info Found Xcode workspace "myapp.xcworkspace"
info Building (using "xcodebuild -workspace myapp.xcworkspace -configuration Debug -scheme myapp -destination id=79196FB8-2668-4A20-B60A-B21A38C2D84D")
success Successfully built the app
info Installing "/Users/myMac/Library/Developer/Xcode/DerivedData/myapp-bsjwpiurdhulvwbdywaiqybizqxz/Build/Products/Debug-iphonesimulator/app.app"
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Could not install at this time.
Failed to chmod /Users/myMac/Library/Developer/CoreSimulator/Devices/79196FB8-2668-4A20-B60A-B21A38C2D84D/data/Bundle/Application/6BA71E1B-3E00-47AC-97A7-6E9D7B15EC04/app.app/app : No such file or directory
Underlying error (domain=MIInstallerErrorDomain, code=4):
	Failed to chmod /Users/myMac/Library/Developer/CoreSimulator/Devices/79196FB8-2668-4A20-B60A-B21A38C2D84D/data/Bundle/Application/6BA71E1B-3E00-47AC-97A7-6E9D7B15EC04/app.app/app : No such file or directory
info Launching "com.test.app"
error Failed to launch the app on simulator, An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
The request to open "com.test.app" failed.
The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application "com.test.app" is unknown to FrontBoard").
Underlying error (domain=FBSOpenApplicationErrorDomain, code=4):
	The operation couldn’t be completed. Application "com.test.app" is unknown to FrontBoard.
	Application "com.test.app" is unknown to FrontBoard.

**Reproducible demo or steps to reproduce from a blank project**

expo init my-app
cd my-app
npm run eject
npm run ios

Each time when I run `npm run ios`, a new id/folder such as `7DBDD49F-C9B0-468B-8427-C942B974E170` is generated `/Users/myMac/Library/Developer/CoreSimulator/Devices/79196FB8-2668-4A20-B60A-B21A38C2D84D/data/Bundle/Application/7DBDD49F-C9B0-468B-8427-C942B974E170/app.app/app`. However, `7DBDD49F-C9B0-468B-8427-C942B974E170` doesn't exist under Bundle/Application.

**Comment by brentvatne** [comment]
https://stackoverflow.com/a/46385130/659988

**Comment by liemdo** [comment]
When I removed the `EXCLUDE_ARCH` option under Build Settings, I could build the project. I'm not sure where that option came from.
