### ISSUE TITLE
Adding a "did you increment your version" to the expo compile commands

### ISSUE THREAD

**Issue by actuallymentor** [expo/expo-cli#3221]
**Summary**

I notice that I often forget to increment my version numbers. For me it is just annoying, but for you it is wasted cloud resources.

I think a "Did you increment your version number? [Y/n]" could save you a bunch of processing costs.

Maybe I am just an idiot, but if you see often see successive builds on your infrastructure maybe this makes sense.

Happy to draft a PR.

**Environment**

All.

**Please specify your device/emulator/simulator platform, model and version**

CLI

**Error output**

_No response_

**Reproducible demo or steps to reproduce from a blank project**

N/A

**Comment by EvanBacon** [comment]
We're tracking this feature for EAS build https://github.com/expo/eas-cli/issues/116.
