### ISSUE TITLE
Expo react-native app crashes while doing remote debugging in expo 40.0.0

### ISSUE THREAD

**Issue by vishalsinghsaini** [expo/expo-cli#3228]
**Summary**

From the moment Expo version update to 40.0.0 , while doing remote debug js app crashes in emulator.

**Environment**

`
This is my package.json

 {
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~40.0.0",
    "expo-status-bar": "~1.0.3",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0"
  },
  "private": true
}`

**Please specify your device/emulator/simulator platform, model and version**

Android version 10.0

**Error output**

`This is the error

Opening exp://127.0.0.1:19000 on Pixel_3a_XL_API_30_2
Finished building JavaScript bundle in 46214ms.
Running application on Android SDK built for x86.
info Launching Dev Tools...
Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `expo start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Vishal\AppData\Roaming\npm-cache\_logs\2021-02-15T09_26_48_544Z-debug.log
`

`This is the logs

16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Vishal\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start" "-c"
18 verbose node v14.10.1
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error @ start: `expo start`
22 error Exit status 1
23 error Failed at the @ start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Reproducible demo or steps to reproduce from a blank project**

Created a new app
1. expo init (project name)
2. npm start
3.app started in emulator
4. app crashes while chosing remote debug js option in developers option

**Comment by brentvatne** [comment]
what version of expo-cli are you using?

**Comment by vishalsinghsaini** [comment]
Hi sorry for the late response , it got resolved at the end. After downgrading cli version from 40 to 39 to make the debugger work.
It doesnt help. At the end what make the debugger work is . I have to remove the expo cli and react native tools from my system and installed them again. Then i created a new expo project and try to debug that's what worked for me
