### ISSUE TITLE
expo start fails on iOS with missing googleServicesFile for android

### ISSUE THREAD

**Issue by ehlerskon** [expo/expo-cli#323]
Today, I added the google-services.json file to my app.json [like described here](https://docs.expo.io/versions/latest/guides/using-fcm/) and also added it to the .gitignore.
My colleague pulled my changes and experienced the problem, that the expo app didn't start with the notice "There was a problem loading the requested app" on iOS. We tried nearly everything concerning his network connection but were not able to solve the problem. Then, I had the idea to create an empty google-services.json file (not even an empty object) in his root directory of the project and it worked again.

## Expected Behavior

The expo-cli start command should be able to run without the existance of the file referenced in the googleServicesFile property of the app.json - this file is only required to run expo build command for android, isn't it? 
At least, the expo-cli should throw an error in this case.  

## Reproducable demo

1. expo init test
2. cd test
3. add the following config to the app.json:
`"android": {
      "googleServicesFile": "./google-services.json"
}`
4. expo start

![img_1071](https://user-images.githubusercontent.com/1207106/51549775-54875500-1e6b-11e9-9e49-3776af7728b0.png)

**Comment by wschurman** [comment]
Just tried to repro this and it seemed to be working now. Closing this out. Let me know if it re-occurs.

**Comment by danieldanielecki** [comment]
In `eas` builds, if you'd have the `google-services.json` file defined in `.gitingore`, it won't pick up.
