### ISSUE TITLE
$ in password fails to authenticate with Apple Developer Portal

### ISSUE THREAD

**Issue by chrislondon** [expo/expo-cli#3232]
**Summary**

I'm unable to enter a password into the CLI to log into the Apple Developer Portal because it contains a $.  Resetting my password to a password without a dollar sign fixes the issues. However, Expo should fix this.

**Environment**

All

**Please specify your device/emulator/simulator platform, model and version**

build:ios

**Error output**

Saving Apple ID password to the local Keychain. Learn more https://docs.expo.io/distribution/security#keychain
Authenticating to Apple Developer Portal...
Invalid username and password combination, try again.

**Reproducible demo or steps to reproduce from a blank project**

run `expo build:ios` with an Apple Developer account that has a $ in the password

**Comment by EvanBacon** [comment]
Just tested `$` in password works.
