### ISSUE TITLE
SDK40: After upgrading SDK, expo-linear-gradient started throwing Can't find variable: _setGlobalConsole

### ISSUE THREAD

**Issue by Egizas** [expo/expo-cli#3248]
**Summary**

After upgrading to SDK 40, "expo-linear-gradient": "~8.4.0"  started throwing `Can't find variable: _setGlobalConsole`

I have tried both:
1) Installing the latest expo-linear-gradient version (ver. 9.0.0) with `npm i -S expo-linear-gradient `
2) Installing expo sdk compatible version (ver. 8.4.0) with 'expo install expo-linear-gradient"

**Environment**

  Expo CLI 4.1.6 environment info:
    System:
      OS: Windows 10 10.0.19042   
    Binaries:
      Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.2 - ~\AppData\Roaming\npm\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 26, 27, 28, 29, 30
        Build Tools: 27.0.3, 30.0.0, 30.0.1
        System Images: android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version  3.0.0.0 AI-171.4443003
    npmPackages:
      expo: ^40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
      react-navigation: ^4.0.9 => 4.4.3
    Expo Workflow: managed

**Please specify your device/emulator/simulator platform, model and version**

genymotion 3.2.0

**Error output**

_No response_

**Reproducible demo or steps to reproduce from a blank project**

1) Upgrade expo sdk to 40
2) Install expo-linear-gradient version (ver. 9.0.0) with `npm i -S expo-linear-gradient `
3) import { LinearGradient } from 'expo-linear-gradient';
4) Use expo-linear-gradient:
              <LinearGradient
                colors={['rgba(255,255,255,0.10)', 'transparent']}
                style={styles.titleGradient}
              >

**Comment by brentvatne** [comment]
`expo install linear-gradient` is the correct way to install this library - this will give you version 8.4.0 that is compatible with sdk 40

see installation on https://docs.expo.io/versions/latest/sdk/linear-gradient/
and this doc about using libraries https://docs.expo.io/workflow/using-libraries/

**Comment by Egizas** [comment]
@brentvatne I think you were too quick to close the ticket...

First of all `expo install linear-gradient` is installing the linear-gradient v.1.0.3, and not `expo-linear-gradient` library.

Second, as I mentioned in my description (point nr. 2), I tried `expo install expo-linear-gradient` which installs `expo-linear-gradient` ver. 8.4.0 (as described in the documentation https://docs.expo.io/versions/latest/sdk/linear-gradient/)

The issue still persists

**Comment by brentvatne** [comment]
sorry it was a typo `expo install expo-linear-gradient` as the docs i linked to explain
