### ISSUE TITLE
`expo-cli upload:android` error: "the database system is in recovery mode."

### ISSUE THREAD

**Issue by bryanstearns** [expo/expo-cli#3255]
**Summary**

Just did `expo upload:android --track alpha --key ./deploy/google_service_account.json` to submit "the latest build from Expo servers" - it appears to have successfully uploaded the build (I see it in my Play store console) but after the submission summary, it says:

```
✔ Scheduling submission
✖ Something went wrong when submitting your app to Google Play Store.
the database system is in recovery mode.
error Command failed with exit code 1.
```

**Environment**

 Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.4 - ~/.asdf/installs/nodejs/14.15.4/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.10 - ~/.asdf/installs/nodejs/14.15.4/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.1 - /Users/stearns/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 26, 28, 29
        Build Tools: 27.0.3, 28.0.3, 29.0.2
        System Images: android-23 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-navigation: ^4.4.0 => 4.4.0
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: managed

**Please specify your device/emulator/simulator platform, model and version**

N/A - this isn't about running a build, it's about uploading to the store

**Error output**

Since my upload succeeded, I don't need to upload a new build right now, but I'll probably upload another build in the next few days - when I do, I'll be sure to run it with EXPO_DEBUG=1 and add the output in a comment if it happens again.

**Reproducible demo or steps to reproduce from a blank project**

Sorry, haven't done this; hoping this report is helpful without it. Feel free to close this if not - as I said, my build uploaded successfully, but the error message and nonzero exit status were concerning, so I wanted to let you know. Thanks!

**Comment by brentvatne** [comment]
hey @bryanstearns! looking into this right now, will get back to you soon

**Comment by brentvatne** [comment]
@ide let me know that this should be resolved now. we're doing a bit of database maintenance and there was a brief period of unavailability. let me know if you encounter further issues!

**Comment by bryanstearns** [comment]
Aha - good to know it was just my lucky timing. Thanks for checking, @brentvatne!
