### ISSUE TITLE
Error with Babel config and transform react jsx 

### ISSUE THREAD

**Issue by corentin-ach** [expo/expo-cli#3263]
### Summary

Error when building my expo project : babel recommends to remove transform-react-jsx-source and transform-react-jsx-self. This error appears only on macOS. With Linux and Android it builds perfectly. 

### Environment

Expo CLI 4.2.1 environment info:
    System:
      OS: macOS 11.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 15.8.0 - ~/.nvm/versions/node/v15.8.0/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 7.5.1 - ~/.nvm/versions/node/v15.8.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

macOS, iPhone 12 Pro, 14.3

### Reproducible demo or steps to reproduce from a blank project

rm -rf node_modules && yarn install && yarn run expo start -c and 

Here is the error : 

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-03-01 at 18 19 43](https://user-images.githubusercontent.com/34914748/109533621-b985ee00-7aba-11eb-9c58-c492fb25d6e6.png)

**Comment by brentvatne** [comment]
i initialized a blank new project and ran it, it works as expected: https://github.com/brentvatne/corentin

we can reopen this if you can provide a project we can clone and run to reproduce.
