### ISSUE TITLE
Validate Android versionCode

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#3267]
### Summary

https://forums.expo.io/t/android-build-often-failing-at-the-running-graddle-step/49178/10

> builds that are failing have version code outside of range of 32 bit integer (eg 20210226124), builds that work have values 10 times smaller that are just on the edge of that range. We seem to generate build.gradle correctly, but it seems gradle does not support values like that.

### Environment

Happens on every version of Expo CLI

### Please specify your device/emulator/simulator platform, model and version

N/A

### Reproducible demo or steps to reproduce from a blank project

Set versionCode to 20210226124 and try to build with `expo build:android`

**Comment by ide** [comment]
Is the limit a signed or unsigned 32-bit integer?

**Comment by brentvatne** [comment]
https://stackoverflow.com/a/35275169/659988

> android:versionCode — An integer value that represents the version of the application code, relative to other versions.
>
> Checking the java doc, by default, the int data type is a 32-bit signed two's complement integer, which has a minimum value of -2^31 and a maximum value of (2^31)-1.
