### ISSUE TITLE
Android Build Standalone Failed

### ISSUE THREAD

**Issue by olawalejuwonm** [expo/expo-cli#3287]
### Summary

Building standalone app failed

### Environment

 System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.18.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 7.5.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6858069
    npmPackages:
      expo: ^40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Android

### Error output

`Could not find google-services.json while looking in [src/nullnull/debug, src/debug/nullnull, src/nullnull, src/debug, src/nullnullDebug]
Fri, 12 Mar 2021 04:58:09 GMT
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Fri, 12 Mar 2021 04:58:09 GMT
Could not find google-services.json while looking in [src/nullnull/release, src/release/nullnull, src/nullnull, src/release, src/nullnullRelease]
Fri, 12 Mar 2021 04:58:09 GMT
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Fri, 12 Mar 2021 04:58:20 GMT
> Task :app:preBuild UP-TO-DATE
Fri, 12 Mar 2021 04:58:20 GMT
> Task :app:extractProguardFiles
Fri, 12 Mar 2021 04:58:20 GMT
> Task :app:preReleaseBuild
Fri, 12 Mar 2021 04:58:20 GMT
> Task :app:compileReleaseAidl NO-SOURCE
Fri, 12 Mar 2021 04:58:20 GMT
> Task :app:compileReleaseRenderscript NO-SOURCE
Fri, 12 Mar 2021 04:58:20 GMT
> Task :app:generateReleaseBuildConfig
Fri, 12 Mar 2021 04:58:20 GMT
> Task :app:generateReleaseResValues
Fri, 12 Mar 2021 04:58:20 GMT
> Task :app:generateReleaseResources
Fri, 12 Mar 2021 04:58:20 GMT
> Task :app:processReleaseGoogleServices
Fri, 12 Mar 2021 04:58:20 GMT
Parsing json file: /app/turtle/workingdir/android/sdk40/android-shell-app/app/google-services.json
Fri, 12 Mar 2021 04:58:28 GMT
> Task :app:createReleaseCompatibleScreenManifests
Fri, 12 Mar 2021 04:58:28 GMT
> Task :app:extractDeepLinksRelease
Fri, 12 Mar 2021 04:58:29 GMT
> Task :app:processReleaseManifest
Fri, 12 Mar 2021 04:58:29 GMT
/app/turtle/workingdir/android/sdk40/android-shell-app/app/src/main/AndroidManifest.xml:17:9-26:20 Warning:
Fri, 12 Mar 2021 04:58:29 GMT
	provider#expo.modules.filesystem.FileSystemFileProvider@android:authorities was tagged at AndroidManifest.xml:17 to replace other declarations but no other declaration present
Fri, 12 Mar 2021 04:58:29 GMT
> Task :app:javaPreCompileRelease
Fri, 12 Mar 2021 04:58:29 GMT
> Task :app:prepareLintJar
Fri, 12 Mar 2021 04:58:29 GMT
> Task :app:mergeReleaseShaders
Fri, 12 Mar 2021 04:58:29 GMT
> Task :app:compileReleaseShaders NO-SOURCE
Fri, 12 Mar 2021 04:58:29 GMT
> Task :app:generateReleaseAssets UP-TO-DATE
Fri, 12 Mar 2021 04:58:31 GMT
> Task :app:mergeReleaseAssets
Fri, 12 Mar 2021 04:58:32 GMT
> Task :app:checkReleaseDuplicateClasses
Fri, 12 Mar 2021 04:58:32 GMT
> Task :app:processReleaseJavaRes NO-SOURCE
Fri, 12 Mar 2021 04:58:37 GMT
> Task :app:collectReleaseDependencies
Fri, 12 Mar 2021 04:58:37 GMT
> Task :app:sdkReleaseDependencyData
Fri, 12 Mar 2021 04:58:37 GMT
> Task :app:mergeReleaseJniLibFolders
Fri, 12 Mar 2021 04:58:38 GMT
> Task :app:validateSigningRelease
Fri, 12 Mar 2021 04:58:38 GMT
> Task :app:mergeReleaseJavaResource
Fri, 12 Mar 2021 04:58:39 GMT
> Task :app:mergeReleaseResources FAILED
Fri, 12 Mar 2021 04:58:43 GMT
> Task :app:mergeReleaseNativeLibs
Fri, 12 Mar 2021 04:58:43 GMT
[stderr] FAILURE: Build failed with an exception.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr] * What went wrong:
Fri, 12 Mar 2021 04:58:43 GMT
[stderr] Execution failed for task ':app:mergeReleaseResources'.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr] > 
Fri, 12 Mar 2021 04:58:43 GMT
[stderr] Multiple task action failures occurred:
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]       > Android resource compilation failed
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]         /app/turtle/workingdir/android/sdk40/android-shell-app/app/src/main/res/mipmap-mdpi/ic_launcher.png: AAPT: error: failed to read PNG signature: file does not start with PNG signature.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]             
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]         /app/turtle/workingdir/android/sdk40/android-shell-app/app/src/main/res/mipmap-mdpi/ic_launcher.png: AAPT: error: file failed to compile.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]             
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]       > Android resource compilation failed
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]         /app/turtle/workingdir/android/sdk40/android-shell-app/app/src/main/res/mipmap-xxhdpi/ic_launcher.png: AAPT: error: failed to read PNG signature: file does not start with PNG signature.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]             
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]         /app/turtle/workingdir/android/sdk40/android-shell-app/app/src/main/res/mipmap-xxhdpi/ic_launcher.png: AAPT: error: file failed to compile.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]             
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]       > Android resource compilation failed
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]         /app/turtle/workingdir/android/sdk40/android-shell-app/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png: AAPT: error: failed to read PNG signature: file does not start with PNG signature.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]             
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]         /app/turtle/workingdir/android/sdk40/android-shell-app/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png: AAPT: error: file failed to compile.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]             
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]       > Android resource compilation failed
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]         /app/turtle/workingdir/android/sdk40/android-shell-app/app/src/main/res/mipmap-xhdpi/ic_launcher.png: AAPT: error: failed to read PNG signature: file does not start with PNG signature.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]             
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]         /app/turtle/workingdir/android/sdk40/android-shell-app/app/src/main/res/mipmap-xhdpi/ic_launcher.png: AAPT: error: file failed to compile.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]             
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]       > Android resource compilation failed
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]         /app/turtle/workingdir/android/sdk40/android-shell-app/app/src/main/res/mipmap-hdpi/ic_launcher.png: AAPT: error: failed to read PNG signature: file does not start with PNG signature.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]             
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]         /app/turtle/workingdir/android/sdk40/android-shell-app/app/src/main/res/mipmap-hdpi/ic_launcher.png: AAPT: error: file failed to compile.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]             
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]       > Android resource compilation failed
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]         /app/turtle/workingdir/android/sdk40/android-shell-app/app/src/main/res/drawable-xxxhdpi/splashscreen_image.png: AAPT: error: failed to read PNG signature: file does not start with PNG signature.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]             
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]         /app/turtle/workingdir/android/sdk40/android-shell-app/app/src/main/res/drawable-xxxhdpi/splashscreen_image.png: AAPT: error: file failed to compile.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr]             
Fri, 12 Mar 2021 04:58:43 GMT
[stderr] * Try:
Fri, 12 Mar 2021 04:58:43 GMT
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
Fri, 12 Mar 2021 04:58:43 GMT
[stderr] * Get more help at https://help.gradle.org
Fri, 12 Mar 2021 04:58:43 GMT
[stderr] BUILD FAILED in 1m 1s
Fri, 12 Mar 2021 04:58:43 GMT
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Fri, 12 Mar 2021 04:58:43 GMT
Use '--warning-mode all' to show the individual deprecation warnings.
Fri, 12 Mar 2021 04:58:43 GMT
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings
Fri, 12 Mar 2021 04:58:43 GMT
19 actionable tasks: 19 executed
Fri, 12 Mar 2021 04:58:44 GMT
Error: ./gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/app/turtle/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (events.js:418:26)
    at ChildProcess.emit (events.js:311:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
    ...
    at spawnAsync (/app/turtle/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at spawnAsyncThrowError (/app/turtle/node_modules/@expo/xdl/build/detach/ExponentTools.js:201:45)
    at buildShellAppAsync (/app/turtle/node_modules/@expo/xdl/build/detach/AndroidShellApp.js:976:11)
    at async Object.createAndroidShellAppAsync (/app/turtle/node_modules/@expo/xdl/build/detach/AndroidShellApp.js:396:5)
    at async runShellAppBuilder (/app/turtle/build/builders/android.js:95:9)
    at async Object.buildAndroid [as android] (/app/turtle/build/builders/android.js:43:28)
    at async build (/app/turtle/build/jobManager.js:181:33)
    at async processJob (/app/turtle/build/jobManager.js:118:32)
    at async Object.doJob (/app/turtle/build/jobManager.js:49:5)
    at async main (/app/turtle/build/server.js:66:13)`

### Reproducible demo or steps to reproduce from a blank project

expo build:android

Building Standalone Android keep failing.

**Comment by olawalejuwonm** [comment]
please i need urgent help

**Comment by olawalejuwonm** [comment]
@dsokal

**Comment by brentvatne** [comment]
it looks like there is an issue with your google-services json. make sure it's configured properly.

**Comment by olawalejuwonm** [comment]
Yes it's configured, I don't think it's the main issue. Because I'm seeing
something like Gradle version, please check the error log more

**Comment by rajatTemaniya** [comment]
I'm facing the same issue. but not using the firebase in the project so why I'm also getting this message ?

**Comment by brentvatne** [comment]
```
xxxhdpi/splashscreen_image.png: AAPT: error: failed to read PNG signature: file does not start with PNG signature.
```

the splash screen image appears to be invalid?

please provide a reproducible example: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by olawalejuwonm** [comment]
wow! thanks, i changed the splash image and it simply worked
