### ISSUE TITLE
Incorrect mapping of a React Native version to an Expo SDK version

### ISSUE THREAD

**Issue by RedMickey** [expo/expo-cli#3288]
### Summary

Hello,
I am a maintainer of [React Native Tools](https://github.com/microsoft/vscode-react-native) VS Code extension. The extension is used for debugging React Native (including Expo) applications.
We use [`facebookReactNativeVersionToExpoVersionAsync`](https://github.com/expo/expo-cli/blob/master/packages/xdl/src/Versions.ts#L220-L244) function to get an appropriate Expo SDK version and add it to `app.json` file. 

### Environment

Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 11.2.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 25, 27, 28, 29
        Build Tools: 23.0.1, 25.0.1, 25.0.2, 27.0.3, 28.0.3, 29.0.0, 29.0.1, 29.0.2
        System Images: android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Any device or emulator

### Error output

This project requires a newer version of Expo Go - please download the latest version from App Store

### Reproducible demo or steps to reproduce from a blank project

We found out that Expo SDK 41 version was added to the [`versions/latest`](https://exp.host/--/api/v2/versions/latest) endpoint, and it seems that after this update the `facebookReactNativeVersionToExpoVersionAsync` function started to work incorrectly. 
When we pass React Native version `0.63.2` or  `0.63.4` to the function, it returns Expo SDK 41 version instead of 40.
According to the current implementation of the function, we think that it will work correctly again, as soon as Expo SDK 41 is released, but before this, it will return a wrong Expo SDK version.

![image](https://user-images.githubusercontent.com/33267199/111172051-8a8d7300-85b6-11eb-9903-79f1e6100cd3.png)

**Comment by EvanBacon** [comment]
This may be unrelated, but her are some notes about RN / Expo versioning that we use in the repo:

- Expo CLI tooling automatically infers the sdkVersion based on the installed version of the `expo` package in a project. This is done via `getConfig` from `@expo/config`
- We provide a list of native packages that work with each SDK in the `expo/bundledNativeModules.json` file. This is used in `expo install` and `expo eject`.

CC @brentvatne re our discussion on unversioned ejecting.

**Comment by brentvatne** [comment]
we should update `facebookReactNativeVersionToExpoVersionAsync` to only return released SDK versions (using [this logic](https://github.com/expo/expo-cli/blob/29863645980aab85931494d42bf56baca1f5928b/packages/xdl/src/Versions.ts#L94)).

**Comment by fson** [comment]
This should be fixed by #3305.

Please note that the XDL package name has changed from `@expo/xdl` to `xdl`. This fix will be released in the next version of `xdl`. (`@expo/xdl` is still used in a couple of places in our internal systems, but won't be receiving updates in the future.)

**Comment by RedMickey** [comment]
Thank you for your help and the update.
