### ISSUE TITLE
Could not get status from Metro bundler. connect ECONNREFUSED 127.0.0.1:19004

### ISSUE THREAD

**Issue by gaetaneferon** [expo/expo-cli#3304]
### Summary

Trying to run a react native app with expo. I keep getting the following error when I run `expo start` :
`Could not get status from Metro bundler. connect ECONNREFUSED 127.0.0.1:19004`

### Environment

Expo CLI 4.3.1 environment info:
    System:
      OS: Linux 5.4 Debian GNU/Linux 10 (buster) 10 (buster)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 14.15.5 - /usr/local/bin/node
      npm: 6.14.11 - /usr/local/bin/npm
    npmPackages:
      expo: ^39.0.4 => 39.0.5
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.3.1
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Windows + WSL Debian 9

### Error output

Starting project at /mnt/c/www/yooviz-src/yooviz-app-front
Developer tools running on http://localhost:19002
Opening developer tools in the browser...
Could not get status from Metro bundler. connect ECONNREFUSED 127.0.0.1:19004
Connecting to Metro bundler failed.
Error: Connecting to Metro bundler failed.
    at _waitForRunningAsync (/xdl@59.0.26/src/start/startLegacyReactNativeServerAsync.ts:342:11)       
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at startReactNativeServerAsync (/xdl@59.0.26/src/start/startLegacyReactNativeServerAsync.ts:285:3) 
    at startAsync (/xdl@59.0.26/src/start/startAsync.ts:61:5)

### Reproducible demo or steps to reproduce from a blank project

...

I keep getting the same error output even when I remove `.expo`, `node_modules`, `package-lock.json` and after a `npm cache clean --force`.

I need help, thanks in advance

**Comment by brentvatne** [comment]
does this happen on any brand new project or only on a specific of project? it seems like metro is failing to start.

if it is happening on a specific project, please share a reproducible example. if it's on any project, try `EXPO_DEBUG=1 expo start`

**Comment by gaetaneferon** [comment]
Hi, It works with a specific projet (made with expo init). What do you mean by "share a reproductible example" ?
Thanks for your help

**Comment by brentvatne** [comment]
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by EvanBacon** [comment]
Please reopen after sharing a minimum reproducible example.
