### ISSUE TITLE
expo init AwesomeProject eror (code enogit)

### ISSUE THREAD

**Issue by hyrllhsgr** [expo/expo-cli#331]
? Choose a template: expo-template-tabs
? Choose which workflow to use: managed
√ Please enter a few initial configuration values.
  Read more: https://docs.expo.io/versions/latest/workflow/configuration · 100% completed
[20:18:41] Extracting project files...
[20:18:42] Customizing project...
[20:18:42] Installing dependencies...
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/expo/vector-icons.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hayru\AppData\Roaming\npm-cache\_logs\2019-01-27T17_19_23_963Z-debug.log
[20:19:24] Process exited with non-zero code: 1
[20:19:24] Set EXPO_DEBUG=true in your env to view the stack trace.

**Comment by AdamJNavarro** [comment]
Hey @hyrllhsgr,

You need to install git and make sure it's found in your $PATH before using the Expo-CLI. If you still have an issue after that, please let me know and I'll reopen this issue.

Cheers,

Adam

**Comment by Vanguardo66** [comment]
Hi guys!
I have the same issue and I don't know how to resolve it. how to install git.
I'm working on windows 10 64x.  Do i need git client or do I have to install npm git. (I have done both)
what path do I have to add to the system environment?

Thnx in advance.
