### ISSUE TITLE
[electron] Failed to find Electron v6.1.12 for darwin-arm64 when running `yarn expo-electron` on Apple M1

### ISSUE THREAD

**Issue by stephenhandley** [expo/expo-cli#3310]
### Summary

Was following the guide here and ran into error when running the third setup step: 
```
yarn expo-electron
```

and getting error *Failed to find Electron v6.1.12 for darwin-arm64*

### Environment

  Expo CLI 4.3.2 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.6.0 - /var/folders/q5/y3831g4x7_j3nnzd_7qj2rhh0000gn/T/yarn--1616287897245-0.22424516982353238/node
      Yarn: 1.22.10 - /var/folders/q5/y3831g4x7_j3nnzd_7qj2rhh0000gn/T/yarn--1616287897245-0.22424516982353238/yarn
      npm: 7.4.0 - ~/.nvm/versions/node/v15.6.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

MacBook Air (M1)

### Error output

$ yarn expo-electron
yarn run v1.22.10
$ /XXX/node_modules/.bin/expo-electron
› Installing the missing dependencies: react-native-web, electron@^6.0.12.
> yarn add react-native-web electron@^6.0.12
[1/4] 🔍  Resolving packages...
warning react-native-web > deep-assign@3.0.0: Check out `lodash.merge` or `merge-options` instead.
warning electron > electron-download > nugget > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
error /XXX/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /XXX/node_modules/electron
Output:
Downloading tmp-72981-0-electron-v6.1.12-darwin-arm64.zip
Error: GET https://github.com/electron/electron/releases/download/v6.1.12/electron-v6.1.12-darwin-arm64.zip returned 404
/XXX/node_modules/electron/install.js:53
  throw err
  ^

Error: Failed to find Electron v6.1.12 for darwin-arm64 at https://github.com/electron/electron/releases/download/v6.1.12/electron-v6.1.12-darwin-arm64.zip
    at Request.<anonymous> (/XXX/node_modules/nugget/index.js:169:61)
    at Request.emit (node:events:379:20)
    at Request.onRequestResponse (/XXX/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (node:events:379:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:668:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:129:17)
    at TLSSocket.socketOnData (node:_http_client:534:22)
    at TLSSocket.emit (node:events:379:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
/XXX/node_modules/@expo/electron-adapter/bin/expo-electron.js:16
  throw err;
`

### Reproducible demo or steps to reproduce from a blank project

Followed the steps described here on a MacBook Air M1
https://docs.expo.io/guides/using-electron/

**Comment by ajsmth** [comment]
Hi there - if you need a workaround - you'll want to run your install command using `x86_64` architecture. 

This is a pretty good article that goes through setting up just that: https://www.cypress.io/blog/2021/01/20/running-cypress-on-the-apple-m1-silicon-arm-architecture-using-rosetta-2/

**Comment by stephenhandley** [comment]
@ajsmth awesome thx i'll give that a look!

**Comment by stephenhandley** [comment]
Dug a little more and realizing i shouldn't be holding my breath here. looks like this is using [electron-webpack](https://github.com/electron-userland/electron-webpack) which hasn't been actively maintained in over a year. Electron is on v12.0.5 which [has arm support](https://github.com/electron/electron/releases/tag/v12.0.5)

**Comment by ajsmth** [comment]
If you're still curious, you can get an `arm64` build going with this repo: https://github.com/ajsmth/expo-electron-starter - let me know if that works for you!

**Comment by stephenhandley** [comment]
Awesome thanks @ajsmth
