### ISSUE TITLE
Standalone Expo builds with turtle-cli failing due to a failing dependency on dbflow 4.2.4 

### ISSUE THREAD

**Issue by nickvasic** [expo/expo-cli#3312]
### Summary

When performing Android builds using turtle CLI, builds are failing due to dependency on dbflow 4.2.4 not resolving.

### Environment

  Expo CLI 4.3.2 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.0.0 - ~/.nvm/versions/node/v14.0.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v14.0.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
      Android SDK:
        API Levels: 27, 28, 29
        Build Tools: 27.0.3, 28.0.3, 29.0.0, 29.0.2
        System Images: android-22 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.3.2
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

N/A - Android

### Error output

Mar 22 01:45:49 turtle[10976] INFO:     > Could not find com.github.Raizlabs.DBFlow:dbflow:4.2.4.
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Mar 22 01:45:49 turtle[10976] INFO:       Required by:
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Mar 22 01:45:49 turtle[10976] INFO:           project :app > host.exp.exponent:expoview:40.0.0
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"

### Reproducible demo or steps to reproduce from a blank project

Applies to all builds.

**Comment by brentvatne** [comment]
this could be an issue with jitpack.io - we had a similar issue before and resolved it in https://github.com/expo/expo/pull/5892. also related: https://github.com/jitpack/jitpack.io/issues/4002

builds are still working with `expo build:android` so this could be caching related. have you tried clearing your gradle cache? `~/.gradle/caches/`

**Comment by nickvasic** [comment]
Thanks @brentvatne yes confirming `expo build:android` works. Is there any dependency caching on the expo side of things? turtle-cli is still having a problem - confirming the local caches are clean. We'll use expo build command as a workaround for now.

**Comment by byCedric** [comment]
Closing the feedback loop here, this issue is tracked here: https://github.com/agrosner/DBFlow/issues/1717

**Comment by brentvatne** [comment]
@nickvasic - yeah we do some caching so that probably is what prevented this issue from surfacing on turtle. as per https://github.com/agrosner/DBFlow/issues/1717 this is now resolved, sorry for the hassle

**Comment by nickvasic** [comment]
Thanks very much for the update! All good
