### ISSUE TITLE
New snippet prompt doesn't support non-interactive option

### ISSUE THREAD

**Issue by 13013SwagR** [expo/expo-cli#332]
## Description
When running: `sudo expo init --non-interactive --template blank --workflow managed Awesome_project`
Snippet prompt appears, change made in pull request #267 prevents the use of `--non-interactive` option.
`--workflow` option was added, but none for the snippet prompt,
making silent install difficult.

## Expected Behavior
Snippet prompt should not appear.
Solution A: Add options to fill snippet prompt as arguments.
Solution B: Skip the snippet prompt when `managed` workflow is selected.

## Observed Behavior

```
? Please enter a few initial configuration values.
  Read more: https://docs.expo.io/versions/latest/workflow/configuration ‣ 50% completed
 {
   "expo": {
     "name": "<The name of your app visible on the home screen>",
     "slug": "Awesome_project"
   }
 }

```

## Environment
```
  Expo CLI 2.7.0 environment info:
    System:
      OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 11.8.0 - /usr/bin/node
      npm: 6.5.0 - /usr/bin/npm
    npmGlobalPackages:
      expo-cli: 2.7.0
```

## Reproducible Demo
`sudo expo init --non-interactive --template blank --workflow managed Awesome_project`

**Comment by fson** [comment]
Thanks for reporting this issue. Looks like we could just just use the same name for the `slug` and `name` fields (passed as an argument) in non-interactive mode.

**Comment by fson** [comment]
Hey, `expo-cli@2.10.0` was just released and it adds these command line flags to `expo init` to make it possible to use it in non-interactive mode:
```
    --name [name]                   The name of your app visible on the home screen.
    --android-package [name]        The package name for your Android app.
    --ios-bundle-identifier [name]  The bundle identifier for your iOS app.
```
For example, to initialize an app using the managed workflow, you can now run:
```
expo init my-awesome-project --non-interactive --template blank --workflow managed --name Hello
```

**Comment by 13013SwagR** [comment]
Awesome! Thank you.
