### ISSUE TITLE
imports are not resolved properly when importing index module

### ISSUE THREAD

**Issue by SPWizard01** [expo/expo-cli#3333]
### Summary

I am not sure whether this is a configuration issue or a bug, but seems like bug, moreover I am not sure if this is a bug with expo or module-resolver or something else.
The problem is that whenever there is a specific set of imports or directories in the project, modules are not always resolved to index with "."

### Environment

Expo CLI 4.3.2 environment info:
System:
OS: Windows 10 10.0.19042
Binaries:
Node: 10.13.0 - C:\Program Files\nodejs\node.EXE
npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
IDEs:
Android Studio: Version 4.1.0.0 AI-201.8743.12.41.7042882
npmPackages:
expo: ~40.0.0 => 40.0.1
react: 16.13.1 => 16.13.1
react-dom: 16.13.1 => 16.13.1
react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
react-native-web: ~0.13.12 => 0.13.18
Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

emulator Pixel_3a_API_30_x86

### Error output

TypeError: (0 , _.useTheme) is not a function
at node_modules\expo\build\logs\LogSerialization.js:160:14 in _captureConsoleStackTrace
at node_modules\expo\build\logs\LogSerialization.js:41:26 in serializeLogDataAsync

... 9 more stack frames from framework internals

### Reproducible demo or steps to reproduce from a blank project

https://github.com/SPWizard01/EXPO-TEST

expo start -c, and observe the error.

change https://github.com/SPWizard01/EXPO-TEST/blob/main/theming/withTheme.tsx
to `import { useTheme } from "./index"` instead of `"."` and the error is gone, change back to `"."` and this will still build for that run.

because https://github.com/expo/expo-cli/issues/3332 was closed without a valid comment, I would like to reiterate on this one. i would believe that the problem should come up more often than not.

 IDE will suggest "." import and it is perfectly valid one AND it is the first import if will use if the name does not match any name in the node_modules.
i.e. there would be only last 2 lines and by default first one is used.
![image](https://user-images.githubusercontent.com/27969609/112609261-02179980-8e24-11eb-948e-c4fc29e16132.png)

also note that in `https://github.com/SPWizard01/EXPO-TEST/blob/main/components/ComponentA/ComponentB.tsx` the import of ComponentA from `"."` works just fine in ALL cases.

This is NOT expected behavior :)

**Comment by brentvatne** [comment]
please point me to the appropriate line from the es6 import spec that backs up your assertion that this is expected behavior. i'm not saying that it isn't, i'm just saying that i don't know.

also, what you're observing is a behavior in react-native in general, it is not specific to expo.
