### ISSUE TITLE
App not connecting through fiddler after upgrade to 2.7.0

### ISSUE THREAD

**Issue by georgiosd** [expo/expo-cli#334]
Hi,

I've just upgraded to `expo-cli` 2.7.0 and the Expo app auto updated too. It seems that if I enable a fiddler proxy on the wifi of the phone, that the app (android build) can no longer access the network. It was working fine last week. 

Is anyone else seeing this or am I going insane?

Thanks

**Comment by brentvatne** [comment]
hey! sorry there was no reply to this. hopefully you figured it out. as far as i know we did not make any changes that would have impacted this so i suspect this was an intermittent/unrelated issue
