### ISSUE TITLE
Expo Electron Boilerplate

### ISSUE THREAD

**Issue by mtalhagaoglu** [expo/expo-cli#3347]
### Summary

Hi,

I want to create electron app with expo. the reason i want to use expo is to create mobile app also. i can do that separately but minimum coding is much better.

I tried expo's officall doc but it didn't work as expected. If there any boilerplate for expo-electron i would be verry happy.

### Environment

 Expo CLI 4.3.2 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 7.6.2 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 29.0.2
        System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
        Android NDK: 17.2.4988734
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.3.2
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

Windows 10

### Reproducible demo or steps to reproduce from a blank project

There is no...

**Comment by brentvatne** [comment]
https://github.com/expo/examples/tree/master/with-electron
