### ISSUE TITLE
Expo build failed - Error: ./gradlew exited with signal: SIGKILL

### ISSUE THREAD

**Issue by LuptonM** [expo/expo-cli#3352]
### Summary

Error: ./gradlew exited with signal: SIGKILL upon expo build:android

### Environment

  Expo CLI 4.3.2 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\Marc\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^40.0.1 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2
      react-native-web: ^0.15.0 => 0.15.0
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

Android

### Error output

 unimodules-task-manager-interface@5.4.0 from /app/turtle/workingdir/android/sdk40/packages/unimodules-task-manager-interface
Sat, 03 Apr 2021 17:00:51 GMT
Could not find google-services.json while looking in [src/nullnull/debug, src/debug/nullnull, src/nullnull, src/debug, src/nullnullDebug]
Sat, 03 Apr 2021 17:00:51 GMT
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Sat, 03 Apr 2021 17:00:51 GMT
Could not find google-services.json while looking in [src/nullnull/release, src/release/nullnull, src/nullnull, src/release, src/nullnullRelease]
Sat, 03 Apr 2021 17:00:51 GMT
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Sat, 03 Apr 2021 17:01:02 GMT
> Task :app:preBuild UP-TO-DATE
Sat, 03 Apr 2021 17:01:02 GMT
> Task :app:extractProguardFiles
Sat, 03 Apr 2021 17:01:02 GMT
> Task :app:preReleaseBuild
Sat, 03 Apr 2021 17:01:02 GMT
> Task :app:compileReleaseAidl NO-SOURCE
Sat, 03 Apr 2021 17:01:02 GMT
> Task :app:compileReleaseRenderscript NO-SOURCE
Sat, 03 Apr 2021 17:01:02 GMT
> Task :app:generateReleaseBuildConfig
Sat, 03 Apr 2021 17:01:03 GMT
> Task :app:generateReleaseResValues
Sat, 03 Apr 2021 17:01:03 GMT
> Task :app:generateReleaseResources
Sat, 03 Apr 2021 17:01:03 GMT
> Task :app:processReleaseGoogleServices
Sat, 03 Apr 2021 17:01:03 GMT
Parsing json file: /app/turtle/workingdir/android/sdk40/android-shell-app/app/google-services.json
Sat, 03 Apr 2021 17:01:11 GMT
> Task :app:createReleaseCompatibleScreenManifests
Sat, 03 Apr 2021 17:01:11 GMT
> Task :app:extractDeepLinksRelease
Sat, 03 Apr 2021 17:01:14 GMT
> Task :app:processReleaseManifest
Sat, 03 Apr 2021 17:01:14 GMT
/app/turtle/workingdir/android/sdk40/android-shell-app/app/src/main/AndroidManifest.xml:17:9-26:20 Warning:
Sat, 03 Apr 2021 17:01:14 GMT
	provider#expo.modules.filesystem.FileSystemFileProvider@android:authorities was tagged at AndroidManifest.xml:17 to replace other declarations but no other declaration present
Sat, 03 Apr 2021 17:01:14 GMT
> Task :app:prepareLintJar
Sat, 03 Apr 2021 17:01:14 GMT
> Task :app:mergeReleaseShaders
Sat, 03 Apr 2021 17:01:14 GMT
> Task :app:compileReleaseShaders NO-SOURCE
Sat, 03 Apr 2021 17:01:14 GMT
> Task :app:generateReleaseAssets UP-TO-DATE
Sat, 03 Apr 2021 17:01:16 GMT
> Task :app:mergeReleaseAssets
Sat, 03 Apr 2021 17:01:17 GMT
> Task :app:checkReleaseDuplicateClasses
Sat, 03 Apr 2021 17:01:17 GMT
> Task :app:processReleaseJavaRes NO-SOURCE
Sat, 03 Apr 2021 17:01:22 GMT
> Task :app:collectReleaseDependencies
Sat, 03 Apr 2021 17:01:22 GMT
> Task :app:sdkReleaseDependencyData
Sat, 03 Apr 2021 17:01:22 GMT
> Task :app:mergeReleaseJniLibFolders
Sat, 03 Apr 2021 17:01:24 GMT
> Task :app:mergeReleaseJavaResource
Sat, 03 Apr 2021 17:01:24 GMT
> Task :app:validateSigningRelease
Sat, 03 Apr 2021 17:01:24 GMT
> Task :app:javaPreCompileRelease
Sat, 03 Apr 2021 17:01:24 GMT
> Task :app:mergeReleaseResources
Sat, 03 Apr 2021 17:01:30 GMT
> Task :app:processReleaseResources
Sat, 03 Apr 2021 17:01:35 GMT
> Task :app:compileReleaseJavaWithJavac
Sat, 03 Apr 2021 17:01:35 GMT
> Task :app:compileReleaseSources
Sat, 03 Apr 2021 17:01:52 GMT
> Task :app:lintVitalRelease
Sat, 03 Apr 2021 17:01:52 GMT
> Task :app:mergeReleaseGeneratedProguardFiles
Sat, 03 Apr 2021 17:01:52 GMT
> Task :app:mergeReleaseNativeLibs
Sat, 03 Apr 2021 17:02:22 GMT
> Task :app:minifyReleaseWithR8
Sat, 03 Apr 2021 17:05:15 GMT
> Task :app:stripReleaseDebugSymbols
Sat, 03 Apr 2021 17:05:15 GMT
WARNING: Support for ANDROID_NDK_HOME is deprecated and will be removed in the future. Use android.ndkVersion in build.gradle instead.
Sat, 03 Apr 2021 17:05:15 GMT
Support for ANDROID_NDK_HOME is deprecated and will be removed in the future. Use android.ndkVersion in build.gradle instead.
Sat, 03 Apr 2021 17:05:45 GMT
> Task :app:packageRelease
Sat, 03 Apr 2021 17:05:50 GMT
Error: ./gradlew exited with signal: SIGKILL
    at ChildProcess.completionListener (/app/turtle/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:51:23)
    at Object.onceWrapper (events.js:418:26)
    at ChildProcess.emit (events.js:311:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
    ...
    at spawnAsync (/app/turtle/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at spawnAsyncThrowError (/app/turtle/node_modules/@expo/xdl/build/detach/ExponentTools.js:201:45)
    at buildShellAppAsync (/app/turtle/node_modules/@expo/xdl/build/detach/AndroidShellApp.js:976:11)
    at async Object.createAndroidShellAppAsync (/app/turtle/node_modules/@expo/xdl/build/detach/AndroidShellApp.js:396:5)
    at async runShellAppBuilder (/app/turtle/build/builders/android.js:95:9)
    at async Object.buildAndroid [as android] (/app/turtle/build/builders/android.js:43:28)
    at async build (/app/turtle/build/jobManager.js:181:33)
    at async processJob (/app/turtle/build/jobManager.js:118:32)
    at async Object.doJob (/app/turtle/build/jobManager.js:49:5)
    at async main (/app/turtle/build/server.js:66:13)

### Reproducible demo or steps to reproduce from a blank project

expo build:android

**Comment by umbertoghio** [comment]
Got the same issue while building on expo 41 on Android. 
@LuptonM did you managed to get a build?

**Comment by umbertoghio** [comment]
Really weird, I attempted a second build right away and it completed successfully

**Comment by LuptonM** [comment]
I got it built in the end.

I think there was something broken on the expo end as it ran the second time

**Comment by brentvatne** [comment]
we're tracking this in https://github.com/expo/expo/issues/12574
