### ISSUE TITLE
Broken preview link

### ISSUE THREAD

**Issue by SaadRegal** [expo/expo-cli#338]
## Description

After running `expo start` on a blank project, the cli generate a broken link  

## Expected Behavior

exp://192.168.137.1:19000

## Observed Behavior

exp69d2818b57134987cbe5d00a0da9cb27://192.168.137.1:19000

## Environment

Expo CLI 2.7.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.10.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**Comment by swang** [comment]
I too am experiencing this behavior. Cost me over an hour of time trying to figure out why creating a new app couldn't even get loaded. Have to revert to v2.7.0 to get it working again. :|
