### ISSUE TITLE
Logs are not being sent to the Expo CLI

### ISSUE THREAD

**Issue by AlexIsOK** [expo/expo-cli#3380]
### Summary

I'm not sure what happened, but the logs are not being sent to Expo CLI anymore.  I have console log statements everywhere just to test this.  The only logs I get from testing are "Finished building JavaScript bundle in ms." type messages.

On my phone (using Expo Go iOS) I see errors and warnings that were intentionally put there, but nothing is being logged to my terminal.

### Environment

  Expo CLI 4.3.5 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\Alexander\AppData\Roaming\npm\yarn.CMD
      npm: 7.9.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

iPhone 7+ 14.5 using Expo Go app.

### Reproducible demo or steps to reproduce from a blank project

I have no idea how this started.

**Comment by brentvatne** [comment]
are you able to reproduce this issue on a blank project?

**Comment by AlexIsOK** [comment]
no, should i clear some caches or something?  if so, what directories?

**Comment by brentvatne** [comment]
have you possibly modified metro.config.js recently and overwritten sourceExts? see https://docs.expo.io/guides/customizing-metro/

**Comment by AlexIsOK** [comment]
@brentvatne i have not modified it manually, though i don't have a sourceExts in my metro

```json
config.module.exports = {
  transformer: {
    assetPlugins: ['expo-asset/tools/hashAssetFiles'],
  },
};
```

additionally, any buttons i press in the program don't seem to activate at all, and scrolling is broken as well.  seems like this might be more of a react native problem than anything.

**Comment by brentvatne** [comment]
you should try some good ol fashion manual debugging here https://expo.fyi/manual-debugging

**Comment by AlexIsOK** [comment]
i didn't change anything for this to happen.  nothing changed on my end, i changed zero code and ran zero commands.  it just stopped working.

**Comment by brentvatne** [comment]
@AlexIsOK - you can verify that by following some instructions in that doc, eg: "Verify that you can run your app on a previously working commit" - if you check out an old commit where you are 100% sure that everything was working well in your app, then run npm install/yarn install on that commit, and try to boot up your app again - will logs work there?

**Comment by AlexIsOK** [comment]
fixed it.  apparently i changed `registerRootComponent(App)` to `AppRegistry.registerComponent()` or something.

realized this when some fonts weren't loading, thank you for the help though :D
