### ISSUE TITLE
Error extracting /home/user/.npm/expo/32.0.1/package.tgz archive: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by inquiloper** [expo/expo-cli#339]
Hello. I'm trying to install the expo-cli to get started with react native. I tried using expo init and I encounter this error. In windows 10 and in ubuntu 18.04

My npm version is: 3.5.2
Nodejs: 8.10.0

**Comment by AdamJNavarro** [comment]
Hey @inquiloper,

Your npm version is 3 years old. It may not be the fix but is it possible for you to upgrade to a more recent version and give it another try?

Cheers,

Adam
