### ISSUE TITLE
Custom expo client fails to build

### ISSUE THREAD

**Issue by shauns** [expo/expo-cli#3394]
### Summary

After running `expo client:ios` the build process fails upon signing the IPA. It puts together the following provisioning profile mapping:

```
{:"dev.expo.client.ejkkzmzjp3u2ejuwvnnjdudceterwqdjozcbooakcbcuw"=>"15d35432-78b6-46d9-90d0-b4c433502100", :"host.exp.Exponent"=>"match AppStore host.exp.Exponent", :"host.exp.Exponent.ExpoNotificationServiceExtension"=>"match AppStore host.exp.Exponent.ExpoNotificationServiceExtension"}
```

In our profile list we end up with an AppStore profile for our released app, and an AdHoc profile for `*[expo] dev.expo.client.xxxxxxx...`, but there is no profile matching those secondary bundle IDs of `host.exp.Exponent` and `host.exp.Exponent.ExpoNotificationServiceExtension`. Given the provisioning profile is configured during the run of `client:ios` I've raised this issue rather than as part of the general expo project.

Building a custom IPA has worked fine for us the last time we did it (circa 2 months ago), but we're now getting the above issue consistently.

So, perhaps this is a regression. Unfortunately the logs from the successful build are expired now so nothing to compare to.

### Environment

```
  Expo CLI 4.4.1 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.3.0 - ~/.nvm/versions/node/v15.3.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.0.14 - ~/.nvm/versions/node/v15.3.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.4.1
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

iOS 13.7

### Error output

The `client:ios` command doesn't provide any explicit error message.

### Reproducible demo or steps to reproduce from a blank project

`expo client:ios`

**Comment by shauns** [comment]
My personal digging led to https://github.com/expo/expo/pull/12288 as a possible cause -- I don't really know enough about how the custom client is built but if its based on the "main" app's source code directly then this could be a point of divergence.

**Comment by brentvatne** [comment]
hi @shauns! we're planning on rolling back the custom ios client. to the sdk 40 version, and we will no longer support in sdk 41+. we're working on a much better version of this, with support for adding custom native modules, but it's not quite ready yet.  for cases where you are depending on using the custom client for testing, i suggest using `expo build:ios -t simulator` instead - it only takes ~2 minutes to do a build and you can install in your simulator and test directly there.

let me know what you think

**Comment by shauns** [comment]
Thanks for getting back to me. Definitely cool to see what's coming later. Seems like the DX between managed and non-managed workflow are drawing closer (and distinctions beginning to blur).

Our main app is quite location & (google) map heavy so the custom client works really well for dev and running the occasional long lived release channel. Simulator doesn't really do the trick for our feature set. We're needing to build the custom client as not all the team members have it installed and the build artefact has now expired.

So I think my options in the near term are:
1. Somehow get a hold of the 2m old IPA file and distribute to those who don't have it - annoyingly their device ids were part of the profile, I just don't have the build any more.
2. Switch our dev process to be more oriented around ad-hoc build of our main app/different bundle Id+release channel via TestFlight
3. Build the custom client locally via Xcode - it's pretty close to a one-off need so I don't mind that... if I can work out how!

Appreciate the raised issue is likely to be superseded rather than resolved but did wonder if you had a steer on what approach you'd recommend in the meantime?

**Comment by brentvatne** [comment]
> Thanks for getting back to me. Definitely cool to see what's coming later. Seems like the DX between managed and non-managed workflow are drawing closer (and distinctions beginning to blur).

yeah! looking forward to that

> Our main app is quite location & (google) map heavy so the custom client works really well for dev and running the occasional long lived release channel. Simulator doesn't really do the trick for our feature set. We're needing to build the custom client as not all the team members have it installed and the build artefact has now expired.
> [options]
> Appreciate the raised issue is likely to be superseded rather than resolved but did wonder if you had a steer on what approach you'd recommend in the meantime?

if you stay on sdk 39 or sdk 40, you can keep using custom clients indefinitely -- i just rolled back our release so the latest version of the custom client on our build server is for sdk 40.

will this work for you?

**Comment by shauns** [comment]
Absolutely - that would work great. Thanks so much for your help.

**Comment by brentvatne** [comment]
great. the rollback is complete so now you should be able to do a build again. let me know if anything goes wrong
