### ISSUE TITLE
npm install --global expo-cli: No matching version found for @expo/dev-tools@0.13.94.

### ISSUE THREAD

**Issue by costadaniel** [expo/expo-cli#3406]
### Description
```
npm install --global expo-cli
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @expo/dev-tools@0.13.94.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```
### More info

No output running `npm view @expo/dev-tools@0.13.94. version`

### Environment
```
node -v                      
v14.15.4
npm -v                       
7.10.0
```

**Comment by brentvatne** [comment]
try running `npm i -g expo-cli` again. npm registry has been very flakey recently. you can always double check that the version that is not being found is actually on the registry by going to the package page on npmjs.com

<img width="704" alt="Screen Shot 2021-04-21 at 8 14 42 AM" src="https://user-images.githubusercontent.com/90494/115577908-a81ac000-a279-11eb-93cf-b10de725ae96.png">

i don't think that there is anything we can do about npm registry issues, so closing
