### ISSUE TITLE
app.config.ts cannot import from other modules

### ISSUE THREAD

**Issue by awinograd** [expo/expo-cli#3408]
I'm trying to migrate my expo config from static files to a dynamic config. I currently have multiple apps, each with their own config, eg:

app1.config.json
app2.config.json

I'd like to setup my dynamic config like so:

app1.config.ts
app2.config.ts

```ts
// app.config.ts

import { ExpoConfig, ConfigContext } from '@expo/config';

import app1 from './app1.config.ts';
import app2 from './app2.config.ts';

export default function ({...rest}: ConfigContext): ExpoConfig {
  return determineApp() ? app1 : app2;
}
```

when running `expo config` i get the following error: `Error: Cannot find module './app1.config.ts`

It looks like evalConfig doesn't support importing other files (js or ts), rather it only supports requiring json files. Is that intended?

**Comment by awinograd** [comment]
Maybe related to https://github.com/expo/expo-cli/issues/2782

**Comment by brentvatne** [comment]
we only transpile the entry app.config.ts, anything else needs to be js. you can change app1 and app2 to json or config.js and they will work

**Comment by awinograd** [comment]
@brentvatne thanks for the clarification. For those who find this issue in the future, it needs to be js directly interpretable by node, b/c as @brentvatne says above, no other files are transpiled

**Comment by brentvatne** [comment]
@awinograd - care to open a pr to docs related to this to clarify?

**Comment by awinograd** [comment]
sure thing @brentvatne https://github.com/expo/expo/pull/12647
