### ISSUE TITLE
"expo"

### ISSUE THREAD

**Issue by AdemCanCertel** [expo/expo-cli#3410]
I'm doing a React Native mobile app project but I'm getting an expo error, is this a problem everyone has?

https://i.imgur.com/pDI6E7I.png

**Comment by AdemCanCertel** [comment]
Now it gives another error.
https://i.imgur.com/mM9u3qQ.png

**Comment by brentvatne** [comment]
hi there! you should read about how to set up npm properly on your windows machine. this is out of the scope for what we can help with here.

**Comment by brentvatne** [comment]
this is probably a good guide to follow: https://docs.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-windows
