### ISSUE TITLE
expo-cli not working with node v.16.0.0

### ISSUE THREAD

**Issue by sancodes** [expo/expo-cli#3412]
expo-cli not compatible with node v.16+

**Comment by sancodes** [comment]
expo-cli has not yet been tested against Node.js v16.0.0.

* >=10.13.0 <11.0.0 (Maintenance LTS)
* >=12.13.0 <13.0.0 (Maintenance LTS)
* >=14.0.0 <15.0.0 (Active LTS)
* >=15.0.0 <16.0.0 (Current Release)

**Comment by brentvatne** [comment]
it's just a warning, you can still use expo-cli with node 16. if not, let me know what problems you encounter. we haven't explicitly tested against node 16 yet.

**Comment by sancodes** [comment]
> it's just a warning, you can still use expo-cli with node 16. if not, let me know what problems you encounter. we haven't explicitly tested against node 16 yet.

Takes too long to run and eventually fails with the error: 
```
Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (node:internal/fs/watchers:204:21)
```

**Comment by brentvatne** [comment]
it sounds like you didn't install watchman: https://docs.expo.io/get-started/installation/#1-expo-cli

**Comment by sancodes** [comment]
Fixed! 
Thank you.

**Comment by sancodes** [comment]
Is there a way I can contribute to test expo for the recent node v.16 ?
