### ISSUE TITLE
`expo publish` error

### ISSUE THREAD

**Issue by dlenskyi** [expo/expo-cli#3414]
Hey, I cannot publish my project to expo, and error is empty. Here is an error:
```
> expo publish                    

› Expo SDK: 41.0.0
› Release channel: default
› Workflow: Managed

Building optimized bundles and generating sourcemaps...
{}

>
```
Can someone pls help how to fix it? Error is an empty object

```
Expo CLI 4.4.3 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      npm: 6.14.6 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.3, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.4.3
    Expo Workflow: managed
```

**Comment by brentvatne** [comment]
can you share a project that we can reproduce this with?

**Comment by dlenskyi** [comment]
@brentvatne 
Output with EXPO_DEBUG=1
```
➜  src git:(dev) ✗ EXPO_DEBUG=1 expo publish

› Expo SDK: 41.0.0
› Release channel: default
› Workflow: Managed

Building optimized bundles and generating sourcemaps...

Publish Assets:
- Asset target: managed

{}

```

BTW, this morning I successfully published my project (and all days before today), and today it failed. I checked everything that I changed, and, honestly, nothing could affect expo-cli.

About project, unfortunately, I cannot share with it, its commercial

**Comment by brentvatne** [comment]
can you try checking out an old commit that you published on to see if it works? you can publish to another release channel so it doesn't impact your production app, eg: `expo publish --release-channel testing-publish`

also can you share your app config? (app.json/app.config.js - please redact any sensitive strings)

we can add more verbose logging around this with the EXPO_DEBUG flag to try to get more info also.

**Comment by dlenskyi** [comment]
@brentvatne so stupid...
In locale json file I forgot to remote trailing comma, that crashed my project for publishing.. so sorry for stupid mistake!
But if would be nice if Expo could show error on publishing, and not just `{}`, because I didn't understand what went wrong
