### ISSUE TITLE
`expo init` with `--config` flag not working?

### ISSUE THREAD

**Issue by samcorcos** [expo/expo-cli#342]
## Description

I've been trying to generate a new Expo project using a simple script that avoids the interactivity in the terminal, but I've hit a snag with the `--config` flag, which does not appear to recognize the `app.json` path that I'm feeding it.

I've tried this using both `npx` and the globally installed `expo-cli`

An example command: 

`expo init -n MyApp -t blank --workflow managed --config app.json --npm`

I've tried all of these configurations for the `app.json` file, but none seem to work, and there are no errors being logged:

```
{
  "expo": {
    "name": "My app",
    "slug": "my-app"
  }
}
```

```
{
  "name": "My app",
  "slug": "my-app"
}
```

```
{
  "name": "My App",
  "displayName": "my-app"
}
```

## Expected Behavior

I would expect the CLI to recognize the `app.json` file I'm giving it.

## Observed Behavior

The `--config` flag appears to be ignored and nothing is logged.

## Environment

```
  Expo CLI 2.7.1 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.7.0 - /usr/local/bin/node
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.7.1
```

Also specify:

No emulators

## Reproducible Demo

1. create an `app.json` file, and add configurations
2. run `expo init -n MyApp -t blank --workflow managed --config app.json --npm`

**Comment by fson** [comment]
Hey, `expo-cli@2.10.0` was just released and it adds these command line flags to `expo init` to make it possible to use it in non-interactive mode:
```
    --name [name]                   The name of your app visible on the home screen.
    --android-package [name]        The package name for your Android app.
    --ios-bundle-identifier [name]  The bundle identifier for your iOS app.
```
For example, to initialize an app using the managed workflow, you can now run:
```
expo init my-app --non-interactive --template blank --workflow managed --name MyApp
```

Unfortunately the `--config` flag was meant for a different use case (to specify a custom config file path in an existing project) and `init` didn't read its value or the configuration within, even though it accepted the flag. The `--config` flag has now been removed from commands that don't use it.
