### ISSUE TITLE
Error for build:ios authenticating with Apple Developer Portal

### ISSUE THREAD

**Issue by ianmelendez95** [expo/expo-cli#3432]
# Summary

Receiving the following error message when attempting `expo build:ios -t archive`

> Authentication with Apple Developer Portal failed!
> An unexpected error occurred while completing authentication
> AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: An unexpected error occurred while completing authentication

Here's the full output, redacted identifiable info with '***'

```
$ expo build:ios -t archive
Checking if there is a build in progress...

Accessing credentials for *** in project ***
✔ Do you have access to the Apple account that will be used for submitting this app to the App Store? … yes

› Log in to your Apple Developer account to continue
✔ Apple ID: … ***
› Restoring session ***
› Team ***
› The password is only used to authenticate with Apple and never stored on EAS servers
  Learn more.
✔ Password (for ***): … ***
› Saving Apple ID password to the local Keychain
  Learn more.
✔ Logged in New session
› Team ***
Authentication with Apple Developer Portal failed!
An unexpected error occurred while completing authentication
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: An unexpected error occurred while completing authentication
    at loginWithUserCredentialsAsync (/***/node/v14.16.0/lib/node_modules/expo-cli/src/appleApi/authenticate.ts:141:3)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at loginAsync (/***/node/v14.16.0/lib/node_modules/expo-cli/src/appleApi/authenticate.ts:92:12)
    at authenticateAsync (/***/node/v14.16.0/lib/node_modules/expo-cli/src/appleApi/authenticate.ts:152:23)
    at Context.ensureAppleCtx (/***/node/v14.16.0/lib/node_modules/expo-cli/src/credentials/context.ts:85:24)
```

## Troubleshooting Undertaken

1. Signed into all available Apple services (Apple Developer, iTunes, Apple ID) to ensure there aren't missing terms of services or other items needing attention
2. Ran `expo` command as root
3. Cleared credentials
4. Tried both device and sms 2FA

## Workaround

Running with the `--skip-credentials-check` flag allowed us to build (e.g. `expo build:ios -t archive --skip-credentials-check`). This worked for us since we had already successfully setup credentials before the error started happening.

**Comment by terrierscript** [comment]
I got same error.

I can login and build on expo-cli@4.0.17, but error occurred on 4.4.3(latest)

I try to run `expo build:ios -c`, but credentials not clear

**Comment by dawnerd** [comment]
Yeah this is currently blocking me too :\

`UnexpectedAppleResponse: unexpected error occurred` isn't very helpful either.

2FA maybe?

**Comment by brentvatne** [comment]
expo-cli has supported 2fa for years, so that isn't the issue. if you are blocked by this then roll back to the version of expo-cli that you last built with. you can also try changing your password, i've heard one user say that for some reason having mixed cases didn't work for them (unclear why this is the case - most people have this - most likely it was a typo on their part or an issue with their shell).

**Comment by brentvatne** [comment]
@dawnerd - any update?

**Comment by AlastairTaft** [comment]
I got this error while I had another app uploading in Transporter. Not sure if it is related.

**Comment by EvanBacon** [comment]
Rolling a new version soon which just forwards the Apple internal server error, perhaps it can add more information.

**Comment by brentvatne** [comment]
closing this because this was likely just an error with apple's api, @EvanBacon's changes will provide the relevant context from the response that apple provides, it may be useful to debug what is wrong
