### ISSUE TITLE
Stop modifying existing tsconfigs that are complete

### ISSUE THREAD

**Issue by gabrielpetersson** [expo/expo-cli#3435]
I have a top level tsconfig like such
```
{
  "compilerOptions": {
    "target": "esnext",
    "lib": ["esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noImplicitAny": true,
    "noEmit": true,
    "pretty": true,
    "inlineSourceMap": true,
    "jsx": "react-native"
  },
  "exclude": [
    "**/node_modules",
    "babel.config.js",
    "metro.config.js",
    "jest.config.js",
    "build"
  ]
}

```

And a local one for my expo project that extends this as such 
```
{
  "extends": "../tsconfig.json",
  "include": ["./src"],
}

```

On every run, my local config gets overwritten by expo into
```
{
  "extends": "../tsconfig.json",
  "include": ["./src"],
  "compilerOptions": {
    "jsx": "react-native",

    "allowJs": true,
    "skipLibCheck": true,
    "noEmit": true,
    "allowSyntheticDefaultImports": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "moduleResolution": "node"
  }
}


```

Is there any way to stop this from happening

**Comment by EvanBacon** [comment]
https://docs.expo.io/guides/typescript/#base-configuration

> You can disable the TypeScript setup in Expo CLI with the environment variable EXPO_NO_TYPESCRIPT_SETUP=1

**Comment by brentvatne** [comment]
one way to maybe clarify this a bit more, if you'd like to open a pr @gabrielpetersson, is to change the message when this happens from:

> TypeScript: The tsconfig.json has been updated (Use EXPO_NO_TYPESCRIPT_SETUP to skip)

to

> TypeScript: The tsconfig.json has been updated (Use EXPO_NO_TYPESCRIPT_SETUP=1 to skip)
