### ISSUE TITLE
expo export error: unknown option `--force'

### ISSUE THREAD

**Issue by chmac** [expo/expo-cli#3447]
The [docs](https://docs.expo.io/workflow/expo-cli/#expo-export) include the option `--force`:

    -f, --force | Overwrite files in output directory without prompting for confirmation

This option was part of our build scripts and so was definitely supported by previous expo-cli releases. It seems like since I upgraded to the latest expo-cli (4.4.3) this option doesn't exist any more? At least, I get the following error when I try to run `expo export`:

    error: unknown option `--force'

Also, now running `expo export --help` does not include `--force` as an option:

```
expo export --help

  Usage: export [path] [options]

  Export the static files of the app for hosting it on a web server

  Options:

    -p, --public-url <url>  The public url that will host the static files. (Required)
    -c, --clear             Clear the Metro bundler cache
    --output-dir <dir>      The directory to export the static files to. Default directory is `dist` (default: dist)
    -a, --asset-url <url>   The absolute or relative url that will host the asset files. Default is './assets', which will be resolved against the public-url. (default: ./assets)
    -d, --dump-assetmap     Dump the asset map for further processing.
    --dev                   Configure static files for developing locally using a non-https server
    -s, --dump-sourcemap    Dump the source map for debugging the JS bundle.
    -q, --quiet             Suppress verbose output.
    -t, --target [env]      Target environment for which this export is intended. Options are `managed` or `bare`.
    --merge-src-dir [dir]   A repeatable source dir to merge in. (default: )
    --merge-src-url [url]   A repeatable source tar.gz file URL to merge in. (default: )
    --max-workers [num]     Maximum number of tasks to allow Metro to spawn.
    --experimental-bundle   export bundles for use with EAS updates.
    --config [file]         Deprecated: Use app.config.js to switch config files instead.
    -h, --help              output usage information
```

**Comment by EvanBacon** [comment]
Sorry, I can update the docs. The `expo export` script is like `expo build:web`, `next export`, and other web build scripts... in all of these scripts the command just deletes the previous results by default, so it seemed odd that expo cli required you to manually define it. As a result we removed the `force` flag and made force the default and only option. If you want to save a previous build, you'll need to move the current build or change `--output-dir`.

We still have the "previous changes will be overwritten ... deleting files..." logs when you overwrite the current changes in subsequent runs, but this is just to make it a bit clearer to users that this behavior is default now.
