### ISSUE TITLE
"Associated Domains" not added to Expo created App ID

### ISSUE THREAD

**Issue by LinusU** [expo/expo-cli#3448]
When Expo creates a new App ID (e.g. when running `expo build:ios` for the first time) the "Associated Domains" entitlement isn't added even when `expo.ios.associatedDomains` is present in the `app.json` config file.

Because of this, the first build will result in an invalid ipa that we cannot submit to Apple.

In order to fix this we need to do several manual steps:

1. Login to `developer.apple.com`
2. Find the App ID
3. Add the "Associated Domains" entitlement
4. Acknowledge that current provisioning profiles will stop working
5. Run `expo build:ios` again with the `--clear-provisioning-profile` flag

It would be a large timesaver for us if the proper entitlements could be added up front.

If there is anything I can do to help fix this I would be very happy to! Just point me in the right direction and I'll work on it 👨‍🔧

**Comment by brentvatne** [comment]
indeed this is not supported yet, so we explain this same process in docs: https://docs.expo.io/guides/linking/#expo-configuration

there are two pieces here: add the capability to the identifier and add the entitlement to the app. let's look at how this works for notifications.

here's where we sync the notifications capability with apple: https://github.com/expo/expo-cli/blob/522b989a1c5bf6cb88ecdd7330dd50ae4fc99857/packages/expo-cli/src/appleApi/ensureAppExists.ts#L74-L87

here's where we set it in a config-plugin on apps built with `eas build`: https://github.com/expo/expo-cli/blob/522b989a1c5bf6cb88ecdd7330dd50ae4fc99857/packages/config-plugins/src/plugins/unversioned/expo-notifications.ts#L22-L27

apps built with `expo build` use this: https://github.com/expo/xdl/blob/9596171a45c5431cb44082c80d17fd92273c87b8/packages/xdl/src/detach/IosCodeSigning.js#L208

i'm not sure that we want to patch `expo build` to handle this automatically, but i'd be interested in adding support for this to eas build.

**Comment by EvanBacon** [comment]
@LinusU I can take this one on.

**Comment by LinusU** [comment]
@EvanBacon I'm so sorry that I missed following up on this. Thank you for fixing it so quickly 🐎
