### ISSUE TITLE
Steps for using Gatsby result in failure

### ISSUE THREAD

**Issue by ezekiel747** [expo/expo-cli#3451]
Hi, i'm trying to follow the steps here https://docs.expo.io/guides/using-gatsby/
Using expo 41 (latest at the moment of writing this)

> npm install --save gatsby gatsby-plugin-react-native-web
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: undefined@undefined
> npm ERR! Found: react-native-web@0.13.18
> npm ERR! node_modules/react-native-web
> npm ERR!   react-native-web@"^0.13.18" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer react-native-web@"^0.11.7" from gatsby-plugin-react-native-web@3.1.0
>

**Comment by jung-youjin** [comment]
@ezekiel747  Hi did you solve this issue?

**Comment by ezekiel747** [comment]
i did manage to install, but i don't remember exactly how: i think either with npm resolutions for dependency, or specifying an older version.

However due to other issues i encountered i went with nextjs plugin instead.

**Comment by sarahannnicholson** [comment]
Plugin maintainer for `gatsby-plugin-react-native-web` can no longer maintain the project. And it isnt compatible with Gatsby v3 or higher. 

See issue here: https://github.com/slorber/gatsby-plugin-react-native-web/pull/65#issuecomment-827751512 

If you're having issues installing you can try `npm install --save gatsby-plugin-react-native-web --legacy-peer-deps`.
