### ISSUE TITLE
Unable to create a custom iOS client

### ISSUE THREAD

**Issue by trajano** [expo/expo-cli#3452]
I used to be able to create a custom Expo Go client using `expo ios:client` but now when I try to access the link that is provided when executing the command I just get a blank screen.  Looking at the browser it appears to have a JavaScript error on the Expo page.

**Comment by brentvatne** [comment]
custom client isn’t supported on sdk 41+ - we’re moving away from this because we have other plans for the future. please use expo build:ios -t simulator to test anything. read more context in https://github.com/expo/expo-cli/issues/3394

**Comment by trajano** [comment]
Would permissions for Push Notifications work with the alternative?

**Comment by trajano** [comment]
Would permissions for Push Notifications work with the alternative?  Also I haven't upgraded to 41, I'm still on 40.  Though I updated to the most current CLI.

**Comment by brentvatne** [comment]
> Would permissions for Push Notifications work with the alternative?

can you elaborate on what you mean with this question?

**Comment by trajano** [comment]
The main reason for creating the custom client was to allow permissions for Push Notifications to work when you're testing on device.  Other than that there's no real reason to create a custom client AFAIK.

**Comment by brentvatne** [comment]
hmm i still don't understand. you can use permissions for push notifications in the regular expo go app from the app store

**Comment by trajano** [comment]
> Push Notifications
> Push Notifications are currently unavailable with ad hoc clients until we complete our work to add an extra authentication layer to the Expo Push Notification service.

From https://docs.expo.io/guides/adhoc-builds/

Note we just upgraded our CLI but not the SDK so we're still on SDK 40

**Comment by brentvatne** [comment]
@trajano - that is the opposite of what you're going for though - push notifications work on expo go but *not* with custom clients

**Comment by trajano** [comment]
Basically this code snippet is what no longer works

```
const getPushNotificationPermissions = async () => {
  const { status: existingStatus } = await Permissions.getAsync(Permissions.NOTIFICATIONS);
  let finalStatus = existingStatus;
  if (existingStatus !== 'granted') {
    const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
    finalStatus = status;
  }
  if (finalStatus !== 'granted') {
    Alert.alert('You need to enable permissions in settings to receive push notifications');
    return null;
  }
  return Notifications.getExpoPushTokenAsync();
};

```

For now I just changed my code to silently ignore the fact that the notification permissions are not enabled.

**Comment by brentvatne** [comment]
see this page for an example: https://docs.expo.io/versions/latest/sdk/notifications/#api

```
async function registerForPushNotificationsAsync() {
  let token;
  if (Constants.isDevice) {
    const { status: existingStatus } = await Notifications.getPermissionsAsync();
    let finalStatus = existingStatus;
    if (existingStatus !== 'granted') {
      const { status } = await Notifications.requestPermissionsAsync();
      finalStatus = status;
    }
    if (finalStatus !== 'granted') {
      alert('Failed to get push token for push notification!');
      return;
    }
    token = (await Notifications.getExpoPushTokenAsync()).data;
    console.log(token);
  } else {
    alert('Must use physical device for Push Notifications');
  }

  if (Platform.OS === 'android') {
    Notifications.setNotificationChannelAsync('default', {
      name: 'default',
      importance: Notifications.AndroidImportance.MAX,
      vibrationPattern: [0, 250, 250, 250],
      lightColor: '#FF231F7C',
    });
  }

  return token;
}
```

also "no longer works" is not very precise. what does it do?

**Comment by trajano** [comment]
In my case the permissions dialog does not show up.  Which was expected not to show on the Expo Go app hence why the custom client instructions were provided.

**Comment by brentvatne** [comment]
you need to uninstall and reinstall the app to see the permissions dialog again. it will only show up once, that is how ios works
