### ISSUE TITLE
Error Expo 41 -should NOT have additional property 'loading'.

### ISSUE THREAD

**Issue by montanojd** [expo/expo-cli#3458]
in expo build:android i get this error in expo 41
Error: Problem validating fields in app.json. See https://docs.expo.io/workflow/configuration/
 • should NOT have additional property 'loading'.

This is my app.json

{
  "expo": {
    "name": "app name",
    "description": "Made with react app builder",
    "slug": "appname",
    "privacy": "public",
    "version": "1.3021118",
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "platforms": [
      "ios",
      "android"
    ],
    "splash": {
      "image": "./assets/images/splash.png",
      "resizeMode": "cover",
      "backgroundColor": "#ffffff"
    },
    "extra": {
      "firebaseMetaPath": "/saasapps/4oxeGnlNpQbDXsSIHN3BI65VfFI2/appname"
    },
    "icon": "./assets/icons/app.png",
    "loading": {
      "icon": "./assets/icons/loading.png",
      "hideExponentText": false
    },
   
    "packagerOpts": {
      "assetExts": [
        "ttf",
        "mp4"
      ]
    },
    "ios": {
      "supportsTablet": false,
      "bundleIdentifier": "com.app.name",
      "infoPlist": {
        "NSPhotoLibraryUsageDescription": "This app save photos and videos to your Photo Library .",
        "NSUserTrackingUsageDescription": "This identifier will be used to deliver personalized ads to you.",
        "ITSAppUsesNonExemptEncryption": false
      }
    },
    "android": {
      "package": "com.app.name",
      "versionCode": 3021118,
      "permissions": [],
      "config": {
        "googleMaps": {
          "apiKey": "xxxx"
        }
      }
    }
  }
}

**Comment by EvanBacon** [comment]
`loading` is deprecated in favor of `splash`

**Comment by montanojd** [comment]
> `loading` is deprecated in favor of `splash`. Please remove the `loading` field from your app.json

I tried to remove it but the app doesn't start without this line.

**Comment by brentvatne** [comment]
@montanojd - sorry it's hard to say what could be wrong with your app. the `loading` field definitely deprecated and you should remove it, and removing it would have no impact on starting your app. when using any software development tool it's up to the developer to write code that works and it seems like in this case your code is not working. here's how you can maybe try debugging: https://expo.fyi/manual-debugging
