### ISSUE TITLE
Cannot eject any application: UnhandledPromiseRejectionWarning: spawn/bin/cp ENOENT

### ISSUE THREAD

**Issue by Judge24601** [expo/expo-cli#346]
## Description

Any application I try to eject, even the default one, receives this error, whether I start the project in "advanced" configuration or "standard" config and eject afterwards

## Expected Behavior

I ran the command "expo eject" and selected the ExpoKit option.

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the _full terminal output and error message_ in this code block:

```
(node:15828) UnhandledPromiseRejectionWarning: Error: spawn /bin/cp ENOENT
    at notFoundError (C:\Users\...\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\Users\...\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\Users\...\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
(node:15828) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
The system cannot find the path specified.
(node:15828) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
The system cannot find the path specified.
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:
  Expo CLI 2.7.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5199772

Also specify:

- Phone/emulator/simulator platform, model and version:
Shouldn't be relevant, no testing on any platform can be done
## Reproducible Demo

This is reproducible on 2 PCs (both dual-booting to Ubuntu, although I hope that's not the issue)
and 1 MacBook.
Simply run expo init,
choose tabs
and either choose advanced, or the standard then eject afterwards.

**Comment by 1046118935** [comment]
我也遇到了这个问题但是不知道怎么解决

**Comment by bunyaminmrcn** [comment]
Same issue . Not solved yet in windows . But , trying subsystem (ubuntu & node 10.5.1 & 1.13.0) works expected - No errors). Then you can move project into your windows

**Comment by brentvatne** [comment]
ejecting to expokit is deprecated now, `expo eject` on sdk37+ should work as expected on windows

**Comment by epixapp** [comment]
Same error when I run `expo eject` on SDK 37, with the latest Expo CLI 3.20.1:
```
√ App configuration (app.json) updated.
√ Created native project directories (./ios and ./android) and updated .gitignore.
√ Updated package.json and added index.js entry point for iOS and Android.
√ Installed JavaScript dependencies.
\ Applying iOS configuration The system cannot find the path specified.
spawn /bin/cp ENOENT
Error: spawn /bin/cp ENOENT
    at notFoundError (C:\Users\...\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\...\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\...\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```


`expo diagnostics`:
```
Expo CLI 3.20.1 environment info:
System:
  OS: Windows 10 10.0.18362
Binaries:
  Node: 13.11.0 - C:\Program Files\nodejs\node.EXE
  npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
npmPackages:
  expo: ^37.0.0 => 37.0.8
  react: ~16.9.0 => 16.9.0
  react-dom: 16.9.0 => 16.9.0
  react-native: ~0.61.5 => 0.61.5
  react-native-web: ^0.11.7 => 0.11.7
  react-navigation: ^3.0.4 => 3.13.0
```
Any idea?

**Comment by hatim85f** [comment]
Same issue with the same error code, more than 3 weeks I am rounding to find a something.... Anyone could find out ?


`Applying iOS configurationThe system cannot find the path specified.
spawn /bin/cp ENOENT
Error: spawn /bin/cp ENOENT
    at notFoundError (C:\Users\hatim_8pgcn2n\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\hatim_8pgcn2n\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\hatim_8pgcn2n\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)`



Expo CLI 3.21.5 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~37.0.3 => 37.0.12
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: ~0.61.5 => 0.61.5
      react-native-web: ~0.11.7 => 0.11.7

**Comment by dhiahassen** [comment]
still same error after 2 years , with "expo eject"

**Comment by brentvatne** [comment]
@dhiahassen - please post a new issue and share your `expo diagnostics` output along with a project where this happens for you. locking the issue because it's long been closed.
