### ISSUE TITLE
Executing expo export modifies AndroidManifest.xml

### ISSUE THREAD

**Issue by ex3ndr** [expo/expo-cli#3461]
I have unfortunate behaviour that i wasn't able to disable. I am using `expo-updates` with my own CDN and due some strange bugs i decided to put updates for each runtime version to separate folders to avoid accidentally pushing update to wrong folder and keep CDN fully stateless.

Unfortunatelly, it doesn't work well since i am unable to configure updates endpoint via gradle script because running `expo export` overwites current link in manifest that breaks my configuration and there are no way to disable this behaviour.

Expected behaviour: Not updating manifest or being able to disable this.

Suggestion for fix: Use gradle templating and allow gradle to resolve update url instead of writing to manifest.

**Comment by jkhales** [comment]
Hi! That is frustrating. To understand a bit more, is this new behaviour or is this a suggestion for improvement?

**Comment by ex3ndr** [comment]
This is current behaviour on current expo/expo-cli libraries, it works fine until you start to hack around with updates :) I suggest at least be able to avoid modification of manifest and there are no such behaviour for ios, only on Android.

**Comment by jkhales** [comment]
> This is current behaviour on current expo/expo-cli libraries, it works fine until you start to hack around with updates :) I suggest at least be able to avoid modification of manifest and there are no such behaviour for ios, only on Android.

OK great, I am going to look into fixing this for you.

**Comment by brentvatne** [comment]
maybe this would be well suited for an env var, and i think if we make it possible to opt-out of this behavior in export we should do the same for publish

**Comment by zlwu** [comment]
Any progress on this topic?

**Comment by ex3ndr** [comment]
Yeah, I already hit this issue in three different companies :( Almost everyone need some native modules and therefore ejected and begin to manually track runtime version.

**Comment by jkhales** [comment]
Haven't forgotten about this! Just a lot of thing in the "TODO" box!

**Comment by jkhales** [comment]
This is live as of expo-cli@4.11
