### ISSUE TITLE
Is there an error when building an ios app with a `bundleIdentifier` starting with a dot?

### ISSUE THREAD

**Issue by vallereaugabriel** [expo/expo-cli#3469]
Hi, after solving #3315 and #3429 (Thanks to @EvanBacon), I now can see the full run of `expo build:ios`. Build is queued and then, the second it starts, the build fails with no logs available in `expo.io` and nothing more in terminal:

```
Waiting for build to complete.
You can press Ctrl+C to exit. It won't cancel the build, you'll be able to monitor it at the printed URL.
✖ Build failed.
Standalone build failed!
```

Apart from the `bundleIdentifier` I changed nothing else and I have a previous build that works fine. I'm using expo `40.0.0` and that issue might belong in `expo` repository rather than `expo-cli`.

Thanks in advance for the help.

**Comment by cruzach** [comment]
closing in favor of https://github.com/expo/expo-cli/issues/3592
