### ISSUE TITLE
Your project is in SDK version >= 33.0.0, but the expo package version seems to be older.

### ISSUE THREAD

**Issue by georgeMorales** [expo/expo-cli#3470]
Yesterday I updated expo cli and this warning appeared on the console.
I have deleted node_modules and yarn.lock as it says here https://forums.expo.io/t/your-project-is-in-sdk-version-33-0-0-but-the-expo-package-version- seems-to-be-older / 32065 but it doesn't work, neither does this work https://stackoverflow.com/questions/59862639/your-project-is-in-sdk-version-33-0-0-but-the- expo-package-version-seems-to
Sdk 41

Expo CLI 4.4.4 environment info:
    System:
      OS: Linux 4.15 Ubuntu 16.04.7 LTS (Xenial Xerus)
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.5.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 23, 25, 26, 27, 28, 29
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3, 29.0.2
        System Images: android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.4.4
    Expo Workflow: managed

**Comment by amber-pli** [comment]
This is because build/commands/utils/validateDependenciesVersions.js throws Error: `Cannot find module 'nullthrows'`. I have workaround this issue by `npm i -g nullthrows`

**Comment by EvanBacon** [comment]
fixed in ab8843a81effd66b418f800ba73c6af40e7eec56
