### ISSUE TITLE
 expo-cli has not yet been tested against Node.js v16.1.0

### ISSUE THREAD

**Issue by Alexander1309** [expo/expo-cli#3475]
WARNING: expo-cli has not yet been tested against Node.js v16.1.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=10.13.0 <11.0.0 (Maintenance LTS)
* >=12.13.0 <13.0.0 (Maintenance LTS)
* >=14.0.0 <15.0.0 (Active LTS)
* >=15.0.0 <16.0.0 (Current Release)

What can I do to solve the problem?...

**Comment by brentvatne** [comment]
removed this warning in latest version
