### ISSUE TITLE
Unable to resolve 'EXUpdates/EXUpdatesAppController.h' file not found error on Xcode 12.3

### ISSUE THREAD

**Issue by sachin-blinkdigital** [expo/expo-cli#3480]
Podfile: -

platform :ios, '11.0'
project 'chakraapp.xcodeproj'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

target 'chakraapp' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path

 
  use_flipper!({ 'Flipper' => '0.88.0'})
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
     end
  end
end  

package.json: - 

{
  "main": "index.js",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@expo/vector-icons": "^12.0.0",
    "@react-native-community/datetimepicker": "^3.4.7",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/picker": "^1.6.5",
    "@react-native-community/push-notification-ios": "^1.8.0",
    "@react-navigation/bottom-tabs": "^5.7.2",
    "@react-navigation/native": "^5.7.1",
    "@react-navigation/stack": "^5.7.1",
    "apisauce": "^1.1.1",
    "asap": "^2.0.6",
    "expo": "^41.0.0",
    "expo-asset": "~8.3.1",
    "expo-cli": "^4.4.3",
    "expo-constants": "~10.1.3",
    "expo-font": "~9.1.0",
    "expo-linking": "~2.2.3",
    "expo-secure-store": "~10.1.0",
    "expo-splash-screen": "~0.10.2",
    "expo-status-bar": "~1.0.4",
    "expo-updates": "^0.5.4",
    "expo-web-browser": "~9.1.0",
    "formik": "^2.1.5",
    "moment": "^2.27.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "0.63.4",
    "react-native-dropdown-picker": "^3.1.11",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-maps": "0.28.0",
    "react-native-push-notification": "^7.0.0",
    "react-native-razorpay": "^2.2.1",
    "react-native-reanimated": "~2.1.0",
    "react-native-safe-area-context": "3.2.0",
    "react-native-screens": "~3.0.0",
    "react-native-snap-carousel": "^4.0.0-beta.5",
    "react-native-unimodules": "~0.13.3",
    "react-native-version-check": "^3.4.2",
    "react-native-web": "~0.13.12",
    "yup": "^0.29.1"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-jest": "~25.2.6",
    "jest": "~25.2.6",
    "react-test-renderer": "~16.11.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}

I've tried all the available solutions over the internet but all sums at the mentioned error.

**Comment by brentvatne** [comment]
here are install instructions: https://docs.expo.io/bare/installing-updates/
