### ISSUE TITLE
"Couldn't find any builds for this project on Expo servers. It looks like you haven't run expo build:android yet"

### ISSUE THREAD

**Issue by Slapbox** [expo/expo-cli#3484]
But we have recent .apk and .aab builds available via Expo.io. Any ideas?

**Comment by Slapbox** [comment]
After the automated upload failed, we tried a manual upload using the Expo artifact URL but got:

> ✖ Something went wrong when submitting your app to Google Play Store.
> We couldn't figure out what went wrong. Please see logs to learn more.

Where would we find said logs?

**Comment by brentvatne** [comment]
please provide information so we can understand what you are talking about :)

**Comment by Slapbox** [comment]
I should have mentioned, this is when we run `expo upload:android`. Can you let me know what information would be helpful?

**Comment by brentvatne** [comment]
can you link me to one of your builds?

**Comment by Slapbox** [comment]
@brentvatne my bad, I forgot there's project pages that aren't publicly accessible. I was just thinking of the artifact URL privacy and how that is publicly accessible if shared.

Example problem build: https://expo.io/accounts/recollectr/projects/Recollectr/builds/d49cc94e-5e27-40ab-90e7-6a2666c0049d

**Comment by brentvatne** [comment]
any other information you can share? are you signed in as the same user that created the build? are you using token based authentication? do you have some dynamic app.config.js that changes the slug or package name?

**Comment by Slapbox** [comment]
Hey Brent. Unfortunately there's no more obviously relevant additional info I can think to share.

I confirmed we were signed in as the same user. We're not using token-based authentication. We don't have an `app.config.js` (I didn't know that was even a thing, cool!)

When I tried afterwards to upload by entering the `.aab` artifact URL itself, that failed too at first. I came back the next day and tried `expo upload:android` again and still Expo-CLI didn't find the build on the server, but this time when we tried entering the `.aab` artifact URL the upload process worked.

We do have some customizations in our `app.json`, but nothing new lately and nothing that stands out as relevant. In the distant past we manually appended `-Dev` to the end of our app name, and maybe slug, when we wanted to be sure that a fresh build wouldn't trigger an OTA for users. I don't know if that's even a valid concern, but just sharing any info I can, though I'm guessing that's not the sort of name change you had in mind.

**Comment by brentvatne** [comment]
@Slapbox - I just created a new project, built it with `expo build:android`, then ran `expo upload:android` and it detected the build. Are you maybe using different `app.json` files, like `app.prod.json` and `app.staging.json` or something?

**Comment by Slapbox** [comment]
Thanks for looking into this @brentvatne. I don't know what the issue could be, but I can say with certainty that we've only got the one, static `app.json` file. Hopefully it's just a one-off issue with that particular build job. I'll try rebuilding it some time soon.

Am I right to think that `expo build:android` is going to create an updated JavaScript bundle for the app, akin to `expo publish`, which will be pushed to users even if we don't upload the new binary to the Play Store? Or are those two commands entirely separated?

**Comment by brentvatne** [comment]
when you run `expo build:android` it will indeed publish a new bundle, more on how it works here https://blog.expo.io/expo-managed-workflow-in-2021-5b887bbf7dbb

**Comment by brentvatne** [comment]
are you using `owner` in app.json by chance?

**Comment by Slapbox** [comment]
Thanks for the info Brent! Alas, we're not using the `owner` field.

**Comment by brentvatne** [comment]
no idea what could be happening here but it seems to be something particular to your set up :\ i imagine you're using the latest expo-cli?

**Comment by Slapbox** [comment]
Looks like we were on `4.4.6` at the time we had the issue. I really can't think of anything that might be unique about our setup besides a custom `.babelrc`, which mostly replicates the Expo default and adds a few additional aliases.

Next time we would publish I'll try giving the package a build instead (with the latest `expo-cli`) to see if I can reproduce the issue. Thanks again Brent.

**Comment by Slapbox** [comment]
Small update on this. I gave it another go but had the same issue when doing things as I always have, which is:

1. Run `expo build:android` on my primary development machine (Windows)
2. Run `expo upload:android` from macOS because we need to upload the iOS version from there anyway

That gave me the same error. **So I setup the primary development machine with the appropriate API keys (same as on the macOS machine) and then tried `expo upload:android` and that worked fine.**

On macOS I noticed it prompts:

> Android package name: _____

I had tried our project name and the actual Android package name, but no dice either way.

Any ideas? Running the latest `expo-cli` on both machines (4.4.8.)

**Comment by brentvatne** [comment]
> I setup the primary development machine with the appropriate API keys (same as on the macOS machine) and then tried expo upload:android and that worked fine.

which api keys? the google services json?

> On macOS I noticed it prompts

are you signed in to the correct expo account?

**Comment by Slapbox** [comment]
Whoops sorry for the ambiguity! Yes the Google Services JSON. Definitely definitely signed into the right account. It's not a show stopper by any means, but it's a weird issue. If we're the only ones seeing it and we have a workaround, then ¯\_(ツ)_/¯

**Comment by brentvatne** [comment]
> On macOS I noticed it prompts:
>
> Android package name: _____

so you see this when you run `expo upload:android` on one machine but not another? this is strange because it should be read automatically from your app.json: https://github.com/expo/expo-cli/blob/522b989a1c5bf6cb88ecdd7330dd50ae4fc99857/packages/expo-cli/src/commands/upload/submission-service/android/AndroidSubmitCommand.ts#L73-L92

so, something isn't configured properly on that macos machine i believe. does `expo config --type public` work?

**Comment by Slapbox** [comment]
`expo config --type public` does work.

It now suddenly seems to find the package on the Expo servers from the problematic macOS machine. Maybe I was running it from one folder up from where I meant to, because just now it asked for the Google API key JSON path anew, which it hasn't in a long time. But if that's why it asked for the API key path anew, that would seem to imply that it's the directory we'd been using since before this issue began for us.

So anyway, after that I deliberately navigated to some random unrelated directory and tried `expo upload:android`. It asked for the API key path again, and then when it asked for the package name I entered exactly what was shown when running `expo config --type public` from the directory containing our `app.json`, but that portion of the issue persists:

> Couldn't find any builds for this project on Expo servers.

So it looks like maybe a usage error on my end + a bug in Expo CLI when handling manually entered package names?

**Comment by brentvatne** [comment]
i suspect it's the result of running it "one folder up from where [you] meant to". this shouldn't have any interaction with the "hidden" value.

**Comment by Slapbox** [comment]
If that's what happened then the feature to manually enter a package name should still work if you're signed in as the correct user though, right? Otherwise it would be good to return something like, "app.json file not detected."
