### ISSUE TITLE
Error 400 when build:android setting keystore manually.

### ISSUE THREAD

**Issue by bissolli** [expo/expo-cli#349]
Hi guys!

I believe there is an issue with the command `expo build:android -c`, since I am getting error 400 when setting the keystore manually.

We have an app previously built on phonegap and now migrated to React Native/Expo. We are trying to build the android .apk using the keystore we had before and we get the following error:

![image](https://user-images.githubusercontent.com/1808444/52191553-b4fc9600-285e-11e9-8c1b-ad05342e600c.png)

I know that the problem is not with my .keystore, since through `expo fetch:android:keystore` I've got the keystore generated by EXPO and it gives me the same error!

Using `expo build:android` works fine, but I can't deploy since the fingerprints doesn't match with the app I have already published.

Thanks!

**UPDATE**: The problem is with my user! Tried to do the same process with my friend's account and it worked all. Same app, same keystore, just different Expo account.
Still believe there is an issue with the service.

**Comment by zaytrix** [comment]
I am also running into this same issue, using simply `expo build:android`. If this is an account issue, I hope there is some way to fix it.

**Comment by AlastairTaft** [comment]
Hitting the same issue to, recently upgraded from v31 to v32.

**Comment by bissolli** [comment]
Guys,

There was an issue with expo-cli `2.7.1` and it's fixed on `2.7.2`. So just needed to update my cli version!

Do the same and it might work=)

**Comment by AlastairTaft** [comment]
Thanks @bissolli, that solves it.
