### ISSUE TITLE
`react-native/Libraries/Image/AssetRegistry`, the Haste package `react-native` was found. However the module `Libraries/Image/AssetRegistry` could not be found within the package

### ISSUE THREAD

**Issue by nandankushwaha** [expo/expo-cli#3505]
"dependencies": {
    "@expo/vector-icons": "^10.0.0",
    "@react-native-async-storage/async-storage": "^1.13.2",
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/drawer": "^5.8.4",
    "@react-navigation/native": "^5.6.1",
    "@react-navigation/stack": "^5.14.4",
    "expo": "^41.0.1",
    "expo-app-loading": "^1.0.3",
    "expo-asset": "~8.2.0",
    "expo-cli": "^4.4.3",
    "expo-font": "^9.1.0",
    "filter-obj": "^2.0.2",
    "lodash": "^4.17.15",
    "prop-types": "^15.7.2",
    "querystring": "^0.2.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz",
    "react-native-appearance": "^0.0.0",
    "react-native-elements": "3.3.2",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-paper": "^4.8.1",
    "react-native-reanimated": "^2.1.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.1.1",
    "react-native-swipe-list-view": "^3.2.6",
    "react-native-touchable-scale": "^2.1.1",
    "react-native-vector-icons": "^8.1.0",
    "react-native-web": "^0.16.1",
    "react-redux": "^7.2.4",
    "redux": "^4.1.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "source-map-support": "^0.5.19"
  },
  "devDependencies": {
    "@expo/webpack-config": "^0.12.16",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-preset-expo": "^8.3.0",
    "eslint": "^7.3.1",
    "gh-pages": "^2.1.1",
    "jest-expo": "^41.0.0",
    "typescript": "~3.9.2"
  },

Failed building JavaScript bundle.
While resolving module `react-native/Libraries/Image/AssetRegistry`, the Haste package `react-native` was found. However the module `Libraries/Image/AssetRegistry` could not be found within the package. Indeed, none of these files exist:

**Comment by brentvatne** [comment]
if you believe this is a bug then please post to https://github.com/expo/expo/issues and follow the issue template for a bug
