### ISSUE TITLE
QR code not displayed on published project's page

### ISSUE THREAD

**Issue by xavax31** [expo/expo-cli#3516]
Hi, 
like says title, the QR code is not displayed on my published project's page. It worked 5 days ago.
Only title and description is showed, and if I click on organisation name below (by ...), I got a 404 error despite the organisation exists.

<img width="500" alt="Capture d’écran 2021-05-25 à 12 41 29" src="https://user-images.githubusercontent.com/4051022/119485783-c9c70580-bd57-11eb-9f06-4ffd59f7d675.png">

**Comment by byCedric** [comment]
Hi @xavax31! Sorry for that, we added the QR code back. You should be able to see it on your project page.
