### ISSUE TITLE
No matching version found for @expo/config@3.3.43

### ISSUE THREAD

**Issue by ScRiPt1337** [expo/expo-cli#3518]
Unable install expo-cli 

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @expo/config@3.3.43.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\script\AppData\Local\npm-cache\_logs\2021-05-25T22_18_39_878Z-debug.log

C:\Users\script>npm config get registry
https://registry.npmjs.org/

C:\Users\script>npm view @expo/config versions
[
  '1.0.1',          '1.0.2',          '1.0.3',          '1.0.4',        
  '1.0.5',          '2.0.0',          '2.0.1',          '2.0.2',        
  '2.0.3',          '2.0.4',          '2.1.0',          '2.1.1',        
  '2.1.2',          '2.1.3',          '2.1.4',          '2.1.5-alpha.0',
  '2.1.5',          '2.1.6',          '2.2.0',          '2.3.0',        
  '2.4.0',          '2.5.0',          '2.5.1',          '2.5.2',        
  '2.5.3',          '2.5.4',          '2.5.5',          '2.5.6',        
  '2.5.7',          '2.6.0',          '2.6.1',          '2.6.2',        
  '2.6.3',          '2.6.4',          '2.6.5',          '2.6.6',        
  '2.7.0',          '3.0.0',          '3.0.1',          '3.0.2',        
  '3.0.3',          '3.0.4',          '3.0.5',          '3.0.6',        
  '3.0.7',          '3.0.8',          '3.1.0',          '3.1.1',        
  '3.1.2',          '3.1.3',          '3.1.4',          '3.2.0',        
  '3.2.1-alpha.0',  '3.2.1',          '3.2.2',          '3.2.3',        
  '3.2.4',          '3.2.5',          '3.2.6',          '3.2.7',        
  '3.2.8',          '3.2.9',          '3.2.10',         '3.2.11',       
  '3.2.12',         '3.2.13',         '3.2.14',         '3.2.15',
  '3.2.16',         '3.2.17',         '3.2.18',         '3.2.19',
  '3.2.20',         '3.2.21',         '3.2.22',         '3.3.0',
  '3.3.1',          '3.3.2',          '3.3.3',          '3.3.4',
  '3.3.5',          '3.3.6',          '3.3.7',          '3.3.8',
  '3.3.9',          '3.3.10',         '3.3.11',         '3.3.12',
  '3.3.13',         '3.3.14',         '3.3.15',         '3.3.16',
  '3.3.17',         '3.3.18',         '3.3.19',         '3.3.20',
  '3.3.21',         '3.3.22',         '3.3.23-alpha.0', '3.3.23',
  '3.3.24-alpha.0', '3.3.24',         '3.3.25',         '3.3.26',
  '3.3.27',         '3.3.28',         '3.3.29-alpha.0', '3.3.29',
  '3.3.30',         '3.3.31-alpha.0', '3.3.31',         '3.3.32',
  '3.3.33',         '3.3.34',         '3.3.35',         '3.3.36',
  '3.3.37',         '3.3.38',         '3.3.39',         '3.3.40',
  '3.3.41',         '3.3.42',         '3.3.43'
]

C:\Users\script>npm --version
7.14.0

**Comment by brentvatne** [comment]
https://www.npmjs.com/package/@expo/config

notice that the version listed on npm is `3.3.43`, published 10 hours ago

<img width="1349" alt="Screen Shot 2021-05-25 at 3 27 56 PM" src="https://user-images.githubusercontent.com/90494/119576545-cb9bc380-bd6d-11eb-9aab-5c1946b4c43c.png">

perhaps there is an issue on npms side. try installing again

**Comment by brentvatne** [comment]
(if problem persists, let me know)

**Comment by ScRiPt1337** [comment]
C:\Users\script>npm -g install @expo/config

added 301 packages, and audited 302 packages in 18s

21 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

C:\Users\script>npm install --global expo-cli
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @expo/config@3.3.43.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\script\AppData\Local\npm-cache\_logs\2021-05-25T22_31_48_138Z-debug.log

**Comment by brentvatne** [comment]
yeah this looks like a npm issue.. i'm not sure at which layer this is happening in npm, but it has happened to me a couple of times with other packages too and eventually npm sorts itself you.

some related issues:

https://github.com/npm/cli/issues/3111
https://github.com/npm/cli/issues/982
https://github.com/npm/cli/issues/1127

might be worth opening another issue on npm for this

**Comment by ScRiPt1337** [comment]
this worked for me https://github.com/npm/cli/issues/3269#issuecomment-846148702
