### ISSUE TITLE
Failed to compile. Invalid file signature

### ISSUE THREAD

**Issue by chackerian** [expo/expo-cli#3528]
I'm getting this error when running `expo run:web`. I think this has to do with a package version because I wasn't getting this before. Let me know if you have any suggestions.

**Comment by byCedric** [comment]
Hi @chackerian, could you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? Without that, we can't help you debug this issue.

**Comment by chackerian** [comment]
I can try. It's also important to note that my code works properly but when I upload to github and download it this error occurs.

**Comment by 0xrfsd** [comment]
Did you found any solution for this problem?

**Comment by humblesami** [comment]
In my case I had changed favicon in project_root_path/app.json
"favicon": "./assets/some_mine.jpg"
remove that line or change to some valid file (e.g expo init creates a file favicon.png in assests folder, that is really a valid icon file)
