### ISSUE TITLE
Problem with Expo-Cli installation.

### ISSUE THREAD

**Issue by Thinkeraty** [expo/expo-cli#3540]
Due to some problems with my node installation, I had to do a clean install of the software and lost all my node installations as a result.
When installing the expo-cli, I have been running into some problems lately.
The installation keeps getting stuck on -
````[       ...........] | postinstall: verb lock using C:\Users\Thinkeraty\AppData\Roaming\npm-cache\_locks\staging-d2d41f2b2eeb````
It doesn't budge, even after 4 hours.
My package.json - 
````
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "axios": "^0.20.0",
    "expo": "^37.0.0",
    "expo-camera": "~8.2.0",
    "expo-image-picker": "~8.1.0",
    "expo-status-bar": "^1.0.2",
    "joi": "^17.4.0",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-document-picker": "^3.5.4",
    "react-native-fs": "^2.16.6",
    "react-native-web": "^0.11.7",
    "rn-fetch-blob": "^0.12.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "^8.1.0"
  },
  "private": true
}
````

I have confirmed that this is not an issue with npm or my internet as I have successfully downloaded all the packages in package.json.

**Comment by byCedric** [comment]
Hi @Thinkeraty! Thanks for your issue report, but unfortunately, there is not a lot we can do on our end. This is an issue with npm, specifically it's [most likely trying to fetch something from the cache](https://stackoverflow.com/a/46271359/2277025) that could have been corrupted. Try force-clearing the cache with `npm cache clean`, or install the `expo-cli` with Yarn 😄 

Hope this helps!
