### ISSUE TITLE
[nextjs] Playing sounds, MP3 support

### ISSUE THREAD

**Issue by 5ervant** [expo/expo-cli#3554]
Using Next.js with Expo for Web: https://docs.expo.io/guides/using-nextjs/

I'm currently following this on my Next.js Expo application trying to play audio: https://docs.expo.io/versions/latest/sdk/audio/#playing-sounds

But I'm getting this error in web *(I don't know in Android)*:

```
Failed to compile
./MY_DIRECTORY/SUB_DIRECTORY/FOLDER_NAME/NAME.mp3 1:0
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```

I suppose I also need to support MP3 like the following instructions **BUT HOW WITH `.MP3`?**

- Image support: https://docs.expo.io/guides/using-nextjs/#image-support
- Font support: https://docs.expo.io/guides/using-nextjs/#font-support

If `expo-av` isn't yet supported on a Next.js Expo application, any alternatives?

**Comment by byCedric** [comment]
Hi @5ervant, thanks for the report. The guide you linked is for Expo projects only, not Next and using Expo Web. You probably can find an answer in [this thread](https://github.com/vercel/next.js/discussions/12810). Basically, you need to tell the webpack instance from Next how to handle this file.

Hope this helps!
