### ISSUE TITLE
[eject/prebuild] Duplicate entries of IntentFilter values from app.json

### ISSUE THREAD

**Issue by AdamJNavarro** [expo/expo-cli#3555]
When running `expo eject` or `expo prebuild`, the values from `android.intentFilters` in `app.json` will be added regardless if the value already exists in the `Manifest.xml` file resulting in duplicate entries.

**Comment by EvanBacon** [comment]
https://github.com/expo/expo-cli/issues/3316 prebuild officially requires clearing before rerunning.

**Comment by EvanBacon** [comment]
fixed https://github.com/expo/expo-cli/pull/4042
