### ISSUE TITLE
expo export - output created in inorrect directory

### ISSUE THREAD

**Issue by rbro** [expo/expo-cli#3559]
I'm the person who submitted #3478.  I'm still running into an issue using expo-cli 4.5.2 when doing expo export to an output-dir.  I believe the issue is when output-dir is a relative directory.  For example:

```
mkdir /tmp/expo
cd /tmp/expo
expo init my-project --template blank
expo export --public-url https://localhost --output-dir test my-project
```

At this point, /tmp/expo/test does not exist.  It looks like the files were written to /tmp/expo/my-project/test, but they should have been written to /tmp/expo/test.

Thank you for your help.

**Comment by EvanBacon** [comment]
Yes the final property `my-project` is the cwd to run the command in, we need to resolve the value `test` to either nothing `~/test` or the cwd `~/tmp/expo/my-project/test`, we use the latter approach.
