### ISSUE TITLE
[Suggestion] Change the wording when uploading keystore with build:android

### ISSUE THREAD

**Issue by zaytrix** [expo/expo-cli#356]
## Description

The prompts for the keystore password, key alias, and key password during `expo build:android` are confusing, which resulting in me using the wrong passwords. The only fix necessary for this is to change `? Keystore Alias` to `? Key Alias`, similar to what is shown with `expo fetch:android:keystore`.

## Expected Behavior

Like in Android Studio, I'd expect to be asked for the keystore password first, then the alias and password for that alias.
```
? Path to keystore: 
? Keystore Password: [hidden]
? Key Alias: 
? Key Password: [hidden]
```
If possible, for a later update, once the keystore password is given it would be nice to show a list of aliases in the keystore to pick from, like in Android Studio.

## Observed Behavior

With the prompts below, I had assumed that the keystore password meant the password to the alias,  and I put the keystore password into the key password prompt instead. Eventually after looking at `expo fetch:android:keystore` I realized what was wrong, but I'm sure this might confuse others as well.
```
? Path to keystore: 
? Keystore Alias: 
? Keystore Password: [hidden]
? Key Password: [hidden]
```

## Environment

expo-cli v2.8.0

## Reproducible Demo

Run `expo build:android`, or if you've already set the keystore, `expo build:android -c`

**Comment by brentvatne** [comment]
@quinlanj - I missed this issue before :O not sure if still relevant, lmk what you think
