### ISSUE TITLE
Deeplinking issue using latest `expo-cli` version

### ISSUE THREAD

**Issue by mfds** [expo/expo-cli#3568]
Hi!

I get a 404 error when using deeplinking (in dev mode) using the latest `expo-cli` version.

Steps to reproduce:
- create a blank expo project (using expo-cli v4.5.2, which is currently the latest one and Expo SDK 41)
- run `expo start --ios`
- issue `curl "127.0.0.1:19000?test"` on a terminal

What I expect to receive is the JSON output you would normally receive if you run `curl "127.0.0.1:19000"` but I get a 404 instead:
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /</pre>
</body>
</html>
```

If I forcibly install `expo-cli@4.4.2` (the minimum required version for Expo SDK 41) both `curl` commands work as expected.

I was wondering if something has changed on how to make deeplinking work but couldn't find anything on docs.

Node version: both `v12.21.0` and `v16.1.0` (I know support is not guaranteed on v16)

**Comment by brentvatne** [comment]
this isn't really related to deep linking - deep linking applies within the context of loading it in an app. and to open a deep link in expo go you need to include the suffix /--/ -- so `exp://127.0.0.1:19000/--/some/path?test`

what are you hoping to use this for?
