### ISSUE TITLE
Unable to yarn add expo-cli

### ISSUE THREAD

**Issue by ThePlatinum** [expo/expo-cli#3572]
error with yarn add expo on ubuntu 20.04

> Fetching packages...
> error @expo/osascript@2.0.28: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.19.0"
> error Found incompatible module.
> info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

![Screenshot from 2021-06-12 01-29-44](https://user-images.githubusercontent.com/30179079/121759472-ba98d380-cb1d-11eb-8f56-fc1df7e671cc.png)

**Comment by EvanBacon** [comment]
expo-cli only supports Node LTS versions (currently Node +12.0). Please upgrade your version of Node.js from 10.19.0 to 12.
