### ISSUE TITLE
client:install:android doesn't install the suggested version

### ISSUE THREAD

**Issue by bentinata** [expo/expo-cli#3574]
# Information
expo-cli: 3.20.1
node: 16.3.0
running on emulator

# What is printed to stdout

```
? You are currently using SDK 36.0.0. Would you like to install client 2.14.0 released for this SDK? Yes
Uninstalling Expo from Android device.
Installing Expo on device
Done!
```

# What I expected
Expo Go v2.14 is installed

# What I get
Expo Go v2.19 is installed instead, and got error "this project use SDK v36, minimum SDK is v38"

**Comment by byCedric** [comment]
Hi @bentinata! Unfortunately, I can't seem to reproduce this error. Is it possible that a previously installed Expo Go wasn't properly uninstalled before running `$ expo client:install:android`? If you are running on Mac or Linux, it might be worth removing a previously cached APK. You can do that by removing `~/.expo/android-apk-cache/Exponent-2.14.0.apk`.

Hope this helps!

**Comment by bentinata** [comment]
Hi @byCedric, I get around this by globally installing `expo-cli`.
