### ISSUE TITLE
Expo Compatibility with iPhone SE or iPhone 8?

### ISSUE THREAD

**Issue by oporter1** [expo/expo-cli#3575]
I can't download the Expo Client App on any simulators. It just says "Attempting to open simulator..." then the cli says "Xcode needs to be installed (don't worry you wont have to use it), would you like to continue to the app store? (y/n) " 

but I already have Xcode installed so no matter what choice I pick it will just say "done!"

and then nothing happens. The expo.io app doesn't install on any of my devices. I am trying to install it on older version to test compatibility with my app so perhaps it is not compatible with iPhone 8 or SE?

**Comment by EvanBacon** [comment]
What do you see when you run `xcodebuild -version` ?

**Comment by EvanBacon** [comment]
Closing as I cannot repro. Please run expo diagnostic and provide the output before reopening.
