### ISSUE TITLE
Node.js v13.13.0 is no longer supported

### ISSUE THREAD

**Issue by TausifM** [expo/expo-cli#3588]
> ``
![expo-cli-issue](https://user-images.githubusercontent.com/63940752/122631405-7b6c0480-d080-11eb-9d49-9dcef18a516a.jpg)

**Comment by brentvatne** [comment]
this is correct. use one of the supported versions listed in that error message.

we follow nodejs' support schedule https://nodejs.org/en/about/releases/ - notice that there is no 13

![Screen Shot 2021-06-19 at 9 47 36 AM](https://user-images.githubusercontent.com/90494/122649597-62486f80-d0e3-11eb-8e74-c76c2d0a6997.png)
