### ISSUE TITLE
IE 11 compatibility not working

### ISSUE THREAD

**Issue by ezekiel747** [expo/expo-cli#3590]
Hi, 
I've used expo-cli to create a new project, selecting Managed workflow -> tabs (TypeScript)     several example screens and tabs using react-navigation and TypeScript

I can't find a way to make it run on IE11, either in dev mode (npm run web) or prod (expo build:web, then serving the resulting folder).
Using Expo 4.5.2.

Things I've tried:
1. creating .browserslistrc with this content:

> > 0.2%
> not op_mini all
> ie 11

2. or setting this in package.json:

> {
>   ...
>   "browserslist": {
>     "production": [
>       ">0.2%",
>       "not op_mini all",
>       "ie 11"
>     ],
>     "development": [
>       "last 1 chrome version",
>       "last 1 firefox version",
>       "last 1 safari version",
>       "ie 11"
>     ]
>   }
> }
> 

Could you please help pointing to the right solution? 
Thanks in advance!

**Comment by ezekiel747** [comment]
Seems like the bundled code still has arrow functions and unsupported syntax by IE11.

**Comment by tomByrer** [comment]
I'm not sure how much support there should be for a browser with less than 1% of market & getting ready for EOL?  Also Win11 is out soon, so no new computers will not ship with IE11.

> [Microsoft Edge with IE mode is officially replacing the Internet Explorer 11](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/internet-explorer-11-desktop-app-retirement-faq/ba-p/2366549) desktop application on Windows 10. As a result, the Internet Explorer 11 desktop application will go out of support and be retired on June 15, 2022 for certain versions of Windows 10.

**Comment by ezekiel747** [comment]
Hi, thanks for responding.
This compatibility may still be a requirement, depending on who i'm building the app for.
Just to be clear: i'm not asking for out-of-the-box support for IE11 (or some other older version of some browser),
i'm merely asking for a way to approach this.

I found something helpful by @byCedric here:
(i'm leaving the link for anyone looking for a solution)
https://www.gitmemory.com/issue/expo/expo/10588/704859101 

the option **dangerouslyAddModulePathsToTranspile** did the trick in my case.
Unfortunately i can't point the original github thread - could have been deleted.

**Comment by EvanBacon** [comment]
The solution you linked leads me to believe that the issue is with other libraries in the ecosystem and not with Expo CLI itself(?). We only support locally transpiling packages that start with `expo-`, `react-`, etc.
