### ISSUE TITLE
Expo Build creation failing for both iOS and Android

### ISSUE THREAD

**Issue by Yash2711** [expo/expo-cli#3603]
I am try to build and publish app for both iOS and Android, for both the case I am getting below error - 

```
Bundle                     Size
┌ index.ios.js          4.97 MB
├ index.android.js      4.98 MB
├ index.ios.js.map      13.8 MB
└ index.android.js.map  13.9 MB

💡 JavaScript bundle sizes affect startup time. Learn more: https://expo.fyi/javascript-bundle-sizes

Analyzing assets
Saving assets
No assets changed, skipped.

Uploading JavaScript bundles
socket hang up
Error: socket hang up
    at connResetException (internal/errors.js:628:14)
    at TLSSocket.socketOnEnd (_http_client.js:499:23)
    at TLSSocket.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

I have tried updating the expo-cli to latest but the same issue. Also check the network and system configuration and both seem to be same with no firewalls or network filtering or anything enabled.

What I have noticed is while the bundling is happening the progress jumps quite fast not sure so what is going behind the scenes. Any help here will be highly appreciated.

**Comment by brentvatne** [comment]
this seems like a network issue on your end. there was no downtime on our side (https://status.expo.dev/). let me know if you can't get to the bottom of it. try from another machine also.

**Comment by zarcodim** [comment]
I'm also experiencing this. I have another machine that's able to build the expo project, but I still can't get to the bottom of why it's not working on this one. Any debugging tips would be much appreciated, I don't even know where to find the code that prints those messages. (I've also tried `NODE_DEBUG=net expo build:os` but I don't see a smoking gun.)
