### ISSUE TITLE
Android app generated by expo run:android is pointing at incorrect bundler port

### ISSUE THREAD

**Issue by terrymorgan76** [expo/expo-cli#3604]
**Description**
When I run `expo run:android -p 8082`, the react native bundler starts on port 8082 but the generated Android project is still looking for the bundler on port 8081. I can see that the bundler port is specified in the following auto-generated file:

`app/build/generated/res/resValues/debug/values/gradleResValues.xml`

```
<?xml version="1.0" encoding="utf-8"?>
<resources>

    <!-- Automatically generated file. DO NOT MODIFY -->

    <!-- Value from build type: debug -->
    <integer name="react_native_dev_server_port">8081</integer>
    <!-- Value from build type: debug -->
    <integer name="react_native_inspector_proxy_port">8081</integer>

</resources>
```

If I try and edit the port in the above file, it is simply reset to the above at build time, suggesting that the port value of `8081` is populated from "somewhere".

I cannot use the 8081 port as it is blocked on my machine by Macafee and overriding it would violate my company's IT security policy.

**Environment**
`expo diagnostics` output:

```
  Expo CLI 4.7.1 environment info:
    System:
      OS: macOS 11.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.8.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare
```

**Expected**
The Android app generated by `expo run:android -p 8082` should respect the port override in the run command be looking for the react native bundler on port 8082.

**Comment by EvanBacon** [comment]
Our current solution to this issue is to use `expo-dev-client` which effectively chooses the port dynamically in-app (more akin to a browser) as opposed to `react-native`'s tooling which hardcodes the port into the app. The reason we do this is because manually modifying files causes gradle to rebuild entire modules.

It might make sense to check if a project has expo-dev-client installed, and if not, then attempt to modify the XML file you referenced. I'm happy to review a PR if you're willing to take this on?

**Comment by EvanBacon** [comment]
Long term we need to remove all of the React Native code loading in favor of expo-dev-client/expo-updates. Because you can use a stable version of `expo-dev-client` in any development project, I'll consider this issue resolved.

**Comment by tybro0103** [comment]
@EvanBacon Would you mind pointing us the right direction on how to use `expo-dev-client` to get the port right?
I ran into the same thing on iOS.
