### ISSUE TITLE
IOS App Expo Go crash during the test  MaterialCommunityIcons from 'react-native-vector-icons/FontAwesome5

### ISSUE THREAD

**Issue by azabrodin** [expo/expo-cli#3608]
export default class TabNavigator extends Component {
    render() {
        return(
            <Tab.Navigator tabBarOptions={{ showLabel: false}}>
                <Tab.Screen name='Home' component={StackNavigators} options={{
                    tabBarIcon: ({ color }) => (
                        <MaterialCommunityIcons name="home" color={color}     size={24}  /***size={styles.iconTabSize}***/     />
                    ),
                }}/>
                ...
            </Tab.Navigator>
        )
    }
}

If you put  custom size from your 'styles' app Expo Go down!

**Comment by brentvatne** [comment]
https://stackoverflow.com/help/how-to-ask
