### ISSUE TITLE
Newly generated expo project has invalid copy of react-native?

### ISSUE THREAD

**Issue by timothymalcham** [expo/expo-cli#3618]
I'm trying to resolve an issue with react hooks in a newly generated expo app (on macOS). I get this error when starting the app:

```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
```

I know that I'm following the rules of hooks, so it's either 1 or 3.

I tried the following:
```
➜ npm ls react-native
/Users/timothymalcham/dev/[project]
└── react-native@0.63.2  invalid

npm ERR! invalid: react-native@0.63.2 /Users/timothymalcham/dev/[project]/node_modules/react-native
```

I've tried wiping out the `node_modules` directory and deleted `yarn.lock`, run `yarn` again to re-install everything, I've also tried `npm cache clear --force`. Nothing seems to resolve the `invalid` message. How should I go about resolving this? I have a strong assumption that this invalid error is connected to the above hooks error.

Here's more information if that's helpful:
```
➜ expo diagnostics

  Expo CLI 4.7.2 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.17.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/timothymalcham/.rvm/rubies/ruby-2.7.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.81 => 0.12.81
      expo: ^41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.7.2
    Expo Workflow: managed
```

**Comment by brentvatne** [comment]
i'm not sure what npm "invalid" means -- we have a slight fork of react-native 0.63.2 which is why we point react-native to our own archive.

> I'm trying to resolve an issue with react hooks in a newly generated expo app (on macOS). I get this error when starting the app:

are you saying that you see this error when you run a new blank project without any code changes? fwiw this is only happening to you, so this seems most likely to be an issue with your environment
