### ISSUE TITLE
Can't download tar builds from Expo CLI

### ISSUE THREAD

**Issue by buckmaxwell** [expo/expo-cli#3619]
In order to run e2e tests its necessary for me to download the simulator builds from expo before I install them on my iOS simulator. I can download these tar files manually from the build page via the download button, but I cannot find a way to download the build using Expo CLI.

<img width="1240" alt="build page" src="https://user-images.githubusercontent.com/6210452/123693916-a693e800-d826-11eb-8831-c1fb50e55292.png">

I had guessed that publish details might include the download link, but no such luck.

my attempt,

`expo publish:history -p ios -c test-v1 --count 1 --raw | jq ".queryResult[0].publicationId" | xargs expo publish:details --publish-id`

Is there any way to get the link I need  from Expo CLI?

**Comment by brentvatne** [comment]
better to post this kind of question in forums as it is not a bug :)

**Comment by brentvatne** [comment]
https://forums.expo.io/

**Comment by buckmaxwell** [comment]
ok. posted in the forum https://forums.expo.io/t/cant-download-tar-builds-from-expo-cli/53904?u=buckmaxwell
