### ISSUE TITLE
How do i get logs when the app instantly crashes?

### ISSUE THREAD

**Issue by jmccarrell-lmi** [expo/expo-cli#3620]
I'm now using expo-cli 4.7.2

I initialized a brand new project using this version, then ejected, then installed `react-native-webrtc` using `yarn add`.

After the app finishes loading, it crashes. Even without writing any additional code. I don't even need to import `react-native-webrtc` for it to instantly crash.

Regardless, I'm not looking for a solution, I'm just looking for feedback, like logging of any kind.
The metro server shows nothing.
The prompt that ran `npx react-native run-android` shows no errors or warnings, everything looks normal.

This is running on a One Plus 5T with Android version 10.0.1

**Comment by jmccarrell-lmi** [comment]
Also I finally ran a completely blank app from scratch that was ejected and it still doesn't work, although now it gives three errors and doesn't instantly crash... it just doesn't render.

```
[Mon Jun 28 2021 22:10:38.420]  ERROR    Error: Exception in HostObject::get(propName:NativeUnimoduleProxy): java.lang.AssertionError: expo-updates must be configured with a valid update URL or scope key.
[Mon Jun 28 2021 22:10:38.421]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[Mon Jun 28 2021 22:10:38.422]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
```

In this case it was cli 4.7.2 with NOTHING BUT the following commands:
```
expo init truly-empty
cd truly-empty
expo eject
...<defaults, com.what.ever>
npx react-native run-android --deviceId <OnePlus5T-10.0-deviceId>
```

**Comment by brentvatne** [comment]
hi @jmccarrell-lmi - notice the error which says you need to update the expo-updates configuration. if you are not signed in to expo-cli, we don't know where to point expo-updates. so you need to go to your AndroidManifest.xml as described [on this docs page](https://docs.expo.io/bare/installing-updates/#configuration-for-android)

in particular, you need to set the value of `expo.modules.updates.EXPO_UPDATE_URL` to point to `https://exp.host/@[username]/[slug]`

```
<meta-data android:name="expo.modules.updates.EXPO_UPDATE_URL" android:value="https://exp.host/@my-expo-username/my-app" />
```

this is a bad experience and we're going to be changing expo-updates to instead warn loudly and disable itself
