### ISSUE TITLE
Bare workflow template doesn't has typescript version

### ISSUE THREAD

**Issue by ecorrales1979** [expo/expo-cli#3623]
I updated expo to version 4.7.2 and started a new project, but now the option bare workflow template with typescript doesn't exist anymore. This was on purpose or a mistake?

**Comment by EvanBacon** [comment]
This was on purpose, we've supported automatically [configuring typescript](https://docs.expo.io/guides/typescript/) when you create a tsconfig and run expo start, or convert any file to TS fo a while now. We still highly recommend using TypeScript in projects.
