### ISSUE TITLE
Expo eject only generate android folder in my windows machine. so, when i want to build ios what to do?

### ISSUE THREAD

**Issue by subhampanja** [expo/expo-cli#3629]
My expo eject command only generating "android" folder. I also want "iOS" folder too. I am using windows.
now, my problem is what if I code after ejecting in windows (that will only generate android folder). Now I want to build iOS application. and I also have macOS so how to get "iOS" folder. Can you please guide me. its little confusing. 

making my question more clear. I am building app using expo and after that I need to eject because I need some more native modules. and I am building it, after that i also need to build iOS app. and i also have macOS so what to do now? will ejecting again create a iOS folder?

**Comment by jmarks-joshua** [comment]
Yes you can just eject again on a mac computer and it will make your ios folder, it may also make changes to your android folder which you can just discard from your repo if you don't want them.

**Comment by EvanBacon** [comment]
Run `expo prebuild -p ios` on a mac computer to generate the iOS code. You can also use managed EAS build to do this on a mac computer in the cloud.
