### ISSUE TITLE
Eject hangs at Making sure project is set up correctly

### ISSUE THREAD

**Issue by andershagebakken** [expo/expo-cli#364]
Expo and expo-cli version 2.10.0, tried with 2.10.2 as well, same issue. It worked yesterday, before I upgraded version.

## Description

expo eject hangs at "Making sure project is set up correctly...". Nothing happens. Waited for hours. 

## Expected Behavior

Project to eject.

## Observed Behavior

expo eject hangs at "Making sure project is set up correctly...". Nothing happens. 

## Environment

Expo CLI 2.10.0 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.14.1 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.0
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^2.12.1 => 2.12.1
    npmGlobalPackages:
      expo-cli: 2.10.0

Also specify:

- Phone/emulator/simulator platform, model and version:

## Reproducible Demo

Happens no matter what project, if its a fresh one or an older project.

**Comment by AdamJNavarro** [comment]
Hey @andershagebakken,

There's a decent chance this was a network issue. Are you still experiencing it?

Cheers,
Adam
