### ISSUE TITLE
Expo OTA update not working on iOS for SDK 41

### ISSUE THREAD

**Issue by natemartins** [expo/expo-cli#3646]
OTA updates worked perfectly prior to upgrading the SDK from 40 to 41. After upgrading to 41, I made a build which was submitted to the App store. Yesterday, I made a minor bug fix to the app which I published using `expo publish` to the production release channel which we have always used. The Android apps, running on SDK 41, got the update but not the iOS apps.

I even went as far as submitting another build to the App store just in case there was a mismatch with SDK versions. Still, OTA updates are not received by the iOS apps.

**Below is the output of `expo diagnostics`:**

```
Expo CLI 4.5.2 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.15.5 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.11 - /usr/local/bin/npm
      Watchman: 2021.05.31.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.5.2
    Expo Workflow: managed
```

**Comment by brentvatne** [comment]
hi there! i'm not sure what may be happening on your end but this is not a bug impacting any other users.
