### ISSUE TITLE
configure-splash-screen is not working anymore

### ISSUE THREAD

**Issue by menloai** [expo/expo-cli#3647]
I previously ran yarn run configure-splash-screen -b  '#121212' -i app/assets/1/images/splash.png —status-bar-hidden and it worked perfectly since I tried to add the -i option on the same command I get a weird output, could not find anything about it.

$ /Users/path/Code/work/path/app/node_modules/.bin/configure-splash-screen -b '#121212' -i app/assets/1/images/splash.png —status-bar-hidden

Cannot read property 'productType' of undefined

**Comment by brentvatne** [comment]
@yemd - can you share a reproducible example?

**Comment by yemd** [comment]
I can't reproduce the bug the only steps I can share are 

Install a bare workflow project
run
yarn run configure-splash-screen -b '#F4F4F4' -i app/assets/1/images/splash.png --status-bar-hidden
then
yarn run configure-splash-screen -i 'cover' -b '#F4F4F4' -i app/assets/1/images/splash.png --status-bar-hidden

Happy to try and provide anything else

**Comment by Thanaen** [comment]
You can still run the command by doing `npx @expo/configure-splash-screen` or `yarn dlx @expo/configure-splash-screen` 👍

**Comment by jalasem-meta** [comment]
> You can still run the command by doing `npx @expo/configure-splash-screen` or `yarn dlx @expo/configure-splash-screen` 👍

same error `Cannot read properties of undefined (reading 'productType')`

**Comment by byCedric** [comment]
Hi all! The `(@expo/)configure-splash-screen` command has been deprecated in favor of the [`expo-splash-screen` app manifest config options](https://docs.expo.dev/versions/latest/sdk/splash-screen/#configuration). This is handled through the [config plugin of `expo-splash-screen` itself](https://github.com/expo/expo/pull/11634).

Hope this helps!
