### ISSUE TITLE
Unknown type name UMModuleRegistryAdapter

### ISSUE THREAD

**Issue by molimauro** [expo/expo-cli#3648]
I don't now if this can be useful but, referring to issue #2418, the problem is that you include the 

```
#import <UMCore/UMModuleRegistry.h>
#import <UMReactNativeAdapter/UMNativeModulesProxy.h>
#import <UMReactNativeAdapter/UMModuleRegistryAdapter.h>
```

in the ifdef block of the FB_SONARKIT_ENABLED. Move them before the 
```
#ifdef FB_SONARKIT_ENABLED
```

**Comment by brentvatne** [comment]
hello! this is incorrect. those imports should indeed be outside of the `#ifdef FB_SONARKIT_ENABLED` block

**Comment by molimauro** [comment]
That was indeed what I was trying to suggest. In the code snippet provided the UMCore/UMReactNativeAdapter was inside the ```FB_SONARKIT_ENABLED``` block

**Comment by brentvatne** [comment]
can you let me know where this code lives? in our bare template project this is not an issue:

https://github.com/expo/expo/blob/312d0c8ec5902f385466da9da1f828b19bd573a3/templates/expo-template-bare-minimum/ios/HelloWorld/AppDelegate.m#L15-L32

**Comment by molimauro** [comment]
Sorry, maybe I did not explain myself correctly. I was referring to [this](https://github.com/expo/expo-cli/issues/2418#issue-671564964) code snippet :) the guy who opened the issue had this problem in his configuration 😊

**Comment by brentvatne** [comment]
@molimauro - ah i see! i believe in this case the user may have configured their project incorrectly. [in the installation instructions](https://docs.expo.io/bare/installing-unimodules/) we recommend the same snippet as i linked to above. hopefully [this pr](https://github.com/expo/expo-cli/pull/3669) will make it easier for people to install these libraries into projects initialized with `react-native init` :)

thanks for following up

**Comment by molimauro** [comment]
No problem, ty for your work ;)
