### ISSUE TITLE
ENOENT: no such file or directory, watch '/node_modules\expo-modules-core\android\build\kotlin\compileDebugKotlin\caches-jvm' 

### ISSUE THREAD

**Issue by fungmo** [expo/expo-cli#3652]
![image](https://user-images.githubusercontent.com/16655229/125161169-61bb6a00-e1b3-11eb-9333-4fb761c40118.png)

The `managed workflow` built using `expo init`, after exiting to the `bare workflow`, `yarn android` reports this error, and `console.log()` cannot be printed (I don’t know if it is directly related), I think it is very likely.

![image](https://user-images.githubusercontent.com/16655229/125161263-e73f1a00-e1b3-11eb-8559-dc2b26a72b9d.png)

**Comment by brentvatne** [comment]
please share a reproducible example. i can't reproduce this on my end and nobody else is encountering it. it seems like possibly an intermittent issue on your end or something related to another process running and modifying your filesystem

**Comment by JustinRohweller** [comment]
Thought I'd comment that I got this same error with these steps:
-expo init (bare) (sdk43)
-expo install react-native-reanimated
-update app.json expo block to have "jsEngine": "hermes"
-run react-native start --reset-cache

Started working for me once I just ran react-native start instead.
Not looking to start a new issue, just commenting for if others have the same problem.
Thanks

**Comment by mamahui** [comment]
i meet this problem too, are you slove this problems ? how to slove this ,please?
