### ISSUE TITLE
console.log doesn't work anymore after upgrading from expo 41 to 42

### ISSUE THREAD

**Issue by asalha** [expo/expo-cli#3653]
That's the expo diagnostics output:

Expo CLI 4.7.3 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    npmPackages:
      expo: ^42.0.0 => 42.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
    Expo Workflow: managed

And by the way, the OS shows Windows 10, but I have Windows 11 installed.

**Comment by asalha** [comment]
It worked after I restarted my computer!

**Comment by wispyco** [comment]
I can attest that restarting my computer worked, but I also think this tab was closed which keeps the web worker open for console logging anything http://localhost:19000/debugger-ui/
