### ISSUE TITLE
Replace request with node-fetch in expo/ngrok

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo-cli#3679]
This will remove the two following install warnings: 

```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
```

Code lives here: [expo/ngrok](https://github.com/expo/ngrok).

**Comment by Kudo** [comment]
the latest upstream ngork had already [replaced request with got](https://github.com/bubenshchykov/ngrok/commit/e2962e25863c238b2f76a06ce22624fa00e1bb0a). will take some time to upgrade ngrok  😅
