### ISSUE TITLE
error listen EADDRINUSE: address already in use :::19000

### ISSUE THREAD

**Issue by Miku-39** [expo/expo-cli#3687]
After updating expo-cli I can't run my projects. I tried searching for processes using the same port, but there seems to be none. Reinstalled expo-cli, rebooted my machine, tried --clear etc.
Running on macOS Big Sur, expo 4.8.1
```
Starting project at /Users/mikkanartian/Code/BCMobile
Developer tools running on http://localhost:19002
Starting Metro Bundler
Your JavaScript transform cache is empty, rebuilding (this may take a minute).
error listen EADDRINUSE: address already in use :::19000. 

Error: listen EADDRINUSE: address already in use :::19000
    at Server.setupListenHandle [as _listen2] (net.js:1320:16)
    at listenInCluster (net.js:1368:12)
    at Server.listen (net.js:1454:7)
    at /Users/mikkanartian/Code/BCMobile/node_modules/metro/src/index.js:240:20
    at new Promise (<anonymous>)
    at Object.<anonymous> (/Users/mikkanartian/Code/BCMobile/node_modules/metro/src/index.js:239:14)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/mikkanartian/Code/BCMobile/node_modules/metro/src/index.js:46:24)
    at _next (/Users/mikkanartian/Code/BCMobile/node_modules/metro/src/index.js:66:9)
Metro Bundler process exited with code 1
Error: Metro Bundler process exited with code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/expo-cli/node_modules/xdl/src/start/startLegacyReactNativeServerAsync.ts:271:16)
    at Object.onceWrapper (events.js:482:26)
    at ChildProcess.emit (events.js:375:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

**Comment by marcusradell** [comment]
I did a fresh install on my computer and got this.

**Comment by marcusradell** [comment]
`npm i -g expo-cli@4.7.3` seemed to fix the issue for me.
4.8.0 seems to be the first version where it breaks, so probably something in between those two versions that regressed.

**Comment by Miku-39** [comment]
> `npm i -g expo-cli@4.7.3` seemed to fix the issue for me.

That does the job for me! So the problem is indeed with the new version

**Comment by juancarlosjr97** [comment]
Version `4.8.0` presents the same issue starting development environment

**Comment by gabrielste1n** [comment]
> `npm i -g expo-cli@4.7.3` seemed to fix the issue for me.
> 4.8.0 seems to be the first version where it breaks, so probably something in between those two versions that regressed.

Worked for me also!

**Comment by brentvatne** [comment]
@EvanBacon will look into this shortly. rolling back to 4.7.3 will resolve your issue for now if you're encountering this

**Comment by EvanBacon** [comment]
I'm not sure I understand the issue. What command is being run? Can anyone provide a repro?

**Comment by juancarlosjr97** [comment]
Sure @EvanBacon `expo start` is causing the issue

**Comment by EvanBacon** [comment]
If I run `expo start` in one window, and `expo start` in another, I get the following prompt:
```
yolo39 𝝠 expo start
› Port 19000 is running this app in another window
  /Users/evanbacon/Documents/GitHub/lab/yolo39 (pid 12276)
? Use port 19001 instead? › (Y/n)
```
Selecting `Y` uses port 19001 as expected. Running on an Intel mac.

**Comment by juancarlosjr97** [comment]
@EvanBacon I have the issue and I am using a M1 apple

**Comment by EvanBacon** [comment]
Please run `expo diagnostics` in one of the project's you are experiencing this on, and share the results here.

I suspect this has something to do with the SDK version.

**Comment by juancarlosjr97** [comment]
@EvanBacon see below

This one is failing 

```
Expo CLI 4.8.1 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v12.16.3/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.11
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 4.8.1
    Expo Workflow: managed
```

and this is another project which is working 

```
  Expo CLI 4.8.1 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v12.16.3/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.8.1
    Expo Workflow: managed
```

Both are using the `expo-cli@4.8.1`

**Comment by EvanBacon** [comment]
Looks like this is a bug with the legacy dev server which is enabled for projects SDK 39 or less.

**Comment by juancarlosjr97** [comment]
It does work with `EXPO_USE_DEV_SERVER=1` with SDK 38. 

Thank you @EvanBacon!

**Comment by vnctmdc** [comment]
I had the same issue, and I Upgrade Expo SDK. => Fixed!

**Comment by idontcareofusername** [comment]
> `npm i -g expo-cli@4.7.3` seemed to fix the issue for me.
> 4.8.0 seems to be the first version where it breaks, so probably something in between those two versions that regressed.

Yes this worked for me too! Thank you!

**Comment by brentvatne** [comment]
`EXPO_USE_DEV_SERVER=1 expo start` will resolve this issue for SDK 38 users. we'll patch this so it's not needed in a release soon
