### ISSUE TITLE
Cannot pass --npm to expo run:android 

### ISSUE THREAD

**Issue by jramosss** [expo/expo-cli#3690]
Whenever i try to run expo run:android, it tries to install my packages with yarn and this message appears
🧶 Using Yarn to install packages. Pass --npm to use npm instead.
And inmediatly throws 
✖ Something went wrong installing JavaScript dependencies, check your yarn logfile or run yarn install again manually.
So i try to run 
*expo run:android --npm*
and this error appears
error: unknown option `--npm'
so does if i run 
*expo --npm run:android*

**Comment by EvanBacon** [comment]
`expo run:ios` and `expo run:android` abstract over `expo prebuild` if the project doesn't exist. If you'd like to add more customization to prebuild, simply run it before running `expo run:*`
