### ISSUE TITLE
Provide `expo outdated` wrapper?

### ISSUE THREAD

**Issue by jedahan** [expo/expo-cli#3692]
Currently, `npm outdated` shows packages that have specific versions that are handled by expo.

I will `expo upgrade`, copy the output of non-automatically-checked packages, diff them with `npm outdated`, and manually filter.

It would be nice to have `expo outdated` which would just filter the output for us.

**Comment by brentvatne** [comment]
so you want a command called `expo outdated` which runs `npm outdated` but filters out packages included in Expo SDK?

**Comment by jedahan** [comment]
Yep kinda like expo upgrade handles some packages but not others

**Comment by brentvatne** [comment]
this isn't going to be a priority for us in the near future, but if you'd like to open a pr to try this out we can review it :)
