### ISSUE TITLE
expo build:web leads to Failed to compile error: 

### ISSUE THREAD

**Issue by kirillvidyuk** [expo/expo-cli#3709]
### Summary

Should mention that such error we're not experienced with expo-cli 4.5.2 ver.

### Environment

Expo CLI 4.8.1 environment info:
    System:
      OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v12.18.4/bin/npm
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: 16.13.1 => 16.13.1 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: 0.63.3 => 0.63.3 
      react-native-web: ~0.11.7 => 0.11.7 
      react-navigation: ^4.4.0 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.8.1
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

hp laptop

### Error output

EXPO_DEBUG=true expo build:web

✖ Expo Webpack
  Compiled with some errors in 38.17s

Failed to compile.

Please check your GenerateSW plugin configuration:
navigateFallbackBlacklist has been renamed navigateFallbackDenylist.
Error: Please check your GenerateSW plugin configuration:
navigateFallbackBlacklist has been renamed navigateFallbackDenylist.
    at /home/kir/.nvm/versions/node/v12.18.4/lib/node_modules/expo-cli/node_modules/xdl/src/Webpack.ts:295:23
    at finalCallback (/home/kir/.nvm/versions/node/v12.18.4/lib/node_modules/expo-cli/node_modules/webpack/lib/Compiler.js:257:39)
    at /home/kir/.nvm/versions/node/v12.18.4/lib/node_modules/expo-cli/node_modules/webpack/lib/Compiler.js:306:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/kir/.nvm/versions/node/v12.18.4/lib/node_modules/expo-cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
    at AsyncSeriesHook.lazyCompileHook (/home/kir/.nvm/versions/node/v12.18.4/lib/node_modules/expo-cli/node_modules/tapable/lib/Hook.js:154:20)
    at /home/kir/.nvm/versions/node/v12.18.4/lib/node_modules/expo-cli/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (/home/kir/.nvm/versions/node/v12.18.4/lib/node_modules/expo-cli/node_modules/webpack/lib/Compiler.js:499:39)
    at /home/kir/.nvm/versions/node/v12.18.4/lib/node_modules/expo-cli/node_modules/webpack/lib/Compiler.js:298:10
    at /home/kir/.nvm/versions/node/v12.18.4/lib/node_modules/expo-cli/node_modules/webpack/lib/Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/kir/.nvm/versions/node/v12.18.4/lib/node_modules/expo-cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
    at AsyncSeriesHook.lazyCompileHook (/home/kir/.nvm/versions/node/v12.18.4/lib/node_modules/expo-cli/node_modules/tapable/lib/Hook.js:154:20)
    at /home/kir/.nvm/versions/node/v12.18.4/lib/node_modules/expo-cli/node_modules/webpack/lib/Compiler.js:482:27
    at /home/kir/.nvm/versions/node/v12.18.4/lib/node_modules/expo-cli/node_modules/neo-async/async.js:2818:7
    at done (/home/kir/.nvm/versions/node/v12.18.4/lib/node_modules/expo-cli/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/kir/.nvm/versions/node/v12.18.4/lib/node_modules/expo-cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at /home/kir/.nvm/versions/node/v12.18.4/lib/node_modules/expo-cli/node_modules/webpack/lib/Compiler.js:464:33

### Reproducible demo or steps to reproduce from a blank project

*STR:*
* Run expo build:web 

*ER:*
* Project has built successfully

*AR:*
* Error occurs

**Comment by EvanBacon** [comment]
Do you have a custom `webpack.config.js` in your project?

**Comment by kirillvidyuk** [comment]
Hi @EvanBacon ,
Nope:
![image](https://user-images.githubusercontent.com/9048430/126450598-116022e0-38ea-4415-9c92-eda87c363677.png)

**Comment by kirillvidyuk** [comment]
@EvanBacon,
I also searched for 'GenerateSW', 'navigateFallbackBlacklist' and 'navigateFallbackDenylist' across project and can't find anything like that.

**Comment by maximbaibakov** [comment]
Hey @EvanBacon and @kirillvidyuk 

It does look like it has been caused by this two PR https://github.com/expo/expo-cli/pull/1942/files / https://github.com/expo/expo-cli/pull/2023/files

Where PR #2023 - incorrectly reverted the change done in PR #1942

Just installed latest version and what I can see in the file - /usr/local/lib/node_modules/expo-cli/node_modules/workbox-build/src/options/partials/generate.js

```
  navigateFallbackBlacklist: joi.forbidden().error(new Error(
      'navigateFallbackBlacklist has been renamed navigateFallbackDenylist.')),
  navigateFallbackDenylist: joi.array().items(regExpObject),
```

It does look both PR's are from you @EvanBacon are you able to fix it please?

Regards,
Maxim

**Comment by EvanBacon** [comment]
I have, in a way, [fixed this](https://github.com/expo/expo-cli/pull/3729). Workbox support has been removed since it didn't really make sense to abstract over it like we did (see reasoning in the PR).
