### ISSUE TITLE
[iOS] System permissions - No purpose strings in build when only specified in locales

### ISSUE THREAD

**Issue by nicolegros** [expo/expo-cli#3711]
### Summary

Builds don't seem to setup the purpose strings correctly. I tried multiple solutions: 
1.  `eas build -p ios`, then `eas submit -p ios`.
2. `expo prebuild`, then opened the built project in XCode and realized my "purpose strings" were missing.
3. Took my prebuild from step 2, added manually the required strings and used `eas submit -p ios` with my local _.ipa_ file from XCode. 

### Environment

```
 Expo CLI 4.8.1 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.13 - ~/.nvm/versions/node/v14.16.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.4 
    npmGlobalPackages:
      expo-cli: 4.8.1
    Expo Workflow: bare
```

### Please specify your device/emulator/simulator platform, model and version

eas-cli/0.21.0 darwin-x64 node-v14.16.1

### Error output

Here's the error output from Apple 

<blockquote type="cite" style="font-family: Helvetica; font-size: 12px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><div dir="ltr">

TMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSCameraUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy). 
</div></blockquote>

### Reproducible demo or steps to reproduce from a blank project

Here's the content of **app.json** for iOS:
```
"ios": {
      "infoPlist": {
        "CFBundleAllowMixedLocalizations": true
      },
...
"locales": {
      "fr": "./languages/fr.json",
      "en": "./languages/en.json"
    },
```

Here's the content of **en.json**:
```
  "NSCameraUsageDescription": "We need to use your camera to be able to set your profile picture.",
  "NSLocationWhenInUseUsageDescription": "We need your location to be able to find parking spaces near your current position.",
  "NSPhotoLibraryUsageDescription": "We need to access your photos to be able to set your profile picture."
```

**Comment by brentvatne** [comment]
i'm not an expert on this but i believe you still need to add values for these usage descriptions `"infoPlist"` -- not just in the locales.

**Comment by EvanBacon** [comment]
Yes you need the values in your Info.plist, fwiu the locales are used somewhere locally on the device whereas Apple requires your Info.plist to be filled in so they can review it remotely.
