### ISSUE TITLE
add support for appIdSuffix arg to expo run:android

### ISSUE THREAD

**Issue by Stukz** [expo/expo-cli#3714]
Currently on the project I'm working on when I  run `react-native run-android --variant=devDebug --appIdSuffix=dev` the apk output file it's **android/app/build/outputs/apk/dev/debug/app-dev-debug.apk**

And If I use expo run:android 
 The command throws "**Failed to resolve APK build file in folder "/Users/$USER/../android/app/build/outputs/apk/debug**"

expo run:android --variant=devDebug 
The command throws **Failed to resolve APK build file in folder "/Users/$USER/.../android/app/build/outputs/apk/devdebug**"
@EvanBacon

**Comment by EvanBacon** [comment]
After looking at this more, I think I'd rather add a `--flavor` flag which can apply all of the various settings defined in a gradle flavor. This would make the functionality very similar to the `run:ios --scheme` flag.
