### ISSUE TITLE
The app works fine in local, but it crashes when I install the APK and open it

### ISSUE THREAD

**Issue by leoflood** [expo/expo-cli#3715]
### Summary

When I build the app, download the APK, install it and open it, it crashes. I searched solutions but they did not help me.
Here is my code: https://github.com/leoflood/ezejedrez
I run the command `expo build:android` to build.
Thanks!

### Environment

 Expo CLI 4.3.2 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\Massaroli\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7486908
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Xiaomi 6 and Galaxy A50 Exynos

### Error output

java.lang.RuntimeException: Expo encountered a fatal error: Error: Invariant failed 
This error is located at: in c in Unknown in Unknown in RCTView in View in RCTView in View in C, stack: default@759:160 createBrowserHistory@753:3450 c@749:851 Un@100:29003 Yr@100:47084 Cl@100:74733 RI@100:74658 Pl@100:74425 TI@100:71558 TI@-1 at host.exp.exponent.experience.q. E(BaseExperienceActivity.j ava:7) at host.exp.exponent.experience.a.run(Unknown Source: 2) at android.os.Handler.handleCallback(Handler.java:873) at android.os.Handler.dispatchMessage(Handler.java:99) at android.oslooper.loop(Looper.java:201) at android.app.ActivityThread.main(ActivityThread.java: 6820) at java.lang.reflect.Method.invoke(Native Method) at  com.android.internal.os.Runtimelnit$MethodAndArgsCaller .run(Runtimelnit.java:547) at com.android.internal.os.Zygotelnit.main(Zygotelnit.java: 922) 

### Reproducible demo or steps to reproduce from a blank project

app.json:
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest && ts-jest",
    "build": "expo build:android"
  },
  "dependencies": {
    "@babel/preset-typescript": "^7.13.0",
    "@types/jest": "^26.0.23",
    "expo": "~40.0.0",
    "expo-status-bar": "~1.0.3",
    "jest": "^26.6.3",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-web": "~0.13.12",
    "react-router-dom": "^5.2.0",
    "ts-jest": "^26.5.6",
    "typescript": "^4.2.4"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@types/react": "~16.9.35",
    "@types/react-native": "~0.63.2"
  },
  "private": true
}

**Comment by brentvatne** [comment]
hi there! Please refer to docs on how to debug errors in production builds of your app: https://docs.expo.io/workflow/debugging/#production-errors
