### ISSUE TITLE
Typescript in bare workflow. 

### ISSUE THREAD

**Issue by techTutorialsYTube** [expo/expo-cli#3717]
### Summary

The new version as removed the typescript option from bare workflow project creation.  
![image](https://user-images.githubusercontent.com/83872627/126889466-0e55081d-b02c-47c7-a4f7-1d268ae3c29e.png)

### Environment

Windows. 

### Please specify your device/emulator/simulator platform, model and version

windows

### Error output

Typescript option missing.

### Reproducible demo or steps to reproduce from a blank project

expo init <project- name>

**Comment by EvanBacon** [comment]
Duplicate https://github.com/expo/expo-cli/issues/3623
