### ISSUE TITLE
Expo eject iOS icons are not resizing in Images.xcassets

### ISSUE THREAD

**Issue by donkamaras** [expo/expo-cli#3724]
### Summary

Whenever we are ejecting we are getting the wrong size icon images

### Environment

  Expo CLI 4.7.3 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.17.3 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/lib/ruby/gems/2.7.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 24, 25, 26, 27, 28, 29, 30, 31
        Build Tools: 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0
        Android NDK: 21.4.7075529
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.1 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ^0.15.0 => 0.15.7 
    npmGlobalPackages:
      expo-cli: 4.7.3

### Please specify your device/emulator/simulator platform, model and version

Macos15.7

### Error output

We are not getting any error 

### Reproducible demo or steps to reproduce from a blank project

Whenever we open the eject the icons are there in xcode but they are not resized to the correct icon size.

**Comment by leoafarias** [comment]
Same issue here. Seems this is happening after the last CLI update.

**Comment by EvanBacon** [comment]
Confirmed fixed in https://github.com/expo/expo-cli/pull/3698 `expo-cli@4.9.0` by running `EXPO_IMAGE_UTILS_NO_SHARP=1 expo run:ios`. @leoafarias try deleting the cache `rm -rf .expo` and running again.
