### ISSUE TITLE
Standalone build failed - javascript app bundle build sucess, but server build process failed

### ISSUE THREAD

**Issue by sk-nnenu** [expo/expo-cli#3731]
### Summary

Hi, I was successful in running the expo build:ios command for my project, then I was trying to run expo build:android for an android apk and app bundle, the JavaScript app bundle was built successfully, but after uploading to server, the build failed.
Where can I find more debugging information because the error message is very general only shows  - 
"
Waiting for build to complete.
You can press Ctrl+C to exit. It won't cancel the build, you'll be able to monitor it at the printed URL.
✖ Build failed.
Standalone build failed!
"

This is my app.json file when i trying to build production apk:

{
  "expo": {
    "name": "myProject",
    "slug": "myProject",
    "version": "1.1.6",
    "orientation": "portrait",
    "icon": "./assets/images/myProject_icon.png",
    "notification":{
      "icon": "./assets/images/myProject_icon.png"
    },
    "scheme": "myapp",
    "splash": {
      "image": "./assets/images/myProject_splash_screen_1.png",
      "resizeMode": "cover",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "userInterfaceStyle": "light",
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "hk.com.myProject",
      "buildNumber": "1.1.6",
      "userInterfaceStyle": "light"
    },
    "android": {
      "softwareKeyboardLayoutMode": "pan",
      "adaptiveIcon":{
        "foregroundImage": "./assets/images/myProject_icon.png"
      },
      "icon": "./assets/images/myProject_icon.png",
      "googleServicesFile": "./google-services.json",
      "config": {
        "googleMaps": {
          "apiKey": "xxxxx"
        }
      },
      "package": "hk.com.myProject",
      "versionCode": 50,
      "userInterfaceStyle": "light"
    },
    "web": {
      "favicon": "./assets/images/favicon.png"
    }
  }
}

### Environment

  Expo CLI 4.9.0 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.16.0 - /usr/local/bin/npm
      Watchman: 2021.05.31.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.9.0
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Building android apk with macbook

### Error output

kc@kcmacbook iRecycle % EXPO_DEBUG=true expo build:android
- Making sure project is set up correctly...
✔ Choose the build type you would like: › apk
Checking if there is a build in progress...

Accessing credentials for kc in project myProject

› Expo SDK: 42.0.0
› Release channel: default
› Workflow: Managed

Building optimized bundles and generating sourcemaps...

Publish Assets:
- Asset target: managed

Expo Metro config:
- Bundler target: bare
- Legacy: false
- Extensions: ts, tsx, js, jsx, json
- React Native: /Users/kc/Desktop/work/myProject/node_modules/react-native
- Babel config: /Users/kc/Desktop/work/myProject/babel.config.js

Starting Metro Bundler
Finished building JavaScript bundle in 29130ms.

Bundle                     Size
┌ index.ios.js          8.16 MB
├ index.android.js      8.17 MB
├ index.ios.js.map      25.6 MB
└ index.android.js.map  25.6 MB

💡 JavaScript bundle sizes affect startup time. Learn more: https://expo.fyi/javascript-bundle-sizes

Analyzing assets
Saving assets
No assets changed, skipped.

Processing asset bundle patterns:
- /Users/kc/Desktop/work/myProject/**/*

Uploading JavaScript bundles
Publish complete

📝  Manifest: https://exp.host/@kc/imyProject/index.exp?sdkVersion=42.0.0 Learn more: https://expo.fyi/manifest-url
⚙️   Project page: https://expo.io/@kc/myProject Learn more: https://expo.fyi/project-page

Checking if this build already exists...

Build started, it may take a few minutes to complete.
You can check the queue length at https://expo.io/turtle-status

You can monitor the build at

 https://expo.io/accounts/kc/projects/myProject/builds/464d7344-f5db-4f47-959d-979873d3c8a1

Waiting for build to complete.
You can press Ctrl+C to exit. It won't cancel the build, you'll be able to monitor it at the printed URL.
✖ Build failed.
Standalone build failed!

### Reproducible demo or steps to reproduce from a blank project

What kind of code should I use to make a reproducible demo?

**Comment by sk-nnenu** [comment]
"
You can monitor the build at

 https://expo.io/accounts/kc-nnenu/projects/iRecycle/builds/e51c660b-fce3-4ded-b100-52813df45c84

Waiting for build to complete.
You can press Ctrl+C to exit. It won't cancel the build, you'll be able to monitor it at the printed URL.
✖ Build failed.
Standalone build failed!
"

We tried to expo build:android again today, but the build failed too.

We tried to click the link above from the monitor the build, but the page says 

"Something went wrong.

No internal distribution build exists at this URL."

Thanks again please kindly direct me to find out more about this issues.

**Comment by kc-nnenu** [comment]
I figured out where is the cause of the error.

In app.json,

my previous successful expo build:android was using ‘com.mycompany.myproject’

the new failed expo build:android is currently using ‘hk.com.mycompany.i.myproject’

so in app.json, if I revert the expo.android.package value back to 1) ‘com.mycompany.myproject’, the expo build:android will be successful again.




Does expo build forbid changing android package names? or is the format of the expo.android.package value in 2) causing the errors?

Thanks!

**Comment by kc-nnenu** [comment]
I figured out where is the cause of the error.

In app.json,

the previous successful expo build:android was using ‘com.mycompany.myproject’

the new failed expo build:android is currently using ‘hk.com.mycompany.i.myproject’

so in app.json, if I revert the expo.android.package value back to 1) ‘com.mycompany.myproject’, the expo build:android will be successful again.




Does expo build forbid changing android package names? or is the format of the expo.android.package value in 2) causing the errors?

Thanks!

**Comment by kc-nnenu** [comment]
We discovered the bug is within the file ./google-services.json

if you change the app.json's expo.android.package name from android you should also change the target client in ./google-services.json

Thanks.

**Comment by sk-nnenu** [comment]
Thank you.
