### ISSUE TITLE
expo build:ios - IPA - transparent App Store Icon

### ISSUE THREAD

**Issue by bbarthec** [expo/expo-cli#374]
## Description
`iOS` rejects uploading generated `IPA` when `App Store Icon` is transparent

## Expected Behavior

`expo build:ios` during project checking phase would warn about transparency of asset that would be used as `App Store Icon`.

## Observed Behavior

No such checking is provided and user is presented with error at the final stage of app uploading.

## Environment

`iOS` build submission for TestFlight

## Reproducible Demo

- build app using `expo build:ios`
- try to publihs in using `Appliaction Loader`
- observe error presented in the attached screenshot at the final stage of publishing process

![screenshot 2019-02-13 at 11 26 18](https://user-images.githubusercontent.com/16623003/52705170-8da27900-2f82-11e9-9fca-1bf81700d996.png)

**Comment by tsapeta** [comment]
Can you guys fix it asap? This issue makes me unable to publish my app and I will lose my job if I don't do that this week 😞

**Comment by osdnk** [comment]
Please very fix it @dsokal. I'll be fired if I won't deifer my abb

**Comment by osdnk** [comment]
:thanku:

**Comment by dsokal** [comment]
Sorry, but it's an easter egg. We won't fix it.

**Comment by osdnk** [comment]
Could you please rethink your approach to your final users? I consider it more than ridiculous. OSS world should not look like this. Shame on you

**Comment by tsapeta** [comment]
Ok @dsokal, I'll report to your boss that you don't want to fix it.

**Comment by dsokal** [comment]
@tsapeta I'm not afraid of you, sir!

**Comment by osdnk** [comment]
Thanks for this incredible improvements and making Expo and OSS community better place in the world!

**Comment by bbarthec** [comment]
🎉 	Great work! Thank you @dsokal sir! 🎉
