### ISSUE TITLE
[Web] Work well in My Project ,but get error `Module parse failed: Unexpected token` in module 

### ISSUE THREAD

**Issue by bolan9999** [expo/expo-cli#3744]
### Summary

I wrote a component. It works well on iOS, android and Web, then I publish it to NPM. But get error `Module parse failed: Unexpected token` after install it from NPM. However it works well on iOS and android.  

I miss any steps ?

### Environment

Expo CLI 4.9.1 environment info:
    System:
      OS: macOS 11.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.7.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 29, 30
        Build Tools: 29.0.2, 29.0.3, 30.0.0
        System Images: android-21 | Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
        Android NDK: 23.0.7530507-beta6
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ^0.64.2 => 0.64.2 
      react-native-web: ^0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.9.1
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

platform: Web

### Error output

```
Failed to compile.
/Users/mac/Documents/WorkSpace/react-native-pattern-lock/node_modules/@shanshang/react-native-pattern-lock/PatternLock.js 175:4
Module parse failed: Unexpected token (175:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
|   return (
>     <PanGestureHandler onGestureEvent={panHandler}>
|       <Animated.View style={styles.container} onLayout={onContainerLayout}>
|         <TapGestureHandler onGestureEvent={panHandler}>
```

### Reproducible demo or steps to reproduce from a blank project

```
https://github.com/bolan9999/react-native-pattern-lock
```

**Comment by EvanBacon** [comment]
Gotta add the packages that need to be transpiled locally to the webpack config, we automatically do this with packages that start with `react-native` or `expo`, etc. but this package starts with `@shanshang`, here is an example: https://github.com/expo/examples/blob/a0e5bbfcde4720b6192bfb54b1546200b191030d/with-moti/webpack.config.js#L7
