### ISSUE TITLE
Error when starting expo app

### ISSUE THREAD

**Issue by gabrielbarth** [expo/expo-cli#3746]
### Summary

I am facing an error when starting my expo app on my Linux mint and MacOS machines.
1 - run "expo init projectName";
2 - enter its folder and run "expo start";
3 - open the app on android device or emulator.
4 - that error appears..

![Screenshot from 2021-08-04 22-16-23](https://user-images.githubusercontent.com/42456106/128280411-e58b5159-f5fb-4875-beed-a7eef82161fa.png)

### Environment

Expo CLI 4.9.1 environment info:
    System:
      OS: Linux 4.15 Linux Mint 19.1 (Tessa)
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
      Yarn: 1.21.1 - /usr/bin/yarn
      npm: 7.20.3 - ~/.nvm/versions/node/v12.14.1/bin/npm
    SDKs:
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.3
        System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    npmPackages:
      expo: ~42.0.1 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.9.1
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Xiaomi Mi A1 device and Google Pixel 4 emulator

### Error output

Failed building JavaScript bundle.
node_modules/react-native-gesture-handler/src/GestureHandlerRootView.android.tsx: Property body[13] of BlockStatement expected node to be of a type ["Statement"] but instead got "AssignmentExpression"

### Reproducible demo or steps to reproduce from a blank project

1 - run "expo init projectName";
2 - enter its folder and run "expo start";
3 - open the app on android device or emulator.

**Comment by gabrielbarth** [comment]
Well, it seems it's a @babel/core issue.

I just replaced node_modules/@babel getting it from my another older project and now it works fine. But didn't works when I remove @babel/core and install it again on its latest version.

reference: https://stackoverflow.com/questions/68659516/react-native-property-body41-of-blockstatement-expected-node-to-be-of-a-type

**Comment by EvanBacon** [comment]
Seems like it was related to the babel outage that is now resolved https://twitter.com/notbrent/status/1423130707996577792?s=20
