### ISSUE TITLE
[config-plugins] `WarningAggregator` does not work with user-created plugins

### ISSUE THREAD

**Issue by barthap** [expo/expo-cli#3757]
The `@expo/config-plugins` package exports a `WarningAggregator` interface to display warnings. It works well with plugins built into expo-cli, but not with plugins created by user/3rd party library. Probably (I didn't check) the official plugins from `expo/packages/expo-*` don't display warnings too.

**Steps to reproduce:**
1. Create blank app with `expo init`.
2. `yarn add @expo/config-plugins`
3. Create `my-plugin.js` in project root directory with the following content:
   ```js
   const { WarningAggregator } = require("@expo/config-plugins");

   module.exports = function withWarning(config) {
     WarningAggregator.addWarningAndroid("my-plugin", "An Example Warning");

     config.name = config.name + "-warned";
     return config;
   };
   ```
4. Add `my-plugin.js` to the `plugins` section in `app.json`:
   ```json
   "plugins": ["./my-plugin"]
    ```
5. Run `expo config --type prebuild` to ensure the plugin is applied (-warned suffix in app name).
6. Run `expo prebuild` and observe no warning is displayed

I suspect that `WarningAggregator` shipped with expo-cli is a different module instance than the one imported by the plugin. The former is located in the `yarn global` / `volta` installation directory and the latter in local `node_modules`. The CLI uses imports internally the former module to display warnings.

**Comment by EvanBacon** [comment]
I see, maybe we should change the aggregator to push changes to the config, then flush the warnings on the config at the end.
