### ISSUE TITLE
expo build:android -c does not clear credentials form build server

### ISSUE THREAD

**Issue by dashcraft** [expo/expo-cli#376]
# READ THIS FIRST, PLEASE!

We're looking to keep questions on our forums and bug reports on the GitHub repo -- please choose whichever you feel is more appropriate for your issue:

- Post in our community forums (log in with your Expo developer account): https://forums.expo.io/c/help
- File a bug on the Expo CLI repo (for bugs related to the Expo CLI tools): https://github.com/expo/expo-cli/issues/new
- File a bug on the main Expo repo (for other bugs): https://github.com/expo/expo/issues/new
- Request a feature on Canny: https://expo.canny.io/feature-requests

Thanks for reporting the issue you found with Expo CLI!

# Required format for issues

Please make our job easier by filling this template out to completion.

## Description
`expo build:android -c` does not clear the credentials out of the build system. 
## Expected Behavior
I created an android app and used expo to handle credentials.
I fetch the keystore and did not write down the password.
I used `expo build:android -c` so as to clear credentials and just rebuild
using a different expo keystore/build.
I tried both `expo build:android` selecting new build and `expo fetch:android:keystore`
and they both said the keystore still exists and build attempted to re-use the old keystore
to rebuild the application.

I expect the command `expo build:android -c` to clear the credentials from the build server
and return empty or `no existing credentials have been found` after running the build command.

## Observed Behavior
What actually happened when you performed the above actions?
It did not clear the keystore from the build servers.

## Environment

  Expo CLI 2.4.0 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.2.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^29.0.0 => 29.0.1 
      react: ^16.3.1 => 16.6.3 
      react-native: ^0.55 => 0.55.4 
      react-navigation: ^2.13.0 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.4.0

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/dashcraft-d17a778a-6b74-42e7-ad6e-9c296a60b2c7.tar.gz

Also specify:
- Phone/emulator/simulator platform, model and version:
None required, this is not an issue with the phone, emulator or simulator.

## Reproducible Demo
Create a new android app build
Let expo handle the build process and credentials
Attempt clear the credentials
Attempt to fetch existing credentials

**Comment by wkozyra95** [comment]
When you build an application and there is no credentials specified build system is generating them. In your case when you passing `-c` option credentials are removed and then during a build, new keystore is generated. This is the expected behavior.

**Comment by dashcraft** [comment]
@wkozyra95 The issue is that it _doesn't_ create a new keystore. It uses the _same_ keystore as previously indicated, which leads me to believe it's not actually clearing the keystore.

My only resolution was to create a separate account in expo and re-build the application with a different user.

**Comment by wkozyra95** [comment]
Yes, you're right there was a bug there. The fix is ready and currently going through the review process.

**Comment by dashcraft** [comment]
Thank you so much @wkozyra95 I appreciate it!

**Comment by wkozyra95** [comment]
Should be working now (fix is server side, so you don't need to update cli)

**Comment by dashcraft** [comment]
Thank you so much @wkozyra95 for looking into this!
