### ISSUE TITLE
build:ios login error

### ISSUE THREAD

**Issue by olegreznichenko** [expo/expo-cli#377]
expo-cli@2.10.1 - `build:ios` command fails after entering credentials
```
- Trying to authenticate with Apple Developer Portal...?[2K?[1G?[?25h?[31m×?[39m Authentication with Apple Developer Portal failed!
?[31m[19:32:12]?[39m ?[31mProcess exited with non-zero code: 127?[39m
?[31m[19:32:12]?[39m ?[31m?[90mError: Process exited with non-zero code: 127?[31m?[39m
?[31m?[90m    at ChildProcess.child.on (C:\Users\roleg\Desktop\Work\amous-mobile-native\node_modules\@expo\spawn-async\build\spawnAsync.js:39:21)?[31m?[39m
?[31m?[90m    at ChildProcess.emit (events.js:197:13)?[31m?[39m
?[31m?[90m    at ChildProcess.cp.emit (C:\Users\roleg\Desktop\Work\amous-mobile-native\node_modules\@expo\spawn-async\node_modules\cross-spawn\lib\enoent.js:40:29)?[31m?[39m
?[31m?[90m    at maybeClose (internal/child_process.js:978:16)?[31m?[39m
?[31m?[90m    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)?[31m?[39m
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
`expo diagnostics`
```
  Expo CLI 2.10.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338
```

But with cli version 2.6.14 it's working

But I getting an error after last generated Provisioning profile
```
/@expo/traveling-fastlane-linux/traveling-fastlane-1.6.2-linux-x86_64/fetch_new_provisioning_profile" "**.com ** ** *** *** false"
[19:39:00] Error while gathering & validating credentials
[19:39:00] Error: Request failed with status code 400
[19:39:00] Request failed with status code 400
[19:39:00] Error: Request failed with status code 400
    at createError (C:\Users\roleg\Desktop\Work\amous-mobile-native\node_modules\xdl\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\roleg\Desktop\Work\amous-mobile-native\node_modules\xdl\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\roleg\Desktop\Work\amous-mobile-native\node_modules\xdl\node_modules\axios\lib\adapters\http.js:236:11)
    at IncomingMessage.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Have no idea what is wrong, it is first time building ios app
Hope second error will gone after fixing login issue.

**Comment by wkozyra95** [comment]
Hi
Did you follow windows specific steps described in documentation?
https://docs.expo.io/versions/v32.0.0/distribution/building-standalone-apps/

> Windows users must have WSL enabled. We recommend picking Ubuntu from the Windows Store. Be sure to Launch Ubuntu at least once. After that, use an Admin powershell to run: `Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`

**Comment by olegreznichenko** [comment]
Ubuntu was enabled
Fixed if run the command from admin PowerShell console, seems like need to update expo docs :)

**Comment by jreason** [comment]
@olehreznichenko @wkozyra95 i too have this same issue.

When downgrading to 2.6.14 i can not get past the status code 400 error even when using Admin - Powershell

I've spent all day trying various different ways, and different versions of expo-cli.

Any ideas?

`[19:39:00] Error while gathering & validating credentials
[19:39:00] Error: Request failed with status code 400
[19:39:00] Request failed with status code 400
[19:39:00] Error: Request failed with status code 400`

**Comment by m96dy** [comment]
I am having the same problem please help

**Comment by michaelmarriott** [comment]
Same issue, but works on another pc.
My error is:

_Trying to authenticate with Apple Developer Portal...
Authentication with Apple Developer Portal failed!
bash exited with non-zero code: 127
Error: bash exited with non-zero code: 127
    at ChildProcess.completionListener (C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:281:20)
    at ChildProcess.emit (events.js:193:13)
    at ChildProcess.EventEmitter.emit (domain.js:481:20)
    at ChildProcess.cp.emit (C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1001:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
    ...
    at spawnAsync (C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:26:19)
    at _callee$ (C:\expo-cli@2.21.2\src\commands\build\ios\appleApi\fastlane.js:16:28)
    at tryCatch (C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\core-js\library\modules\_export.js:36:28)
    at C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12
    at runAction (C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\build\commands\build\ios\appleApi\fastlane.js:89:17)
    at Object._callee$ (C:\expo-cli@2.21.2\src\commands\build\ios\appleApi\authenticate.js:15:46)
    at tryCatch (C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at processTicksAndRejections (internal/process/task_queues.js:86:5)_

**Comment by m96dy** [comment]
> Same issue, but works on another pc.
> My error is:
> 
> _Trying to authenticate with Apple Developer Portal...
> Authentication with Apple Developer Portal failed!
> bash exited with non-zero code: 127
> Error: bash exited with non-zero code: 127
> at ChildProcess.completionListener (C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules@expo\spawn-async\src\spawnAsync.ts:65:13)
> at Object.onceWrapper (events.js:281:20)
> at ChildProcess.emit (events.js:193:13)
> at ChildProcess.EventEmitter.emit (domain.js:481:20)
> at ChildProcess.cp.emit (C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:34:29)
> at maybeClose (internal/child_process.js:1001:16)
> at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
> ...
> at spawnAsync (C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules@expo\spawn-async\src\spawnAsync.ts:26:19)
> at _callee$ (C:\expo-cli@2.21.2\src\commands\build\ios\appleApi\fastlane.js:16:28)
> at tryCatch (C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:62:40)
> at Generator.invoke [as _invoke] (C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:296:22)
> at Generator.prototype.(anonymous function) [as next] (C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:114:21)
> at step (C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
> at C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14
> at new Promise ()
> at new F (C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\core-js\library\modules_export.js:36:28)
> at C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12
> at runAction (C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\build\commands\build\ios\appleApi\fastlane.js:89:17)
> at Object._callee$ (C:\expo-cli@2.21.2\src\commands\build\ios\appleApi\authenticate.js:15:46)
> at tryCatch (C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:62:40)
> at Generator.invoke [as _invoke] (C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:296:22) at Generator.prototype.(anonymous function) [as next] (C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:114:21) at step (C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30) at C:\Users\MikePc\AppData\Roaming\npm\node_modules\expo-cli\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13 at processTicksAndRejections (internal/process/task_queues.js:86:5)_

Same error, but I am using linux :(

**Comment by wkozyra95** [comment]
@m96dy it's the first time I heard about this problem on linux, can you provide terminal output?
@michaelmarriott  Are you sure you have wsl enabled? What happens when you run some linux comand e.g. `uname -a` ? Have you tried to run powershell as administrator?

**Comment by m96dy** [comment]
@wkozyra95 
that was my terminal output:

> Trying to authenticate with Apple Developer Portal...
> Authentication with Apple Developer Portal failed!
> /home/m96dy/node_modules/@expo/traveling-fastlane-linux/traveling-fastlane-1.9.11-linux-x86_64/authenticate exited with non-zero code: 127
> Error: /home/m96dy/node_modules/@expo/traveling-fastlane-linux/traveling-fastlane-1.9.11-linux-x86_64/authenticate exited with non-zero code: 127
>     at ChildProcess.completionListener (/home/m96dy/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
>     at Object.onceWrapper (events.js:286:20)
>     at ChildProcess.emit (events.js:198:13)
>     at ChildProcess.EventEmitter.emit (domain.js:448:20)
>     at maybeClose (internal/child_process.js:982:16)
>     at Socket.stream.socket.on (internal/child_process.js:389:11)
>     at Socket.emit (events.js:198:13)
>     at Socket.EventEmitter.emit (domain.js:448:20)
>     at Pipe._handle.close (net.js:606:12)
>     ...
>     at spawnAsync (/home/m96dy/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
>     at _callee$ (/expo-cli@2.21.2/src/commands/build/ios/appleApi/fastlane.js:16:28)
>     at tryCatch (/home/m96dy/.npm-global/lib/node_modules/expo-cli/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
>     at Generator.invoke [as _invoke] (/home/m96dy/.npm-global/lib/node_modules/expo-cli/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
>     at Generator.prototype.(anonymous function) [as next] (/home/m96dy/.npm-global/lib/node_modules/expo-cli/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
>     at step (/home/m96dy/.npm-global/lib/node_modules/expo-cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
>     at /home/m96dy/.npm-global/lib/node_modules/expo-cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
>     at new Promise (<anonymous>)
>     at new F (/home/m96dy/.npm-global/lib/node_modules/expo-cli/node_modules/core-js/library/modules/_export.js:36:28)
>     at /home/m96dy/.npm-global/lib/node_modules/expo-cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
>     at runAction (/home/m96dy/.npm-global/lib/node_modules/expo-cli/build/commands/build/ios/appleApi/fastlane.js:89:17)
>     at Object._callee$ (/expo-cli@2.21.2/src/commands/build/ios/appleApi/authenticate.js:15:46)
>     at tryCatch (/home/m96dy/.npm-global/lib/node_modules/expo-cli/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
>     at Generator.invoke [as _invoke] (/home/m96dy/.npm-global/lib/node_modules/expo-cli/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
>     at Generator.prototype.(anonymous function) [as next] (/home/m96dy/.npm-global/lib/node_modules/expo-cli/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
>     at step (/home/m96dy/.npm-global/lib/node_modules/expo-cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
>     at /home/m96dy/.npm-global/lib/node_modules/expo-cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
>     at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by michaelmarriott** [comment]
ok, finally got it to work on windows in powershell  (was always running as admin) I ran "bash" and then did the build:ios. 
Note: I even created docker containers FROM node:10.13-alpine, installed different versions of expo-cli and kept getting:
 _Trying to authenticate with Apple Developer Portal...
Authentication with Apple Developer Portal failed!
spawn /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-linux/traveling-fastlane-1.9.7-linux-x86_64/authenticate ENOENT
Error: spawn /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-linux/traveling-fastlane-1.9.7-linux-x86_64/authenticate ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)_

**Comment by JaredDahlke** [comment]
running expo:build ios IN THE POWERSHELL fixed this for me as well. thank you

**Comment by alexsenichev** [comment]
Run `sudo expo build:ios` helped me
