### ISSUE TITLE
Unable to publish: An unknown error occurred

### ISSUE THREAD

**Issue by weisensee** [expo/expo-cli#3779]
### Summary

running `expo publish --release-channel staging -t managed` results in an error: `An unknown error occurred.`

<img width="724" alt="Screen Shot 2021-08-17 at 4 34 16 PM" src="https://user-images.githubusercontent.com/6687146/129813959-0588bacf-dad0-4633-b32c-3034ad9912f0.png">

### Environment

```
  Expo CLI 4.10.0 environment info:
    System:
      OS: macOS 11.5
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.1/bin/yarn
      npm: 6.14.13 - ~/.nvm/versions/node/v14.17.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.1
        System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.10.0
    Expo Workflow: managed
    
    ```

### Please specify your device/emulator/simulator platform, model and version

Any Platform publish

### Error output

```
yarn run v1.22.10
$ expo publish --release-channel staging -t managed

› Expo SDK: 42.0.0
› Release channel: staging
› Workflow: Managed

Building optimized bundles and generating sourcemaps...

Publish Assets:
- Asset target: managed


Expo Metro config:
- Bundler target: bare
- Legacy: false
- Extensions: ts, tsx, js, jsx, json
- React Native: /Users/luke/workspace/project/node_modules/react-native
- Babel config: /Users/luke/workspace/project/babel.config.js


Expo Metro config:
- Bundler target: bare
- Legacy: false
- Extensions: ts, tsx, js, jsx, json
- React Native: /Users/luke/workspace/project/node_modules/react-native
- Babel config: /Users/luke/workspace/project/babel.config.js

Starting Metro Bundler
Finished building JavaScript bundle in 6903ms.

Bundle                     Size
┌ index.ios.js          4.89 MB
├ index.android.js       4.9 MB
├ index.ios.js.map      14.5 MB
└ index.android.js.map  14.5 MB

💡 JavaScript bundle sizes affect startup time. Learn more: https://expo.fyi/javascript-bundle-sizes

Analyzing assets
Saving assets
An unknown error occurred.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Reproducible demo or steps to reproduce from a blank project

No snack available at the moment, but let us know if you really need one.

**Comment by estebandiazfront** [comment]
Same happens to me when running `expo build:ios --release-channel staging-z`
Is it something related to expo servers? Or do I need to set up something else in my project?

**Comment by EquesMedia** [comment]
Same issue here. Available to provide debug if necessary.

**Comment by brentvatne** [comment]
can someone doing this share some information about their project? eg: what the full name is for your project? `@username/slug`

**Comment by EquesMedia** [comment]
> can someone doing this share some information about their project? eg: what the full name is for your project? `@username/slug`

@clicnpark/clicnpark

**Comment by EquesMedia** [comment]
> can someone doing this share some information about their project? eg: what the full name is for your project? `@username/slug`

@clicnpark/clicnpark

**Comment by brentvatne** [comment]
it looks like there was a regression when publishing update bundles with new assets. we're investigating that now

**Comment by AlenToma** [comment]
This happen to my too, After updating `expo-asset` I begun to receive this problem.

**Comment by brentvatne** [comment]
we have found the root cause and will be releasing a fix shortly

**Comment by eddieatkinson** [comment]
It's working for me now. Thanks!

**Comment by brentvatne** [comment]
good to hear. this should be resolved for everyone now.

**Comment by AlenToma** [comment]
What should I update ? is it expo publish ?

**Comment by brentvatne** [comment]
@AlenToma - i don't understand the question. you don't need to update any tools, this was a server side fix

**Comment by AlenToma** [comment]
Yah I got that now :) its working again thx a lot

**Comment by weisensee** [comment]
Works like a charm, just published to 14 apps. You guys are legendary and I can't say enough about how impressed I am with expo and how much I appreciate your work! Keep it up!
