### ISSUE TITLE
"expo publish:rollback" has incorrect check for --channel-id

### ISSUE THREAD

**Issue by eddieSullivan** [expo/expo-cli#3783]
### Summary

I think this line should be negated: https://github.com/expo/expo-cli/blob/b85cf8a33c681525ce590446526612af42d23f26/packages/expo-cli/src/commands/publish/publishRollbackAsync.ts#L15

It's giving that error message when --channel-id is *not* provided, when it should give that error message when --channel-id *is* provided.

### Environment

  Expo CLI 4.10.0 environment info:
    System:
      OS: macOS 11.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v15.14.0/bin/yarn
      npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 22, 25, 26, 27, 28, 29, 30
        Build Tools: 23.0.2, 25.0.0, 25.0.2, 26.0.1, 26.0.2, 27.0.2, 27.0.3, 28.0.3, 29.0.0, 29.0.0, 29.0.2, 30.0.2, 31.0.0
        System Images: android-21 | Google APIs Intel x86 Atom_64, android-22 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
        Android NDK: 21.0.6113669
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.5
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.3 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.10.0
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

Any

### Error output

This flag is deprecated and does not do anything. Please use --release-channel and --sdk-version instead.

### Reproducible demo or steps to reproduce from a blank project

Publish a release or two, then run:
```
npx expo publish:rollback -c default -s 39.0.0
```

and you'll see the error. Note that this command works fine:

```
npx expo publish:rollback -c default -s 39.0.0 --channel-id anything
```

**Comment by EvanBacon** [comment]
Wow, sorry about that -- opened a PR to fix it.
