### ISSUE TITLE
Expo init gets stuck on installing JavaScript dependencies on Windows

### ISSUE THREAD

**Issue by gfmoore** [expo/expo-cli#3787]
### Summary

As heading.

To solve I have totally removed node from my win 10 system, rebooted, reinstalled and followed instruction to load expo etc

In new folder, using windows command prompt with admin rights (cause I tried everything else...)

expo init myapp

The install is stuck on Installing JavaScript dependencies with rotating /. at least 2 hours.

I note there is no verbose option.

I tried npx expo-cli init myapp --npm, the same

npx expo-cli init myapp worked with yarn (i.e. npx expo-cli init myapp) , but then doing yarn android failed to complete after seemingly getting emulator started (but that's another issue I guess.) Anyway trying to follow a tutorial.

I have managed to get this working before, so don't know why it won't work now. (Had similar troubles though - used Windows Command to solve.
EDIT: Just remembered how I got it working. I didn't, I downloaded a project folder and di npm update? or something on it.

Have tried knocking off bitdefender firewall, no joy.

I have seen a closed thread on this issue. However there was no definitive solution.

This react-native stuff is so flaky. I have spent more time rebooting my system than since windows 3.1 and Windows Me  :(

Totally hacked off.

By the way I can't even close down Command window, ctrl-c stops process, but window won't close. Folder is locked and can't be removed except by rebooting.

Let me know what other info I can provide. Thanks

### Environment

Can't run expo diagnostics because I'm not in a project folder, cause I can't create it!!
node v16.7.0 (but happened on earlier version as well)
npm v7.20.3

### Please specify your device/emulator/simulator platform, model and version

Not applicable

### Error output

Installing JavaScript dependencies

### Reproducible demo or steps to reproduce from a blank project

As above

**Comment by gfmoore** [comment]
I have managed to get a project using yarn instead
expo-cli init myapp
yarn android failed
However I had to manually open my emulator from android studio which also failed, lock files, rebooted again, started emulator, ran  yarn android again and ...eventually after an upgrade to expo go, got it running. What a waste of a morning.

However, the issue still exists with npm and perhaps that is where the problem lies???? It's not an old problem is it, but keeps raising it's head.

**Comment by gfmoore** [comment]
Well, you are making a lot of possibly unwarranted assumptions. The first fact is that it doesn't work on my machine, but does on yours. Yipee for you. However, we arn't trying to solve your issue, you are supposed to be helping me solve mine.

Of course it's down to my local environment, hence I need assistance in trying to figure out where the problem lies. 

My emulator works fine thanks.

Note that npm works fine for anything I've tried it with. Why not suggest things that expo depends on and see if it hangs there

I have provided output using your suggested EXPO_DEBUG, not that you provided any help with that.

You assume it's a node issue? Why? What evidence? 

Again I ask that you re-open this issue. Perhaps someone who cares might be able to offer some help, like things to try, or things to investigate.

And finally I will say this: You are a very arrogant young man. I suggest you find another outlet for your abilities, because as someone who is involved in a help desk situation you are talentless and have no feelings for the struggles of others.

**Comment by brentvatne** [comment]
hi @gfmoore! one way you can determine if this is an issue with expo tooling or npm is to run `expo init` and `npm install` separately.

here's how to do that:

1. `expo init gfmoore --no-install`
2. change to the `gfmoore` directory and run `npm install`

does step 1 work for you? does step 2? or does step 2 hang?

if step 2 hangs, then there is an issue with npm and/or your local machine. neither of those are issues with expo-cli and so unfortunately we'll have to close the issue if that is the case, because this repository is intended for bugs with expo-cli. you can, however, continue to ask for support on https://forums.expo.dev.

let me know either way!

**Comment by gfmoore** [comment]
Step 1 fine,
Step 2 hangs

I have been trying everything to figure out what is causing this, but with no joy. However, I accept that this is an npm issue and not expo.

I'll now close. Thanks for your help.
