### ISSUE TITLE
 Error running `xcrun simctl openurl'

### ISSUE THREAD

**Issue by gollkn** [expo/expo-cli#381]
Hello I am trying to start Expo tabs example project on IOS simulator but there is an error.

1) I have installed tabs example project with expo cli and using **Adavanced** workflow
2) I run `npm start` then click to **i** to run it on IOS simulator but receive following error

`[19:59:47] Error running `xcrun simctl openurl booted expfefa43c5edbf4f2facb61bb5f9035a56://127.0.0.1:19000`: An error was encountered processing the command (domain=NSOSStatusErrorDomain, code=-10814):
The operation couldn’t be completed. (OSStatus error -10814.)

[19:59:47] Error running app. Have you installed the app already using Xcode? Since you are detached you must build manually. Error: Process exited with non-zero code: 194
`

I have cleaned simulator content and settings but it wasn't fixed, I have Xcode Version 10.1 (10B61).

Please help me.

**Comment by AdamJNavarro** [comment]
Hey @gollkn,

Since you chose the advanced workflow the devtool creates an ejected project which requires you to build the app via Xcode or Android Studio. If that's not what you want and you just want a standard Expo project that you can run via the expo-cli, can you create a new project and make sure you select the managed workflow?

Cheers,

Adam

**Comment by gollkn** [comment]
hey @AdamJNavarro  thanks for answer, 
there are some doc how to build viaxcode and android studio ?

**Comment by AdamJNavarro** [comment]
We don't have anything in our docs as these processes are no longer Expo-specific. I'd recommend googling and familiarizing yourself with Xcode projects and Android Studio. I'm going to close this issue. If you have any further questions, please don't hesitate to post on our [forums](https://forums.expo.io)!
