### ISSUE TITLE
v4.11.0 - Throw Error - Unable to resolve module ./package.json from /node_modules/react-native-url-polyfill/index.js

### ISSUE THREAD

**Issue by nullmicgo** [expo/expo-cli#3815]
### Summary

I was doing fine with the expo cli version v4.7.0.
I upgraded to v4.11.0 and it throws the following error.
Unable to resolve module ./package.json from /node_modules/react-native-url-polyfill/index.js

None of these files exist:
* package.json
* node_modules/react-native-url-poly-fill/package.json

<img width="414" alt="updated" src="https://user-images.githubusercontent.com/1070485/131683796-8190ec42-eaec-40cc-a1dc-26d51eae888b.png">

### Environment

  Expo CLI 4.11.0 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.5 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 6.14.14 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 31
        Build Tools: 30.0.2, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.13.1 => 0.13.3 
      expo: ^42.0.0 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.11.0
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

iPhone 11 IOS14.5

### Error output

Unable to resolve module ./metadata.json from /Users/kawailau/..../node_modules/@expo-google-fonts/inter/index.js: 

None of these files exist:
  * metadata.json
  * node_modules/@expo-google-fonts/inter/metadata.json/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
   5 | export { useFonts } from './useFonts';
   6 |
>  7 | export { default as __metadata__ } from './metadata.json';
     |                                          ^
   8 | export const Inter_100Thin = require('./Inter_100Thin.ttf');
   9 | export const Inter_200ExtraLight = require('./Inter_200ExtraLight.ttf');
  10 | export const Inter_300Light = require('./Inter_300Light.ttf');

ABI42_0_0RCTFatal
__37-[ABI42_0_0RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start
0x0

### Reproducible demo or steps to reproduce from a blank project

1) Upgrade the expo to v4.11.0
2) yarn run ios

**Possible impact area:**
1) Expo Google Fonts - When import the JSON file from JS Files

**Comment by nullmicgo** [comment]
my current workaround solution is to downgrade it back to v4.7.0.
Then my project will work again.

**Comment by EvanBacon** [comment]
The "Error output" appears to be related to `@expo-google-fonts/inter` but the first error you mentioned is about `react-native-url-polyfill`, are these the same error?

**Comment by EvanBacon** [comment]
Closing as I could not reproduce this issue. If you believe the issue is still relevant, please reopen with a minimum reproducible example.
