### ISSUE TITLE
Publish fails with expo-cli 4.11.0

### ISSUE THREAD

**Issue by nemesis** [expo/expo-cli#3820]
### Summary

I'm trying to publish a JavaScript bundle to a specific release channel in the bare workflow, and the `expo publish` fails with an error on `expo-cli@4.11.0`, but works fine with `expo-cli@4.10.0`.

### Environment

```
Expo CLI 4.11.0 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
      Watchman: 2021.08.30.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - ~/.rvm/gems/ruby-2.7.2/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.11.0
    Expo Workflow: bare
```

### Please specify your device/emulator/simulator platform, model and version

not applicable

### Error output

```
› Expo SDK: 41.0.0
› Release channel: default
› Workflow: Bare

Building optimized bundles and generating sourcemaps...

Publish Assets:
- Asset target: bare


Expo Metro config:
- Bundler target: bare
- Legacy: false
- Extensions: ts, tsx, js, jsx, json
- React Native: project_dir/node_modules/react-native
- Babel config: project_dir/babel.config.js


Expo Metro config:
- Bundler target: bare
- Legacy: false
- Extensions: ts, tsx, js, jsx, json
- React Native: project_dir/node_modules/react-native

Starting Metro Bundler
iOS Bundling complete 3602ms

Bundle                     Size
┌ index.ios.js          3.31 MB
├ index.android.js      3.33 MB
├ index.ios.js.map       9.5 MB
└ index.android.js.map  9.55 MB

💡 JavaScript bundle sizes affect startup time. Learn more.

Analyzing assets
Saving assets
No assets changed, skipped.

Processing asset bundle patterns:
- project_dir/**/*

Uploading JavaScript bundles
Cannot read property 'meta-data' of undefined
TypeError: Cannot read property 'meta-data' of undefined
    at _maybeRunModifiedExpoUpdatesPluginAsync (~/.nvm/versions/node/v15.14.0/lib/node_modules/expo-cli/node_modules/xdl/src/EmbeddedAssets.ts:355:43)
    at Object.configureAsync (~/.nvm/versions/node/v15.14.0/lib/node_modules/expo-cli/node_modules/xdl/src/EmbeddedAssets.ts:37:3)
    at Object.publishAsync (~/.nvm/versions/node/v15.14.0/lib/node_modules/expo-cli/node_modules/xdl/src/project/publishAsync.ts:179:3)
    at actionAsync (~/.nvm/versions/node/v15.14.0/lib/node_modules/expo-cli/src/commands/publishAsync.ts:88:18)
```

### Reproducible demo or steps to reproduce from a blank project

1. Upgrade to `expo-cli@4.11.0`
2. `expo publish --release-channel=somechannel`

**Comment by EvanBacon** [comment]
Seems like a regression from https://github.com/expo/expo-cli/pull/3764

**Comment by jkhales** [comment]
Hey @nemesis I couldn't repro this on a fresh install. But based on the error logs it seems like it's having difficulty finding the AndroidManifest.xml

Have you done anything non standard there?

**Comment by nemesis** [comment]
Hey @jkhales 

> Have you done anything non standard there?

Not really, I think. We're not currently in the Play Store, but the manifest was added when we ejected to a Bare workflow. I believe without it we weren't able to complete the ejection process, or maybe some subsequent commands weren't succeeding without the manifest (like `publish`).

> Would you mind sharing the contents of your AndroidManifest.xml if possible and perhaps the directory structure of where it is located?

Sure. The contents:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.appname.app"></manifest>
```

It's located under `$(PROJECT_ROOT)/android/app/src/main/AndroidManifest.xml`.

> Another Q I have is are you running this in the root of the project?

Yes. 

Hope this helps - let me know if I can help with anything else.

**Comment by jkhales** [comment]
> <manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.appname.app"></manifest>

That is the entire contents of the `AndroidManifest.xml`? As in that is what you would cat if you `cat`'d it?

And when you ejected do you remember if you were using `expo-cli` 4.10 or 4.11?

**Comment by nemesis** [comment]
> That is the entire contents of the `AndroidManifest.xml`? As in that is what you would cat if you `cat`'d it?

Yep. 😸 

> And when you ejected do you remember if you were using `expo-cli` 4.10 or 4.11?

Oh, we ejected before 4.10 or above was available. Judging by git logs we were on 4.4.7 at the time.

**Comment by jkhales** [comment]
OK, I was able to repro your issue using the `AndroidManifest.xml` that you supplied. 

It seems like the problem originated in the faulty `eject` you mentioned.

My impression is that your android app won't work as expected with your current manifest, but will follow up with more details in a little.

If you aren't concerned with android, you can get get things working now by supplying the missing "main application" (will be putting up a PR for better error messaging as well):

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.appname.app">
  <application android:name=".MainApplication"/>
</manifest>
```

**Comment by nemesis** [comment]
> It seems like the problem originated in the faulty `eject` you mentioned.

Yeah, as far as I remember the eject didn't supply an `AndroidManifest.xml`, and I just grabbed an empty one from the Android docs.

> A second way to fix your `AndroidManifest.xml` would be to `rm -rf android` and redo `expo eject`. (make sure you aren't deleting anything you need when you do this though!), this would give you back a functional `AndroidManifest.xml`.

Just out of curiosity, would this work out fine if the project is already using the bare workflow?

Thanks for looking into this! Tried publishing with v4.11.0 and the manifest you provided and it works. 🙌

**Comment by jkhales** [comment]
> 
> Just out of curiosity, would this work out fine if the project is already using the bare workflow?
> 

This is a bit of a non standard situation so I'm hesitant to give you strong assurances here. I would recommend making sure important changes are committed before trying anything.

One update to my suggestion would be to use `expo prebuild --clean` instead as a safer approach than rerunning `expo eject`.

Glad you got things working!
