### ISSUE TITLE
react-native link don't work

### ISSUE THREAD

**Issue by tomderudderetna** [expo/expo-cli#383]
`react-native link` command don't work.
how to link with expo?

**Comment by wkozyra95** [comment]
https://docs.expo.io/versions/latest/expokit/eject/

**Comment by AdamJNavarro** [comment]
Hey @tomderudderetna,

As @wkozyra95 alluded to, you can not use `react-native link` with a standard Expo project. You'll have to eject (which creates the `android` and `ios` directories) that the aforementioned command needs to be able to be executed.

Also, for future reference, please refrain from creating issues on this repo if the issue doesn't not pertain to the `expo-CLI` devtool. Our [forums](http://forums.expo.io) are a great place to ask these types of questions.

Cheers,
Adam
