### ISSUE TITLE
run:ios -d device not found when device name contains brackets containing an integer

### ISSUE THREAD

**Issue by Lat91** [expo/expo-cli#3843]
### Summary

iPhone device name (settings > General > About > Name) of the form "string (integer)" for example "iphone (2)" note the space between the string and opening bracket as well.  Reproduced with two different iphones and two different Macs with expo.  Wasted far too much time trying to figure out why my iphones couldn't be found when executing expo run:ios -d until the penny dropped and renamed the device.

Expected:
Connect iphone to mac
run: expo run:ios -d
Expect to see connected device in list of devices to run the app on, as well as the simulators.

Actual:
The device is not found and needs to be renamed in order to be found.  Any name that doesn't have a space followed by an integer in brackets seems to be ok.

Example device names used on the iphone (settings > General > About > Name) (taking values within double quotes):
"iphone (th5)" - OK
"iphone (255)" - NOK
"iphone(255)" - OK
"iphone (2)" - NOK
"iphone(2)" - OK
"Foo (2)" - NOK
"Foo(2)" - OK

### Environment

Expo CLI 4.11.0 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.21.0 - ~/.nvm/versions/node/v12.21.0/bin/node
      npm: 7.6.0 - ~/.nvm/versions/node/v12.21.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 29.0.2, 29.0.3, 30.0.0, 30.0.3
        System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.11.0
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

iphone XR and 6S with appropriate device name as per summary ios 14.7.1

### Reproducible demo or steps to reproduce from a blank project

Any project is just fine as it is the run instruction which has the suspected bug when trying to find devices with the offending name.

**Comment by EvanBacon** [comment]
I can reproduce this, unfortunately it's unclear how we can go about safely fixing this without rewriting core parts of xctrace. Currently we run `xcrun xctrace list devices` then parse the devices using regex, we expect:

```
Evan’s MacBook Pro (5665437B-E3BC-XXXX-9FC6-FX679XC4FX0X)
Evan's phone (1) (14.8) (00008101-00XXXXXXX62X003A)
```
then we parse up until the first numeric capture group. If the device doesn't have two numeric capture groups, then we assume it is a non-iOS device (i.e. computer) and omit it. We could hard code in support for having multiple capture groups but that seems pretty unreliable in the long run. `xcrun xctrace` is also an absurdly long command (a couple of seconds to run) so probably not worth it to improve it right now, would be better to replace it with a Node.js implementation that uses `net` to determine which devices are connected to the computer.

**Comment by EvanBacon** [comment]
This is fixed when used with ‘EXPO_USE_APPLE_DEVICE’ and in the new versioned CLI, this will be default behavior.
