### ISSUE TITLE
Android Variants - android apk with variant in wrong output folder

### ISSUE THREAD

**Issue by maitriyogin** [expo/expo-cli#3846]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `expo-cli@4.11.0` for the project I'm working on.

Ok, so here's the issue, when using `expo run:android --variant devDebug` expo-cli looks for the built apk file in the wrong dir
`android/app/build/outputs/apk/devbuild`
although gradle builds it here
`android/app/build/outputs/apk/dev/build`
Also the name of the apk is `app-devbuild.apk` instead of `app-dev-build.apk`

The patch fixes this by making sure the variant is escaped correctly and the correct path and apk name is created as per gradles expectations ...

Without this, expo-cli tries to search for the apk in `android/app/build/outputs/apk/devbuild` while starting up metro and then throws the following and so ending my experience ....
`Failed to resolve APK build file in folder "<approot>/android/app/build/outputs/apk/devdebug"`

This is part 2 of the Android Variants issues.

/Stephen

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/expo-cli/build/commands/run/android/runAndroid.js b/node_modules/expo-cli/build/commands/run/android/runAndroid.js
index 59733a7..93f704d 100644
--- a/node_modules/expo-cli/build/commands/run/android/runAndroid.js
+++ b/node_modules/expo-cli/build/commands/run/android/runAndroid.js
@@ -280,9 +280,9 @@ async function resolveOptionsAsync(projectRoot, options) {
   const variant = options.variant.toLowerCase();
 
   const apkDirectory = _xdl().Android.getAPKDirectory(projectRoot);
-
-  const apkVariantDirectory = _path().default.join(apkDirectory, variant);
-
+  const variantFolder = variant.includes('debug') ? variant.replace('debug', '-debug') : variant.includes('release') ? variant.replace('release', '-release') : variant;
+  const variantFolders = variantFolder.split('-')
+  const apkVariantDirectory = _path().default.join(apkDirectory, ...variantFolders);
   return { ...options,
     port,
     device,
@@ -290,7 +290,7 @@ async function resolveOptionsAsync(projectRoot, options) {
     launchActivity: `${packageName}/${mainActivity}`,
     packageName,
     apkVariantDirectory,
-    variantFolder: variant,
+    variantFolder,
     appName: 'app'
   };
 }
@@ -320,7 +320,6 @@ async function actionAsync(projectRoot, options) {
       metroPort: props.port
     });
   }
-
   const apkFile = await getInstallApkNameAsync(props.device, props);
 
   _log().default.debug(`\u203A Installing: ${apkFile}`);
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by EvanBacon** [comment]
May you please provide a minimal repro of the gradle you're working with?

**Comment by EvanBacon** [comment]
Would you be able to try running #3856 to see if it solves your issue?
