### ISSUE TITLE
Network timeout when trying to use expo go

### ISSUE THREAD

**Issue by KovalchukKonstantin** [expo/expo-cli#3850]
### Summary

I am unable to launch expo go. First I  have tried running through wsl2 like i usually do but that was completely unsuccesful so I switched to windows.  My phone won't connect at all so i started using Android Emulator. The furthest I was able to go is that it launches but then goes to the blue screen with not able to connect  Network response timed out. 

### Environment

  Expo CLI 4.11.0 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

PIXEL 2 API 30, Android 11

### Reproducible demo or steps to reproduce from a blank project

expo start
start the android emulator 
on expo ui press start emulator

**Comment by schrecka** [comment]
+1

**Comment by byCedric** [comment]
Hi @KovalchukKonstantin, unfortunately, using WSL isn't as easy as it seems. WSL has a fairly complex network system, basically it's running its own subnet and has its own IPs. This confuses the Metro and Expo bundlers and probably binds to a wrong IP, causing the network timed out issue.

There is a way to get it working though, [it won't be easy but it works](https://forums.expo.dev/t/expo-with-wsl2-over-lan/38817/4?u=bycedric).

Alternatively, you could work around this issue by using tunneling. Run `expo start --tunnel` to start up the bundler which tunneled past the double network.

Hope this helps!

**Comment by KovalchukKonstantin** [comment]
Hello @byCedric thank you for your response. I gave up on trying to make it work with wsl so now I am running it straight on my Windows computer. I also turned off all the firewalls and enabled traffic through the respective ports. and it still wont work. The tunnel option doesn't launch properly either due to the installation error or something.
