### ISSUE TITLE
[EAS][Android] Splash screen shifts upward at the end 

### ISSUE THREAD

**Issue by artsnr1** [expo/expo-cli#3854]
### Summary

Splash screen shifts upward at the end with EAS build like this https://stackoverflow.com/q/54751605/9399066. It's fine with expo build.

### Environment

Managed workflow production build

### Please specify your device/emulator/simulator platform, model and version

Android

### Error output

--

### Reproducible demo or steps to reproduce from a blank project

--

**Comment by EvanBacon** [comment]
possibly a duplicate of https://github.com/expo/expo-cli/issues/3832
