### ISSUE TITLE
NextJS dev server timeout on page load

### ISSUE THREAD

**Issue by nzhenry** [expo/expo-cli#3859]
### Summary

I created a basic starter project using 'expo init' and then followed the instructions at https://docs.expo.dev/guides/using-nextjs.

When I try to load the index page, the dev server times out.

### Environment

```
Expo CLI 4.11.0 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.6 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
      Watchman: 2021.09.13.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.11.0
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

Chrome 92.0

### Error output

No console output

### Steps to reproduce
- `expo init`
- `cd [project name]`
- `yarn add -D @expo/next-adapter`
- `yarn next-expo`
- `yarn next dev`
- Send HTTP request to http://localhost:3000
### Expected behaviour
Dev server returns HTML response
### Actual Behaviour
Request times out, no console output from dev server

**Comment by samwoolertonFosters** [comment]
I just hit the same issue and think it's because `react-native-web` needs to be transpiled.
I generated a new project per the [docs](https://docs.expo.dev/guides/using-nextjs/) with `npx create-react-native-app -t with-nextjs`, then checked the generated files and found they were transpiling it. Updated my `next.config.js` and it works as expected now.

Here's my `next.config.js` now:
```
const { withExpo } = require("@expo/next-adapter")
const withPlugins = require("next-compose-plugins")
const withFonts = require("next-fonts")
const withImages = require("next-images")

const withTM = require("next-transpile-modules")(["react-native-web"])

module.exports = withPlugins(
  [withTM, withFonts, withImages, [withExpo, { projectRoot: __dirname }]],
  {}
)
```

**Comment by petrbela** [comment]
Also note (just because I spend X hours trying to figure it out) that `withTM` plugin has to be placed before `withExpo`, otherwise the build will get stuck with no console output.

**Comment by AMSTKO** [comment]
@samwoolertonFosters Can you use NextJS dynamic import without issue and this next.config.js config ? I created an issue #3986

**Comment by samwoolertonFosters** [comment]
@AMSTKO I'm not actually using NextJS any more, I ran into a bunch of issues with modules that wouldn't render server-side and found plain Expo Web to be a lot easier to work with (only thing I had to rebuild was navigation with React Router)
