### ISSUE TITLE
Enterprise Apps cannot be launched on iOS 15

### ISSUE THREAD

**Issue by ZHENGXidan** [expo/expo-cli#3862]
### Summary

Enterprise Apps cannot be launched after upgrading to iOS 15. 
We have tried to rebuild the App with "expo build:ios", but it does not work. 

### Environment

  Expo CLI 4.4.3 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.22.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.19.1 - C:\Users\xidanzheng\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.8 - C:\Users\xidanzheng\AppData\Roaming\npm\npm.CMD
    npmPackages:
      expo: ^41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-navigation: ^4.4.4 => 4.4.4
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

iPhone XR/iOS 15

### Reproducible demo or steps to reproduce from a blank project

![image](https://user-images.githubusercontent.com/34149063/134106881-0c564264-1c7c-4270-9a16-25ef2d9edf58.png)

**Comment by brentvatne** [comment]
See https://forums.expo.dev/t/ios-15-cannot-launch-enterprise-signed-application/53701/11

**Comment by brentvatne** [comment]
`expo build` is updated to support ios 15 enterprise builds now
