### ISSUE TITLE
expo:  eject a simple project -> error "cannot read property 'ressources' of null"

### ISSUE THREAD

**Issue by devSeb** [expo/expo-cli#3865]
### Summary

I create a new project and i would like to eject my project.
here my differents steps

-> expo init my-project
-> add lib
-> commit + push in a branch master
-> create a new branch "mobile"
-> expo eject the project

### Environment

my package.json
"dependencies": {
"@react-native-async-storage/async-storage": "^1.15.8",
"expo": "~42.0.1",
"expo-splash-screen": "~0.11.2",
"expo-status-bar": "~1.0.4",
"expo-updates": "~0.8.1",
"react": "16.13.1",
"react-dom": "16.13.1",
"react-native": "~0.63.4",
"react-native-gesture-handler": "~1.10.2",
"react-native-reanimated": "~2.2.0",
"react-native-screens": "~3.4.0",
"react-native-unimodules": "~0.14.5",
"react-native-web": "~0.13.12",
"react-redux": "^7.2.5",
"redux": "^4.1.1",
"redux-persist": "^6.0.0"
},
"devDependencies": {
"@babel/core": "^7.9.0"
},

version of expo-cli: 4.4.8

### Please specify your device/emulator/simulator platform, model and version

android 

### Error output

`Cannot read property 'resources' of null
TypeError: Cannot read property 'resources' of null
at removeColorItem (E:\DEV\projects\folder\project\node_modules@expo\config-plugins\src\android\Colors.ts:39:16)
at Object.assignColorValue (E:\DEV\projects\folder\project\node_modules@expo\config-plugins\src\android\Colors.ts:72:10)
at setSplashColorsForTheme (E:\DEV\projects\folder\project\node_modules@expo\prebuild-config\src\plugins\unversioned\expo-splash-screen\withAndr
oidSplashStyles.ts:79:17)`

### Reproducible demo or steps to reproduce from a blank project

My reproduce steps

-> expo init my-project
-> add lib ( in my package.json)
-> commit + push in a branch master
-> create a new branch "mobile"
-> expo eject the project

thanks for help

**Comment by EvanBacon** [comment]
Does this issue exist on a more recent version of `expo-cli` (like `4.12.0`)?

**Comment by brentvatne** [comment]
you should be using a more recent version of expo-cli, we recommend that you always stay up to date. please update to 4.11.0

(please don't spam multiple repositories with issues, https://github.com/expo/expo/issues/14494 or this issue were sufficient)
