### ISSUE TITLE
Updating version flag for consistancy (to -v not -V)

### ISSUE THREAD

**Issue by jbburf** [expo/expo-cli#3883]
### Do you understand that any feature requests opened in the core Expo repository will be closed?

Yes

**Comment by jbburf** [comment]
Can we update the version flag to a lowercase 'v' so it is consistent with other packages?

**Comment by EvanBacon** [comment]
The `-V | --version` flag is default in commander, which is one of the most popular Node.js CLI packages https://github.com/tj/commander.js#version-option
