### ISSUE TITLE
503 when building and when running locally

### ISSUE THREAD

**Issue by JoshKeenan** [expo/expo-cli#3888]
### Summary

Currently unable to run code locally or generate new builds, when running locally anytime I try to use Expo Go to connect to the server on my laptop I get a 503. When doing a new build I am getting a 503 that is identical.

### Environment

  Expo CLI 4.4.7 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.8.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.21.0 - /usr/local/bin/npm
      Watchman: 2021.08.23.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    IDEs:
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.4.7
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Expo Go iOS 2.21.3 iPhone X 10,6 

### Error output

Error: Request failed with status code 503
    at createError (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (node:events:406:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

### Reproducible demo or steps to reproduce from a blank project

run expo start.

or 

run expo build:ios

**Comment by AchrafBn** [comment]
same problem

**Comment by jean-louis1776** [comment]
same problem too 😑😤😡

**Comment by jean-louis1776** [comment]
servers crashed???

**Comment by scalfs** [comment]
same problem here

**Comment by leaky** [comment]
I didn't realize there was an external dependency to launch apps locally - this means you're unable to develop apps locally when there's no internet connection...?

**Comment by jean-louis1776** [comment]
ya I saw this
