### ISSUE TITLE
Cannot have space in Apple ID password (on Mac)

### ISSUE THREAD

**Issue by robbiemu** [expo/expo-cli#389]
## Description

I am developing an app to run on web and ios, using Expo (with rnw for the web component). I decided to begin to set up the app store presence today -- but I am running into issues:
```
We need your Apple ID/password to ensure the correct teamID and appID

Note: Expo does not keep your Apple ID or your Apple password.

? What's your Apple ID? MY_VALID_APPLE_ID
? Password? [hidden]
[16:22:23] Validating Credentials...
[16:22:24] Error while gathering & validating credentials
[16:22:24] Reason:Invalid credentials, raw:"Invalid username and password combination. Used 'MY_VALID_APPLE_ID' as the username."
[16:22:24] Set EXPO_DEBUG=true in your env to view the stack trace.
error Command failed with exit code 1.
```
I can log in just fine with these same credentials using the web. I thought to try to turn off 2FA, but apple doesn't allow that any longer.

[stackoverflow](https://stackoverflow.com/questions/54816511/when-running-expo-buildios-getting-invalid-credentials-even-though-i-can-sign)

## Expected Behavior

I should be able to log in on the commandline

## Observed Behavior

see above error code.

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:
```
There is a new version of expo-cli available (2.11.1).
You are currently using expo-cli 2.6.14
Run `npm install -g expo-cli` to get the latest version

  Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.5.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.4 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      expo-cli: 2.6.14
```

## Reproducible Demo

As I have resolved my issue, I believe that I have identified it. Having a space in my password caused the problem. When I changed my apple password to one without spaces, it began working.

I got the hunch that this might be the issue after reading the linked response in [this thread](https://forums.expo.io/t/invalid-apple-credentials-for-build-ios/6749/22). 

Maybe whatever fix was applied to resolve that issue in windows has now broken proper function on the mac?

**Comment by tcdavis** [comment]
> I can log in just fine with these same credentials using the web.

You could use the credentials to log in to what?

**Comment by robbiemu** [comment]
my apple developer account -- the App Store connect, etc.

@tcdavis - when you say you can log in just fine, do you mean that:
1. you have an account with a password with a space in it
2. you are on the same expo build

If so, there's not so much left in difference between your set up and mine. I am on MacOS, and was using the terminal with expo. Can I submit any system details for you? Or are we not that far yet?

**Comment by wkozyra95** [comment]
I tested this with password containing spaces and it worked correctly.

**Comment by robbiemu** [comment]
I can't revert my password to test again, but this _definitely_ was happening on my build in my normal Mac terminal. I had triple checked before changing my password based on the hunch I had from the research that I did. Just a heads up this may be opened again by someone else (or me a year from now, when apple lets me revert my password)

**Comment by brentvatne** [comment]
cc @pvinis please let us know if this still doesn't work for you

**Comment by pvinis** [comment]
I will try it soon and get back to you. Thanks.
