### ISSUE TITLE
Install fails in alpine node

### ISSUE THREAD

**Issue by MindFreeze** [expo/expo-cli#390]
## Description

I publish an expo app through a Gitlab CI Docker build. Today it stopped working (after the release of the latest version). Locking expo-cli to the old version doesn't help either.
It tries to build it from source and requires python. Why would I put python in a node container?

This is the error:
```
$ npm install -g expo-cli

> @expo/traveling-fastlane-linux@1.8.0 preinstall /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-linux
> node platform.js

/usr/local/bin/expo -> /usr/local/lib/node_modules/expo-cli/bin/expo.js
/usr/local/bin/expo-cli -> /usr/local/lib/node_modules/expo-cli/bin/expo.js

> node-pty-prebuilt@0.7.6 install /usr/local/lib/node_modules/expo-cli/node_modules/node-pty-prebuilt
> prebuild-install || node scripts/install.js

prebuild-install WARN install No prebuilt binaries found (target=11.10.0 runtime=node arch=x64 libc=musl platform=linux)
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
gyp ERR! System Linux 4.15.0-23-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--build_v8_with_gn=false"
gyp ERR! cwd /usr/local/lib/node_modules/expo-cli/node_modules/node-pty-prebuilt
gyp ERR! node -v v11.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
```

## Environment

Gitlab CI with `image: node:alpine`

**Comment by MindFreeze** [comment]
Even if I add python and the other requirements it still fails with:
```
/builds/.../node_modules/@expo/traveling-fastlane-darwin/platform.js:1
(function (exports, require, module, __filename, __dirname) { if (process.platform !== 'darwin') throw new Error('Not running on darwin');
                                                                                                 ^

Error: Not running on darwin
    at Object.<anonymous> (/builds/.../node_modules/@expo/traveling-fastlane-darwin/platform.js:1:104)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:499:15)
    at startMainThreadExecution (internal/bootstrap/node.js:436:3)
```

**Comment by ide** [comment]
> Why would I put python in a node container?

It's pretty common for native Node packages to use node-gyp, which uses Python: https://github.com/nodejs/node-gyp. Since you're installing Expo CLI and probably doing build work instead of running a live service, using Ubuntu instead of Alpine might make more sense but anything works with the right dependencies.

For the darwin issue, it looks like the darwin package is only imported when:
```js
const travelingFastlane =
  process.platform === 'darwin'
    ? require('@expo/traveling-fastlane-darwin')()
    : require('@expo/traveling-fastlane-linux')();
```
Are you using plain Node or something that could be loading modules that aren't used?

**Comment by nicknovitski** [comment]
You can keep python out of your deployed containers using [multistage builds](https://docs.docker.com/develop/develop-images/multistage-build/).

[traveling-fastlane-darwin is an optional dependency of expo-cli](https://github.com/expo/expo-cli/blob/ffc5e9f994454c2422a4a6ba9dddbc0615fd31c1/packages/expo-cli/package.json#L102), which means that `npm` will attempt to install it, but ["build failures do not cause installation to fail."](https://docs.npmjs.com/files/package.json.html#optionaldependencies) `traveling-fastlane-darwin` [has `platform.js` as a preinstall script](https://github.com/expo/expo-cli/blob/ffc5e9f994454c2422a4a6ba9dddbc0615fd31c1/packages/traveling-fastlane/publishing/darwin/package.json#L8), which means it will run it before trying to install, and raise exactly that error in non-darwin environments, causing the installation of that package to fail, but not the installation of `expo-cli` as a whole.  It's normal to see those errors in linux environments along with the message `Skipping failed optional dependency`, and actually, you see the same things in darwin environments, where `traveling-fastlane-linux` fails to install, for the same reason.

**Comment by nicknovitski** [comment]
Can you post a minimal dockerfile which reproduces your problem?  This one, for example, works:

```
from mhart/alpine-node

RUN apk --no-cache add python

RUN npm install --global expo-cli
```

**Comment by MindFreeze** [comment]
I had Gitlab CI setup like the example in the docs: https://docs.expo.io/versions/latest/guides/setting-up-continuous-integration/
The differences were `unsafe-perm true`, `install yarn` and `git`.
```
image: node:alpine
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ~/.npm
stages:
  - deploy
before_script:
  - npm config set unsafe-perm true
  - npm install -g yarn # required for react-native-expo-image-cache fork
  - npm ci
expo-deployments:
  stage: deploy
  script:
    - apk add --no-cache bash git
    - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - npx expo publish --non-interactive
```
Anyway I switched to a full ubuntu image with all python, build-essential and a bunch of other stuff we use to build other projects and now I still get the darwin error, but the build doesn't fail

**Comment by MindFreeze** [comment]
I understand there might be build dependencies but I was just frustrated that my CI/CD suddenly stopped working with no warning and I couldn't find a mention of a breaking change anywhere.

**Comment by fson** [comment]
We've [removed](https://github.com/expo/expo-cli/pull/401) this dependency in expo-cli v2.11.7. (Going forwards, it will only be installed if you run `expo opt-in-google-play-signing`.)

Installing Expo CLI in Alpine should no longer require installing `build-essential`.
