### ISSUE TITLE
Credentials Manager: Stores Keystore Key as Alias Key

### ISSUE THREAD

**Issue by Gustl22** [expo/expo-cli#3906]
### Summary

Credentials Manager (`expo credentials:manager`) stores Keystore Key as Alias Key, therefore any build with ` expo build:android -t app-bundle -c` while uploading my own keystore credentials leads to an error. The Alias Key isn't stored at all.

### Environment

  Expo CLI 4.12.1 environment info:
    System:
      OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
      Shell: 5.1.4 - /bin/bash
    Binaries:
      Node: 16.0.0 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/bin/yarn
      npm: 7.10.0 - /usr/local/bin/npm
    npmPackages:
      @expo/webpack-config: ~0.12.63 => 0.12.82 
      expo: ^42.0.0 => 42.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Ubuntu 21.04 (Linux), IntelliJ 2021.2.2 (Ultimate Edition)

### Error output

When Running Gradle with ` expo build:android -t app-bundle -c`
```
[stderr] Execution failed for task ':app:signReleaseBundle'.

[stderr] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

[stderr]    > Failed to read key oberhauser-dev-01 from store "/tmp/turtle/keystore-1c0006fe-c326-4c0c-b4a0-ec6cabb4fc04.jks": Get Key failed: Given final block not properly padded
```

### Reproducible demo or steps to reproduce from a blank project

I call:
```
expo credentials:manager
```
✔ Select platform › android
✔ What do you want to do? › Upload Keystore hashes
✔ Would you like to upload a Keystore or have us generate one for you?
If you don't know what this means, let us generate it! :) › I want to upload my own file
✔ Path to the Keystore file. … /my-dev.jks
✔ Keystore password … **myKeyStorePass**
✔ Key alias … my-dev-01
✔ Key password … **myAliasKeyPass** **(other than the first, tried multiple times, copy paste and manual key inputs)**
Keystore updated successfully

Next:
✔ What do you want to do? › Download Keystore from the Expo servers
✔ Do you want to display the Android Keystore credentials? … yes
Saving Keystore to @my-dev__my-dev.bak.jks
Keystore credentials
  Keystore password: **myKeyStorePass**
  Key alias:         my-dev-01
  Key password:      **myKeyStorePass**
  Path to Keystore:  @my-dev__my-dev.bak.jks

**Comment by Gustl22** [comment]
I updated my expo client from `4.12.1` (released 20 days ago) to `4.12.7` and it seems to work now. Thanks for your support!

**Comment by Gustl22** [comment]
@quinlanj I'll try to reproduce again. But as nothing was updated here, I think the issue still exists. I'll let you know.

**Comment by EvanBacon** [comment]
This appears to be resolved in EAS CLI (`expo build:android` is deprecated). If you encounter this issue in the future, please open an issue on [expo/eas-cli](https://github.com/expo/eas-cli/issues/new/choose).
