### ISSUE TITLE
Couldn't start project on Android

### ISSUE THREAD

**Issue by cuongw** [expo/expo-cli#392]
## Description

Couldn't start project on Android: could not install *smartsocket* listener: Address already in use
ADB server didn't ACK.
* failed to start daemon *
error: cannot connect to daemon

## Behavior

`expo start` and run on Android emulator - `Genymotion`

## Environment

```
Expo CLI 2.11.2 environment info:
    System:
      OS: Linux 4.15 elementary OS 5.0 Juno
      Shell: 5.4.2 - /bin/zsh
    Binaries:
      Node: 10.15.1 - /usr/bin/node
      Yarn: 1.13.0 - /usr/bin/yarn
      npm: 6.8.0 - /usr/bin/npm
    npmGlobalPackages:
      expo-cli: 2.11.2
```

Thank you, everyone!

**Comment by tcdavis** [comment]
Something is already listening on that port.  You'll need to figure out what and free it up.
