### ISSUE TITLE
expo-cli 4.12.4 crashes while looking for projectId

### ISSUE THREAD

**Issue by sguha00** [expo/expo-cli#3928]
### Summary

Running `expo start` crashes with expo-cli 4.12.4 crashes on startup when the project has an `app.json` with an `extra` key but without an `eas` sub-key

Looks like the error is on this line https://github.com/expo/expo-cli/blob/930764ccdde1abf4f386043fed40c24a235137d3/packages/xdl/src/Webpack.ts#L158

### Environment

Expo CLI 4.12.4 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm
      Watchman: 2021.10.11.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /Users/***/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.3
        System Images: android-29 | Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.12.4
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

OSX 10.15.7

### Error output

`% expo start
Starting project at /Users/***/code
Developer tools running on http://localhost:19003
Opening developer tools in the browser...
Starting Metro Bundler
Cannot read property 'projectId' of undefined
TypeError: Cannot read property 'projectId' of undefined
    at startDevServerAsync (/Users/***/.nvm/versions/node/v14.17.5/lib/node_modules/expo-cli/node_modules/xdl/src/start/startDevServerAsync.ts:73:53)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at startAsync (/Users/***/.nvm/versions/node/v14.17.5/lib/node_modules/expo-cli/node_modules/xdl/src/start/startAsync.ts:74:41)
`

### Reproducible demo or steps to reproduce from a blank project

https://github.com/sguha00/projectId-crash

**Comment by ataravati** [comment]
This still happens to someone in our team with explo cli 5.3.1 on Windows.
