### ISSUE TITLE
Error: _getCertData: couldn’t find cert bag - when building standalone app for ios

### ISSUE THREAD

**Issue by lanman2000** [expo/expo-cli#393]
## Description

We’re getting the following error when building for iOS. This is the first time we’ve done this so it’s not like it stopped working on something. It’s never worked. We’ve confirmed the certificate, key and provisioning profile are all together in our apple dev account. Not sure what else to check and the error says to post here as you guys have more detailed logs in the background you can look at.

```
Error: _getCertData: couldn’t find cert bag
at _getCertData (/usr/local/turtle-js/node_modules/xdl/build/detach/IosCodeSigning.js:259:11)
at _genP12CertFingerprint (/usr/local/turtle-js/node_modules/xdl/build/detach/IosCodeSigning.js:233:20)
at Object. (/usr/local/turtle-js/node_modules/xdl/build/detach/IosCodeSigning.js:13:25)
at Generator.next ()
at step (/usr/local/turtle-js/node_modules/xdl/build/detach/IosCodeSigning.js:230:191)
at /usr/local/turtle-js/node_modules/xdl/build/detach/IosCodeSigning.js:230:361
at
```

SDK version is 32.0.0

Build command used was:
expo bi -c --config app.json --release-channel qaenv
Then i enter my apple developer account username and password.
Then selected the option “I will provide all the credentials and files needed”
Then provided the full local path to my P12 file
Then provided the password for my P12 file
Then provided the full local path to my P8 file
Then entered the Key ID for that p8 file
Then provided the full local path to my .mobile provisioning profile file.
Then the build runs and eventually fails with the error noted in my OP. The last try is here btw:
https://expo.io/builds/9c5a27c9-f925-4a0b-a04a-d5775f9f1b74 1

We are able to build the apk for android. The error seems related to the apple distribution certificate which is why only the IOS build is failing.

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

Expo CLI 2.10.0 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.1.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.1 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.0.9 
    npmGlobalPackages:
      expo-cli: 2.10.0

**Comment by dsokal** [comment]
Hello @lanman2000,
tt seems that your Distribution Certificate is broken. Try to generate a new one or make sure you're passing the right one to expo-cli.

**Comment by giuliobosco** [comment]
I have the same problem, and I'm passing him a working Distribution Certificate...
What can I do?

**Comment by dsokal** [comment]
@giuliobosco please make sure that you're able to import your Distribution Certificate to Keychain (by double-clicking on the file and providing the password. If you get an error like below it means your Distribution Certificate is broken:
![Screenshot 2019-05-13 at 15 47 35](https://user-images.githubusercontent.com/5256730/57626641-982ad980-7596-11e9-9309-79727bf80efb.png)

**Comment by giuliobosco** [comment]
@dsokal Thanks, it worked!!!
