### ISSUE TITLE
Expo optimize does not make use of all CPU cores

### ISSUE THREAD

**Issue by Rohansi** [expo/expo-cli#3937]
### Summary

Our app has ~800 images bundled and 99% of those are pulled from another location occasionally meaning we need to re-run expo optimize across all of them quite often where the current hash checking doesn't save us. It would be great if expo optimize made use of additional CPU cores so it can zip through large sets of images like this.

### Environment

  Expo CLI 4.12.8 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
    Expo Workflow: managed

(I'm working on upgrading now I promise)

### Please specify your device/emulator/simulator platform, model and version

Android device, Windows dev PC

### Reproducible demo or steps to reproduce from a blank project

1. Add lots of images to your expo project
2. Run `npx expo-optimize`
3. Watch your CPU usage sit at <5% for a long time

**Comment by mako-taco** [comment]
@Rohansi you can install my company's [fork](https://github.com/expo/expo-cli/pull/3956) of `expo-optimize` to get this behavior.  It is a lot faster.

**Comment by kbrandwijk** [comment]
Seems implemented in https://github.com/expo/expo-cli/pull/3956.
