### ISSUE TITLE
Hijacked package 'ua-parser-js'

### ISSUE THREAD

**Issue by yves-bonami** [expo/expo-cli#3938]
Windows Defender reports multiple malicious files and commands when running `expo init`  

This seems to be caused by several versions of the `ua-parser-js` package being hijacked. (See [this issue](https://github.com/faisalman/ua-parser-js/issues/536#issuecomment-949742904)).
The author has requested those packages to be unpublished.

Since I was just following quickstart for the first time, I'm unsure if any action needs to be taken, but it seemed worth mentioning this at least.

**Comment by brentvatne** [comment]
here is our blog post on the topic: https://blog.expo.dev/ua-parser-js-and-malicious-npm-packages-8c13ee4141a
