### ISSUE TITLE
expo fetch:android:hashes not work

### ISSUE THREAD

**Issue by eng-osman** [expo/expo-cli#395]
# expo fetch:android:hashes not work 

Retreiving Android keystore for @******/*****
Writing keystore to C:\ReactNative\Meeting\Meeting.tmp.jks...
Process exited with non-zero code: 3221225781
Set EXPO_DEBUG=true in your env to view the stack trace.

### Environment
windows 10 , 
"expo": "^32.0.0",
"react": "16.5.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",

**Comment by tcdavis** [comment]
That is quite the error code.  From a quick search it appears to be a linking issue.
What shell are you using?
What do you get with EXPO_DEBUG=true ?

**Comment by jkhales** [comment]
Hi, we couldn't reproduce this, but please reopen and provide more information if it is still causing you difficulty.
