### ISSUE TITLE
expo run:ios -d gives error: unrecognized option `--app_deltas'

### ISSUE THREAD

**Issue by goldwareJapan** [expo/expo-cli#3952]
### Summary

Hello I just initialized a new expo app with tabs example
`expo run:ios`  works fine on simulator.
`expo run:ios -d` gives me this error

```
Failed to install the app on device. Error in "ios-deploy" command: ios-deploy: unrecognized option `--app_deltas'
```

do you have any idea what am i doing wrong

### Environment

OSX

❯❯❯ expo -V
4.12.10

### Please specify your device/emulator/simulator platform, model and version

4.12.10

### Error output

Failed to install the app on device. Error in "ios-deploy" command: ios-deploy: unrecognized option `--app_deltas'

### Reproducible demo or steps to reproduce from a blank project

expo init

expo run:ios -d

**Comment by EvanBacon** [comment]
What are the results of `ios-deploy --version`? Should be `1.11.4` or greater
