### ISSUE TITLE
Error: @expo/next-adapter tried to access @expo/config, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound

### ISSUE THREAD

**Issue by oste** [expo/expo-cli#3959]
### Summary

While using @expo/next-adapter with yarn berry(v2/v3) I am getting this error. I think it points to needing to add @expo/config to the package.json.

### Environment

Running `yarn build` with the example project here https://github.com/expo/examples/tree/master/with-nextjs and using latest @expo/next-adapter v3

### Please specify your device/emulator/simulator platform, model and version

web

### Error output

Error: @expo/next-adapter tried to access @expo/config, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound

### Reproducible demo or steps to reproduce from a blank project

https://github.com/expo/examples/tree/master/with-nextjs

**Comment by oste** [comment]
Note this can be resolved by adding `pnpMode: loose` to .yarnmc.yml. Or there is `packageExtensions` that can be added to package.json. See migration guide here https://yarnpkg.com/getting-started/migration#fix-dependencies-with-packageextensions

I will leave this open since I think its best to resolve at the package level.

**Comment by garfieldnate** [comment]
I get the same issue trying to run `expo-cli` and getting `expo-cli tried to access kleur, but it isn't declared in its dependencies;...`. Adding this to to `.yarnrc.yml` fixed it:

```yml
packageExtensions:
  expo-cli@*:
    dependencies:
      kleur: "*" # for expo-cli
```
