### ISSUE TITLE
I have problem usin expo-cli on ubuntu

### ISSUE THREAD

**Issue by Saeideh-Davoudi** [expo/expo-cli#3960]
expo-cli has not yet been tested against Node.js v17.0.1.
I have received this error.
I do not know what should I do

**Comment by TFx01** [comment]
Can you provide more details? How are you executing your program?

**Comment by Saeideh-Davoudi** [comment]
my Ubuntu version is 20.04.3 LTS
my nodejs version is 17.0.1
npm version 8.1.2 
i use this sudo npm install --global expo-cli
this is the problems as you can see in the attachment

![Uploading Screenshot from 2021-11-01 11-30-04.jpg…]()

**Comment by Saeideh-Davoudi** [comment]
![Screenshot from 2021-11-01 11-30-04](https://user-images.githubusercontent.com/65603381/139661599-4eb48db7-cf0e-48e7-b147-8973ce8c3f24.jpg)

**Comment by TFx01** [comment]
There is this warning because they recommend to execute expo with the LTS version of Node, because it might lead to problems, so downgrade the version to the LTS and will be working fine!

**Comment by Saeideh-Davoudi** [comment]
Tnx for the answer. I downgrade it to 16.13.0 but still there is problem.
my Ubuntu version is 20.04.3 LTS
my nodejs version is 16.13.0
npm version 8.1.0
i use this sudo npm install --global expo-cli
this is the problems as you can see in the attachmen
![Screenshot from 2021-11-01 15-03-41](https://user-images.githubusercontent.com/65603381/139665501-1b6e300f-2b43-44ca-a5e8-cbf99b1fa0c9.png)
t

**Comment by TFx01** [comment]
But can you execute your app? can you see if the expo is installed by executing expo --version? it seems to me that you attempt to download is ok

**Comment by Saeideh-Davoudi** [comment]
my version of expo is 4.12.10

**Comment by TFx01** [comment]
Hum.. so its everything correct.

**Comment by Saeideh-Davoudi** [comment]
but it doesn't work

**Comment by Saeideh-Davoudi** [comment]
![Screenshot from 2021-11-03 07-56-11](https://user-images.githubusercontent.com/65603381/140010176-652a6099-738c-4c42-9b14-737dd565ddb3.png
![Screenshot from 2021-11-03 07-57-29](https://user-images.githubusercontent.com/65603381/140010183-304d9fb9-ea2d-4d08-801e-26276500e976.png)
![Screenshot from 2021-11-03 07-58-03](https://user-images.githubusercontent.com/65603381/140010187-e5c87bea-e8a4-4add-a9ea-e9178333f5e1.png)
)

**Comment by EvanBacon** [comment]
It appears as though you don't have any simulators or emulators installed or connected to your device.
