### ISSUE TITLE
[prebuild] Re-running prebuild on the same project produces a changelog

### ISSUE THREAD

**Issue by Yonom** [expo/expo-cli#3961]
### Summary

Running expo prebuild in the same project without any changes to the dependencies or config produces a git changelog (expectation: no changes; same input, same output).

This affects three places:
- SplashScreen.storyboard's guids change
- app.config.js's `android.intentFilters` get duplicated on each prebuild.
- expo-dev-client's `exp+xyz` schemes get added to each intent filter, even if there's already one there

Of course, a workaround is to use `--clear` on each run, but this flag also clears caches which is suboptimal.

### Environment

```
❯ expo diagnostics                                                                                                                                                  

  Expo CLI 4.12.10 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/Cellar/node@16/16.13.0/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.0 - /usr/local/Cellar/node@16/16.13.0/bin/npm
      Watchman: 2021.10.18.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 23, 24, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 31.0.0, 31.0.0, 31.0.0, 31.0.0
        System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~43.0.0 => 43.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.12.10
    Expo Workflow: bare
```

### Please specify your device/emulator/simulator platform, model and version

N/A

### Test 1

- `expo init yonom --yes`
- `expo prebuild` and commit the changes to git
- `expo prebuild` again and check the git changelog

:x: NOK: SplashScreen.storyboard has some changes

![image](https://user-images.githubusercontent.com/1394504/139590615-137de62a-78bb-4d46-8846-b97b6f37bc68.png)

### Test 2

- (reusing the same project made in Test 1)
- Open app.json and add the following intentFilter:

```js
"android": {
  "intentFilters": [{
    "action": "VIEW",
    "data": [{
      "scheme": "https",
      "host": "yonom.example.com"
    }],
    "category": ["BROWSABLE", "DEFAULT"]
  }], ...
}, ...
```
- `expo prebuild` and commit the changes to git
- `expo prebuild` again and check the git changelog

:x: NOK: The file `AndroidManifest.xml` now has a duplicate intentfilter for `yonom.example.com`.

### Test 3

- (reusing the same project from Test 2)
- `expo install expo-dev-client`
- `expo prebuild` and commit the changes to git
- `expo prebuild` again and check the git changelog

:x: NOK: there are multiple instances of "exp+yonom" scheme, every prebuild run adds a new one to each intent filter

![image](https://user-images.githubusercontent.com/1394504/139590722-9e450321-4c67-4eee-83cf-f8f936ddd124.png)

**Comment by EvanBacon** [comment]
`expo prebuild` is meant to be run with the `--clean` flag, we partially support running without the `--clean` flag for convenience and speed.
The `ios` and `android` folders are generated, like the node_modules folder, and are therefore subject to things like uuid values changing between runs (i.e. `SplashScreen.storyboard` changes) usually these changes go unnoticed because generated folders are often gitignored -- we don't currently recommend gitignoring the `ios` and `android` folders because the system is relatively new. 

The intent filter issue appears to be a problem with the expo-dev-client plugin which I can investigate further.

**Comment by Yonom** [comment]
@EvanBacon Thank you! ❤️

**Comment by Yonom** [comment]
@EvanBacon would you be able to take a look at the issue from `Test 2` as well?

It is caused by adding an `intentFilter` to app.json (without using expo-dev-client) and I suspect it has a different root cause:

```
"android": {
  "intentFilters": [{
    "action": "VIEW",
    "data": [{
      "scheme": "https",
      "host": "yonom.example.com"
    }],
    "category": ["BROWSABLE", "DEFAULT"]
  }], ...
}, ...
```
