### ISSUE TITLE
Not getting console.log in expo run:ios: - but getting them on npm run start

### ISSUE THREAD

**Issue by raphaelmsr** [expo/expo-cli#3962]
### Summary

I lately updated to Expo SDK 42 (and now to SDK 43) and I realised I was not getting console.log logs into the expo console when running : expo run:ios 
Only when running npm run start

I thought it was common usage since it was my first time using this magical feature of expo run, but it turned out to be a bug.

### Environment

macOS Monterey 12.0.1
Xcode 13 with iOS 15.0 emulators 
Expo SDK 42 (and 43)

### Please specify your device/emulator/simulator platform, model and version

iOS 15.0 iPhone 13 simulator

### Reproducible demo or steps to reproduce from a blank project

Upgrade to SDK 42, make your first expo:run ios , console.logs won't appear in the console but will appear if run through npm run start

**Comment by EvanBacon** [comment]
What does "npm run start" do in your project?

**Comment by EvanBacon** [comment]
Closing as I cannot repro and cannot get any more info.
