### ISSUE TITLE
Unable to locate adb.exe, can't open adb too.

### ISSUE THREAD

**Issue by NotLGBT** [expo/expo-cli#3963]
### Summary

I made optimization of disk size (simply delete all trash) and when i try to use expo cli - i get typical issue : "Can't open emulator , make it manually from D:/AndroidSdk/..." . I try to resolve this problem with reset SDK Manager, but it doesn't help, so i launch emulator from Android Studio (before i do it from expo host ). And i get another error, that doesn't make my fix-way more clearly : "Unable to locate adb.exe" . After that i try to reassign some enviroment variables (Like Adb  in PATH), that might not have correct way, well - it doesn't work too. So in this time i reset all Android Studio and related garbage (excluding enviroment variables) . So what i get in last attempt : 
Expo :
![image](https://user-images.githubusercontent.com/76618727/139557427-7a4d0d23-2c88-4140-8dcf-7983ed7e44ad.png)
Classic Variables : 
![image](https://user-images.githubusercontent.com/76618727/139557467-248b6947-1d42-414c-bfde-fd663404603f.png)
Path : 
![image](https://user-images.githubusercontent.com/76618727/139557484-070ccf96-f0ef-4ef6-ac66-9c4263b11932.png)

By the way try to run with expo client:install:android - no result (evidently);
And after this manipulation expo doesn't recognize my real phone Imao - casual errro "Check Metro logs"

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

Android 12 SDK 31

### Environment

epxo diagnostic 

### Reproducible demo or steps to reproduce from a blank project

Paste my code project : 
import {StatusBar} from 'expo-status-bar';
import React from 'react';
import {ScrollView, StyleSheet, Text, View} from 'react-native';
import {BACKGROUND_COLOR, PAGES} from './constants';

export default function App () 
{
  return (
    <View>
      <StatusBar style = "auto"/>
      <ScrollView style = {{flex : 1}} horizontal> 
        {PAGES.map((page, index) => 
        (
          <View key = {index.toString()}/>
        ))}
     </ScrollView>   
         </View>
  )
}
const styles = StyleSheet.create(
  {
    container : 
    {
      flex: 1,
      backgroundColor : BACKGROUND_COLOR,
    },
  }
);

**Comment by byCedric** [comment]
Hi @NotLGBT! Setting up environments can be hard and, unfortunately, we can't give full support getting things up and running. That being said, I'm a bit confused about the images you sent, so here are some things from the top of my mind:

1. The terminal image with the Node error stack trace looks "not great", there are a lot of weird characters that should not be there at all. I'm not sure if this is a red flag for your environment being in a "weird state", or if this is related to cmd and special characters.

2. Is the "Classic Variables" image a partial screenshot of the "Environment Variables" settings in Windows? If so, here are some things that pop out:
    - I'm not sure why you have starting and ending `%` characters. If you add them, we can't reference them properly from Node. Basically, if we request `process.env.ANDROID_HOME` we have to use `process.env['%ANDROID_HOME%']` instead. (see [this code](https://github.com/expo/expo-cli/blob/master/packages/xdl/src/Android.ts#L55-L57))
    - I'm not sure if I understand the first line, it looks like you are setting `ANDROID_HOME=$ANDROID_HOME\platform-tools`. Doing this will pretty much invalidate everything else because the next line would be `ANDROID_HOME=$(ANDROID_HOME\platform-tools)\tools/bin`, which points to an invalid directory
    - ^ also goes for `JAVA_HOME\bin=JAVA_HOME\bin`, not sure what this will do

3. Your "Path" screenshot looks fine, and you can validate it by running `adb devices` or `adb.exe devices` in cmd/powershell

I would recommend removing the `ANDROID_HOME` environment variables for the time being. We ship the `expo-cli` with a built-in ADB binary that should work fine. If you don't have an `ANDROID_HOME` variable, it will fall back to that binary and you should be able to get things working again.

Hope this helps!
