### ISSUE TITLE
AndroidManifest.xml missing the required MainApplication element

### ISSUE THREAD

**Issue by joshuacano** [expo/expo-cli#3971]
### Summary

After some routine upgrading of some native libraries in our Bare App, we are now getting the following error when running expo publish. `AndroidManifest.xml missing the required MainApplication element`  However, we do see the publishes successful when running expo publish:history.

### Environment

CircleCI and Locally

### Please specify your device/emulator/simulator platform, model and version

Android

### Error output

![Screen Shot 2021-11-03 at 18 43 47](https://user-images.githubusercontent.com/3310062/140243345-3efd82e5-8822-471a-a2c2-3a054d42a613.png)

![Screen Shot 2021-11-03 at 18 32 05](https://user-images.githubusercontent.com/3310062/140242789-120fe70c-66bc-4e2b-b838-3ed3bc16e3ac.png
![Screen Shot 2021-11-03 at 18 38 19](https://user-images.githubusercontent.com/3310062/140242871-f684593e-746f-4b91-85e7-f27f10e23053.png)
)

### Reproducible demo or steps to reproduce from a blank project

Nothing too significant we could do to reproduce. Expo-cli/publish has been working as expected until our last upgrade of native libraries.

**Comment by EvanBacon** [comment]
Please provide resources, or steps to reproduce the error.

**Comment by joshuacano** [comment]
to reproduce in our Expo 42 code base. We run `./node_modules/.bin/expo publish --non-interactive --release-channel qa`

**Comment by jkhales** [comment]
> to reproduce in our Expo 42 code base. We run `./node_modules/.bin/expo publish --non-interactive --release-channel qa`

Would you mind sharing your AndroidManifest.xml?

**Comment by joshuacano** [comment]
Absolutely.

**Comment by joshuacano** [comment]
[androidmanifest.zip](https://github.com/expo/expo-cli/files/7498379/androidmanifest.zip)

**Comment by joshuacano** [comment]
**UPDATE**: We discovered the issue, expo-cli was looking for MainApplication, however our code had the fully qualified package name in the Android:name in our Activity and Application gradle file in our AndroidManifest.xml. 

Closing bug now!

**Comment by Gongreg** [comment]
@joshuacano, how did you solve this issue? We are also using fully qualified package name and we get this error at the end of `expo export` command.

**Comment by joshuacano** [comment]
android:name=".MainActivity" Was our solution

**Comment by Gongreg** [comment]
Thank you for the answer. 
I will need to check if that does not have any impact in our case.

I am wondering whether checking in  expo-cli for `android:name="*.MainActivity"` would make sense to help people running on bare react native setup to avoid bumping into this issue going forward.
