### ISSUE TITLE
Should error and refuse to start project with invalid name like "react-native" or "expo" or "react"

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#3979]
### Summary

Projects with names like "react-native" will error out during bundling with not-so-useful error messages.

### Environment

```
  Expo CLI 4.12.12 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.1/bin/yarn
      npm: 7.20.3 - ~/.nvm/versions/node/v14.16.1/bin/npm
      Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~43.0.0 => 43.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.12.12
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

n/a

### Reproducible demo or steps to reproduce from a blank project

Try creating a project: `expo init react-native` and running it, you will see an error like this:

<img width="1391" alt="Screenshot_2021-11-05_at_17 02 49" src="https://user-images.githubusercontent.com/90494/140544423-375115f5-bd03-4f88-9b3e-2df11098ed66.png">

**Comment by Aryojaam** [comment]
I can confirm seeing this error after initializing and starting the expo server. @EvanBacon are you currently working on this issue? I would like to have a go at preventing the problem if possible.

**Comment by EvanBacon** [comment]
sure you can give it a try

**Comment by Aryojaam** [comment]
@EvanBacon I have created a draft PR for this problem that shows my approach for fixing this issue. Would you mind reviewing it and give me some feedback if possible? Thanks in advance :)

**Comment by Aryojaam** [comment]
@brentvatne @EvanBacon The PR concerning this problem is merged. Therefore, this issue can be resolved :)
