### ISSUE TITLE
CLI does not update to latest point version

### ISSUE THREAD

**Issue by tomByrer** [expo/expo-cli#3980]
### Summary

`expo upgrade 43` should update to v43.0.2, but instead updated only to v43.0.0

### Environment

  Expo CLI 4.12.12 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.10.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.1 - C:\p\n\yarn\bin\yarn.CMD
      npm: 7.24.0 - C:\Program Files\nodejs\npm.CMD   
    npmPackages:
      expo: ^43.0.0 => 43.0.2
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.2 => 0.64.2
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

RNweb only for now

### Error output

![image](https://user-images.githubusercontent.com/1308419/140660034-f739fb24-7533-44f5-8edf-fb1c06ad19d6.png)

If my IDE (VSCode + plugin) did not warn me that updates were possible, I might have missed important security updates.

Please update your `expo-cli` script along with releases for expo itself.

Otherwise, very hand tool; cheers! :)

### Reproducible demo or steps to reproduce from a blank project

(start with old project)
```bash
yarn global remove expo-cli
...
yarn global add expo-cli
yarn global v1.22.1
[1/4] Resolving packages...
(screen full of warnings)
success Installed "expo-cli@4.12.12" with binaries:
...
expo upgrade 43
```
then picture above

TIA! :)

**Comment by kbrandwijk** [comment]
This is a very common pattern. The `^` in the version number indicates that it will resolve to any minor and patch version, except for major version updates.

As a matter of fact, the environment info you included already indicates that it resolves nicely to the latest version:
```
expo: ^43.0.0 => 43.0.2
```

**Comment by gopidon** [comment]
First 'expo install expo@latest'
Then 'expo upgrade' to make sure nothing is broken :-)
