### ISSUE TITLE
Cannot read properties of undefined (reading 'transformFile')

### ISSUE THREAD

**Issue by nickgomez-tech** [expo/expo-cli#3988]
### Summary

Hello, my name "nickgomez-tech" and I have a problem, when I was trying to run it in my iOS phone it threw this problem:
"Cannot read properties of undefined (reading 'transformFile')"

### Environment

Expo CLI 4.12.12 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 17.0.1 - C:\Program Files\nodejs\node.EXE
      npm: 7.20.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~43.0.2 => 43.0.2
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

iPhone/not an emulator/not a simulator/iPhone 6/iOS 12.13.1

### Error output

iOS Bundling failed 21ms
Cannot read properties of undefined (reading 'transformFile')

### Reproducible demo or steps to reproduce from a blank project

here its my node_modules/metro/src/Bundle.js in line 95 column 35 where the problem (including the function):
return _asyncToGenerator(function*()){
    yield _this3._depGraphPromise;
    return _this3._transformer.transformFile(filePath, transformOptions)
})();

**Comment by jesuscovam** [comment]
hi nick, could you try running the same app on Node 16 LTS version or the 14 LTS version please?

**Comment by JKojakali** [comment]
You should change the node version in your .nvmrc file to a more stable version. Anything LTS should work just fine.

**Comment by JKojakali** [comment]
I ran into this issue when running my bitbucket pipelines and pushing the build to expo. This was happening due to the `image` value being `node:alpine` in my bitbucket.yml file.

**Comment by michaelalassaad** [comment]
> You should change the node version in your .nvmrc file to a more stable version. Anything LTS should work just fine.

how can i do that?

**Comment by jesuscovam** [comment]
> > You should change the node version in your .nvmrc file to a more stable version. Anything LTS should work just fine.
> 
> how can i do that?

https://github.com/nvm-sh/nvm

and after install:
<img width="516" alt="Screen Shot 2021-11-20 at 19 16 44" src="https://user-images.githubusercontent.com/46403187/142744592-0dc17012-4de1-4b71-8065-223b0d208be0.png">

**Comment by michaelalassaad** [comment]
> > > You should change the node version in your .nvmrc file to a more stable version. Anything LTS should work just fine.
> > 
> > 
> > how can i do that?
> 
> https://github.com/nvm-sh/nvm
> 
> and after install: <img alt="Screen Shot 2021-11-20 at 19 16 44" width="516" src="https://user-images.githubusercontent.com/46403187/142744592-0dc17012-4de1-4b71-8065-223b0d208be0.png">

This worked for me! Thank you very much

**Comment by kbrandwijk** [comment]
The Metro bundler is not compatible yet with Node 17.

While there is a workaround, which is running `webpack` with the `openssl-legacy-provider` option, this option _only_ works on Node 17, would be temporary, and would need to be deeply embedded in the CLI.
