### ISSUE TITLE
Error with @expo/metro-config@0.3.0

### ISSUE THREAD

**Issue by jesuscovam** [expo/expo-cli#3997]
### Summary

I'm using expo with amplify and to avoid an error I have to write this metro.config.js file
```
const { getDefaultConfig } = require("@expo/metro-config");
const defaultConfig = getDefaultConfig(__dirname);

// blacklist
const exclusionList = require("metro-config/src/defaults/exclusionList");
defaultConfig.resolver.blacklistRE = exclusionList([/#current-cloud-backend\/.*/]);

// transformer
defaultConfig.transformer.getTransformOptions = async () => ({
  transform: {
    experimentalImportSupport: false,
    inlineRequires: false,
  },
});

module.exports = defaultConfig;
```

I have a project with the expo SDK 43 and the @expo/metro-config@: "^0.2.7" that is working great but this new one I'm building fails.

### Environment

 Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
      Yarn: 1.22.10 - /opt/homebrew/bin/yarn
      npm: 7.22.0 - ~/.nvm/versions/node/v14.17.1/bin/npm
      Watchman: 2021.10.18.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~43.0.2 => 43.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Darwin Jesuss-MacBook-Pro.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 arm64

### Error output

Starting project at /Users/jesuscova/local/projects/slissto/apps/expo-apps/client-app
Developer tools running on http://localhost:19002
Opening developer tools in the browser...
› Unversioned @expo/metro-config@0.3.0 is being used. Bundling apps may not work as expected, and is subject to breaking changes. Install expo or set the app.json sdkVersion to use a stable version of @expo/metro-config.

Expo Metro config:
- Version: 0.3.0
- Bundler target: bare
- Legacy: false
- Extensions: ts, tsx, js, jsx, json
- React Native: /Users/jesuscova/local/projects/slissto/apps/expo-apps/client-app/node_modules/react-native
- Babel config: /Users/jesuscova/local/projects/slissto/apps/expo-apps/client-app/babel.config.js
- Resolver Fields: react-native, browser, main
- Watch Folders:
- Node Module Paths:
- Exotic: false

Cannot find module 'find-yarn-workspace-root'
Require stack:
- /Users/jesuscova/local/projects/slissto/apps/expo-apps/client-app/node_modules/@expo/metro-config/build/getModulesPaths.js
- /Users/jesuscova/local/projects/slissto/apps/expo-apps/client-app/node_modules/@expo/metro-config/build/ExpoMetroConfig.js
- /Users/jesuscova/local/projects/slissto/apps/expo-apps/client-app/metro.config.js
- /Users/jesuscova/local/projects/slissto/apps/expo-apps/client-app/node_modules/import-fresh/index.js
- /Users/jesuscova/local/projects/slissto/apps/expo-apps/client-app/node_modules/cosmiconfig/dist/loaders.js
- /Users/jesuscova/local/projects/slissto/apps/expo-apps/client-app/node_modules/cosmiconfig/dist/createExplorer.js
- /Users/jesuscova/local/projects/slissto/apps/expo-apps/client-app/node_modules/cosmiconfig/dist/index.js
- /Users/jesuscova/local/projects/slissto/apps/expo-apps/client-app/node_modules/metro-config/src/loadConfig.js
- /Users/jesuscova/local/projects/slissto/apps/expo-apps/client-app/node_modules/metro-config/src/index.js
- /Users/jesuscova/.nvm/versions/node/v14.17.1/lib/node_modules/expo-cli/node_modules/@expo/metro-config/build/importMetroFromProject.js
- /Users/jesuscova/.nvm/versions/node/v14.17.1/lib/node_modules/expo-cli/node_modules/@expo/metro-config/build/ExpoMetroConfig.js
- /Users/jesuscova/.nvm/versions/node/v14.17.1/lib/node_modules/expo-cli/build/exp.js
- /Users/jesuscova/.nvm/versions/node/v14.17.1/lib/node_modules/expo-cli/bin/expo.js
Error: Cannot find module 'find-yarn-workspace-root'
Require stack:
- /Users/jesuscova/local/projects/slissto/apps/expo-apps/client-app/node_modules/@expo/metro-config/build/getModulesPaths.js
- /Users/jesuscova/local/projects/slissto/apps/expo-apps/client-app/node_modules/@expo/metro-config/build/ExpoMetroConfig.js
- /Users/jesuscova/local/projects/slissto/apps/expo-apps/client-app/metro.config.js
- /Users/jesuscova/local/projects/slissto/apps/expo-apps/client-app/node_modules/import-fresh/index.js
- /Users/jesuscova/local/projects/slissto/apps/expo-apps/client-app/node_modules/cosmiconfig/dist/loaders.js
- /Users/jesuscova/local/projects/slissto/apps/expo-apps/client-app/node_modules/cosmiconfig/dist/createExplorer.js
- /Users/jesuscova/local/projects/slissto/apps/expo-apps/client-app/node_modules/cosmiconfig/dist/index.js
- /Users/jesuscova/local/projects/slissto/apps/expo-apps/client-app/node_modules/metro-config/src/loadConfig.js
- /Users/jesuscova/local/projects/slissto/apps/expo-apps/client-app/node_modules/metro-config/src/index.js
- /Users/jesuscova/.nvm/versions/node/v14.17.1/lib/node_modules/expo-cli/node_modules/@expo/metro-config/build/importMetroFromProject.js
- /Users/jesuscova/.nvm/versions/node/v14.17.1/lib/node_modules/expo-cli/node_modules/@expo/metro-config/build/ExpoMetroConfig.js
- /Users/jesuscova/.nvm/versions/node/v14.17.1/lib/node_modules/expo-cli/build/exp.js
- /Users/jesuscova/.nvm/versions/node/v14.17.1/lib/node_modules/expo-cli/bin/expo.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/jesuscova/local/projects/slissto/apps/expo-apps/client-app/node_modules/@expo/metro-config/src/getModulesPaths.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)

### Reproducible demo or steps to reproduce from a blank project

https://github.com/jesuscovam/expo-metro-config-error

**Comment by roshangm1** [comment]
Looks like, latest change here is using `find-yarn-workspace-root`.

https://github.com/expo/expo-cli/commit/440f8d9e628887b9c7436ee3a739da074d4aa39f#diff-b479ba82bacf16bc198ded8d3a8c0b9571e25d9a7fa5e1bb1dab46766fe8e816

However, the code related to `find-yarn-workspace-root` in package.json was reverted explicitly here and never re-added in the above commit ^^: 
https://github.com/expo/expo-cli/commit/f0ae625006ba6630f0d3163ede09d292498cda8d#diff-b479ba82bacf16bc198ded8d3a8c0b9571e25d9a7fa5e1bb1dab46766fe8e816

Maybe, forgot to add back the dependency in the package.json ?
