### ISSUE TITLE
(_xdl || _load_xdl(...)).Exp.downloadTemplateApp is not a function

### ISSUE THREAD

**Issue by ddsr17** [expo/expo-cli#402]
## Description

I tried installing expo-cli using npm install -g expo-cli, it successfully installed version 2.11.6 in my system.
But when I try to make a new project using 'expo init MyfirstApp' it fails
Error Occured: (_xdl || _load_xdl(...)).Exp.downloadTemplateApp is not a function

I read a solution somewhere to downgrade expo version, I tried downgrading my expo version to 1.1.0, but still the same error persists.
Kindly help me with the same

## Expected Behavior

What action did you perform, and what did you expect to happen?
expo init MyfirstApp - should have created a new react native base app.
## Observed Behavior
What actually happened when you performed the above actions?
Error occurred

If there's an error message, please paste the _full terminal output and error message_ in this code block:

```
(_xdl || _load_xdl(...)).Exp.downloadTemplateApp is not a function
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:
On running diagnostics:
/[19:08:01] Request failed with status code 500
[19:08:01] Error: Request failed with status code 500

Also specify:

- Phone/emulator/simulator platform, model and version:
Emulator - Google Nexus - Android 9.0 (Google Api's)
## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.
Sorry, cannot provide a working demo for this.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by Kwechetel** [comment]
I facing the same problem with that typical error
(0 , (_wordwrap || _load_wordwrap(...)).default)(...)(...).trimStart is not a function
Set EXPO_DEBUG=true in your env to view the stack trace.

**Comment by iwaffles** [comment]
Having the same issue here. I'm going to install an older version of the expo-cli. 

Until this is fixed, I suggest doing the following:

1. `npm uninstall -g expo-cli`
2. `npm install -g expo-cli@2.11.3`

This worked for me and I can now run `expo init`. Hope this helps someone!

**Comment by ddsr17** [comment]
> 2\. npm install -g expo-cli@2.11.3
Thanks @iwaffles for the workaround.
But keeping this one issue, till someone from the official team takes a look at it.

**Comment by juanorellana13** [comment]
Thank you @iwaffles. This helped very much.

**Comment by x5engine** [comment]
**Critical** bug still open and **NOT fixed** since 6 days ago....

**Comment by fson** [comment]
Hey, @ddsr17 looks like the version of Expo CLI that the error message is from might not be 2.11.6. Maybe you have two versions of Expo CLI installed (e.g. with both npm and yarn)?

Can you run these commands and copy the output here?
```
npm ls --global expo-cli xdl
```
```
yarn global list | grep expo
```

**Comment by fson** [comment]
@Kwechetel that looks like a [different issue](https://github.com/expo/expo-cli/issues/411) altogether. It's been fixed in v2.11.7.

**Comment by ddsr17** [comment]
@fson I just checked, I do not have multiple versions of Expo CLI installed.

**npm ls --global expo-cli xdl**
└─┬ expo-cli@2.11.6
  └── xdl@53.1.2

**yarn global list**
yarn global v1.13.0
✨  Done in 0.02s.

**Comment by drougojrom** [comment]
Still experience the same issue

```
? Choose a template: tabs
[10:53:02] (_xdl || _load_xdl(...)).Exp.downloadTemplateApp is not a function
[10:53:02] Set EXPO_DEBUG=true in your env to view the stack trace.
➜  dev npm ls --global expo-cli xdl  
```

**Comment by fson** [comment]
@drougojrom note that the command is `expo`, not `exp`. (`exp` was the predecessor of Expo CLI, but the command was renamed `expo` a year ago.)

If you have the same issue, please include the output `expo diagnostics` in your comments, as this makes it easier for us to help you. Thanks!

**Comment by fson** [comment]
This issue should be already fixed in the newer versions and there's no new activity in this issue, so I'm closing it. Please open a new issue if you get this error in the latest version of Expo CLI.
