### ISSUE TITLE
expo start --web fails "error:03000086:digital envelope routines::initialization error"

### ISSUE THREAD

**Issue by tomByrer** [expo/expo-cli#4037]
### Summary

expo start --web
fails "error:03000086:digital envelope routines::initialization error"

### Environment
```
Expo CLI 4.13.0 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 17.1.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.1 - C:\p\n\yarn\bin\yarn.CMD
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~43.0.3 => 43.0.3
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.66.3 => 0.66.3
      react-native-web: 0.17.5 => 0.17.5
    Expo Workflow: managed
```
### Please specify your device/emulator/simulator platform, model and version

just web

### Error output

```
Starting project at D:\doc\prog\learn\js\react\reactnative\reanimated2\animate-with-reanimated\all
Developer tools running on http://localhost:19002
Opening developer tools in the browser...
Starting Metro Bundler
Starting Webpack on port 19006 in development mode.
‼ ｢wds｣: transportMode is an experimental option, meaning its usage could potentially change without warning
Web Bundling JavaScript [=======                                                         ] 10%D:\doc\prog\learn\js\react\reactnative\reanimated2\animate-with-reanimated\all\node_modules\metro-hermes-compiler\src\emhermesc.js:77
          throw ex;
          ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (C:\Users\tomby\AppData\Local\Yarn\Data\global\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\tomby\AppData\Local\Yarn\Data\global\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\tomby\AppData\Local\Yarn\Data\global\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\tomby\AppData\Local\Yarn\Data\global\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\tomby\AppData\Local\Yarn\Data\global\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\tomby\AppData\Local\Yarn\Data\global\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\tomby\AppData\Local\Yarn\Data\global\node_modules\loader-runner\lib\LoaderRunner.js:214:10)    at Array.<anonymous> (C:\Users\tomby\AppData\Local\Yarn\Data\global\node_modules\loader-runner\lib\LoaderRunner.js:205:4)    
    at Storage.finished (C:\Users\tomby\AppData\Local\Yarn\Data\global\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\tomby\AppData\Local\Yarn\Data\global\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\Users\tomby\AppData\Local\Yarn\Data\global\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

```

### Reproducible demo or steps to reproduce from a blank project

https://github.com/enzomanuelmangano/animate-with-reanimated/tree/main/10-ripple-effect
install packages
`expo start --web` in node17.1
won't work

uninstalled node17, installed latest node16.x, seems to work fine

**Comment by EvanBacon** [comment]
Looks like this is a [new Node 17 issue](https://stackoverflow.com/a/69665354/4047926).

**Comment by tomByrer** [comment]
Good find!
Where would `export NODE_OPTIONS=--openssl-legacy-provider` go @EvanBacon ?

**Comment by robinmalik** [comment]
@tomByrer Did you ever figure this out?

**Comment by robinmalik** [comment]
Posting back incase this helps someone:

`"start": "set NODE_OPTIONS=--openssl-legacy-provider && expo start ",` in package.json worked to stop that error for me. This is on Windows 10.

**Comment by mogarick** [comment]
Complementing @robinmalik latest post, for *nix/ *nux envs the script command in `package.json` should be:

``` json
{
  "scripts": {
    "start": "export NODE_OPTIONS=--openssl-legacy-provider && expo start"
  }  
}
```

**Comment by Darkyxz** [comment]
i have the same problem, i try to fix but i can't, help please.

Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (C:\Users\Diablo_II\Desktop\web 3.0\ethereum-boilerplate\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\Diablo_II\Desktop\web 3.0\ethereum-boilerplate\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\Diablo_II\Desktop\web 3.0\ethereum-boilerplate\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\Diablo_II\Desktop\web 3.0\ethereum-boilerplate\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\Diablo_II\Desktop\web 3.0\ethereum-boilerplate\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\Diablo_II\Desktop\web 3.0\ethereum-boilerplate\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\Diablo_II\Desktop\web 3.0\ethereum-boilerplate\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\Diablo_II\Desktop\web 3.0\ethereum-boilerplate\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
C:\Users\Diablo_II\Desktop\web 3.0\ethereum-boilerplate\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (C:\Users\Diablo_II\Desktop\web 3.0\ethereum-boilerplate\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\Diablo_II\Desktop\web 3.0\ethereum-boilerplate\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\Diablo_II\Desktop\web 3.0\ethereum-boilerplate\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\Diablo_II\Desktop\web 3.0\ethereum-boilerplate\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\Diablo_II\Desktop\web 3.0\ethereum-boilerplate\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\Diablo_II\Desktop\web 3.0\ethereum-boilerplate\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\Diablo_II\Desktop\web 3.0\ethereum-boilerplate\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\Diablo_II\Desktop\web 3.0\ethereum-boilerplate\node_modules\react-scripts\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.2.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\Diablo_II\Desktop\web 3.0\ethereum-boilerplate>

**Comment by kbrandwijk** [comment]
Again, like has been said before, Node 17 is not supported currently, the CLI will warn you multiple times about that when you try to run any of the commands. The underlying issue has already been linked above. There is a workaround mentioned in that thread and above here as well, but YMMV. Your best option is to stick to a version of Node that Expo supports (12-16).

**Comment by baynex** [comment]
The above mentioned workaround doesn't seem to have any effect.

**Comment by leonzhang51** [comment]
{
  "scripts": {
    "start": "export NODE_OPTIONS=--openssl-legacy-provider && expo start"
  }  
}
perfect work on M1 Mac, when I using Node 17 and expo

**Comment by YangRongAtGit** [comment]
> The above mentioned workaround doesn't seem to have any effect.

Same here, the workaround is not working on Ubuntu 18.04.6 LTS with node version 17.9.0

**Comment by gate5th** [comment]
For any future readers "export NODE_OPTIONS=--openssl-legacy-provider && expo start" solved this for me as well. I'm on a WSL2, node 18.1.0

**Comment by rjpt1** [comment]
> { "scripts": { "start": "export NODE_OPTIONS=--openssl-legacy-provider && expo start" } } perfect work on M1 Mac, when I using Node 17 and expo

it worked for me, this is my setup

  "scripts": {
    "start": "ng serve, export NODE_OPTIONS=--openssl-legacy-provider && expo start",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },

**Comment by mraliahmadi80** [comment]
Add this to package.json

"scripts": {
    "start": "react-scripts --openssl-legacy-provider start",
    "build": "react-scripts --openssl-legacy-provider build",
 }

**Comment by colord** [comment]
WINDOWS - For anyone having issues with the package.json. You can do things manually in Powershell:

`$env:NODE_OPTIONS = '--openssl-legacy-provider'; npx expo start --web`

Or in Command Prompt:

`set NODE_OPTIONS=--openssl-legacy-provider && npx expo start --web`

**Comment by hmagnoINFNET** [comment]
A lot of awnsers for npm run start but none for npm run web.

**Comment by enghseb** [comment]
> 
And what do one do if not even that works?

**Comment by enghseb** [comment]
> WINDOWS - For anyone having issues with the package.json. You can do things manually in Powershell:
> 
> `$env:NODE_OPTIONS = '--openssl-legacy-provider'; npx expo start --web`
> 
> Or in Command Prompt:
> 
> `set NODE_OPTIONS=--openssl-legacy-provider && npx expo start --web`

Does not work for me, unfortunately. Though, no other solution posted does either.

**Comment by haneenmahd** [comment]
Note that however, This is only caused when using `expo-cli` from node-versions that doesn't support expo or hasn't been tested against it. This however causes bugs. One of the stable ways to fix this issue is to install `nvm` and use a node version that is supported by expo.

These are the versions that are supported as of `expo-cli` version `6.0.8`.

| node-version | supported |
| ------------- | ----------- |
| >= 12.13.0 | ✅   |
| < 15.0.0 | ✅ |
| >= 16.0.0 | ✅ |
| < 17.0.0 | ✅ |

**Comment by mukul98s** [comment]
> { "scripts": { "start": "export NODE_OPTIONS=--openssl-legacy-provider && expo start" } } perfect work on M1 Mac, when I using Node 17 and expo

Worked on Linux with node 16 and expo-cli v5. 

Thanks @leonzhang51!

**Comment by AbeApple** [comment]
I finally got it working with the following command:
npx cross-env NODE_OPTIONS=--openssl-legacy-provider expo export:web
