### ISSUE TITLE
--https flag doesn't seem to work

### ISSUE THREAD

**Issue by Promhize** [expo/expo-cli#4044]
### Summary

Starting the cli with --https flag doesn't seem to do anything ie `expo start` and `expo start --https` yields the same result, a http server

### Environment

Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 11.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
      Watchman: 2021.11.08.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~43.0.0 => 43.0.2 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Developing on a mac m1 air and testing on a samsung s10+

### Reproducible demo or steps to reproduce from a blank project

Just run `expo start --https`, it starts a http server

**Comment by byCedric** [comment]
Hi @Promhize! The `--https` flag is only for webpack, not Metro. If you run `expo start --https`, and press `w`, you can see webpack being started on https. (or you can run `expo start:web --https` directly).

From our `expo start --help` command:
> --https - To start webpack with https protocol

Hope this helps!

**Comment by holmesjr** [comment]
This problem still exists in SDK 48 and now the solution mentioned is outdated:

https://docs.expo.dev/workflow/expo-cli/#server-url

```
--https: Start the dev server using a secure origin. This is currently only supported on web.
```

Running `npx expo start --web --https` does not work; it results in:

``` 
Web is waiting on http://localhost:19000
```
