### ISSUE TITLE
(0 , _devServer(...).prependMiddleware) is not a function

### ISSUE THREAD

**Issue by raajnadar** [expo/expo-cli#4046]
### Summary

`Note - moving back to 4.11.0 solves the issue`

Maybe this PR is causing this error? not sure https://github.com/expo/expo-cli/pull/3889

Getting error after running `expo start`

`(0 , _devServer(...).prependMiddleware) is not a function`

Full error on terminal

```
> expo start
Starting project at <project-path>
Developer tools running on http://localhost:19002
Opening developer tools in the browser...
Starting Metro Bundler
(0 , _devServer(...).prependMiddleware) is not a function
TypeError: (0 , _devServer(...).prependMiddleware) is not a function
    at startDevServerAsync (/Users/raajnadar/.config/yarn/global/node_modules/expo-cli/node_modules/xdl/src/start/startDevServerAsync.ts:89:3)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at startAsync (/Users/raajnadar/.config/yarn/global/node_modules/expo-cli/node_modules/xdl/src/start/startAsync.ts:74:41)
```

### Environment

> expo diagnostics

  Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/Cellar/node@16/16.13.0/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.0 - /usr/local/Cellar/node@16/16.13.0/bin/npm
      Watchman: 2021.10.18.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 23, 25, 26, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 31.0.0
        System Images: android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.1 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

MacBook Pro 2019

### Error output

> EXPO_DEBUG=true expo start
Starting project at /Users/raajnadar/projects/electro
Developer tools running on http://localhost:19002
Opening developer tools in the browser...

Expo Metro config:
- Bundler target: bare
- Legacy: false
- Extensions: ts, tsx, js, jsx, json
- React Native: /Users/raajnadar/projects/electro/node_modules/react-native
- Babel config: /Users/raajnadar/projects/electro/babel.config.js

Starting Metro Bundler
(0 , _devServer(...).prependMiddleware) is not a function
TypeError: (0 , _devServer(...).prependMiddleware) is not a function
    at startDevServerAsync (/Users/raajnadar/.config/yarn/global/node_modules/expo-cli/node_modules/xdl/src/start/startDevServerAsync.ts:89:3)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at startAsync (/Users/raajnadar/.config/yarn/global/node_modules/expo-cli/node_modules/xdl/src/start/startAsync.ts:74:41)

### Reproducible demo or steps to reproduce from a blank project

Sorry repro N/A

**Comment by raajnadar** [comment]
I have a expo managed project IDK why the debug logged as `Bundler target: bare`

**Comment by brentvatne** [comment]
hi there! we need a reproducible example. follow this guide to make one: https://expo.fyi/manual-debugging

**Comment by raajnadar** [comment]
If you look carefully I added it works fine after downgrading to 4.11.0 also pinned the commit that might cause the issue.

**Comment by brentvatne** [comment]
@raajnadar - we don't read issues without MCVE. please share a project that you have verified this issue is present on

**Comment by raajnadar** [comment]
This issue does seems like a expo project issue, On top of that it is a fresh expo project.

All version are present in the `Environment` section of the issue

**Comment by brentvatne** [comment]
if this was indeed an issue in a fresh expo project then `expo start` would not work for anybody. please share a MCVE if you would like some support :)

**Comment by raajnadar** [comment]
It seems the issue is throw when expo cli is installed globally, when I install local to a project it compiles.

**Comment by brentvatne** [comment]
are you using yarn to install globally? i've seen issues where yarn does not correctly install dependencies in global packages. you could try removing it and installing it globally with npm instead.

**Comment by raajnadar** [comment]
Yes yarn v1, ok will try with npm and confirm
