### ISSUE TITLE
OCR and camera issue

### ISSUE THREAD

**Issue by omair2010** [expo/expo-cli#405]
im asking if i can use ocr in expo react native projet

![image](https://user-images.githubusercontent.com/32815467/53815455-fcf80100-3f61-11e9-8a72-9cb18d64abd0.png)
because i cant add this setting in expo

**Comment by AdamJNavarro** [comment]
Hey @omair2010,

You can not use OCR in a managed Expo project. You would have to use the [Bare workflow](https://docs.expo.io/versions/v32.0.0/introduction/managed-vs-bare/) which allows to modify native code and run commands like `react-native link`. Additionally, please take these types of questions to our [forums](https://forums.expo.io/) as we prefer to keep Github reserved for bugs!

Cheers,
Adam
