### ISSUE TITLE
`expo login` command warns about needing to be logged in when session is expired

### ISSUE THREAD

**Issue by kbrandwijk** [expo/expo-cli#4050]
### Summary

When you use 'logout of all sessions' in the web UI, the next time you try to login, you get a warning message that you need to be logged in.

![image](https://user-images.githubusercontent.com/852069/144736105-b641f2ab-44a9-4b76-a08f-d9ee2bd62ef5.png)

If you normally logout locally (or aren't logged in at all), you don't get the prompt

![image](https://user-images.githubusercontent.com/852069/144736118-3b9bf429-e534-4994-9afe-0e8d0321ea69.png)

### Environment

```
  Expo CLI 4.13.0 environment info:
    System:
      OS: Linux 5.10 Debian GNU/Linux 9 (stretch) 9 (stretch)
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 14.18.2 - /usr/local/bin/node
      Yarn: 3.1.0 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
    npmPackages:
      expo: ^43.0.0 => 43.0.0 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.5 => 0.17.5 
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

n/a

### Reproducible demo or steps to reproduce from a blank project

- log in with `expo login`
- go to the website and press 'Log Out of Other Sessions'
- run `expo login`

**Comment by vallesluiggi** [comment]
try 
`npx expo login`
