### ISSUE TITLE
expo start --android throwing Couldn't start project on Android: Error running adb: unable to get local issuer certificate

### ISSUE THREAD

**Issue by Deepangose** [expo/expo-cli#4052]
### Summary

I have installed expo-cli and created a new react native project using it.
Also I've installed android studio in my local and my virtual device is ready and ran it.

When i was run project using command: expo start --android its throwing below error:
**Couldn't start project on Android: Error running adb: unable to get local issuer certificate**

Could you please me on this to find a fix

![Uploading image.png…]()

### Environment

Node: 14.x.x
Python: 2.7.15
Java details:
java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

expo: ~43.0.2
react-native: 0.64.3

### Please specify your device/emulator/simulator platform, model and version

Andriod studio: 3.1.25

### Reproducible demo or steps to reproduce from a blank project

1. Create a react native project using expo-init cmd.
2. Install a andriod studio version 3.1.25
3. Create a virtual device & run it
4. Start the app using expo start --andriod. it will throw " unable to get local issuer certificate" error

**Comment by whittenjaw85** [comment]
I have a similar issue.

NPM: 8.1.4
ADB: 31.0.3-7562133
Python: 3.10.0
Expo: 4.13.0
React-Native: 2.0.1

from a terminal:
npm start
`a` #to start android
then

Logs for your project will appear below. Press Ctrl+C to exit.
› Opening on Android...
› Opening exp://x.x.x.x:NnNn on Pixel_2_API_30
Couldn't start project on Android: Error running adb: unable to get local issuer certificate
› Press ? │ show all commands

**Comment by Deepangose** [comment]
Have you find any solution to fix it?

**Comment by Deepangose** [comment]
I tried alot but nothing helped me

**Comment by whittenjaw85** [comment]
I am working behind a corporate proxy. Are you doing the same?

I have tried pointing my npm config set cafile to the pem chain in npnjs.com, but nothing came of it.

**Comment by Deepangose** [comment]
Yeah I'm working behind corporate proxy.

**Comment by Deepangose** [comment]
Solution: Install expo go apk manually in emulator.

Install it from playstore and get the backup of .apk file. Then follow below steps
https://stackoverflow.com/questions/17167636/how-to-install-an-apk-on-the-emulator-in-android-studio

**Comment by JulianOrozcoC** [comment]
Having the same issue, any solution?

**Comment by priyank-R** [comment]
I'm facing this issue. Kindly help.
