### ISSUE TITLE
[SDKv44] reactDelegate break MATCH_INIT

### ISSUE THREAD

**Issue by giautm** [expo/expo-cli#4060]
### Summary

When trying `EXPO_BETA=1 expo prebuild`, I found some plugins break by the new initiative.

```objc
@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
#if defined(FB_SONARKIT_ENABLED) && __has_include(<FlipperKit/FlipperClient.h>)
  InitializeFlipper(application);
#endif
  
  RCTBridge *bridge = [self.reactDelegate createBridgeWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [self.reactDelegate createRootViewWithBridge:bridge moduleName:@"main" initialProperties:nil];
  rootView.backgroundColor = [UIColor whiteColor];
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [self.reactDelegate createRootViewController];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
```

### Environment

non-related

### Please specify your device/emulator/simulator platform, model and version

SDKv44

### Error output

```
[ios.appDelegate]: withIosAppDelegateBaseMod: Cannot add Google Maps to the project's AppDelegate because it's malformed. Please report this with a copy of your project AppDelegate.
```

`react-native-google-cast`
https://github.com/expo/config-plugins/blob/027a1fdb1e82cd54331acbaa8d25ff56a7fdd80e/packages/react-native-google-cast/src/withIosGoogleCast.ts#L121-L124

`react-native-maps`
https://github.com/expo/expo-cli/blob/5039ec303ab8c3487a505be701e30eb8c9cb1ef6/packages/config-plugins/src/ios/Maps.ts#L13-L15

### Reproducible demo or steps to reproduce from a blank project

none

**Comment by giautm** [comment]
This issue break EAS Build too,

<img width="1098" alt="Screen Shot 2021-12-13 at 04 45 59" src="https://user-images.githubusercontent.com/12751435/145730823-e5176d0c-7099-4d73-b3ee-6ef8d7b1d191.png">

**Comment by EvanBacon** [comment]
Partially fixed in `@config-plugins/react-native-google-cast@0.1.0`. CLI will be fixed in the next release.
