### ISSUE TITLE
node.js 17.2.0

### ISSUE THREAD

**Issue by OrJDev** [expo/expo-cli#4076]
### Summary

Expo cli doesn't work using Node.js v17.2.0.
I've seen you put warning it wasn't tested so,
 you should test it.

### Environment

 Expo CLI 5.0.1 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 17.2.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.1.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~43.0.2 => 43.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Windows 10

### Error output

Logs for your project will appear below. Press Ctrl+C to exit.

### Reproducible demo or steps to reproduce from a blank project

null

**Comment by Sourov-Paul** [comment]
E:\React Navive\ReactNativeFirseApp>expo start
WARNING: expo-cli has not yet been tested against Node.js v17.3.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <13.0.0 (Maintenance LTS)
* >=14.0.0 <15.0.0 (Active LTS)
* >=15.0.0 <17.0.0 (Current Release)

**Comment by Sourov-Paul** [comment]
E:\React Navive\ReactNativeFirseApp>expo start
**WARNING: expo-cli has not yet been tested against Node.js v17.3.0.**
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <13.0.0 (Maintenance LTS)
* >=14.0.0 <15.0.0 (Active LTS)
* >=15.0.0 <17.0.0 (Current Release)
