### ISSUE TITLE
uri-schema can't open url with query string

### ISSUE THREAD

**Issue by watanabeyu** [expo/expo-cli#4079]
### Summary

I want to open url like the below.
`npx uri-schema open schema://foo/bar?id=xxxx`

but result is `no matches found: schema://foo/bar?id=xxxx`
`npx uri-schema open schema://foo/bar/id/xxx` is ok.

### Environment

Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nodebrew/current/bin/node
      npm: 8.1.0 - ~/.nodebrew/current/bin/npm
      Watchman: 2021.11.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 26, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~42.0.4 => 42.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

simulator

### Error output

no matches found: schema://foo/bar?id=xxxx

### Reproducible demo or steps to reproduce from a blank project

```bash
$ npx uri-schema open schema://foo/bar/id/xxx
$ npx uri-schema open schema://foo/bar?id=xxxx
```

**Comment by kbrandwijk** [comment]
This is not an issue with `uri-scheme`, this is an issue with the shell. The `?` in the parameter is parsed as a wildcard by the shell. You can quote the URL, or escape the `?`, or use `noglob` or a similar setting in your shell, these all work:

```bash
> noglob npx uri-schema open schema://foo/bar?id=xxxx
> npx uri-schema open schema://foo/bar\?id=xxxx
> npx uri-schema open "schema://foo/bar?id=xxxx"
```
