### ISSUE TITLE
expo.host doesn't escape runtimeVersion parameter in manifest url

### ISSUE THREAD

**Issue by colinux** [expo/expo-cli#4080]
### Summary

After `expo:publish` there is a link shown in console on the form 
`Manifest: https://exp.host/@team/xxx?release-channel=production`
but the link behind is `https://exp.host/@team/xxx/index.exp?release-channel=production&runtimeVersion=zzzz`  (btw this is trapping to link to another url)

This manifest url contains  `runtimeVersion` as query parameter, which does not escape the value (or at least the `+` sign) 

### Environment

```
$ expo diagnostics

  Expo CLI 5.0.1 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /opt/homebrew/Cellar/node@16/16.13.1/bin/node
      Yarn: 3.0.2 - bin/yarn
      npm: 8.1.2 - /opt/homebrew/Cellar/node@16/16.13.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.2/13C90 - /usr/bin/xcodebuild
    npmPackages:
      react: ^17.0.2 => 17.0.2
      react-dom: ^17.0.2 => 17.0.2
    npmGlobalPackages:
      eas-cli: 0.41.1
      expo-cli: 5.0.1
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

macos / iterm2 safari+firefox & ios devices

### Reproducible demo or steps to reproduce from a blank project

Publish a version with `runtimeVersion` containing a `+`, for instance `44+2` (assumes there was a build with the same `runtimeVersion`)

The manifest url is 
`https://exp.host/@team/xxx/index.exp?release-channel=production&runtimeVersion=44+2`

This returns a 404 error because `+` was not escaped :
_Experience "@team/xxxx" for platform "ios" and release channel "production" does not exist or is not published._

It's ok when manually fixing the url : 
`https://exp.host/@team/xxx/index.exp?release-channel=production&runtimeVersion=44%2B2`

Also,it may be related but it seems iOS devices can't download this published version through `expo-updates` (it's OK on Android with the same `runtimeVersion` value).

**Comment by kbrandwijk** [comment]
Possibly related: https://github.com/expo/expo/issues/15647
