### ISSUE TITLE
Expo shuts down straight away after openning

### ISSUE THREAD

**Issue by TuranPehlivan** [expo/expo-cli#4095]
### Summary

I am new to Expo, when I search for it and open it on my Windows 11 pro, it open for 1 second then shuts down immediately.  

### Environment

I am new to Expo, when I search for it and open it on my Windows 11 pro, it open for 1 second then shuts down immediately.  However, I am able keep it on the screen if I click on it before it shuts down.  It then shuts down if I do anything else with it.  this a normal behaviour or have I completely misunderstood it, should not try to open it?  It looks like it does not like the version of Node.js I have installed.  I managed to copy the following:

WARNING: expo-cli has not yet been tested against Node.js v17.2.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <13.0.0 (Maintenance LTS)
* >=14.0.0 <15.0.0 (Active LTS)
* >=15.0.0 <17.0.0 (Current Release)

### Please specify your device/emulator/simulator platform, model and version

Windows 11

### Error output

WARNING: expo-cli has not yet been tested against Node.js v17.2.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <13.0.0 (Maintenance LTS)
* >=14.0.0 <15.0.0 (Active LTS)
* >=15.0.0 <17.0.0 (Current Release)

### Reproducible demo or steps to reproduce from a blank project

Install Node.js v17.2.0. and open Expo.

**Comment by EvanBacon** [comment]
What does "open Expo" mean? Are you opening the Expo Go app on a device, simulator, or emulator? The dev server in a terminal?

**Comment by TuranPehlivan** [comment]
Hi Evan, as I said I dont really know what I am doing or how to use it yet. It looks like a command prompt, tried to open it an my desk top to have look, but it shuts down as soon as it opens.  I am guessing I wasn't  suppose to open it like that.  Does it work on the background etc.?Get Outlook for AndroidFrom: Evan Bacon ***@***.***>Sent: Friday, 7 January 2022, 21:27To: expo/expo-cliCc: TuranPehlivan; AuthorSubject: Re: [expo/expo-cli] Expo shuts down straight away after openning(Issue #4095)
What does "open Expo" mean? Are you opening the Expo Go app on a device, simulator, or emulator? The dev server in a terminal?

**Comment by kbrandwijk** [comment]
Expo CLI commands are run from the command prompt, which means you open a command prompt first, and then run the relevant `expo ...` command: https://docs.expo.dev/workflow/expo-cli/

Beware though, that as the warning suggests, node 17 is not supported, I would recommend switching to node 16.

**Comment by TuranPehlivan** [comment]
Thank you!Get Outlook for AndroidFrom: Kim Brandwijk ***@***.***>Sent: Saturday, 8 January 2022, 21:49To: expo/expo-cliCc: TuranPehlivan; AuthorSubject: Re: [expo/expo-cli] Expo shuts down straight away after openning(Issue #4095)
Expo CLI commands are run from the command prompt, which means you open a command prompt first, and then run the relevant expo .. command: https://docs.expo.dev/workflow/expo-cli/
Beware though, that as the warning suggests, node 17 is not supported, I would recommend switching to node 16.
