### ISSUE TITLE
Can't add expo modules to existing RN project, pod install fails with "Unable to find a specification for `UMFontInterface` depended upon by `UMReactNativeAdapter`"

### ISSUE THREAD

**Issue by lfrkovic-spaceiq** [expo/expo-cli#4097]
### Summary

I'm trying to add expo modules to an existing RN app. Following the official docs (https://docs.expo.dev/bare/installing-expo-modules/), after I run 
`npx install-expo-modules`

once pod install starts, I get an error

```
Project has been deintegrated. No traces of CocoaPods left in project.
Note: The workspace referencing the Pods project still remains.
Using Expo modules
Auto-linking React Native modules for target `OnSite`: BVLinearGradient, OktaSdkBridgeReactNative, RNCMaskedView, RNDeviceInfo, RNFS, RNFileViewer, RNGestureHandler, RNKeychain, RNPermissions, RNReanimated, RNSVG, RNScreens, RNSentry, RNVectorIcons, react-native-blur, react-native-camera, react-native-config, react-native-flipper, react-native-get-random-values, react-native-image-picker, react-native-mmkv-storage, react-native-netinfo, react-native-safe-area-context, and react-native-webview
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
[!] Unable to find a specification for `UMFontInterface` depended upon by `UMReactNativeAdapter`
```

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.3.0 - ~/.asdf/installs/nodejs/16.3.0/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 7.15.1 - ~/.asdf/installs/nodejs/16.3.0/bin/npm
      Watchman: 2021.10.18.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 29.0.2, 30.0.2, 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.2/13C90 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.1 => 44.0.1 
      react: 17.0.2 => 17.0.2 
      react-native: ^0.66.1 => 0.66.1 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

iOS 15.2 iPhone 13

### Reproducible demo or steps to reproduce from a blank project

- have an existing RN 0.66.1 project

Podfile:
```
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'OnSite' do
  use_expo_modules!
  post_integrate do |installer|
    expo_patch_react_imports!(installer)
  end
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"], :hermes_enabled => true)

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!()

  # react-native-permissions, list all necessary permission pods
  permissions_path = '../node_modules/react-native-permissions/ios'

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

**Comment by Kudo** [comment]
hi there! that's interesting! the `UMReactNativeAdapter ` should not be there. could you share your Podfile.lock?

**Comment by Kudo** [comment]
hi there! since we doesn't get response yet, i'm going to close this issue. we are happy to investigate the issue and reopen it once we get enough information.

**Comment by aedocoding** [comment]
@Kudo I am running into the same issue as the original author so I would request the issue be reopened if possible.

Here is my Podfile.lock

PODS:
  - AppsFlyerFramework (6.4.0):
    - AppsFlyerFramework/Main (= 6.4.0)
  - AppsFlyerFramework/Main (6.4.0)
  - boost-for-react-native (1.63.0)
  - DoubleConversion (1.1.6)
  - EXCamera (12.1.0):
    - ExpoModulesCore
  - EXDevice (4.1.0):
    - ExpoModulesCore
  - EXDocumentPicker (10.1.0):
    - ExpoModulesCore
  - EXErrorRecovery (3.0.4):
    - ExpoModulesCore
  - EXFileSystem (13.1.1):
    - ExpoModulesCore
  - EXFont (10.0.4):
    - ExpoModulesCore
  - EXImagePicker (12.0.1):
    - ExpoModulesCore
  - EXJSONUtils (0.2.0)
  - EXKeepAwake (10.0.1):
    - ExpoModulesCore
  - EXManifests (0.2.2):
    - EXJSONUtils
  - EXPermissions (13.1.0):
    - ExpoModulesCore
  - Expo (44.0.5):
    - ExpoModulesCore
  - ExpoModulesCore (0.6.4):
    - React-Core
    - ReactCommon/turbomodule/core
  - EXScreenOrientation (4.1.1):
    - ExpoModulesCore
    - React-Core
  - EXStructuredHeaders (2.1.0)
  - EXUpdates (0.11.5):
    - EXManifests
    - ExpoModulesCore
    - EXStructuredHeaders
    - EXUpdatesInterface
    - React-Core
  - EXUpdatesInterface (0.5.0)
  - FBLazyVector (0.64.3)
  - FBReactNativeSpec (0.64.3):
    - RCT-Folly (= 2020.01.13.00)
    - RCTRequired (= 0.64.3)
    - RCTTypeSafety (= 0.64.3)
    - React-Core (= 0.64.3)
    - React-jsi (= 0.64.3)
    - ReactCommon/turbomodule/core (= 0.64.3)
  - glog (0.3.5)
  - libwebp (1.2.0):
    - libwebp/demux (= 1.2.0)
    - libwebp/mux (= 1.2.0)
    - libwebp/webp (= 1.2.0)
  - libwebp/demux (1.2.0):
    - libwebp/webp
  - libwebp/mux (1.2.0):
    - libwebp/demux
  - libwebp/webp (1.2.0)
  - RCT-Folly (2020.01.13.00):
    - boost-for-react-native
    - DoubleConversion
    - glog
    - RCT-Folly/Default (= 2020.01.13.00)
  - RCT-Folly/Default (2020.01.13.00):
    - boost-for-react-native
    - DoubleConversion
    - glog
  - RCTRequired (0.64.3)
  - RCTTypeSafety (0.64.3):
    - FBLazyVector (= 0.64.3)
    - RCT-Folly (= 2020.01.13.00)
    - RCTRequired (= 0.64.3)
    - React-Core (= 0.64.3)
  - React (0.64.3):
    - React-Core (= 0.64.3)
    - React-Core/DevSupport (= 0.64.3)
    - React-Core/RCTWebSocket (= 0.64.3)
    - React-RCTActionSheet (= 0.64.3)
    - React-RCTAnimation (= 0.64.3)
    - React-RCTBlob (= 0.64.3)
    - React-RCTImage (= 0.64.3)
    - React-RCTLinking (= 0.64.3)
    - React-RCTNetwork (= 0.64.3)
    - React-RCTSettings (= 0.64.3)
    - React-RCTText (= 0.64.3)
    - React-RCTVibration (= 0.64.3)
  - React-callinvoker (0.64.3)
  - React-Core (0.64.3):
    - glog
    - RCT-Folly (= 2020.01.13.00)
    - React-Core/Default (= 0.64.3)
    - React-cxxreact (= 0.64.3)
    - React-jsi (= 0.64.3)
    - React-jsiexecutor (= 0.64.3)
    - React-perflogger (= 0.64.3)
    - Yoga
  - React-Core/CoreModulesHeaders (0.64.3):
    - glog
    - RCT-Folly (= 2020.01.13.00)
    - React-Core/Default
    - React-cxxreact (= 0.64.3)
    - React-jsi (= 0.64.3)
    - React-jsiexecutor (= 0.64.3)
    - React-perflogger (= 0.64.3)
    - Yoga
  - React-Core/Default (0.64.3):
    - glog
    - RCT-Folly (= 2020.01.13.00)
    - React-cxxreact (= 0.64.3)
    - React-jsi (= 0.64.3)
    - React-jsiexecutor (= 0.64.3)
    - React-perflogger (= 0.64.3)
    - Yoga
  - React-Core/DevSupport (0.64.3):
    - glog
    - RCT-Folly (= 2020.01.13.00)
    - React-Core/Default (= 0.64.3)
    - React-Core/RCTWebSocket (= 0.64.3)
    - React-cxxreact (= 0.64.3)
    - React-jsi (= 0.64.3)
    - React-jsiexecutor (= 0.64.3)
    - React-jsinspector (= 0.64.3)
    - React-perflogger (= 0.64.3)
    - Yoga
  - React-Core/RCTActionSheetHeaders (0.64.3):
    - glog
    - RCT-Folly (= 2020.01.13.00)
    - React-Core/Default
    - React-cxxreact (= 0.64.3)
    - React-jsi (= 0.64.3)
    - React-jsiexecutor (= 0.64.3)
    - React-perflogger (= 0.64.3)
    - Yoga
  - React-Core/RCTAnimationHeaders (0.64.3):
    - glog
    - RCT-Folly (= 2020.01.13.00)
    - React-Core/Default
    - React-cxxreact (= 0.64.3)
    - React-jsi (= 0.64.3)
    - React-jsiexecutor (= 0.64.3)
    - React-perflogger (= 0.64.3)
    - Yoga
  - React-Core/RCTBlobHeaders (0.64.3):
    - glog
    - RCT-Folly (= 2020.01.13.00)
    - React-Core/Default
    - React-cxxreact (= 0.64.3)
    - React-jsi (= 0.64.3)
    - React-jsiexecutor (= 0.64.3)
    - React-perflogger (= 0.64.3)
    - Yoga
  - React-Core/RCTImageHeaders (0.64.3):
    - glog
    - RCT-Folly (= 2020.01.13.00)
    - React-Core/Default
    - React-cxxreact (= 0.64.3)
    - React-jsi (= 0.64.3)
    - React-jsiexecutor (= 0.64.3)
    - React-perflogger (= 0.64.3)
    - Yoga
  - React-Core/RCTLinkingHeaders (0.64.3):
    - glog
    - RCT-Folly (= 2020.01.13.00)
    - React-Core/Default
    - React-cxxreact (= 0.64.3)
    - React-jsi (= 0.64.3)
    - React-jsiexecutor (= 0.64.3)
    - React-perflogger (= 0.64.3)
    - Yoga
  - React-Core/RCTNetworkHeaders (0.64.3):
    - glog
    - RCT-Folly (= 2020.01.13.00)
    - React-Core/Default
    - React-cxxreact (= 0.64.3)
    - React-jsi (= 0.64.3)
    - React-jsiexecutor (= 0.64.3)
    - React-perflogger (= 0.64.3)
    - Yoga
  - React-Core/RCTSettingsHeaders (0.64.3):
    - glog
    - RCT-Folly (= 2020.01.13.00)
    - React-Core/Default
    - React-cxxreact (= 0.64.3)
    - React-jsi (= 0.64.3)
    - React-jsiexecutor (= 0.64.3)
    - React-perflogger (= 0.64.3)
    - Yoga
  - React-Core/RCTTextHeaders (0.64.3):
    - glog
    - RCT-Folly (= 2020.01.13.00)
    - React-Core/Default
    - React-cxxreact (= 0.64.3)
    - React-jsi (= 0.64.3)
    - React-jsiexecutor (= 0.64.3)
    - React-perflogger (= 0.64.3)
    - Yoga
  - React-Core/RCTVibrationHeaders (0.64.3):
    - glog
    - RCT-Folly (= 2020.01.13.00)
    - React-Core/Default
    - React-cxxreact (= 0.64.3)
    - React-jsi (= 0.64.3)
    - React-jsiexecutor (= 0.64.3)
    - React-perflogger (= 0.64.3)
    - Yoga
  - React-Core/RCTWebSocket (0.64.3):
    - glog
    - RCT-Folly (= 2020.01.13.00)
    - React-Core/Default (= 0.64.3)
    - React-cxxreact (= 0.64.3)
    - React-jsi (= 0.64.3)
    - React-jsiexecutor (= 0.64.3)
    - React-perflogger (= 0.64.3)
    - Yoga
  - React-CoreModules (0.64.3):
    - FBReactNativeSpec (= 0.64.3)
    - RCT-Folly (= 2020.01.13.00)
    - RCTTypeSafety (= 0.64.3)
    - React-Core/CoreModulesHeaders (= 0.64.3)
    - React-jsi (= 0.64.3)
    - React-RCTImage (= 0.64.3)
    - ReactCommon/turbomodule/core (= 0.64.3)
  - React-cxxreact (0.64.3):
    - boost-for-react-native (= 1.63.0)
    - DoubleConversion
    - glog
    - RCT-Folly (= 2020.01.13.00)
    - React-callinvoker (= 0.64.3)
    - React-jsi (= 0.64.3)
    - React-jsinspector (= 0.64.3)
    - React-perflogger (= 0.64.3)
    - React-runtimeexecutor (= 0.64.3)
  - React-jsi (0.64.3):
    - boost-for-react-native (= 1.63.0)
    - DoubleConversion
    - glog
    - RCT-Folly (= 2020.01.13.00)
    - React-jsi/Default (= 0.64.3)
  - React-jsi/Default (0.64.3):
    - boost-for-react-native (= 1.63.0)
    - DoubleConversion
    - glog
    - RCT-Folly (= 2020.01.13.00)
  - React-jsiexecutor (0.64.3):
    - DoubleConversion
    - glog
    - RCT-Folly (= 2020.01.13.00)
    - React-cxxreact (= 0.64.3)
    - React-jsi (= 0.64.3)
    - React-perflogger (= 0.64.3)
  - React-jsinspector (0.64.3)
  - react-native-appsflyer (6.4.0):
    - AppsFlyerFramework (= 6.4.0)
    - React
  - react-native-safe-area-context (3.3.2):
    - React-Core
  - react-native-version-check (3.4.2):
    - React
  - react-native-webview (11.15.0):
    - React-Core
  - React-perflogger (0.64.3)
  - React-RCTActionSheet (0.64.3):
    - React-Core/RCTActionSheetHeaders (= 0.64.3)
  - React-RCTAnimation (0.64.3):
    - FBReactNativeSpec (= 0.64.3)
    - RCT-Folly (= 2020.01.13.00)
    - RCTTypeSafety (= 0.64.3)
    - React-Core/RCTAnimationHeaders (= 0.64.3)
    - React-jsi (= 0.64.3)
    - ReactCommon/turbomodule/core (= 0.64.3)
  - React-RCTBlob (0.64.3):
    - FBReactNativeSpec (= 0.64.3)
    - RCT-Folly (= 2020.01.13.00)
    - React-Core/RCTBlobHeaders (= 0.64.3)
    - React-Core/RCTWebSocket (= 0.64.3)
    - React-jsi (= 0.64.3)
    - React-RCTNetwork (= 0.64.3)
    - ReactCommon/turbomodule/core (= 0.64.3)
  - React-RCTImage (0.64.3):
    - FBReactNativeSpec (= 0.64.3)
    - RCT-Folly (= 2020.01.13.00)
    - RCTTypeSafety (= 0.64.3)
    - React-Core/RCTImageHeaders (= 0.64.3)
    - React-jsi (= 0.64.3)
    - React-RCTNetwork (= 0.64.3)
    - ReactCommon/turbomodule/core (= 0.64.3)
  - React-RCTLinking (0.64.3):
    - FBReactNativeSpec (= 0.64.3)
    - React-Core/RCTLinkingHeaders (= 0.64.3)
    - React-jsi (= 0.64.3)
    - ReactCommon/turbomodule/core (= 0.64.3)
  - React-RCTNetwork (0.64.3):
    - FBReactNativeSpec (= 0.64.3)
    - RCT-Folly (= 2020.01.13.00)
    - RCTTypeSafety (= 0.64.3)
    - React-Core/RCTNetworkHeaders (= 0.64.3)
    - React-jsi (= 0.64.3)
    - ReactCommon/turbomodule/core (= 0.64.3)
  - React-RCTSettings (0.64.3):
    - FBReactNativeSpec (= 0.64.3)
    - RCT-Folly (= 2020.01.13.00)
    - RCTTypeSafety (= 0.64.3)
    - React-Core/RCTSettingsHeaders (= 0.64.3)
    - React-jsi (= 0.64.3)
    - ReactCommon/turbomodule/core (= 0.64.3)
  - React-RCTText (0.64.3):
    - React-Core/RCTTextHeaders (= 0.64.3)
  - React-RCTVibration (0.64.3):
    - FBReactNativeSpec (= 0.64.3)
    - RCT-Folly (= 2020.01.13.00)
    - React-Core/RCTVibrationHeaders (= 0.64.3)
    - React-jsi (= 0.64.3)
    - ReactCommon/turbomodule/core (= 0.64.3)
  - React-runtimeexecutor (0.64.3):
    - React-jsi (= 0.64.3)
  - ReactCommon/turbomodule/core (0.64.3):
    - DoubleConversion
    - glog
    - RCT-Folly (= 2020.01.13.00)
    - React-callinvoker (= 0.64.3)
    - React-Core (= 0.64.3)
    - React-cxxreact (= 0.64.3)
    - React-jsi (= 0.64.3)
    - React-perflogger (= 0.64.3)
  - RecurlySDK (1.0.0)
  - RNCAsyncStorage (1.15.6):
    - React-Core
  - RNCPicker (2.2.1):
    - React-Core
  - RNFastImage (8.5.8):
    - React-Core
    - SDWebImage (~> 5.11.1)
    - SDWebImageWebPCoder (~> 0.8.4)
  - RNGestureHandler (2.1.1):
    - React-Core
  - RNReanimated (2.3.1):
    - DoubleConversion
    - FBLazyVector
    - FBReactNativeSpec
    - glog
    - RCT-Folly
    - RCTRequired
    - RCTTypeSafety
    - React
    - React-callinvoker
    - React-Core
    - React-Core/DevSupport
    - React-Core/RCTWebSocket
    - React-CoreModules
    - React-cxxreact
    - React-jsi
    - React-jsiexecutor
    - React-jsinspector
    - React-RCTActionSheet
    - React-RCTAnimation
    - React-RCTBlob
    - React-RCTImage
    - React-RCTLinking
    - React-RCTNetwork
    - React-RCTSettings
    - React-RCTText
    - ReactCommon/turbomodule/core
    - Yoga
  - RNSVG (12.1.1):
    - React
  - SDWebImage (5.11.1):
    - SDWebImage/Core (= 5.11.1)
  - SDWebImage/Core (5.11.1)
  - SDWebImageWebPCoder (0.8.4):
    - libwebp (~> 1.0)
    - SDWebImage/Core (~> 5.10)
  - UMCore (7.1.2)
  - UMReactNativeAdapter (6.3.9):
    - ExpoModulesCore
    - React-Core
    - UMCore
  - Yoga (1.14.0)

DEPENDENCIES:
  - AppsFlyerFramework
  - DoubleConversion (from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`)
  - EXCamera (from `../node_modules/expo-camera/ios`)
  - EXDevice (from `../node_modules/expo-device/ios`)
  - EXDocumentPicker (from `../node_modules/expo-document-picker/ios`)
  - EXErrorRecovery (from `../node_modules/expo-error-recovery/ios`)
  - EXFileSystem (from `../node_modules/expo-file-system/ios`)
  - EXFont (from `../node_modules/expo-font/ios`)
  - EXImagePicker (from `../node_modules/expo-image-picker/ios`)
  - EXJSONUtils (from `../node_modules/expo-json-utils/ios`)
  - EXKeepAwake (from `../node_modules/expo-keep-awake/ios`)
  - EXManifests (from `../node_modules/expo-manifests/ios`)
  - EXPermissions (from `../node_modules/expo-permissions/ios`)
  - Expo (from `../node_modules/expo/ios`)
  - ExpoModulesCore (from `../node_modules/expo-modules-core/ios`)
  - EXScreenOrientation (from `../node_modules/expo-screen-orientation/ios`)
  - EXStructuredHeaders (from `../node_modules/expo-structured-headers/ios`)
  - EXUpdates (from `../node_modules/expo-updates/ios`)
  - EXUpdatesInterface (from `../node_modules/expo-updates-interface/ios`)
  - FBLazyVector (from `../node_modules/react-native/Libraries/FBLazyVector`)
  - FBReactNativeSpec (from `../node_modules/react-native/React/FBReactNativeSpec`)
  - glog (from `../node_modules/react-native/third-party-podspecs/glog.podspec`)
  - RCT-Folly (from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`)
  - RCTRequired (from `../node_modules/react-native/Libraries/RCTRequired`)
  - RCTTypeSafety (from `../node_modules/react-native/Libraries/TypeSafety`)
  - React (from `../node_modules/react-native/`)
  - React-callinvoker (from `../node_modules/react-native/ReactCommon/callinvoker`)
  - React-Core (from `../node_modules/react-native/`)
  - React-Core/DevSupport (from `../node_modules/react-native/`)
  - React-Core/RCTWebSocket (from `../node_modules/react-native/`)
  - React-CoreModules (from `../node_modules/react-native/React/CoreModules`)
  - React-cxxreact (from `../node_modules/react-native/ReactCommon/cxxreact`)
  - React-jsi (from `../node_modules/react-native/ReactCommon/jsi`)
  - React-jsiexecutor (from `../node_modules/react-native/ReactCommon/jsiexecutor`)
  - React-jsinspector (from `../node_modules/react-native/ReactCommon/jsinspector`)
  - react-native-appsflyer (from `../node_modules/react-native-appsflyer`)
  - react-native-safe-area-context (from `../node_modules/react-native-safe-area-context`)
  - react-native-version-check (from `../node_modules/react-native-version-check`)
  - react-native-webview (from `../node_modules/react-native-webview`)
  - React-perflogger (from `../node_modules/react-native/ReactCommon/reactperflogger`)
  - React-RCTActionSheet (from `../node_modules/react-native/Libraries/ActionSheetIOS`)
  - React-RCTAnimation (from `../node_modules/react-native/Libraries/NativeAnimation`)
  - React-RCTBlob (from `../node_modules/react-native/Libraries/Blob`)
  - React-RCTImage (from `../node_modules/react-native/Libraries/Image`)
  - React-RCTLinking (from `../node_modules/react-native/Libraries/LinkingIOS`)
  - React-RCTNetwork (from `../node_modules/react-native/Libraries/Network`)
  - React-RCTSettings (from `../node_modules/react-native/Libraries/Settings`)
  - React-RCTText (from `../node_modules/react-native/Libraries/Text`)
  - React-RCTVibration (from `../node_modules/react-native/Libraries/Vibration`)
  - React-runtimeexecutor (from `../node_modules/react-native/ReactCommon/runtimeexecutor`)
  - ReactCommon/turbomodule/core (from `../node_modules/react-native/ReactCommon`)
  - RecurlySDK
  - "RNCAsyncStorage (from `../node_modules/@react-native-async-storage/async-storage`)"
  - "RNCPicker (from `../node_modules/@react-native-picker/picker`)"
  - RNFastImage (from `../node_modules/react-native-fast-image`)
  - RNGestureHandler (from `../node_modules/react-native-gesture-handler`)
  - RNReanimated (from `../node_modules/react-native-reanimated`)
  - RNSVG (from `../node_modules/react-native-svg`)
  - "UMCore (from `../node_modules/@unimodules/core/ios`)"
  - "UMReactNativeAdapter (from `../node_modules/@unimodules/react-native-adapter/ios`)"
  - Yoga (from `../node_modules/react-native/ReactCommon/yoga`)

SPEC REPOS:
  trunk:
    - AppsFlyerFramework
    - boost-for-react-native
    - libwebp
    - RecurlySDK
    - SDWebImage
    - SDWebImageWebPCoder

**Comment by aedocoding** [comment]
From what I've gathered, the app I'm working on makes use of Pubnub, which depends on isomorphic-webcrypto, which itself depends on @unimodules/core and @unimodules/react-native-adapter.

So for any other developers running into a similar issue, I would hold off on upgrading to the latest SDK if you run into a similar issue. It seems the deprecation of unimodules has caused the upgrade to the latest SDK impossible for some apps that are reliant on other libraries that make use of unimodules still.

https://githubhelp.com/kevlened/isomorphic-webcrypto/issues/57

**Comment by Kudo** [comment]
@aedocoding thanks for deep diving the problem. maybe `isomorphic-webcrypto` should remove unimodules or move unimodules out from `optionalDependencies` like this https://github.com/kevlened/isomorphic-webcrypto/pull/41
