### ISSUE TITLE
app.json and app.config.js not getting merged

### ISSUE THREAD

**Issue by acrdlph** [expo/expo-cli#4100]
### Summary

[According to the docs](https://docs.expo.dev/workflow/configuration/#dynamic-configuration-with-appconfigjs) you can have both `app.json` and `app.config.js` and the two will get merged. This is not working when I build my app on EAS. When there is a static `app.json` the build exclusively uses the configuration from there and does not take the dynamic `app.config.js` into account.

(For my dynamic configuration to be picked up, I had to put my entire config into `app.config.js` and remove the `app.json` file. This is not optimal because I also want to use [Standard Version Expo](https://github.com/expo-community/standard-version-expo) which only works with a static `app.json`.)

### Environment

```
Expo CLI 5.0.1 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.12 - /usr/local/bin/npm
      Watchman: 2021.10.11.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.0 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.42.4
      expo-cli: 5.0.1
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

N/A

### Reproducible demo or steps to reproduce from a blank project

Start a new expo project and configure it with eas:

```
expo init app-config-demo
eas build:configure
```

Add an app.config.js that looks somewhat like this:

```
export default ({ config }) => {
  console.log(config);
  return {
    name: "test name",
    slug: "test slug",
    ...config,
  };
};
```

Create a build and see for yourself in the logs of the `Read app config` step that the build is only using the static `app.json` config without taking the dynamic `app.config.js` into account.

MCVE: https://github.com/acrdlph/expo-mcve/tree/dynamic-and-static-config

**Comment by brentvatne** [comment]
this isn't a bug in expo, it's a bug in your javascript ;)

if you use `...config` after defining `name` and `slug` and those properties are also on config, then they will be clobbered by spread. notice if you do this it'll work as expected:

```
export default ({ config }) => {
  console.log(config);
  return {
    ...config,
    name: "test name",
    slug: "test slug",
  };
};
```

you can also test this locally by running `expo config --type public` to evaluate the app config in the same way as eas build does

**Comment by acrdlph** [comment]
Thanks @brentvatne !!

**Comment by CryptoDev4** [comment]
It is necessary to have both files app.json & app.config.js to test and deploy to production the expo app?

**Comment by CryptoDev4** [comment]
Or can i delete app.json?

**Comment by brentvatne** [comment]
@CryptoDev4 - you can use app.json, app.config.js, or both. you can delete app.json if you don't use it.

**Comment by mksquad87** [comment]
Hi @brentvatne,

I had the same issue as acrdlph but when i type `eas update:config` I get the follwoing error:

`It looks like you are using a dynamic configuration! Learn more: https://docs.expo.dev/workflow/configuration/#dynamic-configuration-with-appconfigjs)
In order to finish configuring your project for EAS Update, you are going to need manually add the following to your app.config.js:
Learn more: https://expo.fyi/eas-update-config.md
{
  "runtimeVersion": {
    "policy": "sdkVersion"
  },
  "android": {
    ...
  },
  "ios": {
    ...
  },
  "updates": {
    "fallbackToCacheTimeout": 0,
    "url": "https://u.expo.dev/c21606c0-d0cc-11e9-a631-..."
  }
}

    Error: Cannot automatically write to dynamic config at: app.config.js
`

The app.config.js looks like this:
`
module.exports = () => {
  if (process.env.APP_ENV === "production") {
    return require("./app-production.json");
  } else if (process.env.APP_ENV === "staging") {
    return require("./app-staging.json");
  } else {
    return require("./app.json");
  }
};
`
I tried pasting the json code from the error message directly into `app.config.js` and also directly into the `app.json` but Im still getting the error message...

Very happy about every suggestion/idea!

**Comment by JavaScriptJohn** [comment]
> Hi @brentvatne,
> 
> I had the same issue as acrdlph but when i type `eas update:config` I get the follwoing error:
> 
> ```
> It looks like you are using a dynamic configuration! Learn more: https://docs.expo.dev/workflow/configuration/#dynamic-configuration-with-appconfigjs)
> In order to finish configuring your project for EAS Update, you are going to need manually add the following to your app.config.js: 
> Learn more: https://expo.fyi/eas-update-config.md
> {
>   "runtimeVersion": {
>     "policy": "sdkVersion"
>   },
>   "android": {
>     ...
>   },
>   "ios": {
>     ...
>   },
>   "updates": {
>     "fallbackToCacheTimeout": 0,
>     "url": "https://u.expo.dev/c21606c0-d0cc-11e9-a631-..."
>   }
> }
> 
> Error: Cannot automatically write to dynamic config at: app.config.js
> ```
> 
> The app.config.js looks like this:
> 
> ```
> module.exports = () => {
>   if (process.env.APP_ENV === "production") {
>     return require("./app-production.json");
>   } else if (process.env.APP_ENV === "staging") {
>     return require("./app-staging.json");
>   } else {
>     return require("./app.json");
>   }
> };
> ```
> 
> I tried pasting the json code from the error message directly into `app.config.js` and also directly into the `app.json` but Im still getting the error message...
> 
> Very happy about every suggestion/idea!

I'm having this exact issue, were you able to figure it out? 

When I log the output I see exactly what it's asking for.

**Comment by SebaRiccardo** [comment]
@mksquad87 , @JavaScriptJohn . I did it manually and it worked for me.  Adding the updates url and runtime version.

https://github.com/expo/fyi/blob/main/eas-update-config.md
