### ISSUE TITLE
app.config.tsx get ignored

### ISSUE THREAD

**Issue by RohovDmytro** [expo/expo-cli#4104]
### Summary

`eas build` ignore `app.config.tsx` file extension.

### Environment

 Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
      Watchman: 2021.12.20.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 23, 25, 30, 31
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0
        System Images: android-24 | Google APIs ARM 64 v8a, android-25 | Google APIs ARM 64 v8a, android-28 | Intel x86 Atom_64, android-29 | Google APIs ARM 64 v8a, android-30 | ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-31 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^9.0.2 => 9.0.2 
      expo: ^44.0.3 => 44.0.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

n/a

### Error output

If I have an app.config.tsx file I get only the default config on eas servers:

![Uploading image.png…]()

### Reproducible demo or steps to reproduce from a blank project

n/a

**Comment by brentvatne** [comment]
hi there! `app.config.tsx` doesn't really make sense because app config is a node environment and you will not want to use react there. `app.config.ts` however is supported. you can test this out locally by running `expo config --type public` in your project directory
