### ISSUE TITLE
Eslint and webpack with module path feature

### ISSUE THREAD

**Issue by ifmael** [expo/expo-cli#4107]
I want to use the module path feature in webpack because the code is very clean with this feature.

My current project is an expo app with typescript so i found in the expo doc how to implement the module path feature. Basically, it’s that
```
const createExpoWebpackConfigAsync = require("@expo/webpack-config");
const path = require("path");

module.exports = async function (env, argv) {
    const config = await createExpoWebpackConfigAsync(env, argv);

    config.resolve.modules = [path.resolve("./src"), "node_modules"];

  return config;
};
```
That returns a promise.

On the other hand, I would like to use eslint to have extra help while i’m coding, and that is the problem i don’t know how to configure eslint with the module path feature. The package eslint-plugin-import allow use the webpack cnf for eslint but the webpack conf has to be sync and the expo project use an async configuration.

is there any plan to implement createExpoWebpackConfig in a sync way?

**Comment by fkranenburg** [comment]
This is still a very valid question.
