### ISSUE TITLE
expo cli 5.0.3 with dev-client: Linking is disabled because the client scheme cannot be resolved.

### ISSUE THREAD

**Issue by newme616** [expo/expo-cli#4110]
### Summary

I use  with dev-client, constantly get the error: Linking is disabled because the client scheme cannot be resolved.
<img width="437" alt="Screenshot 2022-01-03 at 19 54 47" src="https://user-images.githubusercontent.com/28349724/147968817-3d9ed24c-fd3c-4247-b1b7-1a819bd8fbc6.png">

the ios build works and I have no other issues.

Before upgrading expo I didn't have any issues.

### Environment

 Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 11.6.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0 => 43.0.4 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.38.3
      expo-cli: 5.0.3
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

Simulator iPhone 13 iOS 15.2

### Error output

Linking is disabled because the client scheme cannot be resolved.

### Reproducible demo or steps to reproduce from a blank project

This is the app.json:
`{
  "expo": {
    "name": "dr_sandbox",
    "slug": "dr_sandbox",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": ["**/*"],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "dr_sandbox"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      },
      "package": "com.dr7.dr_sandbox",
      "googleServicesFile": "./android/app/google-services.json"
    },
    "plugins": [
      "@react-native-firebase/app",
      [
        "expo-image-picker",
        {
          "photosPermission": "The app accesses your photos to let you share them with your friends."
        }
      ]
    ],
    "web": {
      "favicon": "./assets/favicon.png"
    }
  }
}`

and here the package.json
`{
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-community/netinfo": "6.0.2",
    "@react-native-firebase/app": "^13.0.1",
    "@react-native-firebase/auth": "^13.1.0",
    "@react-native-firebase/database": "^13.1.0",
    "@react-native-firebase/firestore": "^13.1.0",
    "@react-navigation/bottom-tabs": "^5.11.10",
    "@react-navigation/drawer": "^5.12.5",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.4",
    "expo": "^43.0.0",
    "expo-app-loading": "~1.2.1",
    "expo-dev-client": "^0.6.3",
    "expo-secure-store": "~11.0.3",
    "expo-splash-screen": "~0.13.5",
    "expo-status-bar": "~1.1.0",
    "expo-updates": "~0.10.13",
    "formik": "^2.2.9",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-reanimated": "~2.2.0",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.8.0",
    "react-native-web": "0.17.1",
    "react-navigation-header-buttons": "^7.0.1",
    "react-redux": "^7.2.4",
    "redux": "^4.1.0",
    "redux-thunk": "^2.3.0",
    "yup": "^0.32.11",
    "expo-image-picker": "~11.0.3"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@testing-library/react-native": "^8.0.0",
    "babel-jest": "^27.3.1",
    "babel-preset-react-native": "^4.0.1",
    "jest": "^27.3.1",
    "jest-expo": "^43.0.0",
    "jest-react-native": "^18.0.0",
    "react-test-renderer": "^17.0.2"
  },
  "jest": {
    "preset": "jest-expo",
    "transformIgnorePatterns": [
      "node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)"
    ]
  },
  "private": true,
  "name": "dr",
  "version": "1.0.0"
}
`

**Comment by tcdavis** [comment]
It is hard to tell from your report, but I believe you have skipped some of the installation steps: https://docs.expo.dev/development/installation/#2-basic-configuration

Could you confirm that that is the case? I think we could potentially show a better warning message here if that is what is happening

**Comment by newme616** [comment]
Thank you so much 
`npx uri-scheme add <your scheme>` solved the issue.

I was a bit confused, because I just "ejected" from managed workflow and it was not a bare project in the beginning.

**Comment by tcdavis** [comment]
Ahh makes sense. Thanks for reporting back!
