### ISSUE TITLE
Apple does not accept expo produced build.

### ISSUE THREAD

**Issue by AjkP** [expo/expo-cli#4114]
### Summary

I started getting the following error when trying to build my app through the expo build cli tool.

```
ITMS-90901: Missing full-screen support for the latest iPad mini display.
The “ExpoKitApp.app” bundle includes UIRequiresFullScreen=YES in the Info.plist
or supports only a subset of UISupportedInterfaceOrientations, and is built with the 14.1 SDK.
To take advantage of the full screen size, recompile with Xcode 13 and the SDK for iPadOS 15 or later.
```
I searched around and the only thing I found is maybe adding `      "requireFullScreen": true` on **app.json** could fix it, but unfortunately it didn't.

I tried to search around the forums and issues but found nothing. I thought maybe my expo version is old, but I can't find any versioning info on the docs (like when requireFullScreen was added). I found a commit in the main expo repo working on requireFullScreen years ago, so I doubt that's the issue.
    

### Environment

  ```
  Expo CLI 4.4.7 environment info:
    System:
      OS: macOS 11.6.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.12.0 - /usr/local/bin/node
      npm: 7.6.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.4.7
    Expo Workflow: managed
    ```

### Please specify your device/emulator/simulator platform, model and version

Build related.

### Error output

N/A. Build runs fine. Just apple doesn't accept it.

### Reproducible demo or steps to reproduce from a blank project

N/A

**Comment by brentvatne** [comment]
update to expo sdk 41, 42, 43, or 44. we only support the latest 4 sdks at any time

**Comment by astriskit** [comment]
This happened with sdk-41 too - would like to reopen this @brentvatne
