### ISSUE TITLE
Expo SDK 44 => expo publish --release-channel <release channel name> is not working

### ISSUE THREAD

**Issue by ahmetbasdan** [expo/expo-cli#4116]
### Summary

The custom release channel I downloaded apk with eas build --profile preview
expo sdk 43 expo publish --release-channel <channel name> works but expo sdk 44 doesn't work either

### Environment

expo build --profile preview
expo publish --release-channel preview 
expo upgrade (SDK 44)
expo publish --release-channel preview  (successful but not updating when I restart my app)

### Please specify your device/emulator/simulator platform, model and version

expo go lasted version - android device

### Reproducible demo or steps to reproduce from a blank project

eas.json
![eas](https://user-images.githubusercontent.com/18085857/148064320-f62b6d87-1628-4f38-a497-de4307a784ae.png)

**Comment by brentvatne** [comment]
it does work. please share a reproducible example if you believe you have found otherwise. what you have provided is incomplete. see https://stackoverflow.com/help/minimal-reproducible-example for more info
