### ISSUE TITLE
[BUILD FAILED] The following build commands failed: 	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'EXUpdates' from project 'Pods')

### ISSUE THREAD

**Issue by garrett-gottlieb** [expo/expo-cli#4119]
### Summary

After upgrading from 43 to 44, I'm receiving some weird errors when attempting to run my Expo bare app on my iPhone.

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 12.22.7 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
      Watchman: 2021.11.01.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27
        Build Tools: 19.1.0, 21.1.2, 23.0.1, 23.0.2, 23.0.3, 24.0.3, 25.0.0, 25.0.2, 26.0.2, 26.0.3, 28.0.2, 28.0.3
        System Images: android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.4
      react-native: 0.64.3 => 0.64.3
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

iPhone XS iOS v15.1

### Error output

```
2022-01-05 05:21:03.595 xcodebuild[44832:2155528]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-19527/DTDeviceKitBase/DTDKRemoteDeviceData.m:373
Details:  (null) deviceType from 00008020-001629CC2146002E was NULL when -platform called.
Object:   <DTDKMobileDeviceToken: 0x7fe4f209f7f0>
Method:   -platform
Thread:   <NSThread: 0x6000034f09c0>{number = 4, name = (null)}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
2022-01-05 05:21:03.884 xcodebuild[44832:2155526]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-19527/DTDeviceKitBase/DTDKRemoteDeviceData.m:373
Details:  (null) deviceType from 00008020-001629CC2146002E was NULL when -platform called.
Object:   <DTDKMobileDeviceToken: 0x7fe4f209f7f0>
Method:   -platform
Thread:   <NSThread: 0x600003bb0300>{number = 10, name = (null)}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
2022-01-05 05:21:03.972 xcodebuild[44832:2155526]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-19527/DTDeviceKitBase/DTDKRemoteDeviceData.m:373
Details:  (null) deviceType from 00008020-001629CC2146002E was NULL when -platform called.
Object:   <DTDKMobileDeviceToken: 0x7fe4f209f7f0>
Method:   -platform
Thread:   <NSThread: 0x600003bb0300>{number = 10, name = (null)}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
** BUILD FAILED **


The following build commands failed:
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'EXUpdates' from project 'Pods')
	PhaseScriptExecution [CP-User]\ Generate\ app.config\ for\ prebuilt\ Constants.manifest /Users/gsquare567/Library/Developer/Xcode/DerivedData/Blogcast-dwouogsenmyqjydcufqlxdhmklle/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/EXConstants.build/Script-5EA29C51D9D7C41F8548CAAF0EA4AA7C.sh (in target 'EXConstants' from project 'Pods')
(2 failures)
Build logs written to /Users/gsquare567/Sites/blogcast/mobile/.expo/xcodebuild.log
error Command failed with exit code 1.
```

### Reproducible demo or steps to reproduce from a blank project

1. Upgrade to Expo 44 from Expo 43 in `expo-yarn-workspaces` project
1. `rm -rf ios android` from project folder
1. `expo prebuild`
1. `APP_ENV=development EXPO_DEBUG=true expo run:ios --device GG --port 8081`

**Comment by garrett-gottlieb** [comment]
Duplicate of https://github.com/expo/expo/issues/15665

Solution was replacing `~/.bash_profile` with an empty file...

**Comment by Seanmclem** [comment]
I can't believe this worked, but it did. Immediately. 

I tried so many other things. I don't even use bash, I use zsh. Still, Fig wrote to the `~/.bash_profile` at some point, and that broke building this app, after a recent pod-install. So random, but emptying the `~/.bash_profile` worked. Thanks!
