### ISSUE TITLE
Trying to bundle with current Node version 17.3.0 results in error and fails.

### ISSUE THREAD

**Issue by rupakhetibinit** [expo/expo-cli#4126]
### Summary

Running `expo start` the bundling fails on current node version 17.3.0. I just upgraded my node version to latest.

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 17.3.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 29, 30, 31
        Build Tools: 29.0.2, 29.0.3, 30.0.2, 31.0.0
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7486908
    npmPackages:
      expo: ^44.0.0 => 44.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Xiaomi Mi A2 Lite Android 10.0, Pixel 

### Error output

Failed to construct transformer:  Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at stableHash (D:\Binit Things\College Minor Project\managed recipe app\recipetohome\node_modules\metro-cache\src\stableHash.js:19:8)
    at Object.getCacheKey (D:\Binit Things\College Minor Project\managed recipe app\recipetohome\node_modules\metro-transform-worker\src\index.js:647:7) 
    at getTransformCacheKey (D:\Binit Things\College Minor Project\managed recipe app\recipetohome\node_modules\metro\src\DeltaBundler\getTransformCacheKey.js:32:19)
    at new Transformer (D:\Binit Things\College Minor Project\managed recipe app\recipetohome\node_modules\metro\src\DeltaBundler\Transformer.js:180:28) 
    at D:\Binit Things\College Minor Project\managed recipe app\recipetohome\node_modules\metro\src\Bundler.js:58:29 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
Android Bundling failed 24ms
Cannot read properties of undefined (reading 'transformFile')

### Reproducible demo or steps to reproduce from a blank project

1. Start a new project with expo init.
2. Run `npm start`
3. Scan QR code on a mobile app.
4. The bundling fails with the above error.

**Comment by kbrandwijk** [comment]
Npm 17 is not supported yet by the underlying webpack engine, used by the bundler. See this issue for more details: https://github.com/expo/expo-cli/issues/3988

**Comment by HeyClos** [comment]
I'm having this issue too.
