### ISSUE TITLE
Unrecognizable URI Scheme

### ISSUE THREAD

**Issue by TechStudent11** [expo/expo-cli#4127]
### Summary

When generating a brand new app using `expo init` and running `yarn start`, I get an error telling me to add a URI Scheme.

```
Dev Client: No common URI schemes could be found for the native iOS and Android projects, this is required for opening the project

Add a common scheme with npx uri-scheme add my-scheme or provide a scheme with the --scheme flag
```

It's telling you to add a new URI Scheme named "my-scheme". The problem? When scanning it on an iPhone with the Expo Go app installed, it's unrecognizable. The scheme should be `exp`.

### Environment

```
Expo CLI 4.10.0 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\moham\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7583922
    npmPackages:
      expo: ~44.0.2 => 44.0.4
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: bare
```

### Please specify your device/emulator/simulator platform, model and version

Device: iPhone, 6 Plus, iOS 12.5.5
Development Machine: Windows 11 Home, Intel i3 10th Gen

### Reproducible demo or steps to reproduce from a blank project

1. Create Project
2. Run `yarn start`
3. Copy, paste and run the command from error.

**Comment by EvanBacon** [comment]
This warning doesn't appear to be part of the CLI anymore, please try upgrading to `expo-cli@5.0.3`

**Comment by TechStudent11** [comment]
> This warning doesn't appear to be part of the CLI anymore, please try upgrading to `expo-cli@5.0.3`

Thanks, I'll try later.
