### ISSUE TITLE
expo-cli 5.0.3 crashes while looking for projectId

### ISSUE THREAD

**Issue by dqii** [expo/expo-cli#4129]
### Summary

Same bug as here: https://github.com/expo/expo-cli/issues/3928
But for line: https://github.com/expo/expo-cli/blob/930764ccdde1abf4f386043fed40c24a235137d3/packages/xdl/src/start/ExpoUpdatesManifestHandler.ts#L139

Running `expo start` crashes with expo-cli 5.0.3 crashes on startup when the project has an app.json with an extra key but without an eas sub-key

### Environment

```

  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.4 - /usr/local/bin/node
      Yarn: 1.22.17 - ~/.yarn/bin/yarn
      npm: 8.1.3 - /usr/local/bin/npm
      Watchman: 2021.11.01.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.4 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.43.0
      expo-cli: 5.0.3
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

Mac

### Reproducible demo or steps to reproduce from a blank project

https://github.com/dqii/projectId-crash

Expo SDK 44 + Expo Updates

**Comment by mzanini** [comment]
Same behavior for me. Expo-cli: 5.0.3. Expo SDK 44, Managed workflow

**Comment by dqii** [comment]
That's the same bug in a different file.

**Comment by ataravati** [comment]
This still happens to someone in our team with expo-cli 5.3.1 on Windows.
