### ISSUE TITLE
Version 2.11.7 fail on alpha channel in Icon

### ISSUE THREAD

**Issue by omrihaim** [expo/expo-cli#414]
After upgrading from version 2.11.6 to 2.11.7, expo build:ios fails with:
"can't have an alpha channel if you wish to upload your app to Apple Store."

this is on an application that was already uploaded with the same icon, so the issue isnt in the specific icon. Revert to version 2.11.6 allowed the build to complete and the upload to app store to be completed.

The icon path in the app.json is:
"icon": "./assets/images/icon.png"

**Comment by wkozyra95** [comment]
Hi

Can you provide output of cmd `file ./assets/images/icon.png`

**Comment by evanheckert** [comment]
I'm still running into this issue with 2.13.0, having used both Preview and Photoshop to verify that alpha is not enabled.

**Comment by dsokal** [comment]
@evanheckert sorry, but we haven't made that change public yet. It will be included in the next release.

**Comment by evanheckert** [comment]
> @evanheckert the issue you're experiencing is a different one. It's not related to the transparency of the icon. It's a common issue when people upgrade Expo SDK version and they don't add the `assetBundlePatterns` key to `app.json` file. Please read the documentation.
> 
> _Originally posted by @dsokal in https://github.com/expo/expo-cli/pull/456#issuecomment-483566831_
> 

@dsokal Thanks for the reply. I've indeed read the documentation, and have indeed added the `assetBundlePatterns` key.

```
{
  "expo": {
    "name": "My AppName",
    "slug": "my_appname",
    "privacy": "public",
    "sdkVersion": "32.0.0",
    "platforms": [
      "ios"
    ],
    "version": "0.9.4",
    "orientation": "default",
    "icon": "./assets/icon-ios.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "cover",
      "backgroundColor": "#F6F7F8"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "assets/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.coname.appname"
    }
  }
}
```

Just ran it again and got the familiar `Error: Failed to resize image: AppIcon29x29@2x.png. (Error: Input file contains unsupported image format)`. Interestingly, it'll sometimes error at the 20x20, and sometimes at the 1024x1024 as well.

**Comment by dsokal** [comment]
@evanheckert 
1. Please don't post random issues in random places. As I already messaged you, it has nothing to do with the alpha channel in your application icon. The check which my pull request added happens only in expo-cli (on the user side).
2. `assetBundlePatterns` is a glob pattern and `assets/*` doesn't cover `/assets/images/icon.png`
3. Change your `assetBundlePatterns` to `assets/**/*`.
