### ISSUE TITLE
Linking is disabled because the client scheme cannot be resolved

### ISSUE THREAD

**Issue by tiavina-mika** [expo/expo-cli#4140]
### Summary

When I run expo android, I got this error: 
`Linking is disabled because the client scheme cannot be resolved`

![image](https://user-images.githubusercontent.com/42656064/149277851-46bd3733-8c3b-4843-8eca-f793cc1b87b5.png)

### Environment

  Expo CLI 5.0.2 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 7.20.1 - C:\Program Files\nodejs\npm.CMD
      Watchman: 20210110.135312.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30, 31, 32
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 32.0.0
        System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom_64, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7935034
    npmPackages:
      expo: ~42.0.0 => 42.0.5
      react: 16.13.1 => 16.13.1
      react-dom: 17.0.1 => 17.0.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

Name: Pixel_4_API_30 CPU/ABI: Google Play Intel Atom (x86) Path: C:\Users\ASUS\.android\avd\Pixel_4_API_30.avd Target: google_apis_playstore [Google Play] (API level 30)

### Error output

Error updating dev session: XDLError: No scheme specified for development client

### Reproducible demo or steps to reproduce from a blank project

- run `yarn ios`

**Comment by hemerson-git** [comment]
Same error here.

"expo": ~44.0.2
"expo-cli": 5.0.3
"react-native": "0.64.3",
"react": "17.0.1",

**Comment by pzatorski** [comment]
Please check if `android:launchMode="singleTask"` property is included in `<activity />` tag.
This tag is used in the `AndroidManifest.xml` file on android.
```
<activity android:name=".MainActivity" android:launchMode="singleTask" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|screenLayout|uiMode" android:documentLaunchMode="never" android:label="@string/app_name" android:screenOrientation="unspecified" android:windowSoftInputMode="adjustResize">
```

**Comment by hemerson-git** [comment]
> Please check if `android:launchMode="singleTask"` property is included in `<activity />` tag. This tag is used in the `AndroidManifest.xml` file on android.
> 
> Example:
> 
> ```
> <activity android:name=".MainActivity" android:launchMode="singleTask" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|screenLayout|uiMode" android:documentLaunchMode="never" android:label="@string/app_name" android:screenOrientation="unspecified" android:windowSoftInputMode="adjustResize">
> ```
> 
> More info [here](https://github.com/expo/fyi/blob/main/setup-android-uri-scheme.md).

In My case, singleTask is included.

This is my .MainActivity:

```
<activity 
      android:name=".MainActivity" 
      android:label="@string/app_name" 
      android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" 
      android:launchMode="singleTask" 
      android:windowSoftInputMode="adjustResize" 
      android:theme="@style/Theme.App.SplashScreen"
    >
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="my-app"/>
        <data android:scheme="exp+my-app"/>
        <data android:scheme="com.exaple.myApp"/>
      </intent-filter>
    </activity>
```

**Comment by EvanBacon** [comment]
This is expected functionality. The "linking" is the QR code. We disable showing the QR code when we detect ios and android are both in the project and they don't share a common URI scheme. You can interact with your URI schemes automatically by using `npx uri-scheme`. For example, if you did `npx uri-scheme add foobar` then the common scheme would be `foobar` as iOS and Android would both conform to that scheme.

Regardless, opening single platforms with `i` or `a` should still work in limited capacities (they won't work if there are no URI schemes).

**Comment by johnyfwesh** [comment]
`npx uri-scheme`
then
npx uri-scheme add foobar

is should work now

**Comment by frederikocmr** [comment]
Just follow this guide: https://github.com/expo/fyi/blob/main/setup-android-uri-scheme.md

And then `npx uri-scheme add your-project-name`

It will work!

**Comment by dilenio** [comment]
I tryed to run this command and I get this message. Can someone help me please?
`npx uri-scheme add your-project-name`
No URI schemes could be added. Please ensure there is a native project available.

**Comment by psudocode** [comment]
> I tryed to run this command and I get this message. Can someone help me please? `npx uri-scheme add your-project-name` No URI schemes could be added. Please ensure there is a native project available.

any update how to solve this?

**Comment by davidcort** [comment]
i have same issue on Expo 44 SDK.
My project is bare react native.

**Comment by lawrence-laz** [comment]
I'm stupid, but maybe this will help someone.

Had same issue, but I accidentally ran the wrong command while using bash history
```
expo start --dev-client --tunnel
```
instead of 
```
expo start --tunnel
```
(current project didn't have a dev client)
