### ISSUE TITLE
expo-cli dependency @expo/apple-utils does not have a license attached

### ISSUE THREAD

**Issue by AndresSalinasB** [expo/expo-cli#4148]
### Summary

expo-cli has a dependency on @expo/apple-utils but the latter does not have a LICENSE file attached to it. Usually all expo packages have a LICENSE file attached (like https://github.com/expo/expo-cli/blob/main/packages/expo-cli/LICENSE).

Is this something that was missed? I could not find the repo of @expo/apple-utils to submit the PR myself.

Thanks!N

### Environment

N/A

### Please specify your device/emulator/simulator platform, model and version

N/A

### Reproducible demo or steps to reproduce from a blank project

N/A

**Comment by EvanBacon** [comment]
`@expo/apple-utils` is in a private repo and shouldn't be used publicly as the API is not stable. Is there a particular reason you need a license for that project?

**Comment by AndresSalinasB** [comment]
We're not trying to consume that package directly, just expo-cli, but because expo-cli fetches apple-utils our company license validation does not allow us to use expo-cli.
