### ISSUE TITLE
expo run:ios fails to install pods 

### ISSUE THREAD

**Issue by MasoudJB** [expo/expo-cli#4149]
### Summary

I am trying to run`expo run:ios` on my Macbook Pro and It does not install pods. My problem gets reproduced with the simplest app as well using the following codes and I get the `Invalid Podfile file: syntax error, unexpected '.'.` error while installing the pods:

`expo init ;
cd my-app ;
yarn install ;
expo run:ios
`

My system uses M1 silicon processor so I have also tested `arch -X86_64 expo run:ios` which resulted in the same error. I have no isse with `eas build`

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
    Managers:
      CocoaPods: 1.5.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.42.4
      expo-cli: 5.0.3
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

MacBook Pro with a M1 architecture

### Error output
```

⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Invalid `Podfile` file: syntax error, unexpected '.'.

 #   from /[Address]/my-app/ios/Podfile:31
 #   -------------------------------------------
 #       installer.pods_project.targets.each do |target|
  >        if (target.name&.eql?('FBReactNativeSpec'))
 #           target.build_phases.each do |build_phase|
 #  -------------------------------------------
 

› Planning build

› 0 error(s), and 0 warning(s)

Failed to build iOS project. "xcodebuild" exited with error code 65.
To view more error logs, try building the app with Xcode directly, by opening /[Address]/my-app/ios/myapp.xcodeproj.

Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project /[Address]/my-app/ios/myapp.xcodeproj -configuration Debug -scheme myapp -destination id=3EF2FC42-F580-48BF-8069-3FD070E8574A

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

note: Using new build system
note: Planning
Analyze workspace

Create build description
Build description signature: 30f9048e4b7daf8859b2c2d9e2f2fd89
Build description path: /[Address]/Xcode/DerivedData/myapp-dborouddiuzdkneusqxfcwnkzowr/Build/Intermediates.noindex/XCBuildData/30f9048e4b7daf8859b2c2d9e2f2fd89-desc.xcbuild

note: Build preparation complete
note: Building targets in parallel
/[Address]/my-app/ios/Pods/Target Support Files/Pods-myapp/Pods-myapp.debug.xcconfig:1:1: error: unable to open file (in target "myapp" in project "myapp")
/[Address]/my-app/ios/Pods/Target Support Files/Pods-myapp/Pods-myapp.debug.xcconfig:1:1: error: unable to open file (in target "myapp" in project "myapp")
/[Address]/my-app/ios/Pods/Target Support Files/Pods-myapp/Pods-myapp.debug.xcconfig:1:1: error: unable to open file (in target "myapp" in project "myapp")
/[Address]/my-app/ios/Pods/Target Support Files/Pods-myapp/Pods-myapp.debug.xcconfig:1:1: error: unable to open file (in target "myapp" in project "myapp")



** BUILD FAILED **

Build logs written to /[Address]/my-app/.expo/xcodebuild.log
```

### Reproducible demo or steps to reproduce from a blank project

`expo init ; cd my-app ; yarn install ; expo run:ios`

**Comment by EvanBacon** [comment]
Cannot repro. This appears to be related to the version of CocoaPods or Ruby that you have installed on your machine.

Here are my versions:
```
app 𝝠 ruby -v
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-darwin20]
app 𝝠 pod --version
1.11.2
```

**Comment by nathalia-rus** [comment]
> Cannot repro. This appears to be related to the version of CocoaPods or Ruby that you have installed on your machine.
> 
> Here are my versions:
> 
> ```
> app 𝝠 ruby -v
> ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-darwin20]
> app 𝝠 pod --version
> 1.11.2
> ```

What is your Xcode version? (mine is 13.1). I know this issue is closed, but I have the same problem - and I have seen this issue pop up in reddit etc recently too

**Comment by apostgit** [comment]
Anyone found a solution to this?

**Comment by aaronksaunders** [comment]
i am getting this issue with even a base project generated from template... looking for solution
