### ISSUE TITLE
Expo 36 : expo publish after IOS and Android Build create showing error :(

### ISSUE THREAD

**Issue by vivek751** [expo/expo-cli#4150]
### Summary

Error: getaddrinfo ENOTFOUND assets
[14:08:31] Before making a release build, make sure you have run 'expo publish' at least once. Learn more. (​https://expo.fyi/release-builds-with-expo-updates​

### Environment

Expo CLI 4.12.0 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - /usr/local/bin/node
      npm: 6.14.15 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.7.5 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-native-web: ^0.11.7 => 0.11.7 
      react-navigation: ^2.18.2 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 4.12.0

### Please specify your device/emulator/simulator platform, model and version

xcode 13

### Error output

https://assets/3a2ba31570920eeb9b1d217cabe58315
https://assets/8b12b3e16d591abc926165fa8f760e3b
https://assets/744ce60078c17d86006dd0edabcd59a7
https://assets/461d9bba8b6a3c91675039df12cfe6ca
https://assets/140c53a7643ea949007aa9a282153849
[14:08:31] Error: getaddrinfo ENOTFOUND assets
[14:08:31] Before making a release build, make sure you have run 'expo publish' at least once. Learn more. (​https://expo.fyi/release-builds-with-expo-updates​)
Command PhaseScriptExecution failed with a nonzero exit code

### Reproducible demo or steps to reproduce from a blank project

https://assets/3a2ba31570920eeb9b1d217cabe58315
https://assets/8b12b3e16d591abc926165fa8f760e3b
https://assets/744ce60078c17d86006dd0edabcd59a7
https://assets/461d9bba8b6a3c91675039df12cfe6ca
https://assets/140c53a7643ea949007aa9a282153849
[14:08:31] Error: getaddrinfo ENOTFOUND assets
[14:08:31] Before making a release build, make sure you have run 'expo publish' at least once. Learn more. (​https://expo.fyi/release-builds-with-expo-updates​)
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by creativemind1** [comment]
I'm also getting same error while doing builds. Getting same error for both Android and iOS

**Comment by ide** [comment]
Could you clarify what you mean? The issue description as it is written is not very clear.

Additionally, you may want to try upgrading Expo CLI since the latest version is the only one that receives patches.

**Comment by creativemind1** [comment]
@ide The issue is we couldn't able to create prod builds for both platform for expokit 36.0.0

**Comment by vivek751** [comment]
Please found solution:
https://github.com/expo/expo/issues/15961#issuecomment-1018448841
