### ISSUE TITLE
Upgrade from SDK v42 to v43 does not point to the react-native version from the expo/react-native

### ISSUE THREAD

**Issue by ivansenic** [expo/expo-cli#4152]
### Summary

Upgrading from SDK v42 to v43 changed the version of the `react-native` in the `package.json` from: 

`"react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz"` to 
`"react-native": "0.64.3",`

Considering that we are used that RN versions are fetched from the `expo/react-native`, is this the expected behavior?

Note that:

* Versions https://github.com/expo/react-native/archive/sdk-43.0.0.tar.gz and https://github.com/expo/react-native/archive/sdk-44.0.0.tar.gz are available for download
* A teammate run the `expo upgrade` from MacOS and this updates the RN to the version from the GitHub pack. I am seeing above behavior running from Linux

Can you please at least say what's the right version.

### Environment

```
  Expo CLI 5.0.3 environment info:
    System:
      OS: Linux 5.4 Ubuntu 18.04.6 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.22.0 - ~/.nvm/versions/node/v12.22.0/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 6.14.11 - ~/.nvm/versions/node/v12.22.0/bin/npm
    npmPackages:
      expo: ^44.0.0 => 44.0.3 
      react: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 0.45.1
      expo-cli: 5.0.3
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

Ubuntu 18.04.6 LTS

### Error output

None.

### Reproducible demo or steps to reproduce from a blank project

Running `expo init` does reveal the same, `package.json` created:

```
{
  "name": "my-app",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~44.0.0",
    "expo-status-bar": "~1.2.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-web": "0.17.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.64.12",
    "typescript": "~4.3.5"
  },
  "private": true
}
```

**Comment by brentvatne** [comment]
https://blog.expo.dev/expo-sdk-43-aa9b3c7d5541

> No more react-native fork in Expo managed apps. In SDK 42 and lower, your package.json includes something like: “react-native”: “https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz". In SDK 43 and higher, it’s just this: “react-native”: “0.64.3”.
