### ISSUE TITLE
How to list all release channel?

### ISSUE THREAD

**Issue by acrazing** [expo/expo-cli#4155]
Is there a way to list all release channel? I found a related question on stackoverflow, but it doesn't seem to get the right answer. <https://stackoverflow.com/questions/49928509/how-to-list-all-expo-release-channel>

### Do you understand that any feature requests opened in the core Expo repository will be closed?

Yes

**Comment by kbrandwijk** [comment]
If you use EAS, there's `eas channel:list`.

**Comment by EvanBacon** [comment]
Unfortunately we won't be adding new features to the classic services (`expo build`, `expo publish`, and associated commands) as they are in maintenance mode. Please migrate to [`eas-cli`](https://github.com/expo/eas-cli) for new features and faster bug fixes.
