### ISSUE TITLE
Prebuild doesn't accept the same 'template shortcuts' that init does

### ISSUE THREAD

**Issue by kbrandwijk** [expo/expo-cli#4158]
### Summary

`expo init` allows a few hardcoded templates (blank, bare, tabs, ...), while `expo prebuild` does. Now while it make not make much sense (apart from 'bare') to use any of those in conjunction with the prebuild command, it still would make sense to unify the behavior.

### Environment

-

### Please specify your device/emulator/simulator platform, model and version

-

### Reproducible demo or steps to reproduce from a blank project

- run `expo prebuild --template bare` and get an error.

**Comment by EvanBacon** [comment]
We should drop the weird template shortcuts from init since they add special logic cases that disallow certain local paths. But not explicitly, they can stay in init until we eventually drop expo-cli init in favor of create-react-native-app or a future create-expo-app.
