### ISSUE TITLE
Tunnel URL not found (it might not be ready yet), falling back to LAN URL.

### ISSUE THREAD

**Issue by IsTheJack** [expo/expo-cli#4159]
### Summary

There's an issue with the ngrok on a blank project. It's falling back to LAN URL.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version (managed workflow only)

44.0.0

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: Linux 4.19 Ubuntu 18.04.4 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 16.13.0 - ~/.asdf/installs/nodejs/16.13.0/bin/node
      npm: 8.1.0 - ~/.asdf/plugins/nodejs/shims/npm
    npmPackages:
      expo: ~44.0.0 => 44.0.5
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.42.4
      expo-cli: 5.0.3
    Expo Workflow: managed

### Reproducible demo

Steps to reproduce:

1 - Update expo-cli to `5.0.3`
2 - Create a new expo project `expo init` (I selected the Typescript blank template)
3 - Go to the project and install ngrok `npm install --save-dev @expo/ngrok@^4.1.0`
4 - Start the project `npm start`
5 - Open the `Expo Developer Tools` on Web . On `Connection`, click on `Tunnel`

Current behavior:
- It's getting: `Tunnel URL not found (it might not be ready yet), falling back to LAN URL.`

Expected behavior:
- It should connect to the tunnel successfully

**Comment by polcats** [comment]
I encountered this issue after returning to an expo project that I haven't touched for a while as well. I was able to make LAN and TUNNEL work by:
1. `adb -a nodaemon server start`
2. `adb reverse tcp:8081 tcp:8081`

I am also not sure WHY, but this works even on eas dev-clients (android & iOS) as well.
```
  Expo CLI 5.0.3 environment info:
    System:
      OS: Linux 5.10 Ubuntu 20.04.2 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.18.1 - ~/repos/emsdk/node/12.18.1_64bit/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/repos/emsdk/node/12.18.1_64bit/bin/npm
    SDKs:
      Android SDK:
        API Levels: 26, 28, 29, 30, 31
        Build Tools: 26.0.3, 28.0.3, 29.0.2, 30.0.0, 30.0.2
    npmPackages:
      expo: ^44.0.0 => 44.0.5
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.45.1
      expo-cli: 5.0.3
    Expo Workflow: managed
```

**Comment by IsTheJack** [comment]
> I encountered this issue after returning to an expo project that I haven't touched for a while as well. I was able to make LAN and TUNNEL work by:
> 
> 1. `adb -a nodaemon server start`
> 2. `adb reverse tcp:8081 tcp:8081`
> 
> I am also not sure WHY, but this works even on eas dev-clients (android & iOS) as well.
> 
> ```
>   Expo CLI 5.0.3 environment info:
>     System:
>       OS: Linux 5.10 Ubuntu 20.04.2 LTS (Focal Fossa)
>       Shell: 5.0.17 - /bin/bash
>     Binaries:
>       Node: 12.18.1 - ~/repos/emsdk/node/12.18.1_64bit/bin/node
>       Yarn: 1.22.4 - /usr/local/bin/yarn
>       npm: 6.14.5 - ~/repos/emsdk/node/12.18.1_64bit/bin/npm
>     SDKs:
>       Android SDK:
>         API Levels: 26, 28, 29, 30, 31
>         Build Tools: 26.0.3, 28.0.3, 29.0.2, 30.0.0, 30.0.2
>     npmPackages:
>       expo: ^44.0.0 => 44.0.5
>       react: 17.0.1 => 17.0.1
>       react-dom: 17.0.1 => 17.0.1
>       react-native: 0.64.3 => 0.64.3
>       react-native-web: 0.17.1 => 0.17.1
>     npmGlobalPackages:
>       eas-cli: 0.45.1
>       expo-cli: 5.0.3
>     Expo Workflow: managed
> ```

@polcats  That's strange! But anyway it did not work here. Step two returns: `error: no devices/emulators found`

**Comment by erickriva** [comment]
> As an extra detail: I'm having issues as well connecting on LAN. The app simply does not load. It's showing the `try again` button. I had it working a few weeks ago but I don't know when it stopped working because I was off of my project a few days as well.

LAN IP address is being recognized, or wasn't and fell back to '127.0.0.1'?
