### ISSUE TITLE
prevent expo to crash for any SyntaxError

### ISSUE THREAD

**Issue by arnaudambro** [expo/expo-cli#416]
### Environment

  Expo CLI 2.11.7 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.1 - /usr/local/bin/node
      Yarn: 1.13.0 - ~/.yarn/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.2
      react: ^16.5.0 => 16.7.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 2.11.7

target: iOS in dev mode

### Steps to Reproduce

make any typo in your code, and the app will crash

![expo-typo-error](https://user-images.githubusercontent.com/31724752/54146563-89a63180-4430-11e9-9655-cc684195b9b3.png)

### Expected Behavior
no crash for a typo, just as it works in android simulator

### Actual Behavior
in iOS (simulator or real device), you need to restart `expo start` and relaunch a new simulator to run the app again.

**Comment by AdamJNavarro** [comment]
Hey @arnaudambro,

This certainly shouldn't be the case. Can you try clearing all your caches and also running `rm -rf .expo`and see if that helps?

Cheers,
Adam

**Comment by arnaudambro** [comment]
I don't exactly know what you mean by clearing all my caches, but I followed what said in the first post of [this topic](https://forums.expo.io/t/how-to-clear-the-react-native-packager/1352), and did also `rm -rf .expo` in the working folder (a brand new one called originally `test` and created with `expo init`), and in my home directory too, but it didn't help : it still crashes at any typo.

If it can help, here is the debug I have from `expo` when running `expo start`: 

```
Running application "main"
with appParams: {
  "rootTag": 1,
  "initialProps": {
    "exp": {
      "manifest": {
        "splash": {
          "resizeMode": "contain",
          "image": "./assets/images/splash.png",
          "backgroundColor": "#ffffff",
          "imageUrl": "http://127.0.0.1:19003/assets/./assets/images/splash.png"
        },
        "developer": {
          "projectRoot": "/Users/me/Desktop/test",
          "tool": "expo-cli"
        },
        "loadedFromCache": false,
        "privacy": "public",
        "logUrl": "http://127.0.0.1:19000/logs",
        "orientation": "portrait",
        "sdkVersion": "32.0.0",
        "mainModuleName": "node_modules/expo/AppEntry",
        "env": {},
        "platforms": ["ios", "android"],
        "xde": true,
        "id": "@anonymous/test-eb764f6e-587b-4f24-873c-7c4085156a4d",
        "hostUri": "127.0.0.1:19000",
        "iconUrl": "http://127.0.0.1:19003/assets/./assets/images/icon.png",
        "assetBundlePatterns": ["**/*"],
        "name": "test",
        "slug": "test",
        "debuggerHost": "127.0.0.1:19003",
        "icon": "./assets/images/icon.png",
        "isVerified": false,
        "packagerOpts": {
          "lanType": "ip",
          "dev": true,
          "minify": false,
          "urlRandomness": "gs-x6p",
          "hostType": "lan"
        },
        "ios": {
          "supportsTablet": true
        },
        "updates": {
          "fallbackToCacheTimeout": 0
        },
        "bundleUrl": "http://127.0.0.1:19003/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%me%2FDesktop%2Ftest%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js",
        "version": "1.0.0"
      },
      "initialUri": "exp://127.0.0.1:19000",
      "appOwnership": "expo",
      "shell": 0
    }
  }
}.__DEV__ === true, development - level warning are ON, performance optimizations are OFF
```

**Comment by GitHubGreg** [comment]
Hi @arnaudambro did you ever find a resolution to this? I have the same issue.

**Comment by arnaudambro** [comment]
@GitHubGreg unfortunately not, I guess a clean install of the computer - or of node or npm or I don't know what - could fix, but I am too lazy to try...
Now I use expo bare flow, and it happens much less, but it still happens.
