### ISSUE TITLE
Error running `npx install-expo-modules` in Android-only project when trying to upgrade `expo` with RN 0.66.x compatibility

### ISSUE THREAD

**Issue by mangkoran** [expo/expo-cli#4163]
### Summary

I followed the direction to use `expo` with RN 0.66.x given in https://github.com/expo/expo/pull/15914#issuecomment-1018514039. My project is Android-only. When I'm trying to run `npx install-expo-modules`, I got the error about iOS deployment target even though my project is Android only. 

### Environment

```
❯ expo diagnostics

  Expo CLI 5.0.3 environment info:
    System:
      OS: Linux 5.15 Arch Linux
      Shell: 3.3.1 - /bin/fish
    Binaries:
      Node: 14.18.1 - ~/.local/share/nvm/v14.18.1/bin/node
      Yarn: 1.22.17 - ~/.local/share/nvm/v14.18.1/bin/yarn
      npm: 8.3.2 - /usr/sbin/npm
    SDKs:
      Android SDK:
        API Levels: 29, 30
        Build Tools: 29.0.2, 30.0.2
    npmPackages:
      expo: ^44.0.0 => 44.0.1
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: bare
```

### Please specify your device/emulator/simulator platform, model and version

WSA v.1.8.32836.0

### Error output

__This is what I get in my personal project__
```bash
❯ npx install-expo-modules
✔ Expo modules minimum iOS requirement is 12.0. This tool will change your iOS deployment target to 12.0. Do you want to continue? … yes
› Updating your project...
Uncaught Error [Error: [ios.dangerous]: withIosDangerousBaseMod: ENOENT: no such file or directory, open '/home/mangkoran/repos/crowdfinder-client/ios/Podfile'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/mangkoran/repos/crowdfinder-client/ios/Podfile'
}
```

### Reproducible demo or steps to reproduce from a blank project

I am not sure that I can provide reproducible demo like what I encountered in my project. But as my project is Android-only, I think deleting the `ios` directory is enough.

Steps:
1. `npx react-native init RN066 --version 0.66`
2. `cd RN066`
3. `rm -rf ios`
4. `npx install-expo-modules`

Edit: It gave the similar error message as what I encountered in my personal project.

**Comment by Kudo** [comment]
hi there! `install-expo-modules` is designed for default react-native project. i'm sorry we doesn't support too much customization there, so removing `ios` folder is not supported. if the automatic installation doesn't work for you, you can still use the [manual installation](https://docs.expo.dev/bare/installing-expo-modules/#configuration-for-android)

**Comment by mangkoran** [comment]
Alright then. That's not what I actually want tho. How do I use `expo` that RN 0.66.4 compatible?

**Comment by Kudo** [comment]
`expo` 44.0.5 should be compatible with react-native 0.66.4. you can try the [manual installation](https://docs.expo.dev/bare/installing-expo-modules/#configuration-for-android) with your existing react-native 0.66.4 project.

**Comment by mangkoran** [comment]
@Kudo I got this error:
```

Logs for your project will appear below. Press Ctrl+C to exit.
› Opening on Android...
› Opening exp+crowdfinder-client://expo-development-client/?url=http%3A%2F%2F172.19.123.211%3A8081 on Subsystem_for_Android_TM_
› Press ? │ show all commands
Warning: Invalid version react-native@0.66.4 for expo sdkVersion 44.0.0. Use react-native@0.64.3
Warning: Invalid version react-native@0.66.4 for expo sdkVersion 44.0.0. Use react-native@0.64.3
Android Bundling complete 18381ms
Android Bundling complete 50ms
Error: ENOENT: no such file or directory, open '/home/mangkoran/repos/crowdfinder-client/http:/172.19.123.211:8081/index.bundle?platform=android&dev=true&minify=false&app=com.crowdfinder.app&modulesOnly=false&runModule=true'
```
`npm list expo`:
```
❯ npm list expo
crowdfinder-client@1.0.0 /home/mangkoran/repos/crowdfinder-client
├─┬ expo-dev-client@0.8.0
│ ├─┬ expo-dev-launcher@0.10.0
│ │ └── expo@44.0.5 deduped
│ ├─┬ expo-dev-menu-interface@0.5.0
│ │ └── expo@44.0.5 deduped
│ ├─┬ expo-dev-menu@0.9.0
│ │ └── expo@44.0.5 deduped
│ ├─┬ expo-updates-interface@0.5.0
│ │ └── expo@44.0.5 deduped
│ └── expo@44.0.5 deduped
├─┬ expo-splash-screen@0.14.1
│ └── expo@44.0.5 deduped
└─┬ expo@44.0.5
  ├─┬ expo-application@4.0.1
  │ └── expo@44.0.5 deduped
  ├─┬ expo-constants@13.0.0
  │ └── expo@44.0.5 deduped
  ├─┬ expo-error-recovery@3.0.4
  │ └── expo@44.0.5 deduped
  ├─┬ expo-file-system@13.1.0
  │ └── expo@44.0.5 deduped
  ├─┬ expo-font@10.0.4
  │ └── expo@44.0.5 deduped
  └─┬ expo-keep-awake@10.0.1
    └── expo@44.0.5 deduped
```

**Comment by Kudo** [comment]
if you could provide a git repo to minimal reproducible example. that would be helpful for troubleshooting.

i tried the following steps for react-native 0.66 and it works for me.

```sh
$ npx react-native init RN066 --version 0.66
$ npx install-expo-modules
$ expo install expo-dev-client

# manually patch node_modules/expo-dev-launcher/android/build.gradle to add this: https://github.com/expo/expo/blob/d2174859d64a146f410ddfc24fddb30048092ea8/packages/expo-dev-launcher/android/build.gradle#L163-L188

$ expo run:android
```

**Comment by mangkoran** [comment]
You are using `npx install-expo-modules`. Like I said before, I cannot use `npx install-expo-modules`. Have you tried installing manually using `npm i expo`?

**Comment by mangkoran** [comment]
Hmm after looking at `npm list expo-file-system`, the version that `expo` 44.0.5 depends on is still `expo-file-system@13.1.0`. I think its best to bump the dependencies too.
