### ISSUE TITLE
Running yarn ios can't find Simulator on fresh installation (macOS Monterrey)

### ISSUE THREAD

**Issue by meerita** [expo/expo-cli#4168]
### Summary

I have the latest XCode installed, also command-line tools working, launching the fresh project or any other will throw error, that cannot find iOS Simulator.

### Environment

```
Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      Yarn: 1.22.17 - ~/.yarn/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

Version 13.2 (972.2) SimulatorKit 613.1 CoreSimulator 783.5

### Error output

```
$ expo start --ios
Starting project at /Users/myuser/Sites/tikitaka
Developer tools running on http://localhost:19002
Starting Metro Bundler
✔ Xcode needs to be installed (don't worry, you won't have to use it), would you like to continue to the App Store? … no
Unable to verify Xcode and Simulator installation.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
``` 

### Reproducible demo or steps to reproduce from a blank project

On macOS Monterrey:

- Install expo
- Create a fresh project
- Run yarn ios

**Comment by meerita** [comment]
I have found the problem: my installation of XCode didn't have the command line tools selected in the preferences. You can solve this problem by opening XCode and go to Preferences > Locations > Command Line Tools.

It will require authentication. Close your terminal, open it again and yarn ios will work.

**Comment by albert-dias** [comment]
I ran this command in terminal and it worked for me  

sudo xcode-select -s /Applications/Xcode.app
