### ISSUE TITLE
Expo Eject creates broken project

### ISSUE THREAD

**Issue by silviasecco** [expo/expo-cli#4186]
### Summary

After upgrading an expo managed project to the latest version, I ejected it. After ejection I tried to run expo run:android (I had to add to the package.json "expo":"expo" in the scripts section otherwise it wouldn't run, but that isn't the point).

When ejected I have this persistent error (even after upgrading react native navigation)

Caused by: org.gradle.api.UnknownProjectException: Project with path ':unimodules-font-interface' could not be found in project ':expo-font'.

I tried changing version for unimodules-font-interface and other modules suspecting it might have to do with versions of the tools. Unfortunately I'm not comfortable in android studio/gradle, so I'm not sure if this is a bug or not.

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 26, 27, 28, 29
        Build Tools: 28.0.3, 29.0.2, 30.0.2
        System Images: android-18 | Intel x86 Atom, android-18 | Google APIs Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8092744
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 9.0.2 => 9.0.2
      expo: ^44.0.0 => 44.0.6
      react: 16.13.1 => 16.13.1
      react-dom: 17.0.1 => 17.0.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: 0.17.1 => 0.17.1
      react-navigation: ^4.3.9 => 4.4.3
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

Android Studio BumbleBee, Mac OS Monterey

### Error output

➜  irideweb2-iridewebapp git:(develop) ✗ EXPO_DEBUG=true expo run:android
/Users/silviasecco/Library/Android/sdk/platform-tools/adb devices -l
/Users/silviasecco/Library/Android/sdk/platform-tools/adb -s emulator-5554 emu avd name
/Users/silviasecco/Library/Android/sdk/platform-tools/adb devices -l
/Users/silviasecco/Library/Android/sdk/platform-tools/adb -s emulator-5554 emu avd name
Found Application ID in Gradle: it.tecsis.irideweb.omceova
› Building app...
  /Users/silviasecco/Documents/Projects/irideWeb_copy_for_android/irideweb2-iridewebapp/android/gradlew app:assembleDebug -x lint -x test --configure-on-demand -PreactNativeDevServerPort=8081 -PreactNativeDevServerPort=8081
Configuration on demand is an incubating feature.

> Configure project :app

Installing unimodules:
 unimodules-core@7.1.2 from /Users/silviasecco/Documents/Projects/irideWeb_copy_for_android/irideweb2-iridewebapp/node_modules/react-native-unimodules/node_modules/@unimodules/core
 unimodules-react-native-adapter@6.3.9 from /Users/silviasecco/Documents/Projects/irideWeb_copy_for_android/irideweb2-iridewebapp/node_modules/@unimodules/react-native-adapter
 expo-splash-screen@0.14.2 from /Users/silviasecco/Documents/Projects/irideWeb_copy_for_android/irideweb2-iridewebapp/node_modules/expo-app-loading/node_modules/expo-splash-screen
 expo-application@4.0.2 from /Users/silviasecco/Documents/Projects/irideWeb_copy_for_android/irideweb2-iridewebapp/node_modules/expo-application
 expo-constants@13.0.2 from /Users/silviasecco/Documents/Projects/irideWeb_copy_for_android/irideweb2-iridewebapp/node_modules/expo-constants
 expo-error-recovery@3.0.5 from /Users/silviasecco/Documents/Projects/irideWeb_copy_for_android/irideweb2-iridewebapp/node_modules/expo-error-recovery
 expo-file-system@13.1.3 from /Users/silviasecco/Documents/Projects/irideWeb_copy_for_android/irideweb2-iridewebapp/node_modules/expo-file-system
 expo-font@10.0.5 from /Users/silviasecco/Documents/Projects/irideWeb_copy_for_android/irideweb2-iridewebapp/node_modules/expo/node_modules/expo-font
 expo-image-loader@2.2.0 from /Users/silviasecco/Documents/Projects/irideWeb_copy_for_android/irideweb2-iridewebapp/node_modules/expo-image-loader
 expo-intent-launcher@10.1.2 from /Users/silviasecco/Documents/Projects/irideWeb_copy_for_android/irideweb2-iridewebapp/node_modules/expo-intent-launcher
 expo-keep-awake@10.0.2 from /Users/silviasecco/Documents/Projects/irideWeb_copy_for_android/irideweb2-iridewebapp/node_modules/expo-keep-awake
 expo-linear-gradient@8.4.0 from /Users/silviasecco/Documents/Projects/irideWeb_copy_for_android/irideweb2-iridewebapp/node_modules/expo-linear-gradient
 expo-local-authentication@12.1.1 from /Users/silviasecco/Documents/Projects/irideWeb_copy_for_android/irideweb2-iridewebapp/node_modules/expo-local-authentication
 expo-modules-core@0.6.5 from /Users/silviasecco/Documents/Projects/irideWeb_copy_for_android/irideweb2-iridewebapp/node_modules/expo/node_modules/expo-modules-core
 unimodules-task-manager-interface@7.1.1 from /Users/silviasecco/Documents/Projects/irideWeb_copy_for_android/irideweb2-iridewebapp/node_modules/expo-notifications/node_modules/unimodules-task-manager-interface
 expo-notifications@0.14.1 from /Users/silviasecco/Documents/Projects/irideWeb_copy_for_android/irideweb2-iridewebapp/node_modules/expo-notifications
 expo-secure-store@11.1.1 from /Users/silviasecco/Documents/Projects/irideWeb_copy_for_android/irideweb2-iridewebapp/node_modules/expo-secure-store
 expo-sharing@10.1.1 from /Users/silviasecco/Documents/Projects/irideWeb_copy_for_android/irideweb2-iridewebapp/node_modules/expo-sharing
 expo-structured-headers@1.1.1 from /Users/silviasecco/Documents/Projects/irideWeb_copy_for_android/irideweb2-iridewebapp/node_modules/expo-structured-headers
 expo-updates-interface@0.2.2 from /Users/silviasecco/Documents/Projects/irideWeb_copy_for_android/irideweb2-iridewebapp/node_modules/expo-updates-interface
 expo-updates@0.8.5 from /Users/silviasecco/Documents/Projects/irideWeb_copy_for_android/irideweb2-iridewebapp/node_modules/expo-updates
 unimodules-app-loader@2.2.0 from /Users/silviasecco/Documents/Projects/irideWeb_copy_for_android/irideweb2-iridewebapp/node_modules/unimodules-app-loader
 unimodules-font-interface@5.4.0 from /Users/silviasecco/Documents/Projects/irideWeb_copy_for_android/irideweb2-iridewebapp/node_modules/unimodules-font-interface

Found some duplicated unimodule packages. Installed the ones with the highest version number.
Make sure following dependencies of your project are resolving to one specific version:
 expo-splash-screen, expo-font, expo-modules-core, unimodules-core, expo-constants, expo-file-system, unimodules-task-manager-interface

> Configure project :expo
Error: Autolinking is not set up in `settings.gradle`: expo modules won't be autolinked.

> Configure project :expo-file-system
WARNING: Configuration 'testApi' is obsolete and has been replaced with 'testImplementation'.
It will be removed in version 5.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.

> Configure project :expo-structured-headers
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/silviasecco/Documents/Projects/irideWeb_copy_for_android/irideweb2-iridewebapp/node_modules/react-native-navigation/lib/android/app/build.gradle' line: 4

* What went wrong:
A problem occurred evaluating project ':react-native-navigation'.
> Plugin with id 'kotlin-android' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-navigation'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 19s
/Users/silviasecco/Documents/Projects/irideWeb_copy_for_android/irideweb2-iridewebapp/android/gradlew exited with non-zero code: 1
Error: /Users/silviasecco/Documents/Projects/irideWeb_copy_for_android/irideweb2-iridewebapp/android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/silviasecco/.nvm/versions/node/v14.5.0/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:421:26)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
    ...
    at spawnAsync (/Users/silviasecco/.nvm/versions/node/v14.5.0/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnGradleAsync (/Users/silviasecco/.nvm/versions/node/v14.5.0/lib/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:83:18)
    at assembleAsync (/Users/silviasecco/.nvm/versions/node/v14.5.0/lib/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:57:16)
    at actionAsync (/Users/silviasecco/.nvm/versions/node/v14.5.0/lib/node_modules/expo-cli/src/commands/run/android/runAndroid.ts:143:9)

### Reproducible demo or steps to reproduce from a blank project

This happens starting from an existing project only, unfortunately this doesn't happen on a clean setup :(

**Comment by brentvatne** [comment]
happy to help if you can share a reproducible example! https://stackoverflow.com/help/minimal-reproducible-example

**Comment by silviasecco** [comment]
I have created a minimal reproducible example by starting an expo app and then embedding my package.json from the other application.
[my-expo-app.zip](https://github.com/expo/expo-cli/files/8008149/my-expo-app.zip)

The error is different but somewhat related in my opinion

<img width="1228" alt="CleanShot 2022-02-05 at 15 18 08@2x" src="https://user-images.githubusercontent.com/6431216/152645574-cb813171-d7cf-42d7-bdbf-86db0805d434.png">
