### ISSUE TITLE
Cannot install CocoaPods after running  expo prebuild --clean 

### ISSUE THREAD

**Issue by jasuno** [expo/expo-cli#4190]
### Summary

I have been trying to get my environment set up to use react-native-firebase, per the instructions, I made the necessary changes and then ran `expo prebuild --clean ` but when it gets to the pod install portions it errors out saying 

`[!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
  In Podfile:
    EXFirebaseAnalytics (from `../node_modules/expo-firebase-analytics/ios`) was resolved to 6.0.1, which depends on
      Firebase/Core (= 7.7.0) was resolved to 7.7.0, which depends on
        Firebase/CoreOnly (= 7.7.0)

    RNFBApp (from `../node_modules/@react-native-firebase/app`) was resolved to 14.3.0, which depends on
      Firebase/CoreOnly (= 8.11.0)

CocoaPods could not find compatible versions for pod "GoogleMaps":
  In Podfile:
    react-native-google-maps (from `/Users/jasonmatthews/Documents/atlantaDark/node_modules/react-native-maps`) was resolved to 0.29.4, which depends on
      Google-Maps-iOS-Utils (= 2.1.0) was resolved to 2.1.0, which depends on
        GoogleMaps

    react-native-google-maps (from `/Users/jasonmatthews/Documents/atlantaDark/node_modules/react-native-maps`) was resolved to 0.29.4, which depends on
      GoogleMaps (= 3.5.0)`

### Environment

 Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.10.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.24.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8005941
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

Ios simulator iphone 11 pro 

### Reproducible demo or steps to reproduce from a blank project

Not sure

**Comment by EvanBacon** [comment]
If you're trying to use `react-native-firebase` then you should probably uninstall `expo-firebase` packages. It appears that conflicting versions of Firebase are being installed. You can also try running `pod repo update` to fix version collisions.
