### ISSUE TITLE
IOS: Stuck on splash screen when running "expo start" works with "expo run:ios"

### ISSUE THREAD

**Issue by fermmm** [expo/expo-cli#4191]
### Summary

I have an app in bare workflow that I built for Android and now I'm trying to make it run on IOS using a MacBook Air M1. When I run `expo run:ios` my app runs perfectly on the Iphone simulator, also works when I run `npx react-native run-ios`. Now I want to run the app on a physical device using `expo start` but in this case my app opens but is stuck on the app splash screen, the same happens in the simulator when I press the i key to open simulator. It seems that `expo start` can't start my app for some reason.

I added a console.log in the App.tsx and is not called, also there is nothing in the console as you can see in the following screenshot (my app's splash is just a color gradient):

<img width="1439" alt="Captura de Pantalla 2022-02-05 a la(s) 19 15 46" src="https://user-images.githubusercontent.com/3660373/152660785-e8a131ce-f9c2-4858-8c70-ee545066704a.png">

How can I get more information about what is happening? I want to make a better bug report than this.

### Environment

Expo CLI 5.0.3 environment info:
```
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
      Yarn: 1.22.15 - ~/.nvm/versions/node/v16.13.2/bin/yarn
      npm: 8.3.1 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 8.5.1 => 8.5.1 
      expo: ^43.0.0 => 43.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: bare
```

### Please specify your device/emulator/simulator platform, model and version

Simulator: Iphone 12 - IOS 15.2

### Reproducible demo or steps to reproduce from a blank project

1. Download the demo: https://drive.google.com/drive/folders/1-16dBEGmHfM9k1lwnQSUTG_XVLY17OSH?usp=sharing
2. Run `npm install`
3. Run `brew install cocoapods` if you don't have cocoapods installed
4. Run `npx pod-install`
5. Run `expo start` and open the app in a simulator

**Comment by oqnunes** [comment]
Same problem here!

**Comment by EvanBacon** [comment]
Correct me if I'm wrong, are you running `expo start` then attempting to open the project in the Expo Go app? If you're trying to use a custom development build, then you should be using `expo start --dev-client` as this starts the dev server on port 8081 (default in React Native).

**Comment by fermmm** [comment]
> Correct me if I'm wrong, are you running `expo start` then attempting to open the project in the Expo Go app? If you're trying to use a custom development build, then you should be using `expo start --dev-client` as this starts the dev server on port 8081 (default in React Native).

I'm trying to run the app in Expo Go, please follow the instructions I provided to reproduce the issue.

**Comment by fermmm** [comment]
> @fermmm in the Expo Go app, do you have Remote Debugging turned on or off in the dev menu?
> 

No remote debugging is disabled in my project because turbo modules are enabled, that is what the menu says.
I'm slowly replacing expo modules like expo-facebook because of errors that does not contain useful information and unexpected issues in general. In general it seems to me that expo contains bad quality code, I don't recommend expo anymore, the only good experience I had with expo is eas build and push notifications. Also this issue contains steps to reproduce the problem and the only response from expo team shows that they didn't look at it, I think they don't care.

**Comment by AlanSl** [comment]
Yeah Expo is absolutely riddled `try {} catch {}` blocks where the error is discarded even though it'll cause the build to fail. It's really bad.

If you're still experiencing the issue posted, it might be possible to brute-force it by temporarily disabling turbomodules and elements that depend on it then using the remote debugger with "Pause at caught errors" enabled (that is of course assuming the problem isn't with turbomodules itself... but at least that'd narrow it down). If there's any way of getting the remote debugger working, even temporarily, it's the best way to get an idea of what's happening in all the swallowed silent errors.

Otherwise, the only effective way I've found to debug Expo is to guess where in the Expo process the problem might be then hack dozens of console statements into the expo JS inside `node_modules/@expo`... 😬
