### ISSUE TITLE
expo run:ios stuck on: Executing react-native Pods/FBReactNativeSpec » [CP-User] Generate Specs

### ISSUE THREAD

**Issue by Seabird22** [expo/expo-cli#4192]
### Summary

I am fairly new to React Native, so forgive my ignorance.  When trying to prebuild with "expo run:ios" the build hangs on the following statement: 

**_Executing react-native Pods/FBReactNativeSpec » [CP-User] Generate Specs._**

There is also a warning that says: 

**Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the /projectname/ editor**

I have node version 16.13.2  and nvm 0.39.1

I tried to build after running: expo install expo-dev-client on my existing project (because I would like to include react-native-firebase), but on a brand new blank Typescript project the build hangs exactly at the same place, so that is apparently not the issue.  
I tried to uninstall and install again: node / nvm / yarn but to no avail..    Do I need to do something with XCode or to have apple developer account setup ??    

Hope someone here can shed a light upon what the problem might be.

### Environment

 Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8139111
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

Mac osx xcode simulator

### Reproducible demo or steps to reproduce from a blank project

expo run:ios

**Comment by EvanBacon** [comment]
These warnings and behaviors come from the Xcode build, perhaps try confirming that the project builds as expected from Xcode.

You can see the xcodebuild logs in the `.expo` project folder to get better insight into what is going on. My guess is that the step is taking up too many resources and xcodebuild comes to a halt.

If you run `EXPO_DEBUG=1 expo run:ios` you'll see the exact `xcodebuild` command that is used to generate the project, you can also try running this command directly to bisect the issue.

**Comment by muffinman987** [comment]
when I run npx expo run:ios it gets stuck on "Planning build". I tried restarting my computer, updated expo, cleared bundler cache, but nothing seems to work. any advice?

**Comment by MaiconLeffa** [comment]
> when I run npx expo run:ios it gets stuck on "Planning build". I tried restarting my computer, updated expo, cleared bundler cache, but nothing seems to work. any advice?

I had the same issue in macos and the problem was permission of my project folder.
