### ISSUE TITLE
expo publish very slow after every computer restart

### ISSUE THREAD

**Issue by konstantinlois** [expo/expo-cli#4194]
### Summary

Thanks for taking the time to look into this.

Since I've switched from a Windows machine to a Mac, `expo publish` and `expo start` became very slow (7-15 minutes) after every restart of the Mac. Once the commands have been run once, subsequent executions run much faster (around 20 seconds), but as soon as I restart the Mac it is back to 7-15 minutes. Maybe this has something to do with the caching mechanism?

Thanks in advance.

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.2 - /usr/local/bin/node
      npm: 8.1.2 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~0.16.2 => 0.16.16 
      expo: ^44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.45.1
      expo-cli: 5.0.3
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

MacBook Air (13'', early 2015)

### Reproducible demo or steps to reproduce from a blank project

1. create a blank project on a MacBook Air (can only test for 2015 model)
2. run `expo start` or `expo publish` (especially `expo publish`)

The commands, will take their time (7-15 minutes)

3. run `expo start` or `expo publish` again

This time the commands will be quick (20 seconds).

4. restart Mac
5. run `expo start` or `expo publish` again

The commands will again take around 7-15 minutes

**Comment by EvanBacon** [comment]
7-15 minutes is a very long time to bundle a fresh project. You could run `DEBUG=* expo export` to peek inside the Metro logs and see what's going on.

I cannot repro this issue locally but it may be do to the power of your local machine.

Another very real possibility is just that Metro (Facebook default bundler for React Native) is a very slow bundler. Metro relies heavily on caching for speed and most of the caches are written to the tmp directory on mac. On mac computers, the tmp directory is cleared when the computer is restarted, this means you'll feel the entire bundling process every time. You can sort of emulate this behavior by doing `expo export --clear` which deletes the main Metro cache before bundling.

Other bundlers in the web ecosystem are turning to native languages like Rust and Go, whereas the long term strategy of Metro is to add more caching to mitigate slowness.


Regardless, a fresh build should only take about a minute on a clean cache so perhaps there are other factors involved.

**Comment by konstantinlois** [comment]
Hi Evan,

thank you for the detailed answer! I am always amazed by how much you guys care about every single issue.

In the meantime I've turned to just not fully shutting down the Mac every time. This works for me as I'm using `expo publish` only every now and then anyway. Just wanted to know if there was a simple little thing I was missing. But as you said, the reason just seems to be a mixture of the Metro caching system on Mac and the relatively low performance of my machine.

Thanks again. 

This can be closed then.
