### ISSUE TITLE
expo run:android fails due to unrecognized VM option

### ISSUE THREAD

**Issue by jakeorbtl** [expo/expo-cli#4196]
### Summary

After running `expo run:android`, the build fails and gives the error:

`Unrecognized VM option 'MaxPermSize=512m'`
`Error: Could not create the Java Virtual Machine.`
`Error: A fatal exception has occurred. Program will exit.`

For some reason though, running `expo run:ios` works fine, and then pressing `a` while in the metro bundler cli successfully bundles for android and runs the app in the emulator. I really don't know what is causing this since I followed all of the setup instructions that I could find in expo's documentation.

Also, I apologize if the error is on my side, but I have been troubleshooting for a week with no success, and I don't know where else to go.

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      npm: 8.1.2 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.46.0
      expo-cli: 5.0.3
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

Pixel XL API 30

### Error output

% EXPO_DEBUG=true expo run:android
adb devices -l
adb -s emulator-5554 emu avd name
adb devices -l
adb -s emulator-5554 emu avd name
Found Application ID in Gradle: com.chukkertv.android
› Building app...
  /Users/username/Projects/chukkertv/chukkertv-mobile/android/gradlew app:assembleDebug -x lint -x test --configure-on-demand -PreactNativeDevServerPort=8081 -PreactNativeDevServerPort=8081
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/6.9/userguide/gradle_daemon.html
Process command line: /Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home/bin/java -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED -Xmx2048m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /Users/username/.gradle/wrapper/dists/gradle-6.9-all/dooywd8nv05k16orzxge2b1bs/gradle-6.9/lib/gradle-launcher-6.9.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.9
Please read the following process output to find out more:
-----------------------
Unrecognized VM option 'MaxPermSize=512m'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
/Users/username/Projects/chukkertv/chukkertv-mobile/android/gradlew exited with non-zero code: 1
Error: /Users/username/Projects/chukkertv/chukkertv-mobile/android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (node:events:510:26)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
    ...
    at spawnAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnGradleAsync (/usr/local/lib/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:83:18)
    at assembleAsync (/usr/local/lib/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:57:16)
    at actionAsync (/usr/local/lib/node_modules/expo-cli/src/commands/run/android/runAndroid.ts:143:9)

### Reproducible demo or steps to reproduce from a blank project

I don't know if this will be reproducible on a different machine, as I'm sure the error is being cause by the way I installed my dependencies or where they are located or something of that nature, but following these steps reproduces the error for me:

1)
    `expo init new-project`
    `✔ Choose a template: › blank (TypeScript)  same as blank but with TypeScript configuration`
    
    `cd new-project`

2)
    Open up android emulator

3)
    `expo run:android`
    `✔ What would you like your Android package name to be? … com.username.newproject`
    
    (this gives me the error again)

Now let's try to run an ios simulator then open android from metro cli.

4)
    `expo run:ios`
    `✔ What would you like your iOS bundle identifier to be? … com.username.newproject`

5)
    Once the build succeeds and the app launches in an ios simulator, go to the metro bundler cli and press the `a` key

Well, upon trying to reproduce this part, I got a different outcome. Instead of the android app starting up as expected, I received a new error, so hopefully this might provide some insight:
`› Opening on Android...`
`› Opening com.username.newproject://expo-development-client/?url=http%3A%2F%2F10.1.10.239%3A8081 on Pixel_XL_API_30`
`Couldn't start project on Android: Error running adb: The development client (com.username.newproject) for this project is not installed. Please build and install the client on the device first.
Learn more: https://docs.expo.dev/clients/distribution-for-android/`

The link brings me to a page that informs me to use the `expo run:android` command to start an android dev build, or to use the eas cli, which I have already tried unsuccessfully in the past, hence I am now trying to build locally. (As an aside, the issue I had with eas was unrelated to this one. The android build was successful but I was getting a build error for ios 🙃)

**Comment by kbrandwijk** [comment]
You seem to be using JDK version 17. The option `MaxPermSize=size` was marked as obsolete in JDK version 16, and removed in JDK 17 (https://docs.oracle.com/en/java/javase/17/docs/specs/man/java.html#removed-java-options).

If you look at the build server infrastructure details for Android here: https://docs.expo.dev/build-reference/infrastructure/#android-build-server-configurations, you'll notice that the default image uses Java 8, and the latest image uses Java 11.

For building locally, I would advise you to stick to Java 8 for now. You can use a tool like jEnv (https://www.jenv.be/) to easily switch between multiple installed Java versions.

**Comment by jakeorbtl** [comment]
That would definitely be the issue.

I had noticed that `MaxPermSize` was deprecated in my JDK version, but I couldn't wrap my head around why expo would use a deprecated VM option.  I'm not used to using JDK, but I looked it up and found out that JDK 8 & 11 are the two most recent JDK versions with long term support, while JDK 17 is still brand new, so it makes sense why my build failed.

I just assumed using an older version of JDK would be a bad idea, but I suppose it's actually common practice. Thank you for your help!

**Comment by joranb** [comment]
JDK 17 is the latest LTS release. Not supporting the latest LTS is definetly something that you should look into. MaxPermSize has been deprecated a while, it was actually removed completely in JDK 17. This issue should not be marked as solved, as it really is not. The use of JDK 17 LTS will only increase in the time coming so this issue will impact more and more users.

**Comment by ildaneta** [comment]
To resolve this problem I had to download the JDK 11 and turn it my main jdk, uninstalling the JDK 17

To dowload JDK 11: 
https://www.oracle.com/java/technologies/downloads/#java11

To know how is your main JDK, you have to run it into your terminal:
` /usr/libexec/java_home`

**Comment by Brenndoerfer** [comment]
I can confirm that downgrading to JDK 11 solves the problem. If you are using brew

```
brew install java11

# to simlink it correctly, in my case the autoinstaller didn't set it up
sudo ln -sfn $(brew --prefix)/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk
```

**Comment by joranb** [comment]
I got around this temporary by removing -XX:MaxPermSize=512m from org.gradle.jvmargs in gradle.properties.

**Comment by AnatuGreen** [comment]
I am having this same issue but on Windows. How do I downgrade the JDK?

**Comment by AnatuGreen** [comment]
> I am having this same issue but on Windows. How do I downgrade the JDK?

I am having this same issue but on Windows. How do I downgrade the JDK?

**Comment by Ad1tyaV** [comment]
@AnatuGreen 
Install an older jdk, like jdk-11 - https://www.oracle.com/java/technologies/javase/jdk11-archive-downloads.html

goto your project terminal and run this command before starting your app
`SET JAVA_HOME=C:\Program Files\Java\jdk-11.0.16.1`

1. note that there's no \bin suffixed at the end.
2. Also you need to run the above command each time you open a new terminal if you want to run the app.

**Comment by tedwong** [comment]
@joranb  May I know how do u find this file?

**Comment by joranb** [comment]
@tedwong You'll find it in the android folder. If you have ejected and use the bare workflow that is.
