### ISSUE TITLE
postPublish hook broken for sentry-expo/upload-sourcemaps

### ISSUE THREAD

**Issue by tomodian** [expo/expo-cli#42]
Hi, I just updated to `expo-cli` from `exp` and seeing this error.

#### `app.json` (excerpt, unchanged since using `exp`)

```
{
  "expo": {
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "myapp",
            "project": "mobile",
            "authToken": "sometoken"
          }
        }
      ]
    }
  }
}
```

Please note that the file exists in `./node_modules/sentry-expo/upload-sourcemaps.js`.

#### Error

This is the error when try to publish my app.

```
[20:28:28] Unable to load postPublishHook: 'sentry-expo/upload-sourcemaps'
[20:28:28] Please fix your postPublish hook configuration.
```

It would be great to hear how could I get Sentry back to the streamline.

**Comment by bsoung** [comment]
I am getting this error as well.

**Comment by brucedesa** [comment]
Same here

`[20:41:07] Unable to load postPublishHook: 'sentry-expo/upload-sourcemaps'. The module does not export a function.
[20:41:08] Please fix your postPublish hook configuration.
`

**Comment by bsoung** [comment]
I switched back to the old exp cli, built fine and everything worked great.

**Comment by dmydry** [comment]
Have the same issue:
```
...
Error uploading sourcemaps to Sentry
response status: 404
error: running update nagger
skipping update nagger because session is not attended
error: project not found
...
```

**Comment by antgel** [comment]
I see the same "project not found" error as @dmydry . Is it possible that there are two issues, or is our configuration broken?

**Comment by antgel** [comment]
@dmydry Our configuration is / was broken. In my case, `organization` wasn't the same as my Sentry organization name. This is [documented](https://docs.expo.io/versions/latest/guides/using-sentry/).
