### ISSUE TITLE
Expo 5.1.1 watchman error

### ISSUE THREAD

**Issue by kav** [expo/expo-cli#4200]
### Summary

running an expo managed application via `expo start --dev-client` with the new 5.1.1 update on MacOS 12.2 results in this error:

> Recrawled this watch 1 times, most recently because:
> MustScanSubDirs UserDroppedTo resolve, please review the information on
> https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
> To clear this warning, run:
> `watchman watch-del '<project dir>' ; watchman watch-project '<project dir>'`

I'd drop the watchman log but I'm not sure how to trigger it in this case but happy to help if anyone has tips on digging that up.

### Environment

Expo CLI 5.1.1 environment info:
    System:
      OS: macOS 12.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
      Watchman: 2022.01.31.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.40.0
      expo-cli: 4.13.0
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

N/A

### Error output

EXPO_DEBUG=true expo start --dev-client
Starting project at <project dir>
Developer tools running on http://localhost:19002

Expo Metro config:
- Bundler target: bare
- Legacy: false
- Extensions: ts, tsx, js, jsx, json
- React Native: <project dir>/node_modules/react-native
- Babel config: <project dir>/babel.config.js
- Resolver Fields: react-native, browser, main
- Exotic: false

Starting Metro Bundler
watchman warning:  Recrawled this watch 1 times, most recently because:
MustScanSubDirs UserDroppedTo resolve, please review the information on
https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
To clear this warning, run:
`watchman watch-del '<project dir>' ; watchman watch-project '<project dir>'`

Recrawled this watch 1 times, most recently because:
MustScanSubDirs UserDroppedTo resolve, please review the information on
https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
To clear this warning, run:
`watchman watch-del '<project dir>' ; watchman watch-project '<project dir>'`

### Reproducible demo or steps to reproduce from a blank project

Doesn't reproduce in a new project but I think that might be a file count thing? Happy to test moving folders around to repro but log hunting seems more likely fruitful

**Comment by brentvatne** [comment]
did you try running `watchman watch-del-all`? this seems to be the suggested workaround on https://github.com/facebook/watchman/issues/981. in general i think that issue is better suited for this discussion so i'll close this one.

**Comment by kav** [comment]
The suggested `watchman watch-del '<project dir>'` but `watchman watch-del-all` resolved the issue. Thanks!
