### ISSUE TITLE
Init project name validations accept "expo1" which is then sanitized to "expo" and project will not run

### ISSUE THREAD

**Issue by iboxgithub** [expo/expo-cli#4203]
### Summary

with this one I can't even launch expo, I don;t know why, it's a simple 
```
expo init
yarn start
```
<img width="800" alt="Screen Shot 2022-02-10 at 18 05 25" src="https://user-images.githubusercontent.com/5391993/153469292-772e475d-117c-4197-b8d2-64d478f66361.png">

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Environment

WARNING: expo-cli has not yet been tested against Node.js v17.4.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <13.0.0 (Maintenance LTS)
* >=14.0.0 <15.0.0 (Active LTS)
* >=15.0.0 <17.0.0 (Current Release)

  Expo CLI 5.1.1 environment info:
    System:
      OS: macOS 12.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 17.4.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.3.1 - /usr/local/bin/npm
      Watchman: 2022.01.31.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8139111
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.1.1
    Expo Workflow: managed

### Reproducible demo

https://github.com/iboxgithub/expo1

**Comment by brentvatne** [comment]
@kbrandwijk - that's a good question! we should double check that

**Comment by iboxgithub** [comment]
I confirm that running:
```
expo init test3 (choose Tabs template)
cd test 3
yarn ios
```
solves the problem. 
Thanks, please let us know when the commit is applied to the last expo-cli version ;)
