### ISSUE TITLE
App Stuck on Splash Screen on Android

### ISSUE THREAD

**Issue by atb-brown** [expo/expo-cli#4206]
### Summary

When I bundle my app to run it on my Android, it gets stuck on the splash screen.

I'm not calling `SplashScreen.preventAuthoHideAsync()`, so [this](https://github.com/expo/fyi/blob/main/splash-screen-hanging.md) doesn't help, 

### Environment

# 📱
Pixel 3a, Android 12
Expo Go v2.23.2

# 💻
Windows 10 Home
Version 20H2
OS build 19042.1526
expo-cli v5.0.3

### Please specify your device/emulator/simulator platform, model and version

Pixel 3a, Android 12

### Error output

Stuck on the splash screen.

![Screenshot](https://user-images.githubusercontent.com/6782887/153501244-e3dd326e-486f-4e96-b612-de0e6cff8735.png)

### Reproducible demo or steps to reproduce from a blank project

https://github.com/atb-brown/expo-issue

## Connect an Android Device

I've tried this with both an Android emulator (via Android Studio) and my own personal Android phone.

## Install/Bundle

1. `yarn install`
2. `yarn android`

**Comment by atb-brown** [comment]
I decided to try and initialize a brand new app using `expo init ...` and that app seems to be running. Not sure if that's helpful or not, but I guess it rules out the possibility of something being wrong with my pc or phone?

**Comment by atb-brown** [comment]
Alright, so it does look like this had something to do with the UUID package resolution. After removing the resolution, my app loads. Here's the yarn.lock difference: https://github.com/atb-brown/expo-issue/commit/c9bcfeff464324e1fafb00473a4cf95ebd519ede#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deL6830-R6840

The reason I did this in the first place is because upon `yarn install` I was seeing this warning:
```
$ yarn install
yarn install v1.22.11
[1/4] Resolving packages...
warning Lockfile has incorrect entry for "uuid@^8.3.0". Ignoring it.
warning Lockfile has incorrect entry for "uuid@^3.4.0". Ignoring it.
warning Lockfile has incorrect entry for "uuid@^3.3.2". Ignoring it.
warning expo > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning expo > expo-constants > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning expo > expo-file-system > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning Lockfile has incorrect entry for "uuid@^8.3.2". Ignoring it.
warning react-native > @react-native-community/cli-platform-ios > xcode > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```

I'm not an expert, so is this warning about uuid a false positive? Is it a different uuid library and yarn is confusing it with a different uuid library? I'm guessing this because the difference between 3.4.0 and 7.x is pretty big.

**Comment by kbrandwijk** [comment]
We'll follow up with updating the uuid dependency in those expo packages that are listed, but it is in fact the same package, and adding a resolution that results in such a big version difference (major version increase indicates potential breaking changes) is, as you have seen, not recommended. I'm considering this specific issue solved as everything is working after you removed it, the follow-up will happen in the expo/expo repo.
