### ISSUE TITLE
Cannot publish the project, error SHA-1 for file AppEntry.js is not computed.

### ISSUE THREAD

**Issue by lvmmth** [expo/expo-cli#421]
## Description

1-2 sentences describing the problem you're having or the feature you'd like to request

## Expected Behavior

The publishing works, then test to open the app via the link.

## Environment

Result of `expo diagnostics`

_Expo CLI 2.11.9 environment info:                                                                   System:                                                                                             OS: Windows 10                                                                                  Binaries:                                                                                           npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD                                                    IDEs:                                                                                               Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842
--_

I run on:
- AzureVM : Windows10
- PC : Windows 7

![expo-publish-failed](https://user-images.githubusercontent.com/30114288/54409668-98376600-471a-11e9-8033-20c41bd80778.png)

**Comment by brentvatne** [comment]
hello! it seems like nobody else has encountered this issue. i'm curious - did it ever go away? did you find the source of the issue?
