### ISSUE TITLE
Issues with switching team IDs

### ISSUE THREAD

**Issue by nmokkenstorm** [expo/expo-cli#4213]
### Summary

As part of transferring an in-house built app to a client I have been made team member in two organisations, but the Expo CLI and EAS Build tool only recognise the former. I got a prompt to switch once, but that also seemed to ignore my wishes. `expo credentials:manager` gives me the old, outdated info, even after removing myself from the former organisation.

### Environment

```
  Expo CLI 5.1.2 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
      Yarn: 1.22.11 - ~/.nvm/versions/node/v15.14.0/bin/yarn
      npm: 7.19.1 - ~/.nvm/versions/node/v15.14.0/bin/npm
      Watchman: 2021.11.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.6
      react: ^17.0.0 => 17.0.1
      react-native: https://github.com/expo/react-native/archive/sdk-44.0.0.tar.gz => 0.64.3
    npmGlobalPackages:
      eas-cli: 0.43.0
      expo-cli: 5.1.2
    Expo Workflow: managed

```

### Please specify your device/emulator/simulator platform, model and version

n/a

### Error output

```
Authentication with Apple Developer Portal failed!
Error: You have no team associated with your Apple account, cannot proceed.
(Do you have a paid Apple Developer account?)
    at promptForTeamAsync (/Users/niels/.nvm/versions/node/v15.14.0/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:1025680)
    at Object.selectTeamAsync (/Users/niels/.nvm/versions/node/v15.14.0/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:1025542)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at Object.validateSessionAsync (/Users/niels/.nvm/versions/node/v15.14.0/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:902823)
    at Object.loginWithUserCredentialsAsync (/Users/niels/.nvm/versions/node/v15.14.0/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:872044)
    at loginWithUserCredentialsAsync (/Users/niels/.nvm/versions/node/v15.14.0/lib/node_modules/expo-cli/src/appleApi/authenticate.ts:133:22)
    at loginAsync (/Users/niels/.nvm/versions/node/v15.14.0/lib/node_modules/expo-cli/src/appleApi/authenticate.ts:92:12)
    at authenticateAsync (/Users/niels/.nvm/versions/node/v15.14.0/lib/node_modules/expo-cli/src/appleApi/authenticate.ts:152:23)
    at Context.ensureAppleCtx (/Users/niels/.nvm/versions/node/v15.14.0/lib/node_modules/expo-cli/src/credentials/context.ts:83:24)
    at generateDistCert (/Users/niels/.nvm/versions/node/v15.14.0/lib/node_modules/expo-cli/src/credentials/views/IosDistCert.ts:425:3)
```

### Reproducible demo or steps to reproduce from a blank project

Build an app in team A, transfer it to team B using the process mandated by Apple, Expo CLI fails to recognise the second team.

**Comment by kbrandwijk** [comment]
Did you update the `owner` field in your `app.json` to point to the new organization?

**Comment by nmokkenstorm** [comment]
> Did you update the `owner` field in your `app.json` to point to the new organization?

I did not, but changing it to the e-mail that is the account holder for the team locks me out of the `eas` process entirely:

```
=eas build -p ios
★ eas-cli@0.47.0 is now available, please upgrade.
Proceeding with outdated version

    AssertionError: You must have access to the [redacted] account to run this command
    Code: ERR_ASSERTION
```

**Comment by nmokkenstorm** [comment]
I ended up logging in under an account that was only in team B, not in team A, no issues reported. I _think_ this is the eas-cli not playing nice with apple authentication.

**Comment by kbrandwijk** [comment]
No, it should not be set to the e-mail of the account holder, `owner` should be set to the organization name (that appears in the settings page for the org on expo.dev (or in the dropdown list of organizations). When switching organizations for your project, Expo will not be able to 'see' to old saved cloud credentials etc. for your app though, so you'll either have to download and reupload that, or go through the steps again.

**Comment by nmokkenstorm** [comment]
> `owner` should be set to the organization name (that appears in the settings page for the org on expo.dev (or in the dropdown list of organizations). When switching organizations for your project, Expo will not be able to 'see'

I was under the impression the authentication for Expo and the one for Apple were separate, is this not the case? I wanted to build my project under the _expo_ credentials as is but upload to a new Apple developer team, are these implicitly coupled?

**Comment by quinlanj** [comment]
As a quick sanity check, could you delete the Apple cookies that are stored and try to authenticate under team B again? In the example below, the Apple cookies are stored at `/Users/quin/.app-store/auth/quin@expo.io/cookie`.

![Screen Shot 2022-03-22 at 1 24 47 AM](https://user-images.githubusercontent.com/6380927/159438472-4e541887-ac68-4fd6-a3fa-a9388a3930a5.png)

**Comment by Santy1422** [comment]
i have this problem
