### ISSUE TITLE
Port settings in packager-info.json not honored but overwritten.

### ISSUE THREAD

**Issue by raarts** [expo/expo-cli#4219]
### Summary

I have a monorepo with multiple expo projects in it. I don't want `expo start` to ask for confirmation when it chooses a different port number (for devtools or web or packager), but preset them to for example 19103, 19101, 19107.

When I tried changing them in packager-info.json my changes are ignored and after `yarn start` the file is reverted.

### Environment

  Expo CLI 5.1.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /opt/homebrew/Cellar/node@16/16.13.1/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.1.2 - /opt/homebrew/Cellar/node@16/16.13.1/bin/npm
      Watchman: 2022.01.17.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: ^17.0.2 => 17.0.2
      react-native: 0.64.3 => 0.64.3
      react-native-web: ^0.17.5 => 0.17.5
    npmGlobalPackages:
      expo-cli: 5.1.3
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

web/ios/android all freshly installed

### Reproducible demo or steps to reproduce from a blank project

This was tried on a freshly install expo, with typescript template and react-native-web and react-dom installed.

**Comment by EvanBacon** [comment]
`packager-info.json` is a generated file that is used by expo-cli to share arguments between the TerminalUI and the dev tools UI (browser UI). Unfortunately, it cannot be reliably used for the purpose you have described as both tools attempt to clear it when the dev server is stopped.

Perhaps you could use the `expo start --port XXX` and `expo start:web --port XXX` arguments to predefine the ports you wish to use.
