### ISSUE TITLE
Cannot open app via QR code.

### ISSUE THREAD

**Issue by lvmmth** [expo/expo-cli#422]
## Description

I run command 

> expo start

And scan QR code which appeared, then get an error code: 500 on red screen.

## Expected Behavior

I want to open my React app as web, android os, ios app.

##Environment

I run on:
PC : Windows 7
Android mobile : version 6.0.1

![scanapperror](https://user-images.githubusercontent.com/30114288/54412280-b0ac7e00-4724-11e9-98df-5cb3ce857017.jpg)

**Comment by thg303** [comment]
please provide the error message which is shown in your terminal.
by the way, make sure your network configuration is set to "tunnel" in the metro bundle web panel.
