### ISSUE TITLE
couldn't initiate a new project

### ISSUE THREAD

**Issue by KarthikSiddarth** [expo/expo-cli#4220]
### Summary

I am trying to initiate a new project on my `Ubuntu` machine using `expo init <app-name>`, it throws error.

### Environment

<img width="559" alt="Screenshot 2022-02-16 at 11 26 22 PM" src="https://user-images.githubusercontent.com/40512676/154326517-545155a5-d57d-403e-ac30-3e820eb1fba4.png">

### Please specify your device/emulator/simulator platform, model and version

Thinkpad/Ubuntu 20.04.3 LTS

### Error output

![error_expo_init](https://user-images.githubusercontent.com/40512676/154327117-2caa302f-df83-4268-9957-1492a10f449c.jpeg)

### Reproducible demo or steps to reproduce from a blank project

- Install latest version of **expo-cli**
- Run `expo init <app-name>`

**Comment by brentvatne** [comment]
it looks like npm isn't working properly on your machine. do you have some npm proxy set up?

expo-template-blank certainly exists on npm: https://www.npmjs.com/package/expo-template-blank
