### ISSUE TITLE
expo client:install:android doesn't install Expo Go, times out

### ISSUE THREAD

**Issue by Elliptica1** [expo/expo-cli#4224]
### Summary

Command to install Expo Go on Android emulator always fails. The emulator launches fine, but nothing happens and finally terminal just times out.

### Environment

  Expo CLI 5.2.0 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 26, 27, 28, 29, 30, 31
        Build Tools: 29.0.2, 29.0.3, 30.0.2, 31.0.0, 32.0.0, 33.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, chromeos-67 | Chrome OS 67
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8139111
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Android, Pixel 4, API 30 (R)

### Error output

![image](https://user-images.githubusercontent.com/24662122/154645495-e5301847-267c-4842-8846-ca8415bda47d.png)

### Reproducible demo or steps to reproduce from a blank project

Step 1: Create new project using `expo init Test0_Blank` 
Step 2: Choose a blank project
Step 3: `cd` into `Test0_Blank`
Step 4: Run `expo client:install:android`

**Comment by Elliptica1** [comment]
Found the reason. The emulator was new, so I had never logged into the Google Play store on it. Once I did that, the command worked. 

Suggest updating the error message or instructions to state that the user must already be logged into the Google Play store (which would not be needed if sideloading the app or something).

**Comment by EvanBacon** [comment]
We run `adb devices -l` on a timer until the device shows up, unfortunately many emulators behave differently and this can lead to edge cases like the one you encountered. There isn't much we can do to mitigate this issue since ADB is currently the most reliable way to interact with Android devices. However, I'm very much open to suggestions and PRs.
