### ISSUE TITLE
Critical vulnerability in @expo/image-utils  Node-fetch 

### ISSUE THREAD

**Issue by pigri** [expo/expo-cli#4230]
Hello expo team! 

Could you update the node-fetch package in the image-utils package, please?

This version includes a high severity security bug. 

https://github.com/advisories/GHSA-r683-j2x4-v87g

https://github.com/expo/expo-cli/blob/main/packages/image-utils/package.json

Reproducible demo or steps to reproduce from a blank project
```yarn audit```

**Comment by EvanBacon** [comment]
Something holding this up has been the drastic size increase https://packagephobia.com/result?p=node-fetch
<img width="838" alt="Screen Shot 2022-04-11 at 3 09 12 PM" src="https://user-images.githubusercontent.com/9664363/162823691-03f44d54-5e4e-4940-b391-b6ca2c3bc56d.png">

Anyone have any recommendations?
