### ISSUE TITLE
Expo doctor should exit with code > 0 if it finds issues

### ISSUE THREAD

**Issue by Jamesking56** [expo/expo-cli#4231]
### Summary

Hi,

We're running `expo doctor` in GitHub Actions to check that a PR doesn't break expo.

We had Renovate upgrade the react-native dependency and `expo doctor` fails with:

```
Warning: Invalid version react-native@0.67.3 for expo sdkVersion 44.0.0. Use react-native@0.64.3
```

However, this does not fail in GitHub Actions because `expo doctor` doesn't return exit code 1 on failure.

`expo doctor` should exit code 1 to tell CI systems that there is a problem.

### Environment

N/A

### Please specify your device/emulator/simulator platform, model and version

N/A

### Error output

N/A

### Reproducible demo or steps to reproduce from a blank project

N/A

**Comment by Jamesking56** [comment]
The workaround for anyone looking for it in GitHub Actions is:

```
- name: Expo Doctor
   run: expo doctor | grep "Didn't find any issues with the project"
```

**Comment by kbrandwijk** [comment]
As this is 'just' a warning, I don't think we should change the _default_ behavior to fail on warnings. But I could see a use case for introducing a flag like `--fail-on-warn`, or `--strict` or similar to configure that behavior.

**Comment by Jamesking56** [comment]
Is this resolved by #17048?

**Comment by kbrandwijk** [comment]
No, but it is fixed by https://github.com/expo/expo-cli/pull/4359.

**Comment by pSnehanshu** [comment]
Expo Doctor is exiting with code 1, but without any explanation. It is arbitrary, sometimes it succeeds, sometimes it fails.

![image](https://github.com/expo/expo-cli/assets/9392350/819c1c8b-5e30-4bab-a5d1-e2d424157f5b)
