### ISSUE TITLE
`uri-scheme` does not work on brand new project

### ISSUE THREAD

**Issue by ImperviousPanda** [expo/expo-cli#4235]
### Summary

I've setup a new project and I'm unable to add a `uri-scheme`. I've run the following commands:

```
$ expo init google-sign-in
$ cd google-sign-in
$ yarn add expo-auth-session@~3.5.0 expo-random@~12.1.1
$ npx uri-scheme add com.example.test
npx: installed 1 in 1.428s
No URI schemes could be added. Please ensure there is a native project available.
```

Why isn't this working?

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.4 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.10 - /usr/local/bin/npm
      Watchman: 2022.02.14.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 25, 29, 30
        Build Tools: 25.0.0, 29.0.2, 30.0.3
        System Images: a...google_apis | Google APIs Intel x86 Atom Sys..., a... | Android TV Intel x86 Atom Syst..., a...google_apis | Google APIs Intel x86 Atom Sys...
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

not relevant

### Error output

```
No URI schemes could be added. Please ensure there is a native project available.
```

### Reproducible demo or steps to reproduce from a blank project

```
$ expo init google-sign-in
$ cd google-sign-in
$ yarn add expo-auth-session@~3.5.0 expo-random@~12.1.1
$ npx uri-scheme add com.example.test
```

**Comment by kbrandwijk** [comment]
You are in a managed project. In managed projects, uri schemes get added to app.json/app.config.js, `uri-scheme` only works for bare workflow projects, as it modifies the native files.
