### ISSUE TITLE
expo init stack

### ISSUE THREAD

**Issue by daunt** [expo/expo-cli#4237]
### Summary

![image](https://user-images.githubusercontent.com/12959799/155901805-01bf8f0c-7b7d-4821-9fc1-f7225f802466.png)
after enter project name then nothing happen 
how do i continue to trying expo or how can i fix or debug that problem ?

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: Linux 3.10 CentOS Linux 7 (Core)
      Shell: 4.2.46 - /bin/bash
    Binaries:
      Node: 14.18.1 - /opt/nvm/versions/node/v14.18.1/bin/node
      npm: 8.5.2 - /opt/nvm/versions/node/v14.18.1/bin/npm
    npmGlobalPackages:
      expo-cli: 5.2.0
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

lastest version of expo

### Error output

no output error just blank

### Reproducible demo or steps to reproduce from a blank project

just "expo init"

**Comment by EvanBacon** [comment]
Can you please rerun with `EXPO_DEBUG=1` environment variable enabled and provide the extra logs (if any).

**Comment by EvanBacon** [comment]
Closing, please feel free to reopen with more info.
