### ISSUE TITLE
How do you run tests in this repo? 

### ISSUE THREAD

**Issue by jcollum-nutrien** [expo/expo-cli#4239]
### Summary

I'm following the contributing guidelines and I have the CLI up and running locally. But when I run the tests in the root of the repo I get 20 failures: 

```
 20 failed, 4 skipped, 213 passed, 237 total
```

This is on main with no changes. Is there some trick to getting the  tests running? 

### Environment

npx expo-env-info
npx: installed 1 in 2.692s

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v14.19.0/bin/yarn
      npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 5.1.2
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

N/A

### Error output

Test Suites: 3 failed, 11 passed, 14 of 126 total
Tests:       20 failed, 4 skipped, 213 passed, 237 total
Snapshots:   3 passed, 3 total

### Reproducible demo or steps to reproduce from a blank project

Follow the contributing guidelines. 

After running the `init` step, try running `yarn test` in the root of the `expo-cli` repo.

**Comment by EvanBacon** [comment]
You can run tests in each folder individually `cd packages/config && yarn test --watch`. The root test does not appear to be in use by CI anymore, we should probably remove it.
