### ISSUE TITLE
Could not get npm url for package "expo-template-blank"

### ISSUE THREAD

**Issue by kasunicts48** [expo/expo-cli#4244]
### Summary

when I run the expo init command I get there following error

Could not get npm url for package "expo-template-blank"

### Environment

~/Project- sudo expo init myg                                                                         
✔ Choose a template: › blank               a minimal app as clean as an empty canvas
✖ Something went wrong while downloading and extracting the template.
Could not get npm url for package "expo-template-blank"

### Please specify your device/emulator/simulator platform, model and version

I run in that command ubuntu 20.04

### Error output

✔ Choose a template: › blank               a minimal app as clean as an empty canvas
✖ Something went wrong while downloading and extracting the template.
Could not get npm url for package "expo-template-blank"

### Reproducible demo or steps to reproduce from a blank project

..

**Comment by kbrandwijk** [comment]
Are you using a global npm registry configuration that is non-default?

Could you try running `npm view expo-template-blank --json` on the command line and share the results?

Also, I see you are using `sudo` to run `expo init`. This could lead to unexpected results. Can you try running the CLI normally, without `sudo`?

**Comment by Ahmed-Ibrahim-Anter** [comment]
I had the same error that happens after I upgrade expo version before that upgrade working good is there asolution? 
```

{
  "_id": "expo-template-blank@44.0.4",
  "_rev": "135-ed69de1199e048cd191fca517870f3d5",
  "name": "expo-template-blank",
  "dist-tags": {
    "latest": "44.0.4",
    "sdk-31": "0.0.3",
    "sdk-32": "0.0.4",
    "next": "36.0.0",
    "sdk-33": "33.0.0",
    "sdk-34": "34.0.1",
    "sdk-35": "35.0.1",
    "sdk-36": "36.0.0",
    "sdk-37": "37.0.2",
    "sdk-38": "38.0.4",
    "sdk-39": "39.0.5",
    "sdk-40": "40.0.5",
    "sdk-41": "41.0.7",
    "sdk-42": "42.0.9",
    "sdk-43": "43.0.6",
    "sdk-44": "44.0.4"
  },
  "versions": [
    "0.0.1",
    "0.0.2",
    "0.0.3",
    "0.0.4-rc.0",
    "0.0.4",
    "33.0.0",
    "34.0.0-rc.0",
    "34.0.0",
    "34.0.1",
    "35.0.0-rc.0",
    "35.0.0",
    "35.0.1",
    "36.0.0",
    "36.0.1",
    "37.0.0",
    "37.0.1",
    "37.0.2",
    "38.0.0",
    "38.0.1",
    "38.0.2",
    "38.0.3",
    "38.0.4",
    "39.0.0",
    "39.0.1",
    "39.0.2",
    "39.0.3",
    "39.0.4",
    "39.0.5",
    "40.0.0",
    "40.0.1",
    "40.0.2",
    "40.0.3",
    "40.0.4",
    "40.0.5",
    "41.0.1",
    "41.0.2",
    "41.0.3",
    "41.0.4",
    "41.0.5",
    "41.0.6",
    "41.0.7",
    "42.0.0",
    "42.0.1",
    "42.0.2",
    "42.0.3",
    "42.0.4",
    "42.0.6",
    "42.0.7",
    "42.0.8",
    "42.0.9",
    "43.0.0",
    "43.0.1",
    "43.0.2",
    "43.0.3",
    "43.0.4",
    "43.0.5",
    "43.0.6",
    "44.0.0",
    "44.0.1",
    "44.0.2",
    "44.0.3",
    "44.0.4"
  ],
  "time": {
    "created": "2018-11-23T19:34:04.241Z",
    "0.0.1": "2018-11-23T19:34:04.604Z",
    "modified": "2022-02-25T09:35:52.023Z",
    "0.0.2": "2018-11-23T20:23:19.855Z",
    "0.0.3": "2018-11-23T20:23:34.949Z",
    "0.0.4-rc.0": "2018-12-20T20:38:04.704Z",
    "0.0.4": "2019-01-04T11:10:18.350Z",
    "33.0.0": "2019-05-31T14:37:04.690Z",
    "34.0.0-rc.0": "2019-07-25T15:16:36.168Z",
    "34.0.0": "2019-07-27T00:35:10.640Z",
    "34.0.1": "2019-07-29T21:49:42.819Z",
    "35.0.0-rc.0": "2019-09-18T08:03:57.393Z",
    "35.0.0": "2019-09-19T13:37:00.777Z",
    "35.0.1": "2019-10-18T22:45:22.049Z",
    "36.0.0": "2019-12-09T11:50:36.420Z",
    "36.0.1": "2019-12-18T00:25:25.009Z",
    "37.0.0": "2020-03-11T15:03:46.769Z",
    "37.0.1": "2020-03-31T21:22:36.767Z",
    "37.0.2": "2020-04-07T01:00:26.191Z",
    "38.0.0": "2020-06-09T08:48:21.446Z",
    "38.0.1": "2020-06-22T14:56:07.601Z",
    "38.0.2": "2020-06-25T02:03:44.451Z",
    "38.0.3": "2020-06-30T22:31:06.177Z",
    "38.0.4": "2020-07-07T22:07:39.682Z",
    "39.0.0": "2020-09-17T19:48:27.423Z",
    "39.0.1": "2020-09-21T22:25:29.964Z",
    "39.0.2": "2020-09-22T01:08:51.999Z",
    "39.0.3": "2020-10-03T05:11:02.941Z",
    "39.0.4": "2020-10-23T00:10:31.837Z",
    "39.0.5": "2020-10-28T18:26:20.072Z",
    "40.0.0": "2020-11-17T05:33:13.512Z",
    "40.0.1": "2020-11-30T22:19:16.533Z",
    "40.0.2": "2020-11-30T22:30:11.233Z",
    "40.0.3": "2020-12-09T04:26:44.376Z",
    "40.0.4": "2020-12-09T20:30:25.468Z",
    "41.0.1": "2021-03-10T03:10:53.506Z",
    "40.0.5": "2021-03-23T18:14:51.335Z",
    "41.0.2": "2021-03-30T17:17:29.942Z",
    "41.0.3": "2021-03-30T17:56:13.524Z",
    "41.0.4": "2021-04-01T23:43:35.110Z",
    "41.0.5": "2021-04-09T23:08:36.830Z",
    "41.0.6": "2021-04-14T19:34:03.563Z",
    "41.0.7": "2021-04-21T00:38:49.996Z",
    "42.0.0": "2021-06-16T19:38:09.314Z",
    "42.0.1": "2021-06-23T02:45:50.676Z",
    "42.0.2": "2021-06-23T19:48:48.768Z",
    "42.0.3": "2021-06-24T20:19:50.919Z",
    "42.0.4": "2021-07-01T04:38:25.925Z",
    "42.0.6": "2021-07-01T23:19:41.660Z",
    "42.0.7": "2021-07-08T20:59:48.736Z",
    "42.0.8": "2021-07-08T23:50:09.346Z",
    "42.0.9": "2021-07-09T21:25:53.939Z",
    "43.0.0": "2021-09-28T16:22:39.785Z",
    "43.0.1": "2021-09-29T11:04:22.360Z",
    "43.0.2": "2021-10-01T23:47:14.129Z",
    "43.0.3": "2021-10-15T21:29:16.885Z",
    "43.0.4": "2021-10-15T21:57:21.123Z",
    "43.0.5": "2021-10-21T21:23:16.081Z",
    "43.0.6": "2021-11-09T20:00:45.095Z",
    "44.0.0": "2021-12-03T23:27:22.242Z",
    "44.0.1": "2021-12-09T00:01:20.582Z",
    "44.0.2": "2021-12-15T19:09:39.648Z",
    "44.0.3": "2021-12-16T19:23:14.408Z",
    "44.0.4": "2021-12-17T01:39:57.967Z"
  },
  "maintainers": [
    "tsapeta <npm@tsapeta.com>",
    "dsokal <dominiksokal@gmail.com>",
    "wkozyra <wojciech.kozyra@swmansion.com>",
    "bbarthec <bartlomiejbukowski.b@gmail.com>",
    "ide <ide+npm@jameside.com>",
    "lukmccall <kosmatylukasz@gmail.com>",
    "kgc00 <kirbygc00@gmail.com>",
    "fiber-god <datwheat@gmail.com>",
    "brentvatne <brentvatne@gmail.com>",
    "ccheever <ccheever@gmail.com>",
    "evanbacon <baconbrix@gmail.com>",
    "quinlanj <quinlanjung@gmail.com>",
    "esamelson <eric@expo.io>",
    "expoadmin <support@expo.io>",
    "charliecruzan <charliecruzan@gmail.com>",
    "tcdavis <tc@expo.io>",
    "exponent <exponent.team@gmail.com>",
    "wschurman <wschurman@gmail.com>",
    "jkhales <jonathan@expo.io>",
    "bycedric <me@bycedric.com>",
    "jonsamp <sampjon@gmail.com>",
    "princefleaswallow <mhampton@hey.com>",
    "andyboythekid <andydevs123@gmail.com>",
    "kudochien <ckchien@gmail.com>",
    "fson <ville.immonen@iki.fi>"
  ],
  "description": "The Blank project template includes the minimum dependencies to run and an empty root component.",
  "readmeFilename": "",
  "_cached": true,
  "_contentLength": 197191,
  "version": "44.0.4",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~44.0.0",
    "expo-status-bar": "~1.2.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-web": "0.17.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "gitHead": "5bb6fa7432a8afd0b7bc00e212ee66d3644c047e",
  "readme": "ERROR: No README data found!",
  "_nodeVersion": "16.13.0",
  "_npmVersion": "8.1.0",
  "dist": {
    "integrity": "sha512-fxk9P66CgXMOcNDgh3x6pEAxdGl2X3Dw4t4zSUim+MMTUbSx9RGFwib+bz9V3k56NNzsa+LYZPM8GL8zEGsZXQ==",
    "shasum": "e6a7de7f509632788229d8f15ed9539dfb47a465",
    "tarball": "https://registry.npmjs.org/expo-template-blank/-/expo-template-blank-44.0.4.tgz",
    "fileCount": 10,
    "unpackedSize": 90867,
    "npm-signature": "-----BEGIN PGP SIGNATURE-----\r\nVersion: OpenPGP.js v3.0.13\r\nComment: https://openpgpjs.org\r\n\r\nwsFcBAEBCAAQBQJhu+ptCRA9TVsSAnZWagAAH6YP/A8b6odCbMEMAuaUDohZ\n4KoM7DqqFSEHFxXEwugoLjAowBHxQYK3pyK56aJBkWXRrJq+8Jb9OrMBCo+j\n56PPifor8dTE1nv9RiRWrOeMc+uF4Hx4/JqBr3H2N1e9YZIWMrTSt3ZgXRfp\nF5OCbBOv1/uaLT7D7KXHZUs1AbxNJGBZ4zm/1pHmRKZO2Hmc46xW+LupBRYr\nk3AlhvOtoP8umzyQlTHRqzTbBb+OXXOBDQAWtltyBkU6l5omlVy1v4z00Rzr\nerzsOyYj9gW7oWa+lSdqpwaq16CC4e8ymteQyfx6g+w712/dHckSbgD5MmTt\nLFwmaRhS5uCbITzHtDMi2rzgXvqm9vKe2FuVpO4zQfy+WAu4uIYUZruglZ+A\nd3F8AAW2s605KG+c+f/nUbvpfSYoAgAkvay9Vo+NgsSLemOCPwpjgnrL/d2N\n64zICdlD/alKIvY2PXRA9aY+D059YxC3WxDyBlLGdtj67XakSSdGPhKcMS9v\nbyx5ZM1cr/XpZyjwJSMLFAVgBA0oCVRjipXILHyav8VNgkuYgsa8uWQi7Smp\nXR+B75cvtl1ZAOjXugymHEsAfXc8r361wE3xCvqt8O64cMMW9ggIknUP/tbq\nss1FeHwUjk2hhb/85olJsVu7w73Q5NLihPfGTfKopmF5xHf1gS6lzzBcpMqi\nwOy7\r\n=M8xx\r\n-----END PGP SIGNATURE-----\r\n"
  },
  "_npmUser": "brentvatne <brentvatne@gmail.com>",
  "directories": {},
  "_npmOperationalInternal": {
    "host": "s3://npm-registry-packages",
    "tmp": "tmp/expo-template-blank_44.0.4_1639705197786_0.7380541170606914"
  },
  "_hasShrinkwrap": false
}

```

> Are you using a global npm registry configuration that is non-default?
> 
> Could you try running `npm view expo-template-blank --json` on the command line and share the results?
> 
> Also, I see you are using `sudo` to run `expo init`. This could lead to unexpected results. Can you try running the CLI normally, without `sudo`?

**Comment by Ahmed-Ibrahim-Anter** [comment]
I had the same error that happens after I upgrade expo version before that upgrade working good is there asolution?


{
  "_id": "expo-template-blank@44.0.4",
  "_rev": "135-ed69de1199e048cd191fca517870f3d5",
  "name": "expo-template-blank",
  "dist-tags": {
    "latest": "44.0.4",
    "sdk-31": "0.0.3",
    "sdk-32": "0.0.4",
    "next": "36.0.0",
    "sdk-33": "33.0.0",
    "sdk-34": "34.0.1",
    "sdk-35": "35.0.1",
    "sdk-36": "36.0.0",
    "sdk-37": "37.0.2",
    "sdk-38": "38.0.4",
    "sdk-39": "39.0.5",
    "sdk-40": "40.0.5",
    "sdk-41": "41.0.7",
    "sdk-42": "42.0.9",
    "sdk-43": "43.0.6",
    "sdk-44": "44.0.4"
  },
  "versions": [
    "0.0.1",
    "0.0.2",
    "0.0.3",
    "0.0.4-rc.0",
    "0.0.4",
    "33.0.0",
    "34.0.0-rc.0",
    "34.0.0",
    "34.0.1",
    "35.0.0-rc.0",
    "35.0.0",
    "35.0.1",
    "36.0.0",
    "36.0.1",
    "37.0.0",
    "37.0.1",
    "37.0.2",
    "38.0.0",
    "38.0.1",
    "38.0.2",
    "38.0.3",
    "38.0.4",
    "39.0.0",
    "39.0.1",
    "39.0.2",
    "39.0.3",
    "39.0.4",
    "39.0.5",
    "40.0.0",
    "40.0.1",
    "40.0.2",
    "40.0.3",
    "40.0.4",
    "40.0.5",
    "41.0.1",
    "41.0.2",
    "41.0.3",
    "41.0.4",
    "41.0.5",
    "41.0.6",
    "41.0.7",
    "42.0.0",
    "42.0.1",
    "42.0.2",
    "42.0.3",
    "42.0.4",
    "42.0.6",
    "42.0.7",
    "42.0.8",
    "42.0.9",
    "43.0.0",
    "43.0.1",
    "43.0.2",
    "43.0.3",
    "43.0.4",
    "43.0.5",
    "43.0.6",
    "44.0.0",
    "44.0.1",
    "44.0.2",
    "44.0.3",
    "44.0.4"
  ],
  "time": {
    "created": "2018-11-23T19:34:04.241Z",
    "0.0.1": "2018-11-23T19:34:04.604Z",
    "modified": "2022-02-25T09:35:52.023Z",
    "0.0.2": "2018-11-23T20:23:19.855Z",
    "0.0.3": "2018-11-23T20:23:34.949Z",
    "0.0.4-rc.0": "2018-12-20T20:38:04.704Z",
    "0.0.4": "2019-01-04T11:10:18.350Z",
    "33.0.0": "2019-05-31T14:37:04.690Z",
    "34.0.0-rc.0": "2019-07-25T15:16:36.168Z",
    "34.0.0": "2019-07-27T00:35:10.640Z",
    "34.0.1": "2019-07-29T21:49:42.819Z",
    "35.0.0-rc.0": "2019-09-18T08:03:57.393Z",
    "35.0.0": "2019-09-19T13:37:00.777Z",
    "35.0.1": "2019-10-18T22:45:22.049Z",
    "36.0.0": "2019-12-09T11:50:36.420Z",
    "36.0.1": "2019-12-18T00:25:25.009Z",
    "37.0.0": "2020-03-11T15:03:46.769Z",
    "37.0.1": "2020-03-31T21:22:36.767Z",
    "37.0.2": "2020-04-07T01:00:26.191Z",
    "38.0.0": "2020-06-09T08:48:21.446Z",
    "38.0.1": "2020-06-22T14:56:07.601Z",
    "38.0.2": "2020-06-25T02:03:44.451Z",
    "38.0.3": "2020-06-30T22:31:06.177Z",
    "38.0.4": "2020-07-07T22:07:39.682Z",
    "39.0.0": "2020-09-17T19:48:27.423Z",
    "39.0.1": "2020-09-21T22:25:29.964Z",
    "39.0.2": "2020-09-22T01:08:51.999Z",
    "39.0.3": "2020-10-03T05:11:02.941Z",
    "39.0.4": "2020-10-23T00:10:31.837Z",
    "39.0.5": "2020-10-28T18:26:20.072Z",
    "40.0.0": "2020-11-17T05:33:13.512Z",
    "40.0.1": "2020-11-30T22:19:16.533Z",
    "40.0.2": "2020-11-30T22:30:11.233Z",
    "40.0.3": "2020-12-09T04:26:44.376Z",
    "40.0.4": "2020-12-09T20:30:25.468Z",
    "41.0.1": "2021-03-10T03:10:53.506Z",
    "40.0.5": "2021-03-23T18:14:51.335Z",
    "41.0.2": "2021-03-30T17:17:29.942Z",
    "41.0.3": "2021-03-30T17:56:13.524Z",
    "41.0.4": "2021-04-01T23:43:35.110Z",
    "41.0.5": "2021-04-09T23:08:36.830Z",
    "41.0.6": "2021-04-14T19:34:03.563Z",
    "41.0.7": "2021-04-21T00:38:49.996Z",
    "42.0.0": "2021-06-16T19:38:09.314Z",
    "42.0.1": "2021-06-23T02:45:50.676Z",
    "42.0.2": "2021-06-23T19:48:48.768Z",
    "42.0.3": "2021-06-24T20:19:50.919Z",
    "42.0.4": "2021-07-01T04:38:25.925Z",
    "42.0.6": "2021-07-01T23:19:41.660Z",
    "42.0.7": "2021-07-08T20:59:48.736Z",
    "42.0.8": "2021-07-08T23:50:09.346Z",
    "42.0.9": "2021-07-09T21:25:53.939Z",
    "43.0.0": "2021-09-28T16:22:39.785Z",
    "43.0.1": "2021-09-29T11:04:22.360Z",
    "43.0.2": "2021-10-01T23:47:14.129Z",
    "43.0.3": "2021-10-15T21:29:16.885Z",
    "43.0.4": "2021-10-15T21:57:21.123Z",
    "43.0.5": "2021-10-21T21:23:16.081Z",
    "43.0.6": "2021-11-09T20:00:45.095Z",
    "44.0.0": "2021-12-03T23:27:22.242Z",
    "44.0.1": "2021-12-09T00:01:20.582Z",
    "44.0.2": "2021-12-15T19:09:39.648Z",
    "44.0.3": "2021-12-16T19:23:14.408Z",
    "44.0.4": "2021-12-17T01:39:57.967Z"
  },
  "maintainers": [
    "tsapeta <npm@tsapeta.com>",
    "dsokal <dominiksokal@gmail.com>",
    "wkozyra <wojciech.kozyra@swmansion.com>",
    "bbarthec <bartlomiejbukowski.b@gmail.com>",
    "ide <ide+npm@jameside.com>",
    "lukmccall <kosmatylukasz@gmail.com>",
    "kgc00 <kirbygc00@gmail.com>",
    "fiber-god <datwheat@gmail.com>",
    "brentvatne <brentvatne@gmail.com>",
    "ccheever <ccheever@gmail.com>",
    "evanbacon <baconbrix@gmail.com>",
    "quinlanj <quinlanjung@gmail.com>",
    "esamelson <eric@expo.io>",
    "expoadmin <support@expo.io>",
    "charliecruzan <charliecruzan@gmail.com>",
    "tcdavis <tc@expo.io>",
    "exponent <exponent.team@gmail.com>",
    "wschurman <wschurman@gmail.com>",
    "jkhales <jonathan@expo.io>",
    "bycedric <me@bycedric.com>",
    "jonsamp <sampjon@gmail.com>",
    "princefleaswallow <mhampton@hey.com>",
    "andyboythekid <andydevs123@gmail.com>",
    "kudochien <ckchien@gmail.com>",
    "fson <ville.immonen@iki.fi>"
  ],
  "description": "The Blank project template includes the minimum dependencies to run and an empty root component.",
  "readmeFilename": "",
  "_cached": true,
  "_contentLength": 197191,
  "version": "44.0.4",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~44.0.0",
    "expo-status-bar": "~1.2.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-web": "0.17.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "gitHead": "5bb6fa7432a8afd0b7bc00e212ee66d3644c047e",
  "readme": "ERROR: No README data found!",
  "_nodeVersion": "16.13.0",
  "_npmVersion": "8.1.0",
  "dist": {
    "integrity": "sha512-fxk9P66CgXMOcNDgh3x6pEAxdGl2X3Dw4t4zSUim+MMTUbSx9RGFwib+bz9V3k56NNzsa+LYZPM8GL8zEGsZXQ==",
    "shasum": "e6a7de7f509632788229d8f15ed9539dfb47a465",
    "tarball": "https://registry.npmjs.org/expo-template-blank/-/expo-template-blank-44.0.4.tgz",
    "fileCount": 10,
    "unpackedSize": 90867,
    "npm-signature": "-----BEGIN PGP SIGNATURE-----\r\nVersion: OpenPGP.js v3.0.13\r\nComment: https://openpgpjs.org\r\n\r\nwsFcBAEBCAAQBQJhu+ptCRA9TVsSAnZWagAAH6YP/A8b6odCbMEMAuaUDohZ\n4KoM7DqqFSEHFxXEwugoLjAowBHxQYK3pyK56aJBkWXRrJq+8Jb9OrMBCo+j\n56PPifor8dTE1nv9RiRWrOeMc+uF4Hx4/JqBr3H2N1e9YZIWMrTSt3ZgXRfp\nF5OCbBOv1/uaLT7D7KXHZUs1AbxNJGBZ4zm/1pHmRKZO2Hmc46xW+LupBRYr\nk3AlhvOtoP8umzyQlTHRqzTbBb+OXXOBDQAWtltyBkU6l5omlVy1v4z00Rzr\nerzsOyYj9gW7oWa+lSdqpwaq16CC4e8ymteQyfx6g+w712/dHckSbgD5MmTt\nLFwmaRhS5uCbITzHtDMi2rzgXvqm9vKe2FuVpO4zQfy+WAu4uIYUZruglZ+A\nd3F8AAW2s605KG+c+f/nUbvpfSYoAgAkvay9Vo+NgsSLemOCPwpjgnrL/d2N\n64zICdlD/alKIvY2PXRA9aY+D059YxC3WxDyBlLGdtj67XakSSdGPhKcMS9v\nbyx5ZM1cr/XpZyjwJSMLFAVgBA0oCVRjipXILHyav8VNgkuYgsa8uWQi7Smp\nXR+B75cvtl1ZAOjXugymHEsAfXc8r361wE3xCvqt8O64cMMW9ggIknUP/tbq\nss1FeHwUjk2hhb/85olJsVu7w73Q5NLihPfGTfKopmF5xHf1gS6lzzBcpMqi\nwOy7\r\n=M8xx\r\n-----END PGP SIGNATURE-----\r\n"
  },
  "_npmUser": "brentvatne <brentvatne@gmail.com>",
  "directories": {},
  "_npmOperationalInternal": {
    "host": "s3://npm-registry-packages",
    "tmp": "tmp/expo-template-blank_44.0.4_1639705197786_0.7380541170606914"
  },
  "_hasShrinkwrap": false
}

**Comment by Ahmed-Ibrahim-Anter** [comment]
Remove node js from your snap store and reinstall it with  download version from the formal website for Node js will solve the problem

**Comment by kasunicts48** [comment]
## I fixed it 
**I removed node js and reinstall node js using the below code**
`sudo apt install nodejs`

**Comment by kasunicts48** [comment]
### I fixed it
**I removed node js and reinstall node js using the below code**
`sudo apt update && sudo apt install nodejs`

**Comment by kasunicts48** [comment]
### I fixed it
**I removed node js and reinstall node js using the below code**
`sudo apt update && sudo apt install nodejs`

**Comment by sheenarbw** [comment]
Just a note on the fix. 

`sudo apt install nodejs` will install an old version of node by default. Just check `node -v` to see what version you are running. 

Here's how to apt install more recent versions: 
https://github.com/nodesource/distributions/blob/master/README.md#debinstall

**Comment by asad-mansoor-dev** [comment]
On my side this issue happened when I was initialising a new **React Native Project** 

This issue occurred because of no permission to read some files. I added sudo word before the command, it resolved my issue. **sudo expo init ProjectName**

**Comment by signor-mike** [comment]
thanks @Ahmed-Ibrahim-Anter 
my solution for the problem:
Uninstall snap Node.js
```
# apt install node.js; // installs node.js from APT, at the moment of writing this: v.12
$ nvm install 18; // using NVM (google: node version manager) to install the latest LTS (v18 as of today)
$ nvm alias system 18; // making v18 system version
```
I can't believe snap let me down this time. I spent almost entire week trying to figure it out.
