### ISSUE TITLE
A very serious problem about the expo - Runtime 

### ISSUE THREAD

**Issue by DhanielB** [expo/expo-cli#4246]
### Summary

I thought the expo was faster but unfortunately when I ran it on my machine it took (30 minutes to give the "expo init") and the ("expo start" takes an average of 30 - 15 minutes) please solve this sorry a lot productivity besides when i can run it disconnects my phone

By dhanielB, Thanks for your attention 

### Environment

Expo : 5.00
Computer : 2 gb ram, 500 gb hd and 1.80ghz cpu
Plataform : Windows 7 32 bits

### Please specify your device/emulator/simulator platform, model and version

Android 11, A10 Samsung 2 gb ram, 32 gb

### Error output

Non have output

### Reproducible demo or steps to reproduce from a blank project

My project is a blank from expo init by default

**Comment by brentvatne** [comment]
hi there! sorry `expo init` really shouldn't take that long. i'm not familiar with your particular machine but this is likely not anything we can act on. all `expo init` does is download a package from npm, extract it, and run `npm install`.
