### ISSUE TITLE
Apps created with "expo build:ios" are rejected from submission with an app thinning error

### ISSUE THREAD

**Issue by fristyr** [expo/expo-cli#4253]
### Summary

Today, as usual, we wanted to make a new build
But after I ran **expo build:ios -t archive**
And uploaded our app to the app store I got this message from App Store
<img width="677" alt="error" src="https://user-images.githubusercontent.com/33237937/157493553-823c8264-1799-47f0-8839-1f0374b51a5b.png">

I tried different Expo-cli versions from the newest 5.3.0 until the old 4.13.0
I tried different machines, Mac Os and Windows just to build.
Nothing helped.
I don't use anything related to bitcode

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.18.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.0.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 13.2/13C90 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 8.5.1 => 8.5.1 
      expo: ^43.0.0 => 43.0.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 4.13.0
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

IOS

### Reproducible demo or steps to reproduce from a blank project

Don't have it

**Comment by RainLdc** [comment]
Same with expo 5.3.0.

**Comment by fristyr** [comment]
> Same with expo 5.3.0. It worked this morning with expo 5.0.1

Have you tried recently with 5.0.1 ? 
I tried a few hours with even 4.13.0.
Still same error

**Comment by drpanxo** [comment]
Same error here expo-cli 5.3.0 and 5.2.0

**Comment by padjiwib** [comment]
Same error here

**Comment by RainLdc** [comment]
> > Same with expo 5.3.0. It worked this morning with expo 5.0.1
> 
> Have you tried recently with 5.0.1 ? I tried a few hours with even 4.13.0. Still same error

Same error with 5.0.1.

when i look at the build in expo.Process is different from yesterday morning.  Expo must have changed something recently but I haven't figured out what yet.

**Comment by amerikan** [comment]
Same here. Using expo-cli@5.3.0

**Comment by Gabrielhanna07** [comment]
Same problem here… worked without any issues until yesterday.

**Comment by InTheNooB** [comment]
Exact same problem... It is my first time using expo to build an IOS app, I thought it was a known problem but I seem to have arrived at the exact wrong moment 😂

**Comment by traenerdev** [comment]
Same here with expo 5.1.3. Really bad timing. You guys think it's an Apple problem or Expo ?

**Comment by RainLdc** [comment]
Any ideas @kbrandwijk @EvanBacon ?

**Comment by ahmadkkhaled** [comment]
Facing this issue with expo@5.0.1 and 5.3.0

**Comment by sitemile** [comment]
I am facing the same issue expo 44.0
and things were great 2 days ago

**Comment by ewfian** [comment]
same issue here

**Comment by adamsesco** [comment]
The same here, hope got answers ASAP.

**Comment by BloodyMonkey** [comment]
Same here, what's happening ??

**Comment by jcvjunior** [comment]
Same here, with expo CLI 4.12.10, expo 43

**Comment by wkozyra95** [comment]
https://forums.expo.dev/t/expo-managed-app-cant-get-submitted-to-apple-appstore-due-to-app-thinning/62231/12

> To our knowledge, this is an unexpected change by the App Store and the Classic Build system has not changed. We are investigating this issue. Given this is an external change it will likely take time to identify the root cause to begin a fix.

> Developers have reported that using EAS Build has fixed this issue. EAS Build or building locally are the best paths forward if you need to submit builds for review before the Classic Build service is updated or the App Store starts accepting these builds again. The Classic Build service will run until the beginning of next year, so while it is not otherwise urgent to migrate to EAS Build or local builds, it will be necessary.

**Comment by ArsalanReal** [comment]
I am facing the same issue. expo build failing, i have tried since yesterday 10 builds but no help. Is there any way to convert existing app to EAS. i am reading here this is not useful also

**Comment by jperera84** [comment]
Same here:
Expo version: 5.0.3
Expo-CLI: 5.0.3
I worked on March 7, I've been tried for the last 3 days an it is not working anymore, always failing in thinned process in App Store.
I tried also with EAS BUILD and it does not work neither.
Any help?

**Comment by BloodyMonkey** [comment]
Switched to EAS build and working like a charm !
Faster, lighter and easy to setup

**Comment by ArsalanReal** [comment]
> Switched to EAS build and working like a charm ! Faster, lighter and easy to setup

how what is easier way to do it?

**Comment by jperera84** [comment]
@BloodyMonkey Can you share how you configured your eas.json for me it does not work?

**Comment by fristyr** [comment]
> Switched to EAS build and working like a charm ! Faster, lighter and easy to setup

EAS is giving me Fastlane error with unknown error

**Comment by adamsesco** [comment]
> Switched to EAS build and working like a charm ! Faster, lighter and easy to setup

Could you share with us more details please!

**Comment by BloodyMonkey** [comment]
I have 2 release channels: dev and prod

`eas build:configure
eas build --profile dev --platform ios`

`{
  "cli": {
    "version": ">= 0.47.0"
  },
  "build": {
    "production": {
      "releaseChannel": "production"
    },
    "dev": {
      "releaseChannel": "dev"
    }
  },
  "submit": {
    "production": {}
  }
}`

**Comment by jperera84** [comment]
Do you know why the EAS Build is telling me this?
Specifying "ios.bundleIdentifier" in app.json is deprecated for bare workflow projects.
EAS Build depends only on the value in the native code. Please remove the deprecated configuration.
✔ Using remote iOS credentials (Expo server)
also why it always take the wrong Bundler Identifier?  Not the one I have in my app.json?

**Comment by fristyr** [comment]
> I have 2 release channels: dev and prod
> 
> eas.json `{ "cli": { "version": ">= 0.47.0" }, "build": { "production": { "releaseChannel": "production" }, "dev": { "releaseChannel": "dev" } }, "submit": { "production": {} } }`
> 
> Setup `eas build:configure`
> 
> Build `eas build --profile dev --platform ios`

Have you made any migrations?

**Comment by BloodyMonkey** [comment]
> Do you know why the EAS Build is telling me this? Specifying "ios.bundleIdentifier" in app.json is deprecated for bare workflow projects. EAS Build depends only on the value in the native code. Please remove the deprecated configuration. ✔ Using remote iOS credentials (Expo server) also why it always take the wrong Bundler Identifier? Not the one I have in my app.json?

Sorry i use managed workflow

> > I have 2 release channels: dev and prod
> > eas.json `{ "cli": { "version": ">= 0.47.0" }, "build": { "production": { "releaseChannel": "production" }, "dev": { "releaseChannel": "dev" } }, "submit": { "production": {} } }`
> > Setup `eas build:configure`
> > Build `eas build --profile dev --platform ios`
> 
> Have you made any migrations?

No migration, all i have done is there (**i use managed workflow**)

**Comment by fristyr** [comment]
I use managed workflow too. 
But for some reason i get Fastlane error, I don't even know what is that

**Comment by BloodyMonkey** [comment]
> I use managed workflow too. But for some reason i get Fastlane error, I don't even know what is that

Maybe a problem with your Apple account
Check your app keys validity and if you have accepted all agreements

**Comment by fristyr** [comment]
> > I use managed workflow too. But for some reason i get Fastlane error, I don't even know what is that
> 
> Maybe a problem with your Apple account Check your app keys validity and if you have accepted all agreements

Oh btw, do you use Hermes as the engine in your app.json ?

**Comment by jacekd** [comment]
Same here on the 5.2.0 and node 16

**Comment by RainLdc** [comment]
No one has [this error](https://github.com/expo/eas-cli/issues/1009) with eas buil ?

**Comment by Gabrielhanna07** [comment]
> No one has [this error](https://github.com/expo/eas-cli/issues/1009) with eas buil ?

I had this issue and i used EAS build.. last time i tried was this morning (GMT+1)

**Comment by deepak2002** [comment]
Same issue here with classic build. Any improvement ?

**Comment by webdevmario** [comment]
Also experiencing this issue on the Classic build. Upgrading to EAS is not ideal right now and based on the comments here doesn't appear to be a guaranteed approach.

**Comment by Warhammer2345** [comment]
Same here with 4.13.0 or 5.3.0

**Comment by jacekd** [comment]
I have it on both on classic and eas build.

**Comment by morocodeintr** [comment]
i dont think so that going to eas could fix the problem, still waiting for expo team!

**Comment by ToStefan** [comment]
Same here, we reverted app and still same issue. Please fix

**Comment by AaronStackBarnes** [comment]
Same issue here with the classic build system I am going to try eas now.

**Comment by ide** [comment]
We're using this GitHub issue to centralize the conversation around this issue. Currently, we believe it is a breaking change with the App Store. The Classic Build service has not changed in the last few days since this issue started.

To keep the conversation focused, I've collapsed comments that don't contain significant information helping suss out the root cause of this issue. I'm leaving this thread unlocked for now so that developers doing deeper investigations can help out with material information but we will need to lock this thread if there are too many low-value comments.

As a guideline, please limit comments to ones with information that are related to builds made with `expo build:ios` and help with identifying the root cause.

**Comment by fristyr** [comment]
> We're using this GitHub issue to centralize the conversation around this issue. Currently, we believe it is a breaking change with the App Store. The Classic Build service has not changed in the last few days since this issue started.
> 
> To keep the conversation focused, I've collapsed comments that don't contain significant information helping suss out the root cause of this issue. I'm leaving this thread unlocked for now so that developers doing deeper investigations can help out with material information but we will need to lock this thread if there are too many low-value comments.
> 
> As a guideline, please limit comments to ones with information that are related to builds made with `expo build:ios` and help with identifying the root cause.

Agreed!
As author of this issue, do i need to do anything to help ?

**Comment by gruckionvit** [comment]
Can people start reporting what versions of Expo they are using to create the builds please. It's unclear if this is happening only on the latest version of Expo or if it's happening to people who are also running older versions too.

We've recently upgraded to the latest Expo SDK and suspected this may have been the cause.

**Comment by fristyr** [comment]
Ok I personally tried with:
Expo SDK 43 / 44
Expo CLI 4.15.0 / 5.3.0
Failed with both

**Comment by ide** [comment]
> It's unclear if this is happening only on the latest version of Expo or if it's happening to people who are also running older versions too.

We've received reports of this happening with apps using SDK 43 and SDK 44. Right now, we believe this an unexpected external change with how the App Store processes builds as there were no recent changes to the Classic Build service.

**Comment by Gabrielhanna07** [comment]
I tried with:
EAS build
SDK 44.0.1
EAS-cli 47.0.0

**Comment by josegutierro** [comment]
Expo-cli 5.2.0
Expo 44.0.0

**Comment by morocodeintr** [comment]
Hello dear, for me im using expo sdk 44.0.0

**Comment by elpampa** [comment]
Expo-cli 5.0.3
SDK 43.0.2

Same error.

**Comment by drpanxo** [comment]
Now my app works and got builded by App Store.

I was in expo-cli 5.3.0 and expo 44.0.0.

How make it work:
- Install globally eas-cli
- Create eas.json file, according to @BloodyMonkey specs. (I don't know how cite the comment, but is in earlier comments)
- run: eas build:configure
- run: eas build --profile dev --platform iOS

Had error with Lottie in expo building console. Updated packages and everything OK.

**Comment by gruckionvit** [comment]
> As a guideline, please limit comments to ones with information that are related to builds made with `expo build:ios` and help with identifying the root cause.

As a guideline, please limit comments to ones with information that are related to builds made with expo build:ios and help with identifying the root cause.

@drpanxo was you using `expo build:ios` before and decided to switch to EAS build to the issue?

**Comment by drpanxo** [comment]
> > As a guideline, please limit comments to ones with information that are related to builds made with `expo build:ios` and help with identifying the root cause.
> 
> 
> 
> As a guideline, please limit comments to ones with information that are related to builds made with expo build:ios and help with identifying the root cause.
> 
> 
> 
> @drpanxo was you using `expo build:ios` before and decided to switch to EAS build to the issue?

Yes

**Comment by kbrandwijk** [comment]
### Update
**A workaround that disables bitcode has been deployed to the servers for classic builds (those using `expo build`). For those experiencing the same issue with EAS builds, you can try disabling bitcode manually by setting the `ios.bitcode` field in app.json/app.config.js to `"Debug"` (thereby disabling it for Release builds) and kick off a new build.**

**Comment by fristyr** [comment]
I btw tried to disable bitcode, expo cli complains that i can't include it

**Comment by rajeshgrapedata** [comment]
Please confirm this is expected app.json to include this **ios.bitcode: false** 
  
```{
   "expo": {
    "name": "Your App Name",
    "icon": "./path/to/your/app-icon.png",
    "version": "1.0.0",
    "slug": "your-app-slug",
    "ios": {
      "bundleIdentifier": "com.yourcompany.yourappname",
      "buildNumber": "1.0.0",
      ios.bitcode: false      <---- change
    },
    "android": {
      "package": "com.yourcompany.yourappname",
      "versionCode": 1
    }
   }
 }
```

**Comment by morocodeintr** [comment]
> Please confirm this is expected app.json ? to include this **ios.bitcode: false**
> 
> ```
>    "expo": {
>     "name": "Your App Name",
>     "icon": "./path/to/your/app-icon.png",
>     "version": "1.0.0",
>     "slug": "your-app-slug",
>     "ios": {
>       "bundleIdentifier": "com.yourcompany.yourappname",
>       "buildNumber": "1.0.0",
>       "bitcode": "Debug"
>     },
>     "android": {
>       "package": "com.yourcompany.yourappname",
>       "versionCode": 1
>     }
>    }
>  }
> ```

I guess like that

**Comment by kbrandwijk** [comment]
@rajeshgrapedata try it like @morocodeintr suggested. It's not a boolean field.

**Comment by rajeshgrapedata** [comment]
@kbrandwijk Thanks a lot for the clarification

**Comment by amerikan** [comment]
> ## Update
> 
> **A workaround that disables bitcode has been deployed to the servers for _Classic Builds_ (i.e. those using `expo build:ios`).** Please try creating a new build and submitting to the App Store.
> ### EAS Build only
> 
> **For those experiencing the same issue with _EAS Build_, you can try disabling bitcode manually by setting the `"ios"`→`"bitcode"` field in app.json/app.config.js to `"Debug"` (thereby disabling it for Release builds) and kick off a new build.**
> 
> An example snippet of this in app.json would look like:
> 
> ```json
> "expo": {
>   "ios": {
>     "bitcode": "Debug"
>   }
> }
> ```
> 
> The above change will not have any effect for Classic Builds created with `expo build:ios`.

Just tried the classic build again right now, and it worked. 👍🏼

**Comment by Damanharneet** [comment]
Same error. Does it works for anyone using classic build?

**Comment by kaushik1094** [comment]
I was able to upload the app to test-flight successfully with Classic build system: ```expo build:ios```

Expo SDK: v41.0.0
React-Native: 0.63.0

Thank you so much! :)

**Comment by fristyr** [comment]
> I was able to upload the app to test-flight successfully with Classic build system: `expo build:ios`
> 
> Expo SDK: v41.0.0 React-Native: 0.63.0
> 
> Thank you so much! @kbrandwijk
> 
> [#4253 (comment)](https://github.com/expo/expo-cli/issues/4253#issuecomment-1064416103)

I can also confirm same stuff!!!!
Thanks a lot to the expo team

**Comment by stefanleoussis** [comment]
Built and Submitted with Classic (expo build:ios) and it has been approved and working. Thank you! 
SDK Version: 41

**Comment by Parth8733** [comment]
Thank you Expo team, it worked. I also verified it.

**Comment by Damanharneet** [comment]
it worked for me as well.. Thank you guys

**Comment by adonisdoda** [comment]
Worked for me too, I was using expo classic build . 

Thanks expo team !!!

**Comment by reido2012** [comment]
Works for me using Expo Classic Build. 

Thanks to the team!

**Comment by hfllr** [comment]
I can confirm for eas build & submit, finally works again.

Thank you expo!

**Comment by ArsalanReal** [comment]
Thanks a lot to expo team, its working for me as well.
