### ISSUE TITLE
App build with "turtle build:ios" also get error from testflight with an app thinning error

### ISSUE THREAD

**Issue by rabbitmouse** [expo/expo-cli#4256]
### Summary

I use “turtle build:ios” to create a ipa package to TestFlight, but  I got this message from App Store too。
I saw the issue [](https://github.com/expo/expo-cli/issues/4253) and add the barcode: 'DeBug' in app.json. Unlucky, i got the same error from testFlight  after I did that and use "turtle build:ios" create an ipa.

<img width="697" alt="image" src="https://user-images.githubusercontent.com/11554140/158523313-a306d072-92ca-4d8a-b0e8-664974a3be69.png">

### Environment

expo: ^42.0.0
react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz
expo-cli: 5.0.3

### Please specify your device/emulator/simulator platform, model and version

iOS

### Error output

No

### Reproducible demo or steps to reproduce from a blank project

step1: expo publish
step2: turtle build:ios

**Comment by rabbitmouse** [comment]
add "bitcode: Debug" is not work,  please help to solve it with “turtle build:ios” .

**Comment by wkozyra95** [comment]
what version of turtle-cli are you using?

**Comment by rabbitmouse** [comment]
> 

thx your reply,  turtle version is **0.24.3**

**Comment by kbrandwijk** [comment]
Bitcode is disabled for all builds in turtle-cli version 0.25.0. Please upgrade to that version and try again. The app.json setting doesn't affect classic builds, so that setting is safe to remove.

**Comment by rabbitmouse** [comment]
> Bitcode is disabled for all builds in turtle-cli version 0.25.0. Please upgrade to that version and try again. The app.json setting doesn't affect classic builds, so that setting is safe to remove.

thank you! It's work for me.
