### ISSUE TITLE
[npx-env-info] always shows Expo workflow, even when not inside a project folder

### ISSUE THREAD

**Issue by kbrandwijk** [expo/expo-cli#4264]
### Summary

![image](https://user-images.githubusercontent.com/852069/159129422-239333b6-800f-4f1c-ab7f-d53b172c505b.png)

### Environment

See above, happens on all platforms.

### Please specify your device/emulator/simulator platform, model and version

N/A

### Reproducible demo or steps to reproduce from a blank project

- Run `npx expo-env-info`

**Comment by frankcalise** [comment]
This is related to this line here? https://github.com/expo/expo-cli/blob/ccb623829a15e5a01b89b9216ee0ef53e1ec332b/packages/expo-env-info/src/diagnosticsAsync.ts#L53
