### ISSUE TITLE
Expo & NextJS - Cannot set property DEFAULT_ICON_COLOR of #<Object> which has only a getter

### ISSUE THREAD

**Issue by haveamission** [expo/expo-cli#4265]
### Summary

Trying to launch Expo, and getting a bunch of errors when it comes to Expo fonts in NextJS, despite having withFonts used

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.7.1 - /usr/local/bin/zsh
    Binaries:
      Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.16.2 => 0.16.19
      babel-preset-expo: 8.5.1 => 8.5.1
      expo: >=43.0.0-* <44.0.0 => 43.0.5
      react: 17.0.1 => 17.0.1
      react-dom: ^17.0.1 => 17.0.2
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      expo-cli: 5.3.0
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

Web

### Error output

```
event - compiled successfully
TypeError: Cannot set property DEFAULT_ICON_COLOR of #<Object> which has only a getter
    at eval (webpack-internal:///./node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/lib/create-icon-set.js:11:80)
    at Module../node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/lib/create-icon-set.js (/Users/andy/Desktop/Projects/PandaistOfficial/Frontend/Expo/.next/server/pages/_app.js:1031:1)
    at __webpack_require__ (/Users/andy/Desktop/Projects/PandaistOfficial/Frontend/Expo/.next/server/pages/_app.js:29:31)
    at eval (webpack-internal:///./node_modules/@expo/vector-icons/build/createIconSet.js:39:46)
```

### Reproducible demo or steps to reproduce from a blank project

This throws an error:

`import { FontAwesome } from "@expo/vector-icons";`

**Comment by haveamission** [comment]
I was able to fix it by also transpiling the Expo Vector Icons

**Comment by discodane** [comment]
> I was able to fix it by also transpiling the Expo Vector Icons

Can you post that transpiling?

**Comment by haveamission** [comment]
@discodane Honestly, I can't recommend this approach anymore - while it did work, it led to a MASSIVE bundle in terms of size.

Highly, highly, highly recommend just popping off the icons you want from the font and using them, because otherwise the resulting bundle is huge. If you still want to try with transpiling, I can take a look either tomorrow sometime or Thursday and get it to you, but I highly, highly recommend against following that approach.

**Comment by nandorojo** [comment]
I recommend using SVG icons instead of Expo’s font-based icons if you’re targeting web, as mentioned on the solito icon docs.
