### ISSUE TITLE
install-expo-modules failing 

### ISSUE THREAD

**Issue by ToyboxZach** [expo/expo-cli#4276]
### Summary

Trying to connect to my current project and getting this error:

```
✔ Expo modules minimum iOS requirement is 12.0. This tool will change your iOS deployment target to 12.0. Do you want to continue? … yes
› Updating your project...
› Installing expo packages...
> yarn add expo@>=43.0.0-0 <44.0.0
Uncaught Error Error: spawn yarnpkg ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn yarnpkg',
  path: 'yarnpkg',
  spawnargs: [ 'add', 'expo@>=43.0.0-0 <44.0.0' ],
  pid: undefined,
  output: [ '', '' ],
  stdout: '',
  stderr: '',
  status: null,
  signal: null
}
```

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      npm: 7.20.3 - ~/node_modules/.bin/npm
      Watchman: 2021.12.06.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 29.0.0, 30.0.0, 30.0.2, 30.0.3
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

N/A

### Error output

✔ Expo modules minimum iOS requirement is 12.0. This tool will change your iOS deployment target to 12.0. Do you want to continue? … yes
› Updating your project...
android.mainApplication: withDefaultBaseMods ➜ withAndroidBaseMods ➜ withGeneratedBaseMods ➜ withAndroidMainApplicationBaseMod
android.mainApplication: 
android.mainActivity: withDefaultBaseMods ➜ withAndroidBaseMods ➜ withGeneratedBaseMods ➜ withAndroidMainActivityBaseMod
android.mainActivity: 
android.settingsGradle: withDefaultBaseMods ➜ withAndroidBaseMods ➜ withGeneratedBaseMods ➜ withAndroidSettingsGradleBaseMod
android.settingsGradle: 
ios.dangerous: withDefaultBaseMods ➜ withIosBaseMods ➜ withGeneratedBaseMods ➜ withIosDangerousBaseMod
ios.dangerous: 
ios.dangerous: 
ios.dangerous: 

ios.dangerous: 
ios.xcodeproj: withDefaultBaseMods ➜ withIosBaseMods ➜ withGeneratedBaseMods ➜ withIosXcodeprojBaseMod
ios.xcodeproj: 
ios.appDelegate: withDefaultBaseMods ➜ withIosBaseMods ➜ withGeneratedBaseMods ➜ withIosAppDelegateBaseMod
ios.appDelegate: 
› Installing expo packages...
> yarn add expo@>=44.0.0-0 <45.0.0
Uncaught Error Error: spawn yarnpkg ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn yarnpkg',
  path: 'yarnpkg',
  spawnargs: [ 'add', 'expo@>=44.0.0-0 <45.0.0' ],
  pid: undefined,
  output: [ '', '' ],
  stdout: '',
  stderr: '',
  status: null,
  signal: null
}

### Reproducible demo or steps to reproduce from a blank project

Run

 EXPO_DEBUG=true npx install-expo-modules 
 
 Not sure what other info is relevent for debug

**Comment by Kudo** [comment]
hi there! can you double check whether `yarn` is installed in your environment? you can use `npm install -g yarn` to install it. we did support npm as well. however, if your project has `yarn.lock` file, we will try to use yarn for adding expo packages.

**Comment by ToyboxZach** [comment]
That was it, I had a yarn.lock but not yarn installed.
