### ISSUE TITLE
@expo/next-adapter breaks debugging next.js server-side

### ISSUE THREAD

**Issue by zksward** [expo/expo-cli#4278]
### Summary

I'm using @expo/next-adapter in a monorepo basically unmodified from here: https://github.com/nandorojo/solito/tree/master/example-monorepos/blank

Inside `app/next/pages/api` I have a simple hello.js

![image](https://user-images.githubusercontent.com/38945511/160149066-9ea89cb0-d1a8-4d1f-a859-b67e75c661c8.png)

When I'm trying to debug the server side next.js endpoints I can only attach breakpoints to a transpiled(?) version that looks like this

![image](https://user-images.githubusercontent.com/38945511/160156509-5c61c88a-08d1-4ab1-bc08-eda17cc80bf2.png)

I'm only able to find that file by using console.log to give me something in the debug console to link to. This problem only arises when using `withExpo` in my next.config.js.

### Environment

```
expo-env-info 1.0.2 environment info:
  System:
    OS: Windows 10 10.0.22000
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

web?

### Reproducible demo or steps to reproduce from a blank project

1. Use https://github.com/nandorojo/solito/tree/master/example-monorepos/blank to get a monorepo with next and expo
2. Run `yarn` from the root
3. Add `/api/hello.js` to `apps/next/pages`
4. Debug next.js

**Comment by kennym** [comment]
I would like to bump this as this affects me, too. What can be done to fix this?
