### ISSUE TITLE
Transformer.transform is not a function

### ISSUE THREAD

**Issue by yasin459** [expo/expo-cli#4279]
i've been working with expo for a while, and I used to get builds by using :

eas build --profile=test --platform=android

but yesterday I tried to make a new build using above command but I got an error in "run gradelw":

> [stderr] Error: @build-script-error-begin
[stderr] Error loading assets JSON from Metro. Ensure you've followed all expo-updates installation steps correctly. index.js: Transformer.transform is not a function
[stderr] @build-script-error-end
[stderr]     at /home/expo/workingdir/build/node_modules/expo-updates/scripts/createManifest.js:39:11
> Task :app:createReleaseExpoManifest FAILED
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:createReleaseExpoManifest'.
[stderr] > Process 'command 'node'' finished with non-zero exit value 1
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info
[stderr] or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 1m 52s
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings
145 actionable tasks: 145 executed
Error: Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.

I checked my package.json and package.lock .json and "metro-config" and "@expo/metro-config" versions were the same for the current branch and the branch which was older( and we had fine builds on them). 

so I suppose that something in the expo might have changed that caused this error in build.
I appreciate any help

**Comment by EvanBacon** [comment]
This is a JS bundling error that is being surfaced up through the build https://github.com/facebook/react-native/issues/29301 I'd recommend running `expo export --experimental-bundle` or related bundling command in order to reproduce the error in a much simpler way. From there you can debug what JS error you are encountering.
