### ISSUE TITLE
Expo Project is not showing 

### ISSUE THREAD

**Issue by Lmmerciano** [expo/expo-cli#4280]
My expo project is not loading properly in the testing environment in the web application.  The name of the project appears on the web tab but the project itself is not loading. The developer tools are running correctly. 
![expo web complete](https://user-images.githubusercontent.com/98420196/160455825-b1a5ab37-726c-4b1d-b369-828eaa480a19.PNG)

**Comment by brentvatne** [comment]
check the chrome dev tools - do you see an error? it's possible there is a runtime exception and so your application isn't rendering
