### ISSUE TITLE
JavaScript engine configuration is inconsistent between app.json and iOS native project

### ISSUE THREAD

**Issue by dereknelson** [expo/expo-cli#4283]
### Summary
Ironically, the error is inconsistent not the configuration!
if the app.json has hermes, the error says app.json has hermes enabled and native does not.
if app.json has jsc, it says app.json does not have hermes enabled but native does have hermes enabled.

### Environment

```
  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
      Yarn: 1.22.18 - /opt/homebrew/bin/yarn
      npm: 8.1.1 - ~/.nvm/versions/node/v14.15.1/bin/npm
      Watchman: 2022.03.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8092744
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: >=44.0.0-0 <45.0.0 => 44.0.6 
      react: 17.0.2 => 17.0.2 
      react-native: 0.66.3 => 0.66.3 
    npmGlobalPackages:
      eas-cli: 0.44.1
      expo-cli: 5.0.3
    Expo Workflow: bare
```

### Please specify your device/emulator/simulator platform, model and version

this is a CLI issue

### Error output

app.json:
```
{
  "expo": {
    "jsEngine": "hermes",
    "ios": {
      "jsEngine": "hermes"
    }
  }
}
```
ios/Podfile.properties.json:
```
{
	"expo.jsEngine": "hermes"
}
```
Podfile:
`use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true)`

Results in 
```
JavaScript engine configuration is inconsistent between app.json and iOS native project.
In app.json: Hermes is enabled
In iOS native project: Hermes is not enabled
```
If I modify the app.json to have `"jsEngine": "jsc"`
The error becomes:
```
JavaScript engine configuration is inconsistent between app.json and iOS native project.
In app.json: Hermes is not enabled
In iOS native project: Hermes is enabled
```

### Reproducible demo or steps to reproduce from a blank project

ran expo publish on my project

**Comment by Kudo** [comment]
i am sorry we didn't support much format from our regular expression here.
https://github.com/expo/expo-cli/blob/cdb715365bab7f735200c32971437de187a9953d/packages/dev-server/src/HermesBundler.ts#L185
please try to have `:hermes_enabled => true` in a separated line 😅

**Comment by dereknelson** [comment]
@Kudo that worked! thanks

**Comment by wassgha** [comment]
Could we add 
```
:hermes_enabled => flags[:hermes_enabled] || podfile_properties['expo.jsEngine'] == 'hermes',
```
 as valid regex as well? @Kudo

**Comment by Kudo** [comment]
@wassgha good catch! we've published `expo-cli@5.4.6` with the fix. please take a look when you get a chance. thanks!

**Comment by wassgha** [comment]
Working correctly now, thanks @Kudo

**Comment by mercurio236** [comment]
working for me
`"expo": {
  "android": {
    "hermesEnabled": true
  }
}`
