### ISSUE TITLE
Expo eject blocked at choosing android name project 

### ISSUE THREAD

**Issue by anisamirouche** [expo/expo-cli#4287]
### Summary

I'm trying to eject an app freshly created with expo init without any changes unsuccessfully, nothing happens after typing android package name.
I've tried com.user.app, com.app , something.com but nothing worked.

### Environment

 System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.5.5 - /usr/local/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 28, 29, 30, 31
        Build Tools: 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 32.0.0
        System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.3.0
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

iPhon 13 (iOS 15.4)

### Reproducible demo or steps to reproduce from a blank project
I also tried with expo-cli version 4.13.0 and version 3.28.6
expo init 
expo eject

**Comment by kbrandwijk** [comment]
`expo eject` is a deprecated command, I would advise you to try `expo prebuild` instead.

**Comment by anisamirouche** [comment]
> `expo eject` is a deprecated command, I would advise you to try `expo prebuild` instead.

i just tried it , it's the same nothing happens

**Comment by brentvatne** [comment]
hi there! you are using a very old version of expo-cli. please upgrade to the latest - 5.3.0 at the time of writing.

**Comment by anisamirouche** [comment]
> hi there! you are using a very old version of expo-cli. please upgrade to the latest - 5.3.0 at the time of writing.

Have You Seen m'y configuration ? Well i'm using 5.3.0

**Comment by brentvatne** [comment]
hi there! please share a reproducible example and i'm happy to investigate further. if you share a link to a github repo i can clone and run `expo prebuild` where this doesn't work i can look

**Comment by anisamirouche** [comment]
> hi there! please share a reproducible example and i'm happy to investigate further. if you share a link to a github repo i can clone and run `expo prebuild` where this doesn't work i can look
> 
> i closed the issue because `expo prebuild` works and is run many times per minute every day in order to generate builds on EAS Build in addition to locally for `expo run` and directly. the steps provided did not reproduce any issue

I mentioned everything in my question, that i tried expo prebuild and it doesn't work, i also chnaged thé computer and it still doesn't work, i tried with thé three expo versions mentionned in the question , and for reproductible example
I also mentionned, all You have to do is run expo init something and then expo eject, the easiest solution is to close the issue

**Comment by brentvatne** [comment]
@anisamirouche - i cannot reproduce by following the exact steps outlined in your issue.

<img width="983" alt="image" src="https://user-images.githubusercontent.com/90494/162848926-d8d533e7-2984-45ad-821e-c704c6c0fea3.png">

**Comment by anton-chikunov** [comment]
@anisamirouche I had same issue, but when I tried `expo prebuild` together with VPN, it solves the problem
