### ISSUE TITLE
IOS & Andoird builds get stuck on the splash screen without crashing the app

### ISSUE THREAD

**Issue by RostyslavStihailo** [expo/expo-cli#4291]
### Summary

So we need to add the Stripe integration to our application. We found the library (@stripe/stripe-react-native) for that and went through all the [installation docs](https://docs.expo.dev/versions/latest/sdk/stripe/ ). Locally app works great with stripe methods, but whenever we try to build it, the app gets stuck on the splash screen without crashes. Building it with expo build:android & eas for ios,
 also I think the problem is with expo cuz found exactly the same issue but without using [stripe](https://stackoverflow.com/questions/70724246/react-native-expo-build-apk-installed-but-frozen-in-splash-screen) 
 EAS config for ios build:
 {
  "build": {
    "release": {
      "releaseChannel": "production",
      "env": {
        "STAGE": "production"
      }
    },
    "preview": {
      "node": "14.17.6",
      "releaseChannel": "staging",
      "distribution": "internal",
      "ios": {
        "simulator": true
      },
      "android": {
        "buildType": "apk",
        "withoutCredentials": true,
        "gradleCommand": ":app:assembleDebug"
      },
      "env": {
        "STAGE": "staging"
      }
    },
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "env": {
        "STAGE": "development"
      }
    }
  },
  "cli": {
    "version": ">= 0.48.2"
  }
}

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.6 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
      Watchman: 2021.12.20.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        API Levels: 23, 28, 29, 30, 31
        Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
        System Images: android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: 44.0.4 => 44.0.4 
      react-native: 0.64.3 => 0.64.3 
    npmGlobalPackages:
      eas-cli: 0.48.2
      expo-cli: 5.3.0
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

iphone 11, android emulator 

### Reproducible demo or steps to reproduce from a blank project

import React from "react";
import { StripeProvider as Provider } from "@stripe/stripe-react-native";

const StripeProvider = ({ children }) => {
  return (
    <Provider publishableKey={'pk_test_51KMT0nJhQebyUemSzoiClPvkdg8tn1zRS8zrbISk0LeAWWD3bMfFUsj12E38BD5zvEtVP1gHMfU5wDwb3bCL3Vp400xxxxxxxxx'}>
      {children}
    </Provider>
  );
};

export default StripeProvider;

**Comment by brentvatne** [comment]
more info: https://expo.fyi/splash-screen-hanging

please post to https://github.com/expo/expo/issues with a reproducible example if you believe you have found a bug

**Comment by BerkeAras** [comment]
@RostyslavStihailo Same issue when using StripeProvider :(
