### ISSUE TITLE
[ custom dev client ] impossible to install on simulator

### ISSUE THREAD

**Issue by actuallymentor** [expo/expo-cli#4292]
## Issue description

According to [this docs page](https://docs.expo.dev/development/build/), using native code config plugins requires:

```
eas device:create
eas build --profile development --platform ios
```

And then `and installing the resulting build on your device.`.

However, the install link triggers a "Check your homescreen" message, but installs nothing (see screenshot).

![simulator_screenshot_3C314620-5DF4-4501-BA94-531803DE9CEC](https://user-images.githubusercontent.com/9071382/162151032-22e321d1-055f-44eb-9abd-1273ad08bb91.png)

In [expo issue #15501](https://github.com/expo/expo/issues/15501) I read that the expected behaviour is a popup like this:

<img width="546" alt="image" src="https://user-images.githubusercontent.com/9071382/162151312-4c8ed437-7db9-4b0c-83c1-fe13f876c83e.png">

This however does not happen.

---

## Notes on UDID

The expo issue 15501 mentions device UDID, for which I have registered the macbook running the simulator using `system_profiler SPHardwareDataType | grep "Provisioning UDID"` (maybe add that one to the docs, since the "register device" urls also do not work in simulators).

Note that everything works fine with `expo run:ios -d`, the client builds, installs and runs perfectly. However in [eas cli issue #1050](https://github.com/expo/eas-cli/issues/1050#issuecomment-1090417123) it was pointed out to me that with config plugins I should not need to eject (which is a consequence of `expo run:ios -d` as I understand it).

### Environment

```
expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.14.0/bin/yarn
      npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8139111
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.48.2
      expo-cli: 5.3.0
    Expo Workflow: bare
```

### Please specify your device/emulator/simulator platform, model and version

simulator, all.

### Error output

Error: The development client (xxx.xxx.xxx) for this project is not installed. Please build and install the client on the simulator first.

### Reproducible demo or steps to reproduce from a blank project

N/A

**Comment by kbrandwijk** [comment]
Have you included `"simulator": true` in your build profile?

**Comment by actuallymentor** [comment]
No. I tried now and it errors:

```
Error: eas.json is not valid [ValidationError: "build.development.simulator" is not allowed]
```

Additionally, this is mentioned [nowhere on the relevant docs page](https://docs.expo.dev/development/getting-started/#developing-your-app).

**Comment by kbrandwijk** [comment]
This is an iOS only option: https://docs.expo.dev/build-reference/eas-json/#simulator.

More details are in the documentation here: https://docs.expo.dev/build-reference/simulators/#configuring-a-profile-to-build-for-simulators

**Comment by Norfeldt** [comment]
Here is the build that worked for me.

```
"build": {
    "local-simulator": {
      "releaseChannel": "local-simulator",
      "ios": {
        "simulator": true
      }
    },
```

Then I downloaded it, unpacked it and dragged it onto my simulator 🤙.
