### ISSUE TITLE
expo start --host tunnel not support hot reload

### ISSUE THREAD

**Issue by gengjiawen** [expo/expo-cli#4298]
### Summary

to fix https://github.com/expo/expo-cli/issues/3880. 
I found expo support ngrok, It worked like a charm. But it doesn't support hot reload ? Is this a known limitation ?

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: Linux 5.16 Ubuntu 20.04.3 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 17.9.0 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/bin/yarn
      npm: 8.5.5 - /usr/local/bin/npm
    SDKs:
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.3
        System Images: android-21 | Google APIs ARM EABI v7a
        Android NDK: 21.4.7075529
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

android with expo-go

### Reproducible demo or steps to reproduce from a blank project

Open https://github.com/gengjiawen/expo-gitpod, click the badge.
When opened, run `yarn gitpod`, scan the qrcode, edit something and check hot reload.

**Comment by EvanBacon** [comment]
Cannot repro using the new `npx expo start`. There are no known limitations as all connections are forwarded through ngrok.

**Comment by gengjiawen** [comment]
> Cannot repro using the new `npx expo start`. There are no known limitations as all connections are forwarded through ngrok.

https://github.com/gengjiawen/expo-gitpod hot-reload works on your side ?

**Comment by gengjiawen** [comment]
<img width="320" alt="image" src="https://user-images.githubusercontent.com/3759816/198183053-2cc0ed76-0c63-4118-b29c-44f2d3fd547c.png">

I just tried, still not working on my side, I have type `r` on every change.
