### ISSUE TITLE
"Starting project at ..." get stuck

### ISSUE THREAD

**Issue by giojkd** [expo/expo-cli#4314]
### Summary

Just installed expo-cli initiated a new project but it get stuck at "Starting project"

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.2 - /usr/local/bin/node
      npm: 8.7.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.3.1
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

emulator

### Error output

Don't get any error I was just expeting the qrcode as usual but this time dind't come

### Reproducible demo or steps to reproduce from a blank project

Just installed expo-cli initiated a new project but it get stuck at "Staring project"

**Comment by EvanBacon** [comment]
This appears to be resolved in the latest, versioned Expo CLI. If you encounter this issue in the future, please open an issue on [expo/expo](https://github.com/expo/expo/issues/new?assignees=&labels=needs+review%2CCLI&template=bug_report_cli.yml).
