### ISSUE TITLE
expo customize:web doesn't work

### ISSUE THREAD

**Issue by Benoit-ROBIN** [expo/expo-cli#4319]
### Summary

I create project with create-react-native-app with typescript template.
I eject the app.
I tried to generate `web/index.html` to customize it with the command `expo customize:web`.
When I select `web/index.html`, the terminal prompt `Exiting with no change...`

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v14.17.0/bin/yarn
      npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
      Watchman: 2021.11.15.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/benoitrobin/.rvm/gems/ruby-2.7.2/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 28, 29, 30, 31
        Build Tools: 29.0.2, 30.0.2, 31.0.0
        System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

macOS 11.6

### Error output

Exiting with no change...

### Reproducible demo or steps to reproduce from a blank project

run `expo eject`
run `expo customize:web` 
and select `web/index.html`

**Comment by mohity777** [comment]
Hey how did u fix it ?

**Comment by eleddie** [comment]
@mohity777 I was able to make it work, here's how:
1. Run `expo customize:web`
2. Use the arrows to select the option
Here I used to press Enter and I got `Exiting with no change...`, instead, press the space bar and then hit enter.

That worked for me
