### ISSUE TITLE
Flags `--android-package` and `--ios-bundle-identifier` of `init` command not updating app.json

### ISSUE THREAD

**Issue by geoffreyvanwyk** [expo/expo-cli#432]
## Description

The `--android-package` and `--ios-bundle-identifier` flags of the `init` command do not set the corresponding properties in **app.json**.

## Expected Behavior

When passing the `--android-package com.expo.test` and `--ios-bundle-identifier com.expo.test` flags to the `init` command, the `expo.android.package` and `expo.ios.bundleIdentifier` properties, respectively, should both be set to `"com.expo.test"` all in **app.json**.

## Observed Behavior

When passing the `--android-package com.expo.test` and `--ios-bundle-identifier com.expo.test` flags to the `init` command, the `expo.android.package` and `expo.ios.bundleIdentifier` properties, respectively, do not appear at all in **app.json**.

## Environment

Output of `expo diagnostics`: 

>   Expo CLI 2.11.9 environment info:
>     System:
>       OS: Windows 10
>     Binaries:
>       Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
>       npm: 6.5.0 - C:\Program Files\nodejs\npm.CMD
>     IDEs:
>       Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842

**Comment by AdamJNavarro** [comment]
Hey @systemovich,

Sorry for the slow follow-up here. I just repro'd this and hopefully we can get to investigating soon.

Cheers,
Adam

**Comment by EvanBacon** [comment]
I believe we've removed this feature, the current interactive flow is much better suited for assigning bundle ID and package name since it does fetch requests to check if they're currently in use.
