### ISSUE TITLE
Error when installing react-native-svg

### ISSUE THREAD

**Issue by atroudi** [expo/expo-cli#4328]
### Summary

Faced the below error when trying to install react-native-svg package:

### Environment

 expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 17.9.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.5.5 - /usr/local/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 9.0.2 => 9.0.2 
      expo: ^44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.3.0
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

Macos Big sur

### Error output

error An unexpected error occurred: "https://registry.yarnpkg.com/@react-native-async-storage%2fasync-storareact-native-svgge: Not found".

### Reproducible demo or steps to reproduce from a blank project

expo install react-native-svg

**Comment by kbrandwijk** [comment]
I'm unable to reproduce this locally on SDK 44. Can you share the full output of the command? 
![image](https://user-images.githubusercontent.com/852069/164998869-50188403-08f9-441c-93f4-649ec393586c.png)

**Comment by atroudi** [comment]
expo install react-native-svg
WARNING: expo-cli has not yet been tested against Node.js v17.9.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <13.0.0 (Maintenance LTS)
* >=14.0.0 <15.0.0 (Active LTS)
* >=15.0.0 <17.0.0 (Current Release)

┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│   There is a new version of expo-cli available (5.3.2).                 │
│   You are currently using expo-cli 5.3.0                                │
│   Install expo-cli globally using the package manager of your choice;   │
│   for example: `npm install -g expo-cli` to get the latest version      │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘
Installing 1 SDK 44.0.0 compatible native module using Yarn.
> yarn add react-native-svg@12.1.1
yarn add v1.22.17
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
info If you think this is a bug, please open a bug report with the information provided in "/Users/anistroudi/IdeaProjects/Taame/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
error An unexpected error occurred: "https://registry.yarnpkg.com/@react-native-async-storage%2fasync-storareact-native-svgge: Not found".
yarnpkg exited with non-zero code: 1
Error: yarnpkg exited with non-zero code: 1
    at ChildProcess.completionListener (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (node:events:642:26)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1090:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:715:12)
    ...
    at Object.spawnAsync [as default] (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at YarnPackageManager._runAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/package-manager/src/NodePackageManagers.ts:323:31)
    at YarnPackageManager.addWithParametersAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/package-manager/src/NodePackageManagers.ts:268:16)
    at actionAsync (/usr/local/lib/node_modules/expo-cli/src/commands/installAsync.ts:141:3)

**Comment by kbrandwijk** [comment]
This is an error from `yarn`, and an issue on your local machine. This issue seems to have nothing to do with `expo-cli`, as `yarn` is correctly called. Try clearing your cache, or running `yarn add` directly to see if you get the same error. If you can reproduce that this issue _only_ happens when running `expo install`, then please report back and we can reopen the issue.
