### ISSUE TITLE
NPM found 27 vulnerabilities after first installation

### ISSUE THREAD

**Issue by lumenier1** [expo/expo-cli#4330]
I've just updated NodeJS and installed expo-cli from scratch but NPM lashes out at 27 vulnerabilities.

`27 vulnerabilities (10 moderate, 17 high)`

Is it normal? And how to avoid it for the first installation?

NodeJS: v16.14.2
NPM: 8.5.0
OS: MacOS

**Comment by manohar4** [comment]
Me too

@lumenier1 found any solution?

**Comment by kbrandwijk** [comment]
Yes, this is fairly normal, as you know, npm is a tangled web of nested dependencies, there's bound to be a vulnerability _somewhere_ in the tree. However, this is a CLI tool, that you use locally, that is not part of your actual app, so that makes it not really relevant.
