### ISSUE TITLE
HELP! expo build:ios shipped an unwanted javascript update to my users

### ISSUE THREAD

**Issue by jakehasler** [expo/expo-cli#4336]
### Summary

Yesterday I ran `expo build:ios --release-channel prod` to create a build for testflight.

When I did this, expo hot-pushed the unwanted javascript code to my users without my knowledge or consent.

I do not have 'updates' enabled on my account. I cannot even see them in my sidebar.

<img width="449" alt="image" src="https://user-images.githubusercontent.com/10869870/165634022-6c0ae8fb-b9c6-4dc2-afc6-dcc5cd3fc3dd.png">

### Environment

```
expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.13.0 - ~/.asdf/shims/node
      npm: 8.1.0 - ~/.asdf/shims/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0 => 43.0.1
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.2 => 0.64.2
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      expo-cli: 5.2.0
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

iPhone 13

### Error output

N/A

### Reproducible demo or steps to reproduce from a blank project

I don't think this is relevant, as there were no errors in my console.

**Comment by brentvatne** [comment]
`expo build:ios` will publish an ota update and then build from that. if you want to revert the update, you can roll it back https://docs.expo.dev/distribution/advanced-release-channels/#publish-rollback

note that EAS Build does not have this behavior and we recommend [moving to it](https://docs.expo.dev/build-reference/migrating/). [SDK 46 will be the last version to support the classic build service](https://blog.expo.dev/turtle-goes-out-to-sea-d334db2a6b60)

**Comment by jakehasler** [comment]
@brentvatne I really appreciate it. Sorry to cause an alarm from my own ignorance. I should have known that's what the cli does.

I'll look at getting moved to EAS asap. Thanks for the help!

**Comment by brentvatne** [comment]
nice, good luck!
