### ISSUE TITLE
Ios Build SKD version Outdated

### ISSUE THREAD

**Issue by braamrichardchristopher** [expo/expo-cli#4342]
### Summary

Getting this error

This app was built with the iOS 14.1 SDK. All iOS apps submitted to the App Store must be built with the iOS 15 SDK or later, included in Xcode 13 or late

### Environment

 System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 23
        Build Tools: 32.0.0
        System Images: android-23 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7935034
    npmPackages:
      expo: ~41.0.0 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ^0.17.0 => 0.17.0

### Please specify your device/emulator/simulator platform, model and version

Version 41.0.0 => 41.0.1

### Error output

This app was built with the iOS 14.1 SDK. All iOS apps submitted to the App Store must be built with the iOS 15 SDK or later, included in Xcode 13 or late

### Reproducible demo or steps to reproduce from a blank project

Building IOS .ipa

**Comment by kbrandwijk** [comment]
You need to update to SDK 43 or above to build your app with the latest XCode/iOS SDK version, which is now required by the App Store. See the [release post](https://blog.expo.dev/expo-sdk-43-aa9b3c7d5541) for SDK 43 for details on upgrading.

**Comment by elie-chaaban** [comment]
![image](https://user-images.githubusercontent.com/29852821/226111241-a14d5287-d3ea-4a2f-a7f7-bf8dfca55fe3.png)

I had expo sdk 45 and now I upgraded to sdk47 and now I get this

**Comment by Lamonarch87** [comment]
> ![image](https://user-images.githubusercontent.com/29852821/226111241-a14d5287-d3ea-4a2f-a7f7-bf8dfca55fe3.png)
> 
> I had expo sdk 45 and now I upgraded to sdk47 and now I get this @kbrandwijk

Mee too. Same message. I submitted a build around 1 month ago with the same expo SDK (47) and the same environment build but was ok.

I'm searching for a solution but i didn't find anything. I'll try to build specifying an older environment in eas.json but i don't know if it can work.

**Comment by elie-chaaban** [comment]
Does it get rejected if we submit it?

**Comment by Lamonarch87** [comment]
> Does it get rejected if we submit it?

I only submitted for TestFlight, and on TestFlight it is working. I don't know what that issue may cause so i'm not so confident to submit to the store...

**Comment by Lamonarch87** [comment]
> Same

In my opinion is an Apple issue. They are saying us that we're using v16.0 but we need 15 or later...it's weird...
