### ISSUE TITLE
"Npm run ios" Bug on expo 45.0  when it build infinite installed Error

### ISSUE THREAD

**Issue by Luceta** [expo/expo-cli#4350]
### Summary

like below screenshot, when i command "npm run ios" ,  it just stopped even finished to install on simulator .

<img width="568" alt="image" src="https://user-images.githubusercontent.com/57941164/167257914-214777ea-4729-4e45-8e56-a8cc83412dcc.png">

in this situation , i press "i" to open simulator on app. like below picture, it manually finsihed to install and open it on app! not automatically installed and open on simulator.
<img width="382" alt="image" src="https://user-images.githubusercontent.com/57941164/167258004-477fad33-919e-47b3-9656-7aec835e5f1e.png">

 Mac Os :12.3.1
 X code: 13.31
<img width="306" alt="image" src="https://user-images.githubusercontent.com/57941164/167258030-d5134d50-ee67-43f9-83cf-75c949287dc8.png">
but if i downgrade on package.json , "expo": "~44.0.2",  it should be automatically installed and open app on simulator and build.

please check it the  45.00 version 

### Environment

After"npx create-react-native-app ",
"npm run ios"

### Please specify your device/emulator/simulator platform, model and version

Mac Os :12.3.1  X code: 13.31 pod : 1.11.3

### Error output

Not error but, it not automaticllly build so it should be press i to open simulator again and to build.

### Reproducible demo or steps to reproduce from a blank project

<img width="290" alt="image" src="https://user-images.githubusercontent.com/57941164/167258323-974b0464-ca93-4428-afc4-7be66e3d8251.png">

**Comment by EvanBacon** [comment]
This appears to be resolved in the latest, versioned Expo CLI. If you encounter this issue in the future, please open an issue on [expo/expo](https://github.com/expo/expo/issues/new?assignees=&labels=needs+review%2CCLI&template=bug_report_cli.yml).
