### ISSUE TITLE
Issue on using new expo sdk 45. 

### ISSUE THREAD

**Issue by bandhavya** [expo/expo-cli#4356]
### Summary

Im seeing the below error on expo eject

<img width="884" alt="Screenshot 2022-05-09 at 6 18 38 PM" src="https://user-images.githubusercontent.com/12510202/167413091-318ee6a4-dcf4-4fe4-bf43-9ff29f1c8413.png">

My package.json

`"dependencies": {
    "axios": "^0.21.1",
    "expo": "~45.0.1",
    "expo-font": "~10.0.3",
    "expo-camera": "^12.0.3",
    "expo-av": "^10.2.1",
    "expo-barcode-scanner": "^11.1.2",
    "expo-web-browser": "^10.0.3",
    "expo-device": "^4.0.3",
    "expo-network": "^4.0.3",
    "expo-location": "^13.0.4",
    "expo-contacts": "^10.0.3",
    "expo-calendar": "^10.0.3",
    "expo-splash-screen": "^0.13.5",
    "expo-document-picker": "^10.1.3",
    "hermes-engine": "0.7.2",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.1",
    "react-native-web": "~0.17.5",
    "@react-native-async-storage/async-storage": "^1.15.14",
    "react-native-bundle-splitter": "^2.1.0",
    "react-native-safe-area-context": "3.3.2",
    "@react-native-community/datetimepicker": "^3.5.2",
    "@react-native-community/slider": "^3.0.3",
    "@react-native-picker/picker": "^1.16.3",
    "react-native-circular-progress": "^1.3.7",
    "@react-native-community/masked-view": "^0.1.10",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "^12.1.1",
    "@react-navigation/native": "^6.0.0",
    "react-native-pager-view": "^5.2.1",
    "react-native-vector-icons": "~8.1.0",
    "expo-status-bar": "~1.3.0"
  },
  "devDependencies": {
    "react-devtools-core": "4.14.0",
    "@babel/cli": "^7.14.5",
    "@babel/core": "^7.12.9"
  },`

I had just update the  "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.1" versions and on expo eject facing this issue.

How to resolve this ?

Tried few approaches specified in few blogs but nothing worked.

### Environment

<img width="1120" alt="Screenshot 2022-05-09 at 6 22 35 PM" src="https://user-images.githubusercontent.com/12510202/167413830-0c974597-eb2a-4707-bd95-6308e278cd14.png">

### Please specify your device/emulator/simulator platform, model and version

build on cmd line is failing

### Reproducible demo or steps to reproduce from a blank project

This is replicable on ejecting the project. I had updated the xcode recently to 13.0 version. Also updated expo sdk to 45 for java 11 support, expo-cli is updated to latest 5.4.3. 
<img width="1120" alt="Screenshot 2022-05-09 at 6 28 30 PM" src="https://user-images.githubusercontent.com/12510202/167414954-49bedff4-0993-4ee2-9b37-45d7053bf8fa.png">

**Comment by ScreamZ** [comment]
@kbrandwijk Thanks for the tips, found that stripe react native is also stale, will update and report to them

**Comment by wyattberlinic** [comment]
Dug into this more. It's possible to use yarn resolutions to force the package version.

```
"resolutions": {
    "@expo/config-plugins": "^4.1.0"
}
```

**Comment by bandhavya** [comment]
@wyattberlinic that means to update the packages to the latest we must provide the resolutions object as you have mentioned above ?

**Comment by kbrandwijk** [comment]
> Seems like almost none of the `expo-*` packages have bumped to support the new version of config plugins so we really can't upgrade until this PR goes through: [expo/expo#17367](https://github.com/expo/expo/pull/17367)

That's not entirely correct. The existing `^4.0.14` that is in most packages will also resolve to 4.1.4 if your lockfile doesn't prevent it.

**Comment by ScreamZ** [comment]
> @wyattberlinic that means to update the packages to the latest we must provide the resolutions object as you have mentioned above ?

This is a global override directive. This is a workaround meant to patch all packages, waiting for the packages to update their version.

**Comment by wyattberlinic** [comment]
Oh, I understand now. Basically, the issue is my `yarn.lock` specified that the transitive dep on `@expo/config-plugins: 4.0.16`. The "correct" way to get it to update would be to follow [this comment](https://github.com/yarnpkg/yarn/issues/4986#issuecomment-395036563) (delete the `@expo/config-plugins` entry, re-run yarn).

The way I fixed it is another way to achieve the same, which is to use the `resolutions` block to force yarn to update the locked deps. You can then remove the resolutions block after the first exec of `yarn`.
