### ISSUE TITLE
Unable to build Android using expo build:android

### ISSUE THREAD

**Issue by JoyMetildaRani** [expo/expo-cli#4357]
### Summary

expo start gives the output but expo build:android throws the output as Unsupported SDK version: our app builders do not support SDK version 45, yet. The latest SDK version is 45.0.0.
Unsupported SDK version

### Environment

 expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~45.0.0 => 45.0.2
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.1 => 0.68.1
      react-native-web: 0.17.7 => 0.17.7
      react-navigation: ^4.4.4 => 4.4.4
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

node.js

### Error output

Unsupported SDK version: our app builders do not support SDK version 45, yet. The latest SDK version is 45.0.0.
Unsupported SDK version

### Reproducible demo or steps to reproduce from a blank project

i have only problem in expo build. it is not creating node modules folder

**Comment by EvanBacon** [comment]
This is now resolved
