### ISSUE TITLE
[EAS] "eas build" command results in "TypeError"

### ISSUE THREAD

**Issue by todorone** [expo/expo-cli#4360]
### Summary

I have 2 computers and for the same project on one of them `eas build` command works as expected(x86 arch), while on the second one(M1 processor) executing the same command results in error:
```
TypeError: (0 , prebuild_config_1.getPrebuildConfigAsync) is not a function
```

### Environment

    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.18 - /opt/homebrew/bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
      Watchman: 4.9.0 - /opt/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/lib/ruby/gems/3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        Android NDK: 21.3.6528147
    IDEs:
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

MacOS

### Error output

$ eas build -p ios --profile browserstack
- Linking to project @zzz
✔ Linked to project @zzz
    TypeError: (0 , prebuild_config_1.getPrebuildConfigAsync) is not a function

### Reproducible demo or steps to reproduce from a blank project

Unfortunately, i was not able to track the reason of an issue and it probably has nothing to do with the project itself, but to the runtime setup, bc it works on one laptop and does not work on another.

**Comment by wkozyra95** [comment]
How is eas-cli installed? if you used yarn please switch to npm for installing global packages, we have seen multiple times that yarn resolves dependencies incorrectly which might result in using an older version of the package e.g. one that does not have getPrebuildConfigAsync method

**Comment by todorone** [comment]
Thanks.

Yeah, it was globally installed and it was the problem.
Local installation fixed it.
It probably would nice to mention this as warning in eas cli installation section for better DX.

**Comment by wkozyra95** [comment]
eas-cli should not be installed locally, The issue you are most likely hitting is bug in yarn.
