### ISSUE TITLE
 Expo Go download bundle broken 

### ISSUE THREAD

**Issue by BloodyMonkey** [expo/expo-cli#4373]
### Summary

Since yesterday, bundle download from my PC went from seconds to SEVERAL MINUTES
It happened in the middle of the day when I had been working with it for hours…
This is working from a Mac.
It happens with any app, on any network, on Android (Samsung & Huawei) and iOS (iPhone & iPad)
I updated all my packages, node, npm, expo, …
What happening ??

### Environment

    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.10.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 23, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.1
        System Images: android-31 | Android TV Intel x86 Atom
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
    npmPackages:
      expo: ^44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: https://github.com/expo/react-native/archive/sdk-44.0.0.tar.gz => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Samsung, Huawei, iPhone 8+, iPad Pro

### Reproducible demo or steps to reproduce from a blank project

Impossible to reproduce

**Comment by EvanBacon** [comment]
I cannot reproduce this. Perhaps there was a server outage or intermittent connection issue.
