### ISSUE TITLE
Android Build Server Socket Bug Error

### ISSUE THREAD

**Issue by thevobos** [expo/expo-cli#4376]
### Summary

Expo build server is not working like better, today i get a warning message on EXPO CLI.

Checking if this build already exists...
Entity Not Found.

i checking the my build list on expo web page in my profil and i can't see any active build process. so i try to again and all time is return same issue

### Environment

expo build:android

### Please specify your device/emulator/simulator platform, model and version

android  build on mac

### Error output

thevobos@Cengizs-MacBook-Air gizerleroto % expo build:android               
┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│   There is a new version of expo-cli available (5.4.4).                 │
│   You are currently using expo-cli 5.4.3                                │
│   Install expo-cli globally using the package manager of your choice;   │
│   for example: `npm install -g expo-cli` to get the latest version      │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘

expo build:android has been superseded by eas build. Learn more: https://blog.expo.dev/turtle-goes-out-to-sea-d334db2a6b60

Run the following:

› npm install -g eas-cli
› eas build -p android https://docs.expo.dev/build/setup/

expo build:android will be discontinued on January 4, 2023 (233 days left).

✔ Choose the build type you would like: › app-bundle
Checking if there is a build in progress...

Accessing credentials for cengizakcan in project gizerleroto

› Expo SDK: 44.0.0
› Release channel: default
› Workflow: Managed

Building optimized bundles and generating sourcemaps...
Starting Metro Bundler
watchman warning:  opendir(/Users/thevobos/Library/Containers/com.apple.corerecents.recentsd/Data/Library/Recents) -> Operation not permitted. Marking this portion of the tree deleted
To clear this warning, run:
`watchman watch-del '/Users/thevobos' ; watchman watch-project '/Users/thevobos'`

Android Bundling complete 3533ms

Bundle                     Size
┌ index.ios.js          3.98 MB
├ index.android.js      3.98 MB
├ index.ios.js.map      10.3 MB
└ index.android.js.map  10.4 MB

💡 JavaScript bundle sizes affect startup time. Learn more: https://expo.fyi/javascript-bundle-sizes

Analyzing assets
Saving assets
No assets changed, skipped.

Processing asset bundle patterns:
- /Users/thevobos/Documents/CustomerProjects/gizerleroto/**/*
- /Users/thevobos/Documents/CustomerProjects/gizerleroto/**/**/*

Uploading JavaScript bundles
Publish complete

📝  Manifest: https://exp.host/@cengizakcan/gizerleroto/index.exp?sdkVersion=44.0.0 Learn more: https://expo.fyi/manifest-url
⚙️   Project page: https://expo.dev/@cengizakcan/gizerleroto?serviceType=classic&distribution=expo-go Learn more: https://expo.fyi/project-page

Checking if this build already exists...

Entity Not Found.

### Reproducible demo or steps to reproduce from a blank project

no because this is socket bug. reporting

**Comment by EvanBacon** [comment]
This appears to have been a server error which has since been resolved. Further, `expo build:android` has been deprecated in favor of `eas build -p android`.
