### ISSUE TITLE
SDK 45 iOS Build fails -> "could not locate a valid AppDelegate"

### ISSUE THREAD

**Issue by homosape** [expo/expo-cli#4380]
### Build/Submit details page URL

https://expo.dev/accounts/narisolutions/projects/delori-payments/builds/14becf86-b954-4673-8e8c-2ef64864cac9

### Summary

My iOS build on SDK 45 using EAS fails. Builds were fine before I upgraded to latest SDK.

my app.config.js

```
export default {
    owner: "narisolutions",
    name: IS_PRODUCTION ? "Delori Payments" : "Delori Payments Staging",
    slug: "delori-payments",
    privacy: "hidden",
    version: VERSION,
    orientation: "portrait",
    icon: IS_PRODUCTION ? "./app/assets/icon.png" : "./app/assets/icon-staging.png",
    plugins: ["sentry-expo"],
    platforms: ["ios", "android"],
    scheme: IS_PRODUCTION ? "delori-payments" : "delori-payments-staging",
    splash: {
        image: IS_PRODUCTION ? "./app/assets/splash.png" : "./app/assets/splash-staging.png",
        resizeMode: "contain",
        backgroundColor: "#ffffff",
    },
    hooks: {
        postPublish: [
            {
                file: "sentry-expo/upload-sourcemaps",
                config: {
                    organization: "xxxxx",
                    project: IS_PRODUCTION ? "delori-payments" : "delori-payments-staging",
                    authToken: "xxxxx",
                    release: `Android (${VERSION_CODE}), iOS (${BUILD_NUMBER})`,
                    distribution: VERSION,
                },
            },
        ],
    },
    updates: {
        checkAutomatically: "ON_ERROR_RECOVERY",
        fallbackToCacheTimeout: 0,
    },
    assetBundlePatterns: ["**/*"],
    ios: {
        supportsTablet: false,
        bundleIdentifier: IS_PRODUCTION ? "io.delori.payments" : "io.delori.payments.staging",
        infoPlist: {
            CFBundleAllowMixedLocalizations: true,
            NSFaceIDUsageDescription: "FaceID is only used to securely sign into the app.",
        },
        jsEngine: "hermes",
        buildNumber: BUILD_NUMBER,
        associatedDomains: [
            IS_PRODUCTION ? "applinks:links.delori.io" : "applinks:links-staging.delori.io",
        ],
    },
    android: {
        adaptiveIcon: {
            foregroundImage: IS_PRODUCTION
                ? "./app/assets/adaptive-icon.png"
                : "./app/assets/adaptive-icon-staging.png",
            backgroundColor: "#FFFFFF",
        },
        package: IS_PRODUCTION ? "io.delori.payments" : "io.delori.payments.staging",
        permissions: ["VIBRATE"],
        versionCode: VERSION_CODE,
        softwareKeyboardLayoutMode: "pan",
        jsEngine: "hermes",
        intentFilters: [
            {
                action: "VIEW",
                data: [
                    IS_PRODUCTION
                        ? {
                              scheme: "https",
                              host: "links.delori.io",
                              pathPrefix: "/delori-payments",
                          }
                        : {
                              scheme: "https",
                              host: "links-staging.delori.io",
                              pathPrefix: "/delori-payments",
                          },
                ],
                category: ["BROWSABLE", "DEFAULT"],
            },
        ],
        googleServicesFile: IS_PRODUCTION
            ? "./app/config/google-services.json"
            : "./app/config/google-services-staging.json",
    },
    web: {
        favicon: "./app/assets/favicon.ico",
    },
    extra: {
        API_URL_STAGING: process.env.API_URL_STAGING,
        API_URL_PRODUCTION: process.env.API_URL_PRODUCTION,
        FIRESTORE_EMULATOR_HOST: process.env.FIRESTORE_EMULATOR_HOST,
        FIREBASE_AUTH_EMULATOR_HOST: process.env.FIREBASE_AUTH_EMULATOR_HOST,
    },
};

```

### Managed or bare?

Managed

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      Yarn: 1.22.18 - ~/.yarn/bin/yarn
      npm: 8.5.0 - /usr/local/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 32.0.0
        System Images: android-28 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-S | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.3 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.1 => 0.68.1 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.3
    Expo Workflow: managed
```

### Error output
<img width="1141" alt="Screenshot 2022-05-14 at 01 14 53" src="https://user-images.githubusercontent.com/70649220/168390505-ad3ef51e-91a3-4274-aa57-3d170c2fbe46.png">

_No response_

### Reproducible demo or steps to reproduce from a blank project

This is project is quite large to reproduce and I can't link a repo here it's private.

**Comment by karanmartian** [comment]
Same issue. Can someone please help urgently?

**Comment by mbrimmer83** [comment]
I'm getting this issue after upgrading from SDK 44 to SDK 45. I notice the same line in the stack trace above for `expo-notifications`

**Comment by homosape** [comment]
Any suggestions regarding this problem would be greatly appreciated.

**Comment by ErikHasp** [comment]
Same issue

**Comment by kbrandwijk** [comment]
Please run `yarn why @expo/config-plugins` and see which package still uses an old version of `@expo/config-plugins` (as in, lower than 4.1.x).

If it's an expo package, try clearing your lock file and reinstalling, all expo packages should resolve to `4.1.x`. If it's a non-expo package, please report to the package maintainer.

**Comment by karanmartian** [comment]
@kbrandwijk here's the output from mine. As you said, it does show older version of @expo/config-plugins being used but it is all being referred by expo packages only. Am I missing something?

karan@karan-B550-VISION-D:~/repos/idrlapp$ yarn why @expo/config-plugins
yarn why v1.22.19
[1/4] Why do we have the module "@expo/config-plugins"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@expo/config-plugins@4.0.15"
info Has been hoisted to "@expo/config-plugins"
info Reasons this module exists
   - Hoisted from "expo-dev-client#@expo#config-plugins"
   - Hoisted from "expo-file-system#@expo#config-plugins"
   - Hoisted from "expo-image-picker#@expo#config-plugins"
   - Hoisted from "expo-media-library#@expo#config-plugins"
   - Hoisted from "expo-notifications#@expo#config-plugins"
   - Hoisted from "expo-system-ui#@expo#config-plugins"
   - Hoisted from "expo-updates#@expo#config-plugins"
   - Hoisted from "expo-dev-client#expo-dev-launcher#@expo#config-plugins"
   - Hoisted from "expo-dev-client#expo-dev-menu#@expo#config-plugins"
info Disk size without dependencies: "2.66MB"
info Disk size with unique dependencies: "4.59MB"
info Disk size with transitive dependencies: "9.25MB"
info Number of shared dependencies: 54
=> Found "@expo/config#@expo/config-plugins@4.1.4"
info This module exists because "expo-constants#@expo#config" depends on it.
info Disk size without dependencies: "1.87MB"
info Disk size with unique dependencies: "3.54MB"
info Disk size with transitive dependencies: "8.13MB"
info Number of shared dependencies: 50
=> Found "@expo/prebuild-config#@expo/config-plugins@4.1.4"
info This module exists because "expo-splash-screen#@expo#prebuild-config" depends on it.
info Disk size without dependencies: "1.93MB"
info Disk size with unique dependencies: "3.59MB"
info Disk size with transitive dependencies: "8.19MB"
info Number of shared dependencies: 50
=> Found "@expo/cli#@expo/config-plugins@4.1.4"
info This module exists because "expo#@expo#cli" depends on it.
info Disk size without dependencies: "1.93MB"
info Disk size with unique dependencies: "3.59MB"
info Disk size with transitive dependencies: "8.19MB"
info Number of shared dependencies: 50

**Comment by kbrandwijk** [comment]
@karanmartian Did you try my suggestion of clearing the lockfile? Alternatively, you can also add a resolution to your package.json to force it to 4.1.4, but I don't recommend doing that.

**Comment by karanmartian** [comment]
@kbrandwijk Wow!! awesome! works now

karan@karan-B550-VISION-D:~/repos/idrlapp$ yarn why @expo/config-plugins
yarn why v1.22.19
[1/4] Why do we have the module "@expo/config-plugins"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@expo/config-plugins@4.1.5"
info Reasons this module exists
   - "expo-dev-client" depends on it
   - Hoisted from "expo-dev-client#@expo#config-plugins"
   - Hoisted from "expo-file-system#@expo#config-plugins"
   - Hoisted from "expo-image-picker#@expo#config-plugins"
   - Hoisted from "expo-media-library#@expo#config-plugins"
   - Hoisted from "expo-notifications#@expo#config-plugins"
   - Hoisted from "expo-system-ui#@expo#config-plugins"
   - Hoisted from "expo-updates#@expo#config-plugins"
   - Hoisted from "expo-constants#@expo#config#@expo#config-plugins"
   - Hoisted from "expo-splash-screen#@expo#prebuild-config#@expo#config-plugins"
   - Hoisted from "expo-dev-client#expo-dev-launcher#@expo#config-plugins"
   - Hoisted from "expo-dev-client#expo-dev-menu#@expo#config-plugins"
   - Hoisted from "expo#@expo#cli#@expo#config-plugins"
info Disk size without dependencies: "2.03MB"
info Disk size with unique dependencies: "3.75MB"
info Disk size with transitive dependencies: "7.36MB"
info Number of shared dependencies: 46
Done in 0.43s.

**Comment by ErikHasp** [comment]
Works, thanks. In the end I used the yarn resolutions to fix these versions in lock file, removed the resolutions after and installed again so it shouldn't cause problems in the future.

**Comment by hadils** [comment]
I need @stripe/stripe-react-native. Here's the output of `yarn why`
```=> Found "@expo/config-plugins@4.1.5"
info Has been hoisted to "@expo/config-plugins"
info Reasons this module exists
   - Hoisted from "expo-camera#@expo#config-plugins"
   - Hoisted from "expo-dev-client#@expo#config-plugins"
   - Hoisted from "expo-file-system#@expo#config-plugins"
   - Hoisted from "expo-image-picker#@expo#config-plugins"
   - Hoisted from "expo-location#@expo#config-plugins"
   - Hoisted from "expo-task-manager#@expo#config-plugins"
   - Hoisted from "expo-updates#@expo#config-plugins"
   - Hoisted from "expo-constants#@expo#config#@expo#config-plugins"
   - Hoisted from "expo-splash-screen#@expo#prebuild-config#@expo#config-plugins"
   - Hoisted from "expo-dev-client#expo-dev-launcher#@expo#config-plugins"
   - Hoisted from "expo-dev-client#expo-dev-menu#@expo#config-plugins"
   - Hoisted from "expo#@expo#cli#@expo#config-plugins"
info Disk size without dependencies: "2.03MB"
info Disk size with unique dependencies: "3.6MB"
info Disk size with transitive dependencies: "6.91MB"
info Number of shared dependencies: 49
=> Found "@stripe/stripe-react-native#@expo/config-plugins@3.1.0"
info This module exists because "@stripe#stripe-react-native" depends on it.
info Disk size without dependencies: "1.59MB"
info Disk size with unique dependencies: "3.43MB"
info Disk size with transitive dependencies: "6.8MB"
info Number of shared dependencies: 50
✨  Done in 0.81s.
```

**Comment by hadils** [comment]
I upgraded `@stripe/stripe-react-native` to 0.10.0 (not the expo version) and was able to `expo eject`.

**Comment by kbrandwijk** [comment]
@stripe/stripe-react-native@0.6.1 also contains the backported change to point to the correct config-plugins version, so the expo recommended version should work for this now as well. 

Closing this now as the issue, and the solutions, are clearly outlined and proven to work.
