### ISSUE TITLE
[ios.dangerous]: withIosDangerousBaseMod: Could not locate a valid AppDelegate at root

### ISSUE THREAD

**Issue by Jigalag** [expo/expo-cli#4391]
### Summary

Running
`expo prebuild`
or 
`expo eject`

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.3 => 45.0.4 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.41.1
      expo-cli: 5.0.1
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

mac

### Reproducible demo or steps to reproduce from a blank project

-

**Comment by trevordunn** [comment]
I just had this happen to me after ejecting from a fresh Expo app. `expo init my-app` then `yarn eject`.

**Comment by trevordunn** [comment]
Upgrading `expo-cli` from `4.12.10` to the latest (`5.4.6`) resolved it for me.

**Comment by ThakurBallary** [comment]
I'm getting the same issue on `expo-cli` `6.0.2` when I run `expo prebuild --clean`

**Comment by hasunperera** [comment]
> I'm getting the same issue on `expo-cli` `6.0.2` when I run `expo prebuild --clean`

I'm also facing the same issue with version 6.0.2

**Comment by codal-mpawar** [comment]
@kbrandwijk @trevordunn @solarisn @Jigalag @hasunperera 
Same issue here on expo-cli 6.0.5

expo prebuild --clean
Warning! Your git working tree is dirty.
It's recommended to commit all your changes before proceeding, so you can revert the changes made by this command if necessary.

✔ Would you like to proceed? … yes

✔ Cleared android, ios code
✔ Created native projects | gitignore already synced
⚠️  Skipped Metro config updates:
› Existing Metro config found; not overwriting.
› You will need to extend the default @expo/metro-config in your Metro config.
  Learn more: https://docs.expo.dev/guides/customizing-metro

✔ Updated package.json and added index.js entry point for iOS and Android
y🧶 Using Yarn to install packages. Pass --npm to use npm instead.
✔ Installed JavaScript dependencies 1557ms
✖ Config sync failed
[ios.dangerous]: withIosDangerousBaseMod: Could not locate a valid AppDelegate at root: "/Users/XXX/Documents/projects/project"
Please report this as an issue on https://github.com/expo/expo-cli/issues
UnexpectedError: [ios.dangerous]: withIosDangerousBaseMod: Could not locate a valid AppDelegate at root: "/Users/XXX/Documents/projects/project"
Please report this as an issue on https://github.com/expo/expo-cli/issues
    at getAppDelegateFilePath (/Users/XXX/Documents/projects/project/node_modules/expo-screen-orientation/node_modules/@expo/config-plugins/src/ios/Paths.ts:26:11)
    at Object.getAppDelegate (/Users/XXX/Documents/projects/project/node_modules/expo-screen-orientation/node_modules/@expo/config-plugins/src/ios/Paths.ts:63:20)
    at /Users/XXX/Documents/projects/project/node_modules/expo-screen-orientation/plugin/build/withScreenOrientation.js:39:63
    at action (/Users/XXX/Documents/projects/project/node_modules/expo-screen-orientation/node_modules/@expo/config-plugins/src/plugins/withMod.ts:214:29)
    at interceptingMod (/Users/XXX/Documents/projects/project/node_modules/expo-screen-orientation/node_modules/@expo/config-plugins/src/plugins/withMod.ts:100:27)
    at action (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:228:14)
    at interceptingMod (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at action (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/createBaseMod.ts:82:21)
    at interceptingMod (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)

**Comment by codal-mpawar** [comment]
@kbrandwijk @trevordunn @solarisn @Jigalag @hasunperera Any update on this? we are stuck here.

**Comment by kbrandwijk** [comment]
> @kbrandwijk @trevordunn @solarisn @Jigalag @hasunperera Any update on this? we are stuck here.

Did you do what I suggested here? https://github.com/expo/expo-cli/issues/4391#issuecomment-1136241116

**Comment by hasunperera** [comment]
@kbrandwijk yes, but it was causing the same issue, but I was able to fix the error by following these steps, not sure which step fixed it though, 
1.) Upgraded MacOS to the latest version (MacOS Monterey 12.6)
2.) Completely removed Xcode and all the other files
3.) Restarted the machine
4.) Installed latest Xcode 14.0 from app store
5.) Installed other dependencies from the Xcode app (Xcode 14.0 command line tools)
6.) Upgraded expo-cli to latest (version 6.0.5)
6.) Restarted the machine
After following these steps, above error disappeared and was able to run the expo build for IOS successfully. (expo run:ios) @trevordunn @solarisn @Jigalag

**Comment by kevinhylant** [comment]
Thanks @hasunperera I followed all your steps & I was still getting this error, so I followed this debugging thread (below) from @kbrandwijk.

> Without showing the actual error, it's hard to pinpoint the cause. But _in general_, this error is caused by a dependency that uses an older version of `@expo/config-plugins`. You can run `yarn why @expo/config-plugins` to see what that package is and check for an update.

I had 3 packages pulling in v4.x (old) @expo/config-plugins dependencies — namely expo-cli, eas-cli, and expo. I removed expo-cli & eas-cli from my dependencies since they weren’t strictly necessary (I can just use  npx to run each expo & eas in CI so that just left expo.

However I wasn’t experiencing the same error when the project was built with eas. Which was curious. Something Brett Vatne mentioned in some other thread led me to the hypothesis that it could be related to my local node version vs the version I’d specified in eas.json (16.13.0 ) vs my local 16.10.x. I rm -rf’d my yarn.lock & node_modules, set my local nodenv to 16.13.0, reinstalled my dependencies, said a prayer, and ran `expo doctor` and voila, no more @expo/config-plugins version mismatch!  Ran `expo prebuild` and no more error.

**Comment by Emex4gman** [comment]
I just noticed the AppDelegate filename generated with expo prebuild is  `AppDelegate.mm` rather than `AppDelegate.m`. I am using Expo 47

**Comment by Brotakuu** [comment]
> I just noticed the AppDelegate filename generated with expo prebuild is `AppDelegate.mm` rather than `AppDelegate.m`. I am using Expo 47

Can't believe this was overlooked. @brentvatne

**Comment by kbrandwijk** [comment]
> > I just noticed the AppDelegate filename generated with expo prebuild is `AppDelegate.mm` rather than `AppDelegate.m`. I am using Expo 47
> 
> Can't believe this was overlooked. @brentvatne

This wasn't overlooked, this was the reason why I pointed out old config-plugins versions in my initial response. The ones with the correct version for this SDK version has been updated to use the correct AppDelegate. Older versions are not.

I'm confused about your contribution to the thread. Were you having the same or a similar issue?

**Comment by Emex4gman** [comment]
> > > I just noticed the AppDelegate filename generated with expo prebuild is `AppDelegate.mm` rather than `AppDelegate.m`. I am using Expo 47
> > 
> > 
> > Can't believe this was overlooked. @brentvatne
> 
> This wasn't overlooked, this was the reason why I pointed out old config-plugins versions in my initial response. The ones with the correct version for this SDK version has been updated to use the correct AppDelegate. Older versions are not.
> 
> I'm confused about your contribution to the thread. Were you having the same or a similar issue?

Oh I see. Thanks for this insight. I was was making an observation and I had a similar issue with expo prebuild failing.

**Comment by fatemehmarzoughi** [comment]
I solved it by downgrading `expo` to `v43.0.0`
