### ISSUE TITLE
Cant run expo run:ios was told to report this as an issue

### ISSUE THREAD

**Issue by catdoglt** [expo/expo-cli#4397]
### Summary

I have tried to run **expo run:ios**, but got this error:

 The ios project is malformed, would you like to clear the project files and reinitialize them? … yes
✔ Cleared ios code
⠋ Creating native project directories (./ios and ./android) and updating .gitignore
✔ Created native project | gitignore already synced
✔ Updated package.json and added index.js entry point for iOS and Android
📦 Using npm to install packages.
✔ Cleaned JavaScript dependencies 3378ms
✔ Installed JavaScript dependencies 7907ms
✖ Config sync failed
[ios.dangerous]: withIosDangerousBaseMod: Could not locate a valid AppDelegate at root: "/Users/itemas/Desktop/siuu-native"
Please report this as an issue on https://github.com/expo/expo-cli/issues

How can I fix that?

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 17.5.0 - /opt/homebrew/bin/node
      npm: 8.4.1 - /opt/homebrew/bin/npm
      Watchman: 2022.02.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.4 => 45.0.4 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.4.7
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

ios simulator

### Error output

 Config sync failed
[ios.dangerous]: withIosDangerousBaseMod: Could not locate a valid AppDelegate at root: "/Users/itemas/Desktop/siuu-native"

### Reproducible demo or steps to reproduce from a blank project

i simply get this error by running  **expo run:ios**

**Comment by kbrandwijk** [comment]
This issue is commonly caused by having an outdated version of `@expo/config-plugins` somewhere in your dependency tree. You can use `yarn why @expo/config-plugins` to check which package uses an older version (older than 4.1.x).

**Comment by ttrebicki** [comment]
This also happens for me after upgrading to expo 45, my `@expo/config-plugins` is at 4.1.5, so there might be something else that causes the issue

**Comment by mikolaj-kozera-prpl-global** [comment]
I have the same issue. I've run `yarn why @expo/config-plugins` and this is the result

```
yarn why v1.22.18
[1/4] 🤔  Why do we have the module "@expo/config-plugins"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@expo/config-plugins@4.1.5"
info Reasons this module exists
   - "expo-apple-authentication" depends on it
   - Hoisted from "expo-apple-authentication#@expo#config-plugins"
   - Hoisted from "expo-av#@expo#config-plugins"
   - Hoisted from "expo-dev-client#@expo#config-plugins"
   - Hoisted from "expo-facebook#@expo#config-plugins"
   - Hoisted from "expo-image-picker#@expo#config-plugins"
   - Hoisted from "expo-notifications#@expo#config-plugins"
   - Hoisted from "expo-updates#@expo#config-plugins"
   - Hoisted from "sentry-expo#@expo#config-plugins"
   - Hoisted from "expo-constants#@expo#config#@expo#config-plugins"
   - Hoisted from "expo-splash-screen#@expo#prebuild-config#@expo#config-plugins"
   - Hoisted from "expo-dev-client#expo-dev-launcher#@expo#config-plugins"
   - Hoisted from "expo-dev-client#expo-dev-menu#@expo#config-plugins"
   - Hoisted from "expo#expo-file-system#@expo#config-plugins"
   - Hoisted from "expo#@expo#cli#@expo#config-plugins"
info Disk size without dependencies: "2.03MB"
info Disk size with unique dependencies: "3.75MB"
info Disk size with transitive dependencies: "7.11MB"
info Number of shared dependencies: 46
✨  Done in 0.64s.
```

so it looks like the package version is correct. Any other idea why this happens?

**Comment by ttrebicki** [comment]
In my case, updating to the newest version of expo-cli worked - I was using 4.x.x, now using 5.x.x
