### ISSUE TITLE
expo mobx decorator

### ISSUE THREAD

**Issue by demiantriebl** [expo/expo-cli#44]
Hi, I have a lot of problems configuring my environment for mobx, I can not use decorator, I install symbols, babel-plugin-transform-decorators-legacy, and many packages in different ways, and I try many times, but I can not, most of them they are babel, I try to update to babel / core: "7.0.0", but it always says 6.2.3 and it is not compatible with decorators,

I think there are good improvements in the package (when it says basic template or tab) that you can choose a mobx and redux template. and the environment is configured from the beginning.

someone use mobx with expo? or do you have a boilerplate?

**Comment by fson** [comment]
Thanks for the question. We're looking to keep questions on our forums and bug reports on this repository. Please post your question to [Expo forums](
https://forums.expo.io/c/help), you'll have a better chance of finding someone who can help. Thanks!
