### ISSUE TITLE
installing Expo-cli using npm hangs

### ISSUE THREAD

**Issue by nabhan0705** [expo/expo-cli#440]
while  installing Expo-cli using npm on windows 7 32 bit machine, the commandline hangs at extract: 
"@expo/traveling-fastlane-linux@1.82 (sha-----Some sha string) seems to be corrupt. Trying once again @expo/traveling-fastlane-darwin SILL extract."  Attempted many times. same result

**Comment by fson** [comment]
Can you try running `npm cache verify` and then try installing again?

**Comment by sudip03** [comment]
i am having same problem @expo/traveliing-fastlane-darwin@1,9,3... seems to be corrupted... and next program halts @rxjs 

1. I tried with node reinstall
2. always added admin privilege to admin
3. always clean cache --force on every try

Node version = 10.5.0
NPM ver : 6.1.0
Windows 7

ANy idea?

**Comment by swarnim89** [comment]
Even i had same issue? any solution would be appreciated

**Comment by sudip03** [comment]
> Even i had same issue? any solution would be appreciated

Nothing positive, 
But i tried download the same node for 32 bit OS on my other PC and tried to run expo install. It worked fine. But on my 64bit OS, it stops. Even i tried to leave my PC for hrs in hope may be it will take some time. 
Please do let me know if you find any solution.

**Comment by sudip03** [comment]
> Even i had same issue? any solution would be appreciated

I installed in another way.. i tried expo install in another windows PC, it works successfully. i then copied the whole npm folder to my PC (windows), and its working. So, you can try this too.

path.. Users >> username >> AppData >> Roaming >> npm

**Comment by SamratSauravJaiswal** [comment]
> > Even i had same issue? any solution would be appreciated
> 
> I installed in another way.. i tried expo install in another windows PC, it works successfully. i then copied the whole npm folder to my PC (windows), and its working. So, you can try this too.
> 
> path.. Users >> username >> AppData >> Roaming >> npm

can you please upload the file..so we can use it

**Comment by kitkay** [comment]
I have the same problem too... extract:@expo/traveling-fastlane-darwin: sill extract -> hanging always...

Even I already npm cache verify.... please help... I'm just new to nodejs and expo-cli

Thanks!

**Comment by vidurajith-darshana** [comment]
I was also faced with that problem. Firstly I removed the npm cache and npm modules from users/AppData/Roaming. then run npm install and expo CLI commands globally in my project file folder. finally, the problem resolved.

**Comment by abdulmutalib1** [comment]
> Can you try running `npm cache verify` and then try installing again?

This really help.....Thank You @fson

**Comment by jDally987** [comment]
> Can you try running `npm cache verify` and then try installing again?

This worked for me too, thanks

**Comment by abduraufsherkulov** [comment]
after clearing the cache, use windows powershell instead cmd, by the way run it as administrator. I didn't understand why this happened so, but while using cmd, it is downloading dependencies in low speed which caused the hanging.

**Comment by itsjustvenky** [comment]
@fson Thanks. Your suggestion worked for me. I am able to install expo-cli.

**Comment by rosnaib11** [comment]
I also had same problem running cmd as administrator solved my problem.

**Comment by jkhales** [comment]
Closing as the issue seems resolved.

**Comment by casteluc** [comment]
After a long research i discovered that just running `npm install expo-cli --global --no-optional` solved the problem.

**Comment by HesterSchoeman** [comment]
I have the same problem. I tried the options above 
-  running cmd as administrator
- npm install expo-cli --global --no-optional
- npm cache verify
but it did not solve my problem. Please any other suggestions?

**Comment by brentvatne** [comment]
you might just have to wait a while, depending on your connection it could take a long time to install. also, if you are using wsl that may be a problem and take a really long time: https://www.reddit.com/r/webdev/comments/d4yysr/nodejs_and_wsl_are_agonisingly_slow/
