### ISSUE TITLE
Connecting to Metro bundler failed.

### ISSUE THREAD

**Issue by MohaEttaibi** [expo/expo-cli#4402]
### Summary

Error: Problem validating fields in app.json. See https://docs.expo.io/workflow/configuration/
 • should NOT have additional property 'nodeModulesPath'.
Could not get status from Metro bundler. connect ECONNREFUSED 127.0.0.1:19001
Connecting to Metro bundler failed.

### Environment

Need to install the following packages:
  expo-env-info
Ok to proceed? (y)

  expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^43.0.0 => 43.0.5
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: https://github.com/expo/react-native/archive/sdk-43.tar.gz => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
      react-navigation: ^4.4.3 => 4.4.3
    Expo Workflow: managed

npm notice
npm notice New minor version of npm available! 8.5.0 -> 8.11.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.11.0
npm notice Run npm install -g npm@8.11.0 to update!
npm notice

### Please specify your device/emulator/simulator platform, model and version

Windows 10 10.0.19043

### Error output

Error: Problem validating fields in app.json. See https://docs.expo.io/workflow/configuration/
 • should NOT have additional property 'nodeModulesPath'.
Could not get status from Metro bundler. connect ECONNREFUSED 127.0.0.1:19001
Connecting to Metro bundler failed.

### Reproducible demo or steps to reproduce from a blank project

Error: Problem validating fields in app.json. See https://docs.expo.io/workflow/configuration/
 • should NOT have additional property 'nodeModulesPath'.
Could not get status from Metro bundler. connect ECONNREFUSED 127.0.0.1:19001
Connecting to Metro bundler failed.

**Comment by EvanBacon** [comment]
Cannot reproduce. You most likely have firewall issues or restrictive wifi which is preventing the connection. You can circumvent this by using a tunnel URL. Expo CLI has a tunnel built-in and accessible with `npx expo start --tunnel`
