### ISSUE TITLE
Command 'expo upgrade' doesn't work on 5.4.7, throws 'Invalid project root'

### ISSUE THREAD

**Issue by Screeper11** [expo/expo-cli#4404]
### Summary

`expo upgrade`
>Invalid project root: C:\<project root>\upgrade

It works on 5.4.6 but doesn't work on 5.4.7

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.8.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8309675
    npmPackages:
      @expo/metro-config: ^0.3.16 => 0.3.18
      expo: ^45.0.4 => 45.0.4
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Windows 10 (64 bit)

### Error output

Invalid project root: C:\<project root>\upgrade

### Reproducible demo or steps to reproduce from a blank project

Run `expo upgrade` in a project

**Comment by MrXyfir** [comment]
@Screeper11 did you solve this?
