### ISSUE TITLE
Trying to launch app on Android Emulator which is unauthorized for Expo CLI

### ISSUE THREAD

**Issue by danielmnetto** [expo/expo-cli#4412]
### Summary

My project was recently created and I'm using Bare Workflow format and I'm trying to launch my project in Expo on my Android Emulator I have just created, but instead of connect to it, it prints:

```
Learn more: https://expo.fyi/authorize-android-device_4_API_30
```

Sending to a 404 page. 
But if I remove the **_4_API_30** part, it sends me to Authorize Android Device guide which it doesn't work with mine because I'm using an emulator from Android Studio.

I have tried to use SHIFT + A to see all listed android devices on my PC and it showed me this:

```
? Select a device/emulator »
 (unauthorized)_30
```

When I press ENTER, it shows the same "Learn more" that I've mentioned before.

How I do proceed to solve this?

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.22000 (Note: i'm using Windows 11)
    Binaries:
      Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
      npm: 7.24.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~45.0.0 => 45.0.4
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

Android Studio Emulator - Pixel 4 API 30

### Reproducible demo or steps to reproduce from a blank project

```I did not use any code on my project since I've just created using 'expo init ProjectName' command.```

**Comment by EvanBacon** [comment]
The link format is a bug that is fixed in the new versioned Expo CLI (`npx expo`). The link points to a relevant guide for authorizing a device to use adb. [Here's another](https://stackoverflow.com/a/25546300/4047926).
