### ISSUE TITLE
EAS build fail for simulator and prod

### ISSUE THREAD

**Issue by tb42** [expo/expo-cli#4414]
### Summary

When submitting a build for the simulator or prod a "Network gateway timeout" error fires. 

![Screen Shot 2022-06-06 at 9 35 33 AM](https://user-images.githubusercontent.com/16248244/172171158-41324c54-eed4-47b5-8d68-c8ccf17af4c5.png)
 

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      npm: 8.9.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.53.0
      expo-cli: 5.0.3
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Mac OS Monterey, Expo iOS simulator

### Error output

Error message is stating I need to ensure eas-cli is up to date, which I did. And if that doesn't work then to report the issue. 

![Screen Shot 2022-06-06 at 9 35 33 AM](https://user-images.githubusercontent.com/16248244/172171158-41324c54-eed4-47b5-8d68-c8ccf17af4c5.png)

### Reproducible demo or steps to reproduce from a blank project

Build a managed ios project and push to simulator

**Comment by thatzacdavis** [comment]
I also started getting this today. Is there anything I can run to help debug?

**Comment by kbrandwijk** [comment]
This was an intermittent issue with our services that has since been resolved. Sorry for the inconvenience.

**Comment by tb42** [comment]
@kbrandwijk Are there still intermittent issues going on? Just hit another error from eas when pushing prod. See below
![Screen Shot 2022-06-06 at 1 48 54 PM](https://user-images.githubusercontent.com/16248244/172216765-bec79102-89b0-44b7-a9aa-77c4a43aef1f.png)
