### ISSUE TITLE
Presence of environment variable BUILD_NUMBER causes fast refresh to break

### ISSUE THREAD

**Issue by mprevdelta** [expo/expo-cli#4418]
### Summary

Presence of environment variable BUILD_NUMBER causes fast refresh to break.

### Environment

 expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-212.5712.43.2112.8609683
    npmPackages:
      expo: ~45.0.0 => 45.0.5
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Pixel 4a API 32

### Reproducible demo or steps to reproduce from a blank project

expo init buildnumber
cd buildnumber
expo start -a
-- modify App.js and verify output changes
-- kill expo
$env:BUILD_NUMBER="Somevalue"
expo start -a
-- modify App.js and output does not change
-- kill expo
$env:BUILD_NUMBER=""
expo start -a
-- modify App.js and output changes again

**Comment by EvanBacon** [comment]
This appears to be related to `ci-info`, if any of [these values](https://github.com/watson/ci-info/blob/449537c1bd372f75660dc4ce2ddff92179dfc740/index.js#L57-L63) are set, then Fast Refresh will be disabled as the environment is assumed to be CI.

Do not set any of the following environment variables:

```
CI
CONTINUOUS_INTEGRATION
BUILD_NUMBER
CI_APP_ID
CI_BUILD_ID
CI_BUILD_NUMBER
RUN_ID
```

Not sure which part of the stack is making this assumption. We only check `CI` in Expo tooling.
