### ISSUE TITLE
WARNING: expo-cli has not yet been tested against Node.js v18.3.0.

### ISSUE THREAD

**Issue by LilianDamico** [expo/expo-cli#4426]
export default function App() {
    return ( <
        View style = { styles.container } >
        <
        Text > Hello World! < /Text> <
        StatusBar style = "auto" / >
        <
        /View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
    },
});
É assim que fica meu código quando eu tento rodar no expo. Existe um aviso de incompatibilidade do Node JS 18 com o CLI.

**Comment by kbrandwijk** [comment]
Indeed, for this SDK cycle, we can't fully guarantee 100% compatibility with Node 18, hence the warning. It doesn't block you from trying though. Let us know if you run into any issues on Node 18!

**Comment by moosemaker** [comment]
it doesnt open a browser window when im using node version 18

**Comment by amanmishra7ave** [comment]
> it doesnt open a browser window when im using node version 18

Same happening with me also,
did you get any solution yet

**Comment by kbrandwijk** [comment]
It doesn't open a browser window in any node version. https://blog.expo.dev/sunsetting-the-web-ui-for-expo-cli-ab12936d2206
