### ISSUE TITLE
expo-cli fails to run when @types/react is updated

### ISSUE THREAD

**Issue by danfinch** [expo/expo-cli#4427]
### Summary

expo-cli will not run if I do not opt to let it downgrade my `@types/react` dependency. This dependency has no run-time impact so it is **not** required to match versions.

I cannot compile my project with the `17.x` TypeScript definitions as many of my dependencies use `18.x`'s fixed typings (which also work for `17.x`).

### Environment

 expo-env-info 1.0.3 environment info:
    System:
      OS: Linux 5.4 Ubuntu 18.04.6 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
      Watchman: 20220206.222721.0 - /usr/local/bin/watchman
    npmPackages:
      expo: ^45.0.0 => 45.0.5
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    npmGlobalPackages:
      eas-cli: 0.53.1
      expo-cli: 5.4.9
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Android emulator

### Error output

✔ It looks like you're trying to use TypeScript but don't have the
required dependencies installed. Would you like to install
@types/react? … no
Please install @types/react by running:

yarn add --dev @types/react@~17.0.21

If you're not using TypeScript, please remove the TypeScript files
from your project and delete the tsconfig.json.

### Reproducible demo or steps to reproduce from a blank project

`expo init my-app`
template: blank (TypeScript)
`cd my-app`
`yarn add -D @types/react`
`expo start --android`

**Comment by a-fortunato** [comment]
This happened to me as well (tried both on Linux Debian 10 and macOS Monterrey 12.4).

I have a `RootNavigator` that looks almost exactly as the one in the [React Navigation docs](https://reactnavigation.org/docs/typescript/#type-checking-the-navigator), and got a ts error about incompatible types.

<img width="1122" alt="Screenshot 2022-06-21 at 02 15 14" src="https://user-images.githubusercontent.com/6339463/174691937-9c0f713c-11d6-46af-bfe9-f58e3b6506fb.png">

My `package.json` dependencies are below (basically the TypeScript blank template + a couple extra packages):
```json
{
  "dependencies": {
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.2",
    "expo": "~45.0.0",
    "expo-status-bar": "~1.3.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-safe-area-context": "4.2.4",
    "react-native-screens": "~3.11.1",
    "react-native-web": "0.17.7",
    "react-query": "^3.39.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.66.13",
    "@typescript-eslint/eslint-plugin": "^5.28.0",
    "@typescript-eslint/parser": "^5.28.0",
    "eslint": "^7.32.0 || ^8.2.0",
    "eslint-config-airbnb-typescript": "^17.0.0",
    "eslint-plugin-import": "^2.25.3",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-react": "^7.28.0",
    "eslint-plugin-react-hooks": "^4.3.0",
    "eslint-plugin-react-native": "^4.0.0",
    "expo-cli": "^5.4.11",
    "typescript": "~4.3.5"
  },
```

The thing is that when I updated `@types/react` to `18.x` the ts error was fixed but then I couldn't run the project (got the same error that @danfinch mentioned above):

```zsh
afortunato@Ulthar HNClient % yarn expo start
yarn run v1.22.19
$ /Users/afortunato/projects/HNClient/node_modules/.bin/expo start
Starting project at /Users/afortunato/projects/HNClient
Developer tools running on http://localhost:19002
✔ It looks like you're trying to use TypeScript but don't have the required dependencies installed. Would you like to install @types/react? … no
Please install @types/react by running:

yarn add --dev @types/react@~17.0.21

If you're not using TypeScript, please remove the TypeScript files from your project and delete the tsconfig.json.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

I had to go back to `17.x` to run the app with expo and continue developing, ignoring the ts error. 😢 

(btw, thank you for the great work you do! 💟 )

**Comment by makhataibar** [comment]
it's fixed in https://github.com/expo/expo-cli/pull/4439

**Comment by EvanBacon** [comment]
If anyone wishes to opt-out of TypeScript setup, set the environment variable `EXPO_NO_TYPESCRIPT_SETUP=1`.
