### ISSUE TITLE
Bug with Contacts.requestPermissionsAsync()

### ISSUE THREAD

**Issue by tb42** [expo/expo-cli#4445]
### Summary

The Contacts Permission request only fires once. Not being able to request the contacts permission multiple times is causing issues e.g. if the user first denies the contact permission the first time, they can't update their permission status later.

### Environment

  expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      npm: 8.12.1 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.53.0
      expo-cli: 5.4.9
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Mac OS Monterey, Expo iOS simulator

### Error output

No error output

### Reproducible demo or steps to reproduce from a blank project

Run the code as shown in the docs [here](https://docs.expo.dev/versions/latest/sdk/contacts/#usage). And then try to trigger the permission request a second time. The contacts permission request will not fire a dialog box for the user to allow permission on the second time.

**Comment by kbrandwijk** [comment]
What is the value of `canAskAgain` that you get back from the permission request? If that is set to `false`, then you cannot request the permission again. This is completely handled by the underlying OS on iOS, and we have no control over it. Also, again depending on the OS, you cannot ask for the same permission multiple times in the same session.

**Comment by tb42** [comment]
@kbrandwijk The issue is that the permission request can not be triggered again, even if a new session is started. Which is not an OS factor, but an expo one. The only way I've found to trigger the contacts permission ask again is to restart all device settings in the iOS simulator. 

With every other Permission response this is not an issue (location, notifications etc.)

**Comment by kbrandwijk** [comment]
Please read up here: https://developer.apple.com/documentation/contacts/requesting_authorization_to_access_contacts on when the popup is supposed to be shown again and when not, and compare that to other permission types like https://developer.apple.com/documentation/corelocation/requesting_authorization_for_location_services and note the difference (contacts specifically mentions: _'For any other authorization status, requesting authorization doesn’t prompt the user again.'_).

Again, this is all dictated by the OS, not a specific implementation on the Expo side.
