### ISSUE TITLE
expo-optimize produce unsupported files error on publish

### ISSUE THREAD

**Issue by soullivaneuh** [expo/expo-cli#4446]
### Summary

If I ran `expo-optimize` on my assets, I have then the following on `expo publish` or while using the app trough `expo start`.

I also notice the file type is indeed changed:

```bash
# Before
❯ file assets/logo/logo.png
assets/logo/logo.png: PNG image data, 512 x 512, 8-bit/color RGBA, non-interlaced
# After
❯ file assets/logo/logo.png 
assets/logo/logo.png: ISO Media, AVIF Image
```

I provided you a public sandbox project with image to reproduce the case with ease.

```
❯ expo --version                    
5.4.12
❯ npx expo-optimize --version
0.2.17
❯ npx sharp-cli --version
2.1.0
```

### Environment

```
  expo-env-info 1.0.4 environment info:
    System:
      OS: Linux 5.15 Manjaro Linux
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 1.22.19 - /usr/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    npmPackages:
      expo: ~45.0.0 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      expo-cli: 5.4.12
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

N/A

### Error output

```
Building optimized bundles and generating sourcemaps...
Starting Metro Bundler
Started Metro Bundler
assets/logo-k-invert.png: unsupported file type: undefined (file: /home/sullivan/p/github.com/soullivaneuh/expo-sandbox/assets/logo-k-invert.png)
TypeError: unsupported file type: undefined (file: /home/sullivan/p/github.com/soullivaneuh/expo-sandbox/assets/logo-k-invert.png)
    at lookup (/home/sullivan/p/github.com/soullivaneuh/expo-sandbox/node_modules/image-size/lib/index.js:34:9)
    at module.exports (/home/sullivan/p/github.com/soullivaneuh/expo-sandbox/node_modules/image-size/lib/index.js:122:12)
    at getAssetData (/home/sullivan/p/github.com/soullivaneuh/expo-sandbox/node_modules/metro/src/Assets.js:164:32)
    at async Object.transform (/home/sullivan/p/github.com/soullivaneuh/expo-sandbox/node_modules/metro-transform-worker/src/utils/assetTransformer.js:30:16)
    at async transformAsset (/home/sullivan/p/github.com/soullivaneuh/expo-sandbox/node_modules/metro-transform-worker/src/index.js:373:18)
    at async Object.transform (/home/sullivan/p/github.com/soullivaneuh/expo-sandbox/node_modules/metro-transform-worker/src/index.js:561:14)
```

### Reproducible demo or steps to reproduce from a blank project

1. Clone this PR: https://github.com/soullivaneuh/expo-sandbox/pull/1
2. `npm install`
3. `npx expo-optimize`
4. `expo publish`

**Comment by soullivaneuh** [comment]
Note: I also have the issue using the app through `npm start`.

**Comment by kbrandwijk** [comment]
This has been resolved in `sharp-cli@2.1.1`. If you install the new version, `expo-optimize` will generate the correct images again.

**Comment by soullivaneuh** [comment]
@kbrandwijk I'll verify that, thanks!

By the way, do we have any way to verify the assets files with the expo cli?

This bug was discovered on our projects only on deployment and triggered a lot of revert process. We would like to prevent that in the future! :smile:

**Comment by kbrandwijk** [comment]
No, there's no built-in way to verify asset files. Feel free to suggest this feature on [Canny](https://expo.canny.io) though, it could be useful (unless there's a package or tool out there that already does so). Going to close this issue, as the original issue is resolved upstream.
