### ISSUE TITLE
Changelog file is outdated

### ISSUE THREAD

**Issue by gasolin** [expo/expo-cli#445]
## Description

The latest update of https://github.com/expo/expo-cli/blob/master/packages/expo-cli/CHANGELOG.md is ended at `2018-07-12`

Please get `CHANGELOG.md` updated or remove it from the repo

## Expected Behavior

See the up-to-date CHANGELOG

## Observed Behavior

https://github.com/expo/expo-cli/blob/master/packages/expo-cli/CHANGELOG.md is ended at `2018-07-12`

**Comment by gustavopch** [comment]
@jkhales Does closing this issue mean there will be no changelog?
