### ISSUE TITLE
Multiple babelTransformerPath on the ejected expo project

### ISSUE THREAD

**Issue by tommycp96** [expo/expo-cli#4455]
### Do you understand that any feature requests opened in the core Expo repository will be closed?

Yes

**Comment by tommycp96** [comment]
Hi All, Is there anyway that we can add multiple `babelTransformerPath` on the ejected Expo project on the `metro.config.js` like in this reference: https://stackoverflow.com/questions/69044870/how-to-add-multiple-babeltransformerpath-in-metro-config.

Cause I really need to add 2 `babelTransformerPath` on our project, thanks

**Comment by kbrandwijk** [comment]
What is preventing you from defining your metro.config.js like in the snippet in the link you shared? From what I can see, that should work. If you run into any issues, feel free to open a topic on the [forums](https://forums.expo.dev). This GitHub repository is for reporting issues with the expo-cli packages, which this is not.
