### ISSUE TITLE
com.segment.analytics.android:analytics error, even with SDK 45

### ISSUE THREAD

**Issue by tomgiam** [expo/expo-cli#4466]
### Summary

Even after upgrading to SDK 45, running "expo build:android -t app-bundle", Google flags the successful build with the message: "Your app com.andiamoplaces.andiamotravelapp version code 9 includes SDK com.segment.analytics.android:analytics, 4.8.2 or an SDK that one of your libraries depends on".

### Environment

expo-env-info 1.0.4 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 7.14.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28
        Build Tools: 28.0.3
        System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom  
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6200805
    npmPackages:
      expo: ~45.0.0 => 45.0.6
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
      react-navigation: ^4.4.4 => 4.4.4
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

NA

### Error output

Your app com.andiamoplaces.andiamotravelapp version code 9 includes SDK com.segment.analytics.android:analytics, 4.8.2 or an SDK that one of your libraries depends on

Your app com.andiamoplaces.andiamotravelapp version code 9 includes SDK com.segment.analytics.android:analytics, 4.9.4 or an SDK that one of your libraries depends on

### Reproducible demo or steps to reproduce from a blank project

 NA

**Comment by kbrandwijk** [comment]
Is version 9 actually the version you are trying to build? Seeing 4.8.2 in the error makes me wonder if it's not referring to an older build in the warning (Google warnings can be very unclear like that).

**Comment by dhruvamcodepxl** [comment]
I had the same issue couple of weeks ago. The thing is expo package contains the Segment Analytics code and is using version 9 that collects information which now Google Play Store does not allow as part of their new policy. The only way I found was using **eas build** command. Since, **eas** command excludes all the code from bundling that is not being used, will also not include the Segment Analytics code and thus you would be able to build successfully. Also, it reduces app size drastically so I would recommend using eas for your future releases.

**Comment by tomgiam** [comment]
@dhruvamcodepxl Thanks for confirming that **eas build** fixes this problem. Unfortunately I ran into a problem with **eas build** and I have an open issue for it as well "Gradle build failed with unknown error". That's with the same exact code that builds "correctly" with **expo build**. So for now I'm using **expo build**, but in August Google will no longer allow those apps.

**Comment by kbrandwijk** [comment]
@dhruvamcodepxl That is incorrect, `expo build` has been updated to use a more recent version of the Android segment analytics package, so this shouldn't happen with `expo build`, which is why I asked if version 9 of the app was actually the correct version.

**Comment by tomgiam** [comment]
@kbrandwijk I'm not sure what version 9 is referring to, I was building version 18 (1.2.7). The new information from today is that I get the same error message when I use eas build. It actually gives me 3 separate error messages, one for Version 15, one for version 9 and one for 4. Do you think that it's referring to my old releases? Those errors appear when I click on the "Review Release" button from my latest release. I'm now testing release 20 (1.3.0)

**Comment by tomgiam** [comment]
@dhruvamcodepxl I got the eas build to work today. The problem was one image file with a .png extension that was actually a .jpg file format. So I converted it to a .png file format and the eas build now works. However, to my surprise even with the eas build I'm still getting the same error from google.

**Comment by dhruvamcodepxl** [comment]
@tomgiam You are getting error for your previous releases because of the Segment Analytics. I tumbled upon same kind of situation where I got error in my previous builds as well. It's strange that even after using **eas build** you are encountering same error. Can you share a screenshot of the error. Is it exactly the same as you received when using expo? 

Also, when you upload your app-bundle are you getting the error at that time or after it's  uploaded for internal testing/production?

**Comment by tomgiam** [comment]
@dhruvamcodepxl To get the errors I:
1. Click on "create new release"
2. Upload the new .aab file
3. Click on the "Review Release" button 

I just noticed that there is a "dismiss" option for each one of the error messages. When I click on that for all 3 errors the issue disappears from the screen and when I repeat steps 1-3 they don't re-appear. Could those have been errors left over from old builds?

From what I remember the 3 errors are the same from expo build and eas build.
Here is the screenshot from one of the errors, the other 2 are similar but refer to a different release of my app or of the SDK.

![Error1](https://user-images.githubusercontent.com/1909294/180461319-319ff152-fafe-4318-bc2c-4e4e88a1831d.JPG)

**Comment by dhruvamcodepxl** [comment]
@tomgiam You are correct. This error is from your previous builds (In the error it refers to the version code 15 of your app not the new one you are trying to upload). I too receive this when uploading new builds. You can safely ignore them and still proceed with  the uploads. It should work.

**Comment by tomgiam** [comment]
@dhruvamcodepxl Thanks, that's a relief!! It's confusing that they show errors from old builds.

**Comment by KodyKendall** [comment]
How is this complete? I am having the exact same issue.
