### ISSUE TITLE
[Question] How to use yarn instead of npm hen running npx create-expo-app ?

### ISSUE THREAD

**Issue by itsramiel** [expo/expo-cli#4467]
### Summary

Not an issue. I just want to know how to initialize a project with yarn instead of npm when running npx create-expo-app.

### Environment

-

### Please specify your device/emulator/simulator platform, model and version

-

### Reproducible demo or steps to reproduce from a blank project

-

**Comment by kbrandwijk** [comment]
`npx` is an `npm` command. Use `yarn create expo-app` if you want to use `yarn`. For reference: https://github.com/expo/expo-cli/tree/main/packages/create-expo-app#create-expo-app
