### ISSUE TITLE
`expo prebuild` generates android.package and ios.bundleIdentifier fields in app.json which throws an eas deprecation

### ISSUE THREAD

**Issue by hcshires** [expo/expo-cli#4468]
### Summary

After running `expo prebuild` on my project, I want to build it via the EAS CLI, and I run across the following deprecation warning:
> Specifying "android.package" in app.json is deprecated for bare workflow projects.
> EAS Build depends only on the value in the native code. Please remove the deprecated configuration.

I remove the line as instructed but come to find that every time I run `expo prebuild` it just puts it back. Is there a way I can tell prebuild to stop adding this line or is this a communication bug between the two CLIs?

### Environment

expo-env-info 1.0.4 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 14.19.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.12.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-212.5712.43.2112.8609683
    npmPackages:
      expo: ~45.0.0 => 45.0.4
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

Google Pixel 5, Android 12

### Error output

No fatal errors, the app builds properly

### Reproducible demo or steps to reproduce from a blank project

1. Run `expo prebuild` in a bare workflow Expo app or an Expo app that utilizes the `\ios` and `\android` native code directories
2. Observe that `android.package` and `ios.bundleIdentifier` have been added to the app.json config
3. Run `eas build` with any arguments and the above warning should appear

**Comment by kbrandwijk** [comment]
The wording on the warning is not too clear, improvement planned here: https://github.com/expo/eas-cli/pull/1211. Having those lines in your app.json is fine, the gist of the warning is that any _changes_ to them in **app.json** will not be picked up automatically.

**Comment by hcshires** [comment]
Ah i see, thanks for the clarification
