### ISSUE TITLE
[create-expo-app] Local template cache is never cleared out

### ISSUE THREAD

**Issue by frankcalise** [expo/expo-cli#4475]
### Summary

Using `npx create-expo-app myapp --template \Users\fcalise\Documents\code\path\to\my\boilerplate` for example, if I had an error in my `package.json` file and later fixed it, create-expo-app still contains the same error because the packed npm tar already exists in `~/.create-expo-app/template-cache`.

### Environment

```
  expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.2/bin/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 5.5.1
```

### Please specify your device/emulator/simulator platform, model and version

Expo 45

### Error output

No error message necessarily, just stale project information when using a local template more than once. 

### Reproducible demo or steps to reproduce from a blank project

1. Clone [infinitered/ignite](https://github.com/infinitered/ignite/)
2. Run `npx create-expo-app MyApp --boilerplate ./path/to/ignite/boilerplate`
3. Let Expo set up the project
4. Modify ./path/to/ignite/boilerplate/package.json (ie, change a dependency version)
5. Run command from Step 2 again (name app differently)
6. Observe the original package.json dependency is versioned from the original template and not the modified one from step 4

**Comment by brentvatne** [comment]
this is resolved here: https://github.com/expo/expo-cli/commit/c3edfc03d8c5b0c3c75272623299e4f835edfd43
