### ISSUE TITLE
Expo Dev Tools no longer work in v5.6.0 - An unexpected error has occurred

### ISSUE THREAD

**Issue by Vercjames** [expo/expo-cli#4479]
### Summary

Expo Dev Tools no longer work in v5.6.0. Ergo running expo start will does not open the tried and true metro service in the browser on port 19002. rather you are greet with the `An unexpected error has occurred.` message. 

### Environment

node -v v16.16.0
npm -v 8.11.0
expo-cli -v 5.6.0

fresh project

### Please specify your device/emulator/simulator platform, model and version

Pixel_3a_API_29

### Error output

Brower Page Reads: 

"An unexpected error has occurred."

console reads:

process is not defined

### Reproducible demo or steps to reproduce from a blank project

https://github.com/Vercjames/expo-cli-error

**Comment by Vercjames** [comment]
I started with node 16.14.0 and got the error. I  decided to upgrade to 16.16.0 in hopes of solving the issue. No luck. same error with 18.6.0 as well.

**Comment by jroux-git** [comment]
I also updated to expo-cli v5.6.0 and wen you run `expo start` I got that error. So I did the complete update to expo 45 with `expo upgrade`. Did not help. I downgraded expo-cli after that to my old version of 5.4.3 and now the cli is working again. I also undid the expo upgrade by using my backup package.json to previous versions before expo upgrade. Will wait until it is more stable. Did not do a Node upgrade, my Node version is 16.14.2

**Comment by FlawaCLV** [comment]
Same error for me. Not working with `expo-cli@5.6.0 / expo 45`.
I downgraded to `expo-cli@5.5.1` and it works.

**Comment by lahirudx** [comment]
Same issue here. `expo-cli@5.6.0 / expo 45`

**Comment by LGmatrix13** [comment]
Getting the same error here

**Comment by jpschw** [comment]
Same issue

**Comment by SAMRIDHISAINII** [comment]
same issue i m having

**Comment by Jerryhuangjp** [comment]
same issue

**Comment by lightrao** [comment]
Same issue  :(

**Comment by mirkokiefer** [comment]
Even the terminal UI is not responsive for me in `expo-cli@5.6.0` - downgrading to `expo-cli@5.5.1` works.

**Comment by brentvatne** [comment]
i've rolled back latest to expo-cli@5.5.1 until we can investigate this tomorrow, thank you for the report

**Comment by brentvatne** [comment]
@mirkokiefer - can you create a new issue with more information about the problem that you are encountering? as far as I know, the only feature that broke in expo-cli@5.6.0 was the deprecated web ui

**Comment by jpschw** [comment]
I didn't know the web ui had been deprecated. Everything is fine on my side
then. The error is expected.

**Comment by brentvatne** [comment]
we have released expo-cli@6.0.0 [with the web ui completely removed](https://blog.expo.dev/sunsetting-the-web-ui-for-expo-cli-ab12936d2206). if you have any other problems with expo-cli@6.0.0, please create a new issue.

**Comment by Vercjames** [comment]
while I am aware that 6..0.0 removed web ui completely; its a bit a faux pas to deprecate a feature before having its corresponding major release version published. It makes legacy decencies that are using ^5.0.0 break without a rich understand about whats going on from an installation perspective.

**Comment by brentvatne** [comment]
@Vercjames - it was not intentional for 5.6.0 to be published with the feature broken, which is why i reverted latest to 5.5.1 and then marked 5.6.0 as deprecated on npm

**Comment by brentvatne** [comment]
in order to ensure this is clear to everyone i also added the following to the deprecation blog post

<img width="813" alt="image" src="https://user-images.githubusercontent.com/90494/180883687-f368edbd-0a5d-4acb-b6bd-0704f42921a6.png">
