### ISSUE TITLE
[web] Decide on build artifact directories

### ISSUE THREAD

**Issue by ide** [expo/expo-cli#448]
While setting up Amplify support, I noticed two things: I needed to tell Amplify where to find the generated output files and that `web-build` contained report.html and ended up getting hosted by default.

We need to figure out:

- Where do we want to emit build artifacts like the JS bundles and image assets? Is there a naming pattern that extends well to other platforms (self-hosted native apps, Electron) as well?
- How do we want to separate production assets from other build artifacts like Webpack stats and the report HTML?
- How can we do the above in a way that lets people customize the directories? For example, they might want to write a CI config that logically does something like `$web_output_dir=...; expo build:web --output="$web_output_dir"; deploy "$web_output_dir"`.

**Comment by EvanBacon** [comment]
This seems mostly baked out now that babel caching and reporting have been solved.
