### ISSUE TITLE
After installed expo-cli 6.0.0, vs-code keeps reporting "This version of expo-cli is not supported anymore..."

### ISSUE THREAD

**Issue by alickcai** [expo/expo-cli#4483]
### Summary

Just finished expo-cli upgrading to 6.0.0 following instruction.
After key in "expo start", system keeps reporting 

│   This version of expo-cli is not supported anymore. 
│   It's highly recommended to update to the newest version.
│   The API endpoints used in this version of expo-cli might not exist,
│   any interaction with Expo servers may result in unexpected behaviour. 

How could solve it?

### Environment

expo-cli@6.0.0

        "expo": "~45.0.0",
        "react": "17.0.2",
        "react-native": "0.68.2",

vs-code

### Please specify your device/emulator/simulator platform, model and version

Expo Go with real devices

### Reproducible demo or steps to reproduce from a blank project

Every time key in "expo start" or "npm start", the message is up (even after local server restart)

**Comment by amandeepmittal** [comment]
@alickcai may I know what key are you using in "expo start"? I'm trying to reproduce the issue on my end but haven't been able to with the information you provided.

**Comment by josafaps** [comment]
@amandeepmittal in my case, its not only when using "expo start", the message is raised in every expo cli command

**Comment by kbrandwijk** [comment]
Could you verify that you are actually on expo-cli@6.0.0, running `expo -V`? I can't reproduce this locally after installing that latest version.

**Comment by rrust** [comment]
> Could you verify that you are actually on expo-cli@6.0.0, running `expo -V`? I can't reproduce this locally after installing that latest version.

confirmed. "expo --version" gives "6.0.0"

**Comment by GreenCurveDev** [comment]
I have exactly the same issues. expo -v confirms version is 6.0.0 (running on Mac)

Eg expo doctor --fix-dependencies

There are also some messages regarding plugin versions which I cannot fix:

"Expected package @expo/config-plugins@^4.1.0
Found invalid:
  @expo/config-plugins@5.0.0"

v 4.1.0 is specified in the package.json, the only place I can find a reference to 5.0.0 is In the yarn lock file. If I delete this and rerun yarn the reference is recreated

**Comment by GreenCurveDev** [comment]
Hi, thanks for the update - I confess I do not know how to include a version number in package info cache - is this something an end user can do? Thanks for your help.

**Comment by joey-harward** [comment]
I am seeing the same error after upgrading to 6.0.0 today

**Comment by rrust** [comment]
> Hi, thanks for the update - I confess I do not know how to include a version number in package info cache

@GreenCurveDev  No need to, just wait until the fix is deployed and update expo-cli. I suppose it'll be 6.0.1 ;-)
If you want to watch the process live go here: https://github.com/expo/expo-cli/actions/runs/2741971995

**Comment by GreenCurveDev** [comment]
Super cool - thanks! re: the @expo/config-plugins issue, I tried workarounds using "resolutions" in package.json but with no luck - would this new version also correct the issue? (its present in the most basic app created using "expo init".?

**Comment by GreenCurveDev** [comment]
Just installed 6.01 and the message has gone - thanks!!! However, the problems with the @expo/config-plugin is still there on a brand new basic project created with expo init. My concern is that is failing expo doctor on the was build server and I don't know the consequences of that.

expo init ABC123
cd ABC123
expo doctor

gives the following:

Expected package @expo/config-plugins@^4.1.0
Found invalid:
  @expo/config-plugins@5.0.0
  (for more info, run: npm why @expo/config-plugins)

I tried adding a "resolutions" entry but it did not correct the problem.

**Comment by kbrandwijk** [comment]
> Just installed 6.01 and the message has gone - thanks!!! However, the problems with the @expo/config-plugin is still there on a brand new basic project created with expo init. My concern is that is failing expo doctor on the eas build server and I don't know the consequences of that.
> 
> expo init ABC123 cd ABC123 expo doctor
> 
> gives the following:
> 
> Expected package @expo/config-plugins@^4.1.0 Found invalid: @expo/config-plugins@5.0.0 (for more info, run: npm why @expo/config-plugins)
> 
> I tried adding a "resolutions" entry but it did not correct the problem.

We'll look into this. However, I think you should be able to give it a try. `expo doctor` warns during build, but it doesn't stop the build. Let me know if that works.

**Comment by GreenCurveDev** [comment]
Update: The only way I could prevent these messages was to degrade expo to version 44.0.0 (also had to downgrade react-native to a compatible version 64.3). Adding 'resolutions' to package.json did not have the desired effect.

**Comment by alickcai** [comment]
the message is gone after I installed 6.0.1, thanks!

**Comment by GreenCurveDev** [comment]
Finally got all the latest versions aligned (so no errors/warnings) but...when I try to load an App using Expo GO it doesn't run - reason..."The project you requested requires a newer version of Expo Go". Fair enough but unfortunately, I have the latest version and the last available update is 2 months old". I am really hoping that this is pilot error on my part but its not looking good - have deleted app and reinstalled. Appreciate this may not be/is not the correct forum but cannot find an Expo Go specific site. Any advice appreciated. Thanks
