### ISSUE TITLE
new dev set up, not opening in browser to connect to phone or simulator

### ISSUE THREAD

**Issue by lilshebeary** [expo/expo-cli#4488]
### Summary

I had to wipe my computer and re set up development environment. Since doing this, the app runs but I have no way to see it. after reinstalling, it no longer opens up in the browser for me to select a devise or a simulator. Not sure why, never had this issue in the past. I am unable to find a resolution online.

they won't update my email on github, please respond cirijaye@yahoo.com

### Environment

Need to install the following packages:
  expo-env-info
Ok to proceed? (y) y

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
      npm: 7.24.2 - ~/.nvm/versions/node/v14.20.0/bin/npm
      Watchman: 2022.07.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.6 => 45.0.6 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ^0.69.3 => 0.69.3 
      react-native-web: ^0.18.7 => 0.18.7 
    npmGlobalPackages:
      expo-cli: 5.5.1
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

I can't get there

### Error output

I have other bugs in my program that I am trying to resolve but they shouldn't be effecting it not opening in the browser. Hopefully the above info will figure out what is happening

### Reproducible demo or steps to reproduce from a blank project

ran watchman watch-del dksjgldfglkfdlkglfk ; watchman watch project sdkjfdjflsjdf;l

{
    "version": "2022.07.04.00",
    "watch-del": true,
    "root": "/Users/ciriryan/Desktop/projects/PSCamera/presize-camera"
}
{
    "version": "2022.07.04.00",
    "watch": "/Users/ciriryan/Desktop/projects/PSCamera/presize-camera",
    "watcher": "fsevents"
}

MacBook-Pro:pa ciriryan$ npm start

> p@1.0.0 start
> react-native start

warn Package expo contains invalid configuration: "dependency.platforms.ios.podspecPath" is not allowed,"dependency.platforms.ios.project" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package react-native-vector-icons contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
                                                      
                        #######                       
                   ################                   
                #########     #########               
            #########             ##########          
        #########        ######        #########      
       ##########################################     
      #####      #####################       #####    
      #####          ##############          #####    
      #####    ###       ######       ###    #####    
      #####    #######            #######    #####    
      #####    ###########    ###########    #####    
      #####    ##########################    #####    
      #####    ##########################    #####    
      #####      ######################     ######    
       ######        #############        #######     
         #########        ####       #########        
              #########          #########            
                  ######### #########                 
                       #########                      
                                                      
                                                      
                    Welcome to Metro!
              Fast - Scalable - Integrated

To reload the app press "r"
To open developer menu press "d"

warn No apps connected. Sending "devMenu" to all React Native apps failed. Make sure your app is running in the simulator or on a phone connected via USB.
info Opening developer menu...

**Comment by andrejpavlovic** [comment]
I'm guessing it's because Web UI has been removed from latest version of `expo-cli`?
https://blog.expo.dev/sunsetting-the-web-ui-for-expo-cli-ab12936d2206

**Comment by lilshebeary** [comment]
ok, how do you now choose simulator or devise, lan or ?

**Comment by newme616** [comment]
> ok, how do you now choose simulator or devise, lan or ?

you just use it via terminal

**Comment by faijan-memon-kt** [comment]
@newme616  how can we do that, i have created expo app and i am scanning the code printed on terminal but expo app in my phone keeps saying 'Network time out" , my phone and my system both are connected on same wifi.

**Comment by lilshebeary** [comment]
> > ok, how do you now choose simulator or devise, lan or ?
> 
> you just use it via terminal

when taking the time to answer the question it is helpful to not just say the terminal, you could add what to type into the terminal, that would be a helpful way of answering the question for me and anyone else searching for answers.

**Comment by Programmer-** [comment]
> 

'shift+a' command lets you select a device or emulator.

**Comment by lilshebeary** [comment]
Thank you, that is helpful :)

**Comment by snmzhako** [comment]
> > 
> 
> 'shift+a' command lets you select a device or emulator.
> 
> Devices available will be listed and you can then choose whichever device you want to run your app on from the terminal.

Where exactly do I type this command?

**Comment by Programmer-** [comment]
From the terminal where you executed your start up script using the 'expo start'/ 'npm start' command

**Comment by Programmer-** [comment]
> > > 
> > 
> > 
> > 'shift+a' command lets you select a device or emulator.
> > Devices available will be listed and you can then choose whichever device you want to run your app on from the terminal.
> 
> Where exactly do I type this command?

From the terminal where you executed your start up script using the 'expo start'/ 'npm start' command

**Comment by exoriparian** [comment]
I'm still confused about what is and isn't enabled at this point.  If I'm on windows, am I still able to launch an apple or android emulator of my app through the npm start menu?  if so, do i need to install anything beforehand?  like the android workshop or the apple equivalent?  sorry if this is basic but i've just found a lot of conflicting answers.  thanks in advance...
