### ISSUE TITLE
Expo is not starting the development server. 

### ISSUE THREAD

**Issue by mukul98s** [expo/expo-cli#4489]
### Expected
When I run `expo start` the project was supposed to start as usual.

### Actual
I'm getting a prompt to install @types/react even when they are already installed. 

![image](https://user-images.githubusercontent.com/40233491/181780703-a1ed91f4-1bb6-4166-b6cf-d1f3ce0f0f5f.png)

I have not updated anything. It happened overnight. 

I have also verified this issue by initializing a new react-native project with typescript. I'm getting the same prompt of installing type for react.

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      babel-preset-expo: ^9.1.0 => 9.1.0
      expo: ~45.0.0 => 45.0.6
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

The project never starts. 

### Error output

```
'EXPO_DEBUG' is not recognized as an internal or external command,
operable program or batch file.
```

### Reproducible demo or steps to reproduce from a blank project

1. Start a new react-native project with typeScript in managed workflow
2. run `yarn run start` or `expo start`

**Comment by lokeshchoudhary-lc** [comment]
Facing same problem

**Comment by kbrandwijk** [comment]
You probably have a different version installed than the one it wants you to install.
