### ISSUE TITLE
[web] Adjust service worker to use network caching policy by default

### ISSUE THREAD

**Issue by ide** [expo/expo-cli#449]
Currently, the service worker has a longer caching policy than is specified in HTTP response headers. When you redeploy a site and visit the page, you still see the old site for awhile or until you force-reload the page.

The service worker defaults should prioritize correctness and understandability -- when I deploy the site, if the server has the new code, I should see the new site on my next visit. When I change HTTP caching headers, they should take effect as if the service worker weren't there unless the developer explicitly takes action to opt into murkier caching.

**Comment by danmaas** [comment]
I just ran into this issue when deploying an Expo project as a PWA with `expo build:web`.

My web server is configured to return a strict Cache-Control header on `index.html` and `service-worker.js` that tells the browser never to cache these files:

```
Cache-Control: max-age=0,no-cache,no-store,must-revalidate
```

Despite this, I often see an outdated version of index.html when visiting the app. I usually have to clear the browser cache and/or un-register the service worker in order to see updates. I'm not 100% sure, but it seems like the service worker is not obeying this header and returning a stale version of `index.html`.

As a work-around, I created a `webpack.config.js` that tweaks Expo's webpack configuration to adjust the Google Workbox parameters, telling Workbox never to cache these two files. Complete contents of `webpack.config.js` follows:

```
// partially override expo-cli's built-in webpack config to fix some
// errors in production builds.
// note: this only affects the expo web build, not native/mobile.

const expoConfig = require('@expo/webpack-config');

module.exports = async function(env, argv) {
    let conf = await expoConfig(env, argv);
    
    // adjust Google Workbox (service worker) config to avoid caching problems
    if(conf['plugins']) {
        conf['plugins'].forEach((plugin) => {
            // detect workbox plugin
            if(plugin['config'] && plugin['config']['swDest'] === 'service-worker.js') {
                // tell it never to cache index.html or service-worker.js
                plugin['config']['exclude'].push(/index.html/);
                plugin['config']['exclude'].push(/service-worker.js/);

                // (optional) tell it to start new service worker versions immediately, even if tabs
                // are still running the old one.
                plugin['config']['skipWaiting'] = true;
            }
        });
    }

    return conf;
};
```

**Comment by nandorojo** [comment]
I'm still facing this issue with the latest expo sdk and CLI.

**Comment by deathemperor** [comment]
for anyone encounter this issue, the solution can be found here https://www.npmjs.com/package/@expo/webpack-config#fully-disabling-the-service-worker.

**Comment by nandorojo** [comment]
Yup ^ disabling offline mode did it for me too.

**Comment by jjg77** [comment]
Ran into this issue recently.  Is disabling the service worker really the only option?  I would like to use the notifications in the future.

**Comment by mbrimmer83** [comment]
Disabling the service didn't work for me. It looks like the old service worker is still hanging around. Anyone ran into this issue?

**Comment by louismuk** [comment]
> Disabling the service didn't work for me. It looks like the old service worker is still hanging around. Anyone ran into this issue?
> 
> ```js
>   const config = await createExpoWebpackConfigAsync(
>     { ...env, offline: false },
>     argv
>   )
> ```
> 
> This has actually made my problem worse. Now the even a hard refresh doesn't give me updates.

you could try this
https://www.npmjs.com/package/webpack-remove-serviceworker-plugin

config.plugins.push(new RemoveServiceWorkerPlugin({filename: "expo-service-worker.js"}));

**Comment by ChronSyn** [comment]
It's possible that the old service worker is still registered for users that visited prior to `offline` being set . In which case, unregistering it would be advised.

In `web/register-service-worker.js` (after running `expo customize:web`, add the following to the `load` function:

```(javascript)
// Unregisters existing service workers
navigator.serviceWorker.getRegistrations().then(function (registrations) {
  for (let registration of registrations) {
    registration.unregister();
  }
})
```

**Comment by joamartico** [comment]
I want to keep the offline functionality but I also want to update the cached version, how can I do it? How can I change the networkFirst strategy that uses workbox to staleWhileRevalidate?
