### ISSUE TITLE
useColorScheme return different result on android between expo Go and expo-dev

### ISSUE THREAD

**Issue by wcastand** [expo/expo-cli#4495]
### Summary

Result of `useColorScheme` are different that the Platform setting for the dark mode between expo go and expo-dev build.

I would expect the useColorScheme to always return the colorScheme defined in the expo config (in my example 'light') or the actual colorScheme of the OS (in my example 'dark')

The emulator are both in Dark mode in the setting of the OS

```
const color = useColorScheme()
console.log(Platform.OS, color)
```

return :

when using expo-dev (`expo start --dev-client` after `yarn run android` and `yarn run ios`):

    on iOS : ios, light
    on Android : android, dark

when using ExpoGo (`expo start`):

    on iOS : ios, light
    on Android : android, light

### Environment

 ``` expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 3.5.0 - /opt/homebrew/bin/fish
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.18 - ~/.yarn/bin/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
      Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.6 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.7 => 0.17.7
    npmGlobalPackages:
      eas-cli: 0.56.0
      expo-cli: 6.0.1
    Expo Workflow: bare
```

### Please specify your device/emulator/simulator platform, model and version

Android emulator pixel a4 / iOS 15.0 iphone 13 pro

### Error output

no error output

### Reproducible demo or steps to reproduce from a blank project

https://github.com/wcastand/stripe-bug

**Comment by brentvatne** [comment]
you need to install expo-system-ui to support this on android. you'll see a warning about this when you run prebuild without the library installed.

`expo install expo-system-ui` - then run a new build
