### ISSUE TITLE
Release Notes for v6

### ISSUE THREAD

**Issue by daveslutzkin** [expo/expo-cli#4496]
### Summary

There's a new major version of expo-cli, v6, but I can't find anywhere release notes for the version. There's `CHANGELOG.md` but that just has dates, it's not clear what's included in v6 or why the major version bump. So I'm scared to update because I don't know if it's going to break our workflows or if there's any config that we need to change or be aware of.

Am I just missing the correct release notes?

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.2 - /opt/homebrew/opt/node@16/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.5.0 - /opt/homebrew/opt/node@16/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/lib/ruby/gems/3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: >=44.0.0-0 <45.0.0 => 44.0.6
      react: 17.0.2 => 17.0.2
      react-native: 0.67.4 => 0.67.4
    npmGlobalPackages:
      eas-cli: 0.55.1
      expo-cli: 5.5.1
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

Doesn't matter for this issue

### Reproducible demo or steps to reproduce from a blank project

Doesn't need a snack because this is about having an old project updating to a newer project:

```
┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│   There is a new version of expo-cli available (6.0.1).                 │
│   You are currently using expo-cli 5.5.1                                │
│   Install expo-cli globally using the package manager of your choice;   │
│   for example: `npm install -g expo-cli` to get the latest version      │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘
```

**Comment by kbrandwijk** [comment]
Each entry in the changelog also includes information on which packages were updated. So there's an entry that includes `expo-cli@6.0.0` and one that includes `expo-cli@6.0.1` in the changelog.

**Comment by daveslutzkin** [comment]
@kbrandwijk right, so what exactly is in v6? Do I have to trawl through the changelog for every entry until I find the v5 tag?
