### ISSUE TITLE
Upgrade from Expo SDK 42 to SDK 46 

### ISSUE THREAD

**Issue by naeembhatti** [expo/expo-cli#4497]
Keep getting errors after `expo update`

` ERROR  Error: Requiring module "node_modules/react-native-reanimated/src/index.ts", which threw an exception: TypeError: this.InnerNativeModule.configureProps is not a function. (In 'this.InnerNativeModule.configureProps(uiProps, nativeProps)', 'this.InnerNativeModule.configureProps' is undefined)`
-----------------------------------------------------------
Following logs I get when I run expo update 

✅ The following packages were updated:
`expo-application, expo-auth-session, expo-barcode-scanner, expo-camera, expo-constants, expo-dev-client, expo-device, expo-font, expo-linking, expo-random, expo-splash-screen, expo-status-bar, expo-updates, @expo/vector-icons, expo-web-browser, @react-native-async-storage/async-storage, @react-native-community/datetimepicker, react-native-gesture-handler, @react-native-masked-view/masked-view, @react-native-picker/picker, react-native-reanimated, react-native-safe-area-context, react-native-screens, react-native-svg, react-native-unimodules, sentry-expo, jest-expo, react-native, react, react-dom, typescript, @babel/core, @types/react, @types/react-dom, react-native-web, @types/react-native, @expo/webpack-config, expo`

🚨 The following packages were not updated. You should check the READMEs for those repositories to determine what version is compatible with your new set of packages:
`@expo/ngrok, @react-navigation/bottom-tabs, @react-navigation/devtools, @react-navigation/drawer, @react-navigation/native, @react-navigation/stack, apisauce, dayjs, format-json, formik, identity-obj-proxy, lodash, native-base, prop-types, querystringify, ramda, react-datepicker, react-native-elements, react-native-keyboard-aware-scroll-view, react-native-modal-datetime-picker, react-native-nfc-manager, react-native-paper, react-native-picker-select, react-native-sectioned-multi-select, react-native-table-component, react-redux, reconnect.js, redux, redux-persist, redux-saga, reduxsauce, seamless-immutable, styled-components, styled-system, yup, @react-native-community/eslint-config, @storybook/addons, @storybook/react-native, @storybook/theming, @types/react-redux, babel-jest, babel-preset-env, buffer, detox, detox-expo-helpers, enzyme, enzyme-adapter-react-16, eslint, eslint-config-prettier, eslint-plugin-prettier, expect, expo-detox-hook, generator-jhipster-react-native, jest, jest-circus, lint-staged, mockery, patch-package, prettier, reactotron-react-native, reactotron-redux, reactotron-redux-saga, redux-devtools-extension, rimraf`

👉 react-native has been changed from 0.69.3 to 0.64.3 because this is the version used in SDK 43.0.0.
`Bare workflow apps are free to adjust their react-native version at the developer's discretion. You may want to re-install react-native@0.69.3 before proceeding.`

🏗  Run `pod install `in your iOS directory and then re-build your native projects to compile the updated dependencies.
------------------------------------------------------
My updated package file looks like below:

```
{
  "name": "......",
  "version": "1.2.0",
  "scripts": {
    "test:watch": "jest --watch",
    "updateSnapshot": "jest --updateSnapshot",
    "coverage": "jest --coverage && open coverage/lcov-report/index.html || xdg-open coverage/lcov-report/index.html",
    "lint": "eslint . --ext .js,.ts,.jsx,.tsx",
    "test": "jest",
    "publish": "expo publish",
    "build:ios": "expo build:ios",
    "build:android": "expo build:android",
    "build:web": "expo build:web",
    "precommit": "lint-staged",
    "start:e2e": "expo start --no-dev --minify",
    "test:e2e": "./e2e/scripts/setup.sh && detox test --configuration ios.sim.release --retries 3",
    "postinstall": "patch-package",
    "prettier": "prettier --write \"{,.,**/,.jhipster/**/}*.{md,json,yml,js,ts,tsx}\"",
    "start": "react-native start",
    "start-dev": "NODE_ENV=development expo start --dev-client",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "NODE_ENV=development expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo/ngrok": "^4.1.0",
    "@expo/vector-icons": "^12.0.0",
    "@react-native-async-storage/async-storage": "~1.15.0",
    "@react-native-community/datetimepicker": "3.5.2",
    "@react-native-masked-view/masked-view": "0.2.5",
    "@react-native-picker/picker": "2.1.0",
    "@react-navigation/bottom-tabs": "^5.11.8",
    "@react-navigation/devtools": "5.1.22",
    "@react-navigation/drawer": "5.12.5",
    "@react-navigation/native": "5.9.4",
    "@react-navigation/stack": "5.14.5",
    "apisauce": "2.1.1",
    "dayjs": "^1.10.7",
    "expo": "^43.0.0",
    "expo-application": "~4.0.0",
    "expo-auth-session": "~3.4.2",
    "expo-barcode-scanner": "~11.1.2",
    "expo-camera": "~12.0.3",
    "expo-constants": "~12.1.3",
    "expo-dev-client": "~0.6.3",
    "expo-device": "~4.0.3",
    "expo-font": "~10.0.3",
    "expo-linking": "~2.4.2",
    "expo-random": "~12.0.1",
    "expo-splash-screen": "~0.13.5",
    "expo-status-bar": "~1.1.0",
    "expo-updates": "~0.10.15",
    "expo-web-browser": "~10.0.3",
    "format-json": "1.0.3",
    "formik": "2.2.9",
    "identity-obj-proxy": "3.0.0",
    "lodash": "^4.17.21",
    "native-base": "^3.0.3",
    "prop-types": "^15.7.2",
    "querystringify": "2.2.0",
    "ramda": "0.27.1",
    "react": "17.0.1",
    "react-datepicker": "3.4.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-elements": "^3.4.2",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-keyboard-aware-scroll-view": "0.9.3",
    "react-native-modal-datetime-picker": "9.1.0",
    "react-native-nfc-manager": "^3.10.0",
    "react-native-paper": "^4.9.2",
    "react-native-picker-select": "^8.0.4",
    "react-native-reanimated": "~2.2.0",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.8.0",
    "react-native-sectioned-multi-select": "0.8.1",
    "react-native-svg": "12.1.1",
    "react-native-table-component": "^1.2.1",
    "react-native-unimodules": "~0.15.0",
    "react-native-web": "0.17.1",
    "react-redux": "7.2.2",
    "reconnect.js": "^1.1.1",
    "redux": "4.0.5",
    "redux-persist": "6.0.0",
    "redux-saga": "1.1.3",
    "reduxsauce": "1.2.0",
    "seamless-immutable": "7.1.4",
    "sentry-expo": "^4.0.0",
    "styled-components": "^5.3.0",
    "styled-system": "^5.1.5",
    "yup": "0.32.8"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@expo/webpack-config": "^0.16.2",
    "@react-native-community/eslint-config": "2.0.0",
    "@storybook/addons": "5.3.21",
    "@storybook/react-native": "5.3.23",
    "@storybook/theming": "5.3.21",
    "@types/react": "~17.0.21",
    "@types/react-dom": "~17.0.9",
    "@types/react-native": "~0.64.12",
    "@types/react-redux": "^7.1.18",
    "babel-jest": "26.6.3",
    "babel-preset-env": "1.7.0",
    "buffer": "6.0.3",
    "detox": "18.3.1",
    "detox-expo-helpers": "git+https://github.com/ruddell/detox-expo-helpers.git#9d02be37c9864dc470fd692f0d69075614b75b31",
    "enzyme": "3.11.0",
    "enzyme-adapter-react-16": "1.15.6",
    "eslint": "7.19.0",
    "eslint-config-prettier": "7.2.0",
    "eslint-plugin-prettier": "3.3.1",
    "expect": "26.6.2",
    "expo-detox-hook": "1.0.10",
    "generator-jhipster-react-native": "^4.2.0",
    "jest": "^26.6.3",
    "jest-circus": "26.6.3",
    "jest-expo": "~43.0.1",
    "lint-staged": "10.5.4",
    "mockery": "2.1.0",
    "patch-package": "6.2.2",
    "prettier": "2.2.1",
    "reactotron-react-native": "^5.0.0",
    "reactotron-redux": "^3.1.3",
    "reactotron-redux-saga": "^4.2.3",
    "redux-devtools-extension": "2.13.8",
    "rimraf": "3.0.2",
    "typescript": "~4.3.5"
  },
  "lint-staged": {
    "{,app/**/,test/**/}*.{js,json,yml,md,ts,tsx}": [
      "prettier --write",
      "eslint --fix --ext .js"
    ]
  },
  "jest": {
    "testMatch": [
      "**/test/**/*.js",
      "**/?(*.)(spec|test).js?(x)"
    ],
    "testPathIgnorePatterns": [
      "/node_modules/",
      "/e2e/",
      "test/setup.js"
    ],
    "moduleNameMapper": {
      "^.+\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "identity-obj-proxy"
    },
    "setupFiles": [
      "./test/setup"
    ],
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
    },
    "transformIgnorePatterns": [
      "node_modules/(?!(@react-native-community|react-native|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|@storybook))"
    ],
    "coveragePathIgnorePatterns": [
      "app/shared/services/api.js",
      "app/shared/themes/",
      "/storybook/",
      "/*\\.story\\.js"
    ],
    "preset": "jest-expo"
  },
  "engines": {
    "node": ">=12.x",
    "npm": ">=6.x"
  }
}

```
My Babel file looks like this 

```
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: ['react-native-reanimated/plugin'],
  };
};

```
any help will be appropriated.

**Comment by jmarceli** [comment]
Hi @naeembhatti,
I had a similar issue and https://github.com/expo/expo/issues/14971#issuecomment-1129608990 helped me a lot

**Comment by SagarMahadik** [comment]
I am not an expert in React native. I was also getting this error while using the bottom sheet. I upgraded "react-native-reanimated": "~2.4.0". It is working now. Hope it may help you.

**Comment by naeembhatti** [comment]
The packages which were not updated how I can update them? do I have to manually update them? is it required? 
Also is it required to run Run pod install?

**Comment by EvanBacon** [comment]
To align packages to the currently installed version of `expo`, run `npx expo install --fix`. For questions about version alignment and upgrading please use the [Expo forums or Discord](https://docs.expo.dev/next-steps/community/).
