### ISSUE TITLE
 hello, I can't get it, I have node - 18.7.0

### ISSUE THREAD

**Issue by arsmur2085** [expo/expo-cli#4498]
### Summary

hello, I can't get it, I have node - 18.7.0
C:\Users\Professional>expo --version
WARNING: expo-cli has not yet been tested against Node.js v18.7.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <15.0.0 (Maintenance LTS)
* >=16.0.0 <17.0.0 (Active LTS)

### Environment

C:\Users\Professional>expo --version
WARNING: expo-cli has not yet been tested against Node.js v18.7.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <15.0.0 (Maintenance LTS)
* >=16.0.0 <17.0.0 (Active LTS)

### Please specify your device/emulator/simulator platform, model and version

C:\Users\Professional>expo --version WARNING: expo-cli has not yet been tested against Node.js v18.7.0. If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues  expo-cli supports following Node.js versions: * >=12.13.0 <15.0.0 (Maintenance LTS) * >=16.0.0 <17.0.0 (Active LTS)

### Error output

C:\Users\Professional>expo --version
WARNING: expo-cli has not yet been tested against Node.js v18.7.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <15.0.0 (Maintenance LTS)
* >=16.0.0 <17.0.0 (Active LTS)

### Reproducible demo or steps to reproduce from a blank project

C:\Users\Professional>expo --version
WARNING: expo-cli has not yet been tested against Node.js v18.7.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <15.0.0 (Maintenance LTS)
* >=16.0.0 <17.0.0 (Active LTS)

**Comment by arsmur2085** [comment]
please help

**Comment by varmab** [comment]
+1 same issue

**Comment by andy19910102** [comment]
You could try to use [nvm-windows](https://github.com/coreybutler/nvm-windows) to control the node.js version in environment, and switch to the version that expo-cli has supported.

**Comment by kbrandwijk** [comment]
What is the problem here? It tells you exactly what is going on. You have Node 18, and the CLI has only been tested against active LTS versions of Node, so Node 14/16.

**Comment by aliajboy** [comment]
I am Currently using V18.7 and see no problem. And these paragraphs that you write here is not error and does nothin to you.
continue programming, then if you encounter any problem, you can unistall Node.js and install LTS version not Current!
You can do it now or later. I'm happy with V18.7 and stay with it.
I get the same messages but they are telling you that they didn't test it with this version, you can test and report if you see any problem, so they can fix it.
happy programming
