### ISSUE TITLE
app.json changes --> no effect for "expo build" --> version/build-version not updating

### ISSUE THREAD

**Issue by ThaBrad** [expo/expo-cli#4500]
### Summary

Expo is building a version that is NOT reflecting current repo/branch app.json version anymore!
And that since ~yesterday morning. Worked flawlessly before!

Should be version 1.15.8 / build version 1.15.8.3 --> but actually builds with a previous version number 1.15.7 (/1.15.7.2).
🤷‍♂️🙉

<img width="578" alt="Screenshot 2022-08-04 at 23 25 12" src="https://user-images.githubusercontent.com/18183189/182955550-09854a3f-829a-44b3-92a6-f2d8fcddcd2a.png">

### Environment

expo build:ios --release-channel production --no-publish

### Please specify your device/emulator/simulator platform, model and version

expo-cli 5.4.7

### Reproducible demo or steps to reproduce from a blank project

https://github.com/DFXswiss/wallet/tree/feature/DEV-367-BTC-Input
* npm install
* expo build:ios --release-channel production --no-publish

(but same with develop branch, if I change the version beforehand

**Comment by brentvatne** [comment]
you need to publish when using classic builds. this happens by default, but you are passing in `--no-publish`, so your most recently published update is being used as the basis for the build. publishing before building does not happen with EAS Build and it will behave as you expected
