### ISSUE TITLE
Cannot use expo app in android 12.1

### ISSUE THREAD

**Issue by shvamabps** [expo/expo-cli#4501]
### Summary

I created the app using the command npx exp init myapp and also installed the expo-cli globally. In both scenarios, the expo app present in the google play store was not able to detect the application running in the project.

### Environment

info Fetching system and libraries information...
System:
OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
Memory: 7.59 GB / 15.40 GB
Shell: 5.8 - /bin/zsh
Binaries:
Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
Yarn: 1.22.19 - /usr/bin/yarn
npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
Watchman: Not Found
SDKs:
Android SDK: Not Found
IDEs:
Android Studio: Not Found
Languages:
Java: 11.0.15 - /usr/bin/javac
npmPackages:
@react-native-community/cli: Not Found
react: 17.0.2 => 17.0.2
react-native: 0.68.2 => 0.68.2
npmGlobalPackages:
react-native: Not Found\

### Please specify your device/emulator/simulator platform, model and version

android 12.1, oneplus nord 2

### Reproducible demo or steps to reproduce from a blank project

Steps to reproduce
1. create the app using the command npx expo init project
2. install the expo application from the play store.
3. then run the application in the terminal
4. scan the qr code mentioned the temrinal

**Comment by EvanBacon** [comment]
This issue can occur when:
- Your device is not on the same network as your computer. 
- The wifi or network has restrictions preventing the connection.
- Your computer has firewalls preventing connection.

I recommend running with an emulator or `npx expo start --tunnel` (starts an ngrok tunnel) to connect.
