### ISSUE TITLE
Can't install expo-cli on windows 10

### ISSUE THREAD

**Issue by isahboy1** [expo/expo-cli#451]
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AppData\Roaming\npm-cache\_logs\2019-03-21T18_06_26_490Z-debug.log

**Comment by isahboy1** [comment]
Help Me Out Please

**Comment by AdamJNavarro** [comment]
Hey @isahboy1,

Sorry you had an issue installing `expo-cli`. A couple things though:

- Please refrain from spamming a post especially a minute after your original post. We seek to help everyone out as timely as we can, but spam is not appreciated and will not get your issue solved any faster.

- Googling errors is a great way to self-triage issues. For instance, this error usually deals with your npm cache. I would suggest taking a look at this [StackOverflow post](https://stackoverflow.com/questions/40566348/maximum-call-stack-size-exceeded-on-npm-install) and seeing if the suggest answers help out.

- When you create issues, please seek to provide as much information as possible by following the issue template provided. The more information you provide, the better equipped we are to help you.

Cheers,
Adam

**Comment by isahboy1** [comment]
Hey@ AdamjNavarro,
Thanks for the help. And i will take noted next time .If i am posting any issue next time

**Comment by isahboy1** [comment]
Thanks i have find the solution to my problem. i location this file in my
node_module and delete  .npmrc file

thanks

**Comment by AdamJNavarro** [comment]
Glad to hear you got it fixed. Thanks for taking my advice to heart.

Hope you enjoy building stuff with Expo and if you have any questions be sure to join our [forums!](https://forums.expo.io/categories)

All the best,

Adam
