### ISSUE TITLE
[webpack-cli] Error: @expo/webpack-config requires a valid mode string which should be one of: development, production.

### ISSUE THREAD

**Issue by alexkendall** [expo/expo-cli#4510]
### Summary

[webpack-cli] Error: @expo/webpack-config requires a valid mode string which should be one of: development, production, none #2367

### Environment

Running './node_modules/.bin/webpack-dev-server -d --config ./web/webpack.config.js --inline --hot --colors', fails and an error is created.

### Please specify your device/emulator/simulator platform, model and version

Mac OSX 13.0 Ventura Command Line

### Error output

[webpack-cli] Error: @expo/webpack-config requires a valid mode string which should be one of: development, production, none #2367

### Reproducible demo or steps to reproduce from a blank project

webpack.config.js

```
const createExpoWebpackConfigAsync = require("@expo/webpack-config");

module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync(env, argv);
  // Customize the config before returning it.
  config.resolve = {
    ...config.resolve,
    alias: {
      "react-native": "react-native-web",
      "react-native-maps": "react-native-web-maps",
    },
    extensions: [ '.web.ts', '.web.tsx', '.web.js', '.js', '.ts', '.tsx' ]
  };
  return config;
};

```

**Comment by NewAlexandria** [comment]
I don't know that I've hit this yet, but I am having issues getting expo to recognize Xcode 14.x, which is part of the Ventura beta.

**Comment by EvanBacon** [comment]
YMMV using Webpack CLI directly. Please use `expo start` or `expo export` to interact with the Webpack bundler.

**Comment by danb4r** [comment]
I got this error after a clean rebuild:

```sh
npx expo prebuild --clean
npx expo run:android --device
```

It does not happen again with ```npm start``` that is a shortcut to ```expo start --dev-client```. 

npm expo 9.2.0
expo-cli 6.1.0
npx expo 0.4.11

**Comment by MordechaiCharlap** [comment]
passing mode worked for me `--env mode=development`
So in your package.json file:
` "build-dev": "webpack --env mode=development",
  "build-prod": "webpack --env mode=production",`

**Comment by g-wozniak** [comment]
For those looking for Cypress integration with components, your `cypress.config.ts` should look similar to:
```
export default defineConfig({
   component: {
      devServer: {
         framework: 'react',
         bundler: 'webpack',
         webpackConfig: {
            mode: 'development'
         }
      }
   }
})
```
to avoid this error.
