### ISSUE TITLE
`@expo/webpack-config@0.17.1` still using `@expo/config@6.0.24`

### ISSUE THREAD

**Issue by outaTiME** [expo/expo-cli#4511]
### Summary

Hey there, 
I'm using Expo SDK46 and `@expo/webpack-config@0.17.1` still uses `@expo/config@6.0.24` in its dependencies which references `@expo/config-plugins@4.1.5`, this causes the `expo-cli doctor` to throw the following warning:

```
Expected package @expo/config-plugins@^5.0.0
Found invalid:
   @expo/config-plugins@4.1.5
   (for more info, run: npm why @expo/config-plugins)
```

At the moment, the only temporary solution is to use:

```
"resolutions": {
  "@expo/config-plugins": "^5.0.0"
}
```

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /private/var/folders/qv/x2xgwlnj1qb2wjnthh5bp_600000gn/T/xfs-9ac8b0cd/node
      Yarn: 3.2.2 - /private/var/folders/qv/x2xgwlnj1qb2wjnthh5bp_600000gn/T/xfs-9ac8b0cd/yarn
      npm: 8.17.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 0.59.0
      expo-cli: 6.0.2
    Expo Workflow: managed

**Comment by BestLeader** [comment]
This issue has regressed from commit 3052b9d from #3763.

Can we refix @kbrandwijk?
