### ISSUE TITLE
Expo does not start

### ISSUE THREAD

**Issue by farhanjaman0723** [expo/expo-cli#4514]
### Summary

I was trying to start doing the Harvard Mobile app development course PROJECT1(the pomodoro timer project) and set up the node js and other stuff as instructed. I logged into my Expo account and now when I'm trying to "expo start" the project, it says :

```
Invalid regular expression: /(node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class


Metro Bundler process exited with code 1
Error: Metro Bundler process exited with code 1
    at ChildProcess.<anonymous> (C:\Users\MOSTOFA\AppData\Roaming\npm\node_modules\expo-cli\node_modules\xdl\src\start\startLegacyReactNativeServerAsync.ts:275:16)
    at Object.onceWrapper (node:events:642:26)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) 
```

I'm using nodejs 16.16.0 rn, I've tried using 16.0.0 and 12.9.0

for 16.0.0, when I run the "expo whoami" to check if I'm logged in, it says:

`
Uncaught Error Error: EPERM: operation not permitted, rename 'C:\Users\MOSTOFA\.expo\state.json.2014073189' -> 'C:\Users\MOSTOFA\.expo\state.json'
`
![xd](https://user-images.githubusercontent.com/111125765/184347360-adc60774-0b11-427c-8775-f92760d3540c.PNG)

for 12.9.0, it says that expo doesn't support that version anymore

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^46.0.3 => 46.0.3
      react: 16.2.0 => 16.2.0
      react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz 

### Error output

'EXPO_DEBUG' is not recognized as an internal or external command,
operable program or batch file.

### Reproducible demo or steps to reproduce from a blank project

I am not being able to open the expo cli, please help

**Comment by EvanBacon** [comment]
Please use the new `npx expo` instead of the legacy `expo-cli` package. This should no longer be an issue. If you do encounter this issue with `npx expo`, please open an issue on the expo/expo repo.
