### ISSUE TITLE
Expo won't download

### ISSUE THREAD

**Issue by wyliecg** [expo/expo-cli#4520]
I'm on macOS 
Node 16.16.0
Npm 8.11.0

I'm trying to download expo-cli by saying npm install --location=global expo-cli but expo won't show afterwards and I have 26 vulnerabilities

After I run that and use an expo command like expo --version
It says zsh: command not found: expo

**Comment by brentvatne** [comment]
1. you don't need to globally install expo-cli anymore, as of sdk 46: https://blog.expo.dev/the-new-expo-cli-f4250d8e3421
2. this means that npm is not installed correctly on your machine. https://stackoverflow.com/questions/15054388/global-node-modules-not-installing-correctly-command-not-found
