### ISSUE TITLE
OutgoingMessage.prototype._headers is deprecated on publish

### ISSUE THREAD

**Issue by ModaxDev** [expo/expo-cli#4530]
### Summary

Hey, guys
When i want to publish my app, from expo start --dev-client
Error when publishing, 

Uploading JavaScript bundles
ERROR
An unknown error occurred.

(node:14474) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.16 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.0 - /Users/clementverhille/.rvm/gems/ruby-3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 4.4.8
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

No simulator

### Error output

(node:14474) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)

### Reproducible demo or steps to reproduce from a blank project

expo start --dev-client and publish project

**Comment by EvanBacon** [comment]
Does the issue occur with `npx expo start --dev-client`?
