### ISSUE TITLE
Some code error are not detected by the build or the local runtime development

### ISSUE THREAD

**Issue by oliviercperrier** [expo/expo-cli#4531]
### Summary

Some error types are not detected by the build script or the local development runtime.

For example, i can try to access undefined properties on an object (which will be highlighted as an error by my editor) but the build will still work and the local web bundling will still be successful.

With a normal ReactJS application, this king of error would make the build/local runtime failed and it should be the same with expo.

There is currently no way to see/know if there are errors like this in our code, which is not very good and not developer friendly.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^9.2.0 => 9.2.0 
      expo: ~45.0.0 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      expo-cli: 6.0.5
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

web, ios 15

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.dev/@olivier.cperrier/frisky-candy

**Comment by oliviercperrier** [comment]
+1

**Comment by brentvatne** [comment]
this is an intentional choice, eg: we do not fail the build if typescript fails as long as we're able to strip typescript from the bundle. this makes it easier to iterate on your app in development. I believe Microsoft worked on a plugin to add this behavior to Metro (react-native's bundler) but I can't recall where to find it.

**Comment by oliviercperrier** [comment]
> this is an intentional choice, eg: we do not fail the build if typescript fails as long as we're able to strip typescript from the bundle. this makes it easier to iterate on your app in development. I believe Microsoft worked on a plugin to add this behavior to Metro (react-native's bundler) but I can't recall where to find it.

@brentvatne  This make it so easy to introduce bug. There is no work around, so that it can be possible to detect error without having to go trough every files in our project?

**Comment by brentvatne** [comment]
yes, you can run `npm run lint` or `npm run test` in your project and set up a lint / test script in package.json to handle this. you can set those to run on watch mode so it stays open

**Comment by oliviercperrier** [comment]
> yes, you can run `npm run lint` or `npm run test` in your project and set up a lint / test script in package.json to handle this. you can set those to run on watch mode so it stays open

@brentvatne I have a lint enable, maybe missing some config. Ill check that more deeply. Thanks for the answer 🙌
