### ISSUE TITLE
Add --https support for Metro bundling in `npx expo`

### ISSUE THREAD

**Issue by cmaycumber** [expo/expo-cli#4537]
### Summary

I'm using `--https` flag with `expo start --web` like: `expo start --web --https` but the server still seems to start in `http` vs.  `https` as expected.

I'm also using the experimental metro bundler for web if that has any relevance and am on `expo-cli@6.0.5`. 

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.volta/tools/image/node/16.14.2/bin/node
      Yarn: 3.2.2 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
      npm: 8.15.1 - ~/.volta/tools/image/npm/8.15.1/bin/npm
      Watchman: 2022.07.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8092744
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

Macbook Pro 2015

### Reproducible demo or steps to reproduce from a blank project

Run `expo start --web --https` on a blank project

**Comment by EvanBacon** [comment]
metro web doesn't have https [support yet](https://github.com/expo/expo/pull/18415), this is also the wrong repo. Legacy expo/expo-cli doesn't support Metro web in any capacity.

**Comment by cmaycumber** [comment]
> metro web doesn't have https [support yet](https://github.com/expo/expo/pull/18415), this is also the wrong repo. Legacy expo/expo-cli doesn't support Metro web in any capacity.

Got I’ll close the issue, thanks for clearing that up!
