### ISSUE TITLE
Firebase/auth import source-map error

### ISSUE THREAD

**Issue by albrimpaqarizi** [expo/expo-cli#4543]
### Summary

I am trying to run the app with expo start but the build is failing due to an import firebase module

This happened with these versions,
Expo CLI version : 6.0.5
Expo SDK Version: 46.0.0

I have tried to fix that with metro config but it doesn't work and I don't find any solution anywhere

The error log is below. Please tell me a solution

### Environment

run: expo start or npx expo start

### Please specify your device/emulator/simulator platform, model and version

--platform android

### Error output

Android Bundling failed 3947ms
Unable to resolve "../../../../src/firebase/auth" from "node_modules\firebase\auth\dist\index.esm.js"

### Reproducible demo or steps to reproduce from a blank project

1. expo install firebase (version: 9+)
2. import { getAuth } from 'firebase/auth' - and use that 
3. run project: expo start

**Comment by EvanBacon** [comment]
Perhaps there is a different version of Firebase that has support for legacy imports. Otherwise, this is an issue with Metro bundler not supporting the `exports` field (which they are actively working on).
