### ISSUE TITLE
ApiV2Error: Account not found.

### ISSUE THREAD

**Issue by CarlosEduR** [expo/expo-cli#4547]
### Summary

Already used Expo a few months ago, was coding and running it on my personal device, connected to USB. 
Today decided to start a new project, following documentation, but when I try to load the project through my real device, it throws that message "ApiV2Error: Account not found.". 

I've checked authentication in both sides - expo android app and expo-cli - and both says I'm logged with my personal user 'carlosedur'.

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.14 Ubuntu 20.04.5 LTS (Focal Fossa)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 16.8.0 - ~/.nvm/versions/node/v16.8.0/bin/node
      Yarn: 1.22.11 - ~/.nvm/versions/node/v16.8.0/bin/yarn
      npm: 7.21.0 - ~/.nvm/versions/node/v16.8.0/bin/npm
    npmPackages:
      expo: ~46.0.9 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
    npmGlobalPackages:
      expo-cli: 6.0.5
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Samsung Galaxy A30s - SM_A307GT 

### Error output

`ApiV2Error: Account not found.
    at ApiV2Client._requestAsync (/home/carlos/.nvm/versions/node/v14.19.3/lib/node_modules/expo-cli/node_modules/xdl/src/ApiV2.ts:244:21)`

![image](https://user-images.githubusercontent.com/40635471/189518291-e38d7eb8-3b7b-4f75-b7a6-6c8ddb94ab45.png)

### Reproducible demo or steps to reproduce from a blank project

1. Create project using `npx create-expo-app my-app`;
2. Run it using `expo start`;
3. When try to run the application on real device, connected on USB, using Expo App downloaded at PlayStore - latest version available;
4. See the error on terminal and Expo App

**Comment by CarlosEduR** [comment]
After hours, created another account and tried with it, it worked.

**Comment by joshuabroqueza** [comment]
Hi, how did you fix the issue?

**Comment by CarlosEduR** [comment]
Hey Joshua, actually I didn't fix it. I just tried to create another account in Expo, and with this new one, it worked.

**Comment by byCedric** [comment]
If you have issues with your account, please contact us through email `secure@expo.dev`. We can help you in private. Closing as this doesn't seem to be an issue with the CLI.
