### ISSUE TITLE
@expo/next-adapter unexpected property, projectRoot

### ISSUE THREAD

**Issue by linojon** [expo/expo-cli#4548]
### Summary

Trying the create a new expo project with next.js, i followed the steps here: o	https://github.com/expo/expo/blob/master/docs/pages/guides/using-nextjs.md#add-nextjs-to-expo-projects as follows:

```
$ npx create-expo-app -t expo-template-blank-typescript
cd to the folder
$ yarn add @expo/next-adapter
$ yarn next-expo
$ yarn next dev
```

it tries to start with the following message, and browsing to http://localhost:3000 loads nothing.

```
  - The root value has an unexpected property, projectRoot, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress,
 crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, future, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, 
images, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewr
ites, sassOptions, serverRuntimeConfig, staticPageGenerationTimeout, swcMinify, trailingSlash, typescript, useFileSystemPublicRoutes, webpack).
```

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156
    npmPackages:
      expo: ~46.0.9 => 46.0.10
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
      react-native-web: ~0.18.7 => 0.18.9
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

any

### Error output

see above

### Reproducible demo or steps to reproduce from a blank project

see above

**Comment by the-programmer-alex** [comment]
Get the same, but when trying to add Expo to an existing Nextjs project.

**Comment by chrisarts** [comment]
The package is not updated, 4.0.13 still has the old package code.

**Comment by sgrund14** [comment]
still seeing the warnings in v5.0.2
