### ISSUE TITLE
npx expo run:ios -d not installing app on my iOS device

### ISSUE THREAD

**Issue by dingshukai** [expo/expo-cli#4549]
### Summary

according to https://docs.expo.dev/development/build/ ,

> The npx expo run commands will create a new build, install it on to your emulator or device, and start running it.

but "npx expo run:ios -d" on my mac does not install any app on my connected device.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.9.0 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 8.19.1 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
      Android SDK:
        Build Tools: 31.0.0
    IDEs:
      Xcode: 14.0/14A309 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.9 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.5
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

iPhone 11 pro, 14.6

### Error output

no error output.
the problem is no app is installed on my device.

### Reproducible demo or steps to reproduce from a blank project

npx create-expo-app my-app
cd my-app
npm run ios -d   
arrow select my device, which is connected to my mac through usb
scan the QR code and got "no usable data found"
check my device and find no new app installed.

**Comment by brentvatne** [comment]
> but "npx expo run:ios -d" on my mac does not install any app on my connected device.

this is not the same as `npm run ios -d`:

```
npm run ios

> dingshukai@1.0.0 ios
> expo start --ios
```

`npm run` will throw away the `-d` flag. `expo start --ios -d` will show you this:

```
expo start -d

  error: unknown option `-d'
```

if you use `npm run ios` then it will launch into the simulator.

use `npx expo run:ios -d` in order to build your app with xcodebuild and install to your device.

**Comment by dingshukai** [comment]
> > but "npx expo run:ios -d" on my mac does not install any app on my connected device.
> 
> this is not the same as `npm run ios -d`:
> 
> ```
> npm run ios
> 
> > dingshukai@1.0.0 ios
> > expo start --ios
> ```
> 
> `npm run` will throw away the `-d` flag. `expo start --ios -d` will show you this:
> 
> ```
> expo start -d
> 
>   error: unknown option `-d'
> ```
> 
> if you use `npm run ios` then it will launch into the simulator.
> 
> use `npx expo run:ios -d` in order to build your app with xcodebuild and install to your device.

I did use `npx expo run:ios -d`, not `npm run ios`

**Comment by dingshukai** [comment]
> > but "npx expo run:ios -d" on my mac does not install any app on my connected device.
> 
> this is not the same as `npm run ios -d`:
> 
> ```
> npm run ios
> 
> > dingshukai@1.0.0 ios
> > expo start --ios
> ```
> 
> `npm run` will throw away the `-d` flag. `expo start --ios -d` will show you this:
> 
> ```
> expo start -d
> 
>   error: unknown option `-d'
> ```
> 
> if you use `npm run ios` then it will launch into the simulator.
> 
> use `npx expo run:ios -d` in order to build your app with xcodebuild and install to your device.

I did use `npx expo run:ios -d`, not `npm run ios`

**Comment by brentvatne** [comment]
that isn't what you said in your post. please provide a video recording showing what you are doing

**Comment by dingshukai** [comment]
> that isn't what you said in your post. please provide a video recording showing what you are doing

sorry that's a typo.

screenshots:

<img width="614" alt="DX-20220916@2x" src="https://user-images.githubusercontent.com/11957952/190551909-a2aa8637-a496-463d-90cf-04aef7257b84.png">
<img width="578" alt="DX-202209161@2x" src="https://user-images.githubusercontent.com/11957952/190551944-8684bf29-db03-41b6-82c1-1599aca04017.png">
<img width="543" alt="DX-202209162@2x" src="https://user-images.githubusercontent.com/11957952/190551980-3fb09cfa-e461-49fd-a656-e59503bc8778.png">
<img width="487" alt="DX-202209164@2x" src="https://user-images.githubusercontent.com/11957952/190552021-079d97b5-31bd-4165-8c26-218f91abfc82.png">

**Comment by brentvatne** [comment]
do you have expo-dev-client installed in your project?

**Comment by dingshukai** [comment]
> do you have expo-dev-client installed in your project?

No... I forgot this.
 
Just now I tried these:
npx expo install expo-dev-client
npx expo run:ios -d

still has no luck. the app is not installed on my device.
![image](https://user-images.githubusercontent.com/11957952/190648824-be6da867-85e2-4b0b-a7c3-681e804cff2c.png)

![image](https://user-images.githubusercontent.com/11957952/190648927-48103c98-9a22-4ce9-a879-7f36f54a244b.png)

**Comment by brentvatne** [comment]
@dingshukai - can you run `DEBUG=* npx expo run:ios -d` and share the full logs?

**Comment by dingshukai** [comment]
> @dingshukai - can you run `DEBUG=* npx expo run:ios -d` and share the full logs?
see attachment
[debuglog.txt](https://github.com/expo/expo-cli/files/9590604/debuglog.txt)

**Comment by dingshukai** [comment]
I run `npx expo run:ios -d` on another device  and get no luck either.
but building with xcode installs development app on the device.
Chances are that I miss some important step.

**Comment by dingshukai** [comment]
finally I fixed.
I changed the node version from v18 to v16 and it worked.
the weird thing is there is no error under v18.
thanks for your time @brentvatne

**Comment by ariccio** [comment]
WEIRD. Swapping to node 16 with nvm got SOME reaction from the physical device, but still didn't boot correctly!!

**Comment by ariccio** [comment]
I had to manually input the dev server URL, and it runs correctly. There's a bug here for sure.

**Comment by izakfilmalter** [comment]
Getting the same thing on node 18.
