### ISSUE TITLE
React native EAS Android Build fails

### ISSUE THREAD

**Issue by CRIMSON-CORP** [expo/expo-cli#4551]
### Summary

Im trying to build My Expo app with EAS build, but it keeps failing, this fails for Android, i am not sure about IOS, i think it has to do with React native navigation

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.17.0 - C:\Program Files (x86)\nodejs\node.EXE
      Yarn: 1.22.19 - ~\node_modules\.bin\yarn.CMD
      npm: 8.3.0 - C:\Program Files (x86)\nodejs\npm.CMD
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Mobile, Android 

### Error output

![Screenshot 2022-09-16 181630](https://user-images.githubusercontent.com/71358573/190652828-0541753a-2402-46ed-9b66-04d04433fe92.png)

### Reproducible demo or steps to reproduce from a blank project

- Created new Expo project with **`npx create-expo-app my-app`**
- Using **`"react-native-navigation": "^7.26.0`**", which i think is the main cause of the problem as regards line 42 of the error log in the screenshot
- eas build fails with feedback **`Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.`**

**Comment by amandeepmittal** [comment]
Hey @CRIMSON-CORP.

The `react-native-navigation` library is not yet compatible with Expo Go or `expo-dev-client`. For more info on this, please go through our FAQ section in https://docs.expo.dev/guides/routing-and-navigation/.

We do recommend using [`createNativeStackNavigator`](https://reactnavigation.org/docs/native-stack-navigator) from React Navigation to use Android and iOS native navigation APIs.

**Comment by CRIMSON-CORP** [comment]
> Hey @CRIMSON-CORP,
> 
> The `react-native-navigation` library is not yet compatible with Expo Go or `expo-dev-client`. For more info on this, please go through our FAQ section in https://docs.expo.dev/guides/routing-and-navigation/.
> 
> We do recommend using [`createNativeStackNavigator`](https://reactnavigation.org/docs/native-stack-navigator) from React Navigation to use Android and iOS native navigation APIs.

Thank you for your support, this has solved my problem and my app has been built successfully, im not sure why i installed that library cause i never used it, i wonder why it was breaking my build since i never imported it in my app

**Comment by stephenson080** [comment]
Pleas is your build working?

**Comment by stephenson080** [comment]
I successfully built an APK. After installing it on my device. The app keeps stopping

**Comment by CRIMSON-CORP** [comment]
Yes my build is working,  but i recently built an App which was also crashing whenever i moved to another page, i am using react-native-navigation by the way, i just thought it was a bug in my code, it works perfectly in development but crashes on production

**Comment by Azizbekshams** [comment]
@amandeepmittal please help me bro

[stderr] Note: /home/expo/workingdir/build/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java uses or overrides a deprecated API.
[stderr] Note: Recompile with -Xlint:deprecation for details.
[stderr] Note: /home/expo/workingdir/build/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStoragePackage.java uses unchecked or unsafe operations.
[stderr] Note: Recompile with -Xlint:unchecked for details.

**Comment by amandeepmittal** [comment]
Hey @Azizbekshams, the log shared is not clear or enough. Can you create a post either in forums.expo.dev with a link to your build? This will help us provide more information.
