### ISSUE TITLE
[next-adapter] unable to resolve dependency tree

### ISSUE THREAD

**Issue by philiplindberg** [expo/expo-cli#4553]
### Summary

I'm trying to use Next.js with my existing Expo app as per [this guide](https://docs.expo.dev/guides/using-nextjs/). 
However, I'm getting the following error when running `npm i --save-dev @expo/next-adapter`:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: expo-next@1.0.0
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.2" from next@11.1.4
npm ERR! node_modules/next
npm ERR!   peer next@"^11" from @expo/next-adapter@4.0.12
npm ERR!   node_modules/@expo/next-adapter
npm ERR!     dev @expo/next-adapter@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/philiplindberg/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/philiplindberg/.npm/_logs/2022-09-19T15_12_42_884Z-debug-0.log
```

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.7.0 - /opt/homebrew/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.15.0 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.0/14A309 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.2
      expo: ~46.0.9 => 46.0.9
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
      react-native-web: ~0.18.7 => 0.18.7
    npmGlobalPackages:
      eas-cli: 2.1.0
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

Web

### Reproducible demo or steps to reproduce from a blank project

Clone repro:
```
git clone https://github.com/philiplindberg/expo-next-adapter-repro
```
Install expo next adapter:
```
npm i --save-dev @expo/next-adapter
```

**Comment by Vuliniar** [comment]
@philiplindberg same on my side. Did you figure out workaround? I don't like solution going backwards to next@11.

**Comment by philiplindberg** [comment]
@Vuliniar I actually just ended up using yarn instead of npm, then everything works fine.

**Comment by Smokovsky** [comment]
Try this:
npm i --save-dev @expo/next-adapter --legacy-peer-deps

More:
https://github.com/npm/cli/issues/4998

**Comment by valerius21** [comment]
Having the same issue. Even with removing `*.lock` files the error persits.
Using `--legacy-peer-deps` seems for me like a temporary solution, which unfortunately is pretty inconvenient.
