### ISSUE TITLE
failed to resolve android path

### ISSUE THREAD

**Issue by krishnacharyGITHUB** [expo/expo-cli#4557]
### Summary

› Press a │ open Android
› Press w │ open web

› Press r │ reload app
› Press m │ toggle menu

› Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.
› Opening on Android...
Failed to resolve the Android SDK path. Default install location not found: /home/Name/Android/sdk. Use ANDROID_HOME to set the Android SDK location.
Failed to resolve the Android SDK path. Default install location not found: /home/name/Android/sdk. Use ANDROID_HOME to set the Android SDK location.
Error: spawn adb ENOENT

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.0 Linux Mint 19.3 (Tricia)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 16.17.0 - /usr/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 8.15.0 - /usr/bin/npm
    IDEs:
      Android Studio: AI-212.5712.43.2112.8815526
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.2 
      expo: ~46.0.8 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
      react-native-web: ~0.18.7 => 0.18.9 
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

android simulator

### Reproducible demo or steps to reproduce from a blank project

Logs for your project will appear below. Press Ctrl+C to exit.
› Opening on Android...
Failed to resolve the Android SDK path. Default install location not found: /home/krishna/Android/sdk. Use ANDROID_HOME to set the Android SDK location.
Failed to resolve the Android SDK path. Default install location not found: /home/krishna/Android/sdk. Use ANDROID_HOME to set the Android SDK location.
Error: spawn adb ENOENT

**Comment by EvanBacon** [comment]
This issue means your computer is not set up for developing Android apps. Please follow the [instructions here](https://reactnative.dev/docs/environment-setup#target-os-1) and try again.

**Comment by kuriel-trivu** [comment]
any update?

**Comment by kuriel-trivu** [comment]
any update?
