### ISSUE TITLE
Error: Request failed with status code 408

### ISSUE THREAD

**Issue by nasyana** [expo/expo-cli#4562]
### Summary

When I try to publish recently - regularly has this issue: 

Uploading JavaScript bundles
Request failed with status code 408
Error: Request failed with status code 408

### Environment

 System:
      OS: macOS 12.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.17.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.15.0 - /usr/local/bin/npm
      Watchman: 2022.08.15.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.0, iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.0/14A5228q - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 6.0.5
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

N/A

### Error output

Uploading JavaScript bundles
Request failed with status code 408
Error: Request failed with status code 408

### Reproducible demo or steps to reproduce from a blank project

N/A

**Comment by EvanBacon** [comment]
[408](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/408#:~:text=The%20HyperText%20Transfer%20Protocol%20(HTTP,previous%20request%20by%20the%20client.) means the server had an outage. Should be fine now. You can see the [outage report here](https://status.expo.dev/incidents/gx3m0k5hdsy0). Follow https://status.expo.dev/ to verify outages in the future.
