### ISSUE TITLE
Installing JavaScript dependencies

### ISSUE THREAD

**Issue by JK-02** [expo/expo-cli#4563]
I inserted code in Powershell "expo init OOOOOO" and Just keep installing in this step (Installing JavaScript dependencies ). Never thinking of going to next step. I saw OOOOOO file has added in my drive but that process has never terminated. What should I do?

PS D:\ggg> expo init OOOOOO

WARNING: expo-cli has not yet been tested against Node.js v18.9.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <15.0.0 (Maintenance LTS)
* >=16.0.0 <17.0.0 (Active LTS)

Migrate to using:
› npx create-expo-app --template

√ Choose a template: » blank               a minimal app as clean as an empty canvas
√ Downloaded template.
📦 Using npm to install packages.
/ Installing JavaScript dependencies.

**Comment by kbrandwijk** [comment]
Did you try what it says, and use `npx create-expo-app`?

**Comment by EvanBacon** [comment]
This is purely related to the speed of the network and npm server issues. You can use the `--no-install` flag to skip installing, then `cd` into the project and manually install if you'd like. There isn't much we can do outside of that.
