### ISSUE TITLE
Dynamic config based on running in Expo Go or not

### ISSUE THREAD

**Issue by Kojon74** [expo/expo-cli#4564]
I have some config that I need when running my app outside of Expo Go (for Google Authentication):

`currentFullName: "@kojon74/clearo",
originalFullName: "@kojon74/clearo",`

But when I leave this in app.json, I get [this error](https://github.com/expo/expo-cli/issues/4440) when running with Expo Go

I tried importing

`import Constants, { ExecutionEnvironment } from require("expo-constants");`

in my app.config.ts file. However, after reading [this issue](https://github.com/expo/expo/issues/8803) I realized that I cannot make this import.

Is there any other way to achieve this?

**Comment by byCedric** [comment]
Hi! You can't import libraries for React Native inside Node. That's just not how they were designed to work.

However, you can use `@expo/config` to load the configuration of your app. We use this internally.

```js
const { getConfig } = require('@expo/config');

// Provide the root of the app as path, either absolute or relative
const { exp } = getConfig('./my-app', { isPublicConfig: true });

// These are only available when using `isPublicConfig: true`
console.log('currentFullName', exp.currentFullName);
console.log('originalFullName', exp.originalFullName);
```

Hope this helps!
