### ISSUE TITLE
expo pre build error - [ios.dangerous]: withIosDangerousBaseMod: Could not locate a valid AppDelegate at root:

### ISSUE THREAD

**Issue by elvisdsilva07** [expo/expo-cli#4567]
### Summary

while running - `npx expo prebuild` getting the rolling error
[ios.dangerous]: withIosDangerousBaseMod: Could not locate a valid AppDelegate at root:

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.0.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.19.2 - ~/TruEquations/healome-mobile-expo/node_modules/.bin/npm
      Watchman: 2022.09.12.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
      Android SDK:
        API Levels: 28, 29, 30, 31, 33
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
        System Images: android-29 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.0/14A309 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.6
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

Xcode cli 14.0.2

### Error output
✖ Config sync failed
[ios.dangerous]: withIosDangerousBaseMod: Could not locate a valid AppDelegate at root:

### Reproducible demo or steps to reproduce from a blank project

`npx expo prebuild`

**Comment by micksmits** [comment]
Also getting this error on ~46.0.16 and the same xcode version as OP.

**Comment by EvanBacon** [comment]
This was resolved by adding support for [`AppDelegate.mm`](https://github.com/expo/expo/blob/66c59ea7086d3f3ce41f7e17dc7e48e76f70bb80/packages/%40expo/config-plugins/src/ios/Paths.ts#L48) but the issue can persist if you have older versions of `@expo/config-plugins` installed. Running `expo-cli doctor` will tell you if this is an issue.
