### ISSUE TITLE
No packages updated after expo upgrade console log confirms packages were updated 

### ISSUE THREAD

**Issue by TomBerriot** [expo/expo-cli#4574]
### Summary

When running `expo upgrade`, logs confirm all packages were updated, but actually none were updated (already up to date).

Code responsible for computing which package have been updated during the command : https://github.com/expo/expo-cli/blob/208354c051037a92c9d837bde425396244ca77c9/packages/expo-cli/src/commands/info/upgradeAsync.ts#L78

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.1.3 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    IDEs:
      Android Studio: Arctic Fox 2020.3.1 Patch 3 Arctic Fox 2020.3.1 Patch 3
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.7 => 46.0.10
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Using latest app version

### Reproducible demo or steps to reproduce from a blank project

- Having any expo project
- Ensuring all packages are already up to date
- Running expo upgrade command
- Checking console 

> ✔ You are already using the latest SDK version. Do you want to run the update anyways? This may be useful to ensure that all of your packages are set to the correct version
...
✅ The following packages were updated:
expo-camera, expo-clipboard, expo-linking, expo-notifications, expo-store-review, react, react-dom, react-native, react-native-safe-area-context, react-native-webview, sentry-expo, typescript, @babel/core, @types/react, @types/react-dom, @types/react-native, expo

This list is actually simply the list of packages of the actual version, dependencies + devDependecies with some specific dependencies removed by the code.

What it should be :  
> 0 packages were updated.

**Comment by byCedric** [comment]
Hi @TomBerriot! Thanks for the report. In the [new Expo CLI](https://blog.expo.dev/the-new-expo-cli-f4250d8e3421), we've fully overhauled this command in `npx expo install --check` and `npx expo install --fix`.

If you still have trouble with the new CLI, please open a new issue on [github.com/expo/expo](https://github.com/expo/expo).

Hope this helps!
