### ISSUE TITLE
Expo CLI is not working in node v18.12.0

### ISSUE THREAD

**Issue by tanbirahammad** [expo/expo-cli#4583]
### Summary

npm start does not work in expo cli

### Environment

npm start

### Please specify your device/emulator/simulator platform, model and version

vs code

### Error output

WARNING: expo-cli has not yet been tested against Node.js v18.12.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <15.0.0 (Maintenance LTS)
* >=16.0.0 <17.0.0 (Active LTS)

### Reproducible demo or steps to reproduce from a blank project

Starting project at D:\react native\starter\scopalomin
Unable to find expo in this project - have you run yarn / npm install yet?

**Comment by EvanBacon** [comment]
Please migrate to the new versioned Expo CLI (npx expo) in SDK 46 which supports a much wider variety of Node.js versions (effectively all LTS+). If the issue persists with npx expo, please reopen on expo/expo with the CLI template and I’ll address it.

**Comment by Albermonte** [comment]
So, there's no way to use `expo-cli` with node v18 and there's no way to use `npx expo upgrade`

The only thing I can do is downgrade node to v16 if I want to upgrade expo to the latest version?
