### ISSUE TITLE
Expo commands don't output raw format

### ISSUE THREAD

**Issue by christynwegner** [expo/expo-cli#459]
## Description

The `--output raw` option does not format the output any differently than the default pretty format. The use case would be to get data in an easy to consume format for scripts (such as in the deploy stage of a CI pipeline in my particular use case).

## Expected Behavior

Any expo cli commands `--option raw` with consumable output should output the raw data in an easy to consume format for scripts.

Also, if the expo cli version is not the most recent version, do not output the upgrade message (if, say, an environment has pinned the expo cli version) such that it doesn't break scripts with unexpected output.

## Observed Behavior

The default (pretty) format is always output regardless of whether `--output raw` is provided or not.

## Environment

```
  Expo CLI 2.13.0 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.12.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^30.0.0 => 30.0.0 
      @types/react: ^16.4.18 => 16.4.18 
      @types/react-native: ^0.57.7 => 0.57.7 
      @types/react-navigation: ^3.0.1 => 3.0.1 
      expo: ^30.0.1 => 30.0.2 
      react: 16.3.1 => 16.3.1 
      react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4 
      react-navigation: ^3.0.2 => 3.0.2 
    npmGlobalPackages:
      expo-cli: 2.13.0
```

## Reproducible Demo (... well not really any way I can share the expo cli on my environment??? but here's some screenshots)

Output of the current version:
<img width="1327" alt="Screen Shot 2019-03-22 at 12 43 43" src="https://user-images.githubusercontent.com/11824423/54849069-65541b80-4ca0-11e9-807f-99eb81cbc17b.png">

Output of a previous version (with upgrade message):
<img width="1325" alt="Screen Shot 2019-03-22 at 12 37 32" src="https://user-images.githubusercontent.com/11824423/54849094-7bfa7280-4ca0-11e9-888b-d397920b7570.png">

**Comment by christynwegner** [comment]
So, some select commands do have a `--raw` option; however, from `expo --help` the `--output [format]` where format is `pretty` or `raw` does not behave as expected

**Comment by cruzach** [comment]
Hey @christynwegner, 

I just confirmed what you're saying, sorry about this issue. The instructions should be more clear on how to get the format you're looking for.

You can get the raw output by running `expo publish:history --raw` 
You can see this by running `expo publish:history --help` which will give more info on that particular command and the associated flags/options

Thanks!
Charlie
