### ISSUE TITLE
Expo stopped

### ISSUE THREAD

**Issue by clecio81** [expo/expo-cli#4595]
### Summary

Hello, my application using expo go works perfectly, but when I make an apk and install and run the application it simply hangs on the splash screen, I have already revised my code, I have already modified it but 
nothing works 

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: android
    Binaries:
      Node: 18.10.0 - /data/data/com.termux/files/usr/bin/node
      Yarn: 1.22.19 - /data/data/com.termux/files/usr/bin/yarn
      npm: 8.19.2 - /data/data/com.termux/files/usr/bin/npm
    npmPackages:
      expo: ^46.0.16 => 46.0.16
      react: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
      react-navigation: ^4.4.4 => 4.4.4
    npmGlobalPackages:
      eas-cli: 2.6.0
      expo-cli: 6.0.8
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Android

### Reproducible demo or steps to reproduce from a blank project

import React, { useState, useEffect } from "react";
import axips from "axios"
//navigation
import { NavigationContainer} from "@react-navigation/native";
import { createNativeStackNavigator } from "@react-navigation/native-stack";
import { Text, View } from "react-native";
import { ActivityIndicator, Colors } from "react-native-paper";
import HomeScreen from '../pages/';
import Web from '../pages/tabs';
import Login from '../pages/login'

//firebase
import {auth} from '../firebase'
const Stack = createNativeStackNavigator();

export default function NavigationStack({ navigation }) {
  const [login, setLogin] = useState(false);
  const [loaded, setLoaded] = useState(false);
  
  useEffect(() => {
   
    auth.onAuthStateChanged((user) => {
      if (!user) {
        setLogin(false);
        setLoaded(true)
      } else {
      setLogin(true);
      setLoaded(true)
      }
    });
  }, []);
  if (!loaded) {
    return (
      <View
        style={{
          flex: 1,
          justifyContent: "center",
          alignItems: "center",
          backgroundColor: "#A74BE8"
        }}
      >
        <ActivityIndicator
          animating={true}
          color={Colors.purple900}
          size="large"
        />
      </View>
    );
  }else if(!login){
     return (
      <NavigationContainer>
        <Stack.Navigator>
          <Stack.Screen
            name="login"
            component={Login}
            options={{
              headerShown: false,
            }}
          />

      </Stack.Navigator>
        </NavigationContainer>
  );
 
  }
  
  return (
      <NavigationContainer>
        <Stack.Navigator>
          <Stack.Screen name="Home" options={{headerShown: false}} component={HomeScreen}/>
          <Stack.Screen name="Web" options={{headerShown: false}} navigation={navigation} component={Web}/>
      </Stack.Navigator>
        </NavigationContainer>
  );
  }

**Comment by EvanBacon** [comment]
You have an error preventing the app from starting. You can build the app locally to determine where the error is: `npx expo run:android`. cite: [native debugging](https://docs.expo.dev/workflow/debugging/#android-studio).
