### ISSUE TITLE
Everytime I run npm start, I am facing Unable to find expo in this project - have you run yarn / npm install yet?

### ISSUE THREAD

**Issue by mianaamirshehzad** [expo/expo-cli#4597]
### Summary

I'm using the following packages:

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-picker/picker": "^1.9.4",
    "@react-navigation/native": "^5.8.10",
    "@react-navigation/stack": "^5.12.8",
    "expo": "~39.0.2",
    "expo-status-bar": "~1.0.2",
    "firebase": "7.9.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz",
    "react-native-carousel-control": "^2.0.1",
    "react-native-gesture-handler": "~1.7.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-modal": "^11.6.1",
    "react-native-reanimated": "^1.13.2",
    "react-native-safe-area-context": "3.1.4",
    "react-native-screens": "~2.10.1",
    "react-native-simple-radio-button": "^2.7.4",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "12.1.0",
    "react-native-textarea": "^1.0.4",
    "react-native-vector-icons": "^7.1.0",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0"
  },
  "private": true
}

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 18.9.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7935034
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

I have Android 12 (using Expo Go app)

### Error output

Unable to find expo in this project - have you run yarn / npm install yet?

### Reproducible demo or steps to reproduce from a blank project

I have an app for online booking tickets of buses. The app is developed in React Native

**Comment by byCedric** [comment]
Hi @mianaamirshehzad! It seems that you are using an outdated and unsupported Expo SDK (`expo@39.0.2`). The oldest supported SDK is `expo@45`, and the latest is `expo@47`. Try upgrading to either one of these SDKs, or try to downgrade `expo-cli` to either `3.x.x` or `4.x.x`.

Hope this helps!

**Comment by Desmondonam** [comment]
I also face the same issue, and I am not sure how this could be, because mine are all upgraded
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~46.0.17",
    "expo-status-bar": "~1.4.0",
    "react": "18.0.0",
    "react-native": "0.69.6",
    "expo-constants": "~13.2.4",
    "@expo/vector-icons": "^13.0.0",
    "react-native-paper": "4.9.2",
    "react-native-screens": "~3.15.0",
    "@react-navigation/stack": "*",
    "@react-navigation/native": "*",
    "react-native-gesture-handler": "~2.5.0",
    "react-native-safe-area-context": "4.3.1",
    "react-native-status-bar-height": "*"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}

**Comment by S-Osman4** [comment]
have you been able to resolve it...i am facing the same issue now

**Comment by Desmondonam** [comment]
I was not able to solve the issue, I decided to use snacks
