### ISSUE TITLE
'Webpack is not running' Issue on expo-cli

### ISSUE THREAD

**Issue by panda0603** [expo/expo-cli#460]
## Description

I get 'webpack is not running' message in red color in terminal when I run expo build  commands. There may be other commands which I have not yet found.

## Expected Behavior

Previous versions, as far I recall, did not show these messages. I started getting them after i updated to latest version. 

## Observed Behavior
No error though, just that red message warning. 

Also specify:

Using Expo-cli latest version at the moment.

## Reproducible Demo

When I run commands such as expo build:ios or expo build:android.
Or after the build is finished and I press ctrl + c, webpack is not running message appears.

**Comment by KEMBL** [comment]
I see the same error when performing the command "expo build:android". 
With EXPO_DEBUG=ture it shows:

Webpack is not running.
Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at C:\xdl@53.1.7\src\Project.js:1035:26
    at Generator.next (<anonymous>)
    at step (C:\Users\Lurker\AppData\Roaming\npm\node_modules\expo-cli\node_modules\xdl\build\Project.js:2371:191)
    at C:\Users\Lurker\AppData\Roaming\npm\node_modules\expo-cli\node_modules\xdl\build\Project.js:2371:361
    at <anonymous>

dependencies:
    "expo": "^32.0.0",
    "react": "16.5.0",
    "react-native": "0.57.1"

**Comment by cruzach** [comment]
Hey @panda0603,

I'm working on a fix for this now, figured out the reason it's showing that message when you press ctrl+c, but if I understand correctly- you're also getting the message in the middle of building? Or it's only when the process exits?

Thanks!
-Charlie

**Comment by panda0603** [comment]
@cruzach

both on build and crtl c as far as I can see.
Thanks for the fix

**Comment by vipin-developer** [comment]
The same thing is happening for me also, webpack is not running shows even if I don't press ctrl+c.

**Comment by cruzach** [comment]
Gotchya, filed a PR which should do away with this message output on ctrl+c

I'll see if the message output on `build` is due to the same code, if not I'll commit a fix for that as well.

Thanks for the info guys!

**Comment by proFaraz** [comment]
Restart Your router, that fixed the problem for me!

**Comment by cruzach** [comment]
@panda0603 and @vipin-developer ,

The fix in the PR should eliminate all instances of this message occurring when web isn't configured (found it occurs on commands: `start`, `publish` and `build`).

Thanks for the patience everyone!

**Comment by KEMBL** [comment]
Guys, I've changed "react-native": "0.57.1" in dependencies to     "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz", removed and installed node modules again. After that android build was successful.
