### ISSUE TITLE
Cannot run "npx expo start"

### ISSUE THREAD

**Issue by rjapenga** [expo/expo-cli#4604]
### Summary

When trying to start, it tells me that I must install  expo@47.0.6. When I do that, I get the following error.

 Not Found - GET https://skimdb.npmjs.com/registry/p-try/-/p-try-2.2.0.tgz - not_found

### Environment

PS C:\u\bob\home\react-native2\MealsToGo-master> npx expo-env-info
Need to install the following packages:
  expo-env-info@1.0.5
Ok to proceed? (y) y
npm ERR! code E404
npm ERR! 404 Not Found - GET https://skimdb.npmjs.com/registry/envinfo/-/envinfo-7.8.1.tgz - not_found
npm ERR! 404
npm ERR! 404  'envinfo@https://skimdb.npmjs.com/registry/envinfo/-/envinfo-7.8.1.tgz' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Local\npm-cache\_logs\2022-11-16T20_57_36_961Z-debug-0.log

### Please specify your device/emulator/simulator platform, model and version

Lenovo Laptop Windows 10 

### Error output

This doesn't make sense since I cannot install expo. But here is what I got:
 EXPO_DEBUG=true  npx expo start
EXPO_DEBUG=true : The term 'EXPO_DEBUG=true' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At line:1 char:1
+ EXPO_DEBUG=true  npx expo start
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (EXPO_DEBUG=true:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

### Reproducible demo or steps to reproduce from a blank project

My problem is so simple - I cannot get started so you already have the commands that fail.

**Comment by byCedric** [comment]
Hi @rjapenga! Thanks for the issue report, unfortunately we can't help you fix this.

1. You are using a non-default npm registry, `https://skimdb.npmjs.com/registry`.
    It seems that the package that it wants to download, does not exist in this registry. In the default registry, you can find it here `https://registry.npmjs.com/p-try/-/p-try-2.2.0.tgz`.

2. The `ObjectNotFound: (EXPO_DEBUG=true:String)` error is because you are trying to use syntax that is not supported on Windows. Try using [cross-env](https://www.npmjs.com/package/cross-env) to set environment variables like this on windows, e.g. `npx cross-env EXPO_DEBUG=true npx expo start`.

Hope this helps!
