### ISSUE TITLE
Expo-go is not downloading on ios-simulator on mac.(M1-Chip, Xcode-14, MacOS-Ventura-13)

### ISSUE THREAD

**Issue by fortdev210** [expo/expo-cli#4606]
### Summary

I have upgraded my mac os version into the latest one(Ventura 13) and downloaded xcode 14. My node js version is 16.14.2 and I have installed expo-cli. I have initiated a new project e.g. testApp with blank typescript project. After all installing, when I hit command on terminal in project, yarn ios, it triggers to download expo go but it doesn't go to 100%. Sometimes it stops at 95%.
<img width="658" alt="image" src="https://user-images.githubusercontent.com/70984534/203224755-7b43b84a-6325-4477-8c9f-6cfc616be0fa.png">

This happens every time and I tried every possible way but failed e.g downgrading expo cli and reinstalling xcode. Could anyone help me this? Here are the steps to reproduce.

```
1, npm install -g expo-cli
2, expo init testApp
3, cd testApp
4, yarn ios
```

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.2/bin/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
      Watchman: 2022.11.14.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 6.0.8

### Please specify your device/emulator/simulator platform, model and version

MacOS, XCode, IOS

### Reproducible demo or steps to reproduce from a blank project

```
1, npm install -g expo-cli
2, expo init testApp
3, cd testApp
4, yarn ios
```

**Comment by byCedric** [comment]
What happens if you run the install command separately? `expo-cli client:install:ios -d` (with `-d`, you can select the device you want to install).

If that doesn't work, try manually downloading Expo Go instead. We keep track of these simulator builds [here](https://exp.host/--/api/v2/versions), so for SDK 47 you can use: https://dpq5q02fu5f55.cloudfront.net/Exponent-2.26.4.tar.gz

**Comment by fortdev210** [comment]
Hi @byCedric
Thank you for your reply.
When I tried the command with -d, it says `unknown option`.
Btw how can i download Expo Go manually on ios simulator?
