### ISSUE TITLE
Expo CLI install has issues with nested dependency iltorb

### ISSUE THREAD

**Issue by byCedric** [expo/expo-cli#461]
## Description

During my tests to get GitHub Actions working for Expo, I noticed something lately when installing Expo CLI. It tries to install [`iltorb`](https://github.com/MayhemYDG/iltorb), a dependency of [`brotli-webpack-plugin`](https://github.com/mynameiswhm/brotli-webpack-plugin/blob/master/package.json#L16) from [`@expo/webpack-config`](https://github.com/expo/expo-cli/blob/master/packages/webpack-config/package.json#L17). 

Right now it's not failing, only erroring trying to "post-install" it's own `node ./scripts/install.js || node-gyp rebuild`.

I think this issue is related to #412 and #460. Guess it's also related to the [experimental web support](https://blog.expo.io/expo-cli-and-sdk-web-support-beta-d0c588221375) (I'm sorry Evan, it's still awesome! ❤️ ).

## Expected Behavior

When installing Expo CLI there are some peer dependencies and other warnings, but I don't expect any errors in there.

## Observed Behavior

<img width="841" alt="Screenshot 2019-03-23 at 17 35 02" src="https://user-images.githubusercontent.com/1203991/54868916-0242b180-4d92-11e9-8944-eebc5c0885a9.png">

## Environment

I ran this with `node:6`, `node:8`, `node:10` and `node:11` all causing the same output. It's also worth mentioning that I tried this with a custom non-root `node:10` image, but it's even worse there.

<img width="839" alt="Screenshot 2019-03-23 at 17 36 33" src="https://user-images.githubusercontent.com/1203991/54868937-3f0ea880-4d92-11e9-8914-b6baf260c5dc.png">

## Reproducible Demo

If you have docker, you can reproduce it by one of these commands:

- `docker run -ti --rm node:6 npm i -g expo-cli`
- `docker run -ti --rm node:8 npm i -g expo-cli`
- `docker run -ti --rm node:10 npm i -g expo-cli`
- `docker run -ti --rm node:11 npm i -g expo-cli`

**Comment by fson** [comment]
cc @EvanBacon

**Comment by EvanBacon** [comment]
We should just make brotli optional for now.
