### ISSUE TITLE
Image import X is not a valid image file

### ISSUE THREAD

**Issue by Razorshnegax018** [expo/expo-cli#4613]
### Summary

I should expect my expo-react-native + nextjs app to build after installing and adding the 'next/images' plugin just like the docs say, but at build time I am stopped by 7 occurrences of the same exact error: "Error: Image import "./assets/X.png" is not a valid image file. The image may be corrupted or an unsupported format." This error is found not only in my own code, but code from packages that I have installed (specifically react-navigation)

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
      Shell: 5.1.4 - /bin/bash
    Binaries:
      Node: 16.17.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.15.0 - /usr/local/bin/npm
      Watchman: 20220528.183901.0 - /usr/local/bin/watchman
    npmPackages:
      expo: ^47.0.0 => 47.0.8 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.10 
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

ChromeOS Version 102.0.5005.189 (Official Build) (64-bit) and CodeSandbox Projects: Latests browser version

### Error output

@react-navigation/elements:154
Error: Image import "./assets/back-icon-mask.png" is not a valid image file. The image may be corrupted or an unsupported format.

./AppbarBackIcon:66
Error: Image import "../../assets/back-chevron.png" is not a valid image file. The image may be corrupted or an unsupported format.

you get the idea

### Reproducible demo or steps to reproduce from a blank project

[Link to repl](https://replit.com/@razorshnegax/exponext-image-error). This repl is my dev environment with all my code removed. The repl should run automatically when it boots. If not, run the command `cd north-sea-native-next/north-sea/next && yarn next dev` and wait for the page to build and the error to appear

**Comment by EvanBacon** [comment]
The expo next.js adapter does not do any image handling, [ref](https://github.com/expo/expo-cli/blob/62ce1fd5619ff2ee8b26a536dd349184f56ed7a8/packages/next-adapter/src/index.ts#L6). Given that multiple images are hitting this issue in your project, I imagine this is a Next.js Webpack configuration issue and not a corrupt image in React Navigation.

My guess would be that you may need to point one of the image loaders in the Next.js Webpack config at the `@react-navigation/elements` node module.

**Comment by Razorshnegax018** [comment]
I found a fix for this error on [stackoverflow](https://stackoverflow.com/questions/73142566/images-not-showing-with-expo-react-native-and-next)

UPGRADED AND WORKING NEXTJS CONFIG: 

`// @generated: @expo/next-adapter@2.1.52
// Learn more: https://docs.expo.io/guides/using-nextjs/

const { withExpo } = require("@expo/next-adapter");
const withPlugins = require("next-compose-plugins");
const withImages = require("next-images");
const withFonts = require("next-fonts");
const withTM = require("next-transpile-modules")(["react-native-web"]);

const nextConfig = {
  images: {
    disableStaticImages: true,
  },
};

module.exports = withPlugins(
  [withTM, withExpo, withImages, withFonts],
  nextConfig
);
`
