### ISSUE TITLE
OTA updates, iOS vs Android

### ISSUE THREAD

**Issue by NextStepDev** [expo/expo-cli#463]
When running `exp build:ios` to perform an OTA update to my app, I noticed that my android app on the Google Play Store was updated with the changes that I was only looking to go out to my iOS app. I’m just looking for a quick explanation to this and how I can do specific OTA updates for iOS and Android.

**Comment by dsokal** [comment]
Hello @NextStepDev,

1. `exp` is deprecated, please install and use `expo-cli`
2. `expo build:ios` is not meant for OTA updates, use `expo publish` instead
3. If you wish to perform OTA updates separately for Android and iOS, learn about release channels - https://docs.expo.io/versions/v32.0.0/distribution/release-channels/

**Comment by AdamJNavarro** [comment]
As a follow-up, I answered your [forum post](https://forums.expo.io/t/ota-updates-ios-vs-android/20853/4) as well. In the future though, please refrain from creating github issues to ask questions such as these as we seek to limit github issues to bugs. The forums are best suited for questions.

Cheers,
Adam
