### ISSUE TITLE
@expo/webpack-config devServer.open doesn't work

### ISSUE THREAD

**Issue by Vadko** [expo/expo-cli#4640]
### Summary

https://webpack.js.org/configuration/dev-server/#devserveropen

is there any chance to get this functionality working to the webpack-config? 

is the withDevServer addon required? Docs around this doesnt have any examples, could you please provide more details?

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.11.0 - /opt/homebrew/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.19.2 - /opt/homebrew/bin/npm
      Watchman: 2022.10.24.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: 0.17.3 => 0.17.3 
      babel-preset-expo: 9.2.0 => 9.2.0 
      expo: 46.0.16 => 46.0.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.69.7 => 0.69.7 
      react-native-web: 0.18.10 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 3.4.1
      expo-cli: 6.1.0
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

expo web

### Reproducible demo or steps to reproduce from a blank project

add devServer.open with modified params - none of them are working when starting dev server

**Comment by EvanBacon** [comment]
Use `expo start --web` to open the dev server, this accounts for any number of additional settings and configuration options. Willing to accept a PR that merges the required dev server options with the user dev server options but I wouldn't recommend using this functionality for `open`.

**Comment by Vadko** [comment]
In our case this is must-have feature since when running with expo start --web with cypress - browser is opened with no need and no option to avoid that. I would be happy to contribute into adding possibility to add option for this, could you please point where should I start with that?

**Comment by EvanBacon** [comment]
It would seem like you'd need to spread the incoming config with this object to prevent clobbering any predefined values: https://github.com/expo/expo-cli/blob/6642a0a75595f1323fe26f0bbcfc5af7061b1d39/packages/webpack-config/src/addons/withDevServer.ts#L123

**Comment by Vadko** [comment]
thanks @EvanBacon. Will work on that!
