### ISSUE TITLE
New app created with create-expo-app produces "null object reference" error

### ISSUE THREAD

**Issue by FrancisVila** [expo/expo-cli#4642]
### Summary

I am following the instructions in as indicated in https://reactnative.dev/docs/environment-setup and end up with an error before changing anything. See "Reproducible demo or steps to reproduce from a blank project" below for exact steps followed.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 18.13.0 - C:\Program_files_plus\node_18_13\node.EXE
      Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.19.3 - C:\Program_files_plus\node_18_13\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 30, 31, 32
        Build Tools: 30.0.3, 31.0.0, 33.0.0
        System Images: android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64, android-33 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335
    npmPackages:
      expo: ~47.0.12 => 47.0.13
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Pixel_2_API_33 

### Error output

`Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference`

![native_error](https://user-images.githubusercontent.com/23334974/216075080-8bb695ba-1170-459d-ad0d-1b565c6a5101.jpg)

### Reproducible demo or steps to reproduce from a blank project

1. I launched the command `npx create-expo-app meteo-vintage`
2. I leave the project totally unchanged
3. `cd meteo-vintage` 
4. `npx expo start ` (as instructed by the dialog)
5. `a` (for open Android)
6. The emulator opens, after a while I see an error message:
`Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference`

![native_error](https://user-images.githubusercontent.com/23334974/216075080-8bb695ba-1170-459d-ad0d-1b565c6a5101.jpg)

**Comment by EvanBacon** [comment]
We cannot reproduce this error following the steps provided, please feel free to reopen with more information that can help us recreate the issue.
