### ISSUE TITLE
Proxy-related issues running expo doctor and expo upgrade commands

### ISSUE THREAD

**Issue by nick-attlee** [expo/expo-cli#4654]
### Summary

When using the `expo doctor` or `expo upgrade` commands using version **6.3.1** of the global Expo CLI package, the commands fail when running behind a proxy server.

This is a similar issue to the (now resolved) problem with the project-based Expo CLI.  https://github.com/expo/expo/issues/18718

### Environment

Running Expo CLI 6.3.1 using Node.js version 19.1.0

### Please specify your device/emulator/simulator platform, model and version

Windows 10 (OS build 19045.2486)

### Error output

Error output from running the `expo doctor` command.

```
WARNING: The legacy expo-cli does not support Node +17. Migrate to the versioned Expo CLI (npx expo).
Unable to reach Expo servers. Falling back to using the cached dependency map (bundledNativeModules.json) from the package "expo" installed in your project.
Warning: could not reach `expo.io`.
Warning: could not reach `expo.fyi`.
Warning: could not reach `expo.dev`.
Warning: could not reach `static.expo.dev`.
Warning: could not reach `exp.host`.

We couldn't reach some of our domains, this might cause issues on our website or services.
Please check your network configuration and try to access these domains in your browser.

Warning: Problem validating app.json: Unable to perform cache refresh for C:\Users\nattlee\AppData\Local\Expo\schema-47.0.0.json: Error: socket hang up.
🎉 Didn't find any issues with the project!
```

Error output from running the `expo upgrade` command.

```
WARNING: The legacy expo-cli does not support Node +17. Migrate to the versioned Expo CLI (npx expo).
Unable to perform cache refresh for C:\Users\nattlee\AppData\Local\Expo\versions.json: Error: socket hang up
Error: Unable to perform cache refresh for C:\Users\nattlee\AppData\Local\Expo\versions.json: Error: socket hang up
    at Cacher.getAsync (C:\npm\node_modules\expo-cli\node_modules\xdl\src\tools\FsCache.ts:107:15)
    at Object.versionsAsync (C:\npm\node_modules\expo-cli\node_modules\xdl\src\Versions.ts:60:10)
    at upgradeAsync (C:\npm\node_modules\expo-cli\src\commands\info\upgradeAsync.ts:390:3)
    at actionAsync (C:\npm\node_modules\expo-cli\src\commands\info\upgradeAsync.ts:42:3)
```

### Reproducible demo or steps to reproduce from a blank project

The error should be reproducible if you attempt one of the aforementioned commands when running behind a HTTP proxy.

**Comment by byCedric** [comment]
Hi @nick-attlee! The `expo-cli` has been deprecated for some time now, in favor of the [versioned CLI](https://blog.expo.dev/the-new-expo-cli-f4250d8e3421) you mentioned. That also means that you should use the fixed CLI, where you can define the `HTTP_PROXY` env var.

As a quick cheatsheet:

`expo-cli` | New CLI
--- | ---
`expo doctor` | `npx expo-doctor`
`expo upgrade <same-version>` | `npx expo install --fix`
`expo upgrade 50` | `npx expo install expo@50 && npx expo install --fix`

Hope this helps!
