### ISSUE TITLE
Project Page URL not working

### ISSUE THREAD

**Issue by vo120** [expo/expo-cli#4655]
### Summary

My project page url after running expo publish doesn't work if I am not signed it, meaning for public it doesn't work. It's already set to be cited as publish but still doesn't work. I have tried it with eas-cli where it adds the policy version and different channels to the eas.json & app.json. With that i couldn't even get it to work for me so i had to remove it and run expo publish then i was able to see it but my main issue is the expo publish link doesn't work for others and I need it to. Does anyone know how I can fix it please? 

### Managed or bare?

managed

### Environment

THIS IS WHAT I GET AFTER RUNNING ``` expo publish ```: 
Uploading JavaScript bundles
Publish complete

📝  Manifest: https://exp.host/@username/project-name Learn more.
⚙️   Project page: https://expo.dev/@username/project-name?serviceType=classic&distribution=expo-go Learn more.

### Reproducible demo or steps to reproduce from a blank project

N/A

**Comment by byCedric** [comment]
Hi @vo120! Unfortunately, the Expo classic updates system has been sunset. Meaning that `expo publish` will soon be shut down (mid Feb, 2024 - [see our blog](https://blog.expo.dev/sunsetting-expo-publish-and-classic-updates-6cb9cd295378)).

If this is still an issue [using EAS Updates](https://docs.expo.dev/eas-update/introduction/) (our new generation of updates), please open a new issue on [github.com/expo/eas-cli](https://github.com/expo/eas-cli).

Hope this helps!
