### ISSUE TITLE
Expo eject breaking in a fresh expo project

### ISSUE THREAD

**Issue by Nidilap** [expo/expo-cli#4667]
### Summary

I created a fresh project using the command "npx create-expo-app my-app". I ran it using "npm run android" and it works as intended.
However, I ran expo eject and, after ejecting, executing the command "npm run android" causes a "package R does not exist" and a "cannot find symbol" of BuildConfig error. The whole error with stacktrace I put in the error output.

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.18.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-221.6008.13.2211.9619390
    npmPackages:
      expo: ~48.0.4 => 48.0.4
      react: 18.2.0 => 18.2.0
      react-native: 0.71.3 => 0.71.3
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

Android Studio - Pixel 4 API 30 - Android 11.0 Google Play | x86

### Error output

npm run android --stacktrace

> expo-splash-screen-bug@1.0.0 android
> expo run:android

Resolved port: 8081, start dev server: true
  expo:start:platforms:android:adbServer C:\Users\mateu\AppData\Local\Android\Sdk/platform-tools/adb devices -l +0ms
  expo:start:platforms:android:adbServer C:\Users\mateu\AppData\Local\Android\Sdk/platform-tools/adb -s emulator-5554 emu avd name +45ms
  expo:start:platforms:android:adbServer C:\Users\mateu\AppData\Local\Android\Sdk/platform-tools/adb devices -l +69ms
  expo:start:platforms:android:adbServer C:\Users\mateu\AppData\Local\Android\Sdk/platform-tools/adb -s emulator-5554 emu avd name +51ms
  expo:android:resolveDevice Resolved default device (name: Pixel_4_API_30, pid: emulator-5554) +0ms
  expo:run:android Package name: com.nidilap.exposplashscreenbug +0ms
› Building app...
  expo:start:platforms:android:gradle   C:\Projetos\expo-splash-screen-bug\android\gradlew.bat app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 +0ms

C:\Projetos\expo-splash-screen-bug\android>if "Windows_NT" == "Windows_NT" setlocal

C:\Projetos\expo-splash-screen-bug\android>set DIRNAME=C:\Projetos\expo-splash-screen-bug\android\

C:\Projetos\expo-splash-screen-bug\android>if "C:\Projetos\expo-splash-screen-bug\android\" == "" set DIRNAME=.

C:\Projetos\expo-splash-screen-bug\android>set APP_BASE_NAME=gradlew

C:\Projetos\expo-splash-screen-bug\android>set APP_HOME=C:\Projetos\expo-splash-screen-bug\android\

C:\Projetos\expo-splash-screen-bug\android>for %i in ("C:\Projetos\expo-splash-screen-bug\android\") do set APP_HOME=%~fi

C:\Projetos\expo-splash-screen-bug\android>set APP_HOME=C:\Projetos\expo-splash-screen-bug\android\

C:\Projetos\expo-splash-screen-bug\android>set DEFAULT_JVM_OPTS="-Xmx64m" "-Xms64m"

C:\Projetos\expo-splash-screen-bug\android>if defined JAVA_HOME goto findJavaFromJavaHome

C:\Projetos\expo-splash-screen-bug\android>set JAVA_HOME=C:\Program Files\Java\jdk-11.0.15

C:\Projetos\expo-splash-screen-bug\android>set JAVA_EXE=C:\Program Files\Java\jdk-11.0.15/bin/java.exe

C:\Projetos\expo-splash-screen-bug\android>if exist "C:\Program Files\Java\jdk-11.0.15/bin/java.exe" goto execute

C:\Projetos\expo-splash-screen-bug\android>set CLASSPATH=C:\Projetos\expo-splash-screen-bug\android\\gradle\wrapper\gradle-wrapper.jar

C:\Projetos\expo-splash-screen-bug\android>"C:\Program Files\Java\jdk-11.0.15/bin/java.exe" "-Xmx64m" "-Xms64m"   "-Dorg.gradle.appname=gradlew" -classpath "C:\Projetos\expo-splash-screen-bug\android\\gradle\wrapper\gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain "app:assembleDebug" "-x" "lint" "-x" "test" "--configure-on-demand" "--build-cache" "-PreactNativeDevServerPort=8081"
Configuration on demand is an incubating feature.

> Configure project :expo-application
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-constants
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-file-system
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-font
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-keep-awake
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-modules-core
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-splash-screen
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo

Using expo modules
  - expo-application (5.1.1)
  - expo-constants (14.2.1)
  - expo-file-system (15.2.2)
  - expo-font (11.1.1)
  - expo-keep-awake (12.0.1)
  - expo-modules-core (1.2.3)
  - expo-splash-screen (0.18.1)

WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build.
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects: ':expo', ':expo-modules-core'

> Task :app:compileDebugJavaWithJavac FAILED
C:\Projetos\expo-splash-screen-bug\android\app\src\main\java\com\nidilap\exposplashscreenbug\MainActivity.java:19: error: package R does not exist
    setTheme(R.style.AppTheme);
              ^
C:\Projetos\expo-splash-screen-bug\android\app\src\main\java\com\nidilap\exposplashscreenbug\MainActivity.java:39: error: cannot find symbol
    return new ReactActivityDelegateWrapper(this, BuildConfig.IS_NEW_ARCHITECTURE_ENABLED, new DefaultReactActivityDelegate(
                                                  ^
  symbol:   variable BuildConfig
  location: class MainActivity
C:\Projetos\expo-splash-screen-bug\android\app\src\main\java\com\nidilap\exposplashscreenbug\MainApplication.java:26: error: cannot find symbol
        return BuildConfig.DEBUG;
               ^
  symbol: variable BuildConfig
C:\Projetos\expo-splash-screen-bug\android\app\src\main\java\com\nidilap\exposplashscreenbug\MainApplication.java:45: error: cannot find symbol
        return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
               ^
  symbol: variable BuildConfig
C:\Projetos\expo-splash-screen-bug\android\app\src\main\java\com\nidilap\exposplashscreenbug\MainApplication.java:50: error: cannot find symbol
        return BuildConfig.IS_HERMES_ENABLED;
               ^
  symbol: variable BuildConfig
C:\Projetos\expo-splash-screen-bug\android\app\src\main\java\com\nidilap\exposplashscreenbug\MainApplication.java:63: error: cannot find symbol
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
        ^
  symbol:   variable BuildConfig
  location: class MainApplication
C:\Projetos\expo-splash-screen-bug\android\app\src\main\java\com\nidilap\exposplashscreenbug\MainApplication.java:63: error: illegal parenthesized expression
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
       ^
7 errors

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
124 actionable tasks: 3 executed, 121 up-to-date

C:\Projetos\expo-splash-screen-bug\android>if 1 EQU 0 goto mainEnd

C:\Projetos\expo-splash-screen-bug\android>rem Set variable GRADLE_EXIT_CONSOLE if you need the _script_ return code instead of

C:\Projetos\expo-splash-screen-bug\android>rem the _cmd.exe /c_ return code!

C:\Projetos\expo-splash-screen-bug\android>set EXIT_CODE=1

C:\Projetos\expo-splash-screen-bug\android>if 1 EQU 0 set EXIT_CODE=1

C:\Projetos\expo-splash-screen-bug\android>if not "" == "" exit 1

C:\Projetos\expo-splash-screen-bug\android>exit /b 1
Error: C:\Projetos\expo-splash-screen-bug\android\gradlew.bat exited with non-zero code: 1
Error: C:\Projetos\expo-splash-screen-bug\android\gradlew.bat exited with non-zero code: 1
    at ChildProcess.completionListener (C:\Projetos\expo-splash-screen-bug\node_modules\@expo\spawn-async\build\spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:642:26)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess.cp.emit (C:\Projetos\expo-splash-screen-bug\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
    ...
    at Object.spawnAsync [as default] (C:\Projetos\expo-splash-screen-bug\node_modules\@expo\spawn-async\build\spawnAsync.js:17:21)
    at spawnGradleAsync (C:\Projetos\expo-splash-screen-bug\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:72:46)
    at Object.assembleAsync (C:\Projetos\expo-splash-screen-bug\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:52:18)
    at runAndroidAsync (C:\Projetos\expo-splash-screen-bug\node_modules\@expo\cli\build\src\run\android\runAndroidAsync.js:31:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### Reproducible demo or steps to reproduce from a blank project

I could not provide a Snack since there's no SDK 48.0 available there.
However, since this is a error that happens with a fresh instalation of expo, it is very easy to replicate.

1. npx create-expo-app expo-testing
2. npm run android 
3.  expo eject
4. npm run android 

The error should happen at the fourth step.

**Comment by Nidilap** [comment]
I have managed to correct this problem.

Basically, while ejecting, the name of the package got mixed and it was giving error.

The package that was supposed to be com.exposplashscreenbug, for example, became com.nidilap.exposplashscreenbug.

I changed all references to it (including a reference inside build.gradle that was just com.nidilap, changing it to com.exposplashscreenbug) and the project worked.

**Comment by Anasmohana84** [comment]
same here I'm struggling to run one old application after the upgrade, then thought to create a new one from scratch and move the code but get the same bug Task :app:compileDebugJavaWithJavac FAILED
C:\js\my-app\android\app\src\main\java\com\myapp\MainActivity.java:19: error: package R does not exist
    setTheme(R.style.AppTheme);

**Comment by Anasmohana84** [comment]
same here try to add some basic expo packages then get this error 

```
Using expo modules
  - expo-app-auth (11.1.1)
  - expo-application (5.1.1)
  - expo-constants (14.2.1)
  - expo-eas-client (0.5.1)
  - expo-file-system (15.2.2)
  - expo-font (11.1.1)
  - expo-google-sign-in (11.0.0)
  - expo-haptics (12.2.1)
  - expo-image-loader (4.1.1)
  - expo-image-picker (14.1.1)
  - expo-in-app-purchases (14.1.1)
  - expo-json-utils (0.5.1)
  - expo-keep-awake (12.0.1)
  - expo-linear-gradient (12.1.1)
  - expo-localization (14.1.1)
  - expo-manifests (0.5.2)
  - expo-modules-core (0.9.0)
  - expo-notifications (0.18.1)
  - expo-splash-screen (0.18.1)
  - expo-structured-headers (3.1.1)
  - expo-updates (0.16.3)
  - 
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':expo-app-auth' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.21

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```
the same thing if try to use aes build:android

**Comment by gregogalante** [comment]
Same error here!

I create a new expo project and try to run on android device:
```bash
npx create-expo-app my-app
cd my-app
yarn install
expo run:android
```

Get this error:

```bash
> Task :app:compileDebugJavaWithJavac FAILED
/Users/gregoriogalante/Desktop/my-app/android/app/src/main/java/com/gregoriogalante/my-app/MainApplication.java:27: error: cannot find symbol
        return BuildConfig.DEBUG;
               ^
  symbol: variable BuildConfig
/Users/gregoriogalante/Desktop/my-app/android/app/src/main/java/com/gregoriogalante/my-app/MainApplication.java:46: error: cannot find symbol
        return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
               ^
  symbol: variable BuildConfig
/Users/gregoriogalante/Desktop/my-app/android/app/src/main/java/com/gregoriogalante/my-app/MainApplication.java:51: error: cannot find symbol
        return BuildConfig.IS_HERMES_ENABLED;
               ^
  symbol: variable BuildConfig
/Users/gregoriogalante/Desktop/my-app/android/app/src/main/java/com/gregoriogalante/my-app/MainApplication.java:64: error: cannot find symbol
    if (!BuildConfig.REACT_NATIVE_UNSTABLE_USE_RUNTIME_SCHEDULER_ALWAYS) {
         ^
  symbol:   variable BuildConfig
  location: class MainApplication
/Users/gregoriogalante/Desktop/my-app/android/app/src/main/java/com/gregoriogalante/my-app/MainApplication.java:67: error: cannot find symbol
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
        ^
  symbol:   variable BuildConfig
  location: class MainApplication
/Users/gregoriogalante/Desktop/my-app/android/app/src/main/java/com/gregoriogalante/my-app/MainApplication.java:67: error: illegal parenthesized expression
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
       ^
/Users/gregoriogalante/Desktop/my-app/android/app/src/main/java/com/gregoriogalante/my-app/MainActivity.java:19: error: package R does not exist
    setTheme(R.style.AppTheme);
              ^
/Users/gregoriogalante/Desktop/my-app/android/app/src/main/java/com/gregoriogalante/my-app/MainActivity.java:39: error: cannot find symbol
    return new ReactActivityDelegateWrapper(this, BuildConfig.IS_NEW_ARCHITECTURE_ENABLED, new DefaultReactActivityDelegate(
                                                  ^
  symbol:   variable BuildConfig
  location: class MainActivity
8 errors
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

FAILURE: Build failed with an exception.
```

**Comment by maloni991** [comment]
any fix on this issue ?

**Comment by BrettThurs10** [comment]
Having the same issue.

**Comment by byCedric** [comment]
Hi all! The `expo-cli` has been deprecated for quite a while, in favor of the [versioned CLI](https://blog.expo.dev/the-new-expo-cli-f4250d8e3421). You might notice that this CLI does not have `expo eject`, as that has been replaced by [expo prebuild](https://docs.expo.dev/workflow/prebuild/).

If you want to generate the native `/android` and/or `/ios` folders, you can use:
- `$ npx expo prebuild --platform android|ios`

Closing this issue as it's using deprecated tooling.
