### ISSUE TITLE
@expo/vector-icons not showing after adding metro.config.js file in project root folder

### ISSUE THREAD

**Issue by francolivelli** [expo/expo-cli#4669]
### Summary

Expo vector icons are not rendering after deployment.
I am using `@expo/metro-config` and this is my metro.config.js file:

```
const { getDefaultConfig } = require("@expo/metro-config");

const defaultConfig = getDefaultConfig(__dirname);

module.exports = {
  resolver: {
    assetExts: [...defaultConfig.resolver.assetExts, "db"],
  },
};
```

Expected behaviour:
![image](https://user-images.githubusercontent.com/109685663/223214187-611456c2-5775-49e6-ab6f-7114b453c472.png)

What actually happens
![image](https://user-images.githubusercontent.com/109685663/223214030-fd88c8d2-1640-4878-8feb-dfbbc6415bc4.png)

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.19 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 16.17.0 - /usr/local/bin/node
      npm: 8.15.0 - /usr/local/bin/npm
    npmPackages:
      expo: ^48.0.4 => 48.0.5 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
      react-native-web: ~0.18.7 => 0.18.12 
    npmGlobalPackages:
      expo-cli: 6.3.2
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Linux 5.19 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)

### Reproducible demo or steps to reproduce from a blank project

https://github.com/francolivelli/expo-error

**Comment by byCedric** [comment]
Hi @francolivelli! It seems that you are not extending the default Expo `metro.config.js`, instead you are overwriting the full config with just `resolver.assetExt`. See [our docs](https://docs.expo.dev/guides/customizing-metro/#assets) for a proper `metro.config.js` example that only adds the extension instead of overwriting the full config.

Hope this helps!
