### ISSUE TITLE
expo build:android occurs error unable to verify the first certificate

### ISSUE THREAD

**Issue by muhammad-ihsan** [expo/expo-cli#467]
## Description
Error occurs about certificate when i run `expo build:android`

## Observed Behavior

And returning this errors:

```
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:631:8)
```

## Environment

```
  Expo CLI 2.13.0 environment info:
    System:
      OS: Windows 7
    Binaries:
      Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338
```

**Comment by cruzach** [comment]
Hey @muhammad-ihsan ,

Can you provide a method for us to reproduce this issue?

Thanks!
Charlie

**Comment by AdamJNavarro** [comment]
Hey @muhammad-ihsan,

Can you confirm you have node installed and also maybe try uninstalling and re-installing `expo-cli`. I'm somewhat concerned that neither of them were picked up by `expo diagnostics`.

Cheers,
Adam

**Comment by muhammad-ihsan** [comment]
> 
> 
> Hey @muhammad-ihsan ,
> 
> Can you provide a method for us to reproduce this issue?
> 
> Thanks!
> Charlie

Hi @cruzach ,

Its happends when i want to build my application with command `expo build:android` . But the `expo start` command is working fine.

**Comment by muhammad-ihsan** [comment]
> 
> 
> Hey @muhammad-ihsan,
> 
> Can you confirm you have node installed and also maybe try uninstalling and re-installing `expo-cli`. I'm somewhat concerned that neither of them were picked up by `expo diagnostics`.
> 
> Cheers,
> Adam

Hi @AdamJNavarro ,

Node Version: 10.12.0
Npm Vesion: 6.4.1

I already reinstalling the `expo-cli` but no luck

**Comment by muhammad-ihsan** [comment]
this is `expo` issue or `expo-cli` issue >:o

**Comment by cruzach** [comment]
@muhammad-ihsan,

Are you able to run `expo publish` without any problems?

**Comment by muhammad-ihsan** [comment]
unable to verify the first certificate
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:631:8)

**Comment by abduraufsherkulov** [comment]
It is still an issue. Did you find a solution?

**Comment by brentvatne** [comment]
via https://forums.nexusmods.com/index.php?/topic/7714173-error-unable-to-verify-the-first-certificate/#ipboard_body

```
"unable to verify the first certificate" indicates a windows setup error.
What it's telling you is that the "chain of trust" that validates the api (or github) is actually the server they claim they are is compromised.
 
The chain of trust is a series of certificates that vouch for each other and then windows contains a list of certificate authorities they say are trustworthy.
So you have trusted CAs vouching for intermediate certificates vouching for the certificate used to sign connections to the server.
 
And I can assure you: all servers Vortex connects to (our own api and github) have proper certificates that your system should be able to validate.
 
So there are a few things that could be happening here:
a) Your windows hasn't been updated in years and doesn't contain current CAs (I don't actually know how old it would have to be)
b) You have broken security software (AV, firewall, proxies or similar) that redirect the network connection without proper certification or they change the certification itself
c) You have manually modified the CA list
d) You have malware that redirects network connections Vortex tries to establish
e) You have malware that changed/removed certificate authorities
```

**Comment by Devilshree123** [comment]
Have you solved the issue I am facing the same problem
