### ISSUE TITLE
Always get a warn message (creating an app and installing a dependence)

### ISSUE THREAD

**Issue by gustavocoimbradev** [expo/expo-cli#4671]
### Summary

I don't know what happened... But I'm always getting messages of warn saying there is 5 high severity vulnerabilities. I have the "create-expo-app" version 1.3.2 installed... 

What should I do?

I already uninstalled the node and deleted the folder 'npm', then reinstalled everything, but I'm still getting this error..

The problem is when I'm installing a dependence, I need to run "npm run audit fix --force" every time, and my code breaks suddenly.

![image](https://user-images.githubusercontent.com/115879524/225778345-d0f8e517-12f1-43c4-96f0-f1adff3df1b0.png)

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD

### Please specify your device/emulator/simulator platform, model and version

Windows 11 PRO

### Error output

npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0

added 1239 packages, and audited 1240 packages in 1m

61 packages are looking for funding
  run `npm fund` for details

5 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

### Reproducible demo or steps to reproduce from a blank project

npx create-expo-app my-app

**Comment by Sk-oo7** [comment]
I am also getting the same thing, @gustavocoimbradev got any solution?

**Comment by gustavocoimbradev** [comment]
Not yet. I already cleaned up my PC and installed the Windows again and nothing was solved. This is very weird.

**Comment by gustavocoimbradev** [comment]
> I am also getting the same thing, @gustavocoimbradev got any solution?


Not yet. I already cleaned up my PC and installed the Windows again and nothing was solved. This is very weird.

**Comment by gustavocoimbradev** [comment]
Update: Just used the Yarn and got the same errors messages...

**Comment by gustavocoimbradev** [comment]
Update: Probably the problem is the Expo CLI. I just update the Expo CLI in another computer and the same problem started to ocurr

**Comment by gustavocoimbradev** [comment]
Update: Mysteriously the problem was solved

**Comment by gustavocoimbradev** [comment]
> I am also getting the same thing, @gustavocoimbradev got any solution?

Check if yours is still having problems. If it still is, run the following command:

npm install -g create-expo-app

**Comment by JovanJevtic** [comment]
I have the same problem, I already ran npm install -g create-expo-app and it still occuress

**Comment by gustavocoimbradev** [comment]
> I have the same problem, I already ran npm install -g create-expo-app and it still occuress

Very weird.. the problem was solved here. I don't know what was happening.

**Comment by gustavoalvim41** [comment]
no solution yet?

**Comment by marklawlor** [comment]
Hey everyone,

I'm going to close this issue has its not a problem with Expo Router, rather its just how npm works. `create-react-app` has a great pinned issue about this exact subject https://github.com/facebook/create-react-app/issues/11174 and I would recommend reading it to get more context.
