### ISSUE TITLE
[expo build] Request failed with status code 502

### ISSUE THREAD

**Issue by carabedo** [expo/expo-cli#4683]
### Summary

Hi! Im trying to build my first project, i just need an apk to upload to my android phone. 

Reading the docs there is two options: eas-cli build (I cant login, im am behind a corporate proxy, also i dont understand the need to build it online), expo-cli build also fails with 502 error. I suspect has something to do with the proxy, i just need to build my app, is there other way to build it complete offline?

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.18 Archcraft
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.0 - /usr/local/bin/node
      Yarn: 3.5.0 - /usr/bin/yarn
      npm: 8.19.4 - /usr/local/bin/npm
    npmPackages:
      @expo/webpack-config: ^0.17.4 => 0.17.4 
      expo: ^48.0.10 => 48.0.10 
      react: ^17.0.2 => 17.0.2 
      react-native: 0.71.6 => 0.71.6 
      react-native-web: ~0.18.10 => 0.18.12 
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

arch linux 

### Error output

Warning: Problem validating app.json: Unable to perform cache refresh for /home/fernando/.cache/expo/schema-48.0.0.json Request failed with status code 502
Error: Request failed with status code 502
    at createError (/usr/lib/node_modules/expo-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/lib/node_modules/expo-cli/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

### Reproducible demo or steps to reproduce from a blank project

expo build:android -t apk

**Comment by byCedric** [comment]
Hi @carabedo! The `expo-cli` has been deprecated in favor of the [versioned CLI](https://blog.expo.dev/the-new-expo-cli-f4250d8e3421). When running `expo build` with an old `expo-cli` version, you are trying to use the [sunset classic build service](https://blog.expo.dev/classic-build-service-no-longer-supported-73c82b500f56).

If you want to build your app locally, you can either use `eas build --local` or `expo run:android`. If you still run into auth issues in the `eas-cli`, please open a new issue on [github.com/expo/eas-cli](https://github.com/expo/eas-cli).

Hope this helps!
