### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by grodriguesCP** [expo/expo-cli#4688]
### Summary

Packages @expo/webpack-config is causing dependency error because use old version of @expo/config-plugins (6.0.20).
The actual version is 8.0.2.

Expected package @expo/config-plugins@~6.0.0
Found invalid:
  @expo/config-plugins@4.1.1

npm why @expo/config-plugins: 
@expo/config-plugins@4.1.1
node_modules/@expo/webpack-config/node_modules/@expo/config-plugins
  @expo/config-plugins@"4.1.1" from @expo/config@6.0.20
  node_modules/@expo/webpack-config/node_modules/@expo/config
    @expo/config@"6.0.20" from @expo/webpack-config@18.0.4
    node_modules/@expo/webpack-config
      @expo/webpack-config@"^18.0.4" from the root project

### Environment

npx expo-cli doctor and when create a new build using eas build

### Please specify your device/emulator/simulator platform, model and version

Ubuntu 20 with expo SDK 48

### Error output

Expected package @expo/config-plugins@~6.0.0
Found invalid:
  @expo/config-plugins@4.1.1

### Reproducible demo or steps to reproduce from a blank project

npx expo-cli doctor

**Comment by byCedric** [comment]
Hi @grodriguesCP! This has been resolved in PR #4703, closing this PR.
