### ISSUE TITLE
Expo prebuild tries to install dependencies even though --no-install flag was provided

### ISSUE THREAD

**Issue by marcus-sa** [expo/expo-cli#4697]
### Summary

`expo prebuild --no-install` tries to install dependencies even though the `--no-install` flag was provided. Dependencies were installed at a previous step.
![Screenshot 2023-04-25 at 09 40 57](https://user-images.githubusercontent.com/8391194/234208347-cdba01b2-6b3d-419b-9b55-09269935aa7c.png)

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.volta/tools/image/node/18.15.0/bin/node
      Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
      npm: 9.5.0 - ~/.volta/tools/image/node/18.15.0/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

ios & android, expo build service, exposdk:47.0.0

### Reproducible demo or steps to reproduce from a blank project

https://nx.dev mono repository with an Expo app.

**Comment by wkozyra95** [comment]
prebuild does not run yarn install, EAS Build worker runs prebuild with --no-install option and then runs yarn install explicitly to make sure that we use the same package manager for both installs. Prebuild adds or modifies some packages, so second install is necessary

**Comment by marcus-sa** [comment]
@wkozyra95 prebuild doesn't run a second install locally, so I'm unsure why you've closed the issue.

**Comment by wkozyra95** [comment]
no install flag works correctly, the second install from your screenshot is not a part of a prebuild. EAS Build runs that install after prebuild is finished.

**Comment by marcus-sa** [comment]
@wkozyra95 so the issue is with EAS Build?

**Comment by wkozyra95** [comment]
> It shouldn't be running install.

I already explained above why it needs to run a second install. If we provided a way to skip installation, some dependencies might be missing, and the build process would fail later on.

> It's a waste of time and money.

If no packages are missing, the second install will only take a few seconds.
