### ISSUE TITLE
error Command "next-expo" not found.

### ISSUE THREAD

**Issue by givik** [expo/expo-cli#4704]
### Summary

next-expo command not working ```yarn next-expo``` or I am doing something wrong?

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.16.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.6.6 - /usr/local/bin/npm
      Watchman: 2023.05.01.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.7 => 48.0.16 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.10.2
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

MacOS, Using Terminal

### Error output

```error Command "next-expo" not found.```

### Reproducible demo or steps to reproduce from a blank project

See my codesandbox example here:

https://codesandbox.io/p/sandbox/laughing-worker-r27bxj?file=%2F.codesandbox%2Fworkspace.json%3A10%2C7

you can run ```yarn next-expo``` or ```yarn next-expo --help```. Non of them are working. Thanks!

**Comment by pavelbabenko** [comment]
Same issue

**Comment by byCedric** [comment]
Hi all! `next-expo` is not an existing command we provide. If you want to setup a NextJS project with expo, either use `@expo/next-adapter`, or the `react-native-web` babel plugin (examples: [next.config.js](https://github.com/byCedric/expo-monorepo-example/blob/8229117fd826dd51562f17725a8084b9bf450b99/apps/web/next.config.js), [babel.config.js](https://github.com/byCedric/expo-monorepo-example/blob/8229117fd826dd51562f17725a8084b9bf450b99/apps/web/babel.config.js))

Hope this helps!
