### ISSUE TITLE
webpack-config is dependent on @expo/config:6 which is depending on outdated @expo/config-plugins:4

### ISSUE THREAD

**Issue by hunwalk** [expo/expo-cli#4711]
### Summary

The following issue can be checked by `npx expo-doctor`

1. Create an expo project
2. Add latest webpack-config as a dependency
3. Run `npx expo-doctor`

If everything went right all the new packages should be expecting @expo/config-plugins:6 except for webpack wich is expecting @expo/config:6 => @expo/config-plugins:4.1.1

├─┬ @expo/webpack-config@18.0.4
│ └─┬ @expo/config@6.0.20
│   └── @expo/config-plugins@4.1.1

### Environment

expo-env-info 1.0.5 environment info:
  System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.20.0 - /usr/bin/node
    npm: 8.19.4 - /usr/bin/npm
  npmPackages:
    @expo/webpack-config: ^18.0.4 => 18.0.4 
    expo: ^48.0.17 => 48.0.17 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8 
    react-native-web: ~0.18.7 => 0.18.12 
  npmGlobalPackages:
    eas-cli: 3.13.2
  Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

GPU Emulated Pixel 3 / Android Virtual Device

### Error output

gergely@shoebox:~/test$ npx expo-doctor
✔ Validating global prerequisites versions passed
✔ Checking for incompatible packages passed
✔ Checking for conflicting global packages in project passed
✖ Verifying prebuild support package versions are compatible failed
Issues:
  Expected package @expo/config-plugins@~6.0.0
  Found invalid:
    @expo/config-plugins@4.1.1
    (for more info, run: npm why @expo/config-plugins)
Advice:
  • Upgrade dependencies that are using the invalid package versions.
✔ Checking dependency versions for compatibility with the installed Expo SDK passed
✔ Validating Expo Config passed
✔ Checking package.json for common issues passed

### Reproducible demo or steps to reproduce from a blank project

1. Create an expo project
2. Add latest webpack-config as a dependency
3. Run `npx expo-doctor`

**Comment by byCedric** [comment]
Hi @hunwalk! Sorry for the delayed response. We are cleaning up this repository and resolving the last outstanding issues and PRs.

This has been resolved in PR #4703, closing this PR and issue #4712.
