### ISSUE TITLE
"Error: NPM package not found: exp-template-blank-typescript@latest" when using Typescript template

### ISSUE THREAD

**Issue by Naren219** [expo/expo-cli#4713]
### Summary

When using the typescript template to create a new expo app, I'm running into an error where the NPM package for that template is not found even though I don't need to install anything for the basic typescript template. 
### Environment

System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 19.7.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - ~/.npm-global/bin/yarn
      npm: 9.6.7 - ~/.npm-global/bin/npm
      Watchman: 2023.03.13.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9477386
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 6.3.7
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

N/A

### Error output

✖ Something went wrong in downloading and extracting the project files: NPM package not found: exp-template-blank-typescript@latest
Error: NPM package not found: exp-template-blank-typescript@latest

### Reproducible demo or steps to reproduce from a blank project

This is the initial step in creating an Expo app, so just have the dependencies (such as Node and Expo-cli) installed and run this command: 

`npx create-expo-app myApp -t exp-template-blank-typescript`

**Comment by byCedric** [comment]
Hi @Naren219! It's indeed correct that `exp-template-blank-typescript` will throw a not-found error. We published it under `expo-template-blank-typescript`, or just `npx create-expo-app myApp -t blank`.

Hope this helps!
