### ISSUE TITLE
Getting an unexpected token when I try to install expo-cli or npx expo-cli -h 

### ISSUE THREAD

**Issue by HerRA17** [expo/expo-cli#4714]
### Summary

I am new to expo and I am following steps from the course guide:
I want to know if it could be an issue regarding Windows and npm or npm & expo-cli. 
I am using Powershell, node in Windows.

### Environment

I started by:
nvm install 16.19.0
nvm use 16.19.0
Afterwards I tried with the following errors:
npm i -g expo-cli or even npx expo-cli -h as mentioned in the Docs.

### Please specify your device/emulator/simulator platform, model and version

Powershell, windows 11

### Error output

npm ERR! Unexpected token '.'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\(my-user)\AppData\Local\npm-cache\_logs\2023-05-30T19_25_17_859Z-debug-0.log

### Reproducible demo or steps to reproduce from a blank project

I am not really sure what I could provide extra to emulate the issue.

**Comment by byCedric** [comment]
Hi @HerRA17! Unfortunately, the `expo-cli` has been deprecated for some time now. We've migrated towards the CLI shipped within `expo` ([versioned CLI](https://blog.expo.dev/the-new-expo-cli-f4250d8e3421)).

You should be able to create a new project through `npm|yarn create expo ./my-app`, without the deprecated `expo-cli` 😄 Then, starting would be `npm|yarn start` or `npm|yarn expo start`.

Hope this helps!
