### ISSUE TITLE
Still not able to get CLI to work....

### ISSUE THREAD

**Issue by jdcrunchman** [expo/expo-cli#4725]
### Summary

WARNING: expo-cli has not yet been tested against Node.js v18.15.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

When I run npm install -g expo-cli as per instructions,  I'm sad to report that this expo-cli is 4.7.3.   It is NOT the latest.   I've not gotten
ANY version to work.

### Environment

Need to install the following packages:
  expo-env-info@1.0.5
Ok to proceed? (y) y

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/miniforge3/envs/react/bin/node
      Yarn: 1.22.19 - ~/miniforge3/envs/react/bin/yarn
      npm: 9.5.0 - ~/miniforge3/envs/react/bin/npm
      Watchman: 2023.06.26.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

My device is iPhone 13.  ios 16.5.1,   VSCode editor

### Error output

I don't understand "Your command here",   were you referring to "npx expo start". I'm not sure this is what you are looking for.

### Reproducible demo or steps to reproduce from a blank project

I installed expo-cli as follows:   npm install --global expo-cli@6.3.9
(react) johndraper@Johns-MacBook-Pro native-project % npx expo start
WARNING: The legacy expo-cli does not support Node +17. Migrate to the new local Expo CLI: https://blog.expo.dev/the-new-expo-cli-f4250d8e3421.
┌───────────────────────────────────────────────────────────────────────────┐
│                                                                           │
│   This version of expo-cli is not supported anymore.            

Unable to find expo in this project - have you run yarn / npm install yet?
SEE ABOVE!!,   YES I DID..          │
│   It's highly recommended to update to the newest version.   

I did....     \

**Comment by zethzeth** [comment]
@jdcrunchman 

I'm having the same error. 

I tried just removing the line: `"@expo/webpack-config": "^18.0.1",` from my `package.json`-file:
 - It works when running in the iOS simulator
 - I can compile and see my app in Expo Go.
 - I _cannot_ open the app on my iOS-phone (after `eas build` and `eas submit`). I'm guessing due to me recently updated to version SDK49-related. 

I can read here: <https://blog.expo.dev/expo-sdk-49-c6d398cdf740> that it's recommended to use [Metro](https://docs.expo.dev/guides/customizing-metro/) instead: 

It says: 

> Metro is now recommended for web. The @expo/webpack-config package is currently in maintenance mode, and our efforts on web support are focused on [Metro](https://docs.expo.dev/guides/customizing-metro/). We strongly recommend all new projects use Metro for web. Many existing projects should work well with Metro as long as they don’t require any of [the few remaining features only supported by Webpack](https://docs.expo.dev/guides/customizing-metro/#expo-webpack-vs-expo-metro). Refer to the “Known Regressions” section below for more information on issues you may encounter using Webpack with SDK 49.

**Comment by erictslee** [comment]
asdfasdf

**Comment by byCedric** [comment]
Hi @jdcrunchman! I'm not sure where we document that you have to install the `expo-cli`, this CLI has been deprecated for some time now. If it's documented on [docs.expo.dev](https://docs.expo.dev), please open a new issue on [github.com/expo/expo](https://github.com/expo/expo) with the links to those pages.

You don't need the `expo-cli` anymore, we've migrated to the CLI included within the `expo` package itself: https://blog.expo.dev/the-new-expo-cli-f4250d8e3421

Hope this helps!
