### ISSUE TITLE
Error: expo tool

### ISSUE THREAD

**Issue by sanchit11** [expo/expo-cli#473]
when i type expo start in command line the browser opens but gives an error like
Expo Developer Tools is disconnected from Expo CLI. Use the expo start command to start the CLI again.

**Comment by cruzach** [comment]
Hi @sanchit11 ,

Could you share your environment info with us? Just run `expo diagnostics` and paste the output.

Off the bat, I'd recommend re-installing expo-cli

Thanks!
Charlie

**Comment by fson** [comment]
I’m closing this pull request for now because of inactivity.

However, if you're still having this problem, please open a new issue with updated information (see the issue template for information to provide), thanks!
