### ISSUE TITLE
Fetching the user profile failed when scanning qr code or publishing

### ISSUE THREAD

**Issue by rendword** [expo/expo-cli#474]
Hi , I've started using Expo and installed the latest versions of node.js , git , jdk , expo and also expo on my mobile phone.
Everything is alright when running `expo start` but when I try to scan the Qr-code on my phone tells me "something went wrong could not load exp://myip:1900.network response timed out."
and also in browser Expo these messages
Fetching the user profile failed
connect ETIMEDOUT 35.202.142.166:443
Same Issue when trying to publish the app
I have my Firewall off
Logged in from expo android app
and in metro bundler shows logged in 
I also tried logging in from npm and same message
I have changed my network priority and any suggested ways
My pc is connected with ethernet cable and my phone on the wifi of same router,can this be the problem?

**Comment by rendword** [comment]
One thing to say is that Expo is not opening in my country , so I'm using it with a proxy 
and when I click view error log This appears:
Uncaught Error : java.io.IOException:Unexpected end of stream on connection {192.168.1.4:19000,proxy=DIRECT hostAddress=/192.168.1.4:19000 cipherSuite=none protocol=http/1.1

**Comment by cruzach** [comment]
Hey @rendword,

Are you able to open other published projects by scanning the QR code? Can try on any of [these](https://expo.io/featured)

Also, we have a guide for [Troubleshooting Proxies](https://docs.expo.io/versions/latest/introduction/troubleshooting-proxies/)

-Charlie

**Comment by Amateur92** [comment]
if you have a problem running your app on your phone using expo client just do the following:

1. make sure your phone and your laptop are on the same wireless network (create a hotspot on either phone or laptop and connect them to the same network).

2. make sure port 19000 is opened in your firewall inbound rules.
3. use an expo SDK version <= 31. Modify app.json, and pacakge.json as follows:
in app.json ---> set sdkVersion = 31.0.0
in package.json --------> set expo = 31.0.0
