### ISSUE TITLE
"Development team for signing the app" not updating

### ISSUE THREAD

**Issue by chen-rn** [expo/expo-cli#4757]
### Summary

We created a new appstore account and linked it to our Expo account. EAS build works, but local builds to device do not work as we can't seem to find the right development team when prompted "Development team for signing the app".

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.0 - ~/.volta/tools/image/node/18.17.0/bin/node
      Yarn: 4.0.0-rc.48 - ~/.volta/tools/image/yarn/4.0.0-rc.48/bin/yarn
      npm: 9.6.7 - ~/.volta/tools/image/node/18.17.0/bin/npm
      Watchman: 2023.06.08.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, visionOS 1.0, watchOS 10.0
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 15.0/15A5229m - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.10 => 49.0.10 
      react: 18.2.0 => 18.2.0 
      react-native: ^0.72.4 => 0.72.4 
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

iPhone 12 mini

### Reproducible demo or steps to reproduce from a blank project

I suppose this should be able to be recreated if you link a new Appstore project to your Expo Team account?

**Comment by chen-rn** [comment]
I was able to resolve this by opening up the ios/.xcworkspace project using XCode.
Manually selecting the _new_ development team to build with.
Then it npx expo prebuild --clean.
Then it showed up when I ran npx expo run:ios -d.

**Comment by byCedric** [comment]
Hi @chen-rn! I'm glad you were able to resolve this. If you think we can handle this better in any way, please open a new issue on [github.com/expo/expo](https://github.com/expo/expo).

Closing this since you resolved the issue.
