### ISSUE TITLE
expo init error

### ISSUE THREAD

**Issue by sudip03** [expo/expo-cli#477]
I am new to EXPO. Tried **expo init HelloProject** and got this error.

14072 verbose stack Error: EPERM: operation not permitted, unlink 'c:\reactnative\HelloProject\node_modules\.staging\react-native-ef60a9e2\Libraries\Renderer\oss\ReactNativeRenderer-dev.js'
14073 verbose cwd c:\reactnative\HelloProject
14074 verbose Windows_NT 6.1.7601
14075 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\dip\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
14076 verbose node v10.15.3
14077 verbose npm  v6.9.0
14078 error path c:\reactnative\HelloProject\node_modules\.staging\react-native-ef60a9e2\Libraries\Renderer\oss\ReactNativeRenderer-dev.js
14079 error code EPERM
14080 error errno -4048
14081 error syscall unlink
14082 error Error: EPERM: operation not permitted, unlink 'c:\reactnative\HelloProject\node_modules\.staging\react-native-ef60a9e2\Libraries\Renderer\oss\ReactNativeRenderer-dev.js'
14082 error  { [Error: EPERM: operation not permitted, unlink 'c:\reactnative\HelloProject\node_modules\.staging\react-native-ef60a9e2\Libraries\Renderer\oss\ReactNativeRenderer-dev.js']
14082 error   cause:
14082 error    { Error: EPERM: operation not permitted, unlink 'c:\reactnative\HelloProject\node_modules\.staging\react-native-ef60a9e2\Libraries\Renderer\oss\ReactNativeRenderer-dev.js'
14082 error      errno: -4048,
14082 error      code: 'EPERM',
14082 error      syscall: 'unlink',
14082 error      path:
14082 error       'c:\\reactnative\\HelloProject\\node_modules\\.staging\\react-native-ef60a9e2\\Libraries\\Renderer\\oss\\ReactNativeRenderer-dev.js' },
14082 error   stack:
14082 error    'Error: EPERM: operation not permitted, unlink \'c:\\reactnative\\HelloProject\\node_modules\\.staging\\react-native-ef60a9e2\\Libraries\\Renderer\\oss\\ReactNativeRenderer-dev.js\'',
14082 error   errno: -4048,
14082 error   code: 'EPERM',
14082 error   syscall: 'unlink',
14082 error   path:
14082 error    'c:\\reactnative\\HelloProject\\node_modules\\.staging\\react-native-ef60a9e2\\Libraries\\Renderer\\oss\\ReactNativeRenderer-dev.js' }
14083 error The operation was rejected by your operating system.
14083 error It's possible that the file was already in use (by a text editor or antivirus),
14083 error or that you lack permissions to access it.
14083 error
14083 error If you believe this might be a permissions issue, please double-check the
14083 error permissions of the file and its containing directories, or try running
14083 error the command again as root/Administrator (though this is not recommended).

## note
1. I have used cli as administrator
2. Cleared cache and tried same again
3. Make sure no antivirus, editor uses any file.
4. Folder permission is ok

## Environment:
node -v : 10.15.3
expo -V: 2.14.0
OS: windows 7

**Comment by sergeichestakov** [comment]
Not sure about the specifics of Windows permissions, but you shouldn't be running `expo init` as an administrator. This may make files in the project not accessible for non admin users. Try again without admin and see if that helps.

However, I'm a little confused because the following error seems to suggest you are not running the command as an administrator:
```
14083 error If you believe this might be a permissions issue, please double-check the
14083 error permissions of the file and its containing directories, or try running
14083 error the command again as root/Administrator (though this is not recommended).
```

Were you able to resolve this issue?

**Comment by IBRAHIMDANS** [comment]
run with `npx expo init`

**Comment by jkhales** [comment]
Closing as the issue seems resolved.
