### ISSUE TITLE
Build Webhook stopped sending expo-signature header

### ISSUE THREAD

**Issue by danieltaub** [expo/expo-cli#4778]
### Summary

I am reaching out to bring an issue to your attention regarding the Expo webhooks I have set up to receive alerts on builds and submits within Expo. Until recently, the webhooks were functioning as expected. However, I have observed that the expo-signature has stopped being sent with the webhook requests.

Given that our webhook URL is publicly accessible, it is crucial for us to validate incoming requests to ensure their legitimacy. The absence of the expo-signature is preventing us from doing so, as we rely on it as a key component of our validation process.

I have checked the status page for any relevant updates or known issues, but did not find any mention of this particular problem.

Could you please look into this matter and provide clarification on why the expo-signature is no longer being sent with the webhook requests? Your assistance in resolving this issue will be greatly appreciated, as the webhooks are a vital part of our workflow.

### Environment

prod

### Please specify your device/emulator/simulator platform, model and version

webhooks

### Reproducible demo or steps to reproduce from a blank project

-

**Comment by blobkitten** [comment]
No reproducible demo means it will usually be closed

**Comment by byCedric** [comment]
Hi @danieltaub! I'm sorry that your issue report remained unanswered for some time. In the future, if you have issues with our infra, I think it's best if you contact us directly through [expo.dev/contact](https://expo.dev/contact).

I double-checked and verified that we are still sending the `expo-signature`, together with the `user-agent: Expo-Webhook-Caller/1.0` and `content-type: application/json` headers.

If you still have problems with this, please reach out 😄
