### ISSUE TITLE
Error: xcrun exited with non-zero code: 115

### ISSUE THREAD

**Issue by miltone92** [expo/expo-cli#4789]
### Summary

I am encountering an issue where I receive the following error message when running yarn start in my Expo project: 'Error: xcrun exited with non-zero code: 115.' This prevents the expo app from opening, on the simulator end, it just closes the expo app as soon as it tries to open it.

### Environment

Environment: 
xcode version: Version 15.0.1 (15A507)
ios: 17.0
os: 14.1.1 (23B81)
"expo": "~48.0.15",
"expo-application": "~5.1.1",

### Please specify your device/emulator/simulator platform, model and version

ios 17.0. Iphone 15 (Simulator on Mac)

### Error output

```
Error: xcrun exited with non-zero code: 115
An error was encountered processing the command (domain=LSApplicationWorkspaceErrorDomain, code=115):
Simulator device returned an error for the requested operation.
Underlying error (domain=LSApplicationWorkspaceErrorDomain, code=115):
        The operation couldn't be completed. (LSApplicationWorkspaceErrorDomain error 115.) 

```

### Reproducible demo or steps to reproduce from a blank project

Step to reproduce:
Navigate to my Expo project directory.
Run the command yarn start to start the development server.
Observe the error message, 'Error: xcrun exited with non-zero code: 115.'
The iOS simulator fails to launch, and I cannot proceed with testing my app."

**Comment by pedroksty** [comment]
Try change the node version

**Comment by abdulsamadayoade** [comment]
Make sure the simulator is opened before starting the development server and if simulator fails to launch, delete and reinstall simulator

**Comment by angel3cu** [comment]
I am having the exact same issue. Using:

- iOS 17 in the Simulator
- Expo 49
- Expo CLI 0.10.11

```
Error: xcrun exited with non-zero code: 115
An error was encountered processing the command (domain=LSApplicationWorkspaceErrorDomain, code=115):
Simulator device returned an error for the requested operation.
Underlying error (domain=LSApplicationWorkspaceErrorDomain, code=115):
        The operation couldn’t be completed. (LSApplicationWorkspaceErrorDomain error 115.)
```

**Comment by angel3cu** [comment]
I figured it out. I had a build made for a physical device, but I needed a special build for a Simulator. I know, rookie mistake, but maybe it could help anyone reading this in the future. 🙂

**Comment by otmancra** [comment]
I encountered a similar issue, which seems to be linked to Apple Silicon chips (M*). I'm using the M3 Chip, and resolving this problem involved installing Rosetta. After installing Rosetta, I was able to successfully run the Expo Go app and the Dev build in the simulator.

For those facing the same issue, you can install Rosetta using the following command:
`softwareupdate --install-rosetta`

This resolved the compatibility issue for me. Hopefully, it helps others facing a similar challenge!

**Comment by miltone92** [comment]
Thank you.
I managed to get my app going on the simulator by installing a new vanilla expo app. This prompted me to update expo go on my simulator. I updated. Went back to my desired app, and reject the app's request to updated expo go. This rendered the app correctly.

To sum it up, used another version of expo app prompted by default starter app.

**Comment by miltone92** [comment]
> softwareupdate --install-rosetta

This solved my issue! Thanks!!

**Comment by miltone92** [comment]
> I encountered a similar issue, which seems to be linked to Apple Silicon chips (M*). I'm using the M3 Chip, and resolving this problem involved installing Rosetta. After installing Rosetta, I was able to successfully run the Expo Go app and the Dev build in the simulator.
> 
> For those facing the same issue, you can install Rosetta using the following command: `softwareupdate --install-rosetta`
> 
> This resolved the compatibility issue for me. Hopefully, it helps others facing a similar challenge!

This solved my issue 100%. Thank you!

**Comment by amorimcode** [comment]
deleting the emulator and creating again solved for me

**Comment by MariuzM** [comment]
> deleting the emulator and creating again solved for me

Same for me thought updating to latest node version causes issue, but creating new sim solved
