### ISSUE TITLE
Invalid sdkVersion 32.0 after update

### ISSUE THREAD

**Issue by thg303** [expo/expo-cli#479]
## Description
After updating expo-cli, when creating new projects using `expo init`, the project is built with `"sdkVersion": "32.0.0",` but the "npm start" script leads to error.

 
1-2 sentences describing the problem you're having or the feature you'd like to request

## Expected Behavior

it should not display any error/warning.

## Observed Behavior

```
Warning: Problem validating app.json: Unable to perform cache refresh for /Users/ali/.expo/cache/schema-32.0.0.json: Error: Request failed with status code 400.
Error: Invalid sdkVersion. Valid options are 10.0.0, 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0, 16.0.0, 17.0.0, 18.0.0, 19.0.0, 20.0.0, 21.0.0, 22.0.0, 23.0.0, 24.0.0, 25.0.0, 26.0.0, 27.0.0, 28.0.0, 29.0.0, 30.0.0, 31.0.0, 7.0.0, 8.0.0, 9.0.0
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

```
  Expo CLI 2.14.0 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
      Yarn: 1.12.3 - ~/.nvm/versions/node/v10.15.0/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 2.14.0
```

## Reproducible Demo
update after creating a project with older version.

**Comment by thg303** [comment]
I removed the package and reinstall it. still the same.
looks like there should be a `schema-32.0.0.json`file in this path **https://github.com/expo/expo-cli/tree/master/packages/xdl/caches**

**Comment by cruzach** [comment]
Hey @thg303,

Could you try [this solution](https://github.com/react-community/create-react-native-app/issues/622#issuecomment-379435125) and let me know if that works? 

I tried to recreate this issue, same environment, but I'm not seeing it. When I run `ls ~/.expo/cache`, "schema-32.0.0.json" does appear. Let me know if running `rm -rf ~/.expo/cache` and a reinstall helps

**Comment by thg303** [comment]
@cruzach Charlie I tried that. it was the same. when I tried running `expo start` I got these lines:
Warning: Problem validating app.json: Unable to perform cache refresh for ```
/Users/ali/.expo/cache/schema-32.0.0.json: Error: Request failed with status code 500.
Error: Invalid sdkVersion. Valid options are 10.0.0, 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0, 16.0.0, 17.0.0, 18.0.0, 19.0.0, 20.0.0, 21.0.0, 22.0.0, 23.0.0, 24.0.0, 25.0.0, 26.0.0, 27.0.0, 28.0.0, 29.0.0, 30.0.0, 31.0.0, 7.0.0, 8.0.0, 9.0.0
```

I found that `npm start`, makes the expo checks for sdk version and tries to refresh the cache using "35.202.142.166:443" server. which normally is not accessible from my internet. could be a restriction from local Internet ISP or US sanctions. anyway I could by pass it by using **proxychains**

**Comment by AliTalebi** [comment]
Hi, I had this problem then I change expo sdkVersion in app.json to 31.0.0 that works

**Comment by thg303** [comment]
it always works if you ignore updates ;)
