### ISSUE TITLE
(Error) Upgrading to SDK 32. Production mode only: Can't find variable: error

### ISSUE THREAD

**Issue by szholdiyarov** [expo/expo-cli#482]
## Description

I have upgraded an expo sdk version to 32 from 26 (I followed an instruction). When I run an app in the development mode everything is OK, but production mode leads to error: 'Can't find variable: error'. The error is happening on both platforms in only PRODUCTION mode (IOS and Android). 

## Expected Behavior

First, I run `expo start` and toggle production mode. Then I run my app in either android or ios simulators. I expect that the application is started without error.

## Observed Behavior

An actual behavior is an error screen on both platforms. An error does not contain any useful information on how to find a 'reason' where it comes from. 

There is no terminal output. But I can access a logcat from the Android Studio. No logs from ios.

```
host.exp.exponent E/ReactNativeJS: Can't find variable: error
host.exp.exponent E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
```
I have also observed a strange RuntimeException (and still I do not know if it's somehow related):

```
host.exp.exponent E/d: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
```

## Environment

```
Expo CLI 2.14.0 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.1/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ~2.3.1 => 2.3.1 
    npmGlobalPackages:
      expo-cli: 2.14.0
```

- IOS Emulator (iPhone X)
- Android Simulator (Pixel - x86_64)

## Tried
- Removing node_modules
- Clearing npm, yarn metro, haste, babel caches
- Following Expo 32 upgrade guide
- Stripping out all my code
- Removing all my package.json dependencies
- Various versions of Expo@32.0.x
- Uninstalling app on device
- Clearing storage for app on device

## Reproducible Demo

This is a private application, so I can't provide the full repository, but would be happy to provide any information which might be useful.

![Simulator Screen Shot - iPhone X - 2019-04-01 at 23 45 56](https://user-images.githubusercontent.com/9438488/55348428-003aca00-54d9-11e9-9f07-79954d3d6824.png)
![Screenshot_1554140551](https://user-images.githubusercontent.com/9438488/55348433-0335ba80-54d9-11e9-8b69-303f958bcb46.png)

package.json:

```
{
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "scripts": {
    "build": "babel src/ -d lib/",
    "test": "node ./node_modules/jest/bin/jest.js --watch",
    "flow": "flow"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@babel/core": "^7.4.0",
    "@expo/samples": "2.1.1",
    "@expo/vector-icons": "^10.0.1",
    "babel-eslint": "^8.2.6",
    "babel-plugin-module-resolver": "^3.2.0",
    "babel-preset-expo": "^5.1.1",
    "eslint-plugin-react-native": "^3.6.0",
    "exp": "51.4.0",
    "expo": "^32.0.0",
    "exponent": "^14.0.0",
    "hoist-non-react-statics": "^2.5.5",
    "i18next": "^10.2.2",
    "install": "^0.10.2",
    "module-alias": "^2.2.0",
    "npm": "^5.10.0",
    "prop-types": "15.6.1",
    "react": "16.5.0",
    "react-i18next": "^7.13.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-dropdown-menu": "git+https://github.com/mataoct/react-native-dropdown-menu.git",
    "react-native-easy-toast": "^1.2.0",
    "react-native-elements": "^1.1.0",
    "react-native-i18n": "^1.0.0",
    "react-native-image-slider": "^1.1.5",
    "react-native-modal": "^9.0.0",
    "react-native-modal-dropdown": "^0.6.0",
    "react-native-responsive-image": "^2.2.0",
    "react-native-responsive-screen": "^1.2.1",
    "react-navigation": "~2.3.1",
    "react-navigation-redux-helpers": "^2.0.9",
    "react-redux": "^5.1.1",
    "redux": "4.0.0",
    "redux-devtools-extension": "^2.13.8",
    "redux-persist": "^5.10.0",
    "redux-promise-middleware": "^5.1.1",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-preset-flow": "^6.23.0",
    "eslint": "^5.15.3",
    "eslint-config-airbnb": "^17.1.0",
    "flow-bin": "^0.63.1",
    "jest-expo": "^32.0.0",
    "schedule": "^0.4.0"
  },
  "_moduleAliases": {
    "@root": ".",
    "@components": "src/components",
    "@screens": "src/screens"
  }
}
```

app.json
```
{
  "expo": {
    "privacy": "public",
    "sdkVersion": "32.0.0",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./src/assets/images/logostore.png",
    "splash": {
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "ios": {
      "supportsTablet": false,
      "buildNumber": "8",
      "bundleIdentifier": "***"
    },
    "android": {
      "package": "***",
      "versionCode": 8
    }
  }
}
```

**Comment by brentvatne** [comment]
hello! sorry there was no reply to this, i hope you were able to resolve it. i'm not able to determine what may have gone wrong in this case without seeing the actual code. i'll close this because it's old now, we'll respond more timely next time. apologies
