### ISSUE TITLE
expo start gives error 

### ISSUE THREAD

**Issue by GalacticRogue** [expo/expo-cli#485]
# READ THIS FIRST, PLEASE!

We're looking to keep questions on our forums and bug reports on the GitHub repo -- please choose whichever you feel is more appropriate for your issue:

- Post in our community forums (log in with your Expo developer account): https://forums.expo.io/c/help
- File a bug on the Expo CLI repo (for bugs related to the Expo CLI tools): https://github.com/expo/expo-cli/issues/new
- File a bug on the main Expo repo (for other bugs): https://github.com/expo/expo/issues/new
- Request a feature on Canny: https://expo.canny.io/feature-requests

Thanks for reporting the issue you found with Expo CLI!

# Required format for issues

Please make our job easier by filling this template out to completion.

## Description
Well I have installed expo-cli via `npm install -g expo-cli` it worked successfully then I have 
Initialized a directory via `expo init  HelloProject` it worked , but when I have tried  `npm start` it connects for a second and shows error , [errorimage](https://drive.google.com/file/d/1aVSZjIU66-7o_RuXMBFSYrTNOEBbLs85/view?usp=drivesdk)

## Expected Behavior

It should connect successfully and stay connected 

## Observed Behavior

It gave the error shown above in the errorimage

## Environment

`expo diagnostics`
```
Expo CLI 2.14.0 environment info:
    System:
      OS: Linux 4.14 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.10.0 - /usr/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 3.5.2 - /usr/bin/npm
    npmPackages:
      expo: ^32.0.0 => 32.0.6•
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 2.14.0
```

**Comment by cruzach** [comment]
Hey @GalacticRogue ,

You actually need Node version 10 or above, see our [installation instructions](https://docs.expo.io/versions/latest/introduction/installation/#local-development-tool-expo-cli)

Thanks!
Charlie

**Comment by GalacticRogue** [comment]
Well I tried it with node v11 as well but same issue
