### ISSUE TITLE
npm run android doesn't work but expo start --android works just fine

### ISSUE THREAD

**Issue by ivicasapina** [expo/expo-cli#49]
# Required format for issues

Installing any package, for example lodash, or mobx

## Description

Created app with expo init app_name
working just fine with npm run android, but after installing any package that breaks

## Expected Behavior

After npm run android i expected to opet project on android emulator

## Observed Behavior

Installed lodas and cannot use npm run android, but still can use expo start --android and that works.
But why? if npm run android calls expo start --android

```
> npm run android

> my-new-project@ android D:\dev\Android\my-app
> expo start --android

This command requires Expo CLI.
Do you want to install it globally [Y/n]?
if i press  Y
Installing the package 'expo-cli'...
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-new-project@ android: `expo start --android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-new-project@ android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dom Net 240\AppData\Roaming\npm-cache\_logs\2018-09-26T14_05_44_811Z-debug.log
```

But if i run expo start --android it all works just fine.
## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

Environment:
  OS: Windows 10
  Node: 10.11.0
  Yarn: Not Found
  npm: 6.4.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  lodash: ^4.17.11
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/nebitno-e3ec3d47-3996-429c-9761-77daac4ae0fe.tar.gz

**Comment by ivan-navarro-75** [comment]
Exactly the same issue here.

Environment:
  OS: Windows 10
  Node: 10.5.0
  Yarn: Not Found
  npm: 6.1.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4907809

Packages: (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/sinplanbsoft-dcdbdf37-c5c1-448c-804a-651f82564ff9.tar.gz

**Comment by elitdie** [comment]
Had same problem, but made next things:
1. Run PowerShell as administrator (right-click on windows icon in left-bottom corner)
2. `npm install -g expo-cli` (cause installing under user was generate error EACCES aka "has no permission")
expo still unreachable and suggests to install it.
3. Run PowerShell normally
4. again `npm install -g expo-cli` (installation finished success)

**Comment by dashu3f** [comment]
npm update

**Comment by PsychoXIVI** [comment]
Same issue :C

**Comment by shatodj** [comment]
Install `expo-cli` locally:
`npm i expo-cli --save-dev`

**Comment by glautrou** [comment]
As said above by @dashu3f, run :
> npm update

That will update Expo package to the latest version which include the fix (31.0.6). Now there is no need for any workaround.

Pull request : #2853

**Comment by isapina** [comment]
@glautrou @dashu3f
I have made an update to 31.0.0 and it's working just fine (so far) :)
Thanks

@fson This issue can be closed now that it doesn't throw an error on sdk ^31.0.0

**Comment by ivicasapina** [comment]
@glautrou @dashu3f
I have made an update to 31.0.0 and it's working just fine (so far) :)
Thanks

@fson This issue can be closed now that it doesn't throw an error on sdk ^31.0.0

**Comment by orsospatrick** [comment]
Go to=>Advance system setting\Enviroment variable and set system variables path
 C:\Windows\System32\ variable and restart your System.

just add it to the PATH: C:\Windows\System32 and start cmd as Administrator
