### ISSUE TITLE
Unable to create react native project using expo-cli

### ISSUE THREAD

**Issue by vikascn** [expo/expo-cli#490]
Unable to create react native project using expo-cli

I installed expo-cli using this command: 
npm install -g expo-cli
It installed successfully

***
Later i am tried to create a new react native project, but getting permission denied errors :

sudo expo init photo-feed

? Choose a template: expo-template-blank
✔ Please enter a few initial configuration values.
  Read more: https://docs.expo.io/versions/latest/workflow/configuration/ · 100% completed
Extracting project files...
Customizing project...
Initialized a git repository.
Installing dependencies...
npm WARN deprecated core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.

> fsevents@1.2.7 install /Users/vnandiha/Documents/Personal/Android Projects/reactNative/photo-feed/node_modules/fsevents
> node install

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.7 and node@10.15.3 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/Users/vnandiha/Documents/Personal/Android Projects/reactNative/photo-feed/node_modules/fsevents/lib' 
**gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir** '/Users/vnandiha/Documents/Personal/Android Projects/reactNative/photo-feed/node_modules/fsevents/build'
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/Users/vnandiha/npm-global/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/vnandiha/Documents/Personal/Android Projects/reactNative/photo-feed/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/vnandiha/Documents/Personal/Android Projects/reactNative/photo-feed/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /Users/vnandiha/Documents/Personal/Android Projects/reactNative/photo-feed/node_modules/fsevents
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /Users/vnandiha/npm-global/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/vnandiha/Documents/Personal/Android Projects/reactNative/photo-feed/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/vnandiha/Documents/Personal/Android Projects/reactNative/photo-feed/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/vnandiha/Documents/Personal/Android Projects/reactNative/photo-feed/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/vnandiha/Documents/Personal/Android Projects/reactNative/photo-feed/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/vnandiha/Documents/Personal/Android Projects/reactNative/photo-feed/node_modules/fsevents
node-pre-gyp ERR! node -v v10.15.3
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /Users/vnandiha/npm-global/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/vnandiha/Documents/Personal/Android Projects/reactNative/photo-feed/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/vnandiha/Documents/Personal/Android Projects/reactNative/photo-feed/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=3 --node_abi_napi=napi' (1)
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN expo-google-sign-in@2.0.0 requires a peer of react-native@^0.55.4 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-reanimated@1.0.0-alpha.11 requires a peer of react@16.0.0-alpha.6 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-reanimated@1.0.0-alpha.11 requires a peer of react-native@^0.44.1 but none is installed. You must install peer dependencies yourself.
npm WARN url-loader@1.1.2 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 892 packages from 434 contributors and audited 24003 packages in 34.229s
found 6 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

Your project is ready at /Users/vnandiha/Documents/Personal/Android Projects/reactNative/photo-feed

To get started, you can type:

  cd photo-feed
  npm start

***
It created the project folder even though it gave errors.
I did 'npm start', but more permission errors:

 npm start

> @ start /Users/vnandiha/Documents/Personal/Android Projects/reactNative/photo-feed
> expo start

EACCES: permission denied, mkdir '/Users/vnandiha/Documents/Personal/Android Projects/reactNative/photo-feed/.expo'
Set EXPO_DEBUG=true in your env to view the stack trace.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `expo start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

***
## Environment

  Expo CLI 2.14.0 environment info:
    System:
      OS: macOS Sierra 10.12.6
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      npm: 6.9.0 - ~/npm-global/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 2.3 AI-162.4069837
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      expo-cli: 2.14.0

**Comment by methodbox** [comment]
I don’t believe this is an expo issue.

I believe the OP needs to follow the `node_modules` global folder installation method moving the folder to the user’s home directory (as I indicated in his other post on the same issue).

However, if `node-gyp` is already installed in a different global folder it will find this first and the issue will not be resolved.

Kill the npm cache. Manually delete `node-gyp` from the current global folder.

Move the global folder and reassign the global folder location variable. You *must* create this folder in your home directory and verify ownership is for your user. Creating it as root will cause similar problems.

Manually reinstall `npm install -g node-gyp`.

Then reinstall Expo.

**Comment by sergeichestakov** [comment]
Hey @vikascn,

As @methodbox said, you should not be using sudo for `expo init` nor any other expo command. In general, you should err on the side of not giving programs sudo permissions if they don't need it.

Can you set the EXPO_DEBUG environment variable via ```export EXPO_DEBUG=true``` and rerun the command? This will help us see which function threw the error as I was not able to reproduce this issue on my MacOS machine.

You could also try using yarn instead by running ```rm -rf node_modules && yarn```. Just make sure you install yarn on your system first.

Let me know if that helps or if you were able to resolve the issue.
