### ISSUE TITLE
Can't run app on android after eject 

### ISSUE THREAD

**Issue by ElegantSoft** [expo/expo-cli#492]
after ejecting 
I tried react-native run android 
and cd android && ./gradlew installDevDebug
and ./gradlew instalDebug
and get same error 
Parallel execution with configuration on demand is an incubating feature.

> Configure project :app
AWS Device Farm Plugin version 1.3
AWS Device Farm configuration is NOT VALID
AWS Device Farm configuration is NOT VALID
Could not find google-services.json while looking in [src/dev/kernel/debug, src/devKernel/debug, src/debug/devKernel, src/dev/debug, src/dev/kernel, src/dev/kernelDebug, src/devKernel, src/debug, src/devKernelDebug, src/dev, src/devDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/dev/kernel/release, src/devKernel/release, src/release/devKernel, src/dev/release, src/dev/kernel, src/dev/kernelRelease, src/devKernel, src/release, src/devKernelRelease, src/dev, src/devRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/prod/kernel/debug, src/prodKernel/debug, src/debug/prodKernel, src/prod/debug, src/prod/kernel, src/prod/kernelDebug, src/prodKernel, src/debug, src/prodKernelDebug, src/prod, src/prodDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/prod/kernel/release, src/prodKernel/release, src/release/prodKernel, src/prod/release, src/prod/kernel, src/prod/kernelRelease, src/prodKernel, src/release, src/prodKernelRelease, src/prod, src/prodRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDevDebug' not found in root project 'android'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by sergeichestakov** [comment]
Hey @ElegantSoft,

Thanks for filing this issue! I went ahead and tried to eject/run on Android and ran into some issues as well although I got a different set of errors. Some things that worked for me:
- `yarn add @babel/core` and `yarn add @babel/runtime`
- Explicitly set RN version: `yarn add react-native@0.57.1`
- Create `index.js` if it doesn't already exist and register your app using `AppRegistry.registerComponent`

This fixed the problem for me and got my app running after I ejected although it seems like you're past that issue. The error message you're getting seems to be related to a dependency that relies on `google-services.json`. It might help to move that file and other dependencies into the `android/app/` directory as described in [this](https://stackoverflow.com/questions/32072568/how-to-add-google-services-json-in-android#32078958) SO post.

Let me know if that helps.
