### ISSUE TITLE
React native Set EXPO_DEBUG=true 

### ISSUE THREAD

**Issue by JayeshPoriya** [expo/expo-cli#50]
I am working on MacBook Pro & fire command on terminal.
Created react native app using create-react-native-app AwesomeApp and error on when run expo start in the app folder

IND-MAC-012:AwesomeProject rls$ expo start
[12:06:14] Starting project at /Users/rls/Desktop/Jayesh Poriya/React Native/LTMS/AwesomeProject
[12:06:33] Starting Metro Bundler on port 19003.
[12:06:33] Metro Bundler ready.
**[12:06:54] Could not access packager status at http://localhost:19003/status 1. Are you sure the packager is running and reachable?**
**[12:06:54] Set EXPO_DEBUG=true in your env to view the stack trace.**
IND-MAC-012:AwesomeProject rls$

A project is not started. Not get QRCode.
Can anyone help me?
![jayesh_poriya](https://user-images.githubusercontent.com/16848686/46123710-9ac20400-c23d-11e8-89ab-748ad077200a.png)

**Comment by fson** [comment]
Closing this as a duplicate, in favor of #52, which has more information.

**Comment by GhagSagar23** [comment]
Just go to the directory of your project from terminal. Then paste the below code.

export EXPO_DEBUG=true

![screen shot 2019-03-01 at 12 44 52 pm](https://user-images.githubusercontent.com/32163934/53622452-da8f7c00-3c1f-11e9-8473-afe123f04568.png)

**Comment by craigcosmo** [comment]
> Just go to the directory of your project from terminal. Then paste the below code.
> 
> export EXPO_DEBUG=true
> 
> ![screen shot 2019-03-01 at 12 44 52 pm](https://user-images.githubusercontent.com/32163934/53622452-da8f7c00-3c1f-11e9-8473-afe123f04568.png)

Thanks

**Comment by jhocyemir** [comment]
Buenas señores tengo el mismo problema pero en window, intente con export EXPO_DEBUG = true y no me funciona. Aquí imagen del error
![Error expo](https://user-images.githubusercontent.com/55995217/67152262-ed7ebb80-f297-11e9-8774-0dca5f33b4fd.PNG)

**Comment by kumohen** [comment]
i am also getting same issue in my window .i had already setting set EXPO_DEBUG=true in my VS code terminal .still it is not working
