### ISSUE TITLE
setting.json dev will auto become false  i not know  the reason  it  will not allowed to  use hot  reloading....

### ISSUE THREAD

**Issue by yehoan** [expo/expo-cli#503]
# READ THIS FIRST, PLEASE!

We're looking to keep questions on our forums and bug reports on the GitHub repo -- please choose whichever you feel is more appropriate for your issue:

- Post in our community forums (log in with your Expo developer account): https://forums.expo.io/c/help
- File a bug on the Expo CLI repo (for bugs related to the Expo CLI tools): https://github.com/expo/expo-cli/issues/new
- File a bug on the main Expo repo (for other bugs): https://github.com/expo/expo/issues/new
- Request a feature on Canny: https://expo.canny.io/feature-requests

Thanks for reporting the issue you found with Expo CLI!

# Required format for issues

Please make our job easier by filling this template out to completion.

## Description

i  use  expo start  and  use  a  app  at first it is  okay  including  hot  reloading  but  then  i  not know  the  reason  not  allowed  use  hot reloading  and find   setting.json  dev become  false  

![image](https://user-images.githubusercontent.com/22631753/55955448-0cbae180-5c94-11e9-850e-c0e4d017bc07.png)

1-2 sentences describing the problem you're having or the feature you'd like to request

## Expected Behavior

What action did you perform, and what did you expect to happen?

i  really  want  to  the  reason  why   

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the _full terminal output and error message_ in this code block:

```
Error text goes here!
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

  Expo CLI 2.14.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - D:\工具\node.EXE
      Yarn: 1.15.2 - C:\Users\Administration\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - D:\工具\npm.CMD

Also specify:

- Phone/emulator/simulator platform, model and version:

use emulator 
## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by brentvatne** [comment]
i think dev mode may have been toggled somewhere by accident. you can toggle it in expo-cli (press ? to see the list of commands) or in the web-based dev tools https://docs.expo.io/versions/latest/workflow/development-mode/#toggling-development-mode-in-expo-dev-tools
