### ISSUE TITLE
Issues with expo in window SO

### ISSUE THREAD

**Issue by pixsolution** [expo/expo-cli#518]
Hello,

Hope you're doing well!
Yesterday I was working well with expo and today I try to update to last version and I get error attached capture. And I try also to create a new project with expo and I get the same error.
![1](https://user-images.githubusercontent.com/47191848/56141806-ce783780-5f9d-11e9-9bfb-726bfbab0d20.png)

In the project I was developing that yesterday I ran "expo start" today and nothing does not open the local expo server and the terminal says "that command is not recognized". It's really strange everything I don't know what happen :s

Do you know what could be?

My computer it's using windows 7

Hope you can help!

Regards

**Comment by AdamJNavarro** [comment]
Hey @pixsolution,

I responded to your forum post [here](https://forums.expo.io/t/issues-with-expo-in-window-so/21628/2). I'm going to close this issue. Let me know in the forum thread if you encounter any issues.

Cheers,
Adam
