### ISSUE TITLE
Metro Bundler has encountered an internal error, please check your terminal error output for more details

### ISSUE THREAD

**Issue by japenguin** [expo/expo-cli#521]
## Description

Running expo build:android results in in Metro Bundler internal error.  

## Expected Behavior

When last run 14 days ago, had no issues.

## Observed Behavior

Never get a build, as the process ends. With EXPO_DEBUG=true I get the following output"

> expo build:android
Checking if there is a build in progress...

Unable to find an existing Expo CLI instance for this directory, starting a new one...
Starting Metro Bundler on port 19001.
Tunnel ready.
Publishing to channel 'default'...
Building iOS bundle
Metro Bundler has encountered an internal error, please check your terminal error output for more details
Unexpected end of JSON input
::ffff:127.0.0.1 - - [17/Apr/2019:03:23:22 +0000] "GET /node_modules/expo/AppEntry.bundle?dev=false&minify=true&hot=false&assetPlugin=C%3A%5CUsers%5CE.Robert%5CDocuments%5CProjects%5CGenius%5Cmain%5Csource%5Cclient-native%5Cnode_modules%5Cexpo%5Ctools%5ChashAssetFiles.js&platform=ios HTTP/1.1" 500 - "-" "axios/0.19.0-beta.1"Webpack is not running.
Cannot read property 'status' of undefined
TypeError: Cannot read property 'status' of undefined
    at C:\xdl@53.5.0\src\Project.js:158:70
    at Generator.throw (<anonymous>)
    at step (C:\Users\E.Robert\AppData\Roaming\npm\node_modules\expo-cli\node_modules\xdl\build\Project.js:2349:191)
    at C:\Users\E.Robert\AppData\Roaming\npm\node_modules\expo-cli\node_modules\xdl\build\Project.js:2349:402
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Building JavaScript bundle [==========================================================================                          ] 74%

## Environment

  Expo CLI 2.14.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4907809

**Comment by japenguin** [comment]
To troubleshoot, I:
- Deleted node_modules and ran npm -install
- Rebooted machine

**Comment by AdamJNavarro** [comment]
Hey @japenguin,

Just to be certain, have you resolved the issue on your end?

Cheers,
Adam

**Comment by japenguin** [comment]
No, unfortunately nothing I have tried has resolved the issue.



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by japenguin** [comment]
@AdamJNavarro still unable to overcome this issue.  Any ideas on where I can investigate?  Is this on my end?  Starting to roll back code changes to find a successful build but painfully slow.  

Thanks for your help.

**Comment by japenguin** [comment]
If I copy my project directory to another directory on the file system, I can successfully publish the project.  Exact same directory contents.  Does Expo cache information specific to a project outside of the project directory?

**Comment by AdamJNavarro** [comment]
Hey @japenguin,

Some things are stored in a local cache. If you ever suspect that may be the source of an issue, running `rm -rf .expo` will usually help resolve things.

**Comment by szymansd** [comment]
Hey, @japenguin I had the same issue and solved it by removing `expo` from `node_modules` and `.expo` from project dir. After that, I started expo via `expo start` command and then I used `shift+r` command (which should restart expo and clear cache). After that everything worked again.
