### ISSUE TITLE
cannot init project in expo 

### ISSUE THREAD

**Issue by bunlong13137233** [expo/expo-cli#522]
When I install expo using "npm install -g expo-cli" then I try to "expo init project" to create my new project, but it doesn't work. Here is the error: 

internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module './lib/getenv'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/expo-cli/node_modules/getenv/index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)

**Comment by AdamJNavarro** [comment]
Hey @bunlong13137233,

Can you run `expo diagnostics` and paste the log printed out here?

Cheers,
Adam

**Comment by abhitej60** [comment]
C:\Users\HELLO\Desktop\re\AwesomeProject>expo diagnostics

  Expo CLI 2.15.3 environment info:
    System:
      OS: Windows 7
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5264788

**Comment by sergeichestakov** [comment]
The error being thrown here is from Node and indicates that it's failing to import all of the modules it needs. You should try upgrading to the latest version of Node/npm and trying again.

If this error occurs when you run `expo start` on an existing project it likely means you haven't installed all of the dependencies which you can fix by running `npm install` or `yarn install` in the root project directory.

**Comment by GeekRishabh** [comment]
Facing the same issue.
`expo init abc` it hang up 
```
  Expo CLI 2.20.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.20.2
```

**Comment by EvanBacon** [comment]
This has been fixed

**Comment by eduardopelitti** [comment]
> This has been fixed

Hi @EvanBacon, could you point me to where this has been fixed please? 

I'm getting this issue when running `./gradlew assembleRelease` after being able to build successfully for several days.

**Comment by henriquecampaner** [comment]
> > This has been fixed
> 
> Hi @EvanBacon, could you point me to where this has been fixed please?
> 
> I'm getting this issue when running `./gradlew assembleRelease` after being able to build successfully for several days.

I have exactly the same problem

**Comment by BubbaMachina** [comment]
So i made a completely new Expo project, chose bare workflow, and immediately tried to push a signed APK (alredy did the keystore stuff), open in Android Studio, and when i try to build, or attempt ./gradlew assembleRelease i keep getting:
Cannot find module 'getenv' in Android Studio or similar from powershell on VS code
