### ISSUE TITLE
the out on the console is to verbose can we turn off?

### ISSUE THREAD

**Issue by craigcosmo** [expo/expo-cli#531]
every time I press save. the console display the same info

`Running application "main" with appParams: {"rootTag":101,"initialProps":{"exp":{"manifest":{"splash":{"resizeMode":"contain","image":"./assets/images/vegas-logo.png","backgroundColor":"#ffffff","imageUrl":"http://127.0.0.1:19001/assets/./assets/images/vegas-logo.png"},"developer":{"projectRoot":"/Users/craigcosmo/Desktop/vegas","tool":"expo-cli"},"loadedFromCache":false,"privacy":"public","logUrl":"http://127.0.0.1:19000/logs","orientation":"portrait","sdkVersion":"32.0.0","mainModuleName":"node_modules/expo/AppEntry","env":{},"platforms":["ios","android"],"xde":true,"id":"@anonymous/vegas-a5f13b6b-2012-4231-8c83-f077f593fcc0","hostUri":"127.0.0.1:19000","iconUrl":"http://127.0.0.1:19001/assets/./assets/images/vegas-logo.png","assetBundlePatterns":["**/*"],"name":"vegas app","slug":"vegas","debuggerHost":"127.0.0.1:19001","icon":"./assets/images/vegas-logo.png","isVerified":false,"packagerOpts":{"lanType":"ip","dev":true,"minify":false,"urlRandomness":"bw-pu6","hostType":"lan"},"ios":{"supportsTablet":true},"updates":{"fallbackToCacheTimeout":0},"bundleUrl":"http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fcraigcosmo%2FDesktop%2Fvegas%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js","version":"1.0.0"},"initialUri":"exp://127.0.0.1:19000","appOwnership":"expo","shell":0}}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF`

Can we turn it off?

**Comment by fson** [comment]
You're in luck: we've just published a new version of Expo CLI, which removes these logs. You can upgrade with `npm install -g expo-cli`. If you're still seeing `Running application "main" with appParams` in Expo CLI 2.15.2, please reopen the issue.
