### ISSUE TITLE
Unable to boot device in current state: Booted

### ISSUE THREAD

**Issue by fson** [expo/expo-cli#536]
## Description

I'm occasionally getting this error when starting the iOS simulator: "Unable to boot device in current state: Booted"

<img width="786" alt="Screenshot 2019-04-22 at 19 09 31" src="https://user-images.githubusercontent.com/497214/56510608-f6821080-6532-11e9-8cc0-f6bc8219a5b5.png">

## Expected Behavior

Simulator should start without errors.

## Observed Behavior

The `xcrun simctl boot` command fails because when it's called, the simulator is already running:
```
Error running `xcrun simctl boot 4BDC42E4-0213-4850-926E-72D5BB81CACA`: An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=164):
Unable to boot device in current state: Booted
```
This seems to only happen when Simulator.app is initially not running.

I think what might be happening is:
- Simulator.app is not running
- We run `open -a Simulator.app`. This starts **and** boots the simulator.
- While the simulator is still booting, we check the status (in `_waitForSimulatorRunningAsync`).
- The status is not *yet* booted, so we decide to try and boot the simulator.
- In the meantime the simulator has booted so the command fails.

We should probably not try to manually boot the simulator if Simulator.app is initially not running. Instead we could only boot it using `xcrun simctl boot` if it's initially started but not booted.

## Environment

**Tested on master** (4ca219ebb2f7bf46cef2b8ed7b6b2f908b678306)

```
  Expo CLI 2.15.3 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.13.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0-alpha.web.1 => 33.0.0-alpha.web.1 
      react-native: 0.57.1 => 0.57.1 
    npmGlobalPackages:
      expo-cli: 2.15.2

```
Phone/emulator/simulator platform, model and version: iPhone X (simulator)

**Comment by Way2nnadi** [comment]
I am getting this same error. Does any one have any insights to what the issue might be?

**Comment by Way2nnadi** [comment]
@fson I managed to fix this issue. Once the simulator is up to `Hardware` then click on `Erase all Content and Settings...`. Close the simulator and relaunch it, this will cause the latest `expo` to be installed in the simulator. I hope this helps :)

**Comment by oldo** [comment]
@Way2nnadi's solution fixes the issue for me temporarily, however I am regularly still getting this error. Has anyone found a more permanent workaround?

**Comment by NickFoden** [comment]
If anyone else landing on this error, maybe helpful to first check you haven't created an infinite loop. 

I was getting this error, and after some time I realized in a loop I had written `i += 1` written incorrectly as `i =+ 1` Could be helpful to check if you have created an infinite loop in recent code addition, as that was my case. 

```javascript
const createArray = length => {
  const arr = [];
  let i = 0;
  while (i < length) {
    arr.push(i.toString());
   //Had this wrong as i =+ 1
    i += 1;
  }
  return arr;
};
```

Just wanted to put this out there as an example of one possible cause, after I spent time debugging configurations and restarting simulators and updating etc etc.

**Comment by pitops** [comment]
Any updates on this? Getting this as well. The fix above seems to work but might be temporary as others said.

**Comment by nicotroia** [comment]
Install or update to the latest Xcode, and do `sudo xcode-select -s /Applications/Xcode.app` in the terminal. Then reset your Simulator and try `yarn start` followed by `i` to open ios.

**Comment by walter-grace** [comment]
> Install or update to the latest Xcode, and do `sudo xcode-select -s /Applications/Xcode.app` in the terminal. Then reset your Simulator and try `yarn start` followed by `i` to open ios.

also try expo optimize

**Comment by guillaumeduhan** [comment]
Hello, same problem here on Vue-Native CLI running "npm start". @Way2nnadi solution didn't work for me, either switching Xcode version, reinstalling expo.

Xcode: 10.2/10E125
Expo: 33.0.0

**Comment by guillaumeduhan** [comment]
> Hello, same problem here on Vue-Native CLI running "npm start". @Way2nnadi solution didn't work for me, either switching Xcode version, reinstalling expo, expo optimize...
> 
> Xcode: 10.2/10E125
> Expo: 33.0.0

Okay guys, I think I understand what you have to do in time in order to fix problem.

First: I was wrong - you got to follow @Way2nnadi method in order to install Expo on simulator. 

Second: DO NOT USE Iphone Xr device and last version of Xcode (beta 11) : that was my mistake during hours. I used iPhone 5s, still don't understand why but it worked perfectly.

**Comment by trackmystories** [comment]
Hey I fixed this issue: What we have to do is first install watchman once that is installed use sudo to start the application. here is a screenshot: 
<img width="626" alt="Screenshot 2019-06-28 at 12 18 32 PM" src="https://user-images.githubusercontent.com/43073387/60328242-f113cd00-999e-11e9-89ce-3d139cd0963a.png">
<img width="627" alt="Screenshot 2019-06-28 at 12 18 58 PM" src="https://user-images.githubusercontent.com/43073387/60328248-f2dd9080-999e-11e9-8ddf-696ee3fe5809.png">

**Comment by AndrewSouthpaw** [comment]
We have the same problem. It works fine if the Simulator is already up and running, but throws the error otherwise.

It's a pretty easy workaround but it's a surprising error...

**Comment by guillaumeduhan** [comment]
> Hey I fixed this issue: What we have to do is first install watchman once that is installed use sudo to start the application. here is a screenshot:
> 
> <img alt="Screenshot 2019-06-28 at 12 19 03 PM" width="620" src="https://user-images.githubusercontent.com/43073387/60328274-038e0680-999f-11e9-917d-64944f31ea89.png">
> 
> <img alt="Screenshot 2019-06-28 at 12 18 32 PM" width="626" src="https://user-images.githubusercontent.com/43073387/60328299-11dc2280-999f-11e9-89d5-dec825acac66.png">

I confirm: installing watchman solved my problem.

**Comment by AndrewSouthpaw** [comment]
> I confirm: installing watchman solved my problem.

Didn't solve the problem for me. 🙁

**Comment by aaayumi** [comment]
Installing Watchman fixed this error once, but I started to get the same error afterwards again even though Watchman is already installed.
-------------------
Version
Watchman 4.9.0
X-code 9.4.1

**Comment by Comi9** [comment]
Start the iOS simulator using `expo start --ios` in terminal, as opposed to starting it from the Metro Bundler UI.

**Comment by ZaidSA** [comment]
Changing to the latest Xcode version fixed the issue.
