### ISSUE TITLE
Error with new version of expo-cli

### ISSUE THREAD

**Issue by TheeAntoine** [expo/expo-cli#537]
I made the update of expo-cli but after it was impossible to do an "expo start", it's write expo-cli is not installed.

**Comment by AdamJNavarro** [comment]
Can you share the error message you're getting or provide a more detailed description of what is happening? Remember, the more information you provide the better we are equipped to help you out.

**Comment by TheeAntoine** [comment]
I tryed to uninstall everything to made a clean install and now I have a new error message : 

C:\Users\Antoine\MonAppli>expo start
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'C:\Users\Antoine\AppData\Roaming\npm\node_modules\expo\bin\cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by TheeAntoine** [comment]
I also tryed ton install on an other computer and I have an other error with the expo init : 

npm WARN deprecated core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/expo/react-native-maps.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Antoine\AppData\Roaming\npm-cache\_logs\2019-04-23T15_20_37_122Z-debug.log
npm exited with non-zero code: 1
Set EXPO_DEBUG=true in your env to view the stack trace.

**Comment by AdamJNavarro** [comment]
Can you share your `app.json` file for your project?

The issue you're encountering on the second computer is because you either do not have `git` installed or it is not properly configured in your `PATH`. https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

**Comment by TheeAntoine** [comment]
Here is my file app.json : 

{
  "expo": {
    "name": "Projettest",
    "slug": "AwesomeProject",
    "privacy": "public",
    "sdkVersion": "32.0.0",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    }
  }
}

I wil see for my other computer

**Comment by TheeAntoine** [comment]
So it's working on my other computer, it was Git ! 
Now the most important problem was on the first computer.

**Comment by TheeAntoine** [comment]
Ok now it's working on my first computer, I think npm crashed everytime I tryed to install !
