### ISSUE TITLE
Shortcut keys no longer work

### ISSUE THREAD

**Issue by JulianKingman** [expo/expo-cli#539]
## Description

Keyboard shortcuts (`d` for portal, `shift + r` to refresh cache) no longer work, after updating to 2.15.4 (I think it worked 1 - 2 patch versions ago).

## Expected Behavior

Pressing `shift + r` should restart expo and clear the cache, etc...

## Observed Behavior

Nothing, no keyboard interaction. I'm also periodically getting the following error, not sure if it's related:
```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onread (net.js:657:25)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

## Environment

```
 Expo CLI 2.15.4 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.2.1 - /usr/local/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.4 => 31.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
      react-navigation: ^2.18.2 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.15.4
```

Running on iOS simulator, latest OS (12?) and Xcode (10.2.1)

**Comment by macojaune** [comment]
Same behavior here, and my console logs, warnings or Redux-logger don't show up on the console anymore

**Comment by macojaune** [comment]
Oh okay just tried with a " --dev"  and it's working

**Comment by AdamJNavarro** [comment]
Hey @JulianKingman,

I'm running `2.15.4` and the keyboard shortcuts are working for me. Tested both `shift + r` and `d` and both produced the expected results.

**Comment by JulianKingman** [comment]
@AdamJNavarro huh, me too...
I double-checked that I was in dev mode, too, it's definitely not working. I tried `expo start --dev`, `expo start --no-dev`, changed from lan to tunnel mode, nada! Let me know how I can help debug.
<img width="682" alt="Screen Shot 2019-04-30 at 2 45 50 PM" src="https://user-images.githubusercontent.com/1566400/56995838-b684e400-6b57-11e9-8da6-2528591bbc68.png">

**Comment by JulianKingman** [comment]
Clue: it only happens in one project. I tried deleting the `.expo` folder, nothin...

**Comment by JulianKingman** [comment]
I tried deleting the whole project and pulling a fresh copy from github, no luck. @AdamJNavarro is there any configuration that would cause this?

Here's my config:
```
Expo CLI 2.19.4 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.2.1 - /usr/local/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^4.1.18 => 4.1.18 
      expo: ^31.0.4 => 31.0.6 
      react: ^16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
      react-navigation: ^2.18.2 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.19.4
```

**Comment by brentvatne** [comment]
the commands are intentionally disabled in expokit projects, `expo start` only starts the project server for expokit. aside from that you can use `react-native-cli` commands for things like building and running the app
