### ISSUE TITLE
Login trouble with 2FA on iOS Enterprise Account

### ISSUE THREAD

**Issue by sherbondy** [expo/expo-cli#54]
## Description

Hi there, I'm trying to do a new build of an expo project that I haven't touched in a while because the project's enterprise certificate is going to expire soon. I tried issuing a build for our enterprise iOS app using the following expo-cli command:

```
expo build:ios --apple-enterprise-account
```

My account is protected by 2FA. I manage to make it past the login prompt, and I even get to the two-factor auth prompt:

```
Your session cookie has been expired.
Please enter the 6 digit code: 
```

This is where things get funky. I receive the code on my phone and enter the 6-digit code into the CLI.
This seems to trigger *another* code to get sent as soon as I submit the value, and then the CLI indicates that the original login attempt failed:

```
Requesting session...

[13:40:17] Error while gathering & validating credentials
[13:40:17] Reason:Unknown reason, raw:"Unauthorized Access"
[13:40:17] Set EXPO_DEBUG=true in your env to view the stack trace.
```

Because of this, I get stuck and never manage to generate a new enterprise build. This happens regardless of whether I select to manage my own certificates manually or have Expo manage my certs for me.

## Expected Behavior

I expect to be able to login to my enterprise account using 2FA and trigger the build.

## Environment

This project is using an older version of the Expo SDK, but I think it shouldn't matter, as the underlying issue seems to be with the CLI's login process:

```
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.9.0
  Yarn: 1.3.2
  npm: 6.4.1
  Watchman: Not Found
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^21.0.0 => 21.0.2
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz => 0.48.4
```

Thanks, hope I can help get this sorted out somehow. 

Maybe there's an issue with a downstream dependency or a recent change to Apple's developer portal endpoints following the release of iOS 12?

**Comment by emrahtoy** [comment]
Same happening here to ( normal account i assume )

`Expo CLI 2.11.6 environment info:
    System:
      OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.15.1 - /usr/bin/node
      Yarn: 1.13.0 - /mnt/c/Program Files (x86)/Yarn/bin/yarn
      npm: 6.8.0 - /usr/bin/npm
    npmPackages:
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.0.9 => 3.3.2
    npmGlobalPackages:
      expo-cli: 2.11.6`

**Comment by philyboysmith** [comment]
I've just encountered the same issues. When I logged into iTunes connect I had some new agreements to review. Once I reviewed them, the above error went away.

**Comment by erwinwahyura** [comment]
i have the same issues

**Comment by brentvatne** [comment]
> I've just encountered the same issues. When I logged into iTunes connect I had some new agreements to review. Once I reviewed them, the above error went away.

it seems like this is a likely cause for the original issue, we should handle the error better, assuming apple api gives us enough information to do so. PR to help with this would be great

**Comment by BenjaminWFox** [comment]
Cross-referencing another solution. Additional agreements weren't my problem, but I found this issue first while searching for a solution, and this it's also linked from a forum post (which is now closed for replies) that was high up in the search results for Unauthorized Access related to expo.

https://github.com/expo/expo-cli/issues/664#issuecomment-592545033

**Comment by MitchK** [comment]
Hi, I have the same issue! I tried signing in with my password + 2FA, and also with app specific password.

- No agreements pending
- Apple account is associated with my MacBook, but I'm not getting any notifications there.

With regular password + 2FA:
```
Authentication with Apple Developer Portal failed!
Reason: Unknown reason, raw: "Unauthorized Access"
Error: Reason: Unknown reason, raw: "Unauthorized Access"
    at runAction (/expo-cli@3.16.1/src/appleApi/fastlane.ts:28:17)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at authenticate (/expo-cli@3.16.1/src/appleApi/authenticate.ts:48:40)
    at Context.ensureAppleCtx (/expo-cli@3.16.1/src/credentials/context.ts:56:24)
    at IOSBuilder.bestEffortAppleCtx (/expo-cli@3.16.1/src/commands/build/ios/IOSBuilder.ts:99:14)
    at IOSBuilder.prepareCredentials (/expo-cli@3.16.1/src/commands/build/ios/IOSBuilder.ts:116:5)
    at IOSBuilder.run (/expo-cli@3.16.1/src/commands/build/ios/IOSBuilder.ts:46:7)
    at IOSBuilder.command (/expo-cli@3.16.1/src/commands/build/BaseBuilder.ts:29:7)
    at Command.<anonymous> (/expo-cli@3.16.1/src/exp.ts:85:7)
```

With app specific PW:
```
Authentication with Apple Developer Portal failed!
Reason: Invalid credentials, raw: "Invalid username and password combination. Used 'myappleid@domain.tld' as the username."
Error: Reason: Invalid credentials, raw: "Invalid username and password combination. Used 'myappleid@domain.tld' as the username."
    at runAction (/expo-cli@3.16.1/src/appleApi/fastlane.ts:28:17)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at authenticate (/expo-cli@3.16.1/src/appleApi/authenticate.ts:48:40)
    at Context.ensureAppleCtx (/expo-cli@3.16.1/src/credentials/context.ts:56:24)
    at IOSBuilder.bestEffortAppleCtx (/expo-cli@3.16.1/src/commands/build/ios/IOSBuilder.ts:99:14)
    at IOSBuilder.prepareCredentials (/expo-cli@3.16.1/src/commands/build/ios/IOSBuilder.ts:116:5)
    at IOSBuilder.run (/expo-cli@3.16.1/src/commands/build/ios/IOSBuilder.ts:46:7)
    at IOSBuilder.command (/expo-cli@3.16.1/src/commands/build/BaseBuilder.ts:29:7)
    at Command.<anonymous> (/expo-cli@3.16.1/src/exp.ts:85:7)
```

System info:
```
  Expo CLI 3.16.1 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.15.0 - ~/.nvm/versions/node/v12.15.0/bin/node
      Yarn: 1.19.2 - ~/xxxxxx/node_modules/.bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.15.0/bin/npm
    IDEs:
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.1
      react: ^16.12.0 => 16.12.0
      react-native: ^0.61.5 => 0.61.5
```

**Comment by MitchK** [comment]
Found my problem! I was signin into my Apple ID on my Mac, but I didn't have iCloud enabled. Hence, I didn't receive the signin popups on my device (only the login codes via SMS).

**Comment by brentvatne** [comment]
as far as i know this is resolved, if you continue to experience this issue let me know in a new issue!
