### ISSUE TITLE
ECONNREFUSED 127... Connecting to Metro bundler failed. Set EXPO_DEBUG=true in your env to view the stack trace.

### ISSUE THREAD

**Issue by pixsolution** [expo/expo-cli#544]
Hello

I'm facing this issue in my MAC https://ibb.co/yNJNjV2

the strange thing is that when creating a new project with expo if it runs well (blank project) but then when I paste my code and try to run goes back to the same, but I still think it is something of the operating system, because I tried on a computer with windows 7 and it gave another error with the code, but in my mac gives me these errors that I do not understand, I attach details of my operating system https://ibb.co/NVWQQR3

I don’t know if it is something of my code but I doubt it, and of package I am only using firebase then my code in a zip (it is small / little what I have done): https://drive.google.com/file/d/1XLjh4BzcjXK1YS9KY1odeVGcoKrfn1lN/view?usp=sharing

I appreciate your help
regards

**Comment by AdamJNavarro** [comment]
Hey @pixsolution,

Can you try running `rm -rf .expo` to clear your local directory and see if that helps?

Cheers,
Adam
