### ISSUE TITLE
changelog entries per project (and/or at project top-level)

### ISSUE THREAD

**Issue by jonknapp** [expo/expo-cli#55]
## Description

I hope this doesn't come off demeaning as that's not the intention. This projects appears to move quickly and I think it could benefit from keeping a changelog. Expo-cli prompts users to update when ran, which is fine (and helpful), but I'm never sure what was added, changed, removed, etc.

It appears that multiple packages are published at the same time, so maybe having the changes higher up (root of the project?) would be better suited. If the changelog does exist and is in another location, linking to it from the different README files would be helpful.

## Expected Behavior

When commits are added to packages, make related entries into a changelog file to inform users about what is changing from release to release who may not be as familiar with the system or direction of changes.

If entries as part of commits are not enforced, having it as part of the publish process would still be helpful.

**Comment by jkhales** [comment]
Thanks, we have them here now: https://github.com/expo/expo-cli/blob/master/packages/expo-cli/CHANGELOG.md
