### ISSUE TITLE
[ web ] possible to access pathsToInclude in createBabelLoader?

### ISSUE THREAD

**Issue by chrisdrackett** [expo/expo-cli#560]
I'm running into a small issue when using expo for my web project. Our app is a mono repo and we have a couple packages in `node_modules` that need to be transpiled along with our app. I've been trying to get this working with a custom Webpack config but so far haven't had much luck. While looking at the code I noticed that createBabelLoader has a `pathsToInclude` option. If there was a way I could access this via a config it seems like I could save a lot of time. Is this planned? is there already a way to do this?

**Comment by ide** [comment]
I think this is the same as #556 -- fixing #556 would fix what this is trying to achieve -- so I'm closing this issue for now.

**Comment by cruzach** [comment]
Hi @chrisdrackett,

We want our Github to be reserved for actual issues, as this is more of a general question, I'm going to close it here and suggest you post over at the [Expo CLI forums](https://forums.expo.io/c/expo-cli).

Thanks for understanding!
Charlie
