### ISSUE TITLE
Zip end of central directory signature not found

### ISSUE THREAD

**Issue by levani** [expo/expo-cli#573]
# READ THIS FIRST, PLEASE!

We're looking to keep questions on our forums and bug reports on the GitHub repo -- please choose whichever you feel is more appropriate for your issue:

- Post in our community forums (log in with your Expo developer account): https://forums.expo.io/c/help
- File a bug on the Expo CLI repo (for bugs related to the Expo CLI tools): https://github.com/expo/expo-cli/issues/new
- File a bug on the main Expo repo (for other bugs): https://github.com/expo/expo/issues/new
- Request a feature on Canny: https://expo.canny.io/feature-requests

Thanks for reporting the issue you found with Expo CLI!

# Required format for issues

Please make our job easier by filling this template out to completion.

## Description

Getting error when running `expo upload:ios` from command line.

## Expected Behavior

This should work without error and upload the app the to the app store.

## Observed Behavior

Getting the following error message

```
> Failed to upload the standalone app to the app store.
> Zip end of central directory signature not found
> Error: Zip end of central directory signature not found
>     at _callee2$ (/expo-cli@2.16.1/src/commands/upload/utils.js:54:11)
>     at tryCatch (/Users/lm/.nvm/versions/node/v8.11.2/lib/node_modules/expo-cli/node_modules/regenerator-runtime/runtime.js:62:40)
>     at Generator.invoke [as _invoke] (/Users/lm/.nvm/versions/node/v8.11.2/lib/node_modules/expo-cli/node_modules/regenerator-runtime/runtime.js:296:22)
>     at Generator.prototype.(anonymous function) [as next] (/Users/lm/.nvm/versions/node/v8.11.2/lib/node_modules/expo-cli/node_modules/regenerator-runtime/runtime.js:114:21)
>     at step (/Users/lm/.nvm/versions/node/v8.11.2/lib/node_modules/expo-cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
>     at /Users/lm/.nvm/versions/node/v8.11.2/lib/node_modules/expo-cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)
```

This happens after a login to app store:

```
[00:13:18]: [DevCenter] App 'xxx.app' already exists, nothing to do on the Dev Center
[00:13:22]: App 'xxx.app' already exists (xxx), nothing to do on App Store Connect
Uploading the app to Testflight, hold tight...
[00:13:24]: Login to App Store Connect (xxx@gmail.com)
[00:13:27]: Login successful
Failed to upload the standalone app to the app store.
Zip end of central directory signature not found
Set EXPO_DEBUG=true in your env to view the stack trace.
```

## Environment

Expo CLI 2.16.1 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.2 - ~/.nvm/versions/node/v8.11.2/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v8.11.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.6 => 31.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz => 0.57.1
      react-navigation: 3.9.1 => 3.9.1
    npmGlobalPackages:
      expo-cli: 2.16.1

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by cruzach** [comment]
Hi @levani !

First- Expo requires you to use v10 or newer of Node, so I recommend updating ([source](https://docs.expo.io/versions/latest/introduction/installation/). 

Were you able to build the IPA for iOS without any problems?

-Charlie

**Comment by levani** [comment]
@cruzach 

I tried node 10.5 as well but getting the same error.

Yes building IPA works fine.

**Comment by michaelVictoriaDev** [comment]
I had the same error sdk 30 

node version: v11.10.1
expo-cli version: 2.13.0

**Comment by cruzach** [comment]
@levani, could you set `EXPO_DEBUG=true` in your env and share the entire stack trace?

Thanks!
-Charlie

**Comment by levani** [comment]
@cruzach 

I already did. The stack trace a posted above is what I get when setting `EXPO_DEBUG=true`.

**Comment by brij-dev** [comment]
@levani any progress ?

**Comment by michaelVictoriaDev** [comment]
Try the manual upload, you must create in developer.apple.com > developer.apple.com/account/ios/identifier/bundle > Identifiers > App IDs and create Register iOS App IDs 

then go to appstoreconnect.apple.com > my apps > add  new app, (make sure that you have eligible Bundle IDs for iOS apps and linked the created app IDs )
Try generate the .ipa by using 

> expo build:ios
it will generate the on your terminal and copy paste the result SKU on the appstoreconnect.apple.com

Now upload on the testflight  go to 
```
 xcode > open developer tool > application loader
then you can upload you ipa after the expo build:ios
```

wait for a minute to reflect the uploaded ipa on the appstoreconnect.apple.com go to myApps > the application that you created > Test Flight > iOS .

**Comment by levani** [comment]
@brij-dev 
on what?

@michaelVictoriaDev 
Yes, that's what I'm doing until this issue is fixed. Thanks for pointing out.

**Comment by wkozyra95** [comment]
Hi @levani 
I'm guessing that you ran `upload:ios` at some point in the past and stopped it while there was download in progress. It will be fixed soon, but if you need this working now all you need to do is to remove your projects ipa from /tmp directory.

**Comment by brentvatne** [comment]
@wkozyra95 - has this been resolved?
