### ISSUE TITLE
Your project must have a bundleIdentifier set in app.json.

### ISSUE THREAD

**Issue by michaelVictoriaDev** [expo/expo-cli#579]
I have the genarated bundleIdentifier in ios and already config on apple developer, when I creating `expo build:ios` the error says
`[11:17:14] Your project must have a bundleIdentifier set in app.json.
See https://docs.expo.io/versions/latest/guides/building-standalone-apps.htm`

i have the bundleIdentifier which I created in apple developer

```
{
  "expo": {
    "name": "prosperna",
    "description": "Everything you need to sell more real estate",
    "slug": "prosperna",
    "privacy": "public",
    "sdkVersion": "30.0.0",
    "version": "2.0.3",
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "icon": "./assets/icons/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "packagerOpts": {
      "assetExts": ["ttf", "mp4"]
    },
    "ios": {
      "bundleIdentifier": "com.test.test",
      "supportsTablet": true
    },
    "android": {
      "versionCode": 32,
      "package": "com.test.test",
      "config": {
        "googleSignIn": {
          "apiKey": "AIzaSSyADCLdzTBaRTkSurzEMtWGr",
          "certificateHash": "E3C2F31E0D060B49616998"
        }
      },
      "permissions": [
        "WAKE_LOCK"
      ]
    },
    "androidStatusBar" : {
      "backgroundColor" : "#3F71D7"
    }
  }
}
```

> expo version:  sdk 30

> Im are currently using expo-cli 2.9.0

**Comment by cruzach** [comment]
Hi @michaelVictoriaDev 

Do you have a second `ios` property anywhere in your `app.json` file? I've seen a forum post on the same issue, and this was the underlying cause ([source](https://forums.expo.io/t/error-on-ios-build-suggesting-bundleid-isnt-present/935/3)) 
I would also check to ensure you're running `expo build:ios` in the proper directory.

Finally, if none of that provides any solution- can you try running the same command on a new blank project with a bundleID set?

Thanks!
Charlie

**Comment by michaelVictoriaDev** [comment]
Hi @cruzach 

Actually the account in apple developer is fresh and no other application has been publish. that's why i dont have second property. I try to solve on my own way, by trying `exp build:ios` and there's no problem on it.

Then I dont do standaloneapp when `expo upload:ios` It also have a problem `Zip end of central directory signature not found`[#573](https://github.com/expo/expo-cli/issues/573#issuecomment-490345384). I try also solve the issue by using xcode > open developer tool > application loader
then you can upload you ipa after the `expo build:ios`

**Comment by cruzach** [comment]
So you're able to run `expo build:ios` with no issue? I'm a little confused about how this error crops up

It would clear up a lot of questions if you could provide a way for me to reproduce this on my end 😄

**Comment by michaelVictoriaDev** [comment]
@cruzach  sorry for the confusion, I replicate this bug when Im trying to use 

> expo build:ios

now I search what are the other method  then I try 

> exp build:ios
and now its started to build the project :)

**Comment by fson** [comment]
It sounds like this issue has been resolved, so I'm going to close it.

If you're still having issues with `expo build:ios` or anything else, please feel free to open a new issue or post to https://forums.expo.io, whichever is more appropriate.
