### ISSUE TITLE
optimizeAssets original files break Android build

### ISSUE THREAD

**Issue by JonnyBurger** [expo/expo-cli#581]
## Description

I optimized my assets using the new option to optimize images in Expo CLI.
I opted to keep the original assets, so it created a bunch of files like `android/app/src/main/res/mipmap-hdpi/dev_icon.orig.png`.

When making a Gradle build (I am using ExpoKit), it breaks and gives the following error:

```
/Users/jonnyburger/xxxxxxxx-app/android/app/src/main/res/mipmap-mdpi/dev_icon.orig.png: Error: '.' is not a valid file-based resource name character: File-based resource names must contain only lowercase a-z, 0-9, or underscore
```

## Expected Behavior

It should probably not append `.orig` but `_orig` instead

## Observed Behavior

It created some files that broke the gradle build

## Environment

```
  Expo CLI 2.17.0 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.15.2 - ~/.yarn/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.2 => 32.0.2
      @types/react: ^16.7.18 => 16.7.18
      @types/react-navigation: ^3.0.1 => 3.0.1
      expo: 32.0.6 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.0.9 => 3.0.9
    npmGlobalPackages:
      expo-cli: 2.17.0
```

**Comment by sergeichestakov** [comment]
Hey @JonnyBurger,

Super sorry about the inconvenience this caused. I published the changes associated with #583 so you should be able to install the latest version of `expo-cli` soon which should fix your problem (ios and android directories are now ignored).

Let me know if you run into any more issues with this and I'm happy to help.

Thanks,
Sergei

**Comment by JonnyBurger** [comment]
No problem! I think it's a very good idea to optimize the assets. 👍
I will surely run expo publish again soon in the next few days and should there be any problems I will file a new issue.

**Comment by zubair-mehboob** [comment]
I am having the same issue what should i do

**Comment by sergeichestakov** [comment]
Hey @zubair-mehboob, 

Have you tried updating to the latest `expo-cli` version by running `npm install --global expo-cli`? That should resolve the problem.

Thanks,
Sergei
