### ISSUE TITLE
Tunnel not working in docker environment

### ISSUE THREAD

**Issue by lucassardois** [expo/expo-cli#582]
### Environment

`expo diagnostics` returns an error:
```
Cannot read property '1' of null
TypeError: Cannot read property '1' of null
at a.run.then.e (/home/node/.npm-global/lib/node_modules/expo-cli/node_modules/envinfo/dist/envinfo.js:1:97131)
```
I'm trying to make tunnels work in a docker environment. LAN is working fine.
Ngrok is installed inside docker.

### Steps to Reproduce

Steps to reproduce the error:
Use this Dockerfile:
```
# We need nodejs for npm
FROM node:11.14.0-alpine

RUN deluser --remove-home node              && \
  addgroup -S testuser -g 1805              && \
  mkdir /home/testuser                      && \
  adduser -S -G testuser -u 1805 testuser   && \
  chown -R testuser:testuser /home/testuser

# Set the installation folder for global modules in npm
ENV NPM_CONFIG_PREFIX=/home/testuser/.npm-global
ENV PATH=$PATH:/home/testuser/.npm-global/bin

EXPOSE 19000 19001 19002

WORKDIR /home/testuser

RUN apk add --no-cache         \
  bash git python           && \
	rm -rf /var/lib/apt/lists/*

USER testuser

RUN npm i -g expo-cli
```

Build the docker image:
`docker build -t react-native-expo .`

Run the docker image:
`docker run --rm -p 19000:19000 -p 19001:19001 -p 19002:19002 -it react-native-expo bash`

Once started, run `expo start --tunnel`.

### Expected Behavior

The tunnel should start.

### Actual Behavior

The following message appear when trying to do `expo start --tunnel` or turning the tunnel option 'on' in the web interface:
Tunnel URL not found, falled back to LAN URL.

### Reproducible Demo

Here you can find a simple exemple of the problem:
[docker-expo.zip](https://github.com/expo/expo/files/3084008/docker-expo.zip)

**Comment by nicknovitski** [comment]
@loustak Your Dockerfile does not build for me. Neither does this simpler one:

```Dockerfile
FROM node:current-alpine

RUN apk add --update --no-cache \
            bash \
            git \
            python

RUN npm i -g expo-cli
```

```console
$ docker build .
# ...
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
```

Is there anything missing from your example?

**Comment by loustak** [comment]
@nicknovitski Ups. I updated the dockerfile in the first post it should now build. Sorry for the inconvenience.

**Comment by nicknovitski** [comment]
@cruzach The error in expo diagnostics is from the dependency we use to get system information, `envinfo`.  The version we currently depend on raises that error when run in alpine.  The newest version instead hangs forever.

@loustak What's your use case for alpine here?

**Comment by icarus44-zer0** [comment]
What is the status of this issue? Error is still reproducible. 
Updates to [@expo/ngrok](https://libraries.io/npm/@expo%2Fngrok) and [
node:lts-alpine](https://hub.docker.com/layers/node/library/node/lts-alpine/images/sha256-63266a0ed3c7c090e70d8bc21af85586024dd13f22a7fa30cfbac5c343836aa3?context=explore) have not resolved the issue. 

Is there a distro outside of alpine that does support this feature?

**Comment by nicknovitski** [comment]
> Is there a distro outside of alpine that does support this feature?

`expo start --tunnel` works as expected in the non-alpine node image, which I assume is debian-based.

**Comment by byCedric** [comment]
Closing as this likely is an issue with ngrok itself.

If you think this is an issue on our end, please open a new bug report on [github.com/expo/expo](https://github.com/expo/expo).
