### ISSUE TITLE
Can't install expo-cli

### ISSUE THREAD

**Issue by lordenas** [expo/expo-cli#590]
macos 10.14.4
node v10.12.0
Can't install expo cli

```
iMac-Sergej:~ sergejanohin$ sudo npm install -g expo-cli
Password:
npm WARN deprecated joi@14.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

> @expo/traveling-fastlane-darwin@1.9.3 preinstall /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin
> node platform.js

/usr/local/bin/expo -> /usr/local/lib/node_modules/expo-cli/bin/expo.js
/usr/local/bin/expo-cli -> /usr/local/lib/node_modules/expo-cli/bin/expo.js

> fsevents@1.2.9 install /usr/local/lib/node_modules/expo-cli/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.9 and node@10.12.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/local/lib/node_modules/expo-cli/node_modules/fsevents/lib' 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/expo-cli/node_modules/fsevents/build'
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/expo-cli/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/usr/local/lib/node_modules/expo-cli/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /usr/local/lib/node_modules/expo-cli/node_modules/fsevents
gyp ERR! node -v v10.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/expo-cli/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/usr/local/lib/node_modules/expo-cli/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/expo-cli/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Darwin 18.5.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/expo-cli/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/expo-cli/node_modules/fsevents
node-pre-gyp ERR! node -v v10.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/expo-cli/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/usr/local/lib/node_modules/expo-cli/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)

> iltorb@2.4.3 install /usr/local/lib/node_modules/expo-cli/node_modules/iltorb
> node ./scripts/install.js || node-gyp rebuild

WARN install EACCES: permission denied, access '/Users/sergejanohin/.npm'
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/expo-cli/node_modules/iltorb/build'
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/expo-cli/node_modules/iltorb
gyp ERR! node -v v10.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

> sharp@0.22.1 install /usr/local/lib/node_modules/expo-cli/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.4/libvips-8.7.4-darwin-x64.tar.gz
ERR! sharp EACCES: permission denied, open '/usr/local/lib/node_modules/expo-cli/node_modules/sharp/6038-libvips-8.7.4-darwin-x64.tar.gz'
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/page/install for required dependencies
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/expo-cli/node_modules/sharp/build'
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/expo-cli/node_modules/sharp
gyp ERR! node -v v10.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN ts-pnp@1.1.2 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/traveling-fastlane-linux@1.9.3 (node_modules/expo-cli/node_modules/@expo/traveling-fastlane-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/traveling-fastlane-linux@1.9.3: wanted {"os":"win32,linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-win32-x64@2.2.8-beta.1 (node_modules/expo-cli/node_modules/@expo/ngrok-bin-win32-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-win32-x64@2.2.8-beta.1: wanted {"os":"win32","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-win32-ia32@2.2.8-beta.1 (node_modules/expo-cli/node_modules/@expo/ngrok-bin-win32-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-win32-ia32@2.2.8-beta.1: wanted {"os":"win32","arch":"ia32"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-sunos-x64@2.2.8 (node_modules/expo-cli/node_modules/@expo/ngrok-bin-sunos-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-sunos-x64@2.2.8: wanted {"os":"sunos","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-linux-x64@2.2.8 (node_modules/expo-cli/node_modules/@expo/ngrok-bin-linux-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-linux-x64@2.2.8: wanted {"os":"linux","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-linux-ia32@2.2.8 (node_modules/expo-cli/node_modules/@expo/ngrok-bin-linux-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-linux-ia32@2.2.8: wanted {"os":"linux","arch":"ia32"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-linux-arm64@2.2.8 (node_modules/expo-cli/node_modules/@expo/ngrok-bin-linux-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-linux-arm64@2.2.8: wanted {"os":"linux","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-linux-arm@2.2.8 (node_modules/expo-cli/node_modules/@expo/ngrok-bin-linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-linux-arm@2.2.8: wanted {"os":"linux","arch":"arm"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-freebsd-x64@2.2.8 (node_modules/expo-cli/node_modules/@expo/ngrok-bin-freebsd-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-freebsd-x64@2.2.8: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-freebsd-ia32@2.2.8 (node_modules/expo-cli/node_modules/@expo/ngrok-bin-freebsd-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-freebsd-ia32@2.2.8: wanted {"os":"freebsd","arch":"ia32"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-darwin-ia32@2.2.8 (node_modules/expo-cli/node_modules/@expo/ngrok-bin-darwin-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-darwin-ia32@2.2.8: wanted {"os":"darwin","arch":"ia32"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/expo-cli/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: iltorb@2.4.3 (node_modules/expo-cli/node_modules/iltorb):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: iltorb@2.4.3 install: `node ./scripts/install.js || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.22.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sergejanohin/.npm/_logs/2019-05-08T11_58_15_854Z-debug.log

```

**Comment by audjassa** [comment]
This isn't really about permissions it's about sharp and its dependencies... I just encountered the issue so looking into it will post if find any

**Comment by audjassa** [comment]
this worked  found it on expo's forum :)  `sudo npm install --unsafe-perm -g expo-cli `

**Comment by daniellaera** [comment]
this worked for me
`sudo npm install --unsafe-perm -g expo-cli`

**Comment by cwltd** [comment]
For me only work "Manually change npm’s default directory" from https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally **AND** "npm install --unsafe-perm -g expo-cli" (without sudo)

nodejs -v
v10.15.3

npm -v
6.4.1

expo --version
2.17.2

cat /etc/issue
Debian GNU/Linux 9

cat /proc/version
Linux version 4.19.0-0.bpo.4-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)) #1 SMP Debian 4.19.28-2~bpo9+1 (2019-03-27)

**Comment by abch16** [comment]
sudo npm install --unsafe-perm -g expo-cli 
worked for me as well

**Comment by WhatMakesPeopleLazy** [comment]
as chinese developer, i use this command 
`sudo cnpm install expo-cli -g` 
it works fine
and this also worked for me
`sudo npm install --unsafe-perm -g expo-cli`

**Comment by christophe13012** [comment]
Hello,
npm install --unsafe-perm -g expo-cli doesn't work for me on windows, same error.
i'll try on my mac this evening

**Comment by ebertmi** [comment]
Complete uninstall and reinstall of node.js and npm did the trick for me on Win 10. Before I had tried to install expo I upgraded node to v10. Maybe this was causing the error.

**Comment by imrizwan** [comment]
After wasting almost 1 day, i resolved this issue, this error is due to sharp

If you are having issues during installation consider removing the directory C:\Users[user]\AppData\Roaming\npm-cache_libvips.

npm install -g sharp (The installation require python 2.7 on windows and path env configuration)

npm install -g expo-cli

**Comment by satyapriyaarya** [comment]
@imrizwan you didn't wast time. You actually invested your time, Like I am investing.
Cheers...

**Comment by DrKimpatrick** [comment]
This work `sudo npm install --unsafe-perm -g expo-cli` 
But when I try to create a project with `expo init project_name` I get this error
` bash: expo: command not found`

**Comment by dz-s** [comment]
@weekitmo thx worked for me

**Comment by BillyZeBlack13** [comment]
> Hello,
> npm install --unsafe-perm -g expo-cli doesn't work for me on windows, same error.
> i'll try on my mac this evening

Hi Christophe,
For Windows, try to turn off windows defender... I had the same probleme

**Comment by AnasMSN** [comment]
> Hello,
> npm install --unsafe-perm -g expo-cli doesn't work for me on windows, same error.
> i'll try on my mac this evening

Hi Christophe,
For windows, maybe this link can help:
https://stackoverflow.com/questions/56244800/how-to-fix-expo-cli-issus-on-windows-10

this solve my problem

**Comment by ashitagaur00** [comment]
> After spending almost 1 day, i resolved this issue, this error is due to sharp
> 
> If you are having issues during installation consider removing the directory C:\Users[user]\AppData\Roaming\npm-cache_libvips.
> 
> npm install -g sharp (The installation require python 2.7 on windows and path env configuration)
> 
> npm install -g expo-cli

Hii, I still have the same issue!

**Comment by Furqanameen** [comment]
thanks dear friends its working fine for me...............................

**Comment by trungmt** [comment]
@imrizwan It works well for me. Thank you!

**Comment by NeoAnoman** [comment]
Well if it's something about directory permission issues then there maybe an app or antivirus using that directory at the time and that's why you are unable to use it to install the expo-cli in my case it was adb.exe that was running in the background using that directory. So you can always use task manager to observe such suspicious apps in the background. Also if everything is fine then you can always try to switch windows defender or your antivirus off and try it again. Hope this helps somebody....

**Comment by NeoAnoman** [comment]
If there is permission denied then there is always possibility some other app might be using that directory.  
In my case it was adb.exe....  
you can always use task manager to observe suspicious apps  
If you get nothing suspicious then there is there is a chance that antivirus must be causing the problem... So you can give it a try and switch your antivirus and windows defender off and see if it solves the problem.  
I hope this information might be helpful to someone.

**Comment by sunilpatra27** [comment]
Instead of normal cmd try in node cmd :) worked for me.
And I guess your org. proxy or firewall is blocking your request

**Comment by hankfrinkel** [comment]
> This works `sudo npm install --unsafe-perm -g expo-cli`
> But when I try to create a project with `expo init project_name` I get this error
> ` bash: expo: command not found`

Try, it helps me.
$ cd /usr/local/bin/ 
$ sudo ln -s /usr/local/lib/node_modules/expo-cli/bin/expo.js expo

**Comment by shishir610** [comment]
+1 for 
`sudo` npm install --unsafe-perm -g expo-cli`

**Comment by shishir610** [comment]
+1 for 
`sudo npm install --unsafe-perm -g expo-cli`

**Comment by JJader** [comment]
this worked for me, thank u so much @audjassa !!!

https://github.com/expo/expo-cli/issues/590#issuecomment-492397062

**Comment by matcs06** [comment]
It's not recommended to use sudo with npm install, follow the steps from npmjs official docs instead :)

Make a directory for global installations:
mkdir ~/.npm-global

Configure npm to use the new directory path:
npm config set prefix '~/.npm-global'

Open or create a ~/.profile file and add this line:
export PATH=~/.npm-global/bin:$PATH

Back on the command line, update your system variables:
source ~/.profile

Then try to install it: 
npm install -g expo-cli

It worked for me, I tried yarn, it seems to be installed correctly but it wasn't recognizing the expo command on ubuntu terminal. I hope it helps!!

Reference: https://stackoverflow.com/questions/46058546/error-eacces-permission-denied-access-usr-lib-node-modules

**Comment by fson** [comment]
Here's the "official" npm documentation on the `EACCES: permission denied, access ...` issue: [Resolving EACCES permissions errors when installing packages globally](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally). Briefly, you can either:
* [Use a Node version manager to install Node.js and npm](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm#using-a-node-version-manager-to-install-nodejs-and-npm): re-install npm using a version manager. This will also allow you to more easily switch between different Node.js versions.
* [Manually change npm’s default directory](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally#manually-change-npms-default-directory) (**does not apply to Windows**):  you can configure npm to use a different directory that you have permissions to. (Also detailed in the https://github.com/expo/expo-cli/issues/590#issuecomment-555300846 above.)

Note that when npm is installed correctly, you should not have to use `sudo` or `--unsafe-perm` to install packages.

**Comment by bolshed** [comment]
> Open or create a ~/.profile file and add this line: ->> export PATH=~/.npm-global/bin:$PATH

Sorry, I don't get this step. Please explain how do I create bin:$PATH?

**Comment by mehedi481** [comment]
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! envsub@3.1.0 postinstall: `test -d .git && cp gitHookPrePush.sh .git/hooks/pre-push || true`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the envsub@3.1.0 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Mehedi Hasan\AppData\Roaming\npm-cache\_logs\2019-12-05T07_43_26_043Z-debug.log



Please help me ...not Working on my windows 10

**Comment by richjl44** [comment]
Run the scripts in Git Bash and it will work

**Comment by brentvatne** [comment]
there are several issues mentioned here and one of them should be resolved on 3.10.2. the issue was that `@expo/build-tools` was installing a library called `envsub` that would fail on windows 10 in powershell/cmd.exe, so we switched that to an optional dependency - you will still see that `envsub` failed to install but the installation of expo-cli should succeed. we're going to consider breaking `@expo/build-tools` and similar functionality into a separate cli tool to avoid issues like this in the future.

**Comment by giancarlogamarra** [comment]
I had to unistall expo cli first by running this command -> sudo npm -g uninstall expo-cli
Then restart my computer
Then execute this command sudo npm install --unsafe-perm -g expo-cli
and it worked

**Comment by ArkanRomanWork** [comment]
windows 10, nj 10.16.0

go here:
user/appdata/roaming/nvm/10.16.0/node_modules

find and delete 'expo-cli' folder.

in the console write 'npm install -unsafe-perm -g expo-cli'

it helps me

**Comment by shireefkhatab** [comment]
In my case, i deleted two files then everything worked.
the 2 files are in this path: C:\Users\{Username}\AppData\Roaming\npm
under the names 'expo.ps1' and 'expo-cli.ps1'
then run: 

    npm i -g expo-cli@3.5.0

Hope that helps.

**Comment by kushal9291** [comment]
I had the same issue with windows. What worked for me is using Command prompt instead of bash.

**Comment by umairsultan** [comment]
Just try to open Windows PowerShell run as administrator and then run this command line:
Set-ExecutionPolicy RemoteSigned

**Comment by cmcodes1** [comment]
`yarn global add expo-cli`

**Comment by NathanKoehler** [comment]
I don't know if some else mentioned it but after searching for days I finally fixed mine by going into resource monitor on windows and terminating adb.exe (android debug bridge). Credit to https://github.com/expo/expo-cli/issues/283.

**Comment by Akhilbisht12** [comment]
Hey, i am also trying to install expo cli on windows it is giving me this error.
![Screenshot (92)](https://user-images.githubusercontent.com/48013238/80447213-668d5880-8936-11ea-9eb0-018d7ec84058.png)

**Comment by OmiOrOp** [comment]
> Weird. It seems like it's an issue with how you have Node/NPM configured. Are you able to install other modules globally?
> 
> Also, you may be able to avoid the issue if you use npx to execute expo-cli commands without needing to download it: `npx expo init my-project`

Bro, You are right I was tried many times finally error solved.

thank you so much @crashspringfield

**Comment by prashantbhayani** [comment]
> sudo npm install --unsafe-perm -g expo-cli
> worked for me as well

**Comment by GnxR** [comment]
You need to upgrade npm this helps me
`npm install npm@latest -g`
after
`npm install -g expo-cli `
or
use yarn
`yarn global add expo-cli`

**Comment by unikuam** [comment]
For Windows 10, I found a solution which should work in any case. Just use the following command:
npm i -g --unsafe-perms --no-optional expo-cli

**Comment by rohan2734** [comment]
@unikuam  I have run the command ```  npm i -g --unsafe-perms --no-optional expo-cli ```  after ``` npm clean cache --force ```
but still shows an error. My OS is windows.
```
npm ERR! code EPERM
npm ERR! syscall unlink
npm ERR! path C:\Users\jagan\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\.xdl.DELETE\binaries\windows\adb\adb.exe
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\jagan\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\.xdl.DELETE\binaries\windows\adb\adb.exe'
npm ERR!  [OperationalError: EPERM: operation not permitted, unlink 'C:\Users\jagan\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\.xdl.DELETE\binaries\windows\adb\adb.exe'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, unlink 'C:\Users\jagan\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\.xdl.DELETE\binaries\windows\adb\adb.exe'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'unlink',
npm ERR!     path: 'C:\\Users\\jagan\\AppData\\Roaming\\npm\\node_modules\\expo-cli\\node_modules\\@expo\\.xdl.DELETE\\binaries\\windows\\adb\\adb.exe'
npm ERR!   },
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\Users\\jagan\\AppData\\Roaming\\npm\\node_modules\\expo-cli\\node_modules\\@expo\\.xdl.DELETE\\binaries\\windows\\adb\\adb.exe',
npm ERR!   parent: 'expo-cli'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jagan\AppData\Roaming\npm-cache\_logs\2020-08-28T05_51_17_922Z-debug.log
```
