### ISSUE TITLE
[release-channels] fix publish:rollback

### ISSUE THREAD

**Issue by quinlanj** [expo/expo-cli#596]
`publish:rollback` currently removes the rollback'ed entry from the publish logs, preventing new users from getting the entry. However, users who currently have the bad publish will continue to see it as the most recent publish and will not know to update with the last known good publish.

# more explanation
Current situation: 
- Consider a publish log that looks like this: `oldGoodPublish-> newBadPublish`.
- `publish:rollback` will remove `newBadPublish`, making the logs just contain `oldGoodPublish`.
- We’ll need to run `publish:set` at the end to make the logs look like `oldGoodPublish->newGoodPublish`

**Comment by derekstavis** [comment]
Thank you for opening up this one. I confirm this is a bug that I can reproduce on my side.

**Comment by YoshiYo** [comment]
I can reproduce too.

**Comment by quinlanj** [comment]
still need to land https://github.com/expo/expo-cli/pull/1707
