### ISSUE TITLE
[draft] Path to launching Expo Dev Tools

### ISSUE THREAD

**Issue by terribleben** [expo/expo-cli#6]
## 1. Gather team feedback

We are doing this now

- Jim: https://github.com/expo/expo-dev-tools/issues/3
- TC: https://github.com/expo/expo-dev-tools/issues/4
- Ben: https://github.com/expo/expo-dev-tools/issues/5
- Charlie: https://paper.dropbox.com/doc/Thoughts-on-expo-cli-DRaGx5YSHZuhpmkSGMPrc
... more that i am missing from this list
- Brent: #8, https://exponent-internal.slack.com/archives/C5ERY0TAR/p1526326116000341

## 2. Gather partner feedback

Share with a few partners who might be interested. We might just want to paste a canned message in most or all of our partner slack channels, saying "Hey this is an alpha version of a thing we're working on, and would love your feedback if you get a chance to try it."

Before moving to step 3...

- Resolve all blocking issues surfaced by the Expo team
- Respond to feedback brought up by partners (don't have to fix everything, or necessarily implement all their feedback. But try to incorporate any useful feedback we get)
- Make sure at least one person on the Expo team has tried this on Windows and done a stability pass

## 3. Announce more widely, don't set as default

- Post somewhere (slack? blog?) saying how to get the new dev tools. Clearly mark them as Beta
- Pick a public-facing date when we are going to switch over more fully
- Add a banner to XDE saying "XDE is deprecated and will stop receiving updates on this date"

Before moving to step 4...

- Resolve any blocking issues we hear from the community that we didn't catch before
- Figure out a specific migration path for how we plan to get everybody on the new workflow (from old exp, from XDE, from old CRNA)
- Wait until the predetermined "switch" date

## 4. Set as default

- Remove Beta label
- Change our website to show the default getting started steps as Expo Dev Tools
- Change our docs to show the default getting started steps as Expo Dev Tools
- Make the existing-XDE banner more aggressive, like "Hey we don't support this any more, use at own risk"
- Stop offering XDE for download

**Comment by fson** [comment]
Closing this issue as Expo CLI has already been launched!
