### ISSUE TITLE
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.

### ISSUE THREAD

**Issue by AcusioCEO** [expo/expo-cli#60]
## Description

I am trying to install expo-cli but when I run the installation command ( npm install expo-cli --global) I get this message: npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.

I'm not sure how to move forward because if I run expo init after that I get this error: -bash: expo: command not found 
which means it is not installing properly.

Also specify:

Running on macOS High Sierra Version 10.13.4

<img width="1280" alt="screen shot 2018-09-30 at 8 01 25 pm" src="https://user-images.githubusercontent.com/39605851/46267764-a3d7fd00-c4eb-11e8-9101-9723ce959d78.png">

**Comment by GuSoder** [comment]
I also get this warning, installing seems to work for me but I’m running into problems when signing into my account, no idea if related

**Comment by avcman** [comment]
I have exactly same problem. Running on Mac OS Mojave 10.14, node V8.12.0, npm v6.4.1

**Comment by SamaneYaghoobi** [comment]
that happens to me. this warning and a lot of warnings for 'tarball data'.
In Linux Mint x64

**Comment by LorenzoDyce** [comment]
I'm running on Mac OS Mojave 10.14, node V8.11.1, npm v6.4.1 and im almost having this issue as well.

**Comment by IanOstrom** [comment]
Same issue, Mac OS Mojave 10.14, node V8.12.0, npm v6.4.1

**Comment by Louie-Carvalho** [comment]
Same issue - Win7 64x, Node v8.12.0, npm v6.4.1.
@IanOstrom @avcman Did either of you resolve? Maybe with an earlier version of npm?

**Comment by Louie-Carvalho** [comment]
> Same issue - Win7 64x, Node v8.12.0, npm v6.4.1.
> @IanOstrom @avcman Did either of you resolve? Maybe with an earlier version of npm?

Sorry, to clarify what I mean...
The issue I had was that this error was crashing the installation; i.e. it'd lock up and wouldn't ever continue
I rolled npm back to 6.4.0 using npm-windows-upgrade, and tried again - error was still thrown but at least it continued this time

**Comment by IanOstrom** [comment]
I resolved the issue by using sudo to install. Same result for me. It threw
the error, but continued with the installation.

**Comment by LorenzoDyce** [comment]
I think this is a PATH issue because i don't have this issue on my MacBook, it's only happening on my iMac.

**Comment by fson** [comment]
The deprecated dependency has been removed in https://github.com/expo/expo-cli/commit/055207480ed5a44c0662399e230773d839f2da2a. Installing the latest version of Expo CLI with `npm install -g expo-cli` should no longer produce this deprecation warning.

**Comment by technoandroid** [comment]
try this command $sudo chmod 777 -R * && sudo npm install in your project directory
