### ISSUE TITLE
Error in Running Expo Error : (_xdl || _load_xdl(...)).Web.hasWebSupportAsync is not a function

### ISSUE THREAD

**Issue by veronicalw** [expo/expo-cli#600]
Hi guys! I'm new to React Native, and i want to build an App for my college project, So here's the thing. I've been installed the latest node.js , git , JDK for developing this app. I also did created the app in visual studio code. But I want to run the app to test if it's work or not. At first, the app runs well but in the middle of the process it shown an error like this, the result comes with unexpectedly stopped :

```
Starting Metro Bundler on port 19001.
Tunnel ready.
(_xdl || _load_xdl(...)).Web.hasWebSupportAsync is not a function
Set EXPO_DEBUG=true in your env to view the stack trace.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `expo start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Leony\AppData\Roaming\npm-cache\_logs\2019-05-09T15_55_38_121Z-debug.log
```

I have tried to update all the components also I've checked installed component on my laptop. So, what should I do to fix this ?
Thank you
#ReactNative #FailedRunnningExpo #3979 #4173 #npmstart #visualstudiocode #3659 #4173 #3659

**Comment by veronicalw** [comment]
Hi @cruzach, Thanks for your responses ... I've followed your suggestion in following the "Up and Running Guide" but stilll I can't fix my project. This is my environment 👍 
`┌─────────────────────────────────────────────────────────────┐
│                                                             │
│   There is a new version of expo-cli available (2.17.1).    │
│   You are currently using expo-cli 2.15.3                   │
│   Run `npm install -g expo-cli` to get the latest version   │
│                                                             │
└─────────────────────────────────────────────────────────────┘

  Expo CLI 2.15.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338`

What should I do next?
Thank you

**Comment by cruzach** [comment]
Just reproduced this on my end, actually. 

Fixed by upgrading to the most recent version of Expo CLI by running `npm install -g expo-cli`

Is there a reason you're using 2.15.3 instead?

**Comment by veronicalw** [comment]
Thank you so much for helping me @cruzach ! I've tried to upgrading the recent version of Expo CLI. And it's working in my case 😄 .
