### ISSUE TITLE
Windows 32 bit Installation problem

### ISSUE THREAD

**Issue by oron11** [expo/expo-cli#605]
I tried to install the expo cli with the following command:
npm install expo-cli --global

The command failed because of sharp installation.
I looked at sharp and for what I understood there is not support for 32 bit
However, I worked in expo just a year ago.

There is a way to use expo for windows 7, 32 bit currently?

**Comment by patiencendiligence** [comment]
I have the same issue. I'm running this on Windows 7 with 32 bit. 
I tried yarn global add expo-cli, but it's failed with the error "ERR! sharp Windows x86 <32-bit> node.exe is not supported."

**Comment by MatinSasan** [comment]
Would this link help? https://github.com/expo/expo/issues/1343  

The contributor himself told to use ```npm i -g exp``` instead.

**Comment by jkhales** [comment]
Closing as issues seems resolved.
