### ISSUE TITLE
[Something went wrong installing the "sharp" module] when running expo optimize

### ISSUE THREAD

**Issue by ZissiBa** [expo/expo-cli#606]
Iam trying to run expo optimize, but always run into this error:

`Something went wrong installing the "sharp" module
Cannot find module '../build/Release/sharp.node'
- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues`

At first, I checked if sharp even is installed but it wasn't. So I ran
`npm install sharp  --save`

The module '..build/Release/sharp.node' exists now, but I still get the same error.
I tried uninstalling all my modules and rerun npm install, but still the same error.
My package.json:

`{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject",
    "test": "node ./node_modules/jest/bin/jest.js --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/samples": "2.1.1",
    "axios": "^0.18.0",
    "expo": "^32.0.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-calendars": "^1.60.0",
    "react-native-elements": "^1.1.0",
    "react-native-htmlview": "^0.14.0",
    "react-native-map-link": "^2.4.0",
    "react-native-vector-icons": "^6.0.0",
    "react-navigation": "^3.0.9",
    "react-redux": "6.0.0",
    "redux": "^4.0.1",
    "redux-thunk": "^2.3.0",
    "sharp": "^0.22.1"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0",
    "jest-expo": "^32.0.0"
  },
  "private": true
}
`

Is there anything I miss? Do there exist any problems with sharp and some of the packages I use?

**Comment by AdamJNavarro** [comment]
Hey @ZissiBa,

Can you run `expo diagnostics` and paste the log that's printed out here?

Cheers,
Adam

**Comment by sergeichestakov** [comment]
Closed in https://github.com/lovell/sharp/issues/1696

**Comment by jasonchg86** [comment]
> Closed in [lovell/sharp#1696](https://github.com/lovell/sharp/issues/1696)

This issue seem not solve. I have tried sharp/issues/1696 but not working at all. Problem still exist.
![image](https://user-images.githubusercontent.com/7898351/66397306-12f50500-ea0e-11e9-8e0c-b0f8e78614b9.png)

**Comment by seniordev-rt96** [comment]
![image](https://user-images.githubusercontent.com/55588335/67164146-7aba3100-f3ba-11e9-9d56-2157fe9ca2f1.png)


"dependencies": {
    "bootstrap": "^4.3.1",
    "bootswatch": "^4.3.1",
    "classnames": "^2.2.6",
    "gatsby": "^2.16.5",
    "gatsby-cli": "^2.8.3",
    "gatsby-link": "^2.2.22",
    "gatsby-plugin-favicon": "^3.1.6",
    "gatsby-plugin-google-fonts": "0.0.4",
    "gatsby-plugin-netlify": "^2.0.17",
    "gatsby-plugin-netlify-cms": "^3.0.18",
    "gatsby-plugin-offline": "^2.2.10",
    "gatsby-plugin-react-helmet": "^3.1.13",
    "gatsby-plugin-sass": "^2.1.20",
    "gatsby-plugin-sharp": "^2.2.32",
    "gatsby-plugin-sitemap": "^2.2.19",
    "gatsby-remark-copy-linked-files": "^2.1.28",
    "gatsby-remark-images": "^3.1.28",
    "gatsby-remark-prismjs": "^3.2.11",
    "gatsby-remark-relative-images": "^0.2.3",
    "gatsby-source-filesystem": "^2.1.33",
    "gatsby-transformer-remark": "^2.3.12",
    "gatsby-transformer-sharp": "^2.2.23",
    "netlify-cms": "^2.9.1",
    "pixi.js": "^5.1.5",
    "prismjs": "^1.16.0",
    "react": "^16.10.2",
    "react-dom": "^16.10.2",
    "react-helmet": "^5.2.1",
    "react-icons": "^3.7.0",
    "react-iframe": "^1.8.0",
    "react-scroll-parallax": "^2.2.0",
    "react-slick": "^0.24.0",
    "react-tabs": "^3.0.0",
    "react-tilt": "^0.1.4",
    "reactstrap": "^7.1.0",
    "sharp": "^0.23.1",
    "slick-carousel": "^1.8.1"
  },
Help!!!

**Comment by ewein** [comment]
I'm having the same issue, uninstalling and reinstalling expo-cli doesn't fix it.

**Comment by seniordev-rt96** [comment]
> I'm having the same issue, uninstalling and reinstalling expo-cli doesn't fix it.

I got the error from Gatsby static site development.
I solved the issue. In my case, it doesn't related to expo-cli

**Comment by brentvatne** [comment]
sharp can be tricky to get working on some windows machines, so it's just an optional dependency now. we also moved the command to the `expo-optimize` package, so you can run `npx expo-optimize` to use it. you may want to look into the sharp issues to figure out how to get it running on your particular machine: https://github.com/lovell/sharp/issues. keep in mind that optimizing assets using this tool is not mandatory, you can use another similar tool if you can't get sharp installed on your machine. good luck, internet strangers!
