### ISSUE TITLE
I get an error "EACCES: permission denied, mkdir" in CircleCI.

### ISSUE THREAD

**Issue by ru88s** [expo/expo-cli#607]
## Description

When `sudo npm install -g expo-cli` is executed by CircleCI, the error `EACCES: permission denied, mkdir` occurs.

## Expected Behavior

I tried to run sudo npm install -g expo-cli on CircleCI.

## Observed Behavior

```
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/expo-cli/node_modules/iltorb/.node-gyp'
```
<img width="1224" alt="スクリーンショット 2019-05-13 12 47 40" src="https://user-images.githubusercontent.com/42270511/57595197-9523ef00-757e-11e9-99ea-b82ac9dd615b.png">

## Environment

My local project.

  Expo CLI 2.17.1 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.8.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4697961
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^2.18.2 => 2.18.2 
    npmGlobalPackages:
      expo-cli: 2.17.1

**Comment by ru88s** [comment]
Sorry, it is an addition.

Installation was successful if Expo CLI is 2.16.
So I thought 2.17 was suspicious.
Is there a relationship?

<img width="1477" alt="スクリーンショット 2019-05-13 13 35 25" src="https://user-images.githubusercontent.com/42270511/57596204-5abd5080-7584-11e9-98b5-380908e3dbe8.png">

**Comment by ru88s** [comment]
This is the current error.

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.22.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

<img width="1502" alt="スクリーンショット 2019-05-13 13 40 24" src="https://user-images.githubusercontent.com/42270511/57596274-c3a4c880-7584-11e9-94de-74cfc7e617f2.png">

**Comment by Wellers0n** [comment]
use `yarn` to install your package global `yarn global add expo-cli`, then do `expo init ProjectName`

**Comment by Wellers0n** [comment]
`yarn` resolve this problem

**Comment by sibelius** [comment]
use NVM to manage your node

**Comment by ru88s** [comment]
`sudo npm install --unsafe-perm -g expo-cli`

It moved now!
But I do not understand.
Thank you for your help.
