### ISSUE TITLE
[expo-cli] verify an App ID has Push Notifications service enabled prior to scheduling a build

### ISSUE THREAD

**Issue by dsokal** [expo/expo-cli#608]
_Related to https://forums.expo.io/t/missing-push-notification-entitlement-ios-build/21534_

When a user runs `expo build:ios` for the first time (or when some credentials are missing on Expo servers) we check whether the App ID exists on Apple Developer Portal. We should also verify that the App ID has Push Notifications service enabled and if it's not, we should exit with an error saying that a user has to do it manually. The other option is to ask the user for permission to enable it for him and for regenerating the provisioning profile.

**Comment by LouisJS** [comment]
I would very much need this, especially the provisioning profile regeneration. As someone who doesn't know much about mobile environnement, provisioning profile & certs are very confusing to me

**Comment by mccordgh** [comment]
Same here, I have a client that really wants to get a TestFlight build and I can't seem to get push notifications fully going in the standalone. They work great during dev :/

**Comment by dsokal** [comment]
@mccordgh actually this issue is not an issue (or a bug) but rather an improvement. It can't make it impossible to get push notifications working in the production app.

**Comment by mccordgh** [comment]
@dsokal Not sure what you mean "this issue is not an issue but rather an improvement"

I was able to get the standalone TestFlight push notifications working today by following the steps in this forum post: https://forums.expo.io/t/unable-to-get-expo-push-token-in-app-from-testflight/19106/7

It feels weird that I have to go in to the App ID, check "Push Notifications" so that they say "Configurable" and leave them that way. One would think they should have certs and be in the "Enabled" state, but when I did this before they didn't work. They are working with it just in the "Configurable" state.

**Comment by dsokal** [comment]
What I meant by that is this Github issue is not describing a problem which prevents users from successfully sending push notifications to their apps, so they are not blocked by anything if they know how to use Apple Developer Portal :)

The problem you're experiencing is caused by you creating the App ID on your own (prior to using Expo), so you took the risk of "being an expert of Apple certificates and stuff".

**Comment by mccordgh** [comment]
@dsokal ah, I see.

Well, I have changed my App's `bundleIdentifier` in app.json 3 times and let Expo handle the creation of the APP ID each time, and still had no success. The Push Notifications box was never checked until I manually went in, edited the App ID, and checked the box :/

**Comment by sakettawde** [comment]
Just for anyone coming here with less knowledge of the whole situation. Regarding the missing entitlement issue for push notification and push notifications not working in standalone iOS apps, you do not need to make changes to your app or app id (`bundleIdentifier`).

The solution to get push notifications working in a standalone build of iOS if you are asking Expo to handle the certificates:

Build ios standalone app with `expo build:ios`

Expo creates a distribution certificate (or you can choose one that was available from before)
Expo creates a identifier (if this is the first time you are building an app with this app id)
Expo creates provisioning profile
Expo generates Push Notifications Key

Note the terms: **Identifier** and **Provisioning Profile** (many get confused here)

Now do not use this standalone build.

Go to Apple Developer account -> Certificates, Identifiers & Profiles

Go to **Identifiers** -> Click on the one for your app

Scroll down and click on the checkbox next to push notifications

Scroll up and click on Save

Scroll down again and click on Configure/Edit in front of Push Notifications

Click on Create Certificate in front of Push Notifications and follow the instructions to create one for Production SSL Certificate

Once done, come back to the main screen and head over to **Profiles**

Click on the provisioning profile for your app id and remove/revoke it

Now build a new ios app with the following command: `expo build:ios --clear-provisioning-profile`

This will create a new Provisioning Profile for your app. Upload this build.

Note to expo team: if you can warn us at the time of app being built that the push notifications option is not selected for the current app identifier, it will be helpful.

**Comment by averdugo** [comment]
@sakettawde thanks for so clear answeer..

**Comment by maharjanaman** [comment]
@sakettawde do we do this manually `Click on Create Certificate for Production SSL Certificate` and more important, HOW?
Thank you for step-wise process.

**Comment by sakettawde** [comment]
> @sakettawde do we do this manually `Click on Create Certificate for Production SSL Certificate` and more important, HOW?
> Thank you for the step-wise process.

Yes manually. You need a mac.
Last I checked, they had written the process there. You generally use Keychain Access app.

**Comment by maharjanaman** [comment]
@sakettawde did that, followed your step, rebuild the app but still not getting notification. Even tried using https://expo.io/dashboard/notifications, everything gave out `OK`, but still no notifications. Have any idea what might be wrong?

**Comment by sakettawde** [comment]
As long as you are not getting the missing push entitlement message from Apple you should be good to go. So ensure you are not getting that message.

Probably check app permissions for notifications.
Nothing else comes to mind.

**Comment by maharjanaman** [comment]
Read somewhere that with each new builds, the previous expo token becomes invalid. Is that the case?

**Comment by sakettawde** [comment]
That cannot be the case, our expo app has many many users and we have released multiple builds, but not haven't requested our users to send a new token. Everything is working fine.

**Comment by maharjanaman** [comment]
Thanks @sakettawde, for responding.
