### ISSUE TITLE
.env files does not refresh on save, need to restart

### ISSUE THREAD

**Issue by iagorm** [expo/expo-cli#61]
## Description

When you use a .env file with ***react-native-dotenv***, it does not refresh the file with new data, a restart is needed.

## Expected Behavior

When .env file saved, it should be updated in app.

## Observed Behavior

The .env file variables does not update in app while using expo.

## Environment

Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.11.3
  Yarn: 1.9.4
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  expo: ^30.0.0 => 30.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/rebellion-2e21c6c7-7df4-442d-8115-bd2589e604cd.tar.gz

Devices tested:

* Nexus 5 API 26 (emulator device)
* Moto g6 (physical device)

**Comment by fson** [comment]
I have a question for you: Could you tell me what kind of variables are you storing in the `.env` file? For example, if you only need to store configuration variables used in your app, you could just create a JSON or JS file and import the configuration from there in your code. Whenever you change that file, your app will be refreshed without having to restart.
