### ISSUE TITLE
wrong behaviour when publish at non-interactive mode

### ISSUE THREAD

**Issue by blankonn** [expo/expo-cli#612]
## Description

I am trying to publish using the command ```expo-cli --non-interactive publish```, however, it is immediately failed because it directly jumps to ```publishing to channel 'Default'``` without starting expo-cli instance first.

## Expected Behavior

it should probably start the expo-cli instance before start publishing to the channel.

## Observed Behavior

```
expo-cli --non-interactive publish
[20:52:30] "--non-interactive" is not an expo command. See "expo --help" for the full list of commands.
[20:52:30] Publishing to channel 'default'...
[20:52:36] Building iOS bundle
[20:52:36] connect ECONNREFUSED 127.0.0.1:19001
[20:52:36] Set EXPO_DEBUG=true in your env to view the stack trace.
```

**Comment by fson** [comment]
Can you try `expo publish --non-interactive` (the flags should go after the subcommand (`publish`), not before.

**Comment by blankonn** [comment]
I tried that, still the same behaviour

**Comment by cruzach** [comment]
Hi @blankonn,

What version of the `expo-cli` are you using? I just ran `expo publish --non-interactive` on a local project in both version 2.17.1 & 2.17.2 and had no issue.

-Charlie

**Comment by blankonn** [comment]
I am using the latest version, 2.17.2

**Comment by blankonn** [comment]
the issue just resolved by itself. I just tried it without the ```--non-interactive``` flag, and then it prompted me about the optimization thing. And after that, it starts the instance first before publishing to the channel.

I tested it again using the ```--non-interactive``` flag afterward and there is no problem again.
