### ISSUE TITLE
I can not install here, Ubuntu 18.04.2

### ISSUE THREAD

**Issue by PauloMaiaDeveloper** [expo/expo-cli#613]
**Without this package I can not generate apps ...**

sudo su
[sudo] senha para rpmon: 
root@rpmon-Predator-G3-572:/home/rpmon# **npm install -g expo-cli**
npm WARN deprecated joi@14.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.

> @expo/traveling-fastlane-linux@1.9.4 preinstall /usr/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-linux
> node platform.js

/usr/bin/expo -> /usr/lib/node_modules/expo-cli/bin/expo.js
/usr/bin/expo-cli -> /usr/lib/node_modules/expo-cli/bin/expo.js

> iltorb@2.4.3 install /usr/lib/node_modules/expo-cli/node_modules/iltorb
> node ./scripts/install.js || node-gyp rebuild

WARN install EACCES: permission denied, access '/root/.npm'
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.15.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/expo-cli/node_modules/iltorb/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/expo-cli/node_modules/iltorb/.node-gyp'
gyp ERR! System Linux 4.18.0-18-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/expo-cli/node_modules/iltorb
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

> sharp@0.22.1 install /usr/lib/node_modules/expo-cli/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

ERR! sharp EACCES: permission denied, mkdir '/root/.npm'
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/page/install for required dependencies
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.15.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/expo-cli/node_modules/sharp/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/expo-cli/node_modules/sharp/.node-gyp'
gyp ERR! System Linux 4.18.0-18-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/expo-cli/node_modules/sharp
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN ts-pnp@1.1.2 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/traveling-fastlane-darwin@1.9.4 (node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/traveling-fastlane-darwin@1.9.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/expo-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-win32-x64@2.2.8-beta.1 (node_modules/expo-cli/node_modules/@expo/ngrok-bin-win32-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-win32-x64@2.2.8-beta.1: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-win32-ia32@2.2.8-beta.1 (node_modules/expo-cli/node_modules/@expo/ngrok-bin-win32-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-win32-ia32@2.2.8-beta.1: wanted {"os":"win32","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-sunos-x64@2.2.8 (node_modules/expo-cli/node_modules/@expo/ngrok-bin-sunos-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-sunos-x64@2.2.8: wanted {"os":"sunos","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-linux-ia32@2.2.8 (node_modules/expo-cli/node_modules/@expo/ngrok-bin-linux-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-linux-ia32@2.2.8: wanted {"os":"linux","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-linux-arm64@2.2.8 (node_modules/expo-cli/node_modules/@expo/ngrok-bin-linux-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-linux-arm64@2.2.8: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-linux-arm@2.2.8 (node_modules/expo-cli/node_modules/@expo/ngrok-bin-linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-linux-arm@2.2.8: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-freebsd-x64@2.2.8 (node_modules/expo-cli/node_modules/@expo/ngrok-bin-freebsd-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-freebsd-x64@2.2.8: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-freebsd-ia32@2.2.8 (node_modules/expo-cli/node_modules/@expo/ngrok-bin-freebsd-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-freebsd-ia32@2.2.8: wanted {"os":"freebsd","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-darwin-x64@2.2.8 (node_modules/expo-cli/node_modules/@expo/ngrok-bin-darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-darwin-x64@2.2.8: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-darwin-ia32@2.2.8 (node_modules/expo-cli/node_modules/@expo/ngrok-bin-darwin-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-darwin-ia32@2.2.8: wanted {"os":"darwin","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: iltorb@2.4.3 (node_modules/expo-cli/node_modules/iltorb):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: iltorb@2.4.3 install: `node ./scripts/install.js || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.22.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-14T19_43_36_095Z-debug.log

**Comment by baekkyoungjung** [comment]
same here 

someone please save me

**Comment by sergeichestakov** [comment]
Make sure you're not installing using `sudo` or root permissions. You should not have to do that with npm.

If that doesn't work go ahead and try [these instructions](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally). Let me know if you're still having issues after that.

**Comment by PauloMaiaDeveloper** [comment]
Steps ...

sudo apt-get remove nodejs

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash

export NVM_DIR="${XDG_CONFIG_HOME/:-$HOME/.}nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh --no-use"

nvm install node
nvm use --delete-prefix v11.9.0
npm install -g expo-cli


===  But with no success !

**Comment by PauloMaiaDeveloper** [comment]
As root I do not have access to ===

node -v
npm -v
nvm -v

Command 'XXX' not found

**Comment by sergeichestakov** [comment]
Yeah so if you've used `sudo` in the past that may have messed up your `node_modules` permissions which could be why you're getting an error as it expects you to have `sudo` permissions to install this package.

Did you try [this part](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally#manually-change-npms-default-directory) of the instructions? That might work better in this case.

Also please post the output of `expo diagnostics`. That will help us better understand your machine/environment.

**Comment by PauloMaiaDeveloper** [comment]
[Steps](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally#manually-change-npms-default-directory)

1 -
2 -
3 -
4 -

5 -rpmon@rpmon-Predator-G3-572:~$ source ~/.profile
nvm is not compatible with the npm config "prefix" option: currently set to "/home/rpmon/.npm-global"
Run `nvm use --delete-prefix v12.2.0 --silent` to unset it.

**Comment by sergeichestakov** [comment]
Please run `expo diagnostics` and post your output here.

**Comment by PauloMaiaDeveloper** [comment]
rpmon@rpmon-Predator-G3-572:~$ **expo diagnostics**

Command 'expo' not found, did you mean:

  command 'exp' from deb alliance
  command 'expn' from deb sendmail-base
  command 'expr' from deb coreutils

Try: sudo apt install <deb name>

**Comment by sergeichestakov** [comment]
Oh right, never mind. Which version of `node` and `npm` are you using?

Did you try running `nvm use --delete-prefix v12.2.0 --silent` like it says?

**Comment by PauloMaiaDeveloper** [comment]
node v12.2.0
npm 6.9.0

> Now step 5 has gone, I am about to complete the last step (6)

**Comment by PauloMaiaDeveloper** [comment]
6 - rpmon@rpmon-Predator-G3-572:~$ **npm install -g jshint**
/home/rpmon/.nvm/versions/node/v12.2.0/bin/jshint -> /home/rpmon/.nvm/versions/node/v12.2.0/lib/node_modules/jshint/bin/jshint
+ jshint@2.10.2
added 30 packages from 15 contributors in 4.104s


>>> FINISHED !

**Comment by PauloMaiaDeveloper** [comment]
Now **npm install -g expo-cli**

* Returned the same error! did not install.

**Comment by devbysb** [comment]
Hi I have the same issue

**Comment by sergeichestakov** [comment]
It seems lots of people are having issues installing the Sharp library, which we added as a dependency in a recent update and is causing updating `expo-cli` to break for some. Not sure what the root cause is, as it is likely dependent on your OS/machine but here are some general instructions for how to install Sharp: https://sharp.dimens.io/en/stable/install/

If none of those work, here are some SO responses which might help if you're on [Windows](https://stackoverflow.com/questions/47987435/can-not-install-sharp) or [Mac](https://stackoverflow.com/questions/46330275/error-installing-sharp-with-npm-on-macos) which involve installing additional missing dependencies.

Sorry for the inconvenience this is causing. Please let us know if any of those solutions or others work for you and we can try to incorporate those changes in an update to prevent this issue from occurring for others. We're looking into the root cause of this and if this problem persists for many people we will consider removing Sharp as a dependency entirely.

**Comment by cod3hunter** [comment]
Works for me on mac:
`chmod 777 /usr/local/lib/node_modules/`
`npm i -g expo-cli`

Obs: without adm permission.

**Comment by rochelryu** [comment]
sous Système Unix. Aussi.
Il faut que vous donner la permission a votre /usr/local/lib/node_modules/ puis après faire l'installation d'expo.
comme ce que a dit @cod3hunter dans son dernier resolve.

// Translate
under Unix System. As well.
You must give permission to your / usr / local / lib / node_modules / and then install the expo.
like what @ cod3hunter said in his last resolve.

**Comment by PauloMaiaDeveloper** [comment]
did not work !... @cod3hunter 

I do not have this way ... `/usr/local/lib/node_modules/`

Here is ...  `/usr/lib/node_modules/`

* So

`chmod 777 /usr/lib/node_modules/`
`npm i -g expo-cli`
....
.........
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.22.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rpmon/.npm/_logs/2019-05-24T19_23_34_661Z-debug.log

**Comment by cod3hunter** [comment]
try this: https://medium.com/@zameermfm/handling-libvip-sharp-errors-in-react-native-expo-installation-8eb592b6314b

**Comment by PauloMaiaDeveloper** [comment]
What worked was..:

Deleted >>>  /Users/<username>/.npm/_libvips/libvips-8.7.4-darwin-x64.tar.gz

Next, For safety removed expo-cli  , `npm uninstall expo-cli`

> npm i -g expo-cli
> ...
> ...........
> + expo-cli@2.18.3
> added 1433 packages from 920 contributors in 107.525s

**expo-cli --version
**2.18.3

Success 
It worked.


Thank you @cod3hunter 
And to all in general ... Thank you

**Comment by gouqilatiao** [comment]
It woks when I run
`sudo npm i expo-cli --unsafe-perm=true`

**Comment by vmandal** [comment]
Worked in CentOS 7:

[root] $ chmod -R 777 /usr/lib/node_modules/

[NON root] $npm install -g expo-cli

[NON root]$ expo-cli --version
2.18.7

**Comment by isaacdecoded** [comment]
> It woks when I run
> `sudo npm i expo-cli --unsafe-perm=true`

This works for me on Ubuntu 18.04 :) thanks

**Comment by arjunghimire** [comment]
> It woks when I run
> `sudo npm i expo-cli --unsafe-perm=true`
it works
Thank You

**Comment by romulo94** [comment]
> It woks when I run
> `sudo npm i expo-cli --unsafe-perm=true`

It's the solution. So... the issue is closed

**Comment by fson** [comment]
Closing as a duplicate of #591.
