### ISSUE TITLE
Support deprecating old versions of expo-cli

### ISSUE THREAD

**Issue by wkozyra95** [expo/expo-cli#619]
Support deprecating old cli versions based on the configuration in www.
expo-cli older than some specific version should be disabled and display info about the update.

**Comment by fson** [comment]
npm allows [deprecating packages](https://docs.npmjs.com/cli/deprecate) so no www configuration is necessary. I'm not sure if we should ever use that to disable the CLI, though. We could show a big warning (more prominent than the "there's a new version available" message), but if someone tries to still use it, I think they could do it at their own risk.

**Comment by wkozyra95** [comment]
I was thinking here about case where we are doing  large refactor(e.g. in www) want to drop support for old api, in that case almost all api calls would fail. I agree that disabling is a bit extreme, so maybe `--force` flag or confirmation prompt.

**Comment by wkozyra95** [comment]
#735
