### ISSUE TITLE
Link in expo build option is not working correctly

### ISSUE THREAD

**Issue by dzienisz** [expo/expo-cli#62]
## Description

Link in build option is not working correctly

## Expected Behavior

It should be clickable in all width

## Observed Behavior

![expo-cli](https://user-images.githubusercontent.com/3521624/46294863-0cc87f00-c597-11e8-9bd2-28a19658c870.png)

The link is stop being link after `@`.

## Environment

Expo CLI 2.2.0

## Reproducible Demo

Just run expo build:android

**Comment by fson** [comment]
`@` is a valid character in the path proportion of a URL, so this seems like a bug in the terminal emulator. Which terminal are you using?

Unfortunately there isn't much we can do about this. Maybe you can file a bug to the author of the terminal app? In some terminals (e.g. Terminal.app on macOS) you can also highlight the whole URL and then right click to select "open URL".
