### ISSUE TITLE
Create a build workflow that doesn't require Apple username/password if not needed

### ISSUE THREAD

**Issue by ide** [expo/expo-cli#620]
If we don't need the developer's Apple username & password, which are used locally to create provisioning profiles, distribution certificates, APNs keys, etc., then it would be a smoother workflow not to ask for the username & password.

These are some of the questions we need to first answer:
- When do we need the username & password?
- Are there cases where we need the username & password even if we are not creating new provisioning profiles, distribution certificates, APNs keys, etc.?
- Should we ask for the username & password lazily, the first time we need them? Or is there another flow that is smoother?
- How can we make it clear to developers when & why we are asking for their username & password?
- Separately: this might be a good time to add a link to this doc Brent wrote about credential security: https://docs.expo.io/versions/latest/distribution/security/

**Comment by quinlanj** [comment]
This is solved in https://github.com/expo/expo-cli/pull/1609 - At the beginning of credentials workflow, there is a prompt asking if you have apple username/password. We also explain why we need it and what we do with it. If a user has it, we can perform full validation of credentials, giving the best user experience. If not, then we perform best effort validation and do what we can.
