### ISSUE TITLE
Tidy up "Invalid sdkVersion" message

### ISSUE THREAD

**Issue by ide** [expo/expo-cli#623]
## Description

When running an UNVERSIONED project, Expo CLI prints an error like this:
```
Error: Invalid sdkVersion. Valid options are 10.0.0, 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0, 16.0.0, 17.0.0, 18.0.0, 19.0.0, 20.0.0, 21.0.0, 22.0.0, 23.0.0, 24.0.0, 25.0.0, 26.0.0, 27.0.0, 28.0.0, 29.0.0, 30.0.0, 31.0.0, 32.0.0, 7.0.0, 8.0.0, 9.0.0
```

## Expected Behavior

It would be nice to detect UNVERSIONED specifically and print a different warning. Also, the current error message lexicographically sorts SDK versions instead of sorting by semver and goes from smallest to greatest. I think it would be nice to show the most recent SDK versions first (32.0.0, 31.0.0, etc...) and make sure that we sort by semver.

## Reproducible Demo

Run `expo start` in the expo repo in one of the apps.

**Comment by EvanBacon** [comment]
Fixed
