### ISSUE TITLE
ECONNREFUSED error for every CLI command

### ISSUE THREAD

**Issue by boldham31** [expo/expo-cli#63]
## Description

Every time I attempt to run a CLI command, I get an ECONNREFUSED error. Based off of what I've learned from troubleshooting, it seems that Expo is attempting to tunnel through localhost:8888 and connect to the internet to download the "tabs" new project template. I suspect that the reason why the connection is being refused is potentially due to one of these two issues: 

- the configuration of my computer proxy settings 

I followed the directions [here](https://docs.expo.io/versions/latest/introduction/troubleshooting-proxies) to the best of my ability (on a PC instead of a Mac), and the issue remains. 

- Company firewall settings that prevent access to that specific port

Is there any kind of workaround for connecting the Expo CLI that changes how it accesses the internet?

Any help troubleshooting this issue is appreciated. I opened an issue on the Expo main repo [here](https://github.com/expo/expo/issues/2285) if that helps. Thanks.

## Expected Behavior

- expo init
Choose a project name: my-project
Choose a template: tabs

The expected behavior is for expo to tunnel through localhost:8888 and connect to the internet to download the project files.

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

![image](https://user-images.githubusercontent.com/17152030/46295964-e8e94700-c55e-11e8-859a-e4e2149d4c7d.png)

## Environment

![image](https://user-images.githubusercontent.com/17152030/46296256-8e9cb600-c55f-11e8-9428-f5f0b9325ee8.png)

Also specify:

N/A

## Reproducible Demo

N/A - I'm unable to even create the project due to this issue.

**Comment by MarjaanAhmadi** [comment]
Write "exp start" in another window

**Comment by ccheever** [comment]
Here is what this looks like now, if you try to `expo init` without an Internet connection.

![image](https://user-images.githubusercontent.com/56719/71848400-3ae31b80-3084-11ea-82ca-91fc2a741582.png)

Maybe we could make it clearer and say something like what Chrome does?
![image](https://user-images.githubusercontent.com/56719/71848478-6960f680-3084-11ea-90e1-efa631394908.png)
