### ISSUE TITLE
cannot install expo in windows 10 -  error Unexpected end of JSON

### ISSUE THREAD

**Issue by wesyoda** [expo/expo-cli#634]
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
**error Unexpected end of JSON input while parsing near '..."^11.2.1","rimraf":"^'**

Full log here
[2019-05-20T08_32_09_858Z-debug.log](https://github.com/expo/expo-cli/files/3197016/2019-05-20T08_32_09_858Z-debug.log)

**Comment by cruzach** [comment]
Hi @wesyoda,

Thanks for providing the log, but we need all the information we ask for in the issue template to help you out, and root out if there are bugs that need fixing. If you could follow the template, we'd really appreciate it!

Thanks,
Charlie

**Comment by wesyoda** [comment]
First time installing Expo on Windows 10 using CMD, while it is downloading, error message shows up.

typed this in the CMD:  npm install -g expo-cli

Full error log:
[2019-05-20T08_32_09_858Z-debug (1).log](https://github.com/expo/expo-cli/files/3200552/2019-05-20T08_32_09_858Z-debug.1.log)

cannot run "expo diagnostics" because it is not installed yet.
