### ISSUE TITLE
Path not properly set on MacOS

### ISSUE THREAD

**Issue by AdamJNavarro** [expo/expo-cli#637]
`~/.expo/PATH` is not set on MacOS in some circumstances. A [previous issue](https://github.com/expo/expo/issues/417) was opened years ago and the solution was to run `exp path` but that command is no longer present in the `expo` cli. Another recent report from the aforementioned issue is that expo cli actually creates a `PATH` file despite the cli outputting a string saying the command is not available.

**Comment by brahimbouine** [comment]
same here

**Comment by chakrihacker** [comment]
Any update??

**Comment by chakrihacker** [comment]
Hi, when I moved from homebrew node to nvm node, everything is working fine. I think it's some problem with homebrew node
