### ISSUE TITLE
cannot install expo in windows 10 - npm ERR! code ENOENT npm ERR! errno -4058 npm ERR! syscall chmod

### ISSUE THREAD

**Issue by knightkhan** [expo/expo-cli#638]
Any solution of its
npm ERR! path C:\Windows\system32\node_modules\expo-cli\node_modules\miller-rabin\bin\miller-rabin
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Windows\system32\node_modules\expo-cli\node_modules\miller-rabin\bin\miller-rabin'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\n_s_k\AppData\Roaming\npm-cache\_logs\2019-05-21T01_57_58_111Z-debug.log

**Comment by knightkhan** [comment]
Log of above mention error
[2019-05-21T01_57_58_111Z-debug.log](https://github.com/expo/expo-cli/files/3200453/2019-05-21T01_57_58_111Z-debug.log)

**Comment by cruzach** [comment]
Continuing the conversation [here](https://forums.expo.io/t/cannot-install-expo-in-windows-10-npm-err-code-enoent-npm-err-errno-4058-npm-err-syscall-chmod/22954) on our Forums, as this doesn't seem to be a bug with Expo CLI
