### ISSUE TITLE
ERR! sharp windows x86 (32-bit) node.exe is not support

### ISSUE THREAD

**Issue by javadm098** [expo/expo-cli#641]
Hi, my friends, I want to install {{{{{ npm install -g expo-cli }}}} but I encounter these errors

ERR!     windows x86 (32-bit) node.exe is not support
And more errors later on

I use Windows 8.1

npm install -g node-gyp
npm install —global —production windows-build-tools

![expo error](https://user-images.githubusercontent.com/32595052/58159066-97e2ac00-7c30-11e9-9323-517619b35c07.png)

**Comment by dvaJi** [comment]
Its because Sharp only support 64-bit (x64) node.exe.
https://sharp.dimens.io/en/stable/install/#windows-x64

**Comment by javadm098** [comment]
Thank you dvaJi
