### ISSUE TITLE
Eject with lerna monorepo

### ISSUE THREAD

**Issue by rodrigorm** [expo/expo-cli#648]
## Description

`expo eject` commands does not complete on an Lerna managed monorepo when it tries to install new dependencies.

## Expected Behavior

When I run `expo eject` I expect to Expo to correct eject my application.

## Observed Behavior

The eject command stop in a incorrect state with errors when installing new dependencies.

If there's an error message, please paste the _full terminal output and error message_ in this code block:

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@zaxapp%2fapollo-client: Not found".
yarnpkg exited with non-zero code: 1
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

```
  Expo CLI 2.15.4 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.0.3 - /usr/local/bin/bash
    Binaries:
      Node: 11.13.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.15.4
```

Also specify:

- iPhone XR 12.3

**Comment by brentvatne** [comment]
i don't imagine that this is specific to expo-cli, ejecting doesn't do anything interesting beyond running `yarn install`. sorry that we never got back to you on this, i hope it worked out!

**Comment by rodrigorm** [comment]
I understand there is not a specific thing about expo, but with Lerna all
the install/remove commands need to be run through its commands eg: `lerna
add react-native-elements packages/expo-app`. This is needed because Lerna
rewrite package.json files to remove local interdependencies between local
packages. I will try to create a repo wich reproduce the problem.

Em sáb, 7 de dez de 2019 às 22:40, Brent Vatne <notifications@github.com>
escreveu:

**Comment by brentvatne** [comment]
a proposal for how we can solve this would be great too!
