### ISSUE TITLE
Add support for custom templates

### ISSUE THREAD

**Issue by fson** [expo/expo-cli#65]
## Description

Support more templates in addition to the ones included by default. For example 
https://github.com/mathieudutour/create-react-native-app-typescript

see https://github.com/react-native-community/discussions-and-proposals/issues/23#issuecomment-425636736

**Comment by adammenges** [comment]
Even just adding a typescript based default template would be awesome. Related: https://github.com/expo/expo/issues/2336

**Comment by fson** [comment]
We actually support custom templates now. You can pass a name of the template package:
```
expo init --template <npm-package-name>
```
and the contents of that package will be used as a template.
