### ISSUE TITLE
Loading Spinner Stuck on refreshing 

### ISSUE THREAD

**Issue by rajatrao777** [expo/expo-cli#659]
## Description
Forever Loading Spinner stuck in expo mobile app,while selecting refresh from top dropdown menu.
## Expected Behaviour

What action did you perform, and what did you expect to happen?

1.Wrote a line of code in crna default app.
2.As Usual it updated the screen after downloading the js bundle displaying new changes
3.Now pressing back and again selecting same LAN network displayed same view (as there were no changes.) without downloading js bundle
4.Now refreshing from dropdown menu of expo in mob shows forever circle loading spinner, pressing back won't help.
5.Only solution seemed clear cache and start again

Expected behaviour
-After refresh again show same view as there are no changes without infinite loading spinner

## Observed Behaviour

What actually happened when you performed the above actions?

-Displayed infinite loading spinner, didn't help pressing back button...seemed to clear cache and 
started app again helped

## Environment

Expo CLI 2.18.4 environment info:
    System:
      OS: Linux 4.15 Ubuntu 16.04.6 LTS (Xenial Xerus)
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 8.9.4 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      expo-cli: 2.18.4

- Phone
  Redmi Note 4
  Android N

## Reproducible Demo

Can be reproduced as per mentioned in expected behaviour points.
Let me know if needed any help in reproducing the issue again.

**Comment by cruzach** [comment]
Hey @rajatrao777 ,

Just to clarify- this happened with a normal `expo init` project? I tried to repro it on my end and wasn't able to get the behavior you experienced. 

Try setting `EXPO_DEBUG=true` and see if anything comes up in the logs that might help you dig deeper

-Charlie

**Comment by rajatrao777** [comment]
Hi @cruzach 

-Yes it was in a normal expo init project
-Tried setting EXPO_DEBUG=true didn't find any abnormal logs.
-Did you tried with the same version listed above in my environment.
This issue is not produced everytime but it surely does..:(

**Comment by cruzach** [comment]
Yes same version, but one difference is that you are running on Node v8.9.4, and we actually suggest v10 or newer in our [Installation Docs](https://docs.expo.io/versions/latest/introduction/installation/#local-development-tool-expo-cli). That upgrade may be worth a try

**Comment by rajatrao777** [comment]
I did install node v8.10.0 still the same issue..right now i can handle with it ..but i think if possible please look into it..u can close the issue.
Thanks.
