### ISSUE TITLE
throw new Error('expo-cli supports Node versions 8.x.x, 10.x.x and newer.');

### ISSUE THREAD

**Issue by StudyTae** [expo/expo-cli#661]
### Please note that Expo CLI issues opened in the core Expo repository will be closed.

I was writing version 2.15.3. However, the update was posted and I'm update to 'expo-cli@2.18.5'.

But it causes an error.

```
.nvm/versions/node/v9.4.0/lib/node_modules/expo-cli/bin/expo.js:12
  throw new Error('expo-cli supports Node versions 8.x.x, 10.x.x and newer.');
  ^

Error: expo-cli supports Node versions 8.x.x, 10.x.x and newer.
    at Object.<anonymous> (/Users/.nvm/versions/node/v9.4.0/lib/node_modules/expo-cli/bin/expo.js:12:9)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
```

How can you solve this problem?

**Comment by cruzach** [comment]
This doesn't seem to be an issue, as the error message states that Node v8 **or** >= v10 must be used, and you were using v9.

Sidenote for @fson - should I change the [Installation Docs](https://docs.expo.io/versions/latest/introduction/installation/#local-development-tool-expo-cli) to include Node v8? I wasn't aware v8 was supported

**Comment by fson** [comment]
Right now we support Node [**Maintenance LTS** and **Active LTS** versions](https://github.com/nodejs/Release#release-schedule), currently these correspond to 8.x and 10.x, respectively. We will also support the **Current Release** version (12.x).

I will clarify the message printed by the command, as 11.x won't be supported after after its end of life on 1st of June either.

@cruzach you could update the installation page, but perhaps leave a note that we 10.x is the *recommended* version.

**Comment by cruzach** [comment]
Sounds good, thanks for clarifying!
