### ISSUE TITLE
Expo command is not fount ubuntu

### ISSUE THREAD

**Issue by Rapprogtrain** [expo/expo-cli#662]
Hi. 
I have installed expo with this command - npm install expo-cli -g
but when i am writing expo in command line, is writing that expo in not found.
I have tried to install with yarn and it was installed successful but is writing that expo in not found.
I have tried to export PATH to ~/.profile but this did not help me
What i need to do to make my expo project?

**Comment by aburayyanjeffry** [comment]
try this 

updatedb
locate expo-cli
