### ISSUE TITLE
 Expo command is not found ubuntu 

### ISSUE THREAD

**Issue by Rapprogtrain** [expo/expo-cli#663]
Hi.
I have installed expo with this command - npm install expo-cli -g
but when i am writing expo in command line, is writing that expo in not found.
I have tried to install with yarn and it was installed successful but is writing that expo in not found.
I have tried to export PATH to ~/.profile but this did not help me
What i need to do to make my expo project?

**Comment by fson** [comment]
Run `npm bin --global` to find out where npm installs global executable. Add **that** path to your `PATH` environment variable, by adding a line in your `.profile`/`.bash_profile`/`.zprofile` or similar, depending on which shell you use (you can find out what is your default shell using `echo $SHELL`).

Example (add this to your `.profile`/`.bash_profile`/`.zprofile`:
```
export PATH=$PATH:/home/Rapprogtrain/bin
#           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ change to the path returned by "npm bin --global"!

```

If this doesn't help, please let me know what gets printed by these commands:
```
npm ls expo-cli --global
npm bin --global
echo $PATH
```

**Comment by Rapprogtrain** [comment]
I have done all that you said and it is working but until that moment when command line is open. When i close my command line i need one more time do this - export PATH=$PATH:/home/Rapprogtrain/bin

**Comment by RaeWilliams19** [comment]
Hi, I'm having the same issue. When I do` npm bin --global` I get 

 /usr/local/lib/node_modules/bin
 (not in PATH env variable)

I'm not sure what this means..?

echo $PATH returns /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by fson** [comment]
Hey, this means that you need to add it in your `.bash_profile` or `.bashrc` so that it's automatically run every time you open your command line shell.

**Comment by ccheever** [comment]
Seems like the way to fix this is  to fix the user's PATH env var and so there's nothing else to address here.
Closing this out.

**Comment by XeraFiuYTB** [comment]
Hello, 'npm bin --global' give me (not in PATH env variable) and echo $PATH give $PATH, can you help me ?

**Comment by Tianyu9748** [comment]
npm bin --global returns that
/home/rest_user/.nvm/versions/node/v14.3.0/bin

echo $PATh returns that
/home/rest_user/.nvm/versions/node/v14.3.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

But still return expo not found

**Comment by fwdevin** [comment]
I'm seeing the same issue on Ubuntu:

╰─❯ npm bin -g
/usr/local/bin

╰─❯ npm ls expo-cli -g
/usr/local/lib
└── expo-cli@3.22.3 

╰─❯ echo $PATH
/usr/local/lib:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

╰─❯ cd /usr/local/bin
╰─❯ l
total 8.0K
drwxr-xr-x  2 root root 4.0K Apr 23 02:32 .
drwxr-xr-x 10 root root 4.0K Apr 23 02:32 ..

I see expo.js in /usr/local/lib/node_modules/expo-cli/bin, and I can run expo commands like:

╰─❯ ./expo.js --version
3.22.3

But the expo command doesn't work.

**Comment by fwdevin** [comment]
As a workaround I have an alias:

alias expo="/usr/local/lib/node_modules/expo-cli/bin/expo.js"

**Comment by jonasbraga** [comment]
I've the same issue in my ubuntu, what happened was that the expo-cli package needed super user permissions to make changes to the bin folder and files.
Just installing expo-cli with sudo works for me:

`sudo npm install expo-cli --global`

**Comment by devmicaelyg** [comment]
> Eu tenho o mesmo problema no meu Ubuntu, o que aconteceu foi que o pacote expo-cli precisava de permissões de superusuário para fazer alterações na pasta bin e nos arquivos.
> Apenas instalar o expo-cli com sudo funciona para mim:
> 
> `sudo npm install expo-cli --global`

Acabei de instalar dessa forma no meu Ubuntu e não resolveu. Nem sei o que fazer :(

**Comment by Tianyu9748** [comment]
> I've the same issue in my ubuntu, what happened was that the expo-cli package needed super user permissions to make changes to the bin folder and files.
> Just installing expo-cli with sudo works for me:
> sudo npm install expo-cli --global

I fixed it by install it again with npm. First time I installed it by yarn. Later after I use npm this command it works.

**Comment by JonEsparaz** [comment]
I was having this issue on a fresh Pop!_OS install. For those still having trouble, if you install node/npm via [nvm](https://github.com/nvm-sh/nvm) instead of apt, you should be able to run `npm install -g expo-cli` and use `expo` as a command. Using nvm provides the correct configuration and permissions.

**Comment by DiegoMMF** [comment]
expo init react-native-app didn't work
sudo expo init react-native-app didn't work
and neither worked installing expo-cli globally

This worked for me:
$ npx expo init react-native-app

**Comment by nrrahul4** [comment]
npx expo init react-native-app worked for me

**Comment by silnose** [comment]
Same npx expo init <app_name> works for me!

**Comment by neel-thakker** [comment]
> npx expo init react-native-app worked for me

Thanks a lot bhai , This worked for me . I was trying to download expo-cli with "sudo npm i -g expo-cli" , but was getting an error that "Unexpected end of JSON ....." -- solution to this on stackoverflow was to run "npm cache clean --force" but i was still getting that same error. Then i decided to download expo-cli package locally in my folder with 'npm i expo-cli'. It took about 27 minutes. 
But then when i run "expo init native-app", terminal was saying that command not found . I added some locations in my $PATH but still nothing worked . 
Finally using "npx expo init <app_name>" worked . Can you explain what difference did it make adding "npx" in the beggining ?

**Comment by BhyattCoastal** [comment]
Running a fresh install of Kubuntu 20.04, (12/2020) nothing seemed to get expo to work. Until i finely came across this thread. 

sudo -i 

npx expo init react-native-app

brian@Kubuntu:~$ sudo -i
[sudo] password for brian: 
root@Kubuntu:~# npx expo init react-native-app
This command requires Expo CLI.
Do you want to install it globally [Y/n]? y

Installing the package 'expo-cli'...
Expo CLI installed. You can run `expo --help` for instructions.
? Choose a template: › - Use arrow-keys. Return to submit.
    ----- Managed workflow -----
❯   blank                 a minimal app as clean as an empty canvas
    blank (TypeScript)    same as blank but with TypeScript configuration
    tabs (TypeScript)     several example screens and tabs using react-navigation and TypeScript
    ----- Bare workflow -----
    minimal               bare and minimal, just the essentials to get you started
    minimal (TypeScript)  same as minimal but with TypeScript configuration

**// This brought me joy. Thank you all!**

**Comment by Cajavi89** [comment]
this works for me: 

I used this command: 
> npm ls expo-cli --global

it res =  

> /home/myUser/‘~/.npm-global/lib

and then I add at bottom of .`zshrc`  and .`bashrc`  this line: 

>  export PATH=$PATH:/home/myUser/‘~/.npm-global/bin   

Im using WSL2.
hope help someone else.

**Comment by nerialdo** [comment]
Depois de 2 dias, esta solução resolveu meu problema. 

> this works for me:
> 
> I used this command:
> 
> > npm ls expo-cli --global
> 
> it res =
> 
> > /home/myUser/‘~/.npm-global/lib
> 
> and then I add at bottom of .`zshrc` and .`bashrc` this line:
> 
> > export PATH=$PATH:/home/myUser/‘~/.npm-global/bin
> 
> Im using WSL2. hope help someone else.

Depois de 2 dias, esta solução resolveu meu problema.
