### ISSUE TITLE
expo init failed

### ISSUE THREAD

**Issue by sitrakaLeon** [expo/expo-cli#666]
## Description

I have error while create a new project in expo init

npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/expo/react-native-maps.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2019-06-01T07_02_07_212Z-debug.log

## Environment

   System:
      OS: Windows 10
    Binaries:
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

I use windows 10 64 bits and i already install git in my pc

thanks for help :)

**Comment by arjunghimire** [comment]
@sitrakaLeon  this problem is from last 1 month. Why they are not fixed it.

**Comment by cruzach** [comment]
This actually has been [asked on our Forums](https://forums.expo.io/t/expo-init-on-windows-fails-downloading-vector-icon-dependency/18599/3?u=charliecruzan). If you already have git installed, it's probably an issue of adding it to PATH

-Charlie
