### ISSUE TITLE
[SOLVED] Google Maps not showing anymore in simulator with expo-cli (Android)

### ISSUE THREAD

**Issue by giacomocerquone** [expo/expo-cli#669]
## Description

Maps are not displayed anymore on the expo-cli that expo installs on android simulators.
I firstly get the warning that I have to uninstall the expo-cli app from the simulator because there is a new one and when the new one kicks in, maps are not displayed anymore (oddly this doesn't occur on physical devices, but it might depends on the android version).

**This behaviour is not observed on the standalone built app**

## Expected Behavior

I should see a map where I used to see it.

## Observed Behavior

As said, I've an empty view instead of the map (not even a blank map, it's just like there is no added map at all) after upgrading the expo cli (no code touched)

## Environment

```
  Expo CLI 2.18.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Users\Giacomo\AppData\Roaming\npm\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.5429.30.34.5452501
```

Also specify:

- Phone/emulator/simulator platform, model and version:
Tested with two simulators:

- Nexus one, API 23 Android v. 6
- Nexus 6P, API 25 Android v.7.1.1

And one physical:

- Samsung A8 2018, Android v9 where **it's working**

**Comment by giacomocerquone** [comment]
Figured out.

God, I've always used (with no troubles), simulators without the play store (without even knowing the difference).

I solved it in this way: https://github.com/react-native-community/react-native-maps/issues/2778

I think we should add some info somewhere

**Comment by cruzach** [comment]
Hey @giacomocerquone, is [this](https://github.com/react-native-community/react-native-maps/issues/2778#issuecomment-486304526) the solution that worked for you?

**Comment by giacomocerquone** [comment]
@cruzach no, this one https://github.com/react-native-community/react-native-maps/issues/2778#issuecomment-486387049

I'm keeping this open to wait for someone to understand if it's the case to write this somewhere

**Comment by cruzach** [comment]
Ah okay, thanks for linking that. I think it makes sense to add this to the docs. Maybe the [Android Studio Emulator](https://docs.expo.io/versions/latest/workflow/android-studio-emulator/) section would be the best place to put it.

Do you feel up to submitting a PR for this?

**Comment by giacomocerquone** [comment]
Yes, in 1 hour there will be my pr, but I don't know If the team will accept it.

Anyway I'd like to know why, in order to explain it better in the pr, is this happening just now with the new expo? I mean, maps used to work until two days ago with simulators without Google play, has this something to do with the underlying update of react native maps or is it something intrinsic in expo cli? @brentvatne

**Comment by brentvatne** [comment]
hey i'm not sure what ended up happening here, sorry i didn't see the ping. it's not clear to me what happened but as far as i know google play services was always required to use google maps in an emulator
