### ISSUE TITLE
[web] Add CLI command (expo serve:web) for serving the static expo web bundle locally

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo-cli#673]
# Why

There needs to be a way to test the static bundle generated with `expo build:web` before pushing it to a hosting service.

# How 

Maybe a command like `expo serve:web` which serves the static bundles in `web-build`.

* If the project doesn't have a `web-build` folder, prompt to either: 
  1. "specify a path" - meaning this could work in any react project
  2. "build the project" - then `expo build:web` will do the heavy lifting to decide if the project is web-capable
* Host at a location and copy the location to the user clipboard
* Add `--https --no-https` flag

**Comment by c3duan** [comment]
@EvanBacon, may I help you with this issue. If so, can you point me to the files/code I should investigate and understand before implementing since this will be my first PR in this repository?

**Comment by EvanBacon** [comment]
Commands are added here https://github.com/expo/expo-cli/tree/master/packages/expo-cli/src/commands but I'm thinking that this might be adding too much bloat to the main expo-cli package. Maybe creating an `expo-serve-web` in the packages/ directory that we could use to host static bundles, that'd look something like this https://github.com/expo/expo-cli/pull/1192

**Comment by EvanBacon** [comment]
For now I think `npx serve web-build` will suffice.
