### ISSUE TITLE
execAsync error causing a false-positive xcode simulator failure

### ISSUE THREAD

**Issue by aleph-naught2tog** [expo/expo-cli#674]
## Description

After upgrading to Expo SDK33 using all the instructions [here](https://blog.expo.io/expo-sdk-v33-0-0-is-now-available-52d1c99dfe4c), it fails to run on xcode simulator. I did run `sudo xcode-select -s /Applications/Xcode.app` as well, which did not help. I also tried the suggestions in other issues for simulator issues.

**The actual error is about `execAsync` being undefined** and if I rebuild XDL myself changing the `osascript` import to in `Simulator.js` to be `import osascript from '@expo/osascript';`,  and use that built Simulator.js file, the behavior is correct and the simulator opens and runs as expected.

The error getting thrown is the only one for that block, but the actual error occurring has nothing to do with xcode. Changing the code and rebuilding it then it works great, but I hesitate to open a PR because it seems odd that the `import` syntax of a single module would change like that -- I'm assuming it's from an off setting in a tsconfig somewhere with the recent switch to TS? Spitballing here but looks like a lack of `allowSyntheticDefaultImports` in the `compilerOptions`, only the file using it (`Simulator.js`) is Flow, not TS, but the osascript file itself was recently ported to TS

## Expected Behavior

I expect it to open in the simulator like usual.

## Observed Behavior

It *does* run still on my phone after installing the new Expo client. 

If I go back to the commit before changing the version, blow away `node_modules`, reinstall, and `expo start --clear`, it works normally. If I go back to the updated version and do the same -- blow away node modules etc, reinstall, etc -- it fails with the same error.

```
Can't determine id of Simulator app; the Simulator is most likely not installed on this machine TypeError: Cannot read property 'execAsync' of undefined
    at /@expo/xdl@54.1.0/src/Simulator.js:65:31
    at Generator.next (<anonymous>)
    at step (node_modules/@expo/xdl/build/Simulator.js:646:191)
    at node_modules/@expo/xdl/build/Simulator.js:646:437
    at new Promise (<anonymous>)
    at  /node_modules/@expo/xdl/build/Simulator.js:646:99
    at _isSimulatorInstalledAsync (node_modules/@expo/xdl/build/Simulator.js:94:18)
    at /@expo/xdl@54.1.0/src/Simulator.js:399:15
    at Generator.next (<anonymous>)
    at step (node_modules/@expo/xdl/build/Simulator.js:646:191)
Simulator not installed. Please visit https://developer.apple.com/xcode/download/ to download Xcode and the iOS simulator. If you already have the latest version of Xcode installed, you may have to run the command `sudo xcode-select -s /Applications/Xcode.app`.
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

```
  Expo CLI 2.19.0 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @testing-library/react-native: ^4.0.2 => 4.0.2
      @types/react: ^16.8.19 => 16.8.19
      @types/react-native: ^0.57.60 => 0.57.60
      @types/react-navigation: ^3.0.7 => 3.0.7
      expo: ^33.0.3 => 33.0.3
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.0 => 3.11.0
    npmGlobalPackages:
      expo-cli: 2.19.0
```

**Comment by nextriot** [comment]
+1 

Was just about to open an issue myself when I came across this one.
Sys info below. Tried all the 'Simulator not installed...' fixes to no avail. 
Also tried uninstalling and reinstalling Xcode with no luck.

`expo diagnostics`

```
  Expo CLI 2.19.0 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.11.0 - ~/.nvm/versions/node/v10.11.0/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.11.0/bin/npm
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.3 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 2.19.0
```

`Error message`
```
Can't determine id of Simulator app; the Simulator is most likely not installed on this machine TypeError: Cannot read property 'execAsync' of undefined
    at /@expo/xdl@54.1.0/src/Simulator.js:65:31
    at Generator.next (<anonymous>)
    at step (/Users/nextriot/.nvm/versions/node/v10.11.0/lib/node_modules/expo-cli/node_modules/@expo/xdl/build/Simulator.js:646:191)
    at /Users/nextriot/.nvm/versions/node/v10.11.0/lib/node_modules/expo-cli/node_modules/@expo/xdl/build/Simulator.js:646:437
    at new Promise (<anonymous>)
    at /Users/nextriot/.nvm/versions/node/v10.11.0/lib/node_modules/expo-cli/node_modules/@expo/xdl/build/Simulator.js:646:99
    at _isSimulatorInstalledAsync (/Users/nextriot/.nvm/versions/node/v10.11.0/lib/node_modules/expo-cli/node_modules/@expo/xdl/build/Simulator.js:94:18)
    at /@expo/xdl@54.1.0/src/Simulator.js:399:15
    at Generator.next (<anonymous>)
    at step (/Users/nextriot/.nvm/versions/node/v10.11.0/lib/node_modules/expo-cli/node_modules/@expo/xdl/build/Simulator.js:646:191)
Simulator not installed. Please visit https://developer.apple.com/xcode/download/ to download Xcode and the iOS simulator. If you already have the latest version of Xcode installed, you may have to run the command `sudo xcode-select -s /Applications/Xcode.app`.
```

**Comment by aleph-naught2tog** [comment]
@nextriot 

I ended up temporarily adding a script for myself in my project root for the moment (since I'm tinkering and thus blowing away my install frequently at the moment):

```js
// rewrite.js
// `node rewrite`
const fs = require('fs');

console.warn(`Rewriting '@expo/xdl/build/Simulator.js' because breakage.`);

const filename = require.resolve('@expo/xdl/build/Simulator.js');
const data = fs.readFileSync(filename)
               .toString('utf8')
               .replace('default.execAsync', 'execAsync');

fs.writeFileSync(filename, data);
```

**Comment by nextriot** [comment]
@aleph-naught2tog thanks for sharing! Are you installing `expo-cli` locally to the project and calling the script from `package.json`? Something like:

`start: node rewrite.js expo start`

**Comment by aleph-naught2tog** [comment]
Yup! `node rewrite.js && expo start`. Rerunning it doesn't hurt anything; it just won't find those again and won't replace them :)

**Comment by nextriot** [comment]
@aleph-naught2tog That's awesome. Thanks again.

Just to confirm, I went ahead and did a find and replace for `default.execAsync` to `execAsync` on the global package – and that does indeed fix the issue. Thanks for doing the legwork 👍 

Hopefully a PR gets in soon.

**Comment by wayne-li2** [comment]
Ah glad to see this was resolved quickly! :D It's late, so I will just sleep and wait for the next update instead of working around it. Thanks again!

**Comment by cruzach** [comment]
Has anyone had this issue with the most recent version of `expo-cli`? (v2.19.1)

Believe this should be fixed by [this commit](https://github.com/expo/expo-cli/commit/701656d9416b6765fc00d843464af75bad0af979).

**Comment by aleph-naught2tog** [comment]
@cruzach I'll try right now!

**Comment by aleph-naught2tog** [comment]
Yes, @cruzach is right -- 2.19.1 fixes it :)

**Comment by cruzach** [comment]
Glad to hear it! Thanks for bringing this issue up, and for providing so much info everyone 😄

**Comment by aleph-naught2tog** [comment]
No prob! I had spent my whole day wrangling `default` elsewhere, it was nice to actually put all of it to something useful :D
