### ISSUE TITLE
Unnecessary warning after updating to Expo v33.0.0

### ISSUE THREAD

**Issue by SuperThinking** [expo/expo-cli#681]
After upgrading to Expo v33.0.0, on doing 'exp build:android' (which was perfectly working before), it gives an error, /[23:06:12] Standalone build failed!
![image](https://user-images.githubusercontent.com/22829739/59123014-db9c1c00-8979-11e9-8a12-5aad6368c25f.png)
Also, even after installing 'expo-constants' (expo install expo-constants), it shows the warning.
![image](https://user-images.githubusercontent.com/22829739/59123117-1f8f2100-897a-11e9-81a4-085c08f86556.png)

**Comment by cruzach** [comment]
Hi @SuperThinking, we recently updated the builders to allow for SDK 33 builds, when did you run into this? Also, let me know what version of `expo-cli` you're running

**Comment by SuperThinking** [comment]
@cruzach I updated to Expo v33.0.0 today only and have been facing this issue from the past 5-6 hours.
expo-cli -V => 2.19.4

**Comment by SuperThinking** [comment]
>Hmm, interesting, 'expo build:android' solved the issue of build failed.

**Comment by SuperThinking** [comment]
expo-constants warning still exists though

**Comment by BrentGrammer** [comment]
Getting the same warning as well.  I have not imported Constants anywhere in my source code.

**Comment by cruzach** [comment]
Most likely you're importing a library that's using `expo-constants` and they haven't updated their code to the modular style of imports left. I would search for it in your `node_modules`, and if it's a library we control I'll update it, if not you'll have to submit a PR to that particular library

**Comment by mackbrowne** [comment]
@SuperThinking check `sentry-expo`, that's what it was for me.  If you aren't using sentry, If you share the dependencies from package.json I'll try to help.

**Comment by SuperThinking** [comment]
@mackbrowne Please take a look at my package.json,
{

"main": "node_modules/expo/AppEntry.js",

"name": "v-track",

"scripts": {

"start": "expo start",

"android": "expo start --android",

"ios": "expo start --ios",

"eject": "expo eject"

},

"dependencies": {

"axios": "^0.19.0",

"expo": "^33.0.4",

"expo-constants": "^5.0.1",

"expo-font": "^5.0.1",

"expo-module-scripts": "^1.0.0",

"expo-permissions": "^5.0.1",

"moment": "^2.24.0",

"react": "16.8.3",

"react-base": "^0.2.0",

"react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",

"react-native-indicators": "^0.13.0",

"react-native-progress-circle": "^2.0.1",

"react-native-spinner-button": "^1.0.3",

"react-native-svg": "^9.4.0",

"react-native-vector-icons": "^6.4.2",

"react-navigation": "^3.11.0",

"react-redux": "^6.0.1",

"redux": "^4.0.1"

},

"devDependencies": {

"babel-preset-expo": "^5.0.0",

"react-native-svg-asset-plugin": "^0.1.2"

},

"private": true

}

**Comment by Charmaine09** [comment]
Same problem encountered here. I updated mine just 5 hrs ago.

**Comment by mackbrowne** [comment]
@SuperThinking try `expo-module-scripts` . << thats my best guess.  Otherwise do a search as @cruzach mentioned.

@Charmaine09 could it be `@expo/vector-icons` ??

**Comment by Charmaine09** [comment]
I tried to omit `@expo/vector-icons`, remove node_modules folder and do `npm install` again. Run `expo start --android` and the app is working properly. I then run `expo build:android` but the build still failing.
Please see my updated package.json:
{
  "name": "empty-project-template",
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "expo": "^33.0.4",
    "expo-ads-admob": "^5.0.1",
    "expo-codemod": "^1.0.1",
    "expo-font": "^5.0.1",
    "moment": "^2.24.0",
    "os": "^0.1.1",
    "prop-types": "^15.6.2",
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
    "react-native-datepicker": "^1.7.2",
    "react-native-dialog": "^5.5.0",
    "react-native-elements": "^0.19.1",
    "react-native-flexi-radio-button": "^0.2.2",
    "react-native-modal": "^7.0.2",
    "react-native-radio-buttons-group": "^1.0.7",
    "react-native-star-rating": "^1.1.0",
    "react-native-tab-view": "^1.3.1",
    "react-native-vector-icons": "^6.1.0",
    "react-native-whc-loading": "^1.0.3",
    "react-navigation": "^2.17.0",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-persist": "^5.10.0",
    "redux-promise-middleware": "^5.1.1",
    "redux-thunk": "^2.3.0",
    "styled-components": "^4.0.2",
    "supports-color": "^5.5.0"
  }
}
Error build message is still the same.

**Comment by zaytrix** [comment]
Try deleting node_modules and the .lock file and installing the dependencies again, that fixed the warning for me

**Comment by Charmaine09** [comment]
I did it so many times, but I got the same error.

**Comment by vinsidious** [comment]
I was having the same problem. In my case, I _believe_ it's due to `react-navigation`.

**Working backward (or forward, depending on your perspective):**

Dependency | Reference
-----|-----
`react-navigation` depends on `@react-navigation/native` | [package.json](https://github.com/react-navigation/react-navigation/blob/master/package.json#L40)
`@react-navigation/native` depends on `react-native-safe-area-view` | [package.json](https://github.com/react-navigation/native/blob/master/package.json#L94)
`react-native-safe-area-view` relies on `Constants` exported by the `expo` package | [index.js](https://github.com/react-native-community/react-native-safe-area-view/blob/master/index.js#L91)

**Comment by Charmaine09** [comment]
Hi @vince, what do you mean by due to react navigation? Is it the version
or what?
