### ISSUE TITLE
expo optimize should not run against certain directories

### ISSUE THREAD

**Issue by calvinf** [expo/expo-cli#685]
## Description

When running `expo optimize`, it runs against directories that it should not touch.

## Expected Behavior

When running `expo optimize`, it should only optimize images used in my app and not every image recursively found within the project directory.

Ideally, it would only use images that are specified in App.json or otherwise referenced within the source code.

## Observed Behavior

For example, I have `Exponent.app` in `bin/` relative to the root of my project in order to run detox tests.  When running `expo optimize`, it went into this directory and optimized the images despite those images not being part of my app or my build.

## Environment

```
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^5.1.3 => 5.1.3
      expo: ^33.0.3 => 33.0.3
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.0 => 3.11.0
    npmGlobalPackages:
      expo-cli: 2.19.4
```

## Reproducible Demo

* Download latest IPA from [Expo Tools](https://expo.io/tools#client), extract it, rename it too Exponent.app, and put it within `bin/` folder relative to project root, i.e. `~/my-expo-project/bin/Exponent.app`.
* run `expo optimize`

**Comment by sergeichestakov** [comment]
Hey @calvinf,

`expo optimize` does actually default to using values from your `app.json`. More specifically, it looks under the `assetBundlePatterns` field which is initialized as `[ '**/*' ]` in a new Expo project, hence the recursive search.

Have you tried running the command with the `--include` flag? This will overwrite the default and only search the glob pattern that you passed in. For example, if you only want to optimize assets found in `assets/images` you can run `expo optimize --include="assets/images/*"`. Similarly, you can also use the `--exclude` flag to avoid searching in certain directories if that's easier. Just remember that all glob patterns are relative to the project root regardless of which directory you're running the command in.

Let me know if that helps.

Thanks,
Sergei

**Comment by calvinf** [comment]
My assetBundlePattern is indeed the default. I build all of my code and assets into the app and never do a publish for updating so I left the pattern as broad as possible. 

```
 "assetBundlePatterns": ["**/*"],
```

Is asset bundle glob supposed to match all the JS  and images that are used in the app? Is there a good example of using it to match a specific list of directories rather than “everything”? Does it allow for blacklist of any kind? I presume it’s using a standard glob library - I’ll try to look that up as well. 

Does this mean Expo is including anything that matches this path as part of my build? How does it determine what to bundle with the app?

**Comment by calvinf** [comment]
These docs seem relevant: https://docs.expo.io/versions/latest/guides/assets

**Comment by calvinf** [comment]
Is there a reasonable heuristic `expo optimize` could use to detect overly broad `assetBundlePattern` and give a warning before optimizing?

**Comment by sergeichestakov** [comment]
Yeah, the asset bundle patterns specifies which assets will be bundled into the standalone app binary as the docs suggest. Here is the glob library we use for reference: https://www.npmjs.com/package/glob. That might help you make more specific patterns.

What do you mean by overly broad? I think optimizing all images in a project is a pretty typical use case, but if you need to get more specific, you can always use the `--include` and `--exclude` flags

**Comment by calvinf** [comment]
When using “**/*” any directories used for tests, screenshots, helper tools, and similar will have its image assets included in the bundle. I decreased my apk app size by 900kb once I realized this and changed my glob pattern to be more specific.

**Comment by sergeichestakov** [comment]
Great, glad that helped.

I'm closing this issue since it seems you have everything resolved but let me know if you run into anymore problems.

Thanks,
Sergei
