### ISSUE TITLE
Console is flooded even after updating expo to "expo": "^33.0.4"

### ISSUE THREAD

**Issue by ssomlk** [expo/expo-cli#689]
I am using react-navigation package and I am still getting the below warning even after updating the expo package to 33.0.4 as mentioned in issue https://github.com/expo/expo/issues/4501

The following APIs have moved to separate packages and importing them from the "expo" package is deprecated: Constants.

1. Add correct versions of these packages to your project using:

   expo install expo-constants

   If "install" is not recognized as an expo command, update your expo-cli installation.

2. Change your imports so they use specific packages instead of the "expo" package:

 - import { Constants } from 'expo' -> import Constants from 'expo-constants'

I have noticed that the global.Expo.Constants is being used in below files

node_modules\react-native-reanimated\src\base.js
node_modules\react-native-safe-area-view\index.js

**Comment by raajnadar** [comment]
upgrade to expo@33.0.4 to fix the warning

**Comment by cruzach** [comment]
As Brent said in that issue:

> if it's from a package we control we can resolve it, if not you may need to send a pull request to someone or use patch-package for now.

Looks like `react-native-reanimated` and `react-native-safe-area-view` must still use the old importing style

**Comment by ssomlk** [comment]
> upgrade to expo@33.0.4 to fix the warning

I have already done this raajnadar without luck. Thank you anyway

**Comment by ssomlk** [comment]
> As Brent said in that issue:
> 
> > if it's from a package we control we can resolve it, if not you may need to send a pull request to someone or use patch-package for now.
> 
> Looks like `react-native-reanimated` and `react-native-safe-area-view` must still use the old importing style

Yes they are. They have global.Expo.Constants in both the files like @raajnadar raajnadar has mentioned in the expo/expo#4501

**Comment by arkinem** [comment]
I'm currently on 33.0.5 and I'm still facing this issue. In my case, the problem is related probably with `react-native-paper`.

**Comment by BettyJJ** [comment]
I'm currently on 33.0.7 and I'm still facing this issue.

**Comment by ssomlk** [comment]
I have updated the expo-cli to the latest and this issue is now fixed
