### ISSUE TITLE
npm ERR! peer dep missing

### ISSUE THREAD

**Issue by jathniel234** [expo/expo-cli#690]
## Description

Having issue with @expo/xdl

## Expected Behavior

I just globally install expo-cli

## Observed Behavior

├── bower@1.8.8
├── expo-cli@2.19.4
├── gulp@4.0.2
├── node-gyp@4.0.0
├── npm@6.9.0
├── react-native-cli@2.0.1
└── yarn@1.16.0

npm ERR! peer dep missing: @expo/xdl@^53.8.0, required by @expo/dev-tools@0.5.22

**Comment by cruzach** [comment]
Hi @jathniel234 - What version of Node are you on? Are there any more error logs you could share?

**Comment by jathniel234** [comment]
I finally fix this issue, all i need is to update all the library on npm
