### ISSUE TITLE
Couldn't start project on Android: Error running adb:

### ISSUE THREAD

**Issue by pioNavarro** [expo/expo-cli#694]
I'm having a problem running the expo to my android studio emulator. Its so wierd because it works on my android device but not on my emulator.

Here's the error I'm getting.
![image](https://user-images.githubusercontent.com/51459273/59059189-ed75b480-88d0-11e9-8e08-22aba8614bf4.png)

My Expo version is 2.19.1
My Android Studio version:
![image](https://user-images.githubusercontent.com/51459273/59059349-4fceb500-88d1-11e9-8374-c71b338abeb0.png)

**Comment by schellack** [comment]
I have this issue reported here as well. When I tried to create reproducible steps to post, I created a branch new Pixel 2 image. This new image does not have the problem. It's only my old Pixel 2 AVD that does.

One difference I can see between them is that the expo-cli doesn't show this message for the emulator that doesn't work properly:

> Successfully ran `adb reverse`. Localhost URLs should work on the connected Android device.

After some digging, all I could figure was that my older emulator could not longer be connected to via adb. So for others who have this issue: perhaps try creating a new emulator?

**Comment by dragosdehelean** [comment]
I've just created a new Pixel 2 image and the problem remains the same:
![image](https://user-images.githubusercontent.com/34175492/59245912-46bc4b80-8c23-11e9-8811-bd378097245c.png)

**Comment by apiep** [comment]
I also have the same problem, be it emulator or real device (samsung A7 and Xiaomi Redmi 5).

λ adb --version                                                                                  
Android Debug Bridge version 1.0.41                                                              
Version 29.0.0-5611747                                                                           
Installed as C:\Users\Me\AppData\Local\Android\Sdk\platform-tools\adb.exe                     

λ expo --version                                                                                 
2.19.4

**Comment by Andy4ward** [comment]
Was pointed in the direction of this thread overnight.

Went to start the project this morning and was informed that expo-cli was now at version 2.19.5 so did the update.

Went to open Android Studio to see if the new cli version was going to fix the adb problem and was informed that there was an update to the sdk platform-tools for version 29.0.1. So did the update.

Ran `expo start` with the updated cli and platform tools and it came up first time without a problem.

Not sure which update was responsible or if it was a combined effort but thanks for getting this sorted.

**Comment by pioNavarro** [comment]
Thank you for the information @Andy4ward  i got my expo now working. I thought the fix was reinstalling my android studio.

**Comment by wenyufei2018** [comment]
@pioNavarro reinstalling my android studio can fix this issue?

**Comment by pioNavarro** [comment]
> @pioNavarro reinstalling my android studio can fix this issue?

try to update first your expo. if not fixed then try to reinstall your android studio.

**Comment by tiagocpeixoto** [comment]
I was facing the exact same problem. 

I used scoop to install android-sdk with Powershell (Windows 10). So I uninstalled it (android-sdk) and reinstalled it with CMD (and not Powershell). So the problem with adb was solved and I could start Android emulator.

Hope it helps.

**Comment by meenal456** [comment]
I have updated expo version in package.json file. But after uninstalling and reinstalling Android Studio ,I was facing same error. Please help me to solve this issue.

**Comment by muradmm83** [comment]
I had the same issue. I'm using Windows 10. It appears that this issue only happens if I use git bash. When using PowerShell everything is fine. Also, using git bash if you type `expo start --android` your app will app in your emulator. Hope that helps.

**Comment by fzabin** [comment]
I had a similar issue after update the expo-sdk version of a project and I tried another emulator image and it ran just fine. Then I reset the emulator image with problem and tried again and it worked too.

The message I received was:

`Couldn't start project on Android: Error running adb: Error running app. Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=exp://192.168.0.8:19000 flg=0x10000000 }`

Hope it helps.

**Comment by LucioOSilva** [comment]
i got the same error here! =/

**Comment by LucioOSilva** [comment]
I got that problem too (that's why find that post and i came here), and the solution was solved when I restarted the expo. =D

**Comment by EfeAgare** [comment]
Install the expo app on your android emulator, then restart your server

**Comment by jithustvr** [comment]
Open your Expo by typeing expo start
Then open your android studio
goto tools -> AVD Manger Then launch any installed emulator
Then open expo and click on Run on Android device/emulator
will be fine

**Comment by aman90attari** [comment]
I had same problem solve after disconnecting my phone from PC or USB debugging disable will also work

**Comment by donni106** [comment]
`expo start --android` gives me:

<img width="290" alt="Bildschirmfoto 2020-05-14 um 13 28 41" src="https://user-images.githubusercontent.com/1942953/81929180-d8c49500-95e6-11ea-8a19-c9bf0742a2c4.png">

I got this without any further message. It does not matter if I try an emulator or with a real device.

* expo-cli 3.20.3
* tried with code bases using expo sdk 33.0.0 and 34.0.0
* updated everything connected to Android Studio

**Comment by gouravrc** [comment]
This worked for me 👍 

```Open Android Studio > SDK Manager > SDK Tools```

You can see the items which need to be updated. Check **Status** column.
if you see **Update available**, please update the following.

Hope it helps.

**Comment by praneethpj** [comment]
run with sudo 

sudo expo start --android

**Comment by azizulhaq800804** [comment]
Have the same issue. First time it failed. Then keeping the emulator open and then npm start resolved it.

**Comment by Palash1999** [comment]
> I had a similar issue after update the expo-sdk version of a project and I tried another emulator image and it ran just fine. Then I reset the emulator image with problem and tried again and it worked too.
> 
> The message I received was:
> 
> `Couldn't start project on Android: Error running adb: Error running app. Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=exp://192.168.0.8:19000 flg=0x10000000 }`
> 
> Hope it helps.

I cleared the data of my emulator and it worked!

**Comment by jpg-130** [comment]
1. Keep usb debugging ON in developer mode.
2. In notification bar (android device) keep in transfer files mode(to enable sdk/adb whatever installation).
3. Then run `expo start --android.`

I was having the same issue but solved it this way.

**Comment by sainifacundo-tech** [comment]
maybe you have your cell phone connected to your pc?
That happened to me. unplug the cell phone and it worked fine

**Comment by FranH20** [comment]
Fix the problem by entering my Google account in the emulator so that I can download the application
![image](https://user-images.githubusercontent.com/54047442/94611503-6d165800-0267-11eb-8dd7-96939cc48fa6.png)

**Comment by arfizurrahman** [comment]
I encountered the same issue. In my case, I've created the virtual device with the API level 29, but I had the SDK manager with API level 30 installed. So, I installed the SDK manager 29. It solved my issue.

**Comment by eduhdm** [comment]
What solved this issue for me is killing the current connection in adb:
executed:
`adb devices`
got the id of the connection and run:
`adb disconnect <connection-name>`
Then, I runned the project in android again.

**Comment by GabrielCozma** [comment]
Hello! I had the same issue, trying with Andorid Emulator device and Genymoion Emulator. Both with the same problem. 
I solved it by uninstalling Android Studion, after that I've creted a new emulator with the latests API version and after that my Expo app run's fine. I hope this will help you, it took's me 3 hours of trying.

**Comment by addemark** [comment]
> 
> 
> Open your Expo by typeing expo start
> Then open your android studio
> goto tools -> AVD Manger Then launch any installed emulator
> Then open expo and click on Run on Android device/emulator
> will be fine

This worked for me

**Comment by awaldron** [comment]
> run with sudo
> 
> sudo expo start --android

This worked for me. Also had to have my AVD already open. Thanks!

**Comment by GabrielCozma** [comment]
I'm on windows, but thank you!

vin., 20 nov. 2020, 16:47 Alan Waldron <notifications@github.com> a scris:

**Comment by douglascavanaugh** [comment]
I originally posted the same issue back in May on StackOverflow [https://stackoverflow.com/questions/61858084/android-emulator-adb-error-device-still-connecting](url).

My issue was that I was trying to run two different Android emulators at the same time, and when I clicked the "Run on Android device/emulator" from the Metro Bundler, the emulator crashed and when I booted the Android emulator back up, then clicked on the "Run on Android device/emulator" again, I got the error "Couldn't start project on Android: Error running adb: more than one device/emulator."  Come to find out, the adp device was stuck trying to connect to "emulator-5562 connecting" and I couldn't kill it.

I found the solution in this StackOverflow post:  [https://stackoverflow.com/questions/54953134/prevent-android-emulator-from-starting](url).  I followed his directions exactly and just now (after 6 months), started using my Android emulator again.

**Comment by kyawthura-gg** [comment]
Restarting the emulator worked for me 🔥
![Screenshot 2020-12-18 at 12 06 14 PM](https://user-images.githubusercontent.com/44088165/102578945-c9cc3500-4129-11eb-9ce0-788fdaea064e.png)

**Comment by Stukz** [comment]
My app isn't working properly on my real device with SDK 22 so decided to use emulator and try to debug but I'm having this issue
![image](https://user-images.githubusercontent.com/57040392/103092259-ab9c8400-45c4-11eb-8019-c8b07ccd40db.png)

**Comment by jaber105033** [comment]
Hi, I can not install the Android Studio SDK, and every time I delete it and install it again, this part is empty and I did not bring any Android platform.
 Gmail :jaber105033@gmail.com

**Comment by aleks-rope** [comment]
I got it to work on Ubuntu 20.04.1 LTS. Using android studio 4.1.1 by running `expo start` selecting android from terminal and running the emulator from Android studio. It took a while to download the expo updates on the emulator but it worked. If you need help setting up android studio properly see this guide: https://docs.expo.io/workflow/android-studio-emulator/

**Comment by HeIp** [comment]
This issue is still going on, an update should address this so developers don't' have to manually start up the android emulator from Android Studio. And should work as fluid as it does with react native.

**Comment by Damian-16** [comment]
A mi me funciono iniciando otro emulador en el AvdManager, prueben con eso si se les ha congelado el emulador y no los deja hacer pruebas

**Comment by SajjadTasawar** [comment]
update expo-cli and create a new virtual device in andriod studio and select the one with playstore .This solved my problem.

**Comment by richjeffery** [comment]
My solution to this, after trying a bunch and still getting `device offline` on a Pixel C emulator running Android 10, was :

1) to turn on Developer Options in the emulator by tapping on the `Build` number in `Settings>About emulated device` seven times until it says 'you are now a developer!'
2) Going into `System>Advanced>Developer Options`
3) Turning on USB debugging.

And now Expo can see my device.

**Comment by mukeshphulwani66** [comment]
To fix this issue download expo go apk from your browser and paste that into emulator

**Comment by josh-fryer** [comment]
what solved this issue?

**Comment by jonathanstiansen** [comment]
I followed the instructions on Expo's android installation guide: `https://docs.expo.dev/workflow/android-studio-emulator/?redirected` following all of the env variable steps along the way, and after I confirmed `adb` worked on the command line - I no longer got this error.

**Comment by benbenzy** [comment]
> Hi @pioNavarro - you need to have the Android emulator opened, then you can open the project on it. Let me know if that works!

open the emulator then open the playstore in emulator  and login with email
download expo go app
then after starting the server with expo start
click run android

**Comment by zackenichi** [comment]
> > Hi @pioNavarro - you need to have the Android emulator opened, then you can open the project on it. Let me know if that works!
> 
> open the emulator then open the playstore in emulator and login with email
> download expo go app
> then after starting the server with expo start
> click run android

This is the right fix. Thank you

**Comment by DomVinyard** [comment]
My fix was a combination of the above

Initially the emulator didn't even open, fixed by:

> Open Android Studio > SDK Manager > SDK Tools
> You can see the items which need to be updated. Check Status column.
> if you see Update available, please update the following.

Once the emulator is visible on screen:

> open the emulator then open the playstore in emulator and login with email
> download expo go app
> log in to expo go

**Comment by forinda** [comment]
# I had the same problem
```sh
yarn run v1.22.17
$ expo start --android
Starting project at /home/orinda/Desktop/demoapp
Developer tools running on http://localhost:19002
Opening developer tools in the browser...
Unable to reach Expo servers. Falling back to using the cached dependency map (bundledNativeModules.json) from the package "expo" installed in your project.
Starting Metro Bundler
› Opening exp://192.168.43.140:19000 on itel_W5505
Couldn't start project on Android: Error running adb: connect ECONNREFUSED 172.16.63.3:3128
Error: connect ECONNREFUSED 172.16.63.3:3128
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It shows that its connecting to a proxy server. So for me I diabled the proxy and everything worked okay for me

**Comment by Ivaylo-Iv** [comment]
Hi guys, today I experience the same issue but I have fixed it very easily. Try the solution it might work for you too.
Many developers have wsl or windows subsystem for Linux and it is using a VM and I found it blocks the android sim and causes the error "Error running adb". The solution I found was to open my PowerShell and type "wsl --shutdown". After rerunning the script for android emulation from expo it worked like a charm. Hope I helped.

**Comment by Duclearc** [comment]
Solved it by using the Pixel 5 emulator (Android 11 R - API 30) instead of the default Pixel 3a

**Comment by naganandk** [comment]
Had to recreate the virtual device and restart the metro server.

**Comment by SchmaltzVisuals** [comment]
> Open your Expo by typeing expo start Then open your android studio goto tools -> AVD Manger Then launch any installed emulator Then open expo and click on Run on Android device/emulator will be fine

this is what finally solved my issue

**Comment by zaidajani** [comment]
## Steps to resolve the issue
 
### Step 1: open settings and navigate to about emulated device

![Screenshot 2022-07-30 at 10 10 02 AM](https://user-images.githubusercontent.com/55057446/181872657-8577b214-6e0e-4c33-beb5-e182229fce33.png)

### Step 2: Go to the bottom of the page and press build no 7 times

This will enable developer settings and make you a real developer :) go back and navigate to developer settings.

### Step 3: 

![Screenshot 2022-07-30 at 10 13 19 AM](https://user-images.githubusercontent.com/55057446/181872728-4f69bb8b-a8c1-4270-adda-cd4655420137.png)

Turn on and off USB debugging and go back to the home page

### Checking 

<img width="732" alt="Screenshot 2022-07-30 at 10 14 09 AM" src="https://user-images.githubusercontent.com/55057446/181872741-c5252d07-d58f-4aaa-9ef3-5ec1a34d28e6.png">

It's now working perfectly fine. 

### Conclusion

Turn USB debugging on and off, and start your react native app will run perfectly fine on the android emulator.

**Comment by sanghunka** [comment]
I had the same issue and solved it. 
 
 In my case,

1. Installing adb is not enough. Make sure that you can run adb from your terminal.

check [this](https://docs.expo.dev/workflow/android-studio-emulator/) 

<img width="972" alt="image" src="https://user-images.githubusercontent.com/16280020/183463357-d4a04f23-9398-4776-9f3b-e8e0c3f3cf4c.png">

2. check the free space of emulator device.

check step 3 of [this](https://stackoverflow.com/a/71309984)

**Comment by askariblue** [comment]
The solution to increase the storage resolved this for me

https://stackoverflow.com/questions/54461288/installation-failed-with-message-error-android-os-parcelableexception-java-io

**Comment by tiagosalema** [comment]
> The solution to increase the storage resolved this for me
>
> https://stackoverflow.com/questions/54461288/installation-failed-with-message-error-android-os-parcelableexception-java-io

This worked for me when nothing else did!

**Comment by juni-plxr** [comment]
Hi Guys, I was able to get this working by installing Pixel 2 Q instead of 3. I ran the emulator first before running `expo start`. Hope I will not experience it again once I restart my machine.

**Comment by garrett-gottlieb** [comment]
I'm seeing this error on Pixel 6 API 33 Expo 44 and with Pixel 4 API 30.

**Comment by nguyennk** [comment]
> ## Steps to resolve the issue
> ### Step 1: Open settings and navigate to about emulated device
> <img alt="Screenshot 2022-07-30 at 10 14 09 AM" width="400" src="https://user-images.githubusercontent.com/55057446/181872657-8577b214-6e0e-4c33-beb5-e182229fce33.png">
> 
> ### Step 2: Go to the bottom of the page and press build no 7 times
> This will enable developer settings and make you a real developer :) go back and navigate to developer settings.
> 
> ### Step 3:
> <img alt="Screenshot 2022-07-30 at 10 14 09 AM" width="400" src="https://user-images.githubusercontent.com/55057446/181872728-4f69bb8b-a8c1-4270-adda-cd4655420137.png">
> 
> Turn on and off USB debugging and go back to the home page
> 
> ### Checking
> <img alt="Screenshot 2022-07-30 at 10 14 09 AM" width="400" src="https://user-images.githubusercontent.com/55057446/181872741-c5252d07-d58f-4aaa-9ef3-5ec1a34d28e6.png">
> 
> It's now working perfectly fine.
> 
> ### Conclusion
> Turn USB debugging on and off, and start your react native app will run perfectly fine on the android emulator.

this fixed my problem

**Comment by jrsousadev** [comment]
What worked for me was the following steps (using WINDOWS 10):

1) Enter the system environment variables

2) Click on PATH and add 3 new paths, as follows:

![Sem Título](https://user-images.githubusercontent.com/92350736/215640699-ea42deeb-78f6-4dcc-b49a-0bd635d19c8a.png)

C:\Users\{Your Username}\AppData\Local\Android\Sdk\platforms

C:\Users\{Your Username}\AppData\Local\Android\Sdk\platform-tools

C:\Users\{Your Username}\AppData\Local\Android\Sdk\platform-tools\adb

3) After that, click OK.

4) Restart your computer

5) Open the powershel and enter the command "adb devices" if it doesn't give any error it means it's ok

6) Open the emulator and right after giving the command "expo start"

I hope it helped in some way.

**Comment by EddyMunga** [comment]
> What worked for me was the following steps (using WINDOWS 10):
> 
> 1. Enter the system environment variables
> 2. Click on PATH and add 3 new paths, as follows:
> 
> ![Sem Título](https://user-images.githubusercontent.com/92350736/215640699-ea42deeb-78f6-4dcc-b49a-0bd635d19c8a.png)
> 
> C:\Users{Your Username}\AppData\Local\Android\Sdk\platforms
> 
> C:\Users{Your Username}\AppData\Local\Android\Sdk\platform-tools
> 
> C:\Users{Your Username}\AppData\Local\Android\Sdk\platform-tools\adb
> 
> 3. After that, click OK.
> 4. Restart your computer
> 5. Open the powershel and enter the command "adb devices" if it doesn't give any error it means it's ok
> 6. Open the emulator and right after giving the command "expo start"
> 
> I hope it helped in some way.

This worked magic for me as well. You should ensure that you are using the latest expo version as well.
