### ISSUE TITLE
Unhandled JS Exception: Can't find variable: require - AppEntry.bundle

### ISSUE THREAD

**Issue by syscoavendano** [expo/expo-cli#696]
## Description

Unhandled JS Exception: Can't find variable: require (http://127.0.0.1:19001/./node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Ffranciscoavendano%2FReAxa%2FPH%2FNew%2Flatest%2Fmyaxa-rn-ph%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:410)

global code
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Ffranciscoavendano%2FReAxa%2FPH%2FNew%2Flatest%2Fmyaxa-rn-ph%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:451:3

## Expected Behavior

I try to run the app by yarn start in iOS.

## Observed Behavior

![image](https://user-images.githubusercontent.com/285341/59187484-2307ef80-8ba8-11e9-8995-b06230a2a6ed.png)

## Environment

Running in local machine

- package.json

"dependencies": {
		"ajv": "^6.5.4",
		"buffer": "^5.2.1",
		"currency-symbol-map": "^4.0.4",
		"d3-shape": "^1.2.2",
		"dotenv": "^6.1.0",
		"expo": "^32.0.0",
		"expo-analytics": "^1.0.8",
		"expo-svg-uri": "^1.0.0",
		"js-base64": "^2.4.9",
		"lodash": "^4.17.11",
		"moment": "^2.22.2",
		"native-base": "2.9.0",
		"object-hash": "^1.3.0",
		"prop-types": "^15.6.2",
		"react": "16.5.0",
		"react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
		"react-native-animatable": "^1.3.0",
		"react-native-cache": "^1.1.1",
		"react-native-collapsible": "^1.4.0",
		"react-native-confirmation-code-field": "^3.4.1",
		"react-native-country-picker-modal": "^0.6.2",
		"react-native-dotenv": "^0.2.0",
		"react-native-indicators": "^0.13.0",
		"react-native-keyboard-aware-scroll-view": "^0.8.0",
		"react-native-modal": "^7.0.2",
		"react-native-otp": "^1.0.0",
		"react-native-progress-bar-animated": "^1.0.6",
		"react-native-progress-steps": "^1.2.7",
		"react-native-remote-svg": "^1.4.0",
		"react-native-responsive-fontsize": "0.1.3",
		"react-native-router-flux": "^4.0.3",
		"react-native-slot-machine": "^0.3.2",
		"react-native-smooth-pincode-input": "^1.0.2",
		"react-native-status-bar-height": "^2.2.0",
		"react-native-step-indicator": "0.0.11",
		"react-native-svg-uri": "^1.2.3",
		"react-native-user-inactivity": "^0.1.3-next",
		"react-redux": "^5.0.7",
		"redux": "^4.0.0",
		"redux-actions": "^2.6.1",
		"redux-persist": "^5.10.0",
		"redux-saga": "^0.16.0",
		"rn-pdf-reader-js": "^0.1.7",
		"rn-tooltip": "^1.1.2",
		"stacktrace-parser": "^0.1.4",
		"title-case": "^2.1.1",
		"uuid": "^3.3.2",
		"validate.js": "^0.12.0"
	},

"devDependencies": {
		"@babel/plugin-proposal-class-properties": "^7.4.4",
		"@babel/preset-env": "^7.4.5",
		"@babel/preset-react": "^7.0.0",
		"@babel/plugin-transform-runtime": "^7.4.4",
		"@babel/runtime": "^7.4.5",
		"@unimodules/react-native-adapter": "^2.0.1",
		"babel-eslint": "^10.0.0",
		"babel-plugin-inline-dotenv": "^1.1.2",
		"crossenv": "^0.0.2-security",
		"eslint": "^5.5.0",
		"eslint-config-airbnb": "^17.1.0",
		"eslint-config-prettier": "^3.0.1",
		"eslint-plugin-import": "^2.14.0",
		"eslint-plugin-jest": "^21.22.0",
		"eslint-plugin-jsx-a11y": "^6.1.1",
		"eslint-plugin-prettier": "^2.6.2",
		"eslint-plugin-react": "^7.11.0",
		"fs-extra": "^7.0.1",
		"glob": "^7.1.3",
		"gulp": "^3.9.1",
		"gulp-rename": "^1.4.0",
		"gulp-template": "^5.0.0",
		"husky": "^1.0.0-rc.14",
		"inquirer": "^6.2.0",
		"jest-expo": "^32.0.1",
		"lint-staged": "^7.2.2",
		"mkdirp": "^0.5.1",
		"nock": "^10.0.1",
		"node-fetch": "^2.2.0",
		"plugin-error": "^1.0.1",
		"pre-commit": "^1.2.2",
		"prettier": "^1.14.2",
		"react-dom": "^16.5.2",
		"react-native-scripts": "1.14.0",
		"react-test-renderer": "^16.5.2",
		"redux-mock-store": "^1.5.3",
		"redux-saga-test-plan": "^3.7.0",
		"sinon": "^7.0.0",
		"w3c-xmlhttprequest": "^2.1.3",
		"yargs": "^12.0.2"
	},

**Comment by cruzach** [comment]
Duplicate of #276 , have you tried the fixes there?

**Comment by syscoavendano** [comment]
> Duplicate of #276 , have you tried the fixes there?

I already find a fix. 

module.exports = {
    'presets': [
      'module:metro-react-native-babel-preset',
      'module:react-native-dotenv',
    ],
    'sourceMaps': true,
    'plugins': [
      '@babel/transform-flow-strip-types',
      '@babel/proposal-class-properties',
      '@babel/proposal-object-rest-spread',
      '@babel/transform-runtime'
    ],
  };

**Comment by isabelbicalho** [comment]
Was the solution 'module:react-native-dotenv' ? I'm having the issue too.

**Comment by fahelmoreira** [comment]
for me woked after I did
watchman watch-del-all and rm -fr $TMPDIR/metro*
