### ISSUE TITLE
[web] expo init projects don't build successfully

### ISSUE THREAD

**Issue by chrisdrackett** [expo/expo-cli#697]
## Description

When setting up an expo project with expo init and then building that project for web with `expo build:web` the resulting code will not run successfully.

## Expected Behavior

example projects are able to build successfully for web.

## Observed Behavior

Projects don't render and give the following error:

```
Uncaught TypeError: Cannot read property 'call' of undefined
    at f (runtime~app.2dbaae62.js:1)
    at Object.<anonymous> (2.82fa7fec.chunk.js:1)
    at f (runtime~app.2dbaae62.js:1)
    at Module.<anonymous> (2.82fa7fec.chunk.js:1)
    at f (runtime~app.2dbaae62.js:1)
    at Object.135 (app.cd8a2478.chunk.js:1)
    at f (runtime~app.2dbaae62.js:1)
    at t (runtime~app.2dbaae62.js:1)
    at Array.r [as push] (runtime~app.2dbaae62.js:1)
    at app.cd8a2478.chunk.js:1
```

## Environment

```
  Expo CLI 2.19.4 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.1.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 2.19.4
```

- Safari and Chrome

## Reproducible Demo

just running the lines mentioned in this blog post: https://blog.expo.io/expo-sdk-v33-0-0-is-now-available-52d1c99dfe4c

```
$ npm install -g expo-cli
$ expo init web-test-project && cd web-test-project
$ expo build:web
```

**Comment by chrisdrackett** [comment]
I tried updating the `project.json` file to add `sideEffects` as mentioned here: https://github.com/expo/expo-cli/issues/614#issuecomment-500257991 but was still unable to build.

**Comment by cruzach** [comment]
Hm, I just tried this and was able to build successfully 

Also, any reason you created a new issue that describes the same error as the one you created already -> #614 ?

**Comment by chrisdrackett** [comment]
sorry to open a new issue, but #614 was originally opened based on my own project while this issue deal only with the expo boilerplate. Also, in my experience, once an issue is closed it's very hard for it to get any further attention.

I'm able to build without issue, however if I put the resulting `web-build` on now or Heroku or use `npx serve` I do not get the same results that I do from running the dev server. I get a blank white page and the error mentioned above.

**Comment by cruzach** [comment]
Right, but the errors you are experiencing with each project are the same, so I'm not sure a new issue is warranted. Seems like the issue will be solved once [we are able to publish](https://github.com/expo/expo-cli/issues/614#issuecomment-500226990)
