### ISSUE TITLE
Node core packages question

### ISSUE THREAD

**Issue by aleph-naught2tog** [expo/expo-cli#703]
I understand that Node packages that rely on the core node lib are not available in React Native and hence the error Expo helpfully provides when you try to use one.

Is there a way, however, to override it and force its allowance?

Use case: I have some files to read in as data for the dev environment. If they aren't there, I'd like to write them to a file so that I have them for next time as well. I can absolutely just write a node script that can call `npm start` itself after doing that check and write, but I'd rather do it in `main` if I can. 

Is there a workaround to what I know is a very intentional (and good IMHO) decision, knowing full well I may shoot myself in the foot with this?

**Comment by AdamJNavarro** [comment]
Hey @aleph-naught2tog,

Would you mind creating a [forum post](https://forums.expo.io/c/sdk) for this? We try our best to keep github issues limited to bug reports.

Cheers,
Adam

**Comment by aleph-naught2tog** [comment]
Sure!
