### ISSUE TITLE
Error with Expo's Android client app

### ISSUE THREAD

**Issue by bruno-edo** [expo/expo-cli#710]
## Description

After upgrading the Expo app to version 2.11.0 (so we could upgrade to SDK 33.0.0) the following error started showing up:

![expo_error_app_2-11-2](https://user-images.githubusercontent.com/1909745/59287473-1aff8c80-8c48-11e9-9193-6b60b6502322.png)

![error_sdk_33](https://user-images.githubusercontent.com/1909745/59287496-22269a80-8c48-11e9-86ac-3da95cac57cd.png)

This only starts happening once we reload our app a few times and will persist until we uninstall and reinstall the Expo app in our simulator.

The error kept happening once we downgraded back to SDK 32.0.0, so it should be a problem with the Expo app instead.

## Expected Behavior

We should be able to reload our app and not have to reinstall the Expo app all the time.

## Observed Behavior

The error started showing after a few reloads.

## Environment

```
Expo CLI 2.19.4 environment info:
    System:
      OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.15.2 - /usr/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      expo: 32.0.0 => 32.0.0 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: 3.9.0 => 3.9.0 
    npmGlobalPackages:
      expo-cli: 2.19.4
```
- Simulator: Pixel 2 API 28

**Comment by AdamJNavarro** [comment]
Hey @bruno-edo,

Can you try creating a new project and seeing if you encounter the same issue?

Cheers,
Adam

**Comment by bruno-edo** [comment]
Hey @AdamJNavarro,

I ran `expo init` and was able to reproduce the bug:

![test_app_error](https://user-images.githubusercontent.com/1909745/59290598-50f43f00-8c4f-11e9-855f-cb9ef27da28d.png)

This is what I did to force the error:

- uninstalled Expo from my simulator;
- created a minimal project with `expo init` (dependencies installed with Yarn);
- opened the project on my simulator;
- closed the project on my simulator and stopped the expo DevTools;
- restarted the DevTools and reopened the project on the simulator;
- the error screen will popup 1~2 seconds after the project loads;

Here's the `package.json` file contents:

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^33.0.0",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
    "react-native-web": "^0.11.4"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.1.1"
  },
  "private": true
}
```

**Comment by bruno-edo** [comment]
@AdamJNavarro 

After forcing the `u.default.Mode` error I tried to open the client itself and got an error, here's the log for it:

![error_client_expo](https://user-images.githubusercontent.com/1909745/59291842-1dff7a80-8c52-11e9-88be-b9cc9b92e718.png)


Hope this helps too!

**Comment by schellack** [comment]
I experienced this same issue running my app in the Android emulator on my Mac this morning:

> Uncaught Error: undefined is not an object (evaluating 'u.default.Mode')
> <unknown>@cached-bundle-kernel471465454-UNVERSIONED:748
> 12:05:57 Fatal Error

If I started the Expo app (version 2.11.2) directly, I get the same two errors that bruno-edo posted in the above screenshot.

I didn't have this issue on a similar Android emulator running on my PC. So I uninstalled and reinstalled the Expo app on the Mac-running Android emulator from the expo command line and now the issue is gone.

Deleting and reinstalling from Google Play seems to work fine too.

**Comment by bruno-edo** [comment]
@schellack try following the steps I posted to reproduce the error and see if you'll encounter the error again on your PC.

For me reinstalling the client is only a temporary solution, because the error shows up again once I restart the project.

**Comment by nguanh** [comment]
Our team is having the same issue as @bruno-edo.
Clearing all Storage Data from expo is only a temporary solution as this crash comes up everytime
the expo client is restarted.

This issue didn't come up when I tested the same projects with client version 2.10.6

**Comment by ide** [comment]
We believe the root cause has been fixed. Try re-opening the Android Expo client or re-installing it - though you shouldn't need to.

**Comment by bruno-edo** [comment]
@ide tested the client and it seems like it has been fixed.

Thanks for fixing this so fast.

I'll close this issue.
