### ISSUE TITLE
Add Webpack config as a dependency of the `expo` package

### ISSUE THREAD

**Issue by ide** [expo/expo-cli#713]
Currently the webpack config is a dependency of Expo CLI, which means that upgrading the CLI can change bundling behavior in significant ways (especially considering how much work the webpack config does). To keep projects more stable, we want to move the webpack config to be a dependency of the project, rather than Expo CLI.

The straightforward approach is probably to add it as a dependency of the `expo` package, like the Babel preset.

**Comment by EvanBacon** [comment]
I think adding the webpack config directly to the project is easier at the moment and possible via `expo customize:web`

**Comment by ide** [comment]
Yeah that makes more sense to me. Better to decouple Expo from any one packager configuration.
