### ISSUE TITLE
expo opt-in-google-play-signing TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by JustOnce** [expo/expo-cli#718]
I am trying to build android app using App Signing by Google Play as described in this instruction https://docs.expo.io/versions/latest/distribution/app-signing/#1-using-app-signing-by-google-play. So I run command ```expo opt-in-google-play-signing``` but it fails with error:

```
>>>$ expo opt-in-google-play-signing
Make sure you are not using Google Play App Signing already as this process will remove your current keystore from Expo servers.
You can check whether you are using Google Play App Signing here: https://play.google.com/apps/publish. Select your app and go to "Release management" → "App signing" tab. If you are already using Google Play App Signing, there will be a message that says, "Ap Signing by Google Play is enabled for this app", at the top of the page.
? Is Google Play App Signing enabled for this app? No
Saving current keystore to /media/justonce/DATA/pycharm_project/brain_train/brain_train_sign.jks.bak...
Cannot read property 'bind' of undefined
TypeError: Cannot read property 'bind' of undefined
    at Object.backupExistingCredentials (/@expo/xdl@54.1.5/src/credentials/AndroidCredentials.js:29:26)
    at AppSigningOptInProcess._callee$ (/expo-cli@2.19.5/src/commands/google-play/AppSigningOptIn.js:39:62)
    at tryCatch (/home/justonce/.nvm/versions/node/v10.16.0/lib/node_modules/expo-cli/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/justonce/.nvm/versions/node/v10.16.0/lib/node_modules/expo-cli/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/home/justonce/.nvm/versions/node/v10.16.0/lib/node_modules/expo-cli/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/home/justonce/.nvm/versions/node/v10.16.0/lib/node_modules/expo-cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/justonce/.nvm/versions/node/v10.16.0/lib/node_modules/expo-cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
Also I've tried `expo fetch:android:keystore` and it's works perfect.

## Environment
 `expo diagnostics` output:

  Expo CLI 2.19.5 environment info:
    System:
      OS: Linux 4.15 Linux Mint 18.3 (Sylvia)
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.19.5

**Comment by FabioLG1989** [comment]
@JustOnce Have you solved it? I'm getting same issue here.

`expo diagnostics` output:

  Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.5.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.7 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^2.0.4 => 2.0.4 
    npmGlobalPackages:
      expo-cli: 2.21.2

**Comment by Jack3113** [comment]
Same problem for me on macOs Catalina


  Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.0.2 - /usr/local/bin/bash
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      npm: 6.10.1 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.3 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^2.13.0 => 2.14.2 
    npmGlobalPackages:
      expo-cli: 2.21.2

**Comment by mosnicholas** [comment]
Has anyone found a resolution for this issue? I am encountering it as well.

```
Expo CLI 2.21.2 environment info:
  System:
    OS: macOS 10.14.5
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
  IDEs:
    Android Studio: 3.2 AI-181.5540.7.32.5056338
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    @storybook/react: ^4.1.12 => 4.1.14 
    expo: ^33.0.6 => 33.0.6 
    react: ^16.8.6 => 16.8.6 
    react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
  npmGlobalPackages:
    expo-cli: 2.21.2
```

**Comment by wkozyra95** [comment]
Hi

Sorry, it's taking so long. Fix for that is ready, but there are few issues related to sdk34 release that are blocking us.  Should be ready in a few days.

If you don't want to wait doing this manually should be a problem
- fetch keystore using expo command
- extract private signing key using instructions from play store
- run `expo build:android -c` to generate new keystore
- run `expo fetch:android:upload-cert` to extract public cert from new keystore

private signing key from old keystore and upload cert for new one upload to play store

Before running `build:android -c` save current keystore and credentials somewhere save in case sth goes wrong.
