### ISSUE TITLE
[traveling-fastlane] Does not properly handle enterprise distribution certificate

### ISSUE THREAD

**Issue by jasekiw** [expo/expo-cli#73]
## Description

Running the following fails when allowing expo to handle the certificates. 
`expo build:ios --clear-credentials --apple-enterprise-account --release-channel beta-11`

## Expected Behavior

expo-cli should properly create and manage the certificates.

## Observed Behavior

It fails with the message 

```
The selected team does not have a program membership that is eligible for this feature
```
I found the following lines are responsible for creating and grabbing the in-house distribution certificate
https://github.com/expo/expo-cli/blob/f5afc6d8695c7e158573fdbe3f4256d8f1893f6d/packages/traveling-fastlane/actions/fetch_new_provisioning_profile.rb#L20

https://github.com/expo/expo-cli/blob/f5afc6d8695c7e158573fdbe3f4256d8f1893f6d/packages/traveling-fastlane/actions/fetch_cert.rb#L24

I installed fastlane myself and ran these commands against my own account. The indeed have the same observed behavior. 

I think this is breakage due to the commands being outdated. I found that when removing 'production' from the command it works. ex
`Spaceship::Portal.certificate.in_house.production.all`
to 
`Spaceship::Portal.certificate.in_house.all`

Changing all references of this should fix enterprise deployments. I found what the commands should be from here https://github.com/fastlane/fastlane/blob/master/spaceship/docs/DeveloperPortal.md#enterprise

On a related note: When handling all of my own certificates it seems the expo's build of the app halts after this line of output. Is there an open source repository for the build servers that I can look at for ideas on why this is happening?
```
INFO [2018-10-05 07:57:48.79]: $ /usr/bin/xcrun /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.99.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/8s/t4vscjs14yd6p8736s7b3wyc0000gn/T/gym_config20181005-52280-1n2g48v.plist' -archivePath /private/tmp/turtle/af396780-28d7-4f26-b36e-0267662eaa6a/archive.xcarchive -exportPath '/var/folders/8s/t4vscjs14yd6p8736s7b3wyc0000gn/T/gym_output20181005-52280-zbbhjj' OTHER_CODE_SIGN_FLAGS="--keychain /private/tmp/xdl/e5a30150-c8ae-11e8-90cb-c361f0ab46ca.keychain" 
```

## Environment

```
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.10.0
  Yarn: Not Found
  npm: 6.1.0
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.3871768

Packages: (wanted => installed)
  expo: ^29.0.0 => 29.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4
```

**Comment by woniesong92** [comment]
Is there a quick workaround while this is being fixed?
I just tried running `expo build:ios` from a sample app and ran into the same error message.

**Comment by jasekiw** [comment]
@woniesong92 The only way I was able to get passed this was by ejecting into expo-kit and building it myself because when I tried to manually set up the certificates, the build froze halfway without any error message. It turned a Friday deployment into a week end problem. Not the end of the work week I was looking forward to.

**Comment by revengeofthepencil** [comment]
I'd like to echo the other requests for a workaround here. I'm stuck in the same spot and I'd really like to be able to build without ejecting from Expo

**Comment by dxritchie** [comment]
Did any of you find a work around for this issue? Got approval on my enterprise this morning, have a baby coming in a week was hoping to get an initial version of my app out there for some internal testing. This is my first app trying to keep it simple and stay within expo as long as I can before the need to eject.

**Comment by CricketLaChica** [comment]
Has anyone been able to get a fix for this?

**Comment by dxritchie** [comment]
> Has anyone been able to get a fix for this?

No I had to detach and build via x-code

**Comment by mattrabe** [comment]
https://github.com/expo/expo-cli/pull/297

**Comment by dsokal** [comment]
This should be already fixed.
