### ISSUE TITLE
expo build:ios stalls when target is only ios

### ISSUE THREAD

**Issue by louisgjohnson** [expo/expo-cli#730]
## Description

When I'm trying to build my app, the build never progresses past `Building iOS bundle` when the app.json config is set like:
```
"platforms": [
      "ios"
],
```

## Expected Behavior

iOS app is built

## Observed Behavior

no errors are thrown, it just never progresses.

## Environment

```
  Expo CLI 2.19.5 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.3.1 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.5 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 2.19.4
```

Also specify:
iPad `Version 10.2.1 (SimulatorApp-880.5 CoreSimulator-587.35)`

**Comment by louisgjohnson** [comment]
works fine when setting
```
    "platforms": [
      "ios",
      "android"
    ],
```

**Comment by cruzach** [comment]
@louisgjohnson does it provide you with a build ID? I just tried this on my end with the same `"platforms": ["ios"]` setup and it worked fine.

**Comment by aiham** [comment]
Possibly related to #278

**Comment by dsokal** [comment]
This issue is quite old. I tried to reproduce it but with no success. 
I'm closing it for now but I'm looking forward to hearing from @louisgjohnson. If you could test this and let us know if it's still broken for you it would be great. We'll reopen the issue then.
