### ISSUE TITLE
Expo error when react-native-fs is used

### ISSUE THREAD

**Issue by sebastianbochan** [expo/expo-cli#734]
## Description
In my application I am not able to run it with linked modules. 

## Expected Behavior

React native should link module.

## Observed Behavior

I need to open files from local system. In npm, there is library like `react-native-fs` but still receive error.

```
undefined is not an object (evaluating 'RNFSManager.RNFSFileTypeRegular')
```

How to add module?
1. `npm install react-native-fs`
2. `react-native link react-native-fs`

It seems that expo ignores "linked" modules to react-native.

**Comment by cruzach** [comment]
You can only use these modules in a bare Expo project, not a managed one, unfortunately 😕 

https://docs.expo.io/versions/latest/introduction/managed-vs-bare/

**Comment by sebastianbochan** [comment]
I would like to know if in ExpoKit is also not supported?

**Comment by cruzach** [comment]
It does, that's probably the [main reason for ejecting](https://docs.expo.io/versions/latest/expokit/eject/#should-i-eject-to-expokit)
