### ISSUE TITLE
[webpack-config] Better support for modern browsers

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo-cli#736]
@developit [suggested](https://twitter.com/_developit/status/1139208252577779712) that webpack could potentially create two bundles:

```html
<script type="module" src="./modern.js"></script>
<script nomodule src="./polyfilled.js"></script>
```

This would provide significantly smaller bundles for modern browsers. I would imagine that this could look something like a Webpack Plugin. 

It would also make sense to investigate a more advanced system for polyfilling only what is needed to make the project run. https://babeljs.io/docs/en/babel-polyfill

Related:
[Remove polyfill by default](https://github.com/expo/expo-cli/pull/733)
[MJS support](https://github.com/expo/expo-cli/pull/731)

**Comment by MetalDent** [comment]
Hi, is anyone working on this issue?
