### ISSUE TITLE
app.json doesn't support unicode characters

### ISSUE THREAD

**Issue by siddiq** [expo/expo-cli#74]
`expo build:ios` fails with the following app.json.
```
{
    "expo": {
        "sdkVersion": "27.0.0",
        "name": "سونا",
        "description": "سونا",
        "icon": "./icon.png",
        "version": "1.0.0",
        "orientation": "portrait",
        "ios": {
            "bundleIdentifier": "com.mycompany.myapp"
        }
    }
}
```

**Comment by fson** [comment]
Closing this issue, since there has not been any activity in a year.

If you are still experiencing this issue, please open a new issue with all the information in the issue template filled out. Thanks!
