### ISSUE TITLE
expo install fails without app.json in project root and does not recognise --config path

### ISSUE THREAD

**Issue by romanonthego** [expo/expo-cli#740]
## Description

`expo isntall ${package}` (in my case it's `expo-camera`) is failing if there is no `app.json` file in project root; it's fine and all, but unlike other commands `expo install` does not recognise `--config path/to/app.json` option, so I have to create _mock_ `app.json` file

## Expected Behavior

`expo install ${package}` does not failing if there is no `app.json` present or can understand `--config ${path}` option if you decide to keep configs in other place.

## Observed Behavior

```bash
project [branch] % expo install expo-camera
Can't read JSON file: /Users/user/Code/project/app.json
└─ Cause: Error: ENOENT: no such file or directory, open '/Users/user/Code/project/app.json'
Set EXPO_DEBUG=true in your env to view the stack trace.
```

```bash
project [branch] % expo install expo-camera --config configs/app.development.json

  error: unknown option `--config'
```

## Environment

```bash

  Expo CLI 2.20.0 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.3.1 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/react-native: ^0.57.63 => 0.57.63
      expo: ^33.0.6 => 33.0.6
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.0 => 3.11.0
    npmGlobalPackages:
      expo-cli: 2.20.0
```

**Comment by rakirox** [comment]
the same happens to optimize command
`expo optimize`
output: `No Expo configuration found. Are you sure this is a project directory?`
`expo optimize --config <somewhere>/app.json` 
output: `error: unknown option `--config'`

**Comment by EvanBacon** [comment]
- `--config` has been fixed 
- Projects can now run without an `app.json`
