### ISSUE TITLE
expo build:web failed successfully (No error, but web-build isn't created)

### ISSUE THREAD

**Issue by NiciusB** [expo/expo-cli#749]
## Description

Building for android or iOS works without any issues. Dev mode also works great for web, but once you try to build it, it just doesn't create any files. It doesn't seem to be an issue with the enviroment, since the same thing is happening on another computer running macOS.

## Expected Behavior

web-build to be created with the web-ready build.

## Observed Behavior

No web-build folder.

## Environment

  Expo CLI 2.20.2 environment info:
    System:
      OS: Linux 4.15 Debian GNU/Linux 9 (stretch) 9 (stretch)
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/bin/node
      npm: 6.9.0 - ~/.node_modules/bin/npm
    npmPackages:
      expo: ^33.0.0 => 33.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.20.2

## EXPO_WEB_INFO=true output

nuno@mx-nuno:~/projects/beacon-app $ EXPO_WEB_INFO=true expo build:web

Start Copy

<details><summary>
[Webpack Info]
</summary>

```json
{
  "mode": "production",
  "devtool": "source-map",
  "entry": {
    "app": [
      "/home/nuno/projects/beacon-app/node_modules/expo/AppEntry.js"
    ]
  },
  "context": "/home/nuno/.node_modules/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/webpack",
  "alias": {
    "react-native$": "react-native-web",
    "@react-native-community/netinfo": "react-native-web/dist/exports/NetInfo",
    "react-native/Libraries/Image/AssetSourceResolver$": "expo-asset/build/AssetSourceResolver",
    "react-native/Libraries/Image/assetPathUtils$": "expo-asset/build/Image/assetPathUtils",
    "react-native/Libraries/Image/resolveAssetSource$": "expo-asset/build/resolveAssetSource",
    "react-native/Libraries/Components/View/ViewStylePropTypes$": "react-native-web/dist/exports/View/ViewStylePropTypes",
    "react-native/Libraries/EventEmitter/RCTDeviceEventEmitter$": "react-native-web/dist/vendor/react-native/NativeEventEmitter/RCTDeviceEventEmitter",
    "react-native/Libraries/vendor/emitter/EventEmitter$": "react-native-web/dist/vendor/react-native/emitter/EventEmitter",
    "react-native/Libraries/vendor/emitter/EventSubscriptionVendor$": "react-native-web/dist/vendor/react-native/emitter/EventSubscriptionVendor",
    "react-native/Libraries/EventEmitter/NativeEventEmitter$": "react-native-web/dist/vendor/react-native/NativeEventEmitter"
  }
}
```
</details>
<details><summary>
[Environment Info]
</summary>

```json
{
  "projectRoot": "/home/nuno/projects/beacon-app",
  "pwa": true,
  "production": true,
  "info": true
}
```
</details>
<details><summary>
[Statics Info]
</summary>

clean-webpack-plugin: /home/nuno/projects/beacon-app/web-build has been removed.
Building Webpack bundle [==                  ] 10% (0.0 seconds) building modules- **folder**: `web-default` : `/home/nuno/.node_modules/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/web-default`
- **indexHtml**: `index.html` : `/home/nuno/.node_modules/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/web-default/index.html`
- **manifest**: `manifest.json` : `/home/nuno/.node_modules/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/web-default/manifest.json`
- **serveJson**: `serve.json` : `/home/nuno/.node_modules/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/web-default/serve.json`
- **favicon**: `favicon.ico` : `/home/nuno/.node_modules/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/web-default/favicon.ico`
</details>
<details><summary>
[App.json]
</summary>

```json
{
  "name": "Beacon",
  "name": "Expo App",
  "ios": {},
  "android": {},
  "web": {
    "shortName": "Beacon",
    "shortName": "Expo App",
    "orientation": "portrait",
    "orientation": "any",
    "name": "Beacon",
    "name": "Expo App",
    "icons": {
      "0": {
        "src": "/home/nuno/projects/beacon-app/assets/images/icon.png",
        "src": "/home/nuno/.node_modules/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/web-default/icon.png"
      }
    }
  }
}
```
</details>
<details><summary>
[Babel Preset]
</summary>

- [✔︎ Not using .babelrc] Expo web runs best with Babel 7+
- [✔︎ Using `babel-preset-expo`] Tree-shaking should work as expected.
</details>

End Copy

Building Webpack bundle [====================] 100% (9.4 seconds) 

Build completed in 9.402s

nuno@mx-nuno:~/projects/beacon-app $

# package.json
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "dev": "BROWSER=none expo start --web --non-interactive",
    "dev:web": "expo start --web --non-interactive",
    "build:android": "expo build:android",
    "build:ios": "expo build:ios",
    "build:web": "expo build:web",
    "test": "node ./node_modules/jest/bin/jest.js --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "eslintConfig": {
    "extends": "universe/native"
  },
  "dependencies": {
    "expo": "^33.0.0",
    "expo-camera": "^5.0.1",
    "expo-image-manipulator": "^5.0.1",
    "expo-image-picker": "^5.0.2",
    "expo-permissions": "^5.0.1",
    "expo-web-browser": "^5.0.3",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
    "react-native-is-iphonex": "^1.0.1",
    "react-native-story-share": "^0.4.0",
    "react-native-svg": "^9.4.0",
    "react-native-view-shot": "^2.6.0",
    "react-native-web": "^0.11.2",
    "react-navigation": "^3.11.0",
    "react-redux": "^7.1.0",
    "redux": "^4.0.1",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "eslint": "^5.16.0",
    "eslint-config-universe": "^1.0.7",
    "jest-expo": "^33.0.0",
    "prettier": "^1.17.0"
  },
  "private": true
}
```

**Comment by limin9988** [comment]
Im having this tooo....
start a new project 
expo init web-test-project && cd web-test-project
expo build:web

in windows is working fine , the output web-build and files is generated
however in macOS , it will delete the web-build folder , but not generating  web-build

was on 
node v10.15.3
expo-cli 2.21.2

**Comment by NiciusB** [comment]
I've just pinned this down to PanResponder. It seems like if there's a file importing it, the build will just not do anything and not fire any error. When in dev mode, there's just a message in the console stating that it's not supported (even thought it seems to work fine)

**Comment by EvanBacon** [comment]
Unfortunately there are some issues with babel updates: https://github.com/expo/expo-cli/issues/842 I suspect that the react-native preset is using some babel plugins that are creating errors.

**Comment by EvanBacon** [comment]
This is related to the Webpack option [`optimization.noEmitOnErrors`](https://webpack.js.org/configuration/optimization/#optimizationnoemitonerrors). Your project has errors in it but by default Webpack doesn't surface these errors. I opened a PR to run a linter on the code and generate more warnings and errors. Hopefully this helps make debugging a lot more clear: https://github.com/expo/expo-cli/pull/845

**Comment by vjsingh** [comment]
@EvanBacon 

Once that PR goes in hopefully we'll be able to see the build errors and get to the bottom of it.

One thing I did notice is that when building webpack in dev mode (```expo start -w```) I get a ton of build errors for all of my absolutely imported files (using aliases). I wonder if this is related?
```Could not resolve "/Users/Varun/Documents/workspace/clyme/src/src/styles/RawTheme" in file /Users/Varun/Documents/workspace/clyme/src/src/App.tsx.```

See here for how I configured my babel.config.js https://forums.expo.io/t/help-resolving-absolute-imports-in-expo-33/23780

```babel.config.js```
```const path = require('path');

module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      [
        'module-resolver',
        {
          root: ["./"],
          alias:   {
            src: path.resolve(__dirname, 'src/src/'),
          }
        }
      ]
    ],
    env: {
      development: {
        "plugins": ["@babel/plugin-transform-react-jsx-source"]
      }
    }
  };
};```

```tsconfig.json```
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "src/*": ["src/src/*"],
    }
  }
}
```

**Comment by vjsingh** [comment]
@EvanBacon 

I upgraded to the new expo-cli with linting support, and tried running ```build:web```.

Getting the error copied below. I'm not sure what to do since the file doesn't reference any of my original source files, and the error is ambiguous.

Any ideas?

```
➜ expo build:web
clean-webpack-plugin: /Users/Varun/Documents/workspace/clyme/web-build has been removed.
Building Webpack bundle [====================] 100% (46.2 seconds)

Build completed in 46.266s

Failed to compile.

Failed to minify the bundle. Error: static/js/app.9ce3f209.chunk.js from Terser
Unexpected token keyword «var», expected punc «,» [static/js/app.9ce3f209.chunk.js:201,0]
    at /@expo/xdl@56.1.3/src/Webpack.js:189:25
    at finalCallback (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/Compiler.js:210:39)
    at /usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/Compiler.js:226:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/local/lib/node_modules/expo-cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/usr/local/lib/node_modules/expo-cli/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/Compiler.js:224:21)
    at /usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/Compiler.js:552:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/local/lib/node_modules/expo-cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/usr/local/lib/node_modules/expo-cli/node_modules/tapable/lib/Hook.js:154:20)
    at /usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/Compiler.js:549:30
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/local/lib/node_modules/expo-cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/usr/local/lib/node_modules/expo-cli/node_modules/tapable/lib/Hook.js:154:20)
    at /usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/Compilation.js:1312:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/local/lib/node_modules/expo-cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/usr/local/lib/node_modules/expo-cli/node_modules/tapable/lib/Hook.js:154:20)
    at /usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/Compilation.js:1303:32
    at eval (eval at create (/usr/local/lib/node_modules/expo-cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:19:1)
Read more here: https://bit.ly/CRA-build-minify
```

**Comment by flieks** [comment]
for me it worked to do build:web
