### ISSUE TITLE
npm outdated not implemented yet

### ISSUE THREAD

**Issue by alljamin** [expo/expo-cli#751]
## Description

Trying to follow the [React native getting started guide](https://facebook.github.io/react-native/docs/getting-started) and after `expo init AwesomeProject` running `npm outdated` says that it is not implemented yet. Is there any particular reason why I cannot run `npm outdated`?

## Expected Behavior

`npm outdated` either returns nothing if all the dependencies are up-to-date or it returns a list of outdated dependencies, neither of these two options take place after the `expo init AwesomeProject`.

## Observed Behavior

```
$ npm outdated
npm ERR! Not implemented yet

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.../.npm/_logs/2019-06-23T06_05_55_315Z-debug.log
```

## Environment

 Expo CLI 2.20.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.6 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.20.2

**Comment by EtienneBourque** [comment]
outdated is broken in npm 6.9.0, 6.9.1 and 6.9.2.

You can go back to 6.8.0 by doing
`npm i -g npm@6.8.0`

**Comment by EtienneBourque** [comment]
Update : npm outdated works again in the latest npm 6.10.0

**Comment by fson** [comment]
Looks like this was a problem with npm, and not expo-cli per se, and it's solved now. Closing this issue.
