### ISSUE TITLE
Duplicate assets path name when loading a local file

### ISSUE THREAD

**Issue by m1m6** [expo/expo-cli#752]
Hi,

I'm trying to load a local html file from my assets folder
```
const localUri = Expo.Asset.fromModule(
  require('../../../assets/analytics/analytics.html'),
);

```
the file got loaded, but the problem comes when an addition assets path got added to the localUri.uri path

here's an example of the output of localUri.uri 
 "html",
`"uri": "http://192.168.1.113:19001/assets/assets/intercom/intercom.html?platform=android&hash=b7f8ed17a6eb37cb8609261ed66e4843?platform=android&dev=true&minify=false&hot=false"`

rather it should be (without duplicate assets)
`"uri": "http://192.168.1.113:19001/assets/intercom/intercom.html?platform=android&hash=b7f8ed17a6eb37cb8609261ed66e4843?platform=android&dev=true&minify=false&hot=false"`

**Comment by EvanBacon** [comment]
Not sure what to make of this. Could you please fill out the issue template. Is this a web problem?

**Comment by ccheever** [comment]
hi @m1m6  -- are you sure that you put the right number of `../`s in your path?
If you can make https://stackoverflow.com/help/minimal-reproducible-example then we can investigate this. And like, @EvanBacon said, it will be a lot easier to look into this if you fill out the issue template.

**Comment by ccheever** [comment]
closing this for now, but reopen if you are still having an issue and can make an MRE for us to investigate.
