### ISSUE TITLE
Expo-init new-project permission denied

### ISSUE THREAD

**Issue by smrbts** [expo/expo-cli#763]
I am having an issue setting up a new react-native project through the expo cli. 
I ran : npm install -g expo-cli --> then the below "expo init AwesomeProject", and could not even enter any input for "choose a template"

Node version 12.4.0
NPM version 6.9.0

// ♥ expo init AwesomeProject 
? Choose a template: (Use arrow keys)
  ----- Managed workflow -----
❯ blank               minimal dependencies to run and an empty root component 
  blank (TypeScript)  same as blank but with TypeScript configuration 
  tabs                several example screens and tabs using react-navigation 
  ----- Bare workflow -----
  bare-minimum        minimal setup for using unimodules Uncaught Error [Error: EACCES: permission denied, open '/Users/myusername/.expo/state.json.2003686284'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/Users/myusername/.expo/state.json.2003686284'
}

**Comment by ide** [comment]
Could you verify the filesystem permissions of ~/.expo and the files in that directory, and make sure the user under which `expo-cli` is running has access to those files?

**Comment by smrbts** [comment]
I had previously installed some expo components with "sudo" and this was causing the issue. Instead of trying to brute force my way through, I uninstalled all .expo files, re-installed both node and npm properly using nvm, then the issue was cleared.

**Comment by ide** [comment]
Thanks for following up. In general it's almost always better not to use `sudo` with Node or Expo CLI. nvm is great because it sets things up in a sudo-less way, in contrast with the default Node installer, which used to install packages in a place where sudo was needed.
