### ISSUE TITLE
[SDK 31] Expo CLI displays HTTP requests

### ISSUE THREAD

**Issue by ide** [expo/expo-cli#77]
## Description

With SDK 31, the Expo CLI displays HTTP requests from the client. It used to show HTTP requests only from web browsers but not from the mobile client.

## Expected Behavior

Don't show HTTP requests from the client. Maybe hide them unless running with the `EXPO_DEBUG` environment variable set.

## Observed Behavior

Got messages like this in both the CLI and Metro Bundler section of the web UI:

```
[14:58:38] ::ffff:192.168.1.83 - - [08/Oct/2018:21:58:38 +0000] "POST /symbolicate HTTP/1.1" 200 - "-" "Expo/2.8.4 CFNetwork/974.2.1 Darwin/18.0.0"

[14:58:45] ::ffff:192.168.1.83 - - [08/Oct/2018:21:58:45 +0000] "GET /onchange HTTP/1.1" - - "-" "Expo/2.8.4 CFNetwork/974.2.1 Darwin/18.0.0"
```

## Environment

Expo CLI 2.2.0
macOS 10.14
Using master from the expo repo

## Reproducible Demo

Ran NCL with SDK 31 using Expo CLI. You don't need to do anything special.

**Comment by panda0603** [comment]
so is this a bug or intended? wonder what's the progress with this

**Comment by ide** [comment]
It’s not intended and happened because the React Native development tools introduced this bug.

**Comment by gerardo15** [comment]
@ide is there any temporary way to hide these? or in what file are these generated so i can figure something out?

**Comment by ide** [comment]
I suspect they are generated in one of the packages under `<your project>/node_modules/metro(-something)?`.

**Comment by brentvatne** [comment]
fixed in https://github.com/expo/expo-cli/commit/88aeb735808fe86da5789e699099cdf3fd0bfd74

you can install the latest expo-cli to get this
