### ISSUE TITLE
Just a little typo when `expo upload:ios`

### ISSUE THREAD

**Issue by MikaelConecto** [expo/expo-cli#777]
# Required format for issues

Not a big deal

## Description

When running `expo upload:ios` before running `expo build:ios` the quotation is not right.

## Expected Behavior

The text should look like this:
`Failed to upload the standalone app to the app store.
There are no builds on the Expo servers, please run 'expo build:ios' first`

## Observed Behavior

``Failed to upload the standalone app to the app store.
There are no builds on the Expo servers, please run 'expo build:ios first'``

**Comment by fson** [comment]
Would you like to send a PR? This is where the error comes from: https://github.com/expo/expo-cli/search?q=There+are+no+builds+on+the+Expo+servers&unscoped_q=There+are+no+builds+on+the+Expo+servers

**Comment by yokodev** [comment]
I' de like to help with this... Any particular way this should be done?

**Comment by fson** [comment]
Fixed in #790.
