### ISSUE TITLE
Expo Building JavaScript bundle Error

### ISSUE THREAD

**Issue by ilahishaikh** [expo/expo-cli#782]
Tunnel ready.
Unable to resolve "./app/Component/Main" from "App.js"
Failed building JavaScript bundle.
Unable to resolve "./app/Component/Main" from "App.js"
Building JavaScript bundle [===================================================================================== ] 99%

How can i solve

**Comment by mahmoudafer** [comment]
Hi, this is not an issue with expo-cli itself, it's an issuee related to your code, you're either importing the component Main from the wrong location or it doesn't exist. check the import line in your App.js and make sure you've got the file in the correct location
