### ISSUE TITLE
Expo CLI creates URLs of the form "localhost?line=<port>&column=0" for the browser UI page

### ISSUE THREAD

**Issue by edoantonioco** [expo/expo-cli#787]
## Description

When you run "npm run android" or "expo start", it opens the expo cli browser page.
The correct page would be "http://localhost:19002/", but it instead redirects me to "http://localhost/?line=19002&column=0"

## Expected Behavior

Expo cli should open "http://localhost:19002/"

## Observed Behavior

it opens "http://localhost/?line=19002&column=0", which does not exist

## Environment

Linux, latest version expo cli

## Reproducible Demo
 does not apply, it happens with any project.

**Comment by oguzkaganeren** [comment]
I get the same issue. Is there any solution?

**Comment by brentvatne** [comment]
is this still happening for you on linux?

**Comment by edoantonioco** [comment]
no, its not happening anymore

**Comment by brentvatne** [comment]
thanks for the follow up. sorry nobody got back to you before!
