### ISSUE TITLE
Expo app crashes if the bundler throws an error, forcing the simulator to be reopened.

### ISSUE THREAD

**Issue by shamilovtim** [expo/expo-cli#792]
## Description

If LiveReload is on and the user saves a file with poor JSX syntax (for instance accidentally having a `<View>` with no closing tag `</View>`) the CLI will throw an error in the command line but the expo app in the simulator crashes at 100% built. The simulator freezes and needs a CMD-W to shut it down. After the code is fixed the simulator must be reopened.

## Expected Behavior

If I have a syntax error the entire expo app shouldn't crash. It should allow the user to fix his code and then trigger a rebuild.

1. If code is so wrong that it breaks the expo app building, do not build the code in the first place. Have some compile time error checking, especially if the user is using TypeScript (as I currently am).
2. Even if the code is wrong, and it's allowed to be compiled, regardless of all of that it still should not crash the simulator. Have sort of graceful restart button inside. 

## Observed Behavior

```
Error text goes here!
```

## Environment

```
Expo CLI 2.20.0 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: yarn install v0.21.3
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.40s. - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.20 => 16.8.20
      @types/react-native: ^0.57.63 => 0.57.63
      @types/react-navigation: ^3.0.7 => 3.0.7
      expo: ^33.0.0 => 33.0.6
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.0 => 3.11.0
    npmGlobalPackages:
      expo-cli: 2.20.0
```

Also specify:

iPhone X 12.2
Version 10.2.1 (SimulatorApp-880.5 CoreSimulator-587.35)

**Comment by brentvatne** [comment]
i can't reproduce this issue, it may have been an intermittent issue on sdk33. if it continues on sdk35+ please create a new issue. apologies that you did not receive a response when this was originally posted! we'll try to respond more quickly in the future.
