### ISSUE TITLE
Windows Installation Error - This program is blocked by group policy. For more information, contact your system administrator - When doing expo init.

### ISSUE THREAD

**Issue by break-through** [expo/expo-cli#797]
## Description

After installing expo-cli in cmd/powershell with admin permissions, I then attempt to run expo init and create a new project, but it doesn't work.

## Expected Behavior

When doing expo init, it should start to ask me for my project name and such. 

## Observed Behavior

When I ran it, it says "this program is blocked by group policy. For more information, contact your system admin." But this is my PC, and this makes no sense. I don't know how to allow it through group policy, nor can I find anyone else who has had this issue.

```
This program is blocked by group policy. For more information, contact your system admin.
```

## Environment

Say the same thing:
This program is blocked by group policy. For more information, contact your system admin.

Also specify:

Windows 10, on cmd

## Reproducible Demo
Just install, and type in expo init, and if this happens to you, it has been reproduced (the group policy error).

**Comment by AdamJNavarro** [comment]
Hey @break-through,

As the error describes, this is due to a firewall/group policy from your OS. You'll have to look into how to handle this on Windows 10 as it's not something we can control on our end.

Cheers,
Adam
