### ISSUE TITLE
Show more human-readable errors when computer cannot connect to AWS/GCP

### ISSUE THREAD

**Issue by Changdao** [expo/expo-cli#806]
![image](https://user-images.githubusercontent.com/2177183/60568494-94018800-9d9f-11e9-89b2-a3cf5d325d75.png)

**Comment by Changdao** [comment]
YOU, EXPO, SERVICE heavily depends on Cloud service, but has no fail-over/high-available design.
In fact, I investigate into your script, which is trivial and wasting time.
![image](https://user-images.githubusercontent.com/2177183/60570293-daf17c80-9da3-11e9-846d-dece987fc5e3.png)
can not be connected. Which is a instable service to us.
And there is no retry method and other easy to recover method to solve the environment problem.
The following is my suggestions:
1. if you depends on remote service, please implicityly tell the developer which service is not reachable.
2. Add more document and notice to tell the user, expo is not easy working in "detach" mode.
3. Support intuitive tool to help developer organize the "detach" process.
4. Provide effective method to import native Android/iOS component into expo instead of "detach"
That's all, thank you.

**Comment by Changdao** [comment]
Please understand a CHINSE developer's SPECIAL concern.

**Comment by Changdao** [comment]
![image](https://user-images.githubusercontent.com/2177183/60731114-43458700-9f79-11e9-9fb3-bd62ab48d6d2.png)
Hang here, why don't you give more detail about the network activity?

**Comment by ide** [comment]
We rely on AWS CloudFront, which is already responsible for being highly available and having its own failover at the DNS level. If there is an issue with your network connection preventing you from connecting to one of the largest / the largest CDN on the planet, that is out of the scope of our infrastructure at the moment.

I agree we could make the error message clearer and more human-readable and have changed the title of this issue appropriately.

**Comment by Changdao** [comment]
![image](https://user-images.githubusercontent.com/2177183/64007022-ff6c9980-cb45-11e9-9437-10494dc12525.png)

**Comment by Changdao** [comment]
Please refer to the above message?
What did we get from it? Just nothing.
It's strong recommend that expo could provide more useful information

**Comment by EvanBacon** [comment]
I recently took a pass at upgrading the error messages for asset uploading in #2517 if you run into any more confusing error messages please feel free to open a new issue!
