### ISSUE TITLE
Updated to  Expo CLI 2.21.2 and SQLite insert no longer works

### ISSUE THREAD

**Issue by GalacticSmarties** [expo/expo-cli#809]
# READ THIS FIRST, PLEASE!

We're looking to keep questions on our forums and bug reports on the GitHub repo -- please choose whichever you feel is more appropriate for your issue:

- Post in our community forums (log in with your Expo developer account): https://forums.expo.io/c/help
- File a bug on the Expo CLI repo (for bugs related to the Expo CLI tools): https://github.com/expo/expo-cli/issues/new
- File a bug on the main Expo repo (for other bugs): https://github.com/expo/expo/issues/new
- Request a feature on Canny: https://expo.canny.io/feature-requests

Thanks for reporting the issue you found with Expo CLI!

# Required format for issues

Please make our job easier by filling this template out to completion.

## Description

Since updating to  expo-cli@2.21.2  getting " Cound not find proper type in SQLite module" (TYPO IS NOT MINE)

## Expected Behavior

Until the update, this command did an insert to the SQLite DB.

## Observed Behavior

What actually happened when you performed the above actions?
      DB was not written to

Error text goes here!
   Cound not find proper type in SQLite module
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:55 in <unknown>
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:414:4 in __invokeCallback
- ... 4 more stack frames from framework internals

## Environment
Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.4.1 - /usr/local/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.6 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.14.0
Also specify:

- Phone/emulator/simulator platform, model and version:
Android 9 emulator for Pixel 2 API 28

**************************************************************************
**** This does NOT happen when running iOS simulator for iPhone 6s 12.2
instead, it writes my Date Time object as 
{
}
***********************************************************************

I suspect that there is something about Date/Time in SQLite that has changed since SDK 33. However, Android was working until I updated the cli a couple of hours ago

## Reproducible Demo

I would love to- and will try to get to that on Monday - but need to skedaddle. Wanted to get this to you all as quickly as possible.

**Comment by Xrew** [comment]
I have exactly the same problem...is there any solution or workaround?

**Comment by Xrew** [comment]
It is definitely caused by Date type, but I do not know why. 

I am trying to insert date as a text: 2019-07-11T07:09:03.798Z
It should by OK, it is ISO8601 (https://www.sqlite.org/datatype3.html), but it causes this: [Error: Cound not find proper type in SQLite module]

It works before upgrade to SDK33 correctly.

**Comment by Xrew** [comment]
The problem is also discussed here: https://forums.expo.io/t/sdk-33-sqlite-date-bug/24674

**Comment by Xrew** [comment]
Ok, I have found a solution.

The problem is, that I pass Date object param to tx.executeSql instead of STRING. There was propably some automatic conversion. In console log it was "OK", because console converted it automatically too.

If I manually convert Date to String throught .`toISOString()`, than it works correctly.

**Comment by GalacticSmarties** [comment]
https://forums.expo.io/t/sdk-33-sqlite-date-bug/24674/3 - 
@xsychr03 found a solution - use .toISOString() to convert dates to strings before storing them in SQLite db.
I also change my create table to create the date fields as text.
