### ISSUE TITLE
`expo build:ios` usability improvements

### ISSUE THREAD

**Issue by esamelson** [expo/expo-cli#81]
A few usability improvements for the `expo build:ios` credentials step that @EvanBacon suggested:
- we should be more deliberate about which errors should cause the process to exit -- e.g. if there is an error with Apple credentials we may want to let the user retry without having to go through the publish step again.
- we should allow people to pass their username (and perhaps password) as a param, e.g. `expo build:ios -u my@apple.id`
- Fastlane only needs your apple password once and then it remembers it if you use the same username. Can we do something like that as well?

**Comment by fson** [comment]
We should use a command-line flag for the username and an environment variable such as `EXPO_APPLE_ID_PASSWORD` for the password (so people wouldn't write passwords in their CI scripts).

Fastlane stores the iTunes authentication cookies in a file after a successful login, so I think we should be able to just stop passing the password to `Spaceship::Portal.login` and it would then use the existing session or ask the user to provide a password.

**Comment by fson** [comment]
We should allow a command-line flag for the username and an environment variable for the password (so people wouldn't be encouraged to write passwords in their CI scripts).

If no password is given, [Fastlane first looks for the password](https://github.com/fastlane/fastlane/blob/347474dcba2b46654388da34d594314c712a7c4d/credentials_manager/lib/credentials_manager/account_manager.rb#L47-L58) in the `FASTLANE_PASSWORD` or `DELIVER_PASSWORD` environment variables, then from the macOS keychain and finally, if not found, prompts the user to enter a password. So I think we could just stop passing the password to `Spaceship::Portal.login` and it would behave like Fastlane and only ask for the password when necessary. We'd document that we also accept the password via `FASTLANE_PASSWORD` env variable.
