### ISSUE TITLE
node_modules/expo/build/Linking/Linking.js: Unknown helper objectSpread2

### ISSUE THREAD

**Issue by ibogdan94** [expo/expo-cli#820]
Hi guys
I have a problem after updating SDK33 (Please, see the screenshot)

http://joxi.ru/52aLVn4UEQMWom

  Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.3.1 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.13 => 32.0.13 
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^2.16.0 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.21.2`

My babel.config.js http://joxi.ru/v29kVOZiZK8LYr

**Comment by ide** [comment]
This may have been an issue with Babel 7.5.0 that was fixed in 7.5.1. I would try updating your lockfile if you have one and try again.

**Comment by ibogdan94** [comment]
@ide thanks for the answer
I resolved this issue by migration from the js to TS anyway :)
