### ISSUE TITLE
ERROR: Node.js version 10.10.0 is no longer supported.

### ISSUE THREAD

**Issue by Gregoirevda** [expo/expo-cli#821]
Expo-cli v3.0 throws an error when executing `expo login` 
`ERROR: Node.js version 10.10.0 is no longer supported.`

Which NodeJS version should we use for the expo-cli 3* version?

**Comment by ide** [comment]
See here: 
https://github.com/expo/expo-cli/blob/3f771778207922b20b63e30d965ec180915c217b/packages/expo-cli/bin/expo.js#L7-L11

```js
var supportedVersions = [
  { range: '>=8.9.0 <9.0.0', name: 'Maintenance LTS' },
  { range: '>=10.13.0 <11.0.0', name: 'Active LTS' },
  { range: '>=12.0.0', name: 'Current Release' },
];
```
