### ISSUE TITLE
v3.0.0 build:android fails with property error

### ISSUE THREAD

**Issue by brunogirin** [expo/expo-cli#822]
# Required format for issues

## Description

Running the `build:android` command with expo-cli v3.0.0, the command fails with an error. It works with expo-cli v2.21.2

## Expected Behavior

Ran `expo build:android`
The command should succeed with no error.

## Observed Behavior

The command fails if the expo-cli version is 3.0.0 but works if it is a 2.x version (I tried with 2.20.11 and 2.21.2).

```
$ expo build:android
[16:18:49] Cannot read property 'readConfigJsonAsync' of undefined
[16:18:49] TypeError: Cannot read property 'readConfigJsonAsync' of undefined
    at Object.checkSplashScreenImages (/@expo/xdl@56.0.0/src/Android.ts:359:37)
    at AndroidBuilder._callee$ (/expo-cli@3.0.0/src/commands/build/AndroidBuilder.js:27:19)
    at tryCatch (/usr/local/share/.config/yarn/global/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/share/.config/yarn/global/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/share/.config/yarn/global/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/usr/local/share/.config/yarn/global/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/share/.config/yarn/global/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

```
  Expo CLI 3.0.0 environment info:
    System:
      OS: Linux 4.19 Debian GNU/Linux 9 (stretch) 9 (stretch)
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.3.2 => 3.3.2 
```

Also specify:

- Phone/emulator/simulator platform, model and version: N/A

## Reproducible Demo

No reproducible demo at this time as it felt like a straighforward regression that you would want to know about fairly quickly.

**Comment by branislavantic87** [comment]
I have same problem. Everything was smooth, after installing update of expo-cli this error appeared when application should run on emulator. iOS also has this problem.

**Comment by zacharywenner** [comment]
Just upgraded to 3.0.0 and having this issue trying to start the iOS simulator as well.

**Comment by antronic** [comment]
I also have the same issue. I pined for it!

**Comment by branislavantic87** [comment]
Not sure what was previous version of expo, you can roll back and work if you don't want to wait this issue fixed. npm install -g expo-cli@2.21.2

**Comment by laurentnguyen** [comment]
Same issue when trying to run on iOS simulator.

**Comment by romainbriand** [comment]
Same issue here with iOS simulator after upgrading to expo-cli@3.0.0

![image](https://user-images.githubusercontent.com/183016/60755565-c60a2880-9ff1-11e9-82eb-ba79284d4942.png)

**Comment by brunogirin** [comment]
> Not sure what was previous version of expo, you can roll back and work if you don't want to wait this issue fixed. npm install -g expo-cli@2.21.2

The latest v2.x was 2.21.2 at the time when I filed this issue.

**Comment by AdamJNavarro** [comment]
Hey all, we rolled back the `latest` to `2.21.1`. Sorry for the inconvenience, we'll push `3.x` out again once we've fixed said issues.

**Comment by sendyputra** [comment]
i still got error after rolled back to 2.21.1 and debug report on the below

`TypeError: Cannot read property 'readConfigJsonAsync' of undefined
    at Object.openProjectAsync (/@expo/xdl@56.0.0/src/Simulator.ts:470:35)`

## My Environment

Expo CLI 3.0.0 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.5.0 - /usr/local/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 6.10.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 2.21.1

**Comment by luke-john** [comment]
Just got this on error on expo cli 3.0.1 as well

```sh
$ yarn expo diagnostics

 Expo CLI 3.0.1 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /var/folders/4s/2r_6vqj57mgfg235sws12rkh0000gn/T/yarn--1563535020078-0.8389878561514317/node
      Yarn: 1.16.0 - /var/folders/4s/2r_6vqj57mgfg235sws12rkh0000gn/T/yarn--1563535020078-0.8389878561514317/yarn
      npm: 6.9.0 - /usr/local/opt/node@10/bin/npm
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/react-native: ^0.57.56 => 0.57.56 
      expo: ^33.0.7 => 33.0.7 
      react: ^16.8.6 => 16.8.6 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
```

**Comment by Junaagnah** [comment]
I was getting the same issue on iOS simulator (did'nt try with Android emulator) but reinstalling expo solved the issue for me.
