### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by ravibhagat** [expo/expo-cli#825]
Not able to install on window 10.
NPM version: 6.9.0
Node version: v12.6.0
--------------------------------------------------------------
$ npm install -g expo-cli --verbose
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '-g',
npm verb cli   'expo-cli',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@6.9.0
npm info using node@v12.6.0
npm verb npm-session bdb6a50253e4e207
npm http fetch GET 304 https://registry.npmjs.org/expo-cli 464ms (from cache)
npm timing stage:loadCurrentTree Completed in 579ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
npm http fetch GET 304 https://registry.npmjs.org/babel-runtime 380ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ansi-regex 390ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/axios 391ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/base32.js 101ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/boxen 100ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/chalk 96ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/cli-table 103ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/commander 121ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/dateformat 121ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/delay-async 97ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/enquirer 94ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/envinfo 94ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-extra 105ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/getenv 106ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/es6-error 135ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/indent-string 118ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/glob 121ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/inflection 116ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/inquirer 89ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/klaw-sync 94ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lodash 100ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@expo%2fbunyan 1146ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/match-require 135ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/npm-package-arg 130ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/open 124ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ora 113ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/pngjs 105ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/progress 104ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/pacote 114ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/qrcode-terminal 126ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@expo%2fsimple-spinner 1412ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@expo%2fxdl 1415ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/request 115ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@expo%2fconfig 1430ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/semver 115ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/slash 118ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/split 23ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/untildify 118ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@expo%2fspawn-async 1544ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/source-map-support 150ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/wordwrap 118ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/validator 124ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@expo%2fdev-tools 1567ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@expo%2fjson-file 1597ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@expo%2ftraveling-fastlane-linux 1144ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@expo%2ftraveling-fastlane-darwin 1378ms (from cache)
npm timing stage:rollbackFailedOptional Completed in 1ms
npm timing stage:runTopLevelLifecycles Completed in 3427ms
npm verb stack SyntaxError: Unexpected end of JSON input while parsing near '...:"^3.5.1"},"_hasShrin'
npm verb stack     at JSON.parse (<anonymous>)
npm verb stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
npm verb stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50
npm verb stack     at processTicksAndRejections (internal/process/task_queues.js:85:5)
npm verb cwd C:\Users\ravi.bhagat
npm verb Windows_NT 10.0.17134
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "expo-cli" "--verbose"
npm verb node v12.6.0
npm verb npm  v6.9.0
npm ERR! Unexpected end of JSON input while parsing near '...:"^3.5.1"},"_hasShrin'
npm verb exit [ 1, true ]
npm timing npm Completed in 5242ms

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ravi.bhagat\AppData\Roaming\npm-cache\_logs\2019-07-08T13_42_35_895Z-debug.log

**Comment by AdamJNavarro** [comment]
Hey @ravibhagat,

Can you share your environment information? OS and version, Node version, etc.

Cheers,
Adam

**Comment by ravibhagat** [comment]
![image](https://user-images.githubusercontent.com/17745162/60863558-c0ede900-a23e-11e9-80d1-4fd5eb864ad7.png)

**Comment by ravibhagat** [comment]
C:\Users\ravi.bhagat>node -v
v12.6.0

C:\Users\ravi.bhagat>npm -v
6.9.0

**Comment by lewatt23** [comment]
@ravibhagat please I have the same issue, since now about a week yarn and npm are not able to install expo-cli, please how did you resolve it?

**Comment by oguzhanali** [comment]
Windows users can try delete local node_modules_global/node_modules/expo_cli folder then try npm install -g expo-cli

**Comment by brentvatne** [comment]
from https://github.com/expo/expo-cli/issues/2084#issuecomment-625428161

> hi there! this is a probably that people occasionally encounter with npm on windows: https://stackoverflow.com/questions/47675478/npm-install-errorunexpected-end-of-json-input-while-parsing-near-nt-webpack
>
> to resolve it, run:
>
> ```
> npm cache clean --force
> npm install -g expo-cli
> ```
