### ISSUE TITLE
'expo diagnostics' does not work on Linux

### ISSUE THREAD

**Issue by edoantonioco** [expo/expo-cli#828]
# Required format for issues

Please make our job easier by filling this template out to completion.

## Description
"expo diagnostics" command does not work

## Expected Behavior
'expo diagnostics' should provide data about the host system

## Observed Behavior

It shows this error output instead:

```
Cannot read property '1' of null
Set EXPO_DEBUG=true in your env to view the stack trace.
```

## Environment

Cannot read property '1' of null
Set EXPO_DEBUG=true in your env to view the stack trace.

OS: Linux manjaro

**Comment by AdamJNavarro** [comment]
Hey @edoantonioco,

What version of the `cli` is this occurring on?

Cheers,
Adam

**Comment by edoantonioco** [comment]
version 2.21.2

**Comment by fson** [comment]
Hiw @edoantonioco, could you run this command and copy paste the output:
```
EXPO_DEBUG=true expo diagnostics
```
(The `EXPO_DEBUG` environment variable makes the CLI print the stacktrace which would be helpful for fixing this issue.)

**Comment by edoantonioco** [comment]
```
]$ EXPO_DEBUG=true expo diagnostics
Cannot read property '1' of null
TypeError: Cannot read property '1' of null
    at /usr/lib/node_modules/expo-cli/node_modules/envinfo/dist/envinfo.js:1:97131
    at async Promise.all (index 0)
    at action (/expo-cli@3.4.1/src/commands/diagnostics.js:5:14)
    at Command.<anonymous> (/expo-cli@3.4.1/src/exp.ts:81:7)

```

**Comment by kathawala** [comment]
+1 I also have this issue. Exact same output of `EXPO_DEBUG=true expo diagnostics`

**Comment by EvanBacon** [comment]
Possibly fixed since upgrading to the latest version of `envinfo`.
