### ISSUE TITLE
Newly built iOS apps `Missing Push Notification Entitlement`

### ISSUE THREAD

**Issue by cruzach** [expo/expo-cli#830]
##  Description

The default configuration on newly built iOS apps submitted to the app store get a rejection stating:

> Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. Xcode does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file.

## Expected Behavior

Push Notifications should be enabled by default

## Observed Behavior

As of now, devs need to go to https://developer.apple.com/ then navigate to the specific App ID, and check the `Push Notifications` capability`

## Environment

Expo CLI 2.21.1 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.6.0 - ~/.nvm/versions/node/v11.6.0/bin/node
      Yarn: 1.17.0 - /usr/local/bin/yarn
      npm: 6.1.0 - ~/.nvm/versions/node/v11.6.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
    npmGlobalPackages:
      expo-cli: 2.21.1

## Reproducible Demo

Build a new iOS binary, and submit. 

[Relevant forum post](https://forums.expo.io/t/how-to-fix-missing-push-notification-entitlement/19615/8) with a little more info as to the workaround

Looks like [this PR](https://github.com/expo/expo-cli/pull/744) solved the same issue, but for adhoc builds

**Comment by ide** [comment]
If anyone is planning to work on this, go ahead and re-assign this to yourself.

**Comment by brentvatne** [comment]
@wkozyra95 - any insight on this?

**Comment by cruzach** [comment]
Would just changing [this line](https://github.com/expo/expo-cli/blob/master/packages/expo-cli/src/commands/build/ios/credentials/generate.js#L14) to include an `options` object of `{ enablePushNotifications: true }`, similar to [this change](https://github.com/expo/expo-cli/commit/ee99925aa041299ecdf29b3cb0b2b6c3370a86d2#diff-94c2d45864d854c1ac55297557274a13), enable push notifications by default?

**Comment by wkozyra95** [comment]
As far I understand this happens only when apple id already exists if we are creating new one Push Notification Entitlements should be added.

**Comment by LouisJS** [comment]
You might be interested by this issue (https://github.com/expo/expo-cli/issues/608)
And more particularly by the answer from sakettawde

I've had the same issue. Going in my Apple Profiles, i've seen the one i was using was invalid. Just follow the well explained guideline from the comment, and you're done ;)

**Comment by wkozyra95** [comment]
sakettawde answer is correct with the exception of one point
> Click on Create Certificate for Production SSL Certificate

this point is not necessary.

Only thing you actually need to do is enable in app id and run `expo build:ios --clear-provisioning-profile --revoke-credentials`

**Comment by brentvatne** [comment]
🎉

**Comment by LouisJS** [comment]
Nice ! Congrats guys ! 🤩

**Comment by dsokal** [comment]
This should be fixed in the next release of expo-cli :)
