### ISSUE TITLE
Update gitignore when ejecting

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#832]
This would be useful so people don't accidentally commit their build directories

**Comment by anatula** [comment]
After doing `expo eject` the `gitignore` file remained the same, resulting in 2k+ changes to commit. I'm going to use the one from [expo-template-bare-typescript/gitignore](https://github.com/expo/expo/blob/master/templates/expo-template-bare-typescript/gitignore) Using `expo --version 3.11.1`.

**Comment by brentvatne** [comment]
my only concern about updating it is we might want to ask people if they want it to be updated automatically or not, because it could be annoying to have your custom gitignore updated without consent

**Comment by EvanBacon** [comment]
Fixed in 92e47d7
