### ISSUE TITLE
OTA Updates - One publish is linked to different release channels

### ISSUE THREAD

**Issue by YoshiYo** [expo/expo-cli#834]
## Description

I have some problems with the release channels. 
I create two builds on two different channels. For my example it will be : 
`production` and `staging`

## Expected Behavior
App version `1.0.7`
Publish on the different channels will publish to each channel respectively.
`expo-cli build:ios --release-channel production`
`expo-cli build:ios --release-channel staging`

Next, i will launch an OTA update on staging.
`expo-cli publish --release-channel staging`
`staging` will receive a new OTA update.
It will not update the `production` channel.

## Observed Behavior
App version `1.0.7`
`expo-cli build:ios --release-channel production`
`expo-cli build:ios --release-channel staging`

Next, i will launch an OTA update on staging.
`expo-cli publish --release-channel staging`
`staging` will receive a new OTA update.
`production` will receive a new OTA update.

## Environment

```
Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.npm-packages/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.7 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.21.2
```

I don't know if I miss-understood a concept, but I can't explain why different release channels can be related to one publish on a specific channel. It occurs two times on my side.

**Comment by WahidHasanAriyanto** [comment]
same behaviour happened here

**Comment by erikdao** [comment]
@YoshiYo Hi,
Have you figured out the cause of this issue and did you have any solution for it?
Turns out that I'm dealing with the same thing now.

**Comment by brentvatne** [comment]
i believe this must have been an intermittent issue. i cannot reproduce this locally.

i created a new project, published something to the `staging` release channel and then changed it slightly and published to the `production` release channel. next i ran `expo build:ios -t simulator --release-channel staging --no-publish`. i downloaded and installed the app in the simulator, it used the staging release as expected. i then ran `expo publish --release-channel production` and reloaded the app a few times and it was not impacted.
