### ISSUE TITLE
Expo build:web does not generate any files

### ISSUE THREAD

**Issue by vjsingh** [expo/expo-cli#837]
## Description

```expo build:web``` does not generate any files.

**EDIT:** ```expo build:web -d``` (development) appears to work as expected.

## Expected Behavior

I expected files to be created in web-build/

## Observed Behavior

Upon running ```expo build:web```, I get the below output, and no new files are generated in my folder.
```
clean-webpack-plugin: /Users/Varun/Documents/workspace/clyme/web-build has been removed.
Building Webpack bundle [====================] 100% (28.7 seconds)

Build completed in 28.717s
```

A note that running ```expo start -w``` does work. Also, I was able to successfully use ```expo build:web``` in a brand new ```expo init``` project, but am unsure how to further debug my current setup, or create a reproducible demo.

Related files:
```webpack.config.js```
```
const createExpoWebpackConfigAsync = require('@expo/webpack-config');
const path = require('path');

module.exports = async function(env, argv) {
  const config = await createExpoWebpackConfigAsync(env, argv);
  config.resolve.alias['src'] = path.resolve(__dirname, 'src/src');
  return config;
};
```

```package.json```
```
...
  "main": "node_modules/expo/AppEntry.js",
...
```
## Environment

```
  Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/v10.16.0/bin/node
      Yarn: 1.17.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/v10.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.19 => 16.8.23
      @types/react-native: ^0.57.60 => 0.57.65
      expo: ^33.0.0 => 33.0.7
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
      react-navigation: ^2.0.4 => 2.18.3
    npmGlobalPackages:
      expo-cli: 2.21.2
```

**Comment by EvanBacon** [comment]
I noticed that I get this same bug when using node v12. Can confirm it works on node v10.14.1. Could you let me know if this doesn't fix your problem.

**Comment by vjsingh** [comment]
@EvanBacon Using Node v10.14.1 unfortunately does not fix the problem for me. Let me know if there's anything else I can do to help debug the issue.

**Comment by EvanBacon** [comment]
Duplicate https://github.com/expo/expo-cli/issues/749
