### ISSUE TITLE
Can't install it. Freeze at "extract to" for hours and never ends.

### ISSUE THREAD

**Issue by GuilhermeEsdras** [expo/expo-cli#840]
My Node Version: v10.16.0
I was able to install react-native normally. Even running it on an Android emulator, though, my computer is too slow and I can not use it right, so I need to run it on my smartphone.

So, I tried:
>npm install expo-cli --global (I tried npm install expo-cli too but didnt worked)

npm WARN deprecated joi@14.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated @babel/polyfill@7.4.4: 🚨 As of Babel 7.4.0, this
npm WARN deprecated package has been deprecated in favor of directly
npm WARN deprecated including core-js/stable (to polyfill ECMAScript
npm WARN deprecated features) and regenerator-runtime/runtime
npm WARN deprecated (needed to use transpiled generator functions):
npm WARN deprecated
npm WARN deprecated   > import "core-js/stable";
npm WARN deprecated   > import "regenerator-runtime/runtime";
npm WARN deprecated joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN tarball tarball data for @expo/traveling-fastlane-linux@1.9.9 (sha512-DKfeDhfeXmYhfM/CT7yiPjyvEMFyLvEDuKU3RIdieMZ3CJOobTkdaOQlQd39VYZ+q1a1qL5QvTiIlPvcSXv9PQ==) seems to be corrupted. Trying one more time.

I tried several times and the same problem always occurs. Always lock in an extraction.

**Comment by devlinb** [comment]
Can confirm this on Windows 10, gets stuck at @expo/traveling-fastlane-linux

**Comment by lewatt23** [comment]
same here stuck at @expo/traveling-fastlane-linux

**Comment by lewatt23** [comment]
any work around ?

**Comment by lewatt23** [comment]
I think the problem is the latest version when i install version  2.20.2 everything when well

**Comment by lewatt23** [comment]
@GuilhermeEsdras found a solution?

**Comment by oguzhanali** [comment]
Windows users can try delete local node_modules_global/node_modules/expo_cli folder then try npm install -g expo-cli

**Comment by lewatt23** [comment]
@oguzhanali  please where is it found ?

**Comment by oguzhanali** [comment]
@lewatt23 default location is under your windows' selected user folder. Just file search for node_modules_global

**Comment by lewatt23** [comment]
@oguzhanali  nothing works tried that too but does not work, even I just reinstalled node and yarn but still the same problem......am just fade up is been days now that I can't get expo working

**Comment by azoz158** [comment]
Anyone solved this problem?

**Comment by pilov-pa** [comment]
I had the same problem. Upgrading npm to the latest version solved it

**Comment by KingTigre** [comment]
@FernandoAlbiero same here, the package installation wont go past this package

**Comment by KingTigre** [comment]
OK guys, I was wable to go through it... Initially, I tried, without success, to: 

1. - do a npm cache verify and npm cache clean, but it did not help. 
2. -  Tried to uninstall nodejs (it was the windows installer) and then install it again using nvm, but the issue persisted
3.-Tried to update NPM using npm i @latest -g, but did not have any success

Even though those things did not work suddenly,I believe that what worked for me was quite a combination of what I had tried
1. - Switch from windows installer nodejs version to a node version management installation
2.-Update the npm to the latest version
3.- do a npm cache verify
4.-Try to install expo

I am not sure why I was not able to install it before... I am trying it for days, and I do have the impression that I had followed these steps before, even in an unordered manner. The most notable thing is that I had done npm cache verify folllowed by attempts to install explo-cli without success, but the last time that I tried, it worked.

I hope this can help any of you guys

**Comment by FernandoAlbiero** [comment]
Idk but i'm suspicious that the problem is because i trying to install expo-cli on 32 bit machine. I tried on another 3 PC's with 64 bits architecture and installed it without a problem.

I also found this: https://github.com/expo/expo-cli/issues/605
I tried "npm i -g exp", it installed successfull but didn't worked as expected.

What architecture are u guys using? 32 or 64 bit?

**Comment by devlinb** [comment]
@FernandoAlbiero 64bit here.

**Comment by FernandoAlbiero** [comment]
Well, i gived up, i had to change the computer to solve to issue.

**Comment by fran893** [comment]
I had the same problem and the only solution i got was delete the folder "node_modules" inside npm folder, C:\Users\{userName}\AppData\Roaming\npm

**Comment by fernandoalb12** [comment]
Well, i solved the issue using the git shell instead of cmd.
Command used: npm install -g expo-cli.
I hope this help you.

**Comment by FernandoAlbiero** [comment]
Well, i solved the issue using the git shell instead of cmd.
Command used: npm install -g expo-cli.
I hope this help you.

**Comment by nitinsharmacs** [comment]
for lubuntu users, it worked by following steps,
1. npm cache verify
2. sudo npm install -g expo-cli

thats it!

**Comment by EvanBacon** [comment]
I've removed Fastlane in the latest version `expo-cli@4.1.0`. Installs should be far more stable on all computers now!
