### ISSUE TITLE
Error when installing a iOS simulator artifact

### ISSUE THREAD

**Issue by rodrigorm** [expo/expo-cli#841]
# READ THIS FIRST, PLEASE!

We're looking to keep questions on our forums and bug reports on the GitHub repo -- please choose whichever you feel is more appropriate for your issue:

- Post in our community forums (log in with your Expo developer account): https://forums.expo.io/c/help
- File a bug on the Expo CLI repo (for bugs related to the Expo CLI tools): https://github.com/expo/expo-cli/issues/new
- File a bug on the main Expo repo (for other bugs): https://github.com/expo/expo/issues/new
- Request a feature on Canny: https://expo.canny.io/feature-requests

Thanks for reporting the issue you found with Expo CLI!

# Required format for issues

Please make our job easier by filling this template out to completion.

## Description

Error when installing a iOS build in Simulator.

## Expected Behavior

I have a functional test suite using Detox which build a iOS simulator using `expo build:ios`, download the artifact using `expo url:ipa` and run tests using `detox test`.

The expected behavior is the app to be installed in iOS simulator and detox tests to pass.

## Observed Behavior

The detox tool is unable to install the downloaded artifact in iOS simulator.

If there's an error message, please paste the _full terminal output and error message_ in this code block:

```
app: detox[43015] ERROR: [exec.js/EXEC_FAIL, #6] "/usr/bin/xcrun simctl install 8D798521-2E5E-4027-835B-92CA69C6354B "/Users/travis/build/zaxapp/zaxstore/packages/app/build/zaxapp.app"" failed with code = 1, stdout and stderr:
app: 
app: detox[43015] ERROR: [exec.js/EXEC_FAIL, #6] 
app: detox[43015] ERROR: [exec.js/EXEC_FAIL, #6] An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
app: This app could not be installed at this time.
app: Failed to chmod /Users/travis/Library/Developer/CoreSimulator/Devices/8D798521-2E5E-4027-835B-92CA69C6354B/data/Bundle/Application/E813980E-087A-4525-AEDE-A76A1B19255D/zaxapp.app/BrComZaxappAppbeta : No such file or directory
app: Failed to chmod /Users/travis/Library/Developer/CoreSimulator/Devices/8D798521-2E5E-4027-835B-92CA69C6354B/data/Bundle/Application/E813980E-087A-4525-AEDE-A76A1B19255D/zaxapp.app/BrComZaxappAppbeta : No such file or directory
app: Underlying error (domain=MIInstallerErrorDomain, code=4):
app: 	Failed to chmod /Users/travis/Library/Developer/CoreSimulator/Devices/8D798521-2E5E-4027-835B-92CA69C6354B/data/Bundle/Application/E813980E-087A-4525-AEDE-A76A1B19255D/zaxapp.app/BrComZaxappAppbeta : No such file or directory
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

```
❯ expo diagnostics
┌─────────────────────────────────────────────────────────────┐
│                                                             │
│   There is a new version of expo-cli available (2.21.2).    │
│   You are currently using expo-cli 2.19.4                   │
│   Run `npm install -g expo-cli` to get the latest version   │
│                                                             │
└─────────────────────────────────────────────────────────────┘

  Expo CLI 2.19.4 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.0.7 - /usr/local/bin/bash
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 9.3.1/9E501 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^4.1.11 => 4.1.16 
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.5.1 
    npmGlobalPackages:
      expo-cli: 2.19.4
```

Also specify:

- Phone/emulator/simulator platform, model and version:

iOS Simulator iPhone X, iOS 11.1

**Comment by rodrigorm** [comment]
What I have found according to the error message is the `BrComZaxappAppbeta` come from `Info.plist` file `CFBundleExecutable` configuration, but the correct value should be `ExpoKitApp`.

This configuration has been changed recently in the #836 and maybe is the source of this problem.

Can you guys give me information how to resolve this? I can provide a pull request but I does know how to validate the issue and the fix.

**Comment by supryan** [comment]
@rodrigorm I can also confirm this issue. Adding the `CFBundleExecutable` Info.plist key worked for me to fix the chmod error. Otherwise, building for the simulator outputs a camelcased version of my `bundleIndentifier`.

```json
"ios": {
  "infoPlist": {
    "CFBundleExecutable": "ExpoKitApp"
  },
}
```
Enviroment:

```zsh
» expo diagnostics                                                                                                                                                                                                                                                                                                                                                         Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.12.0 - ~/.nvm/versions/node/v10.12.0/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.12.0/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.2 => 31.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1
      react-navigation: ^3.0.7 => 3.0.9
    npmGlobalPackages:
      expo-cli: 2.21.2
```

Device:  `iOS Simulator iPhone 7, iOS 12.2`

**Comment by dsokal** [comment]
Anyone who is experiencing the issue - the fix has been just deployed to our builders. Please rebuild your apps. Sorry for the inconvenience!

**Comment by rodrigorm** [comment]
It's woking now @dsokal. Thank you!

**Comment by JorgeMoralesLopez** [comment]
I can't install my .ipa app in the xCode simulator, it throws me this error "operation coludn’t be completed, invalid argument". I have sent my application for Facebook social login verification and they tell me that they cannot run it in their xCode simulator.
The .ipa app works well on the real device with testFlight.
I have built the .ipa with expo build: ios

**Comment by nroso-brightplan** [comment]
I still have the same issue when generating a build for simulator
