### ISSUE TITLE
Can't run basic compiled web app

### ISSUE THREAD

**Issue by itaisteinherz** [expo/expo-cli#843]
## Description

After bootstrapping an app using `$ expo init` (using the tabs template) and compiling the web version of the app using `$ expo build:web`, the app is successfully compiled but an error message in the JS bundle prevents the website from working correctly.

## Expected Behavior

The app should be successfully rendered.

## Observed Behavior

I get a blank screen, and the following error message in the web console:

```
[Error] TypeError: undefined is not an object (evaluating 'e[r].call')
	f (runtime~app.efa64587.js:1:518)
	(anonymous function) (2.ebc21c7d.chunk.js:1:223681)
	f (runtime~app.efa64587.js:1:523)
	(anonymous function) (2.ebc21c7d.chunk.js:1:300895)
	f (runtime~app.efa64587.js:1:523)
	(anonymous function) (app.6c953f42.chunk.js:1:5137)
	f (runtime~app.efa64587.js:1:523)
	t (runtime~app.efa64587.js:1:389)
	r (runtime~app.efa64587.js:1:252)
	Global Code (app.6c953f42.chunk.js:1)
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

```
❯ expo diagnostics

  Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.3.1 - /var/folders/18/fyntf8sj5pz3r9bv_b9n4bkc0000gn/T/fnm-shell-8956181/bin/node
      Yarn: 1.16.0 - /var/folders/18/fyntf8sj5pz3r9bv_b9n4bkc0000gn/T/fnm-shell-8956181/bin/yarn
      npm: 6.9.0 - /var/folders/18/fyntf8sj5pz3r9bv_b9n4bkc0000gn/T/fnm-shell-8956181/bin/npm
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.21.2
```

Also specify:

- Phone/emulator/simulator platform, model and version:
I'm using Safari version 12.0 (14606.1.36.1.9), running on macOS 10.14 (Mojave).

## Reproducible Demo

https://github.com/itaisteinherz/expo-web-demo

The app is running live (on Netlify) [here](https://expo-web-demo.netlify.com).

**Comment by LouisJS** [comment]
https://forums.expo.io/t/expo-web-cli-is-broken/24721

This [PR](https://github.com/expo/expo-cli/pull/823) fixed the issue. However it's a temporary fix. We're waiting for a release of expo-cli

**Comment by EvanBacon** [comment]
Until then you can disable it by:
- running `expo customize:web`
- selecting `webpack.config.js`
- change `webpack.config.js`
```diff
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

module.exports = async function(env, argv) {
  const config = await createExpoWebpackConfigAsync(
+    { ...env, removeUnusedImportExports: false },
    argv,
  );
  // Customize the config before returning it.
  return config;
};
```

**Comment by itaisteinherz** [comment]
Note that you might need to clear your browser's cache (in Safari this can be done through `Develop` => `Empty Caches`) in order to get the new and fixed version of your website (I tried to figure out why @EvanBacon's fix wasn't working for me for 20mins, when in reality it did work but my browser was still using the old files 😅).

**Comment by LouisJS** [comment]
I'm facing the same issue as @patheticGeek when using custom webpack.config.js such as

const createExpoWebpackConfigAsync = require('@expo/webpack-config');

module.exports = async function(env, argv) {
  const config = await createExpoWebpackConfigAsync(
+    { ...env, removeUnusedImportExports: false },
    argv,
  );
  // Customize the config before returning it.
  return config;
};
Result is :

Building Webpack bundle [=================== ] 95% (40.5 seconds) emitting(node:17150) UnhandledPromiseRejectionWarning: TypeError: Data must be a string or a buffer
    at Hash.update (crypto.js:99:16)
    at exports.default (/@expo/webpack-pwa-manifest-plugin@1.2.0/src/helpers/fingerprint.js:6:6)
    at processIcon (/@expo/webpack-pwa-manifest-plugin@1.2.0/src/icons.js:41:29)
    at _callee2$ (/@expo/webpack-pwa-manifest-plugin@1.2.0/src/icons.js:111:10)
Node version : v8.15.1

**Comment by EvanBacon** [comment]
Fixed https://github.com/expo/expo-cli/pull/761. Please use the latest `expo-cli@3.0.3`. `npm i -g expo-cli`
