### ISSUE TITLE
ExpoKit: Running script 'Prepare Expo' Hangs Forever

### ISSUE THREAD

**Issue by lightninglu10** [expo/expo-cli#847]
### Environment

Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.21.2

### Steps to Reproduce

Running fastlane to build the iOS app, it hangs at the step "Running script 'Prepare Expo'"

### Expected Behavior

Expo Prepare finishes quickly

### Actual Behavior

Expo Prepare hangs and doesn't get to the next step.

**Comment by lightninglu10** [comment]
@cruzach ran fastlane's default build_app.

For reference here's our fastfile:


```
lane :release do
    build_app(workspace: "...", scheme: "...")
    upload_to_app_store(force: true)
  end
```

using the most recent version of fastlane.

**Comment by EvanBacon** [comment]
ExpoKit is deprecated in SDK 37, please upgrade to the bare workflow.
