### ISSUE TITLE
Expo start --terminal (luxury issue)

### ISSUE THREAD

**Issue by Norfeldt** [expo/expo-cli#85]
Would it be possible to either avoid the browser from opening or avoid the browser from obtaining focus?

Would like to just type `expo start`, wait and press `i` (to open iOS simulator). But the browser view keeps taking the focus.

I'm clearly aware that this is a "nice-to-have" feature.

**Comment by fson** [comment]
After running `expo start`, you can press `shift+d` to disable Dev Tools automatically opening in the browser. Then whenever you want to pop up the browser window, just press `d`.

**Comment by Norfeldt** [comment]
Thank you!

**Comment by designbyadrian** [comment]
Is there a setting so you don't have to `shift-d` at all? I don't want a browser window to open.

**Comment by fson** [comment]
Yes, there is the setting, which can be toggled by pressing `shift-d`. Your preference is saved automatically and the browser window won't open anymore.
