### ISSUE TITLE
"An unknown error occurred." from expo push:android:upload --api-key <api key>

### ISSUE THREAD

**Issue by jsur** [expo/expo-cli#851]
## Description

Tried to run `expo push:android:upload --api-key <api key>`, got  **An unknown error occurred.**

## Expected Behavior

Expected the execution to complete successfully.

## Observed Behavior

Output from command:

```
Reading project configuration...
Logging in...
Setting API key on Expo's servers...
An unknown error occurred.
```

## Environment

```
  Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.16.0 - /usr/local/bin/node
      Yarn: 1.1.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
      react-navigation: ^2.18.2 => 2.18.3
    npmGlobalPackages:
      expo-cli: 2.21.2
```

## Reproducible Demo

Run `expo push:android:upload --api-key <your api key>`.

**Comment by aymericbouzy** [comment]
I'm seeing this too. I attempted to do this because I've receiving very recently the following error when attempting to send push notifications :

> InvalidCredentials: Failed to authenticate with the FCM server. Ensure the FCM server key you uploaded is correct

Push notifications were working previously. I tried running the command `expo push:android:upload --api-key <api-key>` again thinking it might solve the error, and got the `An unknown error occurred.` message.

**Comment by cruzach** [comment]
Hi,

Just wanted to say that we're aware of this issue and currently looking into it. Will keep you updated here, thanks!

**Comment by cruzach** [comment]
**UPDATE**

We have just pushed out a fix for this. Let me know if you are still running into the issue

Sorry everyone for the outage, and we really can't thank you all enough- both for your patience and **especially** for bringing it to our attention so quickly. It's really helpful to have such a proactive community

Again- we're really sorry for the inconvenience this caused everyone. You've all put a lot of trust in Expo, and we try our best to make sure that trust is well-placed, and that our services rarely, **if ever**, have hiccups like this.

(this was posted over on our forums, but I'm pasting here in case anyone found this issue and hasn't seen the [forum post](https://forums.expo.io/t/notifications-suddenly-stopped-working-invalidcredentials-failed-to-authenticate-with-the-fcm-server/25356/19))

**Comment by jsur** [comment]
Yup, seems to work again, thanks for the quick response!
