### ISSUE TITLE
build:ios and build:android hang after build is complete

### ISSUE THREAD

**Issue by mikebro** [expo/expo-cli#854]
## Description

When running `yarn expo-cli build:ios` or `yarn expo-cli build:android` it hangs indefinitely after the build is complete:

>Waiting for build to complete. You can press Ctrl+C to exit.
>Build finished.
>Successfully built standalone app: https://expo.io/artifacts/artifactId

It hangs here indefinitely until pressing Ctrl+C to exit

## Expected Behavior

The process should end shortly after the message
>Successfully built standalone app: https://expo.io/artifacts/artifactId

## Observed Behavior

The node process hangs indefinitely after receiving the message
>Successfully built standalone app: https://expo.io/artifacts/artifactId

## Environment

```
  Expo CLI 2.21.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3 - C:\Users\MBROAD~1\AppData\Local\Temp\yarn--1563473997309-0.7280547100137744\node.CMD
      Yarn: 1.17.3 - C:\Users\MBROAD~1\AppData\Local\Temp\yarn--1563473997309-0.7280547100137744\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
```

## Reproducible Demo

This is occurring with a fresh app made using expo init, blank template with an [android package](https://docs.expo.io/versions/latest/distribution/building-standalone-apps/#2-configure-appjson) specified then running `build:android`

**Comment by AdamJNavarro** [comment]
Hey @mikebro,

Can you try upgrading to the latest version (`3.0.2`) and see if the issue persists?

Cheers,
Adam

**Comment by mikebro** [comment]
Hello @AdamJNavarro,

I've upgraded to `3.0.2` and the issue persists.
```
  Expo CLI 3.0.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 10.15.3
      Yarn: 1.17.3
      npm: 6.4.1
```

I also tested on a Mac and I did not have the issue, but I noticed something that might be a hint. When it is hanging indefinitely on Windows and I press `Ctrl+C` I get some output about a `Packager` that I don't see on Mac when it doesn't hang.

> Waiting for build to complete. You can press Ctrl+C to exit.
> √ Build finished.
> Successfully built standalone app: https://expo.io/artifacts/ _artifactId_
>
> _it hangs here forever, so I press `Ctrl+C`_
>
> **Stopping packager...**
> **Packager stopped.**
> Done in 504.11s.
