### ISSUE TITLE
webpack-config has unlisted dependency on eslint / eslint-config-universe

### ISSUE THREAD

**Issue by FLGMwt** [expo/expo-cli#859]
## Description

`yarn web` fails on a new project with expo-cli@3 seemingly because recent versions of webpack-config rely on eslint and eslint-config-universe being available. When webpack-config is used by the CLI (instead of by the project directly), this would seem to require global installs of both packages.

## Expected Behavior

I expected `yarn web` to successfully build the starter app and that I wouldn't have to add any unlisted global dependencies.

## Observed Behavior

```
> yarn web
yarn run v1.17.3
$ expo start --web
Starting project at C:\git\black-screen-test
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Warning: This project contains unoptimized assets. Please run `expo optimize` in your project directory.
Starting Metro Bundler on port 19001.
Tunnel ready.
Cannot find module 'eslint'
```

I expect users would encounter this issue if they did any of the following:

1. Created a new project with `expo init` using cli@3+
2. Had an existing project **without** a `webpack.config.js` and updated to cli@3+
3. Had an existing project **with** a `webpack.config.js` and a dependency on `@expo/webpack-config` and updated `@expo/webpack-config` to a recent version with the eslint loader.

## Environment

```
expo diagnostics

  Expo CLI 3.0.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245
```

## Reproducible Demo

Assuming:
- expo-cli@3.0.2 is globally installed
- eslint is NOT globally installed
- eslint-config-universe is NOT globally installed

```
git clone git@github.com:FLGMwt/expo-cli-3-eslint-issue.git
cd expo-cli-3-eslint-issue
yarn install
yarn web
```

## Workaround

You can work around this issue by running `expo customize:web`, selecting webpack, then overriding the webpack-config version to one before the eslit config was added:

```
yarn add -D @expo/webpack-config@0.5.19
```

Alternatively, run the yarn / npm command above and create a `webpack.config.js` file in the root of your project with the following content:

```
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

module.exports = async function(env, argv) {
  const config = await createExpoWebpackConfigAsync(env, argv);
  // Customize the config before returning it.
  return config;
};
```

Which does the same as customize:web.

**Comment by hodgef** [comment]
Having same issue just after updating to expo-cli 3.0.2
![image](https://user-images.githubusercontent.com/25509135/61567762-b9a0b980-aa4e-11e9-87b4-3ac415d7a289.png)

`npm install eslint` doesn't seem to help.

Not sure if there's CI for this project, but a project of this size really needs it.

**Comment by vivirose** [comment]
the same here

**Comment by cdcv** [comment]
I'm having the same issue.  I tried the workaround proposed by FLGMwt, but it is not working, or I am not using it has intended. I run expo start --web, I end up with a

**Comment by FLGMwt** [comment]
@cdcv Sorry the workaround didn't work for you. We've just started expo so our project isn't much changed from the `expo init` starting point.

Your best bet is probably to stick to cli version 2.21.2 until this is resolved (`npm install --global expo-cli@2.21.2` / `yarn global add expo-cli@2.21.2`).

Expo web support is very new and strongly warns against breaking changes. It is under heavy development to make it better : ) https://blog.expo.io/the-roadmap-for-expo-sdk-34-b2e379ab9fff#e41a. 

There's a PR out to add web integration tests for the CI in this repo (#861) and as @.hodgef noted, a PR out to fix this issue #860 <3

**Comment by louiechristie** [comment]
@FLGMwt 

Your second workaround didn't work for me. 

> Your best bet is probably to stick to cli version 2.21.2 until this is resolved (`npm install --global expo-cli@2.21.2` / `yarn global add expo-cli@2.21.2`).

The Expo Developer Tools in the browser just shows a black screen in the browser after downgrading to expo-cli@2.21.2 for me.

Steps to replicate:

Upgrade to expo-cli@3
`npm install expo-cli --global`.
Downgraded to expo-cli@2.21.2,
`npm uninstall expo-cli --global`,
`npm install expo-cli@2.X`
`expo init test` 
`cd test`
`yarn start`

**Comment by FLGMwt** [comment]
Update: it looks like #860 was merged and a new version of the CLI is out (https://www.npmjs.com/package/expo-cli/v/3.0.4). I've confirmed that this works with my project by doing the following:

````
npm install --global expo-cli
cd my-expo-project
rm webpack.config.js
yarn remove @expo/webpack-config
yarn web
```

Thanks a ton expo team  : D

**Comment by EvanBacon** [comment]
#860. Run `npm i -g expo-cli` to get the latest

**Comment by cbanning510** [comment]
Please see:

https://github.com/expo/web-examples/issues/51
