### ISSUE TITLE
"undefined" error when Metro has an internal error

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#86]
## Description

There are situations where the error message in the packager logs of Expo CLI will only show me `undefined` as the error message when failing to build a bundle. I have a demo of one such situation in the reproducible demo section.

## Expected Behavior

I would expect it to provide the underlying Metro error message (if there is one) or suggest what I might to do investigate the problem.

### In expo-cli

> [15:52:43] undefined
> [15:52:43] Failed building JavaScript bundle.

### In simulator

<img width="485" alt="screen shot 2018-10-11 at 3 58 13 pm" src="https://user-images.githubusercontent.com/90494/46838540-92ee7d80-cd6e-11e8-809e-9879c2a14b12.png">

This is with expo-cli 2.2.0 and SDK 30.

## Reproducible Demo

https://github.com/brentvatne/lol-asset - you can comment out line 8 in App.js and it will be fine, otherwise you get the undefined error. Notice also that if you change the require on line 5 to something like `./ville-lol.png` (a file that doesn't exist) then you will get a sensible error. I have run into this in other situations before and I suspect it's a similar code path of metro errors that we're not properly hooking in to.

**Comment by vkedwardli** [comment]
Upgraded to Expo 30 from Expo 28 recently, at first everything is running fine, until I tried to upgrade some package and do a `npm install`, and seems I'm stucked with this `undefined` forever, reverting to Expo 28 and Expo XDE doesn't work. How can I get my project running again? thanks

**Comment by brentvatne** [comment]
cc @fson - this makes it really difficult to find underlying metro errors

**Comment by vkedwardli** [comment]
Found my problem, it was due to a node module do not have the `dist` folder (requires manual building after the `npm install`), the error should be something like file not found if Metro is working correctly

**Comment by brentvatne** [comment]
I agree @vkedwardli

**Comment by EvanBacon** [comment]
Stale, closing
