### ISSUE TITLE
[FeatureRequest] Add an option to change the ENV

### ISSUE THREAD

**Issue by YoshiYo** [expo/expo-cli#868]
## Description

Hi expo team 👋🏻
I would like to give you an idea for the expo-cli. I realise that expo-cli was pluged on two different BABEL_ENV, `development` and `production`. I would like to imagine some pipelines, builds etc.. on different environnements. Is it possible to provide an expo-cli option to change the BABEL_ENV (NODE_ENV) ?

## Expected Behavior

For exemple : `expo-cli build:android --environnement automation --release-channel automationv1`

**Comment by brentvatne** [comment]
what would this allow you to do in your code that can't be done from switching on release channels? 

```
if (Constants.manifest.releaseChannel == 'automation') {
  //
}
```

vs

```
if (SOME_ENV_THING === 'whatever') {
  // ..
}
```

**Comment by EvanBacon** [comment]
You can also pass in dynamic params using `app.config.js`
