### ISSUE TITLE
What to do?

### ISSUE THREAD

**Issue by Sohail-Ansari** [expo/expo-cli#876]
$ expo build:android -t apk
- Making sure project is set up correctly...
[20:26:12] An Expo user account is required to proceed.
[20:26:12] Not logged in. Use `function(str) {
  if (arguments.length === 0) return this._name;
  this._name = str;
  return this;
} login -u username -p password` to log in.
[20:26:12] Set EXPO_DEBUG=true in your env to view the stack trace.

**Comment by AdamJNavarro** [comment]
Hey @Sohail-Ansari,

As the error indicates, you need to be logged in to run a build command. You can either run a separate command of `expo login` or you can add the `login -u username -p password` flags and values as mentioned above.

You can test to see if you are logged in and to which account you're logged into by running `expo whoami`.

If you are logged in and still get this error, please open up a new issue and describe the issue with as much details as you can provide. In the future, please bring these types of questions to our [forums](https://forums.expo.io/) as we try to reserve github issues for reproducible bugs.

Cheers,
Adam
