### ISSUE TITLE
Expo build (IOS & android)  and Expo publish error

### ISSUE THREAD

**Issue by Alhydra** [expo/expo-cli#879]
## Description

I've been trying to build an app I was working for for the last month, but it doesn't want to work when I use the commands:
```
expo build:android
```
```
expo build:ios
```

```
expo publish
```

But my app runs normally on development mode, on both real android and IOS devices

Samsung galaxy s8
Iphone 9s

with no errors or anything.

## Expected Behavior

I want to build an IOS app from my project, but it doesn't work

## Observed Behavior

```
expo build:android
Checking if there is a build in progress...

Request failed with status code 500
Error: Request failed with status code 500
    at createError (C:\Users\FiercePC\AppData\Roaming\npm\node_modules\expo-cli\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\FiercePC\AppData\Roaming\npm\node_modules\expo-cli\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\FiercePC\AppData\Roaming\npm\node_modules\expo-cli\node_modules\axios\lib\adapters\http.js:237:11)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

## Environment

```
 expo diagnostics

  Expo CLI 3.0.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4907809
```

Also specify:

- Testing devices

```
Samsung galaxy s8
Iphone 9s
```

**Comment by cruzach** [comment]
What's the error when you run `expo publish`?

**Comment by Alhydra** [comment]
@cruzach same error for all of them.
But I fixed the error, It's a bit weird, but after I deleted the field "owner" from app.json, It worked
for some reason It didn't accept it, and removing it solved the problem

**Comment by cruzach** [comment]
Okay, so `owner` defaults to the username of the current user if it's not set. I'm guessing the user you were logged in as was different?

**Comment by Alhydra** [comment]
@cruzach in the app.json, I put my full name, the doc does no't set what you should fill it with, a full name, email, username... so I put my full name as a string.
I believe that if you get the same error, it's almost certain you have an error in the app.json file.
