### ISSUE TITLE
Constants.manifest.extra is always undefined in development

### ISSUE THREAD

**Issue by andrioid** [expo/expo-cli#88]
## Description

It seems that Constants.manifest.extra is always `undefined` in development when using expo-cli. This behaviour is different than from the previous tool `exp`.

## Expected Behavior

I expected `expo` to behave like `exp`

`Constants.manifest.extra` should contain the keys in app.json as documented here: https://docs.expo.io/versions/latest/guides/configuration.html#extra

## Observed Behavior

It's always undefined in development when running `expo`, but works perfectly if I run `exp` instead.

## Environment

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.6.0
  Yarn: 1.7.0
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  expo: ^28.0.1 => 28.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/parkpark-a3e94739-88f6-43e1-9358-1a34d42e57ff.tar.gz

Native iPhone XS device

## Reproducible Demo

This should be easy to reproduce. Try to print `Constants.manifest.extra` in any App.js while running the app in `expo`, then try again with `exp` to see difference.

**Comment by fson** [comment]
Unfortunately I wasn't able to reproduce this. I tried the following `app.json`:
```json
{
  "expo": {
    "name": "expo-hello-test",
    "description": "This project is really great.",
    "slug": "expo-hello-test",
    "privacy": "public",
    "sdkVersion": "30.0.0",
    "platforms": ["ios", "android"],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "extra": {
      "hello": "world"
    }
  }
}
```

and this code:
```js
export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>
          {JSON.stringify(
            {
              extra: Constants.manifest.extra,
              developer: Constants.manifest.developer
            },
            null,
            2
          )}
        </Text>
      </View>
    );
  }
}
```
Running it with `expo-cli` 2.2.0, the app displays the data from `extra`:
<img width="535" alt="screen shot 2018-10-19 at 19 29 44" src="https://user-images.githubusercontent.com/497214/47231473-a4bacb00-d3d5-11e8-9e62-c91e1c70473a.png">

Could you provide a link to an app to repro this with?

**Comment by andrioid** [comment]
How weird! I'll take a look Monday and provide a way to reproduce this, or close it myself.

**Comment by andrioid** [comment]
Let's close this for now. I'll re-open with a repo link if I run into problems again.

**Comment by andrioid** [comment]
If anyone else encounters something weird like this, try restarting the Expo-client app on your phone.

I can't reproduce this, but I encountered this again with exp (old), exp (new) and expo-cli where Constants.manifest.extra was undefined.

Restarting the client helped. Caching in the client maybe?

**Comment by Kingkobra813** [comment]
I'm currently having this issue. It was working but then it stoped. 
I have uninstalled the expo app and reinstalled and still no luck.

**Comment by wremacle** [comment]
> If anyone else encounters something weird like this, try restarting the Expo-client app on your phone.
> 
> I can't reproduce this, but I encountered this again with exp (old), exp (new) and expo-cli where Constants.manifest.extra was undefined.
> 
> Restarting the client helped. Caching in the client maybe?

Thanks. It worked for me.

**Comment by shahzore-qureshi** [comment]
I can also confirm that on iOS, closing the app via swiping it away in the multitasking screen fixes the issue for me. Thank you @andrioid !!

**Comment by adrianpraja** [comment]
I had the same problem in iOS Simulator

Solved by closing / reopening Simulator

**Comment by linus** [comment]
I have the same (or similar) problem after ejecting, running in iOS Simulator. For me, Constants.manifest is null. Restarting does not solve it. Constants has all the right keys and info, Constants.manifest exists, but equals null.

**Comment by Andruschenko** [comment]
I'm facing the exact same issue as @linus after ejecting. The intermediate solution I'm using I've taken from [this post](https://forums.expo.io/t/error-after-ejecting-to-bare-workflow-null-is-not-an-object-error-evaluating-expoconstants-default-manifest-releasechannel/28497/3):

```
import * as manifest from "../app.json"
if (!Constants.manifest){
    Constants.manifest = manifest.expo
}
``` 

Another workaround is to replace `Constants.manifest.extra.myValue` with `(Constants.manifest || manifest.expo).myValue`.

**Comment by juandav** [comment]
@fson 

Was this tested with typescript?
I get the same error

Constants.manifest.extra is undefined
