### ISSUE TITLE
Unable to enable iosDisplayInForeground in expo 34.0.3

### ISSUE THREAD

**Issue by sirpeas** [expo/expo-cli#899]
### Environment

```
Expo CLI 3.0.6 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.10.0 - /usr/local/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: 32.0.13 => 32.0.13
      @types/react: ^16.8.23 => 16.8.23
      @types/react-native: ^0.57.65 => 0.57.65
      expo: ^34.0.1 => 34.0.3
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.0 => 3.11.1
    npmGlobalPackages:
      expo-cli: 3.0.6
```

```
No matter what is app target
```

### Steps to Reproduce

1. Add `expo.notification.iosDisplayInForeground: true` to `app.json`
2. Run `expo r -c`
3. Then you will see an error in the console:
```
Error: Problem validating fields in app.json. See https://docs.expo.io/versions/v34.0.0/workflow/configuration/
 • Field: notification - should NOT have additional property 'iosDisplayInForeground'.
```

### Expected Behavior

Same as in steps to reproduce but without step 3.

### Actual Behavior

Same as in steps.

### Other:

As far as I see code responsible for this feature is missing after installation even though it's 34.0.3 in a `lock` file.
Check `node_modules/expo/build/Notifications/Notifications.js`

yarn.lock
```
expo@^34.0.1:
  version "34.0.3"
  resolved "https://registry.yarnpkg.com/expo/-/expo-34.0.3.tgz#5e2ac4ff2ddbcb2a095106d82e920e6a02a3dbaa"
```

package-lock.json
```
"expo": {
      "version": "34.0.3",
      "resolved": "https://registry.npmjs.org/expo/-/expo-34.0.3.tgz",
```

**Comment by sirpeas** [comment]
@cruzach true that `expo-cli` is a proper place, sorry 😃

With this setup
```
Expo CLI 3.0.6 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.10.0 - /usr/local/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: 32.0.13 => 32.0.13
      @types/react: ^16.8.23 => 16.8.23
      @types/react-native: ^0.57.65 => 0.57.65
      expo: ^33.0.0 => 33.0.7
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.0 => 3.11.1
    npmGlobalPackages:
      expo-cli: 3.0.6
```
I've got exacly the same error
```
Error: Problem validating fields in app.json. See https://docs.expo.io/versions/v34.0.0/workflow/configuration/
 • Field: notification - should NOT have additional property 'iosDisplayInForeground'.
```
even though I switched back to SDK 33

**Comment by rrust** [comment]
Just to add: using the "_displayInForeground": true option in the individual push notification message in order to override iosDisplayInForeground in the "notiification" section of app.json as stated in the [Expo documentation](https://docs.expo.io/versions/latest/workflow/configuration/#notification) has no effect. Push notifications on iOS are still invisible when the app is in foreground.

**Comment by cruzach** [comment]
Sorry, this feature isn't available in any current SDKs (most likely to be included in the next one). Sorry for the confusion, it was meant to remain in the `unversioned` documentation. I've made the fixes both to docs, to the changelog, and to the Push Notification tool -- thanks for pointing this out!

**Comment by rrust** [comment]
Thanks! Looking forward to see this feature in an upcoming release!

**Comment by rrust** [comment]
The docs for SDK34 shows the options for iosDisplayInForeground and _displayInForeground as well. Obviously SDK34 doesn't feature these yet, too...

**Comment by cruzach** [comment]
Yeah, the docs still need to be *deployed*, but i have made the fixes. See this PR- https://github.com/expo/expo/pull/5131
