### ISSUE TITLE
Error when running web after upgrade to expo 34

### ISSUE THREAD

**Issue by chrisdrackett** [expo/expo-cli#901]
## Description

I just updated our project that supports web from expo 33 -> expo 34. I also upgraded expo-cli from `2.19.4` to `3.0.6`.

When running `expo start --web-only` and visiting the page in the browser I get the following error (regression):

```
index.js:3 Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Module.<anonymous> (index.js:3)
    at Module.../node_modules/strip-ansi/node_modules/ansi-regex/index.js (index.js:14)
    at __webpack_require__ (bootstrap:724)
    at fn (bootstrap:101)
    at Object.../node_modules/strip-ansi/index.js (index.js:2)
    at __webpack_require__ (bootstrap:724)
    at fn (bootstrap:101)
    at Object.../node_modules/react-dev-utils/webpackHotDevClient.js (webpackHotDevClient.js:20)
    at __webpack_require__ (bootstrap:724)
    at fn (bootstrap:101)
```

## Expected Behavior

I expect the site/app to run without errors.

## Environment

  Expo CLI 3.0.6 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.6.0 - /var/folders/ls/x4zssmm56vxgm5hc_81l99sm0000gn/T/yarn--1564605622529-0.04212595766652649/node
      Yarn: 1.16.0 - /var/folders/ls/x4zssmm56vxgm5hc_81l99sm0000gn/T/yarn--1564605622529-0.04212595766652649/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.3 => 34.0.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8

Also specify:

- Phone/emulator/simulator platform, model and version: `Safari`, `Chrome`

## Reproducible Demo

an app created with `expo init` is not giving me issues so I'm going to attempt to make a simple test case, I'll add it when I have it.

**Comment by chrisdrackett** [comment]
I'm not sure what I did, but this seems to have fixed itself? Closing for now.

**Comment by Elijen** [comment]
I have the same issue and it did not fix itself yet :)

**Comment by radud** [comment]
> 
> 
> I have the same issue and it did not fix itself yet :)
> 
> edit: Seems that updating expo-cli from 3.0.7 to 3.0.8 and using `-c` param fixed the problem.

Saved my day. **_npm install -g expo-cli_** fixed the issue
