### ISSUE TITLE
Can not install apk to my device

### ISSUE THREAD

**Issue by marknguyen85** [expo/expo-cli#903]
i have been using expo-cli to build and export to an apk file but cannot install it to my device.

`There was a problem parsing the package.`

here the config files:

expo-cli -v 
v3.0.6
node -v 
v12.6.0
android device
v7
app.json 
```

{
  "react-native": "0.59.8",
  "expo": {
    "name": "BVBDReport",
    "icon":"./assets/logo.png",    
    "version": "0.1.0",
    "slug": "BVBD",
    "sdkVersion": "34.0.0",
    "platforms": [
      "ios",
      "android"
    ],

```
package.json 
```

{
  "name": "report",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "jest-expo": "^34.0.0",
    "react-test-renderer": "16.3.1",
    "redux-logger": "^3.0.6",
    "remote-redux-devtools": "^0.5.13",
    "remotedev-rn-debugger": "^0.8.3"
  },
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "eject": "expo eject",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "axios": "^0.18.1",
    "expo": "^34.0.0",
    "moment": "^2.22.2",
    "native-base": "^2.13.4",
    "npm": "^6.3.0",
    "react": "16.3.1",
    "react-native": "0.59.8",
    "react-native-awesome-alerts": "^1.0.8",
    "react-native-datepicker": "^1.7.2",
    "react-native-flags": "^1.0.0",
    "react-native-modal-datetime-picker": "^6.0.0",
    "react-native-orientation-loading-overlay": "^0.1.4",
    "react-native-picker-select": "^4.2.0",
    "react-native-snap-carousel": "^3.7.2",
    "react-native-table-component": "^1.2.0",
    "react-native-vector-icons": "^5.0.0",
    "react-navigation": "^2.11.2",
    "react-navigation-redux-helpers": "^2.0.5",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-promise": "^0.6.0",
    "redux-saga": "^0.16.0"
  }
}
```

and when ran to export apk i used keystone from expo-cli handle it.

**Comment by dacevedo12** [comment]
Hi, could you please the command that you are running to build your app? 

Also, make sure to specify --type apk because it defaults to aab and you can't install such file directly to your phone. aab is only for distributing to playstore

**Comment by EvanBacon** [comment]
Stale, closing. Please feel free to reopen with more info.

**Comment by swipe13** [comment]
Good I found myself with the same error ... I used to form my build the expo: android only and dps selected apk and then he did everything for me in the end the build gave me success but to install the apk on the phone gave me the same error my app.json is complete i don't understand why this error

my app.json

`{
  "expo": {
    "name": "testeexpo",
    "slug": "testeexpo",
    "version": "1.0.0",
    "sdkVersion": "36.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "bundleIdentifier": "com.swipeee.testeexpo",
      "supportsTablet": true
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      },
      "package": "com.swipeee.testeexpo"
    },
    "web": {
      "favicon": "./assets/icon.png"
    }
  }
}
`
