### ISSUE TITLE
Recent Mapview fix for standalone android apps doesnt work with .aab package format executables

### ISSUE THREAD

**Issue by edoantonioco** [expo/expo-cli#906]
### Environment

Linux, expo sdk 33.0.7, targeting android. This in standalone.

### Steps to Reproduce

Since around july 30th, MapView stopped working properly in standalone apps, so you have to apply the fix given in the MapView page:

1. Apply this https://docs.expo.io/versions/latest/sdk/map-view/#deploying-to-a-standalone-app-on-android to your android project so it will work properly in standalone apps
2. Generate an .apk and install it in a real device (With 'expo build:android') 
3. Realize map fix does works fine here.
3. Then, generate an .aab (with 'expo build:android -t app-bundle') and upload it to the play store.
4. Wait for the update with the new code.
5. Realize maps doesnt show up in this new version.

### Expected Behavior

Maps should work when generating a standalone android app with  'expo build:android -t app-bundle'
![Screenshot_1564625106](https://user-images.githubusercontent.com/5560824/62260315-cae2b200-b3ce-11e9-8287-804f03a75e2a.png)

### Actual Behavior

Maps doesnt work when generating a standalone android app with  'expo build:android -t app-bundle'

![photo5049024628621682779](https://user-images.githubusercontent.com/5560824/62260321-d2a25680-b3ce-11e9-9c1d-04be28d20e27.jpg)

**Comment by cruzach** [comment]
Hey @edoantonioco - sorry you're running into this issue. Is there any error from the device logs? Maybe indicating a lack of a Google Maps API key?

**Comment by edoantonioco** [comment]
I think the error is not caused because of this, because I just uploaded an apk instead of aab and the error is still there.

So the error only happens when the standalone release is uploaded to the play store, since installing the .apk directly works fine. 

- So if I upload the app to the play store and download it to the device = maps wont work
- If I get the .apk and install it directly in the phone = maps works

I generated the key as recomended by the MapView documentation.

**Comment by edoantonioco** [comment]
@cruzach the issue is that the documentation https://docs.expo.io/versions/latest/sdk/map-view/#deploying-to-a-standalone-app-on-android mentions that you have to get the Google Certificate Fingerprint by running a command in the pc, but the truth is, that certificate you have to obtain it from the developer play store page of your application.

So that documentation should be updated with the correct information.

**Comment by Abdo-zayed** [comment]
i have the same issue 
mapView not working when building apk or .aab and causing crush after update new version of expo

**Comment by cruzach** [comment]
@Abdo-zayed can you try the solution the Edoantonioco shared? I haven't seen any other reports of this so I'm hesitant to change the documentation

**Comment by Abdo-zayed** [comment]
yes , it's working 
thank you ,but please make it clear or any update or change
