### ISSUE TITLE
Wording on the 'There is a new version of expo-cli available' box

### ISSUE THREAD

**Issue by adokce** [expo/expo-cli#914]
## Description

This is not a big issue but since it raised few questions in my head, I'm posting it here. 
Wording on the "There is a new version of expo-cli available" green box in terminal may be too generic. (specifically the line: `npm install -g expo-cli`)
![image](https://user-images.githubusercontent.com/20118440/62410610-3fdd0400-b5e8-11e9-9a49-5248bc8fb5e6.png)

## Expected Behavior

I use yarn to install all my dependencies, both inside the repo and global and I'm happy with not touching npm. I expect expo-cli to work well with yarn.

## Observed Behavior

The green box when the new expo-cli version is available says `npm install -g expo-cli`. I wasn't thinking much and just copy pasted the command while forgetting my expo-cli is actually installed with yarn.
Am I expected to translate the npm command to yarn, or is Expo recommending npm for global expo-cli installs. _This is only confusing to me because the expo init command suggests yarn for installing dependencies._ Otherwise, I will just update my global package with yarn next time.

**Comment by fson** [comment]
Fixed in #920.
