### ISSUE TITLE
Can you make Expo download just the edited js file to expo app?

### ISSUE THREAD

**Issue by RsPlayer** [expo/expo-cli#915]
I have just started using expo cli and it was amazing, but whenever I edit a simple text in a .js file it redownload the whole javascript bundle which it takes too much time per edit, can you make it partial download that updates only the modified parts?

**Comment by ankhzet** [comment]
You have "Live reload" feature enabled in expo client. For quick updates, enable "Hot reload" instead.
https://docs.expo.io/versions/latest/workflow/up-and-running/

**Comment by AdamJNavarro** [comment]
Hey @RsPlayer,

Going to close this as @ankhzet answered your question. Also, in the future, please direct these types of questions to our [forums](https://forums.expo.io/)! We try to keep Github issues reserved for reproducible bug reports.

Cheers,
Adam
