### ISSUE TITLE
[android] expo init blank -> eject uses old sdk in android/app/build.gradle

### ISSUE THREAD

**Issue by aniltirola** [expo/expo-cli#916]
Please make our job easier by filling this template out to completion.

## Description

template blank -> eject produces build.gradle with old sdk

## Expected Behavior

eject should produce build.gradle with the following line
`api 'com.facebook.react:react-native:34.0.0'`

## Observed Behavior

eject produces build.gradle with the following line
`api 'com.facebook.react:react-native:33.0.0'`

## Environment
expo-cli Version: 3.0.8
latest MacOs

## Reproducible Demo
```
expo init -t blank --name testsdk34 testsdk34
cd testsdk34/
expo eject

# now choose the expokit option

# after finish check the file android/app/build.gradle
```

**Comment by peterkuiper** [comment]
Still an issue with `expo-cli` version 3.0.10. Everything seems to work though.

**Comment by EvanBacon** [comment]
New templates use whatever version of react-native you have installed https://github.com/expo/expo/blob/d39095cd1b037bd54107a932b05d7261b219df58/templates/expo-template-bare-minimum/android/build.gradle#L27
