### ISSUE TITLE
expo eject ---> getaddrinfo ENOTFOUND exp.host exp.host:443

### ISSUE THREAD

**Issue by yangdachu** [expo/expo-cli#918]
When I use an `expo eject `command

![image](https://user-images.githubusercontent.com/23580181/62427229-6901af80-b722-11e9-9187-52089e343e07.png)

**Comment by ide** [comment]
`getaddrinfo ENOTFOUND` is a DNS error. You may have a network configuration issue on your end. One way to check that both DNS and the HTTP server are working is to visit https://downforeveryoneorjustme.com/exp.host.
