### ISSUE TITLE
[web] unable to use production build with expo build:web

### ISSUE THREAD

**Issue by kriswep** [expo/expo-cli#919]
## Description

Unable to trigger production webpack build with `expo build:web`. Output uses React dev build, also doesn't set expo `__DEV__` va to false.

## Expected Behavior

Created a new blank managed expo project via `expo init`, rendering the `__DEV__` variable into a Text component.
Created a build via `expo build:web`

## Observed Behavior
I would have expected `expo build:web` to use the react production version and to set `__DEV__` to false. But the output still uses the dev version, resulting in huge bundles. Also no service workers or other prod assets.

Also tried setting NODE_ENV=production with no success.
It did work on earlier versions for me, also I'm not sure which version worked.

## Environment

Tried on expo@3.0.8 as well as expo@3.0.3

Please run `expo diagnostics` in the project folder and copy the output here:
```
Expo CLI 3.0.8 environment info:
    System:
      OS: Linux 4.18 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.17.3 - /usr/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    npmPackages:
      expo: ^34.0.1 => 34.0.3 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.0.8
```

Also specify:

- Phone/emulator/simulator platform, model and version: none, using expo for web build

## Reproducible Demo

As described above, the issue is reproducible (for me) in a fresh expo blank project.

**Comment by bdombro** [comment]
This is happening for me also, literally ballooned my build from 150kb to 1mb. Am using expo-cli@3.0.6 until this is resolved.

**Comment by chrisdrackett** [comment]
yep, looks like doing web build at the moment is doing a dev build now and not a production build. `process.env.NODE_ENV` is coming back as `production` for me, react is in dev mode, etc.

**Comment by chrisdrackett** [comment]
I just tried the following without any luck:

`"build": "NODE_ENV=production expo build:web",`

**Comment by chrisdrackett** [comment]
for now I'm using the following `webpack.config.js`:

```javascript
const createExpoWebpackConfigAsync = require('@expo/webpack-config')

// Expo CLI will await this method so you can optionally return a promise.
module.exports = async function(env, argv) {
  const tempEnv = {
    ...env,
    mode: 'production',
    development: false,
    production: true,
  }


  const config = await createExpoWebpackConfigAsync(tempEnv, argv)

  config.module.rules.push({
    test: /\.mjs$/,
    include: /node_modules/,
    type: 'javascript/auto',
  })

  return config
}
```

**Comment by chrisdrackett** [comment]
ok, finial update for now:

I ended up rolling back the following based on my previous `yarn.lock`:

```
  "resolutions": {
    "react": "16.8.3",
    "expo-cli": "^3.0.6",
    "@expo/config": "2.1.2",
    "@expo/dev-tools": "0.5.42",
    "@expo/json-file": "8.1.9",
    "@expo/xdl": "56.1.3",
    "@expo/webpack-config": "0.7.0"
  },
```

and it fixed the issue without needing the above (this way dev mode still works).

I assume something changed in one of the above requirements, but I can't seem to figure out what!

**Comment by bdombro** [comment]
@chrisdrackett thanks for sharing! I foolishly tried something similar in webpack.config.js, but made a critical mistake which your snippet corrected. I could not get the version rollback working, but am very happy with the webpack.config.js overrides. I recommend you switch back to overrides so that you can upgrade your dependencies.

I tweaked your snippet to only force production env if an env variable is set.

```
const expoConfig = require('@expo/webpack-config');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;


module.exports = async function(env, argv) {

  /**
   * There is a bug in expo-cli that prevents prodenv from being set.
   * Ref: https://github.com/expo/expo-cli/issues/919
   *
   * The following will force webpack to bundle in production mode
   */
  if (process.env.BUILD_ENV === 'production') {
    env.mode = 'production';
    env.development = false;
    env.production = true;
  }

  const config = await expoConfig(env, argv);

  config.plugins.push(process.env.ANALYZE ? new BundleAnalyzerPlugin() : () => null);

  config.plugins.push(
    new CopyWebpackPlugin([
      { from: __dirname + '/web/favicon.ico' },
      { from: __dirname + '/web/preview.png' }
    ])
  );

  return config;
};
```

You can force production env now by running `BUILD_ENV=production npx expo build:web`.

**Comment by chrisdrackett** [comment]
@bdombro nice! I wish someone from expo would see this, but at least this makes the process less painful!

**Comment by bdombro** [comment]
@chrisdrackett Yeah, agree. I am resisting the urge to fix the issue, because there is a good chance that Expo will fix it soon anyways.

**Comment by bdombro** [comment]
@jackiewung could you elaborate? I tried running `expo build:web --no-dev` and got `error: unknown option --no-dev`

**Comment by EvanBacon** [comment]
@bdombro I have removed the `--no-dev` flag in favor of just never using dev mode in production builds. #1020
