### ISSUE TITLE
Ejected Android Build Not Using Release Channel Information

### ISSUE THREAD

**Issue by larkintuckerllc** [expo/expo-cli#92]
# READ THIS FIRST, PLEASE!

We're looking to keep questions on our forums and bug reports on the GitHub repo -- please choose whichever you feel is more appropriate for your issue:

- Post in our community forums (log in with your Expo developer account): https://forums.expo.io/c/help
- File a bug on the Expo CLI repo (for bugs related to the Expo CLI tools): https://github.com/expo/expo-cli/issues/new
- File a bug on the main Expo repo (for other bugs): https://github.com/expo/expo/issues/new
- Request a feature on Canny: https://expo.canny.io/feature-requests

Thanks for reporting the issue you found with Expo CLI!

# Required format for issues

Please make our job easier by filling this template out to completion.

## Description

1-2 sentences describing the problem you're having or the feature you'd like to request

Running command in an ejected Android application, `expo publish --release-channel sample`, in not updating `AppConstants.java` (used to indicate which release-channel to use). Result is that the Android build will use the `default` channel.

What action did you perform, and what did you expect to happen?

Action above appears to need to update `AppConstants.java` with release channel information (confirmed works if you hand edit this file).

```
public static String INITIAL_URL = "exp://exp.host/@larkintuckerllc/react-native-scaffold?release-channel=sample";
…
 public static final String RELEASE_CHANNEL = "sample";
```
## Observed Behavior

What actually happened when you performed the above actions?

The `AppConstants.java` file not being updated with the release channel information; all builds then use `default`.

If there's an error message, please paste the _full terminal output and error message_ in this code block:

N/A`

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

```
Environment:
  OS: Linux 4.10
  Node: 8.12.0
  Yarn: 1.10.1
  npm: 6.4.1
  Watchman: 4.7.0
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/larkintuckerllc-b2897e8a-7f87-4afb-9199-d24213172868.tar.gz

```

Also specify:

- Phone/emulator/simulator platform, model and version:

Not really relevant, but Samsung Galaxy 6

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

https://github.com/larkintuckerllc/react-native-scaffold/tree/develop-native

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by esamelson** [comment]
Hi @larkintuckerllc - thanks for the report. We actually just recently merged a fix for this issue here: https://github.com/expo/expo-cli/commit/c1bfeba88c2271b4ce3d29d285d9e205c2a943db 😄  It will go out with the next release of expo-cli. Apologies for the inconvenient workflow up until this point!

**Comment by quinlanj** [comment]
looks like the fix has been landed and released  :)
