### ISSUE TITLE
expo build:web issue with resource paths for static files

### ISSUE THREAD

**Issue by srmaharjan** [expo/expo-cli#936]
## Description

Unable deploy production build for subdomain (https://example.com/app). All resource path including manifest.json in index.html starts with root path.

## Expected Behavior

Resource's path should have starts with subdomain instead of root path.

## Observed Behavior

I have included following configuration in `package.json`
`"homepage": "/app"`

So, when we execute `expo build:web`, it should generate production ready index.html file that includes path to manifest.json as  below
`<link rel="manifest" href="/app/manifest.json"/>`
However it generate index.html which contain 
`<link rel="manifest" href="/manifest.json"/>`

Because of this issue,
When we browse application using` https://example.com/app` url, application could not find manifest.json as it request for `https://example.com/app/manifest.json` and could not find that resource.

## Environment

>  Expo CLI 3.0.4 environment info:
>     System:
>       OS: macOS 10.14.3
>       Shell: 3.2.57 - /bin/bash
>     Binaries:
>       Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
>       Yarn: yarn install v0.27.5
> [1/4] Resolving packages...
> success Already up-to-date.
> Done in 0.64s. - /usr/local/bin/yarn
>       npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
>     IDEs:
>       Xcode: /undefined - /usr/bin/xcodebuild
>     npmPackages:
>       expo: ^34.0.1 => 34.0.4 
>       react: 16.8.3 => 16.8.3 
>       react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
>       react-navigation: ^3.11.0 => 3.11.1 
>     npmGlobalPackages:
>       expo-cli: 3.0.4

## Reproducible Demo

As described above, the issue is reproducible in a fresh expo tabs project. 

and add following lines in package.json
`"homepage": "/app",`
and build using `expo build:web` command

**Comment by AlexGrafe** [comment]
There is a configuration in app.json: `web.publicPath` but it doesn't work anymore for me.
This issue on expo/web-examples: https://github.com/expo/web-examples/issues/40

**Comment by AlexGrafe** [comment]
@oxyii This is your issue as well.

**Comment by carlos-cubas** [comment]
I'm facing this issue as well has anyone else found a solution

**Comment by EvanBacon** [comment]
Fixed:
- #1336
- #938
