### ISSUE TITLE
expo build:web build only development bundle not production bundle

### ISSUE THREAD

**Issue by srmaharjan** [expo/expo-cli#937]
## Description
`expo build:web` build only development bundle not production bundle even though we do not use --dev option.

## Expected Behavior
`expo build:web` should build a production bundle for your project, compressed and ready for deployment as per documentation and help menu.

## Observed Behavior
`expo build:web` build only development bundle NOT production bundle even though we do not use --dev option.

## Environment

>   Expo CLI 3.0.9 environment info:
>     System:
>       OS: macOS 10.14.3
>       Shell: 3.2.57 - /bin/bash
>     Binaries:
>       Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
>       Yarn: yarn install v0.27.5
> [1/4] Resolving packages...
> success Already up-to-date.
> Done in 0.87s. - /usr/local/bin/yarn
>       npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
>     IDEs:
>       Xcode: /undefined - /usr/bin/xcodebuild
>     npmPackages:
>       expo: ^34.0.1 => 34.0.4 
>       react: 16.8.3 => 16.8.3 
>       react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
>       react-navigation: ^3.11.0 => 3.11.1 
>     npmGlobalPackages:
>       expo-cli: 3.0.9
> 

## Reproducible Demo
As described above, the issue is reproducible in a fresh expo tabs project.
And then build using `expo build:web` command

**Comment by EvanBacon** [comment]
Fixed. Related: https://github.com/expo/expo-cli/pull/929 https://github.com/expo/expo-cli/pull/688
