### ISSUE TITLE
[ios]The speed of downloading JavaScript bundle is too slow

### ISSUE THREAD

**Issue by wulichenyang** [expo/expo-cli#941]
I tried to connect my project (on win 10) using iPhone through expo client, but can only work on tunnel way. Besides, every time I save my program, the expo client will download all JavaScript bundles again, which costs too much time.

- I opened 19000 and 19001 ports in my PC 
- My phone and PC are in one LAN

This is my package.json:

``` json
  "dependencies": {
    "@expo/samples": "~3.0.3",
    "@expo/vector-icons": "^10.0.3",
    "@react-navigation/web": "^1.0.0-alpha.9",
    "expo": "^34.0.1",
    "expo-asset": "^6.0.0",
    "expo-constants": "6.0.0",
    "expo-font": "~6.0.0",
    "expo-web-browser": "6.0.0",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "0.59.8",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-web": "^0.11.4",
    "react-navigation": "^3.11.0"
  },
  "devDependencies": {
    "babel-preset-expo": "^6.0.0",
    "jest-expo": "^34.0.0"
  },
```
How can I solve these two problems? Looking for your help, thanks!

**Comment by wulichenyang** [comment]
No, I turn off the production mode.
I shook my phone, it shows 'Hot Reloading Unavailable (!)'. Is there a config key to open hot reloading in app.json?

_expo diagnostics:_

  Expo CLI 3.0.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 8.12.0 - D:\node\node.EXE
      Yarn: 1.12.3 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - D:\node\npm.CMD

**Comment by cruzach** [comment]
> I shook my phone, it shows 'Hot Reloading Unavailable (!)'

there should be a key below that says 'Disable Live Reloading', which will mean you have live reloading enabled

**Comment by chenop** [comment]
I got mac - For me what  solved is to enable "Internet Sharing".
go to Setting --> Sharing --> Share your connection from: "USB 10/100/1000 LAN"
--> Check "Wi-fi"
--> check "Internet Sharing"
--> Now fill details of new network
--> Connect iPhone to the new network you've created.

Click play in Xcode and try again

**Comment by EvanBacon** [comment]
Fixes:
- Fast Refresh works with Expo SDK 36
- We've split up the main Expo package making JS bundles smaller by default.

**Comment by pie6k** [comment]
> I got mac - For me what solved is to enable "Internet Sharing". go to Setting --> Sharing --> Share your connection from: "USB 10/100/1000 LAN" --> Check "Wi-fi" --> check "Internet Sharing" --> Now fill details of new network --> Connect iPhone to the new network you've created.
> 
> Click play in Xcode and try again

Wow! This worked like a charm!

It was a bit unclear for me, so I'll describe my flow:

1. Connect iPhone to laptop via cable
2. Set up internet sharing in system preferences like this on Mac
<img width="659" alt="CleanShot 2021-12-30 at 23 05 50@2x" src="https://user-images.githubusercontent.com/7311462/147790938-1a541d11-fd36-4708-ad91-bdf97f44905a.png">
3. While setting it up you can click "Wifi Options" button and set wifi network name and password
4. Connect to this WiFi with iPhone
5. Wifi icon should become like this
<img width="80" alt="CleanShot 2021-12-30 at 23 07 15@2x" src="https://user-images.githubusercontent.com/7311462/147791024-ba6df28c-fbcc-4202-b381-e6a2fe132af6.png">
6. Then you have to re-build the app in XCode (I suppose some build phase will use proper local ip etc)

After this, dev bundle loads in like 0.5s while before it was taking ~20-30s
