### ISSUE TITLE
expo build:web release channel

### ISSUE THREAD

**Issue by richardpeng** [expo/expo-cli#948]
## Description

I would like to be able to change the endpoint URLs based on release channel when building for web: `expo build:web --release-channel staging`. However, `release-channel` is not a valid option for `build:web`. I'd like to be able to use `Constants.manifest.releaseChannel` to control which endpoint URL is used in my build.

## Expected Behavior

I expect to be able to use the behavior documented here when running `expo build:web`:
https://docs.expo.io/versions/latest/distribution/release-channels/

## Observed Behavior

```
$ expo build:web --release-channel staging
error: unknown option `--release-channel'
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:
```
  Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.13.0 - ~/.asdf/installs/nodejs/10.13.0/bin/node
      Yarn: 1.16.0 - ~/.asdf/installs/nodejs/10.13.0/.npm/bin/yarn
      npm: 6.4.1 - ~/.asdf/installs/nodejs/10.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.3 => 34.0.3 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 3.0.10
```

Also specify:

- Phone/emulator/simulator platform, model and version:
Not applicable.

## Reproducible Demo

Not applicable.

**Comment by chrisdrackett** [comment]
@EvanBacon is this on the roadmap? using `react-native-dotenv` is a huge pain with vars that change often.

**Comment by kopax** [comment]
Hi, I am new to expo and I am hitting this too. Before I was testing with `react-native-dotenv` and I confirm it is a hudge pain to get android/ios/web all together getting env configuration.

I want to provide using an env switch a specific env  configuration to the whole expo running or builded app. 

How is this possible?

**Comment by EvanBacon** [comment]
I recommend using `app.config.js` + `extra` to dynamically configure your project. Release channels are not on the roadmap as Expo's hosting service currently does not support web. Definitely want to investigate this further in the future tho

**Comment by richardpeng** [comment]
@EvanBacon what do you mean by `app.config.js` + `extra`? I'm not sure what `extra` means.

**Comment by EvanBacon** [comment]
https://docs.expo.io/versions/latest/config/app/#extra

```js
// app.config.js
export default {
  expo: {
    extra: { somn: process.env.MY_ENV_VARIABLE }
  }
}
```
```js
// App.js
import Constants from 'expo-constants';
const value = Constants.manifest.extra.somn;
```

**Comment by sreuter** [comment]
Is this still supposed to work with Expo SDK 42? We switched to EAS for our native builds, but still rely on this for our web builds. Unfortunately though it doesn't seem to work anymore.

**Comment by gyoon-dev** [comment]
Is there a way to create a dev build for web?

The closest command I can find is:
`expo build:web -d`

but this is still building with production env.

(https://docs.expo.dev/workflow/expo-cli/)

**Comment by gyoon-dev** [comment]
> Is there a way to create a dev build for web?

Read over the comments above and implemented a development build by using a "custom" process.env.STAGING_BUILD.

```
// app.config.js
export default {
  expo: {
    apiUrl: process.env.STAGING_BUILD === 'development' ? 'DEV_API_URL' : 'API_URL'
  }
}
```

```
// build script
BUILD_STAGING=development expo build:web
```

---

Still confused about what the  -d, --dev flag does when building with the `expo build:web -d` as shown from 

`expo build:web --help`
-d, --dev        Turns dev flag on before bundling

Is there a link between the -d, --dev flag and the `__DEV__` or is `__DEV__` only relevant when running in one of iOS/aOS simulators?

**Comment by EvanBacon** [comment]
Release channels are related to the hosting service used with your static bundle, Expo currently doesn't offer web hosting like we do for native JS bundles. Think of `expo build:web` like a bundle command (`webpack bundle`, `next export`, `npx react-native bundle`, etc.), whereas `expo publish` is more like bundle + upload to hosting provider. We currently don't offer anything like "upload to hosting provider" for web. In the future we can add support for release channels to something like EAS Updates if/when we add web support there.
