### ISSUE TITLE
BUILD FAILED: Could not resolve com.google.android.gms:play-services-ads-identifier

### ISSUE THREAD

**Issue by arvenjadeaguilar** [expo/expo-cli#953]
Build Failed in expo build:android
Having an error of could not resolve all files for configuration ':app:releaseCompileClasspath'.
[stderr] > Could not resolve com.google.android.gms:play-services-ads-identifier:[15.0.1,16.0.0).
[stderr]   Required by:
[stderr]       project :app > com.google.android.gms:play-services-ads:15.0.1
1-2 sentences describing the problem you're having or the feature you'd like to request

## Expected Behavior
Build Success

## Observed Behavior

Build Failed Having an error of 
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Could not resolve all files for configuration ':app:releaseCompileClasspath'.
[stderr] > Could not resolve com.google.android.gms:play-services-ads-identifier:[15.0.1,16.0.0).
[stderr]   Required by:
[stderr]       project :app > com.google.android.gms:play-services-ads:15.0.1

## Environment
  Expo CLI 3.0.9 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
      Yarn: yarn install v0.24.6
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.09s. - /usr/local/bin/yarn
      npm: 6.5.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 3.0.9

**Comment by tbkh91** [comment]
I ran into a similar issue. I couldn't see any issues on my end and decided to give it another go. Worked the second time around.

**Comment by tkud04** [comment]
I ran into this issue today with expo build:android. This issue started after I added google-services.json to project root (downloaded from firebase)

**Comment by sirpeas** [comment]
I'm facing the same issue, but I haven't added anything to the `app.json`

**Comment by gypsicoder** [comment]
I am also having the same issue

**Comment by wodin** [comment]
I think the syntax is ok. See the following:

https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html

**Comment by ciruz** [comment]
I just got the same error and my project is basically a fresh, almost an empty expo project.

**Comment by sirpeas** [comment]
I tried to build again and I haven't got this message. So solved in my case

**Comment by EKoetsjarjan** [comment]
same here, deleted build folder , and then it worked again
