### ISSUE TITLE
expo export  --merge-src-url option results in an error

### ISSUE THREAD

**Issue by fson** [expo/expo-cli#965]
## Description

Passing the `--merge-src-url` option to `expo export` results in an error.

## Expected Behavior

Expected to `--merge-src-url` to merge manifests without errors.

## Observed Behavior

Running `expo export --public-url <url> --merge-src-url <url>` results in the following error:
```
(0 , _axios(...).default)(...).pipe is not a function
```

I noticed this when converting code to TypeScript, since the return value of `axios(url)` is not a stream (therefore doesn't have the `.pipe` method), but a promise, so this piece of code had a type error:
https://github.com/expo/expo-cli/blob/ec088839e0001e7b085a31bdfdfcf1d6921ec20a/packages/expo-cli/src/commands/export.js#L119-L120

## Environment

```

  Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /var/folders/vm/7_1sz9n56yj8d6v_dl1xpdf80000gn/T/fnm-shell-7022071/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /var/folders/vm/7_1sz9n56yj8d6v_dl1xpdf80000gn/T/fnm-shell-7022071/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.0.10
```

## Reproducible Demo

Run ` expo export --merge-src-url https://example.com --public-url https://example.com` in an Expo app.

**Comment by EvanBacon** [comment]
`--merge-src-url` is dropped in the latest `npx expo export` command.
