### ISSUE TITLE
Password exposed when logged in via cmd

### ISSUE THREAD

**Issue by roeniss** [expo/expo-cli#978]
## Description

With specific login flow, my password is absolutely exposed. 

## Expected Behavior

Like `expo login`, Password should be hidden like this:

![image](https://user-images.githubusercontent.com/26613280/64060367-723d4980-cc06-11e9-9f37-a58bb0ce500c.png)

## Observed Behavior

Following login flow makes my password exposed.

- make new project with `expo init` (template doesn't matter)

- get in project folder in cmd (`cd my_new_project`)

- `expo start` then press `s` to login in

with this flow, my password is absolutely exposed. 

Please check the picture below:

![image](https://user-images.githubusercontent.com/26613280/64060351-28ecfa00-cc06-11e9-97bc-3aae896cbb03.png)

First Login attempt: password is exposed.

Second Login attempt: after typing any one character, clicking makes `? Password: [input is hidden]` deleted.

## Environment

```
C:\Users\user>expo diagnostics

  Expo CLI 3.0.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.12.1 - C:\Users\user\AppData\Roaming\npm\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
```

## Reproducible Demo

Check "Observed Behavior" please.

**Comment by EvanBacon** [comment]
This has been resolved in our migration to `prompts`
