### ISSUE TITLE
JSON input parsing error while installing expo-cli 3.0.3

### ISSUE THREAD

**Issue by myavaydotcom** [expo/expo-cli#979]
C:\Deezer>npm install --global expo-cli
npm ERR! Unexpected end of JSON input while parsing near '...dateformat":"3.0.3","'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2019-09-01T21_24_34_642Z-debug.log

**Comment by jkhales** [comment]
Hey, sorry to hear that.
Tried to reproduce this with 3.0.3 and 3.3.0 and both installs worked. 
If you continue to have difficulty, please reopen a new issue that also includes your node and windows version.
