### ISSUE TITLE
The installation don't progress / freeze

### ISSUE THREAD

**Issue by Suniron** [expo/expo-cli#982]
Hello,

When i try to install expo-cli with the command:
`  npm install -g --unsafe-perm expo-cli `

```
npm WARN deprecated joi@14.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN tarball tarball data for @expo/traveling-fastlane-linux@1.9.11 (sha512-xCHnqKfwWYygQfRbi9MGNSG28EHKDtzMB+QDklSH1GeD90TA0beAjlNF+Z+KPxj28s3WZlQr9yw1AqBS7aipcw==) seems to be corrupted. Trying one more time.
[            ......] / extract:@expo/traveling-fastlane-darwin: sill extract @expo/traveling-fastlane-darwin@1.9.11 extracted to C:\Users\SVXW3966\AppData\Roaming\npm\node_modules\.staging\@expo\traveling-fastlane-darwin-9317e36d (807[
         ......] / extract:@expo/traveling-fastlane-darwin: sill extract @expo/traveling-fastlane-darwin@1.9.11 extracted to C[            ......] / extract:@expo/traveling-fastlane-darwin: sill extract @expo/traveling-fastlane-darwin@1.9
```

I’ve got this and the installation is going nowhere...

Thanks if you have an idee :'(

**Comment by mtg09** [comment]
try:
npm clear cache --force

**Comment by KingTigre** [comment]
I have the same problem... 
npm cache clear --force does not solve the problem for me'
Also tried to update npm version and did not work

**Comment by bisubus** [comment]
It's been stuck on @expo/traveling-fastlane-linux , then after aborting installation process the same happened on @expo/traveling-fastlane-darwin. Both packages are optional since I'm installing on Windows.

`cache clean` and `cache verify` didn't help. I'm not sure why it's recommended as a panacea. Cache shouldn't become corrupt for everyone who use Expo. 

I ended up removing these packages from package.json in global node_modules/expo-cli and re-installing it manually by running `npm i --production-only` there.

Windows 7 x64, npm 6.11.3, Node 12.1.0

**Comment by Suniron** [comment]
I thinks it's a problem with node-sass

**Comment by atherkhalil** [comment]
> It's been stuck on @expo/traveling-fastlane-linux , then after aborting installation process the same happened on @expo/traveling-fastlane-darwin. Both packages are optional since I'm installing on Windows.
> 
> There was no _seems to be corrupted_ error, `cache clean` and `cache verify` didn't help.
> 
> I ended up removing these packages from package.json in global node_modules/expo-cli and re-installing it manually by running `npm i --production-only` there.
> 
> Windows 7 x64, npm 6.11.3, Node 12.1.0

It worked! I removed those optional dependencies from package.json and ran `npm i expo-cli --production-only` in my project folder and it worked. I spent hours trying to get it to work. Thanks a Million!

**Comment by aeroborn79** [comment]
I ran into the same issue. I performed
npm uninstall expo-cli --global
then
npm install expo-cli --global
and it worked.

**Comment by Bradblooms** [comment]
> It's been stuck on @expo/traveling-fastlane-linux , then after aborting installation process the same happened on @expo/traveling-fastlane-darwin. Both packages are optional since I'm installing on Windows.
> 
> There was no _seems to be corrupted_ error, `cache clean` and `cache verify` didn't help.
> 
> I ended up removing these packages from package.json in global node_modules/expo-cli and re-installing it manually by running `npm i --production-only` there.
> 
> Windows 7 x64, npm 6.11.3, Node 12.1.0

Im having the same problem, did you remove those files from package .json file before instalation and if yes how did you do that? how can i find my global expo package.json before installation?

cheers

**Comment by bisubus** [comment]
@Bradblooms It was in global node_modules after first unsuccessful Expo installation. I edited node_modules/expo-cli/package.json and had to create global bin files manually after `npm i`.
The problem disappeared for me with newer release, uninstalled global expo-cli and it was installed successfully.

**Comment by ccheever** [comment]
@Suniron If you are still having this problem, can you say what versions of operating systen, node, and npm you're using?

**Comment by Suniron** [comment]
Hello,

Expo-cli is now installed but i can't update it.. 
I give more information later..

**Comment by wanderer-1994** [comment]
My God! Got no idea how I got through this time-consuming problem!
What I did was: 
npm i -g npm@latest
npm cache verify
Then open cmd with administrator run:
npm install expo-cli --global

Hop it could help!

**Comment by udeshx** [comment]
Solution
Installed latest version of stable node 12.13.1 at the time
then installed again with admin

**Comment by softwareengineer111** [comment]
> Solution
> Installed latest version of stable node 12.13.1 at the time
> then installed again with admin

Thanks. I have same problem. How did you install expo-cli. Can your share your NodeJs , Npm Version.?

**Comment by udeshx** [comment]
> Thanks. I have same problem. How did you install expo-cli. Can your share your NodeJs , Npm Version.?
Nodejs = v12.13.1
Npm = 6.12.1

I'm on windows and use NVM to switch between node versions
https://github.com/coreybutler/nvm-windows

I had a problem after that , using the blacklist.js replacement technique below fixed it
https://github.com/expo/expo-cli/issues/1074

**Comment by softwareengineer111** [comment]
> oblem after that ,

Thanks for your help. Which version of expo did you use? Thanks

**Comment by udeshx** [comment]
> Thanks for your help. Which version of expo did you use? Thanks

expo-cli --version
3.9.1

if you are on windows this may help you
https://elision.design/en/blog/msbuild-error-and-missing-microsoft-cpp-default-props

**Comment by maroof-ahmed** [comment]
This worked for me...

https://stackoverflow.com/questions/58234545/npm-warn-tarball-tarball-data-for-expo-traveling-fastlane-darwin1-10-0-seems-t/59323762#59323762

**Comment by George-98** [comment]
I found that C:\Program Files\Git then git-cmd finally worked for me. git-bash kept giving me an error saying that it was deprecated due to too many vulnerabilities.

**Comment by devdattakhoche** [comment]
This is one hell of a problem with npm!!
I was also facing the same issue
until I read some solutions and tried this:
`npm i -g npm@latest
npm cache verify
npm install expo-cli --global --no-optional --unsafe-perm
`
