### ISSUE TITLE
android build failed on expo

### ISSUE THREAD

**Issue by bilalyaqoob** [expo/expo-cli#992]
I made one project using expo and then i run 
expo ba (for making android build)
expo build failed due to some error

https://expo.io/builds/dcdda3a1-5fa1-4f96-89a7-7782b92ca4c1

![bug](https://user-images.githubusercontent.com/31065558/64405954-f9bd0980-d099-11e9-81a5-4ab5c19c71ec.PNG)

**Comment by cruzach** [comment]
Can you run `expo diagnostics` and paste the output here?

Do you get the same result when trying to build a blank `expo init` project?

**Comment by bilalyaqoob** [comment]
expo diagnostics result 
![diagnostics](https://user-images.githubusercontent.com/31065558/64475225-581ce180-d199-11e9-8fed-7e923f36d13f.PNG)

**Comment by bilalyaqoob** [comment]
I am getting this error during the build

![erroror](https://user-images.githubusercontent.com/31065558/64477512-e606c580-d1b5-11e9-8ccd-288490d023f7.PNG)

**Comment by cruzach** [comment]
That looks like you're running `expo start`, not `expo build:android`

Can you try this on a blank `expo init` project?

**Comment by bilalyaqoob** [comment]
i show u the error i did expo start in 1 terminal and expo build:android in 2nd terminal and then i get the above err in 1st terminal and 2nd terminal build failed

**Comment by bilalyaqoob** [comment]
I did with the blank project build was successful

**Comment by cruzach** [comment]
Make sure you read the blog post for the SDK you're using- [here is SDK 34's](https://blog.expo.io/expo-sdk-34-is-now-available-4f7825239319), and it mentions `react-navigation`:
> - upgrade `react-navigation` to "^3.11.1" (if you use it — this is also optional, you don’t have to update it to use the newest SDK. If you choose to, make sure you read the changelog for breaking changes.)
> If you use react-navigation you should also run expo install react-native-gesture-handler react-native-reanimated as these are no longer bundled in the expo JavaScript package.

**Comment by bilalyaqoob** [comment]
this is my package .json
"dependencies": {
    "expo": "^34.0.4",
    "native-base": "^2.13.7",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-gesture-handler": "^1.3.0",
    "react-navigation": "^4.0.0",
    "react-navigation-stack": "^1.5.3"

**Comment by cruzach** [comment]
You're using `"react-navigation": "^4.0.0"`, try downgrading to `react-navigation to "^3.11.1"`

**Comment by bilalyaqoob** [comment]
thank you friend for your valuable time and help.I finally get successful build
