### ISSUE TITLE
Bundler gets stuck at 100% when syntax errors are present in debug mode

### ISSUE THREAD

**Issue by shamilovtim** [expo/expo-cli#993]
When an Expo app is placed in debug mode, syntax errors crash iOS and makes the bundler get stuck at 100%, which requires the iOS emulator to be force closed and restarted. One graceful way of handling this would be, use `tsc --noEmit --watch`. Rather than serving the broken code to the emulator, if the React Native / Expo project is using Typescript, use Typescript to check the code first and print errors to console and do not compile the bundle and send to the iOS emulator. The user will be required to fix syntax errors and once they're 
fixed the bundle will finally be allowed to compile and sent to the emulator / device. I'm sure there are other solutions but in my opinion integrating `tsc --noEmit --watch` would significantly improve Expo's ecosystem and give developers an extra shield against runtime errors.

Expo version:
```
 Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: yarn install v0.21.3
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.32s. - /usr/local/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.20 => 16.8.20
      @types/react-native: ^0.57.63 => 0.57.63
      @types/react-navigation: ^3.0.7 => 3.0.7
      expo: ^34.0.4 => 34.0.4
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.1.tar.gz => 0.59.8
      react-navigation: ^3.11.1 => 3.12.1
    npmGlobalPackages:
      expo-cli: 3.0.10
```

Steps To Reproduce
Place an Expo app in debug mode
Use iOS Emulator to serve the app
If there is a syntax error, the emulator will crash.

Describe what you expected to happen:
I would expect that the app is syntax checked prior to compiling, and errors are thrown in console, compilation is stopped, and my emulator will not crash at 100% bundle and require a force-close.

**Comment by brentvatne** [comment]
the simulator no longer crashes in this case, however metro bundler still suffers from a known issue where if you have a syntax error on the first build after opening it then it will need to be restarted in order to compile successfully.
